openucx/ucx

src/tools/perf/libperf.c, src/ucp/core/ucp_rkey.c, src/ucp/tag/rndv.c, src/ucp/wireup/select.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.h, test/gtest/uct/uct_test.h
- Removes same process, same gpu check
- UCP protocol changes to enable cuda-IPC
- added "rma_bw" lane for each mem_type.  
- inter-node case:
IB TL handle both HOST and CUDA rma
- intra-node case
KNEM rma lane for HOST mem type,  CUDA-IPC rma lane for CUDA mem type
- Handle the case where IPC accessibility depends on the GPU locality.
- cuda IPC is peer accessible if GPU are connected NVLINK, PCIe, PCI switch
- cuda IPC is not peer accessible connection between GPU have  SMP interconnect between NUMA nodes (e.g., QPI/UP
- checking peer accessibility each time when a process  unpack RKEY to support dynamic GPU selection during application run,
=> UCP/CUDA-IPC: enable protocols using cuda-ipc for inter-node GPU transfers

contrib/test_jenkins.sh, src/ucm/event/event.c, test/mpi/test_memhooks.c
Fix a bug in malloc hooks that were not installed for shmat() and mmap() when user requested VM_UNMAPPED event
Without this fix, the could be data corruption issue in applications using shmat(REMAP) or mmap(FIXED)
replaces #2730
=> Fix installing malloc hook symbols for shmat(REMAP) and mmap(FIXED)

contrib/test_jenkins.sh, src/ucm/event/event.c, test/gtest/ucm/cuda_hooks.cc, test/mpi/test_memhooks.c
Fix a bug in malloc hooks that were not installed for shmat() and mmap() when user requested VM_UNMAPPED event
Without this fix, the could be data corruption issue in applications using shmat(REMAP) or mmap(FIXED)
Picked from master #2731
=> Fix malloc hook symbols for shmat(REMAP) and mmap(FIXED) - v1.3.x

test/gtest/ucp/test_ucp_wireup.cc, test/gtest/uct/test_pending.cc
Fix some failures in unit tests on new ARM test machine
Make the test more portable: fix failure when testing release build, and when running with "ulimit -n" of 1024 (max number of open files). 
Fixes  #2736 
Fixes #2737
=> Unit test portability fixes 

src/uct/ib/dc/base/dc_ep.c, test/gtest/uct/ib/test_dc.cc
Fix for a problem found with application.
The application crashed due to the following assertion:
dc_ep.c:136  Assertion `ep->dci == UCT_DC_EP_NO_DCI' failed
The problem happened during the following flow:
1) TX resources are exhausted
2) Some operation is added to the pending queue (waiting for DCI allocation)
3) Another operation has been invoked for the same ep (which forced ep to take DCI, but it was not descheduled from DCI allocation pending queue)
4) The assertion happened
=> UCT/DC: Fix DCI pending allocation scheme

src/uct/ib/dc/base/dc_ep.c, test/gtest/uct/ib/test_dc.cc
Fix for a problem found with application.
The application crashed due to the following assertion:
dc_ep.c:136 Assertion `ep->dci == UCT_DC_EP_NO_DCI' failed
The problem happened during the following flow:
1. TX resources are exhausted
2. Some operation is added to the pending queue (waiting for DCI allocation)
3. Another operation has been invoked for the same ep (which forced ep to take DCI, but it was not descheduled from DCI allocation pending queue)
4. The assertion happened
Picked from master #2740
=> UCT/DC: Fix DCI pending allocation scheme - v1.4.x

src/uct/ib/dc/base/dc_ep.c, test/gtest/uct/ib/test_dc.cc
Fix for a problem found with application.
The application crashed due to the following assertion:
dc_ep.c:136 Assertion `ep->dci == UCT_DC_EP_NO_DCI' failed
The problem happened during the following flow:
1. TX resources are exhausted
2. Some operation is added to the pending queue (waiting for DCI allocation)
3. Another operation has been invoked for the same ep (which forced ep to take DCI, but it was not descheduled from DCI allocation pending queue)
4. The assertion happened
Picked from master #2740
=> UCT/DC: Fix DCI pending allocation scheme - v1.3.x

src/ucs/stats/stats_fwd.h
- suppressed OMPI BTL/UCT build warning:
function declaration isn't a prototype
=> UCS/STATS: suppressed build warning

src/ucs/datastruct/pgtable.c, src/uct/Makefile.am, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
Removed simple khash based mapping list as this will not work.
Added pgtable based caching.
cuda IPC mapping are created at destination side for source gpu memory handles.  These mappings at the destination are not valid when cudaFree() is called on original source side.  The next cudaMalloc() on source might get same virtual address but it generates unique memory handle.  At destination, when virtual address is same, simple comparison of the memhandles is not sufficient to close the previous handle and remap the new handle. It has to close mapping of  all the overlapping regions.
=> UCT/CUDA_IPC:  caching for remote cuda ipc memhandle mappings 

src/ucs/stats/stats_fwd.h
- suppressed OMPI BTL/UCT build warning:
function declaration isn't a prototype
(cherry picked from commit d62284ecbffa108ae1ccdf287d88d0af8096778e)
=> UCS/STATS: suppressed build warning - v1.4

src/ucm/event/event.c, test/gtest/ucm/cuda_hooks.cc
porintg https://github.com/openucx/ucx/pull/2756
=> UCM/CUDA: do not generate VM_UNMAP for cudaFree with NULL - v1.4.x

src/ucs/sys/rcache.c
fixes #2749
This should have be done in #2719, because there are specific cases when mem registration can fail.
(described in #2702 and #2719)
=> UCS: Change rcache reg warn to debug

src/ucs/datastruct/pgtable.c
porting https://github.com/openucx/ucx/pull/2768 to v1.4.x
=> UCS/PGTABLE: return error instead of assert on inserting overlapped region - 1.4.x

src/ucs/arch/x86_64/cpu.c, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, test/gtest/ucp/ucp_test.cc, test/gtest/ucs/test_stats_filter.cc
- this caused failure on SRIOV (virtual) systems
fixes https://github.com/openucx/ucx/issues/2773
=> GTEST: ignore warnings on stats filter test

src/ucp/core/ucp_context.c
The PR fixes typos in UCP env var descriptions and in comments
=> UCP: fix a bunch of typos

src/ucp/core/ucp_context.c
This PR fixes UCX_TLS description.
1. `rc`  alias does not include ud anymore (only for bootstrap). The same is relevant for `rc_x`.
2. Pure `ud` and `dc` were not mentioned at all.
The relevant discussion is here: #2721
=> UCP: Clarify UCX_TLS possible values

src/ucm/util/log.c
fixes:
```
#6  <signal handler called>
#7  0x00007fba272d6921 in __strlen_sse2_pminub () from /usr/lib64/libc.so.6
#8  0x00007fb9591394f1 in ucm_log_vsnprintf (buf=0x7ffc1232e837 "in dlopen(\351\062\022\374\177", max=185, fmt=0x7fb959145a80 "in dlopen(%s), re-applying '%s' to %p", ap=0x7ffc1232e7d8) at util/log.c:159
#9  0x00007fb959139aa6 in __ucm_log (file=0x7fb95914592d "util/reloc.c", line=278, function=0x7fb959145bb6 <__FUNCTION__.5888> "ucm_dlopen", level=UCS_LOG_LEVEL_DEBUG,
message=0x7fb959145a80 "in dlopen(%s), re-applying '%s' to %p") at util/log.c:263
#10 0x00007fb95913a7ba in ucm_dlopen (filename=0x0, flag=2) at util/reloc.c:277
#11 0x00007fba00cda1f1 in py_dl_open () from /usr/lib64/python2.7/lib-dynload/_ctypes.so
#12 0x00007fba27f3dbb0 in PyEval_EvalFrameEx () from …
```
=> UCM: fix crash in debug log for NULL filename

src/uct/ib/ud/base/ud_ep.c
The change fixes out of order sending in UD transport
The bug occurs when user's callbach sends from different EP than
UCT matches which has pending messages.
Block the iface for sending from AM callback
=> UCT/UD: fix out of order sending

ucx.spec.in
Explicitly set gcc-c++ as a requirement in rpm spec file.
It is required by Fedora 29 and newer:
https://fedoraproject.org/wiki/Changes/Remove_GCC_from_BuildRoot
Koji build with fixed spec file: https://koji.fedoraproject.org/koji/taskinfo?taskID=29118481
=> rpm: explicitly set gcc-c++ as requirement - v1.3

ucx.spec.in
Explicitly set gcc-c++ as a requirement in rpm spec file.
It is required by Fedora 29 and newer:
https://fedoraproject.org/wiki/Changes/Remove_GCC_from_BuildRoot
Koji build with fixed spec file: https://koji.fedoraproject.org/koji/taskinfo?taskID=29118481
=> rpm: explicitly set gcc-c++ as requirement - v1.4

ucx.spec.in
Explicitly set gcc-c++ as a requirement in rpm spec file.
It is required by Fedora 29 and newer:
https://fedoraproject.org/wiki/Changes/Remove_GCC_from_BuildRoot
Koji build with fixed spec file: https://koji.fedoraproject.org/koji/taskinfo?taskID=29118481
=> rpm: explicitly set gcc-c++ as requirement

src/ucp/core/ucp_worker.c
Fix data alignment 
detected poor performance for GPU transfers on power arch because of fragmented RDAMA WRITE in memtype pipelining put protocol
=> UCP/WORKER: Fix rndv pipeline fragment pool alignment

config/m4/rocm.m4, src/uct/Makefile.am
Improve the configure tests for ROCm; follow autotools best practices.  User-only flags CPPFLAGS, LDFLAGS, and LIBS are no longer overridden by the test results.  Tests for header files no longer use hard-coded paths, using the value of CPPFLAGS instead.  Add a test for the HSA runtime library instead of blindly hard-coding and assuming its LDFLAGS path.
There is no bug report associated with this PR.  Internal testing showed that when not using prepared debian packages for ROCm, or for non-default source builds, the hard-coded paths might fail.
It would be nice if after this PR is accepted it could be cherry-picked to the 1.3.x and 1.4.x release branches.  Thank you.
=> UCT/ROCM: improve configure tests and Makefile

config/m4/rocm.m4
Internal regression testing revealed a missing default header path.
No existing PR.  Related to #2826 fixing paths for the current/upcoming release, prior versions used different header paths. #2826 caused a regression.  This fixes the ROCm configure for both old and new ROCm versions.
Apologies for this not being caught during #2826 preparation.  Backports to 1.3.x and 1.4.x will follow this being merged to master.
=> UCT/ROCM: additional default header path

src/ucm/util/reloc.c
patch->prev_value must have always valid pointers, like libc
@hoopoepg @Artemy-Mellanox pls review
=> UCM/RELOC: fix modifying GOT mechanism

src/ucs/sys/sys.c
Fixes the regression failures on jenkins-ppc
=> UCS/SYS: Fallback to malloc() if hugepages are not supported

test/examples/Makefile.am
This PR adds an ld flag`-lucm` to test/examples/Makefile.am
After building all of the main components, make in `test/examples` fails with the following error.
```
$ cd test/examples/
$ make installcheck-local
INSTALLCHECK: Compiling examples with installed library
gcc -o uct_hello_world   $HOME/ucx/install/share/ucx/examples/uct_hello_world.c   -luct -lucs -I$HOME/ucx/install/include -L$HOME/ucx/install/lib -Wall -Werror -Wl,-rpath,$HOME/ucx/install/lib -pedantic
$HOME/ucx/install/lib/libucs.so: undefined reference to `ucm_global_opts'
collect2: error: ld returned 1 exit status
Makefile:612: recipe for target 'installcheck-local' failed
make: *** [installcheck-local] Error 1
```
This is because the function `ucm_global_opts` is included in UCM but libucm is not linked.
=> Build fails in test/examples

src/ucp/core/ucp_types.h, test/gtest/common/test_obj_size.cc
- increased number of lanes used in single message up to 4
backport from https://github.com/openucx/ucx/pull/2851
=>  MRAIL: increased max number of lanes in message - v1.4

src/ucs/sys/init.c
backport from https://github.com/openucx/ucx/pull/2856
(cherry picked from commit 97afcfefcccf3aa46fc44aa2f64ff2e517d37308)
=> DEBUG: added cmd line to debug output - v1.4.x

test/examples/Makefile.am
This PR is a backport of #2849 to `v1.4.x` branch.
=> Add -lucm to Makefile.am - v1.4.x

src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/verbs/rc_verbs_common.h, test/gtest/common/test_obj_size.cc
- fixes #2859, need confirmation
- to be picked to v1.4.x
=> UCT/IB: Wrap calls to ibv_wc_status_str() from header files

test/gtest/ucp/test_ucp_sockaddr.cc
Should fix rdmacm related failures reported in #2872
=> GTEST/UCP/SOCKADDR: fix log handlers leak

src/ucp/api/ucp.h
~~- ucp_ep_flush_nb, ucp_worker_flush_nb flush all TX outstanding operation~~
- trailing whitespaces cleanup
~~Make docs consistent with implementation~~
=>  UCP/DOC: trailing whitespaces cleanup

test/examples/ucp_hello_world.c
* Removed unused functions: run_server(), run_client()
* Made naming of the various handlers more consistent
* Updated reference in a printf from ucp_ep_flush (now deprecated) to ucp_ep_flush_nb
The goal of these changes is to make the sample code we provide clear and consistent both within itself and with the API Specification.
.
=> TEST/EXAMPLES: ucp_hello_world.c code cleanup.

test/gtest/uct/ib/test_ib_xfer.cc
Fixes #2433 
This reverts commits:
69eb3ac5d93f4cb04f1a231a179367a74270ad47
919c15db66b791a692037f2b09d125a0c4743b04
f9b36294975fedfd297243f0cdd75fb595b13851
=> TEST/IB: Enable ODP tests on aarch64 and ppc64

src/uct/ib/rdmacm/rdmacm_ep.c, src/uct/ib/rdmacm/rdmacm_ep.h, src/uct/ib/rdmacm/rdmacm_iface.c
Fix of race condition on rdmacm endpoint between rdmacm async thread and main thread calling uct_ep_flush()
14:22:22 [ RUN      ] sockaddr/test_uct_sockaddr.connect_client_to_server_with_delay/0
14:22:22 [     INFO ] Testing 1.1.1.5:56401 Interface: eth2
14:22:32 /scrap/jenkins/workspace/hpc-ucx-pr-4/label/hpc-test-node/worker/1/contrib/../test/gtest/uct/ib/test_sockaddr.cc:181: Failure
14:22:32 Value of: comp.status()
14:22:32   Actual: 1
14:22:32 Expected: UCS_OK
14:22:32 Which is: 0
14:22:32 
see full gtests log at [internal mellanox link](http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7797/label=hpc-test-node,worker=1/consoleFull)
add a mutex to guard ops queue and EP status
=> UCT/RDMACM/EP: fix a race condition on ops queue

test/gtest/ucs/test_stats_filter.cc
- fixed issue in stats test on systems with extra long host name
failure log: http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7818/label=r-vmb-rhel7-u4-x86-64-ucx-builder,worker=0/console
```
15:09:22 [----------] 1 test from stats_filter_report, where TypeParam = 
15:09:22 [ RUN      ] stats_filter_report.report
15:09:22 /scrap/jenkins/workspace/hpc-ucx-pr/label/r-vmb-rhel7-u4-x86-64-ucx-builder/worker/0/contrib/../test/gtest/ucs/test_stats_filter.cc:215: Failure
15:09:22 Value of: output
15:09:22   Actual: "r-vmb-rhel7-u4-x86-64-ucx-builder:1689:\n  category:\n    data-0:\n      counter0: 10\n      counter1: 20\n      counter2: 30\n      counter3: 40\n    data-1:\n      counter0: 10\n      counter1: 20\n      counter2: 30\n      counter3: 40\n    data-2:\n      counter0: 10\n …
```
=> TEST: fixed stats test

config/m4/compiler.m4
Compile time optimization flags for ThunderX2
Never versions of compilers supposed to pick up LSE extensions out of the
box but for older compilers it is useful to pass some of the options
explicitly.
=> CONFIG: Adding ThunderX2 compile time tunings

test/gtest/common/test_obj_size.cc, test/gtest/ucp/test_ucp_wireup.cc
Fix test failures with default configure options
- Skip object size test when assertions are enabled
- Don't check address hostname when debug data is disabled
@tonycurtis
=> TEST/GTEST: Fix test failures with default configure parameters

test/gtest/ucs/test_stats_filter.cc
- fixed issue in stats test on systems with extra long host name
backport from https://github.com/openucx/ucx/pull/2905
(cherry picked from commit e79849ae31e8d871e34bf82c91d9ece68fbd61d0)
=> TEST: fixed stats test - v1.4.x

test/gtest/ucp/test_ucp_perf.cc
Increase upper bound for atomic add rate in ucp_perf_envelope test.
The test may fail during high/low load on the server, like [here](http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7829/label=hpc-test-node3,worker=0/consoleFull#212814535244550c5d-247a-4f9d-bad5-5b93d2b6e2ac)
```
15:38:33 [     INFO ]            atomic add rate : 0.427 Mpps
15:38:40 [     INFO ]            atomic add rate : 0.440 Mpps (attempt 1)
15:38:46 [     INFO ]            atomic add rate : 0.338 Mpps (attempt 2)
15:38:51 [     INFO ]            atomic add rate : 0.414 Mpps (attempt 3)
15:38:57 [     INFO ]            atomic add rate : 0.392 Mpps (attempt 4)
15:39:04 [     INFO ]            atomic add rate : 0.418 Mpps (attempt 5)
15:39:10 [     INFO ]            atomic add rate : 0.420 Mpps (attempt 6)
15:39:16 [ …
```
=> GTEST: Increase range for perf atomic add rate

src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/tag_match.c, src/ucp/tag/tag_match.h, test/gtest/ucp/test_ucp_tag_offload.cc
Hash all tags of messages arriving to offload-capable interface if more than one interface is activated on the worker.
This is needed to avoid posting receive buffers, which are expected to arrive from offload incapable iface (like shm), to the HW.
Add tag to offload hash table if:
- more than 1 interface activated on the worker
- message length is bigger than TM_THRESH (to avoid ~10ns penalty for small messages, which are not supposed to be offloaded)
=> UCP/TAG: Hash tags coming to offload-capable iface

test/gtest/uct/test_p2p_am.cc
=> TEST/UCT: Skip p2p_am tests if transport has AM_DUP flag

test/gtest/uct/uct_p2p_test.cc
Test mem_type only if MD support it (or)  HOST mem type MD can register a mem_type memory
cudaError_t cudaMemcpy(void * dst,const void * src,size_t count,enum cudaMemcpyKind kind );
cuda_copy is intended for RMA between host and cuda buffers.  cuda_copy can register HOST buffer but not intended to copy between the 2 host buffers.  This is throwing error on older GPUs(k80).
=> GTEST: restrict cuda_copy uct to test RMA only with cuda target buffer

src/tools/perf/libperf.c, src/tools/perf/perftest.c, src/tools/perf/ucp_tests.cc, src/ucp/core/ucp_context.c, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.inl, src/ucp/dt/dt.c, src/ucp/dt/dt.inl, src/uct/api/uct.h, test/gtest/uct/test_md.cc
- Introducing managed memory MD
- Enabling UCP tag to handle managed memory transfers using memcpy to/from bounce buffers
- UCP perftest extension to use managed memory
- Adds basic cuda managed memory support
- by forcing dt_pack/unpack to treat managed memory similar to host
- we still don't want zcopy operations to/from managed memory (exception to this is p9 but that's a separate PR)
@bureddy Can you review and provide feedback? 
Edit: I've not handled non-contig transfers. Will follow up with another PR for that.
=> UCP/UCT/UCM: Managed memory support

test/gtest/ucp/test_ucp_perf.cc
- extended range to make tests happy
=> GTEST: extended allowed tag sync mr range

test/gtest/ucm/malloc_hook.cc
- added barrier to test exit to prevent race on event fire
=> GTEST/MALLOC_HOOKS: added barrier to test exit

src/ucs/profile/profile.c
Fix _accum_ profiling mode
Different comp units may define different locations for the same type of record/event
When location id is not set try to find the existing one by iterating thru all locations and comparing file, name and func (can be already initialized by another comp unit)
=> UCS/PROFILE: Fix 'accum' profiling mode

config/m4/ib.m4
=> UCT/IB/MLX5: Accel requires CQ ignore overrun

src/ucp/tag/offload.c
Add profiling of tag postings and cancels
This type of info can be important for application profilings
=> UCP/TAG/PROFILE: Profile tag post and tag cancel

NEWS
=> NEWS: Update for rc1

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h
- removed duplicating indirect atomics/UMR configuration
=> IB/AMO: removed duplicating indirect AMO conf

src/ucp/proto/proto_am.inl, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucp/ucp_datatype.h
- Fix zcopy_multi protocol for iov datatype, do not send the empty tail. 
- New gtest for this.
- Fixed ucp::data_type_desc_t usage in stream tests
https://github.com/openucx/ucx/commit/8e5225022a0b3d432486a5e1973ce3d2353b5495 fixes #2822
=>  UCP/AM: fix zcopy_multi protocol for iov datatype

src/ucs/debug/log.c, src/ucs/debug/log.h, test/gtest/common/test.cc, test/gtest/common/test.h, test/gtest/ucp/test_ucp_atomic.cc, test/gtest/ucp/test_ucp_context.cc, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucs/test_async.cc, test/gtest/ucs/test_log.cc, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/test_p2p_err.cc, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/uct_test.cc
Replace static API for log handlers set/clean up with `scoped_log_handler` class
Some tests potentially set up handlers and don't clean up them in case of exception, e.g. `ucs::test_skip_exception`. Tests fail when they run in some magic sequence due to lack of log handlers slots and the following test can't handle expected error:
```
12:59:52 [----------] 1 test from rc/test_ucp_sockaddr_with_rma_atomic
12:59:52 [ RUN      ] rc/test_ucp_sockaddr_with_rma_atomic.wireup/3
12:59:52 [     INFO ] Testing 65.65.65.12:35126
12:59:52 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/r-vmb-ppc-jenkins/worker/0/contrib/../test/gtest/common/test.cc:260: Failure
12:59:52 Failed
12:59:52 Got 1 errors during the test
12:59:52 
```
Using RAII idiom
=> GTEST: refactor log handlers using RAII idiom

src/ucs/debug/log.c, src/ucs/debug/log.h, test/gtest/common/test.cc, test/gtest/ucp/test_ucp_atomic.cc, test/gtest/ucp/test_ucp_sockaddr.cc
- address CR comments to #2958
- fix test_ucp_sockaddr_with_rma_atomic.wireup
=> GTEST: log handlers, part 2

src/tools/perf/libperf.c, src/tools/perf/uct_tests.cc, src/ucp/core/ucp_worker.c, src/ucp/rma/amo_sw.c, src/ucp/rma/rma_sw.c, src/ucp/stream/stream_recv.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/rndv.c, src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/rdmacm/rdmacm_ep.c, src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/ib/ud/base/ud_ep.c, test/examples/uct_hello_world.c, test/gtest/uct/ib/test_cq_moderation.cc, test/gtest/uct/ib/test_dc.cc, test/gtest/uct/ib/test_ib.cc, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/test_event.cc, test/gtest/uct/test_many2one_am.cc, test/gtest/uct/test_mm.cc, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/test_tag.cc, test/gtest/uct/uct_test.cc
Remove redundant UCT_CB_FLAG_SYNC
Flags UCT_CB_FLAG_SYNC and UCT_CB_FLAG_ASYNC are mutually exclusive
=> UCT/API: remove redundant UCT_CB_FLAG_SYNC

test/gtest/ucp/test_ucp_stream.cc
=> GTEST: fix test_ucp_stream_many2one.drop_data

src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h
When polling CQ, at first check that obtained CQE opcode is not MLX5_CQE_INVALID. 
opcode CQE values are initialized to MLX5_CQE_INVALID. RX progress of accelerated verbs transports goes to slow path if no data arrives, because it does not check opcode validity. 
Verified with shmem_overlap test that  `uct_rc_mlx5_iface_check_rx_completion` is not invoked on the target when it does not receive anything.
=> UCT/ACCEL: Avoid slow path when no CQE ready

contrib/test_jenkins.sh, src/ucs/datastruct/queue.h, test/gtest/ucs/test_datatype.cc
=> UCS/QUEUE: Fix ucs_queue_for_each() with armclang

contrib/test_jenkins.sh, src/ucp/core/ucp_worker.c, src/ucs/config/parser.c, src/ucs/sys/init.c, test/gtest/common/main.cc
=> UCP/UCS: Warn about unused environment variables at ucp_worker_create()

contrib/test_jenkins.sh, src/ucs/datastruct/queue.h, test/gtest/ucs/test_datatype.cc
#2968 backport
Fixing compile time failure
=> #2968 backport

src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h
Add more debug info to find the root cause of #2226. 
The problem is extremely hard to reproduce, new assert would help to distinguish whether it is some race on CREQ sender or just OOO/DUP packet.
=> UCT/UD: Add more debug info for OOO/DUP CREQ case

src/ucp/core/ucp_context.h
Optimize mem type detection for the case when CUDA is not configured/used. 
This saves up to 4ns in ucp_tag_recv_nbr() and up to 9ns in ucp_tag_send_nbr (for non-inlined sends) with osu_latency -i 1000000 -m 0:256
=> UCP: Optimize mem type detection for non-CUDA case

src/tools/perf/perftest.c
This PR matches the code to the description of perftest's `-M` option in the help message.
Without this, we run into a segfault when we use perftest's `-M` option.
This PR allows perftest's `-M` option to take an optarg.
=> Enable M option

contrib/test_jenkins.sh, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_rkey.c, src/ucp/tag/offload.c, src/ucp/tag/rndv.c
Fix rma lane selection for CUDA mem type when there is lane with is not required RKEY(ex CMA)
When KNEM is not present, CMA will be selected for RMA for which RKEY is not needed. When RKEY is not needed, it is hard determinically indicate if it can do RMA to specific mem type. With current mem type protocols it is not possible to support all combinations for src and dst mem type combinations( {(host,host) (host,cuda), (cuda,host), (cuda, cuda)) in this scenario.
Fixes #2919
pack mem_type info in RKEY and validate rma lane mem type with  remote and local memory type
=> validate rma lane if rkey is not needed for mem type

src/uct/ib/base/ib_iface.c
Add support for 16 IB channels width 
Such a width is possible with HDR, UCX should not fail in this case.
=> UCT/IB: Add HDR 16-links config recognition

config/m4/ib.m4, src/uct/ib/mlx5/ib_mlx5.h
This reverts commit 3d949802d66571d5a99ec0ccddbefd4f5dabe6d6.
Fixes #3025
=> UCT/IB/MLX5: Revert include verbs.h before mlx5dv.h

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.h, src/ucp/rma/flush.c, src/uct/ib/dc/base/dc_iface.c, src/uct/tcp/tcp_ep.c
This PR fixes a hang in shmem_verifier lock:atomic_lock_stress test. 
Since we have to flush SW RMA/AMO operations anyway, we have to go over all UCP endpoints. We could list all endpoints with pending RMA operations on the worker to avoid that, but it would make the UCP endpoint larger.
See commit message for more info.
=> UCP/FLUSH: Flush endpoint while flushing a worker

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c
UCT/UD: treat local error as a fatal on err handling path. 
Usually all local errors caused by a bugs, so we don't handle them.
`uct_ud_iface_handle_failure` should accept EP as an argument but it's `cqe` if it's called from common `uct_ib_mlx5_check_completion` and causes segfault in case of UD. That's OK for rc_mlx5 where EP lookup is implemented in `uct_rc_mlx5_iface_handle_failure` and remote error is also handled here. For UD, all remote failures are handled by timeout in `uct_ud_ep_slow_timer`.
=> UCT/UD: treat local error as a fatal on err handling path

contrib/test_jenkins.sh, doc/doxygen/ucxdox
Fail jenkins testing if docs build has warnings
=> TEST/DOCS: add WARN_AS_ERROR to doxygen config to check with jenkins

.gitlab-ci.yml
Use GitLab CI service to automatically upload tarballs for release tags.
GitLab mirror project: https://gitlab.com/amaslenn/openucx-ci
Currently it is set up using my user, later would nice to use something like `ucx-bot@openucx.org`.
=> GitLab CI config to upload release assets

src/uct/cuda/gdr_copy/gdr_copy_md.c
1) Align address to GPU PAGE SIZE when rcache is turned off.
2) register only requested memory region instead of complete allocation(cudaMalloc) region because this is inefficient if only small region of bigger allocation is used in the communication,
=> UCT/GDR_COPY:  Fix gdr_copy registration issues

src/ucp/wireup/select.c
Include iface latency cost to the AM BW lane score calculation.
latency overhead may grow with number of endpoints (e.g IB RC transports), so omitting it in score calculations may result in selecting unscalable transports for big scale
cherry-picked from #3051
=> UCP: Add latency to am_bw score calc - v1.5.x

src/ucp/wireup/select.c
Include iface latency cost to the AM BW lane score calculation.  
latency overhead may grow with number of endpoints (e.g IB RC transports), so omitting it in score calculations may result in selecting unscalable transports for big scale 
fixes #3050
=> UCP: Add latency to am_bw score calculation

src/ucp/core/ucp_ep.inl, src/ucp/rma/flush.c, src/ucp/wireup/wireup.c, src/uct/sm/mm/mm_ep.c, test/gtest/ucs/test_stats.cc, test/gtest/ucs/test_stats_filter.cc
Picked from #3054
Fixes #3063
(#3058 was supposed to be for v1.5.x, but it was based on master by mistake)
=> Fixes for endpoint flush - v1.5.x

config/m4/ib.m4
Resulted in variable names like `ac_cv_have_decl_________________________ibv_create_srq`
and `HAVE_DECL_________________________IBV_EVENT_TYPE_STR`.
architecture, approach, etc.
=> m4: Avoid line continuation in macro list

src/ucp/core/ucp_mm.h, src/ucp/core/ucp_rkey.c, src/ucp/rma/amo_send.c, src/uct/sm/mm/mm_posix.c, src/uct/sm/mm/mm_sysv.c
Returns error from shmem operations if invalid rkey is used in debug mode
follow up on  https://redmine.mellanox.com/issues/1582208 (Mellanox internal link)
=> UCP/RKEY: Add check that rkey is used on same ep it's unpacked on

src/tools/perf/libperf.c, src/tools/perf/libperf_int.h, src/tools/perf/ucp_tests.cc, src/tools/perf/uct_tests.cc, src/ucs/arch/x86_64/cpu.c, src/ucs/arch/x86_64/cpu.h, src/ucs/time/time.h
Replaces #2793 
Fixes #2792
@rzambre 
This PR also removes the CPU frequency warning. Instead of warning, just fall back to gettimeofday().
Currently ucs_get_time() is not used in data path. Even UD transport samples the timer during async thread only.
=> Use gettimeofday() in perftest and if rdtsc is unstable

src/ucp/wireup/select.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/mm_iface.c
- updated bandwidth values for shared memory transports
- rma_bw lanes will not be initialized for RMA feature
- avoid creating knem lan for RMA-only context
=> SHM: updated bandwidth value + removed RMA_BW from RMA

Makefile.am, contrib/test_jenkins.sh, contrib/ucx_perftest_config/README, contrib/ucx_perftest_config/test_types_ucp, contrib/ucx_perftest_config/test_types_uct, src/tools/perf/Makefile.am
Use UCX env variables instead of -d and -x options for UCP perftest.
- To avoid flooding of warnings like: 
`UCX  WARN  -d 'posix' ignored for UCP test; see NOTES section in help message`
- To run UCP tests with different devices rather than running with the same set of devices on each cycle iteration
=> TEST/JENKINS: Use correct options for ucx_perftest

src/ucp/core/ucp_ep.c
Fixes RMA short/bcopy/zcopy thresholds
Fixes https://github.com/openucx/ucx/issues/3081
UCX_ZCOPY_THRESH was not applied to ucp_<put|get>*
=> UCP/EP: fix rma config thresholds

src/tools/info/tl_info.c, src/tools/perf/perftest.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_thread.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucs/async/async.c, src/ucs/async/async.h, src/ucs/async/async_int.h, src/ucs/async/thread.c, src/ucs/async/thread.h, src/ucs/config/parser.c, src/ucs/config/types.h, src/uct/ib/base/ib_device.c, src/uct/ib/cm/cm.h, src/uct/ib/cm/cm_iface.c, test/gtest/common/test_perf.cc, test/gtest/ucs/test_async.cc, test/gtest/uct/test_flush.cc, test/gtest/uct/test_uct_ep.cc, test/gtest/uct/uct_test.cc
Replace ucp_mt_lock_t with ucs_async_context_t.
UCP may acquire mt_lock and async in different ordering, this is a potential deadlock.
=> UCP/WORKER: refactoring of MT locking

src/ucs/Makefile.am, src/ucs/type/init_once.h, test/gtest/ucs/test_type.cc
Motivation: to be used by UCX loadable modules service, to load modules only once, and resolve module directory only once. Since modules could be loaded from any thread, need a thread-safe solution.
=> UCS/TYPE: Add type macros for thread-safe one-shot initialization

config/m4/sysdep.m4, src/ucs/sys/sys.c
Fixes #3023 by restoring the previous behavior of not printing an error in case of EPERM
In addition, print better error message in case of EPERM
=> UCS/SYS: Better error handling of missing CAP_IPC_LOCK for HUGETLB

src/ucp/api/ucp.h, src/ucp/core/ucp_worker.c
- in case if single thread build is used - force single thread
worker initialization instead of error
=> UCP: fallback into single thread on single-thread build

src/uct/ugni/configure.m4
This PR is addressing issue 3135.
Adjust --with-ugni interpretation to allow explicit values.
This is ensure that it is possible to disable ugni even if it is present.  The commit also assures that custom directory selections will be honored.  The current m4 code forces the value "forced" for any user-supplied input for --with-ugni (and --without-ugni, I believe), and then defaults with_ugni to yes if the user doesn't supply any argument.  This effectively keeps the ugni code active all the time and forces the auto-detection to pass if ugni is present at all.
The update allows user intention to flow through the AC_ARG_WITH block.
Some systems have a compile environment which includes ugni, even if that is desired in the final build.
I suspect it can be merged following approval, however a …
=> UGNI: configure.m4: Adjust --with-ugni interpretation to allow explicit values

config/m4/cray_ugni.m4
This PR is addressing issue 3135.
Adjust --with-ugni interpretation to allow explicit values.
This is ensure that it is possible to disable ugni even if it is present.  The commit also assures that custom directory selections will be honored.  The current m4 code forces the value "forced" for any user-supplied input for --with-ugni (and --without-ugni, I believe), and then defaults with_ugni to yes if the user doesn't supply any argument.  This effectively keeps the ugni code active all the time and forces the auto-detection to pass if ugni is present at all.
The update allows user intention to flow through the AC_ARG_WITH block.
Some systems have a compile environment which includes ugni, even if that is desired in the final build.
The master branch version of this PR was approved and …
=> Adjust --with-ugni interpretation to allow explicit values

src/ucs/debug/memtrack.c
Adds ucs/sys/math.h include to memtrack.c
Functions in memtrack.c uses ucs_max() without the math.h include. Default configurations will pull in the header anyways, (it looks like --enable-stats is the guilty party here). This patch makes this include explicit.
=> UCS: Add missing include to memtrack.c

contrib/configure-devel, test/examples/ucp_client_server.c, test/examples/ucp_hello_world.c, test/examples/uct_hello_world.c, test/examples/ucx_hello_world.h
Useful to have built examples during development, for example, to check compatibility.
@amaslenn @yosefe
=> CONTRIB: add --enable-examples to configure-devel

src/ucs/debug/memtrack.c
Backport of #3142
Adds ucs/sys/math.h include to memtrack.c in 1.5.x branch.
Functions in memtrack.c uses ucs_max() without the math.h include. Default configurations will pull in the header anyways, (it looks like --enable-stats is the guilty party here). This patch makes this include explicit.
=> UCS: Add missing math.h headerfile to memtrack.c

config/m4/cuda.m4
The CUDA autoconf script has a typo that prevented LDFLAGS from being properly restored after the CUDA configure test. This bugfix fixes cuda.m4 to restore proper behavior.
Ref: #3143
=> CONFIG/CUDA: bugfix in autoconf script

src/tools/perf/perftest.c
Fix memtype initialization for perftest.
Not needed for v1.5.x - since the change which caused this was on master after the branch.
=> PERFTEST: Fix memory types initialization

src/tools/info/ucx_info.c
Address comments from RH bug [1667548](https://bugzilla.redhat.com/show_bug.cgi?id=1667548)
=> ucx_info: fix english wording in help

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_ep.c, test/gtest/ucp/test_ucp_wireup.cc
Reduce worker address size when unified mode is enabled
Worker address (which needs to be exchanged at startup) reduced as follows on one of the test machines:
- From 590b to 248b with default parameters
- From 51b to 36b with dc_x tls and specific HCA
Do not pack interface attributes in unified mode. It is enough to pass resource index of every tl iface, so that the peer could take attrs from its local tl iface with the same resource index.
=> UCP: Reduce worker address for unified mode

src/tools/info/ucx_info.c
Address comments from RH bug [1667548](https://bugzilla.redhat.com/show_bug.cgi?id=1667548)
=> ucx_info: fix english wording in help — v1.5

src/uct/ib/base/ib_iface.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/verbs/ud_verbs.c
- use regular SKB entry to send UD ACK messages
(instead of inline SKB record)
=> RC/UD: add support for max_inline==0

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/uct/ib/test_dc.cc
Add random DCI allocation policy for DC transport.
This allocation policy is known to provide better communication/computation overlap.
With this policy every endpoint gets its own DCI during initialization.
Several endpoints may share the DCI.
=> UCT/DC: Implement random dci allocation policy

src/uct/ib/rdmacm/rdmacm_md.c
RDMACM: disables iWarp device initialization due to lack of support
=> RDMACM: temporary disabled iWarp device initialization

PULL_REQUEST_TEMPLATE.md, src/ucp/api/ucp.h
PR fixes misprint in the doxygen for UCP/API: `ucp_tag_send_nbr()`
and + PR template is update to use italic font for comment in the HOW? section as for the WHAT? and WHY? sections. -- it seems that `_` was missed at the end of the comment.
`ucp_tag_send_nb()` should be used instead of `ucp_tag_send_nbr()`, because `ucp_tag_send_nbr()` is compared to `ucp_tag_send_nb()`
`ucp_tag_send_nbr()` -> `ucp_tag_send_nb()`
=> UCP/API: Fix misprint in the doxygen

doc/doxygen/conventions.md, doc/doxygen/design.md, test/examples/uct_hello_world.c
This PR applies the following changes:
- renames PD to MD in UCT "hello world" example
- minor fixes for misprints in the doc/doyxgen
Protection Domain is the deprecated name. Memory Domain is the new one.
architecture, approach, etc.
Studying source code of examples/uct
=> EXAMPLES/UCT: Rename PD to MD as PD is deprecated name

src/ucp/core/ucp_ep.c
This patch fixes `ucp_ep_print_info` output for protocol ranges for the transports that don't provide Eager short protocol (i.e. this attribute is set to `-1` in the config)
This is an example of how to reproduce the bug (usage: `UCX_TLS=tcp ucx_info -e -u t -D net`):
- w/o fix
```
#
#
#
#
```
- w/ fix
```
#
#
#
#
```
There is the transport (UCT/tcp) that doesn't have Eager short
support. This should be handled in the UCP config print operation.
The print operation doesn't work correctly, because the maximum
Eager short attribute is `ssize_t` (this is `-1`, when it is not
supported by some transport) and is passed as a `size_t` into
`ucp_ep_config_print_tag_proto`.
The fix is to change argument from `size_t` to `ssize_t` and
don't use in the comparisons with unsigned attributes when
this …
=> UCP/CONFIG: Fix support for UCTs w/o AM short

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, test/gtest/common/test_helpers.h, test/gtest/uct/ib/test_dc.cc, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h
Fix for iface tx ops buffer overflow. 
RC iface allocates buffer for tx op completions, which is used by zcopy and flush operations.
While max number of simultaneous zcopy operations is limited by CQ length, flushes are not limited at all. Since iface buffer for op completions fits just CQ length elements, it can be easily overflowed. 
Limit number of simultaneous flush operations with non NULL completions. 
The drawback of  this approach is that flush may be added to the pending queue, while CQ and QP resources are available. So there may be some extra ops called after flush, but executed before it.
An alternative solution would be using ~unlimited memory pool for TX op completions.
=> UCT/RC/DC: Fix iface tx ops buffer overflow

src/ucs/sys/string.c, test/gtest/ucs/test_sys.cc
- in case if value > 1024 Tb it could use uninitialized memory
to print size suffix
=> UCS: fixed potential data corruption in print memunits

test/gtest/ucs/test_time.cc
=> TEST/TIME: Allow up to 1% time calculation discrepancy for nanoseconds

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, test/gtest/common/test_helpers.h, test/gtest/uct/ib/test_dc.cc, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h
Fix for iface tx ops buffer overflow.
RC iface allocates buffer for tx op completions, which is used by zcopy and flush operations.
While max number of simultaneous zcopy operations is limited by CQ length, flushes are not limited at all. Since iface buffer for op completions fits just CQ length elements, it can be easily overflowed.
Use separate memory pool for flush operations with non NULL completions.
NOTE: this is **not** a cherry-pick from #3172, because of different UCT/IB code base
=> UCT/RC/DC: Fix iface tx ops buffer overflow - v1.5.x

NEWS
=> NEWS: Update

ucx.spec.in
Makes English usage e.g. of "develop" regular between ucx.spec entries
See "What"
N/A
=> Regularize English usage in ucx.spec.in

src/ucs/datastruct/mpool.c, test/gtest/ucs/test_mpool.cc
The PR adds additional checks for user input data for `ucs_mpool_init` and replaces `strdup`-`free` pair with `ucs_strdup`-`ucs_free` pair.
UCS/MPOOL APIs allow to not set
- `ucs_mpool_ops::obj_init`
- `ucs_mpool_ops::obj_cleanup`
but
- `ucs_mpool_ops::chunk_alloc`
- `ucs_mpool_ops::chunk_release`
must be provided by user to the mpool functionality.
Added additional checks for 
- `ucs_mpool_ops` object
- `ucs_mpool_ops::chunk_alloc` function
- `ucs_mpool_ops::chunk_release` function
to `ucs_mpool_init`
=>  UCS/MPOOL: Improve checks for user input values

LICENSES.apache20, bindings/java/checkstyle.xml, bindings/java/pom.xml, bindings/java/src/main/java/dummy-app/dummy/Dummy.java, bindings/java/src/main/java/org/ucx/jucx/Bridge.java, bindings/java/src/main/java/org/ucx/jucx/LoadLibrary.java, bindings/java/src/main/java/org/ucx/jucx/Worker.java
1. Added checkstyle rules, based on [Google java style guide](https://google.github.io/styleguide/javaguide.html), with small modifications (4 spaces).
2. Added licence into pom.xml, so we could publish library on [Maven central](https://maven.org/).
3. Added native-maven-plugin, to automatically generate jni header file from Bridge.java class (command `mvn native:javah`).
4. Minor fixes to pass checkstyle.
Prepare common stuff for JUCX development. TODO: add to jenkins tests JUCX tests.
=> JUCX add checkstyle, licence and header generation plugin.

src/tools/info/tl_info.c, src/tools/perf/lib/libperf.c, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/base/uct_md.c, src/uct/ib/base/ib_iface.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/ib/ud/base/ud_iface.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_iface.c, test/examples/uct_hello_world.c, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/test_tag.cc, test/gtest/uct/uct_test.cc
make uct_iface_open backward compatible
The same way as UCP, adding params argument with field_mask to API routines.
#3115
=> UCT/API: make uct_iface_open backward compatible

src/ucs/config/parser.c
- there was incorrect processing of aliases of configs
=> INFO: fixed crash on ucx_info -fca

src/uct/tcp/tcp_net.c
This PR adds `MSG_NOSIGNAL` flag to each send/recv in UCT/TCP.
`MSG_NOSIGNAL` prevents a sending SIGPIPE during calling send/recv when the remote side breaks the connection.
Updated common wrapper `uct_tcp_do_io` to pass `MSG_NOSIGNAL` as a flag.
=> UCT/TCP: Use MSG_NOSIGNAL to prevent SIGPIPE

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h
- added config for custom PCI bandwidth. this config should be used
to set actual limit for bandwidth in case when PCI can't provide
enough bandwidth
=> IB/MD: added config for custom PCI BW

src/ucp/core/ucp_worker.h, src/ucp/wireup/address.c
- Do not include worker name size to the worker address in release mode, because it is always zero.
- Do not pack iface and ep addr lengths in unified mode, because they can be taken from the local iface attrs.
It reduce worker address size by:
Release build (all modes):
- 1 byte for every address (worker name size)
Unified mode only:
- 1 byte for every iface address on every device   (iface addr length)
- 1 byte for every ep address (if present) on every device   (ep addr length)
=> UCP: Reduce worker address size

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/tcp/tcp_ep.c, test/gtest/uct/test_p2p_err.cc
This patch adds additional test cases that chackes AM ID for AM bcopy and zcopy cases.
And fixes missed checks for AM ID in IB/DC and IB/UD/ACCEL transports,
AM ID should be checked if `ENABLE_PARAMS_CHECK` is enabled
Added missing checks for AM ID in `uct_ep_am_bcopy` and `uct_ep_am_zcopy` functions
=>  UCT/IB: Add missed check on invalid AM ID

src/uct/tcp/tcp_ep.c
This patch changes `uct_tcp_ep_mod_events` behavior.
There is no need to have in epoll fds that don't expect any events
- remove fd from epoll set if new events are not expected anymore:
- add fd to epoll set if current events was 0
- modify fd in epoll set if new events != current events and both are != 0.
=> UCT/TCP: Optimize number of fds in epoll

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/api/ucpx.h
We are looking at using active messages in PGAS models for a variety of applications. Because these PGAS models are implemented on top of UCP, we lack the ability to use active messages from UCX. We attempted to use the UCT level active messages with UCP communication operations, but this introduced concurrency issues because of the different layers locks. To support our research using active messages in PGAS models, we propose a UCP active message API for UCP users to define and use their own active message callbacks at the UCP level. 
This commit only contains the proposed API. If a maintainer approves the API, we have already implemented the functions and can submit a second pull request with the function body, gtest, and example. 
New Proposed API:
- Allow for the insertion/putting of …
=> UCP/API: Proposed API for Active Messages at the UCP level

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, test/gtest/ucs/test_arbiter.cc, test/gtest/uct/test_pending.cc
This PR changes semantic of `ucs_arbiter_group_purge`. Now `purge_cb` return code is not ignored and the element is removed from the group if the code is `UCS_ARBITER_CB_RESULT_REMOVE_ELEM`. If any other value is returned by `purge_cb`, the element is kept in the group 
This way it will be possible to share a single group among several entities. Having one arbiter group per DCI (instead of per ep) in IB DC transport is an example.
=> UCS/ARBITER: Make purge conditional 

test/gtest/common/test_helpers.cc
Add missed IPv6 testing for test_uct_sockaddr
=> TEST/HELPERS: fix is_inet_addr for AF_INET6

src/ucp/core/ucp_context.c, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_wireup.cc
- set default 2 RNDV lanes
- fixed tests to pass on multi-lane mode
=> UCP/RNDV: set 2 RNDV lanes by default

src/ucs/datastruct/arbiter.c, test/gtest/ucs/test_arbiter.cc
Fixes #3259 bug, introduced in #3239. 
If the currently scheduled group changes its head, arbiter pointer should be updated accordingly
=> UCS/ARBITER: Fix purge bug

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
This PR implements AM short send
This improves unidirectional message rate by ~5-7%
Implemented common `uct_tcp_ep_am_send` function that performs send of internal TCP AM header and AM data.
=> UCT/TCP/EP: Implement AM short send

bindings/java/src/main/native/Makefile.am
Fix #3254
Fixes autogen warning for autogenerated files. Correct their names, so it removes during `make distclean`
First added a dependency on generated files as `noinst_...` but found after that just need to add to `BUILT_SOURCES` param.
=> JUCX: Fix autogen warning.

config/m4/gdrcopy.m4, configure.ac, src/uct/cuda/gdr_copy/configure.m4
GDR copy functions:
gdr_copy_to_bar
gdr_copy_from_bar
are much faster than native memcpy function for write combine cached GPU device memory. So ROCM also want to use it like CUDA gdr_copy TL.
But AMD GPU support large bar feature which export all GPU device memory to PCI BAR, so that CPU and other devices can directly access GPU device memory. So ROCM don't need to do GDR map or pin operation.
This is a preparation commit to share GDR config with ROCM in the following commits.
=> UCT/CUDA/GDR: move gdr config to be shared with rocm

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, test/gtest/uct/ib/test_dc.cc
With rand dci policy use arbiter group per DCI rather than per ep
With random dci policy all UCT DC endpoints share just a few DCIs. When ep has pending requests it keeps arbiter group scheduled until all of them are sent. Therefore number of arbiter groups scheduled in the arbiter scales together with number of eps. This may result in very long pending requests processing time, because progress would try to progress every arbiter group (every ep) even if no TX resources currently available.
Use arbiter group per DCI. This way, only up to DCIs num arbiter groups can be scheduled in the arbiter.
Added new `ucs_arbiter_group_purge_cond` routine for proper `uct_ep_pending_purge` support:
DC purge callback checks whether request ep matches ep being purged, and if not it returns error code …
=> UCT/DC: Use arbiter group per dci for rand dci policy

config/m4/cuda.m4, config/m4/gdrcopy.m4, src/uct/ugni/configure.m4
Adds missing "be" to "can't be found" messages in configure, e.g.
```sh
./config/m4/gdrcopy.m4:                    [AC_MSG_ERROR([gdrcopy support is requested but gdrcopy packages can't found])],
```
Fix English.
N/A
=> Missing 'be' in "can't be found" configure messages

src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/stream/stream_send.c, src/ucp/tag/tag_send.c
MEMTYPE
Enable inline send for HOST memory on setups where memtype(GPU) mds are opened 
Inline sends are disabled if UCX is build with memtype configuration support  to avoid buffer memory type check overhead in fastpath.   Now, with loadable modules approach, MEMTYPE mds will be loaded automatically if setup supports.  This would cause poor small message latency for pure HOST applications.
=> UCP: Enable inline send for HOST mem on MEMTYPE setups

contrib/test_jenkins.sh, contrib/ucx_perftest_config/test_types_ucp, src/tools/perf/cuda/cuda_alloc.c, src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc
CUDA tests were not running in Jenkins, and this error was silently ignored. Also, memset() for cuda buffers was missing, and cuda-managed was not tested.
=> Fixes for perftest and Jenkins with CUDA

src/uct/tcp/tcp.h, src/uct/tcp/tcp_iface.c
This PR improves iface initialization by extracting listener initialization to separate function and adds missing `status` assignments that causes UCS_OK return value in case of failure (`bind`, `getsockname`).
Also remove `UCX_TCP_BACKLOG` parameter as it can be replaced my maximal accept queue - `SOMAXCONN` constant.
The PR fixes return value of iface initialization in case of failure (`bind`, `getsockname`).
=> UCT/TCP: Refactor iface and bug-fixing

src/ucs/sys/compiler.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_iface.c
- suppressed too aggressive evaluation for unaligned packet
value warning
fix for https://github.com/openucx/ucx/issues/3289
should be backported to v1.5 branch
=> COMPILATION: fixed compilation by GCC9.x

src/ucs/sys/math.h
Fixes macro definitions in math.h
They violate UCX code style
=> UCS/SYS: Fix math macro definitions

src/uct/tcp/tcp_ep.c
Fix signedness and prevent possible errors.
Epoll events defined as `uint32_t`
`int` -> `uint32_t`
=> UCT/TCP: Fix type of epoll events

bindings/java/src/main/native/Makefile.am, config/m4/java.m4
Allow the java bindings to compile in a VPATH/out-of-source-tree build
Couldn't compile out of tree
* Point configure's maven test to the source directory.
* Tell maven where the POM file is in the source tree.
=> Allow the java bindings to compile in a VPATH/out-of-source-tree build

configure.ac, contrib/test_jenkins.sh
This PR makes configure more strict in case of `--with-docs-only` specified
The PR improves UX when using `configure --with-docs-only`
Check doxygen, html, pdf, man features (tools availability, their versions and etc) after `DX_INIT_DOXYGEN` macro. If something is not found, just fail configure and report an error
=> CONFIG: Fail if --with-docs-only specified, but required tools can't be found

src/ucs/sys/compiler.h, src/uct/rocm/rocm_cma_md.c, src/uct/rocm/rocm_common.c, src/uct/sm/mm/mm_ep.c, src/uct/sm/mm/mm_iface.c
- suppressed too aggressive evaluation for unaligned packet
value warning
fixes https://github.com/openucx/ucx/issues/3289
backport from https://github.com/openucx/ucx/pull/3290, https://github.com/openucx/ucx/pull/3129 and https://github.com/openucx/ucx/pull/3280
(cherry picked from commit 988ff57f4134205c7eca418383471b6397bcea90)
=> COMPILATION: fixed compilation by GCC9.x - v1.5

src/ucp/api/ucp.h
* remove "an" in ucp.h:ucp_context_query()
* update English in ucp.h:ucp_context_print_info().
* also can/should we make the context parameter "const" since it's an inspection routine?
Fixing English.
N/A
=> DOC: Small doc. fix in UCP

bindings/java/src/main/native/Makefile.am
Fixes #3311 
Enumerate all generated source as dependencies.
To fix Makefile generation
=> Fix JAVA: compile fails, missing target

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorkerParams.java
Fixing javadoc build that fails #3251 
Reference to UcpEndpoint, that not yet implemented.
=> JUCX: Fix javadoc build.

test/gtest/Makefile.am
Adds CUDA_LDFLAGS to gtest Makefile.am
gtest build fails with undefined reference to cuda symbols on master
`make -n` shows that the following command is executed
```
echo "  CXXLD   " gtest;/bin/bash ../../libtool --silent --tag=CXX   --mode=link g++ -O0 -D_DEBUG -g -Wall -Werror  -fno-tree-vectorize -DGTEST_UCM_HOOK_LIB_DIR="\"/home/akvenkatesh/ucx-github/build/test/gtest/ucm/test_dlopen/.libs\""   -no-install -Wl,-dynamic-list-data  -o gtest common/gtest-gtest-all.o common/gtest-main.o common/gtest-test_helpers.o common/gtest-test_obj_size.o common/gtest-test_perf.o common/gtest-test.o ucm/gtest-malloc_hook.o uct/gtest-test_amo.o uct/gtest-test_amo_add_xor.o uct/gtest-test_amo_and_or.o uct/gtest-test_amo_cswap.o uct/gtest-test_amo_fadd_fxor.o uct/gtest-test_amo_fand_for.o …
```
=> gtest makefile.am missing lcuda inclusion

test/gtest/uct/test_tag.cc
fixes #3014 
Increase timeout for tag_expected tests, because rndv test uses maximum allowed message sizes, which can be quite resource consuming (especially under high testing load)
=> GTEST/UCT: Fix timeout for hw tag rndv

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c
additional fix for https://github.com/openucx/ucx/issues/3289
backport from https://github.com/openucx/ucx/pull/3307
(cherry picked from commit cbd154e1cb4ad47402203d633da5577ffa70289a)
=> IB: compilation fixes for GCC 9+ - v1.5

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/common/test_obj_size.cc
This PR does refactoring of TCP endpoint initialization.
This PR is needed by subsequent PRs that implement non-blocking `connect()` and connections reusing per direction.
Added new abstractions:
- Communication context (`uct_tcp_ep_ctx_t`)
Currently an EP created by user calling `uct_ep_create_connected` is used by TCP to perform TX operations. Also TCP creates another EP (hidden from user) that performs RX operations.
The idea of the communication context is to assign TX or/and RX to TCP EP to allow do TX and RX operation simultaneously.
- Progress (`uct_tcp_ep_progress_t`)
Will be used by TCP CM to adjust function pointers to progress CM (internal messages between TCP EPs or non-blocking `connect()` handler while they are not connected) and then AM data w/o any impact on critical path …
=> UCT/TCP: EP code refactoring

src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
Fixes #3236 
(seg size and RX CQ len are overwritten with wrong values by RC_IFACE constructor when HW TM is enabled)
Use correct segment size and RX CQ len with HW TM.
=> UCT/TM: Fix tag-matching initialization

configure.ac, src/uct/rocm/Makefile.am, src/uct/rocm/base/rocm_base.c, src/uct/rocm/configure.m4, src/uct/rocm/gdr/Makefile.am, src/uct/rocm/gdr/configure.m4, src/uct/rocm/gdr/rocm_gdr_ep.c, src/uct/rocm/gdr/rocm_gdr_ep.h, src/uct/rocm/gdr/rocm_gdr_iface.c, src/uct/rocm/gdr/rocm_gdr_iface.h, src/uct/rocm/gdr/rocm_gdr_md.c, src/uct/rocm/gdr/rocm_gdr_md.h, ucx.spec.in
GDR copy functions get higher bandwidth than
OS native memcpy for GPU write combine cached
device memory.
Due to AMD GPU support large bar feature, CPU
can access all GPU device memory directly, so
no need to do GDR pin/map.
=> UCT/ROCM: add GDR TL

bindings/java/src/test/java/org/ucx/jucx/UcpContextTest.java, contrib/test_jenkins.sh
Disable signal trapping for java. Can cause errors reported in #3337 
JVM has it's own [signal handler](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/aa318070b27849f1fe00d14684b2a40f7b29bf79/hotspot/src/os/posix/vm/os_posix.cpp#L848)
Some signals are catched and propagate to java. Also if error in JNI happens JVM will generate [hs_err file](https://github.com/facebook/rocksdb/wiki/JNI-Debugging#interpreting-hs_err_pid-files), that makes debugging easier, and not freezes process for 240 minutes.
=> DNM JUCX: Disable signal trapping for java

src/uct/api/uct_def.h
Move the embedded comment inside the enum to before the enum where the
"ingroup" is. Fixes #3333 
Crashing out on Fedora 29 with "runaway argument"
N/A
=> DOC/doxygen: Attempt to fix "runaway argument" error on Fedora.

test/gtest/uct/test_stats.cc
This PR handles `UCS_ERR_NO_RESOURCE` in stats tests
UCT transport may return `UCS_ERR_NO_RESOURCE` at the first call, this should be handled by application/test
`TEST_STATS_CALL_AND_TRY_AGAIN` macro loops while an operation returns `UCS_ERR_NO_RESOURCE`
=> GTEST/UCT: Handle ERR_NO_RESOURCE in stats tests

config/m4/java.m4
Do not build java unless explicitly requested.
To avoid for now issues like in #3355
=> JUCX: don't build java unless explicitly specify

test/gtest/uct/test_event.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/test_stats.cc, test/gtest/uct/uct_test.h
Add progress loop to finish connection for some transports where it's required
Some transport may need some time to establish a connection to a peer before start data transfer
Add short_progress_loop() for 1 second to make sure that connections are established.
=> UCT/GTEST: Add progress loop to finish connection for some transports

src/tools/perf/lib/libperf.c
This PR enables iface progress before the worker callback queue is being progressed inside `uct_perf_test_setup_endpoints` in case of `uct_iface_flush` returns `UCS_INPROGRESS`.
Libperf calls `uct_perf_iface_flush_b` inside `uct_perf_test_setup_endpoints`, but UCT iface progress isn't enabled before that. So, this leads to hanging in `uct_perf_iface_flush_b`, because `uct_iface_flush` will always return `UCS_INPROGRESS` for tranports that may have some underlying communications (e.g. TCP with non-blocking connections)
swap(`uct_perf_test_setup_endpoints(...)`, `uct_iface_progress_enable(...)`) in libperf.c.
=> UCT/PERF: Enable iface progress before progressing worker

configure.ac
Enables strict handling for `--enable-doxygen-{html | man | pdf}` arguments if `--with-docs-only` requested
Improves configuration UX
1. Checks whether `--enable-doxygen-{html | man | pdf}` was set to `"yes"` or set to other value (or not set at all)
2. If set and there are no required tools found during `DX_INIT_DOXYGEN`, reports an error in case of `--with-docs-only` set
=> CONFIG/DOCS: Enable strict handling for --enable-doxygen-x args

configure.ac
English fixes in configure
review comments from #3371 
`is/are` -> `was/were`
=> CONFIG: Fix error messages

bindings/java/src/main/native/Makefile.am, contrib/test_jenkins.sh
Set a maven project repo inside a project dir. Fixes #3347 
By default, maven uses ~/.m2 to download and cache dependencies. On jenkins nodes user /home directory is NFS, so if multiple builds run simultaneously, it can conflict on dependencies files.
=> JUCX: use maven local repo in project dir.

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h
Updates English in UCP header files
Usage of "will" replaces "would" (latter implies "doesn't actually happen")
N/A
=> Update would -> will in UCP headers

src/ucp/api/ucp.h, src/ucp/api/ucpx.h
There are a few trailing spaces in ucp.h/ucpx.h
Remove trailing spaces.
N/A
=> Remove some trailing end-of-line spaces in UCP(X) headers

bindings/java/pom.xml
Update checkstyle version, to fix a vulnerability warnings
```Known     moderate     severity security vulnerability detected in com.puppycrawl.tools:checkstyle     < 8.18     defined in pom.xml.                        pom.xml update suggested: com.puppycrawl.tools:checkstyle     ~> 8.18.                            Always verify the validity and compatibility of suggestions     with your codebase..```
=> JUCX: Update checkstyle version to fix vulnerability warnings.

src/uct/tcp/tcp.h, src/uct/tcp/tcp_iface.c
This PR fixes the behavior of TCP iface progress engine when `UCX_TCP_MAX_POLL` is set to >= 32 or set to `-1` (`UINT_MAX`) - until drained.
Also, this PR does some cleanups in TCP configuration table
`UCX_TCP_MAX_POLL` accepts `-1` as an argument to do progress/polling until drained.
Wrap `epoll_wait()` with `do {} while ()` loop that checks whether we need to read more events from the epoll - i.e. it should meet the following conditions:
1. total read events < `UCX_TCP_MAX_POLL`
2. current number of read events == maximal expected events per each `epoll_wait()`
=> UCT/TCP: Fix progress until drained

contrib/test_jenkins.sh, src/ucs/time/time.h, test/gtest/Makefile.am, test/gtest/common/main.cc, test/gtest/common/test.cc, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/common/test_obj_size.cc, test/gtest/common/test_watchdog.cc, test/gtest/uct/test_pending.cc
This PR introduces timeout per each test (current value - `900` seconds = `15` minutes)
To abort testing if some test takes too long to complete.
Start an additional thread that waits for a signal on `pthread` conditional variable with timeout set.
When a test completes, it calls `pthread_cond_signal`, the watchdog thread restarts the timer.
If the timer expires before a test calls `pthread_cond_signal`, the watchdog thread calls `abort()`.
=> GTEST/COMMON: Add timeout per test

src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/perftest.c
This pull request will fix a problem in ```ucx_perftest```'s multi-threaded mode, which caused the test to run only on the master thread.
It also contains fixes for several other problems that have been revealed by the previous fix, as automated tests will not pass without them.
When operating under the multi-threaded mode, only the master thread's ```max_iter```, ```report_interval``` and other related counters/timers are restored correctly after the warm-up run.
Therefore, when entering the actual timed benchmark, all the other threads will fail the check in ```ucx_perf_context_done``` immediately and skip to the end of the test.
As a result, the thread number, provided by ```-T thread_num```, does not work as the user would expect.
A new function …
=> TOOLS/PERF: Fix ucx_perftest's multi-threaded mode

src/uct/base/uct_iface.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/common/main.cc
Implements ring-buffer for partial receive of AM messages and avoidance of extra `memcpy` (`memmove`)
This PR starts series of optimization for UCT/TCP transport.
This PR replaces `memmove` applied for already received data to the
end of the `ep::buffer` by having AM buffer (`ep::buffer`) with
`size = iface::config::buf_size * 2`. The second half of the
buffer is used as a virtual buffer to do partial receive into it.
Before this PR:
After this PR:
1) The AM headers of the messages received fully
2) The AM headers of the (N-1) messages received fully, the header of the N message consists of two parts.
=> UCT/TCP: Implement partial receive/message coalescing using ring buffer

src/ucs/arch/x86_64/cpu.c
This PR fixes a stack buffer overflow that happens during reading `/proc/cpuinfo` on the x86 platform.
This bug can crash an optimized build of UCX, if Clang was used as the compiler.
The scanset `%[\n]` works like a `%s` in the sense that it also writes a terminating null character to the provided buffer, and this causes a buffer overflow. This behavior can be verified by:
```
char* str = "hi\n";
char eol[3] = {'z', 'z', 'z'};
sscanf(str, "hi%[\n]", eol);
printf("%x\n", eol[0]);
printf("%x\n", eol[1]);
printf("%x\n", eol[2]);
```
Increasing the buffer size to two resolves the issue.
=> UCS/ARCH: Fix stack overflow in sscanf

src/uct/base/uct_iface.h
Use an argument instead of a local variable from the function that calls `uct_pending_queue_dispatch`
Fixing copy-paste bug
Added missing `_`
=> UCT/BASE: Fix pending queue macro

src/uct/tcp/tcp.h, test/gtest/uct/test_p2p_am.cc
Fixes #3382
TCP uses for AM header - `uint16_t` [0..65535], but it's not enough for messages > 65535.
Use `unsigned` (i.e. 32-bit unsigned int) for TCP AM header instead, because internal `uct_iface_invoke_am` and  API `uct_ep_am_short` also uses this type.
=> UCT/TCP: Add support for messages with the length > 64k

src/uct/tcp/tcp_ep.c
Fix possible fd leak
This is a resource leak in case of memory allocation failure
`UCS_OK` -> `status`
=> UCT/TCP: Fix possible fd leak

contrib/test_jenkins.sh, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/test_tag.cc
This PR allows using common tag (and max_bb) variable names for rc_x and dc_x transports.
UCT_RC_TM* vars will work for both transports
Can be useful for app runs with default transport - only a single variable would need to be specified (no need to worry about particular transport). 
We used to have common names for all rc, dc, rc_x and dc_x transports in the past
=> UCT/TM: Define common TM config names for rcx and dcx

contrib/test_jenkins.sh, test/gtest/common/test_watchdog.cc, test/gtest/ucm/malloc_hook.cc
Fixes #3404 
Make the testing stable enough under high load
Increase `sleep(...)` time (1 minute) value through `WATCHDOG_GTEST_SLEEP_TIME_` env  and expected timeout (5 minutes) in the `test_jenkins.sh` script.
=> GTEST/COMMON: Add more safety margin for the watchdog test

src/tools/perf/perftest.c, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_iface.c, test/gtest/ucs/test_sock.cc
This PR adds the option for socket RCV buffer (default: 64k - the same as for SND buffer)
Also, handles 0 value for both options as a default system value
This gives the possibility to adjust RCV buffer for tuning UCT/TCP
The same as it was done for socket SND buffer size
=> UCT/TCP: Add cfg option for socket RCV buffer

test/gtest/uct/test_stats.cc, test/gtest/uct/uct_p2p_test.cc
1) Refactor UCT stats tests.
2) Add progress+flush to test initialization.
1) Makes UCT stats tests stable to different UCT implementations (and this is needed for 2)).
2) This helps us to avoid adding `flush()` in the different places of code to progress connections and make it common.
1) Keep the initial values of EP and IFACE counters to use in the stats tests.
2) Add `flush()` calling to `init()` function.
=> UCT/GTEST: Refactor UCT stats tests

test/gtest/ucp/test_ucp_rma.cc
Disable some UCP RMA tests
They are disabled due to sporadic slowness - as a result, failure in Jenkins (watchdog kills the test)
Check transport and variant for the RMA test
=> UCP/GTEST: Conditionally disable slow RMA tests

config/m4/compiler.m4, src/ucs/debug/memtrack.c
- to prevent unaligned access violations on clang
fixes https://github.com/openucx/ucx/issues/3395
=> COMPILATION: set max type alignment to 16 bytes

bindings/java/src/main/java/org/ucx/jucx/NativeLibs.java, bindings/java/src/main/java/org/ucx/jucx/ucs/UcsConstants.java
Load UCT transport in JUCX.
To support listeners and other functionality needs at least rdma_cm transport that comes in a separate shared library.
Extract from a jar resources ucx folder where al UCT transport libs are located. 
Now in logs we see:
```
[1553185102.403338] [mti-swat5:24517:0]         module.c:61   UCX  DEBUG ucs library path: /tmp/jucx5528761481474773491/libucs.so
[1553185102.403345] [mti-swat5:24517:0]         module.c:245  UCX  DEBUG loading modules for uct
[1553185102.404006] [mti-swat5:24517:0]         module.c:177  UCX  TRACE loaded /tmp/jucx5528761481474773491/ucx/libuct_ib.so [0x7fb6f854ea90]
[1553185102.404011] [mti-swat5:24517:0]         module.c:136  UCX  TRACE could not find symbol 'ucs_module_global_init' in /tmp/jucx5528761481474773491/ucx/libuct_ib.so …
```
=> JUCX: load UCT transport.

config/m4/compiler.m4
Fix spelling of "arhitecture" 
English
N/A
=> Fix 'architecture' spelling in compiler.m4

config/m4/rocm.m4, src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/ipc/rocm_ipc_ep.c, src/uct/rocm/ipc/rocm_ipc_md.c, src/uct/rocm/ipc/rocm_ipc_md.h
UCX won't pass host memory to rocm_ipc, so remove
the CMA code in IPC which was used to support host
memory.
=> UCT/ROCM/IPC: remove unused CMA code

src/uct/ib/dc/dc_mlx5.c
Remove unnecessary checks from DC iface flush
- Flush is considered to be IN_PROGRESS if just one of dcis is not ready yet, thus no need to check the rest of dcis
- All DC eps are not deleted if they are waiting for grant, no need to postpone flush until grant is received
=> UCT/DC: Remove needless checks from iface flush

contrib/valgrind.supp, src/uct/ib/cm/cm_iface.c
Disable the cm transport if the ib_ucm.ko module is not loaded.
cherry-picked from the master branch.
48acfc1e8818a37031fe36aabeb7fb7899661193
cda835bffd48fee738d9ea243c062df953ac05f1
Prevent an attempt to use the cm transport when a required module for it is not loaded on the host, thus prevent an init failure.
Check if the ib_ucm.ko module is loaded when checking if the cm transport can be used. 
If not, exclude this transport from the list of available resources.
=> UCT: Disable the cm transport if the ib_ucm.ko module is not loaded - v1.6.x

src/ucs/sys/math.h, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/rc/base/rc_iface.c, test/gtest/uct/ib/test_ib.cc
Fixes `UCX_{RC_VERBS, RC_MLX5, DC_MLX5}_RNR_TIMEOUT` environamnet variable
Align the RNR timeout value calculation (conversion from seconds) with the values for RNR NAK timer filed from `Table 48 Encoding for RNR NAK Timer Field` of IBTA spec Vol 1 - Release 1.3
1. Implement `uct_ib_to_rnr_fabric_time` that calculates the IB RNR value that is in range [0..31]. It replaces the use of `uct_ib_to_fabric_time` that calculates QP timeout.
2. Set `RNR_TIMEOUT` default value to `1 ms` instead of `30ms` that was converted by the IB QP time formula to `13` that means `0.96` milliseconds delay - so it keep the same behavior as previos (i.e. `~0.96 ms` RNR NACK timeout)
3. Rename `uct_ib_to_fabric_time` -> `uct_ib_to_qp_fabric_time`
=> UCT/IB: Fix conversion from seconds to IB RNR time

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_net.c
Add UCS blocking and non-blocking send/recv
They are needed to use from UCT/TCP and UCT/TCPCM code.
Implement `ucs_socket_send`/`ucs_socket_recv` and `ucs_socket_send_nb`/`ucs_socket_recv_nb` (copied from the TCP code)
=> UCS/SYS: Add non-blocking/blocking send/recv operations

src/ucm/malloc/malloc_hook.c
=> UCM: Avoid releasing environment strings in library destructor

src/ucm/malloc/malloc_hook.c, src/ucm/util/reloc.c, test/gtest/ucm/malloc_hook.cc
dlerror(), which is called from dynamic module loader, is calling
asprintf() which is allocating memory. Under valgrind, reloc hooks are
not catching intra-glibc calls to malloc, so need special hook for
asprintf().
=> UCM: Add reloc hooks for (v)asprintf - v1.6.x

src/ucm/util/reloc.c, src/ucm/util/reloc.h
Make ucm_reloc_get_orig() a static function 
We need to make sure that the symbol search is done from the context of the shared object which defines the replacement function.
More info is here - https://github.com/openucx/ucx/pull/3436
=> UCM: Make ucm_reloc_get_orig() a static function - v1.6.x

bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am, configure.ac, contrib/test_jenkins.sh
Generating pom file during configuration to support out of source build, removing env variable dependency.
To solve #3311 and got all needed information regarding paths from autoconf.
=> JUCX: Fixes for out-of-source build

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/ucx/jucx/UcpWorkerTest.java
Ability to get worker address from JUCX.
To be able to instantiate endpoints by specifying worker address.
Wrap memory of `ucp_address_t` to java's direct byte buffer in JNI -> copy to java's direct byte buffer, allocated and managed in java -> release `ucp_address_t` in JNI. `ByteBuffer` is handy class, that could be directly used in java socket communication.
=> JUCX: get ucp_worker address functionality.

src/ucs/config/parser.c, test/gtest/uct/test_peer_failure.cc
Fixes inheritance of common RC MLX5 config for RC/MLX5 and DC/MLX5.
W/o this fix it requires configuration names with excessive `RC` prefix (e.g. `RC_RC_IB_TX_QUEUE_LEN` instead of expected `RC_IB_TX_QUEUE_LEN`).
Remove `RC` prefix when inheritances RC common MLX5 configuration.
+
1. add a missing article in logging
2. remove check for "dc" UCT transport in the `test_uct_peer_failure_multiple` tests
=> GTEST/UCT: Fix name for DC&RC's TX_QUEUE_LEN config parameter

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, src/uct/api/uct.h, src/uct/base/uct_iface.h, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_iface.c, test/gtest/ucs/test_arbiter.cc
- in some cases reply to FC_HARD_REQ could not be sent immediately due
to lack of HW resources, in this case request is pushed into arbiter.
But in case if peer is fallen into same situation - it could cause
deadlock.
- fix: add FC grand request with high priority to send it out-of-order
backport from https://github.com/openucx/ucx/pull/3442 & https://github.com/openucx/ucx/pull/3443
=>  UCS/ARBITER: Add function to push element to group head, fixed RC FC deadlock - v1.6

test/gtest/ucs/test_frag_list.cc, test/gtest/ucs/test_time.cc, test/gtest/ucs/test_twheel.cc
Removes excessive (and harmful for issues reproduction) `srand()` calls.
GTEST calls `srand()` and prints seed at the beginning of the testing, but some tests re-writing this value by calling `srand()`
Remove `srand()`s
=> GTEST: don't change random seed set during initialization

doc/CodeStyle.md
Fix wrong format for `Doxygen` and `Error handling` items
Looks like wrong format
Remove excessive asterisks (`*`)
=> DOC: Update CodeStyle.md

contrib/test_jenkins.sh, test/gtest/uct/uct_p2p_test.cc, test/gtest/uct/uct_p2p_test.h, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
The PR adds "GTEST_UCT_TCP_RDMA_DEVS_ONLY" knob that controls for which devices GTEST/UCT will be run - for all or for RDMA devices only.
The PR reduces the total time consumed by Jenkins testing by reducing the number of configurations run for UCT/TCP.
`contrib/test_jenkins.sh` sets `GTEST_UCT_TCP_MLX_DEVS_ONLY=1` to run UCT/TCP gtests over IP interfaces configured on RDMA devices.
In this case GTEST/UCT skips the IP interfaces configured on non-RDMA devices. If no RDMA devices found, it uses fallback mode that adds found non-RDMA device's resources to the vector with all resources.
=> GTEST/UCT: Run Jenkins gtests for TCP over fastest device

src/ucs/sys/sock.c, src/ucs/sys/sock.h, test/gtest/ucs/test_sock.cc
Implement sockaddr compare function
They will be needed for #3423 and #3428 
The same is it done for other utilities in the `ucs/sys/sock.[ch]`
=>  UCS/SYS: Implement sockaddr compare function

src/uct/ib/dc/dc_mlx5.c
Align attributes and attributes mask passed to modify QP (experimental and normal) for DCI
They need to be aligned
- Remove/add flag from/to attributes mask
- Remove attribute field filling
=> UCT/IB/DC: Align attributes and attributes mask passed to modify QP

src/uct/ib/base/ib_verbs.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/base/rc_iface.c
Fix AR support when HW TM is enabled
If OOO support is enabled, need to create TM XRQ with OOO support as well.
So that internal HW TM DCIs (managed by FW) would be created with OOO support
Cherry-pick from #3465 (3 commits squashed to one, no other changes)
=> UCT/DC: Fix OOO support for TM DCIs - v1.6.x

src/ucp/core/ucp_request.c, src/ucp/tag/tag_send.c
- removed tag specific initializations from general request_start call
to eliminate data conflict
=> UCP/TAG: tag specific initialization removed from general init function

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
Set cuda_ipc bandwidth score to NVLink bandwidth capacity
If IB and cudaIPC selected in intra node rma_bw lanes, cuda IPC need to appear before IB lane as both can do RMA to cuda memory
=> UCT/CUDA_IPC: Set cuda_ipc bandwidth score high for priority 

src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/test_flush.cc
Invoke error handling flow for UCT_FLUSH_FLAG_CANCEL instead of just SW resources cleanup.
Fixes the bug which was rare reproducible on zcopy or RMA operation when user's buffer
is freed before operation completion.
=>  UCT/IB: fix uct_ep_flush with UCT_FLUSH_FLAG_CANCEL 

bindings/java/pom.xml.in, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpContext.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpMemory.java, bindings/java/src/main/native/Makefile.am, bindings/java/src/main/native/context.cc, bindings/java/src/main/native/memory.cc, bindings/java/src/test/java/org/ucx/jucx/UcpMemoryTest.java
Register memory in JUCX.
To be able to perform RDMA operations in JUCX
Added to `UcpContext` 2 public methods: `allocateMemory` and `registerMemory` to allocate or register `MemoryMappedBuffer`.
=> JUCX: UCP memory registration functionality.

src/ucm/configure.m4
=> UCM: Link with --no-as-needed, to find all symbols at runtime

test/gtest/common/test_perf.cc, test/gtest/common/test_perf.h, test/gtest/ucp/test_ucp_perf.cc, test/gtest/uct/test_uct_perf.cc
Reduce the number of iterations (100k) for TCP
The tests (with 2kk iterations) takes too long
Set the maximum number of iterations (100k) if has TCP transport
=> GTEST: Reduce the number of iterations (1k) for TCP

bindings/java/src/main/native/Makefile.am, bindings/java/src/main/native/jucx_common_def.h
Remove requirement for c++11, since for now not used any features of c++11. 
To compile on old gcc.  cc @alinask
=> JUCX: remove c++11 requirement.

bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java
Do not start a listener on connecting by worker address in test
No need to create it.
=> JUCX: do not start listener on connecting by worker address

src/ucm/cuda/Makefile.am, src/ucm/rocm/Makefile.am
Fixes #3480 
@Akshay-Venkatesh  @bureddy
=> UCM/BUILD: Make sure -l<lib> for linker is passed after --no-as-needed

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpMemory.java, bindings/java/src/main/native/context.cc, bindings/java/src/test/java/org/ucx/jucx/UcpMemoryTest.java
Set memory address of start of registered memory.
Need to do RDMA operations (ucp_get_nb/ucp_put_np, etc).
=> JUCX: set memory address of registered memory.

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/ucx/jucx/UcpWorkerTest.java
Worker progress functionality.
Needed for RDMA non blocking operations.
=> JUCX: worker progress functionality.

bindings/java/src/main/native/context.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h
Add jucx_context structure that would keep needed information to map ucp_request - to java world. For now, only pointer to callback object is needed.
Need to perform callbacks from ucx to java. Here's a cdde snippet:
```
ucs_status_ptr_t request = ucp_get_nb((ucp_ep_h)ep_ptr, result_address, result_size,
remote_address, rkey_p, send_callback);
if (UCS_PTR_IS_PTR(request)) {
((struct jucx_context *)request)->callback = env->NewGlobalRef(clbk);
}
void send_callback(void *request, ucs_status_t status)
{
struct jucx_context *ctx = (struct jucx_context *)request;
while(ctx->callback == NULL) {
pthread_yield();
}
if (status == UCS_OK) {
call_on_success(ctx->callback);
} else {
call_on_error(ctx->callback, status);
}
JNIEnv *env = get_jni_env();
env->DeleteGlobalRef(ctx->callback);
ctx->callback …
```
=> JUCX: jucx context initializtion.

test/gtest/common/test.h
Fix skip reason for skip condition passed as a macro
Fixes #3518 
Stringify `skip_cond` argument inside the wraper macro
=> GTEST: Fix skip reason

src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, test/gtest/uct/test_p2p_am.cc
Removes `MAX_SHORT` attribute from UCT config
Only TCP and MM transports depend on this attribute. They can be replaced by the transport-related attributes (`FIFO_ELEM_SIZE` for MM)
1. Removes max_short from config
2. Remove dependencies from CUT transports on this parameter
3. Remove excessive UD_MIN_INLINE macro
4. Remove unnecessary test that checks MAX_SHORT config
=> UCT: Remove MAX_SHORT attribute from UCT config

test/gtest/common/test.cc
Move `watchdog_signal()` invocation from `TestBodyProxy` to `TearDownProxy`
Some tests skip testing before initialization is done, i.e. `SetUpProxy` catches Skip exception and doesn't execute `TestBodyProxy`. So, the watchdog wasn't notified about the skipped test and doesn't restart its timer.
It may lead to gtest failures when there are multiple skipped tests and small watchdog timeout set.
1. Move `watchdog_signal()` invocation from `TestBodyProxy` to `TearDownProxy`
2. Removed empty `else-if`s in `TestBodyProxy`
=> GTEST: move watchdog signaling to TearDownProxy

src/ucm/malloc/malloc_hook.c, src/ucm/util/reloc.c, test/gtest/ucm/malloc_hook.cc
Fixes issue with UCX python bindings where dlopen() call from python executable was not hooked, so a library loaded by python (runtime.cpython-37m-x86_64-linux-gnu.so) did not have Cuda hooks installed
=> UCM: Search for symbols in .got, in additon to .got.plt

README
Added a reference to the MPICH/UCX wiki page
The README was missing a link to it.
=> README: added a reference to the MPICH/UCX wiki page.

bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h
Get JNI env method.
Need to call java stuff from UCX callbacks.
Cache global JavaVM object (singleton) and after [attach thread to get JNIEnv* ](https://stackoverflow.com/a/12421377)
=> JUCX: Get JNI env utility.

bindings/java/src/main/java/org/ucx/jucx/UcxCallback.java
ucxCallback class.
To pass callbacks from java to JNI and call them back asynchronously. Needed for Rdma operations + error handling.
=> JUCX: UcxCallback class.

bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h
JUCX: set error handler for endpoint 
To not freeze process when transport error occurred.
Depends on #3525
=> JUCX: set error handler for endpoint

test/gtest/uct/test_p2p_am.cc
Consider AM::max_short when setting the length for the send buffer.
Fix possible bug in the test if some (e.g. future) transport supports `iface_attr.cap.am.max_short` < 80 bytes.
`MIN(value, am::max_short)`
=> GTEST/UCT: Consider AM::max_short when setting the length for the send buffer

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h
Fix DC iface flush 
Ep may have lack of EP FC resources preventing it from flushing its pending queue. Therefore iface flush may return success while having some requests in eps pending queues.
This partially reverts #3419. Need to find a corresponding solution for DCI rand policy (or disable FC with rand policy)
=> UCT/DC: Fix possible OOO in iface flush

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_net.c, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_wakeup.cc, test/gtest/ucs/test_sock.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
This patch expands TCP CM adding CM message exchange between peers when a connection is established. The messages exchange has the following sequence:
0. The connection is established
1. The client sends a CM connection request including IFACE address:port information to the peer
2. The server receives the CM connection request from the client, saves the IFACE address:port information about the peer 
3. The server sends a CM connection acknowledgment to the peer -> `EP::conn_state = CONNECTED`
4. The client receives the CM connection acknowledgment from the peer -> `EP::conn_state = CONNECTED`
Note: Client - a connection initiator, Server - a connection acceptor
This infrastructure will be used to identify on server (client) side before acknowledging (requesting) a new connection. 
The CM …
=> UCT/TCP: Implement CM messages exchange between peers

src/ucs/sys/compiler.h
Simplify comment in src/ucs/sys/compiler.h for ucs_unaligned_ptr()
Old comment references armclang for platform where first seen (I suspect?).  Since this also required  elsewhere, remove that part of comment.
N/A
=> UCS: Comment on ucs_unaligned_ptr() macro references armclang: remove since usage seen elsewhere (e.g. x86_64)

src/ucs/Makefile.am, src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, test/gtest/Makefile.am, test/gtest/ucs/test_event_set.cc
This PR is aim for porting OpenUCX to macOS.
This PR a request for review design API.
macOS doesn't exist `epoll` function. Instead, it needs to use `kqueue`.
I'm seperating epoll codes into `ucs/sys/event_set.{c,h}`.
@yosefe Could you review this?
=> UCS/API event_set

test/gtest/uct/test_tag.cc
Do not set `SYNC_RATIO` in tag tests, because it does not exist anymore
=> GTEST/UCT: Minor tag test fix

src/uct/base/uct_iface.h, src/uct/tcp/tcp_ep.c
1. Fixes common `uct_iface_invoke_am` function
2. Add useful printout in case of `assert` is evaluated to `false`
3. Remove the excessive check for AM id in TCP
Fixes possible crash/data corruption
Move using the AM id down (i.e. after `assert` for AM id)
=> UCT: Don't use AM id before checking it

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpContext.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/ucx/jucx/UcpListenerTest.java, bindings/java/src/test/java/org/ucx/jucx/UcpWorkerTest.java
Add fabric methods to create worker, endpoint, listener.
To make API less verbose and sync with [python api](https://github.com/Akshay-Venkatesh/ucx-py/blob/devel/doc/code-organization.md)
=> JUCX: [minor] add fabric methods.

src/ucp/core/ucp_context.c, src/uct/Makefile.am, src/uct/tcp/sockcm/sockcm_def.h, src/uct/tcp/sockcm/sockcm_ep.c, src/uct/tcp/sockcm/sockcm_ep.h, src/uct/tcp/sockcm/sockcm_iface.c, src/uct/tcp/sockcm/sockcm_iface.h, src/uct/tcp/sockcm/sockcm_md.c, src/uct/tcp/sockcm/sockcm_md.h
Adds UCT skeleton connection management logic using socket
_For systems that want to use server client feature in UCX without RDMACM_
_Actual implementation in followup PR. Had to change name from tcpcm->sockcm because transport and memory domain wasn't being picked up because of presence of tcp uct/md and use of strncpy in the library_
cc @yosefe @shamisp @dmitrygladkov @evgeny-leksikov
=> UCT/sockcm: Socket-based connection management skeleton

bindings/java/src/main/java/org/ucx/jucx/NativeLibs.java
Fixes NullPointerError when JUCX is used as a dependency library.
`ucxFolder.listFiles()` doesn't work when it's inside jar archive. When we run tests it's in build folder on FS, so it works there. https://stackoverflow.com/a/20073154
=> JUCX: fix unpack UCT libs.

configure.ac, contrib/configure-devel, src/ucp/Makefile.am, src/ucp/core/ucp_context.c, src/ucp/core/ucp_resource.h, src/uct/ib/Makefile.am, src/uct/ib/base/ib_alloc.h, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/mlx5/ib_mlx5_dv.h, src/uct/ib/rc/accel/rc_mlx5_common.c, test/gtest/uct/ib/test_ib_md.cc, test/gtest/uct/ib/test_ib_xfer.cc, test/gtest/uct/test_p2p_mix.cc, test/gtest/uct/test_p2p_mix.h, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
- Add support for installing devel headers by --enable-devel-headers configure flag
- Add function to UCP to query UCT memory domains
- Add IB memory domain function to allocate device memory
- Any registration on device memory address will find the internal device memory object and use it for registration.
=> UCT/IB/TEST: Add Support for device memory allocation

src/uct/cuda/cuda_copy/cuda_copy_ep.c
For HOST to DEVICE transfers, the final destination buffer may not updated with blocking cudaMemcpy() API if the source host buffer is not pinned (https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior__memcpy-sync)
=> UCT/CUDA_COPY: Use cudaMemcpyAsync API for put short

src/uct/sm/self/self.c, src/uct/sm/self/self.h
This PR adds explicit inheritance of base iface config in UCT/SELF
Setting `UCX_MAX_BCOPY`/`UCX_ALLOC`/`UCX_FAILURE` doesn't have any effect for UCT/SELF's config attributes.
e.g. `UCX_MAX_BCOPY=16k ucx_info -afc` produces the following
- w/o the fix:
```
#
#
#
UCX_SELF_MAX_BCOPY=8K
```
- w/ the fix
```
#
#
#
UCX_SELF_MAX_BCOPY=16K
```
1. Implement new structure to represent SELF config - `uct_self_iface_config_t`
2. Use `uct_iface_config_t` implicitly through `uct_self_iface_config_t` instead
=> UCT/SELF: Inherit base iface config

src/ucp/core/ucp_am.c, src/ucp/core/ucp_am.h
Fixing compiling issue due to alignment.
So the active messages will compile on Fedora. This is the same issue addressed in  https://github.com/openucx/ucx/pull/3308/files 
Adding ucs_unaligned_ptr() to the short active message header.
=> UCP/AM: Fixing Compilation issue on Fedora system.

test/gtest/ucs/test_event_set.cc
This PR fixes the following compile error in Ubuntu and gcc
```
CXX      ucs/gtest-test_event_set.o
ucs/test_event_set.cc: In static member function ‘static void* test_event_set::event_set_read_func(void*)’:
ucs/test_event_set.cc:25:14: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
write(fd[1], evfd_data, strlen(test_event_set::evfd_data));
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Due to this error, tranvis-ci couldn't compile the code.
=> UCS/SYS/TEST add return value check for fixing compile error.

src/ucm/malloc/malloc_hook.c, src/ucm/util/log.c, src/ucs/debug/log.c, src/ucs/profile/profile_defs.h, src/ucs/sys/sys.c
This PR use `HOST_NAME_MAX` value instead of fixed value `40`.
Some host uses a long hostname.
The value is longer than 40byte.
@shamisp was commented me about this fix in the mailing list.
https://elist.ornl.gov/pipermail/ucx-group/2019-May/000901.html
I'm worrying that the comment part of this PR is longer than 80 columns.
Please let me know how to fix it (code style) If I need to modify it.
I got the following error in Travis-CI.
```
[ RUN      ] test_profile.accum
[1557713507.276473]
[travis-job-163edf4a-5d93-41a0-8ea7-d67dcb38c452:17120:0]
profile.c:296  UCX  INFO  profiling is enabled
ucs/test_profile.cc:91: Failure
Value of: std::string(hdr->hostname)
Actual: "travis-job-163edf4a-5d93-41a0-8ea7-d67d"
Expected: std::string(ucs_get_host_name())
Which is: …
```
=> Use HOST_NAME_MAX instead of fixed value.

bindings/java/pom.xml.in, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorkerParams.java
JUCX: Suppress javadoc warnings.
To reduce jenkins log size.
=> JUCX: suppress javadoc warnings.

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c
Improve IO error handling
This is needed for TCP #3547 
Implemented `ucs_socket_io_err_info_t` structure that is passed to error handling callback
=> UCS/SYS: Improve IO error handling

src/ucs/config/parser.c, test/gtest/ucs/test_config.cc
Fix the name of an alias.
This prints wrong the name for aliases that has not only `UCX_` prefix.
Currently, it prints only `UCX_` prefix for all aliases, for example:
- good (real example for UCP context config):
`UCX_MAX_EAGER_LANES` alias for `UCX_MAX_EAGER_RAILS` real name
- bad (fictional example, but it is reproduced for PR that is under development):
`UCX_MAX_BCOPY` alias for `UCX_MM_SEG_SIZE` real name, but it has to be `UCX_MM_MAX_BCOPY`
Pass the list of prefixes to the alias search routine and fill it. When a prefix is found, build the alias prefix string.
=> UCS/CONFIG: Fix the name of alias

src/ucs/sys/math.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, test/gtest/ucs/test_sock.cc
1. Adds `ucs_sockaddr_cmp`
2. `ucs_sockaddr_is_equal` uses `ucs_sockaddr_cmp` under the hood
3. Refactor tests for is_equal and cmp routines
`ucs_sockaddr_cmp` will be used by TCP to compare socket addresses and determine how is lower to resolve simultaneous connection establishment situation.
The `ucs_sockaddr_cmp` is almost the same as `ucs_sockaddr_is_equal` was. It compares in_addr/in6_addr using `memcmp()` and returns signum of the value; ports are compared using `<`.
=> UCS/SYS: Add ucs_sockaddr_cmp needed for TCP

src/ucp/core/ucp_ep.c
Initialize tag_lane with UCP_NULL_LANE to provide correct iface attributes of underlying (next) EP if HW TM is disabled
=> UCP/WIREUP: initialize tag_lane with UCP_NULL_LANE

src/ucs/config/parser.h, src/uct/sm/base/sm_iface.c, src/uct/sm/base/sm_iface.h, src/uct/sm/cma/cma_ep.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/cma/cma_iface.h, src/uct/sm/knem/knem_ep.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/knem/knem_iface.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h
Add environment variable, controlling effective memory BW (which is now defined as a constant for every SM transport)
memory BW may vary depending on different factors. Need to have an ability to adjust it, so that UCP can select the most optimal transport
=> UCT/SM: Add env var controlling memory bandwidth

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/worker.cc
UCP worker wait functionality.
To avoid burning CPU when events are rare (for example on metadata node in SparkRDMA).
=> JUCX: worker wait functionality.

contrib/test_jenkins.sh, test/gtest/common/main.cc, test/gtest/common/test.h, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h
1. Add the infrastructure to report the TOP-N longest tests from the gtest environment
2. Use this infrastructure from Jenkins to report TOP-20 longest tests
This is needed to always be aware of the longest tests and use for the development purposes
Collect the name from `UnitTest::TestCase::TestInfo` and the testing time from `UnitTest::TestCase::TestInfo::TestResut`, store them in the vector, sort the vector na dreport TOP-N longest tests.
=> GTEST: Add test analysis at the end of testing

src/ucs/config/parser.c
Fix the name of documentation width
Must have `UCS_` prefix instead of `UCP_`
`UCP_` -> `UCS_`
=> UCS/CONFIG: Fix the name of documentation width

src/ucp/core/ucp_worker.c, src/ucs/config/parser.c, src/ucs/config/parser.h, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucs/test_config.cc
Add tests for unused env vars functionality
To safely continue further development/maintenance that touches related code 
1. Move `warn_once` flag to the caller's code (i.e. UCP's code)
2. Add UCX environment cleanup class that:
- ctor: `unsetenv` all UCX env vars
- dtor: restore all UCX env vars
3. Add the tests
=> UCS/CONFIG: Add tests for unused env vars functionality

src/ucs/sys/sock.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c
Don't use `errno` name for the function argument
Fixes the bug in the UCS/SYS that leads to the crash when IO error handling is invoked (an `errno` argument is expanded to `__errno_location=0x68`):
```
#0  0x0000000000000068 in ?? ()
#1  0x00007ffff78590d9 in uct_tcp_ep_io_err_handler_cb (arg=0x1531e60, __errno_location=0x68) at tcp/tcp_ep.c:580
#2  0x00007ffff7ad1d7b in ucs_socket_do_io_nb (fd=30, data=0x1818140, length_p=0x7fffffffd090, io_func=0x7ffff678ea20 <recv>, name=0x7ffff7b80b80 "recv", err_cb=0x7ffff7859097 <uct_tcp_ep_io_err_handler_cb>, err_cb_arg=0x1531e60)
at sys/sock.c:206
#3  0x00007ffff7ad1f5f in ucs_socket_recv_nb (fd=30, data=0x1818140, length_p=0x7fffffffd090, err_cb=0x7ffff7859097 <uct_tcp_ep_io_err_handler_cb>, err_cb_arg=0x1531e60) at sys/sock.c:249
```
Rename …
=> UCS/SYS: Don't use errno for the function argument

test/gtest/Makefile.am
By default use warn log level for gtests 
To avoid ep config traces in Jenkins testing
=> GTEST: Reduce gtest log level to warn

src/ucs/sys/compiler_def.h
Added `@param`s
Fix the comment inside `@return`
Fix the comment for `ucs_field_sizeof`
=> UCS/COMPILER: Fix the comment

src/uct/ib/base/ib_md.c
=> UCT/IB: Don't fail if no devices are found; return an empty list

test/gtest/ucp/test_ucp_memheap.cc, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_rma.cc, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/uct/test_md.cc, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_p2p_err.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/uct_p2p_test.cc
Reduces the number of iterations (or the size of messages) for some tests when running under valgrind
Reduces testing time under valgrind
Use `ucs::test_time_multiplier()`
=> GTEST/UCP: Adjust the number of iterations when running under valgrind

src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, test/gtest/ucs/test_event_set.cc
* Extend ucs_event_set_wait API for passing handler extra arguments.
* Add `ucs_` prefix to event_set_handler_t for keep naming consistency.
As discussed #3610. It requires to extend event_set API for using it in `ucs/async/thread.c`.
=> UCS/SYS/TEST: Extend event set abstraction

test/gtest/uct/test_peer_failure.cc
1. Add handling of ud_mlx5 TL name in peer failure test to set the correct name for accelerated UD
2. Improve error handling for this test
Fixes #3634 
1. `if (has_transport("ud"))` -> `if (has_ud())`
2. Added error report if the config parameter was set, but it wasn't found during getting the velue set for this config parameter.
=> GTEST/UCT: Add ud_mlx5 TL name handling in peer failure test

src/uct/ib/cm/configure.m4, ucx.spec.in
Fix requirement for with_ib_cm
Fedora30 and newer deprecated `libibcm-devel` package.
=> RPM/CONFIG: fix requirement for ib_cm

src/ucp/core/ucp_context.c, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/cm/cm_iface.c, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_iface.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/self/self.c, src/uct/sm/self/self.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/uct/test_many2one_am.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
Replace `MAX_BCOPY` by `SEG_SIZE` attribute that is set directly to tranpsort's segment size
`MAX_BCOPY` is not needed anymore
Remove `MAX_BCOPY` and `TM_MAX_BCOPY` attributes and replace them by `SEG_SIZE`
=> UCT: replace MAX_BCOPY by SEG_SIZE attribute

src/uct/ib/cm/configure.m4, ucx.spec.in
Fix requirement for with_ib_cm
Fedora30 and newer deprecated `libibcm-devel` package.
Cherry-picks from https://github.com/openucx/ucx/pull/3585
=> RPM/CONFIG: fix requirement for ib_cm — v1.6

NEWS
=> NEWS: news update before v1.6.0 rc1

src/tools/info/tl_info.c, src/tools/perf/lib/libperf.c, src/ucp/core/ucp_context.c, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_rkey.c, src/uct/api/uct.h, src/uct/base/uct_md.c, test/examples/uct_hello_world.c, test/gtest/uct/test_md.cc, test/gtest/uct/test_mem.cc, test/gtest/uct/uct_test.cc
The goal is to avoid going over all MD components in uct_rkey_unpack() and compare the md name
=> UCT/API: Add 'component' parameter to md_open and rkey functions

Makefile.am
Add java sources to distribution
To be able to compile java from the distribution package. Fixes #3651
=> JUCX: include java sources to distribution

test/examples/ucp_client_server.c
Fix ucp_client_server example
1) ucp_stream_recv_nb can return ucs_ok, it hasn't been handled before
2) added flag to ucp_stream_recv_nb to be sure that all the data was received
=> TEST/EXAMPLES: ucp_stream_recv_nb can return UCS_OK

NEWS, src/ucs/config/parser.c, test/gtest/ucs/test_config.cc
Fix the name of an alias.
This prints wrong the name for aliases that has not only `UCX_` prefix.
Currently, it prints only `UCX_` prefix for all aliases, for example:
- good (real example for UCP context config):
`UCX_MAX_EAGER_LANES` alias for `UCX_MAX_EAGER_RAILS` real name
- bad (fictional example, but it is reproduced for PR that is under development):
`UCX_MAX_BCOPY` alias for `UCX_MM_SEG_SIZE` real name, but it has to be `UCX_MM_MAX_BCOPY`
Pass the list of prefixes to the alias search routine and fill it. When a prefix is found, build the alias prefix string.
this ports #3566
=> UCS/CONFIG: Fix the name of alias - v1.6

src/ucp/core/ucp_ep.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, test/gtest/ucp/test_ucp_tag_offload.cc
Moves sending of `UCP_WIREUP_MSG_ACK` from an async thread (e.g. UD's `uct_ud_iface_timer` that progress data) to `ucp_worker_progress` function.
Fixes #3642
Also, it prevents the calling of UCT AM routines from different threads at the same time
Register the function that sends `UCP_WIREUP_MSG_ACK` in UCT worker.
=> UCP/WIREUP: Fix data race

NEWS, configure.ac, contrib/test_jenkins.sh, src/ucp/rma/amo_sw.c, src/ucp/rma/rma.inl, src/ucp/rma/rma_sw.c, src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/sys/sys.c, src/uct/ib/base/ib_iface.c, src/uct/ib/dc/base/dc_iface.c, test/apps/Makefile.am, test/apps/test_dlopen_cfg_print.c, ucx.spec.in
Fixing multiple issues for redhat per https://bugzilla.redhat.com/show_bug.cgi?id=1715129
- Static checker: memory pool allocation falures, redundant code, ucx_info alias print
- Fixing segfault reported by Fedora when OpenMPI is compiled with UCX
=> Multiple fixes for UCX v1.5.2

ucx.spec.in
Disable ibcm on RHEL7+ by default.
There is no `libibcm.so` for RHEL7.
=> SPEC/RPM: disable ibcm on RHEL7+ by default

src/uct/ib/rdmacm/rdmacm_iface.c
=> UCT/IFACE/SOCKADDR/RDMACM: handle errno=EADDRNOTAVAIL (v1.6.x)

ucx.spec.in
cherry picked from commit 7a1d24e5ace46875cb9d90d194010251cdb31ff2, PR: #3666 
Disable ibcm on RHEL7+ by default.
There is no `libibcm.so` for RHEL7.
=> SPEC/RPM: disable ibcm on RHEL7+ by default — v1.6.x

Makefile.am
JUCX: include java sources to distribution
To be able to build java from release taball. Port to 1.6
=> JUCX: include java sources to distribution - v1.6.x

src/uct/ib/base/ib_iface.c, test/gtest/Makefile.am, test/gtest/common/test_helpers.h, test/gtest/uct/ib/test_ib.cc, test/gtest/uct/ib/test_ib.h, test/gtest/uct/ib/test_ib_pkey.cc
Implement fallback to the first available pkey table idx when the default pkey isn't found
Covers the system that doesn't have `0x7fff` (the default pkey) configured.
1. added `uct_ib_iface_find_pkey` that lookups pkey table idx fopr given pkey
2. `uct_ib_iface_init_pkey` was updated to find the pkey table idx for the UCT's `ib_config::pkey`
- if it is not found, find the first available pkey table idx with full membership
=> UCT/IB: Implement fallback to the first available pkey table idx when the default pkey isn't found

NEWS, contrib/test_jenkins.sh, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/rdmacm/rdmacm_md.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h, test/gtest/uct/ib/test_ud.cc, test/gtest/uct/ib/test_ud_pending.cc, test/gtest/uct/ib/test_ud_slow_timer.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
- use regular SKB entry to send UD ACK messages
(instead of inline SKB record) in case if max_inline
is not enough
- fixed asserts
- fixed iface attr values on zero max_inline
=> UD/RC VERBS: added support of max_inline==0 - v1.5

NEWS, src/ucp/core/ucp_ep.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, test/gtest/ucp/test_ucp_tag_offload.cc
Moves sending of `UCP_WIREUP_MSG_ACK` from an async thread (e.g. UD's `uct_ud_iface_timer` that progress data) to `ucp_worker_progress` function.
Fixes #3642
Also, it prevents the calling of UCT AM routines from different threads at the same time
Register the function that sends `UCP_WIREUP_MSG_ACK` in UCT worker.
back-port of #3654
=> UCP/WIREUP: Fix data race - v1.6

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
Pushes notifications of send (aka memcpy) completion to `ucp_worker` efd. 
Allow blocking progress for `cuda_ipc` UCT. UCXpy needs this in order to leverage NVLINK
Borrows sockets-way logic of pushing send completion events
- While this PR and capability works when `UCP_WAKEUP_FEATURE` alone is requested, `cuda_ipc` gets dropped when an ep which uses it is created with _SERVER-CLIENT_ of connection.
- Adding `ERROR_HANDLING_MODE` flag trivially to iface flags doesn't solve this issue.
cc @bureddy @shamisp @yosefe
=> UCT/CUDA_IPC: event notification support

bindings/java/src/main/native/context.cc
Fix overriding register buffer.
When we register memory we create new ByteBuffer that shares the same memory as the original one. But for original refcount doesn't keep, so java may think it's no need anymore and reuse it or free it.
=> JUCX: fix overriding register buffer.

src/tools/profile/read_profile.c, src/ucs/profile/profile.c
1) Use debug log level for profile enabling message
2) Extend space for func names in `ucx_read_profile`
1) info should be used for important info, need to use it carefully (log is full of profiling messages when profile on scale)
2) Align profile output
Before:
```
uct_iface_mp_chunk_release        17.142            51          3          uct_mem.c:363  uct_iface_mp_chunk_release()
ucp_tag_recv_nb         2.049            49         24         tag_recv.c:180  ucp_tag_recv_nb()
ucp_rndv_progress_rma_get_zcopy         2.925            32         11             rndv.c:305  ucp_rndv_progress_rma_get_zcopy()
ucp_rndv_get_completion         1.959            22         11             rndv.c:440  ucp_rndv_get_completion()
```
After
```
uct_iface_mp_chunk_release        17.142            51 …
```
=> UCS/TOOLS: Minor profiling fixes

Makefile.am
To include java sources no matter whether `make dist` was configured `--with-java` or not.
Fixes #3701
=> JUCX: include java sources for release.

src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h
Add configuration parameter for IB/UD slow timer tick
Address TODO in the code + ports changes from #3603
Read the user passed value and convert to `ucs_time_t`
=> UCT/IB/UD: Add configurable slow timer tick

src/ucm/event/event.c, src/ucm/event/event.h, src/ucm/mmap/install.c, test/gtest/ucm/malloc_hook.cc
- there were issue in ucm_event_test call: it could false
positive detect missing or over-called events
- re-implemented function using event-by-event check
- added gtests
backport from https://github.com/openucx/ucx/pull/3647, https://github.com/openucx/ucx/pull/3674 and https://github.com/openucx/ucx/pull/3690
=> UCM/EVENT: fixed ucp_test_event call - v1.6

src/uct/ib/dc/dc_mlx5_ep.h, test/gtest/uct/ib/test_dc.cc
Fix dci leak
Got this assert when used relatively small TX CQ
```
dc_mlx5_ep.c:243  Assertion `uct_dc_mlx5_iface_dci_has_outstanding(iface, (ep)->dci)' failed: iface (0x7e1970) ep (0x849070) dci leak detected: dci=7
```
If DCI is allocated, but no CQ resources available, dci may not be released quite long time (until something is sent on this ep).
=> UCT/DC: Fix possible dci leak with dcs policy

src/ucs/debug/log.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Implement deferred setting of relatively small UD EP timeout (`3 sec`, instead of default one - `5 min`) for Wireup/Aux UCT/UD EP and for data UCT/UD EPs.
Fixes #3627, #3630, #3577, #3364, #3679
UCT/UD EP peer timeout for sender's UCP EP is set directly from UCP test code after initialization (e.g. wireup for RC transports or UD EP early peer failure detection - when puts some `send_nb()`s on a sender) done.
=> GTEST/UCP: Improve stability of peer failure tests

src/tools/info/tl_info.c, src/tools/perf/lib/libperf.c, src/ucp/core/ucp_context.c, src/uct/api/uct.h, src/uct/base/uct_md.c, test/examples/uct_hello_world.c, test/gtest/uct/test_md.cc, test/gtest/uct/test_mem.cc, test/gtest/uct/uct_test.cc
Instead of searching component by MD name, just pass the component handle
=> UCT/API: Replace md_name by component handle in uct_md_config_read()

src/ucs/sys/event_set.c, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Use new event_set API in `uct/tcp`
Portability for using OpenUCX in macOS.
See also #3682
=> UCT/TCP: uct/tcp use event_set API

NEWS, src/ucm/event/event.c, src/ucm/mmap/install.c, src/ucm/mmap/mmap.h, test/examples/ucp_client_server.c, test/gtest/ucm/malloc_hook.cc
=> Port fixes to v1.6.x: UCM events test, client/server example

contrib/test_jenkins.sh
Increase UD timeout for `ucp_hello_world -e` test
Make `ucp_hello_world -e` test more stable
i.e. this fixing the following errors happened from time to time (e.g. on `boo31` jenkins node):
```
19:12:48 + ./ucp_hello_world -e -n boo31 -p 10002
19:12:48 INFO: UCP_HELLO_WORLD mode = 0 server = boo31 port = 10002
19:13:50 UCX_NET_DEVICES=all
19:13:50 UCX_SHM_DEVICES=all
19:13:50 UCX_ACC_DEVICES=all
19:13:50 UCX_SELF_DEVICES=all
19:13:50 UCX_TLS=all
19:13:50 UCX_ALLOC_PRIO=md:sysv,md:posix,huge,thp,md:*,mmap,heap
19:13:50 UCX_SOCKADDR_TLS_PRIORITY=rdmacm,*
19:13:50 UCX_SOCKADDR_AUX_TLS=ud,ud_x
19:13:50 UCX_WARN_INVALID_CONFIG=y
19:13:50 UCX_BCOPY_THRESH=0
19:13:50 UCX_RNDV_THRESH=auto
19:13:50 UCX_RNDV_SEND_NBR_THRESH=256K
19:13:50 UCX_RNDV_THRESH_FALLBACK=inf
19:13:50 …
```
=> JENKINS: Increase UD timeout to make ucp_hello_world stable

configure.ac, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.h, test/gtest/uct/ib/test_ud.cc, test/gtest/uct/ib/test_ud_slow_timer.cc
The enable/disable logic was busted in quite a few places.
It "almost" work with the exception that the --disable didn't
really work. Since all the options are disabled by default, we didn't
notice this.
=> CONFIG: Fixing broken configure logic

test/gtest/ucm/malloc_hook.cc
fixes https://github.com/openucx/ucx/issues/3734
=> GTEST: disabled new_delete test on valgrind

contrib/test_jenkins.sh, src/uct/tcp/tcp_ep.c
Silence build warning 
build system reported on `r-vmb-ppc-jenkins` node:
```
tcp/tcp_ep.c: In function ‘uct_tcp_ep_am_short’:
tcp/tcp_ep.c:735:32: error: ‘hdr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
memcpy((uint8_t*)(hdr + 1) + sizeof(header), payload, length);
^
tcp/tcp_ep.c: In function ‘uct_tcp_ep_am_bcopy’:
tcp/tcp_ep.c:764:43: error: ‘hdr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
hdr->length = payload_length = pack_cb(hdr + 1, arg);
^
cc1: all warnings being treated as errors
make[2]: *** [tcp/libuct_la-tcp_ep.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/hpc/local/benchmarks/hpcx_future_install_2019-06-22/src/hpcx_future-gcc-redhat7.4/ucx-master/src/uct'
make[1]: *** …
```
=> UCT/TCP: Silence build warning (incorrect)

src/uct/ib/ud/base/ud_ep.c, test/gtest/ucp/test_ucp_peer_failure.cc
1. Improves logging for UD timeout
2. Connect stable EPs to each other before testing to avoid EP timeout between them
1. Improve debugging, because we change UD timeout from test code
2. to avoid errors like:
```
[ RUN      ] shm_ib/test_ucp_peer_failure.bcopy_multi/1
[     INFO ] < ep 0x29fff70: timeout of 3.08 sec (timeout - 3.00 sec) >
[     INFO ] < ep 0x29fed60: timeout of 3.31 sec (timeout - 3.00 sec) >
[     INFO ] < failed to send wireup: Endpoint timeout >
[1561011694.122564] [boo31:17685:0]      ucp_test.cc:198  UCX  ERROR operation returned error: Endpoint timeout
[1561012018.837039] [boo31:17685:1]          ud_ep.c:164  UCX  ERROR ep 0x7fdc50001200: timeout of 324.85 sec (timeout - 300.00 sec)
```
1. Add UD timeout printing along with diff time
2. Call `smoke_test(true);` at …
=> GTEST/UCP: Connect stable pair to avoid EP timeouts on it

test/gtest/uct/ib/test_ib.cc, test/gtest/uct/ib/test_ib.h, test/gtest/uct/ib/test_ib_pkey.cc
Split IB tests into subclasses with the name `test_uct_ib_*`, where `*`:
- lmc
- gid_idx
- addr
Fixes #3745
Fixes bugs come with #3639
Add `test_uct_ib::ib_init()` and `test_uct_ib::ib_cleanup()` that are responsible to initialize IB to perfrom some checks before UCT/IB are executed (e.g. available pkey or GID index). If a check is unsuccesful, a test is skipped
=> GTEST/UCT/IB: Split IB tests into subclasses

src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.h
Check for CQ resources just once in DC communication routines. Do not use `UCT_RC_CHECK_CQE`, as it does RC only related stuff.
Move `UCT_RC_MLX5_CHECK_RES_PTR` from common RC/DC file, because it is used by RC only
Checking CQ and TX desc resources separately allows to avoid ~2ns penalty.  
Looks like no need to eliminate RC only related moderation handling in `uct_rc_txqp_posted`, because it does not have any perf impact.
=> UCT/DC: Check CQ resources just once

contrib/test_jenkins.sh
specify the path for coredump java files to analyze.
To be able to figure out an issue in #3737
=> JUCX: specify path for error file.

bindings/java/src/main/native/Makefile.am
Reduces messages in job log, like:
```
[INFO] Downloading: https://repo.maven.apache.org/maven2/commons-chain/commons-chain/1.1/commons-chain-1.1.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar (1201 KB at 337.1 KB/sec)
```
To make jenkins job log cleaner.
https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output
=> JUCX: reduce maven messages

src/ucp/core/ucp_ep.c
This PR adds calculation of Zcopy thresholds for MDs w/o `UCT_MD_FLAG_NEED_MEMH` flag set
This enables support of Zcopy protocol on UCP level for transports that don't require memory registration for local memory access (e.g. TCP)
Changed the condition for skipping Zcopy
from
`!((iface_attr::cap::flags & zcopy_flag) && (md_attr::cap::flags && UCT_MD_FLAG_REG))`
to
`(!(iface_attr::cap::flags & zcopy_flag) || ((md_attr::cap::flags & UCT_MD_FLAG_NEED_MEMH) && !(md_attr::cap::flags & UCT_MD_FLAG_REG)))`
=> UCP/EP: Calculate Zcopy thresholds for MDs w/o local memory handle requirements

src/uct/tcp/tcp_ep.c
Simplifies receive wrapper in UCT/TCP
There is no need to pass `recv_length` by address, the caller isn't interested in real received size through this variable.
Change from
```
static inline unsigned uct_tcp_ep_recv(uct_tcp_ep_t *ep, size_t *recv_length)
```
to
```
static inline unsigned uct_tcp_ep_recv(uct_tcp_ep_t *ep, size_t recv_length)
```
=> UCT/TCP: Simplify receive wrapper

test/gtest/uct/ib/test_ib.cc
Fix bug - GID index is valid when raw gid representation isn't empty
Fixes #3789
Wrong check was introduced in #3717
Invert result from `uct_ib_device_is_gid_raw_empty`
=> GTEST/UCT/IB: GID index is invalid if gid.raw is empty

src/uct/ib/dc/dc_mlx5_ep.h
Fixes gcc warning
`txqp` is set, but never used if statistics are not enabled
```
Error: CLANG_WARNING:
ucx-1.7.0/src/uct/ib/dc/dc_mlx5.c:8: included_from: Included from here.
ucx-1.7.0/src/uct/ib/dc/dc_mlx5_ep.h:450:13: warning: Value stored to 'txqp' is never read
ucx-1.7.0/src/uct/ib/dc/dc_mlx5_ep.h:450:13: note: Value stored to 'txqp' is never read
```
Use `iface->tx.dcis[ep->dci].txqp.stats` directly
=> UCT/IB/DC: Fix gcc warning

src/tools/info/tl_info.c
Fix clang warnings
Fixes the following warnings:
```
Error: CLANG_WARNING:
ucx-1.7.0/src/tools/info/tl_info.c:248:41: warning: Potential buffer overflow. Replace with 'sizeof(buf) - strlen(buf) - 1' or use a safer 'strlcat' API
ucx-1.7.0/src/tools/info/tl_info.c:248:41: note: Potential buffer overflow. Replace with 'sizeof(buf) - strlen(buf) - 1' or use a safer 'strlcat' API
Error: CLANG_WARNING:
ucx-1.7.0/src/tools/info/tl_info.c:251:44: warning: Potential buffer overflow. Replace with 'sizeof(buf) - strlen(buf) - 1' or use a safer 'strlcat' API
ucx-1.7.0/src/tools/info/tl_info.c:251:44: note: Potential buffer overflow. Replace with 'sizeof(buf) - strlen(buf) - 1' or use a safer 'strlcat' API
Error: CLANG_WARNING:
ucx-1.7.0/src/tools/info/tl_info.c:255:35: warning: Potential buffer …
```
=> TOOLS/INFO: Fix clang warnings

.gitignore
Add some files to `.gitignore` file
To show fewer files when running `git status`
Add to `.gitignore` the following files:
1. etags default filename - `TAGS`
2. autogenerated xml, tex and script files
3. binary files
=> Add some files to .gitignore

src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, src/ucs/sys/math.h, src/uct/tcp/tcp_iface.c, test/gtest/ucs/test_event_set.cc
This PR refactors UCS/SYS/EVENT_SET API in order to match requirements of UCT/TCP (requires `max_events`) and UCS/ASYNC/THREAD (requires `max_events` and `timeout`) needs.
This is needed to have 1 API for reading I/O events for different use cases: UCT/TCP and UCS/ASYNC/THREAD.
Introduced `ucs_sys_event_set_event_t` strucutre that represents I/O events (epoll_event, kevent or etc). When new I/O procedures will be added (for portability to FreeBSD and macOS), it should look like:
```
#if HAVE_EPOLL
typedef struct epoll_event ucs_sys_event_set_t;
#elif HAVE_KQUEUE
typedef struct kevent ucs_sys_event_set_t;
#endif
```
`ucs_event_set_wait` accepts new parameters:
- an array of `ucs_sys_event_set_t` elemnts
- a number of `ucs_sys_event_set_t` elements, timeot (in milliseconds) …
=>  UCS/SYS: Refactor ucs_event_set_wait API to accept timer/max_events

src/uct/base/uct_component.c
Fix clang warning
The clang warning is incorrect, because if a program reaches 2nd and/or 3rd code blocks under `if` statements, it is guaranteed that the 1st condition is true.
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -DCPU_FLAGS= -I/builddir/build/BUILD/ucx-1.7.0/src -I/builddir/build/BUILD/ucx-1.7.0 -I/builddir/build/BUILD/ucx-1.7.0/src -O3 -g -Wall -Werror -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c sm/mm/base/mm_iface.c  -fPIC -DPIC -o sm/mm/base/.libs/libuct_la-mm_iface.o …
```
=> UCT/BASE: Fix clang warning (incorrect)

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/ib/test_cq_moderation.cc, test/gtest/uct/ib/test_rc.cc
Change config so that tx cq moderation is only shown for relevant transports (rc)
DC and CM do not support moderation, UD uses static value. 
`ucx_info -c | grep TX_CQ_MOD` output before:
```
$ucx_info -c | grep TX_CQ_MOD
UCX_RC_VERBS_TX_CQ_MODERATION=64
UCX_RC_MLX5_TX_CQ_MODERATION=64
UCX_DC_VERBS_TX_CQ_MODERATION=64
UCX_DC_MLX5_TX_CQ_MODERATION=64
UCX_UD_VERBS_TX_CQ_MODERATION=64
UCX_UD_MLX5_TX_CQ_MODERATION=64
UCX_CM_TX_CQ_MODERATION=64
```
`ucx_info -c | grep TX_CQ_MOD` output after:
```
UCX_RC_VERBS_TX_CQ_MODERATION=64
UCX_RC_MLX5_TX_CQ_MODERATION=64
```
=> UCT/IB: Expose tx cq moderation for RC transports only

src/ucs/sys/stubs.h
Fix one of the compilation errors on FreeBSD, because FreeBSD system headers are more strict in namespace pollution avoidance.
To continue merging of the FreeBSD compilation patches.
=> UCS/SYS: ssize_t is defined in sys/types.h.

test/gtest/uct/test_md.cc, test/gtest/uct/test_md.h, test/gtest/uct/uct_p2p_test.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
Makes gtest pass on machine with AMD GPU
related to (but NOT fixing) #3722
=> TEST/UCT: If cannot allocate a memory type, skip instead of fail

src/ucp/core/ucp_ep.inl
Remove always true condition
csmock suite has a warning about this part of code:
```
Error: CONSTANT_EXPRESSION_RESULT (CWE-569):
ucx-1.6.0/src/ucp/core/ucp_ep.inl:196: result_independent_of_operands: "ep->flags & UCP_EP_FLAG_FLUSH_STATE_VALID" is always 0 regardless of the values of its operands. This occurs as the logical operand of "!".
Error: CONSTANT_EXPRESSION_RESULT (CWE-569):
ucx-1.6.0/src/ucp/core/ucp_ep.inl:200: extra_high_bits: In "ep->flags |= UCP_EP_FLAG_FLUSH_STATE_VALID", wider "UCP_EP_FLAG_FLUSH_STATE_VALID" has high-order bits (0x400000) that don't affect the narrower left-hand side.
```
Just remove check + add an assertion
=> UCP/EP: Remove always true condition

src/ucp/core/ucp_worker.c
Fixes dead code in case of single-thread code
csmock suite found:
```
Error: DEADCODE (CWE-561):
ucx-1.6.0/src/ucp/core/ucp_worker.c:1387: assignment: Assigning: "thread_mode" = "UCS_THREAD_MODE_SINGLE".
ucx-1.6.0/src/ucp/core/ucp_worker.c:1395: assignment: Assigning: "thread_mode" = "UCS_THREAD_MODE_SINGLE".
ucx-1.6.0/src/ucp/core/ucp_worker.c:1398: const: At condition "thread_mode == UCS_THREAD_MODE_MULTI", the value of "thread_mode" must be equal to 0.
ucx-1.6.0/src/ucp/core/ucp_worker.c:1398: dead_error_condition: The condition "thread_mode == UCS_THREAD_MODE_MULTI" cannot be true.
ucx-1.6.0/src/ucp/core/ucp_worker.c:1399: dead_error_line: Execution cannot reach this statement: "worker->flags = UCP_WORKER_...".
Error: DEADCODE (CWE-561):
ucx-1.6.0/src/ucp/core/ucp_worker.c:1387: …
```
=> UCP/WORKER: Fix dead code in case of single-thread code

src/ucm/event/event.c, src/ucs/type/init_once.h, test/gtest/ucs/test_type.cc
Add `double_unlock` suppression to `UCS_INIT_ONCE` macro
Covers all places where `UCS_INIT_ONCE` is called:
```
Error: LOCK (CWE-765):
ucx-1.6.0/src/ucm/event/event.c:486: unlock: "pthread_mutex_unlock" unlocks "init_once.lock".
ucx-1.6.0/src/ucm/event/event.c:486: double_unlock: "pthread_mutex_unlock" unlocks "init_once.lock" while it is unlocked.
```
```
Error: LOCK (CWE-765):
ucx-1.6.0/src/ucs/sys/module.c:111: unlock: "pthread_mutex_unlock" unlocks "ucs_module_loader_state.init.lock".
ucx-1.6.0/src/ucs/sys/module.c:111: double_unlock: "pthread_mutex_unlock" unlocks "ucs_module_loader_state.init.lock" while it is unlocked.
```
Add a comment `/* coverity[double_unlock] */` before `for {}` loop in `UCS_INIT_ONCE` macro
=> UCS/TYPE: Add double_unlock suppression to UCS_INIT_ONCE macro

src/ucp/wireup/address.c, src/uct/sm/mm/base/mm_iface.c
Suppress cppcheck warning
```
Error: CPPCHECK_WARNING:
ucx-1.7.0/src/uct/sm/mm/base/mm_iface.c:505: error[internalAstError]: Syntax Error: AST broken, binary operator '=' doesn't have two operands.
```
```
Error: CPPCHECK_WARNING:
ucx-1.7.0/src/ucp/wireup/address.c:538: error[internalAstError]: Syntax Error: AST broken, binary operator '==' doesn't have two operands.
```
Add comment `cppcheck-suppress internalAstError`
=> UCP, UCT: Suppress cppcheck warning

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h
Suppress coverity warning about overrunning a 16-element array using `255` index
```
Error: OVERRUN (CWE-119):
ucx-1.6.0/src/uct/ib/dc/dc_mlx5_ep.c:996: cond_const: Checking "ep->dci == 255" implies that "ep->dci" is 255 on the true branch.
ucx-1.6.0/src/uct/ib/dc/dc_mlx5_ep.c:1013: overrun-call: Overrunning callee's array of size 16 by passing argument "ep->dci" (which evaluates to 255) in call to "uct_dc_mlx5_ep_rand_arb_group".
```
Add a comment that suppresses Coverity warning:
`/* coverity[overrun-call] */`
=> UCT/IB/DC: Suppress coverity warning

src/ucs/debug/memtrack.c
Removes lock-unlock from cleanup
1. Other UCS functionalities don't acquire/release locks in `ucs_init` and `ucs_cleanup`
2. Fixes coverity issue - `ORDER_REVERSAL`
- `ucs_stats_node_remove()` acquires `pthread_mutex_lock(&ucs_stats_context.lock` and then acquires `ucs_stats_context_t.lock` inside `ucs_stats_get_class()`
- `ucs_memtrack_cleanup()` acquires `pthread_mutex_lock(&ucs_memtrack_context.lock)` and then acquires `ucs_stats_context_t.lock` inside `ucs_stats_node_free()`
Removes `pthread_mutex_lock(&ucs_memtrack_context.lock)` and `pthread_mutex_unlock(&ucs_memtrack_context.lock)` in `ucs_memtrack_cleanup`
=> UCS/DEBUG: Remove lock-unlock memtrack's mutex from cleanup

test/gtest/uct/test_flush.cc, test/gtest/uct/test_p2p_err.cc, test/gtest/uct/test_uct_ep.cc
Prepare test infrastructure for TCP AM Zcopy
Fixes test to pass with TCP after AM Zcopy will be enabled
from #3782 
1. Adding missed UCT `progress()` for connection establishment
2. Limit the number of iterations for `test_uct_ep.disconnect_after_send`
3. Increase message sizes in `test_ucp_tag_probe.limited_probe_size` to be able fully consume receive buffer
=> GTEST/UCT: Prepare test infra for TCP AM Zcopy

bindings/java/src/main/native/Makefile.am
JUCX: remove maven for clean step.
To be able to run `make clean` on nodes without maven
cc @alinask
=> JUCX: remove maven for clean step.

src/ucs/stats/stats.h
Fixes coverity warning(Deadcode) in case of UCS statistics are not defined
```
Error: DEADCODE (CWE-561):
ucx-1.6.0/src/ucp/core/ucp_worker.c:1443: assignment: Assigning: "status" = "UCS_OK".
ucx-1.6.0/src/ucp/core/ucp_worker.c:1445: const: At condition "status != UCS_OK", the value of "status" must be equal to 0.
ucx-1.6.0/src/ucp/core/ucp_worker.c:1445: dead_error_condition: The condition "status != UCS_OK" cannot be true.
ucx-1.6.0/src/ucp/core/ucp_worker.c:1446: dead_error_line: Execution cannot reach this statement: "goto err_free;".
```
```
ucx-1.6.0/src/uct/ib/rc/accel/rc_mlx5_iface.c:427: assignment: Assigning: "status" = "UCS_OK".
ucx-1.6.0/src/uct/ib/rc/accel/rc_mlx5_iface.c:429: const: At condition "status != UCS_OK", the value of "status" must be equal to 0. …
```
=> UCS/STATS: Fix coverity warning

contrib/test_jenkins.sh
Speed-up testing on several hosts
=> TEST/JENKINS: Don't run valgrind tests if JENKINS_NO_VALGRIND is set

src/ucs/datastruct/queue.h
Fix cppcheck warnings
Performance evaluation of this patch was done using OpenMPI/PML/UCX and OSU MB (`osu_latency` and `osu_mbw_mr`) - it shows same or (sometimes) slightly better performance (`osu_latency` sometimes gives `- ~10-20 nanoseconds`, `osu_mbw_mr` - `+ 1k-2k messages`)
1)
```
Error: CPPCHECK_WARNING (CWE-682):
ucx-1.7.0/src/ucp/tag/offload.c:369: error[nullPointerArithmetic]: Overflow in pointer arithmetic, NULL pointer is subtracted.
```
2) 
```
Error: CLANG_WARNING:
ucx-1.7.0/src/ucp/wireup/wireup_ep.c:90:5: warning: The left operand of '-' is a garbage value
ucx-1.7.0/src/ucs/datastruct/queue.h:229:17: note: expanded from macro 'ucs_queue_for_each_extract'
ucx-1.7.0/src/ucs/sys/compiler_def.h:120:38: note: expanded from macro 'ucs_container_of' …
```
=> UCS/QUEUE: Fix cppcheck & clang warnings

test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h, test/gtest/uct/ib/test_ud.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
Removed unused `wnd` parameter from `uct_test::send_am_message`
Fix rc test to use `send_am_messages`, as was the intention
=> GTEST/UCT: Fix params of send_am_message

src/tools/profile/read_profile.c, src/ucs/datastruct/khash.h
Suppresses clang false-positive warnings
```
Error: CLANG_WARNING:
ucx-1.7.0/src/tools/profile/read_profile.c:195:1: warning: Array access (via field 'flags') results in a null pointer dereference
#KHASH_MAP_INIT_INT64(request_ids, int)
#^
ucx-1.7.0/src/ucs/datastruct/khash.h:656:2: note: expanded from macro 'KHASH_MAP_INIT_INT64'
ucx-1.7.0/src/ucs/datastruct/khash.h:380:2: note: expanded from macro 'KHASH_INIT'
ucx-1.7.0/src/ucs/datastruct/khash.h:377:2: note: expanded from macro 'KHASH_INIT2'
ucx-1.7.0/src/ucs/datastruct/khash.h:336:21: note: expanded from macro '__KHASH_IMPL'
ucx-1.7.0/src/tools/profile/read_profile.c:231:9: note: Assuming 'scope_ends' is not equal to NULL
ucx-1.7.0/src/tools/profile/read_profile.c:231:5: note: Taking false branch …
```
=> TOOLS/PROFILE: Suppress clang false-positive warnings

test/examples/uct_hello_world.c
Register local memory handle only if `md_attr.md_attr.cap.flags` requires it (i.e. `UCT_MD_FLAG_NEED_MEMH` set)
To fix error in `uct_hello_world -z ...` with TCP transport
1. Query MD attributes.
2. Check whether we should register a communication buffer to get local memory handle.
3. Do AM Zcopy send.
=> TEST/EXAMPLES: Fix AM Zcopy proto usage in uct_hello_world

test/gtest/uct/test_tag.cc
Fix test_tag, which was accidentally disabled in #3816
=> GTEST/UCT/TAG: Fix test_tag initialization

src/tools/perf/perftest.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_request.h, src/ucs/Makefile.am, src/ucs/debug/assert.h, src/ucs/type/init_once.c, src/ucs/type/init_once.h, src/uct/base/uct_worker.c, src/uct/ib/base/ib_iface.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/base/rc_iface.h
Fixes Coverity warnings that appear in a release mode
Fixes ~20 Coverity warnings
1. Makes `ucs_assert` not empty in a release mode if static analyzers (Coverity or/and Clang) are used
2. Fixes `goto` labels usage
3. Improves loop return condition to make analyzers happy
=> UCS, UCT, UCP: Fix Coverity warnings

src/ucp/wireup/ep_match.c, src/ucs/datastruct/queue.h
Fix cppcheck & clang warnings
1. UCP/WIREUP: fix for NULL subtraction found by cppcheck
2. UCS: fix possible NULL dereference found by clang
Now csmock passes w/o any warnings
1. Refactor EP match list `foreach` macro to stop the loop when reaches `NULL` (w/o casting to `ucp_ep_ext_gen_t` type)
2. Add `ucs_assert` to suppress clang warning
=> UCP, UCS: Fix cppcheck & clang warnings

test/examples/ucp_hello_world.c, test/examples/uct_hello_world.c, test/examples/ucx_hello_world.h
Some tests fails because of what appears to be partial receive
So ensure a full receive, and in any case of failure, print the return value
=> TEST/EXAMPLES: Fix socket operations - use MSG_WAITALL and print result

src/uct/api/tl.h, src/uct/api/uct.h, src/uct/api/uct_def.h
Adding a new API for client-server in UCT.
Sockaddr transports should be opened on an entity that isn't an iface, that depends on an md (that represents a single device), since a sockaddr tl's md currently isn't really opened on a device (as opposed to other transports). This PR 'breaks' this direct connection between a sockaddr transport and an md.
This is also done in order to prepare for the addition of a close protocol to UCX.
Introducing a new entity - CM - communication manager, through which UCT level listeners and endpoints will be created. 
Adding new UCT level callbacks as well to handle a disconnection of client-server peers.
=> UCT/API: A new client-server API in UCT with a connection manager.

src/ucp/core/ucp_worker.c, src/ucs/async/thread.c, src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, src/ucs/sys/sys.h
Use new `event_set` API in `ucs/async/thread.c`
Portability for using OpenUCX in macOS.
I'll appreciate if someone tell me modification direction.
Revised [ [Q] How to modify ucs/async/thread.c for using new	event_set API?](https://elist.ornl.gov/pipermail/ucx-group/2019-May/000897.html) in the Mailing list
I created the new API event_set for using kqueue/epoll with the same API. (https://github.com/openucx/ucx/pull/3426)
I've got started to modify `ucs/async/thread.c` for using event_set API 
instead of `epoll`.
And I have two issues.
1. How to call `ucs_async_pipe_drain(&thread->wakeup)` in event handler?
2. How to change `is_missed` flag in event_handler?
We introduced new event API(`ucs_event_set_wait`) for waiting for events,
It calls event handler when file descriptor has changed. …
=> ucs/async/thread.c use event_set API 

src/ucs/type/class.c, src/ucs/type/class.h
Suppress false-positive Coverity warning
Coverity reports that it's possible that `status != UCS_OK`, but `obj_p` contains a pointer to some memory block
Now all Coverity warnings are fixed. Will enable running Coverity w/o `--security` and `--concurrency` options for UCX release build in the next PR
Suppress Coverity warning by adding `ucs_assert()`
=> UCS/CLASS: Suppress Coverity warning (false-positive)

test/gtest/uct/test_p2p_am.cc
`uct_p2p_am_tx_bufs.am_tx_max_bufs` test is skipped over TCP:
```
[==========] Running 4 tests from 1 test case.
[----------] 4 tests from tcp/uct_p2p_am_tx_bufs
[ RUN      ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/0
[     SKIP ] (Test does not apply to the current transport)
[       OK ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/0 (1 ms)
[ RUN      ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/1
[     SKIP ] (Test does not apply to the current transport)
[       OK ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/1 (0 ms)
[ RUN      ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/2
[     SKIP ] (Test does not apply to the current transport)
[       OK ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/2 (1 ms)
[ RUN      ] tcp/uct_p2p_am_tx_bufs.am_tx_max_bufs/3
[     SKIP ] (Test …
```
=> GTEST/UCT: Don't skip tests for TCP

src/ucs/sys/event_set.c, src/ucs/sys/event_set.h
Move `#include <sys/epoll.h>` into `event_set.c` file
For minimizing depndency.
=> UCS/SYS: Move epoll.h into event_set.c file for minimizing depndency.

test/gtest/common/test.h
Pass empty skip reason to MT test macro
Add missed `""` skip reason for MT macros
Call `UCS_TEST_P_` w/ `""`
=> GTEST: Pass empty skip reason to MT test macro

src/ucm/event/event.h, src/ucm/mmap/install.c, test/gtest/ucm/malloc_hook.cc
fixes https://github.com/openucx/ucx/issues/3831
=> UCM: added madvise into VM_UNMAP events group

test/gtest/uct/ib/test_ib.cc
In some configurations, non-default GID index cannot be used on the
device. Skip the test if it's not possible to create a "loopback"
address handle by ibv_crate_ah() on that device and GID index.
Fixes #3787
=> TEST/IB: Skip non-default GID test if AH cannot be created

src/ucm/event/event.h, src/ucm/mmap/install.c, test/gtest/ucm/malloc_hook.cc
- added gtest for missed madvise event
- added test for madvise call
backport from https://github.com/openucx/ucx/pull/3836
(cherry picked from commit 51a14c3eb88232185805753b2dc982c10d18edc4)
Conflicts:
test/gtest/ucm/malloc_hook.cc
=> UCM: added madvise into VM_UNMAP events group - v1.6

bindings/java/checkstyle.xml, bindings/java/pom.xml.in, bindings/java/src/main/java/org/ucx/jucx/UcxRequest.java, bindings/java/src/main/java/org/ucx/jucx/UcxUtils.java, bindings/java/src/main/java/org/ucx/jucx/examples/UcxReadBWBenchmarkReceiver.java, bindings/java/src/main/java/org/ucx/jucx/examples/UcxReadBWBenchmarkSender.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/ucx/jucx/UcpListenerTest.java
Change JUCX native API to accept native address + size.
- To be able to use memory pooling. Pre-allocate and reuse buffers of a bigger size.
- To be able to mimic scatter-gather (e.g. allocate a contiguous buffer of size of 100 bytes and send 2 ucp_get requests by 50 bytes).
- To avoid the copy of Rkey to intermediate buffer.
- To work with [Byte buffers > 2GB](http://nyeggen.com/post/2014-05-18-memory-mapping-%3E2gb-of-data-in-java/)
For ByteBuffer operations use `ByteBuffer.position()` and `ByteBuffer.remaining()` to extract offset and size. Add additional methods to accept address and size parameters.
=> JUCX: change API to support address, offset and size.

bindings/java/src/main/native/jucx_common_def.cc
Fixing unused variable warning (treated as error) when configured without debug
Fixes ` ./contrib/buildrpm.sh -t -s -b` reported by @amaslenn 
```
jucx_common_def.cc: In function ‘JNIEnv* get_jni_env()’:
jucx_common_def.cc:134:10: error: unused variable ‘rs’ [-Werror=unused-variable]
```
=> JUCX: fix unused variable error.

ucx.spec.in
Enable debuginfo rpms generation on SUSE.
Debuginfo rpm are useful and we already have it for RHEL since it is generated by default.
=> RPM: updates for SUSE

src/ucs/async/thread.c
Use the same approach as we have before #3610
- fix `EINVAL` from epoll_wait when we provide `num_events=0` in case of a signal received
- return back the previous behavior
Check return value of `ucs_event_set_wait`
if this is error status, call `ucs_fatal`, check timers and do new iteration
=> UCS/ASYNC: Don't spin when event_set return INPROGRESS

src/uct/api/uct.h
Update uct_ep_am_zcopy documentation
the `uct_ep_am_zcopy`description is not complete
Added in the description for `uct_ep_am_zcopy`:
```
@return UCS_OK              Operation completed successfully.
```
```
@return UCS_ERR_NO_RESOURCE Could not start the operation now due to lack
of send resources.
```
```
@note If the operation returns @a UCS_INPROGRESS, the memory buffers pointed
to by @a iov array must not be modified until the operation is completed
by @a comp. @a header can be released or changed
```
=> UCT/API: Update uct_ep_am_zcopy description

src/ucp/core/ucp_worker.c
Remove locking from ucp_worker_wait.
When using separate "progress thread" like:
```
while(1) {
if (ucp_worker_progress(worker) == 0) {
ucp_worker_wait(worker);
}
}
```
`ucp_worker_wait` acquires a lock on the worker, thus prevents to use other operations that that may need a lock on the worker (`ucp_listener_create`, etc). 
`ucp_worker_arm`  and `poll` are thread-safe. Though calling `ucp_worker_wait` from multiple threads may have unpredictable behavior for **threads 2,...** (e.g. one thread will wake up, while others won't). So **at least one thread** will wake up.
=> UCP: remove locking from ucp_worker_wait.

src/ucp/core/ucp_worker.c, src/ucs/async/async_fwd.h, src/ucs/async/thread.c, src/uct/ib/base/ib_device.c, src/uct/ib/cm/cm_iface.c, src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/udt/ugni_udt_iface.c, test/gtest/ucs/test_async.cc
Use UCS/EVENT_SET events instead of POLLIN/POLLERR in UCT transports:
- IB/BASE
- IB/CM
- IB/RDMACM
- TCP
- UGNI
and UCP/WORKER
1. Direct mapping events (w/o conversion from `POLL*` to `UCS_EVENT_SET_EV*`)
2. Adoption for future kqueue support in Event Set for BSD
=> UCP, UCT, UCS: Use UCS/EVENT_SET events instead of poll events

src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, test/gtest/ucs/test_event_set.cc
This PR does the following:
1. refactor UCS/EVENT_SET gtests
2. introduces edge-triggered mode needed for UCP/WORKER
1. reduce code duplication
2. UCP/WORKER needs an edge-triggered mode
=> UCS/SYS: Introduce edge-triggered mode + refactor tests

test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/ucp/test_ucp_wakeup.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucs/test_async.cc, test/gtest/ucs/test_datatype.cc, test/gtest/ucs/test_debug.cc, test/gtest/ucs/test_memtype_cache.cc, test/gtest/ucs/test_pgtable.cc, test/gtest/ucs/test_time.cc, test/gtest/ucs/test_twheel.cc
Skip some UCP and UCS tests before `init()` called
Speedups test skipping
Move skip condition to `UCS_TEST_SKIP_COND_*()` macro from test body
=> UCP, UCS: Use SKIP_COND test macro to skip tests

contrib/test_jenkins.sh, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, test/gtest/ucs/test_event_set.cc
Use UCS/EVENT_SET in UCP/WORKER
Remove dependency on `epoll`
=> UCP/CORE, UCS/SYS: Use event set in UCP worker

src/ucs/datastruct/khash.h
Use `TAB`s instead of spaces
Align with khash's code style
Use `TAB`s instead of spaces where calling `kassert()`
=> UCS/DATASTRUCT: Fix khash's code style

src/tools/info/proto_info.c, src/tools/info/ucx_info.c, src/tools/info/ucx_info.h, src/ucp/api/ucp.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h
- ppn hint can be used for more accurate intra-node transport select
- added new values into config datatypes and basic processing
=> UCP/CONTEXT: added PPN runtime parameter

src/uct/base/uct_iface.c
Add asserts for deprecated `MAX_BCOPY`
Missed asserts for `MAX_BCOPY` as we have for `MAX_SHORT`
Use `UCS_CONFIG_TYPE_DEPRECATED` instead of `UCS_CONFIG_TYPE_MEMUNITS`
=> UCT/BASE: Add asserts for deprecated variable

src/ucs/async/async.h, src/ucs/async/async_fwd.h, src/uct/tcp/tcp.h
Remove `epoll` keyword from comments. Fix #3900 
We eliminate epoll function in files. Fix comments properly.
Could you review @dmitrygx ?
=> UCS, UCT: Remove epoll keyword from comments.

src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c
Send `ACK` along with `WAIT_REQ` if EP is waiting for ACK
Fixes #3784 and #3769 
Need to send `ACK + WAIT_REQ` when EP is in a `WAITING_ACK` state, since there is a chance that a peer didn't receive `REQ` event or `accept()` TCP connection yet. If this is case and the peer does `AM send` and right after completion of the send operation closes EP, such code hangs on `AM send` from a receiver
When EP receives `ACK + WAIT_REQ`, it moves to itself to `WAITING_REG` state and can't send any data before `REQ` isn't received for that EP - after that, it moves itself to `CONNECTED` state (Note: if `ACK + WAIT_REQ` was received after `REQ` is handled, it just skipped and handled as `ACK` event - i.e. moves itself to `CONNECTED` state)
Reproducer …
=> UCT/TCP: Send ACK along with WAIT_REQ if EP is waiting for ACK

test/gtest/Makefile.am, test/gtest/ucp/test_ucp_am.cc
Signed-off-by: John Snyder <jms285@duke.edu>
This will probably not pass tests until the other PR with the implementation is used for the test.
Gtest to test several aspects of the UCP active message layer.
To test whether the active messages are working in general and on different transports.
=> UCP/GTEST adding ucp_am gtest

src/ucs/async/async.h, src/ucs/async/async_fwd.h, src/uct/tcp/tcp.h
UCS, UCT: Remove `epoll` keyword from comments.(revised #3901)
After merged #3901, @tonycurtis commented that PR.
https://github.com/openucx/ucx/pull/3901#issuecomment-513262804
@tonycurtis , Thank you for that comment. And could you review this?
=> UCS, UCT: Remove epoll keyword from comments.(revised #3901)

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_net.c, test/gtest/common/main.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_probe.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/uct/test_many2one_am.cc
The PR adds the following:
- `TX_SEG_SIZE` and `RX_SEG_SIZE` instead of `SEG_SIZE` to support large buffer size on a receiver side needed for implementing optimal AM Zcopy protocol (can send up to `RX_SEG_SIZE` using AM Zcopy) in TCP - #3782 
- Correct MTU value used for AM operations alignment
This is needed for performance improvements implemented in #3782 
- Updates in TCP iface config table
- Extend `uct_tcp_netif_caps()` function to repport MTU value
=> UCT/TCP: Add TX/RX_SEG_SIZE and report correct MTU used for alignment

src/uct/tcp/tcp_iface.c
Allow TCP iface connection listener be bound to a port that's in `TIME_WAIT` state
```
[ RUN      ] tcp/test_uct_event_fd.am/0
tcp_iface.c:327  UCX  ERROR bind(fd=19) failed: Address already in use
Error: Input/output error
```
The error above may happen when there is a pretty small interval between two runs of test with TCP transport, since there were no enough time to move a port used by iface's listener from `TIME_WAIT` state to `INIT` after the socket bound to the port was `close()`ed
Set `SO_REUSEDADDR` option on a listener socket before `bind()`ing it to a given `addr:port` pair
=> UCT/TCP: Allow iface listener be bound to a port that's in TIME_WAIT state

test/gtest/uct/ib/test_dc.cc
The test uses put_zcopy, need to check  corresponding caps 
Fix incorrect porting to `UCS_TEST_SKIP_COND_P` (check was removed from common `test_iface_ops`, but DC test was not updated)
=> GTEST/UCT/DC: Fix caps check for stress iface test

src/ucs/sys/sock.c, src/ucs/sys/sock.h
The PR adds:
- IOV socket send function
- getter of maximum IOV count supported by current OS
This is needed for implementing AM Zcopy protocol in UCT/TCP - #3782 
Adds `ucs_socket_sendv_nb` and `ucs_socket_max_iov`
=> UCS/SYS: Implement IOV socket send and get maximum IOV count functions

src/ucs/sys/compiler.h
Signed-off-by: Konstantin Belousov <kib@freebsd.org>
alloca.h is not always available.
Continue pushing FreeBSD patches.
=> UCS/SYS: Handle alloca.h inclusion properly.

src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5_common.c, src/uct/ib/ud/accel/ud_mlx5_common.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/common/test_obj_size.cc
Remove path bits field from ud and rc endpoints
Remove sl field from rc endpoint
They are not used (just duplicating iface value), but rc ep address decreased from 72 to 62 bytes
=> UCT/RC/UD: Remove sl and path bits from ep

test/gtest/uct/ib/test_ud.cc
Enable majority of UD tests for Mellanox HCAs
They were accidentally disabled in 3883b79a 
UD supports "put_shot emulation", but real PUT capability is not exposed
=> GTEST/UCT/UD: Re-enable majority of UD tests

src/ucp/wireup/select.c
Removes always true parameter (`select_best`) that's used for RMA/AMO selection logic
The parameter is always true
1. Remove `ucp_wireup_add_memaccess_lanes` function argument
2. Remove the dead code (i.e. the code that is executed if `select_best = false`).
=> UCP/WIREUP: Remove always true parameter for RMA/AMO selection logic

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
This PR enables AM Zcopy protocol support for UCT/TCP
Performance improvements for large messages
- Introduce `ucs_socket_do_iov_nb`
- Introduce `ucs_socket_max_iov` to get maximum supported IOVs count
- Added Zcopy AM function + some updates for progress in-progress Zcopy TX operations
=> UCT/TCP: Enable AM Zcopy

src/ucs/sys/sys.c
=> UCS/SYS: Implement ucs_get_tid() and ucs_tgkill() using FreeBSD tids.

src/ucs/debug/debug.c, src/ucs/debug/log.c, src/ucs/memory/rcache.c, src/ucs/memory/rcache_int.h, src/ucs/time/timerq.c, src/ucs/time/timerq.h
Use `ucs_spinlock` instead of `pthread_spinlock` for minimizing depndency.
Please see also #3928. This PR change UCS parts.
I want to minimize `ptread_spinlock` dependency because macOS doesn't have `pthread_spinlock`.
=> UCS: Use ucs_spinlock instead of pthread_spinlock.

src/tools/info/sys_info.c, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.c, src/ucs/arch/x86_64/cpu.h
- in case if non-intel cpu is detected - then disable memcpy_relaxed by default
this PR is partially copied from https://github.com/openucx/ucx/pull/3889, could be conflicts
=> UCS/ARCH: added cpu vendor call

src/ucp/core/ucp_am.c, src/ucp/core/ucp_context.c
Adding feature flag check for Active Messages
To give a more informative error message when the correct feature flags are set instead of just a segmentation fault. In response to issue #3950 .
=> UCP/AM/Context: Adding flag check for UCP_FEATURE_AM

src/ucp/wireup/address.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h
Unify UCP EP address packing logic based in IFACE capabilities with lanes selection logic.
Continue #3933 in scope of #3946
=> UCP/WIREUP/ADDRESS: unify connect to EP or IFACE selection logic

src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/sys/string.h
Add support for infinite value for ULUNITS type
This is needed for #3944 (to define infinite MAX_NUM_EPS in all transports except RC)
Handle `UCS_ULUNITS_INF` (`SIZE_MAX`) value + updates for help message
=> UCS/CONFIG: Add support for infinite value for ULUNITS type

src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/ib/base/ib_iface.c, src/uct/ib/cm/cm_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/rocm/copy/rocm_copy_iface.c, src/uct/rocm/gdr/rocm_gdr_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/self/self.c, src/uct/tcp/sockcm/sockcm_iface.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c
Introduce `iface_attr::max_num_eps` configurable parameter
This is needed to implement UCP scoring for fallback on more salable transports when running on large scale
1. Introduce new config value `MAX_NUM_EPS`
2. API change in `uct_iface_attr_t` - new field `max_num_eps`
3. By default this is `INF`, RC overrides it to `256`
=> UCT: Introduce iface_attr::max_num_eps configurable parameter

bindings/java/src/main/native/context.cc, bindings/java/src/main/native/endpoint.cc, contrib/test_jenkins.sh, src/tools/info/tl_info.c, src/ucp/core/ucp_am.c, src/ucp/wireup/wireup_ep.c, src/ucs/debug/debug.c, src/uct/cuda/gdr_copy/gdr_copy_md.c
Enable running Coverity for UCX release build
It should find new codding errors
Re-use `run_coverity()` function (call it from `build_release_pkg()` to run it with release build)
=> JENKINS: Run Coverity for release build

src/uct/ib/base/ib_device.c
These are devices with Mellanox chips but Bull dev_id.
Adding to uct_ib_builtin_device_specs array so these devices
are recognized.
Adds Bull Atos HCA device IDs into uct_ib_builtin_device_specs[].
So that these devices (which use Mellanox silicon) are recognized as such and so the same optimizations can be applied.
N/A
=> src/uct/ib/base/ib_device.c: adds Bull Atos HCA device IDs

doc/CodeStyle.md
Add macro definition examples + minor fixes
To specify the correct macro definition rule for developers
=> DOC/CODESTYLE: Add macro definition examples

src/uct/sm/mm/base/mm_md.h
Fixes #3987 (confirmed by @lyu)
Issue introduced by #3973 - allocation priority was wrong and shared memory memory was not allocated
=> UCT/MM: Fix redundant stringification in component name

src/ucs/stats/stats.c, src/ucs/type/spinlock.h
Assign a value as `pthread_t` type explicitly.
I got the error below on macOS.
Maybe it's the same on FreeBSD too.
https://github.com/kostikbel/ucx/commit/ad5b58e72e5c2aec404d8c2fc8434e9799c025cf
```
.../openucx/ucx/src/ucs/type/spinlock.h:104:21: error:
incompatible integer to pointer conversion assigning to 'pthread_t' (aka
'struct _opaque_pthread_t *') from 'unsigned long'
[-Werror,-Wint-conversion]
lock->owner = 0xfffffffful;
^ ~~~~~~~~~~~~
```
=> UCS: Fix a compiler error. Cast pthread_t explicitly.

src/ucp/wireup/select.c, src/ucp/wireup/wireup.h, src/ucp/wireup/wireup_ep.c, src/ucs/sys/math.h
Refactor transport selection code
This is needed for #3944 PR (prepare the ground to enable fallback logic based on a `max_num_eps` transport's iface parameter)
1. Added helpers functions for scores comparisons
2. Added `ucp_wireup_select_info_t` structure to use for selected transports
=> UCP/WIREUP: Refactor transport selection

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_listener.h
Store tl_iface instead of wiface_idx lookup on connect request callback
Simplify code, especially for https://github.com/openucx/ucx/pull/3946
=> UCP/WIREUP/SOCKADDR: refactor ucp_conn_request_t

src/uct/cuda/cuda_copy/cuda_copy_md.c
skip cuda_copy registration for cudaMallocHost() returned HOST memory
cudaMallocHost()  returned HOST memory is already registered with CUDA.  It return error if we call cudaHostRegister() on this memory.
=> UCT/CUDA_COPY: Fix cuda_copy registration for cudaMallocHost() memory

src/uct/base/uct_component.c
Use `component` instead of `mdc`
Fix compiler warning
Use `component` instead of `mdc`
=> UCT: Fix compiler error

src/ucs/sys/sock.c
Handle 	UCS_ERR_NO_PROGRESS	 properly in blocking send functions
Fixes #4008 
`0` length mustn't be passed to `ucs_socket_do_io_nb`
```
Mon Aug  5 12:50:21 2019[1,6]<stderr>:[jazz30:22851:0:22851]        sock.c:247  Assertion `*length_p > 0' failed
Mon Aug  5 12:50:21 2019[1,9]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 9:
Mon Aug  5 12:50:21 2019[1,9]<stderr>:ERROR: Got wrong received message 4
Mon Aug  5 12:50:21 2019[1,5]<stderr>:[**ERROR**]: MPI_COMM_WORLD rank 5:
Mon Aug  5 12:50:21 2019[1,5]<stderr>:ERROR: Got wrong received message 4
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 5 in communicator MPI_COMM_WORLD
with errorcode 1.
```
1. Move status checking in a `while (...)`
2. Always update `cur_cnt` to `length - done_cnt`, …
=> UCS/SYS: Handle UCS_ERR_NO_PROGRESS properly in blocking send functions

src/ucp/proto/proto_am.inl
disable zcopy proto for generic datatype
=> UCP/PROTO: Fix mem type support with generic datatype

configure.ac, src/uct/ugni/configure.m4
Backporting autoconf fix to 1.6.x branch.
Problem still exists. 1.6.x is the desired target for MPICH+UCX builds at the moment.
=> remove pkg.m4 dependency for 1.6.x

src/uct/sm/cma/cma_iface.c
Call base iface query to set a correct value for `max_num_eps`
Fixes bugs
`memset` -> `uct_base_iface_query`
=> UCT/SM/CMA: Call base iface query

src/uct/ib/base/ib_device.c
These are devices with Mellanox chips but Bull dev_id.
Adding to uct_ib_builtin_device_specs array so these devices
are recognized.
Same as PR #3620 on master  
https://github.com/openucx/ucx/pull/3620#issuecomment-519000995
=> Add Bull Atos HCA device IDs - v1.6.x

src/ucm/event/event.c, src/ucm/malloc/malloc_hook.c, src/ucs/memory/rcache.c, test/gtest/ucs/test_rcache.cc
Fixes #4016
Issue introduced by #3939
This PR also adds event checks to UCM, so the rcache unit test will fail to create the rcache.
=> UCS/RCACHE/TEST: Fix 'status' variable override in rcache error flow

.gitignore, buildlib/azure-pipelines.yml, buildlib/fedora.Dockerfile
Add build with GCC9 and Clang8 in Fedora30, run `cppcheck` on compile database generated by `bear`.
Check UCX build support on the latest compilers.
=> AZP: Run static checkers

src/uct/sm/mm/xpmem/Makefile.am, src/uct/sm/mm/xpmem/configure.m4
Fixes #4021.
Avoids pkg.m4 dependency in XPMEM build configuration.
Relying on pkg.m4 can complicate the build process.
=> BUILD/XPMEM: Avoid pkg.m4 dependency

src/uct/sm/mm/xpmem/Makefile.am, src/uct/sm/mm/xpmem/configure.m4
=> BUILD/XPMEM: Avoid pkg.m4 dependency - v1.6.x

buildlib/azure-pipelines.md, buildlib/azure-pipelines.yml, buildlib/centos7.Dockerfile, buildlib/fedora.Dockerfile
Enable Azure Pipelines testing in v1.6.x branch. State is copied from not yet merged #3966.
=> AZP: port buildlib/ from master — v1.6

buildlib/azure-pipelines.yml
Enable AZP checks for all release branches and related PRs.
To have all release PRs tested before merge.
=> AZP: enable for all release branch (and related PRs)

src/uct/tcp/tcp_iface.c
Changes behavior of the `is_reachable` function to return always `true`
Fixes #3513 (is_reachable will return `true`, `connect()` should fail if a peer is unreachable)
`uct_iface_is_reachable()` returns true istead
=> UCT/TCP: Always return true from is_reachable function

test/gtest/ucp/test_ucp_wireup.cc
Fix wrong test case name
Have to be "/stream" instead of "/tag"
Set "/stream" instead of "/tag"
=> GTEST/UCP: Fix wrong test case name

src/ucp/rma/rma.h
Use C style comments instead of C++ ones
Align with UCX coding style
`// ...` -> `/* ... */`
=> UCP/RMA: Use C style comments

src/ucp/wireup/select.c
Reenable tag offload support accidentally disabled by #3975
=> UCP/TAG: Fix tag offload lane selection

src/ucs/type/status.h
Fix code alignment + add missing `()` wraping `_status`
Fix possible bug
Add `()` around `_status`
=> UCS/TYPE: Code cleanup in status code

src/ucp/core/ucp_ep.h, src/ucp/rma/rma.inl
prepare ucp_ep_flush_state_t for close protocol
In scope of #3946 
Adding union and new structure to ucp_ep_flush_state_t  definition.
=> UCP/EP/FLUSH: prepare ucp_ep_flush_state_t for close proto

src/ucp/wireup/select.c, src/ucp/wireup/wireup.h, test/gtest/ucp/test_ucp_tag_offload.cc
Test that tag offload lane is created when we have transports supporting it.
To avoid bugs, like the one fixed in #4062.
=> GTEST/UCP: Test tag offload lane selection

src/ucs/sys/sock.c, src/uct/tcp/tcp_ep.c
Print error (+ use `io_errno` instead of `errno`) if an error callback is not set.
Fix bug when a callback is not set
Fix if statement
=> UCS/SOCK: Print error if an error callback is not set

test/gtest/uct/ib/test_sockaddr.cc
=> GTEST: increase timeout for the client-server over CM stress tests.

src/ucs/Makefile.am, src/ucs/sys/iovec.c, src/ucs/sys/iovec.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Implemented IOV send for AM Short over recently added non-blocking vector send function
Improves performance for messages in a range of [2kb, 8kb]
`ucx_perftest -t am_lat -D short` shows 3 usec improvement for messages with 2kb-8kb (*kb is a limit for AM Short/Bcopy operations in TCP) on IB, no performance changes on 1 GbE
1. Add new parameter - `UCX_TCP_MIN_AM_SHORTV=2kb`
2. Send AM Short data using non-blocking vector send function for messages with length > `UCX_TCP_MIN_AM_SHORTV` - this is a zero-copy path in user level
3. Minor code cleanups/improvements + bug-fixing in TCP iface init
=> UCT/TCP: Add IOV send for AM Short

src/ucp/core/ucp_listener.c, src/ucp/core/ucp_listener.h, src/ucp/core/ucp_types.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, test/gtest/ucp/test_ucp_sockaddr.cc
Adds initialization and destroy of ucp_listener object on top of uct_listeners
this PR is in dependency from https://github.com/openucx/ucx/pull/3978
to continue #3946
=> UCP/LISTENER: add CMs initialization and destroy

src/ucp/core/ucp_context.h, src/ucp/wireup/select.c
Introduce selection context
Minor code cleanups
This is needed for #4052 - current scalable tl bitmap will be saved there, also direct access to AM selection info
Init selection context and use it always
=> UCP/WIREUP: Introduce selection context + minor code cleanups

src/uct/tcp/tcp_iface.c
Improve query device routine
To avoid doing `ioctl()` for "." and ".." entries
```
[1566393490.343573] [jazz14:177437:0]           sock.c:51   UCX  DEBUG ioctl(req=35093, ifr_name=.) failed: No such device
[1566393490.343581] [jazz14:177437:0]           sock.c:51   UCX  DEBUG ioctl(req=35093, ifr_name=..) failed: No such device
[1566393490.343603] [jazz14:177437:0]           sock.c:51   UCX  DEBUG ioctl(req=35093, ifr_name=em4) failed: Cannot assign requested address
[1566393490.343610] [jazz14:177437:0]           sock.c:51   UCX  DEBUG ioctl(req=35093, ifr_name=em2) failed: Cannot assign requested address
[1566393490.343614] [jazz14:177437:0]           sock.c:51   UCX  DEBUG ioctl(req=35093, ifr_name=em3) failed: Cannot assign requested address
[1566393490.343619] [jazz14:177437:0] …
```
=> UCT/TCP: Improve query device routine

src/uct/tcp/sockcm/sockcm_def.h, src/uct/tcp/sockcm/sockcm_ep.c, src/uct/tcp/sockcm/sockcm_ep.h, src/uct/tcp/sockcm/sockcm_iface.c, src/uct/tcp/sockcm/sockcm_iface.h, src/uct/tcp/sockcm/sockcm_md.c
Adds sockcm md/iface/ep initialization and teardown. WIll follow this up with #3570 which will add asynchronous handlers and tests.
#3570 is passing tests but PR LOC was over 500 after adding asynchronous event handlers. Hope to get this merged into master before merging #3570 
Note that some of the code added doesn't make sense without event handler implementations but they mostly include enumerations or structures in header files.
@yosefe @alinask @evgeny-leksikov
=> UCT/TCP/SOCKCM: Adding md component, iface/ep init/cleanup fxns

test/gtest/uct/test_zcopy_comp.cc, test/gtest/uct/uct_p2p_test.cc
Add the progressing of local and remote entities when waiting for completion after blocking send done
Fix a hang when a sender needs to wait for some message(s) (e.g. an acknowledgment in #4092) from a peer. But the receiver is unable to send the message, since a test don't call progress on receiver's iface
`sender()::flush()` ->`uct_test:Lflush()`
=> GTEST/UCT/P2P: Progress local and remote entities when doing blocking send

src/uct/base/uct_iface.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.c, src/uct/ugni/udt/ugni_udt_ep.c
- added uct_am_short_fill_data function to unify data copy procedure
for non-accelerated transports
=> UCT/AM-SHORT: code beautify: added common fill short packet function

.gitignore, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java
Flush functionality for ucp_worker and ucp_endpoint.
In SparkUCX there's a need to wait for multiple request completion. This will allow to track just 1 request except of number requests to wait:
```
while (!requests.forall(_.isCompleted)) {
worker.progress();
}
```
to:
```
UcxRequest request = worker.fush(''');
while (!request.isCompleted) {
worker.progress()
}
```
=> JUCX: endpoint and worker flush functionality.

src/uct/sm/self/self.c, src/uct/tcp/tcp_md.c
Add dummy memory registration
To make possible select TCP for RMA_BW lanes when it will support PUT ZCOPY operation
Apply the same approach as SELF did
=> UCT/TCP: Add dummy memory registration

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp_cm.c
Improve status querying for non-blocking connect
`getsockopt()` is not stable to a flow when someone call `recv`/`send`/etc for the same socket fd that changes `errno` before `getsockopt()`
`ucs_socket_connect_nb_get_status()` -> `ucs_socket_is_connected()` that uses `getpeername()` to check whether a connect are done or not
=> UCS/SYS: Improve nb connect status querying

src/uct/base/uct_worker.h, src/uct/ib/mlx5/ib_mlx5.c
backport fixes from master that was added in #3803 PR
v.1.6.x doesn't contain some fixes for Clang warnings
`git cherry-pick` them
=> UCT: backport fixes from master (1.6.x)

src/ucs/async/signal.c
=> UCS/ASYNC: Handle spelling of the tid/thread_id in struct sigevent.

src/ucp/api/ucp.h, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_listener.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/api/uct.h, src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/ib/rdmacm/rdmacm_listener.c, src/uct/tcp/sockcm/sockcm_iface.c, test/examples/ucp_client_server.c, test/gtest/ucp/test_ucp_sockaddr.cc
Use sockaddr_storage (instead of only port) for the ucp and uct listeners attributes.
1. Include more information in the listener's attributes - not only port, as it is now.
2. The uct listener that is used in the new CM flow already has a sockaddr_storage field in its attributes - this PR will align the ucp and 'uct on iface' listener with it.
The ucp and uct listeners attributes, which are returned after their query functions, will have a sockaddr_storage field to hold both the IP and the port on which the listener is listening on.
=> UCP/UCT/API: ucp/uct listener query - use sockaddr in attr

src/ucm/api/ucm.h, src/ucm/bistro/bistro.c, src/ucm/mmap/install.c, src/ucm/util/reloc.c, src/ucm/util/replace.c, src/ucm/util/replace.h, src/ucm/util/sys.c
- removed void* arithmetics (replaced by macro)
- minor code cleaning
- this is part of PGI compiler adaptation
=> UCM: better fit C11 standard

src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/select.c, test/apps/test_ucx_tls.py, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Use UCT maximum number of EPs attribute to implement selection logic
This is intended to implement fallback from transports with low scalability (IB/RC) to highly scalable transports (IB/UD) based on their max_num_eps UCT iface attribute
The problem occurs when a system doesn't have IB/DC transport support (can do RMA/AMO), but have only IB/RC (can do RMA/AMO) and IB/UD (can't do RMA/AMO, only AM transport). So, using already implemented scoring it chooses IB/UD instead of IB/RC for AM lane starting for some big enough est_num_eps value, but RMA/AMO lanes still use IB/RC, since IB/UD doesn't support it.
=> UCP/WIREUP: Implement selection logic based on UCT maximum number of EPs

src/uct/tcp/tcp_md.c
Fix MD attributes query
The bug was introduced when adding TCP MD dummy registration in #4108 
Remove `md_attr::cap::flags` setting to `0`
=> UCT/TCP: Fix MD attributes query

config/m4/compiler.m4, configure.ac, src/ucm/event/event.c, src/ucm/malloc/malloc_hook.c, src/ucm/util/log.h, src/ucs/algorithm/crc.c, src/ucs/arch/cpu.c, src/ucs/async/async.c, src/ucs/async/thread.c, src/ucs/config/parser.c, src/ucs/datastruct/mpool.c, src/ucs/datastruct/strided_alloc.c, src/ucs/debug/debug.c, src/ucs/debug/log.c, src/ucs/debug/memtrack.c, src/ucs/memory/rcache.c, src/ucs/profile/profile.c, src/ucs/stats/client_server.c, src/ucs/stats/serialization.c, src/ucs/stats/stats.c, src/ucs/sys/compiler.h, src/ucs/sys/compiler_def.h, src/ucs/sys/module.c, src/ucs/sys/sys.c
- removed void* arithmetics (replaced by macro)
- minor code cleaning
- this is part of PGI compiler adaptation
=> UCS: better fit C11 standard

src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_wireup.cc
Fix resource iteration in `ucp_wireup_get_reachable_mds`, need to go thru relevant resources map only.  
Fixes #4126
=> UCP: Fix resource iteration in unified mode

src/ucs/sys/iovec.c, src/ucs/sys/iovec.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/sm/base/sm_iface.h, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Merge maximum IOVs getters into a single function
Avoid duplication
Remove `ucs_socket_max_iov` and update `ucs_get_max_iov`
=> UCS/SYS: Merge maximum IOVs getters into a single function

src/ucp/wireup/address.c
Fix printing md_flags when packing address
pack and unpack print a different` md_flags` value:
before:
```
pack addr[0] : rc_mlx5/mlx5_1:1 md_flags 0x1e tl_flags 0xd2548000067f bw 0.000000e+00 + 4.596050e+09/n ovh 4.000000e-08 lat_ovh 1.500000e-06 dev_priority 30 a32 0xf/0x3f a64 0xf/0x3f
unpack addr[0] : md_flags 0x2 tl_flags 0xd2548000067f bw 0.000000e+00 + 4.596050e+09/n ovh 4.000000e-08 lat_ovh 1.500000e-06 dev_priority 30 a32 0x0/0x0 a64 0x0/0x0
```
after:
```
pack addr[0] : rc_mlx5/mlx5_1:1 md_flags 0x2 tl_flags 0xd2548000067f bw 0.000000e+00 + 4.596050e+09/n ovh 4.000000e-08 lat_ovh 1.500000e-06 dev_priority 30 a32 0xf/0x3f a64 0xf/0x3f
unpack addr[0] : md_flags 0x2 tl_flags 0xd2548000067f bw 0.000000e+00 + 4.596050e+09/n ovh 4.000000e-08 lat_ovh 1.500000e-06 dev_priority 30 a32 …
```
=> UCP/WIREUP: Fix printing md_flags when packing address

src/ucp/proto/proto_am.inl, src/ucp/tag/rndv.c
Fix multilane AM Zcopy operation when a last AM Zcopy operation returns UCS_OK while there is(are) in-progress AM Zcopy operation(s) that returned UCS_INPROGRESS on other lane(s).
So, we need to wait until they completed and the last completed operation will complete UCP request
Fixes #4141 
Check UCT completion's counter before complete UCP request when a last AM Zcopy returns UCS_OK
=> UCP/PROTO: Fix multilane AM Zcopy operation

src/ucs/config/parser.c
Suppress Clang warning in parser
Fix Clang warning
Use mpool to allocate memory for hash keys (name of the environment variables)
=> UCS/CONFIG: Suppress Clang warning in parser

buildlib/azure-pipelines.yml, buildlib/fedora.Dockerfile
Enable `csclng` checks in AZP.
Cover RHEL static checks in UCX CI.
=> AZP: enable csclng checks

config/m4/compiler.m4
- in case if nested CHECK_COMPILER_FLAG is used - restore
original CFLAGS before "false" section is called
=> BUILD: fixed nested  CHECK_COMPILER_FLAG macro

src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_rkey.c, src/ucp/stream/stream.h, src/ucs/config/parser.c, src/ucs/debug/debug.c, src/uct/ib/base/ib_iface.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/verbs/rc_verbs_ep.c
Fix Clang warnings in UCP, UCT, UCS (backport from master branch - #4115)
Fixes warnings found during AZP testing in #4112
=> UCP, UCS, UCT: Fix clang warnings (v1.6.x)

src/ucs/profile/profile.c
=> UCS/PROFILE: Add cast from pthread_t to uintmax_t, to avoid warning.

src/uct/ib/base/ib_iface.c
PR fixes RX headroom initialization for IB transports
=> UCT/IB: Fix RX headroom initialization

src/uct/tcp/tcp_ep.c
Remove excessive code
Simplifies code
`UCS_ERR_NO_RESOURCE` error is handled in `uct_tcp_ep_ctx_buf_need_progress()`
Remove `status = UCS_OK;` statement
=> UCT/TCP: Remove excessive code

test/gtest/uct/uct_p2p_test.cc
Progress remote and local entities when waiting for remote comp
Some UCT TLs require (e.g. TCP) to progress remote side due to exchanging by control messages and for receiving a payload
Call `flush()` instead of `sender().flush()`
=> GTEST/UCT/P2P: Progress remote and local entities when waiting for remote comp

config/m4/cuda.m4
Patching cuda.m4 to find the cuda stub libraries if the use points to a specific cuda runtime version.
In a cloud environment I've been working with the build system has installed the cuda runtime, but not the nvidia/cuda hardware drivers. This means that libcudart.so is available, but not libcuda.so.  When this happens, UCX fails to configure with this:
```
$ contrib/configure-devel --with-cuda=/usr/local/cuda-10.1/
...
checking cuda.h usability... yes
checking cuda.h presence... yes
checking for cuda.h... yes
checking cuda_runtime.h usability... yes
checking cuda_runtime.h presence... yes
checking for cuda_runtime.h... yes
checking for cuPointerGetAttribute in -lcuda... no
configure: error: CUDA support is requested but cuda packages cannot be found
```
This environment can be recreated …
=> BUILD: Look for cuda stubs in the stubs/ dir

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java, src/ucp/api/ucp.h
JUCX: get/put nbi functionality.
Needed for the cases when a callback is not needed, to reduce callback overhead.
=> JUCX: get/put nbi functionality.

src/uct/sm/cma/cma_ep.c
Add pid to CMA error message
Would be useful to know pid when get messages like this (when analyzing apps failures):
`cma_ep.c:113  UCX  ERROR process_vm_readv delivered 0 instead of 91389, error message No such process`
=> UCT/CMA: Add pid to error message

src/uct/api/tl.h, src/uct/base/uct_iface.c
Why:
Better fit to C11 standard. PGI compiler adaptation.
What:
typedefs allows to strict cast function pointers into required datatype. C11 standard forbids non-strict cating for non-compatible pointers
How:
Added typedefs for iface ops values for more strict casting
=> UCT/IFACE: added typedefs for iface ops values

src/uct/tcp/tcp_cm.c
Add connect ack sending to pending queue if already connected and unable to send
Fixes #4161 (we have to not mix user and CM data)
If EP is in CONNECTED state and there is user data in progress (i.e. TX buffer length != 0), we should move CM ack sending to pending queue and process it when TX buffer length == 0
=> UCT/TCP: Don't mix user and CM data

config/m4/compiler.m4, configure.ac, contrib/configure-opt, contrib/configure-release, src/uct/sm/knem/Makefile.am, src/uct/sm/knem/configure.m4, test/gtest/ucs/test_debug.cc
CPU architecture optimizations (e.g AVX/SSE4) were not enabled in release builds because `--enable-optimizations` flag for configure did not work. This PR fixes it.
=> CONFIGURE: Fix CPU optimizations m4 macro

test/gtest/ucs/test_profile.cc
Fix an issue reported by Coverity 2018.09
Use `std::vector` to save `pthread_t`s
=> GTEST/UCS/PROFILE: Fix Coverity 2018.09 issue

src/ucm/util/reloc.c, test/gtest/ucm/malloc_hook.cc
- added processing of special case dlopen(NULL) used to
get handle to main program
- added gtest for such case
potentially fixes https://github.com/openucx/ucx/issues/4190
=> UCM/DLOPEN: fixed potential crash on dlopen(NULL)

src/ucm/cuda/cudamem.c, src/uct/cuda/base/cuda_md.c
Sets [SYNC_MEMOPS](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__UNIFIED.html#group__CUDA__UNIFIED_1g89f7ad29a657e574fdea2624b74d138e) attribute on GPU pointer after either 
* detecting as pinned device memory (when `MEMTYPE_CACHE=n`)
* intercepting CUDA allocation call (when `MEMTYPE_CACHE=try/y`)
Data validation issues come up from the following steps:
1. If a host->device transfer is initiated with a blocking cudaMemcpy operation
2. Then tag_send_nb is called (either directly or through MPI)
Then there is a chance that cudaMemcpy blocking operation returns even before data has been placed on device memory. A subsequent ibv_post_send may actually read stale values before sending this out if SYNC_MEMOPS attribute isn't set on the buffer region that is passed to ibv_post_send. …
=> UC(M/T)/CUDA: Set SYNC_MEMOPS ptr attr so NIC reads updated GPU buffers

src/uct/ib/dc/dc_mlx5.c
Fixes description of UCX_DC_MLX5_NUM_DCI  var.
before change:
`Number of DC initiator QPs (DCI) used by the interface (up to UCT_DC_MLX5_IFACE_MAX_DCIS).`
after this change:
`Number of DC initiator QPs (DCI) used by the interface (up to 16).`
=> UCT/DC: Fix UCX_DC_MLX5_NUM_DCI description

src/ucs/async/async.c, src/ucs/datastruct/callbackq.c
Add  `#include "coffig.h"` in some files.
```C
#ifdef HAVE_CONFIG_H
#endif
```
For future development, I need to reference `#define`ed values in `config.h`.
These files are missing #include part.
Some files still missing `#include` part. (For example, `.ucs/time/time.c`). Do we need it it in all files?
=> UCS: Add #include "config.h" to files

src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, test/gtest/uct/ib/test_ud_slow_timer.cc
Fix "SLOW_TIMER_BACKOFF" check
UD back off is slowtimer multiplier, defining it less than 1 makes no sense 
Currently defining it to small values give the following (unclear) fatal error:
`timer_wheel.c:63   Fatal: Timer resolution is too low. Min resolution 25811.101538 usec, wanted 20971.520000 usec`
=> UCT/UD: Fix timer backoff initialization/check

src/uct/tcp/tcp_cm.c
Just return an error in case of  `ucs_socket_connect` failure 
We have to not move EP from `CLOSED` connection state to `CLOSED` state (there is an assertion for that)
Simplify `uct_tcp_cm_conn_start`
=> UCT/TCP: Fix connect error handling

src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Implement switching for non-blocking connection and use blocking connections by default to support large scale runs. Also, print help info about limits that have to be set to support large scale runs
1. Fixes #4183 
2. Fixes #3758 
2. `MPI_Init()` takes ~2x time than non-blocking connect, but overall `startup/osu_init` takes < ~2 times when `--mca mpi_add_procs_cutoff` >= number of ranks (i.e. static connections)
Mark socket as non-blocking after a connection was established if blocking connect is requested
=> UCT/TCP: Use blocking connection establishment

bindings/java/pom.xml.in, contrib/test_jenkins.sh
[Needed maven plugins](https://stackoverflow.com/a/42917618) to perform release to maven central.
JUCX [can be published now](https://issues.sonatype.org/browse/OSSRH-51674) to maven central. This will allows use it as a java dependency for application developers. Need to have several plugins to publish source code, sign artifacts + meet [needed requirements](https://central.sonatype.org/pages/requirements.html) added section about SCM + developers
=> JUCX: maven plugins to release and submit to maven central.

src/ucp/core/ucp_worker.c
Select device atomics if there is a scalable device
Do not mix Device and AMO over AM atomics
Select only scalable enough TL for Device atomics in `ucp_worker_init_device_atomics`
=> UCP/WORKER: Select device atomics if there is a scalable device

src/ucs/sys/sock.c, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_iface.c
Prints `addr:port` information for a connected pair
Improve traceability for TCP connections establishment procedure
1. Implement common `ucs_socket_getname_str()` function that's used for printing local addr:port pair for a given socket fd
2. Use it in `ucs_socket_connect()` and `ucs_socket_is_connected()`
3. Call `ucs_socket_is_connected()` and check for `ECONNABORTED` when `accept()` done
=> UCS/SYS, UCT/TCP: Improve logging

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_listener.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/rma/flush.c, test/gtest/ucp/test_ucp_wireup.cc
1. Fixed worker iface access in ucp_ep_config_calc_params
2. Fixed worker iface creation. Need to pass correct worker iface address to uct_iface_open as an argument of unexpected eager callback
3. Properly close excessive ifaces with worse performance (was broken a while ago) + tests for that
Fixes certain application run scenarios
Maintain array of iface pointers  per worker (rather than array of ifaces itself). Then worker interface pointer remains valid even if some of the interfaces closed (as excessive)
=> UCP: Unified mode fixes

src/ucm/util/replace.c
Use gcc-ism __attribute__((constructor)) when not available.
=> UCM/UTIL: PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP is not portable.

src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.h, src/uct/api/uct_def.h, src/uct/ib/rc/accel/rc_mlx5.inl, test/gtest/uct/test_tag.cc
Add  UCT API required for implementing Multi-Packet XRQ support
MP XRQ is intended to optimize tag offload flow in the following manner:
- Reduce memory consumption, while enabling higher rendezvous thresholds.  
- Optimize sub-middle messages latency by pipelining sending fragments of the message with its handling on the receiver (for unexpected tag offload flow). Should provide up to 20% benefit for 4KB-64KB messages comparing with the current HW TM flow (making it on pair with SW TM)  
With MP XRQ, single message may be delivered in different WQEs and unexpected eager callback will be called for each fragment of the message. Thus it is necessary to introduce some auxiliary data for correct assembling of the message. The PR adds:
1) New flags for unexpected eager callback (to …
=> UCT/API: Multi-packet XRQ for HW TM (API only)

src/ucm/util/replace.c
Clang compiled this code, but gcc apparently is more picky about numbers:
/usr/home/kostik/work/mellanox/openmpi/ucx/contrib/../src/ucm/util/replace.c:32:1: error: constructor priorities from 0 to 100 are reserved for the implementation [-Werror=prio-ctor-dtor]
32 | static void ucm_reloc_get_orig_lock_init(void) __attribute__((constructor(0)));
| ^~~~~~
cc1: all warnings being treated as errors
=> UCM/UTIL: change constructor priority to 101.

test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h
Basic tests for MP XRQ. Not instantiated, because MP code is not upstreamed yet.
=> GTEST/UCT/RCX: Initial tests for MP XRQ

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_listener.c, src/ucp/wireup/wireup_ep.c
rename ucp_wireup_client_data_t -> ucp_wireup_sockaddr_data_t
This structure will be reused in new CM based client-server wireup on both sides, client and server.
This is a part of https://github.com/openucx/ucx/pull/4090/
@alinask
=> UCP/WIREUP/SOCKADDR: rename ucp_wireup_client_data_t

src/ucp/wireup/select.c, src/ucp/wireup/wireup.h
Split ucp_wireup_select_ctx_t on ucp_wireup_select_context_t and
ucp_wireup_select_params_t
to separate in/out parameters in selection logic stack
@dmitrygx
=> UCP/WIREUP/SELECT: refactor ucp_wireup_select_ctx_t

src/uct/tcp/sockcm/sockcm_ep.c
Do not handle endpoint failure twice
partial fix for #4207
=> UCT/SOCKCM/EP: fix error handling

test/gtest/ucs/test_async.cc
Fixes prints in test_async.warn_block
Fixes #4251 
No need to print all leftover warnings from previous tests
=> GTEST/UCS: Fix prints in test_async

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.h
_Adding support for accessing peer devices that are currently masked out by CUDA_VISIBLE_DEVICES_ 
_To allow the use of cuda_ipc in such cases. _
_Replacing cuDeviceCanAccessPeer(...) with a call to cuIpcOpenMemHandle(...) to determine if the peer is accessible.   The opened handle is passed through to the memhandle cache (to avoid having to close and re-open it), and a local cache is now in-place to cache peer accessibility._
=> UCT/CUDA: CUDA_VISIBLE_DEVICES support.

src/ucp/Makefile.am, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_listener.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, src/ucp/wireup/wireup_ep.h
This PR adds sockaddr/cm wireup, part 1
To prepare for adding close protocol
Initiate connect request by calling `ucp_ep_create` on client side
=> UCP/WIREUP/CM: ucp_ep_create, client side

src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_proxy_ep.c, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_worker.c, src/ucp/dt/dt.c, src/ucp/dt/dt_iov.c, src/ucp/proto/proto_am.c, src/ucp/proto/proto_am.inl, src/ucp/rma/amo_send.c, src/ucs/datastruct/strided_alloc.h, src/ucs/debug/log.h
- first portion of UCP related fixes for PGI compiler support
=> portion of UCP related fixes for PGI

config/m4/cuda.m4, src/uct/cuda/cuda_ipc/cuda_ipc_md.c
Check for `cuDeviceGetUuid` presence in libcuda
After merging #4137, a linking issues occurs on hpc-test-node3 (host misconfiguration):
```
13:41:03   CXXLD    gtest
13:41:07 ../../src/uct/cuda/.libs/libuct_cuda.so: undefined reference to `cuDeviceGetUuid'
13:41:07 collect2: error: ld returned 1 exit status
13:41:07 make[3]: *** [gtest] Error 1
13:41:07 make[3]: Leaving directory `/scrap/jenkins/workspace/hpc-ucx-pr-6/label/hpc-test-node-legacy/worker/2/build-test/test/gtest'
13:41:07 make[2]: *** [all-recursive] Error 1
13:41:07 make[2]: Leaving directory `/scrap/jenkins/workspace/hpc-ucx-pr-6/label/hpc-test-node-legacy/worker/2/build-test/test/gtest'
13:41:07 make[1]: *** [all-recursive] Error 1
13:41:07 make[1]: Leaving directory …
```
=> UCT/CUDA: Check for cuDeviceGetUuid presence

bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am
Fixing failing installation when older maven versions are used. Mentioned in #4241 
There's a separate javadoc configuration `<doclint>` that recognized by all maven versions. Also fixed logic of install - need just to copy the jar to `libdir` directory instead of installing to a local repo
=> JUCX: fix installation for old maven versions.

configure.ac
Fixes https://github.com/openucx/ucx/issues/4218
Sets `link_all_deplibs` to `yes` to ensure `libtool` links dependencies.
Without this fix we are unable to build 1.6.0+ as `libucp.so` has symbols it is unable to resolve.
We set this flag in `configure.ac`.
cc @yosefe (I gave you author credit here since this was [your patch]( https://github.com/openucx/ucx/issues/4218#issuecomment-535572106 ). Hope that is ok :)
=> Fix libtool linking error

configure.ac
Fixes https://github.com/openucx/ucx/issues/4218
Backports PR ( https://github.com/openucx/ucx/pull/4279 ) to the `v1.6.x` branch. Questions answered below are direct copies of those answered in that PR.
Sets `link_all_deplibs` to `yes` to ensure `libtool` links dependencies.
Without this fix we are unable to build 1.6.0+ as `libucp.so` has symbols it is unable to resolve.
We set this flag in `configure.ac`.
cc @yosefe
=> Fix libtool linking error (backport to `v1.6.x`)

configure.ac
Fixes https://github.com/openucx/ucx/issues/4218
Backports PR ( https://github.com/openucx/ucx/pull/4279 ) to the `v1.7.x` branch. Questions answered below are direct copies of those answered in that PR
Sets `link_all_deplibs` to `yes` to ensure `libtool` links dependencies.
Without this fix we are unable to build 1.6.0+ as `libucp.so` has symbols it is unable to resolve.
We set this flag in `configure.ac`.
cc @yosefe
=> Fix libtool linking error (backport to `v1.7.x`)

test/gtest/common/test.cc, test/gtest/ucs/test_async.cc
Clear warnings vector during test init (for obsolete warnings do not pop up in other tests)
=> GTEST: Clear warnings during test init

src/ucp/tag/rndv.c
Fallback to RNDV PUT scheme if `UCX_RNDV_SCHEME=auto` and payload length < min GET Zcopy
Fixes assertion
Update if statement when handling RTS
=> UCP/TAG/RNDV: Switch to RNDV PUT scheme if payload length < min GET Zcopy

src/uct/tcp/sockcm/sockcm_ep.c
Fix race condition on remove event handler. 
Fixes #4207
=> UCT/SOCKCM/EP: fix race condition on remove event handler. Fixes #4207

src/uct/tcp/tcp_ep.c
Cherry-picked from #4248
Close TCP socket when unable to send data anymore and report an error to a user from `uct_ep_am_short()` and `uct_ep_am_bcopy()` if `uct_tcp_ep_am_send()` is unable to send data
Fixes #4243 
Return error code from `ucs_socket_send_nb()` to a caller
=> UCT/TCP: Close TCP socket when unable to send data

src/uct/tcp/tcp_ep.c
Simplify check length in PUT Zcopy
Use macro that calculates service data length
`sizeof(put_req) + uct_iov_total_length(iov, iovcnt)` -> uct_iov_total_length(iov, iovcnt)
`UCT_TCP_EP_PUT_ZCOPY_MAX - sizeof(uct_tcp_am_hdr_t)` -> `UCT_TCP_EP_PUT_ZCOPY_MAX - UCT_TCP_EP_PUT_SERVICE_LENGTH`
=> UCT/TCP: Simplify check length in PUT Zcopy

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/verbs/ud_verbs.c
Add missed UCT_CHECK_LENGTH for PUT Short
Fix it for consistency with other operations
Call `UCT_CHECK_LENGTH` and expect that `sizeof(*neth) + sizeof(*put_hdr) + length` <= `iface->super.config.max_inline`
=> UCT/IB/UD: Add missed UCT_CHECK_LENGTH for PUT Short

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c
Increment iface outstanding counter only once per EP when need to wait for ACK
Fixes #4316 
1. Check `PUT_WAITING_ACK` flag - If not set, increment iface outstanding counter
2. When removing flag, decrement iface outstanding counter (previous logic)
=> UCT/TCP: Fix iface flush after receiving ACK for several PUT operations

src/ucp/core/ucp_am.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/tag/rndv.c, src/ucp/wireup/select.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_md.c
Add fallback to PUT scheme if GET scheme is unsupported
Currently, UCP code assumes that RMA_BW lanes (i.e. underlying UCT ifaces) support both GET and PUT Zcopy operations. We should support UCTs that support a different set of RMA capabilities based on a requested RNDV scheme.
This partially fixes UCP/TAG/RNDV usage over UCT/TCP transport that will support only PUT Zcopy - #4092 (GET Zcopy will be added soon as well). Now it selects a correct RNDV scheme (if `UCP_RNDV_SCHEME` attribute is `auto` or `put_zcopy`)
1. UCP/EP:
When setting RNDV threshold, pass a correct UCT RMA iface capability flag.
- If RNDV mode is GET_ZCOPY, the correct UCT RMA iface capability flag - `UCT_IFACE_FLAG_GET_ZCOPY`
-  If RNDV mode is AUTO and UCT iface supports `UCT_IFACE_FLAG_GET_ZCOPY`, the correct UCT RMA …
=>  UCP/EP, TAG/RNDV, WIREUP: Add fallback to PUT scheme if GET scheme is unsupported

src/ucp/core/ucp_ep.c, test/gtest/ucp/test_ucp_peer_failure.cc
fix RNDV thresholds if UCP_ERR_HANDLING_MODE_PEER
RNDV protocols are not supported yet if err handling is enabled
=> UCP/EP: fix RNDV thresholds if UCP_ERR_HANDLING_MODE_PEER

test/gtest/ucp/test_ucp_rma_mt.cc, test/gtest/ucp/test_ucp_tag_mt.cc
This PR fixes the warning generated by clang 9 when the loop variable of a parallel loop is declared from outside of the loop and uninitialized, for `test_ucp_rma_mt` and `test_ucp_tag_mt`.
Starting from clang 9, compiling the following piece of code
```
#include <iostream>
int main()
{
int i;
#pragma omp parallel for num_threads(4)
for (i = 0; i < 4; i++) {
std::cout << i << '\n';
}
}
```
will generate the following warning
```
test.cpp:10:22: warning: variable 'i' is uninitialized when used here [-Wuninitialized]
std::cout << i << '\n';
^
test.cpp:6:10: note: initialize the variable 'i' to silence this warning
int i;
^
= 0
1 warning generated.
```
This is because the loop variable `i` is required to be private by the OpenMP standard, declaring it from outside the parallel region …
=> GTEST/UCP: Fix clang 9 warnings for OpenMP loop variable initialization

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/tag/rndv.c, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_tag_probe.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
The intent of this PR is to
1. add testing for RNDV/ZCOPY thresholds - e.g. check that max_short is adjusted when RNDV/ZCOPY threshold set by a user.
2. check minimal PUT Zcopy before switching to RNDV PUT Zcopy scheme (when unable to use RNDV GET Zcopy scheme due to limits/scheme)
3. adjust TAG maximal short value by RNDV AM threshold if RNDV_THRESH is set
4. not print `"0..<egr/bcopy>..0..<rndv>...(inf)"`
5. not overwrite Eager thresholds after that are adjusted
1. better code coverage and regression
2. fix case minimal PUT Zcopy > payload length - should use AM
3. fix the case when transport w/o PUT/GET Zcopy caps (UD/UD_MLX5 TLs) are used - RNDV_THRESH does not affect TAG max short in this case
4. fix `ucp_ep_print_info` used by `ucx_info -e` as it prints weird information that both …
=> UCP/CORE, GTEST/UCP: Add tests for zero-thresholds + fixes for RNDV thresholds

src/ucs/memory/memtype_cache.c, test/gtest/common/mem_buffer.cc, test/gtest/common/mem_buffer.h, test/gtest/ucs/test_memtype_cache.cc
Uses alignment required by Page Table and it fixes caching regions that have one shared page, i.e. first and second regions shares its last and first pages, respectively
Fixes #4222
Update MemoryType Cache alignment
=> UCS/MEMTYPE_CACHE: Align regions by Page Table alignment

src/tools/perf/perftest.c
Print an error if memory type is unsupported
`ucx_perftest` silently exits w/o printing any errors
Use `ucs_error`
=> TOOLS/PERF: Print an error if memory type is unsupported

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/mlx5/exp/ib_exp_md.c, test/gtest/uct/ib/test_ib_xfer.cc
performance on Intel E5-2697A 32 cores
without patch
100G shmem_init:      25.32 secs
shmem_finalize:   3.26 secs
200G shmem_init:     106.29 secs
shmem_finalize    9.55 secs
with patch
100G shmem_init:       1.63 secs
shmem_finalize:   0.44 secs
200G shmem_init:       3.01 secs
shmem_finalize    0.85 secs
`
=> UCT/IB: Add multi-threaded MR handling

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/common/test_obj_size.cc
Repeat connection establishment, when a connection was dropped by a remote peer due to lack of resources (accept queue, inability to handle connection request, etc)
Fixes #4237
1. Close old client socket on which failure was detected
2. Move connection to `CLOSED` state
2. Create a new client socket and call `connect()`
if an error occurred, report to a user possible solution on how to solve it setting new system limits
=> UCT/TCP, UCS/SYS: Repeat connection establishment when a connection was dropped

test/gtest/uct/ib/test_sockaddr.cc
Reduce execution time of stress sockaddr testing under valgrind
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12880/label=hpc-test-node-legacy,worker=2/consoleFull
```
18:17:45 TOP-20 longest tests:
18:17:45  1. rc/test_ucp_perf.envelope/0                                                         - 182009 ms
18:17:45  2. sockaddr/test_uct_cm_sockaddr.many_conns_on_client/22                               - 80507 ms
18:17:45  3. tcp/test_ucp_tag_match.rndv_exp_huge_mix/1                                          - 79929 ms
18:17:45  4. sockaddr/test_uct_cm_sockaddr.many_conns_on_client/26                               - 65279 ms
18:17:45  5. sockaddr/test_uct_cm_sockaddr.many_conns_on_client/18                               - 58733 ms
18:17:45  6. ud/test_ucp_tag_match.rndv_exp_huge_mix/1 …
```
=> TEST/GTEST: reduce time execution of stress sockaddr testing under valgrind

src/ucs/async/async.c, src/ucs/async/async_int.h, test/gtest/ucs/test_async.cc
This PR fixes failures in sockcm which look like this:
```
12:52:44 [     INFO ] Testing :::53485 Interface: eth0
12:52:44 [1572432764.828215] [hpc-arm-cavium-jenkins:92947:0]   sockcm_iface.c:214  UCX  WARN  accept(fd=6) failed with non-recoverable error Bad file descriptor
12:52:44 [     INFO ] < failed to connect to fe80::1e1b:dff:fe66:53dc:53485 >
12:52:44 /scrap/jenkins/workspace/hpc-ucx-pr-2/label/hpc-arm-cavium-jenkins/worker/3/contrib/../test/gtest/common/test.cc:273: Failure
12:52:44 Failed
12:52:44 Got 1 warnings during the test
12:52:44 
[  FAILED  ] sockaddr/test_uct_sockaddr.err_handle/5, where GetParam() = sockaddr/eth0 (2 ms)
```
The issue was introduced in #4339
=> UCS/ASYNC/TEST: Fix sync handler remove

src/ucs/debug/debug.c
On FreeBSD SIGSYS is 12, and SIGPIPE is 13.  On the other hand, there
is no SIGSTKFLT and SIGPWR.
=> UCS/DEBUG: Do not use undefined signal names, and terminate the array.

src/ucs/debug/debug.c, src/ucs/debug/debug.h, src/ucs/debug/log.c, src/ucs/debug/log.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/base/uct_iface.c, test/gtest/ucs/test_log.cc
=> UCT/IFACE: added backtrace output on invalid AM ID

src/ucm/cuda/cudamem.c
Skip the call to `cuPointerSetAttribute` if the pointer is null.
User applications may have `cudaMalloc((void*)&ptr, 0)` which is a valid CUDA API call, returning success and setting `ptr` to null. However, calling `cuPointerSetAttribute` on a null pointer is not valid, which will raise a UCX warning.
Simply return if `dptr` is null.
=> Skip ucm_cuda_set_ptr_attr when pointer is null

buildlib/azure-pipelines-release.yml
Edit the existing release (if found) instead of creating a new one.
This change supports two approaches:
1. Tag pushed by git command (new draft will be created)
2. The new release created via GH web. This created release will be used to attach assets.
=> AZP: edit existing release if exist

test/gtest/uct/test_md.cc, test/gtest/uct/uct_test.h
Add ROCm unit tests to the gtest framework.
This will enable the ROCm GPU transport to have unit test coverage.
=> GTEST/UCT/ROCM: Enable ROCm unit tests in the gtest framework

src/ucm/cuda/cudamem.c
Only call assert in ucm_cudafree_dispatch_events if cuMemGetAddressRange() call
succeeds and downgrade warning to debug message when it fails.
A CUDA context may not be set during a call to `cuMemGetAddressRange`, which will return an error, thus causing the assertion to fail, even though the program could free the pointer nevertheless and continue.
Check if CUDA call is successful before assertion.
Fixes #4367
=> UCM/CUDA: fix ucm_cudafree_dispatch_events assertion

src/ucs/arch/aarch64/cpu.h
The change is driven by recent clarifications in linux kernel code:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=22ec71615d824f4f11d38d0e55a88d8956b7e45f
Performance testing shows 8% uplift for short messages using InfiniBand.
=> ARCH/ARM: Barrier code update.

src/tools/perf/api/libperf.h, src/tools/perf/cuda/cuda_alloc.c, src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/lib/uct_tests.cc, src/tools/perf/perftest.c, src/ucs/memory/memtype_cache.c, src/uct/cuda/cuda_copy/cuda_copy_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, test/gtest/uct/test_uct_perf.cc
Adds `-m <mem_type>` option for UCT test as we have for UCP tests
Makes possible running `ucx_perftest`'s UCT tests with CUDA memory
1. Added UCT alloc/free for CUDA and HOST memories
2. Added `memcpy` for HOST->HOST, CUDA->HOST, HOST->CUDA
3. Used them across `ucx_perftest` to fix crashes when dereferencing CUDA memory as a local memory
=> TOOLS/PERF: Enable CUDA memory type support for UCT perf tests

src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/sys/string.h, src/uct/ib/base/ib_iface.c, test/gtest/uct/ib/test_ib_pkey.cc
1. Add `const` qualifier for all source values in `clone`, `write`
2. Make default PKEY - `auto`
1. We don't change source values in those functions
2. Improves search time when PKEY value is not set - we use first available
1. Add `const` qualifier
2. Add parsing/writing `auto` for HEX table entries; make `auto` default value for `PKEY`; fix it `in uct_ib_iface_init_pkey`
=> UCT/IB, UCS/CONFIG: Make default PKEY - auto, improve PKEY search time

src/ucm/cuda/cudamem.c
Backport of #4374. Only call assert in ucm_cudafree_dispatch_events if cuMemGetAddressRange() call
succeeds and downgrade warning to debug message when it fails.
=> UCM/CUDA: fix ucm_cudafree_dispatch_events assertion - v1.7.x

src/ucm/cuda/cudamem.c
Backport of #4351, skips the call to `cuPointerSetAttribute` f the pointer is null.
=> UCM/CUDA: Skip ucm_cuda_set_ptr_attr when pointer is null - v1.7.x

src/uct/api/uct.h
Fix formula listed for `Process Per Node (PPN) bandwidth specification`
A function parameter has to be `ppn` rather than `x` (that's not sued in the formula)
`x` -> `ppn`
=> UCT/API: Fix typo in BW formula documentation

src/ucs/memory/memtype_cache.h
=> UCS/MEMORY: pthread_rwlock_t requires pthread.h.

src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/mm/base/mm_md.c, src/uct/sm/mm/base/mm_md.h, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, src/uct/sm/mm/xpmem/mm_xpmem.c
Preparation for adding RNDV over XPMEM - moving MD ops directly to mappers to avoid extra level of indirection in rkey pack/unpack
=> UCT/MM: Move MD operations definition to mapper components

src/ucp/core/ucp_context.c, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_worker.h, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/rndv.h, src/uct/cuda/cuda_copy/cuda_copy_iface.c
Implements 3 stage rndv pipeline put protocol for mem type buffers
- Stage 1:  GET from src SEND MEMTYPE buffer to HOST staging buffer
- Stage 2:  PUT from HOST staging buffer to remote HOST staging buffer
- Stage 3:  Put from HOST staging buffer to RECV buffer
Currently RNDV protocol is inefficient in following cases
1. (inter-node GPU-GPU) rndv protocol fallback to AM bcocy fragmentation protocol if GPUDirectRDMA is disabled. Which is very inefficient because of cuda staging with bcopy protocol.
2. (inter-node GPU-GPU) GPUDirectRDMA transfers are inefficient if GPU and NIC are diffent PCIe topology
3. (intra-node GPU-GPU) CUDA-IPC is not supported if the GPU are connected under same PCIe RC or NVLINK.
1. In rndv AUTO protocol, the receiver detects if it required a 3-stage pipeline abd …
=> UCP/MEM_TYPE:  3-stage rndv pipeline fragmentation for mem type buffers

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c
Rename enum UCP_WIREUP_SOCKADDR_CD_* to UCP_WIREUP_SA_DATA_* according
to ucp_wireup_sockaddr_data_t data type.
=> UCP/WIREUP/SOCKADDR: rename enum UCP_WIREUP_SOCKADDR_CD_*

src/ucp/tag/rndv.c
Fix segfault in Host to Device ( H to D) pipelining when multiple rndv lanes present.
when multiple fragments transferred, it called deregister on same unused lane multiple time for each fragment
For each fragment transfer set memh of the selected lane only.
=> UCP/RNDV: Fix Host to Device pipeline protocol

test/gtest/uct/uct_test.cc
Test started to failed after loading nv_peer_mem kernel module on GPU test nodes
=> Fixes in gtest for GPU memory with peer-direct

src/ucs/arch/cpu.c, src/ucs/arch/cpu.h, src/ucs/arch/x86_64/cpu.c
Use built-in memcpy for 1Kb..136Kb on AMD CPUs
Performance tuning on AMD CPUs
It improves UCP/TAG/Eager/Zcopy using IB device on [2Kb..256Kb]:
bytes | improvement
-- | --
2048 | 10.86%
4096 | 17.51%
8192 | 12.16%
16384 | 3.33%
32768 | 0.28%
65536 | 3.43%
131072 | 5.07%
262144 | 2.01%
Performance data for built-in `memcpy()`:
```
```
```
```
136 Kbytes is a maximum that was choosen, since it is last `memcpy()` size that gives better perfromance using built-in `memcpy()`:
```
```
Use the same approach as for Intel CPU >= Haswell model, but in a range of [1Kb..136Kb] where built-in `memcpy()` shows better performance than glibc `memcpy()`
=> UCS/ARCH: Use built-in memcpy for 1Kb..136Kb on AMD

src/tools/info/type_info.c, src/ucp/core/ucp_context.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/verbs/ud_verbs.c, test/apps/test_ucx_tls.py, test/gtest/ucp/test_ucp_context.cc, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_ud.cc, test/gtest/uct/ib/test_ud_ds.cc, test/gtest/uct/ib/test_ud_pending.cc, test/gtest/uct/ib/test_ud_slow_timer.cc, test/gtest/uct/ib/ud_base.h, test/gtest/uct/test_tag.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
=> UCP/UCT/TEST: Rename "rc","ud" transports to "rc_verbs","ud_verbs"

test/gtest/uct/uct_test.cc
=> Fixes in gtest for GPU memory with peer-direct - v1.7.x

bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Fixing an issue when recv_callback is called inside `ucp_tag_recv_nb` and it waits for fields in request that were not initialized.
To fix an issue, reproduced by test.
Keep additional fields inside request: `bool completed` and `ucs_spin_lock`. Inside recv callback, acquire lock and set request completed.
=> JUCX: fix livelock when callback is called inside ucp_tag_recv_nb.

src/ucp/wireup/select.c
Show errors only if non-scalable Tl bitmap used for lanes selection
Fixes issue: error is not printed when used TL bitmap is reduced
Add the additional parameter `show_error` for `ucp_wireup_select_params_init`:
- `1` show error
- `0` don't show error (scalable TL bitmap case only)
=> UCP/WIREUP: Don't show error in case of scalable TL bitmap only

src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm_ep.c, test/gtest/ucp/test_ucp_sockaddr.cc
+ UCT/RDMACM_CM: return correct err status
+ improve error message
+ add handling off new error message to UCP tests
+ skip sockaddr testing for self(loop back) transport, client and server EPs must be different.
+ To propagate correct error status (#4247) to user level and make possible to handle it in UCP gtests
+ sockaddr testing doesn't make sense for self transport
=> UCT/RDMACM_CM: return correct err status

src/ucs/memory/memory_type.c, src/ucs/memory/memtype_cache.c, test/gtest/ucs/test_memtype_cache.cc
Add support for the following cases
1. when a user lookups a region that includes multiple buffers that were allocated separately and they are contiguous
2. when CUDA buffer consists of multiple regions that were detected by MemType Cache during existing allocation handling
Fixes #4393 
example:
1. [0x250 .. 0x500] was allocated by using `cudaMalloc()`
2. `ucp_init()` was called
3. Memtype Cache init: read [0x100 .. 0x900] from `proc/self/maps` and add it to Memtype Cache with LAST memory type
4. [0x100 .. 0x200] and [0x200 .. 0x250] were allocated using `cudaMalloc()`. So, cache has [0x100 .. 0x250] - CUDA, [0x250 ... 0x900] - LAST.
5. User calls `ucp_mem_map()` for [0x220 .. 0x500], it reports an error when tries to register it in cuda-copy UCT as it assumes that this memory is HOST …
=> UCS/MEMTYPE: Merge regions that have same memory type

bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am, config/m4/java.m4, configure.ac, contrib/buildrpm.sh, contrib/rpmdef.sh.in, ucx.spec.in
Rpmbuild for jucx.
To build ucx-java.rpm where possible and correctly handle when the maven is not installed.
To fix https://github.com/openucx/ucx/pull/4362
=> JUCX: rpmbuild for java bindings.

src/ucp/tag/tag_match.c
UCP/TAG: Don't put request on matchq when the key is deleted
Signed-off-by: sheng yang <shengyang1@huawei.com>
=> UCP/TAG: donot put request on matchq when the key is deleted

bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am, buildlib/azure-pipelines.yml, contrib/buildrpm.sh, ucx.spec.in
Enable testing of rpm build in PR check.
It is used by the release pipeline and has to always work.
=> AZP: enable testing of rpm build

src/ucp/core/ucp_context.h, src/ucp/tag/eager_snd.c, src/ucp/wireup/signaling_ep.c
Add more assertions in UCP/TAG and UCP/WIREUP for better debugging
Improves debugging and error detection
1. Add common function for TAG Eager Bcopy packing and asserts there
2. Add assert for memory type (it must be HOST always) in signaling pack cb in UCP/WIREUP
=> UCP/TAG/WIREUP: Improve debugging adding useful assertions

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Intended to fixes failures like http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/2688/pipeline where timeout is too small, but still finish the test fast when the message is received
=> JAVA/TEST: Increase timeout for endpoint recv test

bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java, src/ucs/async/async.c, src/ucs/async/async_fwd.h, src/ucs/async/async_int.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/sockcm/sockcm_ep.c, src/uct/tcp/sockcm/sockcm_iface.c, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucs/test_async.cc, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/test_md.cc, test/gtest/uct/uct_test.cc
Enable gtest to test IPv6 interfaces with the sockaddr testing.
To test IPv6 interfaces as well.
Porting of https://github.com/openucx/ucx/pull/4326
=> GTEST/UCS: Enable sockaddr testing with an IPv6 address - v1.7.x

src/uct/ib/base/ib_device.c
This patch adds support for Bull devices (with Bull vendor_id) for which the firmware reports Mellanox device_id.
This is a workaround while waiting for Mellanox fix.
N/A
=> UCT/IB: Add entries with Bull vendor_id and Mellanox device_id

src/uct/ib/base/ib_device.c
Adds 3 more Atos Bull HCAs (ConnectX-6) into recognized device list. This PR is equivalent to #4415 on v1.7.x branch
So these devices with Mellanox silicon can use the optimizations. As decided on the call with Mellanox we'll drop the PR #4415 and merge this into master branch first.
N/A
=> UCT/IB: Add Bull sequana device IDs for Sequana 2 HCAs

bindings/java/src/main/java/org/openucx/jucx/UcxUtils.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxBenchmark.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConstants.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpContext.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpMemMapParams.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpMemory.java, bindings/java/src/main/native/context.cc, bindings/java/src/main/native/ucp_constants.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpMemoryTest.java
Enhance registerMemory functionality by supporting register by address, ODP flag, and allocation flag. Everything is backward compatible.
1. To be able to work with a pointer to device memory (GPU, etc.).
2. To support ODP is SparkUCX.
3. To be able to allocate memory directly from UcpContext.
=> JUCX: context.RegisterMemory: expose register by address, odp flags, allocation

bindings/java/src/main/native/Makefile.am, contrib/test_jenkins.sh
Print error file in Jenkins on segfaults.
To easier debug segfaults errors on JUCX during Jenkins tests.
=> JUCX: print error log file on error.

src/uct/sm/mm/xpmem/mm_xpmem.c
=> UCT/MM/XPMEM: Add remote regions cache for fast rkey_unpack

src/ucp/core/ucp_am.inl, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.inl, src/ucp/dt/dt.c, src/ucp/dt/dt.inl, src/ucp/tag/rndv.c, src/ucp/tag/tag_send.c, src/ucs/memory/memory_type.h, src/uct/ib/base/ib_md.c, src/uct/sm/cma/cma_md.c, src/uct/sm/knem/knem_md.c, src/uct/sm/mm/xpmem/mm_xpmem.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_md.c, src/uct/ugni/base/ugni_md.c
Add support CUDA and ROCM managed memories for all UCT MDs
UCT MDs support CUDA- and ROCM-managed memories as they accessible from CPU
Define and use `UCS_MEMORY_TYPES_CPU_ACCESSIBLE` macro
=> UCS/UCT: Add support CUDA- and ROCM-managed memories for all UCT MDs

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_listener.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/ucp/wireup/wireup_cm.c
This PR adds sockaddr/cm wireup, part 3. part 2 was implemented in #4266
To prepare for adding close protocol
=> UCP/WIREUP/CM: establish connection on uct lanes

contrib/test_jenkins.sh, src/tools/perf/perftest.c, test/examples/Makefile.am, test/examples/ucp_hello_world.c, test/examples/uct_hello_world.c, test/examples/ucx_hello_world.h, test/gtest/common/mem_buffer.cc
Introduce CUDA memory support in UCP and UCT hello-world examples
Add running of those test in test_jenkins.sh:
- UCP: when CUDA available
- UCT: when CUDA and GPUDirect available
To have a simple reproduction and show that UCP/UCT can use CUDA/CUDA-Managed memory
Add `mem_type_allcoators[UCS_MEMORY_TYPE_LAST]` array of memory functions that can be used to access HOST/CUDA/CUDA-Managed buffers from example code
=> TEST/EXAMPLES: Enable CUDA memory support for UCP/UCT hello-world examples

src/ucp/dt/dt.c
FIx error message in ucp_mem_type_pack
Add mem type domain name to error message since it was supposed to be there
=> UCP/DT: Fixed typo in error messages

test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
Add variants generation func for UCT tests
To avoid writing resource wrapper class when need to run UCT test on the same device/transport several times (with different pre/conditions) 
Would be enough to specify `enum_resource` method in the test class:
```
static std::vector<const resource*> enum_resources(const std::string& tl_name) {
static std::vector<resource> all_resources;
if (all_resources.empty()) {
generate_test_variant(TEST_TAG_1_STRIDE, "1 str", all_resources);
generate_test_variant(TEST_TAG_8_STRIDE, "8 str", all_resources);
generate_test_variant(TEST_TAG_1_STRIDE | TEST_GLOBAL_ADDR,
"1 str, global",  all_resources, "dc_mlx5");
generate_test_variant(TEST_TAG_8_STRIDE | TEST_GLOBAL_ADDR,
"8 str, global",  all_resources, "dc_mlx5");
}
return filter_resources(all_resources, …
```
=> GTEST/UCT: Add variant for UCT tests

test/gtest/uct/ib/test_sockaddr.cc
test disconnect event on unexpected peer destroy (without disconnect)
test error handling detection mechanism to be used in UCP close protocol
=> GTEST/UCT/SOCKADDR/CM: test disconnect event on unexp peer destroy

contrib/test_jenkins.sh, test/gtest/uct/uct_test.h
After changing MM transport names to sysv/posix/xpmem, some tests did not run
1. Fix ucx_perftest in test_jenkins.sh 
2. Fix UCT gtest transports and run on every shared memory transport
=> TEST/UCT: Enable shared memory tests on all transports

src/ucp/rma/rma.inl
Use `ucp_request_put` instead of `ucs_mpool_put`
We have to use `ucp_request_put` as it traces releasing of request and invokes `UCS_PROFILE_REQUEST_FREE` macro
`ucs_mpool_put(req);` -> `ucp_request_put(req);`
=> UCP/RMA: Use ucp_request_put instead of ucs_mpool_put

src/ucp/core/ucp_request.c, src/ucp/tag/tag_match.c, src/ucp/tag/tag_match.h, test/gtest/ucp/test_ucp_tag_cancel.cc
Fix `ucp_request_cancel` for already matched requests. In this case request should be completed OK, not canceled.  
Fixes #4490
=> UCP/TAG: Fix ucp_request_cancel for matched reqs

src/ucs/sys/sock.c
I'm on Centos 7 and noticed that when a NULL sockaddr is encountered, I get a segfault. Upon further inspection, I found that these null socket addresses corresponded to interfaces for VPN tunnels which aren't even in use at the time the bug is encountered. 
This is causing a segfault on my Centos 7 workstation. I do not have any special configuration set up which would cause this behavior to be expected. I would expect that UCX would recognize that one of the `sockaddr`s is null and skip over it. 
The solution here is very simple- just skip over the NULL sockaddr.
=> UCS/SYS: Skipping over null sockaddr, rather than segfaulting

bindings/java/src/main/java/org/openucx/jucx/UcxUtils.java, bindings/java/src/main/native/Makefile.am
JNI header files dependencies from source files.
To rebuild header files when java files changed, to avoid errors.
=> JUCX: rebuild header files when java sources changed.

src/ucs/sys/sock.c
This PR cherry picks the null ifaddr check, which was committed to master a couple weeks ago, into version 1.7 so that it can be released with an upcoming UCX-py version
Many tunnel interfaces, like Cisco AnyConnect VPN, for example, are causing null pointer segfaults in regular UCX usage. 
This PR skips over interfaces where ifaddr is NULL
=> [REVIEW] Cherry picking null ifaddr check to 1.7

src/ucp/tag/offload.c, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/uct/test_tag.cc
Restrict posting the same buffer to the HW more than once
SW RNDV request in tag offload mode stores RTS in the user buffer (in case of expected).
Can be corrupted when the same buffers is posted several times in a row (bw pattern)
Use set of buffers in UCT. Add new set element every time new tag is being posted. Delete buffer from the set, when:
- cancel with force
- got completion of tag remove (noforce)
- got message_handled completion from HW
=> UCT/TAG: Do not post the same buffer more than once

src/ucs/arch/aarch64/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.c, src/ucs/arch/x86_64/cpu.h, src/uct/rocm/copy/rocm_copy_ep.c
Use faster memcpy for device to host copies
Native memcpy is slow for device to host copies
Use non-temporal load (MOVNTDQA) to implement memcpy
=> UCT/ROCM/COPY: Use faster memcpy for device to host copies

src/uct/rocm/ipc/rocm_ipc_ep.c
Use local GPU agent as the source and destination for ROCM-IPC copies
* Fix incorrect agent selection when all HSA agents are not visible to all ranks
* Fix failure when unequal number of GPUs are assigned to different ranks
=> UCT/ROCM/IPC: Use correct agent for IPC copies

doc/doxygen/conventions.md
Fix heading for Signal Handler Functions section to display properly
Grammar fix: "an UCX" -> "a UCX"
Documentation Cleanup
=> DOC/CONVENTIONS: Cleanup Conventions and Notations section of the API document

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/rndv.h, test/gtest/ucp/test_ucp_tag_offload.cc
Add software rendezvous protocol for tag offload flow
Performance optimization. Using tag offload for eager messages only can be beneficial for certain applications (those which do not overlap communication and computation)
Use sw rendezvous request instead of real rendezvous request if SW mode is forced.
=> UCP/TAG: Add SW RNDV protocol for tag offload mode

bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConstants.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/main/native/ucp_constants.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java, contrib/test_jenkins.sh
Expose ep_close_nb into JUCX. via 2 methods: `endpoint.closeNonBlockingFlush` `endpoint.closeNonBlockingForce`
Requested by #4403 + `ucp_ep_destroy` is deprecated.
=> JUCX: ep_close_nb functionality.

buildlib/tests.yml
Enable posting of the real status from `./contrib/test_jenkins.sh` for AZP. Originally added in #4394.
AZP agents look stable, there are no infra issues during a week+.
=> AZP: report real status of test_jenkins.sh run

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/sm/base/sm_iface.c, src/uct/sm/base/sm_iface.h, src/uct/sm/cma/cma_ep.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/cma/cma_iface.h, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_md.h, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, src/uct/sm/mm/xpmem/mm_xpmem.c
- use access to shared memory segment for is_reachable test
on iface initialization (instead of GUID based)
=> SHM/MM: use real SHM access for reachable test

config/m4/ucs.m4
Fixes a typo in `./configure`'s `--cache-line-size` help message.
As above
NA
=> CONFIG/M4: Fix typo in --cache-line-size help

src/ucp/tag/rndv.c
Call correct completion function associated with a request during progress inside `ucp_rndv_progress_rma_get_zcopy`.
This fixes failures in the D-H and H-D path with ROCm.
Thanks to @yosefe and @bureddy for providing the fix.
=> UCP/RNDV: Call correct completion function in pipeline protocol

test/gtest/uct/test_p2p_mix.cc
Progress all UCT entities in order to complete sender flush in P2P test
Fixes #4419 
Fixes #3769
The test hangs from time to time when running with TCP UCT TL, since the last AM operation was not able to send full buffer (The receiver is out of space to receive the buffer) and report `UCS_OK`.
Then we enter `entity::flush()` for sender that waiting for `flush()` complete on a sender and progress only sender's worker.
Use `uct_test::flush()` that progress all UCT entities
=> GTEST/UCT: Progress all UCT entities in order to complete sender flush

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucs/arch/cpu.c, src/ucs/arch/cpu.h
Use a lower Bcopy BW value for more optimal RNDV threshold on AMD.
For `UCX_TLS=rc`: Improves BW for messages with size from `[16 KBytes .. 19 KBytes]`.
BW was not changed for messages with size < 16 KBytes (eager/zcopy - experiments shows that eager/zcopy is better here than rndv) and > 19 KBytes (rndv)
1. Make `BCOPY_BW` configuration parameter as BW rather than MEMUNITS
2. Introduce estimated Bcopy BW values for different CPU vendors (AMD - 5000 MBytes/s; other - 5800 MBytes/s as it was before the patch)
3. if `BCOPY_BW=auto`, take the Bcopy BW value from the Bcopy BW table based on CPU vendor
=> UCP/UCS: Use a lower Bcopy BW value for more optimal RNDV threshold on AMD

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpRequest.java, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcxTest.java
Additional field to UcpRequest to get received length.
Needed to get actual receive size of data. The same logic will be reused when will implement stream_recv.
=> JUCX: get recv size from UcpRequest.

src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c
Add assert to check that don't send CM data when connected
In order to catch potential bug found by #4525 and #4406
Add assert and fix comment (`them` -> `they`)
=> UCT/TCP: Add assert to check that don't send CM data when connected

src/ucp/core/ucp_mm.h, src/ucp/core/ucp_rkey.c
Set flag in the rkey desc to indicate if the desc is allocated from pool or malloc
RKEY desc is allocated from pool or malloc based on the remote_md_map, but it is considering only unpacked key md_map causing segfault when it is unable to unpack all the remote keys.
=> UCX/RKEY: Fix crash with RKEY desc free

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_listener.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
apply SOCKADDR_TLS_PRIORITY for CMs
to have ability to disable partially implemented uct_sockcm_cm in PR https://github.com/openucx/ucx/pull/4448 ([usage](https://github.com/openucx/ucx/pull/4448/commits/06bfe241e6f4da41bfc6516f7af5cdd648cf4a75#diff-c19a05052b898dabf25801d90564171bR74))
=> UCP/CONTEXT/WORKER: apply SOCKADDR_TLS_PRIORITY for CMs

buildlib/azure-pipelines.yml
Disable commit title style check for direct pushes and merges. The check will look like [this](https://dev.azure.com/ucfconsort/ucx%20-%20test/_build/results?buildId=3147&view=logs&j=a3e7afe8-b282-5869-712a-9857fbd4b4a9&t=fd231581-c084-51fb-f10e-187ae5f1c153).
Fixes #4538 
Commit range is not available in this case.
=> AZP: skip commit style check for non-PRs

src/uct/tcp/tcp_ep.c
Fix memcpy from PUT HDR to RX buffer that can be overlapped
Fixes #4584:
RX buffer and PUT Zcopy header can be overlapped
Use `memmove()` instead of `memcpy()`
=> UCT/TCP: Fix memcpy for overlapped buffers

test/gtest/ucp/test_ucp_wireup.cc
Test if atomic operation is completed after ep flush which is in wireup state.
Found an uncertain behavior during SW AMO with loopback implementation.
add new unit gtest
@yosefe pls take a look, is this a bug or expected behavior? for rcx and dcx (rare) flush completion callback is called before AMO is done
=> GTEST/UCP/AMO: test wireup + amo + flush

src/ucp/tag/offload.c
1. Do not use tag offload bounce buffers for GPU memory receives (to avoid cuda_copy from staging buffer to the destination memory)
2. Remove `ucs_unlikely` hint for zero copy receives, since it is always used by default
better performance
=> UCP/TAG: Tag offload bounce buffer optimization

config/m4/rocm.m4, src/tools/perf/Makefile.am, src/tools/perf/configure.m4, src/tools/perf/perftest.c, src/tools/perf/rocm/Makefile.am, src/tools/perf/rocm/configure.m4, src/tools/perf/rocm/rocm_alloc.c
Adds support for ROCm in UCP perf tests
ROCm support was missing in perf tests
Required for manual testing and CI
```
$ ./bin/ucx_perftest localhost -f -c 2 -t tag_lat -m rocm
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
1000000     1.458     8.188     9.640       0.93       0.79      122133      103732
$ ./bin/ucx_perftest localhost -f -c 2 -t tag_bw -m rocm …
```
=> TOOLS/PERF: Enable ROCM memory type support for UCP perf tests

bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Set request completed when there's a progress thread that comes to the callback earlier than `process_request` happen.
In `process_request` it handles only to call the callback, but not to set request completed + recv_size.
=> JUCX: set request completed when there's race in progress thread.

src/ucs/datastruct/pgtable.c, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, test/gtest/ucs/test_memtype_cache.cc, test/gtest/ucs/test_pgtable.cc
1. Fix search range in Memtype Cache
2. Fix bug in `ucs_pgtable_search_range()` in Page Table
1. Since search region includes the next region's address, removal of Memtype Cache regions produces the following warnings when do slicing of regions (it insert same region several twice to a cache):
```
...
[1574090233.115291] [clx-mld-064:42075:0]  memtype_cache.c:83   UCX  ERROR failed to insert region 0x55c4d0fffc30 [0x7fe000000000..0x7fe058b05000]: Element already exists
[1574090233.115294] [clx-mld-064:42075:0]  memtype_cache.c:83   UCX  ERROR failed to insert region 0x55c4d0fffc30 [0x7fe000000000..0x7fe058b81000]: Element already exists
[1574090233.115298] [clx-mld-064:42075:0]  memtype_cache.c:83   UCX  ERROR failed to insert region 0x55c4d0fffc30 [0x7fe000000000..0x7fe058d46000]: …
```
=> UCS/GTEST/MEMORY/DATASTRUCT: Fix search range in Page Table

src/ucp/core/ucp_request.h, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/rndv.h, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
1. Fixes RNDV PUT Zcopy scheme when posted received buffer is larger than send buffer.
2. Fixes incorrect `ucs_assert()` condition.
1. Fixes #4474, reproduced: 
- for TCP: `tcp/test_ucp_tag_match_rndv.post_larger_recv/0 <tcp>` hangs.
- for IB: 
```
[ RUN      ] rcx/test_ucp_tag_match_rndv.post_larger_recv/0 <rc_x>
[hpc-test-node-gpu01:15977:0:15977] ib_mlx5_log.c:139  Local protection on mlx5_0:1/IB (synd 0x4 vend 0x53 hw_synd 0/157)
[hpc-test-node-gpu01:15977:0:15977] ib_mlx5_log.c:139  RC QP 0x320a4 wqe[3]: RDMA_WRITE s-- [rva 0x1816050 rkey 0x36d33c] [va 0x1838130 len 32 lkey 0x36d841]
```
2. RNDV RTS header can have `address == 0` in case of non-contig datatype or RNDV GET Zcopy scheme can't be used for data transfer.
this leads to test failure for DC and RC transports:
``` 
[ RUN …
```
=> UCP/TAG: Fixes for RNDV PUT Zcopy scheme

test/gtest/common/mem_buffer.cc, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h
Introduce cartesian product for vectors and memory type pairs
#4427 and #4450 PRs depend on the memory type pair
1. Implemented cartesian product of vectors
2. Implemented memory type pairs using the cartesian product of vectors of supported memory types
=> GTEST: Introduce cartesian product for vectors and memory type pairs

src/ucp/core/ucp_ep.c
Fix EP TAG config printing
Assume that a user sets `UCX_RNDV_THRESH=inf` and `UCX_ZCOPY_THRESH=inf`
Before:
```
```
After:
```
```
1. Remove `(max_bcopy < min_rndv)` check - since it is incorrect
2. Add  `(max_bcopy > 0)` check - to avoid printing when either `zcopy_thresh` or `min_rndv` is `0`
=> UCP/CORE: Fix EP TAG config printing

test/gtest/ucs/test_profile.cc
Increase profile overhead test timeout for x86 and PPC
In order to fix the following issue that happens from time to time (now it has to be more stable):
```
[----------] 1 test from st/test_profile_perf
[ RUN      ] st/test_profile_perf.overhead/0 <1>
[     INFO ] overhead: 51.1441 nsec
[     INFO ] overhead: 51.3293 nsec
[     INFO ] overhead: 51.2073 nsec
[     INFO ] overhead: 55.421 nsec
[     INFO ] overhead: 50.9175 nsec
[     INFO ] overhead: 50.2257 nsec
[     INFO ] overhead: 54.939 nsec
[     INFO ] overhead: 50.1322 nsec
[     INFO ] overhead: 52.8947 nsec
[     INFO ] overhead: 50.8988 nsec
[     INFO ] overhead: 51.6139 nsec
/scrap/jenkins/workspace/hpc-ucx-pr-3/label/hpc-test-node-gpu/worker/0/contrib/../test/gtest/ucs/test_profile.cc:393: Failure
Expected: (overhead_nsec) …
```
=> GTEST/UCS: Increase profile overhead test timeout for x86 and PPC

src/ucs/sys/sock.c
Do not print stale error in case of successful `connect()`
It prints wrong information about connection status (since `errno` variable contains stale error code), e.g.
```
connect(fd=16, src_addr=192.168.1.1:52001 dest_addr=192.168.1.2:49678): Connection reset by peer
```
but `connect()` returned 0. it has to be:
```
connect(fd=16, src_addr=192.168.1.1:52001 dest_addr=192.168.1.2:49678): Success
```
1. Set `conn_errno` to real `errno` in case of `connect()` returned `ret < 0`
2. Set `conn_errno` to 0 in case of `connect()` returned `ret == 0`
=> UCS/SYS: Do not print stale error in case of successful connect()

src/ucs/async/async.c
Fixes warning message printed from ASYNC
Real warning message w/o the fix:
```
[1577277735.196837]          async.c:368  UCX  WARN  async 0x4973618 handler 0x4965fb0 [id=18 ref 2] uct_tcp_cm_magic_number_handler() uct_tcp_cm_magic_number_handler() not released
```
Expected:
```
[1577277735.196837]          async.c:368  UCX  WARN  async 0x4973618 handler 0x4965fb0 [id=18 ref 2] uct_tcp_cm_magic_number_handler() not released
```
remove `%s()` and `ucs_debug_get_symbol_name(handler->cb)`, since `UCS_ASYNC_HANDLER_FMT` and `UCS_ASYNC_HANDLER_ARG(handler)` already print it
=> UCS/ASYNC: Fix warning message

src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c
Fix bugs when handling error flow + add useful `assert()`s
1. Fix possible double EP destroying in `uct_tcp_cm_handle_conn_req()` when an error occurs in `uct_tcp_cm_handle_simult_conn()` after EP was destroyed fro the first time
2. Fix possible dereference of a pointer to EP that was destroyed (i.e. memory was freed) from `uct_tcp_ep_progress_am_rx()` after handling CONN_REQ CM event
1. Remove EP destroying from `uct_tcp_cm_simult_conn_accept_remote_conn()` and `uct_tcp_cm_handle_simult_conn()` always do EP destroying from `uct_tcp_cm_handle_conn_req()` that calls them
2. Always set `*ep_p` to `NULL` after EP destroying in order to handle it in `uct_tcp_ep_progress_am_rx()` and break the loop w/o dereferencing this invalid EP
=> UCT/TCP: Fix error flow for EP when receiving CM CONN_REQ

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h
Check subnet prefix for "global" IB address outside of uct_ib_addr_pack
In case of RDMACM we pass GID "as is" to pack function and "global" fields are not initialized for "local" IB address.
=> UCT/IB/ADDRESS: define is_global outside of addr pack

src/ucp/dt/dt.h, src/ucp/tag/offload.c, test/gtest/ucp/test_ucp_tag_offload.cc
Fix handling of HWTM sw rndv requests arriving to GPU memory 
SW rndv request is stored in the user buffer when matched. If it is GPU memory, need to fetch the request to the host memory before trying to access its data.
=> UCP: Fix for hwtm rndv request with CUDA

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c
pass device address index in sa_data
In case of CM wireup, IFACE/EP and device address are passed to a peer separately. Remote device address index is needed for correct wireup lanes selection. 
Add ucp_wireup_sockaddr_data::dev_index to private data and use this value for initialization of unpacked address before wireup selection logic.
=> UCP/WIREUP/CM: pass device address index in sa_data

test/gtest/ucp/test_ucp_rma.cc
This PR enables `UCX_TLS=dc` + non-blocking mem_map (ODP) variant for RMA tests
Fixes #3409
Slowness was resolved. So, we need to revert PRs that disable RMA tests for DC+ODP variant
remove `test_ucp_rma::init()`
=> GTEST/UCP/RMA: Enable DC + non-blocking mem_map (ODP) variant for RMA tests

src/ucs/sys/string.c, src/ucs/sys/string.h
Allow passing ucs_memunits_to_str() as a parameter to another function, e.g printf()
=> UCS/STRING: Return the output buffer from ucs_memunits_to_str()

src/ucs/sys/math.h
Allow using ucs_min/ucs_max for variables whose names are 'a' or 'b'
=> UCS/MATH: Add prefix to temp vairables in ucs_min/ucs_max

src/uct/ib/rc/base/rc_iface.c
Increase SEG_SIZE for RC/DC TLs from `8 Kbytes` to `8 Kbytes + 64 bytes` (i.e. `8256 bytes`)
Dramatically improves bi-directional BW for 8 Kbytes and 16 Kbytes message sizes and small improvements can be seen on BW and latency
Set `SEG_SIZE=8256` during inheritance of IB config table for RC common config table (i.e. impacting RC_VERBS, RC_MLX5, DC)
=> UCT/IB: Increase SEG_SIZE for RC/DC TLs

src/ucs/datastruct/string_buffer.c, src/ucs/datastruct/string_buffer.h, test/gtest/ucs/test_string.cc
For example, to use ucs_string_buffer_rtrim() after appending several comma-separated strings, to remove trailing commas, whitespaces, etc.
=> UCS/STRING_BUFFER: Add right-trim function

src/ucs/config/parser.c, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/base/mm_iface.c, test/gtest/uct/test_peer_failure.cc
1. Fix config inheritance for IB TLs and SM TLs
2. Don't print similar prefixes if the same prefix name is used several times in a sequence, e.g. "IB_" -> "RC_" -> "RC_"
1. Fixes the following case:
Before
```
#
#
#
UCX_RC_MLX5_DM_SIZE=2K
#
#
#
UCX_RC_MLX5_DM_COUNT=1
#
#
#
UCX_RC_MLX5_MMIO_MODE=auto
```
After:
```
#
#
#
UCX_RC_MLX5_DM_SIZE=2K
#
#
#
UCX_RC_MLX5_DM_COUNT=1
#
#
#
UCX_RC_MLX5_MMIO_MODE=auto
```
2. Fixes the following case (See `inherits`):
Before:
```
#
#
#
UCX_RC_VERBS_SEG_SIZE=8K
```
After:
```
#
#
#
UCX_RC_VERBS_SEG_SIZE=8K
```
1. Add the prefix name during inheritance (where it was missed) of base config to show correct names
2. Add new list entry if `prefix_list` is empty or the prefix name of the entry in the tail of the list is not  the same as the current one
=> UCT/UCS: Fix config inheritance for IB and SM TLs

Makefile.am, bindings/java/Makefile.am, bindings/java/src/main/native/Makefile.am, configure.ac
- Fix recent build issues on fedora30 VM
- Clean up dist tarball
- Install JAR file via generic (rather than custom) method
- Make sure EXTRA_DIST includes only source files
- Install JAR by defining jardir and jardir_DATA variables
=> JAVA/BUILD: Fix make dist and jar install

src/ucp/core/ucp_request.h, src/ucp/tag/tag_match.inl, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
1. Release non-contig buffer when detecting truncated messages.
2. Add `assert()` that `ucp_request::recv::tag::non_contig_buffer` is `NULL` before assigning new memory block to it.
1. Fixes memory leak when detecting that message truncated (i.e. receive buffer less than send buffer) after one Eager segment is received (i.e. `ucp_request::recv::tag::non_contig_buffer` is allocated). The memory leak was reproduced in the new `rcx/test_ucp_tag_xfer.generic_unexp_truncated/*` on `hpc-test-node-upstream-02` node test after `UCX_RC_TM_SEG_SIZE` was increased to 10 kB in order to use TM MP offload for messages with a size of 10000 bytes - 2 segments, where during processing the 2nd segment, it detects that the receiving is truncated  (when it was `UCX_RC_TM_SEG_SIZE=8 kB`, 1000 bytes - Eager …
=> UCP/TAG: Release non-contig buffer when detecting truncated message

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c
Fix comments in UCT/TCP
1. Typo in a comment
2. Unclear comment for EP::RX/TX::offset field
1. `doen't` -> `doesn't`
2. Re-phrase a comment for `uct_tcp_ep_ctx_t::offset` structure field
=> UCT/TCP: Fix comments

src/uct/api/uct.h
Document `uct_ep_disconnect` return codes
To make clearer specially handled errors
=> UCT/DOC: document uct_ep_disconnect return codes

src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/perftest.c, src/ucs/memory/memory_type.c, src/ucs/memory/memory_type.h
Add support for specifying different memory types as source and destination in perftest
Currently the same memory type is used by the sender and the receiver.
Hence, only H-H and D-D transfers can be tested.
This PR adds support for H-D and D-H transfers.
Backward compatibility is preserved by using the same memory type as source and destination if only one is specified.
=> TOOLS/PERF: Enable specifying different memory types for sender and receiver

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/Makefile.am, test/gtest/uct/tcp/test_tcp.cc
Protect UCT/TCP listener against unexpected connections from non-UCX socked-based applications.
Fixes #4525 (master  branch):
UCT/TCP accepts a connection from some client isn't UCT/TCP and tries to receive data from it, but a client violates UCT/TCP AM protocol.
1. UCT/TCP client: always send the first message that includes `CRC16(EP's peer address)` after a connection was established successfully.
2. UCT/TCP server: after some connection was accepted, do not move new EP to a main thread. Wait for the first message with `CRC16(iface's listener address)` and then move to the main thread.
=> UCT/TCP/GTEST: Protect against connection from non-UCX sock-based app

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag_offload.cc
Define minimum value for rndv thresholds when tag offload is configured
1) There is a lower bound for rndv threshold with tag offload. We should not send messages smaller than SW RNDV request size, because receiver may temporarily store this request in the user buffer (which will result in crash if the request does not fit user buffer).
2) Fix the UCT crash (with 0 size messages), when rndv_zcopy is invoked with invalid memh
=> UCP: Fix minimum rndv thresh for tag offload

src/ucp/api/ucp.h
Fix documantation for `ucp_get_nb` and `ucp_get_nbi`
Wrong description for parameters in Doxygen
Fix the description according to the real meaning
=> UCP/API/DOC: Fix ucp_get_[nb|nbi] documentation

Makefile.am, bindings/java/Makefile.am, bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am, config/m4/java.m4, configure.ac, contrib/buildrpm.sh, contrib/rpmdef.sh.in, contrib/test_jenkins.sh, ucx.spec.in
Backport JUCX fixes to v1.7.x in order to fix JUCX build on GPU node
=> JAVA: Backport JUCX fixes to v1.7.x

test/gtest/ucp/test_ucp_tag_offload.cc
Run tag offload tests with relevant transports only (i. e. those which support tag offload)
- Avoid wasting time on skipping the tests for transports which do not support tag offload
- Shorten test outputs
=> UCP/GTEST: Initialize tag offload tests for relevant tls

src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, src/ucp/wireup/wireup_ep.c
- reduce size of ucp_wireup_sockaddr_data_t
- fixes #4652
rdmacm has limited space for private data
=> UCP/WIREUP/CM: reduce size of ucp_wireup_sockaddr_data_t

test/gtest/common/mem_buffer.cc
Should be able to instantiate tests with ROCm memory type
Related: #4641
=> TEST/GTEST: Add support for ROCm memory in mem_buffer

test/gtest/ucm/test_dlopen/Makefile.am, test/gtest/ucm/test_dlopen/dlopen_test_do_load.c
fixed rpath dlopen tests compiled with high level optimization (O2/O3)
fixes https://github.com/openucx/ucx/issues/4602
fix is prevent tail recursion unwind in test
=> GTEST/DLOPEN: fixed dlopen test compiled with -O2/O3

NEWS
* Updating news file
* Copyright dates were bumped up
Once it is merged we tag RC2
=> NEWS: Updating news file before RC2

src/uct/cuda/base/cuda_iface.h, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
Skip resource cleanup if there exists no context
If CUDA application destroys context either through driver API or through `cudaDeviceReset` before `ucp_cleanup`, then cuda resources in CUDA UCTs need not be cleaned explicitly as an attempt to do so results in an error of the following form:
```
cuda_ipc_cache.c:52   UCX  ERROR cuIpcCloseMemHandle((CUdeviceptr)region->mapped_addr) is failed. ret:context is destroyed
cuda_ipc_iface.c:429  UCX  ERROR cuStreamDestroy_v2(self->stream_d2d[i]) is failed. ret:invalid device context
```
cc @bureddy @yosefe
=> UCT/CUDA: Skip cuda resource cleanup if context has been destoyed

src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
When we arm CUDA-IPC transport to notify an event descriptor through callback threads, today we launch work on all streams that the process has created but there maybe work only on a subset of streams. This results in process waking up almost immediately after armed if at least one stream was empty (highly likely because some peers are not even CUDA-IPC accessible but there are streams created for them and there would never be any real work issued on streams dedicated for those peer GPUs). The way to get around this issue is to maintain a refcount and issue callbacks if there are outstanding ops on the stream.
cc @bureddy @quasiben
=> UCT/CUDA/CUDA_IPC: add per stream refcount; avoid callbacks when no pending ops on stream

bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h
Cache UcpRkey jclass and constructor.
In sparkUcx `unpackRkey` happens in the datapath. It takes about 1% on big number of blocks to every time lookup class and constructor. 
http://normanmaurer.me/blog/2014/01/07/JNI-Performance-Welcome-to-the-dark-side/#caching-jmethodid-jfieldid-and-jclass
=> JUCX: cache UcpRkey class and constructor.

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_rkey.c, src/ucp/tag/rndv.c, src/ucp/wireup/select.c, test/gtest/ucp/test_ucp_mmap.cc
Results of osu_bw on 2 processes single node Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz:
| message size | default bw (knem) | bw with xpmem | improvement |
| -------------| ------------- | ------------- |------------- |
| 8192 | 9164.13 | 21851.42 | 58% |
| 16384 | 11237.16 | 19785.50 | 43% |
| 32768 | 14080.48 | 21291.83 | 34% |
| 65536 | 15759.88 | 23173.28 | 32% |
| 131072 | 15850.78 | 22697.77 | 30% |
| 262144 | 13108.42 | 17175.02 | 24% |
| 524288 | 12644.49 | 15609.91 | 19% |
| 1048576 | 12849.59 | 15777.29 | 19% |
| 2097152 | 12940.73 | 15852.41 | 18% |
| 4194304 | 12938.09 | 15809.98 | 18% |
- Select lanes which support rkey_ptr into rma_bw_lanes
- When getting a remote key in rdnv, check any of the local lanes which were selected for rkey_ptr can reach the rkey. If yes, call …
=> UCP/RNDV: Enable shared memory rendezvous protocol over xpmem

src/uct/tcp/tcp_ep.c, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_match.cc
Don't complete uncompleted PUT operation (this is the last received PUT operation) during sending ACK for previous already completed PUT operation(s)
Fixes #4676 
Fixes #4680 
Assume the following situation:
1. Received PUT Req with sn=0
2. Handled PUT data for PUT with sn=0
3. Sending PUT ACK for PUT with sn=0, but it can't be completed due to some TX operation is using the TX buffer
4. Received PUT Req with sn=1
5. TX operation was completed, now can send PUT RX ACK - PUT RX ACK will be sent for PUT with sn=1 -- this is a bug
Remove `UCT_TCP_EP_CTX_TYPE_PUT_RX_SENDING_ACK` when handling PUT Request + add assert that `UCT_TCP_EP_CTX_TYPE_PUT_RX_SENDING_ACK` flag is not set.
PUT ACK will be sent for all completed operation when the last operation was completed
=> UCT/TCP: Fix sending PUT ACK for uncompleted operations

src/ucp/tag/eager_rcv.c
No need to hash first message fragment in tag offload flow(it was a leftover from previous implementation), hashing can be done starting from the second one (like in SW tag matching flow) 
1. Unnecessary code
2. Fixes segfault due to the following sequence:
- element is added to the hash when first fragment arrives in `ucp_tag_offload_eager_first_handler`
- then `ucp_tag_frag_list_process_queue` is called in `ucp_eager_tagged_handler` (expected case)
- `kh_put` is called again (even though element is already added, hash is reallocated and element changed its address)
- then `matchq->unexp_q` is wrongly treated as non-empty, because `ucs_queue_is_empty` compares `queue->ptail`  with `&queue->head`(note the address, which changed during hash reallocation)
=> UCP: Do not hash first msg fragment for tag offload

src/ucp/core/ucp_am.c, src/ucp/proto/proto_am.c, src/ucp/proto/proto_am.inl, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/rndv.c
1. Reset request offset in case of error from UCT AM Bcopy
2. Remove `hdr_size_middle` parameter `ucp_do_am_bcopy_multi` that's not needed + add asserrtion for the first segment to check that `packed_len == ucp_ep_get_max_bcopy(ep, req->send.lane)`
3. Remove check `status == UCP_STATUS_PENDING_SWITCH` for after `ucp_do_am_bcopy_single`
4. Move check for the last segment to the `packed_len >= 0` branch
1. `ucp_dt_pack()` advances `ucp_request::send::dt::offset`, since AM Bcopy may fail (e.g. `UCS_ERR_NO_RESOURCE` status) this request is put to the pending. In this case, offset will be > than the real send length - it will lead to undefined behavior (failure in `assert()` or crash)
Fixes #4600
Fixes #2077
Fixes #4274
2. This is not needed, since we can compare `packed_len` and …
=> UCP/PROTO: Reset request offset in case of error from UCT AM Bcopy

src/tools/info/proto_info.c
Fix usage of PPN parameter that can be specified in ucx_info through `-N <ppn>`
PPN parameter (`-N <ppn>`) can't be applied for UCP
Add `UCP_PARAM_FIELD_ESTIMATED_NUM_PPN` for `params.field_mask`
=> TOOLS/INFO: Fix usage of PPN parameter

src/ucp/core/ucp_context.c, test/gtest/ucp/ucp_test.h
Add GPU-aware TLs instantiation helper macro that enables ROCm and CUDA tests
#4427 and #4450 depend on this helper macro
Add `UCP_INSTANTIATE_TEST_CASE_GPU_AWARE`
=> GTEST/UCP: Add GPU-aware TLs instantiation helper macro

src/ucp/tag/rndv.c
Fix typo in the comment
Better code documentation
`remove` -> `remote`
=> UCP/TAG: Fix typo in the comment

README
1. I am fixing a broken link to contributing instructions
2. I am changing the parameters passed to example test on the README.
1. Broken link
2. It's not obvious that, if running on the same host, the server and client sides should be on different cores. My test was hanging when running on the same core.
1. Fix broken link to point to valid one
2. Changed the affinity of one of the threads and added a note explaining what `-c` means.
=> README: fixed broken link and fixed ucx_perftest example

src/uct/sm/mm/base/mm_iface.c
Fix the name of the parameter when printing an error
Wrong name when printing an error
`"UCT_MM_MAX_SHORT"` -> `UCT_MM_CONFIG_FIFO_ELEM_SIZE` where
```
#define UCT_MM_CONFIG_FIFO_ELEM_SIZE "FIFO_ELEM_SIZE"
```
=> UCT/MM: Fix the name of parameter when printing an error

src/ucp/core/ucp_worker.c
Fix crash when releasing ifaces during rollback after `uct_iface_open` failure
Need to check for `wiface` `NULL`-pointer
```
$ UCX_MM_FIFO_ELEM_SIZE=8 UCX_TLS=posix ucx_info -e -u t
...
[1579715965.698909] [hpc-test-node-gpu01:13235:0]       mm_iface.c:528  UCX  ERROR The UCT_MM_MAX_SHORT parameter must be larger than the FIFO element header size. ( > 28 bytes).
Program received signal SIGSEGV, Segmentation fault.
ucp_worker_close_ifaces (worker=0x65f9b0) at core/ucp_worker.c:1049
...
#0  ucp_worker_close_ifaces (worker=0x65f9b0) at core/ucp_worker.c:1049
#1  0x00007ffff7ba13a1 in ucp_worker_create (context=<optimized out>, params=params@entry=0x7fffffffcd00, worker_p=worker_p@entry=0x7fffffffcc10) at core/ucp_worker.c:1823
#2  0x0000000000402618 in print_ucp_info …
```
=> UCP/CORE: Fix crash when releasing ifaces during rollback

src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.h
UCP tag offload optimizations for unexpected flow
- No need to activate iface and do tag hashing when some middle fragment arrives. It is enough to do that for first fragments of single-fragment messages
- When do tag hashing, the case when it is already present in the hash is considered to be a fast-path. So better check it with `kh_get` and use `kh_put` only for hash miss
=> UCP/TAG: Tag offload optimizations

src/ucs/datastruct/callbackq.c, test/gtest/ucs/test_callbackq.cc
Keep order of slowpath callbacks so events from async thread will be invoked in same order on the main thread
Instead of removing a slow-path element, mark its id as NULL, avoid dispatching it, and purge all NULL callbacks after dispatched all other callbacks. The purge function moves only the valid callbacks to the beginning of the array, thus removing all "holes".
@evgeny-leksikov
=> UCS/CALLBACKQ/TEST: Keep order when removing slowpath elements

bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am
Use by default google mirror for maven.
Fix build for java10+, using compiler plugin to generate native headers.
Should be more reliable to build in containers + fixes https://github.com/DSC-SPIDAL/twister2/issues/831
=> JUCX: use google mirror + fix build on java10+.

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConstants.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/main/native/ucp_constants.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
Streaming API functionality.
To be able to do recv on endpoint.
TODO:
if remove from test `requestRmaFeature` it fails even though no RMA operations there (only streaming). Fails on endpoint destroy:
```
Stack: [0x00007f3e08337000,0x00007f3e08438000],  sp=0x00007f3e084349f8,  free space=1014k
94 Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
95 C  0x00007f3e000002b8
96 C  [libucp.so+0x3afbd]  ucp_ep_flush_internal+0x2ed
97 C  [libucp.so+0x1e8f5]  ucp_ep_close_nb+0xa5
98 C  [libucp.so+0x1ead1]  ucp_ep_destroy+0x41
99 C  [libjucx.so+0x439f]  Java_org_openucx_jucx_ucp_UcpEndpoint_destroyEndpointNative+0x20
100 j  org.openucx.jucx.ucp.UcpEndpoint.destroyEndpointNative(J)V+0
101 j  org.openucx.jucx.ucp.UcpEndpoint.close()V+7
102 j …
```
=> JUCX: streaming API.

src/uct/sm/mm/base/mm_iface.c
Increase MM segment size to include UCP header for 8KB msgs.
1. on ARM system:
- BW
before:
```
#bytes      Mbytes/sec      Msg/sec
8192         5573.17       680319
16384         6944.31       423847
```
after:
```
#bytes      Mbytes/sec      Msg/sec
8192         5120      8456.62      1032302
16384         2560      7114.03       434206
```
- BiBW
before:
```
#bytes      Mbytes/sec      Msg/sec
8192         4703.24       574126
16384         5500.17       335704
```
after:
```
#bytes      Mbytes/sec      Msg/sec
8192         6762.30       825476
16384         5732.34       349874
```
2. on PPC system:
- BW
before:
```
#bytes      Mbytes/sec      Msg/sec
8192         7250.08       885019
16384         9791.01       597596
```
after:
```
#bytes      Mbytes/sec      Msg/sec
8192 …
```
=> UCT/SM/MM: Increase MM segment size to include UCP header for 8KB msgs

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h
- signal worker after adding slow callbacks (wakeup feature support)
- remove uct_cm_ep from arg to CM progress CBs as unnecessary for now
- fix memory leak on reject path
UCT piece of #4448
using git magic power
=> UCP/SOCKADDR/CM: signal worker after adding slow path callbacks

src/uct/tcp/tcp_iface.c
Increase maximum connection retries in case of server's syn backlog overrun
make UCT/TCP more robust in case of slow server when we overrun its SYN backlog
Fixes #4480
Changes the default value for `UCX_TCP_MAX_CONN_RETRIES`:
`5` -> `25`
=> UCT/TCP: Increase maximum connection retries in case of server's syn backlog overrun

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java, src/ucp/api/ucp_def.h
Fix typo in UCP Worker description
better documentation
`implement` -> `implemented` in the following files:
- `bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java `
- `src/ucp/api/ucp_def.h`
=> UCP/API/DOC: Fix typo in UCP Worker description

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/cm/cm_ep.c, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rdmacm/rdmacm_cm.c, test/gtest/uct/ib/test_ib.cc
- optimization for global address processing: in case if
IB EP's are in same subnet - do not use global address
scope
- fixed performance degradation
=> IB/ADDR: optimization for global address processing

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, src/ucs/type/status.c, src/ucs/type/status.h, src/uct/ib/rdmacm/rdmacm_cm.c
- remote disconnect notification
- force close support
- enable complex protocols (RNDV, SYNC send) in case if error handling mode is peer failure and CM lane is presented
Add missed functionality
=> UCP/EP/CM: error handling mode peer support

bindings/java/checkstyle.xml, bindings/java/pom.xml.in
Update checstyle version.
To fix [CVE-2019-10782](https://nvd.nist.gov/vuln/detail/CVE-2019-10782) github warnings.
=> JUCX: Update checkstyle version.

src/ucs/config/parser.h, src/ucs/debug/log.h
In GCC v9.2.0 there are new kinds of warning - one of which is a double semicolon ( ; ; ).
We had it in our code, so here's a (harmless) fix.
=> UCS: Fix GCC v9.2 build error

test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
this PR extends testing for close protocol introduced in #4445
test coverage
- SOCKADDR_CM_ENABLE=y
- do traffic and closing client/server EPs in different combination
=> GTEST/UCP/SOCKADDR: extend testing for close protocol

buildlib/azure-pipelines.yml, buildlib/tests.yml, contrib/test_jenkins.sh
Inherit CPU affinity from the agent instead of setting it manually.
This will allow us to better utilize hosts with AZ agents.
=> AZP: inherit CPU affinity from the agent

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Before this fix DC was disabled on RoCE interface because the internal check for DC support did not set is_global=1 for INIT2RTR.
Set is_global=1 and add debug prints
=> UCT/IB: Fix DC test for mlx5dv, when DevX is not available

src/uct/ib/base/ib_md.c, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Before this fix ODP was disabled even if DevX is not used
=> UCT/IB/DEVX: Disable ODP on DevX memory domain only

contrib/test_jenkins.sh, src/ucp/core/ucp_ep.c
Fix compiler warning when compiling UCP with clang after loading ICC
Fixes #4735 
```
...
core/ucp_ep.c:1896:49: error: implicit conversion from 'unsigned long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
if ((zcopy_thresh < 0.0) || (zcopy_thresh > SIZE_MAX)) {
~ ^~~~~~~~
/usr/include/stdint.h:261:22: note: expanded from macro 'SIZE_MAX'
^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
1. Don't need to check for `> SIZE_MAX` for `double` datatype, checking for `< 0.0` is enough
2. Enabled compiling with clang after ICC loaded
=> UCP/CORE: Fix compiler warning produced by oneAPI DPC++ clang from PSXE 2020

src/ucp/core/ucp_ep.c, src/ucp/tag/rndv.c
Fix usage of GET/PUT RNDV schemes if they are not supported
No need to try GET or PUT if they are not supported. A receiver has to send RTR and sender has to fallback to RNDV over AM
Reset PUT/GET Zcopy min/max limits to correctly identify whether we can use PUT Zcopy or GET Zcopy RNDV schemes or not (before this, they are was set to <min - 0; max - SIZE_MAX>, so UCP thinks that it can do either GET or PUT schemes)
=> UCP/TAG: Fix usage of GET/PUT RNDV schemes if they are not supported

test/gtest/ucp/test_ucp_tag_xfer.cc
multiple tag_xfer fixes (some tests were just duplicating others)
=> UCP/GTEST: Multiple tag_xfer fixes

src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_md.c
Before this PR, cuda_ipc transport picks a stream indexed by the device number provided in the rkey that the peer populates. If there are two processes that do the following:
|  proc id | proc 0  | proc 1  | proc 2  | proc 3  |
|---|---|---|---|---|
|  CUDA_VISIBLE_DEVICES | 0,1,2,3   | 1,2,3,0   | 2,3,0,1 | 3,0,1,2 |
| relative device selection | 0 | 0 | 0 | 0 |
| absolute device picked | 0 | 1 | 2 | 3 |
|  rkey->dev_num | 0 | 0 | 0 | 0 |
|  stream used for all peers |  0 | 0 | 0 | 0 |
|  desired stream usage for peers (0,1,2,3) |   0,1,2,3   |    0,1,2,3   |    0,1,2,3   |    0,1,2,3   |
We already have logic in `cuda_ipc` UCT to generate a unique index based on the uuid returned as part of rkey. We reuse the this unique index as the index to use a stream from stream array at each …
=> UCT/CUDA_IPC: Avoid stream sequentialization; provide max mpool events env

bindings/java/pom.xml.in, bindings/java/src/main/native/Makefile.am, buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.md, buildlib/azure-pipelines.yml, buildlib/jucx-publish.yml, contrib/test_jenkins.sh
Set the default version to SNAPHOT. Publish Snapshot and Release from AZP. Remove libjucx dependencies from other ucx libs. TODO: cross-compile for other platforms/cpu and include all binaries to jar.  
To have nightly snapshots artifacts on maven central + to automate jar release procedure.
=> AZP/JUCX: publish SNAPHOT and RELEASE jars to maven central.

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Fixes #4752 
@evgeny-leksikov 
After the fix 100k iterations of gtest passed (previously it failed after ~7k iterations)
1. ucp_ep_disconnected() must be called with lock held, to make sure no more CM events arrive while ep is being destroyed. Stopping CM events in a synchronous way is achieved by destroying UCT CM endpoint while async lock is held.
2. The test must install disconnect callback on server side as well to handle normal flow of client disconnect. CONN_RESET error must be ignored because it's now part of normal disconnect flow.
=> Multiple fixes for UCP client/server disconnect flow and tests

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, test/gtest/uct/ib/test_dc.cc
Fix adding to pending of flow control packets. Lack of FC credits should not prevent flow control packets being sent. 
To avoid  FC  head-to-head deadlocks.
Fixes https://redmine.mellanox.com/issues/2068025 (Mellanox internal link)
Always add pending grants to the head of arbiter group
=> UCT/DC/GTEST: Fix FC deadlock

bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
UcpRequest class constructor accepts `long` field as nativeId pointer. When we set it to `NULL` it casts to long 0, and bypass check `getNativeId() == null` when checks for request completion. Then it fails:
```
#7  ucp_request_check_status (request=0x0) at /hpc/mtr_scrap/users/peterr/devel/ucx/contrib/../src/ucp/core/ucp_request.c:32
#8  0x00007fe54646b4af in Java_org_openucx_jucx_ucp_UcpRequest_isCompletedNative () from /tmp/jucx3675268389635953312/libjucx.so
```
Fixes this by settings ` env->SetObjectField(jucx_request, native_id_field, NULL);` that sets `Long` class to null.
Stream recv immediate completion wasn't caught in unit tests. Added explicit worker progress, to make sure stream recv will go through immadiate path.
=> JUCX: fix and test stream_recv request immediate path.

src/ucs/sys/iovec.c, src/ucs/sys/iovec.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, test/gtest/uct/tcp/test_tcp.cc
- Fixed the comment for socket send functions that don't return `UCS_ERR_CANCELED` error
- Added the handling of 0-byte messages for UCS send/recv functions (e.g. this is allowed for UDP sockets)
Fixes [4674 (comment)](https://github.com/openucx/ucx/pull/4674/files#r367505380)
- For better documentation
- For future use for UDP sockets and to simplify code to show that send can return `0` only in case of a user's data length is `0`
- Remove mention `UCS_ERR_CANCELED` for `ucs_socket_send_nb` and `ucs_socket_send` + Add assert in `ucs_socket_handle_io_error` for the name of the IO opeartion used (it has to be equal to `recv` only)
- Handle return value == `0` right after `io_func`/`iov_func` completion in case of a user's data length == `0`
=> UCS/SOCK: Fix the comment for socket send and handle case when a user's data length is 0

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h
Code cleanup and preparation for multi-path (RoCE LAG/LMC) support in UCT
=> UCT/IB: Move few slow-path functions to C file
