openucx/ucx

src/uct/ib/cm/cm.h, src/uct/ib/cm/cm_ep.c, src/uct/ib/cm/cm_iface.c
=> UCT/CM: Notification callback should be per ep.

src/tools/perf/Makefile.am
=> BUILD: Fix perftest libtool build.

config/m4/cma.m4, configure.ac, src/uct/Makefile.am, src/uct/sm/cma/cma_ep.c, src/uct/sm/cma/cma_ep.h, src/uct/sm/cma/cma_iface.c, src/uct/sm/cma/cma_iface.h, src/uct/sm/cma/cma_pd.c, src/uct/sm/cma/cma_pd.h, test/gtest/uct/uct_test.h
At this it supports only zcopy get/put operations
=> CMA: adding support CMA transport

src/uct/ugni/ugni_ep.c
Fixing the failures identified by gtest.
=> UGNI: Fixing NULL callback failure

src/uct/ugni/ugni_ep.c
Following Yossi's suggesting to replace "if" with
inline cb.
=> UGNI: Cleaning the callback flow

config/m4/knem.m4, configure.ac, src/uct/Makefile.am, src/uct/sm/knem/knem_ep.c, src/uct/sm/knem/knem_ep.h, src/uct/sm/knem/knem_iface.c, src/uct/sm/knem/knem_iface.h, src/uct/sm/knem/knem_pd.c, src/uct/sm/knem/knem_pd.h, test/gtest/uct/uct_test.h
Missing functionality:
- check for capability flags
- async communication
=> KNEM: Adding initial support for KNEM SM

src/uct/sm/knem/knem_pd.c
See CID 128531
Signed-off-by: Pavel Shamis (Pasha) <shamisp@ornl.gov>
=> KNEM: Addressing memory leak in KNEM

config/m4/sysdep.m4
=> CONFIG: Fixing bug in valgring config

src/ucs/stats/client_server.c, src/ucs/stats/libstats.h, src/ucs/stats/serialization.c, test/gtest/ucs/test_stats.cc
=> STATS/TEST: Fix statistics test.

src/uct/sm/knem/knem_ep.c
See https://scan8.coverity.com/reports.htm#v27370/p11529/fileInstanceId =7867043&defectInstanceId=2805442&mergedDefectId=128530
=> KNEM: Addressing Coverity CID 128530

contrib/test_jenkins.sh, src/ucs/async/signal.c, test/gtest/ucs/test_async.cc
=> Async fixes

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5.h, src/uct/sm/mm/mm_posix.c
This 3 files were missed in #375
=> LICENSE: clarifications for a few files

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.h
in ud_mlx5 available tx wqe count may be negative. 
@yosefe
=> UCT/UD_MLX5: fixes bug in available wqe counting

src/ucp/proto/ucp_context.c
Signed-off-by: Pavel Shamis (Pasha) <shamisp@ornl.gov>
=> UCP: Fixing ucp_init error flow

test/gtest/uct/test_uct_perf.cc
Signed-off-by: Pavel Shamis (Pasha) <shamisp@ornl.gov>
=> GTEST: Adjusting thresholds

LICENSE, debian/copyright
The copyright is in sync LICENSE.
=> DEBIAN: Replacing copyright file with the LICENSE

src/uct/api/uct_def.h, src/uct/ugni/base/ugni_device.c, src/uct/ugni/base/ugni_device.h, src/uct/ugni/base/ugni_iface.c, src/uct/ugni/base/ugni_iface.h, src/uct/ugni/base/ugni_pd.c, src/uct/ugni/rdma/ugni_rdma_ep.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.h, test/gtest/uct/uct_test.h
* Increasing the limit for TL name to fit ugni_rdma
* Restructuring the common code between ugni/base and ugni/rdma
=> UGNI/API: ugni code base restructuring

src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.h
Same issue as in #387, but for RC.
=> RC/MLX5: Fix counting available TX WQEs.

doc/doxygen/intro.dox
Some initial edits for the motivation section.
=> Edits to motivation

src/uct/Makefile.am, src/uct/ugni/base/ugni_device.c, src/uct/ugni/base/ugni_device.h, src/uct/ugni/base/ugni_ep.c, src/uct/ugni/base/ugni_ep.h, src/uct/ugni/base/ugni_iface.c, src/uct/ugni/base/ugni_iface.h, src/uct/ugni/base/ugni_pd.c, src/uct/ugni/rdma/ugni_rdma_ep.c, src/uct/ugni/rdma/ugni_rdma_ep.h, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/udt/ugni_udt_ep.c, src/uct/ugni/udt/ugni_udt_ep.h, src/uct/ugni/udt/ugni_udt_iface.c, src/uct/ugni/udt/ugni_udt_iface.h, test/gtest/uct/test_uct_perf.cc, test/gtest/uct/uct_test.h
* Adding basic support for datagram
* Cleanup of UGNI infrastracture
* UCT level bugfixes (some of these really bloody!)
TODO:
- Pending queue support (have to talk with Yossi)
- Out of order messages (rare but happens)
=> UGNI/UDT: Adding support for UGNI datagram

doc/doxygen/doxygen.am
=> DOXYGEN: Disable doxygen configure file update

src/tools/perf/libperf.c, src/ucp/api/ucp.h, src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_atomic.cc
=> UCP/API/ATOMIC/TEST: Separate atomic32/atomic64 features.

doc/doxygen/ucxdox, src/ucp/api/ucp.h, src/ucp/api/ucp_def.h
I added IBM's copyright since I reused some of ideas
from PAMI documentation.
=> DOXYGEN/API: Addiging definitions for basic UCP concepts

doc/uml/ucp.dot
This PR has to go after #451 proposed by @MattBBaker
=> DOC/UML: Adding UML diagram for UCP

doc/doxygen/ucxdox, src/ucp/api/ucp.h, src/uct/api/uct.h
* Updating documentation for UCP API
* Improving HTML layout (pdf is still broken)
=> DOXYGEN: Updates for documentation

src/uct/ib/mlx5/ib_mlx5_log.c
=> IB/LOG: Fix mlx5 inline data dump.

src/ucs/debug/debug.c
The goal is that if there is an error from non-ucx code, and ucx merely catches the error, "ucx" would not appear in the backtrace.
=> UCS/DEBUG: Remove ucx error handlers from backtrace print.

src/tools/perf/perftest.c
This allows running mpi/perftest with gdb, as well in other cases where isatty(0)==1
=> PERFTEST: Add option to force MPI/non-MPI run.

src/uct/sm/mm/mm_posix.c
=> MM/POSIX: check if there is enough space for the posix backing file.

src/ucs/datastruct/arbiter.c, src/uct/ib/base/ib_verbs.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_pending.cc
reduce batch size to 16 from 32
{rc,ud}_verbsa: always try to post recv wqe
ud: do not allow setting tx_batch size less then ud batch size
@yosefe
=> UCT/IB: post recv fixes

src/ucs/datastruct/queue.h, test/gtest/ucs/test_datatype.cc
=> UCS/QUEUE: Fix queue_del_iter / ucs_queue_for_each_safe()

Makefile.am, autogen.sh, configure.ac, external/Makefile.am
Updates the autogen.sh to check for the existence of git and do git submodule commands to pull all of the defined submodules.
=> BUILD: Make autogen.sh pull git submodules

contrib/ptmalloc3/COPYRIGHT, contrib/ptmalloc3/ChangeLog, contrib/ptmalloc3/README, contrib/ptmalloc3/lran2.h, contrib/ptmalloc3/malloc-2.8.3.h, contrib/ptmalloc3/malloc-private.h, contrib/ptmalloc3/malloc.c, contrib/ptmalloc3/ptmalloc3.c, contrib/ptmalloc3/sysdeps/generic/atomic.h, contrib/ptmalloc3/sysdeps/generic/malloc-machine.h, contrib/ptmalloc3/sysdeps/generic/thread-st.h, contrib/ptmalloc3/sysdeps/pthread/malloc-machine.h, contrib/ptmalloc3/sysdeps/pthread/thread-st.h, contrib/ptmalloc3/sysdeps/solaris/malloc-machine.h, contrib/ptmalloc3/sysdeps/solaris/thread-st.h, contrib/ptmalloc3/sysdeps/sproc/malloc-machine.h, contrib/ptmalloc3/sysdeps/sproc/thread-st.h, contrib/ptmalloc3/t-test.h, contrib/ptmalloc3/t-test1.c, contrib/ptmalloc3/t-test2.c, contrib/ptmalloc3/tst-independent-alloc.c
Adding ptmalloc3 from http://www.malloc.de/en/ as a preparation to implement memory hooks.
=> CONTRIB: Add ptmalloc3 library.

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_pending.cc, test/gtest/uct/test_ud_pending.cc, test/gtest/uct/uct_p2p_test.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
@yosefe @alinask 
Return error if pending_add is called while ep has resources to send.
Try to process pending queue before doing send
Fixes
https://github.com/openucx/ucx/issues/513
Reverts commit
https://github.com/openucx/ucx/commit/f418f20c01c6c4867cd992be18b919002704482b
=> UCT/UD: fix async pending queue and pending queue add

src/ucp/core/ucp_context.c, src/uct/ib/cm/cm_iface.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, test/gtest/uct/test_ud.cc
=> UCT/UD: fix iface capability flags

src/ucs/debug/debug.c
After the commit, the error message would print something like this:
```
[hpchead:5187 :0] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x12)
/labhome/yosefe/workspace/ucx/src/ucs/sys/rcache.h: [ ucs_rcache_get() ]
...
146     pgt_region = ucs_pgtable_lookup(&rcache->pgtable, start);
147     if (ucs_unlikely(pgt_region == NULL)) {
148         region = ucs_derived_of(pgt_region, ucs_rcache_region_t);
==>   149         if ((region->flags & UCS_RCACHE_REGION_FLAG_VALID) &&
150             ((start + length) < region->super.end))
151         {
152             ucs_rcache_region_hold(region);
[hpchead:5187 :0] Process frozen, press Enter to attach a debugger...
```
=> UCS/DEBUG: If possible, print the source code of program error.

src/uct/Makefile.am, src/uct/ugni/base/ugni_ep.c, src/uct/ugni/base/ugni_ep.h, src/uct/ugni/base/ugni_iface.c, src/uct/ugni/base/ugni_iface.h, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.h, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.h, src/uct/ugni/udt/ugni_udt_iface.c, test/gtest/uct/uct_test.h
New transport layer for short messages in UGNI. 
This change also add pending queue support for UDT and RDMA transport layers.
=> New smsg tl for Cray UGNI

src/uct/ib/ud/base/ud_iface.c
=> UCT/UD: add lock when doing async callback

src/ucp/core/ucp_context.c
ugni_smsg is added to the list
Signed-off-by: Pavel Shamis (Pasha) <shamisp@ornl.gov>
=> Updating the alias for ugni

Makefile.am, src/tools/info/type_info.c, src/ucp/core/ucp_worker.c, src/ucs/Makefile.am, src/ucs/datastruct/pgtable.c, src/ucs/datastruct/pgtable.h, src/ucs/sys/rcache.c, src/ucs/sys/rcache.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/type/status.h, src/uct/base/uct_pd.c, src/uct/sm/mm/mm_posix.c, test/gtest/Makefile.am, test/gtest/ucs/test_rcache.cc, test/gtest/ucs/test_sys.cc
=> UCS: Add registration cache data structure.

src/ucm/malloc/malloc_hook.c
=> UCM: Fixes in malloc hooks.

src/ucm/util/reloc.c
=> UCM: Handle corner cases when replacing dlopen().

src/ucp/api/ucp.h
=> UCP: fix api prototype to make gcc happy

src/tools/perf/libperf.c, src/tools/perf/uct_tests.cc, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/tag/eager.c, src/ucp/wireup/wireup.c, src/uct/api/uct.h, src/uct/base/uct_iface.c, test/examples/active_message.c, test/gtest/uct/test_ib.cc, test/gtest/uct/test_many2one_am.cc, test/gtest/uct/test_mm.cc, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_pending.cc
@yosefe @shamisp 
- api change
- add am callback flag that allows callback invocation from
async event. (ex progress thread)
=> UCT/API: add flags to active message callbacks

test/gtest/uct/test_ud_pending.cc, test/gtest/uct/ud_base.cc, test/gtest/uct/ud_base.h
=> GTEST/UD: change default delay to 10ms in short_progress_loop

config/m4/ucm.m4, configure.ac, src/ucm/mmap/install.c, src/ucm/mmap/mmap.h, src/ucm/mmap/replace.c, src/ucm/util/log.h, src/ucm/util/reloc.c, src/ucm/util/reloc.h, src/ucm/util/sys.c
=> UCM/CONFIG: Fixing mmap symbols override.

doc/CodeStyle
=> DOC: Update CodeStyle

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/rma/basic_rma.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup.c
=> UCP: Fix recursive call to ucp_worker_progress().

config/m4/compiler.m4, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.c, src/ucs/arch/x86_64/cpu.h, src/ucs/sys/compiler.h, src/ucs/sys/init.c, src/ucs/sys/preprocessor.h
Fixes https://github.com/openucx/ucx/issues/559
@yosefe @miked-mellanox could you please comment
=> UCS: Add CPU detection check

src/tools/perf/libperf.c, src/tools/perf/libperf.h, src/tools/perf/perftest.c, src/tools/perf/uct_tests.cc
@yosefe 
- progress requestor only once per 16 sends instead of every send
- command line option to choose async progress mode
=> TOOLS/PERF: perfomance optimizations

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_ud.cc
=> UCT/UD: fixes problem with the allocation of reserved skbs

src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, test/gtest/uct/test_ud.cc, test/gtest/uct/test_ud_pending.cc, test/gtest/uct/ud_base.cc, test/gtest/uct/ud_base.h
@yosefe @brminich please take a look
=> UCT/UD: simple AI/MD congestion avoidance

src/uct/sm/mm/mm_iface.h
Signed-off-by: Pavel Shamis (Pasha) <pashareserch@gmail.com>
=> MM: Adding padding between head/tail

src/ucs/arch/aarch64/bitops.h, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/cpu.h
=> UCS: Adding support for ARM64

contrib/test_jenkins.sh, test/examples/active_message.c
- device and transport names are mandatory parameters now
- added make installcheck to test_jenkins to keep the test compilable
- test is invoked in test_jenkins.sh to keep consistency with UCX API
=> Fixed inconsistencies and compile errors in active_message example

src/uct/sm/cma/cma_ep.c
Apparently CMA support in Ubuntu 15.10 is broken. For large message sizes it
may end-up transferring only a sub-block of iovec entry, even so it is
not supposed to break it in the middle. This patch adds more detail error
reporting, which helps identify problematic systems.
Signed-off-by: Pavel Shamis (Pasha) <pashareserch@gmail.com>
=> CMA: Improvement for CMA error reporting

src/uct/ib/ud/base/ud_ep.c, test/gtest/uct/test_ud.cc
@yosefe 
send ack_req before going into full resend mode
=> UCT/UD: resend optimization

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/base/ib_verbs.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c
@yosefe 
pick up to UCT_IB_WC_MAX completions
=> UCT/UD: accell poll optimization

src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/base/ud_inl.h, src/uct/ib/ud/verbs/ud_verbs.c
=> ud am_zcopy implementation

contrib/test_jenkins.sh
This change will allow to use newer version of doxygen.
=> CONTRIB: added module for newer doxygen version

src/uct/ugni/smsg/ugni_smsg_iface.c
Last bit of SMSG for now. Each invocation of progress will totally drain the completion queues before moving on.
=> UCT/UGNI/SMSG Drain entire smsg queue

src/uct/Makefile.am, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_pd.c, src/uct/ib/base/ib_pd.h
Silence error about ibv_fork_init when MPI_INIT did not do it but allready created qpairs
=> Silence error about ibv_fork_init when MPI_INIT did not do it 

src/uct/ib/base/ib_verbs.h, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/base/ud_log.c, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_ud_ds.cc
=> UCT/UD: use separate device/iface/ep adresses instead of sockadrr

src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/ud/base/ud_iface.c, test/gtest/uct/test_ud.cc
fixes bug in calculation of rx buffer length
@yosefe
=> UCT/IB: fixes max segment size calculation

src/ucp/amo/basic_amo.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/proto/proto.h, src/ucp/proto/proto_am.inl, src/ucp/rma/basic_rma.c, src/ucp/tag/eager.h, src/ucp/tag/eager_snd.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_send.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/stub_ep.c, src/ucp/wireup/stub_ep.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/ucs/arch/atomic.h, src/ucs/datastruct/notifier.c, src/ucs/datastruct/notifier.h
See https://github.com/openucx/ucx/wiki/Connection-establishment
Fixes #521 and #497
=> UCP: Add support for endpoints using multiple transports.

src/tools/perf/libperf.c, src/ucp/api/ucp.h, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_rkey.c, test/gtest/ucp/test_ucp_mmap.cc
-Also fixed libperf issue (to avoid segfaults)
=> UCP:Support for zero size memory registration

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/Makefile.am, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/uct/test_rc_flow_control.cc
- basic FC protoicol infrastructure
- FC support for rc (mlx4_0)
- basic test
=> UCT: Flow control for RC transport

src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/test_rc_flow_control.cc
=> UCT: Flow control for mlx5

contrib/test_jenkins.sh, test/examples/ucp_hello_world.c
Signed-off-by: Ilya Nelkenbaum <ilyan@mellanox.com>
=> TEST/EXAMPLES: Add UCP hello world example

src/ucp/tag/probe.c, test/gtest/ucp/test_ucp_tag_probe.cc
=> UCP: Fix for #784 (wrong len returned by probe)

test/gtest/uct/test_rc_flow_control.cc
=> UCT: FC test fix

src/ucs/arch/aarch64/cpu.h
Fix for #780.  The issue was discovered using test_callbackq.threads unit test
=> UCS: Using "stronger" barrier

src/uct/ib/ud/base/ud_inl.h
new skb is put on cache if cache is empty.
@yosefe
=> UCT/UD: uct_ud_iface_get_tx_skb doc update and small fix

test/gtest/ucp/test_ucp_mmap.cc, test/gtest/uct/test_ud_ds.cc
=> GTEST: compilation fixes

src/uct/Makefile.am, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.h, src/uct/ib/base/ib_verbs.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_rc_flow_control.cc, test/gtest/uct/uct_test.h
=> UCT/IB: preparation for DC transport

contrib/upload_docs.sh
=> CONTRIB: Add script to upload ucx.pdf to wiki.

contrib/test_jenkins.sh, doc/doxygen/ucxdox, src/ucp/api/ucp.h, src/ucp/core/ucp_worker.c, test/examples/Makefile.am, test/examples/ucp_hello_world.c
1. Added additional modes for ucp_hello_world
2. changed command line switches in ucp_hello_world test
3. changed test_jenkins.sh due to new command line of the test
4. changed ucp_worker_wait function (added ucp_worker_arm in the body)
5. added rpath for the build procedure of the hello_world tests
Fixes #797 and #798
=> ucp_hello_world changes

src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/ud/base/ud_inl.h, src/uct/sm/mm/mm_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.c, src/uct/ugni/udt/ugni_udt_ep.c, test/gtest/uct/test_rc_flow_control.cc, test/gtest/uct/test_stats.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
=> UCT/RC: Add statitiscs and enable/disable config for RC flow control.

config/m4/ib.m4, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c
=> UCT/IB/RC: Fix atomic endianness for ConenctX-4 devices.

src/uct/ib/base/ib_device.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs_iface.c
=> UCT/RC: fixes cqe leak

src/ucp/core/ucp_context.c, src/uct/Makefile.am, src/uct/api/uct.h, src/uct/self/self_ep.c, src/uct/self/self_ep.h, src/uct/self/self_iface.c, src/uct/self/self_iface.h, src/uct/self/self_md.c, src/uct/self/self_md.h
Loop-back skeleton for stability test and am_short implemented
=> UCT/Loop-back: Initial implementation

test/gtest/uct/test_p2p_err.cc
Fixes [#838](url https://github.com/openucx/ucx/issues/838)
=> Minor bug in test_p2p_err fixed. Issue #838

src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/Makefile.am, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_rc.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
=> UCT/RC/TEST: Fix configuration for maximal number of WRs.

src/uct/Makefile.am, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/dc/verbs/dc_verbs.h, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/Makefile.am, test/gtest/ucp/ucp_test.h, test/gtest/uct/test_dc.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/uct_test.h
=> UCT/DC: initial implementation

test/gtest/uct/test_pending.cc
issue https://github.com/openucx/ucx/issues/859
@yosefe
=> GTEST: fixes hung in pending_fairness test

test/gtest/uct/test_pending.cc
=> TEST/PENDING: Fix fairness test to retry adding to pending.

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_inl.h
=> UD: Fix flush - avoid adding ctl_op to arbiter while processing pending.

test/gtest/uct/test_flush.cc
- uct_flush_test changed to use sender()/receiver() functions instead
class variables
- timeouts added for potential hung loops (gtest mustn't hung)
Ignored for this PR
- found ud_mlx5/uct_flush_test.am_pending_flush_nb failed from time to
time. This was a gtest hung without timeout. The issue is in progress
loop at line test_flush.cc:354 (currently with timeout)
=> TEST/FLUSH: enable flush test on self transport

src/ucs/datastruct/callbackq.c, src/ucs/datastruct/callbackq.h, test/gtest/ucs/test_callbackq.cc
- New API for adding slow path callbacks to the callback queue.
The number of such callbacks is not limited (maintained by ucs_queue_t).
- Tests update
TODO: Implement safe remove for slow path callbacks
=> UCS: Slow path callback queue

src/ucs/config/parser.c, src/ucs/config/types.h, test/examples/Makefile.am
- Based on Rafi PR 902
- Check for compilation of ucp_hello_world added to jenkins
=> UCS: padded warning fix

config/m4/ib.m4, src/ucp/api/ucp.h, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/cm/cm_iface.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, test/examples/ucp_hello_world.c, test/gtest/uct/test_ib.cc, test/gtest/uct/test_uct_perf.cc
currently only for the ud (verbs) transport.
related to https://github.com/openucx/ucx/issues/193
=> UCT/IB - added support for RoCE.

src/ucm/malloc/malloc_hook.c, src/ucs/debug/debug.c, src/uct/base/uct_iface.c, test/gtest/ucm/malloc_hook.cc
Fix coverity errors appeared after migrating to version 8.5
=> UCS/UCM/UCT/GTEST: Coverity errors fix

config/m4/ucs.m4
=> Adding configure check for cntvct_el0

config/m4/ucs.m4, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.h
=> Providing a configuration option that let's set the default cache line size

config/m4/ib.m4, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/ucs/test_hash_perf.cc, test/gtest/uct/test_fence.cc
=> IB/DC/RC: improve performance of atomic ops

src/ucp/core/ucp_context.c
=> UCP: adds dc_x alias

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/stub_ep.c, src/ucp/wireup/wireup.c, src/ucs/sys/sys.c, src/ucs/sys/sys.h, test/gtest/common/test.h, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_fence.cc, test/gtest/ucp/test_ucp_memheap.cc, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> UCP: Flush endpoints as part of the disconnect process

contrib/test_jenkins.sh, src/tools/info/proto_info.c, src/tools/info/tl_info.c, src/tools/info/ucx_info.c, src/tools/info/ucx_info.h, src/ucp/api/ucp.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/wireup.c
=> UCP/INFO: Print UCP context, worker, and endpoint info.

config/m4/ib.m4, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5.h, src/uct/ib/ud/verbs/ud_verbs.c
=> UCT/UD/MLX5: Set AV.GRH segment if needed.

test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_fence.cc, test/gtest/ucp/test_ucp_memheap.cc, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> TEST: Progress all entities while disconnecting.

test/gtest/uct/test_ud.cc
=> TEST/UD: Fix compilation.

test/gtest/uct/test_ud.cc
=> TEST/UD: Fix UD ca_md, crep_drop, and ca_ai tests

src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
=> UCT/IB/RC/VERBS: Make support of zero copy APIs in rc_verbs

src/uct/sm/base/sm_iface.h, src/uct/sm/cma/cma_ep.c, src/uct/sm/cma/cma_iface.c
Related Issue #951
@shamisp Could you please take a look?
=> UCT/SM/CMA Make support of zero copy APIs in sm_cma

src/uct/ib/ud/verbs/ud_verbs.c
=> UD/VERBS: Avoid passing empty SGE entry.

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_verbs.h, src/uct/ib/ud/accel/ud_mlx5.c
=> UCT/IB/UD/MLX5: CQE size fixes.

src/uct/ib/base/ib_iface.c
=> UCT/IB/WAKEUP: Split CQ in wakeup_arm

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_inl.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/ib/ud/verbs/ud_verbs.h, src/uct/sm/base/sm_iface.h, src/uct/sm/cma/cma_ep.c, src/uct/sm/cma/cma_iface.c
=> UCT/IB/UD/VERBS: Make support of zero copy APIs in ud_verbs

src/uct/sm/knem/knem_ep.c, src/uct/sm/knem/knem_iface.c
=> UCT/SM/KNEM: Make support of zero copy APIs in sm_knem

src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/sm/cma/cma_ep.c
=> UCT/RC/CMA: Performance improvements in release

src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/verbs/rc_verbs_common.h
Related Issue #951
@shamisp Could you please take a look?
=> UCT/IB/DC/VERBS: Make support of zero copy APIs in dc_verbs

src/uct/ib/mlx5/ib_mlx5.h
=> IB: Adding restricted to uct_ib_mlx5_inline_copy

src/uct/api/uct.h
=> UCT/API: Documentation fix for am_zcopy

src/uct/ib/mlx5/ib_mlx5.h
=> IB: Adding support for Neon

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c
Related Issue #951
DC and RC are combined into one PR due to many common functions used.
=> UCT/RC/DC/MLX5: Make support of zero copy APIs in rc_mlx5 and dc_mlx5

configure.ac, debian/control.in, src/ucs/Makefile.am, src/ucs/arch/aarch64/cpu.h
Bug fixes for bugs discovered with Jenkins. 
=> Bug fixes for Jenkins on ARM

config/m4/knem.m4, config/m4/xpmem.m4
* Help message update for knem
* XPMEM autodetect code
=> AUTOTOOLS: minor updates for configure scripts

src/uct/ib/base/ib_iface.h, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/ud/accel/ud_mlx5.c
=> UCT/UD/MLX5: Make support of zero copy APIs in ud_mlx5

src/uct/base/uct_iface.h, src/uct/ugni/rdma/ugni_rdma_ep.c
=> UCT/UGNI: Localize CHECK_PARAM_IOV to finalize UCT zcopy support.

test/examples/ucp_hello_world.c
=> EXAMPLES: Add custom buffer size for UCP example.

src/uct/ugni/base/ugni_ep.c, src/uct/ugni/base/ugni_ep.h, src/uct/ugni/base/ugni_iface.c, src/uct/ugni/base/ugni_iface.h, src/uct/ugni/rdma/ugni_rdma_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.h, src/uct/ugni/udt/ugni_udt_iface.h
Long overdue patch to make UGNI understand flush callbacks.
=> UCT/UGNI/BASE Implement flush callback for UGNI eps.

test/gtest/uct/test_ib.cc, test/gtest/uct/test_wakeup.cc
This fix related to build procedure failed. Addressed comments in #1044 
@MattBBaker Could you please take a look?
=> UCT/TESTS: Wakeup tests fix for ugni

test/gtest/ucp/test_ucp_wireup.cc
=> TEST/WIREUP: Fix compilation on gcc 6.1.0

src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.h, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/base/ud_inl.h
Just trailing spaces clean-up. No other changes.
=> UCT/IB: Code style. Trailing spaces removed only

src/ucp/Makefile.am, src/ucp/api/ucp.h, src/ucp/core/ucp_request.h, src/ucp/dt/dt_iov.c, src/ucp/dt/dt_iov.h, src/ucp/proto/proto_am.inl, src/ucp/tag/eager_snd.c, src/ucp/tag/match.h, src/ucp/tag/tag_send.c, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_xfer.cc
Related Issue #951
Several tests added
=> UCP/IOV: Add support of iovec APIs with bcopy.

test/gtest/uct/test_flush.cc
=> TEST/FLUSH: Fix counting active messages - pending should be counted too

Makefile.am, config/m4/mpi.m4, src/tools/perf/Makefile.am, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_memheap.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_probe.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
HAVE_MPI checks just for the mpirun and not mpicc.
While typically distro provides both binaries, typically
these are distributed with two different packages.
In this case we have to use already existing MPICC
Signed-off-by: Pavel Shamis (Pasha) pasharesearch@gmail.com
=> Test fixes and enhancements

src/ucp/dt/dt_iov.c, src/ucp/dt/dt_iov.h, src/ucp/tag/eager_snd.c, src/ucp/tag/match.h, src/ucp/tag/tag_recv.c, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_tag_xfer.cc
=> UCP/IOV: Add support of iovec APIs with receive

src/ucp/core/ucp_request.h, src/ucp/proto/proto_am.inl, src/ucp/tag/eager_snd.c, src/uct/ugni/smsg/ugni_smsg_ep.c
Fix the bug in offset handling in case of error in bcopy algorithm in PR #1072 
Related Issue #951 
@MattBBaker please review (changes are based on your proposal. Thank you for this.)
=> UGNI/IOV: Fix bcopy_multy algo

src/ucp/api/ucp.h, src/ucp/wireup/address.h, src/uct/api/uct.h
Fixed a bunch of typos in the documentation
=> UCT/UCP: Documentation fixes

src/ucs/debug/profile.c, src/ucs/debug/profile.h
This would fix bogus failures in profile unit test, if case other places in UCX are also profiled.
=> UCS/PROFILE: Reset location records during global cleanup.

configure.ac, contrib/configure-devel, contrib/configure-release-mt, contrib/valgrind.supp, src/ucp/amo/basic_amo.c, src/ucp/api/ucp.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/rma/basic_rma.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/probe.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_send.c, src/ucs/datastruct/mpool.inl, src/ucs/type/spinlock.h, test/gtest/Makefile.am, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_mt.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Revert field mask name UCP_CONTEXT_ATTR_REQUEST_SIZE to UCP_ATTR_REQUEST_SIZE.
=> Add basic MT support to UCP level.

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_wakeup.cc, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_ud.cc, test/gtest/uct/test_ud_pending.cc, test/gtest/uct/test_wakeup.cc, test/gtest/uct/ud_base.h
=> UCT/UD/wakeup: Make wakeup interface support in UD

config/m4/sysdep.m4
This PR fixes #1155 
Related PR is #1153
=> UCT/MD: Fix configure time msg in NUMA support

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/rma/basic_rma.c
@yosefe please take a look at the refactoring
refactor put/get and put/get nbi code to support zcopy and to use
common code during progress and pending op processing.
=> UCP/RMA: Refactoring, unite blocking/nbi flows

src/tools/info/tl_info.c, src/tools/perf/libperf.c, src/ucp/api/ucp.h, src/ucp/core/ucp_worker.c, src/ucs/Makefile.am, src/ucs/type/cpu_set.h, src/uct/api/uct.h, src/uct/ib/base/ib_iface.c, test/examples/active_message.c, test/gtest/Makefile.am, test/gtest/ucs/test_type.cc, test/gtest/uct/uct_test.cc
UCP/API: Added  worker_params value to ucp_worker_create()  …
Added cpu_set to worker_params
=> UCP/API: Add CPU affinity support to UCP worker

src/uct/ib/dc/base/dc_iface.c, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/Makefile.am, test/gtest/uct/test_rc.cc, test/gtest/uct/test_rc.h
- Only Hard requests will be used/handled by DC, so it should use another handler for FC messages
- Some basic changes addressing FC for DC
=> UCT/RC: DC flow control preparation

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/proto/proto_am.inl, src/ucp/rma/basic_rma.c, src/ucp/tag/eager_snd.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_atomic.cc, test/gtest/ucp/test_ucp_memheap.cc, test/gtest/ucp/test_ucp_memheap.h, test/gtest/ucp/test_ucp_rma.cc
initial commit
@yosefe please take a look
=> RMA: zcopy support

test/gtest/uct/test_ud.cc
Fixes problems described in #1182
=> UCT/UD/GTEST: Fixes in UD tests

src/ucs/datastruct/arbiter.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, test/gtest/ucp/ucp_test.cc, test/gtest/uct/test_dc.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/test_uct_ep.cc
=> UCT/DC: fixes dci leak of ep pending queue

test/gtest/uct/test_ud.cc
=> TEST/UD: Fix ca_md test - make sure there are enough TX resources.

configure.ac, contrib/test_jenkins.sh
* Minor bugfix (mostly useful for OSX users)
* Adding jenkins test case for this build
=> DOCS: Fixing --with-docs-only

test/gtest/uct/test_ud.cc
Two tests remained to be sensitive to polling delays (i.e with valgrind). The correction corresponds to the other similar tests -  make sure the expected event occurred in a loop with relatively big timeout. 
crep_drop2 is also updated to check that TX win is really empty,
Fixes #1087
=> UCT/UD/GTEST: Fix a couple of UD tests

src/ucs/async/async.c, src/ucs/async/thread.c, src/ucs/time/timerq.h, test/gtest/ucs/test_time.cc
Fixes #1229 and recent failures in jenkins perftest
@shssf
=> Fixes for races in async infra

src/uct/ugni/base/ugni_ep.c, src/uct/ugni/base/ugni_ep.h, src/uct/ugni/base/ugni_iface.h, src/uct/ugni/udt/ugni_udt_ep.c, src/uct/ugni/udt/ugni_udt_ep.h, src/uct/ugni/udt/ugni_udt_iface.c, src/uct/ugni/udt/ugni_udt_iface.h
Rework of UDT layer so that it now does 'the right thing'. This is the bug free version.
=> UCT/UGNI/UDT: Rework to enable async callback support in UDT

contrib/ucx_perftest_config/test_types, src/tools/perf/libperf.c, src/tools/perf/libperf.h, src/tools/perf/libperf_int.h, src/tools/perf/perftest.c, src/tools/perf/ucp_tests.cc, src/tools/perf/uct_tests.cc, src/ucp/tag/tag_send.c, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_perf.cc
Implemented IOV list options in UCP part of the test
This is related to #951
=> PERF/UCP: IOV support in PERF UCP part

src/ucs/Makefile.am, src/ucs/arch/aarch64/cpu.h, src/ucs/datastruct/callbackq.c, src/ucs/datastruct/callbackq.h, src/ucs/datastruct/callbackq.inl, src/uct/base/uct_md.c, src/uct/sm/base/sm_iface.c, src/uct/sm/self/self_iface.h, test/gtest/ucs/test_callbackq.cc
config.h defines HAVE_HW_TIMER
=> UCS: HW timer detection bugfix

src/tools/info/proto_info.c, src/tools/info/tl_info.c, src/tools/info/ucx_info.c, src/tools/info/ucx_info.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.h, src/uct/api/uct.h, src/uct/cuda/cuda_iface.c, src/uct/ib/base/ib_iface.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_iface.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/mm_iface.c, src/uct/sm/self/self_iface.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c
This PR enhances the transport selection logic by taking job scale into consideration
=> UCT/UCP/TOOLS: Transport latency as function of number of connections.

contrib/ucx_perftest_config/test_types, src/tools/perf/libperf.c, src/tools/perf/perftest.c
Small fixes in documentation and datatype parameters assignment.
This is related to #951
=> PERF/UCP: IOV support in PERF UCP part. Fix documentation.

src/tools/perf/libperf.c
=> TOOLS/PERF: Fix invalid 'free' in perf/iov.

test/gtest/uct/test_dc.cc
- Use timeout for condition check, like in other tests
- Simplify the test itself
=> UCT/DC/GTEST: Simplify dci_leak test

contrib/valgrind.supp, src/ucm/malloc/malloc_hook.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/Makefile.am
=> Valgrind fixes

test/gtest/uct/test_dc.cc, test/gtest/uct/test_flush.cc, test/gtest/uct/test_rc.cc, test/gtest/uct/test_stats.cc, test/gtest/uct/uct_test.h
1) uct_flush_test fix. Fixes #1255 
2) uct_stats fix. Fixes #1274
=> UCT/GTEST: test fixes

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/dt/dt_iov.h, src/ucp/proto/proto.h, src/ucp/proto/proto_am.inl, src/ucp/rma/basic_rma.c, src/ucp/tag/eager_snd.c, src/ucp/tag/match.h, src/ucp/tag/rndv.c, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_tag_xfer.cc
This PR is related to #951 
This PR close #1179
=> UCP/IOV: Add support of iovec API with zcopy in eager protocol

src/ucp/Makefile.am, src/ucp/amo/amo.inl, src/ucp/amo/basic_amo.c, src/ucp/amo/nb_amo.c, src/ucp/api/ucp.h, src/ucp/core/ucp_request.h, test/gtest/ucp/test_ucp_atomic.cc, test/gtest/ucp/test_ucp_atomic.h
Non blocking AMO implementation I fleshed out.
=> UCP/AMO: Nonblocking AMO API and implementation

test/examples/ucp_hello_world.c
=> TEST/ucp_hello_world: ucx_init() parameters initialization

src/ucs/datastruct/mpool.c
=> UCS/MPOOL: Fix race condition with valgrind mpool destroy.

src/uct/sm/mm/mm_iface.c
=> MM: Fix deadlock in shared memory flush.

test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_p2p_rma.cc, test/gtest/uct/uct_p2p_test.cc, test/gtest/uct/uct_p2p_test.h, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
=> TEST: Fix p2p_am test - wait for active message to arrive.

src/ucp/rma/basic_rma.c
=> UCP/RMA: mem dereg optimization/code style

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_ud.cc
=> TEST/UD: Fix crep_drop2 test - validate connect after hook is restored.

src/ucp/core/ucp_mm.c, src/ucs/datastruct/mpool.c, src/ucs/debug/memtrack.c, src/ucs/sys/sys.c, src/uct/api/uct.h, src/uct/base/uct_mem.c, src/uct/sm/mm/mm_sysv.c, test/gtest/uct/test_mem.cc, test/gtest/uct/uct_test.cc
This PR is opened instead of https://github.com/openucx/ucx/pull/1303 because of splitting on different PRs for UCT and UCP. UCP part will be upstreamed after merge of this one.
@shssf , @brminich please review
=> UCT: add support fixed address for mmap

test/gtest/ucs/test_async.cc, test/gtest/ucs/test_datatype.cc, test/gtest/ucs/test_profile.cc, test/gtest/uct/test_uct_perf.cc
Fixes for some of the recent Jenkins test failures
=> TEST: Small test fixes for low CPU availability.

src/ucm/api/ucm.h, src/ucm/malloc/malloc_hook.c, src/ucm/mmap/install.c, src/ucs/sys/compiler.h, src/ucs/sys/compiler_def.h
Fix compilation for the OMPI and the user application with the UCM.
=> UCM/API: allow installed package compilation

test/gtest/uct/test_ib.cc
=> TEST/wakeup: fix issue 1337 (timeout enlarged)

src/ucp/core/ucp_ep.c, src/ucs/type/class.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, test/gtest/uct/test_dc.cc
=> Fix hang in dc flush

test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_probe.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
=> UCP: fix unexp stats test

contrib/test_jenkins.sh
- disable valgrind
- fix IB device enumeration
=> JENKINS: Fixes to make Jenkins run on ARM machine.

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_rkey.c, src/ucp/tag/tag_send.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c
=> UCP: Update RMA/AMO lane selection logic.

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucs/config/types.h, src/uct/Makefile.am
This fixes "Device all is not available" message
=> UCT/BUILD: Compile self transport regardless of knem.

src/uct/ugni/base/ugni_device.c
=> UCT/UGNI: Add new string.h include

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_worker.c, test/gtest/ucp/test_ucp_wakeup.cc, test/gtest/uct/test_ib.cc, test/gtest/uct/test_wakeup.cc
API for #1062 
@shssf @brminich @yosefe please take a look
=> UCP/WORKER: Add tx/rx wakeup events specification

config/m4/ib.m4, configure.ac, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_log.c, src/uct/ib/base/ib_log.h, src/uct/ib/base/ib_verbs.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/verbs/ud_verbs.c
=> UCT/IB/RC: tag matching infrastructure

src/uct/ib/cm/cm.h, src/uct/ib/cm/cm_iface.c
@yosefe
Use a slow callback to dispatch pending ops.
=> UCT/IB/CM: use slow callback

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h
=> Consider cpu-device proximity

src/ucp/api/ucp.h, src/ucp/core/ucp_worker.c, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/generic/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.h
Blocking API for waiting on memory update
=> UPC/API: Adding ucp_worker_wait_mem

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_def.h, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/common/test_helpers.h, test/gtest/ucs/test_async.cc, test/gtest/uct/test_error_handling.cc
=> UCT: DC error handling

src/ucs/sys/sys.c, src/ucs/sys/sys.h, test/gtest/uct/uct_p2p_test.cc
=> gtest memory allocation limit

test/gtest/ucp/test_ucp_perf.cc, test/gtest/uct/test_uct_perf.cc
Increase latency limit so test on ARM will pass.
=> UCT/GTEST: increase latency limit

src/uct/ugni/udt/ugni_udt_iface.c
When multi threading the UDT tear-down routine was found to be insufficiently robust. It is now.
=> UCT/UGNI/UDT: Fix iface cleanup

contrib/test_jenkins.sh, src/ucs/debug/memtrack.c, src/ucs/debug/memtrack.h, src/uct/base/uct_md.c, src/uct/sm/mm/mm_posix.c, test/gtest/common/test.cc
=> UCS/memtrack: resuscitation procedures

test/gtest/Makefile.am, test/gtest/uct/test_tag.cc, test/gtest/uct/test_ud.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
=> GTEST: add tag matching tests

test/gtest/common/test.cc
This PR is related to PR #1405 and fixes #1408
=> UCT/gtest: fixed signal handling

test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> TEST/TAG: Fix rndv test to wait for send completion.

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/ud/accel/ud_mlx5.c, test/gtest/uct/test_uct_ep.cc
=> UCT/IB/MLX5: Fix SRQ cleanup flow.

test/gtest/ucp/test_ucp_wakeup.cc, test/gtest/uct/test_ib.cc, test/gtest/uct/test_wakeup.cc
=> TEST/WAKEUP: Increase poll timeout to 1000 * time_multiplier().

src/uct/ib/base/ib_iface.c
=> Fix RoCE bandwidth estimation

src/ucp/core/ucp_request.inl, src/ucp/tag/eager_rcv.c, src/ucp/tag/rndv.c, src/uct/api/uct.h, src/uct/api/uct_def.h, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/sm/mm/mm_iface.c, src/uct/sm/self/self_ep.c, src/uct/ugni/udt/ugni_udt_iface.c, test/examples/uct_hello_world.c, test/gtest/uct/test_many2one_am.cc, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_tag.cc
=> UCT/UCP/API: align TM cb with new AM cb interface

config/m4/ib.m4, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
=> UCT/RC/VERBS: Added tag-matching rendezvous infrastructure.

src/uct/ib/rc/verbs/rc_verbs_common.h
@yosefe @brminich please take a look
=> IB/RC/VERBS: pass correct length when logging RX

src/uct/ib/cm/cm.h, src/uct/ib/cm/cm_ep.c, src/uct/ib/cm/cm_iface.c, test/gtest/uct/uct_test.cc
=> UCT/IB/CM: Fixes in flush flow.

src/ucp/core/ucp_request.inl, src/ucp/tag/eager_rcv.c, src/ucp/tag/match.h, src/ucp/tag/rndv.c, src/ucp/tag/tag_recv.c
=> UCP: Extract common code in tag matching.

config/m4/sysdep.m4, config/m4/ucs.m4
=> CONFIG: Removing zlib dependency

src/uct/api/tl.h, src/uct/api/uct.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/cm/cm_iface.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/sm/mm/mm_iface.c, src/uct/sm/mm/mm_iface.h, src/uct/sm/self/self_ep.c, src/uct/sm/self/self_iface.c, src/uct/sm/self/self_iface.h, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c, src/uct/ugni/udt/ugni_udt_iface.h
The main purpose of this PR is to support variable header lengths for the transport
=> UCT: Make uct_iface_release_desc more flexible

src/uct/ugni/base/ugni_ep.c, src/uct/ugni/base/ugni_ep.h, src/uct/ugni/udt/ugni_udt_ep.c, src/uct/ugni/udt/ugni_udt_ep.h, src/uct/ugni/udt/ugni_udt_iface.c
Cleaned up some bugs in how UDT cleaned up it's iface. This version should be Bug Free (TM).
=> UCT/UGNI/UDT: UDT iface cleanup hang fixes

src/uct/ib/base/ib_iface.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/ib/ud/verbs/ud_verbs.h, test/gtest/uct/test_error_handling.cc, test/gtest/uct/test_wakeup.cc
Also it should fix https://github.com/openucx/ucx/issues/1377
=> UCT/UD: error handling

src/uct/api/uct.h, src/uct/api/uct_def.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/base/uct_md.c, src/uct/cuda/cuda_iface.c, src/uct/ib/base/ib_iface.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/mm_iface.c, src/uct/sm/self/self_iface.c, src/uct/tcp/tcp_iface.c, test/gtest/uct/test_error_handling.cc, test/gtest/uct/uct_test.cc
Should be merged before https://github.com/openucx/ucx/pull/1432
[UCP patch](https://github.com/evgeny-leksikov/ucx/commit/e01b5a873f2203c51ce5e5ac81542474fc6a5c13) based on this one in [development branch ](https://github.com/evgeny-leksikov/ucx/tree/ucp_err_handle_cb)
=> UCT/API: add error handling callback

test/gtest/uct/test_pd.cc
=> TEST/UCT/MD: Add timeout to registration performance test.

src/uct/base/uct_iface.c, test/gtest/uct/test_error_handling.cc
=> UCT: allow to destroy EP from error handling callback

src/uct/api/uct_def.h, src/uct/base/uct_iface.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/test_tag.cc
=> UCT/RC/VERBS: tag matching RNDV support

src/uct/api/tl.h, src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/sm/self/self_ep.c, src/uct/sm/self/self_ep.h, src/uct/sm/self/self_iface.c
Separated from https://github.com/openucx/ucx/pull/1432
@yosefe pls, review
=> UCT/API: add uct_ep_check

src/uct/ib/rc/verbs/rc_verbs_iface.c
=> UCT/RC: fix TM RNDV unexpected callback

src/tools/perf/perftest.c
=> PERF: Removing unsupported option from help messages

src/uct/ugni/base/ugni_def.h, src/uct/ugni/base/ugni_ep.c, src/uct/ugni/base/ugni_ep.h, src/uct/ugni/base/ugni_iface.c, src/uct/ugni/base/ugni_types.h, src/uct/ugni/rdma/ugni_rdma_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.h, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_ep.c, src/uct/ugni/udt/ugni_udt_ep.h, src/uct/ugni/udt/ugni_udt_iface.c
Replace terrible previous hack with new right and proper implementation.
=> UGNI: Support EP flush with callbacks

src/ucs/async/async.c
=> UCS/ASYNC: Fix possible deadlock when removing event handler.

src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/stats/libstats.c, src/ucs/stats/libstats.h, src/ucs/stats/serialization.c, src/ucs/stats/stats.c, src/ucs/stats/stats_fwd.h, test/gtest/Makefile.am, test/gtest/ucs/test_stats_filter.cc
Add short counters report
wiki in:
https://github.com/openucx/ucx/wiki/Statistics
=> UCS/STATS: counters filter

src/ucs/sys/rcache.c, src/ucs/sys/rcache.h, src/uct/ib/base/ib_md.c, test/gtest/ucs/test_rcache.cc, test/gtest/uct/test_pd.cc
=> UCS/RCACHE: Fix rcache merge while mappings are modified.

src/ucm/util/sys.c, src/ucm/util/sys.h, src/ucs/sys/sys.c
=> UCS/UCM/SYS: Read /proc/self/maps fully into a buffer.

src/tools/perf/Makefile.am
=> TOOLS/PERF: Fix perftest compilation with CFLAGS.

src/tools/perf/libperf.c
Fix pingpong test bandwidth to be twice, as the traffic being sent
and receive.
=> TOOLS/PERF: ping pong test BW

src/ucp/core/ucp_worker.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h
- fix uninitialized UCT err handler in UCP
- increased UD timeout, fix variable name
=> UCX: fix #1462

src/ucs/stats/stats.c
=> UCS/STATS: missing lock

src/ucs/debug/debug.c
=> UCS/DEBUG: Allocate backtrace with mmap().

test/gtest/uct/test_ud.cc
=> TEST/UD: Fix test_ud.ca_md.

configure.ac
=> CONFIGURE: set the UCX version to v1.2.

src/uct/api/uct.h
@yosefe please review api spec
=> UCT: adds enable/disable progress API

src/ucp/tag/rndv.c, test/gtest/ucp/test_ucp_tag_match.cc
=> UCP: Fix RNDV truncated on receiver

src/ucp/core/ucp_context.c, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/base/uct_mem.c, src/uct/sm/cma/cma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c, test/gtest/uct/test_mem.cc
Add new memory allocation type.
=> UCT/BASE: Add THP mem allocation

src/uct/ib/ud/accel/ud_mlx5.c
Adding missing barrier in order to enforce the order of loads
=> IB/UD/MLX5: Fixing #1470

config/m4/compiler.m4, src/tools/info/Makefile.am, src/tools/perf/Makefile.am, src/tools/profile/Makefile.am, src/ucm/Makefile.am, src/ucp/Makefile.am, src/ucs/Makefile.am, src/uct/Makefile.am, test/apps/Makefile.am, test/gtest/Makefile.am, test/mpi/Makefile.am
Same change as in #1554 except for the master branch.
=> CONFIGURE: Bring in CFLAGS (v1.3)

config/m4/compiler.m4, src/tools/info/Makefile.am, src/tools/perf/Makefile.am, src/tools/profile/Makefile.am, src/ucm/Makefile.am, src/ucp/Makefile.am, src/ucs/Makefile.am, src/uct/Makefile.am, test/apps/Makefile.am, test/gtest/Makefile.am, test/mpi/Makefile.am
=> CONFIGURE: Bring in CFLAGS (v1.2)

test/gtest/uct/test_stats.cc
=> TEST/STATS: Wait for completion of atomic operation.

src/uct/base/uct_mem.c
=> UCT/BASE: madvise debug

src/ucp/core/ucp_worker.c
Fix error handling part of #1578
=> UCP: fix stup ep lookup in error handler

AUTHORS
fixes #1559 
picked from #1596
=> Add AUTHORS file (v1.2)

src/ucp/core/ucp_request.h, src/ucp/core/ucp_types.h, src/ucp/core/ucp_worker.c, src/ucp/proto/proto_am.c, src/ucp/tag/eager.h, src/ucp/tag/eager_rcv.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/tag_match.c, src/ucp/tag/tag_match.h, src/ucp/tag/tag_match.inl
=> UCP: TM offload sync send support

config/m4/ib.m4, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/base/ib_log.h, src/uct/ib/base/ib_verbs.h, src/uct/ib/cm/cm_iface.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_iface.c
=> UCT/RC/VERBS: makes HW tag matching use MOFED API

README
=> Remove outdated badge

src/ucs/sys/sys.c
=> UCS/SYS: THP sysfs parsing

src/uct/base/uct_worker.c, src/uct/base/uct_worker.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/ud/base/ud_ep.c, src/uct/sm/mm/mm_ep.c, src/uct/sm/mm/mm_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_ep.c
Fixes #1637 and should also fix ORNL failure
=> UCT: Add progress callbacks using thread-safe method.

test/gtest/uct/test_ud_slow_timer.cc
=> TEST/UD: Wait for a packet up to 10 sec.

src/uct/ib/base/ib_md.c, src/uct/ib/dc/accel/dc_mlx5.c, test/gtest/ucs/test_stats.cc, test/gtest/ucs/test_stats_filter.cc
=> IB/DC/TEST: Fix compilation with gcc 7.1

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_worker.c, src/ucp/wireup/stub_ep.c, src/ucp/wireup/stub_ep.h
Cherry-picked from https://github.com/openucx/ucx/pull/1475 + refactoring
@yosefe pls take a look, i addressed your comments regarding to the fix here
=> UCP: fix error handing on wireup

contrib/test_jenkins.sh, test/examples/ucp_hello_world.c
Do not merge before https://github.com/openucx/ucx/pull/1461
=> UCP/EXAMPLE: add error handling in ucp_hello_world

config/m4/compiler.m4, config/m4/knem.m4, configure.ac, test/gtest/ucp/test_ucp_wakeup.cc
Made the autoconf files more robust.
=> CONFIGURE: Fixes several places where CFLAGS was being rewritten.

.gitignore, Makefile.am, configure.ac, ucx.spec.in
Rework existing rpm spec to follow Fedora's requirements.
=> Prepare UCX rpm for Fedora packaging

Makefile.am, ucx.spec.in
The review process is in Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1474033.
=> rpm: comply Fedora guidelines

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/common/test_helpers.h, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
- fixes rc (verbs/mlx5) and dc (verbs/mlx5)
=> UCT/IB: fix CQ credit counting on error handling

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/stub_ep.c, src/ucp/wireup/wireup.c, src/uct/ib/base/ib_iface.c, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_tag_perf.cc, test/gtest/ucp/test_ucp_tag_probe.cc, test/gtest/ucp/test_ucp_wakeup.cc
addresses #1318 
This PR disables progress for unused uct_iface's, including auxiliary ifaces used only for wireup.
=> UCP/TEST: Adaptive progress optimization.

src/ucp/api/ucp.h, src/ucp/core/ucp_rkey.c, test/gtest/ucp/test_ucp_mmap.cc
@yosefe @shamisp  please review
=> UCP: adds ucp_rkey_ptr()

src/ucp/api/ucp_version.h.in, test/gtest/ucp/ucp_test.h
=> UCP: fixes problem with UCP_VERSION macro

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.h, src/ucp/proto/proto_am.inl, src/ucp/tag/eager.h, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_send.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_inl.h
Also fixes UCT/UD error handling according to correct usage of comp counter in UCP
fixes https://github.com/openucx/ucx/issues/1669
=> UCP: align UCT completion usage in protocols

src/ucp/tag/offload.c
=> UCP: fixes hand in tm offload

src/ucp/tag/offload.c, src/uct/api/uct.h, src/uct/ib/rc/verbs/rc_verbs_iface.c
@yosefe 
Add max_zcopy for receive operation
Add max_outstanding for receive operations.
=> UCT/API: Update UCT iface tag caps

src/ucp/tag/rndv.c
Fixes https://github.com/openucx/ucx/issues/1754
=> UCP: fix RNDV early completion.

test/gtest/uct/test_p2p_err.cc
This fixes a test failure on ppc64le
=> TEST/UCT: Make sure the address passed in error check tests is invalid.

src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/types.h, src/ucs/debug/log.c, src/ucs/debug/log.h, src/ucs/sys/sys.c, test/gtest/Makefile.am, test/gtest/ucs/test_log.cc
=> UCS: add ucs_print()

src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/rndv.c, src/ucp/tag/rndv.h
=> UCP: hw tm: optimize RNDV for large messages

src/ucp/tag/offload.c, src/ucp/tag/rndv.c
=> UCP: fixes problem in HW TM rndv

src/ucp/core/ucp_worker.c
- function ucp_worker_wakeup_pipe_write renamed
to ucp_worker_wakeup_signal_fd for betted fit to
implementation
=> wakeup: function ucp_worker_wakeup_pipe_write renamed

src/uct/ib/base/ib_md.c
=> UCT/IB: add ibv_dereg_mr profiling

src/ucs/sys/rcache.c, src/ucs/sys/rcache.h, src/ucs/sys/sys.c, test/gtest/ucs/test_rcache.cc
=> UCS/RCACHE: optimize region merging

contrib/test_jenkins.sh, src/ucm/malloc/malloc_hook.c, src/ucm/ptmalloc286/malloc.c, test/gtest/common/test_helpers.cc, test/gtest/ucm/malloc_hook.cc
@yosefe please take a look
Take trim and mmap threshold values from
MALLOC_TRIM_THRESHOLD_
MALLOC_MMAP_THRESHOLD_
=> UCM: support setting trim and mmap thresholds via env variables

src/ucp/api/ucp.h
This API/DOC change is separated from https://github.com/openucx/ucx/pull/1822
=> UCP/API/DOC: enum ucp_ep_close_mode

ucx.spec.in
(cherry picked from commit 3346cfa06a865264370989879255865e10b7b2c2)
=> rpm: restore default BuildRoot value

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
=> UCT/DC: preparations for the hw tag matching

src/ucp/core/ucp_ep.c, src/ucp/tag/eager.h, src/ucp/tag/eager_snd.c, src/ucp/tag/rndv.c, test/gtest/ucp/test_ucp_peer_failure.cc
=> UCP/TAG: Fix error handling for pending zero-copy reqeusts.

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/accel/dc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c
- added processing of GRH to DC MLX5 transport
- removed limitations on local connection only
=> uct/dc_mlx5: added procesing of GRH

config/m4/ucm.m4, test/gtest/ucm/malloc_hook.cc, test/gtest/ucs/test_log.cc
- fixed potential issue reported by gcc 7.1.1
- added configuration scripts to skip tests on
malloc state API is unavailable
this is fix for issue: https://github.com/openucx/ucx/issues/1779
=> TEST: fixed compilation by gcc 7.1.1

test/gtest/ucp/test_ucp_stream.cc
- fixed compilation of ucp_stream test
=> TEST/UCP/stream: fixed compilation

src/ucp/core/ucp_worker.h, src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/rndv.c, src/ucp/tag/tag_match.c, test/gtest/ucp/test_ucp_tag_match.cc
=> GTEST: set threshold in tag matching tests

src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c
@yosefe @alinask please take a look
=> UCT/SM/CMA: update expected memory bandwidth

contrib/test_jenkins.sh, src/uct/ib/ud/base/ud_iface.c
=> UCT/UD: Fix assert compilation issue with O0

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup_ep.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/ucp/ucp_test.cc, test/gtest/uct/ib/test_dc.cc
Pls, review API and DOC change in separated PR https://github.com/openucx/ucx/pull/1823
=> UCP/UCT: ucp_ep_close implementation over uct_ep_flush

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.h
- added processing of GRH to dc_verbs & dc_mlx5 TL's
=> UCT/FC: added processing of GRH to DC Flow Control

src/ucp/tag/offload.h, test/gtest/ucp/test_ucp_tag_xfer.cc
=> UCP: fixes #1862 HW TM + ERR handling bug

src/uct/ib/base/ib_iface.c, src/uct/ib/cm/cm_iface.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c
=> UCT/IB: Detect 50g Eth speed.

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/tag/offload.c, test/gtest/ucp/test_ucp_wakeup.cc, test/gtest/uct/test_tag.cc
* Check for stub ep when RNDV arrives
* Activate iface if it is used for tag offload
=> UCP/GTEST: HW TM fixes

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, test/gtest/Makefile.am, test/gtest/uct/ib/test_cq_moderation.cc
- added CQ moderation configuration to recv CQ
- minor code refactoring to avoid code duplication
- changed default moderation parameters
=> UCT: extended CQ moderation to RX cq

src/ucp/core/ucp_worker.c, src/ucp/stream/stream_recv.c
API functions ucp_stream_worker_poll and ucp_stream_recv_nb are not
implemented yet
=> UCP/Stream: fix unresolved symbols

src/tools/perf/libperf.c, src/tools/perf/libperf_int.h, src/tools/perf/ucp_tests.cc, test/gtest/ucp/test_ucp_perf.cc
=> TOOLS/PERF: support outstanding (-O) requests in ucp tests

test/gtest/ucp/test_ucp_peer_failure.cc
=> TEST/UCP: Fix checking send request status after failure.

src/ucs/sys/rcache.c
=> UCS/RCACHE: Fix race condition in rcache region put.

src/ucp/amo/amo.inl, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/proto/proto_am.c, src/ucp/proto/proto_am.inl, src/ucp/rma/basic_rma.c, src/ucp/rma/flush.c, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup_ep.c
=> UCP/REQUEST: unite send.state (uct_comp + dt)

src/ucp/stream/stream_send.c, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> GTESTS: add send IOVs testing in test_ucp_stream

src/ucs/sys/rcache.c, src/ucs/sys/rcache.h, test/gtest/ucs/test_rcache.cc
=> UCX/RCACHE: Fix early rcache invalidation.

src/tools/info/build_info.c, src/ucs/async/pipe.h, test/gtest/uct/ib/test_ud_pending.cc, test/gtest/uct/ib/test_ud_slow_timer.cc, test/gtest/uct/ib/ud_base.h, test/mpi/shmem_pingpong.c
(cherry picked from commit e38c6918015c8dc7cdeb342481e014056f04ea3d)
=> FIX: fix license in several files

src/uct/ib/ud/base/ud_ep.c
Should fix a valgrind error seen in #1946
=> UCT/UD: Fix uninitialized skb->flags

src/tools/perf/ucp_tests.cc
The bug affected numbers for small number of iterations
=> TOOLS/PERF: fix measurement of UNI window

src/uct/api/uct.h, src/uct/api/uct_def.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/cm/cm_ep.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/ud/accel/ud_mlx5_common.c, src/uct/ib/ud/verbs/ud_verbs.c
- added traffic class support: UCX_IB_TRAFFIC=num to set traffic class
- minor refactoring of calls of AH creation API
- added calls to init ah_attr object
=> UCX/IB: added traffic class support + refactoring of AH creation

src/uct/rocm/rocm_common.c
Just a small changes to fix a build issue with latest ROCM releases
=> UCT/ROCM : Fix a build issue

src/ucs/sys/sys.c
sysconf return value -1 does not necessary mean an error. For max/min
values it may mean that the value is undefined. According sysconf man
pages the right way to check for an error is to verify that errno value
was not changed. Also, we should not convert the value to unsigned, but
let the upper layer to handle undefined values for min/max variables.
On Ubuntu 17.10 _SC_IOV_MAX value is undefined and this leads
to a failure in gtest.
=> UCX: Fixing error handling for sysconf call

src/ucs/stats/client_server.c
=> Backport #1952

src/ucs/arch/aarch64/cpu.h
=> Backport #1848

src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/base/dc_iface.h, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/mlx5/ib_mlx5_log.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_common.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c
Fixes IB part of https://github.com/openucx/ucx/issues/1956
=> UCT/IB: pass error status thru handle_failure and set_ep_failed

src/uct/Makefile.am, src/uct/cuda/gdr_copy/gdr_copy_ep.c, src/uct/cuda/gdr_copy/gdr_copy_ep.h, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.h, src/uct/cuda/gdr_copy/gdr_copy_md.c, src/uct/cuda/gdr_copy/gdr_copy_md.h
- copy from system memory to cuda memory using gdr copy utility
- gdr copy (https://github.com/NVIDIA/gdrcopy)
=> UCT/CUDA/GDR_COPY:   gdr copy uct

contrib/test_jenkins.sh, contrib/valgrind.supp, src/ucs/debug/debug.c, src/ucs/type/status.c, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h
=> Backport fixes from master to v1.2.x

Makefile.am, NEWS, configure.ac, contrib/test_jenkins.sh, src/tools/perf/Makefile.am, test/examples/Makefile.am, ucx.spec.in
Changes were approved on the review: https://bugzilla.redhat.com/show_bug.cgi?id=1474033
=> RPM: follow Fedora guidelines in rpm spec

contrib/test_jenkins.sh, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c
- Backport DGID packet filtering for RoCE from 1.3/master
- Add debug build to Jenkins (needed to check static assertions with O0)
=> UCT/UD: Backport DGID packet filtering

src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
Move connections related TM stuff to RC level
=> UCT/RC: TM preparations for accelerated tls p2

src/tools/info/type_info.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/accel/dc_mlx5.h, src/uct/ib/dc/base/dc_ep.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c
@yosefe please assign a reviewer
Signed-off-by: Alex Mikheev <alexm@mellanox.com>
=> UCT/DC_MLX5: reduce ep size if grh is not used

src/ucp/api/ucp.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl
Similar to `ucp_tag_recv_request_test`
=> UCP/API/STREAM: add ucp_stream_recv_request_test

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_types.h, src/ucp/core/ucp_worker.c, src/ucp/stream/stream.h, src/ucp/stream/stream_recv.c, src/ucp/tag/tag_recv.c, src/ucs/sys/compiler.h
- add ucp_stream_recv_nb implementation
- add a helper macro for address arithmetic `UCS_PTR_BYTE_OFFSET` which can be used for https://github.com/openucx/ucx/issues/1982
=> UCP/STREAM: add ucp_stream_recv_nb

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/tag/rndv.c
- added mem-pool datatype for rndv remote key
- access to request/rkey is wrapped by inline calls
=> UCP/RNDV: added multiple rkeys on recv side

src/ucp/core/ucp_context.c
=> UCP: add dc/dc_mlx5 transports to the ib alias

src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/ud/accel/ud_mlx5.c
=> UCT/UD_ACCEL: fix calc of max short am threshold

test/gtest/ucp/test_ucp_wireup.cc
=> TEST/WIREUP: Make test pass on machine with large number of devices.

test/gtest/ucp/test_ucp_fence.cc
=> TEST/FENCE: Do not connect back from receiver to sender.

test/gtest/uct/ib/test_cq_moderation.cc
- fix for https://github.com/openucx/ucx/issues/2033
- increased event moderation limit
=> UCT/CQ-MODERATION: fixed test

src/ucp/core/ucp_rkey.c, src/ucs/sys/math.h, test/gtest/ucs/test_math.cc
- some cosmetic helper to simplify MD's enumeration
=> UCP/MD: added syntax sugar to enumerate MD in map

src/ucp/rma/basic_rma.c, test/gtest/ucp/test_ucp_peer_failure.cc
=> UCP/RMA: complete failed RMA request

test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_stream.cc
Add IOV testing in many2one tests
=> GTEST/STREAM: parameterize datatype in test_ucp_stream_many2one

src/ucp/core/ucp_worker.c, src/ucp/wireup/wireup_ep.c
=> UCP/ERR: Fix error handling with multiple wireup proxies.

test/gtest/Makefile.am, test/gtest/ucs/test_obj_size.cc
- added static asserts on sizeof key objects
=> UCX: added static evaluations for object size

src/ucp/core/ucp_request.c
- corrected registration memory flags
=> UCP/RNDV: changed registration flags

test/gtest/uct/test_p2p_am.cc
=> TEST/UCT: Fix AM_DUP check in uct_p2p_am_test.am_bcopy test

src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/knem/knem_md.c, src/uct/sm/knem/knem_md.h
- added caching of registration memory for KNEM TL
=> UCT/KNEM: added rcache support

src/ucp/wireup/select.c
- added selection mode to select all available lanes
=> UCP/WIREUP: select all available RMA BW lanes

src/ucp/tag/eager_rcv.c
=> UCP: add profiling to eager tag recv

src/uct/base/uct_mem.c
=> UCT/MEM: Don't print error message if madvise(HUGEPAGE) fails.

test/gtest/uct/ib/test_dc.cc, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h
=> GTEST/UCT: Fix FC tests

src/uct/base/uct_iface.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
=> UCT/TCP: Fix iface flush

src/uct/ib/ud/base/ud_def.h
=> UCT/UD: Fix clang5 compilation

src/ucs/async/signal.c
=> UCS/ASYNC/SIGNAL: Add lock around signal handler modification.

src/ucp/wireup/select.c
- do not allow multiple connections for same MD
=> UCP/WIREUP: filter connections by MD index

test/gtest/ucs/test_hash_perf.cc
=> TEST/HASH: Add several retries to hash performance test.

contrib/test_jenkins.sh, test/gtest/common/main.cc, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_tag_perf.cc, test/gtest/ucs/test_datatype.cc, test/gtest/ucs/test_hash_perf.cc
=> GTEST/JENKINS: Check performance according to JENKINS_TEST_PERF env var

test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> TEST/UCP: Disconnect all endpoints during test cleanup.

test/gtest/common/test_obj_size.cc
=> UCX/GTEST: fixed compilation issue

contrib/test_jenkins.sh, test/gtest/common/main.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_rma.cc, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucp/test_ucp_tag_xfer.cc, test/gtest/uct/test_p2p_am.cc
Reduces the time it takes the test to complete with UD
=> Reduce unit test execution time

src/ucs/datastruct/callbackq.h, test/gtest/ucs/test_callbackq.cc
=> TEST/CALLBACKQ: Avoid calling callback dispatch from multiple threads.

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h
- Tag offload initialization/cleanup (mlx5 common)
- Some mlx5 TM infra
- XRQ ops posting for mlx5 common (RC and DC)
=> UCT/MLX5: Preparations for HW TM for PRM tls p2

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_common.h
- MLX5 common TM receive poll function
- tag_eager_bcopy support
=> UCT/MLX5: Initial TM support for rc_x tl

src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_rkey.c, src/ucp/proto/proto_am.inl, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/wireup/select.c, test/gtest/ucp/test_ucp_mmap.cc
- added processing of several lanes on rndv-get protocol
=> UCP/RNDV/MULTI-LANE: multi-lane rndv-get mode

src/ucp/rma/flush.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc
Fixes https://github.com/openucx/ucx/issues/2152
=> UCP/FLUSH: fix err handling flow for flush request from pending queue

src/ucp/api/ucp.h, src/ucp/core/ucp_ep.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> UCP/API: add ucp_ep_modify_nb

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/proto/proto_am.inl, src/ucp/stream/stream_send.c, src/ucp/tag/eager.h, src/ucp/tag/eager_rcv.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/rndv.h, src/ucp/tag/tag_match.c, src/ucp/tag/tag_match.h, src/ucp/tag/tag_send.c, src/ucp/wireup/select.c, src/ucs/type/status.c, src/ucs/type/status.h
- added message ID & offset to AM message header
=> UCP/AM: sender-side multilane preparation

src/ucs/sys/compiler_def.h, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_ep.c
- UCT/IB: Minor cleanups
- UCT/IB/MLX5: Fix tm_op in rc_hdr filling
=> UCT/IB: Fixes and minor cleanups 

src/ucp/core/ucp_ep.c
=> ucx_info: add printing of ucp_tag_send_nbr thresholds

contrib/ucx_perftest_config/test_types, src/tools/perf/Makefile.am, src/tools/perf/libperf.c, src/tools/perf/libperf.h, src/tools/perf/perftest.c, src/tools/perf/ucp_tests.cc, test/gtest/common/test_helpers.h, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_perf.cc
- add support for unexpected tag
- compilation and mpi launch fixes
- nicer gtest perf test output
=> perftest enhancements

src/ucp/wireup/select.c
- mask AM BW lanes by device index
- added remote address mask to select transport routine
=> UCP/WIREUP/AM-BW: mask lanes by device

src/uct/base/uct_iface.h, src/uct/sm/self/self_ep.c, src/uct/sm/self/self_iface.c, src/uct/sm/self/self_iface.h
- fixed re-entry issue in Self TL
- added helper macro to unregister desc
Fixes https://github.com/openucx/ucx/issues/2200
=> UCT/SELF: fixed potential data corruption

src/ucp/wireup/select.c
- BW lanes selection shifted into own routine
- RMA BW lane selection refactored to use new routine
and unified with AM BW lane selection
=> UCP/WIREUP/BW: mask RMA BW lanes by device

contrib/test_jenkins.sh, test/gtest/common/test_obj_size.cc
- updated obj_size test to actual object size
=> UCP/REQUEST: updated gtest to actual object size

test/gtest/uct/test_event.cc
=> TEST/EVENT: Fix for transport which can generate spurious events.

config/m4/xpmem.m4, test/gtest/ucp/test_ucp_mmap.cc
=> UCT/XPMEM: add /usr/local/xpmem to pkg search path

src/ucp/proto/proto_am.inl, src/ucp/tag/eager_snd.c
- fixed mtt failure
fixes https://github.com/openucx/ucx/issues/2224
=> UCP/EAGER: fixed failures on MPI test suite

src/ucp/wireup/select.c
- due to issues in US progress multilane is disabled for
this transport
fixes https://github.com/openucx/ucx/issues/2229
=> UCP/UD: disabe multi-lane for UD TLS

src/ucp/wireup/select.c
- fixed regression for UD detection function
=> UCP/WIREUP: fix for UD TL processing

src/uct/ib/ud/base/ud_iface.c
=> UCT/UD: Fix race condition of arming the interface

bindings/java/pom.xml, bindings/java/src/main/java/org/ucx/jucx/Bridge.java, bindings/java/src/main/java/org/ucx/jucx/LoadLibrary.java, bindings/java/src/main/java/org/ucx/jucx/Worker.java, bindings/java/src/main/native/Makefile.am, bindings/java/src/main/native/bridge.cc, bindings/java/src/main/native/bridge.h, bindings/java/src/main/native/context.cc, bindings/java/src/main/native/context.h, bindings/java/src/main/native/request_util.cc, bindings/java/src/main/native/request_util.h, bindings/java/src/main/native/worker.cc, bindings/java/src/main/native/worker.h, bindings/java/src/test/java/org/ucx/jucx/WorkerTest.java, config/m4/java.m4
- Added Java Worker class.
- Java Worker class is backed by a c++ worker wrapper.
- Added Java unit-testing for Worker class (junit dependency in pom.xml).
- Moved the ucp context initialization to wrapper c++ class.
- Minor changes to java.m4 in order skip unit-testing while compiling Dummy.java.
=> JUCX: First control path object

test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_fence.cc, test/gtest/ucp/test_ucp_memheap.cc, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/uct/test_mem.cc
=> TEST/RMA: Use larger fixed address to avoid collision with heap pointers

test/gtest/ucp/test_ucp_tag_xfer.cc
- added smoke tests for multi-lane transfer
=> UCP/TEST: added smoke tests for mlane

src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/rndv.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/verbs/rc_verbs_common.h, test/gtest/ucp/test_ucp_tag_match.cc
=> Fix rendezvous with TM offload for huge messages - v1.3.x

src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/rndv.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/verbs/rc_verbs_common.h, test/gtest/ucp/test_ucp_tag_match.cc
=> Fix rendezvous with TM offload for huge messages - master

src/uct/ib/rc/accel/rc_mlx5_iface.c
Forbid connections on rc_x if peers have different HW TM support status
=> UCT/RCX: Add iface addr handling

src/ucp/tag/eager_rcv.c
There may be no headroom in the data buffer if there is no UCT_CB_PARAM_FLAG_DESC tl flag.
In this case need to allocate hdr + data on the stack.
=> UCP/TAG: Fix unexp eager handler for inlines

src/ucs/Makefile.am, src/ucs/arch/aarch64/cpu.c, src/ucs/arch/aarch64/cpu.h, src/uct/ib/base/ib_iface.c
=> UCS/SYS/IB: Limit IB CQE size for specific ARM boards

src/ucp/tag/eager_rcv.c
There may be no headroom in the data buffer if there is no UCT_CB_PARAM_FLAG_DESC tl flag. In this case need to allocate hdr + data on the stack.
=> UCP/TAG: Fix unexp eager handler for inlines - v1.3.x

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_ep.h, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/verbs/dc_verbs.c
Pending queue may stop dispatching when user pending
request returns UCS_OK without actually sending anything.
I will add a unit test in the PR to master
@yosefe @brminich @hoopoepg please take a look
Fixes #2257
=> UCT/DC: fixes a case of pending reqs not being progressed

src/ucp/tag/rndv.c
- added evaluation for min zcopy value
this is backport from https://github.com/openucx/ucx/pull/2278
=> UCP/RNDV-GET: fixed processing of message size, backport for v1.3

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_ep.c, test/examples/ucp_hello_world.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/test_ucp_wireup.cc
=> UCP/API: restore ucp_ep_params_t compatibility

contrib/test_jenkins.sh, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.h, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_tag_offload.cc
- fixes for armclang5 build
- added test armclang5 build
backport from https://github.com/openucx/ucx/pull/2274
Fixes #2176
=> UCP/COMPILE: armclang fix v1.3

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_ep.c, test/examples/ucp_hello_world.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/test_ucp_wireup.cc
Cherry-picked from https://github.com/openucx/ucx/pull/2280
@yosefe @shamisp
=> UCP/API: restore ucp_ep_params_t compatibility 1.3.x

test/gtest/ucp/test_ucp_stream.cc
Fixes https://github.com/openucx/ucx/issues/2282
@alex-mikheev
=> GTEST: fix test_ucp_stream_many2one.drop_data test

contrib/test_jenkins.sh, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.h, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_tag_offload.cc
- fixes for armclang5 build
- added test armclang5 build
=> UCP/COMPILE: armclang fix

src/ucp/tag/rndv.c
- added processing of no-resources state to rndv proto
=> UCP/RNDV: fix for hang on osu collective tests with multi-rail - v1.3

test/gtest/ucm/malloc_hook.cc
=> TEST/UCM: Fix performance test of malloc with multiple ptrs

test/gtest/uct/test_p2p_am.cc
=> TEST/UCT: Wait for send resorces for up to 10sec

src/ucp/tag/rndv.c
- added lock on lane when called from pending
fixes https://github.com/openucx/ucx/issues/2301
=> UCP/RNDV: fix for hang on osu collective tests with multi-rail

src/uct/ib/base/ib_iface.c
=> UCT/IB: Remove leftover numa.h include

src/uct/cuda/cuda_copy/cuda_copy_ep.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.h
=> UCT/CUDA: create cuda streams on first use - v1.3.x

NEWS
=> UCX: Update NEWS file

src/tools/perf/libperf.c, src/tools/perf/ucp_tests.cc, src/ucs/Makefile.am, src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, src/uct/ib/cm/cm.h, src/uct/ib/cm/cm_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/base/ud_inl.h, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/test_pending.cc
@yosefe @brminich please take  a look
=> UCT/UD: dispatch pending ops from the progress() context only

src/ucp/stream/stream_recv.c, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucp/ucp_datatype.h
=>  UCP/STREAM: add generic datatype support to ucp_stream_recv_nb

src/ucp/core/ucp_ep.c
port https://github.com/openucx/ucx/pull/2317 to v1.3.x
=> UCP: reset uuid in address pack for mem type ep

test/gtest/uct/test_pending.cc
The test covers DC transports issue the was fixed in
3bb34d4986c11fd68e3204cbd76656d3d900b95c
@yosefe @hoopoepg please take a look
=> GTEST/UCT: add UCS_OK pending queue test

src/tools/info/type_info.c, src/ucs/Makefile.am, src/ucs/sys/rcache.c, src/ucs/sys/rcache.h, src/ucs/sys/rcache_int.h, test/gtest/ucs/test_rcache.cc
=> UCS/RCACHE: add stats

src/uct/ib/rc/accel/rc_mlx5_common.c, test/gtest/ucp/test_ucp_peer_failure.cc
=>  UCT/RC/MLX5: Fix SRQ clean flow

config/m4/ib.m4, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/accel/dc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c
- added common config infra
- updated common data initialization to operate by common config
- added DM stub as reference for common config
=> UCT/MLX5: added common config infrastructure

config/m4/ib.m4, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h
- added basic initialization of Device Memory
=> UCT/MLX5: added DM initialization

ucx.spec.in
This commit should be merged once we are ready with v1.3.0.
=> RPM Spec: bump version to 1.3.0

src/uct/api/uct.h, src/uct/base/uct_worker.c
=> UCT/DOC: Fix documentation of uct_worker_create() - async cannot be NULL

src/uct/rocm/rocm_cma_ep.c, src/uct/rocm/rocm_cma_md.c, src/uct/rocm/rocm_common.c, src/uct/rocm/rocm_common.h
This patch to fix an issue introduced with new rocm 1.7.1
=> UCT/ROCM: fix an issue with memory mapping with rocm

src/ucp/core/ucp_ep.c
=> UCP/EP/INFO: Fix ep info print when there is no wireup lane

src/ucp/core/ucp_ep.c
=> UCP/EP/INFO: Fix ep info print when there is no wireup lane - v1.3.x

test/gtest/uct/test_p2p_err.cc, test/gtest/uct/uct_test.cc
Fixes https://github.com/openucx/ucx/issues/2417
=> GTEST/UCT: Fix rc_mlx5/uct_p2p_err_test.remote_access_error

src/ucs/config/parser.c, src/ucs/datastruct/khash.h
- fixed crash on process exit when used variable is set
=> UCS/PARSER: fixed crash on exit

contrib/valgrind.supp, src/tools/perf/libperf.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/mlx5/ib_mlx5_log.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/ud/accel/ud_mlx5.c
- added *short routines implementation
- refactoring of common DM stuff to reduce code duplication
- fixes
=> UCT/DCX: added DM based *short send routines

src/uct/ib/rc/accel/rc_mlx5_common.h
Treat HW TM unexpected flow as a fast path, because small messages should not be offloaded to the HW
=> UCT/RCX/DCX: Optimize path for small unexp messages

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_ep.c
- renamed atomic related macro & funcs to make it more
general
=> UCT/ATOMIC: bit-op preparation: renaming of func-macro

src/ucs/Makefile.am, src/ucs/datastruct/strided_alloc.c, src/ucs/datastruct/strided_alloc.h, src/ucs/sys/compiler.h, src/ucs/sys/compiler_def.h, test/gtest/Makefile.am, test/gtest/ucs/test_strided_alloc.cc
the goal is to use this for allocating UCP endpoints
=> UCS/TEST: Add strided allocator data structure

test/gtest/uct/ib/test_ib_xfer.cc
=> TEST/ODP: Skip ODP tests on ppc64

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_listener.c
preparation for dest_ep_ptr-based protocols (instead of dest_uuid)
=> UCP/EP: Refactor endpoint creation

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup.h
- now UCP initializes UCT atomics based on new AMO masks
=> UCP/ATOMIC: updated UCP/UCT atomic masks

src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/ud/accel/ud_mlx5.c
=> UCT/IB/MLX5: Fix TX completion accounting

src/ucp/wireup/wireup.c
=> UCP/WIREUP: Fix hang due to wireup request message not being sent

src/ucs/sys/rcache.c
=> UCS/RCACHE: Fix access to uninitialized queue

test/gtest/uct/ib/test_ud_slow_timer.cc
=> TEST/UD: Fix test_ud_slow_timer.tick1

src/uct/cuda/base/cuda_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.h, test/gtest/uct/test_md.cc, test/gtest/uct/test_p2p_rma.cc, test/gtest/uct/test_stats.cc, test/gtest/uct/test_uct_perf.cc, test/gtest/uct/test_zcopy_comp.cc, test/gtest/uct/uct_test.h
- added cuda-ipc uct
- gtest changes
- no cache (in follow-up PR)
@bureddy
=> UCT/CUDA-IPC: Adding implementation (initial reviews incorporated)

src/ucp/api/ucp.h, src/ucp/core/ucp_mm.c, test/gtest/ucp/test_ucp_mmap.cc
=> UCP/MM/TEST: Allow mmap with address=NULL and length=0

src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_ep.c
=> UCP/WIREUP: Fix race conditions in wireup

src/uct/sm/mm/mm_ep.c
(cherry picked from commit 8b81ca603ed732ba7cbac17fed77d21234a44422)
=> MM: Adding an assert and using an existing function.

src/ucp/proto/proto_am.inl, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/rndv.c
- removed deprecated ID_LAST argument
=> UCP: clean zcopy_multi code

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/base/uct_mem.c
enables running UCX on ppc64 VM
=> UCS/SYS/UCT: Avoid allocating huge pages if not supported by the system

test/gtest/common/test.cc, test/gtest/common/test.h, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h, test/gtest/uct/ib/test_ib_xfer.cc, test/gtest/uct/test_peer_failure.cc
Fixes #2537 by increasing UD timeout
=> TEST/UCP/ERROR: Refactor test_ucp_peer_failure

src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c
=> UCT/UD: Don't report errors for internal endpoints

src/ucp/core/ucp_context.c, src/ucs/config/parser.c
- MAX_XXX_LANES vars are marked as alias to RAILS vars
=> UCP/CONFIG: added MAX_XXX_RAILS variables

test/gtest/uct/test_tag.cc
Need to wait send completion when message is sent with RNDV protocol
Fixes #2655
=> GTEST: Fix test_tag tests

test/examples/ucp_client_server.c
(cherry picked from commit fe63b51f83ba35ce1514624d05ef4773a283aab6)
=> TEST/EXAMPLES: Update the documentation in ucp_client_server.c

src/ucp/wireup/select.c
picked up from https://github.com/openucx/ucx/pull/2669, commit 9cc678efc172e900fc4a7f037a7da642438d3850
=> UCP/RNDV/MLANE: disable mlane on self/shared AM TL - v1.4

src/ucp/api/ucp.h
=> UCP/DOC: improve ucp_worker_signal description

src/ucp/core/ucp_worker.c
Related to https://github.com/openucx/ucx/pull/2679
=> UCP/WORKER: remove extra lock in ucp_worker_signal

contrib/test_jenkins.sh, src/ucm/event/event.c, test/gtest/ucm/malloc_hook.cc, test/gtest/ucs/test_stats_filter.cc
=>  UCM/TEST: Generate VM_UNMAP event for shmat(REMAP) and mmap(FIXED) - v1.4.x

src/ucm/event/event.c, test/gtest/ucm/cuda_hooks.cc
picked from master pr https://github.com/openucx/ucx/pull/2711
=> UCM/CUDA/GTEST: pass cudaFree memory size to VM_UNMAP event - v1.4.x

config/m4/ib.m4, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/cm/cm_iface.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5_dv.h, src/uct/ib/mlx5/ib_mlx5_hw.c, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/verbs/rc_verbs_common.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/verbs/ud_verbs.c, test/gtest/uct/ib/test_ib.cc
=> IB/DV: Fix CQ poll/arm/clean

src/tools/perf/libperf.c, src/ucp/core/ucp_rkey.c, src/ucp/tag/rndv.c, src/ucp/wireup/select.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.h, test/gtest/uct/uct_test.h
=> UCP/CUDA-IPC: enable protocols using cuda-ipc for inter-node GPU transfers- v1.4.x

src/ucs/datastruct/pgtable.c, src/uct/Makefile.am, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
porting https://github.com/openucx/ucx/pull/2738/ to v1.4.x branch
=> UCT/CUDA_IPC: caching for remote cuda ipc memhandle mappings -v1.4.x

contrib/test_jenkins.sh, src/ucm/malloc/malloc_hook.c, src/ucm/util/reloc.c, src/ucm/util/reloc.h
fixes https://github.com/openucx/ucx/issues/2762
=> TEST: fixed valgrind args

src/ucm/event/event.c, src/ucs/sys/rcache.c, src/ucs/sys/rcache.h, src/uct/cuda/gdr_copy/gdr_copy_md.c, src/uct/ib/base/ib_md.c, src/uct/sm/knem/knem_md.c, test/gtest/ucm/cuda_hooks.cc, test/gtest/ucs/test_rcache.cc
- detached VM_UNMAP from cudaFree
- allow rcache to register with multiple events
=> UCM/UCS/RCACHE: allow rcache to register for multiple events

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h
- default value: UCX_IB_ENABLE_UMR_PACK=y
=> Added variable to enable/disable UMR tbl pack

src/ucs/debug/assert.c, src/uct/ib/ud/base/ud_inl.h
Enhance logging: fix ud log level and add UCX string to fatal error message
=> Logging fixes

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h
=> UCT/IB: options to enable/disable GPUDirect RDMA

contrib/valgrind.supp, test/apps/test_ucx_tls.py
=> Fixes for MLNX_OFED 4.4 testing

config/m4/rocm.m4, src/uct/Makefile.am
Cherry-pick ROCm build improvements from master into 1.3.x.
Requested by @shamisp.
=> cherry-pick ROCm build improvements into 1.3.x

config/m4/rocm.m4, src/uct/Makefile.am
Cherry-pick ROCm build improvements from master into 1.4.x.
Requested by @shamisp.
=> cherry-pick ROCm build improvements into 1.4.x

src/ucp/core/ucp_worker.c
porting https://github.com/Mellanox/hcoll/pull/755 to v1.4.x
=> UCP/WORKER: Fix rndv pipeline fragment pool alignment - v1.4.x

src/ucp/core/ucp_types.h, test/gtest/common/test_obj_size.cc
- increased number of lanes used in single message up to 4
=> MRAIL: increased max number of lanes in message

contrib/valgrind.supp, test/apps/test_ucx_tls.py
=> Fixed for MLNX_OFED 4.4 testing - v1.4.x

test/gtest/uct/test_tag.cc
Bug fix
Fixes #2855 
Need to wait send completion when message is sent with RNDV protocol
=> GTEST: Fix test_tag tests  - v.1.4.x

contrib/test_jenkins.sh, test/examples/uct_hello_world.c
fixes https://github.com/openucx/ucx/issues/2861
=> EXAMPLE: fixed missing initialization of EP

src/ucs/arch/ppc64/cpu.h
arch/power: Use faster "lwsync" to ensure store ordering
Reduces ib/mlx5 latency by 9 ns when changing memory barrier between WQE and DB record writes.
=> POWER: improve store mem barrier

src/ucm/util/reloc.c
Cherry-picked from https://github.com/openucx/ucx/pull/2828
=> UCM/RELOC: fix modifying GOT mechanism v1.4.x

contrib/test_jenkins.sh, test/examples/uct_hello_world.c
- fixed missing initialization of EP in uct hello world
- added uct hello world over tcp proto to Jenkins
backport from https://github.com/openucx/ucx/pull/2862
=> Fixed uct hello world crash v1.4

src/ucp/tag/offload.c
Minor cleanups in UCP tag offload code.
=> UCP/TAG: Minor cleanups in tag offload

AUTHORS, NEWS
- Adding v1.4.0 update
- Porting v1.3.1 news from 1.3.x branch
- Updated contributors list
=> Updating news and authors files

AUTHORS, NEWS
News and authors files update before RC1
=> NEWS: Backport #2843 from master v1.4.x

NEWS
Update NEWS with tag stats API
=> Update NEWS with tag stats API

src/ucm/util/reloc.c
porting https://github.com/openucx/ucx/pull/2898 from master
=> UCM/RELOC: add dlopen symbol to reloc patch list  - v1.4.x

src/ucm/util/reloc.c
=> UCM/RELOC: add dlopen symbol to reloc patch list

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_worker.c, src/ucp/rma/amo_send.c, src/ucp/rma/rma_send.c, src/ucp/stream/stream_recv.c, src/ucp/stream/stream_send.c, src/ucp/tag/probe.c, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_peer_failure.cc
Print error message and return UCS_ERR_INVALID_PARAM if required features are not enabled
Improve user experience in debugging simple bugs
=> UCP: improve check parameters in API routines

src/ucp/tag/offload.c
This PR adds UCS profiling of tag offload callbacks
Can be useful for apps performance analysis
=> UCP/TAG: Profile tag offload callbacks

NEWS
=> NEWS: Updating news file with known issues

test/gtest/ucm/malloc_hook.cc
=> TESTS: fixed tests for bistro-multithread

test/gtest/ucm/malloc_hook.cc
=> TEST: fixed build by latest compiler

test/gtest/ucs/test_async.cc
=> TEST/ASYNC: Do several retries with waiting for timer events

test/gtest/Makefile.am
fixes https://github.com/openucx/ucx/issues/2939
=> GTEST: failed make test in case if gtest was disabled

src/ucp/core/ucp_listener.c, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Testing an API added in #2840 and implemented in #2889
=>  GTEST/UCP: client/server API with connection handle testing

src/ucp/core/ucp_context.c, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.inl, src/ucp/dt/dt.c, src/ucp/dt/dt.inl, src/uct/api/uct.h, test/gtest/uct/test_md.cc
Adds Cuda-managed memory support to 1.4.x
@shamisp @yosefe
=> UCP/UCT: CUDA Managed memory support

NEWS
=> NEWS: Updating NEWS for release

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Fixes https://github.com/openucx/ucx/issues/2981 by
- fixing err handling on wireup
- fixing test_ucp_sockaddr_with_rma_atomic.wireup
=>  UCP: fix err handling on wireup

src/ucs/datastruct/khash.h, src/uct/base/uct_worker.h, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/base/ib_md.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/verbs/dc_verbs.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/ud/accel/ud_mlx5_common.c, src/uct/ib/ud/verbs/ud_verbs.c
- all created address handlers are cached in worker to optimize
AH processing
fixes https://github.com/openucx/ucx/issues/2885
=> IB: added cache for AH

test/gtest/ucs/test_rcache.cc
=> TEST/RCACHE: Fix rcache stats test, to account for region struct unmap

doc/doxygen/ucxdox
Minor fix to generate man page link file per function
=> DOC: Newer doxygen generates reasonably good man pages

test/gtest/ucs/test_async.cc
=> TEST/ASYNC: Add retries to test_async_timer_mt.multithread

doc/doxygen/ucxdox, src/ucp/api/ucp.h, src/ucp/api/ucp_compat.h, src/ucp/api/ucp_def.h, src/ucs/config/types.h, src/ucs/datastruct/callbackq.h, src/uct/api/uct.h, src/uct/api/uct_def.h
Fix doxygen warnings about broken links
=> DOCS: fix doxygen warnings about broken links

src/uct/ib/base/ib_iface.c
=> UCT/IB: Fix force global AV

contrib/test_jenkins.sh, ucx.spec.in
1. Sync spec file with other branches.
2. Check if the current version is present in spec changelog.
=> spec: keep rpm spec changelog up to date

test/gtest/uct/ib/test_ud_slow_timer.cc
=> GTEST: increase timeout in test_ud_slow_timer.ep_destroy

src/ucp/rma/rma_basic.c, src/uct/ib/rc/accel/rc_mlx5_common.h
=> Optimizations for PUT message rate

test/gtest/uct/ib/test_ib_xfer.cc, test/gtest/uct/test_p2p_mix.cc, test/gtest/uct/uct_p2p_test.cc
=> TEST/IB: Re-enable ODP tests, and flush sender iface to fix err syndrome

src/ucp/core/ucp_ep.inl, src/ucp/rma/flush.c, src/ucp/wireup/wireup.c, src/uct/sm/mm/mm_ep.c
=> Fixes for endpoint flush - v1.5.x

test/gtest/ucs/test_stats.cc, test/gtest/ucs/test_stats_filter.cc
Cherry-picked from https://github.com/openucx/ucx/pull/3064/commits
Do not block other PRs
@yosefe
=> TEST/GTEST: Workaround armclang 19 segfault - avoid empty initializer

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/proto/proto_am.inl, src/ucp/rma/amo_sw.c, src/ucp/rma/rma.inl, src/ucp/rma/rma_send.c, src/ucp/rma/rma_sw.c, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucp/ucp_test.h, test/gtest/uct/ib/test_dc.cc, test/gtest/uct/test_stats.cc, test/gtest/uct/uct_test.h
Last part of #2864
#2656 was fixed in OMPI because of lack of this functionality in UCX
Using https://github.com/openucx/ucx/pull/2965
=> UCP/WIREUP: add async wireup

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/tag/rndv.c, src/ucp/wireup/select.c
- added cross-lane calculation of min_zcopy
=> UCP/RNDV: Fix next min_zcopy check

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h
Refer https://github.com/openucx/ucx/pull/3062
@yosefe @bureddy @brminich @shamisp
=> UCT/IB/CUDA: Penalizing HCAs farther away from GPU

src/ucp/stream/stream.h, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.c, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_iface.h
=> gcc9 compilation fixes

NEWS
- News file update
- Minor clean up of the file
- Copyright updates for 2019
=> NEWS: Updating new for 1.5.0 rc2

src/tools/info/ucx_info.c
Fixes issues described in https://bugzilla.redhat.com/show_bug.cgi?id=1667548.
Fixes #3147.
=> ucx_info: fixes for RH1667548

src/tools/info/ucx_info.c
Fixes issues described in https://bugzilla.redhat.com/show_bug.cgi?id=1667548.
Fixes #3147.
Cherry-picked from #3148.
=> ucx_info: fixes for RH1667548 — v1.5

src/ucp/api/ucp.h, src/uct/api/uct_def.h
* responsible to -> for
* accesses -> ed
* reacheble -> reachable
Fixes some English and spelling in ucp.h
To correct spelling
N/A
=> Fix some English/spelling in ucp.h

src/ucp/core/ucp_worker.c, src/uct/ib/dc/accel/dc_mlx5.c, src/uct/ib/dc/base/dc_iface.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/mlx5/ib_mlx5_log.h, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5_common.c
=> UCT/DC/MLX5: Set proper source port for FC over RoCE - v1.5.x

README, ucx.spec.in
=> Topic/update ucx desc in spec and readme v1.5.x

src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/cm/cm_ep.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/ud/base/ud_ep.c, src/uct/sm/mm/base/mm_ep.c, src/uct/tcp/tcp_ep.c, src/uct/ugni/base/ugni_ep.c, test/gtest/uct/test_stats.cc
The PR adds statistics for number of pending requests added
Useful for profiling apps/benchmarks
=> UCT: Add pending stats

configure.ac, contrib/buildrpm.sh, src/uct/Makefile.am, src/uct/configure.m4, src/uct/ib/Makefile.am, src/uct/ib/base/ib_md.c, src/uct/ib/cm/Makefile.am, src/uct/ib/cm/configure.m4, src/uct/ib/configure.m4, src/uct/ib/mlx5/ib_mlx5_hw.c, src/uct/ib/rdmacm/Makefile.am, src/uct/ib/rdmacm/configure.m4, src/uct/ib/rdmacm/rdmacm_def.h, test/gtest/Makefile.am, ucx.spec.in
+ Separate module for rdma_cm (uct framework)
+ Separate module for cm  (uct_ib framework)
+ Update RPM spec
=> UCT/IB/SPEC: Build IB transports as loadable modules

NEWS
Small fix. Thanks to @manjugv for pointing this out.
=> NEWS: Removing duplicated line.

test/gtest/ucs/test_async.cc
=> TEST/ASYNC: Add retries to test_async.modify_event

src/ucs/debug/assert.c, src/ucs/debug/assert.h, src/ucs/debug/debug.c, src/ucs/debug/debug.h, src/ucs/debug/log.c, test/gtest/common/test.cc
Needed for logging IB completion with error details
=> UCS/LOG: Add support for multi-line log messages

config/m4/ucs.m4, src/ucs/debug/debug.c
=> UCS/DEBUG: Remove libiberty.h include

src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/debug/memtrack.c, src/ucs/debug/memtrack.h, src/ucs/sys/string.c, test/gtest/ucs/test_config.cc, test/gtest/ucs/test_sys.cc
- added speed datatype
- added PCI device speed datatype
=> CONFIG: added processing of speed units

config/m4/sysdep.m4, src/ucs/sys/string.c, src/ucs/sys/string.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/sm/cma/cma_md.c, test/gtest/Makefile.am, test/gtest/ucs/test_string.cc
=> UCS/CMA: Check yama.ptrace_scope permissions

test/gtest/Makefile.am
=> TEST/GTEST: Fix IB depenedency in Makefile

src/uct/ib/base/ib_md.c
- added reading of actual PCI BW from /sys/*** files
=> MD/IB: added read of PCI info from files

src/ucs/datastruct/arbiter.h
Minor fixes in the arbiter documentation
=> UCS/ARBITER: Fix docs

src/ucp/core/ucp_ep.c
- updated RNDV threshold calculation algorithm
using multi-lane BW
=> UCP/RNDV: mlane RNDV threshold calculation

src/uct/rocm/rocm_cma_ep.c, src/uct/rocm/rocm_cma_ep.h, src/uct/rocm/rocm_cma_iface.c, src/uct/rocm/rocm_cma_iface.h, src/uct/rocm/rocm_cma_md.c, src/uct/rocm/rocm_cma_md.h
Updates ROCM UCT to conform to changes to uct_ep_create (PR#3115)
=> ROCM UCT: Updating for uct_ep_create changes

src/ucm/api/ucm.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/uct/api/uct.h, test/gtest/uct/test_md.cc
Prepare for adding UCM rocm and new rocm TL.
=> UCP&UCT: add ROCM memory type

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup_ep.c, src/ucs/Makefile.am, src/ucs/sys/socket.c, src/ucs/sys/socket.h, src/ucs/sys/string.c, src/ucs/sys/string.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/ib/rdmacm/rdmacm_md.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_net.c, test/gtest/Makefile.am, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucs/test_socket.cc, test/gtest/ucs/test_sys.cc
This PR adds needed common code for further in PR #3252 (TCP transport optimizations)
Just to reduce code lines that will be reviewed in PR #3252
=> UCS/SYS: add socket and sockaddr helper functions

src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/wireup/select.c
fix coding style, basically too long lines
=> UCP/MD: fix coding style

src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c
additional fix for https://github.com/openucx/ucx/issues/3289
=> IB: compilation fixes for GCC 9+

src/ucp/api/ucp.h
Would help to avoid confusion with rkeys
(someone forgot to release rkeys in his app)
=> UCP/DOC: Minor documentation fixes

src/uct/rocm/Makefile.am, src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/copy/rocm_copy_ep.c, src/uct/rocm/copy/rocm_copy_ep.h, src/uct/rocm/copy/rocm_copy_iface.c, src/uct/rocm/copy/rocm_copy_iface.h, src/uct/rocm/copy/rocm_copy_md.c, src/uct/rocm/copy/rocm_copy_md.h
=> UCT/ROCM: add rocm_cpy TL

contrib/test_jenkins.sh, src/tools/perf/lib/libperf.c, src/ucm/configure.m4, src/ucm/event/event.c, src/ucs/sys/module.c, src/ucs/sys/module.h, src/uct/base/uct_md.c, src/uct/cuda/base/cuda_md.c, src/uct/ib/base/ib_md.c, test/apps/Makefile.am, test/apps/test_link_map.c, test/gtest/ucs/test_sys.cc
=> UCS/UCM: Avoid linking UCM loadable modules with "nodelete" flag

src/uct/rocm/Makefile.am, src/uct/rocm/ipc/rocm_ipc_cache.c, src/uct/rocm/ipc/rocm_ipc_cache.h, src/uct/rocm/ipc/rocm_ipc_ep.c, src/uct/rocm/ipc/rocm_ipc_ep.h, src/uct/rocm/ipc/rocm_ipc_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.h, src/uct/rocm/ipc/rocm_ipc_md.c, src/uct/rocm/ipc/rocm_ipc_md.h
=> UCT/ROCM: add rocm_ipc TL

doc/doxygen/header.tex.in
=> DOC: Fixing latex error on OSX

src/ucp/core/ucp_mm.h, src/ucp/tag/rndv.c
For https://github.com/openucx/ucx/issues/3241
=> UCP: enable get_zcopy for ROCM by default

contrib/cray-ugni-mock/cray-pmi.pc, contrib/cray-ugni-mock/cray-ugni.pc, contrib/cray-ugni-mock/include/gni_pub.h, contrib/cray-ugni-mock/include/pmi.h, contrib/cray-ugni-mock/include/pmi2.h, contrib/test_jenkins.sh, src/uct/ugni/base/ugni_ep.c, src/uct/ugni/smsg/ugni_smsg_ep.c
Adds mock UGNI headers to test UCT UGNI compilation in Jenkins
=> JENKINS: Add cray-ugni build test

src/ucp/core/ucp_ep.c, test/gtest/ucp/test_ucp_peer_failure.cc
Fixes #3081
Adjust AM max_short if zcopy_threshold is set externally
=> UCT/EP/CONFIG: adjust AM max_short if zcopy_threshold is set externally

src/ucm/api/ucm.h, src/ucm/event/event.c, src/ucm/mmap/install.c, src/ucm/mmap/mmap.h, test/gtest/ucm/malloc_hook.cc
- added ucm_test_events call
- added gtest test for new call
=> UCM/HOOKS: added ucm_test_events routine to check if hooks works properly

test/gtest/ucp/test_ucp_tag_offload.cc
Enable multirail for tag offload tests 
To cover more use-cases with tag offload
activate tag offload with a bigger message (>= TM_THRESH). In case of multi-rail (i.e. more than 1 active rx ifaces) this will result in proper iface hashing and following tag postings
=> GTEST/UCP: Adjust tag offload test to multirail

src/ucm/api/ucm.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_request.inl, src/ucp/dt/dt.c, src/ucp/dt/dt.inl, src/uct/api/uct.h, test/gtest/uct/test_md.cc
=> UCX: add ROCM managed memory type

src/ucp/tag/rndv.c
=> UCP/RNDV: Fix pipelined rndv condition checks

src/ucs/debug/debug.c, src/ucs/sys/sys.c, src/ucs/sys/sys.h
=> UCS/DEBUG: Add ability to read env for TMPDIR

configure.ac, ucx.spec.in
Bump version to v1.7.0
We just forked v1.6.x branch, so update master version to 1.7
=> CONFIG/SPEC: Bump version to 1.7.0

AUTHORS
Would like to add Wenbin to AUTHORS
Wenbin has made a number of contributions recently
N/A
=> Add Wenbin to AUTHORS file to acknowledge his contributions

config/m4/rocm.m4, src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/ipc/rocm_ipc_ep.c, src/uct/rocm/ipc/rocm_ipc_md.c, src/uct/rocm/ipc/rocm_ipc_md.h
Cherry pick from master branch.
This is code cleanup and remove some build dependency from rocm side, so I'd like this to be in the 1.6 release of ucx.
Thanks.
=> UCT/ROCM/IPC: remove unused CMA code

doc/CodeStyle.md
Code style examples
Code style example may help for developing OpenUCX.
=> DOC/CODESTYLE Add code style example

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, test/gtest/ucs/test_arbiter.cc
Would be used to prioritize RC/DC flow control messages over regular data
=> UCS/ARBITER/TEST: Add function to push element to group head

src/uct/ib/base/ib_verbs.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/base/rc_iface.c
Fix AR support when HW TM is enabled 
If OOO support is enabled, need to create TM XRQ with OOO support as well.
So that internal HW TM DCIs (managed by FW) would be created with OOO support
=> UCT/DC: Fix OOO support for TM DCIs

src/ucs/datastruct/arbiter.c
- issue was detected by coverity
=> ARBITER: fixed initialization of arbiter on abort processing

src/ucm/event/event.c, test/gtest/ucm/malloc_hook.cc
Cherry pick from #3448 (without additional changes)
@bureddy
=> UCM/TEST: Fix handling of shmat(SHM_REMAP|SHM_RND) - v1.6.x

ucx.spec.in
=> SPEC: Remove CUDA BuildRequires, since package name is not consistent - v1.6.x

ucx.spec.in
=> SPEC: Remove comments from subpackages

test/gtest/Makefile.am
=> GTEST: Add CUDA_CPPFLAGS for cuda build

src/uct/ib/rdmacm/rdmacm_iface.c
Translate errno=EADDRNOTAVAIL set by rdmacm_bind failure to UCS_ERR_BUSY
Fixes https://github.com/openucx/ucx/issues/3514
=> UCT/IFACE/SOCKADDR/RDMACM: handle errno=EADDRNOTAVAIL

test/examples/ucp_client_server.c
Simple change convert port number for listener address to network order.
=> TEST/EXAMPLES: use htons on server_port

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_listener.c, src/uct/api/uct.h, src/uct/ib/rdmacm/rdmacm_iface.c, test/examples/ucp_client_server.c, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
=> API/UCP/UCT/TEST: Added a function to retrieve the listening port.

bindings/java/src/main/native/Makefile.am, bindings/java/src/main/native/jucx_common_def.h, config/m4/compiler.m4, contrib/test_jenkins.sh, test/apps/test_ucx_tls.py, test/gtest/Makefile.am, test/gtest/ucs/test_sock.cc
Adapt the code to older SW versions.
=> CONFIG/JENKINS/TEST/UCS: Fixes and adaptations for older sw versions - v1.6

bindings/java/pom.xml.in, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpRemoteKey.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/memory.cc, bindings/java/src/test/java/org/ucx/jucx/UcpMemoryTest.java
JUCX:  unpack remote key buffer functionality.
To unpack buffer outside of data path.
=> JUCX: unpack remote key buffer functionality.

src/uct/base/uct_component.h
Fixes https://github.com/openucx/ucx/pull/3484#issuecomment-488286273
=> UCT/COMPONENT: Struct member doc fix

src/ucm/malloc/malloc_hook.c, src/ucm/util/reloc.c, test/gtest/ucm/malloc_hook.cc
=> UCT/TEST: Fix deadlock with dlopen() from multiple threads

src/uct/sm/self/self.c
Fix MD config table set for SELF
Wrong config table set
Replace IFACE config table set for MD component by empty MD config table
=> UCT/SELF: Fix MD config table

bindings/java/src/main/java/org/ucx/jucx/NativeLibs.java, bindings/java/src/main/native/context.cc, bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/ucx/jucx/UcpListenerTest.java, config/m4/java.m4, contrib/test_jenkins.sh
Jenkins doesn't run JUCX tests. 
`$(MVN)` command started to substitute to `true` for some reason:
```
22:08:29 true -B -f /scrap/jenkins/workspace/hpc-ucx-pr-4/label/hpc-test-node/worker/0/build-test/bindings/java/pom.xml -Dmaven.repo.local=/scrap/jenkins/workspace/hpc-ucx-pr-4/label/hpc-test-node/worker/0/build-test/.deps test
```
=> JUCX: Fix and run tests on Jenkins.

src/uct/cuda/cuda_copy/cuda_copy_ep.c
- Move away from using cudaMemcpy on default stream for `get_short` as well.
@bureddy Can you review?
=> UCT/CUDA_COPY: Move to using non-blocking stream for get_short

AUTHORS
=> AUTHORS: Add Hiroyuki Sato

bindings/java/src/main/java/org/ucx/jucx/UcxCallback.java, bindings/java/src/main/java/org/ucx/jucx/UcxRequest.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/test/java/org/ucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/ucx/jucx/UcpMemoryTest.java
JUCX: get nonblocking functionality.
First RDMA operation skeleton. Consecutive operations (SEND, PUT, RECV, etc.) would be very easy to add since would reuse callback functionality.
=> JUCX: get non blocking operation.

bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/ucx/jucx/UcpWorkerTest.java
JUCX: worker signal functionality.
To be able to wakeup sleeping worker.
=> JUCX: worker signal functionality.

test/examples/ucp_client_server.c
Recreating this https://github.com/openucx/ucx/pull/3533
cc @yosefe @shamisp
=> TEST/EXAMPLES: use htons on server_port - v1.6.x

src/ucs/async/async.c, src/ucs/async/signal.c, src/ucs/async/thread.c
Ensure that faulty cases are printed by default
=> UCS/ASYNC: Revise logs severity
