NEWS
Use the opportunity to reflect v1.5.1 in master news file.
=> NEWS: Getting news ready for v1.6.x

src/ucs/arch/aarch64/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.h, src/uct/ib/mlx5/ib_mlx5.inl
Revisiting aarch64 barriers.
Adding special case for TX2.
=> UCS/UCT: Updating barrier code

src/ucp/core/ucp_worker.c
The patch handles the case when some UCT iface (`uct_iface_create` fails) can't be created during `ucp_worker_create`
Fixes incorrect handling the case when UCT iface can't be created
1. Set exact num of iface allocated to `worker::num_ifaces`
2. Don't check `worker::iface[<idx>] == NULL` as it is always not a `NULL`
3. Call `ucs_async_remove_handler` for worker iface if `worker_iface::event_fd != -1`
4. When closes iface, set it to `NULL` to be able check for `worker_iface::iface != NULL` before destroying it
5. Close UCT iface if query iface (`uct_iface_query`) fails
=> UCP/WORKER: Fix worker_create when can't create UCT iface

src/ucm/event/event.c, src/ucm/event/event.h, src/ucm/mmap/install.c
- there were issue in ucm_event_test call: it could false
positive detect missing or over-called events
- re-implemented function using event-by-event check
=> UCM/EVENT: fixed ucp_test_event call

test/gtest/ucm/malloc_hook.cc
this is GTEST for https://github.com/openucx/ucx/pull/3647
=> GTEST/EVENTS: added test for false positive

src/ucp/api/ucp.h
@petro-rudenko @shamisp @tonycurtis
=> UCP/API/DOC: Add clarification for ucp_ep_rkey_unpack()

src/ucm/mmap/install.c
Fixes segfault with valgrind on Jazz machine
=> UCM: Fix mmap events test

src/ucs/debug/debug.c
=> UCS/DEBUG: Check that signal hash is initialized before using it

src/ucs/sys/event_set.c, src/ucs/sys/event_set.h, test/gtest/ucs/test_event_set.cc
This PR is an extension event_set API. See also #3682 
It requires to use this API in uct/tcp.
=> UCS/SYS New event_set API for using in UCT layer.

bindings/java/src/main/java/org/ucx/jucx/examples/UcxBenchmark.java, bindings/java/src/main/java/org/ucx/jucx/examples/UcxReadBWBenchmarkReceiver.java, bindings/java/src/main/java/org/ucx/jucx/examples/UcxReadBWBenchmarkSender.java, bindings/java/src/main/java/org/ucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/jucx_common_def.cc, contrib/test_jenkins.sh
JUCX: standalone benchmark application, that has 2 parts: sender and receiver. Sender registers buffer -> sends it's address and key to the receiver. The receiver does ucp_get_nb to read buffer content and measure bandwidth.
To show full jucx application
=> JUCX: standalone benchmark application

src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_mm.h, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/dt/dt.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/uct/base/uct_md.c, test/gtest/uct/test_md.cc, test/gtest/uct/uct_test.cc
- small improvement to rndv latency (~100ns)
- tested on 8 nodes 28ppn shmem application
=> UCP/TOOLS/UCT: Implement component parameter for rkey functions

bindings/java/src/main/native/context.cc, bindings/java/src/main/native/jucx_common_def.cc
Fixes issue with not initialized request.
Incorrect behavior, that sometimes causes segfaults.
=> JUCX: add size & init context flags to initialize request properly.

test/gtest/ucs/test_async.cc
=> TEST/ASYNC: Add few retries to async event tests

test/apps/test_ucx_tls.py
To fix failures on hpc-test-node-upstream
=> TEST/APPS: Fix extracting driver name for IB device

test/gtest/ucs/test_event_set.cc
Improve stability of UCS/event_set tests
Fixes #3765
1. Use infinite timeout for `ucs_event_set_wait` in case of we wait for events
2. Use pthread barrier between main thread and the thread that calls `event_set_tmo_func`
=> GTEST/UCS: Fix event_set tests instability

src/ucm/mmap/install.c
=> UCM/MMAP: Fix race condition updating fired_events from multiple threads

src/ucp/tag/eager_snd.c
Fixes bug in `ucp_tag_send_sync_nb` for UCT zcopy message sizes, when `uct_ep_am_zcopy` returns `UCS_OK`
`ucp_tag_send_sync_nb` doesn't work for UCT zcopy message sizes, when `uct_ep_am_zcopy` returns `UCS_OK`, i.e. the request is never completed
`ucp_tag_send_nb`:
- calls `ucp_proto_am_zcopy_req_complete` to complete Zcopy request if the operation completes immediately (i.e `uct_ep_am_zcopy` returns `UCS_OK`).
- calls `ucp_proto_am_zcopy_completion` in Zcopy completion callback with checks for `req->send.state.dt.offset == req->send.length` when Zcopy operation completes not immediately (i.e. `uct_ep_am_zcopy` returns `UCS_INPROGRESS`)
Apply the same approach for `ucp_tag_send_sync_nb` as we do for `ucp_tag_send_nb`:
- calls `ucp_tag_eager_sync_zcopy_req_complete`, if `uct_ep_am_zcopy` …
=> UCP/TAG: Fix sync send for UCT zcopy message sizes

src/uct/base/uct_md.c
=> UCT/MD: Fix component name check in uct_rkey_unpack

src/uct/tcp/tcp_net.c
=> UCT/TCP: Remove IB include

src/ucm/util/replace.c, src/ucs/datastruct/mpool.c, src/ucs/sys/sys.c, src/uct/base/uct_mem.c, src/uct/sm/mm/sysv/mm_sysv.c
These are random selections of three changes I did while making UCX compilable on FreeBSD.
To start the process of merging the accumulated work for porting to FreeBSD.  Look at my freebsd branch for whole collection of commits.  I chose three which are not completely trivial but a simple enough to start.
I added necessary autoconf tests and avoided using missed features or re implemented them.  Nothing unusual to see.
=> First three freebsd port pulls

bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h
Add callback functions profiliation
To be able to profile jucx hot methods.
=> JUCX: profile callback functions.

.gitignore
Add some files to `.gitignore` file
To show fewer files when running `git status`
Add to `.gitignore` the following files:
* gnu global default filename - GTAGS etc
* ignore `modules` directory
* ignore vim temporary file.
=> Add some files to .gitignore

src/tools/perf/perftest.c, src/ucp/proto/proto_am.c, src/ucp/wireup/wireup.c, src/ucs/config/parser.c, src/ucs/datastruct/mpmc.c, src/ucs/datastruct/strided_alloc.c, src/ucs/sys/sys.c, src/ucs/type/class.c, src/uct/ib/base/ib_md.c, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/ib/rdmacm/rdmacm_md.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/sm/mm/base/mm_md.c, src/uct/tcp/sockcm/sockcm_md.c, src/uct/tcp/tcp_ep.c
Fixes a bunch of compiler/cppcheck warnings generated by csmock tool
Fixes possible bugs
=> UCS, UCT, UCP, TOOLS: Fixed few csmock warnings

src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h
=> UCT/RC/DC: Resource check cleanups

src/ucs/stats/stats.c
- there was access to removed statis data on stats dump
- added data duplication on node remove
=> STATS: Fixed crash on stat trigger "exit"

test/examples/uct_hello_world.c
As I proposed #3823, add `Example` part in `uct_hello_world` command usage
This example may help for beginners.
=> TEST/EXAMPLES: Add uct_hello_world command example in usage.

src/uct/base/uct_component.c, src/uct/base/uct_worker.h, src/uct/ib/mlx5/ib_mlx5.c
Fixes some compiler/cppcheck warnings generated by csmock tool
Fixes possible bugs
=> UCT: Fix csmock issues

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/test_tag.cc
Align RC/DC config with iface inheritance
=> UCT/RC/DC: Fix RC and DC config inheritance

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/configure.m4, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Add --with(out)-devx configure option.
Add UCX_IB_MLX5_DEVX config var.
=> UCT/IB: Make DEVX configurable

src/tools/perf/perftest.c
Removes changes introduced in #3799
They are unneeded and can be removed
=> TOOLS/PERFTEST: Fix bug when using socket rte

buildlib/azure-pipelines.md, buildlib/azure-pipelines.yml, buildlib/centos7.Dockerfile
=> Add a CI using Azure Pipelines

NEWS
Updating name and date before release tag
=> NEWS: Release date update.

test/gtest/uct/test_pending.cc
=> TEST/UCT: Skip cm/test_uct_pending.pending_ucs_ok_dc_arbiter_bug

bindings/java/src/main/native/jucx_common_def.cc
Caching methodID and fieldID that is used in hot data path (callbacks). No need each time to lookup them. 
As described [here](http://normanmaurer.me/blog/2014/01/07/JNI-Performance-Welcome-to-the-dark-side) it's a good practice to cache jclass and methods that are used in a hot path.
=> JUCX: cache JNI method and field lookup.

config/m4/ucs.m4, src/tools/info/sys_info.c, src/ucp/core/ucp_request.inl, src/ucp/dt/dt.c, src/ucp/dt/dt.inl, src/ucs/Makefile.am, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/aarch64/global_opts.c, src/ucs/arch/aarch64/global_opts.h, src/ucs/arch/global_opts.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/ppc64/global_opts.c, src/ucs/arch/ppc64/global_opts.h, src/ucs/arch/x86_64/cpu.c, src/ucs/arch/x86_64/cpu.h, src/ucs/arch/x86_64/global_opts.c, src/ucs/arch/x86_64/global_opts.h, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/sys/init.c, test/gtest/ucs/test_sys.cc
- used ```rep movsb``` instruction on Intel arch
=> UCS: added optimized version of memcpy

src/tools/perf/perftest.c, src/ucp/core/ucp_ep.inl, src/ucp/rma/amo_send.c, src/ucp/rma/rma_send.c, src/ucp/stream/stream_recv.c, src/ucs/datastruct/arbiter.h, src/ucs/datastruct/ptr_array.c, src/ucs/datastruct/queue.h, src/ucs/time/timer_wheel.c, src/ucs/type/class.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/ud/base/ud_ep.h, test/gtest/common/test_obj_size.cc
Some additional fixes against master detected by csmock on 1.6.x branch
Fixes potential bugs
=> UCS, UCP, UCT: Fixes for csmock

NEWS
=> NEWS: Fix misprint

NEWS
=> NEWS: Fix misprint - v1.6.x

src/tools/perf/lib/libperf.c, src/tools/perf/perftest.c, src/tools/profile/read_profile.c, src/ucm/ptmalloc286/malloc.c, src/ucp/core/ucp_listener.c, src/ucp/wireup/address.c, src/ucp/wireup/select.c, src/ucs/datastruct/pgtable.c, src/ucs/datastruct/ptr_array.c, src/uct/ib/base/ib_log.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rc/base/rc_ep.c, test/apps/sockaddr/sa_main.cc
Fix csmock issues found during AZP testing 
Fixes failures found in #3932
=> CI/AZP: Fixes for csmock issues found during AZP testing 

src/ucp/wireup/address.c
Preparation for using same device name for all shared memory transports, to avoid UCP hack of checking SELF/SHM for multi-rail
=> UCP/ADDRESS: Support different memory domains with same device name

src/tools/perf/lib/libperf.c, src/tools/perf/perftest.c, src/ucm/ptmalloc286/malloc.c, src/ucp/wireup/address.c, src/ucp/wireup/select.c, src/ucs/datastruct/pgtable.c, src/ucs/datastruct/ptr_array.c, src/uct/ib/base/ib_log.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rc/base/rc_ep.c, test/apps/sockaddr/sa_main.cc
Backport fixes for csmock issues (w/o any changes)
Fixes bugs found by csmock tool during CI/AZP testing
=> CI/AZP: Fixes for csmock issues found during AZP testing (backport) - v1.6

src/ucs/async/signal.c, src/ucs/debug/debug.c
Makes signal handling code compilable on FreeBSD.
To continue merging FreeBSD port.
=> UCS: Handle differences in the signal handling on Linux vs. FreeBSD.

src/ucp/api/ucp_def.h
=> DOC: Replacing UCX_OK with UCS_OK in a few places

src/tools/perf/perftest.c, src/ucm/util/log.c, src/ucm/util/reloc.c, src/ucs/debug/assert.c, src/ucs/debug/log.c, src/ucs/sys/module.c, src/ucs/sys/string.h
- added ucs_basename function which may operate by const char string
=> UCS: added ucs_basename function

contrib/test_jenkins.sh
The PR does the following:
- fixes indent issues
- runs ucx_perftest with TCP
- introduces a client-server launcher (`run_client_server_app` function)
- uses a client-server launcher to run `ucx_hello_world` and `ucp_client_server` apps
- uses a client-server launcher to run ucx_perftest with socket rte (in addition to what we do with MPI)
Simplifies Jenkins test script and adds regression for ucx_perftest/SocketRTE
=> JENKINS: Improvements, run ucx_perftest with TCP and with sock rte launcher

src/uct/base/uct_component.c, src/uct/base/uct_component.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/cuda/base/cuda_md.c, src/uct/cuda/base/cuda_md.h, src/uct/cuda/cuda_copy/cuda_copy_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/gdr_copy/gdr_copy_md.c, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/rdmacm/rdmacm_md.c, src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/copy/rocm_copy_md.c, src/uct/rocm/gdr/rocm_gdr_md.c, src/uct/rocm/ipc/rocm_ipc_md.c, src/uct/sm/cma/cma_md.c, src/uct/sm/knem/knem_md.c, src/uct/sm/mm/base/mm_md.c, src/uct/sm/mm/base/mm_md.h, src/uct/sm/self/self.c, src/uct/tcp/sockcm/sockcm_md.c, src/uct/tcp/tcp_md.c, src/uct/ugni/base/ugni_md.c, test/gtest/uct/ib/test_ib.cc
Allows reusing same functions (md_open, query_resources) for similar components
=> UCT: Add 'component' param to internal md_open() and query_resources()

src/tools/info/tl_info.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/proto/proto_am.inl, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/select.c, src/uct/api/uct.h, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/ib/base/ib_iface.c, src/uct/rocm/copy/rocm_copy_iface.c, src/uct/rocm/gdr/rocm_gdr_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c, src/uct/sm/cma/cma_iface.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c, test/gtest/uct/uct_test.cc
- added dedicated & bandwidth BW values
- added function to calculate actual bandwidth based on
dedicated/shared bandwidth values
- updated score functions to use new call
=> UCP: added infra for bandwidth manipulation

src/tools/info/tl_info.c, src/uct/cuda/gdr_copy/gdr_copy_md.c
Picks the fixes for coverity warnings from master to 1.6
Fixes potential bugs
=> UCT, UCP: Fix coverity warnings - v1.6

src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/sys/string.h, src/uct/ib/base/ib_md.c, test/gtest/ucs/test_config.cc
- also added UCS_VALUE_AUTO_STR preprocessor string to use in strcmp
=> PARSER: added bandwidth auto value

src/uct/tcp/tcp_iface.c
Move check for thread mode above to avoid possible memory leaks
Fix memory leaks for iface resources
Move at the beginning of the function
=> UCT/TCP: Fix possible memory leak

contrib/test_jenkins.sh
Add running of Coverity
This could find additional errors
Run for release and debug build based on an argument passed to the function
=> JENKINS: Run Coverity for release build - v1.6

src/ucs/stats/stats.c
Use usual cond var to wait for condition on platforms without futexes.
=> UCS/STATS: Futexes are only available on Linux.

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.h
fix internal docs
apply CR comments to #3978
=> UCP: fix internal docs

test/gtest/uct/test_p2p_am.cc
=> TEST/P2P_AM: Add locking to async progress function and to main thread

src/ucs/Makefile.am, src/ucs/arch/aarch64/cpu.h, src/ucs/arch/cpu.c, src/ucs/arch/cpu.h, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/x86_64/cpu.c, src/ucs/arch/x86_64/cpu.h, src/ucs/sys/compiler_def.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, test/gtest/ucs/test_sys.cc
- also added gtest for new call
=> UCS: added system CPU cache size processing

src/ucm/api/ucm.h, src/ucm/util/reloc.c, src/ucm/util/sys.c, src/ucm/util/sys.h, src/ucs/config/ucm_opts.c, test/gtest/configure.m4, test/gtest/ucm/malloc_hook.cc, test/gtest/ucm/test_dlopen/Makefile.am, test/gtest/ucm/test_dlopen/dlopen_test_do_load.c, test/gtest/ucm/test_dlopen/rpath-subdir/Makefile.am, test/gtest/ucm/test_dlopen/rpath-subdir/configure.m4, test/gtest/ucm/test_dlopen/rpath-subdir/dlopen_test_rpath.c
- added processing of rpath section in caller module
- added gtest for new functionality
fixes https://github.com/openucx/ucx/issues/4001
=> UCM/DLOPEN: added processing of rpath

LICENSE, src/uct/sm/mm/xpmem/Makefile.am
=> LICENSE: Add ANL copyright

src/ucp/core/ucp_worker.c
Remove extra semicolon
To beautify the code
Pressing del key
=> UCP/WORKER: remove extra semicolon

src/tools/perf/lib/libperf.c, src/ucm/malloc/malloc_hook.c, src/ucm/mmap/install.c, src/ucm/util/replace.c, src/ucp/dt/dt_generic.c, src/ucs/datastruct/ptr_array.c, src/ucs/debug/memtrack.c, src/ucs/debug/memtrack.h, src/ucs/memory/memtype_cache.c, src/ucs/memory/rcache.c, src/uct/base/uct_md.c, src/uct/base/uct_mem.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/rocm/ipc/rocm_ipc_cache.c, test/gtest/ucs/test_memtrack.cc
Collection of portability fixes for malloc(3)-related stuff.
=> malloc() use portability fixes.

src/uct/ib/rc/accel/rc_mlx5_devx.c
Fix `osu_bw` hang with devx + HW TM
=> UCT/DEVX: Fix XRQ tm_list size init

src/uct/tcp/tcp_ep.c
Don't copy TCP AM header to TX buffer, it's already there
Fixes #4095
Calculate offset based on a TCP AM header size
=> UCT/TCP: Don't copy TCP AM header to TX buffer

buildlib/azure-pipelines.yml
Improve AZP checks reporting.
To make developers' life a bit more comfortable.
=> AZP: improve reporting

src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_devx.c, src/uct/ib/rc/accel/rc_mlx5_iface.c
Add support for cyclic XRQ topology with DEVX and tag offload  
It gives ~10-20 nano performance improvement on latency benchmarks
Setting wq type when creating XRQ via DEVX. To be added for SW TM as well
=> UCT/RC/DC: Add cyclic XRQ support for HWTM with DEVX

src/ucp/wireup/address.c
Fixes unified mode
Iface latency overhead depends on NUMA locality, which may be different on different processes depending on their mapping/pinning (even on homogeneous clusters). 
Packing latency overhead in addition to rsc index to the address in unified mode fixes the issue.
=> UCP: Fix unified mode

src/ucp/core/ucp_am.c, src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_worker.c, src/ucp/stream/stream.h, src/ucp/wireup/wireup_ep.c, src/ucs/config/parser.c, src/ucs/debug/debug.c, src/uct/ib/base/ib_iface.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/tcp/sockcm/sockcm_md.c
Fix Clang warnings in UCP, UCT, UCS
Fixes warnings found during AZP testing in #4112
=> UCP, UCS, UCT: Fix clang warnings

config/m4/compiler.m4
- added PGI specific switches to suppress annoying warnings
=> BUILD: added PGI specific switches

buildlib/azure-pipelines.yml, buildlib/fedora.Dockerfile
=> AZP: enable csclng checks — v1.6

src/uct/tcp/tcp_ep.c
Calculate TX buffer offset when it is used
This needs to be done after `sendv()` called - it updates `tx.offset` value
Move under `uct_tcp_ep_ctx_buf_need_progress()` if statement
=> UCT/TCP: Calculate TX buffer offset when it is used

src/ucp/wireup/address.c
Fix packing/unpacking worker address in unified mode. 
Processes may chose different devices for atomics depending on NUMA locality. When unpacking address in unified mode need to know whether the remote resource can be used for atomics on the peer (i.e. it is a part of `worker->atomic_tls` bitmap).
Fixes #4160
=> UCP: Fix atomic caps in unified worker address

src/ucp/core/ucp_context.c
est_num_ppn fix - don't overwrite the params.est_num_ppn setting in the next step to 1
=> Fixes est_num_ppn setting from params

src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/config/types.h, test/gtest/ucs/test_config.cc
- added on/off/auto datatype to parser
- added gtest for new datatype
- minor update for test_config initialization
=> UCS/PARSER: added on/off/auto datatypes

src/uct/api/uct.h
Fix `uct_ep_pending_add` documentation
Improves UCT API documentation
Fix `@param flags` descriprtion
=> UCT/API: Fix uct_ep_pending_add documentation

bindings/java/src/main/native/jucx_common_def.cc, src/ucp/api/ucp.h, src/ucs/type/status.h, test/examples/ucp_hello_world.c, test/gtest/ucp/test_ucp_am.cc, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucs/test_type.cc
=> UCP/API/TEST: Fix ucs_status_ptr_t checks

test/gtest/ucp/test_ucp_mem_type.cc
Fixes valgrind issue
Fixes #4134
1. Add `mem_buffer::set()` that does `memset`/`cudaMemset` depends on a memory type
2. Use it in UCP mem type test to initialize a send buffer
=> GTEST/MEM_BUFFER, GTEST/UCP: Fix valgrind issue

src/ucp/core/ucp_rkey.c, src/ucs/debug/log.c, src/ucs/debug/log.h, src/ucs/sys/string.c, src/ucs/sys/string.h, src/uct/base/uct_iface.c
- added dump of payload (first 64 bytes) into
stub AM handler to simplify debugging
=> IFACE/STUB-AM-HANDLER: added dump of payload

config/m4/gdrcopy.m4, src/uct/cuda/gdr_copy/gdr_copy_ep.c, src/uct/cuda/gdr_copy/gdr_copy_md.c, src/uct/cuda/gdr_copy/gdr_copy_md.h
_Adding support for new versions of gdrcopy_
_Breaking changes in gdrcopy API_
@bureddy
=> UCT/CUDA: Support new gdrcopy API.

src/uct/ib/rdmacm/rdmacm_iface.c, src/uct/tcp/sockcm/sockcm_iface.c
Inherit UCT base config table
Report correct UCT iface attributes
Inherit UCT base config table when defining a specific UCT config table
=> UCT/IB/RDMACM, UCT/SOCKCM: Inherit UCT base config

config/m4/compiler.m4, src/ucm/bistro/bistro.c, src/ucs/arch/atomic.h, src/ucs/async/async.c, src/ucs/async/thread.c, src/ucs/memory/rcache.c, src/ucs/sys/compiler.h, src/uct/base/uct_cm.c, src/uct/base/uct_iface.c, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/base/uct_mem.c, src/uct/base/uct_worker.c, src/uct/sm/cma/cma_ep.c, src/uct/sm/cma/cma_md.c, src/uct/sm/knem/knem_iface.c, src/uct/sm/mm/base/mm_def.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/mm/base/mm_md.c, src/uct/tcp/sockcm/sockcm_ep.c, src/uct/tcp/sockcm/sockcm_iface.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_net.c, test/gtest/ucs/test_rcache.cc
- added atomic_sub call
- fixed void* arithmetics
- minor datatype conversions
- suppressed compiler error on dynamic size arrays
=> UCT/IB/SHM: portion of fixes for PGI compiler

src/uct/ib/base/ib_iface.h, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
- also optimized fence flag evaluation
=> IB/ACCEL: added RDMA_PUT fenced operations

src/uct/api/uct_def.h
Add more details about message context used by to `uct_tag_unexp_eager_cb_t`
=> UCT/API: tag msg context clarification

src/uct/ib/rdmacm/rdmacm_cm_ep.c
=> UCT/RDMACM_CM: return correct err status

test/gtest/ucp/ucp_test.h, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/ib/test_rc.h, test/gtest/uct/test_tag.cc
- More tests for MP XRQ
- Some minor fixes
Release of UCT descriptor involves quite complicated flow in UCT, need to properly test it
=>  GTEST/UCT/RC: desc release tests for MP XRQ

src/uct/tcp/tcp_ep.c
Close TCP socket when unable to send data anymore and report an error to a user from `uct_ep_am_short()` and `uct_ep_am_bcopy()` if `uct_tcp_ep_am_send()` is unable to send data
Fixes #4243 
Return error code from `ucs_socket_send_nb()` to a caller
=> UCT/TCP: Close TCP socket when unable to send data

src/ucp/rma/amo_sw.c, src/ucp/rma/rma_send.c, src/ucp/rma/rma_sw.c, src/ucp/stream/stream_recv.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/ucp/tag/tag_match.inl, src/ucp/tag/tag_recv.c, src/ucp/wireup/address.c, src/ucp/wireup/select.c, src/ucp/wireup/signaling_ep.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_ep.c
- fixed wireup, amo, rma components
=> UCP/PGI: fixes for PGI compiler

src/ucp/core/ucp_worker.h, src/ucp/wireup/address.c
Refactoring: use `ucp_worker_iface_get_attr` where it's relevant
=> UCP/WORKER: use ucp_worker_iface_get_attr

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, test/gtest/ucp/test_ucp_wireup.cc
Fix a bug in UCP address packing (AMO tls were disabled)
Fixes #4276
=> UCP/WIREUP: Fix address packing (AMO)

test/examples/ucp_client_server.c
To test `ucp_client_server` functionality for a specific IP address.
=> TEST/EXAMPLES: explicitly set listener address; use INADDR_ANY if not provided

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/wireup/address.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.h
address code review comments to #4252
=> UCP/WIREUP/CM: ucp_ep_create, client side (2)

src/ucp/core/ucp_ep.c
Adjust maximal short value by RNDV
Fixes inability to start RNDV or protocol from 0 since max short is not adjusted by the limit
Adjust maximum short value by RNDV during EP initialization
=> UCP/EP: Fix max short calculation when UCP_RNDV_THRESH != auto

src/tools/info/ucx_info.c, src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/lib/uct_tests.cc, src/tools/perf/perftest.c, src/ucp/wireup/address.h, src/ucs/sys/string.h, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucs/test_sys.cc
- set of fixes for PGI compiler of UCX tools
=> TOOLS: fixed compilation by PGI compiler

test/gtest/common/test.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucs/test_datatype.cc, test/gtest/ucs/test_pgtable.cc, test/gtest/ucs/test_rcache.cc, test/gtest/uct/test_p2p_mix.cc, test/gtest/uct/uct_test.cc
- set of fixes for compilation by PGI compiler
=> GTEST/PGI: fixes compilation by PGI compiler

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/uct/api/uct.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/cuda/base/cuda_md.c, src/uct/cuda/base/cuda_md.h, src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/copy/rocm_copy_md.c
- use const void* buffers for memory type detection
this is some pre-devel for SW RMA over CUDA
=> MEM/TYPE-DETECT: use const pointer

src/uct/ib/base/ib_iface.h, src/uct/ib/configure.m4, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_devx.c, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, test/gtest/uct/ib/test_rc.cc, test/gtest/uct/test_tag.cc
Multi-Packet support for RCX tl
Better tag offload performance and memory consumption
Still need to polish a bit, creating PR to trigger testing
=> UCT/RCX: MP XRQ support

config/m4/compiler.m4, src/tools/perf/lib/Makefile.am, src/tools/perf/lib/configure.m4, test/examples/Makefile.am, test/gtest/Makefile.am, test/gtest/configure.m4
- fixed compilation flags detection for PGI compiler
=> TOOLS/TESTS/BUILD-PGI: fixed compilation flags

NEWS
=> News update for 1.7.0-rc1

test/gtest/ucs/test_async.cc
=> TEST/ASYNC: Add retries to test_async.ctx_event_block

buildlib/azure-pipelines-release.yml
(cherry picked from commit ab86fb41a12a359489c02f5b89bf4707b68e6594)
=> AZP: edit existing release if exist - v1.7.x

buildlib/azure-pipelines-release.yml
(cherry picked from commit ab86fb41a12a359489c02f5b89bf4707b68e6594)
=> AZP: edit existing release if exist — v1.6

src/uct/cuda/cuda_ipc/cuda_ipc_md.c
=> UCT/CUDA_IPC: Fix peer_accessible check

src/uct/ib/rc/base/rc_iface.c
- added jump label for more accurate error handling/resource cleaning
=> RC/IFACE: fixed potential leak on failed rc iface init

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h
This PR adds sockaddr/cm wireup, part 2. part 1 was implemented in #4252 
To prepare for adding close protocol
=> UCP/WIREUP/CM: ucp_ep_create, server side (accept)

src/ucp/tag/offload.c, src/ucp/tag/offload.h
- Minor tag offload fixes
- Added clarification on tags hashing in tag offload flow
=> UCP/TAG: Minor tag offload fixes

src/ucp/core/ucp_ep.c
Fix printing of max_short value in EP when `UCX_RNDV_THRESH=1`, i.e. when expecting that max_hosrt will be used for zero-size messages
Changes from
```
```
to
```
```
Handles `max_short=0` separately
=> UCP/CORE: Fix printing of max_short value in EP

src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.h
remove ucp_wireup_select_info_t::reachable
https://github.com/openucx/ucx/pull/4266#discussion_r339593364
@yosefe pls take a look
=> UCP/WIREUP: remove ucp_wireup_select_info_t::reachable

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.h, src/ucp/proto/proto_am.inl, src/ucp/tag/eager_rcv.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/rndv.c, src/ucp/tag/tag_match.h, src/ucp/tag/tag_match.inl, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
Add UCP support for multi fragment tag eager offload protocol
Better performance and memory consumption for unexpected tag eager offload flow 
Align with existing software tag protocol whenever possible
=> UCP/TAG: Support for multi-fragment tag offload protocol

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/common/test_obj_size.cc
Backport of #4313 to v1.7.x
Fixes #4461
=> UCT/TCP, UCS/SYS: Repeat connection establishment when detected dropped connections

src/uct/ib/base/ib_md.c
=> UCT/IB: Minor code style fixes

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
=> JAVA/TEST: Wait for progress thread to finish before destroying ep

src/ucs/sys/topo.c, src/ucs/sys/topo.h, test/gtest/ucs/test_topo.cc
Based on feedback from @yosefe  
First step before adding implementation to discover, query distance between system devices. Will followup with implementation along the lines of https://github.com/openucx/ucx/pull/4321
=> UCS/SYS/TOPO: Add UCS topology query/print API

contrib/test_jenkins.sh
- fixed test-gcc-latest cleanup to fix valgrind testing
=> AZP: fixed valgrind test

buildlib/azure-pipelines.yml, buildlib/tests.yml
=> AZP: run tests in MLNX pool

src/ucp/core/ucp_worker.c
Improve error flow of worker creation
To avoid segfaults during ifaces cleanup when OOM. Like happened in http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/2828/pipeline/109
```
[2019-11-24T19:01:40.369Z] [ RUN      ] shm_ib/test_ucp_stream.send_recv_data_recv_iov/0 <shm,ib>
[2019-11-24T19:01:40.369Z] [boo31:8327 :0:8327] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
[2019-11-24T19:01:40.933Z] 
[2019-11-24T19:01:40.933Z] /scrap/jenkins/workspace/ucx-2/contrib/../src/ucp/core/ucp_worker.c: [ ucp_worker_close_ifaces() ]
[2019-11-24T19:01:40.933Z]       ...
[2019-11-24T19:01:40.933Z]      1036     UCS_ASYNC_BLOCK(&worker->async);
[2019-11-24T19:01:40.933Z]      1037     for (iface_id = 0; iface_id < worker->num_ifaces; …
```
=> UCP/CORE: Improve worker creation error flow

src/uct/sm/mm/xpmem/mm_xpmem.c
Fix XPMEM compilation on ppc64le platform by converting segid/apid to unsigned long for printf()
Make pmem module compile on ppc
@amaslenn
=> UCT/XPMEM: Fix build on ppc64le

src/ucs/sys/string.c, src/ucs/type/status.c, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/ib/rdmacm/rdmacm_cm_ep.h, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
fix error codes of uct_ep_disconnect and EP states in RDMACM implementation
uct_ep_disconnect returns BUSY ERR if try to disconnect from disconnect callback in scope of https://github.com/openucx/ucx/pull/4445
=> UCT/IB/RDMACM/CM: fix error codes of uct_ep_disconnect and EP states

src/ucm/cuda/cudamem.c, src/ucm/util/replace.h, src/uct/cuda/base/cuda_md.c, src/uct/cuda/cuda_copy/cuda_copy_ep.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/gdr_copy/gdr_copy_ep.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_md.c
- set of changes for cuda module to support PGI 19
=> PGI-19: fixes for cuda module

docs/source/download.md, docs/source/faq.md, docs/source/index.rst
Add Download and FAQ from gh-pages.
Rendered HTML: https://openucx.readthedocs.io/en/topic-docs-rtd-add-download-and-faq-pages
=> DOCS/RTD: Add download and FAQ pages

src/ucs/Makefile.am, src/ucs/datastruct/linear_func.h, test/gtest/ucs/test_math.cc
Represent performance of protocols, transport, etc. as linear functions
=> UCS/DATASTRUCT: Add linear function data structure

bindings/java/pom.xml.in, bindings/java/src/main/java/org/openucx/jucx/examples/UcxBenchmark.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java, bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConnectionRequest.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpointParams.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListener.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListenerConnectionHandler.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListenerParams.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/main/native/listener.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
Request handler functionality.
To be able to create endpoint on listener connection request. 
TODO: reject functionality.
=> JUCX: connection request handler functionality.

src/ucs/sys/sys.c
Remove extra `if` statement (cosmetic change)
Just a cosmetic change
remove `if (flags & SHM_HUGETLB)`
=> UCS/SYS: Remove extra if (cosmetic change)

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/uct/ib/rdmacm/Makefile.am
- fix stub EP configuration
- fix UCT/RDMACM/IB dependencies
- fix sockaddr storage for IPv6
- fix memory errors
bugfix
=> UCP/UCT/CM: bunch of CM related fixes

src/tools/perf/lib/libperf.c
Report error when using non-host memory type for UCP RMA and AMO
We should report error to user instead of crashing/failing or etc in UCP level
1. Add new check for API type, memory type and command in ucx_perf_test_check_params
2. Print error only in case of it was requested by flags
=> TOOLS/PERF: Report error when using non-host memory type for UCP RMA and AMO

NEWS
* Removing RC label from the news
* Updating date
=> NEWS: Bumping up the date for v1.7.0 release

src/ucp/wireup/address.c
- Add useful assert for address pack/unpack
- Compare `rsc_index` with number of TLs in `dev_tl_bitmap` when looking for the last resource
- Code style fixes
Fix bugs and code style + improve debugging
- Use `ucs_assrty()`
- Use resulted `dev_tl_bitmap` instead of `dev->tl_bitmap`
- Add missing brackets + check for `== 0` instead of `!` for numberic values
=> UCP/WIREUP: Add useful asserts for address pack/unpack

src/ucp/core/ucp_worker.h, src/ucp/tag/offload.c, src/ucp/tag/rndv.c, src/uct/cuda/cuda_copy/cuda_copy_ep.c, test/gtest/Makefile.am, test/gtest/ucp/test_ucp_tag_mem_type.cc
=> UCP/RNDV: Fix pipeline rndv protocol when tag recv_length > send_length

test/gtest/uct/ib/test_rc.cc
=> UCT/GTEST: Fix stress_iface_ops test

contrib/test_jenkins.sh, contrib/ucx_perftest_config/test_types_ucp, src/ucp/tag/rndv.c
Fixes https://github.com/openucx/ucx/issues/4722
=> UCP/RNDV: Fix mem type for rma bw lane selection with pipeline protocol

config/m4/java.m4
Fixes `/opt/azure/agent-03/AZP_WORKSPACE/1/s/contrib/../configure: line 23943: ,: command not found `
=> JUCX: [minor] fix warning on configure

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
=> UCT/IB/MLX5: Detect broken DEVX support

src/uct/sm/knem/knem_ep.c
Added check for ICOPY current status + minor code cleanup
UCT/SM/KNEM doesn't report any error from RMA operations something wrong happened during data copying, since we checking only an `ioctl()` return value (this return value only shows errors that happen during preparation for data transfer thru KNEM). In order to report errors during doing KNEM synchronous inline copy (e.g. KNEM uses wring remote cookie), we have to check for `knem_cmd_inline_copy::current_status` even if `ioctl()` returns `0`.
1. Add check for `knem_cmd_inline_copy::current_status != KNEM_STATUS_SUCCESS` after `ioctl()`
2. Removed extra initialization for `knem_cmd_inline_copy` fields
3. Fixed code style
=> UCT/SM/KNEM: Check ICOPY current status + minor code cleanup

NEWS
Update news
Master news are behind 1.7.x
=> NEWS: Backport NEWS file from v.1.7.x branch.

src/uct/ib/rc/accel/rc_mlx5_iface.c
temporary workaround for uct_ep_flush(cancel) case when EP has been
destroyed but successful CQE was not polled out from the CQ
better fix https://github.com/openucx/ucx/pull/4743 takes longer time then expected due to corner cases on different HW
check NULL pointer
=> UCT/IB/RC/MLX_5: workaround segfault in poll TX on deleted EP

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpParams.java, bindings/java/src/main/native/context.cc, bindings/java/src/test/java/org/openucx/jucx/UcpContextTest.java
Ability to provide additional configuration and global options params before context creation.
As requested in #4724
=> JUCX: set dynamic configuration and global options.

src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h
Introduce UCX_UD_MAX_WINDOW parameter, which makes upper limit of UD congestion avoidance algorithm configurable.
Allow users configure different window size to reduce network congestion.
=> UCX/IB/UD: Add UCX_UD_MAX_WINDOW param

src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h
Introduce UCX_UD_MAX_WINDOW parameter, which makes upper limit of UD congestion avoidance algorithm configurable.
Allow users configure different window size to reduce network congestion.
backport from https://github.com/openucx/ucx/pull/4824
=> UCX/IB/UD: Add UCX_UD_MAX_WINDOW param - v1.8.x

src/ucp/core/ucp_ep.c, src/ucp/wireup/wireup_cm.c, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc
backport of #4761, #4771
don't block CI for other PRs
=> backport of #4761, #4771 to v1.8.x

src/ucp/dt/dt_iov.h
=>  UCP/DOC: Multiple fixes in UCP iov doc

AUTHORS
The author list is based of git log.
The list has not been updated for a while
```git shortlog --summary --numbered --email | awk '{print $2" "$3}' | sort -u```
=> AUTHORS: Updating authors list

src/tools/perf/perftest.c
Signed-off-by: Zhu Yanjun <yanjunz@mellanox.com>
=> TOOLS/PERF: rename latency to overhead in bandwidth

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, src/uct/ib/dc/dc_mlx5.c
- fixed hang on DCX IMB Alltoall bench
=> DCX: fixed hang on IMB alltoall

config/m4/compiler.m4, src/ucs/arch/cpu.h, src/ucs/config/parser.h, src/ucs/debug/debug.c, src/ucs/type/class.h, src/uct/base/uct_component.h, src/uct/ib/base/ib_md.h, src/uct/sm/self/self.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c
- added build flag -Wnested-externs
- fixed typo
- re-organized C-only flags specification
=> BUILD/FLAGS: added build flag -Wnested-externs

src/ucs/arch/aarch64/cpu.h
- fixed compilation
fixes https://github.com/openucx/ucx/issues/4886
=> BUILD/ARM-TX2: fixed compilation

test/gtest/ucp/test_ucp_wireup.cc
Need more stable solution to identify whether we should check for scalable-only TLs or not.
Fix scalability tests for Ethernet-only systems, e.g.:
```
[     INFO ] Testing 257 number of EPs
/home/pavsha01/ucx/contrib/../test/gtest/ucp/test_ucp_wireup.cc:992: Failure Value of: test_est_num_eps_fallback(test_min_max_eps + 1, min_max_eps, has_only_unscalable)
Actual: false
Expected: true
[  FAILED  ] ud_tcp/test_ucp_wireup_fallback.est_num_eps_fallback/0, where GetParam() = ud_x,ud_v,tcp (86 ms)
```
Check whether we have any scalable devices to perform data transfer (i.e. CM and ACC TLs are not suitable), and if there are such TLs - perform checks that are only scalable TLs are selected.
=> GTEST/UCP/WIREUP: Fix scalability test for Ethernet-only systems

buildlib/azure-pipelines.yml, buildlib/tests.yml
=> AZP: run new bunch of tests - legacy

src/uct/ib/rdmacm/rdmacm_cm.c
fix reachability for IB local address case
If all GIDs of IB device have the same subnet prefix (`fe80:0000:0000:00c6`), rdmacm does not fill `qp_attr.ah_attr.is_global` since it's accessible by LID. As a result GID won't be added to IB address and remote side will initialize `subnet_prefix` with `UCT_IB_LINK_LOCAL_PREFIX` value (`fe80`) which doesn't match to actual one.
fill GID info from rdmacm id for IB local address as well
=> UCT/IB/RDMACM/CM: fix reachability

buildlib/azure-pipelines.yml
=> AZP: run new bunch of tests - GPU

buildlib/azure-pipelines.yml, buildlib/tests.yml, contrib/test_jenkins.sh
Run "legacy" testing in AZP
Cherry-pick of https://github.com/openucx/ucx/pull/4899
=> AZP: run new bunch of tests - (legacy&GPU) — v1.8

src/ucs/arch/aarch64/cpu.h, src/ucs/debug/debug.c, src/ucs/sys/checker.h, src/uct/base/uct_md.h, src/uct/ib/mlx5/ib_mlx5.h
- added missing include config.h
- fixed incorrect macro name
- some system defined macro was checked by #ifdef instead #if
=> PREPROCESSOR/MACRO: fixed some preprocessor macro

buildlib/azure-pipelines.yml, contrib/test_jenkins.sh
1. Run "new" tests in Azure.
2. Update number of parallel tasks to use.
Align v1.8.x with master
Related PRs: https://github.com/openucx/ucx/pull/4951 https://github.com/openucx/ucx/pull/4942
=> CI: port updates from master — v1.8

buildlib/azure-pipelines.yml
=> AZP: run new bunch of tests - new

src/ucs/async/async.c, src/ucs/async/pipe.c
1. Avoid extra `if` statement
2. Wrap by `()` conditions in `if` statement
Minor code fixes
1. Check for `NULL` at the beginning of the function, return `UCS_OK` if `if (async == NULL)` takes true and then it is not needed
2. Add `()` for each condition in `if` statement
=> UCS/ASYNC: Minor code fixes

contrib/test_jenkins.sh, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/lib/uct_tests.cc
- check for all .c files include config.h
=> JENKINS: check for config.h

config/m4/compiler.m4, configure.ac, contrib/test_jenkins.sh, src/ucp/wireup/wireup_cm.c, test/apps/Makefile.am, test/apps/iodemo/Makefile.am, test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
add IO demo application for sockaddr
Yet another client/server example but written in C++ and more close to real world application than ucp_client_server.c
=> TEST/APPS/IO_DEMO: add IO demo application for sockaddr

src/ucp/wireup/address.c
1. Rename `UCT_ADDRESS_FLAG_ATOMIC*` to `UCP_ADDRESS_FLAG_ATOMIC*`
2. Introduce pack/unpack flags functions
3. Remove trailing empty line at the end of the `ucp/wireup/address.c` file
1. This is UCP code, they should have UCP prefix
2. To simplify code and will use them later in #4962 PR to pack/unpack event flags in the same way
3. Should have only one empty line at the end of the source file
1. Rename macros and fix all places where they are used
2. Move pack and unpack code to `ucp_address_pack_flags`/`ucp_address_unpack_flags` and use them instead
3. Remove an excessive line
=> UCP/WIREUP: Minor code cleanups in address code

buildlib/azure-pipelines-pr.yml, buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.yml, buildlib/tests.yml
Sync AZP configs with the master branch.
Related PRs: https://github.com/openucx/ucx/pull/4997 and https://github.com/openucx/ucx/pull/4989
=> AZP: align buildlib/ with master - v1.8.x

src/uct/ib/dc/dc_mlx5_devx.c
=> UCT/MLX5/DEVX: Fix setting DSCP priority for RoCE

src/ucs/datastruct/arbiter.c, src/ucs/datastruct/arbiter.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/ud/base/ud_inl.h, test/gtest/ucs/test_arbiter.cc
=> UCS/ARBITER/TEST: Allow same-group rescheduling from dispatch callback

src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5.h
Fix invalid doorbell record read by HW
@Artemy-Mellanox
=> UCT/IB/MLX5: Initialize doorbell record to zero

test/gtest/ucs/test_async.cc
=> TEST/ASYNC: Add retries to all tests

src/ucp/core/ucp_am.c
Some of UCP AM functions missing worker lock while accessing/changing worker resources
=> UCP/AM: Add missing locks in some functions

AUTHORS
Fix English in paragraph crediting community contribution.
=> AUTHORS: minor fix for English content

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, test/gtest/uct/ib/test_devx.cc
=> UCT/IB/MLX5: Use proper MMIO mode for DEVX

contrib/test_jenkins.sh, test/apps/test_ucx_tls.py
add verbose to test_ucx_tls.py
for debugging purpose
=> TEST/APPS: add verbose to test_ucx_tls.py

src/ucp/core/ucp_context.c, test/gtest/ucp/ucp_test.cc
fixes https://github.com/openucx/ucx/issues/4808
Update: all commits related to close protocol are moved to https://github.com/openucx/ucx/pull/5075 to avoid merge conflicts
=> UCP/CONTEXT: fix CM initialization

test/gtest/uct/ib/test_rc.cc
cancel posted ops before ep destroy
to clean up SW and HW resources before destroying EP
using uct_ep_flush
=> GTEST/UCT: fix test_rc_get_limit.get_zcopy_purge

src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc, test/gtest/ucp/test_ucp_perf.cc
Fix  #4975
Issue introduced by #4969
=> TOOLS/PERF: Fix hang in perftest with armclang compiler

LICENSE
Copyright years time-stamp have not been updated in a while.
=> LICENSE: Updating copyright dates

NEWS
Master new is outdate. Bringing changes from v1.8.0
=> NEWS: Backport NEWS v1.8.0 to Master

src/ucs/debug/log.c
Log file formatting cleanups
Avoid code duplication
Will be used in #5028
Define FMT/ARG helper macros and use them
=> UCS/LOG: Log file formatting cleanups

docs/source/download.md, docs/source/index.rst, docs/source/ucx_features.rst
* Removing outdated feature list
* Fix broken links
* Minor clarifications
Pure magic
=> DOCS: readthedocs update

src/ucp/proto/proto_am.inl
Minor code cleanups in proto AM
To align with the existing UCX code style
1. Fix the name of the variable
2. Fix code alignments
=> UCP/PROTO: Minor code cleanups in proto AM

contrib/test_jenkins.sh, test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Improve IO demo test application
Make it more configurable/robust
Fixes, cleanups and new parameters
=> TEST/APPS: Improve IO demo

src/ucp/core/ucp_request.inl, src/ucp/rma/rma.inl, src/ucp/rma/rma_send.c, src/ucp/tag/tag_send.c
- added implementation of get/put _nbx calls
=> UCP/RMA/NBX: added implementation of NBX API

src/uct/ib/ud/base/ud_ep.c
=> UCT/UD: Stop resending if the resend window was acknowledged

src/ucp/api/ucp.h, src/ucp/rma/amo_send.c
- added atomic-fetch nbx calls
=> UCP/API: added atomic fetch nbx API

test/gtest/ucs/test_memtype_cache.cc
fixes https://github.com/openucx/ucx/issues/5158
=> GTEST/MEMTYPE: destroy cache only if it is created.

src/ucp/rma/amo_send.c
- added implementation of ucp_atomic_fetch_nbx function
- ucp_atomic_fetch_nb is re-implemented using fetch_nbx call
=> AMO/NBX: added implementation of fetch-op

src/ucp/core/ucp_worker.c
Fix support for Event FD/CB
UCP doesn't arm for events if UCT support async callback invocation event mechanism
1. Add all UCTs with FD/CB event mechanisms to the ARM list
2. If user support both Event mechanisms, use CB
=> UCP/CORE: Fix support for Event FD/CB

src/ucm/event/event.c, src/ucm/mmap/install.c
- there was missing test for madvice/vm_unmap call
- updated aggregate state calculation for test_events
=> MHOOK/TEST: fixed issue in test_events

src/uct/ib/base/ib_md.c
=> UCT/IB: Fix typo in REG_MT_CHUNK description

src/ucm/event/event.c
- fixed resource leak in shmat implementation
- minor optimization
=> UCM/SHMAT: fixed resource leak

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
TEST/APPS:Improve IO demo for 4K messages throughput 
There are a lot of overhead on malloc/free calling during data reading and writing.
1. Use memory pool.
2. Replace std::list with ucs format list API.
3. Replace std::string in log function with char array.
=> TEST/APPS:Improve IO demo for 4K messages throughput

src/ucp/core/ucp_mm.h, src/ucp/core/ucp_worker.c, src/ucp/tag/rndv.c, src/ucp/tag/rndv.h, src/uct/cuda/cuda_copy/cuda_copy_ep.c
Receiver **GET** the fragment from source and then PUT it to the mem-type destination buffer
- sender sends address and rkey in the RTS message
- receiver initiates the pipelining
o GET fragment from receiver
o PUT them to DEVICE destination buffer).
=> UCP/RNDV/CUDA:  MEMTYPE staging protocol enhancements

test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
code cleanup, remove unused function
=> GTEST: code cleanup

src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/base/ud_log.c, test/gtest/uct/ib/test_ud_ds.cc
=> UCT/UD: Include path index in connection lookup

src/ucm/api/ucm.h, src/ucm/event/event.c, src/ucm/mmap/install.c, src/ucm/mmap/mmap.h, src/ucm/util/log.c, src/ucm/util/log.h, test/gtest/ucm/malloc_hook.cc
- added ucm_test_external_events function
- added tests for new function
- bit update test for bistro hooks
=> UCM/TEST-EVENTS: added test_external_events call

LICENSE
Add SBU copyright info as requested by Pasha
=> LICENSE: Add LICENSE copyright stanza for SBU

buildlib/az-distro-release.yml, buildlib/azure-pipelines-pr.yml, buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.md, buildlib/azure-pipelines.yml, buildlib/centos7-release.Dockerfile, buildlib/docker-compose.yml, buildlib/fedora.Dockerfile, buildlib/jucx-publish.yml, buildlib/push-release-images.sh, buildlib/ubuntu-release.Dockerfile, contrib/buildrpm.sh, ucx.spec.in
CI configs synced with the master.
RPM/SPEC changes are required for v1.8.1.
Koji build verified: https://koji.fedoraproject.org/koji/taskinfo?taskID=45574030
=> CI/RPM/SPEC: sync with master - v1.8.x

ucx.spec.in
Provide a more general description of UCX in RPM spec
=> SPEC/DOC: Generalize UCX package description

src/ucp/rma/flush.c
=> UCP/FLUSH: Support set_ep_failed() during flush

buildlib/azure-pipelines-pr.yml, contrib/test_jenkins.sh, src/uct/ugni/base/ugni_device.c, test/mpi/test_memhooks.c
=> AZP: run tests on HWI

src/ucp/api/ucp.h, src/ucp/core/ucp_ep.c, src/ucp/rma/flush.c
- added ucp_worker_flush_nbx, ucp_ep_flush_nbx and ucp_ep_close_nbx calls
- part of new request API activity
- added new calls
=> UCP/API: nbx API for flush and disconnect calls

contrib/test_jenkins.sh
Reduce testing time and avoid timeouts
=> JENKINS: Reduce perftest iterations

src/ucp/Makefile.am, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_types.h, src/ucp/proto/proto.c, src/ucp/proto/proto.h
Start adding protocols which allow configuring thresholds and lanes per buffer/memory type, and decouple protocol performance calculation from protocol selection
WIP implementation: https://github.com/yosefe/ucx/tree/wip/protov2
Introduce structures for defining protocols and key for selection
=> UCP/PROTO: Introduce protocol definition template

test/apps/iodemo/io_demo.cc
Add chunk size support for io demo.
Sometimes we want to send data with irregular size as small chunks.
Divide data as small chunks, send and receive as chunks.
=> TEST/APPS: Add chunk size support for io demo

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h
Improve server side error flows
=> UCP/WIREUP/SOCKADDR: improve server side error flows

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_worker.c, src/ucp/wireup/address.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/ucp/wireup/wireup_cm.c
prefer connect to EP in CM case
client server connection is naturally p2p
=> UCP/WIREUP: prefer connect to EP in CM case

NEWS, configure.ac
News update before 1.8.1 rc1
Bugfix release
=> NEWS: News update before 1.8.1 RC1

src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/memory/rcache.c, src/ucs/memory/rcache.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, test/gtest/ucs/test_rcache.cc
- added RCACHE_PFN_MAX_PAGES setting to allow multiple
pages evaluation
- updated pfn check to cover multiple pages
=> UCS/PFN: enabled evaluation of multiple pages

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/stream/stream_recv.c, src/ucp/stream/stream_send.c
- added nbx notation for stream API
=> UCP/API: nbx API for stream calls

src/ucp/core/ucp_request.inl, src/ucp/dt/dt_iov.h, src/ucs/datastruct/frag_list.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_devx.c, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm_ep.c
- suppressed some false positives detected by cppcheck on Fedora 32 distro
=> TEST/FEDORA-32: suppressed false positives

buildlib/azure-pipelines-release.yml, buildlib/centos7.Dockerfile
* Added `rpm-build` to centos7.Dockerfile
* Changed ref on `centos7:2` container image
in the azure-pipelines-release.yaml
=> AZP: Upload src.rpm/tar.gz to release page

ucx.spec.in
Pull request #5314 was merged without passing tests
=> SPEC: Bump changelog to new version - v1.8.x

src/ucp/api/ucp.h, src/ucp/rma/rma_send.c
renamed param length->count
updated docs
=> UCP/RMA/NBX: renamed param

src/ucp/api/ucp.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/rma/flush.c, src/ucp/rma/rma.inl, src/ucp/rma/rma_send.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup_cm.c
- added nbx implementation for ucp ep & worker flush
- added nbx implementation for ucp ep close
=> UCP/NBX/FLUSH-CLOSE: added ep/worker flush and ep close nbx

src/uct/api/uct.h
=> UCT/DOC: uct_ep_create sockaddr/conn_request

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.inl
- there was issue in constant processing
- fixed
=> UCP/EP-CLOSE: fixed ep_close_nb impl

NEWS
RC preparation.
https://github.com/openucx/ucx/issues/5354
=> NEWS: RC2 news update

test/gtest/ucp/test_ucp_tag_offload.cc
Added tag offload test for ROCm
=> GTEST/UCP/TAG: Add tag offload test for ROCm

src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/stream/stream_recv.c, src/ucp/stream/stream_send.c
- added implementation of stream nbx calls
=> UCP/STREAM/NBX: added implementation of stream NBX

examples/ucp_client_server.c, examples/ucp_hello_world.c
- updated examples using send/recv NBX API
=> EXAMPLES/NBX: re-implemented examples using NBX API

test/apps/iodemo/io_demo.cc
Check time limit during connection retries
Fixes https://github.com/openucx/ucx/pull/5201#issuecomment-653504502
Check the run-time limit during connection retries
=> APPS/IO_DEMO: Check time limit during connection retries

buildlib/az-helpers.sh, buildlib/az-io_demo.sh, buildlib/az-network-corrupter.sh, buildlib/azure-pipelines-pr.yml, buildlib/io-demo.yml
Initial implementation of CI for `io_demo`
1. I removed all other checks to speed up testing and do not load regular CI.
2. This PR is to start the discussion about the implementation approach and test cases.
3. The review is required for `buildlib/io-demo.yml` only.
=> CI: initial setup for IO Demo testing

NEWS
=> NEWS: v1.8.1 release date update

src/tools/perf/perftest.c
Fix memory leak of msg size list + minor code cleanups
it fixes the memory leak, e.g. it's detected by ASan
```
==1439==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7fda383c212e in __interceptor_calloc ../../../../source/gcc-9.2.0/libsanitizer/asan/asan_malloc_linux.cc:153
#1 0x407671 in init_test_params /labhome/dmitrygla/work_auto/ucx/src/tools/perf/perftest.c:608
#2 0x40939c in parse_opts /labhome/dmitrygla/work_auto/ucx/src/tools/perf/perftest.c:873
#3 0x40ca38 in main /labhome/dmitrygla/work_auto/ucx/src/tools/perf/perftest.c:1680
#4 0x7fda35d923d4 in __libc_start_main (/lib64/libc.so.6+0x223d4)
SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```
Release the memory pointed by `ctx->params.super.msg_size_list` …
=> TOOLS/PERF: Fix memory leak of msg size list

src/ucm/cuda/cudamem.c, src/ucm/event/event.h, src/ucm/rocm/rocmmem.c, src/ucm/util/sys.c, src/ucm/util/sys.h, test/gtest/ucm/cuda_hooks.cc
Backport of https://github.com/openucx/ucx/pull/5299
=> UCM/CUDA: get context from memtype

src/uct/tcp/tcp_ep.c
Fix "Bad fd" warning from `ucs_close_fd()`
Fixes #5438
Need to check whether EP was created or not:
- if  created: close fd from EP
- if not created: close fd from local variable
=> UCT/TCP: Close fd in EP if EP was created

src/ucp/wireup/select.c
=> UCP/WIREUP: Check that number of lanes is within limit - v1.9.x

src/ucs/sys/string.c, src/ucs/sys/string.h, src/ucs/sys/topo.c, src/ucs/sys/topo.h, test/gtest/ucs/test_topo.cc
Backport of https://github.com/openucx/ucx/pull/5339
=> UCS/TOPO: distance query based on dev-path difference - v1.9.x

src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/mlx5/exp/ib_exp_md.c
- in case if ibv_reg_mr is failed then check pointer for page size
and in case if huge page is detected - ask to
set variable RDMAV_HUGEPAGES_SAFE
=> IB/HUGE-PAGE: added warning about huge page used

src/ucp/api/ucp.h
- fixed params specs for ucp_put_nbx and ucp_get_nbx calls
Fixes #5453
(to be ported to v1.9.x)
=> DOCS/PUT-GET-NBX: fixed params specs

test/gtest/common/test.cc, test/gtest/common/test.h
Allow stopping a test if some errors were detected
=> TEST/COMMON: Add method to get number of errors/warnings in the test

contrib/test_jenkins.sh, contrib/valgrind.supp, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/ib/ud/verbs/ud_verbs.h
=> Update cuda module version and add valgrind suppressions

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/ib/ud/verbs/ud_verbs.h
Refactor UD code to prepare it for UCS/CONN_MATCH
prepare for UCS/CONN_MATCH implementation
Just reverted revert of #5430 + some additional fixes
=> UCT/IB/UD: Refactor UD code to prepare it for UCS/CONN_MATCH

src/ucs/async/async.c
Improve logging for async handler error flow when adding new async handler
To debug issues that appeared in AZP GPU nodes
Print the name of the event handler that was found in hash
=> UCS/ASYNC: Improve logging for async handler error flow

buildlib/tests.yml, contrib/test_jenkins.sh, contrib/valgrind.supp, src/uct/ib/ud/base/ud_ep.c
Picked from master: #5497, #5499, #5481
=> Update cuda module version and add valgrind suppressions - v1.9.x

src/uct/ib/rc/accel/rc_mlx5_common.c
Make sure that if INLRESP=0 then sq_sig_all is set to 0 even if
create_flags are not supported - to disable scatter2cqe.
Fixes #5505
=> UCT/RC/MLX5: Fix scatter2cqe for older rdma-core

src/uct/ib/rc/base/rc_ep.h
=> RC/EP: use uct_rc_txqp_available instead of direct value access

src/ucp/core/ucp_am.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/rndv.c, src/ucs/async/async.c, src/ucs/sys/sock.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/tcp/tcp_ep.c
=> UCS/UCT/UCP: Compilation bugfix for 1.9.x

AUTHORS
This is a port of the list from 1.8.0 plus recent contributors from the
master.
=> AUTH: Updating author list

src/ucs/datastruct/string_set.c, src/uct/tcp/tcp_sockcm_ep.c
Remove unused  goto labels 
otherwise compilation fails with icc
=> UCS/UCT: Remove unused labels

AUTHORS
This is a port of the list from master
=> AUTH: Updating author list v1.9.0

test/apps/iodemo/io_demo.cc
Add multi-connection support for io demo. 
We need the multi-connection support testing coverage.
Support one client connect to multiple servers. Specify the addesses of servers in the command line of client side.
=> TEST/APPS/IO_DEMO: Add multi-connection support

docs/source/glossaries.rst, docs/source/index.rst
Document improvement. add glossaries
Many acronyms have been used in this project. I think new project members want to know these words' meanings.
I use a reStructured text format. Because It's sort friendly
Add glossaries page.
=> DOCS: Add glossaries

src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/uct/test_peer_failure.cc
- added implementation of ep_check for rc_mlx5 transport
- added gtest for ep_check functionality
replacement for https://github.com/openucx/ucx/pull/5523
=> UCT/RC-MLX5: added ep_check implementation

NEWS
News update
Getting ready for release
` git log --merges --date=relative v1.8.x..v1.9.x`
=> NEWS: Updates before v1.9.x

config/m4/rocm.m4
Fix ROCm build for ROCm 3.7 and above
=> CONFIG/M4: Update build libraries for ROCm-3.7+ releases

NEWS
=> NEWS: Date update before RC3

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml
* Added CUDA-11 builds (centos7, ubuntu18.04)
* Added specific MOFED version to the name of artifacts: `mofed5.0-1.0.0.0`
=> Topic/fix release azp v1.9 (2)

test/gtest/ucp/test_ucp_sockaddr.cc
add new tests
to improve test coverage
=> GTEST: add test_ucp_sockaddr_protocols.stream_short

src/ucp/core/ucp_am.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/proto/proto_am.inl, src/ucp/rndv/rndv.c, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_am.cc, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucp/ucp_datatype.cc, test/gtest/ucp/ucp_datatype.h
Implement zcopy protocol for `ucp_am_send_nbx`
=> UCP/AM: Zcopy protocol for ucp_am_send_nbx

NEWS
=> NEWS: 1.9.0 rc4 news update

test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag.h, test/gtest/ucp/test_ucp_tag_cancel.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_mem_type.cc, test/gtest/ucp/test_ucp_tag_mt.cc, test/gtest/ucp/test_ucp_tag_probe.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
- initial update for NBX tests
- updated tests test_ucp_tag to NBX API
- updated test infra to add user data
=> GTEST/NBX: re-implemented part of send/recv tests using NBX API

NEWS
=> NEWS: Updating news for RC5

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucs/config/parser.c, src/ucs/config/parser.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
- enabled keepalive feature in UCP
- added runtime configuration
- added gtest
- fixed wireup initialization
=> UCP/KEEPALIVE: enabled keepalive feature

src/ucp/tag/rndv.c
porting https://github.com/openucx/ucx/pull/5675
=> UCP/RNDV/CUDA: Fix host bw lane check for staging - v1.9.x

src/ucp/core/ucp_mm.c, src/uct/api/uct.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/base/uct_mem.c, src/uct/sm/mm/base/mm_md.c, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, test/gtest/uct/test_md.cc, test/gtest/uct/test_mem.cc, test/gtest/uct/test_mm.cc, test/gtest/uct/uct_test.cc
- Revive https://github.com/openucx/ucx/pull/5204
=> UCT/API: Rework of uct_mem_alloc/uct_md_mem_alloc to use mem_type

test/apps/iodemo/io_demo.cc
Add option specify differen port for each server
We want to make different port can be specified for each server on client side.
Specify the port number behind the server address.
=> TEST/APPS/IO_DEMO: Add option specify differen port for each server

NEWS
=> NEWS: Updating the date for the 1.9.0 release

config/m4/compiler.m4, src/tools/perf/lib/ucp_tests.cc, src/ucp/core/ucp_ep.c, src/ucp/proto/lane_type.h, src/ucp/rndv/rndv.c, src/ucp/wireup/ep_match.c, src/ucp/wireup/ep_match.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucs/memory/memory_type.h, src/ucs/stats/stats.h, src/ucs/sys/sys.c, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/accel/rc_mlx5_devx.c, test/gtest/ucp/test_ucp_worker.cc, test/gtest/uct/ib/test_ib_event.cc
- fixed set of mixes int<->enum data types
=> BUILD/PGCC: set of fixes to build by pgcc compiler

contrib/test_jenkins.sh
=> JENKINS: Run cuda ucx_perftest only in client/server mode

src/uct/base/uct_mem.c
`alloc_length` and `address` variables in uct_mem_alloc may not retain user requested values after one or methods are attempted. This patch re-initializes the variables to the original user requested values.
=> UCT/BASE: uct_mem_alloc reinit addr/length before using any method

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/time/time.h, src/uct/sm/base/sm_ep.c, src/uct/sm/base/sm_ep.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_ep.h, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/scopy/base/scopy_ep.h, src/uct/sm/scopy/base/scopy_iface.h, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
- added implementation of ep_check for memory mapper
based transports: posix & sysv
- updated tests
=> MM/EP-CHECK: added ep_check for memory mapper tls

src/ucp/Makefile.am, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_types.h, src/ucp/dt/datatype_iter.inl, src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.h, src/ucp/proto/proto_multi.inl, src/ucp/proto/proto_select.inl, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_send.c, test/gtest/common/test_obj_size.cc, test/gtest/ucp/test_ucp_dt.cc, test/gtest/ucp/test_ucp_tag_match.cc
Add the most basic eager protocol which can support all sizes and types
=> UCP/PROTO/TEST: Add eager/bcopy/multi protocol progress implementation

test/gtest/ucp/test_ucp_stream.cc
- tests are shifted to Stream NBX API
=> GTEST/STREAM: re-implemented tests using NBX API

src/uct/ib/rdmacm/rdmacm_cm.c
Pack dest-gid from qp_attr instead of CM id if qp_attr.ah_attr.is_global
=> UCT/RDMACM: Pack dest-gid from qp_attr instead of CM id

src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
First part of #5709 
#5709  affects too many core places
=> UCP/EP: discard lanes on failure with UCP EP reconf

src/uct/ugni/configure.m4
Removing "guess" mode that does not do anything. Fixes #5731.
=> UGNI: Fixing broken disable logic in config

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c
- removed uct_rc_fc_t.flags value
- added flags value to uct_rc_ep_t
=> RC/FC: removed uct_rc_fc_t.flags value

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
- datatype uct_rc_fc_request_t renamed to uct_rc_pending_req_t
to be used in more general cases
=> RC/FC: added base datatype

src/ucs/async/async.c, src/ucs/async/async_int.h, src/uct/tcp/tcp_cm.c, test/gtest/common/test.cc
- fixed compilation by HPC SDK version 20.9
=> BUILD/NVC: set of fixes for new HPC SDK

debian/control.in
Signed-off-by: Artem Ryabov <artemry@mellanox.com>
Changes:
* Removed deb package dependencies in scope of https://github.com/openucx/ucx/issues/5596
https://github.com/openucx/ucx/issues/5596
=> DEBIAN: Removed deb package dependencies

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucs/datastruct/list.h
- added processing of NO_RESOURCES error: it will retry to send
keepalive message in case if no resources available
=> UCP/KEEPALIVE: added error processing

NEWS
NEWS: Backport of news from 1.9.x
=> NEWS: Backport of news from 1.9.x

src/ucp/wireup/select.c, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_copy/cuda_copy_ep.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.h, src/uct/ib/ud/base/ud_iface.c
Add wakeup feature for cuda_copy UCT
=> UCT/CUDA/CUDA_COPY: add cuda_copy wakeup feature

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h
- to provide DCI specific failure handling added ops
to DCI structore
- added callback to rx_purge_outstanding function to allow
custom purge algorithms
=> DC/RC: added callbacks into handling failures

src/ucp/core/ucp_am.c
Add profiling for UCP AM handlers
=> UCP/AM: Add profiling for AM handlers

src/ucp/core/ucp_rkey.c, src/ucp/wireup/select.c, test/gtest/ucp/test_ucp_mmap.cc
Fix performance issue of fallback to SW emulation put, even though posix/sysv can access to remote allocated memory
@shamisp
=> UCP/RMA/TEST: Fix un-needed fallback to SW protocol with shared memory

src/ucp/wireup/wireup_cm.c
1. Fixed memory leak of connection request in case TL bitmap is empty.
2. Don't print invalid server EP.
```
[UCX-connection #1 0.0.0.0:0] created new connection, total: 1
[1603461453.146678] [<host>:84410:0]         select.c:449  UCX  ERROR no active messages transport to <no debug data>: rc_verbs/mlx5_0:1 - Destination is unreachable, rc_mlx5/mlx5_0:1 - Destination is unreachable, dc_mlx5/mlx5_0:1 - Destination is unreachable, ud_verbs/mlx5_0:1 - Destination is unreachable, ud_mlx5/mlx5_0:1 - Destination is unreachable
[1603461453.146710] [<host>:84410:0]      wireup_cm.c:1034 UCX  WARN  server ep (nil) failed to connect to worker address on device mlx5_0:1, tl_bitmap 0x1f00, status Destination is unreachable
[UCX] ucp_ep_create() failed: Destination is unreachable[UCX-connection #1 …
```
=> UCP/WIREUP: Several fixes in CM server create

docs/source/glossaries.rst
Document improvement. update glossaries
Same as #5538
Update glossaries.
=> DOCS: Update glossaries

buildlib/az-io_demo.sh, test/apps/iodemo/Makefile.am, test/apps/iodemo/README.md, test/apps/iodemo/io_demo.cc, test/apps/iodemo/run_io_demo.sh, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h, ucx.spec.in
Port new IODEMO features and bugfixes from the internal branch
Keep master branch up to date w. r. t. IODEMO app
=> TEST/IODEMO: Port features/bugfixes from int3 branch

src/ucs/stats/serialization.c
This update applies statistics filtering to the UDP report.
Statistics filtering is already available on UCX but not applied to the UDP server report (only to stdout report).
By applying it using the current UCX statistics SW architecture.
=> STAT: Apply UCX statistics filtering to UDP report

src/ucp/api/ucp.h
Fix description of `ucp_am_recv_data_nbx`
=> UCP/AM/DOC: Fix doc for ucp_am_recv_data_nbx

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/uct/test_peer_failure.cc
- added ep_check implementation for DCX transport
- updated error handling
=> DC/MLX5: added keepalive feature

src/ucp/core/ucp_am.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, test/gtest/ucp/test_ucp_am.cc
Support for `UCP_AM_SEND_FLAG_EAGER` and  `UCP_AM_SEND_FLAG_RNDV` in `ucp_am_send_nbx`
=> UCP/AM: Support for eager/rndv send flags

src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/copy/rocm_copy_md.c, src/uct/rocm/gdr/rocm_gdr_md.c, src/uct/rocm/ipc/rocm_ipc_md.c, test/gtest/common/test.cc, test/gtest/uct/test_md.cc, test/gtest/uct/test_md.h
- added stub mem_query call
- updated tests
=> GTEST/ROCM: fixed ROCM tests

buildlib/io-demo.yml, test/apps/iodemo/io_demo.cc, test/apps/iodemo/run_io_demo.sh, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Add option to use AM API instead of TAG in IODEMO
=> TEST/IODEMO: Add initial AM support

src/uct/base/uct_iface.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/ib/test_rc.cc
- enabled keepalive feature for rc-verbs transport
=> RC/VERBS/KEEPALIVE: enabled keepalive feature

src/ucp/rma/flush.c
cherry-picked from https://github.com/yosefe/ucx/pull/91
=> UCP/EP/FLUSH: fix error handling flow

test/gtest/ucp/test_ucp_mmap.cc
Fix mmap tests for 0-length RMA
Fixes #5840 (#5918)
1. Fix code style violations
2. Expect SW proto for TLs with non-RMA offload (all TLs except RC/DC, SHM, SELF) and for TLs with RMA offload, but zero-length (or NULL) buffer
=> GTEST/UCP: Fix mmap tests for 0-length RMA

buildlib/az-helpers.sh, buildlib/io-demo.yml, buildlib/tests.yml, test/apps/iodemo/run_io_demo.sh
move io_demo run to instinct
roce server is slow
change server
=> AZP: change roce server for io_demo to instinct

src/ucp/core/ucp_context.c, src/ucp/core/ucp_worker.c, src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/time/time.h, test/gtest/ucs/test_config.cc
- added "inf" and "auto" values
=> UCS/TIME-UNITS: added "inf" and "auto" values

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.h
add listen retry for iodemo-server
cherry-picked from https://github.com/yosefe/ucx/pull/94
=> IODEMO: add listen retry for server

src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
- added support of keepalive feature for TCP transport
=> TCP/KEEPALIVE: enabled ep_check feature for TCP

contrib/test_jenkins.sh
need stop CI it port in init state
=> Jenkins: Add function for check state on device

bindings/java/src/main/native/Makefile.am
Trigger JAR rebuild if example source is changed
=> BUILD/JAVA: Fix build dependencies

buildlib/tests.yml, contrib/test_jenkins.sh
Added warning message for azure pipeline
=> AZP: add warning for azure

src/ucp/core/ucp_listener.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Fix IODEMO server exit and destructors flow
=> Fixes for iodemo and listener destroy flow

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup_cm.c
- removed incorrect assert on keepalive remove ep
=> UCP/KEEPALIVE: removed incorrect assert

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/base/cuda_iface.c, src/uct/cuda/base/cuda_iface.h, src/uct/cuda/base/cuda_md.c, src/uct/rocm/base/rocm_base.c, src/uct/sm/base/sm_iface.c, src/uct/sm/self/self.c
Adjust iface latency scores using topo distance in UCP/WIREUP to generalize https://github.com/openucx/ucx/pull/5434
=> UCP/WIREUP: use ucs topo to compare with mem_type md and adjust latency

contrib/test_jenkins.sh, examples/ucp_hello_world.c
- added sender/receiver/keepalive error simulations to
ucp_hello_world application
=> UCP/HELLO-WORLD: added error simulations

src/uct/ib/rc/accel/rc_mlx5_devx.c
=> UCT/IB/DEVX: Set modify-QP global address parameters only for GRH case - v1.10.x

buildlib/io_demo/az-stage-io-demo.yaml, buildlib/io_demo/io-demo.yml
iodemo test can run on different PR
=> IODEMO: Run in uniq folder

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Implemented uct_ep_am_short_iov in TCP.
=> UCT/TCP: Implemented AM short IOV in TCP.

src/ucm/bistro/bistro_x86_64.c, src/ucm/cuda/cudamem.c, src/ucm/event/event.c, src/ucm/mmap/install.c, src/ucm/rocm/rocmmem.c, src/ucm/util/reloc.c
=> UCM/BISTRO: Improve x86 parser to recognize some mov flavors

src/ucp/tag/offload.c, test/gtest/ucp/test_ucp_tag_offload.cc
=> UCP/TAG: Fix offload completion with inlined data

src/tools/info/tl_info.c, src/tools/perf/lib/libperf.c, src/ucp/wireup/select.c
- added missing log entries for keepalive flags
=> WIREUP/LOG: improved keepalive logging

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml
=> AZP: Fix release pipeline

src/ucp/tag/offload.c, test/gtest/ucp/test_ucp_tag_offload.cc
=> UCP/TAG: Fix offload completion with inlined data - v.1.10.x

buildlib/io_demo/az-stage-io-demo.yaml, buildlib/io_demo/io-demo.yml
python: can't open file 'buildlib/io_demo/iodemo_analyzer.py': [Errno 2] No such file or directory
Analyzer can use from other PR
Analyzer will put to artifact
=> AZP/IODEMO: Add analyzer to artifact

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml
=> AZP: fix docker image

src/ucp/api/ucp.h
- fixed descriptions of receive buffer
=> UCP/DOC: fixed copy-paste issue in doc

src/ucp/wireup/select.c
Fix the typo in the comment
Code documentation w/o mistakes
`reuested` -> `requested`
=> UCP/WIREUP: Fix the comment

src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup.c
cleanup leftovers from removed UCT/iface approach
code quality
https://github.com/openucx/ucx/pull/6127#issuecomment-760961620
=> UCP/WIREUP/SOCKADDR: cleanup leftovers

src/ucp/core/ucp_worker.c
- moved keepalive progress callback into FAST queue
- refactored callback function
=> UCP/KEEPALIVE: performance optimization

contrib/valgrind.supp, src/uct/ib/base/ib_device.c, src/uct/ib/configure.m4, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h
porting https://github.com/openucx/ucx/pull/5965 to v1.9.x
=> UCS/UCT/IB: Ignore PFs without RDMA cap on BF2 according to its gid_t…  - v1.9.x

debian/control.in
Add system dependencies for UCX deb package.
Fixes #6170
=> DEB/PKG: add essential system dependencies.

src/tools/vfs/vfs_main.c, src/ucs/vfs/fuse/vfs_fuse.c
Make coverity pass on machines with fuse3-devel
@avildema
=> VFS/FUSE: Fix coverity errors

src/ucp/proto/proto_select.c
Allow searching for a protocol from protocol initialization function, will be used by rendezvous protocol to guess the protocol the remote side would select, for its performance estimation.
=> UCP/PROTO/SELECT: Fix recursive protocol selection

buildlib/azure-pipelines-pr.yml
=> AZP: add tests for sputnik

src/uct/base/uct_iface.c, src/uct/base/uct_iov.inl, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/ud/accel/ud_mlx5.c
Implemented uct_ep_am_short_iov in UD mlx.
=> UCT/IB/UD: Implemented AM short IOV in UD mlx.

src/uct/sm/self/self.c
Implemented uct_ep_am_short_iov for self transport.
=> UCT/SM/SELF: Implemented AM short IOV for self transport.

src/ucs/vfs/fuse/vfs_fuse.c
Stop FUSE thread if no inotify_fd was created
To fix hang of `ucp_client_server -h` (and other)
Check `stop` flag
=> UCS/VFS: Stop FUSE thread if no inotify_fd was created

src/ucp/Makefile.am, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_worker.c, src/ucp/proto/proto.h, src/ucp/proto/proto_single.h, src/ucp/proto/proto_single.inl, src/ucp/tag/eager.h, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload/eager.c, src/ucp/tag/tag_rndv.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_offload.cc
Implement support for tag offload eager with new protocols
=> UCP/PROTO/TAG: New protocols eager offload support

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpAmData.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpAmRecvCallback.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConstants.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/main/native/ucp_constants.cc, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Active Messages API support in JUCX
UcpAmData  class wrapper that incapsulates logic for eager and rndv active message data.
=> JUCX: Active Messages API.

src/uct/ib/rc/accel/rc_mlx5_ep.c
Replaced declaration of variables by macro.
=> UCT/IB/RC: Replaced declaration of variables by macro.

src/uct/ib/rdmacm/rdmacm_cm_ep.c
Prevent segfault in uct_rdmacm_cm_ep_str when id is not initialized
CM ID isn't initialized
Backport of #6076 to v1.10.x
=> UCT: Prevent segfault in uct_rdmacm_cm_ep_str when id is not initialized [v1.10.x]

src/ucp/wireup/wireup.c
Unite WIREUP MSG checks for all MSG types.
Reduce duplication and add missing checks.
1. Introduce `UCP_WIREUP_MSG_CHECK` macro with all needed checks.
2. Use the new macro in PRE_REQ/REQ/REPLY/ACK handlers.
=> UCP/WIREUP: Unite WIREUP MSG checks

buildlib/io-demo.yml
=> AZP/IODEMO: fix get PID in corrupter - v1.10.x

buildlib/io_demo/az-stage-io-demo.yaml
=> AZP/IODEMO: fix get PID in corrupter

config/m4/compiler.m4, src/tools/vfs/vfs_server.c, test/gtest/ucs/test_pgtable.cc
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1922680
Error details: https://kojipkgs.fedoraproject.org//work/tasks/251/61050251/build.log
Test compile&link flag, instead of testing only compiler flag
=> CONFIG/VFS/TEST: Fix compilation on gcc11

debian/control.in
=> DEB/PKG: add essential system dependencies. v1.10

buildlib/az-helpers.sh, buildlib/azure-pipelines-pr.yml, buildlib/coverity.yml, buildlib/tools/common.sh, buildlib/tools/coverity.sh
=> AZP: add coverity

src/ucp/core/ucp_worker.c, test/gtest/ucp/test_ucp_sockaddr.cc
Fix invalid printing if failed lane is CM lane.
`tl_rsc` is invalid in case of CM lane, so don't touch it.
```
[ RUN      ] ud/test_ucp_sockaddr.err_handle_without_err_cb/0 <ud_v/tag>
=================================================================
==14988==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c0002d8944 at pc 0x7f9207f1e64d bp 0x7f91ff67d820 sp 0x7f91ff67cfd0
READ of size 1 at 0x60c0002d8944 thread T40
#0 0x7f9207f1e64c in printf_common ../../../../source/gcc-10.1.0/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:547
#1 0x7f9207f1ff45 in __interceptor_vsnprintf ../../../../source/gcc-10.1.0/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1647
#2 0x60f725 in ucs::test_base::format_message[abi:cxx11](char const*, …
```
=> UCP/CORE: Fix invalid printing if failed lane is CM lane

src/ucp/core/ucp_ep.c
Fix io_demo hangs due to infinite log messages which look like the below. Issue introduced in #6286 
```
2021-02-07T19:59:04.1927087Z sputnik2: [1612727944.191767] [sputnik2:3955 :0]          ucp_ep.c:2402 UCX  WARN  unexpected return status from uct_ep_check(ep=0x7fa835955000): Unsupported operation
2021-02-07T19:59:04.1931829Z sputnik2: [1612727944.191852] [sputnik2:3955 :0]          ucp_ep.c:2402 UCX  WARN  unexpected return status from uct_ep_check(ep=0x7fa835955000): Unsupported operation
2021-02-07T19:59:04.1933453Z sputnik2: [1612727944.191857] [sputnik2:3955 :0]          ucp_ep.c:2402 UCX  WARN  unexpected return status from uct_ep_check(ep=0x7fa835955000): Unsupported operation
2021-02-07T19:59:04.1935043Z sputnik2: [1612727944.191861] [sputnik2:3955 :0]          ucp_ep.c:2402 …
```
=> UCP/KEEPALIVE: Refresh lane map in case of configuration change

src/ucp/wireup/wireup.c
Fix sending AM Bcopy for `length=1` or `length=257` (as it fails the test), since `((ucs_status_t)257) == 1`
`UCS_INPROGRESS` is declared as `1`, so sending when sending `1` or `257` or etc bytes for WIREUP MSG breaks `UCP_AM_BCOPY_HANDLE_STATUS` macro.
Reproduced in #6245
```
2021-02-05T17:58:56.2889124Z [ RUN      ] all/test_ucp_sockaddr_different_tl_rsc.unset_devices_and_communicate/0 <all/unset_self_devices>
2021-02-05T17:58:56.2989503Z [     INFO ] Testing 127.0.0.1:0
2021-02-05T17:58:56.2990555Z [     INFO ] server listening on 127.0.0.1:35213
2021-02-05T17:58:56.3013421Z [swx-rdmz-ucx-althca:19250:0:19250]      wireup.c:128  Assertion `((ucs_status_t)packed_len) != UCS_INPROGRESS' failed
2021-02-05T17:58:56.8706063Z 
2021-02-05T17:58:56.8708415Z …
```
=> UCP/WIREUP: Fix sending AM Bcopy for (length % 256) == 1

buildlib/coverity.yml, buildlib/tools/coverity.sh
fix artefact directory for coverity
=> AZP: Fix upload folder for coverity

src/ucp/rma/rma_basic.c
porting https://github.com/openucx/ucx/pull/6284
=> UCP/RMA: Fix length check condition in RMA PUT short - v1.10.x

buildlib/azure-pipelines-pr.yml, buildlib/coverity.yml, buildlib/io_demo/io-demo.yml, buildlib/jucx-publish.yml, buildlib/tests.yml
add fetchDepth: 100 to checkout section fo CI
it should be increased git clone
=> AZP: add fetchDepth 100 for checkout

src/ucp/Makefile.am, src/ucp/core/ucp_context.c, src/ucp/core/ucp_types.h, src/ucp/proto/proto.h, src/ucp/proto/proto_select.c, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/rndv_get.c, src/ucp/tag/tag_rndv.c
The first phase of new rendezvous protocols - initialize protocol configuration and performance estimation
=> UCP/PROTO: New protocols rendezvous - selection and performance model

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, test/gtest/ucp/test_ucp_peer_failure.cc
- for connect-to-iface EPs use AM based keepalive
- new way is implemented using ping-pong pattern
=> UCP/KEEPALIVE: add AM-based keepalive

buildlib/azure-pipelines-pr.yml, buildlib/coverity.yml
=> AZP: Fix 2 publish artefacts

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_ep.c
Re-factored RC/DC AM short IOV implementation for device memory.
According to [review comment](https://github.com/openucx/ucx/pull/6279#pullrequestreview-585460141) to reduce code duplication.
Combined RC/DC AM short IOV implementation for device memory to single function.
Introduced `uct_mlx5_txqp_bcopy_post` to move common code from RC and DC specific functions.
=> UCT/IB: Re-factored RC/DC AM short IOV implementation for device memory.

.gitignore
- added new entries into gitignore file
=> GIT: update gitignore

contrib/test_jenkins.sh
- module versions "latest" were replaced by strict module version
to prevent un-controlled tools updates
=> BUILD/JENKINS: fixed tools versions

buildlib/azure-pipelines-pr.yml, buildlib/centos7-release.Dockerfile, buildlib/centos7.Dockerfile, src/uct/ib/base/ib_md.c, src/uct/ib/rdmacm/rdmacm_cm.c
Test ucx_info from container w/o rdma devices.
To justify #6210
=> AZP: Test ucx_info from container w/o rdma devices.

src/ucp/tag/offload.c
Fix failure handling in RNDV offload send.
Fixes https://github.com/openucx/ucx/pull/5821#discussion_r574259481
If `uct_ep_tag_rndv_request()`/`uct_ep_tag_rndv_zcopy()` fail, `ucp_tag_offload_sw_rndv()`/`ucp_tag_offload_rndv_zcopy()` don't handle it.
So, `ucp_request_try_send()` will fail with `ucs_fatal()` error.
Handle `((status != UCS_ERR_NO_RESOURCE) && (status != UCS_OK))` by returning `UCS_OK` and calling `ucp_rndv_rts_handle_status_from_pending()` to deallocate UCP request and release UCP request ID.
=> UCP/TAG: Fix failure handling in RNDV offload send

src/uct/ib/rc/accel/rc_mlx5.inl
Re-factored RC/DC am short implementation for device memory.
According to [review comment](https://github.com/openucx/ucx/pull/6200#discussion_r570582887) to reduce code duplication.
Replaced implementation of uct_rc_mlx5_iface_common_copy_to_dm by uct_rc_mlx5_iface_copy_iov_to_dm. Because ...copy_to_dm is a special case of ...copy_iov_to_dm.
=> UCT/IB/RC: Combine methods which copy iov and contig buffer to DM to single one.

AUTHORS
Updating the list of authors
`git log --pretty=format:"%an%x09%ae" | sort | uniq`
=> AUTHORS: Updating the list of authors - v1.10.0

NEWS
=> NEWS: Update before RC3 - v1.10.0

src/ucp/core/ucp_am.c, src/ucp/proto/proto_am.inl
Pack user header to the end of UCP Active message.
Now AM will be constructed like `| AM HDR | PAYLOAD | USER HDR|`, instead of  `| AM HDR | USER HDR | PAYLOAD |`
1. It is needed for adding AM alignment option, which would guarantee specific alignment of AM payload on the receiver
2. To allow user calling `ucp_am_recv_data_nbx` for eager messages inside AM data callback. To support this, UCX has to initialize rdesc before passing the data to the AM data callback, which (with current alignment) would overwrite user header.
=> UCP/AM: Pack user hdr to the end of message

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml
=> AZP: add new OS for release CI

src/ucs/sys/string.c, src/ucs/sys/string.h, src/ucs/sys/topo.c, test/gtest/ucs/test_string.cc
Backport of https://github.com/openucx/ucx/pull/6174
=> UCS/TOPO: Use common prefix and char count for path distance estimation - v1.10.x

src/uct/rocm/base/rocm_base.c, src/uct/rocm/base/rocm_base.h, src/uct/rocm/ipc/rocm_ipc_iface.c
Detect link type (PCIe/xGMI) and declare appropriate bandwidth
Note: assumes all GPUs are connected through same type of link
Fix https://github.com/openucx/ucx/issues/4855
=> UCT/ROCM/IPC: detect link type and declare correct BW for rocm_ipc

src/tools/perf/lib/libperf.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.h
=> UCT/CUDA_IPC: make cuda-ipc cache global - v1.10.x

src/uct/cuda/base/cuda_iface.h, src/uct/cuda/cuda_copy/cuda_copy_md.c, test/gtest/common/main.cc, test/gtest/common/mem_buffer.cc, test/gtest/common/mem_buffer.h, test/gtest/uct/test_md.cc, test/gtest/uct/test_mem.cc
=> UCT/CUDA: Add alloc methods for cuda pinned/managed memory

README
=> README: Add notice about known issues

src/ucp/Makefile.am, src/ucp/proto/proto_common.inl, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv_get.c, src/ucp/tag/tag_rndv.c, test/gtest/ucp/test_ucp_tag_match.cc
Support rendezvous protocol progress with new protocols framework
- Implement RNDV progress functions 
- Add handlers for RTS/ATS
- Enable protocols in rndv tests
=> UCP/PROTO/TEST: Implement rndv/get/zcopy with new protocols

src/ucp/core/ucp_ep.c
Check that UCP EP is being destroyed, when destroying real UCT lanes.
For better debugging and prevent some unexpected behavior during further development.
1. Re-implement `ucp_ep_cleanup_lanes()` function to do only one loop and not duplicate checks.
2. Don't purge and destroy `ucp_failed_tl_ep` UCT EP to fix some Coverity issues if not to do it.
3. Add assertion that we expect that UCP EP's ref_cnt is `1` when destroying real UCT EP.
=> UCP/CORE: Check that UCP EP is being destroyed, when destroying real UCT lanes

.clang-format, contrib/test_jenkins.sh, test/apps/iodemo/Makefile.am, test/apps/iodemo/io_demo.cc
Support CUDA and CUDA managed in io_demo.
Improve test coverage.
Introduce `CustomMemoryPool` in `io_demo`, which supports allocating buffers using the requested memory type. Add conditionally compiled code (`HAVE_CUDA`) flag which handles CUDA buffers. Add testing parameterization in `test_jenkins.sh` which runs with CUDA if supported on the platform.
=> TEST/APPS: Support CUDA & CUDA managed in io_demo

src/ucp/core/ucp_ep.c
Set all lanes to failed ones when discarding lanes.
It happens that there is NULL lane for TMP EP (CM lane), and we don't set it in `ucp_ep_cleanup_lanes()` to `&ucp_failed_tl_ep` which is expected to be in `ucp_ep_discard_lanes()`
```
[2021-02-21T22:08:01.566Z] [ RUN      ] rc/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/0 <rc_v/tag>
[2021-02-21T22:08:01.566Z] [     INFO ] Testing fe80::7efe:90ff:fe72:6fef:0
[2021-02-21T22:08:01.566Z] [     INFO ] server listening on fe80::7efe:90ff:fe72:6fef:36192
[2021-02-21T22:08:02.147Z] [r-vmb-ppc-jenkins:16222:0:16222]      ucp_ep.c:798  Assertion `(uct_ep == &ucp_failed_tl_ep) || (ep->ref_cnt == 1)' failed
[2021-02-21T22:08:02.736Z] 
[2021-02-21T22:08:02.736Z] /scrap/jenkins/workspace/ucx-3/contrib/../src/ucp/core/ucp_ep.c: [ …
```
=> UCP/CORE: Set all lanes to failed ones when discarding lanes

src/uct/cuda/cuda_copy/cuda_copy_md.c
Dummy registration for pinned/managed memory in cuda_copy.
Even though cuMemcpy operations don't need the registration, for cuda_copy put/get operations over pinned/managed memory we need to call uct_md_mem_reg in UCP flows. This PR populates memory handle with dummy value for pinned/managed memory.
=> UCT/CUDA_COPY: Dummy registration of pinned/managed memory

buildlib/azure-pipelines-pr.yml
instinct server will be deprecated
=> AZP: change ucx_instinct label to ucx_docker

src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/lib/uct_tests.cc, src/tools/perf/perftest.c, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_perf.cc
Add UCP AM support to ucx_perftest
evaluate UCP AM performance
=> TOOLS/PERF: Add UCP AM support to perftest

NEWS
=> NEWS: News update for v1.10.0 rc5

src/uct/ib/base/ib_log.c
Fixes #6424
Issue introduced by #6411
=> UCT/IB/LOG: Fix compilation with experimental verbs

test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
gtest code clean up
delete code duplications and leftovers
=> GTEST: code clean up

buildlib/azure-pipelines-pr.yml, src/uct/ib/dc/dc_mlx5.c
=> AZP: add RHEL 7.6 with mofed 4.7

src/uct/base/uct_iface.c
Fixed fedora 34 build issue.
Failure:
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=14181&view=logs&j=388a871c-1c79-55fb-9b87-030460a06453&t=5e35f88b-fb7b-53de-08b1-5a98a76597a1
#6438 
Compiler assumed an issue in case of `uct_iov_total_length(iov, iovcnt)` equal to zero.
=> UCT/BASE: Fixed possible uninitialized memory issue.

NEWS
=> NEWS: remove jucx from packages. [v.1.10]

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, buildlib/jucx-publish.yml
=> AZP/RELEASE: Add dockers with cuda11.2 for v1.10

test/apps/iodemo/io_demo.cc
=> IODEMO: fixed typo in usage wording

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, test/gtest/ucp/test_ucp_tag.cc
Fix DCI LAG port bugs:
* in EP create - check path_index against max_num_pools
* in test - create DCI with DEVX
=> UCT/DC: DCI pool per LAG port - 4

src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/mlx5/exp/ib_exp_md.c
=> UCT/IB: Ignore devices with invalid GID

NEWS, buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, buildlib/jucx-publish.yml
Fix build trigger for pushed tags
=> NEWS/BUILD: Update Build.Reason trigger and release date -v1.10.x

src/ucp/core/ucp_ep.c
Set `EP_FAILED` in cleanup_lanes + don't allocate local req ID for memtype EP
Local request ID is not needed for memory type EP.
`EP_FAILED` has to be set to keep EP reference counter updated and to pass assertion in EP destroy.
Don't set local req ID for EP if MEMTYPE flag was specified.
Set EP_FAILED flag for `cleanup_lanes()` as we do for `discard_lanes()`.
=> UCP/CORE: Set EP_FAILED in cleanup_lanes + don't allocate local req ID for memtype EP

buildlib/tools/builds.sh
rename log_error to azure_log_error for build script
=> AZP: rename log_error to azure_log_error for build script

test/apps/iodemo/io_demo.cc
- fixed assert: io_demo.cc:1140: size_t DemoClient::get_server_index(const UcxConnection*):
Assertion `_server_index_lookup.size() == _active_servers.size()' failed
=> TEST/IODEMO: fixed assert

buildlib/azure-pipelines-pr.yml, buildlib/tools/builds.sh
add fedora 34 container for build testing
=> AZP: add fedora 34

src/ucp/tag/tag_send.c
Fix updating statistics in TAG send code.
Don't need to update Eager statistics if RNDV protocol send is used.
Change sequence of checking return value from `ucp_request_send_start()`:
1. Check for `ucs_likely(status == UCS_OK)` - means Eager was selected and initialization was successful. Eager statistics are updated here.
2. Check for `status == UCS_NO_PROGRESS` - means callback from Eager to RNDV. RNDV statistics are updated here in case of success.
3. Otherwise - some failure happens.
=> UCP/TAG: Fix updating Eager statistics for RNDV operation

src/ucs/vfs/fuse/vfs_fuse.c
Updated FUSE callbacks: get attributes, open a file, read data from an open file, read directory. Added FUSE callback to release an open file.
The callbacks are required to implement virtual filesystem which will be used for debugging and analysis of UCX-based applications.
UCS/VFS object manipulation interfaces were used to update FUSE callbacks #6456 .
=> UCS/VFS: Updated FUSE callbacks using interfaces to manipulate VFS objects.

buildlib/azure-pipelines-pr.yml, buildlib/coverity.yml, buildlib/tools/builds.sh, buildlib/tools/common.sh, buildlib/tools/coverity.sh
after cancel job next job cannot remove workspace
=> AZP: remove ws

src/ucs/vfs/base/vfs_obj.c
Fixed formatting of VFS node relative path.
=> UCS/VFS: Fixed formatting of VFS node relative path.

src/ucp/api/ucp.h, src/ucp/core/ucp_listener.c, src/uct/ib/rdmacm/rdmacm_listener.c, test/gtest/ucp/test_ucp_sockaddr.cc
update doc and fix param check
fixes https://github.com/openucx/ucx/issues/6257, see conversation https://github.com/openucx/ucx/issues/6257#issuecomment-771981284
=> UCP/LISTENER: ucp_listener_create

src/tools/perf/lib/libperf.c, src/uct/base/uct_mem.c
=> UCS/MEM/LIBPERF: fixed typos in comments

NEWS
=> NEWS: Backport news updates from v1.10.x

src/ucp/rndv/rndv.c
Don't expect that MD map set in GET Zcopy completion in case state ff.
If RNDV GET Zcopy was started, but due to no resource, progress callback wasn't called at all, `md_map` can be `0`.
So, the assertion that expects that `md_map == 0` fails in fast-forward of send request state after error.
Check that we are doing fast-forward by checking the completion status and the EP's FAILED flag presense.
=> UCP/RNDV: Don't expect that MD map set in GET Zcopy completion in case state ff

src/ucp/core/ucp_worker.c
Replaced if/else block by macro extracting params values.
=> UCP/CORE: Replaced if/else by macro.

bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
1. Iterate over network interfaces in reverse order to first try to bind listener on RDMA capable network interface.
2. For all endpoints use peerErrorHandling mode
3. Progress stream send/recv on correct workers
To fix JUCX tests hangs like here: https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/15292/logs/219
*It does not fix the fundamental problem (when using non-RDMA NIC sometimes connection handler comes with wrong sockaddr), but at least will not break tests. On RDMA capable NICs didn't reproduce
=> JUCX: fix some hangs in UcpListenerTest.

src/uct/ib/base/ib_iface.c
IB device bandwidth was miscalculated on HDR100 port, which is 2x50Gbs, which led to selecting invalid lanes for intra-node communication: both shared memory and IB were selected, even though only shared memory should be selected.
- Fix active_width parsing per IBTA specification: a value of 16 means 2x
- Add fallback for unrecognized port width, to use 1x
=> UCT/IB: Fix port width check on HDR100

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, buildlib/jucx/jucx-publish.yml
Fix a problem with launch dockers for JUCX stage, for example https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=14454&view=logs&j=e29bbc24-f342-5915-29b0-97abf7400e12&t=dfce8edc-31a3-4b85-ae66-f22d64bb9d09
Refactoring conditions for release pipeline
=> AZP/RELEASE: Update release ci for jucx stage

config/m4/compiler.m4, src/ucs/configure.m4
- added ability to set custom log level. useful for performance
investigation tasks
- fixed few typos
=> BUILD/CONFIG: added custom max log level

src/ucp/rma/amo_sw.c, src/ucs/async/signal.c, src/ucs/stats/libstats.c, src/uct/base/uct_iface.c, test/gtest/ucp/test_ucp_dt.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
=> UCS/UCT/UCP/GTEST: Remove extra semi-colons

NEWS, src/uct/ib/base/ib_iface.c
=> UCT/IB: Fix port width check on HDR100 - v1.10.x

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, buildlib/jucx-publish.yml
JUCX try launch rdmx docker on azure cloud
=> AZP/RELEASE: launch jucx in lab

src/ucs/sys/event_set.h, src/uct/base/uct_cm.c, src/uct/base/uct_cm.h, src/uct/base/uct_iface.c, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/ib/rdmacm/rdmacm_cm_ep.h, src/uct/tcp/tcp_sockcm.c, src/uct/tcp/tcp_sockcm_ep.c, src/uct/tcp/tcp_sockcm_ep.h, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
implementation of extended connection establishment API introduced in https://github.com/openucx/ucx/pull/6378
=> UCT/API/SOCKADDR: implementation of extended connection establishment API

src/ucp/core/ucp_request.inl, src/ucp/rndv/rndv.c
=> UCP/REQUEST: fixed typos in comments

src/ucp/core/ucp_request.inl
- added status value print into assert
=> REQUEST/RECV-DATA-UNPACK: improved assert

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
Added directory to represent UCP ep in VFS.
The directory is created inside worker refresh callback.
The changes are required to analyze and debug UCX-based applications.
=> UCP/CORE: Added node to represent UCP ep in VFS.

configure.ac, docs/source/faq.md, src/tools/info/ucx_info.c, src/ucs/Makefile.am, src/ucs/config/ini.c, src/ucs/config/ini.h, src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/config/types.h, test/gtest/Makefile.am, test/gtest/ucs/test_config.cc, test/gtest/ucs/ucx.conf, ucx.spec.in
Support configuring UCX params using a configuration file in INI format
Improve configuration flexibility
=> UCS/CONFIG: Support configuration file

src/ucp/core/ucp_context.c, src/ucp/core/ucp_worker.c, src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h
Added worker name to worker's vfs node.
The changes are required to address this comment: https://github.com/openucx/ucx/pull/6582#discussion_r603597295
=> UCP/CORE: Added worker name to worker's vfs node.

buildlib/io_demo/az-stage-io-demo.yaml, buildlib/io_demo/io-demo.yml, buildlib/io_demo/iodemo_analyzer.py
Enable network interference script during io_demo run in CI
Test error flows with port up/down, client/server kill, etc
=> AZP: enable corrupter

src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c
switch to new UCT API
preparation to fix race condition due to calling `uct_ep_create` from async thread
=>  UCP/WIREUP/CM: switch to new UCT API

buildlib/az-helpers.sh, buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.yml
Snapshot pipeline skip now . condition for launch is null
Add conditional for launch in snapshot pipeline
=> AZP/SNAPSHOT: Fix snapshot Pipeline

src/ucp/core/ucp_worker.c
Fix expectations regarding error detection on AUX EP.
The error on AUX EP could be detected on a client as well and it could be not only due to closing AUX EP on another side, but due to real error (e.g. switch port down).
```
[jazz30:66130:0:66130]  ucp_worker.c:598  Assertion `ucp_ep->flags & UCP_EP_FLAG_CONNECT_PRE_REQ_QUEUED' failed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210408_061224_166977_2730_jazz17.swx.labs.mlnx/installs/dwgc/tests/io_demo/ucx.git/src/ucp/core/ucp_worker.c: [ ucp_worker_iface_handle_uct_ep_failure() ]
...
595         (lane == ucp_ep_get_wireup_msg_lane(ucp_ep)) &&
596         (wireup_ep != NULL)                          &&
597         ucp_wireup_aux_ep_is_owner(wireup_ep, uct_ep)) {
==>   598         ucs_assert(ucp_ep->flags & …
```
=> UCP/CORE: Fix expectations regarding error detection on AUX EP

src/uct/base/uct_worker.c
Added directory to VFS to represent UCT worker.
=> UCT/BASE: added vfs node for uct worker.

src/ucp/rndv/rndv.c
regression from #6208
cuda_copy ZCOPY is ignored on self endpoint because addr info is not sent because key md_map is empty.
Revert #6208 
Instead of deriving the scenarios by whether the address is passed or not in the RTS, pass the memory type of source address in the RTS to make the decisions at the receiver.
=> UCP/RNDV: Fix in mem type pipeline

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
add non blocking disconnect
to improve scalability
1. on all requests completion in case if connection->disconnect() was called move the connection to connecting progress list on context
2. close the endpoint and wait its completion
3. then the EP is closed, invoke user's disconnect callback which can delete the connection without blocking progress
=> IODEMO: non blocking disconnect

NEWS, src/ucp/rndv/rndv.c
porting https://github.com/openucx/ucx/pull/6614
=> UCP/RNDV: Fix in mem type pipeline - v1.10.x

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c
Added UCP EP error handling mode and peer name to VFS structure.
=> UCP/CORE: Added UCP EP features to VFS.

src/uct/base/uct_iface.c, src/uct/base/uct_md.c
Added directory to VFS to represent UCT interface object.
=> UCT/BASE: Added VFS node for UCT iface object.

src/ucs/sys/sock.c, src/ucs/sys/sock.h, test/gtest/ucs/test_sock.cc
Added method to get IP address of a given sockaddr structure.
To address PR comment: https://github.com/openucx/ucx/pull/6652#discussion_r615365118
=> UCS/SYS: Added method to get IP address from sockaddr.

NEWS, src/ucp/core/ucp_am.c, test/gtest/ucp/test_ucp_am.cc
=> UCP/AM: force eager protocol for old AM API - v1.10.x

src/ucp/proto/proto_am.c
If have not finished sending all fragments, do not complete the reqeust.
We could still post additional fragments from progress pending context.
cherry-picked from https://github.com/yosefe/ucx/pull/131
=> UCP/PROTO: Fix error handling for AM_ZCOPY

buildlib/azure-pipelines.yml, buildlib/jucx/jucx-publish.yml
Snapshot doesn't work when PR merged
run snapshot pipeline always when PR merged
=> AZP: Fix snapshot, run always in merge state

src/ucp/core/ucp_listener.c
Added directory to VFS tree representing UCP listener object.
Added UCP listener ip address and port to VFS structure.
The changes help to perform runtime analysis of UCX-based applications.
=> UCP/CORE: Added VFS nodes representing UCP listener.

buildlib/tools/builds.sh, buildlib/tools/common.sh
support PGI compiler from nvidia HPC-SDK toolchain
=> AZP: Add PGI support from hpc-sdk module

test/gtest/ucp/test_ucp_sockaddr.cc
Introduce `CM_USE_ALL_DEVICES=y` variant in sockaddr tests.
For better test coverage.
1. Add new test modifier `TEST_MODIFIER_CM_USE_ALL_DEVICES` in the same way as we have for `TEST_MODIFIER_MT`.
2. if `TEST_MODIFIER_CM_USE_ALL_DEVICES` set, set `CM_USE_ALL_DEVICES` to `"y"`, otherwise to `"no"`
3. Skip `connect_and_fail_wireup` and `compare_cm_and_wireup_configs` test if  `CM_USE_ALL_DEVICES` is `"no"`
=> GTEST/UCP: Introduce CM_USE_ALL_DEVICES=y variant in sockaddr tests

buildlib/azure-pipelines.yml
Snapshot launch on each commit to PR
pr: none should forbid launch on each commit to all PR
=> AZP: Build only for push to master/v*x not for each PR

buildlib/azure-pipelines.yml, buildlib/jucx-publish.yml
we need to use lowest version for build
=> AZP: Fix snapshot v1 10

src/uct/ib/rc/accel/rc_mlx5_devx.c
Fix compilation with devx, but without tag offload
=> UCT/RC: Fix hwtm compilation

src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_worker.c, src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, test/gtest/ucs/test_vfs.cc
Updated VFS structure API adding optional parameter to text callback function.
To simplify addition of similar files to VFS tree.
https://github.com/openucx/ucx/pull/6710#discussion_r620933659
=> UCS/VFS: Optional argument to text callback function.

src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, src/uct/tcp/tcp_sockcm.c, src/uct/tcp/tcp_sockcm_ep.c
UCP/WIREUP/CM: move uct_ep_connect to progress thread
to avoid calling UCT API from async thread 
schedule to progress queue
=> UCP/WIREUP/CM: move uct_ep_connect to progress thread

examples/ucp_client_server.c
=> EXAMPLES/UCP: fixed hang for RNDV case in UCP client server example

docs/source/faq.md
As it was pointed out, some of the answer are out of date. Updating the
answers to reflect the current state of the code.
FAQ update
As it was pointed out, some of the answer are out of date. Updating the
answers to reflect the current state of the code.
Answers have discussed
=> FAQ: Updating some of the answers.

src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_rkey.h, src/ucp/core/ucp_rkey.inl, src/ucp/core/ucp_worker.inl, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_reconfig.c, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/rndv.c, src/ucs/type/serialize.h, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/ucp/test_ucp_proto.cc, test/gtest/ucs/test_type.cc
Preparation for passing system topology information in rkey buffer
=> UCP/RKEY/TEST: Refactor rkey pack/unpack and tests

NEWS
News update
Adding missing items and making sure that we follow news format as defined by previous releases
=> NEWS: News update

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/dv/ib_mlx5_ifc.h, src/uct/ib/mlx5/ib_mlx5.h
Provide a method to tweak DC transport properties from UCX
=> UCT/DC/MLX5: Add configuration for full handshake mode

src/ucs/datastruct/frag_list.c, src/ucs/datastruct/queue.h, test/gtest/ucs/test_datatype.cc
Potential fix for #6738
Thanks @SeyedMir for identifying the issue!
=> UCS/QUEUE/FRAGLIST: Fix checking for last element in fraglist queue

src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/scopy/cma/cma_ep.c, src/uct/sm/scopy/cma/cma_ep.h, src/uct/sm/scopy/cma/cma_iface.c, test/gtest/common/test_obj_size.cc, test/gtest/uct/test_peer_failure.cc
Add support for handling peer failures to CMA and KNEM transports
Error handling support would allow  client-server application to use these transports
=> UCT/CMA/KNEM: Add errh support

src/ucs/datastruct/frag_list.c
Fixes https://github.com/openucx/ucx/issues/6785
=> UCS/FRAGLIST: Fix sn compare in assert

test/gtest/uct/test_peer_failure.cc
=> GTEST/UCT/CMA: Fix CMA peer failure test

NEWS
=> NEWS: News update before release v1.10.1

src/ucp/core/ucp_am.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_rkey.h, src/ucp/core/ucp_rkey.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/core/ucp_worker.inl, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_reconfig.c, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/offload.c, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_rndv.c, src/ucp/tag/tag_rndv.h, src/ucs/sys/topo.c, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/ucp/test_ucp_proto.cc
Pass remote topology information to select a protocol which is good for both local and remote topology
=> UCP/PROTO/RKEY: Pack system topology information

test/apps/iodemo/io_demo.cc
Improve logging of sent/completed.
To improve debugging.
Split `num_sent` to IO read and IO write as we have for `num_completed`
=> APPS/IODEMO: Improve logging of sent/completed

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup_cm.c
- reuse common priv data pack for client and server
- pass ucp_tl_bitmap_t as a pointer
=> UCP/WIREUP: refactoring

src/ucp/rndv/proto_rndv.c
- fixed potential coverity issue: Error: CHECKED_RETURN
=> RNDV/COVERITY: fixed potential issue

src/ucp/core/ucp_rkey.c, src/ucp/rndv/proto_rndv.c, src/ucs/sys/math.h, src/ucs/sys/topo.c, test/gtest/ucp/test_ucp_mmap.cc
Fixing post-merge code review comments for #6757
@gleon99
=> UCP/RKEY/TEST: Apply review comments for system device pack/unpack

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcxTest.java, src/ucp/core/ucp_mm.c, src/uct/base/uct_mem.c, test/gtest/ucp/test_ucp_mmap.cc
Let ucp_mem_map allocate mem_type memory 
Needed for device staging buffers for rendezvous pipeline
=> UCP/CORE: support cuda memory allocations with ucp_mem_map

src/tools/perf/lib/ucp_tests.cc, src/ucp/api/ucp.h, src/ucp/api/ucp_def.h
Remove UCP AM chunk API
It was not released (and implemented) yet. There are plans to change it, so need to avoid releasing this version of API now.
=> UCP/API: Remove  UCP AM chunk API

buildlib/io_demo/iodemo_analyzer.py
Support new and old format for io-demo output
=> IODEMO: Support new log format

src/ucs/memory/rcache.c, src/ucs/memory/rcache.h, test/gtest/ucs/test_rcache.cc
- added ucs_rcache_region_put_and_invalidate function
=> RCACHE: added region_put_and_invalidate call

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c
Call handler for DC KA send completion to release it when purging.
To correctly release DC KA send operation when it wasn't completed yet and we purge it from TX QP.
This is preparation for the new send operation with custom handler in DC (e.g. sending FC_PURE_GRANT).
1. Fix `uct_rc_txqp_purge_outstanding()` to check the type of handler and if it is Atomic, Bcopy, Zcopy - cast to `desc` and put to mpool. But if it is some other operation - just call operation hadler.
2. Fix `uct_dc_mlx5_ep_keepalive_cleanup()` to check not only pointer to `EP` in send operation structure, but check handler to make sure that this is KA send operation.
3. Fix code style where it is broken in the related code.
=> UCT/IB: Call handler for DC KA send completion to release it when purging

src/uct/cuda/gdr_copy/gdr_copy_md.c
gdr_map can return failure on non-contig gpu physical pages when it is trying to merge registration regions
=> UCT/GDRCOPY: Silent mem reg errors if flag is set

src/ucs/memory/rcache.c, src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, test/gtest/ucs/test_vfs.cc
Updated `ucs_vfs_obj_add_dir` to handle duplicate directory names.
=> UCS/VFS: Handle duplicate directory names.

.readthedocs.yaml, buildlib/azure-pipelines-pr.yml, docs/.readthedoc.requirements.txt, docs/doxygen/ucxdox, docs/source/api.rst, docs/source/conf.py, docs/source/index.rst, src/ucp/api/ucp.h
Read The Docs and doxygen integration
Generates very nice website for our API automatically: https://ucx-shamisp.readthedocs.io/en/latest/api.html
Using sphinx + breath + Doxygen XML
=> DOCS: Read The Docs and doxygen integration

src/uct/rocm/base/rocm_base.c, src/uct/rocm/copy/rocm_copy_md.c, src/uct/rocm/ipc/rocm_ipc_md.c
Fix issues with ROCm memory registration
1. Fix incorrect logic for identifying device memory
2. Don't try to lock device memory for registration
=> Fix issues with ROCm memory registration

bindings/java/src/main/native/context.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Fixes and tests tagSenderMask parameter
=> JUCX: fix tag sender mask.

src/uct/ib/base/ib_md.c
Remove unnecessary if
Optimization
Simply return status
=> UCT: Remove unneeded check

src/uct/api/v2/uct_v2.h
- updated comments on functions descriptions
=> UCT/MEM/V2: updated docs

src/ucp/core/ucp_worker.c
fix error handling
if the EP has been closed from completion callback its state was changed
do not destroy already closed EP
=> UCP/EP: fix error handling

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
fix connection leak if its establishment fails
bugfix
cherry-picked from https://github.com/yosefe/ucx/pull/146
=> IODEMO: fix connection leak if its establishment fails

src/uct/rocm/copy/rocm_copy_md.c
Port https://github.com/openucx/ucx/pull/6920 to v.1.11.x branch
=> UCT/ROCM/COPY: Fix device memory deregistration - v1.11.x

buildlib/azure-pipelines-pr.yml
Build ucx in centos7 container and run ucx_info and perftest on ubuntu20
=> AZP: Test ucx binary compatibility between OS versions.

src/ucs/arch/bitops.h
Signed-off-by: Alex Margolin <alex.margolin@huawei.com>
=> UCS: fixes #6925 by checking the remainder

contrib/test_jenkins.sh, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/debug/memtrack.c, test/apps/Makefile.am, test/apps/test_memtrack_limit.c
- added memory limit to memtrack infra
to allow terminate process on too
high memory usage
=> MEMTRACK: added memory limit

Makefile.am, bindings/go/Makefile.am, bindings/go/context.go, bindings/go/context_params.go, bindings/go/context_test.go, bindings/go/go.mod, buildlib/azure-pipelines-pr.yml, buildlib/go/go-test.yml, config/m4/go.m4, configure.ac, contrib/test_jenkins.sh
=> BINDINGS/GO: Go language bindings: UcpContext + Build  + CI infra

src/ucp/core/ucp_worker.c
Complete KA round if iter == iter_begin after removing EP from KA.
Fixes:
```
[jazz23:179207:0:179207] ucp_ep.c:2800 Assertion `(now - ucp_ep_ext_control(ep)->ka_last_round) >= worker->context->config.ext.keepalive_interval' failed: ep 0x7f63c864d098: now=2841347436793599 ka_last_round=2841347429892534 ka_interval=144000000000
```
The following case leads this, when the KA is done several times for the `EP #1`:
1. Introduced wrapper for completing KA round - `ucp_worker_keepalive_complete()`.
2. When removing the EP from KA and the current KA iterator points to the EP, check if the next KA iterator point to the `iter_begin` (if yes, complete KA round).
=> UCP/CORE: Complete KA round if iter == iter_begin after removing EP from KA

src/uct/ib/rc/verbs/rc_verbs_iface.c
The old way of checking support for RC verbs does not work correctly for EFA devices. It wrongly concludes that the device supports RC and thus leads to errors in `ucx_info -d`.
Fixes https://github.com/openucx/ucx/issues/6882
=> UCT/IFACE: Check RC verbs support by creating a dummy QP

src/ucp/wireup/wireup.c, src/ucs/config/parser.c, src/ucs/memory/rcache.c, src/uct/ib/mlx5/ib_mlx5_log.c
- there is set of coverity false positives
- suppressed
=> COVERITY: suppressed false positives

src/uct/ib/dc/dc_mlx5_ep.h
=> UCT/DC/MLX5: Fix deadlock between DCI resources and RDMA_READ credits - v1.11.x

bindings/go/Makefile.am, buildlib/go/go-test.yml
Fixes out of source build in go
=> BINDINGS/GO: fix OOS build.

test/apps/iodemo/ucx_wrapper.cc
Improve logging by printing the type of operation that was completed/canceled.
To improve logging in IO-demo.
1. Define global constants which have names of the UCP operations.
2. Save the name of the operation to the request structure - `struct ucx_request`/
3. Print the name of the operation when canceling operations or completing them during disconnect.
=> APPS/IO-DEMO: Improve logging

src/uct/rocm/copy/rocm_copy_iface.c, test/gtest/uct/test_p2p_rma.cc, test/gtest/uct/v2/test_uct_query.cc
Fix test_uct_query gtest
Was failing due to missing implementation of iface_estimate_perf()
=> UCT/ROCM/COPY: Fix test_uct_query gtest

bindings/go/Makefile.am
Fix gopath to be outside of source.
To fix #6982
=> BINDINGS/GO: Fix gopath to be outside of source.

test/apps/iodemo/io_demo.cc
It's possible that data is splitted into small chunks during write/read operation. If the internal chunk write/read operation is executed without that ucs_status_t is UCS_OK, then the end of callback should take the internal failure case into consideration.
=> converge ucs_status for action in the end of callback

src/tools/perf/lib/ucp_tests.cc
Add a method reset_buffers to reset sn for both send/receive buffers in ucp_put cases. This method is then used in run_pingpong and run_stream_uni.
Without the resetting a performance degradation was encountered in run_stream_uni. https://github.com/openucx/ucx/pull/6951 reported this issue and proposed a simple patch. This patch is for the same purpose but takes yosefe's comments in.
=> TOOLS/PERF: Add a method to reset sn in ucp_put case

buildlib/azure-pipelines-release.yml
Failed Release CI when set tag
Change system variable that contains CommitID
=> AZP/RELEASE: Change variable for get CommitID for set tag

buildlib/azure-pipelines-release.yml
Failed Release CI when set tag
Change system variable that contains CommitID
=> AZP/RELEASE: Change variable for get CommitID for set tag v1.11.x

NEWS
News update before release 
Manual parsing of git log
=> News update for v1.11.0 rc2

AUTHORS, buildlib/azure-pipelines-pr.yml
=> AUTHORS: Updating the list

NEWS
=> NEWS: Backport of news from 1.10.1 release

AUTHORS, buildlib/azure-pipelines-pr.yml
Backport from v1.11.x tree + recent contributors
`git log --format='%aN <%aE>' | sort -u `
=> AUTHORS list update

src/tools/info/ucx_info.c
Updating ucx_info help message to reflect which feature flags should be specified.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1973959
=> TOOLS/INFO: Update help message for context features

test/apps/iodemo/io_demo.cc
Replace rand by urand where it is possible.
To simplify code.
`rand(size_t(0), <max_val> - 1)` -> `urand<size_t>(<max_val>)`
=> APPS/IO-DEMO: Replace rand by urand where it is possible

test/apps/iodemo/io_demo.cc
Fix reporting performance when no data completed on IO-Demo Client/Server.
Fixes:
```
[1625154064.946534] [DEMO] read 0.801156 MBs min:0(2.1.3.8:57414) max:2 total:35 | write 0.564616 MBs min:0(2.1.3.8:57414) max:0 total:9 | active: 101/101, buffers:690
```
i.e. reporting that total completed - `9`, but maximum completed per servers - `0`.
1. Fix `update_min_max()` to correctly calculate `min`/`max` using number of completions instead of bytes. Bytes can be written, when not all fragments are received, but completion counter isn't incremented in case of error.
2. Fix `update_min_max()` to correctly calculate `max` if some iterator is `min` and `max` by removing `else` for `max`.
3. Fix `report_performance()` on a Client by removing `op_info_t` (no longer needed) and calculate …
=> APPS/IO-DEMO: Fix reporting performance when no data completed

NEWS
Updating the news for next RC, after fixing release pipeline
=> NEWS: Update to v1.11.0-rc3

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
- register allocated memory in memtrack
=> IO-DEMO: register allocated memmory in memtrack

buildlib/az-distro-release.yml, buildlib/az-helpers.sh, buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.yml, buildlib/jucx/jucx-publish.yml, contrib/buildrpm.sh
Port Azure pipeline fixes to master branch
=> AZP/RELEASE: Port fixes from v1.11.x to master

NEWS, src/uct/ib/dc/dc_mlx5.h
Backport #7079 and update news
=> UCT/DC: Fix compilation with rdma-core 20 - v1.11.x

src/ucp/tag/eager.h, src/ucp/tag/eager_single.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/offload/eager.c
Add tag sync offload protocols with new proto infrastructure
=> UCP/PROTO: Add new protocols for tag offload sync

test/apps/iodemo/io_demo.cc
Report performance after IO operations done for all connections at least once.
Report performance w/o "min:0" (if possible), i.e. when number of active servers is equal to number of all servers.
1. Go over all connection using `_active_servers` vector - it is already randomly shuffled.
2. Increment next active server index only when all operations are done at least one for a connection.
3. Report performance if all IO operations for all connections are done at least once.
=> APPS/IO-DEMO: Report performance after IO operations done for all connections at least once

test/apps/iodemo/io_demo.cc
num_offcache_buffers does not take effect anymore. Needs to support it.
num_offcache_buffers does not take effect anymore. Needs to support it.
_offcache_queue was populated in ObjectPool constructor which indirectly called virtual function construct() so move _offcache_queue population into a newly created function init().
=> APPS/IODEMO: Support num_offcache_buffers again

test/apps/iodemo/io_demo.cc
Fix reporting BW if no operations done.
Fixes reporting BW when no operations done at all:
```
[1626338858.727786] [DEMO] total min:0 max:0 total:0 | read 1.06687 MBs min:0(1.1.28.3:20001) max:0 total:0 | write 1.06321 MBs min:0(1.1.28.3:20001) max:0 total:0 | active:0/0 buffers:112
```
1. Save `bytes_sent`/`bytes_completed` in `server_info_t` objects.
2. Get the values from `IO_READ_COMP` and `IO_WRITE_COMP` messages.
3. Remove `total_bytes` passed to `report_performance()` on a client and calculate total_bytes for each operation in `report_performance()` by using `bytes_completed` from each `server_info_t`.
4. Add useful assertions to verify `bytes_sent`/`bytes_completed`.
=> APPS/IO-DEMO: Fix reporting BW if no operations done

src/uct/ib/rdmacm/rdmacm_cm_ep.c
fix err code on rdma_establish failure
return clear err code
=> UCT/IB/RDMACM: fix err code on rdma_establish failure

test/apps/iodemo/io_demo.cc
1. Add comments.
2. Remove excessive code.
1. Need to document the fields of `server_info_t`.
2. `get_num_completed_round()`/`get_numPosted_round()` are not needed.
1. Add comments for `bytes_sent`/`bytes_completed`.
2. Remove functions and replace usage of `get_num_completed_round()` by its body.
=> APPS/IO-DEMO: Add comments, remove excessive code

src/uct/cuda/base/cuda_iface.h, src/uct/cuda/cuda_copy/cuda_copy_ep.c
Show Cuda function calls in read_profile tool
=> UCT/CUDA: Profile Cuda runtime function calls

src/tools/profile/read_profile.c
Fix the output of read_profile tool
=> TOOLS/PROFILE: Fix read_profile print of new request

test/apps/iodemo/io_demo.cc
Handle SIGINT signal to gracefully terminate client/server.
This is needed to close all Network objects (e.g. UCX worker, EPs, etc) and destroy memory for all allocated operationss/callbacks.
1. Move `_status` field to `P2pDemoCommon` class which is common for `DemoClient`/`DemoServer`.
2. Set signal actions from `vfs_server_sighandler()` to be able raise the signal to the old signal handler.
3. Handle `SIGINT` signal in IO-Demo signal handler and set `_status` to `RUNTIME_EXCEEDED`.
4. Stop server process by checking `_status != OK`.
=> APPS/IO-DEMO: Handle SIGINT signal to gracefully terminate client/server

test/apps/iodemo/io_demo.cc
Simplify io_demo scheduling code
- Remove _num_active_servers_to_use variable; instead add/remove used/unused servers to _active_servers array
- Unify add/remove with make_used/unused
=> IODEMO: Refactor and simplify _active_servers usage

src/ucs/config/global_opts.c, src/ucs/type/init_once.h, src/ucs/vfs/base/vfs_obj.c
Added RW file to represent log level in VFS.
The changes allows to set log level of the target process via VFS file in run time.
=> UCS/CONFIG: Added VFS node representing log level.

src/ucs/datastruct/string_buffer.c, src/ucs/datastruct/string_buffer.h, test/gtest/ucs/test_string.cc
Convenience function to print flags/bitmask
=> UCS/STRING: Add method ucs_string_buffer_append_flags

test/apps/iodemo/io_demo.cc
Fix BW calculation by resetting bytes_completed counter.
To report the correct BW every round. BW was correct only for the first round.
Reset server_info's `bytes_sent`/`bytes_completed` to `0` for each operation.
=> APPS/IO-DEMO: Fix BW calculation by resetting bytes_completed counter

buildlib/az-helpers.sh
=> AZP/RELEASE: Fix commit title check - v1.11.x

buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.yml, buildlib/jucx/jucx-publish.yml
=> JUCX: fix JUCX publish v.1.11

src/ucp/core/ucp_request.h, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_multi.h, src/ucp/proto/proto_multi.inl, src/ucp/rma/get_offload.c, src/ucp/rma/put_am.c, src/ucp/rma/put_offload.c, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv.h, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, src/ucp/tag/tag_rndv.c
Adding rdnv/put/zcopy new protocol is a large change to it's split to 2 PRs.
This PR adds some infra changes, next PR will add the protocol itself
=> UCP/PROTO: Preparations for adding rdnv/put/zcopy protocol

examples/ucp_client_server.c
Add TAG IOV operation in ucp_client_server program 
it's too heavy to add TAG IOV operation in io_demo. It's decided to add the operation in ucp_client_server program
1. This PR doesn't break the original usage.
2. new option "-v" to set iov data count in one iov operation. default value is "1", which works under contig data operation.
=> add TAG IOV operation in ucp_client_server program

docs/source/running.md
Add documentation for running in docker
=> DOCS: Add documentation for running in docker

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/core/ucp_worker.inl
Split UCP worker's ptr_map into ep_ptr_map and request_ptr map.
Locked modifying of ep_ptr_map.
=> UCP/CORE: Split worker's ptr_map.

src/uct/base/uct_iface.h
Porting TCP fix from #7168 to v1.11.x
There were no merge conflicts
@dmitrygx
=> UCT/BASE: Fix deadlock in TCP - v1.11.x

test/gtest/ucp/test_ucp_mmap.cc
When new protocols are enabled, rkey->cache is not used and left uninitialzed
=> TEST/RKEY: Don't test rkey.cache when proto is enabled

buildlib/azure-pipelines-pr.yml, buildlib/tests.yml, contrib/test_jenkins.sh, src/uct/api/uct.h, src/uct/ib/base/ib_md.c, src/uct/ib/base/ib_md.h, src/uct/sm/mm/base/mm_md.c, src/uct/sm/mm/base/mm_md.h, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, test/apps/test_ucp_dlopen.c, test/gtest/ucp/test_ucp_stream.cc, test/gtest/ucs/test_twheel.cc, test/gtest/uct/ib/test_ib.cc, test/gtest/uct/uct_p2p_test.cc
=> AZP: Run tests in Docker

NEWS, src/ucs/Makefile.am, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/sys/uid.c, src/ucs/sys/uid.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h
Create new header uid.h , add it to installed list, and move ucs_iface_get_system_id from sys.h to uid.h 
Expose ucs_iface_get_system_id to UCS public API
Move method between headers
=> UCS/SYS: Add uid header file

test/apps/iodemo/run_io_demo.sh
=> IODEMO: add key -kill for run_io_demo.sh

NEWS, src/ucs/Makefile.am, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/sys/uid.c, src/ucs/sys/uid.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h
=> UCS/SYS: Add uid header file - v.11.x

NEWS
Bring news changes from the v1.11.x to the master.
=> NEWS: Porting news from 1.11.x to master

src/ucp/core/ucp_rkey.c
Fixes condition to check `UCP_RKEY_MPOOL_MAX_MD` to get allocation from a memory pool or by malloc.
=> UCP/RKEY: fix condition to use mpool for unpacked rkeys

docs/source/running.md
Mention explicitly the requirements for using RDMA.
=> DOCS: Improve docker docs

src/ucp/tag/probe.c
=> UCP/TAG: Fix mt bug in probe - v1.11.x

src/ucp/tag/probe.c
Add locks in probe function (mistakenly removed #6265)
=> UCP/TAG: Fix mt bug in probe

buildlib/azure-pipelines-pr.yml, contrib/test_jenkins.sh, src/ucp/proto/proto_common.c, src/ucp/rndv/rndv_put.c, src/ucs/datastruct/khash.h, src/ucs/debug/memtrack.c, test/apps/iodemo/io_demo.cc
- Static checker was passing even though there were errors, due to wrong source path dir
- Improve/clean CI output
=> AZP: Test fixes

src/ucp/dt/datatype_iter.c, src/ucp/dt/datatype_iter.h, src/ucp/dt/datatype_iter.inl, src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.inl, src/ucp/proto/proto_single.inl, src/ucp/rma/amo_offload.c, src/ucp/rma/amo_sw.c, src/ucp/rma/get_am.c, src/ucp/rma/get_offload.c, src/ucp/rma/put_am.c, src/ucp/rma/put_offload.c, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_put.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload/eager.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_dt.cc, test/gtest/ucp/test_ucp_tag_match.cc
Support zero-copy IOV send with datatype_iter and eager_multi protocol
=> UCP/PROTO/TEST: Eager-multi zero copy with IOV list

test/gtest/ucp/test_ucp_perf.cc
=> TEST/PERF: Reduce testing time for test_ucp_wait_mem

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConnectionRequest.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListener.java, bindings/java/src/main/native/Makefile.am, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/listener.cc, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
ucp_listener_reject functionality.
To reject incoming connection request.
CC @abellina
=> JUCX: ucp_listener_reject functionality.

src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_select.c
Easier debug of protocol lanes and performance estimations
=> UCP/PROTO: Add more logging to protocol selection process

src/ucs/datastruct/callbackq.c
Provide more debug info for callback queue
=> UCS/CALLBACKQ: Print leaked callbacks

src/tools/vfs/vfs_main.c
Removed mountpoint directory on stop of VFS monitoring daemon.
This PR fixes the following scenario:
1. User1 executes `ucx_vfs` with default parameters.
2. `/tmp/ucx/` is created
3. User1 executes `ucx_vfs` stop.
4. User2 executes `ucx_vfs` with default parameter.
5. User2 starts UCX-based application and gets "failed to create directory ...".
=> TOOLS/VFS: Remove mountpoint directory.

buildlib/io_demo/iodemo_analyzer.py
1 min threshold  is not enough for analyzer
=> IODEMO: Change default threshold to 3 min for analyzer

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/time/time.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, test/gtest/uct/test_peer_failure.cc
=> UCT/UCS/KEEPALIVE: Fix overflow when recording file create time

src/ucp/core/ucp_request.inl
Removed extra method `ucp_ep_ptr_id_alloc`.
Re-named `ucp_ep_ptr_map_check_status` to `ucp_request_ptr_map_status_check`.
Addressed https://github.com/openucx/ucx/pull/7159#discussion_r689850233
=> UCP/CORE: Updated methods working with request ptr map.

test/apps/iodemo/run_io_demo.sh
To know when some prints happened
=> IODEMO: Print timestamps from run_io_demo.sh script

src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_devx.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5_common.c, src/uct/ib/ud/accel/ud_mlx5_common.h, src/uct/ib/ud/verbs/ud_verbs.c
Debug failures with ibv_create_ah()
=> UCT/IB: Print reason for creating AH when ibv_create_ah() fails

test/gtest/ucs/test_datatype.cc
Replaced multiple call for new operator by initializing vector.
Addressed
https://github.com/openucx/ucx/pull/7159#discussion_r689863284
https://github.com/openucx/ucx/pull/7159#issuecomment-901674724
=> GTEST/UCS: Updated ptr_map gtests.

test/apps/iodemo/io_demo.cc
- added logging of handled signals to simplify logs parsing
=> IODEMO/LOG: added logging of handles signals

buildlib/jucx/jucx-publish.yml
Fixes pipeline to publish JUCX
Porting #7309 to master
=> AZP: Fix publish pipeline.

src/uct/ib/dc/dc_mlx5_ep.c
Fix "timeout waiting" for replies error from io_demo, when all DCIs are scheduled for release but release progress is not running, and iface cannot send anything.
DCI release progress should keep doing its thing until all DCIs are released. Sometimes progressing pending operations can add more DCIs to the release queue.
=> UCT/DC: Keep releasing DCIs until release_bitmap is 0

src/ucp/core/ucp_request.h, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_multi.h, src/ucp/proto/proto_multi.inl, src/ucp/proto/proto_select.h, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_put.c, test/gtest/common/test_obj_size.cc
Preparations for RNDV-pipeline protocol
=> UCP/RNDV: Add infrastructure for rndv pipeline

NEWS
Update the news for v1.11.1 release
=> NEWS: Update for v1.11.1 release

test/gtest/ucs/test_memtrack.cc
- Sometimes, the ucs_posix_memalign_realloc() call may hold
two buffers for a short time if malloc() returned an unaligned pointer.
- The above yields a larger peak_size of the memalign_realloc()
and causes the test to fail.
=> UCS: Fix test total_memalign_realloc issue (memtrack)
