openucx/ucx

- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
fix and test stream_recv request immediate path (port to 1.8 branch)
Cherry pick from #4754
> JUCX: fix and test stream_recv request immediate path - v1.8.x

- src/uct/api/uct.h
- src/uct/base/uct_iface.c
Support devices which have larger bandwidth when using multiple connections, for example RoCE LAG, or IB LMC.
Add "dev_num_paths" count in UCT API which specifies how many endpoints can be created to same destination for optimal performance. UCP would use this to instantiate multiple UCT endpoints in a multi-rail fashion using the different paths.
> UCT/API: Add API for endpoints multi-path

- src/ucp/core/ucp_ep.c
- src/ucp/wireup/wireup_cm.c
- test/gtest/ucp/ucp_test.cc
- if client has flushed "EP to IFACE" lanes and disconnected CM lane
faster than server completes connection establishment, server may get
connect callback invoked with status UCS_ERR_CONNECTION_RESET.
- invoke ucp_ep_invoke_err_cb(ucp_ep, UCS_ERR_CONNECTION_RESET)
after flush
bugfix
> UCP/EP/CM: fix close protocol on server side

- src/ucs/sys/sock.c
- src/ucs/sys/sock.h
- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_device.h
- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/cm/cm_ep.c
- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/dc/dc_mlx5_devx.c
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/mlx5/exp/ib_exp_md.c
- src/uct/ib/mlx5/ib_mlx5_log.c
- src/uct/ib/rc/accel/rc_mlx5_common.c
- src/uct/ib/rc/accel/rc_mlx5_devx.c
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
- test/gtest/uct/ib/test_ib.cc
When checking if two peers are reachable in the IB uct, consider their RoCE version and address family (in case of an ETH link layer), and if they are not same on both sides, consider the peers as unreachable.
Fixes https://github.com/openucx/ucx/issues/4619
Pack the RoCE version and address family in uct_ib_address_pack() and compare the values in uct_ib_iface_is_reachable()
> UCT/IB: consider the RoCE version when checking reachability.

- src/ucp/core/ucp_request.inl
- src/ucp/proto/proto_am.inl
Fix a bug found with multi-path code: if there are no resources on both lanes on same arbiter (they could be on same arbiter only in case of multi-path), they would keep reschedule each other without sending anything, and without stopping the arbiter, which leads to infinite loop and hang in arbiter dispatch.
When we fail to send on a particular lane, don't try to move to next lane, this will force returning UCS_ERR_NO_RESOURCE from UCP pending callback, back to UCT progress code, which will in turn check the iface resources and return ARBITER_STOP.
> UCP/PROTO: Move to next am_bw lane only if sending was successful

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpTagMessage.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java
- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/main/native/jucx_common_def.h
- bindings/java/src/main/native/worker.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java
Ucp tagProbe message functionality: `tagProbe` and `recvTagMessage`
As requested in #4723 and also for SparkUCX to submit recv request only when there's a message in recv queue.
> JUCX: tag_probe message functionality.

- test/gtest/common/test_helpers.cc
- test/gtest/common/test_helpers.h
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/uct/ib/test_sockaddr.cc
- test/gtest/uct/uct_test.cc
add a loop around UCS_ERR_BUSY on listener create in \*test_ucp_sockaddr\*
fixes #4739
1) start listener on port 0 (any) then update value in storage used by client.
2) loop is needed because different underlying UCT implementations are sharing the same port but some port space can be free but other one - busy.
> GTEST/UCP/SOCKADDR: add a loop around UCS_ERR_BUSY on listener create

- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
On running infinite jucx test loop, in rare cases it fails:
```
org.junit.ComparisonFailure: expected:<[]> but was:<[d9cd8ee0-d5fa-4ac8-a5d1-2e590d3c1fac]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.openucx.jucx.UcpEndpointTest.testPutNB(UcpEndpointTest.java:139)
```
Indeed 
```
Call-back function that is invoked whenever the put operation is completed and the local buffer
can be modified. Does not guarantee remote completion.
```
So flushing the second worker to guarantee put completion to dst buffer.
Fixing test issue.
> JUCX: flush worker to guarantee put completion on receive side.

- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.inl
- src/ucp/proto/proto_am.inl
Don't register UCT memory handle for TLs that don't need it
Improves performance and adds support for UCT TLs that don't need MEMH, e.g. TCP, SELF (they have stubs for memory registration) and KNEM (call `ioctl()` to register memory, but it doesn't)
After enabling multi-lane over IOV for TAG and AM the following test failures were seen:
* UCP AM API:
```
[ RUN      ] rcx/test_ucp_am.send_process_iov_am/0 <rc_x>
[     INFO ] 1581x10^1 500x10^2 158x10^3 50x10^4 [jazz09:106635:0:106635] ib_mlx5_log.c:139  Local protection on mlx5_0:1/IB (synd 0x4 vend 0x52 hw_synd 0/146)
[jazz09:106635:0:106635] ib_mlx5_log.c:139  RC QP 0x1194e wqe[0]: SEND s-- [inl len 36] [va 0x1cca86c len 8164 lkey 0xcfc12]
/labhome/dmitrygla/work_auto/ucx/src/uct/ib/mlx5/ib_mlx5_log.c: [ uct_ib_mlx5_completion_with_err() …
```
> UCP/CORE: Don't register UCT memory handle for TLs that don't need it

- src/tools/profile/read_profile.c
Move the incorrect assert to the proper place in ucx_read_profile tool code
Fixes the following assertion failure:
```
ucx_read_profile: read_profile.c:558: show_profile_data_log: Assertion `reqid_ctr > 1' failed.
```
1. Move `assert()` under the case when khash entry was found
2. Remove extra empty space after `NEW` in the `"NEW "` string constant
3. Fix name of `num_records` variable
4. Use `size_t` instead of `int` for request ID to avoid overflow
> TOOLS/PROFILE: Fix incorrect assert

- src/uct/ib/base/ib_iface.h
- src/uct/ib/base/ib_verbs.h
- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_common.c
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/verbs/ud_verbs.c
- src/uct/ib/ud/verbs/ud_verbs.h
- test/gtest/uct/ib/test_dc.cc
- test/gtest/uct/ib/test_rc.cc
- test/gtest/uct/ib/test_rc.h
- test/gtest/uct/ib/test_ud.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
Update `max_iov` capabilities of UCT RCX and DC interfaces
Remove extra restrictions for UCT zcopy functions (can really send up to 14 iovs instead of 8 with RC PRM transports)
> UCT/RCX/DC/GTEST: Update max_iov iface caps for PRM tls

- src/ucp/tag/tag_send.c
Don't increment AM message ID twice for Bcopy/Zcopy multi protocols
It's already done before this in `ucp_request_send_start()` when detected that we have to use multi-protocol of Bcopy or Zcopy
Just remove excessive `if` statement and code executed there (new AM message ID assigned, AM message ID increment, setting AM BW index to `1`)
> UCP/TAG: Don't increment AM message ID twice for Bcopy/Zcopy multi

- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- test/gtest/uct/ib/test_rc.cc
Flow control for rdma_read operations:
- Add env variable which limits number of simultaneous RDMA_READ operations.
- Add env variable which defines maximal size of get_zcopy operation
Can be useful to avoid/control congestions 
Maintain a counter of simultaneous get operations
> UCT/RC: Flow control for get operations

- src/ucp/core/ucp_context.c
Avoid incorrect error message when several tl aliases (including the same transport) are provided in `UCX_TLS`
Confusing error message. It proposes to use "unavailable" transport as one of "available transports", like below:  
transport **'rc'** is not available, please use one or more of: ..., **rc**, ...
**Example**
Before:
```
$mpirun -n 2 -mca pml ucx  -x UCX_TLS=sm,ib,rc  ./osu_latency
[1582272180.128662] [jazz13:155325:0]    ucp_context.c:690  UCX  WARN  transport 'rc' is not available, please use one or more of: cm, cma, dc, dc_mlx5, dc_x, ib, knem, mm, posix, rc, rc_mlx5, rc_v, rc_verbs, rc_x, self, shm, sm, sysv, tcp, ud, ud_mlx5, ud_v, ud_verbs, ud_x, xpmem
[1582272180.128674] [jazz13:155324:0]    ucp_context.c:690  UCX  WARN  transport 'rc' is not available, please use one or …
```
> UCP: Do not report excessive tl alias as unavailable

- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_cm.h
- src/ucp/wireup/wireup_ep.c
- src/uct/api/uct.h
- src/uct/api/uct_def.h
- src/uct/base/uct_cm.c
- src/uct/base/uct_cm.h
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/rdmacm/rdmacm_cm_ep.c
- src/uct/ib/rdmacm/rdmacm_ep.h
- src/uct/ib/rdmacm/rdmacm_iface.c
- src/uct/ib/rdmacm/rdmacm_listener.h
- src/uct/tcp/sockcm/sockcm_ep.c
- src/uct/tcp/sockcm/sockcm_ep.h
- src/uct/tcp/tcp_listener.h
- src/uct/tcp/tcp_sockcm_ep.c
- test/gtest/uct/ib/test_sockaddr.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
Add field mask usage to the client-server CM callbacks.
Allow backward compatibility support when passing the arguments to the CM callbacks.
Add new structs with field_mask in them and the possible fields that are set for the callback. Each field corresponds to its own bit in the field_mask. If the bit is set, the filed value is valid and can be used.
Pass the struct as arguments to the callbacks rather than the fields in the them.
> UCP/UCT/API/GTEST: Add field mask usage to the client-server CM callbacks

- config/m4/compiler.m4
- configure.ac
- src/ucs/Makefile.am
- src/ucs/arch/aarch64/cpu.h
- src/ucs/arch/aarch64/memcpy_thunderx2.S
Add memcpy from https://github.com/jjones-cavium/thunderx2lib/blob/master/memcpy_thunderx2.S for fast Marvell ThunderX2 memcpy with XPMEM
Improves XPMEM performance on ThunderX2 CPUs, as tested with OSU bibw.
Cavium optimised memcpy
> UCS/ARCH: Added optimized memcpy for ThunderX2

- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
- contrib/test_jenkins.sh
- src/ucs/memory/memtype_cache.c
Close rkey after worker flush.
This + `export UCX_MEM_EVENTS=no` fixes #4786 + runs 12 hours (3100 iterations) on boo31.
TODO: whether to add  `export UCX_MEM_EVENTS=no` to jucx tests or to figure out why it fails java malloc/free on boo31.
> JUCX: close rkey after worker flush.

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_worker.c
- src/ucp/tag/offload.c
- src/ucp/tag/rndv.c
- src/ucp/wireup/address.c
- src/ucp/wireup/address.h
- src/ucp/wireup/select.c
Use `ucp_md_index_t` instead of `ucp_rsc_index_t` with MD index
We have a type for MD index and `ucp_rsc_index_t` is a typedef for `ucp_md_index_t`
But this is just for consistency
Find and replace:
`ucp_rsc_index_t` -> `ucp_md_index_t`
> UCP: Use ucp_md_index_t instead of ucp_rsc_index_t with MD index

- src/uct/api/uct_def.h
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/tcp/tcp_sockcm_ep.c
- test/examples/ucp_client_server.c
- test/gtest/uct/ib/test_sockaddr.cc
Allow server side to see the IP address of the connecting client, similar to Linux accept() call.
This PR implements UCT part: pass IP address to server connection request callback. Next PR will use this UCT API to implement UCP part.
> UCT/API: add client's sockaddr as param to server connection request cb

- bindings/java/src/main/native/jucx_common_def.cc
Set debug log level for on error callback. Users in JAVA will get status and can use any log level. For cancel request do not log at all.
To not bother with errors when there's no errors (like request cancel).
> JUCX: do not log on canceled requests + decrease log level.

- src/ucp/core/ucp_worker.c
- src/ucs/config/types.h
- src/ucs/debug/log.c
- src/ucs/debug/log.h
do not print error on UCS_ERR_CONNECTION_RESET
do not print error if connection reset by remote peer since it can be part of user level close protocol
> UCP/WORKER: do not print error on UCS_ERR_CONNECTION_RESET

- test/gtest/ucp/test_ucp_sockaddr.cc
fix address storage
bad commit is c1b9af1d923367177a692b92588a7ec53aba09d2
> GTEST/UCP/SOCKADDR: fix test_ucp_sockaddr.listen_inaddr_any

- test/gtest/ucp/test_ucp_wireup.cc
> GTEST/UCP: test_ucp_wireup_amo.relese_key_after_flush

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/select.c
Without this fix too many shared memory lanes are created, e.g
```
$ UCX_TLS=sm ./build-devel/src/tools/info/ucx_info -e -u t
#
#
#
#
#
```
replaces #4787
@dmitrygx
> UCP/SELECT: Don't select more rma_bw lanes if found rkey_ptr lane

- src/ucs/datastruct/arbiter.c
- src/ucs/datastruct/arbiter.h
- src/ucs/datastruct/list.h
- src/uct/ib/dc/dc_mlx5.c
- test/gtest/ucs/test_arbiter.cc
- test/gtest/uct/ib/test_rc.cc
In order to support multi-path need to be able to schedule one group (next lane) while another group is being dispatched (next lane) on the same arbiter (the iface these lanes belong to). Before multi-path the lanes were always on different ifaces so such support was not needed.
Use normal double-linked list with dummy head element for arbiter schedule queue, instead of circular list without dummy element. This allows removing the dispatched group from list head, re-inserting it to list tail if needed, but also adding/removing other groups to that list at any time.
Also, much of arbiter code related to group add/remove can be simplified.
> UCS/ARBITER: Support scheduling another group from dispatch callback

- test/gtest/ucs/test_async.cc
Drain pipe before test
Fixes #4838 
pipe behavior changes in upstream 5.5
torvalds/linux@1b6b26a
cherry-pick the fix from https://github.com/openucx/ucx/pull/4819
> TEST/ASYNC: Drain pipe before test - v1.8.x

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_iface.c
1. Disable PUT Zcopy by default
2. Set `max_num_eps` to `256`
1. PUT Zcopy is not optimal on collectives (need to evaluate performance)
2. Avoid using TCP for RNDV when DC is not available
> UCT/TCP: Add knob to disable PUT Zcopy by default, fix scalability issue - v1.8.x

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_iface.c
- test/apps/test_ucx_tls.py
- test/gtest/ucp/test_ucp_wireup.cc
1. Scalability fixes for TCP - don't select RC over UD for RNDV lanes even considering TCP support RNDV
2. Disable PUT Zcopy by default
1. RNDV over AM/UD has to be used since TCP isn't scalable enough as RC
2. Collectives and NCCL are not good enough with PUT Zcopy
1. Set `UCX_TCP_MAX_NUM_EPS` to 256 + add tests for fallback
2. Add `UCX_TCP_PUT_ENABLE` (`'y'` by default) to enable/disable PUT Zcopy in TCP
> UCT/TCP: Scalability fixes for TCP and add knob to disable PUT Zcopy

- src/ucp/core/ucp_worker.c
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- test/gtest/ucp/test_ucp_tag_offload.cc
Avoid creating "expensive" tag offload infrastructure (XRQ, large staging buffers) if no tag feature needed 
Better memory consumption/scalability
> UCP/UCT/GTEST: Do not enable offload if no tag feature requested

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.inl
- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/stream/stream_send.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/tag/rndv.c
- src/ucp/tag/tag_send.c
- src/ucp/wireup/select.c
- test/gtest/ucp/test_ucp_am.cc
Add support for multi-lane in UCP AM API (disabled by default)
May improve performance if `UCX_MAX_EAGER_LANES=<num_devices>` set, where, e.g., `<num_devices>` is a number of active IB devices
1. Combine TAG and AM to the common `msg_proto` structure in UCP request structure to share `message_id` and `am_bw_index` fields.
2. Select for AM BW lanes during Wire-up procedure if user requested UCP AM API
3. Minor find-replaces changes
> UCP/AM: Add support for multi-lane

- src/uct/ib/rc/accel/rc_mlx5_common.c
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- test/gtest/ucp/test_ucp_tag.cc
- test/gtest/uct/test_tag.cc
Use MP XRQ with 8 strides by default for tag offload
- better memory consumption 
- better performance in tag offload unexpected flow
> UCT/RC/DC: Use 8 strides by default for tag offload

- src/ucp/core/ucp_mm.c
- src/ucp/core/ucp_thread.h
Allways do locking on ucp_context mt_lock even if ucx was build without `--enable-mt` flag.
Context locking is used in a slow path (mem reg, ucp_rkey_pack).  In applications, like SparkUCX it uses worker per thread, but context is shared to register memory. It causes deadlocks:
```
>>> bt
#0  0x00007ffff7bcb495 in pthread_spin_lock () from /usr/lib64/libpthread.so.0
#1  0x00007fe3c44e0fe6 in mlx5_poll_cq_1 () from /usr/lib64/libmlx5.so.1
#2  0x00007fe3c49557da in ibv_poll_cq (wc=0x7fe3cc75c8f0, num_entries=1, cq=<optimized out>) at /usr/include/infiniband/verbs.h:1458
#3  uct_ib_mlx5_exp_reg_indirect_mr (md=md@entry=0xd9e570, addr=0x7fe337052200, length=1036528, mem_reg=mem_reg@entry=0x7fe4c5ce0230, list_size=<optimized out>, create_flags=create_flags@entry=2, umr_type=umr_type@entry=0, …
```
> UCP/CORE: Always lock on ucp_context mt_lock.

- src/uct/Makefile.am
- src/uct/sm/scopy/base/scopy_ep.c
- src/uct/sm/scopy/base/scopy_ep.h
- src/uct/sm/scopy/base/scopy_iface.c
- src/uct/sm/scopy/base/scopy_iface.h
Introduce SCOPY iface and EP
It is the common class for CMA and KNEM that will be used to implement doing PUT/GET Zcopy from iface's progress in the further PRs
Use common UCS class infrastructure to implement new classes for SCOPY iface and EP
> UCT/SM: Introduce SCOPY iface and EP

- src/ucp/api/ucp.h
- fixed typos
- wrong words are used
- fixed comments
> UCP/TYPO: fixed typos in UCP_STREAM_RECV_FLAG_WAITALL description

- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/main/native/jucx_common_def.h
- src/tools/info/type_info.c
- src/ucm/event/event.c
- src/ucm/malloc/malloc_hook.c
- src/ucp/core/ucp_thread.h
- src/ucs/async/async.h
- src/ucs/async/thread.c
- src/ucs/async/thread.h
- src/ucs/datastruct/callbackq.c
- src/ucs/debug/debug.c
- src/ucs/memory/rcache.c
- src/ucs/memory/rcache_int.h
- src/ucs/time/timerq.c
- src/ucs/time/timerq.h
- src/ucs/type/spinlock.h
- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_device.h
- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
- src/uct/ib/mlx5/ib_mlx5.h
- src/uct/sm/mm/xpmem/mm_xpmem.c
- src/uct/ugni/base/ugni_def.h
- src/uct/ugni/base/ugni_types.h
- src/uct/ugni/smsg/ugni_smsg_iface.c
- src/uct/ugni/smsg/ugni_smsg_iface.h
- test/gtest/ucs/test_sys.cc
This patch adds support for the shared-memory alternative of the pthread spinlock already in UCS.
This was done to enable implementations with inter-process synchronization requirements. Specifically, this patch was introduced to support UCG - Group-based collective operations.
In addition to the existing "intra-process" spinlock (API and functionality unchanged), we add a "pure" spinlock (smaller footprint unless it's a "debug-build") - which can be used in shared-memory segments to synchronize between multiple processes (in accordance with pthread documentation).
> UCS: support for a shared-memory spinlock

- bindings/java/src/main/native/jucx_common_def.cc
Port #4801  to 1.8
Annoying message in SparkUCX logs.
> JUCX: port to 1.8 do not log on canceled requests + decrease log level.

- src/uct/ib/configure.m4
- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Note: to detect PCI atomics DEVX still need to be enabled in FW
> UCT/IB/MLX5: Check PCI atomics when DEVX disabled

- .gitmodules
- LICENSE
- Makefile.am
- autogen.sh
- config/m4/ucg.m4
- configure.ac
- contrib/upload_docs.sh
- src/ucp/core/ucp_ep.inl
This patch extends UCX to include experimental support for UCG - Group-based collective operations.
Collective operations have been decided to be an important feature to explore, and this provides the necessary framework to do so. This code can start driving the discussion on how best to integrate collective operations into UCX.
In order to avoid placing experimental code inside the UCX repository, it has been proposed to implement support using git-submodules (UCG resides on a different repository), with minimal changes to the UCX code base.
> UCG/UCP: added collective operations support via git-submodule

- buildlib/azure-pipelines-release.yml
- buildlib/azure-pipelines.yml
- buildlib/tests.yml
Do clean checkout in AZP.
Avoid issues related to unrelated sources.
Run git clean -ffdx && git reset --hard HEAD before fetching (according to the Azuze doc). Details on this step: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout
> AZP: clean checkout

- src/ucp/api/ucp.h
- src/uct/api/uct_def.h
Add functionality to query the connection request on the server side.
The connection request may hold values that are interesting to the user. For example, the address of the client that sent the request to connect to the server.
Add a function to query the connection request on the server side and a struct to hold its attributes, which will return to the user.
> API/UCP: Allow querying the connection request fields on the server side

- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Remove "unused" flag from DevX ODP check
The function is used in `uct_ib_mlx5_devx_md_open`
Remove `UCS_F_MAYBE_UNUSED`
> UCT/IB/MLX5: Remove unused flag from DevX ODP check

- src/ucp/wireup/select.c
Fix buffer overflow read in select logic
Fixes #4868 
Add missing entry in the `ucp_wireup_md_flags` array for `UCT_MD_FLAG_RKEY_PTR` flag that's used to search for RKEY PTR lane
> UCP/WIREUP: Fix buffer overflow read in select logic

- src/ucp/rma/amo_basic.c
Fix stack buffer overflow in case of CSWAP32
Fixes #4872
Cast 64-bit value to 32-bit in order to dereference only valid buffer
> UCP/AMO: Fix stack buffer overflow in case of CSWAP32

- src/uct/sm/base/sm_iface.h
- src/uct/sm/scopy/cma/cma_ep.c
- src/uct/sm/scopy/cma/cma_ep.h
- src/uct/sm/scopy/cma/cma_iface.c
- src/uct/sm/scopy/cma/cma_iface.h
- src/uct/sm/scopy/knem/knem_ep.c
- src/uct/sm/scopy/knem/knem_ep.h
- src/uct/sm/scopy/knem/knem_iface.c
- src/uct/sm/scopy/knem/knem_iface.h
Introduce CMA/KNEM inheritance from SCOPY
This is needed to move the common code from CMA/KNEM to SCOPY
Call super init functions from SCOPY when creating CMA/KNEM's IFACE and EP objects
> UCT/SM/SCOPY: Introduce CMA/KNEM inheritance from SCOPY

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/dc/dc_mlx5_devx.c
- src/uct/ib/mlx5/dv/ib_mlx5_dv.c
- src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
- src/uct/ib/mlx5/ib_mlx5.c
- src/uct/ib/mlx5/ib_mlx5.h
- src/uct/ib/rc/accel/rc_mlx5_common.c
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/ib/rc/accel/rc_mlx5_devx.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_iface.c
Enable DevX RMP support for RC/DC SRQ for non-HW TM case
RMP supports "cyclic" WQ type that's significantly better than "list" WQ type
1. Added in/out bits for RMP DevX object creation.
2. Create DevX RMP if it's supported and requested in the same way as we creating XRQ for HW TM case.
3. Use DevX SRQ number instead of de-referencing Verbs SRQ (that's `NULL` in case of DevX SRQ was created) when creating DCT.
> UCT/IB: Enable DevX RMP for RC/DC SRQ for non-HW TM

- src/uct/tcp/tcp_ep.c
Fix use after free issue
Fixes #4700 
Do a comparison for UCT EP length after handling receive to avoid "use after free"
> UCT/TCP: Fix use after free issue

- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- test/gtest/uct/ib/test_rc.cc
Block RMA and AMO operations if no RDMA_READ credits available
With RC/DC transport, fence operations relies on QP ordering and is implemented as no-op
> UCT/RC: Block RMA and AMO if no read credits

- config/m4/compiler.m4
- config/m4/sysdep.m4
- config/m4/ucs.m4
- src/tools/perf/lib/configure.m4
- test/examples/ucp_client_server.c
- test/examples/uct_hello_world.c
- test/examples/ucx_hello_world.h
- test/gtest/configure.m4
+Wno-missing-field-initializers
+Wno-unused-parameter
+Wno-unused-label
+Wno-long-long
+Wno-endif-labels
+Wno-sign-compare
+Wno-multichar
+Wno-deprecated-declarations
+Winvalid-pch
+Wno-pointer-sign
+Wvariadic-macros
+Wno-format-zero-length
+Werror-implicit-function-declaration
flags are added to build only in case if compiler supports it
> BUILD/FLAGS: added strict compilation flags:

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_mm.h
- src/ucp/core/ucp_worker.c
- src/ucp/rma/rma_send.c
- src/uct/base/uct_md.c
- Calculate GET Zcopy thresh for RMA lanes
- Increase RCACHE_OVERHEAD parameter value to have more suitable value
- Improve performance for [2KB .. 8KB] where better to use GET Zcopy instead of GET Bcopy
- Fix limits that are set for GET protocol, w/o this fix we use GET Zcopy from 547 bytes, but should start from 1KB
- Added formula for GET Zcopy calculation
- `90ns -> `180ns` for "RCACHE_OVERHEAD" parameter
> UCP/CORE: Calculate GET Zcopy thresh for RMA lanes

- src/ucp/wireup/address.c
- test/gtest/ucp/test_ucp_wireup.cc
Fix passing multiple endpoint addresses in unified mode
Instead of assuming unified mode will always have one endpoint address, add LAST bit to lane_index to allow passing multiple endpoint addresses.
> UCP/ADDRESS/TEST: Fix endpoint address pack in unified mode

- test/gtest/ucs/test_time.cc
time_calc fails on NXP Arm platform. Make the test less sensitive.
> GTEST: Reducing timer test sensitivity

- config/m4/compiler.m4
Fixing #4884. Autoconf does not fail if C++ compiler is not present.
See more here:
http://gnu-autoconf.7623.n7.nabble.com/AC-PROG-CXX-should-have-a-way-to-not-fall-back-to-g-td21034.html
> CONFIG: Fixing broken detection of C++ compiler

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_ep.inl
- src/ucp/tag/rndv.c
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
Support RoCE LAG and IB multi-path
Create multiple UCT endpoints / lanes on same local-remote devices
> UCP/WIREUP: Use device multi-path to create multiple UCT lanes

- src/ucp/core/ucp_request.inl
- src/ucp/core/ucp_worker.c
- src/ucp/stream/stream_recv.c
- test/gtest/ucp/test_ucp_stream.cc
- test/gtest/ucp/ucp_test.cc
complete stream recv requests on ep destroy
app can be blocked on stream recv request if ep is failed and/or closed
> UCP/STREAM: complete recv requests on ep destroy

- src/ucs/Makefile.am
- src/ucs/sys/iovec.c
- src/ucs/sys/iovec.h
- src/ucs/sys/iovec.inl
- src/ucs/sys/sock.c
- src/uct/Makefile.am
- src/uct/base/uct_iface.h
- src/uct/base/uct_iov.inl
- src/uct/cuda/cuda_copy/cuda_copy_ep.c
- src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/rc/accel/rc_mlx5.inl
- src/uct/rocm/copy/rocm_copy_ep.c
- src/uct/rocm/ipc/rocm_ipc_ep.c
- src/uct/sm/scopy/cma/cma_ep.c
- src/uct/sm/scopy/knem/knem_ep.c
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
- test/gtest/Makefile.am
- test/gtest/ucs/test_iov.cc
Updates for UCT and UCS/SYS IOV functions for further usage by SM/SCOPY.
This will be used by SM/SCOPY TLs to fill system IOVEC (CMA) or KNEM IOVEC (KNEM) by elements from UCT IOV before sending a segment of the data.
Implemented common macro to convert one IOV type to another IOV type.
> UCT/UCS/IOV: Updates for IOV functions for further usage by SM/SCOPY

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- src/ucp/wireup/wireup_cm.c
fix TL lanes selection according to device
Server did take into account CM device during lanes configuration, so if connect request is arrived on slower device, wireup mechanism could select faster one according to scores.
add tl_bitmask where it was missed
> UCP/WIREUP/CM: fix TL lanes selection according to device

- src/uct/tcp/sockcm/sockcm_def.h
Increase sockcm's private data length.
The current private data length may be too narrow for machines with many interfaces, such as a DGX-2. Refer to https://github.com/openucx/ucx/issues/4842 for additional details.
> Backport: UCT/TCP/SOCKCM: UCT_SOCKCM_PRIV_DATA_LEN to 2048

- src/uct/tcp/sockcm/sockcm_def.h
Increase sockcm's private data length.
The current private data length may be too narrow for machines with many interfaces, such as a DGX-2. Refer to https://github.com/openucx/ucx/issues/4842 for additional details.
Fixes #4842 #4557
> UCT/TCP/SOCKCM: UCT_SOCKCM_PRIV_DATA_LEN to 2048

- buildlib/azure-pipelines-release.yml
Port to 1.8 #4909
To have `libjucx.so` in 1.8 release jar.
> JUCX: build ucx to include libjucx.so into release jar - v1.8

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- src/ucp/wireup/wireup_cm.c
#4903 backport to v1.8.x 
requested by @amaslenn https://github.com/openucx/ucx/pull/4903#issuecomment-602199848
cherry-picked
> UCP/WIREUP/CM: fix TL lanes selection according to device, backport to v1.8.x

- config/m4/ucs.m4
- src/ucs/debug/debug.c
- enables support of new API provided by binutils 2.34+
fixes https://github.com/openucx/ucx/issues/4894
> BUILD/DEBUG: added new API of binutils

- buildlib/azure-pipelines-release.yml
`jucx-1.8.0-rc1.jar` doesn't have `libjucx.so` in the jar, because no ucx was build before in pipeline
To include `libjucx.so` in jar as was expected. master pipelines has build step before jucx-publish
> JUCX: build ucx to include libjucx.so into release jar.

- test/gtest/uct/ib/test_rc.cc
- test/gtest/uct/test_tag.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
Create tag offload capable entity for iface attrs testing
Tag offload is not initialized if no eager and rendezvous callbacks passed to the iface create function, therefore its max_iov caps would not be tested
> UCT/GTEST: Enable tag offload for iface_attrs testing

- src/ucs/sys/iovec.inl
- src/uct/base/uct_iov.inl
- src/uct/sm/scopy/base/scopy_ep.c
- src/uct/sm/scopy/base/scopy_ep.h
- src/uct/sm/scopy/base/scopy_iface.c
- src/uct/sm/scopy/base/scopy_iface.h
- src/uct/sm/scopy/cma/cma_ep.c
- src/uct/sm/scopy/cma/cma_ep.h
- src/uct/sm/scopy/cma/cma_iface.c
- src/uct/sm/scopy/knem/knem_ep.c
- src/uct/sm/scopy/knem/knem_ep.h
- src/uct/sm/scopy/knem/knem_iface.c
Implement doing GET/PUT from IFACE progress (pseudo-non-blocking PUT and GET)
Reduces duplication code between CMA and KNEM by moving their common code to SCOPY
1. Add `uct_scopy_ep_tx_func_t` operation in `uct_scopy_iface_ops_t` that should be defined by CMA and KNEM.
2. Implement PUT/GET Zcopy, IFACE progress, IFACE/EP flush on SCOPY layer.
3. SCOPY PUT/GET Zcopy just schedules TX operation that will be performed from IFACE progress. It calls CMA/KNEM's `uct_scopy_ep_tx_func_t` function to transfer the user's data by segments. The size of the segments is configured by means of `UCX_SCOPY_SEG_SIZE` parameter.
> UCT/SM/SCOPY: Implement doing GET/PUT from IFACE progress

- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_worker.c
Minor code cleanups in worker iface:
1. Align `ucp_tl_iface_latency()` and `ucp_tl_iface_bandwidth()` to accept similiar arguments.
2. Remove excessive functions.
3. Reorganized code to remove forward-declaration.
Make code more clear
1. Align `ucp_tl_iface_latency()` and `ucp_tl_iface_bandwidth()` to make them similar. (can't use `uct_iface_attr_t*` as the second parameter in both function, since `ucp_tl_iface_bandwidth()` requires getting `uct_ppn_bandwidth_t*` w/o iface_attr in UCP/WIREUP/SELECT code).
2. Remove `ucp_worker_iface_latency()` and replace it with `ucp_tl_iface_latency()` as they do the same work.
3. Remove forward-declaratio n`ucp_worker_iface_check_events()` and make it `static`, move some function (`ucp_worker_iface_deactivate()`, `ucp_worker_iface_progress_ep()`, …
> UCP/CORE: Minor code cleanups in worker iface

- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_inl.h
- src/uct/ib/ud/verbs/ud_verbs.c
preparation for zero-copy resend, to fix handling of GPU memory: we should not try to copy user data to resend skb.
> UCT/UD/MLX5: Refactor and extract common post_send code

- .gitmodules
- autogen.sh
Make UCX track UCG's master branch (rather than a specific commit id).
Originally UCG's submodule was set to track a specific commit id, in order to keep UCX and UCG versions "in sync". This means that if I make a change in UCX and UCG - I first merge into UCG, then push into UCX a PR for the change + the corresponding UCG commit id. This way - UCX-UCG version compatibility is always kept. The only reason spinlocks were the exception is that spinlocks were merged during UCG being reviewed.
Since UCG is a temporary measure - I'll make it track UCG master. We can always revisit this decision in the future.
> UCG: track master instead of a specific commit id

- src/uct/sm/mm/base/mm_ep.c
- src/uct/sm/mm/base/mm_iface.c
- src/uct/sm/mm/base/mm_iface.h
Implemented the following optimizations for UCT/SM/MM/BASE:
- poll multi FIFO elements in a single iface progress call. The number of polled operations is controlled by `UCT_MM_FIFO_MAX_POLL` and dynamically adjusted every `UCT_MM_FIFO_WINDOW_UPDATE_MAX_OTER` successful reads - it adjusted to `MIN("average read count" value + 1; fifo_max_poll)`
- Optimizations for FIFO polling procedure
Dramatically improves performance for UCT MM. The following improvements can be seen:
* osu_bw:
bytes | gain, %
-- | --
1 | 22.94%
2 | 22.34%
4 | 21.21%
8 | 20.03%
16 | 20.60%
32 | 18.87%
64 | 17.95%
128 | 10.27%
256 | 31.41%
512 | 13.56%
1024 | 10.37%
2048 | 0.25%
4096 | 1.64%
8192 | 0.39%
16384 | 10.58%
32768 | 3.54%
65536 | 2.80%
131072 | 2.42%
262144 | 0.86%
524288 | -4.24%
1048576 | -2.84%
2097152 | …
> UCT/SM/MM: Poll multi FIFO elements in a single iface progress + optimizations

- src/ucs/type/class.h
This is a small fix for GCC v9.2, where the following error occurs due to a recent change:
````
/home/hpc/huawei-ucx/src/ucs/type/class.h:97:13: error: declaration of '_init_count' shadows a parameter [-Werror=shadow]
97 |         int _init_count = 1; \
|             ^~~~~~~~~~~
/home/hpc/huawei-ucx/src/ucs/type/class.h:152:23: note: in expansion of macro 'UCS_CLASS_INIT'
152 |             _status = UCS_CLASS_INIT(_type, obj, ## __VA_ARGS__); \
|                       ^~~~~~~~~~~~~~
/home/hpc/huawei-ucx/src/ucs/type/class.h:143:5: note: in expansion of macro '_UCS_CLASS_NEW'
143 |     _UCS_CLASS_NEW (_type, _obj, ## __VA_ARGS__)
|     ^~~~~~~~~~~~~~
sm/mm/coll/mm_coll_ep.c:204:14: note: in expansion of macro 'UCS_CLASS_NEW'
204 |     status = UCS_CLASS_NEW(uct_mm_ep_t, &self->tx, …
```
> UCS: fix "shadows a parameter" error on GCC v9.2

- contrib/test_jenkins.sh
1. Set a number of parallel jobs for the Coverity analyzer.
2. Check pinned CPU threads and use them for a number of parallel jobs.
1. Avoid using threads not pinned for this particular process.
2. Better utilize Azure agent settings, this can help with scaling multiple agents on a host.
> AZP: use pinned CPU threads for CI

- src/ucp/tag/probe.c
Add profiling for `ucp_tag_probe_nb`
Helps in customer apps profiling (working with one, which spends ~70% of time in probe)
> UCP/TAG: Add profile for tag_probe

- src/tools/info/ucx_info.c
- src/ucp/api/ucp.h
- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_worker.c
- src/ucs/config/global_opts.c
- src/ucs/config/parser.c
- src/ucs/config/parser.h
- src/ucs/config/ucm_opts.c
- src/ucs/sys/compiler.h
- src/ucs/sys/compiler_def.h
- src/uct/base/uct_component.c
- src/uct/ib/base/ib_iface.c
- src/uct/tcp/tcp_ep.c
- test/apps/test_dlopen_cfg_print.c
- test/gtest/common/main.cc
- test/gtest/common/test_helpers.cc
- test/gtest/ucs/test_config.cc
Environment variable prefix order is changes in order to fix false warning about unused variables.
UCS parser functionality extended to support environment variables that starts with any prefix.
Fixes false warning about unused variables, for instance
* before changes
```shell
$mpirun -np 2 -x UCX_LOG=info  -x UCX_OSHMEM_NET_DEVICES=dev -x UCX_OSHMEM_LALALA=1 -mca pml ucx $HPCX_OSHMEM_DIR/tests/osu-micro-benchmarks-5.3.2/osu_oshm_barrier
[1584627303.072203] [jazz09:147733:0]         parser.c:1611 UCX  WARN  unused env variables: UCX_LOG, UCX_OSHMEM_NET_DEVICES,... (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
[1584627303.072171] [jazz09:147732:0]         parser.c:1611 UCX  WARN  unused env variables: UCX_LOG, UCX_OSHMEM_NET_DEVICES,... (set UCX_WARN_UNUSED_ENV_VARS=n to …
```
> UCS/PARSER: change environment prefix order

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/tag/rndv.c
Ensure that that current length is over minimum GET Zcopy
```
$nnodes=1; ppn=2; mpirun -np $((nnodex * ppn)) -x UCX_LOG_LEVEL=info -x UCX_RNDV_THRESH=0 --bind-to core -map-by ppr:$ppn:node -mca coll_hcoll_enable 0 osu_bw
[1584697553.078959] [hpc-test-node-gpu02:8958 :0]     ucp_worker.c:1555 UCX  INFO  ep_cfg[1]: tag(cuda_copy/cuda); rma(cuda_copy/cuda);
[1584697553.079046] [hpc-test-node-gpu02:8958 :0]     ucp_worker.c:1555 UCX  INFO  ep_cfg[2]: rma(rocm_gdr/rocm_gdr);
[1584697553.234009] [hpc-test-node-gpu02:8957 :0]     ucp_worker.c:1555 UCX  INFO  ep_cfg[1]: tag(cuda_copy/cuda); rma(cuda_copy/cuda);
[1584697553.234173] [hpc-test-node-gpu02:8957 :0]     ucp_worker.c:1555 UCX  INFO  ep_cfg[2]: rma(rocm_gdr/rocm_gdr);
[1584697553.236379] [hpc-test-node-gpu02:8958 :0] …
```
> UCP/TAG/RNDV: Ensure that the current length is over minimum GET Zcopy

- test/gtest/uct/ib/test_ud.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
Fix logic that leads to the double destroy of the same UCT EP object
It is wrong to destroy UCT EP objects twice
1. Introduce wrapper for `ucs::handle::revoke()` operation in `uct_test::entity` - `uct_test::entity::revoke_ep(unsigned index)` that revokes EP with `index` for a given entity.
2. Fix double destroy of the same UCT EP object in GTEST/UCT/IB:
- `test_ud.ep_destroy_flush`: call `revoke_ep(0)` at the end of the testing, since EP handle is used in `validate_flush()`
- `test_ud.ep_destroy_passive`: call `revoke_ep(0)` at the end of the testing, since EP handle is used in `validate_flush()`
- `test_ud.ep_destroy_creq`: Destroy EP by calling `destroy_ep(0)` as it is not used anymore
> GTEST/UCT/IB: Don't destroy EP objects twice

- NEWS
> NEWS: News file update for RC2

- contrib/test_jenkins.sh
- due to some reasons armclang failed to build apps,
in this case just exclude it from processing
> JENKINS/ARMCLANG: added evaluation for armclang works

- src/uct/sm/scopy/base/scopy_ep.c
- src/uct/sm/scopy/base/scopy_iface.c
- src/uct/sm/scopy/base/scopy_iface.h
Introduce TX quota
It is used by UCT/SM/SCOPY TLs to send only one TX segment (by default) during `uct_iface_progress()` call. This makes `uct_iface_progress()` more light-weight and UCT applications (e.g. UCP) can progress other UCT ifaces and not be blocked while there are some data to read on this iface.
If reaches TX quota, returns `UCS_ARBITER_CB_RESULT_STOP` from Arbiter dispatch callback
> UCT/SM/SCOPY: Introduce TX quota

- src/ucp/api/ucp.h
- src/ucp/api/ucp_def.h
- src/ucp/core/ucp_request.c
- src/ucp/rma/rma_send.c
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
Add new request API to UCP: uct_tag_[send|recv]_nbx
Full implementation
UCX: #4703
OMPI PML/UCX: https://github.com/open-mpi/ompi/pull/7349
Extend UCP request API to support the following:
- User-defined context which can be set on a request before it's returned
from a send/recv function. This will eliminate possible race conditions
of setting request context and completing the request from another
thread.
- Unite send_nb/send_nbr functionality to single API call without adding
overhead for fast path (immediate completion)
- Resolve the weirdness that ucp_tag_recv_nb can call the completion
callback internally before returning the request to user
- Allow using pre-allocated request (e.g tag_send_nbr) - with callback
- Allow additional request flags in the future without adding extra …
> UCP/REQUEST_API: new request based API

- src/ucs/Makefile.am
- src/ucs/memory/memory_type.h
- src/uct/api/uct.h
- src/uct/base/uct_md.c
- src/uct/base/uct_md.h
- test/gtest/Makefile.am
Add uct_md_mem_query function. Revised https://github.com/openucx/ucx/pull/4943 based on @yosefe feedback
Today uct_memory_detect_md returns just the memory type associated with the pointer passed to it. We need a more generic return type to capture both memory type and detect the system device type associated with buffer. This allows us to make topology-aware decisions in protocols to specific to memory type and the device backing the buffer.
> UCT: Introduce uct_md_attr_t and uct_md_mem_query

- src/ucp/core/ucp_worker.h
- fixed typos in macro definition in ucp_worker.h
> TYPO/MACRO: fixed typos in worker macro

- src/uct/sm/mm/xpmem/configure.m4
_Add xpmem lib file verifying in config._ 
_When the xpmem header file exists and lib file is absent, a build error will be caused._
_Verify both header and lib files to fix this issue._
> CONFIG: Add xpmem lib verifying.

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/tag/rndv.c
Implement pseudo-non-blocking mode for RKEY_PTR
Need to do RKEY_PTR data transfer from the progress rather than completing it in place when RT is received to avoid be blocking doing long memory copy that is harmful for applications
1. When RTS is received and RKEY_PTR lane is supported, save needed information (remote request ptr, RKEY, pointer to receiver request, local ptr to remote data, receiver buffer and its length) and insert RNDV req to the queue of the REKY_PTR requests and register worker CBQ handler for the current RKEY_PTR CBQ ID.
2. Call `ucp_request_recv_data_unpack()` to do memory copy for `MIN(512 KBytes (by default); remaining part of the data)`.
3. If done, check the queue of submitted RKEY_PTR request, if it is empty, remove CBQ handler from worker CBQ.
> UCP/TAG: Implement pseudo-non-blocking mode for RKEY_PTR

- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Return correct error code if MD open failed
```
[2020-04-05T16:14:40.624Z] [1586103280.408573] [hpc-arm-cavium-jenkins:11236:0]   ib_mlx5dv_md.c:718  UCX  ERROR mlx5dv_devx_umem_reg() zero umem failed: Cannot allocate memory
[2020-04-05T16:14:40.624Z] [1586103280.409119] [hpc-arm-cavium-jenkins:11238:0]   ib_mlx5dv_md.c:718  UCX  ERROR mlx5dv_devx_umem_reg() zero umem failed: Cannot allocate memory
[2020-04-05T16:14:40.624Z] [hpc-arm-cavium-jenkins:11238:0:11238] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x318)
[2020-04-05T16:14:40.624Z] [hpc-arm-cavium-jenkins:11236:0:11236] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x318)
[2020-04-05T16:14:40.885Z] 
[2020-04-05T16:14:40.885Z] …
```
> UCT/IB/MLX5/DV: Return correct error code if MD open failed

- buildlib/azure-pipelines-pr.yml
- buildlib/azure-pipelines-release.yml
- buildlib/azure-pipelines.yml
Split Azure pipelines into three independent parts: PR, merge (and direct pushes) and release (tag creation).
Reduce the load on CI by avoiding duplicating runs for PR and merge (we test on merge commit anyway).
> AZP: split pipelines into PR/merge/release

- src/ucs/datastruct/arbiter.c
- src/ucs/datastruct/arbiter.h
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/dc/dc_mlx5_ep.h
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_inl.h
- src/uct/sm/mm/base/mm_ep.c
- src/uct/sm/mm/base/mm_ep.h
- src/uct/sm/scopy/base/scopy_ep.c
- src/uct/sm/scopy/base/scopy_ep.h
- src/uct/ugni/base/ugni_ep.c
- src/uct/ugni/base/ugni_ep.h
- src/uct/ugni/udt/ugni_udt_ep.c
- src/uct/ugni/udt/ugni_udt_ep.h
- test/gtest/ucs/test_arbiter.cc
Preparation for supporting arbiter recursive reschedule, to address #4267 
1. Make ucs_arbiter_group_head_reset() and ucs_arbiter_group_head_is_scheduled() private
1. Remove ucs_arbiter_elem_group() , instead pass group to arbiter dispatch function
1. Remove ucs_arbiter_elem_is_last() and replace its usage by ucs_arbiter_elem_is_only()
> UCS/ARBITER/UCT: Make some arbiter APIs private

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.h
- src/ucp/proto/proto_am.inl
- src/ucp/rma/flush.c
- src/ucp/rma/rma_sw.c
- src/ucp/stream/stream_send.c
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/tag_recv.c
- src/ucp/wireup/select.c
- src/uct/base/uct_iface.c
- test/gtest/common/test_helpers.cc
- test/gtest/common/test_helpers.h
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/uct/test_peer_failure.cc
Fix several protocols to handle transition from wireup endpoint to real endpoint, as it happens during client-server connection establishment
1. Fix default max_bcopy for tag protocol
1. Fix flush to handle case of more lanes added during flush progress
1. Fix status check from in am_bcopy_multi protocol
1. Recalculate send lane in rma_sw protocol progress
1. Allow EAGER_FIRST with one packet (in case protocol was started as eager multi and eventually sent only one packet)
1. Allow RMA/AMO emulation with error handling and CM
1. Fix failed endpoint pending_add return value - it should force retrying send operation
1. Add unit test with multiple cases
> UCP/TEST: Fixing protocols initialization for stub endpoints

- buildlib/tests.yml
Some files can be created as read-only (probably in make dist) and it
prevents Agent from cleaning the workspace.
Make AZP more reliable and robust.
> AZP: fix permissions for workspace before cleaning it

- test/apps/iodemo/ucx_wrapper.cc
bugfix on error handling flow
if sender gets EP error and closes/deletes the connection,
stop sending throwing exception
> TEST/APPS/IO_DEMO: fix null dereference

- src/ucp/rma/flush.c
- src/ucp/wireup/wireup_cm.c
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_wireup.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/ucp/ucp_test.h
fix double call to disconnect CM lane
if ucp_ep_cm_disconnect_flushed_cb completed with error, the ep
is in error state and CM lane was disconnected by
ucp_worker_set_ep_failed
> UCP/EP/CM: fix disconnect_flushed_cb err case

- src/uct/sm/mm/xpmem/configure.m4
https://github.com/openucx/ucx/pull/4970 broke the xpmem detection
incorrect AC_CHECK_LIB macro usage
save/restore LDFLAGS/CPPFLAGS
> CONFIG: fixes xpmem m4 detection

- bindings/java/pom.xml.in
JDK9+ produces incompatible bytecode with JDK8. When compiling on JDK9+ and running on JDK8 there's a:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
at org.openucx.jucx.ucp.UcpMemory.getRemoteKeyBuffer(UcpMemory.java:71)
at org.openucx.jucx.examples.UcxReadBWBenchmarkSender.main(UcxReadBWBenchmarkSender.java:39)
```
More info here: https://github.com/eclipse/jetty.project/issues/3244
The solution is to whether add `<release>` property for JDK9+ in maven (what is implemented) or to cast ByteBuffer to Buffer.
Add profile that automatically activates on JDK9+ and adds `<release>` property that would produce jdk8 comparable bytecode. The same approach used in other projects:, e.g: …
> JUCX: fix NoSuchMethodError: ByteBuffer.clear when compiling on JDK9+.

- bindings/java/src/main/native/jucx_common_def.cc
On non-English locales JUCX apps logs parser errors:
```
[1586354539.262029] [node70-host:26959:0]         parser.c:930  UCX  ERROR Invalid value for MEM_REG_GROWTH: '0.06ns'. Expected: time value: <number>[s|us|ms|ns]
[1586354539.262038] [node70-host:26959:0]         uct_md.c:269  UCX  ERROR Failed to read MD config
```
Steps to reproduce:
```
LANG=de_DE.UTF-8  java -cp lib/jucx-1.9.0.jar:lib/ org.openucx.jucx.examples.UcxReadBWBenchmarkReceiver s=...
```
To disable annoying error
> JUCX: set locale to fix parser errors on non english locales.

- src/tools/perf/api/libperf.h
- src/tools/perf/lib/libperf.c
- src/ucp/wireup/wireup_ep.c
Use UCT TLs+Device ARG/FMT helper macros in UCP and LIBPERF code
Reduce code duplication
1. In UCP - use `UCT_TL_RESOURCE_DESC_ARG`
2. In LIBPERF: - introduce `UCT_PERF_TEST_PARAMS_FMT` and `UCT_PERF_TEST_PARAMS_ARG` and use them to reduce code duplication
> LIBPERF/UCP: Use UCT TLs+Device ARG/FMT helper macros

- src/uct/ib/ud/base/ud_ep.c
Fix #5009 
Fix #4987
Seems the queue iterator bug was there from day1, and triggered by recent changes in resend logic (before these changes seems `*ep->tx.window.ptail` was NULL by "luck")
> UCT/UD: Fix multiple issues in resend

- src/uct/ib/dc/dc_mlx5_ep.h
- src/uct/ib/rc/base/rc_ep.c
- test/gtest/uct/ib/test_dc.cc
- test/gtest/uct/ib/test_rc.cc
Fix 2 bugs:
1) Gracefully purge get_* operations (and release taken rdma read resources) when active ep is closed
2) Do not try to access ep when putting dci of already closed ep
> UCT/RC/DC: Fix bugs in get fc and dc error flow

- src/tools/info/type_info.c
- src/tools/perf/perftest.c
- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/base/ib_md.c
- src/uct/ib/base/ib_md.h
- src/uct/ib/base/ib_verbs.h
- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/mlx5/dv/ib_mlx5_dv.c
- src/uct/ib/mlx5/dv/ib_mlx5_dv.h
- src/uct/ib/mlx5/exp/ib_exp.h
- src/uct/ib/mlx5/exp/ib_exp_md.c
- src/uct/ib/mlx5/exp/ib_mlx5_hw.c
- src/uct/ib/mlx5/ib_mlx5.c
- src/uct/ib/mlx5/ib_mlx5.h
- src/uct/ib/mlx5/ib_mlx5.inl
- src/uct/ib/rc/accel/rc_mlx5_common.c
- test/gtest/uct/ib/test_ib_md.cc
- test/gtest/uct/ib/test_rc.cc
- test/gtest/uct/ib/test_ud.cc
- updated preprocessor directives for IB related transports
to better fit autotools tests
- this is part of enabling -Wundef build flag
> PREPROCESSOR: updated preprocessor directives for IB

- configure.ac
Adopt symbolic-ref for git version < 1.8
Fixes #5017
Use `sed 's/^.\{11\}//'` instead of `--short` for `git symbolic-ref` command to avoid wrong `SCM_BRANCH` for GIT versions where `--short` is not supported.
Also, added `--quiet` to fix the following case:
```
$ git checkout origin/master
$ git symbolic-ref HEAD
fatal: ref HEAD is not a symbolic ref
```
> CONFIG: Adopt symbolic-ref for git version < 1.8

- test/gtest/uct/test_pending.cc
bugfix in test
- fix pending status check
- increase timeout (use common)
happened in CI testing of https://github.com/openucx/ucx/pull/4967 
```
2020-04-15T15:15:59.3036327Z [ RUN      ] ud_verbs/test_uct_pending.pending_fairness/2 <ud_verbs/mlx5_3:1>
2020-04-15T15:15:59.8212617Z /scrap/azure/agent-05/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_pending.cc:83: Failure
2020-04-15T15:15:59.8213812Z Error: Device is busy
2020-04-15T15:15:59.8333655Z [  FAILED  ] ud_verbs/test_uct_pending.pending_fairness/2, where GetParam() = ud_verbs/mlx5_3:1 (530 ms)
```
full log here https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/5494/logs/111
> GEST/UCT: fix test_uct_pending.pending_fairness

- test/gtest/ucs/test_rcache.cc
Fix RCACHE test when running under ASan
Fixes #5039
Check if RCACHE supported due to UCM event notification mechanisms that are disabled if running under ASan (#5036).
And if it's not supported, skip the tests
> GTEST/UCS: Fix RCACHE test when running under ASan

- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- test/gtest/uct/ib/test_ib.cc
Fix IB address pack test
The failure is detected by ASan
Fixes #5031
0. Refactor address pack/unpack/size functions in IB
1. Use `uct_ib_address_pack()` instead of `uct_ib_iface_address_pack()` in order to use test GID
2. Use `uct_ib_address_size()` instead of `uct_ib_iface_address_size()` in order to correctly calculate IB address size for a given GID
> GTEST/UCT/IB: Fix IB address pack test

- src/uct/ib/rc/accel/rc_mlx5_common.c
fix rndv completions array name
> UCT/RC: Fix typo in rndv_comp array name

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/rma/flush.c
- src/ucp/rma/rma.inl
- src/ucp/stream/stream_send.c
- src/ucp/tag/tag_match.inl
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
- test/gtest/common/test_obj_size.cc
this is replacements for https://github.com/openucx/ucx/pull/4703
new request API proposal
Extend UCP request API to support the following:
- user-defined context which can be set on a request **before** it's returned from a send/recv function. This will eliminate possible race conditions of setting request context and completing the request from another thread. Fixes #4609 .
- unite send_nb/send_nbr functionality to single API call without adding overhead for fast path (immediate completion)
- resolve the weirdness that ucp_tag_recv_nb can call the completion callback internally before returning the request to user
- allow using pre-allocated request (e.g tag_send_nbr) - with callback
- method to support additional request flags in the future without adding extra parameter
set of …
> UCP: Implementation of new request API - refresh

- bindings/java/src/main/native/Makefile.am
- bindings/java/src/main/native/endpoint.cc
- buildlib/azure-pipelines-release.yml
- buildlib/azure-pipelines.yml
Build and release JUCX in centos7 container.
In a release pipeline we build libjucx binary. We have to build it on the lowest supported glibc and gcc. 
@abellina pointed out that there's an issue that a new gcc compiler that is used in fedora by default builds c++ (libjucx uses c++) in c++11 standard, that's not ABI compatible if you have libcpp98.
> AZP/JUCX: Build and release JUCX in centos7 container.

- bindings/java/pom.xml.in
Update google mirror site.
Google updated their mirror site: https://github.com/apache/spark/pull/27688
Happens that fails to build jucx, when can't resolve google address: https://kojipkgs.fedoraproject.org//work/tasks/2088/43682088/build.log_
> JUCX: update google mirror site.

- src/ucs/Makefile.am
- src/ucs/datastruct/hlist.h
- test/gtest/ucs/test_datatype.cc
preparation for keeping a list of in-flight SW requests on a UCP endpoint
> UCS/TEST: Add detached-head list data structure

- src/ucs/datastruct/ptr_array.c
- src/ucs/datastruct/ptr_array.h
- src/uct/ib/rc/accel/rc_mlx5_common.c
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/ud/base/ud_iface.c
- test/gtest/ucs/test_datatype.cc
- Improves foreach performance by 30-40% on sparse arrays.
- Adds test for foreach in gtest.
- Does not affect insert/remove performance.
- Improves foreach performance by 30-40% on sparse arrays by introducing an elements_counter
in the ptr_array structure.
- Adds test for foreach in gtest.
- Does not affect insert/remove performance.
In many cases, there is a need to improve foreach performance on ptr_arrays to reach higher performance of an algorithm implementation.
Adds an occupied elements counter and improves some of the code of insert and remove a little bit thus, making sure no need to iterate through a full sparse array size, just until the number of elements is reached (i.e. from index = 0 as long as n_occupied-- > 0 AND index < ptr_array->size).
Tested on: Tested on Intel(R) …
> UCS: Improve foreach performance of ptr-array and add ptr_array locked interface

- src/ucp/api/ucp.h
- src/ucp/tag/tag_send.c
- Rename "ZCOPY" flag to a more generic name
- Add separate flag for user_data, in case we would want to specify it without callback in the future
- added flag UCP_OP_ATTR_FIELD_USER_DATA
- added value flags to ucp_request_param_t
> UCP/API: added flags to op_attr

- config/m4/java.m4
Detect `JAVA_HOME` by readlink of javac
On systems there may be installed java jre (runtime environment) and jdk (compiler + jni headers) of different versions. If no `JAVA_HOME` is set we're trying to find one by running `readlnk java`. It could find `JAVA_HOME` of JRE not JDK.
#5071
> JUCX: detect javac to use for JAVA_HOME

- src/ucp/core/ucp_ep.c
if UCT returns error from ep create with conn request handle, the handle
is already released by UCT, need to free only UCP related part.
> UCP/EP/CM: fix error handling

- buildlib/azure-pipelines.yml
Fixes #5091
Fix docker container name for merge pipeline.
> AZP: use CentOS7 instead of Fedora for on-merge pipeline

- contrib/test_jenkins.sh
- test/gtest/ucp/ucp_test.h
Right now a number of threads in mt-tests is hardcoded to 4. On CI environment configure it via `OMP_NUM_THREADS`, so it basically will be the same.
Will add `test_ucp_mmap_mt` test to remove locks from ucp_mmap and ucp_rkey_pack. In SparkUCX some issues with parallel mmap reproduced on a high number of threads. Right now if run existing tests on jazz with all cores, timer issue would be easy reproduced: https://github.com/openucx/ucx/issues/5046#issuecomment-620594743
> GTEST: configure number of threads in mt-tests via OMP env.

- test/gtest/ucm/rocm_hooks.cc
Fix failing gtests for ROCm
```
Note: Google Test filter = *rocm*
[==========] Running 193 tests from 22 test cases.
[----------] 4 tests from rocm_hooks, where TypeParam =
[ RUN      ] rocm_hooks.test_hipMem_Alloc_Free <> <>
[       OK ] rocm_hooks.test_hipMem_Alloc_Free (28 ms)
[ RUN      ] rocm_hooks.test_hipMallocManaged <> <>
[       OK ] rocm_hooks.test_hipMallocManaged (0 ms)
[ RUN      ] rocm_hooks.test_hipMallocPitch <> <>
[       OK ] rocm_hooks.test_hipMallocPitch (0 ms)
[ RUN      ] rocm_hooks.test_hip_Malloc_Free <> <>
[       OK ] rocm_hooks.test_hip_Malloc_Free (1 ms)
[----------] 4 tests from rocm_hooks (29 ms total)
```
> GTEST/UCM/ROCM: fix hipMallocPitch and hipMallocManaged tests

- src/ucp/core/ucp_ep.c
- test/gtest/ucp/test_ucp_sockaddr.cc
Fix stub ep, so sync_send can resolve the destination ep, while  no cm events received yet
Fixing this
```
[jazz03:27931:0:27931]      wireup.c:1111 Assertion `lane != ((ucp_lane_index_t)-1)' failed
/labhome/mikhailb/wgit/ucx/src/ucp/wireup/wireup.c: [ ucp_wireup_connect_remote() ]
...
1108     ucs_trace("ep %p: connect lane %d to remote peer", ep, lane);
1109
1110     ucs_assert(lane != UCP_NULL_LANE);
==>  1111
1112     UCS_ASYNC_BLOCK(&ep->worker->async);
1113
1114     /* checking again, with lock held, if already connected or connection is
==== backtrace (tid:  27931) ====
0 0x00000000000591d8 ucs_debug_print_backtrace()  /labhome/mikhailb/wgit/ucx/src/ucs/debug/debug.c:656
1 0x000000000007dda0 ucp_wireup_connect_remote()  /labhome/mikhailb/wgit/ucx/src/ucp/wireup/wireup.c:1111
2 …
```
> UCP: Fix stub ep for client-server case

- src/ucp/tag/rndv.c
Release RNDV request in case of error
Fixes leak of RNDV request in case of error handling
```
[1588270638.985520] [sputnik1:6526 :0]          mpool.c:42   UCX  WARN  object 0x62e0000083c0 was not returned to mpool ucp_requests
```
Release RNDV request in case of completing RNDV GET Zcopy with the error, i.e. call `ucp_request_put(rndv_req)`, instead of sending ATS (i.e. `ucp_rndv_req_send_ats()`)
> UCP/TAG: Release RNDV request in case of error

- bindings/java/src/main/java/org/openucx/jucx/NativeLibs.java
Support loading UCX shared library via `-Djava.library.path` and `LD_LIBRARY_PATH`
Right now we require UCX to be in classpath. Classpath in java is more for java stuff. Shared libraries should be loaded from  `-Djava.library.path`  or `LD_LIBRARY_PATH`, as discussed with @abellina 
The priority now is a next:
1. Load libjucx from classpath (from jar).
2. Load binaries from the classpath (for backward compatibility).
3. Load binaries from `-Djava.library.path`
4. Load binaries from `LD_LIBRARY_PATH`
> JUCX: load shared libraries from java.library.path and LD_LIBRARY_PATH.

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/stream/stream_recv.c
Change UCP AM data release flow, so copying rdesc would not be needed for every release operation.
- performance
- code cleanup
> UCP/AM: Improve data release flow

- bindings/java/pom.xml.in
Fix JUCX publish on centos7
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=5793&view=logs&j=d3e6da6b-dace-5955-5a3f-1d9faad0a965&t=deebc48f-1661-5a61-6008-8ee9ad0a4431&l=300
This parameter was added to gpg2 work on fedora container. On centos7 container gpg is on an older version and doesn't recognize it:
https://bugzilla.redhat.com/show_bug.cgi?id=1582209#c5
> JUCX: Fix gpg sign on centos7 container.

- src/ucp/core/ucp_worker.c
Fix comment
The statement in the comment is incorrect
`ucp_suspended_iface_event()` -> `ucp_worker_iface_async_fd_event()`
> UCP/CORE: Fix comment

- src/ucs/config/global_opts.c
- src/ucs/config/global_opts.h
- src/ucs/debug/log.c
- src/ucs/debug/memtrack.c
- src/ucs/stats/stats.c
- src/ucs/sys/string.c
- src/ucs/sys/sys.c
- src/ucs/sys/sys.h
- test/gtest/ucs/test_log.cc
Add support for limited log file size (by default, there is no limit) and for backup of log files (by default, `0`).
The maximal log file size can be adjusted by `UCX_LOG_FILE_MAX_SIZE=<memunits>`
The maximal number of log files can be set by `UCX_LOG_FILE_BACKUP_COUNT=<uint>`
Some users may want to limit the maximal log file size due to some constraints on the systems where they use UCX.
pseudo-code:
```
log_entry_size = get_log_entry_size(...); // snprintf(NULL, 0, ...) to get the length
if ((log_entry_size  + cur_pos) >= max_log_file_size) {
if (backup_files != 0) {
for (all created files) {
rename_files(idx, idx+1);
/* file -> file.1; file.1 -> file.2 ... */
}
array_of_files[0] = create_new_file();
log_file                 = open_new_file(array_of_files[0]);
} else { …
```
> UCS/LOG: Add support for limited log file size

- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_def.h
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/base/ud_inl.h
- src/uct/ib/ud/verbs/ud_verbs.c
- test/gtest/uct/ib/test_ud.cc
Fixes #5112 : don't shrink send window before resends are done. fixes the failure when ca_wnd becomes lower, but tx_count is small.
Fixes #5114: don't dispatch send completions of skb's which are still in the outstanding queue. Otherwise they could be processed again when completion does arrive, leading to access to already released skb.
List of all fixes:
- If the async thread runs after reading prev_cwnd, but before setting tx_count=0, the async progress can resend and reduce cwnd, but then tx_count would be set to 0, effectively losing count of all those resends.
- Add iface locking for ep create/destroy
- Separate completion-with-error handler from timeout handler
- Use callback_q to invoke timeout handler, instead of async_comps_q
- Count number of QP-outstanding resends per …
> TEST/UD: Fix race conditions in ca_md

- buildlib/azure-pipelines-pr.yml
Allow "-" in commit prefix, so that PR like #5124, containing `UCT/CUDA-IPC:`  would not fail
> BUILD: Allow '-' symbol in commits

- src/uct/ib/ud/base/ud_iface.c
Fix #5134
EP flush is also broken, but fix is more complex, and will be in another PR.
> UCT/UD: Fix iface flush with outstanding send operations

- bindings/java/src/main/java/org/openucx/jucx/NativeLibs.java
If fails to load jucx from jar, print a reason.
e.g.
`Failed to load libjucx.so: libnuma.so.1: cannot open shared object file` - more clearly why it fails to load libjucx.
> JUCX: print error message if fails to load so lib.

- src/ucs/sys/topo.c
- src/ucs/sys/topo.h
- src/uct/api/uct.h
- test/gtest/ucs/test_topo.cc
Makes comparison of system devices straight-forward. Once we have `ucs_sys_device_t` being an unsigned integer, `uct_md_mem_query` can lookup bus_id associated with a buffer and either return a valid index associated with the device or return an UNKNOWN sys device. The index can later be compared with an index from another device for topology distance lookups and make decisions about lane selection. 
The expected flow is that UCTs populate a valid `ucs_sys_bus_id_t` or use  `ucs_sys_dev_bus_id_unknown` as bus_id to `ucs_topo_find_device_by_bus_id` and then return the associated system device index concerning buffer passed to `uct_md_mem_query`. As an example, the associated system device can be hash over input `ucs_sys_bus_id_t`
* Need an implementation of translation from …
> UCS/TOPO: Change ucs_sys_device_t from a structure to unsigned int

- src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.h
We retain opened memory handle as part of IPC reachability check with the assumption that the opened handle will be cached in the endpoint's remote_cache. We saw some applications where this is not true potentially because there are H<->D transfers as part of which memory handles are opened but never cached because an ep_{put/get}_zcopy wasn't issued subsequently (which triggers the caching logic).
This change closes the memory handle immediately after check if peer is reachable. When put_zcopy/get_zcopy is requested, if memory handle mapping hasn't occurred or is not in cache, then memory handle is opened.
cc @bureddy @ssaulters
> UCT/CUDA-IPC: Close ipc-handle after checking if peer is reachable

- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_request.c
- src/ucp/rma/flush.c
- src/uct/base/uct_iface.h
- src/uct/ib/ud/base/ud_ep.c
- test/gtest/uct/uct_p2p_test.cc
Fixes #5083
Don't release skb's which are still in the iface outstanding queue, and add assertion to prevent it
There were actually 2 bugs with similar side effect:
1. UD transport did tx window purge without checking skb flags. Solution is to check skb flags and act accordingly. Thus, we can unite the window release flow for remote ACK and flush(CANCEL).
2. UCP flush operation did "fast forward", and disregarded all "comp" handles will owned by UCT. Instead we need to wait for completions to arrive on all lanes which already started.
> UD: Fix flush(CANCEL) cleanup

- src/ucp/tag/tag_send.c
ignore rndv threshold tuning for UCP_OP_ATTR_FLAG_FAST_CMPL with memtype transfer
the default nbr rndv threshold (`UCX_RNDV_SEND_NBR_THRESH=256K`) is high for mem type transfers.
> UCP/RNDV: rndv threshold for MEMTYPE

- src/ucp/core/ucp_am.c
- test/gtest/ucp/test_ucp_sockaddr.cc
Fix the case when send is started as bcopy-multi, but just one packet was sent (due to different bcopy limits in stub and regular eps)
> UCP/AM: Fix stub ep multi-bcopy flow

- src/ucp/tag/rndv.c
Remove extra getting AM lane
`ucp_do_am_bcopy_single()` and `ucp_do_am_bcopy_multi()` do it
Just remove the excessive statement
> UCP/TAG/RNDV: Remove extra getting AM lane

- src/tools/perf/api/libperf.h
- src/tools/perf/lib/libperf.c
- src/tools/perf/lib/libperf_int.h
- src/tools/perf/lib/ucp_tests.cc
- src/tools/perf/lib/uct_tests.cc
- src/uct/ib/ud/base/ud_def.h
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_iface.c
- test/gtest/uct/test_uct_perf.cc
Fix uct_ep_flush() for UD, to flush any resend operations on the QP.
1. Keep skbs which are still being resent on the window to maintain strict order of completions
2. Add perftest flag to use flush_ep instead of flush_iface to test uct ep flush
> UCT/UD/PERF: Fix uct_ep_flush() for UD

- src/ucs/memory/rcache.c
- src/ucs/memory/rcache_int.h
- test/gtest/common/test_helpers.h
- test/gtest/ucs/test_rcache.cc
Fix rcache invalidation queue memory leak caused by long loop of malloc()+free() calls without any calls to UCX/MPI
Invalidate regions immediately if can lock the page table, and put the invalidate region on GC list. The region would not be found again after this.
> UCS/RCACHE/TEST: Fix memory leak of rcache invalidation entries

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_am.inl
- test/gtest/ucp/test_ucp_am.cc
Remove trailing whitespace in UCP AM files. No other changes
> UCP/AM: remove trailing whitespaces in AM files

- src/uct/ib/ud/base/ud_ep.c
Remove duplicate re-adding of UD timer during uct_ud_ep_timeout()
The timer is also added from uct_ud_ep_timer_backoff()
> UCT/UD: Remove duplicate call to ucs_wtimer_add()

- src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
- src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
- src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
- src/uct/cuda/cuda_ipc/cuda_ipc_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.h
Backport 2 cuda-ipc UCT fixes to 1.8.x
- Use a refcount to handle concurrent ops on same memory handle
- Close memory handle after reachability test to avoid reopened memory handle error
> Topic/refcount close memhndl after reach 1.8.x

- config/m4/ucs.m4
- src/ucs/debug/debug.c
- enables support of new API provided by binutils 2.34+
backport from https://github.com/openucx/ucx/pull/4925
(cherry picked from commit 93bdcb84b707078431c8ddffbfd7a188173cc3f3)
> BUILD/DEBUG: added new API of binutils - v1.8

- src/ucm/mmap/mmap.h
- test/gtest/common/test_helpers.cc
- test/gtest/common/test_helpers.h
- test/gtest/ucm/malloc_hook.cc
- test/gtest/ucp/test_ucp_mmap.cc
- test/gtest/uct/test_mem.cc
- due to conflicts between address sanitizer and bistro infrastructure
malloc hooks tests are disabled
> GTEST/MALLOC_HOOKS: disable malloc hooks tests if address sanitizer enabled

- src/ucs/datastruct/arbiter.c
- src/ucs/datastruct/arbiter.h
- src/uct/base/uct_iface.h
- test/gtest/ucs/test_arbiter.cc
Remove excessive parameter in push head elem routines
It's not used
1. Remove parameter
2. Remove passing this parameter in all occurrences
> UCS/ARBITER: Remove excessive parameter in push head elem routines

- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
Minor code cleanups in UCT/IB/UD.
This is needed for #5149.
1. Fix code alignments.
2. Re-use wrappers where it's possible.
3. Don't init request in `uct_ud_ep_do_pending`, since it can be ctl op.
> UCT/IB/UD: Minor code cleanups

- bindings/java/src/main/java/org/openucx/jucx/NativeLibs.java
During test ucx shared libraries are in classpath. No need to copy it to temp folder. Need to copy only `libjucx.so` that's inside a jar file.
JUCX loads only `ucp/uct/ucs` modules. Transport modules loaded by dlopen in ucs libs. When we copy it to temp directory we got:
```
[1589539565.270132] [jazz31:4474 :0]           init.c:94   UCX  DEBUG /tmp/jucx2548400424524342306/libucs.so loaded at 0x7fe2a66      16000
[1589539565.293519] [jazz31:4474 :0]         module.c:68   UCX  DEBUG ucs library path: /tmp/jucx2548400424524342306/libucs.so
[1589539565.293527] [jazz31:4474 :0]         module.c:250  UCX  DEBUG loading modules for uct
[1589539565.293628] [jazz31:4474 :0]         module.c:233  UCX  DEBUG dlopen('/tmp/jucx2548400424524342306/ucx/libuct_ib.so', mode=0x1) failed: …
```
> JUCX: do not copy shared library in tests.

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
- test/gtest/ucp/test_ucp_sockaddr.cc
Do not reconfigure ep in CM pack event cb, because it may be done asynchronously with the main thread
To avoid errors like
```
[jazz03:114011:0:114011]   ib_mlx5.inl:393  Assertion `iov[iov_it].memh != ((void *)0)' failed
/labhome/mikhailb/wgit/ucx/src/uct/ib/mlx5/ib_mlx5.inl: [ uct_ib_mlx5_set_data_seg_iov() ]
...
390             continue;
391         }
392         ucs_assert(iov[iov_it].memh != UCT_MEM_HANDLE_NULL);
==>   393
394         /* place data into the buffer */
```
or
```
mlx5: jazz20.swx.labs.mlnx: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000001 00000000 00000000 00000000
00000000 92005204 0a00f2ef 0000ffd2
```
Create local eps on tmp ep and move them to the real ep on connect event progress done from the main thread
> UCP/CM: Do not reconfigure ep in cm pack event cb

- src/uct/ib/rc/accel/rc_mlx5_devx.c
Fix compilation error in DevX
Fixes #5176
Add missing parameter in the `uct_rc_mlx5_devx_iface_event_handler()` async event callback
> UCT/IB/RC: Fix compilation error in DevX

- src/ucs/arch/cpu.c
Disable built-in memcpy for AMD
It is slow for shared buffer on some AMD configurations
set built-in memcpy minimum and maximum size to `UCS_MEMUNITS_INF`
> UCS/ARCH/CPU: Disable built-in memcpy for AMD

- src/uct/ib/rc/accel/rc_mlx5.inl
- src/uct/ib/rc/accel/rc_mlx5_common.h
MP XRQ implementation for RCX strongly relies on the ordering of packets. The state of current packet processing (message context) is stored in the endpoint and reset when the last fragment arrives. With HW TM, FW may send its own packets signalling RNDV completion (IBV_TMH_FIN) using FW/HW owned QP.
If such FIN packet arrives, while ep is receiving multi-fragment tag eager message, ep message context can be broken. To avoid this problem, do not analyze/process message state for non-tag packets, because they should always arrive in a single fragment.
Fixes #5059
> UCT/RC/DC: Fix MP XRQ rx flow for non tag CQEs

- buildlib/azure-pipelines-pr.yml
- buildlib/fedora.Dockerfile
- ucx.spec.in
Specify `openjdk-devel` package as a build dependency.
For some reason, Fedora doesn't pull `openjdk-devel` as a dependency for Maven, have to set it manually.
> SPEC: specify openjdk-devel package as dependency

- src/uct/ib/base/ib_iface.c
- test/gtest/uct/ib/test_ib.cc
- due to manipulation with subnet prefix in case if used custom
subnet prefix value, size of packed address is calculated
incorrectly: there is no room for subnet prefix value.
Fix: just increase address size by missing room
> GTEST/IB/ADDRESS-PACK: fixed heap corruption

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- Remove length field from UCP AM header, because it is not used (length is provided by the UCT on the receiver)
- Some minor cleanup
> UCP/AM: Remove length field from AM hdr

- test/gtest/ucs/test_async.cc
fix failure https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/6387/logs/111
> TEST/ASYNC: Add retries to test_async_event_mt.multithread

- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup_cm.c
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/rdmacm/rdmacm_cm_ep.c
do not reset `UCP_EP_FLAG_LOCAL_CONNECTED` flag on err handling flow of `ucp_cm_server_conn_notify_cb` to invoke `uct_ep_disconnect` from `ucp_worker_set_ep_failed` to invoke `disconnect_cb` on client side and complete close request.
fixes https://github.com/openucx/ucx/issues/5162
> UCP/SOCKADDR/CM: fix ucp_cm_server_conn_notify_cb err handling

- src/ucs/datastruct/arbiter.h
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_inl.h
- test/gtest/uct/test_pending.cc
Make sure that there are no pending reqs when doing AM
to avoid out-of-order sends reproduced in the following case (only when IB_NUM_PATHS=2):
1. do multiple sends on UCP EP > IB_SEG_SIZE to transfer them on all UCT EPs
2. both UCT EPs have pending requests scheduled (no window to send data anymore - waiting for ACKs), e.g. EP#1 has Multi AM Bcopy scheduled
3. do progress, both EPs receive ACKs, so they are able to do TX (`ep::tx::psn` < `ep::tx::max_psn`)
4. start dispatching pending requests that are scheduled on UCT IFACE arbiter, dispatching multi AM Bcopy callback on EP#1:
- AM Bcopy from pending progress was successful on EP#1
- switching to the second lane (EP#2)
- doing AM Bcopy on EP#2 - <getting assert here> out-of-order send - since there are pending requests scheduled on step …
> UCT/IB/UD: Make sure that there are no pending reqs when doing AM

- src/ucp/tag/offload.c
- src/uct/ib/rc/accel/rc_mlx5_common.c
- test/gtest/ucp/test_ucp_tag_offload.cc
Avoid offloading tag buffers which fit CQE inline. Otherwise it will be a segafult when copying data from the CQE to the GPU buffer
> UCT/RC/DC/TAG: Avoid scatter2cqe for expected tag buffs

- src/uct/api/uct.h
- src/uct/base/uct_iface.h
- src/uct/base/uct_md.c
- To be able to query device index (`ucs_sys_device_t`) associated with a specific lane (like an entry in UCP rma_bw_lanes), add device index member in `uct_tl_resource_desc`.
> UCT/API: return device index as part of tl_resource/device descriptor

- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
- optimization for contig datatypes used for legacy API
implemented via NBX API
> UCP/TAG-SEND/NBX: performance improvements for tag_send_nbx

- src/uct/ib/base/ib_iface.c
fix subnet packing to IB address
wrongly advanced pointer leads to corrupted subnet mask in case of packing path mtu
> UCT/IB/ADDRESS: fix IB subnet pack

- test/gtest/uct/test_pending.cc
Fix request leak in the UCT pending test
There is UCT pending request leak in case of test skipping
```
2020-05-27T16:25:56.887Z] [ RUN      ] rc_mlx5/test_uct_pending.send_ooo_with_pending_another_ep/0 <rc_mlx5/mlx5_bond_0:1>
[2020-05-27T16:25:57.448Z] [     SKIP ] (can't fill UCT resources for all EPs in the given time (done=3, expected=2))
[2020-05-27T16:25:57.448Z] [       OK ] rc_mlx5/test_uct_pending.send_ooo_with_pending_another_ep/0 (488 ms)
```
Don't skip the test if there are some UCT EPs that scheduled pending operations
> GTEST/UCT: Fix request leak in the UCT pending test

- src/uct/ib/base/ib_device.h
- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/cm/cm_ep.c
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/ud/base/ud_iface.c
- test/gtest/common/test_helpers.cc
- test/gtest/common/test_helpers.h
- test/gtest/uct/ib/test_ib.cc
- test/gtest/uct/ib/test_ib_pkey.cc
- test/gtest/uct/ib/test_ud_ds.cc
Allow QP initialization for pkey with limited membership.
To allow communications between peers with limited and full membership (L<->F, F<->L, F<->F).
1. Allow using PKEY with limited membership if it was requested thru environment variable.
2. Pack PKEY value (if it is not default - 0xffff) to the IB address and update UCT reachability function.
> UCT/IB: Allow QP for pkey with limited membership

- src/ucp/core/ucp_am.h
Guard `ucp_am.h` file with corresponding ifdefs for correct inclusion
(started getting errors with some internal prototype affecting AMs)
> UCP/AM: guard header with ifdefs

- src/ucp/core/ucp_am.c
- test/gtest/ucp/test_ucp_am.cc
Do not initialize data descriptor until requested by the user (i.e. UCS_INPROGRESS is returned from the AM callback)
Performance improvement: In case of small inline messages (scatter2CQE on IB) do not copy the data into descriptor before calling cb
> UCP/AM: Do not init data desc until requested

- ucx.spec.in
Java has a special requirement for packaging in the Fedora environment.
UCX's users take it from Maven, so RPM is not required.
Related discussion: https://github.com/openucx/ucx/pull/5071
Build verification in Koji: https://koji.fedoraproject.org/koji/taskinfo?taskID=45235856
> RPM: package UCX without Java

- bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java
- bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpointErrorHandler.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpointParams.java
- bindings/java/src/main/native/endpoint.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
- bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java
Ability to specify UcpEpError handler.
As discussed with @abellina  to be able to catch endpoint errors in JUCX apps.
E.g. in this unit test it catches:
```
[1589621202.433722] [jazz11:137347:0] jucx_common_def.cc:191  UCX  ERROR JUCX: request error: Endpoint timeout
[1589621202.437750] [jazz11:137347:0]    ib_mlx5_log.c:143  UCX  ERROR Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[1589621202.437750] [jazz11:137347:0]    ib_mlx5_log.c:143  UCX  ERROR RC QP 0x12434 wqe[2]: SEND s-- [inl len 10] [va 0x7fb668307060 len 4096 lkey 0x26b254]
```
EndpointErrorHandler could be generic for many endpoints. However to not keep a map between native endpoint -> JUCX endpoint class, each callback handler is wrapped in an internal callback handler, that has a reference …
> JUCX: Endpoint error handler functionality.

- src/uct/ib/ud/base/ud_ep.c
Remove debug leftover introduced by #5149 PR
We don't need the prints from the code to the standard output
Remove printing the debug message to the standard error stream
> UCT/IB/UD: Remove debug leftover

- src/uct/cuda/base/cuda_iface.h
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
Improve shared bandwidth reported by `cuda_ipc` based on the device generation.
> UCT/CUDA/CUDA_IPC: assign shared bandwidth based on device generation

- src/ucs/async/pipe.h
- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/base/ud_inl.h
- src/uct/ib/ud/verbs/ud_verbs.c
- test/gtest/uct/ib/test_cq_moderation.cc
- test/gtest/uct/ib/test_ib.cc
- test/gtest/uct/ib/test_ib.h
- test/gtest/uct/ib/test_ud_pending.cc
- test/gtest/uct/ib/ud_base.cc
- test/gtest/uct/test_event.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
Enable async progress in IB/UD
Avoid intervention timer-based async progress
1. Implement event-based async progress in IB/UD thru waiting on IB completion chanel's FD and calling user's callback (if specified)
2. Send resend packet as solicited event
3. Get solicited-only events, by default. If users armed for Tx/Rx events, provide them thru callback
> UCT/IB/UD/GTEST: Enable async progress

- bindings/java/src/main/java/org/openucx/jucx/NativeLibs.java
Do not delete a shared library if it wasn't loaded from jar.
If library was loaded from the classpath (e.g. by specifying classpath=UCX_HOME, JUCX will delete so after the finish. Need only to delete files that were unpacked to tmp directory from jar.
> JUCX: do not delete so file if it's not from jar.

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.inl
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_cm.h
add helper functions:
+ ucp_ep_has_cm_lane
+ ucp_ep_init_flags_has_cm
to remove code duplications
> UCP/EP/WIREUP: add helper functions

- src/ucs/datastruct/khash.h
- src/ucs/sys/init.c
- src/ucs/sys/topo.c
- src/ucs/sys/topo.h
- test/gtest/ucs/test_topo.cc
- Uses two hash maps to return device index given bus id (to implement `ucs_topo_find_device_by_bus_id`), and bus_id given device index (to implement `ucs_topo_get_distance`)
- extend existing unit test to check correctness
- introduce ucs_topo_init and cleanup to initiate destroy hashmaps (used `ucs/debug` usage of khash as reference for implementation)
- each time `find_device_by_bus_id` is called, if the bus_id is not an existing key in the hashmap, the key is added and sys_device id is returned. This sys_device_t id the current size of the hashmap, so it increases by 1 count for each new bus_id encountered. 
- when a new bus_id key is added, for reverse mapping the corresponding pair (sys_device_t id, bus_id) is also entered into another hashmap for quick sys_device id -> bus_id …
> UCS/TOPO: Implementation of ucs_topo_find_device_by_bus_id

- test/apps/iodemo/io_demo.cc
Fix ops random generation.
Currently, IO demo “-o” option doesn’t work as expected. It runs only “write” operations, but “read” and “write” should be tested.
$ UCX_SOCKADDR_CM_ENABLE=y io_demo
$ UCX_SOCKADDR_CM_ENABLE=y io_demo -o read,write
…
[1589882713.903671] 1000 writes at 299.996 MB/s, average latency: 13.021 usec
The op modes can't be generate randomly due to the LCG returns alternating even/odd values.
It is always be the same value even if have two different values in opts().operations.
Change the random generate method for the case that only 1 distance between max and min.
>  TEST/APPS: Fix ops random generation

- src/ucp/core/ucp_worker.c
- src/ucp/tag/tag_match.c
- test/gtest/ucp/test_ucp_peer_failure.cc
Release rdesc from unexpected list.
If UCT transport doesn't support `RDESC` feature, UCP is responsible to release all allocated `rdesc`s that is used to keep received unexpected data.
For example, the problem could be reproduced in UCP peer failure tests with implemented error handling support in UCT/TCP. UCT/TCP doesn't support `RDESC` feature.
1. Go over the elements in the TM unexpected list and release `rdesc`s of uncompleted tag requests
2. Cleanup TM before cleanup of `AM_MP` mpool to avoid errors about unreleased mpool elements.
> UCP/CORE/TAG: Release rdesc from unexpected

- .github/CONTRIBUTING.md
Updating guidelines for contributors with clarifications for PR force-push policy
Make it clear that force-push during review is not allowed
> DOC: Updating guidelines for contributors

- src/ucp/wireup/wireup_cm.c
- src/uct/api/uct.h
- src/uct/ib/rdmacm/rdmacm_cm_ep.c
- src/uct/tcp/tcp_sockcm_ep.c
- test/gtest/uct/ib/test_sockaddr.cc
- test/gtest/uct/uct_test.cc
Flatten `ucp_ep_params_t` structure so it would be better suitable for future extensions
> UCP/UCT/API/GTEST: Remove the sockaddr_connect_cb union in uct_ep_params

- buildlib/az-distro-release.yml
- buildlib/azure-pipelines-release.yml
- buildlib/azure-pipelines.md
- buildlib/azure-pipelines.yml
- buildlib/centos7-release.Dockerfile
- buildlib/docker-compose.yml
- buildlib/jucx-publish.yml
- buildlib/push-release-images.sh
- buildlib/ubuntu-release.Dockerfile
- contrib/buildrpm.sh
- ucx.spec.in
Build Ubuntu18.04, Ubuntu16.04, and CentOS7 packages (DEBs and RPMs accordingly) and publish for releases on Github.
Provide an easy way for users to try latest release ASAP.
> AZP: build distro packages for releases

- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- do not test local iface reachability for CM flow
- do not iterate not existing resources in transport selection loop
(cut bitmask by context->tl_bitmap)
CM can provide alternative reachable address, but unreachable from
default iface configuration. For example, in case of IB, rdmacm_cm can select
other GID, path mtu, etc.
> UCP/WIREUP: do not test local iface reachability for CM flow

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_types.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- Inherit AM headers from one another
- Use smaller header for middle fragments
- Remove some code duplication
- potential perf improvement for multi-fragmented messages
- cleanup and preparation for new AM API
> UCP/AM: Update handling of multi_fragment AM

- test/gtest/ucp/test_ucp_peer_failure.cc
Don't print a warning about unmatched  unexpected rdesc
To avoid annoying `INFO` prints
Remove `UCS_TEST_MESSAGE`
Check for `"unexpected tag-receive descriptor"` instead of `"receive descriptor"`
> GTEST/UCP: Don't print a warning about unmatched unexpected rdesc

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
Fix comparing TX/RX capabilities in UCT/TCP.
Currently,  EP's `ctx_caps` field is used to keep TX/RX capabilities and extra flags that show which operation is ongoing (PUT/AM Zcopy). So, when comparing EP capabilities, we have to compare only TX/RX capabilities.
e.g. if not to do this, `assert()` happens in `uct_ep_close()` if PUT/AM Zcopy was in progress, i.e. this bit is set in `ctx_caps`.
Introduce `UCT_TCP_EP_CTX_CAPS` EP capabilities macro that will be used to compare EP's `ctx_caps` when we need to know which caps were set (TX/RX).
> UCT/TCP: Fix comparing TX/RX capabilities

- test/gtest/ucp/test_ucp_sockaddr.cc
backport of #4809 to c1.8.x
bugfix
cherry-picked
> GTEST/UCP/SOCKADDR: fix test_ucp_sockaddr.listen_inaddr_any (v1.8.x)

- src/ucp/core/ucp_ep.c
- src/ucp/wireup/wireup.c
do not use UCP_EP_FLAG_CONNECT_REQ_QUEUED for CM case
this prevents resources leak when disconnecting of not completely
connected UCP EPs
> UCP/WIREUP: do not use UCP_EP_FLAG_CONNECT_REQ_QUEUED for CM case

- test/gtest/ucs/test_log.cc
Improve debugging in logging tests
to debug #5241
```
[ RUN      ] log_test_file_size.large_file <> <>
[     INFO ] "grep 'SLNQgeR4n4R6ax957WvSzzrSX3RsDJfdc23IgSMRWmW6jfApB3HA29bXA0NOK21w33FjVZ90Lf43IEsTF9bHGAmRB9nVCmPDpewJC3JXgNayaQPpYz5o9pDKzyn9lDMffff' /tmp/gtest_ucs_log.4933.*" failed after 20 iterations (return value: 1)
```
Print grep command and `errno` when it failed
> GTEST/UCS: Improve debugging in logging tests

- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/ucp/ucp_test.h
select random interface for each test, important if there are several
differently configured interfaces, for example IPoIB, RoCE, IPv4/6
to improve test coverage
> GTEST/UCP/SOCKADDR: randomize iface selection for testing

- src/ucs/sys/sock.c
Fix error cb argument in blocking socket send/recv
Wrong argument passed
`err_cb` -> `err_cb_arg`
> UCS/SYS: Fix error cb argument in blocking socket send/recv

- src/ucp/core/ucp_context.c
Fix indexing in ucp_fill_sockaddr_cms_prio_list
context->config.cm_cmpt_idxs and num_sockaddr_cms should have different
indexes since in case of '*', num_sockaddr_cms is set to one but
context->config.cm_cmpt_idxs may have multiple entries, in case of more
than one cm.
Add a separate index to context->config.cm_cmpt_idxs
> UCP: fix indexing in ucp_fill_sockaddr_cms_prio_list

- src/ucp/tag/rndv.c
- test/gtest/ucp/test_ucp_tag_mem_type.cc
Ensure RNDV pipeline fragment size matches PUT/GET limits
Fixes #5260
```
[----------] 1 test from rc/test_ucp_tag_mem_type
[ RUN      ] rc/test_ucp_tag_mem_type.xfer_mismatch_length/55 <rc_v,cuda_copy,rocm_copy>
[     INFO ] TEST: host <-> cuda length: 9437270
[       OK ] rc/test_ucp_tag_mem_type.xfer_mismatch_length/55 (236 ms)
[----------] 1 test from rc/test_ucp_tag_mem_type (236 ms total)
[==========] 1 test from 1 test case ran. (237 ms total)
[  PASSED  ] 1 test.
```
1. Use the already implemented functionality to ensure that the length of the fragment is over MIN Zcopy and less than MAX Zcopy.
2. Wrap this functionality to the common function.
3. Use it for GET/PUT pipeline fragment size …
>  UCP/TAG: Ensure pipeline fragment size matches PUT/GET limits

- src/ucs/datastruct/string_buffer.c
- test/gtest/ucs/test_string.cc
Fix 2 bugs in string buffer grow:
1. When calling vsprintf() need to pass how many bytes **remain** in the buffer, and not the whole capacity
2. When capacity==length+1, need to grow **by** a size, and not revert back to the initial size
Fix growth calculations + add gtest to test: 1st bug is tested by appending 100 byte string, 2nd bug is tested by appending twice.
> UCS/TEST/STRING: Fix string buffer grow

- test/gtest/ucp/test_ucp_am.cc
Use `sender()` ep when do AM send in tests
> GTEST/UCP/AM: Use correct eps for sending in AM tests

- contrib/test_jenkins.sh
Workaround for OpenMPI issue https://github.com/open-mpi/ompi/issues/7833
> JENKINS: Workaround mpirun exit without sync

- src/ucp/core/ucp_context.c
- src/ucs/config/parser.c
- src/ucs/config/parser.h
- src/ucs/sys/string.c
- src/ucs/sys/string.h
- src/uct/ib/base/ib_md.c
- test/gtest/ucs/test_config.cc
- test/gtest/ucs/test_sys.cc
- Avoid float == comparison, use UCS_CONFIG_BW_IS_AUTO() to cast to ssize_t first
- Print bandwidth in an easy-to-read format (so that the number is not too big) since it doesn't have to be very accurate
- Remove redundant checks for INF/AUTO from ucs_config_sprintf_memunits()
- Print 'auto' value from ucs_memunits_to_str()
> UCS/CONFIG: Cleanups in bandwidth / memunits parsing

- test/gtest/uct/test_peer_failure.cc
- test/gtest/uct/test_pending.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
adopt tests for future TCP peer failure support
UCT `purge_failed_peer` peer failure test can't be used with TCP's error handling support, since it expects that `uct_ep_pending_add()` will be successful, but it's not true in TCP. The failure is detected during doing AM short operation, `uct_ep_pending_add()` returns `UCS_ERR_BUSY`.
0. re-implemented `pending_cb` to do AM Short until it is failed
1. fill UCT resources
2. kill the receiver
3. add 64 pending UCT requests
4. do `flush()` - `pending_cb` will be failed, since the receiver was killed
> GTEST/UCT: Adopt tests for future TCP peer failure support

- config/m4/rocm.m4
- src/tools/perf/rocm/Makefile.am
- src/ucm/rocm/Makefile.am
- src/uct/rocm/Makefile.am
The changes fixes UCX build for ROCm environment when configured with **--with-rocm=/opt/rocm-ver** to build modules that link with the specified version of ROCm in with-rocm.
The fixes also **enables** UCX for ROCm **build** on Ubuntu/Debian as well as **CentOS/RHEL environment (requires devtoolset-7 gcc/g++).**
The UCX lib*so modules relied on ldconf entries to load ROCm modules, which is error prone when there are multiple versions of ROCm are installed. The modules built against a specific ROCm-version installation when used with a different version of ROCm could lead to undefined results due to differences/incompatibilities between ROCm releases.
Use DT_RUNPATH to set the ROCm version installed paths.
**Example**: Excerpt from build configured using **--with-rocm=/opt/rocm-3.5.0** of …
> UCM/UCT/PERF/ROCM: fix UCX ROCm build, use DT_RUNPATH for libs

- src/ucp/Makefile.am
- src/ucp/proto/proto_select.h
- test/gtest/Makefile.am
- test/gtest/ucp/test_ucp_proto.cc
Add data structures to support generic protocol selection: first, encode a 'key', according to operation properties (opcode, datatype, mem type, locality, ...). The key will be used for hash lookup to resolve an array of 'thresholds'. Then do a linear search on this array to find the protocol for the given message length.
Full implementation: https://github.com/yosefe/ucx/tree/wip/protov2
> UCP/PROTO: Add protocol selection data structures

- src/ucs/datastruct/linear_func.h
- test/gtest/ucs/test_math.cc
Provide infrastructure for UCP protocol selection using linear functions, which represent the performance of a potential protocol as a function of message size
> UCS/MATH: Add more linear_func functions and tests

- buildlib/azure-pipelines-pr.yml
- buildlib/fedora.Dockerfile
Change Fedora image from 30 to 32.
Fedora 30 was EOL-ed.
> AZP: switch for Fedora 32 since Fedora 30 is EOL-ed

- src/ucs/datastruct/ptr_array.h
- Use CPU dcache prefetching to further improve the ptr_array
performance.
- Improvement achieved is ~10% on Intel processors.
Improves ptr_array foreach performance by 10% using CPU prefetch.
Improves performance.
Improves ptr_array foreach performance by 10% using CPU dcache prefetch.
> UCS: Improve ptr_array foreach performance by prefetching

- src/ucp/api/ucp.h
- src/ucp/rma/amo_send.c
- test/gtest/ucp/test_ucp_atomic.cc
- test/gtest/ucp/test_ucp_atomic.h
Define `reply_buffer` field for `ucp_request_param_t`. Update `ucp_atomic_fetch_nbx` to use it
This field can be relevant for other operations defined in the future, e.g `ucp_am_send_nbx`.
Thus, having this field in params would be more consistent from API perspective.
> UCP/API: Define reply_buffer field for nbx parms

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_request.h
Remove unneeded malloc from multi-fragment AM path (use rdesc of the first fragment instead)
- performance
- constistency with other APIs (tag, stream)
> UCP/AM: Remove malloc in multi-fragment handling

- src/ucs/datastruct/queue.h
Fixes GCCv10 build issue found by @shuki-zanyovka, and a typo on the way (may replace #5328, if it passes the CI):
````
CXX      uct/ib/gtest-test_dc.o
CXX      uct/ib/gtest-test_sockaddr.o
In file included from /mnt/central/users/szanyovka/ucx/src/ucs/memory/memory_type.h:11,
from ./common/mem_buffer.h:10,
from ./common/test_helpers.h:13,
from ./common/test.h:16,
from ucs/test_datatype.cc:8:
ucs/test_datatype.cc: In member function 'virtual void test_datatype_queue_iter_Test::test_body()':
/mnt/central/users/szanyovka/ucx/src/ucs/sys/compiler_def.h:138:7: error: array subscript -2 is outside array bounds of 'ucs_queue_head_t [1]' {aka 'ucs_queue_head [1]'} [-Werror=array-bounds]
138 |     ( (_type*)( (char*)(void*)(_ptr) - ucs_offsetof(_type, _member) )  )
| …
```
> UCS: fix GCCv10 issue in queue for-each

- src/ucp/core/ucp_request.h
- src/ucp/tag/rndv.c
Fix recv request usage. Can not use values from different structs of the same union
`ucp_rndv_recv_data_init` initializes data in conflicting parts of the same union
Possible crash/undefined behavior. It luckily does not crash with tag due to req->recv.tag layout, but provokes a crash with AM RNDV prototype 
Use req->flags to distinguish pipeline and regular RNDV protocols
> UCP/RNDV: Fix req->recv union usage for rndv

- src/ucs/sys/sock.c
- src/ucs/sys/sock.h
- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_device.h
- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/verbs/ud_verbs.c
- test/gtest/ucp/test_ucp_sockaddr.cc
packet filter by any GID present on device
rdmacm can select different GID on addr/route resolve than UCT does it locally. In this case GRH will contain DGID according to remote EP configuration based on CM settings.
> UCT/IB/UD: packet filter by any GID present on device

- buildlib/az-distro-release.yml
Azure cleans up only working directory while DEB pkg is created on an upper level. This leads to the wrong DEB taken for release.
Fixes #5335
> AZP: build packages in a subfolder

- buildlib/az-distro-release.yml
Backport of #5342.
(cherry picked from commit 9fc86a42585fc070dac8a3a9bd183f71fb312030)
> AZP: build packages in a subfolder — v1.8

- src/ucp/api/ucp.h
Fix doxygen reference for `start_pack` function
> UCP/DT/DOC: Fix typo in generic dt ops doc

- src/uct/cuda/base/cuda_iface.h
- src/uct/cuda/cuda_copy/cuda_copy_ep.c
- src/uct/cuda/cuda_copy/cuda_copy_iface.c
- src/uct/cuda/cuda_copy/cuda_copy_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
- src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.h
Don't print memory registration errors from the context of ucp_mem_map(), since they are not fatal. ucp_mem_map() updates the registration bitmap of ucp_memh according to the memory domain which were able to register successfully.
> UCT/CUDA: Respect UCT_MD_MEM_FLAG_HIDE_ERRORS flag for md_mem_reg()

- src/ucs/Makefile.am
- src/ucs/datastruct/conn_match.c
- src/ucs/datastruct/conn_match.h
Define new connection matching API in UCS as internal one that could be used by UCP/UCT
In order to use it for UCP/UCT and don't duplicate the same functionality in different UCP/UCT implementations
The implementation is copied from UCP one and redesigned in order to support different address type by defining an opaque structure that could represent different address types:
- UCP: `uint64_t` UUID
- UD: IB address
- TCP: sockaddr_in
> UCS/DATASTUCT: Implement conn match

- src/ucs/memory/rcache.c
- src/ucs/memory/rcache.h
- src/uct/cuda/gdr_copy/gdr_copy_md.c
- src/uct/ib/base/ib_md.c
- src/uct/sm/mm/xpmem/mm_xpmem.c
- src/uct/sm/scopy/knem/knem_md.c
- test/gtest/ucs/test_rcache.cc
Since xpmem does not pin pages, we should not check PFN of xpmem pages in rcache, even if requested by user.
> UCS/PFN: page may be unmapped after xpmem reg_mr

- bindings/java/pom.xml.in
Port #5110 to 1.8
To fix publish error: https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=7475&view=logs&j=9330fceb-9a99-5389-6029-bfbc83e640a0&t=9692db60-489d-4db6-84eb-919ddaa0eddf
> JUCX: Fix gpg sign on centos7 container. Port to 1.8

- buildlib/azure-pipelines-release.yml
- buildlib/centos7.Dockerfile
* Added `rpm-build` to centos7.Dockerfile
* Changed ref on `centos7:2` container image
in the azure-pipelines-release.yaml
Signed-off-by: Yuriy Shestakov <yuriis@mellanox.com>
> AZP: Upload src.rpm/tar.gz to release page — v1.8

- src/uct/cuda/base/cuda_iface.h
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
- include Ampere bandwidth
- report peak bandwidth capability as opposed bandwidth per nvlink
> UCT/CUDA: Update cuda-ipc bandwidth for Ampere

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/tag/offload.c
- src/ucp/tag/rndv.c
- src/ucp/tag/tag_send.c
- test/gtest/ucp/test_ucp_mmap.cc
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_tag.cc
Move rndv parameters/thresholds to common part of ep config
Rndv is a common protocol which can be used by different APIs, not only TAG.
AM implementation is POC ready, can be implemented for stream as well
- Move rndv info to common part of ep config, because RNDV is performed on AM and RMA lanes regardless of API which is going to use it. 
- Keep separate RNDV thresholds in tag specific configuration, because they may be different if tag offload is used and tag offload and AM are different lanes.
> UCP/RNDV: Make rndv ep config generic (not tag specific)

- test/gtest/ucp/ucp_datatype.cc
- test/gtest/ucp/ucp_datatype.h
Extend UCP datatype infrastructure in gtest:
- generate all possible pairs of data types, which can be used like "send dt", "recv dt"
- a couple of other auxiliary functions used for testing UCP AM POC
It will be used for testing new UCP AM interface
> GTEST/UCP: Add dt pairs func to tests

- src/ucp/core/ucp_ep.c
PR #4912, RMA bw lanes for some mem type are ignored when there is another mem type lane is 10x (UCX_MULTI_LANE_MAX_RATIO) faster 
For example. HOST lanes ignored when PR https://github.com/openucx/ucx/pull/5344 set cuda_ipc bw with max NVlanes
> UCP/EP: Consider all memtypes for GET_ZCOPY lanes

- src/ucp/core/ucp_ep.c
porting https://github.com/openucx/ucx/pull/5357 to v1.9.x branch
> UCP/EP: Consider all memtypes for GET_ZCOPY lanes - v1.9.x

- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- test/gtest/uct/ib/test_rc.cc
Flow control for rdma READ operations, based on number of simultaneously transferred bytes 
To better protect communication patterns when different size messages are read
> UCT/RC: RDMA_READ FC by number of bytes

- src/ucs/sys/topo.h
ucs_sys_device_t is going to be a a filed in UCP structures for protocol lookup, as part of hash key. In order to optimize UCP, we can make the device index smaller, we are not expecting more than 64k devices on same system.
> UCS/TOPO: Make ucs_sys_device_t a uint16, for smaller UCP structures

- docs/doxygen/ucxdox
- src/ucp/api/ucp.h
- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucs/memory/memory_type.h
to enable OMPI cuda initialization in UCX PML only if UCX supports cuda mem type (https://github.com/open-mpi/ompi/pull/7893)
> UCP: Add memtype query in ucp_context_query() API

- src/ucs/type/status.h
Fix macros
Missed `)` at the end of the macros
Add missing `)` at the end of the macros
> UCS/STATUS: Fix macros

- src/ucs/datastruct/conn_match.c
Fix allocation of peer object in connection matching
Connection matching doesn't work as expected
Allocate memory for peer structure and for the destination address
> UCS/DATASTRUCT: Fix allocation of peer object

- test/apps/iodemo/io_demo.cc
Fix timeout exceeded error detection
`-l` option doesn't work as expected in case of reconnects
No need to check for `_status == OK` when checking timeout
> APPS/IO_DEMO: Fix timeout exceeded error detection

- src/ucp/Makefile.am
- src/ucp/core/ucp_request.h
- src/ucp/tag/offload.c
- src/ucp/tag/rndv.c
- src/ucp/tag/rndv.h
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_rndv.c
- src/ucp/tag/tag_rndv.h
- src/ucp/tag/tag_send.c
Start making rendezvous a common protocol suitable for different APIs 
This code will be used by UCP AM rdnv as well
Move tag specific to `tag_rndv` files where possible. As a next step `rndv.*` files will be moved from `ucp/tag` folder to `ucp/proto`
> UCP/RNDV: Make rndv generic proto, not bound to TAG API only

- ucx.spec.in
Need to avoid runtime CUda dependency.
Don't install examples since the binary can depend on Cuda libs.
This PR is only for v1.9.x release branch, for master we probably want to create separate binaries for Cuda and make them part of ucx-cuda subpackage.
> SPEC: Don't install examples - v1.9.x

- src/ucs/sys/string.c
What do you think to use `ucs_basename` instead of `basename`?
The `basename(3)` on macOS defined as the following.
```
SYNOPSIS
#include <libgen.h>
char *
basename(char *path);
```
When I build `ucs/sys/string.c` on macOS, It complain the following error. Because `use_get_user_name()` returns `const char *`.
```
sys/string.c:73:49: error: passing 'const char *' to parameter of type 'char *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
snprintf(p, end - p, "%s", basename(ucs_get_user_name()));
^~~~~~~~~~~~~~~~~~~
```
Replace `basename` to `ucs_basename`.
> UCS/SYS/STRING: use ucs_basename instead of basename

- ucx.spec.in
Need to avoid runtime Cuda dependency.
Don't install examples since the binary can depend on Cuda libs.
This PR ports the fix from #5391, to make sure we don't have a regression in next UCX release. Should be replaced by a better fix to separate example binaries.
> SPEC: Don't install examples

- src/ucs/type/status.h
- test/gtest/uct/test_peer_failure.cc
GTEST/UCT: Retry adding pending request if ERR_BUSY returned
to avoid failures on expecting `UCS_OK` when `UCS_ERR_BUSY` error is returned form `uct_ep_pending_add()`
Fixes #5373 
retry filling UCT resources when `uct_ep_pending_add()` returns `UCS_ERR_BUSY`
> GTEST/UCT: Retry adding pending request if ERR_BUSY returned

- src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
bandwidth lowering no longer needed after https://github.com/openucx/ucx/pull/5357
> UCT/CUDA/CUDA-IPC: revert lowered bandwidth reporting in cuda-ipc

- src/tools/info/type_info.c
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_types.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/wireup/ep_match.c
- src/ucp/wireup/ep_match.h
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
Use UCS conn match in UCP
To avoid duplication of the connection matching functionality in UCP/UCTs
1. Remove EP match form UCP/WIREUP code
2. Add adoption of UCS connection matching
> UCP/CORE/WIREUP: Use UCS conn match

- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- test/gtest/uct/ib/test_rc.cc
Flow control for rdma READ operations, based on number of simultaneously transferred bytes
To better protect communication patterns when different size messages are read
Cherry-pick from master PR #5381
> UCT/RC: RDMA_READ FC by number of bytes - v1.9.x

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_ep.inl
- src/ucp/core/ucp_mm.h
- src/ucp/core/ucp_types.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/wireup/wireup.c
- test/gtest/ucp/test_ucp_atomic.cc
- test/gtest/ucp/test_ucp_mmap.cc
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_tag.cc
- test/gtest/ucp/test_ucp_tag_mem_type.cc
- test/gtest/ucp/test_ucp_tag_offload.cc
- test/gtest/ucp/test_ucp_tag_xfer.cc
- test/gtest/ucp/test_ucp_wireup.cc
Preparation for adding Rkey configuration (similarly to ep configuration) which will allow protocol selection according to remote memory type/locality.
> UCP/WORKER: Rename ucp_ep_cfg_index_t to ucp_worker_cfg_index_t

- src/ucs/datastruct/conn_match.c
Fix logging in connection matching
This patch fixes stack overflow
1. Use the `address` parameter instead of an address of the `address` parameter
2. Print the type of connection that wasn't found (expected/unexpected)
> UCS/DATASTRUCT: Fix logging in connection matching

- src/ucp/api/ucp.h
- src/ucp/core/ucp_mm.c
Add prot READ/WRITE to prot parameters of UCP API.
Currently prot READ|WRITE is hard code in UCX, we need configure them through UCP API.
Add prot READ/WRITE relative macros in the prot parameter of UCP API.
> UCP: Add prot parameter to UCP API.

- src/tools/perf/perftest.c
- src/tools/profile/read_profile.c
- src/ucs/profile/profile.c
- src/ucs/sys/module.c
This PR the same #5392 change. For another file. (`ucs/profile/profile.c`)
The `basename(3)` on macOS defined as the following.
```
SYNOPSIS
#include <libgen.h>
char *
basename(char *path);
```
When I build `ucs/profile/profile.c` on macOS, It complain the following error.
```
profile/profile.c:403:47: error: passing 'const char *' to parameter of type 'char *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
!strcmp(loc->super.file, basename(file)) &&
^~~~
```
Replace `basename` to `ucs_basename`.
The `sys/module.c` also use `basename`.
When I try to change `ucs_basename` like the following on Linux,
It complains about the following error.
```diff
diff --git a/src/ucs/sys/module.c b/src/ucs/sys/module.c
index ee6b0dd..999b9b0 100644
--- …
```
> UCS/PROFILE,SYS: use ucs_basename instead of basename

- src/uct/ib/base/ib_verbs.h
Code cleanups in pack uint24 function
`uct_ib_pack_uint24()` is used in UD for EP_ID value
1. Remove extra empty line
2. Rename `qp_num` to all parameter
3. Remove `const` qualifier as not needed
> UCT/IB: Code cleanups in pack uint24 function

- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_iface.c
Workaround for #5412 and recent rdma-core, which calls rand() only when `ah_attr.flow_label != 0`.
Older rdma-core versions which always call rand for ibv_create_ah() on RoCE will not be "fixed".
> UCT/IB: Workaround rdma-core issue of calling rand() from ibv_create_ah

- src/uct/api/uct.h
Add prot READ/WRITE to flags parameter of UCT API.
Currently prot READ|WRITE is hard code in UCX, we need configure them through API parameter.
Add prot READ/WRITE relative macros in the flags parameter of UCT API.
> UCT: Add prot READ/WRITE to flags parameter of API.

- src/ucp/Makefile.am
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_mm.h
- src/ucp/core/ucp_rkey.c
- src/ucp/core/ucp_rkey.h
- src/ucp/core/ucp_worker.c
- src/ucp/rma/rma.h
- test/gtest/ucp/test_ucp_mmap.cc
Preparation for creating rkey configuration cache and keeping RMA protocols selection structures in the rkey configuration
> UCP/RKEY: Move rkey structures to separate header file

- src/tools/info/type_info.c
- src/ucp/Makefile.am
- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.inl
- src/ucp/dt/datatype_iter.h
- src/ucp/dt/datatype_iter.inl
- src/ucp/dt/dt.c
- src/ucp/dt/dt.h
- src/ucp/dt/dt.inl
- src/ucp/dt/dt_generic.c
- src/ucp/dt/dt_generic.h
- src/ucp/dt/dt_iov.c
- src/ucp/dt/dt_iov.h
- test/gtest/ucp/test_ucp_dt.cc
- test/gtest/ucp/ucp_datatype.cc
- test/gtest/ucp/ucp_datatype.h
Create iterator over type send/receive buffer which will be used for new protocols (replace request state)
The iterator holds all datatype related state and allows pack, unpack, and generating uct_iov_t for zero-copy operations
> UCP/TEST: Add datatype iterator structure, to be used by ucp request

- src/ucs/datastruct/arbiter.c
- src/ucs/datastruct/arbiter.h
- test/gtest/ucs/test_arbiter.cc
Fix arbiter when the group, while being dispatched on the arbiter, is rescheduled to the another arbiter.
Fixes #5382
> UCS/ARBITER: Fix group rescheduling to another arbiter from dispatch

- src/uct/ib/base/ib_device.c
> UCT/IB: Check RoCE LAG without reading 'roce_lag_enable' from sysfs - v1.9.x

- test/gtest/Makefile.am
- test/gtest/ucs/test_conn_match.cc
- test/gtest/ucs/test_log.cc
Add tests for UCS conn match functionality
Cover UCS conn match functionality by gtests
Add tests for uint64_t address and implement extendable infrastructure
> GTEST/UCS: Add tests for conn match

- examples/ucp_hello_world.c
- src/ucs/sys/sock.c
- src/ucs/sys/sock.h
- src/uct/tcp/sockcm/sockcm_ep.c
- src/uct/tcp/sockcm/sockcm_iface.c
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_cm.c
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
- src/uct/tcp/tcp_sockcm_ep.c
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/uct/tcp/test_tcp.cc
Implement peer failure support (i.e. adding `UCT_IFACE_FLAG_ERRHANDLE_PEER_FAILURE`) in UCT/TCP
To support applications that require peer failure feature on commodity Ethernet-based systems
1. Refactor code
2. Call `uct_set_ep_failed()` where it's needed
> UCT/TCP: Implement peer failure support

- src/ucs/datastruct/arbiter.c
- src/ucs/datastruct/arbiter.h
- test/gtest/ucs/test_arbiter.cc
Fix the case when group, while being dispatched on the arbiter, is rescheduled to the another arbiter.
Fixes #5382  
cherry-picked from #5422
> UCS/ARBITER: Fix group rescheduling to another arbiter from dispatch - v1.9.x

- src/ucp/tag/rndv.c
- src/uct/sm/scopy/knem/knem_md.c
- test/gtest/ucp/test_ucp_tag.cc
- there is incorrect assert which prevents fallback into
AM mode. Removed it.
> RNDV/LANE-COUNT: removed incorrect assert

- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_iface.c
> UCT/IB: Workaround rdma-core issue of calling rand() from ibv_create_ah - v1.9.x

- test/gtest/ucs/test_conn_match.cc
Always do cleanup/init when initializing new address length
Fix possible failures when same address length is used
Fixes https://github.com/openucx/ucx/pull/5429#issuecomment-660525625
remove the check for address length that was before and currently provided by the test
> GTEST/UCS: Fix possible failures when same address length is used

- src/uct/ib/mlx5/ib_mlx5.h
- src/uct/ib/mlx5/ib_mlx5.inl
- src/uct/ib/mlx5/ib_mlx5_log.c
- src/uct/ib/mlx5/ib_mlx5_log.h
Add function to dump AV
This function will be used in UCT/IB/UD/MLX5 transport to print EP peer address in UCS/CONN_MATCH
Move code of printing BASE AV and GRH AV from `uct_ib_mlx5_dump_dgram()` to `uct_ib_mlx5_av_dump()` that will be exposed to the all IB functions
> UCT/IB/MLX5: Add function to dump AV

- src/ucp/wireup/ep_match.c
- src/ucs/datastruct/conn_match.c
- src/ucs/datastruct/conn_match.h
- test/gtest/ucs/test_conn_match.cc
Update conn_match str operation to accept conn_match_ctx
It will be used by UCT/IB/UD/MLX5 for UCS/CONN_MATCH to check whether iface created on Ethernet device or not
1. Update `ucs_conn_match_address_str_t` to accept `conn_match_ctx`
2. Call `address_str` user's function with `conn_match_ctx` passed
3. Update UCP/WIREUP/EP_MATCH's `address_str` function
> UCS/DATASTRUCT: Update conn_match str operation to accept conn_match_ctx

- src/ucp/wireup/select.c
In some cases the number of lanes can exceed hard-coded limit, so print in error and don't add more lanes
(to be ported to v1.9.x as well)
> UCP/WIREUP: Check that number of lanes is within limit

- src/ucp/Makefile.am
- src/ucp/core/ucp_rkey.c
- src/ucp/core/ucp_rkey.h
- src/ucp/core/ucp_rkey.inl
- src/ucp/core/ucp_types.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/core/ucp_worker.inl
- test/gtest/ucp/test_ucp_proto.cc
Allow selecting protocols per remote memory type/mapping.
> UCP/WORKER: Add rkey configuration cache

- src/ucp/core/ucp_types.h
- src/ucs/sys/preprocessor.h
Enable token-paste of 3 elements by a single macro
1. Add UCS_PP_TOKENPASTE3 to preprocessor.h
2. Adjust indentation
3. Use UCS_PP_TOKENPASTE3() in ucp_types.h
> UCS/PREPROCESSOR: Add UCS_PP_TOKENPASTE3() macro

- src/ucm/mmap/install.c
- src/ucm/util/reloc.c
- src/ucp/wireup/select.c
- src/ucs/arch/cpu.c
- src/ucs/arch/x86_64/cpu.c
- src/ucs/sys/compiler_def.h
- src/ucs/sys/sys.c
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_tag_match.cc
- test/gtest/ucs/test_log.cc
Remove duplicate macro `ucs_array_size` and `ucs_static_array_size`
1. Convert all usages of `ucs_array_size` to `ucs_static_array_size`
2. Remove `ucs_array_size`
3. We have the remove the STATIC_ASSERT from the macro, to make it usable from STATIC_ASSERT, e.g `UCS_STATIC_ASSERT(UCM_MMAP_REPORT_BUF_LEN <= UCS_ALLOCA_MAX_SIZE)` in https://github.com/openucx/ucx/blob/master/src/ucm/mmap/install.c#L231
> UCS: Unify ucs_static_array_size() macro

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_cm.c
- src/uct/tcp/tcp_ep.c
Rename `ctx_caps` EP field to `flags`.
This field will new used by TCP connection matching implementation to save the flag that informs whether the EP is on connection matching contest or not (i.e. on IFACE's EP list) - this is needed to save 64 bytes f memory tpo not keep `ucs_conn_matc_elem_t` as a separate field (it will be the `union` of `ucs_list_link_t` - for EP list and `ucs_conn_match_elem_t` - for connection matching).
Fixes https://github.com/openucx/ucx/pull/5294#discussion_r455757321 in a different way
1. Remove `uct_tcp_ep_ctx_type_t` enumerator and declare its declarations as anonymous `enum`.
2. Rename `ctx_cps` to `flags` in EP structure.
3. Fixes all occurrences of former `*_CTX_TYPE_*` and `ctx_caps`.
> UCT/TCP: Rename ctx_caps to flags

- src/ucp/wireup/ep_match.c
- src/ucs/datastruct/conn_match.c
- src/ucs/datastruct/conn_match.h
- test/gtest/ucs/test_conn_match.cc
Introduce connection matching lookup operation:
```
ucs_conn_match_elem_t *
ucs_conn_match_get_elem(ucs_conn_match_ctx_t *conn_match_ctx,
const void *address, ucs_conn_sn_t conn_sn,
ucs_conn_match_queue_type_t conn_queue_type,
int delete_from_queue);
```
that is trying to find a concrete connection matching element (using the address and conn_sn parameters) in expected or unexpected or both queues.
Also, this function can remove a found element if this is requested.
UD implementation of connection matching requires to not retrieve (i.e. don't delete the element from the connection matching context), since CREQ could be re-sent by the peer and new Passive EP will be created. If lookup operation returns the EP when received CREQ, just use this EP (this EP could be in expected or unexpected …
> UCS/DATASTRUCT: Introduce connection matching lookup operation

- test/gtest/ucp/test_ucp_tag_match.cc
It may happen that sync_send can take more time than expected, and the test will be failed since the `completed` flag of the request is `false`.
Need to progress and wait for lag for some amount of time instead of just doing progress
Fix possible test failure if sync_send takes too long
Replace `short_progress_loop()` by `wait_for_flag(&my_send_req->completed)`
> GTEST/UCP: Fix possible test failure if sync_send takes too long

- src/ucs/sys/string.c
- src/ucs/sys/string.h
- src/ucs/sys/topo.c
- src/ucs/sys/topo.h
- test/gtest/ucs/test_topo.cc
- Use solution used for 1.6 for 1.9 as well to query distance between IB and GPU for example. 
- Tested only with cuda and IB devices
- This along with #5299 will be need in UCT/IB to penalize IB devices away from GPU for 1.9
> UCS/TOPO: distance query based on dev-path difference

- src/ucp/Makefile.am
- src/ucp/core/ucp_ep.c
- src/ucp/proto/rndv.c
- src/ucp/proto/rndv.h
- src/ucp/tag/probe.c
- src/ucp/tag/tag_rndv.h
Move common rendezvous protocol files from `tag` to `proto` folder
Rendezvous will be used by several protocols, not tag only
> UCP/RNDV: Move common rndv files to proto dir

- src/ucs/debug/memtrack.c
- src/ucs/debug/memtrack.h
- test/gtest/ucs/test_memtrack.cc
Signed-off-by: Alex Margolin <alex.margolin@huawei.com>
This PR adds a new function: `ucs_posix_memalign_realloc()`. The arguments are the same as in the existing `ucs_posix_memalign()`.
This function is necessary because realloc() doesn't guarantee the alignment will be kept, so If a user wants to extend (or shrink) a buffer resulting from `ucs_posix_memalign()` there's no simple way to do this. I plan to use it in a future contribution related to shared-memory communication.
The call uses `realloc()` to both try and change the buffer size "in place", and to update the size stored in its entry. If the realloc doesn't keep the alignment - we call another `ucs_posix_memalign()` and copy the buffer.
> UCS: added posix_memalign_realloc()

- examples/ucp_hello_world.c
- src/ucp/api/ucp.h
- src/ucp/core/ucp_context.h
- src/ucp/stream/stream_recv.c
- src/ucp/stream/stream_send.c
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
- src/ucs/memory/memory_type.h
In some cases, SW layer above UCX has memory type information for allocations.  In this PR, adding an ability to pass the memory type information with UCP NBX API  if it is already known to the caller.
> UCP/API: Add flag to pass buffer memory type with UCP NBX API

- src/ucp/api/ucp.h
- fixed params specs for ucp_put_nbx and ucp_get_nbx calls
(cherry picked from commit 950573dd2a17bbf40607e07b28ecd59f3e123a2a)
backport from https://github.com/openucx/ucx/pull/5455
> DOCS/PUT-GET-NBX: fixed params specs - v1.9

- src/ucp/wireup/ep_match.c
- src/ucs/datastruct/conn_match.c
- src/ucs/datastruct/conn_match.h
- src/ucs/datastruct/hlist.h
- test/gtest/ucs/test_conn_match.cc
- test/gtest/ucs/test_datatype.cc
Introduce purge_cb to release elements during `ucs_conn_match_cleanup()`.
This will be needed by TCP to release EPs that were allocated as internal ones and don't appear in iface's EP list.
1. `purge_cb`  will control behavior - if specified, will clean the queue thru the callback, otherwise - print the diagnostics
2. Add gtest for purge case
> UCS/DATASTRUCT: Introduce purge_cb to release elements

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_cm.c
- src/uct/tcp/tcp_ep.c
Don't log error in some cases when CM event couldn't be sent.
e.g. EP could be found in hash during creating new EP from API, we send CONN_REQ to the peer thru the existing socket and it could fail, since the connection was closed by the peer a bit earlier. So, we should not log the error and just create new EP
Update `uct_tcp_cm_send_event()` to accept a parameter that shows whether we should log an error or not depending on a decision of the caller of the function.
> UCT/TCP: Don't log error in some cases when CM event couldn't be sent

- src/ucp/api/ucp.h
- src/ucp/core/ucp_mm.c
- src/ucs/memory/memory_type.h
- test/gtest/ucp/test_ucp_mmap.cc
In some cases, SW layer above UCX has memory type information for allocations. we have a use case(nccl/ucx-rma), where optimized ucx memory type detection using memtype cache is not working because of the cuda allocations are from cudaruntime statically linked library.  In this scenario, workaround is to disable the memtype cache.
In this PR, adding an option to pass the memory type information with ucp_mem_map() API, if this information is already known to the user.
> UCP/API: Add flag to pass memory type info in ucp_mem_map() API

- test/gtest/ucp/test_ucp_am.cc
- test/gtest/ucp/test_ucp_atomic.cc
- test/gtest/ucp/test_ucp_fence.cc
- test/gtest/ucp/test_ucp_mem_type.cc
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_rma.cc
- test/gtest/ucp/test_ucp_rma_mt.cc
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_stream.cc
- test/gtest/ucp/test_ucp_tag.cc
- test/gtest/ucp/test_ucp_wireup.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/ucp/ucp_test.h
Preparation for adding 'request_release' method to ucp_test class
> TEST/UCP: Rename ucp_test::wait() to request_wait()

- src/tools/perf/lib/ucp_tests.cc
- src/tools/perf/perftest.c
1. Progress responder on PUT unidir test until the last data isn't arrived
2. Add a missed description for `-o` option
1. To fix performance report for TLs with SW implementation of RMA - e.g. UD and TCP
Fixes #5396 
2. To provide information about all options
1. Applicable only for PUT unidir test: increment current iter number to reserve it for the last PUT operation, after sending all PUTs with sn=0, send the  last with sn=1. Responder waits for sn=1 and progress UCP worker.
2. Add `print()` for `-o` option
> TOOLS/PERF: Progress responder on PUT unidir test until the last data isn't arrived

- src/ucs/Makefile.am
- src/ucs/datastruct/array.h
- src/ucs/datastruct/array.inl
- test/gtest/ucs/test_datatype.cc
- Use as common code for growing arrays
- Implement string_buffer on top of 'array', so it could be used for static buffers as well (no need to malloc/free)
> UCS/DATASTRUCT/TEST: Add dynamic/fixed array data structure

- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
When get_zcopy() is completed, we need to mark the memory as valgrind-define. Currently it's done only for get_copy().
Save a copy of the the original IO vector on the RC send operation and mark all its segments as defined when completed.
> UCT/IB/VALGRIND: Set memory as defined for get_zcopy() operations

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/mlx5/ib_mlx5.c
- src/uct/ib/rc/accel/rc_mlx5_common.c
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- test/gtest/uct/ib/test_ib_xfer.cc
Make sure TX_INLINE_RESP=0 will set get.min_zcopy=1
> UCT/IB/MLX5: Fix TX_INLINE_RESP=0 behavior and add tests for it

- src/ucm/cuda/cudamem.c
- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_device.h
- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
Adds uct function to get IB device bus id from device path. Then, similar to numa_latency, adds cuda_latency overhead. This way, if a cuda device context is detected during NIC selection then the NIC closest to the cuda device will be picked.
> UCT/IB: detect cuda context and assign cuda_latency penalization - v1.9.x

- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/accel/ud_mlx5.h
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/verbs/ud_verbs.c
- src/uct/ib/ud/verbs/ud_verbs.h
Refactor UD code to prepare it for UCS/CONN_MATCH
This is needed for easy adoption for UCS/CONN_MATCH
Also, it reduces code duplication and fixes code style violations
1. Introduce `ep_peer_address` structures in Verbs and MLX5
2. Introduce `get_peer_address` to get peer address from IB device and IB iface address
3. Move setting peer address to EP and sending CREQ control message to the UD/BASE code
4. Move setting peer address to the EP to UD/BASE code
5. Minor code style fixes (a declaration with initialization goes first, alignments and etc)
> UCT/IB/UD: Refactor UD code to prepare it for UCS/CONN_MATCH

- buildlib/tests.yml
- src/uct/ib/ud/base/ud_ep.c
Fix sporadic UD timeouts, when resends of WIREUP_MSG are not processed since the UD timer is disabled initially.
ACK with ACK-request flags, same as resends, must be sent with SOLICITED flag to wake the remote interface.
> UCT/UD: Send ACK request with SOLICITED flag

- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/verbs/rc_verbs.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- test/gtest/common/test_obj_size.cc
Fixes #5318 and https://github.com/open-mpi/ompi/issues/7968
1. Create on-demand dummy region for dummy RDMA_WRITE just to flush communications
2. Exchange region address and rkey during connection setup of rc_verbs transport
3. flush by RDMA_WRITE(length=1)
> UCT/RC/VERBS: Use non-empty RDMA_WRITE for endpoint flush

- examples/ucp_client_server.c
- src/ucp/api/ucp.h
- src/ucp/api/ucp_def.h
- src/ucp/core/ucp_am.c
Adding new UCP AM API with rendezvous protocol support. 
Details:
- Definition of ucp_am_send_nbx
- Add operation flags to `ucp_request_param_t`
- Definition of ucp_am_recv_nbx (for obtaining rendezvous data)
- Definition of new data callback and its installer
- Allow sending user defined header together with active message
> UCP/API: Add new UCP AM API

- src/ucp/wireup/wireup_cm.c
remote disconnect progress should ignore UCP_EP_FLAG_CLOSE_REQ_VALID on failed EP if the EP is closed
newly implemented TCP error handling is able to report errors on flushed EPs if remote EP is closed.
> UCP/CM: ignore UCP_EP_FLAG_CLOSE_REQ_VALID on failed EP

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/wireup.c
Print CM component name for CM lane
to fix printed info
before:
```
[1596053355.113290] [r-vmb-ppc-jenkins:20139:0]         wireup.c:913  UCX  DEBUG ep 0x3fffb5ae0000: am_lane 1 wireup_lane 255 reachable_mds 0x2
[1596053355.113295] [r-vmb-ppc-jenkins:20139:0]         wireup.c:919  UCX  DEBUG ep 0x3fffb5ae0000: lane[0]: 255:/.0 md[0]                     -> addr[0].md[255]/posix
[1596053355.113299] [r-vmb-ppc-jenkins:20139:0]         wireup.c:919  UCX  DEBUG ep 0x3fffb5ae0000: lane[1]:  2:rc_verbs/mlx5_1:1.0 md[1]     -> addr[0].md[1]/ib       rma_bw#0 am am_bw#0
```
after:
```
[1596198613.229554] [r-vmb-ppc-jenkins:21440:0]         wireup.c:928  UCX  DEBUG ep 0x3fff7f3a0000: am_lane 1 wireup_lane <none> cm_lane 0 reachable_mds 0x2
[1596198613.229559] [r-vmb-ppc-jenkins:21440:0] …
```
> UCP/WIREUP: Print CM component name for CM lane

- src/ucs/arch/aarch64/cpu.h
Defines the `ucs_aarch64_dsb(_op)` macro.
Bugfix for #5500 .
> UCS: ucs_aarch64_dsb(_op) definition added to fix bug

- src/ucm/Makefile.am
- src/ucm/malloc/malloc_hook.c
- src/ucm/util/khash_safe.h
- src/ucm/util/reloc.c
1. The hash table for dl symbols should not use malloc/free because it can modify those symbols
2. In some cases the previous value from libucm.so may not be correct because of points to free@plt of the main program. This leads to infinite recursion because we patched the main program to call ucm_free() instead.
The fix is to take original free pointer from main program before we patch it to call ucm_free(). Only if it doesn't exist we use libucm.so.
> Memory hooks fixes

- src/ucp/api/ucp.h
Fix compilation errors when using `ucp_dt_make_iov()` in C++ code
> UCP/API: Cast ucp_dt_make_iov() to ucp_datatype_t

- src/uct/base/uct_iface.h
- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_def.h
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/base/ud_log.c
- src/uct/ib/ud/verbs/ud_verbs.c
- test/gtest/uct/ib/test_ud.cc
- test/gtest/uct/ib/test_ud_ds.cc
Implement connection matching
To reduce duplication of connection matching functionalities between UCP, TCP, UD
Re-use code form UCS/CONN_MATCH
> UCT/IB/UD: Implement connection matching

- src/ucp/core/ucp_am.c
- src/ucp/proto/rndv.c
- src/ucp/tag/eager_rcv.c
- src/ucs/async/async.c
- src/ucs/sys/sock.c
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/tcp/tcp_ep.c
Fixing build issue
GCC 9.3.1 on Fedora 30 (aarch64) fails with multiple warnings
complaining about usage of uninitialized variables.
Configure command line: `configure --enable-compiler-opt=g`
> UCS/UCT/UCP: Fixing compilation warning

- src/ucs/arch/aarch64/cpu.h
Affects performance. Optimized the UCS `clear_cache` routine for aarch64 by reading cache-coherency bits to determine if cache invalidations are necessary.
This optimization speeds up clear_cache significantly. 
Used the `CTR_EL0` register to determine if the I-cache and D-cache are coherent. If they are, some of the cache flush instructions and DSB can be safely skipped. Used the Arm ARM as a reference.
> UCS: Improve clear_cache performance for aarch64

- src/ucs/arch/aarch64/cpu.h
Backporting aarch64 dsb bugfix
Backport to v1.9.x
> UCS: ucs_aarch64_dsb(_op) definition added to fix bug - v1.9.x

- src/ucs/debug/memtrack.c
- test/gtest/ucm/malloc_hook.cc
- test/gtest/uct/uct_test.cc
- test/mpi/test_memhooks.c
Only include malloc.h when it works and needed.
Same as #4000. Some OSes don't have `malloc.h`. 
Add `#ifdef` check
macOS doesn't have `malloc_usable_size`. I'll use an alternative function on another PR(Later).
> UCS/DEBUG: Only include malloc.h when it works and needed.

- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/verbs/rc_verbs.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- test/gtest/common/test_obj_size.cc
> UCT/RC/VERBS: Use non-empty RDMA_WRITE for endpoint flush - v1.9.x

- src/ucs/arch/aarch64/cpu.h
Backport to v1.9.x aarch64 `clear_cache` optimization 
backport
> UCS aarch64 clear cache optimization for v1.9.x

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_worker.c
- test/gtest/ucp/test_ucp_am.cc
Add support for maximal AM header size worker attribute. 
User will be able to query worker for maximum header size which can be used with AM API.
> UCP/AM: Add max_am_hdr worker attribute

- src/ucs/sys/sock.c
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_cm.c
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
Implement connection matching
To reduce duplication of connection matching functionalities between UCP, TCP, UD
Re-use code form UCS/CONN_MATCH
> UCT/TCP: Implement connection matching

- examples/ucp_client_server.c
- src/ucp/api/ucp.h
- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_worker.h
- test/gtest/ucp/test_ucp_am.cc
- Rename `ucp_am_handler_attrs_field` enum to `ucp_am_handler_params_field` (and *ATTR_FIELD* enum values to *PARAM_FIELD*) for `ucp_worker_set_am_recv_handler`. Please note that these names are changed for **unreleased** API.
- Implement `ucp_worker_set_am_recv_handler`
- Add test and reorg AM tests to have common base class for legacy and new AM APIs
> UCP/AM: Implementation of ucp_worker_set_am_recv_handler

- src/ucm/event/event.c
This PR uses a portable `printf` format like `PRId64` instead of `%ld`.
Same as #5547 reason. (for porting macOS)
Fix the following error on macOS.
`off_t` defined as `long long` on macOS. But it defined as `long int` on Linux.
Please see detail https://github.com/hiroyuki-sato/ucx/issues/30
```
Making all in .
CC       event/libucm_la-event.lo
event/event.c:173:46: error: format specifies type 'long' but the argument has
type 'off_t' (aka 'long long') [-Werror,-Wformat]
addr, length, prot, flags, fd, offset);
^~~~~~
/path/to/ucx/src/ucm/util/log.h:31:76: note: expanded
from macro 'ucm_trace'
......) ucm_log(UCS_LOG_LEVEL_TRACE, _message, ## __VA_ARGS__)
~~~~~~~~     ^~~~~~~~~~~
/path/to/ucx/src/ucm/util/log.h:22:22: note: expanded
from macro 'ucm_log'
^~~~~~~~~~~
```
Use `PRId64` instead …
> UCM/EVENT: Cast off_t as long data type

- src/uct/base/uct_cm.c
- src/uct/base/uct_md.c
- src/uct/sm/mm/base/mm_ep.c
- src/uct/sm/mm/base/mm_iface.c
- src/uct/sm/self/self.c
- src/uct/tcp/sockcm/sockcm_iface.c
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_sockcm_ep.c
This PR uses a portable `printf` format like `PRIx64` instead of `%llx`.
As discussed #5514, I'm porting OpenUCX to macOS.
`uint64_t` in macOS use `unsigned long long` instead of Linux.
(Linux use `unsigned long int`)
So, It reports format errors like the following.
This PR fix these errors.
```
base/uct_cm.c:118:19: error: format specifies type 'unsigned long' but the
argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
params->field_mask);
^~~~~~~~~~~~~~~~~~
```
| Before | After | Note |
|--------|-----|------|
| %lx | PRIx64 | |
| %zu | PRIu64 | these variable defined as `uint64_t` not `size_t` |
> UCT: Use portable format string like PRIx64.

- src/ucs/datastruct/conn_match.c
- src/ucs/sys/topo.c
This PR uses a portable `printf` format like `PRId64` instead of `%ld`.
Same as #5547 and #5548 reason. (for porting macOS)
Use `PRId64` instead of `%ld`
> UCS: Use portable format string like PRIu64

- src/ucp/core/ucp_mm.c
- src/ucp/core/ucp_request.inl
- src/ucp/stream/stream_recv.c
- src/ucp/stream/stream_send.c
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
- Define inline func for getting memory type from `ucp_request_param_t`, like it is done for other param fields
- Minor cleanups (use existing inline funcs where it is missing)
- Code cleanup
- To be reused in other APIs: AM, Stream
> UCP: Define inline func for mem_type init from params

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_mm.c
- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.inl
- src/ucp/core/ucp_rkey.c
- src/ucp/core/ucp_rkey.h
- src/ucp/dt/dt.inl
- src/ucp/proto/proto_common.c
- src/ucp/proto/rndv.c
- src/ucp/rma/amo_send.c
- src/ucp/rma/amo_sw.c
- src/ucp/rma/rma_sw.c
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/tag_match.c
- src/ucp/tag/tag_send.c
- src/ucp/wireup/address.c
- src/ucp/wireup/ep_match.c
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- test/gtest/common/test.h
This PR uses a portable printf format like `PRIx64` instead of `%lx.`
Same as #5547, #5548 and #5549 reason. (for porting macOS)
For fixing https://github.com/hiroyuki-sato/ucx/issues/38
Use `PTRx64` and `PTRxPTR` instead of `%lx`.
> UCP: Use portable format string like PRIx64.

- src/ucs/datastruct/hlist.h
- test/gtest/ucs/test_datatype.cc
add `ucs_hlist_for_each_extract_if`
syntax sugar if list is used like queue
> UCS/HLIST: add ucs_hlist_for_each_extract_if

- src/ucs/Makefile.am
- src/ucs/datastruct/ptr_map.h
- src/ucs/datastruct/ptr_map.inl
- test/gtest/ucs/test_datatype.cc
add ucs_ptr_map_t data structure
to use ptr keys instead of raw pointers in wire protocols to make them more secure
> UCS: add ucs_ptr_map_t data structure

- src/ucp/core/ucp_am.c
- src/ucp/stream/stream_send.c
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
Change function datatype from `uintptr_t` -> `ucp_datatype_t`
For fixing this compiler error.
* CC: Apple clang version 11.0.3
* OS: macOS 10.15.6
```
CC       core/libucp_la-ucp_am.lo
core/ucp_am.c:522:36: error: conflicting types for 'ucp_am_send_nb'
UCS_PROFILE_FUNC(ucs_status_ptr_t, ucp_am_send_nb,
^
/path/to/ucx/src/ucp/api/ucp.h:2718:18: note: previous
declaration is here
ucs_status_ptr_t ucp_am_send_nb(ucp_ep_h ep, uint16_t id,
^
1 error generated.
```
Replace `uintptr_t` -> `ucp_datatype_t`
> UCP: uintptr_t -> ucp_datatype_t for avoiding compiler error

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_request.h
- src/ucp/proto/rndv.c
- src/ucp/proto/rndv.h
- src/ucp/tag/offload.c
Improving out-of-the-box behavior for cuda transfers
-  Default try GET protocol for CUDA and fallback to pipeline protocol if GET protocol fails
-  Option to tune sender-side pipelining scheme 
The current default rndv scheme for CUDA transfers is to use sender-side pipelining to overcome GPUDirectRDMA performance limitation on architecture where GPUs are connected to CPU socket directly.
But, now most of the GPU system architectures are designed where GPU and NIC are connected to same PCIe Switch ( Ex: all DGX systems, different vendor GPU server architectures). we are recommending users set `UCX_RNDV_SCHEME=get_zcopy` explicitly inorder to get an optimal GPUDirectRDMA performance on these architectures.  And also we do not have an optimal fallback if GET protocol fails (ex  GPUs …
> UCP/RNDV/CUDA: RNDV protocol improvements for CUDA

- bindings/java/src/main/java/org/openucx/jucx/UcxParams.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java
- bindings/java/src/main/native/endpoint.cc
- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/main/native/jucx_common_def.h
- bindings/java/src/main/native/worker.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Support of IOV data type operation for send/recv tagged and stream.
To match many-to-many API in SparkUCX. 
TODO:
- Switch at some point to nbx API
@abellina FYI
> JUCX: support IOV DT.

- buildlib/azure-pipelines-release.yml
GithubRelease task of the release-pipeline requires
'ReleaseNotes' attribute to be added
Signed-off-by: Yuriy Shestakov <yuriis@mellanox.com>
> AZP: Fixed GithubRelease task

- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
add ptr_map
the container will be used in wire protocols to exchange keys instead of raw pointers to EPs and requests
> UCP/WORKER: add ptr_map

- src/tools/perf/lib/uct_tests.cc
- src/tools/perf/perftest.c
This PR uses a portable printf format like `PRIu64` instead of `%ld.`
```
perftest.c:421:71: error: format specifies type 'long' but the argument has type
'ucx_perf_counter_t' (aka 'unsigned long long') [-Werror,-Wformat]
...number of iterations to run (%ld)\n", ctx->params.super.max_iter);
~~~      ^~~~~~~~~~~~~~~~~~~~~~~~~~
%llu
perftest.c:423:33: error: format specifies type 'size_t' (aka 'unsigned long')
but the argument has type 'ucx_perf_counter_t' (aka 'unsigned long long')
[-Werror,-Wformat]
ctx->params.super.warmup_iter);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
uct_tests.cc:506:61: error: format specifies type 'long' but the argument has
type 'ucx_perf_counter_t' (aka 'unsigned long long') [-Werror,-Wformat]
..."recv_sn=%d iters=%ld", sn, m_perf.current.iters);
~~~ …
```
> TOOLS/PERF: Use portable format string like PRIu64

- test/gtest/ucs/test_time.cc
Why: The test occasionally fails on lx2160a.
> TEST: Bumping up timer threshold

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/tag/tag_send.c
- test/gtest/ucp/test_ucp_am.cc
- Implementation of `ucp_am_send_nbx`. Only bcopy and short protocols, zcopy and rendezvous will follow
- Some basic tests on new AM API, more to be pushed in next PRs
Upstream of new AM API
> UCP/AM: Implement ucp_am_send_nbx (short and bcopy)

- test/gtest/common/test_helpers.h
Fixing:
implicit conversion from 'unsigned long' to 'double' changes value from
18446744073709551615 to 18446744073709551616
> TEST: Fixing clang 10 compile issue

- test/gtest/common/test_helpers.h
Fixing:
implicit conversion from 'unsigned long' to 'double' changes value from
18446744073709551615 to 18446744073709551616
> TEST: clang10 fix - v1.9.x

- buildlib/azure-pipelines-release.yml
GithubRelease task of the release-pipeline requires
`ReleaseNotesFile: NEWS` attribute to be added
Signed-off-by: Yuriy Shestakov <yuriis@mellanox.com>
> AZP: Fixed GithubRelease task - v1.9.x

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/select.c
- test/gtest/ucp/test_ucp_wireup.cc
- added initialization of lanes map which should be used
for keepalive
- added gtest for new functionality
- support of keepalive functionality on wireup level
- enumerate selected lanes & select one lane with FLUSH_CHECK caps per device
this PR depends from https://github.com/openucx/ucx/pull/5523 and https://github.com/openucx/ucx/pull/5554
> WIREUP/KEEPALIVE: added ep_check lanes map

- src/uct/tcp/tcp_ep.c
- fixed warning "unused variable" reported by PGI compiler
related to https://github.com/openucx/ucx/issues/5602
> TCP/COMPILE: fixed PGI compiler warning

- examples/ucp_client_server.c
- src/ucp/api/ucp.h
- src/ucp/api/ucp_def.h
- src/ucp/core/ucp_am.c
- Add worker parameter to `ucp_am_data_recv_nbx` for consistency
- Rename `ucp_am_data_recv_nbx` to `ucp_am_recv_nbx`
- Rename `ucp_am_data_recv_nbx_callback_t` to `ucp_am_recv_nbx_callback_t`
**Note:** This changes API, which was not released yet
> UCP/AM/API: Add worker param to ucp_am_data_recv_nbx

- src/ucp/core/ucp_ep.c
- src/ucp/wireup/select.c
Use `UCP_MAX_MDS` constant as md index for CM lane selection
It has to be `UCP_MAX_MDS` instead of `UCP_NULL_RESOURCE`
https://github.com/openucx/ucx/blob/a06839401fe3620c8ccd5f9c1b4cbc362d3025b2/src/ucp/core/ucp_ep.c#L71
`select_info.rsc_index`->`UCP_MAX_MDS` passing to `ucp_wireup_add_lane_desc`
> UCP/WIREUP: Use UCP_MAX_MDS as md index for CM lane selection

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
Add `is_equal` for config lanes for further re-use
It will be used to reduce code duplication in the following code:
https://github.com/openucx/ucx/blob/c65ba3b70a59d93775841506345a0076d1122b55/src/ucp/wireup/wireup.c#L317
Wrap comparing config lanes to the separate function that could be used in #5582
> UCP/CORE: Add is_equal for config lanes for further re-use

- src/ucp/core/ucp_ep.inl
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
Use `ucp_wireup_ep_connect` for P2P TLs in case of CM Client when creating UCT EPs
Reduces code duplication
Improves code sharing
Replace `uct_ep_create()` and code around this by calling `ucp_wireup_ep_connect()`
> UCP/WIREUP: Use ucp_wireup_ep_connect for P2P TLs in case of CM Client

- config/m4/compiler.m4
- suppressed diagnostic warning 1902: Use of a const variable in a constant
expression is nonstandard in C
- diagnostic is actual for new nvc compiler
- updated configuration scripts
fix for https://github.com/openucx/ucx/issues/5602
> CONFIG/BUILD: added diag suppress 1902

- src/ucp/core/ucp_ep.c
- in case if ucs_ptr_map_put failed there is dead object
left in list
> UCP/EP_CREATE: fixed potential all-eps list crash

- buildlib/az-distro-release.yml
Add releaseNotesSource/releaseNotesFile to
az-distro-release.yml pipeline
Signed-off-by: Yuriy Shestakov <yshestakov@mellanox.com>
> AZP: Fix GithubRelease@0 in az-distro-release.yml

- src/ucp/core/ucp_worker.c
This PR uses a portable printf format like `PRIx64` instead of `%lx.`
```
core/ucp_worker.c:1144:19: error: format specifies type 'unsigned long' but the argument has type
'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
tl_bitmap, ucs_popcount(tl_bitmap));
^~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:48:76: note: expanded from macro
'ucs_debug'
#define ucs_debug(_fmt, ...)        ucs_log(UCS_LOG_LEVEL_DEBUG, _fmt, ##  __VA_ARGS__)
~~~~      ^~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:41:76: note: expanded from macro
'ucs_log'
ucs_log_component(_level, &ucs_global_opts.log_component, _fmt, ## __VA_ARGS__); \
~~~~     ^~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:35:84: note: expanded from macro
'ucs_log_component'
...(ucs_log_level_t)(_level), _comp_log_config, _fmt, ## …
```
> UCP/CORE: Use portable format string like PRIx64.

- buildlib/az-io_demo.sh
Use relevant var for flow-control when running IO-DEMO
-  to avoid warning like below
```
2020-08-30T17:07:24.738459619Z [1598807243.968486] [swx-rdmz-ucx-roce-01:64049:0]         parser.c:1146 UCX  WARN  UCX_RC_TX_NUM_GET_OPS is deprecated (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
```
- to use flow control
> APP/IO_DEMO: Use relevant var for FC

- src/ucp/wireup/wireup_cm.c
Fix a typo in error message
Should be "too small" instead of "to small"
`to` -> `too`
> UCP/WIREUP: Fix a typo in error message

- src/ucs/sys/stubs.c
- src/ucs/sys/stubs.h
- src/uct/sm/mm/posix/mm_posix.c
- removed datatype spec from cb init
> SHM/POSIX: code beautify

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpRequest.java
- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
If native ID is negative error - construct UcpRequest object with nativeId = 0
We fist constructing `UcpRequest` object by passing  request to it. If request is error it's negative, we therefore anyway need to construct UcpRequest object, to invalidate it at: https://github.com/openucx/ucx/blob/master/bindings/java/src/main/native/jucx_common_def.cc#L282
`setNativeId` method has a check:
```
if (nativeId != null && nativeId < 0) {
throw new UcxException("UcxNativeStruct.setNativeId: invalid native pointer: "
+ nativeId);
}
```
> JUCX: fix constructing UcpRequest object on error.

- src/ucs/datastruct/ptr_array.c
- src/ucs/datastruct/ptr_array.h
- test/gtest/ucs/test_datatype.cc
An `is_empty()` function for ptr_array (and locked_ptr_array). Also - old, unused and misleading functions were replaced (`get_size`->`get_elem_count`).
Stumbled upon this while debugging #5580 - turns out is_empty was tested using `ptr_array->size`, which is just wrong.
ptr_array now counts elements (increment on insert, decrement on removal).
> UCS: ptr_array now counts elemets to test is_empty

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_ep.inl
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/core/ucp_worker.inl
- src/ucp/proto/proto_am.c
- src/ucp/proto/proto_am.h
- src/ucp/rma/amo_sw.c
- src/ucp/rma/rma.h
- src/ucp/rma/rma_sw.c
- src/ucp/rndv/rndv.c
- src/ucp/rndv/rndv.h
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/tag/offload.h
- src/ucs/datastruct/ptr_map.inl
use request ptr keys instead of raw pointers
to avoid access to deleted objects on error handling
using `ucs_ptr_map_t`
> UCP: use request ptr IDs instead of raw pointers

- src/ucp/proto/proto_common.c
- src/ucp/proto/proto_common.h
- src/ucp/proto/proto_multi.c
- src/ucp/proto/proto_multi.h
- src/ucp/proto/proto_single.c
- src/ucp/proto/proto_single.h
Reuse code between proto_single and proto_multi
> UCP/PROTO: Add common structure for protocol lane configuration

- src/ucp/proto/proto.h
- src/ucp/proto/proto_common.c
- src/ucp/proto/proto_common.h
- src/ucp/proto/proto_select.c
- src/ucp/tag/eager_multi.c
- src/ucp/tag/eager_single.c
Set priorities between different configured thresholds, e.g UCX_RNDV_THRESH vs. UCX_ZCOPY_THRESH
> UCP/PROTO: Set protocol configuration priorities

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpRequest.java
- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/main/native/jucx_common_def.h
- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Add sender tag to UcpRequest.
To get sender tag when using a wildcard mask. Needed for SparkUCX to not send worker tag.
> JUCX: add sender tag to UcpRequest.

- src/ucp/api/ucp.h
Update description of `ucp_atomic_op_nbx` - mention that only 1 element is supported so far
> UCP/AMO/API: Update ucp_atomic_op_nbx doc

- src/ucp/wireup/wireup_cm.c
Fix the following error on macOS.
```
wireup/wireup_cm.c:518:35: error: format specifies type 'size_t'
(aka 'unsigned long') but the argument has type 'uint64_t' (aka
'unsigned long long') [-Werror,-Wformat]
"(field_mask %zu)", remote_data->field_mask);
~~~    ^~~~~~~~~~~~~~~~~~~~~~~
%llu
/path/to/ucx/src/ucs/debug/log_def.h:44:75: note:
expanded from macro 'ucs_error'
......)        ucs_log(UCS_LOG_LEVEL_ERROR, _fmt, ## __VA_ARGS__)
~~~~     ^~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:41:76: note:
expanded from macro 'ucs_log'
...&ucs_global_opts.log_component, _fmt, ## __VA_ARGS__); \
~~~~     ^~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:35:84: note:
expanded from macro 'ucs_log_component'
...(ucs_log_level_t)(_level), _comp_log_config, _fmt, ## __VA_ARGS__); \
~~~~ …
```
> UCP/WIREUP: use portable print format PRIu64

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_request.h
- src/ucp/tag/offload.c
- src/ucp/tag/rndv.c
- src/ucp/tag/rndv.h
porting https://github.com/openucx/ucx/pull/5473 from master
> UCX/RNDV/CUDA: RNDV protocol improvements for CUDA - v1.9.x

- src/ucp/wireup/wireup_cm.c
Introduce a function to get the device index from TL bitmap.
To reduce code/functionality duplication.
Introduce a new function.
> UCP/WIREUP: Introduce a function to get device index from TL bitmap

- src/ucs/datastruct/hlist.h
- test/gtest/ucs/test_datatype.cc
fix access to freed memory in post condition if the element was freed in the body of loop
such scenario was reproduced in #5666 CI testing
> UCS/HLIST: fix ucs_hlist_for_each_extract_if

- config/m4/rocm.m4
Warn users if they are using an unsupported/older ROCm version
> CONFIG/M4: Detect and emit warning for releases older than ROCm-3.7

- examples/uct_hello_world.c
- src/tools/perf/lib/uct_tests.cc
- src/ucp/core/ucp_request.inl
- src/ucp/rma/amo_send.c
- src/ucp/rma/flush.c
- src/uct/api/uct.h
- src/uct/base/uct_iface.h
- src/uct/ugni/rdma/ugni_rdma_ep.c
- test/gtest/uct/ib/test_dc.cc
- test/gtest/uct/ib/test_rc.cc
- test/gtest/uct/ib/test_sockaddr.cc
- test/gtest/uct/test_amo.cc
- test/gtest/uct/test_amo_swap.cc
- test/gtest/uct/test_fence.cc
- test/gtest/uct/test_flush.cc
- test/gtest/uct/test_p2p_mix.cc
- test/gtest/uct/test_peer_failure.cc
- test/gtest/uct/test_pending.cc
- test/gtest/uct/test_stats.cc
- test/gtest/uct/test_tag.cc
- test/gtest/uct/test_zcopy_comp.cc
- test/gtest/uct/uct_p2p_test.cc
add uct_completion.status
to be able to report first occurred error in the end. for example, without the change, in case if fragmented protocol is failed in the middle but last fragment is completed with OK, the whole request will be completed successfully that's incorrect.
> UCT/API: add uct_completion.status

- src/uct/ib/rc/accel/rc_mlx5_devx.c
> UCT/IB/MLX5: Set udp.sport only for RoCEv2

- .gitignore
ignore generated files in the docs directory
1a19352abe3a8173221c62cc8894c9be067998c8 renamed `doc` folter to `docs`
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
docs/doxygen-doc/
docs/doxygen/header.tex
docs/uml/ucp.pdf
docs/uml/uct.pdf
docs/uml/uml.tag
```
Update `.gitignore`
> GITIGNORE: ignore generated files in the docs directory

- src/uct/ib/rc/accel/rc_mlx5_devx.c
> UCT/IB/MLX5: Set udp.sport only for RoCEv2 - v1.9.x

- src/ucm/configure.m4
This PR doesn't change the current behavior.
UCM_MODULE_LDFLAGS setting per OSes
For porting UCX to macOS, we need to set `UCM_MODULE_LDFLAGS` option. 
It doesn't the same setting as the Linux platform.
Switch that setting using `case` statement.
I'll add macOS setting later.
> UCM/CONFIGURE: UCM_MODULE_LDFLAGS setting per OSes

- src/ucp/rndv/rndv.c
Fixes https://github.com/openucx/ucx/issues/5646
It is incorrect to derive the existence of host bw lane from rma_bw_md_map, which is different than what is imposed by rma_bw_lanes.
> UCP/RNDV/CUDA: Fix host bw lane check for staging

- src/ucm/event/event.c
- src/ucm/mmap/install.c
- src/ucs/sys/sys.c
As a part of the effort of MacOS porting, this PR removes hard-dependency to `SHM_REMAP`, which is a Linux-specific feature. This PR closes #3945.
`SHM_REMAP` symbol for `shmat()` POSIX system call is a Linux-only extension. Towards MacOS port, the absence of `SHM_REMAP` must be detected and related UCX functions need to be modified.
According to the discussion [1], this PR makes the following modification.
(1) `ucm_shmat()`, `ucs_sysv_alloc()` functions return error if `SHM_REMAP` is specified or required.
(2) `ucm_fire_mmap_events_internal()` just ignores `SHM_REMAP`
Note that functions that call `ucm_shmat()` or `ucs_sysv_alloc()` must be able to handle errors caused by the absence of `SHM_REMAP`. However, AFAIK, in the cases, every status code is handled properly or the calls are …
> BUILD:MACOS Remove hard dependency to SHM_REMAP

- NEWS
> NEWS: News update for RC6

- buildlib/az-distro-release.yml
Signed-off-by: Yuriy Shestakov <yshestakov@gmail.com>
This PR increases timeout of distro build step in the `az-distro-release.yml` pipeline
> AZP: Increase timeout for distro build to 180 mins

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
Print a correct component information for the CM lane
Before the fix, it print rdmacm always, despite on the fact that we use tcpcm isntead
Now it looks like:
- TCP
```
[1599831835.240612] [r-vmb-ppc-jenkins:2463 :0]     ucp_worker.c:1694 UCX  INFO  ep_cfg[0]: tag(tcp/enP1p0s2); stream(tcp/enP1p0s2);
[1599831835.240620] [r-vmb-ppc-jenkins:2463 :0]         wireup.c:941  UCX  INFO  ep 0x3fffb5ec0000: am_lane 1 wireup_lane <none> cm_lane 0 reachable_mds 0x1
[1599831835.240626] [r-vmb-ppc-jenkins:2463 :0]         wireup.c:952  UCX  INFO  ep 0x3fffb5ec0000: lane[0]:  cm <unknown>
[1599831835.240631] [r-vmb-ppc-jenkins:2463 :0]         wireup.c:952  UCX  INFO  ep 0x3fffb5ec0000: lane[1]:  2:tcp/enP1p0s2.0 md[0]          -> addr[0].md[0]/tcp      rma_bw#0 am am_bw#0
[1599831835.247935] …
```
> UCP/WIREUP/CORE: Print a correct component information for the CM lane

- src/ucm/api/ucm.h
- src/ucm/util/sys.c
- src/ucs/config/ucm_opts.c
- on some systems dlopen(RTLD_LAZY) on loaded module may produce segfault
- removed RTLD_LAZY flag: it is not required because module
already loaded & initialized
> UCM/DLOPEN: fixed potential crash on prevent unload

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_am.h
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/rndv/rndv.c
- src/ucp/rndv/rndv.h
- src/ucp/tag/offload.c
- src/ucp/tag/probe.c
- src/ucp/tag/tag_match.inl
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_rndv.c
- src/ucp/tag/tag_rndv.h
- src/ucp/tag/tag_send.c
- src/ucp/wireup/address.h
- src/ucp/wireup/select.c
- src/ucp/wireup/signaling_ep.c
- src/ucp/wireup/wireup.h
- test/gtest/ucp/test_ucp_am.cc
Rendezvous protocol support for AM.
To be done in next PRs:
- support UCP_AM_SEND_EAGER/RNDV flags
- send ATS if no recv invoked, but RTS released
- more tests
- CPU mem support
> UCP/AM: Initial rndv support

- src/uct/base/uct_iface.h
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
Fix error handling during connection establishment in UCT/TCP
The following situation can happen:
Assume that we have one peer only.
The 2 epoll operations were read (the 1st - `CONN_REQ` event for `accept_fd`, the 2nd - the receive data for `connect_fd`).
During handling `CONN_REQ` event, the connection deduplication algorithm chooses to use `connect_fd` instead of `accept_fd`. Then, `connect_fd` sends `CONN_ACK` event, but it fails since the peer was closed using `ucp_ep_close_nbx()`. So, during handling this error, `uct_set_ep_failed()` is called and `connect_fd` is closed and EP is destroyed. Continue handling events from epoll, but the 2nd event is for already destroyed EP. So, here we are dereferencing already destroyed EP.
If connection problem is detected during send/recv by TCP …
> UCT/TCP: Fix error handling during connection establishment

- src/ucp/core/ucp_worker.c
initialize completion status of discard ep
found by CI/valgrind in #5711
added missed struct field initialization
> UCP: initialize completion status of discard ep

- src/ucp/proto/proto_am.inl
- src/uct/tcp/tcp_ep.c
Fix error handling in case of AM Zcopy failed
1. If EP AM Zcopy operation failed in-place (i.e. error was returned from `uct_ep_am_zcopy()`), UCP has to complete the request.
2. TCP has to return the same error from the EP send operation as it passes to the user error handling callback, i.e. `UCS_ERR_ENDPOINT_TIMEOUT`.
Fixes #5704
1. Call user completion calbback if error was returned from `uct_ep_am_zcopy()` in-place.
2. Translate error status to `UCS_ERR_ENDPOINT_TIMEOUT` if error callback was specified by the user.
> UCP/PROTO/UCT/TCP: Fix error handling in case of AM Zcopy failed

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/dc/dc_mlx5_ep.h
- src/uct/ib/rc/accel/rc_mlx5.h
- src/uct/ib/rc/accel/rc_mlx5.inl
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- src/uct/ib/rc/verbs/rc_verbs_impl.h
- test/gtest/uct/ib/test_dc.cc
- test/gtest/uct/ib/test_rc.cc
- test/gtest/uct/ib/test_rc.h
Check RDMA READ resources for any API send operation
To avoid reordering. For instance if some AM sends added to the pending queue right after the get operation, these AM sends would be blocked until get resources are available. While, if QP and CQ resources available, it is possible to send new AM, which 
would arrive OOO
> UCT/RC/DC: Fix ordering with RDMA_READ FC

- src/ucm/rocm/Makefile.am
link libucm_rocm.so to libhsa-runtime64.so
Fixes pytorch exit due to undefined symbol on some systems
python3: symbol lookup error: /work/ucx-1.9.0-rc3/lib/ucx/libucm_rocm.so.0: undefined symbol: hsa_amd_memory_pool_get_info
> UCM/ROCM: link libucm_rocm to libhsa-runtime64

- src/uct/ib/base/ib_md.c
Fix to UCX to fail with an error when GPUDirectRDMA plugin not installed and user forced enabled with option UCX_IB_GPU_DIRECT_RDMA=y
> UCX/IB/CUDA: Fix check when force enabling gpu direct rdma

- test/gtest/uct/test_md.cc
Remove unnecessary `include`
I want to fix the following error on macOS.
```
CXX      uct/gtest-test_md.o
uct/test_md.cc:20:10: fatal error: 'linux/sockios.h' file not found
#include <linux/sockios.h>
^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [uct/gtest-test_md.o] Error 1
```
Even on Linux, It seems that `#include <linux/sockios.h>` unnecessary in this `test_md.cc` file.
Remove `#include <linux/sockios.h>`
> TEST/GTEST/UCT: remove unnecessary include

- test/gtest/common/test_helpers.cc
Add a decleration of `extern char ** environ` in `test/gtest/common/test_helpers.cc`
This patch is in the context of MacOS porting.  In macOS darwin, users have to explicitly declare the `environ` variable.
In Linux, the declaration is included in `unistd.h` when `_GNU_SOURCE` is defined.
```
#define _GNU_SOURCE
#include <unistd.h>
```
NOTE: I believe this additional declaration is harmless on Linux platforms, so I didn't put any `ifdef` guard.
> TEST/GTEST: add explicit decleration of environ

- bindings/java/src/main/native/endpoint.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Fixes segfault when no UcpEpErrorHandler set, since it tries to throw an exception with error_msg string.
Need to pass error_msg as ` env->NewStringUTF(ucs_status_string(status))` to java methods, otherwise it incorrectly constructs java String from `const char *`
> JUCX: fix segfault in UcpErrorHandler.

- test/gtest/uct/test_stats.cc
This PR change `#include` order for fixing redefined macros. (`__STDC_FORMAT_MACROS`)
Fixing the following error.
```
CXX      uct/gtest-test_stats.o
In file included from uct/test_stats.cc:13:
./common/test.h:16:9: error: '__STDC_FORMAT_MACROS' macro redefined [-Werror,-Wmacro-redefined]
#define __STDC_FORMAT_MACROS 1
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/inttypes.h:248:12: note:
previous definition is here
^
1 error generated.
make[1]: *** [uct/gtest-test_stats.o] Error 1
```
* OS: macOS 10.15.6
* Compiler: Apple clang version 12.0.0 (clang-1200.0.32.2)
* OpenUCX: 66e54034231abbe4e3881592db773879c33fd250
`__STDC_FORMAT_MACROS` defined in `<common/test.h>` like the below.
```C
#define __STDC_FORMAT_MACROS 1
#include …
```
> TEST/GTEST/UCT: change #include order for fixing redefined macros.

- src/uct/ib/dc/dc_mlx5.c
- first in set of refactoring PR's in DCX initialization
- DCI creation is shifted to separate function to allow to
create single DCI
> DCX/DCI: minor initialization refactoring

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/rndv/rndv.c
- src/ucp/rndv/rndv.h
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/tag_match.inl
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
- test/gtest/ucp/test_ucp_am.cc
Second part of AM RNDV support:
- send ATS if processing of rts is failed, or data is not needed
- more tests, like testing all combinations of send and recv datatypes
-  some minor fixes
> UCP/AM: Rndv support part2

- src/ucs/sys/sys.c
UCS/SYS: optimization for namespace processing
in case of high PPN reading of system namespace may take
significant time. as workaround of issue added caching
of values
added caching of namespace values
> UCS/SYS: optimization for namespace processing

- test/gtest/ucp/test_ucp_wireup.cc
Pass a function (e.g. empty function) instead of NULL when error handling requested
There is a chance that error handling could be started in the keepalive test
`NULL` -> `reinterpret_cast<ucp_err_handler_cb_t>(ucs_empty_function)`
> GTEST/UCP: Pass a function instead of NULL when error handling requested

- src/ucs/datastruct/conn_match.c
- src/uct/tcp/tcp_cm.c
Fixes for connection matching functionality.
1. Need to pass correct address when getting string from it in TCP.
2. Don't print trailing ` )` in `ucs_conn_match_remove_elem()`.
1. Remove getting a pointer address from the `address` parameter.
2. Remove `" )"`.
> UCS/UCT: Fixes for connection matching functionality

- src/ucs/sys/sys.c
UCS/SYS: optimization for namespace processing
in case of high PPN reading of system namespace may take
significant time. as workaround of issue added caching
of values
added caching of namespace values
backport from https://github.com/openucx/ucx/pull/5755
> UCS/SYS: optimization for namespace processing - v1.9

- src/ucp/core/ucp_worker.c
- src/ucs/async/async.c
- src/ucs/async/async_fwd.h
- src/ucs/async/async_int.h
- src/ucs/async/signal.c
- src/ucs/async/thread.c
- src/ucs/sys/event_set.c
- src/ucs/sys/event_set.h
- src/uct/ib/base/ib_device.c
- src/uct/ib/cm/cm_iface.c
- src/uct/ib/rc/accel/rc_mlx5_devx.c
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/rdmacm/rdmacm_iface.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/tcp/sockcm/sockcm_ep.c
- src/uct/tcp/sockcm/sockcm_iface.c
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
- src/uct/tcp/tcp_listener.c
- src/uct/tcp/tcp_sockcm.c
- src/uct/tcp/tcp_sockcm.h
- src/uct/tcp/tcp_sockcm_ep.c
- src/uct/tcp/tcp_sockcm_ep.h
- src/uct/ugni/udt/ugni_udt_iface.c
- test/gtest/common/test_obj_size.cc
- test/gtest/ucs/test_async.cc
- test/gtest/ucs/test_event_set.cc
Use `ucs_event_set_type_t` (`uint8_t`) instead of `int`
To avoid casting int to `ucs_event_set_type_t`
To decrease UCT/TCP EP size by 8 bytes
Replace usage `int` by `ucs_event_set_type_t`
> UCS/UCT/UCP: Use ucs_event_set_type_t instead of int

- contrib/test_jenkins.sh
Fix http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/7308/pipeline/946
http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/7308/nodes/946/steps/954/log/?start=0
```
[2020-09-30T12:31:26.931Z] + echo '==== Running UCP client-server  ===='
...
[2020-09-30T12:31:26.931Z] + taskset -c 4 ./ucp_client_server -p 10002
...
[2020-09-30T12:31:42.085Z] + kill -9 4167
...
[2020-09-30T12:31:42.085Z] ==== Running 'run_io_demo' (task 1/4) ====
...
[2020-09-30T12:31:42.348Z] + taskset -c 4 ./test/apps/iodemo/io_demo -o write,read -d 128:4194304 -i 10000 -w 10 -p 10002
[2020-09-30T12:31:42.348Z] [UCX] created context 0x10024043dd0
[2020-09-30T12:31:42.348Z] [UCX] created worker 0x100240818a0
[2020-09-30T12:31:42.348Z] [1601469102.337746] …
```
> JENKINS: Set different TCP port number for each client/server test

- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/dc/dc_mlx5_ep.h
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- test/gtest/uct/ib/test_rc.cc
Add ordering checks for UCT AM APIs in RC transports. Check is not added for other communication functions, because ordering between them and AM funcs is not respected (others are not affected by  FC).
To avoid future changes which would ruin ordering between AM messages.
> UCT/RC: Check AM ordering

- src/uct/tcp/tcp_cm.c
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
Code cleanups and fixes for error handling
It may happen that we're destroying EP in iface_progress from am_handler, so, EP could be destroyed, but iface_progress still need to release RX resources for ut
Replace `uct_tcp_ep_destroy_internal()` by calling `uct_tcp_ep_set_failed()` that will do `uct_tcp_ep_destroy_internal()` from progress (if only RX capability)
> UCT/TCP: Code cleanups and fixes for error handling

- test/gtest/common/mem_buffer.cc
- test/gtest/common/mem_buffer.h
1. Don't instantiate GPU tests if Cuda/ROCm libraries are present, but GPU device is not present
2. Add more info to mem_buffer errors
> TEST/COMMON: mem_buffer class enhancements

- .gitignore
Signed-off-by: Artem Ryabov <artemry@mellanox.com>
Added .idea folder (JetBrains PyCharm and other JetBrains IDEs system files) into .gitignore.
For the convenience for those who uses JetBrains IDEs.
> GITIGNORE: Added JetBrains IDE files into .gitignore

- buildlib/docker-compose.yml
Signed-off-by: Artem Ryabov <artemry@mellanox.com>
Changed UCX docker-compose configs with proper network propagation. 
`network: host` lets propagate host network interfaces inside the docker environment (e.g. to allow connecting to the Internet from the docker). docker-compose configs itself are used to prepare UCX build/test docker environment e.g. for manual tests (see https://github.com/openucx/ucx/blob/master/buildlib/azure-pipelines.md#release-images for details).
> BUILD: fixed docker-compose configs with proper network propagation

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/core/ucp_worker.c
- src/ucp/proto/proto_am.inl
- src/ucp/proto/proto_common.inl
- src/ucp/rma/rma.inl
- src/ucp/rma/rma_send.c
- src/ucp/rndv/rndv.c
- src/ucp/stream/stream_send.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
discard lanes on failure and replace with dummy failed lane
do common part of error handling on UCP level and allow non-blocking resources clean up in UCT
> UCP/EP: discard lanes on failure

- docs/source/index.rst
> DOCS/INSTALL: Fix typo in install instructions

- src/uct/ib/ud/base/ud_iface.h
Fix printing an error about invalid AM Bcopy length
```
[1602139840.345824] [r-vmb-ppc-jenkins:25124:0]        ud_mlx5.c:379  UCX  ERROR Invalid am_bcopy length length: 4128 (expected: <= 1024)
```
Remove extra `length` from the string
> UCT/IB/UD: Fix printing an error about invalid AM Bcopy length

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- renamed flags UCT_RC_EP_FC_FLAG_*** to UCT_RC_EP_FLAG_FC_*** due to
flags moved into basic RC_EP structure
> UCT/RC/EP: flow control flags are renamed

- src/ucp/core/ucp_am.c
- test/gtest/ucp/test_ucp_am.cc
- Do not pass `UCP_AM_RECV_ATTR_FLAG_DATA` flag to AM recv callback in case of rendezvous, because it is mutually exclusive with `UCP_AM_RECV_ATTR_FLAG_RNDV` by API.
- Pass `UCP_AM_RECV_ATTR_FIELD_REPLY_EP` flag to AM recv callback  in case of rendezvous if it was requested by the sender.
> UCP/AM: Do not pass data flag to AM RX cb in case of rendezvous

- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/rma/amo_sw.c
- src/ucp/rma/rma.inl
- src/ucp/rma/rma_sw.c
- src/ucp/wireup/wireup_ep.c
- test/gtest/ucp/test_ucp_worker.cc
Cleanup worker discarding functionality
To prevent possible UCT EPs leaks that were scheduled on UCP worker discarding. But discarding of them wasn't completed on time (i.e. user doesn't wait for `ucp_worker_flush_nbx()` completion) and UCP worker was destroyed.
0. Change discarded UCT EP hash with set type to map type and make `ucp_request_t*` as a value of the element
1. Go through cbq and remove all occurrences of callback scheduled for the discard
2. Go through discarded UCT EP hash and destroy the UCT EPs and release UCP request and decrement `ucp_worker_t::flush_ops_count`
> UCP/WORKER/GTEST: Cleanup worker discarding functionality

- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- due to implementation of keepalive feature flush_mp memory
pool is going to be used for keepalive operations too
- renamed to fit more general usage
> RC/IFACE: flush_mp value is renamed to send_op_mp

- test/gtest/common/mem_buffer.cc
Fix build issue with Gtest and ROCm enabled
Fixes #5751 
Use hip* API instead of hsa_* (which is currently only available from inside the ROCm TLs)
> TEST/COMMON: fix ROCm build failure for mem_buffer test

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_ep.inl
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/core/ucp_worker.inl
- src/ucp/stream/stream_recv.c
- src/ucp/wireup/address.c
- src/ucp/wireup/address.h
- src/ucp/wireup/ep_match.c
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
Implement support for SHM/multi-lane in case of CM
If the connection was established thru CM (i.e. RDMACM or TCPCM), UCP EP config has lanes configured on the same device where CM is running on.
It means that SHM/CUDA/multi-lane couldn't be used in the current implementation.
This PR addresses this.
After CM flow, UCP EPs start WIREUP MSG protocol to exchange by all addresses and try to select lanes with the best available TLs.
WIREUP MSGs are sent through WIREUP lane (UCT EP that was created on the same device as CM). If after reconfiguration UCT EP for WIREUP lane isn't selected, change WIREUP lane to CM lane and hide UCT EP from WIREUP lane to the CM_WIREUP_EP/AUX_EP and use it for WIREUP MSGs.
> UCP/WIREUP: Implement support for SHM/multi-lane in case of CM

- src/tools/perf/lib/libperf.c
- src/ucp/core/ucp_rkey.c
- src/ucp/core/ucp_worker.c
- src/ucp/proto/proto_common.c
- src/ucp/rndv/rndv.c
- src/uct/api/uct.h
- src/uct/cuda/cuda_copy/cuda_copy_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.c
- src/uct/cuda/gdr_copy/gdr_copy_md.c
- src/uct/ib/base/ib_md.c
- src/uct/ib/rdmacm/rdmacm_md.c
- src/uct/rocm/copy/rocm_copy_md.c
- src/uct/rocm/gdr/rocm_gdr_md.c
- src/uct/rocm/ipc/rocm_ipc_md.c
- src/uct/sm/mm/base/mm_md.c
- src/uct/sm/scopy/cma/cma_md.c
- src/uct/sm/scopy/knem/knem_md.c
- src/uct/sm/self/self.c
- src/uct/tcp/sockcm/sockcm_md.c
- src/uct/tcp/tcp_md.c
- src/uct/ugni/base/ugni_md.c
- test/gtest/uct/test_p2p_mix.cc
- test/gtest/uct/test_stats.cc
- test/gtest/uct/test_zcopy_comp.cc
- test/gtest/uct/uct_p2p_test.cc
MD attributes allow MDs to access only a single memory type today which is an issue for transports like cuda_copy which can access HOST, CUDA, CUDA_MANAGED. This PR changes `md_attr.access_mem_type` to uint64_t along the lines of other members like `reg_mem_types` to address the above issue.
> UCT/API: allow transports to access multiple mem_types

- contrib/valgrind.supp
- src/ucp/proto/proto_common.c
- test/gtest/common/mem_buffer.cc
- it seems there are error detections improved in new valgrind-13
which cause false positives on CUDA 11 runtime
- suppressed
5dd99cf3035fa9f65cb5fb0785025fdb37c1e881 is cherry-picked from https://github.com/openucx/ucx/pull/5797
> GTEST/VALGRIND: fixed gtests failures on valgrind runtime

- src/ucp/wireup/wireup_cm.c
Handle connection request from uninitialized device.
cherry-picked from https://github.com/yosefe/ucx/pull/60
If listener is started on any address and device is configured after UCP initialization, client can try to connect to new available address but server is not able to handle it.
Print error and return unreachable status.
> UCP/WIREUP/CM: handle connection request from uninitialized device

- src/ucp/core/ucp_worker.h
Fix comment for UCT EP discard hash
Better documentation
`set to` -> `map of`
> UCP/CORE: Fix comment for UCT EP discard hash

- src/uct/ugni/udt/ugni_udt_iface.c
> UGNI: Fixing clang 11 warning

- src/ucp/proto/proto_common.c
This PR uses a portable printf format like `PRIu64` instead of `%ld.`
```
CC       proto/libucp_la-proto_common.lo
proto/proto_common.c:207:31: error: format specifies type 'unsigned long' but
the argument has type 'ucp_md_map_t' (aka 'unsigned long long')
[-Werror,-Wformat]
rkey_config_key->md_map);
^~~~~~~~~~~~~~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:49:75: note:
expanded from macro 'ucs_trace'
......)        ucs_log(UCS_LOG_LEVEL_TRACE, _fmt, ## __VA_ARGS__)
~~~~     ^~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:41:76: note:
expanded from macro 'ucs_log'
...&ucs_global_opts.log_component, _fmt, ## __VA_ARGS__); \
~~~~     ^~~~~~~~~~~
/path/to/ucx/src/ucs/debug/log_def.h:35:84: note:
expanded from macro 'ucs_log_component'
...(ucs_log_level_t)(_level), _comp_log_config, _fmt, …
```
> UCP/PROTO: use portable print format PRIx64

- bindings/java/pom.xml.in
Fixes #5811 
For java10+ need to add a special compiler arg `--add-exports java.base/sun.nio.ch=ALL-UNNAMED`
> JUCX: support build on java10+

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- test/gtest/ucp/test_ucp_sockaddr.cc
Introduce the test to check an equality of CM and WIREUP configs.
To test #5696.
The test does the following:
1. Creates EP using CM, does send-recv, saves its config.
2. Creates EP using  WIREUP, does send-recv, saves its config.
3. Compares configs.
> UCP/CORE/GTEST: Introduce the test to check an equality of CM and WIREUP configs

- src/ucp/core/ucp_request.h
Fix comment for a recv part of UCP request
Add `am_recv`, since it also uses receive part of UCP request
Add `am_recv` to the existing comment
> UCP/CORE: Fix comment for a recv part of UCP request

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- src/ucp/wireup/wireup_cm.c
Don't check reachability during CM phase
e.g. if SHM TLs are supported in CM (after adding `ERR_HANDLE_PEER_FAILURE` support), UCP will start failing to communicate between EPs created on different physical hosts (i.e. without shared memory), since it will try to use SHM TLs and think that they are reachable
When doing `is_reachable()`, check that `ep_init_flags` is CM phase and CM lane is configured to not check UCT reachability of TLs
> UCP/WIREUP: Don't check reachability during CM phase

- src/ucp/proto/proto_am.inl
- test/gtest/ucp/test_ucp_sockaddr.cc
When UCP AM is sent with `ucp_am_send_nbx`, user header does not change tx state of the data buffer. If just header is sent while wireup procedure is not finished yet, multi-lane bcopy protocol may be selected. But the data buffer state will remain zero, as no data is sent.
> UCP/AM/GTEST: Remove invalid assert

- src/ucp/api/ucp.h
Rename flags used by `ucp_am_send_nbx` for consistency with other flag names
> UCP/API/AM: Rename AM send flags for consistency with other flags

- src/ucp/core/ucp_request.h
- test/gtest/common/test_obj_size.cc
Reduce UCP request size
The 8 bytes will be used in #5821
Re-pack UCP request send the structure to use the hole created by the following fields (`pending_lane` + `lane` + `multi_lane_idx` = `24`)
> UCP/CORE: Reduce UCP request size

- contrib/test_jenkins.sh
CI: fix command find grep for large count of files
CI on Azure pipeline fail with 123 code on find grep
> AZP: fix command find grep for large count of files

- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/rma/flush.c
- src/ucp/rndv/rndv.c
- test/gtest/common/test_obj_size.cc
Reduce UCP request size (new approach).
The approach helps us to save 24 bytes.
The 16 bytes will be used in #5821 for hlist element on the common memory for both `send` and `recv` part of UCP request
now the biggest structures of send part of UCP request has the same size:
```
(gdb) p sizeof(((ucp_request_t*)0)->send.flush)
$1 = 32
(gdb) p sizeof(((ucp_request_t*)0)->send.rndv_get)
$2 = 32
(gdb) p sizeof(((ucp_request_t*)0)->send.msg_proto)
$3 = 32
```
1. Re-pack UCP request `send` structure to use the hole created by the following fields (pending_lane + lane + multi_lane_idx = 24).
2. Make `mem_type` as `uint8_t` instead of `ucs_mem_type_t` (that's is `enum` and equal to the `int` type).
3. Remove pointer to the super request from send protocols in `send` part of UCP request and move it …
> UCP/CORE: Reduce UCP request size (new approach)

- src/ucp/Makefile.am
- src/ucp/proto/proto_common.c
- src/ucp/proto/proto_common.h
- src/ucp/proto/proto_multi.c
- src/ucp/proto/proto_multi.inl
- src/ucp/proto/proto_single.c
- src/ucp/rma/get_am.c
- src/ucp/rma/get_offload.c
- src/ucp/rma/put_am.c
- src/ucp/rma/put_offload.c
- src/ucp/rma/rma.h
- src/ucp/rma/rma_send.c
- src/ucp/rma/rma_sw.c
- src/ucp/tag/eager_multi.c
- src/ucp/tag/eager_single.c
- test/gtest/ucp/test_ucp_rma.cc
Implement ucp_get* APIs over new protocols data-structures
* Implement protocol progress for get/am, get/offload.bcopy, get/offload/zcopy
* In ucp_get_nbx() [common function for all ucp_get* APIs] ,check if protocols are enabled, and if yes initialze and start the send request with new protocol progress functions
> UCP/RMA/TEST: Add new protocols for ucp_get operations

- src/ucp/rndv/rndv.c
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/offload.c
- src/ucp/tag/offload.h
- test/gtest/ucp/test_ucp_tag_offload.cc
1. Remove extra memory deregistration in RNDV flow. When get_zcopy protocol is used, need to deregister memory on `rndv_req` only (which points to the receive buffer as well). Can save tens of ns on certain patterns.
2. Deregister rreq buffer when SW RNDV arrives as expected HWTM message (plus gtest, which fails on assert without this change)
> UCP/RNDV/GTEST: RNDV optimization and HWTM bugfix

- src/ucp/core/ucp_am.c
Use internal UCX memcpy for AM eager flow 
Performance + profiling of memory copies
> UCP/AM: Use UCX memcpy for AM eager

- test/gtest/uct/tcp/test_tcp.cc
Serialize access to EP list.
Fixes #5846
Go through all EPs on iface with lock held, since EPs are created and inserted to the EP list from async thread during accepting a connection.
Use `UCS_ASYNC_BLOCK()`/`UCS_ASYNC_UNBLOCK`
> GTEST/UCT/TCP: Serialize access to EP list

- test/gtest/uct/test_stats.cc
Fix usage of `EXPECT_EQ`/`EXPECT_TRUE` macros.
1. An expected value has to go first in `EXPECT_EQ`.
2. Statements have to be wrapped by `(...)`.
1. Swap arguments passed to `EXPECT_EQ`.
2. Use `UCS_STATUS_IS_ERR()` auxiliary macro and `EXPECT_FALSE` instead of checking for `UCS_INPROGRESS`/`UCS_OK` directly.
> GTEST/UCT: Fix usage of EXPECT_* macros

- src/ucp/wireup/wireup.h
Reduce wireup msg by 3 bytes.
Possible reduce latency, when sending wireup messages.
Repalce `ucp_err_handling_mode_t` by `uint8_t`.
> UCP/WIREUP: Reduce wireup msg

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_cm.c
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
- test/gtest/common/test_obj_size.cc
Introduce CONNECT_TO_EP support in TCP
CONNECT_TO_EP is required for TCP to use it in CM
1. Move the starting TCP connection to the first flush/send invocation in order to make sure that `peer_conn_sn` is specified
2. Implement `CONNECT_TO_EP` support
3. Some bug-fixing
> UCT/TCP: Introduce CONNECT_TO_EP support

- test/gtest/ucp/test_ucp_am.cc
- test/gtest/ucp/test_ucp_atomic.cc
- test/gtest/ucp/test_ucp_context.cc
- test/gtest/ucp/test_ucp_fence.cc
- test/gtest/ucp/test_ucp_mem_type.cc
- test/gtest/ucp/test_ucp_mmap.cc
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_perf.cc
- test/gtest/ucp/test_ucp_proto.cc
- test/gtest/ucp/test_ucp_rma.cc
- test/gtest/ucp/test_ucp_rma_mt.cc
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_stream.cc
- test/gtest/ucp/test_ucp_tag.cc
- test/gtest/ucp/test_ucp_tag.h
- test/gtest/ucp/test_ucp_tag_match.cc
- test/gtest/ucp/test_ucp_tag_mem_type.cc
- test/gtest/ucp/test_ucp_tag_mt.cc
- test/gtest/ucp/test_ucp_tag_offload.cc
- test/gtest/ucp/test_ucp_tag_xfer.cc
- test/gtest/ucp/test_ucp_wakeup.cc
- test/gtest/ucp/test_ucp_wireup.cc
- test/gtest/ucp/test_ucp_worker.cc
- test/gtest/ucp/ucp_datatype.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/ucp/ucp_test.h
- reduce the amount of code in each test for creating different variants
- show the name of each variant when test is running:
```
[----------] 9 tests from rcx/test_ucp_am_nbx_rndv_dts
[ RUN      ] rcx/test_ucp_am_nbx_rndv_dts.rndv/1 <rc_x/contiguous,iov>
[       OK ] rcx/test_ucp_am_nbx_rndv_dts.rndv/1 (92 ms)
[ RUN      ] rcx/test_ucp_am_nbx_rndv_dts.rndv/5 <rc_x/iov,generic>
[       OK ] rcx/test_ucp_am_nbx_rndv_dts.rndv/5 (110 ms)
[ RUN      ] rcx/test_ucp_am_nbx_rndv_dts.rndv/3 <rc_x/iov,contiguous>
[       OK ] rcx/test_ucp_am_nbx_rndv_dts.rndv/3 (97 ms)
...
```
- allow having multiple variants and generating all possible combinations of them
- Add variants generator functions to ucp_test.h/cc
- Refactor existing UCP tests to use the new generators
> TEST/UCP: Enhance test variants

- src/ucp/wireup/wireup_ep.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- added flag UCT_RC_EP_FLAG_EP_CONNECT_TO_EP to identify
EP_2_EP mode
- added processing of this flag (set/clear)
- added evaluation of this flag in keepalive
> UCT/RC: added flag UCT_RC_EP_FLAG_EP_CONNECT_TO_EP

- bindings/java/pom.xml.in
use java.home system property instead of the JAVA_HOME.
To work on environments where `JAVA_HOME` is not set
Fixes #5858
> JUCX: javadoc use java.home system property instead of the JAVA_HOME.

- src/tools/perf/api/libperf.h
- src/tools/perf/lib/libperf.c
- src/tools/perf/perftest.c
add interrupt request support to perftest.
To select transports that support wake-up mechanism, that is used in apps like SparkUCX.
TODO: 
maybe to add `ucp_worker_wait()` in the progress loop to test the real wakeup penalties?
> PERF: add request interrupt feature support.

- src/ucm/bistro/bistro.c
- src/ucm/bistro/bistro_aarch64.c
- src/ucm/bistro/bistro_int.h
- src/ucm/bistro/bistro_x86_64.c
- src/ucm/bistro/bistro_x86_64.h
Fix race condition when UCX progress thread calls munmap() while UCX main thread installs malloc hooks
Patched munmap() before this PR:
```
(gdb) disas /r
Dump of assembler code for function munmap:
0x00007f78c7ade3f0 <+0>:    49 bb 30 b6 e1 c8 78 7f 00 00    movabs $0x7f78c8e1b630,%r11
0x00007f78c7ade3fa <+10>:    41 ff e3    jmpq   *%r11
0x00007f78c7ade3fd <+13>:    73 01    jae    0x7f78c7ade400 <munmap+16>
0x00007f78c7ade3ff <+15>:    c3    retq  
0x00007f78c7ade400 <+16>:    48 8b 0d 69 da 2c 00    mov    0x2cda69(%rip),%rcx        # 0x7f78c7dabe70
0x00007f78c7ade407 <+23>:    f7 d8    neg    %eax
0x00007f78c7ade409 <+25>:    64 89 01    mov    %eax,%fs:(%rcx)
0x00007f78c7ade40c <+28>:    48 83 c8 ff    or     $0xffffffffffffffff,%rax
0x00007f78c7ade410 <+32>:    c3    retq  
``` …
> UCM/BISTRO: Use relative jump instead of absolute jump

- src/uct/tcp/tcp_net.c
fix default route interface confirmation
@yosefe, Could you take a look when you get a chance? It seems that you are the author of this part.
**Update**: this change wil fail CI test. but I think the curren default route interface checking doesn't work properly.
It seems that the default route interface confirmation logic is incorrect.
* `sscanf` doesn't return `ret == 3` because `sscanf` checks two variables only.
* override `result_p` value if the interface is default.
* `ret == 2` instead of `ret == 3`
* return immediately when default interface find.
> UCT/TCP: fix default route interface confirmation

- src/ucp/rma/put_offload.c
Add remaining protocols for ucp_put* APIs over transports which support direct put operation
Implement initialization and progress functions for put/offload/short and put/offload/zcopy
depends on #5807
> UCP/RMA: Add put/offload/short and put/offload/zcopy protocols

- src/tools/info/ucx_info.c
- src/ucp/core/ucp_context.c
- src/ucs/config/global_opts.c
- src/ucs/config/parser.c
- src/ucs/config/parser.h
- src/ucs/config/ucm_opts.c
- src/uct/base/uct_component.h
- src/uct/base/uct_iface.h
- test/apps/test_dlopen_cfg_print.c
ucs_config_parser_print_all_opts prints options in given list.
pass list to UCS_CONFIG_REGISTER_TABLE_ENTRY and save this entry on given list.  
Will allow to use ucs_config_parser_print_all_opts in UCC. Separate config tables of UCX and UCC.
> UCS/PARSER: specify config list in register table entry

- src/ucp/core/ucp_am.c
Use short protocol for sending AM RTS when it fits the limit
Performance (see 200ns improvement on IO_DEMO with AM and 8K messages)
> UCP/AM: Use short for sending AM RTS when possible

- bindings/java/pom.xml.in
Sets different javadoc paths for different java versions.
As suggested [here](https://stackoverflow.com/q/57081473/3271168) should fix #5858
> JUCX: use different javadoc executbale path for different java versions.

- AUTHORS
- src/ucs/stats/stats.c
GCC will otherwise generate the following warning that is treated as error when configuring with `--enable-stats`:
```
CC       stats/libucs_la-stats.lo
In file included from ../src/ucs/sys/sys.h:19,
from ../../../src/ucs/stats/stats.c:18:
../../../src/ucs/stats/stats.c: In function 'ucs_stats_node_alloc':
src/ucs/debug/memtrack.h:136:52: error: 'filter_node' may be used uninitialized in this function [-Werror=maybe-uninitialized]
136 | #define ucs_free(_p)                               free(_p)
|                                                    ^~~~
../../../src/ucs/stats/stats.c:399:30: note: 'filter_node' was declared here
399 |     ucs_stats_filter_node_t *filter_node;
|                              ^~~~~~~~~~~
cc1: all warnings being treated as errors
```
Signed-off-by: Joseph …
> Fix potentially uninitialized pointer variable in ucs_stats_node_add

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_ep.inl
- src/ucp/core/ucp_listener.c
- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup_cm.c
Reduce the size of generic EP extension for further usage
Generic EP extension will be used by #5821 to have `ucs_hlist_head_t` for tracking UCP requests.
Introduce a pointer to a control extension that is placed in the generic extension. Control extension includes:
- local and remote IDs
- error callback
- union for `close_req` and `listener`
other fields are in generic extension, since they are could not be moved to a control extension (e.g. we have to have a mechanism to translate `flush_state` or `conn_match` to generic extension, or even to EP)
> UCP/CORE: Reduce size of generic EP extension for further usage

- buildlib/az-io_demo.sh
- test/apps/iodemo/io_demo.cc
- Fix `-l` option of IODEMO (client job timeout)
- Increase IODEMO iterations back in AZP, because it can be managed by timeout now
> TEST/IODEMO/AZP: Fix client tmo option in IODEMO

- test/apps/iodemo/io_demo.cc
Fix test failures like https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=10639&view=logs&j=9a09e8a2-2283-5d47-b9f8-4a5d5904e945&t=382e4f39-11af-5b27-1ff6-14936a85d331
issue introduced in #5881 
@brminich
> TEST/IODEMO: Fix assertion '_status == OK' failed

- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- test/gtest/ucp/test_ucp_worker.cc
Don't discard CM lane.
Don't schedule UCT CM lane to be discarded, since UCP EP will be destroyed due to peer failure and `ucp_cm_disconnect_cb()` could be invoked on async thread after UCP EP is destroyed and before UCT CM EP is destroyed from discarding functionality. So, UCP EP will passed as a corrupted argument to `ucp_cm_disconnect_cb()`.
Fixes #5875
Add `if` check into the `ucp_worker_iface_err_handle_progress()` to understand whether the lane is CM or not:
- if it is a CM lane, purge pending operations by calling `uct_ep_pending_purge()` and destroy UCT EP in-place by calling `uct_ep_destroy()`
- if it is not a CM lane, schedule UCT EP to be discarded
> UCP/WIREUP: Don't discard CM lane

- contrib/test_jenkins.sh
Current test with build icc compiler fail with intel/ics 
module intel/ics  have link to 17 compiler
update to latest 19.1.1
> AZP: update ics to latest version

- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
- test/gtest/ucp/test_ucp_sockaddr.cc
Enable CM WIREUP MSG phase for TCP.
To be able to create UCP EPs over multi-lane UCT/TCP EPs.
Also, to be able to connect through SOCKCM/TCP CM TL and then re-configure EP to SHM/IB/etc. 
1. Remove checks for TCP CM in UCP/WIREUP code and fix UCP/SOCKADDR gtest.
2. Fix TCP to gracefully close the connection between peers when using CONNECT_TO_EP method for connection establishment.
It was fixed by sending `CONN_CLOSE_REQ` CM packet when destroying UCT EP that was responsible for initiating a connection establishment, peer handles this and if TX capability was removed (i.e. `uct_ep_close()` was called for the EP), destroy an EP, otherwise, remove RX capability and wait for `uct_ep_close()` is being called by user.
> UCP/UCT: Enable CM multi-lane for TCP

- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Make `uct_ib_mlx5_devx_md_cleanup()` function `static`.
`uct_ib_mlx5_devx_md_cleanup()` is not explicitly used outside of the `uct/ib/mlx5/dv/ib_mlx5dv_md.c` source file.
Add `static` qualifier.
> UCT/IB/MLX5: Make cleanup function static

- src/ucp/rndv/rndv.c
Fix wrong initialization of datatype in rndv_get request. Datatype is initialized with `dt_make_contig(1)` a few lines above
> UCP/RNDV: Fix dt for get_zcopy rndv req

- src/tools/perf/api/libperf.h
- src/tools/perf/lib/libperf.c
- src/tools/perf/lib/ucp_tests.cc
- src/tools/perf/lib/uct_tests.cc
- src/ucs/arch/aarch64/cpu.h
- test/gtest/Makefile.am
- test/gtest/common/test_perf.cc
- test/gtest/common/test_perf.h
- test/gtest/ucp/test_ucp_wfe.cc
Fixing wait for event implementation and adding test to verify that WFE
does not introduce any substantial overheads.
Fixing WFE implementation and adding test to verify that it is correct one or at least does not hurt performance
Current implementation is broken.
Adding test with and without WFE and check latency on small put messages.
> GTEST/ARCH/TOOLS: Reworking wfe support

- src/ucp/core/ucp_context.c
Align `"mm"` alias with other aliases
It has to be ended with `NULL`
But it is not a problem though, since an array of TLs will be extended up to `7` elements (to be aligned with `"ib"` alias that's the longest one)
Added NULL at the end of `"mm"` alias
> UCP/CORE: Align mm alias with other aliases

- config/m4/compiler.m4
- src/tools/perf/perftest.c
- src/ucm/cuda/cudamem.c
- src/ucp/tag/offload.c
- src/ucs/memory/rcache.c
- src/ucs/profile/profile_on.h
- src/uct/ib/base/ib_log.c
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/dc/dc_mlx5_ep.h
- src/uct/ib/mlx5/ib_mlx5.inl
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ugni/base/ugni_md.c
- src/uct/ugni/rdma/ugni_rdma_ep.c
- src/uct/ugni/udt/ugni_udt_ep.c
- test/apps/profiling/ucx_profiling.c
- test/apps/test_dlopen_cfg_print.c
Add the "-Werror=declaration-after-statement" flag to compilation command of every file in the repo, and fix incompatible code accordingly.
To enforce at compile-time the "no mixing of declaration & code" rule from our coding guidelines, rather than requiring a human review for that.
> MAKE: Enforce no mixing of declarations and code during compilation

- test/apps/iodemo/Makefile.am
Fix linker error for unresolved symbol. It's reproduced when `-ldl` is not added by another dependency.
> TEST/IODEMO: Add '-ldl' linker flag, since the test uses dladdr()

- src/ucs/sys/string.c
- src/ucs/sys/string.h
- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/mlx5/dv/ib_mlx5_dv.c
- src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
- src/uct/ib/mlx5/ib_mlx5.c
- src/uct/ib/mlx5/ib_mlx5.h
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/verbs/ud_verbs.c
- test/gtest/ucs/test_string.cc
- test/gtest/uct/ib/test_ib.cc
Introduce automatic selection of SL with AR support.
Improve out of the box user experience.
Before this feature, user has to discover the network and understand on which SLs AR was configured and then specified the required SL through `UCX_IB_SL=[0..15]`. There were no guarantees that AR is really configured (e.g. network reconfiguration, but the user is not aware of it and still using same SL, but w/o AR), i.e. UCX didn't provide any errors about missing AR on required SL.
Now, user could specify `UCX_IB_AR_ENABLE={ no, yes, try }` with the following logic **_[1]_**:
- `no`: AR is not needed, any SL could be used (i.e. `UCX_IB_SL` value, or `0` by default us used)
- `yes`: AR is strictly needed. If `UCX_IB_SL` value is specified, it will use this SL if AR is configured, otherwise - …
> UCT/IB/MLX5/GTEST: Introduce selection of SL with AR support

- test/gtest/ucp/test_ucp_sockaddr.cc
Fix skip info message
1. Fixes message
```
[2020-11-11T13:54:12.759Z] [     SKIP ] (Skipping due an unreachable destination (unsupported feature or too long worker address or no supported transport to send partial worker address))
```
2. Fit 80 symbols per line
1. `due` -> `due to`
2. Rearrange message
> GTEST/UCP: Fix skip info message

- src/ucp/core/ucp_worker.c
Print transports used for AM API if `UCX_LOG_LEVEL` set to `info`
To be able to check what transports were selected for AM
`ep_cfg[0]: am(rc_mlx5/mlx5_0:1 posix/memory knem/memory);`
> UCP/AM: Print AM tls with info log level

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/rc/accel/rc_mlx5_iface.c
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs_iface.c
Add new env variable which forces RC transports to poll TX CQs every progress iteration. Currently TX CQ is polled only when no RX completions found.
We noticed significant performance benefits with certain communication patterns when polling TX completions equally with RX completions. For instance when MPI rank is waiting for blocking MPI_Send() completion while receiving lots of unexpected messages.
> UCT/RC/DC: Add option to poll TX CQ every progress iteration

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_request.inl
- src/ucp/rndv/rndv.c
- src/ucp/tag/offload.c
- src/ucp/tag/tag_rndv.c
- src/ucp/tag/tag_send.c
- src/ucp/wireup/select.c
- src/uct/api/uct.h
- src/uct/cuda/cuda_copy/cuda_copy_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.c
- src/uct/cuda/gdr_copy/gdr_copy_md.c
- src/uct/ib/base/ib_md.c
- src/uct/ib/rc/accel/rc_mlx5.inl
- src/uct/ib/rdmacm/rdmacm_md.c
- src/uct/rocm/copy/rocm_copy_md.c
- src/uct/rocm/gdr/rocm_gdr_md.c
- src/uct/rocm/ipc/rocm_ipc_md.c
- src/uct/sm/mm/xpmem/mm_xpmem.c
- src/uct/sm/scopy/cma/cma_md.c
- src/uct/sm/scopy/knem/knem_md.c
- src/uct/sm/self/self.c
- src/uct/tcp/sockcm/sockcm_md.c
- src/uct/tcp/tcp_md.c
- src/uct/ugni/base/ugni_md.c
- test/gtest/common/mem_buffer.cc
- test/gtest/ucp/test_ucp_rma.cc
- test/gtest/ucp/test_ucp_tag_mem_type.cc
- test/gtest/uct/test_tag.cc
Avoid using ZCOPY RDMA protocols with CUDA-Managed memory
CUDA managed memory pages will migrate between the CPU and GPU based on who access it. It will result in data validation issues with RDMA if memory is migrated to GPU. 
Use staging protocols.
> UCP/CUDA: Fix CUDA managed memory support

- ucx.spec.in
Allow installing UCX RPM to another prefix by `rpm -i --prefix <dir> ucx-*.rpm`
> SPEC: Make UCX RPM relocatable

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
- test/gtest/ucp/test_ucp_tag_match.cc
Fix PUT protocol
The following happens on UCP when TCP and MM are used (TCP for PUT, MM for AM):
- MM sends RTS from sender
- MM sends RTR from receiver
- TCP does PUT and completes it in-place, but some data still is sending by TCP/IP stack
- MM sends ATP immediately from sender
- Receiver verifies the data, it is incomplete
1. Always return `UCS_INPROGRESS` from TCP PUT operation and add user's completion to a queue of PUT completions that are waiting for ACK.
2. Allocate PUT completion from iface TX mpool instead of heap by doing `calloc()`.
3. Update UCP TAG match RNDV tests to run over TCP/MM, it reproduces the bug.
> UCT/TCP: Fix PUT protocol

- test/apps/iodemo/run_io_demo.sh
Propagate all relevant parameters to server in run_iodemo script. The following params are added:
-k <chunk-size> 
-r <io-request-size> 
-b <number of buffers> ( Number of offcache IO buffers)
-v                         (Set verbose mode)
-H                         (Use human-readable timestamps)
> TEST/IODEMO: Fix server params in run_iodemo script

- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
Create WIREUP EP for P2P TLs on a CM server side.
Fixes #5908 
All lanes have to be WIREUP EP until CM and WIREUP_MSG phases of connection establishment are not done.
Fixes the following test failure on jazz nodes:
```
[10:44 AM] Evgeny Leksikov
[ RUN      ] dcx/test_ucp_sockaddr_destroy_ep_on_err.onesided_c2s_cforce/4 <dc_x/tag,
cm>
[New Thread 0x7ffff40ba700 (LWP 102524)]
[     INFO ] Testing 2.1.3.22:0
[     INFO ] server listening on 2.1.3.22:33672
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff749d64d in ucp_wireup_ep_pending_queue_purge (uct_ep=0x26f9ec0,
cb=0x7ffff74a55ce <ucp_wireup_pending_purge_cb>, arg=0x7fffffffbae0)
at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup_ep.c:215
215         ucp_worker_h worker        = …
```
> UCP/WIREUP: Create WIREUP EP for non-P2P TLs on a CM server side

- test/gtest/ucp/test_ucp_wfe.cc
Disable checking perf for WFE test
Workaround to stop failing #5913
`true` -> `false` for `run_test()`
> GTEST/UCP: Disable checking perf for WFE test (w/a)

- src/ucp/core/ucp_worker.c
- src/ucp/rma/flush.c
- test/gtest/ucp/ucp_test.cc
Fix started_lanes mask on failure
If UCT flush fails need to mark this lane completed to avoid hang
cherry-picked from #5926 to avoid extra dependencies and blocking to due to other failures there
> UCP/EP/FLUSH: fix started_lanes mask on failure

- src/uct/configure.m4
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
- added socket options to enable kernel-level keepalive functionality
> UCT/TCP: add sock options for keepalive

- test/gtest/ucp/test_ucp_mmap.cc
Expect SW RMA when managed memory is used.
After merging #5889 and #5921 simultaneously, `*test_ucp_mmap.reg_mem_type*` over RDMA started failing, because UCP doesn't use RDMA/GPUDirect over CUDA/RoCM-manged memory.
Adjust `expect_rma_offload` parameter considering CUDA/RoCM-managed memory types in the `test_ucp_mmap::reg_mem_type` test case.
> GTEST/UCP: Expect SW RMA when managed memory is used

- src/uct/api/uct.h
- added iface capability UCT_IFACE_FLAG_EP_KEEPALIVE
- to  identify EP's which can provide keepalive functionality
without UCX involving
- API changed
> API/UCT: added UCT_IFACE_FLAG_EP_KEEPALIVE caps

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- test/gtest/ucp/test_ucp_am.cc
Several UCP AM improvements/fixes:
- Adjust max AM header based on RTS size
- Fix small `UCX_RNDV_THRESH` (smaller than `max_short`) for AM rndv
- A couple of fixes in `ucp_am_send_req`
- Tests for the above
> UCP/AM: AM rndv fixes

- src/uct/ib/base/ib_device.c
Decrease log level for testing addr family gid index.
It occupies > 20% of debug logs, making harder to find useful information
> IB: Decrease log level for testing addr family gid index.

- src/ucp/api/ucp.h
Add `recv_info` to `ucp_request_param_t`, so that `*recv_nbx` function can get receive data details in case of immediate completion.
If operation completes immediately the callback is not invoked. Need to provide the length (and other info) of received data to the user.
> UCP/API: Add recv_info to ucp_request_param_t

- src/ucp/core/ucp_context.h
- src/ucs/arch/x86_64/cpu.c
- src/ucs/arch/x86_64/cpu.h
- src/ucs/config/parser.c
- src/ucs/config/parser.h
- src/ucs/config/types.h
- src/uct/ib/mlx5/ib_mlx5.c
- src/uct/ib/mlx5/ib_mlx5.h
- src/uct/ib/rc/accel/rc_mlx5_common.h
- src/uct/sm/mm/base/mm_iface.h
- src/uct/sm/mm/base/mm_md.h
- src/uct/sm/scopy/knem/knem_md.h
- test/gtest/uct/ib/test_ib.cc
Select SL not depending on AR support by default.
To align with previous behavior, since users may not expect that UCX selects SL with AR (if possible) or SL without AR (if possbile) after #5869.
1. Introduced new value for `ucs_ternary_value_t` - `"auto"` that select default value for ternary value.
2. Handled `"auto"` value when selecting SL. If `"auto"` is set, UCT/IB/MLX5 selects SL requested by a user (thru `UCX_IB_SL=<sl>`) or `0`.
3. Updated UCT/IB gtests accordingly and fix bug when verifying OK case (some case wasn't handled, e.g. `UCS_NO`).
> UCS/UCT/IB: Select SL not depending on AR support by default

- src/tools/info/sys_info.c
- src/ucs/arch/cpu.c
- src/ucs/arch/cpu.h
- src/ucs/arch/x86_64/cpu.c
Add support for Zhaoxin processors. 
Including three micro-architectures: Zhangjiang, Wudaokou, Lujiazui.
Added support for three processors: ZX-C, KX5000, KX6000.
> UCS/ARCH: Add Zhaoxin cpu detection

- src/ucp/rma/flush.c
- test/gtest/ucp/ucp_test.cc
fix too early completion for failed EP
in case if scheduled err handler was not be invoked yet, the EP can be closed with requests in pending
reproducer is implemented in https://github.com/openucx/ucx/pull/5931 but that PR has other dependency
> UCP/EP/FLUSH: fix too early completion for failed EP

- test/gtest/uct/test_tag.cc
UCT test must copy-out inline data, following #5889 
@bureddy
> TEST/TAG: Fix tag test to check inline data flag

- bindings/java/src/main/java/org/openucx/jucx/examples/UcxBenchmark.java
- bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkReceiver.java
- bindings/java/src/main/java/org/openucx/jucx/examples/UcxReadBWBenchmarkSender.java
- contrib/test_jenkins.sh
Catch ep timeout exception in JUCX tests. 
Fixes errors in CI: http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/8270/pipeline/1015/
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=11330&view=logs&jobId=da813497-1cca-54a8-f0a9-cb3fd519bc00&j=da813497-1cca-54a8-f0a9-cb3fd519bc00&t=7dd3ffab-efd6-51e7-77f1-40598eb2014b
> JUCX: catch exception on ep close.

- test/gtest/ucp/test_ucp_tag.cc
Fix rndv threshold check for tag offload case. 
Need to check that selected rndv threshold is not less than minimal value (not vice versa)
> GTEST/UCP/TAG: Fix offload thresh check

- src/ucs/arch/aarch64/cpu.h
Add ARM Scalable Vector Extension (SVE) version of the `memcpy` function to UCS.
We are seeing very low intra-node bandwidth on our A64FX machine with the latest UCX. The `memcpy` function shipped in glibc 2.28 (CentOS 8.1) isn't optimized, and it will probably take a long time, if ever, for users to have access to SVE-optimized glibc in production.
Add SVE-optimized `memcpy` written with intrinsics, enabled automatically when the compiler supports it. The SVE version is faster than what glibc provides for all array sizes in my tests.
Compiling UCX using GCC 10.2, with `-march=armv8.2-a+sve` in CFLAGS, running `taskset -c 1 ucx_info -s` on A64FX FX700.
Without patch:
```
```
With patch:
```
```
However, this patch only applies to the places that call `ucs_memcpy_relaxed`, so …
> UCS/ARCH: Add SVE memcpy

- .clang-format
- buildlib/azure-pipelines-pr.yml
- buildlib/fedora.Dockerfile
- src/ucs/arch/x86_64/cpu.c
Add clang-format configuration to allow manual code formatting by developers.
Add code formatting verification to Azure pipeline - issue a warning if the code is not well-formatted.
Enforce consistency of all new code with our coding style.
Save time in code reviews by eliminating the need for code check by the reviewer.
Usage instructions: see https://github.com/openucx/ucx/wiki/Code-style-checking
> CODE: Add style check support

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_worker.inl
- test/gtest/ucp/test_ucp_am.cc
- If single fragment AM received without UCP_AM_SEND_REPLY flag it
should be delivered to the user even if the corresponding rx ep is
closed/failed.
- If single fragment AM received with UCP_AM_SEND_REPLY flag it
should be droppped if the corresponding rx ep is closed/failed,
because reply ep can not be provided in the data callback.
- If some fragment of multi-fragmented AM received and the corresponding rx ep
is closed/failed, this fragment should be dropped regardless of send AM flags
(no way to assemble a message without aux info storedd in ep extension)
- If AM RTS is received and the corresponding rx ep is closed/failed,
this RTS should be droppped and ATS with EP_TIMEOUT should be sent
back to the sender.
Proper error handling
> UCP/AM: Drop AM data if rx ep is closed

- src/ucs/configure.m4
Update AC_DEFINE text to indicate h/w timer enabled
Wrong text in comment
N/A
> UCS/CONFIGURE: aarch64 default is to have HW_TIMER set, change config.h comment text to reflect that

- src/ucp/core/ucp_mm.h
- src/ucp/core/ucp_rkey.c
- src/ucp/rndv/rndv.c
- src/uct/rocm/base/rocm_base.c
- src/uct/rocm/copy/rocm_copy_ep.c
- src/uct/rocm/copy/rocm_copy_iface.c
- src/uct/rocm/copy/rocm_copy_iface.h
- src/uct/rocm/copy/rocm_copy_md.c
- src/uct/rocm/copy/rocm_copy_md.h
Add support for host-staged transfers for ROCm D2D instead of GPUDirect RDMA
Improves performance on platforms where GDR read performance is poor
|   |   Latency (us) |   | BW (MBps)   |   |
|---|---|---|---|---|
Bytes | GDR | Staged | GDR | Staged
1 | 2.95 | 2.94 | 1.33 | 1.31
2 | 2.91 | 2.89 | 3.27 | 3.26
4 | 2.92 | 2.89 | 6.62 | 6.57
8 | 2.91 | 2.89 | 13.24 | 13.16
16 | 2.91 | 2.89 | 26.56 | 26.31
32 | 3.00 | 2.99 | 52.24 | 52.22
64 | 3.06 | 3.04 | 95.38 | 95.30
128 | 3.29 | 3.30 | 145.53 | 145.58
256 | 3.34 | 3.35 | 289.14 | 289.06
512 | 3.01 | 3.02 | 545.24 | 540.69
1024 | 3.09 | 3.10 | 1084.63 | 1073.03
2048 | 3.27 | 3.28 | 2210.85 | 2204.88
4096 | 3.74 | 3.75 | 4102.36 | 4104.76
8192 | 4.11 | 4.11 | 6552.18 | 6553.11
16384 | 6.16 | 6.10 | 9919.29 | 9905.94
32768 | 9.08 | 9.11 | …
> UCP/RNDV/ROCM: add support for staging rndv protocol for ROCm

- src/tools/perf/perftest.c
Fix the test name printing format in `print_test_name`
PR #4969 missed this function.
Before this patch:
```
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
+UCP_put-------+---------+---------+---------+----------+----------+-----------+-----------+
Final:                  1000     0.000  8242.369  8243.613     7764.76    7763.59         121         121
```
After this patch:
```
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | …
```
> TOOLS/PERF: Fix test name printing format

- src/uct/ib/base/ib_device.c
- src/uct/ib/base/ib_device.h
- src/uct/ib/base/ib_iface.c
UCT/IB: get roce ndev name according to right gid but not fixed gid 0.
Currently we get ndev name from gid 0, this can cause problem when the ndev name of right gid is different as gid 0.
Add gid index to paramters of uct_ib_device_get_roce_ndev_name().
> UCT/IB: get roce ndev name according to right gid but not fixed gid 0

- src/ucp/core/ucp_ep.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- test/gtest/ucp/test_ucp_sockaddr.cc
Fix dead code in `ucp_ep_cm_remote_disconnect_progress()`:
```
if (!(ucp_ep->flags & UCP_EP_FLAG_REMOTE_CONNECTED)) {
<body1>
}
<body2>
```
`<body2>` is unreachable, since `ucp_ep_cm_disconnect_progress()` removes the flags before calling `ucp_ep_cm_remote_disconnect_progress()`.
We have to do `flush()` and call user err_cb() instead of do `set_ep_failed()`.
1. Move removing of `UCP_EP_FLAG_REMOTE_CONNECTED` to the end of `ucp_ep_cm_disconnect_progress()`.
2. Introduce test which checks user's `err_cb()` calling. It passes before and after fix.
> UCP/WIREUP/GTEST: Fix dead code in CM disconnect

- src/ucs/config/parser.c
- test/gtest/ucs/test_config.cc
- there was possible double free of string when
user tried to set incorrect value using ucs_config_parser_set_value
function
fixes https://github.com/openucx/ucx/issues/5980
> UCS/CONFIG: fixed crash on incorrect value set

- src/ucs/Makefile.am
- src/ucs/datastruct/bitmap.h
- test/gtest/Makefile.am
- test/gtest/ucs/test_bitmap.cc
Add a bitmap data struct, which allows bitmaps of arbitrary length (not limited to a particular integer size).
Currently a 64-bit integer is used to represent bitmaps, which is not enough. This PR introduces a new bitmap implementation, by using an array of 64-bit integers.
Each bitmap type (length in bits) must be statically defined in `bitmap.h`, currently 64-bit and 128-bit are added. See `test_bitmap.cc` for usage example.
> UCS/DATASTRUCT: Add bitmap data struct

- src/ucp/rma/amo_sw.c
Use remote_addr from AMO part of request instead of RMA.
Fixes possible correctness issue in the future if `remote_addr` moved to new offset in either AMO or RMA substructure of a UCP request.
Use `send.amo.remote_addr` instead of `send.rma.remote_addr`
> UCP/AMO: Use remote_addr from AMO part of request instead of RMA

- NEWS
- src/ucp/api/ucp.h
- src/ucp/tag/tag_recv.c
- test/gtest/ucp/test_ucp_tag_probe.cc
NBX routine for tag_recv_msg
Want to switch JUCX completely to NBX API. This routine is missing in implementation.
> UCP: Recv msg nbx routine.

- src/uct/api/uct.h
- Extended uct_iface_params structure to pass keepalive interval from UCP to UCT
- Allow synchronize UCT/UCP keepalive timeout intervals, so that user can specify keepalive interval once and it will affect all involved entities
- Added keepalive_timeout value to uct_iface_params structure
> API/UCT/IFACE: added keepalive_timeout value

- test/gtest/ucp/test_ucp_wireup.cc
Skip wireup 1sided disconnect test for TCP (workaround)
workaround for #5977
Skip the test + add the comment
> GTEST/UCP: Skip wireup 1sided disconnect test for TCP (workaround)

- buildlib/io-demo.yml
- test/apps/iodemo/io_demo.cc
- test/apps/iodemo/run_io_demo.sh
Add a window on the client side, per every remote server
For better flow control per connection
1. Renames AM implementation from `-a` to `-A`
2. Introduces `-a <window_size>` option
3. Sort on the flight active servers vector on a client by the following rule:
- if not full, the servers are placed before `_num_active_server_to_use` counter
- if full, the servers are places after `_num_active_server_to_use` counter` counter
4. Use `_num_active_server_to_use` counter` counter to randomly generate active server index for servers that are not full
> TEST/IO_DEMO: Add a window on the client side, per every remote server

- src/uct/ib/base/ib_device.c
Ignore PFs without RDMA cap on BF2 according to its gid_tlb_len==0
On BF2/ARM switchdev mode only SFs have RDMA cap, PFs don't have RDMA cap. We should filter out the SF devices with RDMA cap and ignore the PF devices without RDMA cap.
We can filter out the devices with RDMA cap according to gid_tlb_len > 0, and ignore the devices without RDMA cap according to gid_tlb_len==0.
> Ignore PFs without RDMA cap on BF2 according to its gid_tlb_len==0

- src/ucp/wireup/address.c
Fixes error to be
`address.c:1006 UCX  ERROR failed to parse address: number of addresses exceeds 64`
instead of
`address.c:1006 UCX  ERROR failed to parse address: number of addressesexceeds 64`
> UCP: Fix address unpacking error

- src/ucp/core/ucp_request.h
- src/ucp/proto/proto_common.inl
- src/ucp/proto/proto_multi.inl
- src/ucp/proto/proto_single.inl
- src/ucp/rma/get_am.c
- src/ucp/rma/get_offload.c
- src/ucp/rma/put_am.c
- src/ucp/rma/put_offload.c
- src/ucp/rma/rma_sw.c
- src/ucp/tag/eager_multi.c
- src/ucp/tag/eager_single.c
- test/gtest/common/test_obj_size.cc
Rearrange fields in a UCP request to reduce its size.
`dt_iter` and `dt` are not used simultaneously for the same UCP requests.
1. Move `dt_iter` and `dt` under `union`.
2. Update the gtest that checks size of critical UCX structures from `296` to `240`.
> UCP/CORE/GTEST: Rearrange fields in a UCP request to reduce its size

- src/ucs/datastruct/mpool.c
- test/gtest/ucs/test_mpool.cc
Make elem defined for Valgrind
`ucs_mpool_chunk_leak_check()` fails with Valgrind when touches elements that were allocated to user through `ucs_mpool_get_inline()` (it does `VALGRIND_MAKE_MEM_NOACCESS(elem, sizeof *elem);` for the first `sizeof(elem)` bytes).
if a buffer wasn't returned to mpool, it will has the first `sizeof(elem)` bytes uninitialized.
for example:
```
==14461== Invalid read of size 8
==14461==    at 0x508CC28: ucs_mpool_chunk_leak_check (mpool.c:41)
==14461==    by 0x508D334: ucs_mpool_cleanup (mpool.c:137)
==14461==    by 0x588E436: ucp_worker_destroy_mpools (ucp_worker.c:1770)
==14461==    by 0x588FCEA: ucp_worker_destroy (ucp_worker.c:2291)
==14461==    by 0x7F3387: ucs::handle<ucp_worker*, void*>::release() (test_helpers.h:667)
==14461==    by 0x7F2A8C: …
```
> UCS/MPOOL: Make elem defined for Valgrind

- src/ucp/core/ucp_request.inl
- src/ucp/tag/tag_rndv.c
- test/gtest/ucp/test_ucp_tag.cc
- test/gtest/ucp/ucp_test.h
- fixed crash in completion callback when user is tried to free
external request
- added UCP_REQUEST_FLAG_EXTERNAL (replaced
UCP_REQUEST_DEBUG_FLAG_EXTERNAL)
- added gtest
fixes https://github.com/openucx/ucx/issues/5991
> UCP/NBX: fixed external request free from CB

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.c
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_request.inl
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.inl
- src/ucp/rma/amo_sw.c
- src/ucp/rma/get_am.c
- src/ucp/rma/rma.h
- src/ucp/rma/rma_basic.c
- src/ucp/rma/rma_send.c
- src/ucp/rma/rma_sw.c
- src/ucp/rndv/rndv.c
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/tag/offload.h
- src/ucp/tag/tag_match.inl
- src/ucp/tag/tag_rndv.c
- src/ucs/datastruct/ptr_map.inl
- test/gtest/common/test_obj_size.cc
- test/gtest/ucp/test_ucp_sockaddr.cc
Fix and test ucp requests leak from the ptr_map.
To prevent having leaked requests in ptr map.
1. Save request ID to the request to be able remove them just getting an ID form request.
2. Delete IDs where it is needed.
3. Fix AMO/RMA protocols to generate request ID from progress function (release an allocated ID if send was not OK) rather than from pack_cb that could be invoked several times.
> UCP/GTEST: Fix and test ucp requests leak from the ptr_map

- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/rdmacm/rdmacm_cm.h
- src/uct/ib/rdmacm/rdmacm_cm_ep.c
- src/uct/ib/rdmacm/rdmacm_cm_ep.h
share dummy CQ per device
to reduce resources consumption
ported from https://github.com/yosefe/ucx/pull/105
> UCT/CM/RDMACM: share dummy CQ per device

- .clang-format
Prevents clang of formatting java files.
Java uses maven for code style checking. Clang prints warnings if there are java files in diff:
```
diff --git a/bindings/java/src/test/java/org/openucx/jucx/UcpRequestTest.java b/bindings/java/src/test/java/org/openucx/jucx/UcpRequestTest.java
index bdca94fc6..cc73b46ab 100644
--- a/bindings/java/src/test/java/org/openucx/jucx/UcpRequestTest.java
+++ b/bindings/java/src/test/java/org/openucx/jucx/UcpRequestTest.java
@@ -4,13 +4,13 @@
*/
package org.openucx.jucx;
+import static org.junit.Assert.*;
+
+import java.nio.ByteBuffer;
import org.junit.Test;
import org.openucx.jucx.ucp.*;
import org.openucx.jucx.ucs.UcsConstants;
-import java.nio.ByteBuffer;
-import static org.junit.Assert.*;
-
public class UcpRequestTest {
@Test
public void …
```
> JUCX: Prevent clang of formatting java files.

- contrib/test_jenkins.sh
- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_worker.c
- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
- src/uct/tcp/tcp_iface.c
- test/gtest/ucp/test_ucp_peer_failure.cc
- added processing of "auto" timeouts for keepalive
- added parser type UNITS to allow set number with "auto" & "inf"
> UCP/TCP/KEEPALIVE: added processing of auto time

- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_iface.c
- src/uct/ib/rc/base/rc_iface.h
Protect rc_iface->ep_list and rc_iface->eps with a spinlock 
we may create RC QP from the progress thread in wireup_cm pack
callback, it has to be thread safe wrt other iface operations
using `ucs_spinlock_t`
> UCT/RC: Protect rc_iface->ep_list and rc_iface->eps with a spinlock 

- src/ucs/sys/sock.c
- src/ucs/sys/sock.h
- src/uct/ib/rdmacm/rdmacm_cm.c
- src/uct/ib/rdmacm/rdmacm_cm.h
- src/uct/ib/rdmacm/rdmacm_cm_ep.c
- src/uct/ib/rdmacm/rdmacm_md.c
- test/gtest/common/test_helpers.cc
- test/gtest/common/test_helpers.h
- test/gtest/ucs/test_sock.cc
- test/gtest/uct/ib/test_sockaddr.cc
- test/gtest/uct/test_mm.cc
- test/gtest/uct/uct_p2p_test.h
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
add UCX_RDMA_CM_SOURCE_ADDRESS config
to have a way to specify rdmacm src address
> UCT/CM/RDMACM: add UCX_RDMA_CM_SOURCE_ADDRESS config

- src/ucp/api/ucp.h
- src/ucp/core/ucp_am.c
- test/gtest/ucp/test_ucp_am.cc
Define a flag for UCP AM handlers which guarantees that receive handler callback will always provide a persistent data pointer, which can be used outside the callback.
1. Extended functionality, user will not need to copy-out small messages if need to access them later
2. Preparation for GPU support for eager messages
> UCP/AM: Define persistent data flag for AM handlers

- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/mlx5/ib_mlx5.c
- test/gtest/uct/ib/test_ib.cc
Fixes for SL selection
1. Fixes SL (Etherhent priority) selection for RoCE devices.
2. Fixes SL=15 selection.
3. Covers more use cases in gtests.
1. If the selected device has RoCE type, select SL from empty mask assuming that AR_ENABLE=no.
2. SL mask is done for `16`.
3. Check reported string, and check different SLs instead of just `8`.
> UCT/IB: Fixes for SL selection (v1.10.x)

- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_iface.h
- src/uct/ib/mlx5/ib_mlx5.c
- test/gtest/uct/ib/test_ib.cc
Don't select SL for Ethernet devices.
there are systems where mixed IB and RoCE devices, then we will get (even if RoCE won't be used due to selection logic by performance):
```
[1608109568.519295] [r-hpc29:95512:0]        ib_mlx5.c:795  UCX  ERROR AR=n was requested for SL=auto, but could not detect AR mask for SLs. Please, set SL manually without AR on mlx5_bond_0:1, SLs with AR support = { <none> }, SLs without AR support = { <none> }
```
1. Before selecting SL, check that type of device port.
2. If it's RoCE port, just return `UCS_OK`.
> UCT/IB: Fixes for SL selection

- src/uct/ib/rc/accel/rc_mlx5_common.c
- fixed issue in iface recv prepost when adaptive progress enabled
- fixed assert: rc_mlx5_common.c:128  Assertion `rc_iface->rx.srq.available >= count' failed
- don't try prepost recv twice
> RC_MLX5/IFACE: fixed assert

- Makefile.am
- config/m4/fuse3.m4
- configure.ac
- contrib/buildrpm.sh
- src/tools/vfs/Makefile.am
- src/tools/vfs/vfs_daemon.h
- src/tools/vfs/vfs_main.c
- src/ucs/Makefile.am
- src/ucs/configure.m4
- src/ucs/sys/compiler.h
- src/ucs/sys/compiler_def.h
- src/ucs/sys/init.c
- src/ucs/vfs/base/vfs_obj.c
- src/ucs/vfs/base/vfs_obj.h
- src/ucs/vfs/fuse/Makefile.am
- src/ucs/vfs/fuse/configure.m4
- src/ucs/vfs/fuse/vfs_fuse.c
- src/ucs/vfs/sock/Makefile.am
- src/ucs/vfs/sock/configure.m4
- src/ucs/vfs/sock/vfs_sock.c
- src/ucs/vfs/sock/vfs_sock.h
- ucx.spec.in
Add means for run time monitoring of UCX-based applications
```
$ ucx_vfs   
$ ucx_info -u t -e
$ tree /tmp/ucx/
/tmp/ucx/
└── 4524
├── ucp
│   └── context
│       └── 0x613010
│           └── worker
│               └── 0x68f720
│                   ├── ep
│                   │   └── 0x7fffe729f000
│                   │       ├── info
│                   │       └── state
│                   └── info
└── ucs
└── rcache
├── 0x61ed50
│   ├── name
│   └── stat
├── 0x63d6d0
│   ├── name
│   └── stat
└── 0x63ea00
├── name
└── stat
13 directories, 9 files
$ cat /tmp/ucx/4524/ucp/context/0x613010/worker/0x68f720/ep/0x7fffe729f000/info
#
#
#
#
#
$ cat /tmp/ucx/4524/ucs/rcache/0x61ed50/stat 
regions : 3
```
> UCS/TOOLS/BUILD: Infrastructure for FUSE-based monitoring file-system

- src/ucp/wireup/select.c
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_wireup.cc
- test/gtest/uct/test_peer_failure.cc
- exclude from ep_check map lanes where built-in keepalive
feature is supported
- updated ep-check gtests to disable built-in keepalive
> WIREUP: exclude ep_check lanes where KA supported from map

- src/uct/ib/ud/verbs/ud_verbs.c
Implemented uct_ep_am_short_iov in UD verbs.
> UCT/IB/UD: Implemented AM short IOV in UD verbs.

- src/uct/ib/rc/accel/rc_mlx5_common.c
- fixed issue in iface recv prepost when adaptive progress enabled
- fixed assert: rc_mlx5_common.c:128  Assertion `rc_iface->rx.srq.available >= count' failed
- don't try prepost recv twice
backport from https://github.com/openucx/ucx/pull/6046
> RC_MLX5/IFACE: fixed assert - v1.10

- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/verbs/rc_verbs_ep.c
Handle multiple flush cancel w/o completion
`uct_ep_flush()` with `UCT_FLUSH_FLAG_CANCEL` and w/o completion will be called by a user multiple times while it returns `UCS_INPROGRESS`
Fixes #6048
Fixes #6027
Fixes #5999
1. RC_VERBS/RC_MLX5 - remove the assertion that check FLUS_CANCEL flag
2. DC_MLX5 - if FLUSH_CANCEL is already set, don't do any actions, just move to allocating completion and returning `UCS_INPROGRESS`
> UCT/IB: Handle multiple flush cancel w/o completion

- src/ucp/api/ucp.h
- src/ucp/core/ucp_ep.c
- test/gtest/ucp/test_ucp_wireup.cc
Use user passed params for `ucp_ep_flush_internal` in `ucp_ep_close_nbx` to handle callback and user data fields.
To unify ucp API, and makes easier to implement JUCX logic.
> UCP: call user callback on ucp_ep_close_nbx.

- src/ucp/core/ucp_ep.c
porting https://github.com/openucx/ucx/pull/6054 from master
> UCP/MEM_TYPE: Adjust mem type zcopy thresh if user sets UCX_ZCOPY_THRESH - v1.10.x

- src/uct/ib/rc/accel/rc_mlx5_devx.c
Fix modify_qp syndrome when passing ah_attr.tclass for IB port with is_global==0
> UCT/IB/DEVX: Set modify-QP global address parameters only for GRH case

- .clang-format
- buildlib/az-helpers.sh
- buildlib/azure-pipelines-pr.yml
- buildlib/fedora.Dockerfile
Use a custom build of `clang-format` when formatting code in the pipeline, which fixes pointer alignment and supports alignment of consecutive declarations even if there is a comment between them.
Improve the automatic code formatting done in the CI, by making it consistent and closer to our coding style, so that making it a mandatory step would make sense.
> CODE: Use custom LLVM build, improve clang-format configuration

- src/uct/ib/rc/base/rc_iface.h
- src/uct/ib/rc/verbs/rc_verbs.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- src/uct/ib/rc/verbs/rc_verbs_impl.h
Implemented uct_ep_am_short_iov in RC verbs.
> UCT/IB/RC: Implemented AM short IOV in RC verbs.

- src/ucs/sys/compiler.h
- src/ucs/sys/compiler_def.h
In PR https://github.com/openucx/ucx/pull/5935, moved UCS_STATIC_INIT/UCS_STATIC_CLEANUP  to compiler.h from compiler_def.h, which is causing build failure for libs using UCS_CONFIG_REGISTER_TABLE
> UCS: Move UCS_STATIC_INIT macro to compiler_def.h

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java
- bindings/java/src/main/native/endpoint.cc
- bindings/java/src/main/native/worker.cc
add memory type hint to all ucp operations.
Would be implemented in NBX API (from #6067). This is backward compatible since by default it passes `UCS_MEMORY_TYPE_UNKNOWN`
> JUCX: add memory type hint to ucp operations.

- src/ucp/api/ucp.h
- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/proto/proto_am.inl
- src/ucp/rndv/rndv.c
- src/ucp/tag/tag_send.c
- test/gtest/common/mem_buffer.cc
- test/gtest/common/mem_buffer.h
- test/gtest/ucp/test_ucp_am.cc
GPU support for AM. Now:
- `ucp_am_send_nbx` can send buffer of any memory type
- `ucp_am_recv_data_nbx` can receive rendezvous data to any memory type
- eager data always arrives to the staging CPU buffer (ability to call `ucp_am_recv_data_nbx` for eager messages will be added in the next PR)
> UCP/AM/GTEST: GPU support for UCP AM

- buildlib/io_demo/az-stage-io-demo.yaml
Have error:
Line drop_12110/install/bin/io_demo: symbol lookup error: /lib/libuct.so.0: undefined symbol: ucs_config_sprintf_ternary
> AZP/IODEMO: add LD_LIBRARY_PATH

- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_ep.c
Fix pending_add of WIREUP MSGs when CM AUX EP is WIREUP EP.
`ud/test_ucp_sockaddr.onesided_disconnect_bidi_wait_err_cb/5` tests hangs when UCT EP created during CM phase will not be re-used by the new configuration and cleint/server is not able to send WIRUEP MSG due to lack of resources. So, w/o this fix the following sequence occurs:
- AM Bcopy of WIREUP MSG returns UCS_ERR_NO_RESOURCE.
- Add WIREUP MSG progress request to AUX EP of CM lane.
- AUX EP of CM Lane is WIREUP EP, so WIREUP MSG progress is not really scheduled on real transport, it is kept in WIREUP EP's .internal queue.
Extract UCT EP from a WIREUP EP when setting UCT EP as AUX EP for a CM WIREUP EP
> UCP/WIREUP: Don't allow wireup EP over wireup EP

- src/uct/ib/base/ib_verbs.h
- src/uct/ib/ud/base/ud_def.h
Fix typedef for iface address
It has to be `typedef` for `struct uct_ud_iface_addr`
Replace `uct_ib_qpnum_t` by `struct uct_ud_iface_addr`
> UCT/IB/UD: Fix typedef for iface address

- src/uct/ib/rdmacm/rdmacm_cm_ep.c
Fixes #6075 
It segfaults when running tests with `UCX_LOG_LEVEL=debug` (needed to fix other issues in JUCX tests).
1. `UCX_LOG_LEVEL=debug ./gtest --gtest_filter="*sockaddr*"`
2.
```
>>> bt
#0  0x00007f077b375179 in waitpid () from /lib64/libpthread.so.0
#1  0x00007f077c7a3e55 in ucs_debugger_attach () at debug/debug.c:813
#2  0x00007f077c7a421c in ucs_error_freeze (message=0x7f077c8716f4 "address not mapped to object") at debug/debug.c:908
#3  0x00007f077c7a486b in ucs_handle_error (message=0x7f077c8716f4 "address not mapped to object") at debug/debug.c:1078
#4  0x00007f077c7a4626 in ucs_debug_handle_error_signal (signo=11, cause=0x7f077c8716f4 "address not mapped to object", fmt=0x7f077c87187d " at address %p") at debug/debug.c:1027
#5  0x00007f077c7a476c in ucs_error_signal_handler …
```
> UCT: Prevent segfault in uct_rdmacm_cm_ep_str when id is not initialized

- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_ep.h
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/verbs/ud_verbs.c
- test/gtest/ucp/test_ucp_peer_failure.cc
Introduce EP check (Keep Alive) in UCT/UD.
To extend the functionality provided by UCT/UD and use it in UCP for better error handling.
1. Introduce new packet type - `UCT_UD_PACKET_FLAG_CHECK`.
2. The packet is sent by UD when a user calls `uct_ep_check()` (it is not sent if UD Ep is not connected or there are some unacked TX operations).
3. Upon receiving the packet, UD increases PSN that will be ACKed then and ACKs its own operations (if they exist).
> UCT/IB/UD: Introduce EP check (Keep Alive)

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.inl
- src/uct/tcp/tcp_iface.c
- test/gtest/ucp/test_ucp_sockaddr.cc
- enabled keepalive by default: 60s * 128 EP's
- added processing of UCP keepalive in iface_open call
> UCP/KEEPALIVE: enabled by default

- src/ucs/vfs/fuse/vfs_fuse.c
Infrastructure for exposing UCX internal status over FUSE
- UCS starts a FUSE thread which connects to a mount daemon and serves filesystem operations
- If the daemon does not exits, the thread will wait for it to appear, using inotify service
```
+-----------------------+
| filesystem operations |
| (cat, ls, etc.)       |
+-----------------------+
|
+------------v-----------+
|   kernel FUSE driver   |
+------------------------+
^
|
+----v----+             +---------+
|         |             |         |
|  UCS    |             | ucx_vfs |
|  fuse   +<----------->+ mount   |
|  thread |             | daemon  |
|         |             |         |
+---------+             +---------+
```
> UCS/VFS: Connect to daemon and expose dummy filesystem

- src/ucp/core/ucp_worker.c
Remove unused pending queue
The pending queue defined and initialized, but unused
Removed declaration and initialization
> UCP/CORE: Remove unused pending queue

- src/ucp/core/ucp_ep.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_cm.h
- test/gtest/ucp/test_ucp_sockaddr.cc
Follow up on #6036 to get a completion callback on close request.
To fix test hangs in JUCX NBX API #6067  since it doesn't call completion on close request
> UCP/EP: set callback on close request.

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpRequest.java
- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/main/native/jucx_common_def.h
- bindings/java/src/test/java/org/openucx/jucx/UcpRequestTest.java
Add status field to UcpRequest class.
In following PR when switch to NBX status will be updated for all the requests
> JUCX: add request status field.

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_request.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_ep.c
- test/gtest/ucp/test_ucp_worker.cc
Allow EP check during WIREUP phase, i.e. UCP will do KA during WIREUP pahse.
The remote peer could be failed or forcibly closed during WIREUP MSG phase, e.g. as in #6011 issue:
- server closes EP forcibly after receiving and handling RDMA CM event "CONNECT REQUEST".
- client receives RDMA CM event "CONNECT RESPONSE".
- client does `rdma_establish()` and UCT informs client about connect completion. CM phase is considered as completed on a client side. Server will start WIREUP MSG phase after from CM's `conn_notify_cb` callback
- client hangs for a while since neither WIREUP "PRE_REQUEST" message nor RDMA CM event "DISCONNECTED" was received.
Fixes #6011.
Enabling KA by default (#6059) will fix the issue fully.
Do WIREUP EP check if UCT EP is locally connected or auxiliary UCT EP is not a …
> UCP/WIREUP: Allow EP check during WIREUP phase

- config/m4/cuda.m4
- configure.ac
- contrib/test_jenkins.sh
- examples/Makefile.am
- src/tools/perf/cuda/Makefile.am
- src/ucm/cuda/Makefile.am
- src/uct/cuda/Makefile.am
- src/uct/cuda/gdr_copy/Makefile.am
- test/apps/Makefile.am
- test/gtest/Makefile.am
Fix build failure when only dynamic libraries of Cuda are installed
> CUDA/TEST: Check if libcudart_static is present for memory hook test

- src/ucs/sys/string.c
- src/ucs/sys/string.h
- src/uct/ib/base/ib_device.c
- test/gtest/ucs/test_sys.cc
Get device/vendor ids of SF from its parent PCI.
We can't get device/vendor ids of SF from its sysfs directly, so we get the ids from SF's parent PCI.
Get the parent PCI of SF, then get the device/vendor ids of parent PCI. The SF has the same device/vendor ids as its parent PCI.
> Get device/vendor ids of SF from its parent PCI

- src/ucs/config/parser.c
- src/ucs/config/parser.h
- src/ucs/config/types.h
- test/gtest/ucs/test_config.cc
Introduce the `allow_list` data struct in UCP config parser. It is based on a strings array, adding a `mode`, which is one of `ALL`, `ALLOW` or `NEGATE`.
In order to support negation in `UCX_TLS` and maybe other options.
> UCS/DATASTRUCT: Add allow_list data struct

- src/ucp/rndv/rndv.c
Fix releasing of local request ID when switching to RNDV AM
Fixes https://github.com/openucx/ucx/pull/6100#issuecomment-757496024
When releasing local send request ID, need to use the `rndv_rtr_hdr->sreq_id` instead of `rndv_rtr_hdr->rreq_id` which is saved to `sreq->send.msg_proto.rreq_id` when switiching to RNDV AM protocol
1. Replaced using `rndv_rtr_hdr->sreq_id` instead of `sreq->send.msg_proto.rreq_id` at the end of the function when releasing local ID.
2. Added useful assert to compare local send request ID and ID received from a peer.
> UCP/RNDV: Fix releasing of local request ID when switching to RNDV AM

- src/ucp/api/ucp.h
- removed incorrect note from function description, since `ucp_tag_recv_nbx` **can** return a pointer to request.
> DOC/RECV-NBX: removed incorrect note

- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- added parameter to skip progress iterations to reduce ucs_get_time call
> UCP/KEEPALIVE: skip progress iterations

- src/ucm/util/reloc.c
Define the macro in `reloc.c`, if it is not defined.
Otherwise, cppcheck might fail with an "unknown macro" warning.
> UCM/UTIL: Ensure ElfW macro is defined

- test/apps/iodemo/io_demo.cc
Change default values of window sizes to 16 to get good throughput.
The original default window size values are 1 which can't make iodemo gettting good throughput.
Change default values of window sizes to 16.
>  Change default values of window sizes to 16 to get good throughput.

- src/ucs/datastruct/bitmap.h
- test/gtest/ucs/test_bitmap.cc
Add convenience functions & macros to the UCS bitmap data structure: `IS_ZERO`, `FFS`, `POPCOUNT`, `MASK`. Add support both for in-place (modifying) bitwise operations, and those that return a new value (which are handy when working with r-values and can't take references).
In-place operations are done with the first bitmap passed by reference:
```
UCS_BITMAP_OR_INPLACE(&bitmap, bitmap2);
```
Operations on r-values require explicitly passing the exact type of the bitmaps, for example:
```
UCS_BITMAP_OR(bitmap, bitmap2, 128);
```
Preparation for the support of >64 TL devices in UCP, which will be done by replacing `uint64_t tl_bitmap` type with usage of UCS bitmap.
> UCS/DATASTRUCT: Improve bitmap datastruct

- src/uct/sm/mm/base/mm_iface.c
- src/uct/sm/self/self.c
- test/gtest/uct/test_p2p_am.cc
- test/gtest/uct/test_stats.cc
Updated shared memory transport max iov count capability.
The max iov count capability is used as a limit for an argument of uct_ep_am_short_iov method.
self/posix/sysv transports transports support am short interface along with uct_ep_am_short_iov interface method. Thus the value can be changed from 1.
> UCT/SM: Updated shared memory transport max iov count capability.

- .clang-format
- Tweak `penalty` settings in `.clang-format` to better match our coding style
- Use `master` branch of `openucx/llvm-project` when building docker image
Improve code style check
> UCS/CODE: Update clang format configuration

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.inl
- src/ucp/proto/proto_am.inl
- src/ucp/rma/amo_sw.c
- src/ucp/rma/rma_sw.c
- src/ucp/rndv/rndv.c
- src/ucp/stream/stream_recv.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/wireup/wireup.c
- test/gtest/ucp/test_ucp_am.cc
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/ucp/ucp_test.h
Drop packets with invalid REQ or UCP EP IDs
Just drop packets instead of asserting that we expect that requests or EPs are found by their ids.
1. Add additional if to check the result from `ucp_worker_get_ep_by_id()` and `ucp_worker_get_request_by_id()`. If it unsuccessful to find a request or an EP, just drop a packet.
2. Add gtests to reproduce an invalid EP or request ID handling during peer failure flow.
> UCP/CORE: Drop packets with invalid REQ or UCP EP IDs

- src/ucp/api/ucp.h
- removed incorrect note from function description
(cherry picked from commit 4b4df04074e57bf82005c08fa2a9a802d9034413)
backport from https://github.com/openucx/ucx/pull/6104
> DOC/RECV-NBX: removed incorrect note - v1.10

- src/ucp/rndv/rndv.c
Fix releasing of local request ID when switching to RNDV AM (backport of #6101)
Fixes https://github.com/openucx/ucx/pull/6100#issuecomment-757496024
When releasing local send request ID, need to use the `rndv_rtr_hdr->sreq_id` instead of `rndv_rtr_hdr->rreq_id` which is saved to `sreq->send.msg_proto.rreq_id` when switiching to RNDV AM protocol
1. Replaced using `rndv_rtr_hdr->sreq_id` instead of `sreq->send.msg_proto.rreq_id` at the end of the function when releasing local ID.
2. Added useful assert to compare local send request ID and ID received from a peer.
> UCP/RNDV: Fix releasing of local request ID when switching to RNDV AM (v1.10.x)

- .clang-format
Adjust clang format configuration to avoid any modification of comments in code.
Some comments contain meaningful alignment (e.g function `@param` docs). When clang-format detects a long line and breaks it to 2 lines, it is unable to correctly preserve the alignment. We might fix that behavior in the future, meanwhile it's better to completely disable comments processing.
> UCS/CODE: Modify clang format config - don't reflow comments

- src/tools/info/ucx_info.c
- src/ucp/core/ucp_ep.c
Add AM option to ucx_info
Can check UCP AM proto thresholds with ucx_info command:
```
$./src/tools/info/ucx_info -e -um
#
#
#
#
```
> UCP/TOOLS: Add AM option to ucx_info

- src/ucp/wireup/wireup_cm.c
Reset flush state during CONN_REQ processing on a server.
Flush state has to be reset during CM.
Update `ucp_ep_cm_server_create_connected()` to call `ucp_ep_flush_state_reset()` when updation remote ID.
> UCP/WIREUP: Reset flush state during CONN_REQ processing on server

- src/ucp/core/ucp_request.h
- src/ucp/proto/proto_multi.inl
- src/ucp/tag/eager.h
- src/ucp/tag/eager_multi.c
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/eager_single.c
- src/ucp/tag/tag_send.c
Support tag_send_sunc() API with new protocols
- Add new protocol which supports TAG_SEND_SYNC operation
- Use new protocols in ucp_tag_send_sync_nbx() function
> UCP/PROTO/TAG: Implement eager_sync with new protocols

- src/ucs/datastruct/array.h
- src/ucs/datastruct/string_buffer.h
Allow in-place initialization of dynamic string buffers and dynamic arrays
> UCS/ARRAY/STRB: Add initializer macros

- src/ucs/sys/topo.c
- src/ucs/sys/topo.h
- test/gtest/ucs/test_topo.cc
To allow passing BDF device name to ucx_info tool, to show protocols w.r.t particular memory unit
> UCS/TOPO/TEST: Add method to find device by BDF name

- src/ucs/sys/string.c
- test/gtest/ucs/test_string.cc
When printing a trivial range (end==start), should not use `..` notation
> UCS/STRING: Fix ucs_memunits_range_str() when range_start==range_end

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_ep.c
1. Allow multi-rail over lanes with BW ratio >= `1/4`.
2. Compare lane scales with `-epsilon` in the following formula:
`(scale - min_scale) < -epsilon`, where `epsilon(a,b) = (a + b) * 1e-6`, e.g.:
`(0.1 - 0.10000001) < -((0.1+ 0.10000001) * 1e-6)` ->
`-0.00000001 < -0.00000020000001` - false as expected
but
`(0.09999999 - 0.10000001) < -((0.09999999 + 0.10000001) * 1e-6)` ->
`-0.00000002 < -0.0000002` - true as exepected
1. Don't select too slow lanes for multi-rail.
2. Make lanes selection by its scales stable for float arithmetic.
1. Change default value for `MULTI_LANE_MAX_RATIO` from `10` to `4`.
2. Update lane scales comparison (`min_scale = 1 / MULTI_LANE_MAX_RATIO`)
from:
`scale < min_scale`
to:
`(scale - min_scale) < -epsilon`, where `epsilon(a,b) = (a + b) * 1e-6`
> UCP/CORE: Allow multi-rail over lanes with BW ratio >= 1/4

- src/ucp/core/ucp_am.c
- src/ucp/proto/proto_am.inl
- src/ucp/stream/stream_send.c
- src/ucp/tag/eager_snd.c
Handle UCT AM short failure correctly in UCP progress functions.
If AM short failed in a progress function (i.e. the status is neither `UCS_OK` nor `UCS_ERR_NO_RESOURCE`), a UCP request has to be completed with the `status`, but `UCS_OK` should be returned from a function to satisfy `ucp_request_try_send()` expectations that `UCS_OK`/`UCS_INPROGRESS`/`UCS_ERR_NO_RESOURCE` statuses could be returned from progress functions.
1. Introduce `ucp_am_short_handle_status_from_pending()` common function for AM Short to use in all TAG/AM/STREAM function as we have for AM Bcopy.
2. Use the new function to handle `status` from `uct_ep_am_short()` in TAG/AM/STREAM short progress functions.
> UCP/PROTO: Handle AM short failure correctly

- src/ucs/debug/log.c
- src/ucs/debug/log_def.h
- test/gtest/common/test.cc
- test/gtest/common/test_helpers.cc
- test/gtest/common/test_helpers.h
- test/gtest/ucs/test_log.cc
Add a visual hint of which log messages are printed in the context of a specific block/function
> UCS/LOG/TEST: Add log indent to display nested log messages

- src/ucs/datastruct/bitmap.h
- test/gtest/ucs/test_bitmap.cc
Fix 2 bugs in bitmap data structure:
1. `UCS_BITMAP_FOR_EACH_BIT` iterates over some bits, even if they are not set (specifically, bits 64, 128, etc...)
2. `;` and the end of some macros needs to be removed (it prevents composing them).
1. Fix by adding a check that a bit is indeed set before entering the loop (the check had been previously removed).
Added a corresponding test to verify it.
> UCS/DATASTRUCT: Bug fixes

- src/ucp/core/ucp_ep.c
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_cm.h
delay client EP restoring for all devices case in 2-phase client-server connection establishment
fixes https://github.com/openucx/ucx/pull/5926#issuecomment-758542946 failure
> UCP/WIREUP/CM: delay client EP restoring for all devices case

- src/ucp/core/ucp_am.c
- src/ucp/proto/proto_am.inl
- src/ucp/stream/stream_send.c
- src/ucp/tag/eager_snd.c
Handle UCT AM short failure correctly in UCP progress functions.
If AM short failed in a progress function (i.e. the status is neither `UCS_OK` nor `UCS_ERR_NO_RESOURCE`), a UCP request has to be completed with the `status`, but `UCS_OK` should be returned from a function to satisfy `ucp_request_try_send()` expectations that `UCS_OK`/`UCS_INPROGRESS`/`UCS_ERR_NO_RESOURCE` statuses could be returned from progress functions.
1. Introduce `ucp_am_short_handle_status_from_pending()` common function for AM Short to use in all TAG/AM/STREAM function as we have for AM Bcopy.
2. Use the new function to handle `status` from `uct_ep_am_short()` in TAG/AM/STREAM short progress functions.
backport of #6157 PR
> UCP/PROTO: Handle AM short failure correctly [v1.10.x]

- src/uct/ib/rc/accel/rc_mlx5_ep.c
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/verbs/rc_verbs_ep.c
Handle multiple flush cancel w/o completion
`uct_ep_flush()` with `UCT_FLUSH_FLAG_CANCEL` and w/o completion will be called by a user multiple times while it returns `UCS_INPROGRESS`
Fixes #6048
Fixes #6027
Fixes #5999
Fixes #5844
RC_VERBS/RC_MLX5 - remove the assertion that checks FLUS_CANCEL flag
backport of #6055 (RC-only, didn't port due to DC was not updated to have TX flush, i.e. #5872 is not a part of v1.10.x)
> UCT/IB/RC: Handle multiple flush cancel w/o completion [v1.10.x]

- buildlib/azure-pipelines-pr.yml
Needed due to moving some docker agents to different machines
> AZP: Run dockers in privileged mode, to work on older host OS

- src/uct/ib/rc/verbs/rc_verbs.h
- src/uct/ib/rc/verbs/rc_verbs_ep.c
- src/uct/ib/rc/verbs/rc_verbs_iface.c
- test/gtest/common/test_obj_size.cc
- test/gtest/uct/ib/test_rc.cc
Keep rc_verbs address size small, don't pass address/rkey
- Use flow-control to flush old mthca devices, instead of extending rc_verbs address to pass virtual address and rkey
- Add configuration parameter to control flush mode
Partially reverts #5488
> UCT/RC/TEST: Flush by flow control on old devices

- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- test/apps/test_ucx_tls.py
- test/gtest/uct/uct_test.cc
Use allow_list for TLS list in UCP context, instead of an array.
Support negation (forbidding) particular TLS, for example:
`UCX_TLS=^ib,tcp ...` will avoid using `ib` and `tcp` as transports.
> UCP/CORE: Use allow_list for tls in ucp_config

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_worker.inl
- src/ucp/rma/amo_sw.c
- src/ucp/rma/rma_sw.c
- src/ucp/rndv/rndv.c
- src/ucp/stream/stream_recv.c
- src/ucp/tag/eager_multi.c
- src/ucp/tag/eager_rcv.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/wireup/wireup.c
- src/ucs/datastruct/ptr_map.inl
- src/uct/tcp/tcp_ep.c
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_wireup.cc
- test/gtest/ucs/test_datatype.cc
- Eliminate some branches, since ptr_map values cannot be NULL. This affects all flows which use request/endpoint id: rdnv, sw rma/atomics, eager-sync, stream, active message with reply-ep.
- Fix lookup in ATS, atomic reply, and eager-sync-ack handlers
- Fix potential NULL access in ucp_worker_extract_request_by_id()
- Return status from ptr_map lookup, instead of a pointer
- Checking the status code allows the compiler to eliminate branches
Before the PR (after adding the missing NULL check in ucp_eager_sync_ack_handler):
<table>
<tr>
<td>
Before: <b>0.154 usec</b>
</td>
<td>
After: <b>0.144 usec</b>
</td>
</tr>
<tr>
<td style="align:top">
```
ucp_eager_sync_ack_handler
2.11 │       push   %r14
2.50 │       push   %r13
0.25 │       push   %r12
5.00 │       push   %rbp
2.06 │       push …
```
> UCP/UCS/TEST: Optimize ptr_map lookup and small lookup fixes

- src/uct/api/uct.h
- src/uct/base/uct_md.c
- src/uct/base/uct_md.h
- src/uct/cuda/base/cuda_md.c
- src/uct/cuda/base/cuda_md.h
* Add 'typedef' to uct_md_mem_attr_field enum (for consistency with other enums)
* Remove 'const' qualifier from 'size_t' field since it has no effect and is inconsistent with other APIs
* Rename 'addr'->'address' in implementation of uct_md_mem_query, for consistency with API parameter name
> UCT/API/CUDA: Cleanup parameter names

- src/ucp/core/ucp_am.c
- src/ucp/rndv/rndv.c
- src/ucp/rndv/rndv.h
1. Update status to report failure.
2. Move a sending ATS/ATP/frag_ATP to a common function.
3. Complete send request for PUT operations before sending ATP in the same way as we do for GET operations.
1. The status should be updated by the first failure status or `UCS_OK` in order to complete the request with the correct status.
Before the fix, we updated the status only after getting the status from `uct_ep_put|get_zcopy`, but ignore the error status in the completion callback.
2. Reduce code duplication and improve code reuse.
3. It potentially should be better for the sender, it will receive completion earlier while ATP will be sent in progress to notify a receiver about the completed operation.
1. Invoke `uct_completion_update_status()` from UCT completion callback for GET and PUT …
> UCP/RNDV: Update status to report failure

- src/ucp/proto/proto_am.inl
- src/ucs/datastruct/callbackq.c
- test/gtest/ucs/test_callbackq.cc
Fix recursive one-shot
To avoid a stuck until out-of-memory
limit iteration count by actual value before the loop
> UCS/CALLBACKQ: fix recursive one-shot

- contrib/test_jenkins.sh
- src/ucs/sys/sock.c
- src/uct/ib/rdmacm/rdmacm_cm.c
Enable the loopback IP as a TCP and testing resource
Support the loopback interface when establishing a connection through TCP.
Don't disqualify the loopback interface when checking for resources.
Also, use CM fallback on rdmacm route_resolve error.
> UCS/UCT/JENKINS: Enable the loopback IP as a tcp and testing resource

- src/ucp/core/ucp_am.c
- src/ucp/proto/proto_am.c
- src/ucp/proto/proto_am.inl
- src/ucp/rndv/rndv.c
- src/ucp/rndv/rndv.h
- src/ucp/tag/tag_rndv.c
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_tag_offload.cc
- test/gtest/ucp/ucp_test.h
Handle status from AM/TAG RNDV RTS/data correctly in UCP progress functions.
If AM/TAG RNDV RTS/data sending failed in a progress function (i.e. the status is neither `UCS_OK` nor `UCS_ERR_NO_RESOURCE`), a UCP request has to be completed with the status, but `UCS_OK` should be returned from a function to satisfy `ucp_request_try_send()` expectations that `UCS_OK`/`UCS_INPROGRESS`/`UCS_ERR_NO_RESOURCE` statuses could be returned from progress functions.
1. Introduced `ucp_rndv_rts_handle_status_from_pending()` to handle `status` returned from RTS send progress function.
2. Used the new function to handle `status` returned for sending AM/TAG RNDV RTS packet.
3. Fixed possible failure during sending RNDV data - used `ucp_am_bcopy_handle_status_from_pending()` w/o completing a request.
4. …
> UCP/CORE/RNDV/GTEST: Handle status from AM/TAG RNDV RTS/data correctly

- src/ucs/datastruct/string_buffer.c
- src/ucs/datastruct/string_buffer.h
- test/gtest/ucs/test_string.cc
- Hex dump - will be used to dump rkey buffer
- Stream print - will be used to dump protocols information to string buffer, and then printing the to stream as part of `ucp_ep_print_info()`
> UCS/STRING_BUFFER: Add append_hex and dump-to-stream methods

- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
Fix a performance degradation in an application, introduced by #5499
Elapsed time results (T is baseline), lower is better:
| before #5499 | after #5499 | after this PR |
| --- | --- | --- |
| T| T*1.52 | T |
Set a minimal interval of requesting remote wakeup by sending ACK+REQ message with SOLICITED event. 
Hopefully, ACKs would arrive by that time, so would not need to send ACK+REQ any more.
> UCT/UD: Don't wake up remote peer for every ACKREQ packet

- test/apps/test_ucx_tls.py
fail on python test with print command from python2
Ubuntu 20.04 have default python3
set explicit python2
> CI: add support for UBUNTU20.04

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_request.h
- src/ucp/rndv/rndv.c
- test/gtest/ucp/test_ucp_mmap.cc
Implement PUT Zcopy multi-rail.
Align PUT Zcopy with GET Zcopy to allow using multiple devices for transports that have PUT Zcopy capability.
It improves performance like GET Zcopy multi-rail does.
e.g. multi-rail RNDV configuration for TCP transport (only 3 IP ifaces available on a given host, i.e. 3 RNDV lanes will be initialized for TCP tranposrt which supports only PUT Zcopy scheme):
```
$ UCX_TLS=tcp UCX_MAX_RNDV_LANES=4 ./src/tools/info/.libs/ucx_info -eptw -u tra
#
#
#
#
#
#
#
#
#
#
#
```
Re-use RNDV GET Zcopy multi-rail infrastructure for RNDV PUT Zcopy.
> UCP/RNDV: Implement PUT Zcopy multi-rail

- src/uct/ib/mlx5/ib_mlx5_log.c
- test/gtest/ucp/test_ucp_peer_failure.cc
Fix expected status in peer failure tests.
Fixes #6203
Flow:
0. Error handling was called for the test due to KEEPALIVE, the status of failure is `UCS_ERR_ENDPOINT_TIMEOUT`.
1. CQ returns Work Completion Element (WCE) with WR_FLUSH_ERR syndrome for send operation after the receiver was destroyed.
2. uct_rc_verbs_wc_to_ucs_status()/uct_ib_mlx5_completion_with_err() returns `UCS_ERR_CANCELED` for this error.
3. UCP send request completed with `UCS_ERR_CANCLED` status.
4. But gtest expects that UCP send request's completion status will be the same as in error handling callback, i.e. `UCS_ERR_ENDPOINT_TIMEOUT`.
1. Removed unreachable code in `uct_ib_mlx5_completion_with_err()` function, it checks `MLX5_CQE_SYNDROME_WR_FLUSH_ERR` syndrome twice.
2. Updated `test_ucp_peer_failure::do_test()` …
> UCT/UCP/GTEST: Fix expected status in peer failure tests

- src/tools/info/proto_info.c
- src/tools/info/ucx_info.c
- src/tools/info/ucx_info.h
- src/ucp/core/ucp_worker.c
- src/uct/ib/rdmacm/rdmacm_cm.c
decrease log level from error to diag if IB device is not present
fixes https://github.com/open-mpi/ompi/issues/8367
> UCT/RDMACM: decrease log level from error to diag

- src/ucp/core/ucp_mm.c
- src/uct/base/uct_md.c
- src/uct/base/uct_md.h
- src/uct/ib/base/ib_md.c
add diag prints to mem_reg path
for debug purposes
> UCP/UCT/MD: add diag prints to mem_reg path

- src/uct/ib/rc/accel/rc_mlx5.inl
Replaced manual static array size calculation by macro.
> UCT/IB/RC: Minor code fix.

- src/uct/ib/ud/base/ud_ep.c
- src/uct/ib/ud/base/ud_iface.c
- src/uct/ib/ud/base/ud_iface.h
Backport #6218 to release branch, since it fixes a significant degradation in applications' performance
> UCT/UD: Don't wake up remote peer for every ACKREQ packet -v1.10.x

- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
Remove sockaddr related fields in WIREUP EP.
It is not needed anymore.
1. Remove `sockaddr_ep` and `sockaddr_rsc_index` fields from `ucp_wireup_ep_t` structure.
2. Update all places where `sockaddr_ep` and `sockaddr_rsc_index` are used.
> UCP/WIRUEP: Remove sockaddr related fields in WIREUP EP

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/rc/accel/rc_mlx5_iface.c
Do not initialize `rx_hdr_len` in rc and dc constructors, because it is initialized in the common constructor (in `uct_rc_mlx5_iface_common_t`).
> UCT/RC: Clean rc/dc iface initialization

- src/uct/ib/dc/dc_mlx5_ep.c
- test/gtest/ucp/test_ucp_peer_failure.cc
- there could be situation when after flush(cancel) operation any
send operation may be posted without involving progress, in this
case send operation may failed with "cancel" state
> DC-MLX5/FLUSH-CANCEL: fixed flush(cancel) issue

- src/uct/tcp/tcp.h
- src/uct/tcp/tcp_ep.c
Handle peer failure in case of CONNECT_TO_EP.
Fixes #6161 
Fixes #6015
1. Fix minor comment typos and improve documentations of some code snippets.
2. Introduce `uct_tcp_ep_ptr_map_get()` function + common the function to check flags set.
3. Update `uct_tcp_ep_connect_to_ep()` (i.e. implementation of `uct_ep_connect_to_ep()` API function) to check whether an EP that has to accept a connection from a peer is on PTR MAP or not. If this EP doesn't exist in the EP PTR MAP, report `UCS_ERR_UNREACHABLE` status, since the peer was already connected and then disconnected from the local side.
> UCT/TCP: Handle peer failure in case of CONNECT_TO_EP

- src/ucs/sys/string.c
- src/ucs/sys/string.h
- src/ucs/sys/topo.c
- test/gtest/ucs/test_string.cc
When paths are of the `/a/b/c/d` and `/a/x/c/d`, current implementation of ucs_path_calc_distance continues processing after the segment `x`. I'm not sure why we had agreed on this logic. The side effect is that when looking for closest devices using sysfs paths, there is no difference between distance("/a/b/c/d", "/a/b/c/e") vs distance("/a/b/c/d", "/a/x/c/d"). This leads to sub-optimal NIC selection on some clusters.
> UCS/TOPO: Stop processing path similarity when first difference is encountered

- src/tools/info/proto_info.c
- src/tools/info/ucx_info.c
- src/tools/info/ucx_info.h
- src/ucp/core/ucp_worker.c
- src/uct/ib/rdmacm/rdmacm_cm.c
decrease log level from error to diag if IB device is not present
backport of https://github.com/openucx/ucx/pull/6210
cherry-picked
> UCT/RDMACM: decrease log level from error to diag v1.10.x

- .clang-format
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_rkey.c
- src/ucp/core/ucp_rkey.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- src/ucp/proto/proto.h
- src/ucp/proto/proto_common.c
- src/ucp/proto/proto_multi.c
- src/ucp/proto/proto_multi.h
- src/ucp/proto/proto_select.c
- src/ucp/proto/proto_select.h
- src/ucp/proto/proto_select.inl
- src/ucp/proto/proto_single.c
- src/ucp/proto/proto_single.h
- src/ucp/rndv/rndv.c
- src/ucs/datastruct/string_buffer.c
- test/gtest/ucp/test_ucp_proto.cc
- Use string buffer for protocol information dump, so they could be exported easily in VFS
- Add min/max to protocol config print, to print protocols that delegate to other protocols for different message size ranges (for example, rendezvous protocol)
- Consistent use of string buffer: the caller is responsible for initialization and cleanup. Allows using on-stack string buffers.
> UCP/PROTO: Improve new protocols logging

- test/gtest/ucp/test_ucp_wireup.cc
Don't ask for RMA feature in KA test.
To not skip `test_ucp_wireup_keepalive::attr` for TCP and UD/UD_X transports.
Before:
```bash
[==========] Running 8 tests from 8 test cases.
[----------] 1 test from dcx/test_ucp_wireup_keepalive
[ RUN      ] dcx/test_ucp_wireup_keepalive.attr/1 <dc_x/rma,unified>
[       OK ] dcx/test_ucp_wireup_keepalive.attr/1 (285 ms)
[----------] 1 test from dcx/test_ucp_wireup_keepalive (285 ms total)
[----------] 1 test from ud/test_ucp_wireup_keepalive
[ RUN      ] ud/test_ucp_wireup_keepalive.attr/1 <ud_v/rma,unified>
[     SKIP ] (no remote registered memory access transport to r-vmb-ppc-jenkins:26804: Unsupported operation)
[       OK ] ud/test_ucp_wireup_keepalive.attr/1 (105 ms)
[----------] 1 test from …
```
> GTEST/UCP: Don't ask for RMA feature in KA test

- src/ucp/core/ucp_mm.c
- src/uct/base/uct_md.c
- src/uct/base/uct_md.h
- src/uct/ib/base/ib_md.c
UCP/UCT/MD: add diag prints to mem_reg path
packported from https://github.com/openucx/ucx/pull/6219
@yosefe pls take a look and close if not needed
cherry-picked
> UCP/UCT/MD: add diag prints to mem_reg path, v1.10.x

- src/ucp/proto/proto_multi.inl
- src/ucp/rma/get_offload.c
- src/ucp/rma/put_am.c
- src/ucp/rma/put_offload.c
- src/ucp/tag/eager_multi.c
In order to extend proto_muti, we need to pass private data pointer.
ucp_proto_multi_priv_t ends with variable-size array of lanes, so it
must be the last member of any priv struct which contains it.
We cannot assume req->send.proto_config->priv would point to
ucp_proto_multi_priv_t in case of a derived protocol.
> UCP/PROTO/MULTI: Pass priv pointer to progress functions

- src/ucp/wireup/wireup.c
Fix comments.
Follow up fixes.
1. Fix copyright.
2. Use `!=` instead of `^.`
> UCP/WIREUP: Follow up fixes

- src/ucp/core/ucp_proxy_ep.c
Updated ep initialization setting proxy to uct_ep_am_short_iov interface.
> UCP/CORE: Updated ep initialization setting proxy to new interface.

- src/uct/ib/base/ib_iface.c
- test/gtest/uct/ib/test_ib.cc
- test/gtest/uct/ib/test_ib_pkey.cc
- test/gtest/uct/ib/test_ud_ds.cc
- Syncronise PATH MTU value between EP's
- On clusters where combination Connect-X3/Connect-X4+ are used there could be used incorrect values of PATH MTU values which prevents communication between sych systems
- Pack MTU value for HCA where non 4096 MTU are used
> IB/ADDRESS: pack MTU value for non 4K value

- test/gtest/uct/ib/test_sockaddr.cc
- test/gtest/uct/test_mm.cc
- test/gtest/uct/uct_p2p_test.cc
- test/gtest/uct/uct_test.cc
- test/gtest/uct/uct_test.h
- initialize UCT sockaddr tests by component name
- del unused `generate_test_variant` function
- fix wrongly skipping `rdmacm` tests due to unsupported `md_open` operation
- there is no need in dummy (sockaddr) TL name anymore
- allows to filter tests by component, for example "rdmacm" or "tcp"
> GTEST/UCT/SOCKADDR: fix instantiation and initialization

- NEWS
News format was changed slightly to include additional information based on git log merge commits.
> NEWS: News update before release

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.inl
- src/ucp/proto/proto_am.c
- src/ucp/proto/proto_am.inl
- src/ucp/rma/amo_sw.c
- src/ucp/rma/rma_sw.c
- src/ucp/rndv/rndv.c
- src/ucp/rndv/rndv.h
- src/ucp/stream/stream_recv.c
- src/ucp/tag/eager_snd.c
- src/ucp/tag/offload.c
- src/ucp/tag/tag_rndv.c
- src/ucp/wireup/wireup.c
- test/gtest/ucp/test_ucp_am.cc
- test/gtest/ucp/test_ucp_peer_failure.cc
- test/gtest/ucp/test_ucp_sockaddr.cc
- test/gtest/ucp/test_ucp_tag_offload.cc
- test/gtest/ucp/ucp_test.cc
- test/gtest/ucp/ucp_test.h
Backport of #6163 and #6001
Fixes are needed for users of releases on top of `v1.10.x` branch
Cherry-pick commits from the PRs
> UCP/CORE/RNDV/GTEST: Drop packets with invalid ID and fix handling of status in RNDV RTS/RTR/data [v1.10.x]

- src/tools/info/type_info.c
- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_context.h
- src/ucp/core/ucp_mm.c
- src/ucp/core/ucp_request.inl
- src/ucp/core/ucp_rkey.c
- src/ucp/core/ucp_rkey.h
- src/ucp/core/ucp_worker.inl
- src/ucp/dt/datatype_iter.h
- src/ucp/dt/datatype_iter.inl
- src/ucp/proto/proto_common.inl
- src/ucp/proto/proto_select.c
- src/ucp/proto/proto_select.inl
- src/ucp/rma/rma_sw.c
- src/ucp/stream/stream_recv.c
- src/ucp/stream/stream_send.c
- src/ucp/tag/tag_recv.c
- src/ucp/tag/tag_send.c
- src/ucs/memory/memtype_cache.c
- src/ucs/memory/memtype_cache.h
- test/gtest/ucp/test_ucp_mem_type.cc
- test/gtest/ucp/test_ucp_proto.cc
- test/gtest/ucs/test_memtype_cache.cc
- test/gtest/uct/test_md.cc
In order to select the best protocol and network device for every operation, need to detect the memory locality of user-provided buffer and save it in the UCP request
- Add `ucs_memory_info_t` structure to track both memory type and locality
- Add locality information to memory type cache
- Track memory locality in `ucp_request_t` as part of `ucp_datatype_iter_t`
> UCP/UCS: Detect and save memory locality of user buffers

- config/m4/compiler.m4
- test/gtest/ucs/test_pgtable.cc
Fixing gcc11 compilation issues for v1.10 release
backported from #6258
> CONFIG/TEST: Fix compilation on gcc11 - v1.10.x

- src/tools/info/tl_info.c
- src/ucp/core/ucp_context.c
- src/ucp/core/ucp_ep.c
Remove some old sockaddr flow code.
This code is not needed anymore.
1. Remove `UCT_MD_FLAG_SOCKADDR` occurrences in UCP code.
2. No need to handle other types except `UCP_WIREUP_SA_DATA_CM_ADDR`.
> UCP/CORE: Remove some old sockaddr flow code

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
Remove `status` field from the configuration key.
`status` field is not really needed anymore in the configuration key.
1. Remove `status` field from the structure.
2. Remove all occurrences of `status` in the code.
3. Fix code style in `ucp_ep_config_is_equal()` function.
> UCP/CORE: Remove status field from configuration key

- src/ucs/configure.m4
Set HAVE_HW_TIMER to zero for cross compile built
Set HAVE_HW_TIMER to zero for cross compile built
Fix for #6239 
Added case to configure script
> UCS: A fix for cross compilation support in configure

- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_verbs.h
With the rdma-core version 28.0 or higher the error code
returned by libibverbs for the case where ibv_cq_ex_to_cq
is not supported by the underlying transport has changed.
The transport layer now returns EOPNOTSUPP instead of 
ENOSYS.
Ucx is broken for all the transport devices which do not
have ibv_cq_ex_to_cq implemented. Fixing the error code
check in uct for IB devices.
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>
> UCT/IB: Fix cq creation failure using legacy ibv api

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.h
- test/gtest/ucp/test_ucp_am.cc
Fix invalid pointer free when releasing AM descriptor with non-empty user header, since ucp_am_data_release() does not consider user header size when calculating descriptor pointer from data handle
Save the distance from "data" pointer to malloc'd buffer pointer in newly introduced am_malloc_offset field
> UCP/AM: Fix releasing of deferred data

- src/ucp/proto/proto_am.inl
- src/ucp/wireup/wireup.c
- test/gtest/ucp/test_ucp_sockaddr.cc
Correctly handle failure from AM Bcopy.
To fix the error that can happen if AM Bcopy fails when sending WIREUP MSG.
Handle a failure from `uct_ep_am_bcopy()` in `ucp_wireup_msg_progress()` using `UCP_AM_BCOPY_HANDLE_STATUS` macro and returning `UCS_OK` in case of error.
> UCP/WIREUP: Correctly handle failure from AM Bcopy

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_worker.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
Added KA for TMP EP.
Do EP check for underlying TMP EP lanes to mase sure that a peer is still alive.
Also, fixes cases when UCP EP is going to be removed from KA, but it was not added before (i.e. for mem_type Eps)
1. Add useful assertion in KA add EP.
2. Remove EP from worker's all_eps list when destroying EP if it's not an internal EP (i.e. not a mem_type EP or not a TMP EP).
3. Do EP check for TMP EP inside WIREUP EP's EP check if TMP EP exists.
4. When checking whether UCP EP owns for UCT EP in WIREUP EP, also add a check for TMP EP lanes which can own this EP.
> UCP/CORE/WIREUP: Added KA for TMP EP

- src/uct/ib/base/ib_device.h
- src/uct/ib/base/ib_iface.c
- src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
- src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
Check lag state with lag_state bits。
We are checking the lag state/level according to sys fs. This is not a good approach. We have lag_state bits can indicate the lag state.
Use DevX to query lag_state bits. If lag state is enabled, get the lag level according to hcap_cap.num_lag_ports.
> UCT/IB: Check lag state with lag_state bits.

- src/uct/ib/base/ib_iface.c
- src/uct/ib/base/ib_verbs.h
With the rdma-core version 28 onwards the error code
returned from libibverbs for the case when ibv_cq_ex_to_cq
is not supported by the underlying transport has changed
from ENOSYS to EOPNOTSUPP.
Ucx is broken for the transport devices which do not
support ibv_cq_ex_to_cq while rdma-core version used
is 28+
Fixing the error code check to look for the right
error code.
Updated file headers to add Broadcom copyright
Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>
> UCT/IB: fix cq creation failure using old ibv api

- src/ucs/configure.m4
Back port of #6261, fixes #6239.
> UCS: A fix for cross compilation support in configure - v1.10.x

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListener.java
- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListenerParams.java
- bindings/java/src/main/native/jucx_common_def.cc
- bindings/java/src/main/native/listener.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
Do not delete a reference for ucpListener conn handler.
Fixes a bug when after the first invocation of conn handler reference is removed.
> JUCX: Do not delete reference to listener connHandler.

- src/ucp/core/ucp_am.c
- src/ucp/core/ucp_request.h
- test/gtest/ucp/test_ucp_am.cc
Fix invalid pointer free when releasing AM descriptor with non-empty user header, since ucp_am_data_release() does not consider user header size when calculating descriptor pointer from data handle
Save the distance from "data" pointer to malloc'd buffer pointer in newly introduced am_malloc_offset field
port from #6248 (note: this is not a clean cherry-pick due to different code bases)
> UCP/AM: Fix releasing of deferred data - v1.10.x

- src/uct/ib/base/ib_iface.c
- test/gtest/uct/ib/test_ib.cc
- test/gtest/uct/ib/test_ib_pkey.cc
- test/gtest/uct/ib/test_ud_ds.cc
- Syncronise PATH MTU value between EP's
- On clusters where combination Connect-X3/Connect-X4+ are used there could be used incorrect values of PATH MTU values which prevents communication between sych systems
- Pack MTU value for HCA where non 4096 MTU are used
cherry picked from https://github.com/openucx/ucx/pull/6216 as a single commit
> IB/ADDRESS: pack MTU value for non 4K value - v1.10

- src/ucp/api/ucp.h
- src/ucp/core/ucp_worker.c
- src/ucp/core/ucp_worker.h
- test/gtest/common/test.cc
- test/gtest/common/test.h
- test/gtest/ucp/test_ucp_worker.cc
Allow MPI runtime skip request leak check, which will silence errors like reported in https://github.com/open-mpi/ompi/issues/8426
> UCP/API: Flag to silence request leak check

- src/ucp/core/ucp_ep.c
Don't init EP list element.
Fixes https://github.com/openucx/ucx/pull/6235#discussion_r570631374
This is not needed anymore, since `ucp_ep_delete()` don't delete internal EPs from worker's EP list.
Remove unnecessary code.
> UCP/CORE: Don't init EP list elem

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/core/ucp_worker.c
- src/ucp/rma/flush.c
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
- src/uct/ib/rdmacm/rdmacm_cm_ep.c
- src/uct/tcp/tcp_ep.c
- test/gtest/common/test.cc
- test/gtest/ucp/test_ucp_sockaddr.cc
Fix #6225
Edit: Running ok about 16hrs with this fix. Before the fix - failed after 10-15min
- 1st commit fixes the issue:
- Enable keepalive on UCP client endpoint after getting connect response. init_lanes on wireup_ep->tmp_ep does not really enable keepalive
- Fix uct endpoint search for lanes contained in wireup_ep->tmp_ep
- 2nd commit adds more detailed logging
- ~~5th commit sets ep_check_map on client ep to send keepalive on wireup_ep. Before this change, the ep_check map was 0, so keepalive was not sent.~~  5th commit has incomplete fix
- 8th commit fixes sending ep_check over wireup_ep: need to set ep_check_map right when creating client CM ep, and connect tmp_ep's lanes when getting reply from the server.
> Fix keepalive during wireup and failures in sockaddr gtests

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
- test/gtest/ucp/test_ucp_sockaddr.cc
Fix check intersection, when comparing configuration created during `connect_cb()` and CM initial (fake) configuration on TMP EP.
The initial configuration created during CM client `pack_cb()` built on top of local information about MD/RSC indices, i.e. `dst_md_index` and `dst_rsc_index` aren't legal.
node n.1:
```
$ ucx_info -eptw
...
...
```
node n.2
```
$ ucx_info -eptw
...
...
```
1. Mark a CM initial configuration on a client as fake.
2. Fix `ucp_ep_config_lane_is_peer_equal()` lane comparing function to check only local characteristics (`rsc_index` and `path_index`).
3. `ucp_wireup_check_config_intersect()` will re-use the lanes from the old configuration, but it will be saved as a separate configuration in the configuration storage then, since they are not equal.
_Before_:
_After_:
> UCP/CORE/WIREUP/GTEST: Fix check intersection with CM initial configuration on TMP EP

- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
Fix filling `dst_rsc_index` for CM lane.
Unpacked addresses don't contain CM lane address. So, we should not touch it and fill `dst_rsc_index` as `UCP_NULL_RESOURCE`.
1. Initialize select info's address index for CM lane as `UINT_MAX`.
2. When filling `dst_rsc_indices` array, if a current lane is a CM lane, fill it by `dst_rsc_index` as `UCP_NULL_RESOURCE`.
3. Add useful checks.
> UCP/WIREUP: Fix filling dst_rsc_index for CM lane

- src/ucp/rndv/rndv.c
Fix https://github.com/openucx/ucx/issues/6206
is_get_zcopy_failed=1 if RKEY is null for send buffer if GDR off at sender.  need to register recv buffer to let sender try pipeline.
Set addr NULL in RTS if the sender key md_map is NULL for mem_type, so that it won't attempt get_zcopy at receiver
> UCP/RNDV: register recv buffer always for PUT/PIPELINE

- src/ucp/rndv/rndv.c
> UCP/RNDV: Set addr NULL in RTS if reg md_map is NULL. - v1.10.x

- src/ucp/core/ucp_request.inl
- src/ucp/proto/proto_common.c
- src/ucp/proto/proto_common.h
- src/ucp/proto/proto_common.inl
- src/ucp/proto/proto_multi.inl
- src/ucp/proto/proto_single.inl
- src/ucp/rma/get_am.c
- src/ucp/rma/get_offload.c
- src/ucp/rma/put_am.c
- src/ucp/rma/put_offload.c
- src/ucp/rma/rma_sw.c
- src/ucp/tag/eager_multi.c
- src/ucp/tag/eager_single.c
- src/ucp/tag/offload/eager.c
- Allow a protocol to keep request on pending queue even after multi-send phase finished - for protocols which send bulk data followed by an active message, e.g rendezvous put
- Common error handling for all protocols by calling `ucp_proto_request_abort`
- Common handling of no-resource to be re-used by pipelined rendezvous protocols
> UCP/PROTO: Adjustments in common proto-progress functions

- src/tools/info/proto_info.c
- src/tools/info/ucx_info.c
- src/tools/info/ucx_info.h
- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
Add support querying CM's UCP EP info/
`ucx_info` utility is useful to check the EP configuration on a concrete system, but lack of CM support doesn't allow to check CM UCP EP configuration.
1. Update `ucx_info` utility to accept `-A <ip_addr>` which should be used to specify IP address to connect to.
2. Add support for CM flow: creating listener, connection using socket address to the listener.
3. Add UCP EP flush to make sure that UCP EP has a final configuration.
4. Update UCP EP control extension to save CM index to have the access to the value any time, i.e. even after CM WIREUP EP is not available anymore.
5. Remove CM index field from WIREUP EP - it is needed anymore, UCP EP control extension one will be used to determine CM index.
6. Update `ucp_ep_config_print()` to accept UCP EP …
> UCP/CORE/INFO: Add support querying CM's UCP EP info

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/proto/proto_am.inl
- src/ucp/wireup/select.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
- src/ucp/wireup/wireup_ep.h
- test/gtest/ucp/test_ucp_sockaddr.cc
1. Fix WIREUP MSG AM Bcopy failure handling.
2.  Fix check intersection with CM initial configuration
1. The failure should be handled and `UCS_OK` must be returned to not fail `ucp_request_try_send()`.
2. The initial configuration created during CM client `pack_cb()` built on top of local information about MD/RSC indices, i.e. `dst_md_index` and `dst_rsc_index` aren't legal.
1. Backport of #6260 and #6283.
2. Backport of #6245 and #6296 with some adoptions (since #6127 is not a part of v1.10.x).
>  UCP/CORE/WIREUP/GTEST: Fix check intersection with CM initial configuration [v1.10.x]

- src/tools/info/proto_info.c
Fix compiler warning in TOOLS/INFO code.
Introduced in #6267, but all checks were successful.
```
icc: command line warning #10148: option '-Wno-unused-label' not supported
icc: command line warning #10148: option '-Wno-format-zero-length' not supported
icc: command line warning #10148: option '-Wnested-externs' not supported
icc: command line warning #10148: option '-Wno-unused-label' not supported
icc: command line warning #10148: option '-Wno-format-zero-length' not supported
icc: command line warning #10148: option '-Wnested-externs' not supported
/scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/tools/info/proto_info.c(358): error #177: label "out_destroy_worker" was declared but never referenced
out_destroy_worker:
```
Remove unused goto's label `out_cleanup_context`.
> TOOLS/INFO: Fix compiler warning

- src/uct/ib/base/ib_iface.h
Fix --without-dc compilation
https://github.com/openucx/ucx/issues/6311
> UCT/DC: Fix --without-dc compilation

- src/tools/perf/lib/libperf.c
- src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
- src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
- src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
- src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
- src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
- src/uct/cuda/cuda_ipc/cuda_ipc_md.c
- src/uct/cuda/cuda_ipc/cuda_ipc_md.h
- Move IPC cache from being a per-endpoint entity to per-iface entity
- This allows multiple endpoints from the same process to reuse peer mapped memory and not avoid reopening already opened memory handles
- needed for cuda < 11.1 to avoid fatal error when trying to re-open already opened memory handle
- By using a cache per remote process
- By using a hashtable of remote caches identified by remote pid
> UCT/CUDA: Make cuda_ipc cache global

- src/uct/rocm/copy/rocm_copy_md.c
Fix segfault for ROCm D2D transfers
Failure was introduced from a29b2f7ac7d874e4bb7b64b2e8744a821c96e8df due to calling undefined mem_query function
> UCT/ROCM: Fix missing mem_query definition for rocm_copy md

- bindings/java/src/main/native/Makefile.am
Preserve base config build flags for JUCX build
To build JUCX lib with the same flags (eg. gdb debug symbols, etc.).
> JUCX: preserve base config build flags.

- src/ucs/sys/sys.c
See address and flags passed to shmat() in case it fails
> UCS/SYS: Add debug information to shmat() failures

- bindings/java/src/main/java/org/openucx/jucx/UcxNativeStruct.java
- bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Implement equals and hashCode for native structs.
To compare endpoints that may be created in different places to make sure it's one underlying ucx endpoint.
> JUCX: compare native structs by id.

- bindings/java/src/main/java/org/openucx/jucx/ucp/UcpContext.java
- bindings/java/src/main/java/org/openucx/jucx/ucs/UcsConstants.java
- bindings/java/src/main/native/context.cc
- bindings/java/src/test/java/org/openucx/jucx/UcpContextTest.java
Query supported memory types by context.
1. To do smoke check in Rapids Spark + UCX that Cuda memory is supported (to not decrypt segfaults if is running on UCX that has no cuda support or can't load cuda).
2. In JUCX tests if cuda is supported - run tests with cuda buffers.
3. First step for (`ep.queryBandwidth(MEMORY_TYPE)`) API from #6254
> JUCX: context query supported memory types.

- src/uct/ib/base/ib_device.h
- src/uct/ib/ud/accel/ud_mlx5.c
- src/uct/ib/ud/base/ud_iface.h
- src/uct/ib/ud/verbs/ud_verbs.c
Fix UD gid filtering
Sometimes UD wrongly detects RoCE packet type, because it check GRH for that. But we can not rely on packet type in GRH header in case of RoCEv2/IPv4, because
According to Annex17_RoCEv2 (A17.4.5.2):
"The first 40 bytes of user posted UD Receive Buffers are reserved for the L3 header of the incoming packet (as per the InfiniBand Spec Section 11.4.1.2).  In RoCEv2, this area is filled up with the IP header. IPv6 header uses the  entire 40 bytes.
IPv4 headers use the 20 bytes in the second half of the reserved 40 bytes area (i.e. offset 20 from the beginning of the receive
buffer). In this case, the content of **the first 20 bytes is undefined**. "
Therefore if rx buffer rewrites GRH header (which happens when we initialize rdesc by headroom offset) it can wrongly set …
> UCT/IB/UD: Fix UD dgid filtering

- src/ucp/Makefile.am
- src/ucp/proto/proto.h
- src/ucp/proto/proto_common.inl
- src/ucp/proto/proto_reconfig.c
- src/ucp/proto/proto_select.c
During wireup phase, endpoint configuration may be incomplete, so need to delay protocol selection
> UCP/PROTO: Dummy "reconfig" protocol, which re-selects a new protocol

- src/ucp/core/ucp_listener.c
- src/ucp/core/ucp_worker.c
- src/ucp/proto/proto_am.inl
- src/ucp/rndv/rndv.c
- src/ucp/wireup/wireup.c
Add missing async blocks.
Fixes #6214 (missed block/unblcok in ucp_listener_accept_cb_progress()).
+ Fixes missing locks when accessing `ep->flags` in:
- `ucp_worker_discard_uct_ep_flush_comp()`
- `ucp_wireup_msg_progress()`
1. Update `UCP_AM_BCOPY_HANDLE_STATUS` macro to do user's exit action instead of `return ...`, fix all occurrences.
2. Update `ucp_wireup_msg_progress()` to do `goto out` instead of `return ...` to fix req and buffer leak and lack of async unblocking.
3. Wrap body of the following functions by `UCS_ASYNC_BLOCK`/`UCS_ASYNC_UNBLOCK`:
- `ucp_listener_accept_cb_progress()`
- `ucp_worker_discard_uct_ep_flush_comp()`
- `ucp_wireup_msg_progress()`
> UCP/CORE/WIREUP: Add missing async blocks

- src/uct/sm/base/sm_ep.c
- src/uct/tcp/tcp_ep.c
Use `UCT_EP_KEEPALIVE_CHECK_PARAM` macro instead of `UCT_CHECK_PARAM`.
Reduce code duplication.
Replace invoking `UCT_CHECK_PARAM` macro for UCT completion and for flush in EP check by invoking `UCT_EP_KEEPALIVE_CHECK_PARAM` macro for `TCP` and `SM`.
> UCT/SM/TCP: Use UCT_EP_KEEPALIVE_CHECK_PARAM macro instead of UCT_CHECK_PARAM

- buildlib/az-distro-release.yml
- buildlib/azure-pipelines-release.yml
Expand the matrix of os/cuda versions for binary release packages
> AZP: add new OS for release CI

- src/ucs/datastruct/bitmap.h
- test/gtest/ucs/test_bitmap.cc
Fix a bug in bitmap data structure (`UCS_BITMAP_POPCOUNT_UPTO_INDEX` macro)
Currently the macro iterates over the whole bitmap, including words that are beyond the requested bit index - which is incorrect behavior.
Stop iterating over words upon reaching the requested bit index.
> UCS/DATASTRUCT: Fix bitmap popcount

- src/ucp/core/ucp_listener.c
- src/ucp/core/ucp_worker.c
- src/ucp/proto/proto_am.inl
- src/ucp/rndv/rndv.c
- src/ucp/wireup/wireup.c
Add missing async blocks.
Fixes #6339 (Memory leak in `ucp_wireup_msg_progress()`, because if AM bcopy fails, we do return `UCS_OK` w/o freeing memory allocated for UCP request and address).
Fixes from #6318 are needed on v1.10.x.
Backported #6318 to v1.10.x.
> UCP/CORE/WIREUP: Add missing async blocks (v1.10.x)

- src/uct/ib/dc/dc_mlx5.c
- src/uct/ib/dc/dc_mlx5.h
- src/uct/ib/dc/dc_mlx5_ep.c
- src/uct/ib/dc/dc_mlx5_ep.h
- src/uct/ib/rc/base/rc_ep.c
- src/uct/ib/rc/base/rc_ep.h
- src/uct/ib/rc/base/rc_iface.h
- test/gtest/uct/ib/test_dc.cc
Add hash to track FC grant requests
Fix flush race. After sending FC grant request and calling flush(CANCEL) we can't know whether request was sent and will it be answered. Here we implement logic which checks whether EP which initiated request still available.
> UCT/DC: Add hash to track FC grant requests

- src/ucp/core/ucp_ep.c
- src/ucp/core/ucp_ep.h
- src/ucp/rma/flush.c
- src/ucp/wireup/wireup.c
- src/ucp/wireup/wireup.h
- src/ucp/wireup/wireup_cm.c
- src/ucp/wireup/wireup_ep.c
Do AM keepalive over AUX_EP or TMP_EP lanes if AUX EP or TMP_EP current KA lane is `CONNECT_TO_IFACE` in EP check for WIREUP EP.
Fixes #5192
Fixes #6320
During EP check for WIREUP EP: If AUX_EP or TMP_EP lane is `CONNECT_TO_EP`, do AM keepalive using `ucp_wireup_msg_send()` for `UCP_WIREUP_MSG_EP_CHECK` packet and pack resource index of a main EP's lane.
> UCP/WIREUP: Do AM KA over AUX_EP or TMP_EP lanes if conn2iface

- src/ucp/core/ucp_ep.c
Set UCT lanes to failed one when destroying UCP EP.
To fix the case when discarding of UCT EPs is in-progress and a user issues `ucp_ep_close_nbx(FORCE)` which set all UCT lanes of UCP EP to `NULL`. So, some UCT in-progress operation could be completed and UCP could dereference `NULL` pointer when touches lanes.
e.g. https://github.com/openucx/ucx/blob/719eb0de9d01a32a665a86db7711d36685b52cfa/test/apps/iodemo/ucx_wrapper.cc#L537
leads to the following segmentation fault when GET Zcopy completed and UCP is trying to send ACK to a peer:
```gdb
[1613560606.016788] [UCX-connection #2 2.1.3.18:44768] detected error: Connection reset by remote peer
[1613560606.017234] [DEMO] deleting connection with status Connection reset by remote peer
[1613560606.017241] [UCX-connection #2 2.1.3.18:44768] …
```
> UCP/CORE: Set UCT lanes to failed one when destroying UCP EP

- test/apps/iodemo/ucx_wrapper.cc
Progress connection requests while waiting for operation request completion.
The client can fail connection establishment if a peer is not accepting connection requests for a while, when it closes some connection and waiting for all UCP requests to be completed.
In UCX connection destructor progress all UCX context (i.e. worker progress, conn_reqs queue progress, failed connections, IO messages) while waiting for all UCP requests to be compeleted.
> APPS/IODEMO: Progress connection requests while waiting for operation request completion

- buildlib/azure-pipelines-pr.yml
sametime clean up workdir fails on build stage
problems with git?!
build script on each stage make clean workir and we can avoid `checkout: clean true` 
it can solve problem with cleanup and decrease time of execution
> AZP: Fix for clean workdir

- src/ucp/core/ucp_am.c
Enable multi-rail for UCP AM eager bcopy protocol
Now it is enabled for zcopy only
> UCP/AM: Enable multi-rail for UCP AM bcopy proto

- src/ucp/wireup/wireup.c
1. Fix destroying EP which is `NULL` in WIREUP_MSG/EP_CHECK handler.
2. Don't unpack an address received in a message if UCP EP is valid during handling WIREUP_MSG/EP_CHECK.
1. If `ucp_ep_flush_internal()` is completed with an error or OK immediately, `ucp_ep_disconnected()` was called for `NULL` EP.
2. After understanding that UCP EP is valid, no need to do address unpacking when handling WIREUP_MSG/EP_CHECK, because it takes some time.
1. Simplify code to not have a single return point that destroys UCP EP (e.g. if `ucp_ep_flush_internal()` completed successfully or some error during sending WIREUP_MSG or some error during initializing lanes).
2. After a success form `UCP_WORKER_GET_EP_BY_ID` (i.e. EP is valid), check whether the message type is `UCP_WIREUP_MSG_EP_CHECK` or not. If this …
> UCP/WIREUP: Fix destroying NULL EP + don't unpack address if UCP EP is valid in EP_CHECK handler
