src/ucm/event/event.c
I don't have an actual failure case in UCX to point to here, but I can show how the current code is dangerous.
In `src/ucm/util/replace.h` the _UCM_DEFINE_REPLACE_FUNC macro creates the code for functions like ucm_override_brk() which begin and end with UCM_BISTRO_PROLOGUE / EPILOGUE.
I'll show how the code inside that function is sensitive to compiler behavior that can sometimes save a copy of the r2 register before the PROLOGUE macro (the purpose of those macros is to save/modify/restore r2 since the table of contents for the function we just branched into is different than wherever we just branched from, like brk()).
If you modify the macro in `src/ucm/util/replace.h` to have the extra lines:<br>
(before the UCM_BISTRO_PROLOGUE):
```
typedef void   (*MyFunction_t) ();
volatile …
```
=> noinline to avoid compiler reading TOC before UCM_BISTRO_PROLOGUE

NEWS
=> NEWS: Updating news to reflect rc4 changes

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpConnectionRequest.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpointParams.java, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
Get client address from connection handler.
To easier debug in SparkUCX to which process is endpoint created from connection handler.
=> JUCX: get connection handler client address.

test/gtest/common/mem_buffer.cc
Do not try to set GPU device if not exists. Fixing a change introduced in #5737.
Check for Cuda/ROCm support before setting the GPU device context
=> TEST/COMMON: Set GPU device only if supported

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c
Peer-accessibility map is a 2-d matrix and it was incorrectly initialized following restructuring. This PR fixes that.
=> UCT/CUDA_IPC: fix peer-access-map init

src/ucs/debug/debug.c
Fix pointer (`==>` sign) and line numbers to source code line in backtrace.
`n` starts from `0`, but `line` - from `1`.
before:
```
[swx-dgx01:32231:0:32231]    ucp_ep.inl:162  Assertion `ucs_async_is_blocked(&ep->worker->async)' failed
/labhome/dmitrygla/work_auto/ucx/src/ucp/core/ucp_ep.inl: [ ucp_ep_set_flags() ]
...
159 ucp_ep_set_flags(ucp_ep_h ep, ucp_ep_flags_t flags)
160 {
161     ucs_assert(ucs_async_is_blocked(&ep->worker->async));
==>   162     ep->flags |= flags;
163 }
164
165 static UCS_F_ALWAYS_INLINE void
==== backtrace (tid:  32231) ====
```
after:
```
[swx-dgx01:48758:0:48758]    ucp_ep.inl:162  Assertion `ucs_async_is_blocked(&ep->worker->async)' failed
/labhome/dmitrygla/work_auto/ucx/src/ucp/core/ucp_ep.inl: [ ucp_ep_set_flags() ]
...
159 static UCS_F_ALWAYS_INLINE …
```
=> UCS/DEBUG: Fix pointer to source code line in backtrace

src/ucs/debug/debug.c
Remove the internal function `ucs_debug_print_backtrace` from the backtrace, this function is just generating the backtrace and not part of the error itself.
=> UCS/DEBUG: Filter-out ucs_debug_print_backtrace from backtrace

contrib/ucx_perftest_config/test_types_ucp
Avoid duplicate test names, so when a test fails/struck it will be easy to know its parameters
=> CONTRIB/PERF: Fix perftest batch test names

buildlib/az-distro-release.yml, buildlib/az-helpers.sh, buildlib/azure-pipelines-pr.yml, buildlib/azure-pipelines-release.yml, buildlib/io_demo/az-stage-io-demo.yaml, buildlib/jucx/jucx-test.yml, buildlib/tests.yml, buildlib/tools/builds.sh, buildlib/tools/common.sh
- Set fetchDepth for all cases
- Specific module versions
- Better warning messages
- Fix clang-format git versions - need to fetch remote branch
- Don't try to load armclang on unsupported archs
- Reduce some timeouts
=> AZP: Small fixes

docs/source/running.md
Fix typo in docs(at line 78 of ucx/docs/source/running.md)
when configuring OpenMPI with UCX
--prefix option should be `<ompi-install-path>`,
--with-ucx option should be `<ucx-install-path>`.
In the docs both options are misplaced. 
diff at line 78
```
- ../configure --prefix=<ucx-install-path> --with-ucx=<ompi-install-path>
+ ../configure --prefix=<ompi-install-path> --with-ucx=<ucx-install-path>
```
Thank you for your great work.
=> DOCS: Fix typo in docs

src/uct/ib/base/ib_md.c
Trace ibv_reg_mr time.
To debug slow register time.
=> UCT: trace ibv_reg_mr time.

buildlib/io_demo/az-stage-io-demo.yaml, contrib/test_jenkins.sh, test/apps/iodemo/io_demo.cc
APPS/IODEMO: Fix 'print interval' argument
```
$/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210223_221853_8790_27029_jazz24.swx.labs.mlnx/installs/0YsU/tests/io_demo/ucx.git/install/bin/io_demo -d 512:524288 -P 5 -p 20000
[1614158702.880653] [DEMO] Starting io_demo pid 50339 on jazz24.swx.labs.mlnx
[1614158702.880751] [DEMO] Command line: /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210223_221853_8790_27029_jazz24.swx.labs.mlnx/installs/0YsU/tests/io_demo/ucx.git/install/bin/io_demo -d 512:524288 -P 5 -p 20000
[1614158702.880974] [DEMO] UCX library path: /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210223_221853_8790_27029_jazz24.swx.labs.mlnx/installs/0YsU/tests/io_demo/ucx.git/install/bin/io_demo
[jazz24:50339:0:50339] Caught signal 11 (Segmentation fault: address not mapped to object at …
```
=> APPS/IODEMO: Fix 'print interval' argument

src/ucp/core/ucp_worker.c, src/ucs/datastruct/arbiter.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_ep.h, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_perf.cc
Fix #6304
* UD: Return correct event count from progress
* SM: Make sure arm() would fail if some endpoints can't send. Since we don't have a method to get notifications about send resource updates from the receiver.
* Re-enable gtests for UD and SM
* Some refactoring in SM transport: improve logging, remove unneeded fields
=> Fix wakeup for UD and shared memory transports

src/ucp/core/ucp_am.c, test/gtest/ucp/test_ucp_am.cc
Use correct ep for sending short AM with reply protocol
backport of #6398 
(cherry picked from commit cb69bcc18839ce5b069f038cee7eb8012e2b8d71)
=> UCP/AM: Use correct ep for short send with reply - v1.10.x

src/ucp/core/ucp_am.c, test/gtest/ucp/test_ucp_am.cc
Use correct ep for sending short AM with reply protocol
Fixes #6394
=> UCP/AM: Use correct ep for short send with reply

src/uct/api/uct.h, src/uct/cuda/base/cuda_md.c, src/uct/rocm/base/rocm_base.c, test/gtest/uct/test_md.cc
Allow uct_md_mem_query to return base address and allocation length of the original allocation if the md can detect the memory type for the given buffer. This would allow cuda_cpy md to return base address and allocation length for the UCP registration function to register the whole allocation length as opposed to just user provided length and amortize registration cost for subsequent registration requests for buffers belonging to the same allocation.
=> UCT/API: return base addr and alloc len from md_mem_query

buildlib/io_demo/az-stage-io-demo.yaml, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.c, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/base/rc_iface.c, test/gtest/uct/ib/test_dc.cc
In case LAG is enabled maintain separate pool of DCIs for each bonded port.
UCP will open separate UCT EP for each bonded port to provide full LAG bandwidth.
LAG egress port determined by DCI tx_port_affinity parameter so EP created for specific port will use DCI from pool bound to this port.
=> UCT/DC: DCI pool per LAG port

src/uct/ib/base/ib_iface.h
Fix iov2sge converter in IB.
Fixes #6414.
After merging #6308, the problem is reproduced due to sending data without a local key.
In the test - a user `4011`-length AM header is packed after a user data is `0`, so memory handle (which is `NULL`) for a user data is used for setting a user `4011`-length AM header.
Use the correct iterator (`sge_it` -> `iov_it`) when checking the memory handle of a given IOV.
=> UCT/IB: Fix iov2sge converter

src/ucs/profile/profile_on.h, test/gtest/ucs/test_profile.cc
Fix nesting level in UCS_PROFILE_FUNC macro - before the fix, function contents appeared outside of its scope
Broken by #5894
=> UCS/PROFILE/TEST: Fix profiling scope in UCS_PROFILE_FUNC macro

src/tools/perf/lib/ucp_tests.cc, test/gtest/ucp/test_ucp_perf.cc
Allow 0-size messages benchmarking with UCP AM and TAG protocols
Performance of 0-size messages is important for various synchronization patterns (e.g.  barrier), would be good to support benchmarking for it
=> TOOLS/PERF/UCP: Allow 0 length msg for AM and TAG benchmarks

src/uct/cuda/cuda_copy/cuda_copy_iface.c
Fix performance estimation of cuda/host transfers, which will be used for calculating thresholds for pipelined protocols
=> UCT/CUDA/COPY: Adjust performance estimations

src/uct/ib/base/ib_device.c
Assertion in async event flow
To debug an issue in the flow (callbackq.c:541 Assertion `idx < priv->num_fast_elems' failed)
=> UCT/IB: Assert that async event not handled twice

src/uct/ib/rdmacm/rdmacm_listener.c
Fix debug log message: do not print port twice in sock address
=> UCT/RDMACM: do not print port twice in addr dbg msg

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h
Added context name to UCP parameters.
The parameter is required to identify the context during run time analysis of UCX-based application. E.g. ucx_vfs tool.
=> UCP/API: Added context name to UCP parameters.

src/ucp/rndv/rndv.c, test/gtest/ucp/test_ucp_am.cc
1. Fix UCP AM memtype rndv gtests:
Now use correct memory type for send buffers, which was always HOST memory previously
2. Fix rndv bugs uncovered by rndv gtests. The failing flow was:
- put pipeline protocol is started from non-HOST memory
- Fragment is fetched from the memtype ep and put protocol is started from `ucp_rndv_put_pipeline_frag_get_completion`
- Put operation is split into multiple chunks. Second chunk goes to another lane and is added to pending
- Completion for the first chunk is invoked (`ucp_rndv_send_frag_put_completion`) and request is released to the mpool
- Released request accessed during progression of the second chunk
=> UCP/GTEST: Fix rndv pipeline flows

src/uct/ib/base/ib_md.c
Fix PCIe throughput calculation, which is used for selecting protocols thresholds, and support PCIe gen4
[1] https://www.xilinx.com/support/documentation/white_papers/wp350.pdf
[2] https://xdevs.com/doc/Standards/PCI/PCI_Express_Base_4.0_Rev0.3_February19-2014.pdf
[3] https://www.nxp.com/docs/en/application-note/AN3935.pdf
=> UCT/IB: Fix PCIe bandwidth calculation

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c
Fix doing force-close without error handling.
flush(CANCEL) isn't allowed for transport without error handling support.
1. Fix JUCX to create UCP EPs with error handling mode.
2. Set `UCP_EP_FLAG_FAILED` for UCP EP before discarding lanes.
3. Add check that `UCP_ERR_HANDLING_MODE_PEER` is requested when discarding lanes.
4. Don't do discarding for `ucp_failed_tl_ep`.
=> UCP/CORE/JAVA: Fix doing force-close without error handling

src/ucp/wireup/select.c, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/base/cuda_iface.c, src/uct/cuda/base/cuda_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h, src/uct/sm/base/sm_ep.c, src/uct/sm/base/sm_ep.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_ep.h, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/mm/base/mm_md.c, src/uct/sm/mm/base/mm_md.h, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, src/uct/sm/mm/xpmem/mm_xpmem.c, test/gtest/common/test_obj_size.cc, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
Introduce CUDA-IPC keepalive.
To use CUDA-IPC transport in UCP EPs created with error-handling support.
1. Moved KA-related code implemented in SM and MM to the common code in `uct/base/uct_iface.[ch]`.
2. Split MM ep_check to two phases `create` and `ep_check` itself.
3. Re-used the common code in MM transports (i.e. their common code).
4. Re-used the common code in CUDA-IPC transport:
- create keepalive in `uct_ep_create()`, because there is no access them to pid/startime of a peer (this data is packed as UCT iface address)
- use common ep_check functionality in `uct_ep_check()`
5. Update CUDA-IPC iface address to include process start time (`ucs_time_t`) in addition to self process ID (`pid_t`).
6. Updated UCT keepalive gtest to test CUDA-IPC + adoption.
7. Updated `test_obj_size.cc` …
=> UCT/BASE/CUDA/GTEST: Introduce CUDA-IPC keepalive

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_listener.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/ep_match.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucs/async/async.c, src/ucs/async/async.h, src/ucs/async/async_fwd.h, src/ucs/async/thread.c, src/ucs/async/thread.h, src/ucs/type/spinlock.h, src/uct/tcp/tcp_sockcm_ep.c, test/gtest/ucp/test_ucp_worker.cc, test/gtest/ucs/test_async.cc
1. Add checking of async ownership.
2. Verify `ucp_ep_t::flags` set/unset + add async block/unblock in `ucp_worker_create()` and gtest.
3. Replace places where UCX has the comment "must call with lock held" by checking async ownership + Fix the bugs.
1. This is the method to catch possible issues with missing block/unblock. This mechanism was used to fix a bug in #6214.
2. To catch possible missing block/unblock when set/unset EP flags.
3. To have a check for async ownership to catch possible programming errors.
1. Save `owner` (if `count == 0`) and increment `count` in ASYNC block; reset `owner` (if `count == 0`) and decrement `count` in ASYNC block.
2. Replace setting/unsetting EP flags by calling `ucp_ep_set_flags()`/`ucp_ep_unset_flags()` which checks ownership; Add …
=> UCS/ASYNC/UCP/UCT: Added checking of is_blocked

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, debian/rules.in
JUCX is used solely from maven dependency. 
To not mess up classpath with libjucx.so.  
cc @abellina
=> AZP: do not include libjucx into release packages.

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, debian/rules.in
What
JUCX is used solely from maven dependency.
Why ?
To not mess up classpath with libjucx.so.
porting #6440 to 1.10 if possible
=> AZP: do not include libjucx into release packages. [v.1.10]

src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, test/gtest/ucs/test_vfs.cc
Added three methods to manipulate VFS object tree structure:
- Add directory representing object in VFS.
- Add read-only file describing object features in VFS.
- Recursively remove directories and files associated with the object and its children from VFS.
These methods should be used to add directories and files describing UCX objects, e.g. context, worker, ep, etc.
This is an initial set of methods which will be extended further.
=> UCS/VFS: Implemented methods to manipulate VFS object tree structure.

src/ucp/dt/datatype_iter.inl, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.inl, src/ucp/proto/proto_single.inl, src/ucp/rma/get_offload.c, src/ucp/rma/put_offload.c, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv_get.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload/eager.c
Pass registration flags according to the operation we are going to perform
=> UCP/PROTO: Pass accurate memory registration flags

src/ucs/config/parser.c
Before:
```
#
#
#
UCX_TLS=all
```
=> UCS: remove a redundant space in the syntax of UCX_TLS

buildlib/az-distro-release.yml, buildlib/azure-pipelines-pr.yml, buildlib/azure-pipelines-release.yml, buildlib/jucx/jucx-publish.yml
1. Extend build matrix with cuda 11.0 and 11.2 versions
2. Run release build pipeline when submitting a PR with "AZP/RELEASE" in the title, so we can test it without tagging a release
=> AZP: Add dockers with cuda11.2 for release

test/apps/iodemo/io_demo.cc
shuffle servers list 
cherry-picked and squashed https://github.com/yosefe/ucx/pull/108 and https://github.com/yosefe/ucx/pull/110
to optimize scalable startup
=> IODEMO: shuffle servers list to optimize scalable startup

Makefile.am, src/uct/api/v2/uct_v2.h, src/uct/base/uct_iface.c, test/gtest/Makefile.am, test/gtest/uct/v2/test_uct_query.cc
Support querying a UCT interface (`uct_iface_query`) by operation and memory type
Allow finer granularity in the information retrieved by querying the interface.
The change is breaking and not backwards compatible, but future fields can be added without breaking compatibility, as the structs are now refactored to hold pointers rather than contain nested data.
=> UCT/API: Support interface query by operation and memory type

src/ucp/core/ucp_am.c, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv.h, src/ucp/tag/tag_rndv.c
Introduce common RNDV/RTS send function for AM/TAG.
To improve code sharing.
1. Introduce `ucp_rndv_send_rts()` function.
2. Use the function for sending RNDV RTS in AM and TAG.
=> UCP/CORE/RNDV: Introduce common RNDV/RTS send function for AM/TAG

src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_sockaddr.cc
Print warning if client ep connection failed with all available cms.
Give a hint to user to enable needed device in UCX_NET_DEVICES or use another ip address for connection.
Error strings example is:
```
wireup_cm.c:158  UCX  DIAG  client ep 0x7f6212ebd000 connection failed: device mlx5_3:1 is not enabled, enable it in UCX_NET_DEVICES or use corresponding ip address
wireup_cm.c:158  UCX  DIAG  client ep 0x7f6212ebd000 connection failed: device p2p2 is not enabled, enable it in UCX_NET_DEVICES or use corresponding ip address
wireup_cm.c:102  UCX  WARN  client ep 0x7f6212ebd000 failed to connect using rdmacm,tcp cms, set UCX_LOG_LEVEL=diag for more details
```
=> UCP: Print error if no proper device exists for ep connection

src/ucp/rma/get_am.c, src/ucp/rma/rma_sw.c
Delete local request ID when GET Reply received.
Local request ID has to be destroyed at the end of GET SW protocol.
1. Remove deleting local request ID in GET AM Bcopy complete callback (`ucp_proto_get_am_bcopy_complete()`).
2. Add deleting local request ID in `ucp_get_rep_handler()` when full data was delivered.
=> UCP/RMA: Delete local request ID when GET Reply received

src/ucp/rndv/rndv.c
disqualify pipeline rndv if mem type endpoint not exist
with UCX_RNDV_THRESH=0 and for < 64B  get_zcopy is not supported on IB (min_get_zcopy=64) and fallback to PIPELINE/PUT_ZCOPY/AM.  in this case need to check.  mem type ep not present if runs with only IB (-x UCX_TLSD=ib)
=> UCP/RNDV: Check mem type ep for pipeline rndv 

docs/source/index.rst
Fix broken link, since examples folder was moved in recent versions
=> DOCS/RTD: Fix examples link

src/ucp/core/ucp_am.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/proto/proto_am.inl, src/uct/ib/base/ib_iface.c, src/uct/ib/ud/base/ud_iface.c, test/gtest/ucp/test_ucp_am.cc
1. Use `uct_ep_am_short_iov` for UCP AM short protocols
2. Increase default `IB_TX_MIN_SGE` to 4 (from 3), to fit all UCP AM data together with UCT header
1. Enable short protocol for the cases when both data and header are sent
2. Extend message range for short protocol
=> UCP/AM: Use short_iov for short protocols

src/ucp/core/ucp_ep.c, src/ucp/wireup/wireup_cm.c
Do cleanup of cbq after destroying EP lanes.
`ucp_ep_destroy_base()` is called after completing flush/discard operation to decrement `ref_cnt` and check whether UCP EP should be destroyed or not.
in this case UCP EP can be completed, but some operation can be in cbq for some operation scheduled on this EP - it leads to crash when touching UCP EP which is already destroyed.
Move cbq cleanup to the `ucp_ep_destroy_base()`.
=> UCP/CORE: Do cleanup of cbq after destroying EP lanes

src/ucs/memory/rcache.c, src/ucs/memory/rcache.h, src/ucs/memory/rcache_int.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/cuda/gdr_copy/gdr_copy_md.c, src/uct/ib/base/ib_md.c, src/uct/sm/mm/xpmem/mm_xpmem.c, src/uct/sm/scopy/knem/knem_md.c, test/gtest/ucs/test_rcache.cc
Support limiting max size or regions number in the registration cache.
An rcache without limits might consume an unlimited amount of memory, which is undesirable.
Add an LRU struct in the cache, evicting old regions in case limits are exceeded.
=> UCS/UCT/RCACHE: Add memory usage limits to registration cache

src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_sockaddr.cc
Print CS connection failures with DIAG level instead of ERROR to avoid log flooding during interference tests
=> UCP: Print conn failures to diag instead of error

src/ucp/core/ucp_mm.c
Don't print diag message if memory type registration is not supported.
To avoid flooding by printouts about unsupported memory type registration, e.g. an attempt to register HOST memory type in UCT/CUDA-IPC MD.
if memory type registration is unsupported on UCT MD, do `continue` instead of printing a trace w/ `DIAG` or `ERROR` level.
=> UCP/CORE: Don't print diag message if memory type registration is not supported

src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_request.h, src/ucp/rma/flush.c, src/ucp/rma/rma.inl
Make flush requests to be iterated as hlist elements instead of queue elements.
It is required by #5821 PR to use the same `list_elem` for `proto` and `flush` requests (it will require just moving list iterator from `ucp_request_t::send::flush::list_elem` to `ucp_request_t::send::list_elem`).
1. Replace all occurrences when we operate with flush request as queue element to use it as hlist element.
2. Change type for flush requests container from `ucs_queue_head_t` to `ucs_hlist_head_t`.
=> UCP/CORE/RMA: Make flush reqs to be hlist instead of queue

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm_ep.c, test/gtest/ucs/test_sock.cc
Enhance error print for rdma_resolve_addr.
Print source and destination address passed to `rdma_resolve_addr()` for better debugging.
1. Declare `src_ip_port_str` and `dst_ip_port_str`.
2. Fill them by `ucs_sockaddr_str()` to source and destination address respectively.
3. Update `ucs_error()` string.
=> UCT/IB/RDMACM: Enhance error print for rdma_resolve_addr

test/apps/iodemo/io_demo.cc
Fix this segfault:
```
[<host>:78800:0:78800] Caught signal 11 (Segmentation fault: Sent by the kernel at address (nil))
==== backtrace (tid:  78800) ====
0 0x000000000013df74 __strchr_sse42()  :0
1 0x0000000000410b94 DemoClient::connect()  <path>/installs/e2Lm/tests/io_demo/ucx.git/test/apps/iodemo/io_demo.cc:1445
2 0x00000000004111c4 DemoClient::connect_all()  <path>/installs/e2Lm/tests/io_demo/ucx.git/test/apps/iodemo/io_demo.cc:1525
3 0x000000000041162c DemoClient::run()  <path>/installs/e2Lm/tests/io_demo/ucx.git/test/apps/iodemo/io_demo.cc:1580
4 0x000000000040ba79 do_client()  <path>/installs/e2Lm/tests/io_demo/ucx.git/test/apps/iodemo/io_demo.cc:2185
5 0x000000000040be50 main()  <path>/installs/e2Lm/tests/io_demo/ucx.git/test/apps/iodemo/io_demo.cc:2228
6 0x00000000000223d5 …
```
=> TEST/IODEMO: Fix corruption in random_shuffle

src/uct/ib/base/ib_md.c, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/mlx5/exp/ib_exp_md.c
Suppress warning if a device can't be opened as we do in EXP verbs and DevX.
Experimental verbs and DevX don't print a warning in this case:
- exp: https://github.com/openucx/ucx/blob/e72bf40e4f805479c636a48c06be6337daf45f95/src/uct/ib/mlx5/exp/ib_exp_md.c#L625
- devx: https://github.com/openucx/ucx/blob/e72bf40e4f805479c636a48c06be6337daf45f95/src/uct/ib/mlx5/dv/ib_mlx5dv_md.c#L628
`ucs_warn(...)` -> `ucs_debug(...)`
=> UCT/IB/VERBS: Suppress warning if device can't be opened

src/ucs/datastruct/string_buffer.c, src/ucs/datastruct/string_buffer.h, test/gtest/ucs/test_string.cc
Added method to get string from `ucs_string_buffer_t` which can be freed with method which deallocates memory, e.g. ucs_free.
The method is required to unblock changes in FUSE callback implementation. It addresses [review comment](https://github.com/openucx/ucx/pull/6456#discussion_r594143078).
=> UCS/DATASTRUCT: Added method to get string buffer which can be freed manually.

src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, test/gtest/ucs/test_vfs.cc
Added methods to expose objects in VFS:
- Fill information about VFS node corresponding to the specified path.
- Read the content of VFS node corresponding to the specified path.
- Invoke callback for children of VFS node corresponding to the specified path.
The methods are required to implement UCS/VFS file system operations.
=> UCS/VFS: Added methods to expose objects in VFS.

src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c
fix uct_rdmacm_cm_cqs hash key
`pd->handle` is always `0` in container
make safer key
=> UCT/RDMACM: fix uct_rdmacm_cm_cqs hash key

src/uct/api/tl.h, src/uct/api/uct.h, src/uct/api/uct_def.h
- UCP can change endpoint configuration only from main thread (to avoid race with send operatations)
- Pack callback is always called on progress thread, and has to provide private data blob pack to the CM
- Currently, UCP maintains a tmp_ep to hold the new transports config after connection establishment, which creates many complications on the wireup flow
- In order to cleanup the code and get rid of tmp_ep, need to split pack callback to 2 parts: getting the async notification on progress thread, and providing the private data to the CM on main thread
extend client server connection establishment API
- client side, `uct_cm_ep_priv_data_pack_callback_t` can be replaced
with `uct_cm_ep_resolve_callback_t` + `uct_ep_connect`
- server side, `uct_cm_ep_priv_data_pack_callback_t` can be …
=> UCT/API/SOCKADDR: extend connection establishment API

src/ucp/core/ucp_am.c
Align sending AM first header with AM middle header.
Set the size of the middle header to `0` instead of its real size when sending the first fragment.
This is the same as we do for sending the middle fragment.
`sizeof(mid_hdr)` -> `0ul`
=> UCP/CORE: Align sending AM first header with AM middle header

src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, test/gtest/uct/ib/test_ib_event.cc
Put event handler directly on progress queue. Event handler will remove itself.
- Event dispatcher and event callback proxy concurrently write to cb_id causing race.  
- Set cb->id to NULL under dev->event_lock
=> UCT/IB: Remove event callback proxy

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_worker.c, src/ucp/rma/flush.c, src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_worker.cc
Fix in-progress worker flush when some EP was force-closed.
Worker flush operation crashes if touches EP which is already destroyed.
1. Increment EP's `ref_cnt` when Worker flush operation points to EP.
2. Fix `ref_cnt` assertion to expect it equal to `num_flush_inprog + num_discard_inprog + 1`
=> UCP/CORE/RMA: Fix in-progress worker flush when some EP was force-closed

src/ucp/core/ucp_am.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, test/gtest/ucp/test_ucp_am.cc
Implement support for ucp_am_recv_data_nbx() routine for eager messages
User may want to "unpack" arrived eager data to GPU memory or/and some specific datatype
=> UCP/AM: Implement ucp_am_recv_data_nbx for eager messages

src/ucp/rma/flush.c
Fixes #6514 
Issue introduced in #6458
worker-flush ep iterator was not advanced, as a result we started many flush operations on same endpoint, causing memory leak and hang.
=> UCP/EP: Fix worker flush iterator advance

src/ucp/core/ucp_context.c
Added creation of directory to represent context in VFS during initialization. Added removing VFS object associated with context within clean up.
The changes are required to analyze and debug UCX-based applications.
=> UCP/CORE: Added node to represent context in VFS.

bindings/java/src/main/native/jucx_common_def.cc, src/ucp/core/ucp_context.c, src/ucp/core/ucp_request.c, src/ucs/Makefile.am, src/ucs/async/async.c, src/ucs/async/signal.c, src/ucs/config/parser.c, src/ucs/datastruct/callbackq.c, src/ucs/debug/assert.c, src/ucs/debug/debug.c, src/ucs/debug/debug.h, src/ucs/debug/debug_int.h, src/ucs/debug/log.c, src/ucs/profile/profile.c, src/ucs/sys/init.c, src/uct/base/uct_iface.c, src/uct/ib/rc/base/rc_ep.h, test/gtest/ucs/test_debug.cc
- function ucs_debug_disable_signal is public UCS API
- function ucs_debug_disable_signal is is needed to disable handling of some signals by UCX
- debug.h header is marked as public
- function ucs_debug_disable_signal is moved into public header
=> UCS/DEBUG: added ucs/debug.h file

src/ucp/core/ucp_request.c
Release request ID in send request fast-forward.
To fix assertion about releasing UCP request for which UCP request ID is still allocated.
Check if UCP request ID is not set to `UCP_REQUEST_ID_INVALID`, if it is not set to this value, release UCP request ID calling `ucp_request_id_release()`
=> UCP/CORE: Release request ID in send request fast-forward

src/tools/perf/lib/libperf.c
- there was issue in potential incorrect free on error handling:
in case if memory could not be allocated incorrect
free operation may be called
=> LIBPERF: fixed incorrect error handling

src/tools/perf/lib/libperf.c
- there was issue in potential incorrect free on error handling:
in case if memory could not be allocated incorrect
free operation may be called
(cherry picked from commit e7894da3bd2ecfb68f91becec62b005e5edbd0c5)
backport from https://github.com/openucx/ucx/pull/6513
=> LIBPERF: fixed incorrect error handling - v1.10

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.h
Remove disconnect part of send request.
`disconnect` part of send request is not really used.
1. Remove `send.disconnect`.
2. Remove all occurrences of `send.disconnect`.
=> UCP/CORE: Remove disconnect part of send request

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup.c
Use string buffer in `ucp_ep_config_lane_info_str`
1. To pass debug string in #6487 
2. To unify debug methods to accept string buffer where possible (now some accepts string buffer, some char*, some FILE*)
=> UCP/EP: use string buffer for ep lane info.

src/ucp/core/ucp_worker.c
Decrease log level for keepalive progress to func.
This log is happening inside a loop 
Making a trace log file of size 15 G:
```
$ll -h work/app-20210318180451-0017/3/stdout
-rw-r--r-- 1 prudenko tape 15G Mar 18 20:35 work/app-20210318180451-0017/3/stdout
```
And occupies 99% of the log file.
=> UCP/WORKER: Decrease log level for keepalive progress.

contrib/valgrind.supp
Filter-out valgrind errors from xpmem userspace library
=> CONTRIB/VALGRIND: Add suppression for xpmem_get

src/ucp/Makefile.am, src/ucp/core/ucp_context.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_types.h, src/ucp/core/ucp_worker.c, src/ucp/proto/proto_common.inl, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, test/gtest/ucp/test_ucp_tag_match.cc
- Support cases when zero copy is not possible
- Add RTR protocol as preparation for RNDV over put_zcopy
- Add rndv_rtr protocol which just sends back RTR message
- Add rndv_am protocol which sends the data itself
- Don't disable rndv protocols completely based on rndv scheme. Instead, use cfg_thresh, which allows fallback to rndv_am if nothing else was found.
=> UCP/RNDV: Implement new rendezvous protocol over active messages

src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, test/gtest/ucp/test_ucp_worker.cc, test/gtest/ucp/ucp_test.cc
Fixes #6486 
- Add worker flag to indicate SERIALIZED mode
- Add unit test
=> UCP/WORKER/TEST: Fix ucp_worker_query() thread mode for SERIALIZED

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
implement non-blocking connection establishment
to improve scalability
=> IODEMO: non blocking connection establishment

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/base/ud_inl.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/tcp/tcp_ep.c, test/gtest/uct/test_uct_ep.cc
Purge outstanding operations in EP destroy.
After doing `uct_ep_destroy(ep)` a user doesn't expect receiving completions for already destroyed UCT EP, but UD doesn't fit this requirement and reports completions from `uct_iface_close(iface)` for UCT EPs which are closed by a user.
Also, purge outstanding operation in TCP's `uct_ep_destroy()`.
1. Do `uct_ud_ep_purge(ep, UCS_ERR_CANCELED);` in `uct_ud_ep_disconnect(ep)` which is UD's `uct_ep_destroy(ep)` that does deferred UD destroy to be able send ACKs to a peer.
2. Purge outstanding GET/PUT Zcopy and flush operations for TCP EP.
3. Added gtest to reproduce the issue.
=> UCT/UD/TCP/GTEST: Purge outstanding operations in EP destroy

bindings/java/src/main/java/org/openucx/jucx/UcxException.java, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java, buildlib/jucx/jucx-test.yml, src/ucp/core/ucp_ep.c
Use random port for JUCX listener test + print address where Listener is bound. 
To better understand fails https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/14708/logs/241
=> JUCX: use random port and print listener address.

src/tools/vfs/vfs_server.c
Fixed hang in case of failed mounting replacing closing method by removing.
vfs_server_remove_fd includes vfs_server_close_fd and sets required fields of VFS server context. The replacement allowed to release client waiting for an answer from server.
The issue was triggered by failed of fuse_open_channel while mounting directory.
=> TOOLS/VFS: Fixed hang on failed VFS mount.

src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_multi.h, src/ucp/proto/proto_multi.inl, src/ucp/proto/proto_select.c, src/ucp/proto/proto_single.c, src/ucp/rndv/proto_rndv.c, src/ucs/sys/math.h, test/gtest/ucs/test_math.cc
Add bandwidth optimizations for multi-lane common logic of new protocols:
- Remove lanes with low bandwidth
- Calculate relative weights and fragments size, proportional to bandwidth
Configuration example where the bandwidth on mlx5_0 is ~100Gbs and mlx5_2 is ~50Gbs - eager protocol fragment size and bandwidth is proportional to BW ratio:
```
```
Full output:
```
$ UCX_NET_DEVICES=mlx5_0:1,mlx5_2:1 UCX_MAX_EAGER_LANES=2 UCX_PROTO_ENABLE=y ./build-devel/src/tools/info/ucx_info -u t -e -D net
#
#
#
#
#
```
=> Bandwidth optimizations for new protocols multi-lane

src/ucp/proto/proto_select.c
Fix deleting invalid iterator from khash.
To fix possible undefined behavior when deleting `khiter` which is `kh_end(&proto_select->hash)` in case of `ucp_proto_select_elem_init()` failed by some reason (e.g. `ucs_malloc()` returns `NULL`).
Just remove `kh_del(ucp_proto_select_hash, &proto_select->hash, khiter);` from the body which handles failure from `ucp_proto_select_elem_init()` function.
=> UCP/PROTO: Fix deleting invalid iterator from khash

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_worker.cc
Don't destroy UCT EP from UCT pending callback.
To avoid possible arbiter guard check failures, when `uct_ep_flush()` returns OK in a pending callback which is called from an arbiter. It causes calling `ucs_arbiter_group_purge()` from `uct_ep_destroy()` while UCT is in `ucs_arbiter_dispatch()`
```
[<host>:9399 :0:9410]     arbiter.c:116  Assertion `(group)->guard == 0' failed: scheduling arbiter group 0x7fffbc161ae0 while it's being dispatched
/labhome/dmitrygla/work_auto/ucx/src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_purge() ]
...
113         return; /* Empty group */
114     }
115
==>   116     UCS_ARBITER_GROUP_GUARD_CHECK(group);
117
118     head = tail->next;
119     next = head;
==== backtrace (tid:   9410) ====
0 0x0000000000050d22 ucs_arbiter_group_purge() …
```
=> UCP/CORE: Don't destroy UCT EP from UCT pending callback

src/ucp/core/ucp_request.inl, src/ucp/rndv/proto_rndv.c, src/ucp/tag/eager_rcv.c
1. Check that request ID released when completing a request.
2. Release request ID in RNDV proto RTR handler, otherwise, it won't be released when completing RNDV AM.
3. Release request ID in Eager/Sync proto upon receiving SYNC-ACK for TAG offload.
1. To make sure that we are completing UCP request when a request ID is released by UCP protocol, because `ucp_request_free()` can be called by a user and request will be put to mpool.
2. Release request ID upon handling RNDV RTR packet, since it is no longer needed + fixing possible release request ID after a request is already released.
3. Release request ID in Eager/Sync proto upon receiving SYNC-ACK for TAG offload, since it is no longer needed + fixing possible release request ID after a request is already released.
1. Add check for …
=> UCP/CORE/RNDV: Check that request ID released when completing request + fix in RNDV and Eager/Sync

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_types.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/core/ucp_worker.inl, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_wireup.cc
Renamed UCP worker structure field from name to address_name. Adjusted related structure fields and methods names.
The changes are prerequisites to adding API method to set worker name. The name will be used for analysis tools such as VFS monitor.
=> UCP/CORE: Renamed worker name to worker address name.

src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
Dispatch Arbiter after updating TX resources.
The PR fixes the following flow:
Peer failure detected on some UCT EP and it releases TX resources. So, now UCT IFACE has TX resources for doing AM/RMA/AMO operations on other UCT EPs created on the UCT IFACE.
So, calling `uct_ep_flush(ep, LOCAL)`/`uct_ep_am_bcopy()` (or other operations) returns `UCS_OK` for UCT EPs created on UCT IFACE, but the are some pending requests. So, it could lead to out-of-order problems or broken flush operations which leads to not sending the user's data.
1. Call `ucs_arbiter_dispatch()` at the end of `uct_rc_mlx5_common_update_tx_res()`.
2. Caller has to scheduled/deschedule EP if needed before calling `uct_rc_mlx5_common_update_tx_res()`.
3. If error happens, deschedule EP arbiter group from arbiter to avoid …
=> UCT/IB/RC: Dispatch Arbiter after updating TX resources

test/apps/iodemo/ucx_wrapper.cc
fix `stream_recv_callback` on failed connection
bugfix, if the connection is already failed the establish callback is NULL
=> IODEMO: fix stream_recv_callback on failed conn

buildlib/azure-pipelines-pr.yml
static_checks don't fail when make fail
add check pipe status via `set -o pipefail`
=> AZP: add pipe status check for static_checks

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.inl, src/uct/ib/dc/dc_mlx5_ep.c
Dispatch Arbiter after updating TX resources.
The PR fixes the following flow:
Peer failure detected on some UCT EP and it releases TX resources. So, now UCT IFACE has TX resources for doing AM/RMA/AMO operations on other UCT EPs created on the UCT IFACE.
So, calling `uct_ep_flush(ep, LOCAL)`/`uct_ep_am_bcopy()` (or other operations) returns `UCS_OK` for UCT EPs created on UCT IFACE, but the are some pending requests. So, it could lead to out-of-order problems or broken flush operations which leads to not sending the user's data.
1. Call `ucs_arbiter_dispatch()` in `uct_dc_mlx5_ep_handle_failure()`.
2. Deschedule EP arbiter group from arbiter to avoid dispatching requests, they should be purged by a user rather than dispatched.
=> UCT/IB/DC: Dispatch Arbiter after updating TX resources

src/ucp/core/ucp_request.h
Remove `sreq_id` from RMA part of send request.
It is not needed anymore, since `ucp_request_t::id` can be used instead.
1. Remove sreq_id file of `ucp_request_t::send::rma`.
2. Fix code style.
=> UCP/CORE: Remove sreq_id from RMA part of send request

NEWS, src/ucp/api/ucp.h, src/ucp/core/ucp_context.c, test/gtest/ucp/test_ucp_context.cc
Add ucp_lib_query API in order to query lib thread mode support 
We would like to add an api to query the lib thread mode before ucp_context+ucp_worker Are created. This is required for UCC - there the “thread_mode” is a property of ucc_lib_info_t object. User creates lib_info with the required thread_mode and then can create different ucc_context_t from the lib object. Ucp_worker is created when ucc_context is created, ie after the lib object is allocated
Query thread mode according to UCX MT compilation flag
=> UCP: Add ucp_lib_query API

contrib/check_inst_headers.sh, src/tools/info/sys_info.c, src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/lib/uct_tests.cc, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_select.c, src/ucs/sys/math.h, src/ucs/time/time.h, test/gtest/ucs/test_math.cc
Fix compilation error when using SIZE_MAX from C++ code
Issue introduced by #6534 
@leibin2014
=> Avoid using SIZE_MAX in header file

src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_iface.c
Use wrapper for close fd instead.
It is better to use a wrapper to make sure that `fd` is reset to `-1`.
It is needed to debug which socket fd created/closed.
Replace `close()` by `ucs_close_fd()`
=> UCT/TCP: Use wrapper for close fd instead

src/ucp/api/ucp.h
Fix  the documentation on ucp_request_param_t in ucp.h to use the field name of the callback instead of the union's field type.
Make the doc correct
=> UCP: Documentation of ucp_request_param_t uses type name instead of field name for callback function

src/ucp/core/ucp_listener.c
Don't reset flush state from lisntener's `accept_cb` progress function.
UCP EP flush state is reset prior scheduling `accpt_cb` progress, i.e. in
https://github.com/openucx/ucx/blob/24eb448d07f4b13bbfe0295b3f499f112550ae6a/src/ucp/wireup/wireup_cm.c#L1134
Removed `ucp_ep_flush_state_reset()` from `ucp_listener_accept_cb_progress()`.
=> UCP/CORE: Don't reset flush state from accept_cb

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, test/gtest/ucp/test_ucp_tag_offload.cc, test/gtest/ucp/test_ucp_worker.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Do local flush for AUX EP and then destroy.
To fix the following issue:
```
[prm-dgx-27:7416 :0:7416] rc_mlx5_iface.c:119  Assertion `ep != ((void *)0)' failed
```
UCT EP was destroyed, but it is not flushed prior. So, CQE is received for QP for which UCT EP was destroyed.
Discard AUX EP with FLUSH_CANCEL
=> UCP/WIREUP: Do local flush for AUX EP and then destroy

config/m4/compiler.m4
This PR suppresses warnings that prevented the NV HPC SDK 21.2 toolchain from compiling UCX.
I need to compile UCX with the NV HPC SDK 21.2. 
I just suppressed the warnings and filled #6576 to track investigating and fixed them. Some of the warnings appeared legit (casting enums to integers and back, taking the size of an integer when the size of an enum was intended, unreachable code, and others).
=> BUILD/CONFIG: Suppress warnings to unbreak NV HPC SDK compilers

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c
Fix the following error:
```
$ UCX_TLS=dc_x UCX_IB_NUM_PATHS=4 ucx_info -u t -e
[1617018848.398069] [host:22817:0]      ib_mlx5_dv.c:237  UCX  ERROR mlx5dv_devx_obj_modify(503) failed, syndrome 0: Invalid argument
<Failed to create UCP worker>
[1617018848.436915] [host:22817:0]           mpool.c:44   UCX  WARN  object 0xab5bc0 was not returned to mpool devx dbrec
[1617018848.436926] [host:22817:0]           mpool.c:44   UCX  WARN  object 0xab5c00 was not returned to mpool devx dbrec
[1617018848.436930] [host:22817:0]           mpool.c:44   UCX  WARN  object 0xab5c40 was not returned to mpool devx dbrec
[1617018848.436933] [host:22817:0]           mpool.c:44   UCX  WARN  object 0xab5c80 was not returned to mpool devx dbrec
[1617018848.436936] [host:22817:0]           mpool.c:44   UCX  WARN …
```
=> UCT/DC: Fix UCX_IB_NUM_PATHS influence on DCI pool logic

src/uct/base/uct_iface.h, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/mm/base/mm_md.h, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, src/uct/sm/mm/xpmem/mm_xpmem.c
Fix MM transports iface configuration table inheritance
Before:
```
$ucx_info -c | grep  _FIFO_SIZE
UCX_MM_FIFO_SIZE=64
UCX_MM_FIFO_SIZE=64
UCX_MM_FIFO_SIZE=64
```
After
```
$ucx_info -c | grep  _FIFO_SIZE
UCX_POSIX_FIFO_SIZE=64
UCX_SYSV_FIFO_SIZE=64
UCX_XPMEM_FIFO_SIZE=64
```
Now can adjust vars for every transport separately as well as for the common parent config:
```
$UCX_POSIX_FIFO_SIZE=0 ./src/tools/info/ucx_info -c | grep  _FIFO_SIZE
UCX_POSIX_FIFO_SIZE=0
UCX_SYSV_FIFO_SIZE=64
UCX_XPMEM_FIFO_SIZE=64
$UCX_MM_FIFO_SIZE=0 ./src/tools/info/ucx_info -c | grep  _FIFO_SIZE
UCX_POSIX_FIFO_SIZE=0
UCX_SYSV_FIFO_SIZE=0
UCX_XPMEM_FIFO_SIZE=0
```
- Fix config prefix in `UCT_MM_TL_DEFINE`
- For each transport define its own table, so that:
1. all have common parent config
2. it is possible to …
=> UCT/MM: Fix iface config inheritance

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c
Allow EP flush cancel from EP pending callback if only this request is scheduled.
Fixes:
```
[jazz07:71516:0:71516]       rc_ep.c:505  Assertion `ucs_arbiter_group_is_empty(&ep->arb_group)' failed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210328_234532_183193_31254_jazz03.swx.labs.mlnx/installs/HDr3/tests/io_demo/ucx.git/src/uct/ib/rc/base/rc_ep.c: [ uct_rc_ep_flush() ]
...
502     }
503 
504     if (ucs_unlikely(flags & UCT_FLUSH_FLAG_CANCEL)) {
==>   505         ucs_assert(ucs_arbiter_group_is_empty(&ep->arb_group));
506         ep->flags |= UCT_RC_EP_FLAG_FLUSH_CANCEL;
507     }
508 
==== backtrace (tid:  71516) ====
0 0x0000000000033ca3 uct_rc_ep_flush()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210328_234532_183193_31254_jazz03.swx.labs.mlnx/installs/HDr3/tests/io_demo/ucx.git/sr …
```
=> UCT/RC/DC: Allow EP flush cancel from EP pending callback if only this request is scheduled

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, src/ucp/rma/flush.c, src/ucp/rma/rma.inl, src/ucp/rndv/rndv.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, test/gtest/common/test_obj_size.cc, test/gtest/ucp/test_ucp_sockaddr.cc
Clean up proto reqs on failure
To fix UCP request leak when they are not UCT-managed (i.e. not send in-progress or not in pending)
Use UCP EP extension to save submitted UCP requests (only TAG sync send and TAG/AM RNDV) to hlist
Purge them from hlist when UCP EP failed
=> UCP/EP: Cleanup proto reqs on failure

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c
Align DC with RC pending queue dispatch + minor fixes.
Make DC pending dispatch function aligned with RC one:
- don't check for IFACE TX resources prior to calling pending callback - it is not needed, each callback which does AM/RMA/flush check it prior to doing an operation
- reorganize code to check IFACE TX resources and return `UCS_ARBITER_CB_RESULT_STOP` if they are not available; and then assume that EP TX resources are not available and return `UCS_ARBITER_CB_RESULT_DESCHED_GROUP`.
- update assertion accordingly
Fix duplication of `operations` word in the comment and code style in RC and DC dispatch functions.
1. Make DC code structure the same as in RC.
2. Remove `operations` word from the comment and align code according to the code style
3. Split the format string in the …
=> UCT/RC/DC: Align DC with RC pending queue dispatch + minor fixes

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/tag/eager_rcv.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_worker.cc
Remove EP ID dependant progress functions after releasing EP ID.
Release EP ID only when EP `refcount` reaches `0`
Fixes #6568
The bug was introduced in #6459 when moved filtering and removing progress functions to the place where EP is really destroyed, i.e. when UCP EP `refcount` reaches `0`.
So, it happens that UCP EP ID is released, but a progress function for sending WIREUP_MSG/ACK packet is scheduled and trying to get UCP EP ID which is released.
1. Introduced `ucp_ep_set_failed()` that did all needed actions prior to setting `FAILED` flag to UCP EP, i.e. releases EP ID and deschedules progress callback for sending WIREUP_MSG/ACK packet.
2. Move releasing of UCP EP ID to the place when UCP EP is really destroyed, i.e. calling `ucp_ep_set_failed()` in `ucp_ep_destroy_base()`
3. Reset …
=> UCP/CORE: Remove EP ID dependant progress functions after releasing EP ID

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpAmData.java, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Support receiving eager messages
Could be useful in SparkUCX to not force RNDV flag for small messages, but rather ucx to decide protocol, and if needed to copy to GPU memory just  by calling ucp_amdata_recv
=> JUCX: Support AM recv eager messages.

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/rndv/rndv.c
- there was issue in error handling during rndv ack send:
in case if it failed to send ack message then request may
be completed twice which caused incorrect processing
=> UCP/RNDV: fixed potential crash on rndv ack send

src/uct/rocm/base/rocm_base.c
Fix build failure due to 713694658b
=> UCT/ROCM: fix build failure due to const violation

src/uct/sm/mm/base/mm_iface.c, src/uct/sm/mm/base/mm_iface.h
Enable peer failure support for `posix` and `sysv` transports. 
Make it configurable and off by default 
This would allow using shm transports for various client-server applications, which typically create eps with error handling support
```
$./src/tools/info/ucx_info -d | grep -A 31 posix | grep "error handling"
$./src/tools/info/ucx_info -d | grep -A 31 sysv | grep "error handling"
$UCX_MM_ERROR_HANDLING=on ./src/tools/info/ucx_info -d | grep -A 31 posix | grep "error handling"
$UCX_MM_ERROR_HANDLING=on ./src/tools/info/ucx_info -d | grep -A 31 sysv | grep "error handling"
$./src/tools/info/ucx_info -c | grep _ERROR_HANDLING
UCX_POSIX_ERROR_HANDLING=off
UCX_SYSV_ERROR_HANDLING=off
```
=> UCT/POSIX/SYSV: Define peer failure config

contrib/test_jenkins.sh, src/ucp/wireup/select.c, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_devx.c
Fix the following error:
```console
$ UCX_HANDLE_ERRORS= UCX_IB_NUM_PATHS=4 UCX_MAX_EAGER_LANES=4 UCX_MAX_RNDV_LANES=4 ./build-devel/src/tools/info/ucx_info -u t -e 
[1617123185.782686] [host:135476:0]          select.c:548  UCX  ERROR   cannot add am_bw lane - reached limit (6)
[1617123185.800600] [host:135476:0]          wireup.c:1031 UCX  ERROR   old: am_lane 0 wireup_msg_lane 5 cm_lane <none> reachable_mds 0x7ff ep_check_map 0x0
[1617123185.800625] [host:135476:0]          wireup.c:1041 UCX  ERROR   old: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self     am am_bw#0
[1617123185.800631] [host:135476:0]          wireup.c:1041 UCX  ERROR   old: lane[1]: 31:xpmem/memory.0 md[10]          -> md[10]/xpmem    rkey_ptr
[1617123185.800635] [host:135476:0]          wireup.c:1041 UCX …
```
=> UCP/WIREUP/TEST: Fix endpoint reconfiguration error with many lanes

src/uct/rocm/copy/rocm_copy_md.c, src/uct/rocm/ipc/rocm_ipc_md.c
fix sockaddr_accessibility test for rocm_copy and rocm_ipc
```
$ ./gtest --gtest_filter=*rocm*sockaddr*
[     INFO ] dc_x is not available
[     INFO ] ud_v is not available
[     INFO ] ud_x is not available
[     INFO ] rc_v is not available
[     INFO ] rc_x is not available
[     INFO ] ugni is not available
[     INFO ] rc,dc is not available
[     INFO ] ud is not available
[     INFO ] ud_mlx5 is not available
[     INFO ] rc_x,rc_v,ud_x,ud_v is not available
[     INFO ] dc_x,ud_x,ud_v is not available
[     INFO ] rc_x,rc_v is not available
[     INFO ] ib is not available
[     INFO ] rc is not available
[     INFO ] Using random seed of 24185
Note: Google Test filter = *rocm*sockaddr*
[==========] Running 2 tests from 2 test cases. …
```
=> UCT/ROCM: fix sockaddr_accessibility test for rocm_copy and rocm_ipc

src/ucp/tag/probe.c, src/uct/api/uct.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/ud/base/ud_iface.c, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/self/self.c, test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_tag.cc, test/gtest/uct/uct_p2p_test.cc, test/gtest/uct/uct_p2p_test.h, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
Define interface for aligning Active Messages received in UCT transport buffers.
Some applications can't use UCP AM receive zero copy capabilities, because they need AM data to be properly aligned.
This PR introduces UCT interface for aligning AM receive buffers, which will further be used by UCP.
=> UCT/API/TLS: Define AM alignment in iface params

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
Added worker name to UCP worker parameters to identify the worker.
Added worker name to UCP worker attributes to get the actual worker name.
The parameter is required for more convenient run time analysis of UCX-based application. E.g. ucx_vfs tool.
=> UCP/API: Added name to worker parameters.

src/ucp/core/ucp_request.c, src/ucp/proto/proto_am.inl, src/ucp/rndv/rndv.c
Wait for all completions in case of error handling.
Don't fast-forward sends which are owned by UCT.
Fixes:
```
[jazz26:53617:0:53617]   uct_iface.h:692  Assertion `comp->count > 0' failed: comp=0x29a40e0 count=0
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210402_054559_169009_786_jazz05.swx.labs.mlnx/installs/mLOx/tests/io_demo/ucx.git/src/uct/base/uct_iface.h: [ uct_invoke_completion() ]
...
689 void uct_invoke_completion(uct_completion_t *comp, ucs_status_t status)
690 {
691     ucs_trace_func("comp=%p, count=%d, status=%d", comp, comp->count, status);
==>   692     ucs_assertv(comp->count > 0, "comp=%p count=%d", comp, comp->count);
693 
694     uct_completion_update_status(comp, status);
695     if (--comp->count == 0) {
==== backtrace (tid:  53617) ====
0 0x0000000000033797 …
```
=> UCP/CORE/RNDV: Wait for all completions in case of error handling

src/uct/base/uct_iface.h
Print function name when completing.
To improve debugging.
Use `ucs_debug_get_symbol_name()` to get completion function name and then print it.
=> UCT/BASE: Print function name when completing

test/gtest/configure.m4
Suppress the "pointless comparison of unsigned integer with zero" warning.
In UCS bitmap test, `UCS_BITMAP_MASK(&bitmap, 0)` is called which leads to such "pointless comparison".
Without suppressing this warning, the code won't compile with PGICC.
=> UCS/GTEST: Suppress comparison of unsigned with zero

src/ucp/wireup/address.h
Don't pack TL resource index in CM private data.
TL destination resource indices are used by intersection logic and after worker address is already received where all addresses are sent with their TL resource indices.
So, there is no need to pack TL resource index of the transport selected during CM phase - to shorten CM private data and be compatible with the previous UCX versions which don't pack TL resource index.
Remove `UCP_ADDRESS_PACK_FLAG_TL_RSC_IDX` flag from `UCP_ADDRESS_PACK_FLAGS_CM_DEFAULT` pack flags.
=> UCP/WIREUP: Don't pack TL resource index in CM private data

src/ucp/wireup/address.c
Make unified/non-unified iface addresses packed to shorten worker address.
`ucp_address_packed_iface_attr_t`: 16 -> 16
`ucp_address_unified_iface_attr_t`: 8 -> 5
Add `UCS_S_PACKED` before structure definitions.
=> UCP/WIREUP: Make device/iface addresses packed to shorten worker address

buildlib/azure-pipelines-pr.yml, buildlib/tools/builds.sh, src/tools/perf/lib/uct_tests.cc, src/ucs/datastruct/bitmap.h
- Test build on rhel 7.2
- Separate long/short build tests, to increase build matrix without increasing test time: some of the build tests do not really need to run on each distro's minor version.
replaces #6603
=> AZP: Add rhel7.2 and rhel7.4 to build.sh matrix

src/ucp/api/ucp.h
Replaced 'maximal' by 'maximum' in UCP/API docs.
The changes are required to make the documentation more consistent.
The changes were requested in these review comments:
https://github.com/openucx/ucx/pull/6557#discussion_r604469311
https://github.com/openucx/ucx/pull/6557#pullrequestreview-626636615
=> UCP/API: Replaced 'maximal' by 'maximum' in UCP/API docs.

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/rndv/rndv.c
use `req->send.proto.comp_cb` instead of UCT completion for ATP/ATS err handling
It's confusing to use UCT completion for error handling path only
ported from https://github.com/yosefe/ucx/pull/55
=> UCP/RNDV: fix ATP/ATS completion on failure

src/ucp/wireup/wireup.c
Fix err flow of KA EP
```
21 static inline ucp_ep_config_t *ucp_ep_config(ucp_ep_h ep)
22 {
==>    23     ucs_assert(ep->cfg_index != UCP_WORKER_CFG_INDEX_NULL);
24     return &ep->worker->ep_config[ep->cfg_index];
25 }
26 
==== backtrace (tid:  21048) ====
0 0x00000000000312ec ucp_ep_config()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_ep.inl:23
1 0x0000000000031301 ucp_ep_is_cm_local_connected()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_ep.c:2537
2 0x0000000000041cb9 ucp_worker_set_ep_failed()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_worker.c:501
3 0x00000000000c001e ucp_wireup_init_lanes_by_request()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup.c:443
4 0x00000000000c18d4 …
```
=> UCP/WIREUP/KA: fix ucp_wireup_send_ep_removed err flow

src/ucs/configure.m4
- set default log level for release mode: debug
- useful to improve error handling in release builds
- updated configuration script
=> UCS/LOG: set default log level debug for release build

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_worker.c, test/gtest/ucp/test_ucp_worker.cc
The intent of the PR is to fix UCT EP discarding when manipulating with the hash.
The PR fixes the following bugs:
- UCT EP is not deleted from hash upon discarding operation completion.
- Dangling pending/flush callbacks after the discarded operation was completed from UCT error handling (e.g. RC just purges all outstanding operations).
1. Introduce new tests for UCT EP discarding functionality:
- flush is in progress, don't wait comp and destroy EP and Worker.
- operation is in a pending queue, don't wait comp and destroy EP and Worker.
- flush OK, don't wait and destroy EP and Worker.
2. Added instrumentation of scheduled progress functions for a given UCT EP discarding operation (i.e. for a given UCP request) - when adding progress function, no other operation should be scheduled.
3. …
=> UCP/CORE/GTEST: Keep discarding hash aligned with completed operations

src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/tcp/tcp_sockcm_ep.c, src/uct/tcp/tcp_sockcm_ep.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Handle error provided by conn_cb/conn_notify_cb when pack_cb wasn't called.
Reproduced with RDMACM:
```
server is listening on IP 12.10.44.11 port 13337
Waiting for connection...
Server received a connection request from client at address 12.10.44.11:39527
[swx-rdmz-ucx-gpu-01:17731:0:17731]   wireup_cm.c:1262 Assertion `(uct_cm_ep) == ucp_ep_get_cm_uct_ep(ucp_ep)' failed: 0x7fbc409130f0: uct_cm_ep=0xce1680 vs found_uct_ep=(nil)
/labhome/dmitrygla/ucx/src/ucp/wireup/wireup_cm.c: [ ucp_cm_server_conn_notify_cb() ]
...
1259     ucs_trace("ep %p flags 0x%x: notify callback invoked, status %s", ucp_ep,
1260               ucp_ep->flags, ucs_status_string(status));
1261
==>  1262     UCP_EP_CM_CALLBACK_ENTER(ucp_ep, uct_cm_ep, return);
1263
1264     if (status == UCS_OK) {
1265 …
```
=> UCT/CM/GTEST: Fix error flow for EP created upon receiving conn request

contrib/test_jenkins.sh, examples/Makefile.am, examples/hello_world_util.h, examples/ucp_client_server.c, examples/ucp_hello_world.c, examples/uct_hello_world.c
Add length/mem_type for UCP client-server example.
To have a tiny pre-test with different memory types and different message sizes for UCP client-server.
Use the same infrastructure as `ucp_hello_world` and `uct_hello_world` already use and update TAG/STREAM/AM to use it.
=> EXAMPLES/UCP: Add length/mem_type for UCP client server example

README
Describe known glibc issue in UCX README
replaces #6526 
To warn users about the potential UCX hang with certain glibc versions
=> DOC/README: Describe glibc bug in known issues

src/ucp/core/ucp_am.c, test/gtest/ucp/test_ucp_am.cc
Forced eager protocol for the old AM API due to that it does not support RNDV.
Fixes #6628
=> UCP/AM: force eager protocol for old AM API

src/uct/ib/rdmacm/rdmacm_cm_ep.c, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
- port all sockaddr tests to new API
- add basic sockaddr test with legacy API
test coverage
=> GTEST/UCT/SOCKADDR: port sockaddr tests to new API

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c
- there was incorrect sequence in resetting DCI and
post next opereation: in some cases DCI is resetted just after operation is
posted
- fix: reset DCI prior to post operation from arbiter
=> DC/MLX5: reset DCI prior to next operation

src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/accel/ud_mlx5.h, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c
Fix leak of domain resources destroying them in QP cleanup as it's done in UCT/IB/RC
Fixes #6656
The problem was a leak of domain resources which weren't destroyed after mpool initialization failed in UD_MLX5's `uct_iface_open()`, because `uct_ib_mlx5_iface_create_qp()` allocates the domain resources.
1. Define new operation in UD - `destroy_qp()` and implement it in MLX5 and Verbs.
2. Move doing `uct_ib_mlx5_txwq_init()` from MLX5 iface inti function to `uct_ud_mlx5_iface_create_qp()` - we do the same for RC QP.
3. Do `uct_ib_mlx5_qp_mmio_cleanup()` in `uct_ud_mlx5_iface_destroy_qp()` - we do the same for RC QP.
4. Move `uct_ud_iface_remove_async_handlers()` from MLX5 and Verbs to UD common iface clenup function.
=> UCT/IB/UD: Fix leak of domain resources destroying them in QP cleanup

src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/perftest.c, test/gtest/ucp/test_ucp_perf.cc
Add error handling support to UCX perftest
To measure performance using eps created with error handling support (which simulates various client-server applications).
Not all the transports support error handling, which noticeable accepts performance.
For instance:
No error handling support
```
$UCX_LOG_LEVEL=info ./src/tools/perf/ucx_perftest  -t tag_lat  localhost
[1617891327.753542] [jazz18:56657:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(posix/memory knem/memory rc_mlx5/mlx5_0:1);
[1617891327.753544] [jazz18:56685:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(posix/memory knem/memory rc_mlx5/mlx5_0:1);
```
With error handling support:
```
[1617891296.290892] [jazz18:56608:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(rc_mlx5/mlx5_0:1 rc_mlx5/mlx5_4:1); …
```
=> TOOLS/PERF: Add error handling option to perftest

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.inl, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_wireup.cc
To calculate the expected bandwidth of rendezvous protocols considering both local **and remote** system topology
- Pass system device id in UCP address
- Save remote system device id in endpoint configuration key
=> UCP/ADDRESS: Pass system device id during wireup

src/ucp/core/ucp_ep.c, src/ucp/wireup/wireup_cm.c
Fix checking whether EP needs to do CM disconnect or not.
The bug was introduced in #6460 PR which sets `UCP_EP_FLAG_FAILED` in cleanup lanes, but `ucp_ep_cm_disconnect_cm_lane()` depends on `UCP_EP_FLAG_FAILED` flag (i.e. it doesn't show whether CM disconnect was already done or not).
Fixes:
```
#0  0x00007f9058ca923a in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f8fe4cc7606 in ucs_debugger_attach ()
at /src/ucs/debug/debug.c:813
#2  0x00007f8fe4cca743 in ucs_error_freeze (
message=0x7fff525173c0 "Assertion `!(ucp_ep->flags & UCP_EP_FLAG_FAILED)' failed")
at /src/ucs/debug/debug.c:908
#3  ucs_handle_error (message=message@entry=0x7fff525173c0 "Assertion `!(ucp_ep->flags & UCP_EP_FLAG_FAILED)' failed")
at /src/ucs/debug/debug.c:1078
#4  0x00007f8fe4cc7131 in …
```
=> UCP/CORE: Fix checking whether EP needs to do CM disconnect or not

buildlib/az-distro-release.yml
=> AZP/RELEASE: Remove strict libibverbs dependency

NEWS, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListener.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListenerParams.java, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/listener.cc, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
Port #6273 to v.1.10
A critical bug that doesn't allow to establish multiple client- server connection with connectionHanlders.
=> JUCX: Do not delete reference to listener connHandler (v.1.10.x)

src/ucs/vfs/base/vfs_obj.c
Enabled grouping files related to an object into sub-directories.
To improve usability by grouping features describing an object into directories, e.g. am and put thresholds of UCT iface:
=> UCS/VFS: Group files to sub-directories.

src/ucp/core/ucp_am.c, src/ucp/core/ucp_am.h, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv.h, src/ucp/tag/offload.c, src/ucp/tag/probe.c, src/ucp/tag/tag_rndv.c, src/ucp/tag/tag_rndv.h
Restore wire compatibility for RNDV/RTS header.
To support smooth upgrade from the old UCX where no AM RNDV was introduced to the new UCX.
1. Change the order of RTS header and TAG/AM part of TAG/AM RTS header.
2. Replace `ucs_derived_of` by `ucs_container_of` to convert the common RTS header to TAG or AM ones.
3. Code style fixes.
=> UCP/CORE/RNDV: Restore wire compatibility for RNDV/RTS header

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc
1. Improve logging and fix uninitialized status in requests.
2. Fix uninitialized status in requests.
1. For better debugging experience.
2. To print the correct value of reques'ts `status`.
1. Added `LOG`/`UCX_CONN_LOG` to print more information.
2. Initialize request's `status` in `UcxContext::request_reset()` and move setting request's `status` to common code in `UcxConnection::common_request_callback()`.
=> TEST/IO_DEMO: Improve logging and fix uninitialized status in requests

test/gtest/uct/ib/test_sockaddr.cc
Handle `UCS_ERR_CONNECTION_RESET` status to mark a server as unavailable
Fixes #6701
`UCS_ERR_CONNECTION_RESET` can be passed to `client_connect_cb()` by a TCP_SOCKCM during handling socket data
1. Add check for `status == UCS_ERR_CONNECTION_RESET`.
2. If it is true, mark a server as `TEST_STATE_CLIENT_GOT_SERVER_UNAVAILABLE`.
=> GTEST/UCT: Handle 'Connection reset' status to mark server as unavailable

test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
fix mem leak of EP user data introduced in https://github.com/openucx/ucx/pull/6617
fixes https://github.com/openucx/ucx/issues/6683
store all the allocated data to the separate storage, clean up and/or check in the end of test
=> GTEST/UCT/SOCKADDR: fix mem leak of EP user data

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/rma/amo_sw.c, src/ucp/rma/rma.inl, src/ucp/rma/rma_send.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_peer_failure.cc
1. If lanes were not initialized use `ucp_ep_delete()` to destroy UCP EP
2. Always allow RMA/AMO emulation over AM.
1. It fixes the following bugs:
```
[ RUN      ] ud/test_ucp_sockaddr_protocols.stream_bcopy_4k_exp/0 <ud_v,cuda_copy,rocm_copy/mt>
[New Thread 0x7fffee584700 (LWP 157652)]
[     INFO ] server listening on 2.1.3.25:34962
[1618929869.840880] [jazz25:157464:0]          select.c:509  UCX  ERROR   no remote registered memory access transport to jazz25:157464: Unsupported operation
[jazz25:157464:0:157464]    ucp_ep.inl:23   Assertion `ep->cfg_index != (255)' failed
/labhome/dmitrygla/work_auto/ucx/src/ucp/core/ucp_ep.inl: [ ucp_ep_config() ]
...
20
21 static inline ucp_ep_config_t *ucp_ep_config(ucp_ep_h ep)
22 {
==>    23     ucs_assert(ep->cfg_index != …
```
=> UCP/WIREUP: Allow RMA/AMO emulation always over AM + fix case when init_lanes failed r EP for sending WIREUP/EP_REMOVED

src/ucp/core/ucp_worker.c, src/ucs/config/parser.c, src/ucs/config/parser.h, test/gtest/ucs/test_config.cc
Print used env variables to the info log level
Eliminates the need to ask customers what configuration they used to reproduce/get the fault
```
UCX_BCOPY_THRESH=2 UCX_TCP_SENDV_THRESH=4 UCX_ZCOPY_THRESH=5 UCX_WARN_UNUSED_ENV_VARS=n UCX_RNDV_THRESH=22 UCX_TM_THRESH=1 UCX_MM=2 UCX_LOG_LEVEL=info UCX_RNDV_SCHEME=auto UCX_TM_THRESH=1  UCX_NNN=1 M_UCX_NNN=1 M_UCX_RNDV_THRESH=1 ./src/tools/info/ucx_info -e -ut
[1617980132.433570] [jazz29:22670:0]          parser.c:1910 UCX  INFO  UCX_* env variables: UCX_ZCOPY_THRESH=5, UCX_RNDV_SCHEME=auto, UCX_WARN_UNUSED_ENV_VARS=n, UCX_RNDV_THRESH=22, UCX_BCOPY_THRESH=2, UCX_TCP_SENDV_THRESH=4, UCX_LOG_LEVEL=info, UCX_TM_THRESH=1
```
=> UCS: Print all used env vars with info level

src/ucs/Makefile.am, src/ucs/type/float8.h, test/gtest/ucs/test_type.cc
Introduce double-to-char compressible types, which allow lossy compression of an 8-byte double to a single-byte char.
Each type is defined by a `(min, max)` supported ranged - compressions of an out-of-bounds number result in capping.
In order to transmit less data when exchanging bandwidth information
Parse double value according to the IEEE754 standard. Assume it is non-negative, use 5 most significant bits of the exponent and 3 bits of the mantissa.
=> UCS/TYPE: Support compression of double to char

src/ucp/rndv/rndv.c
Fix segfault due to invalid rkey in D2H rndv path
put pipeline is used for D2H transfers since send memtype is on device.
Current code skips rkey creation even when the md has NEED_RKEY set.
This flag was incorrectly changed from 1 to 0 in  fb6401c8c7
Suggestions to make the change more self descriptive welcome.
```
(gdb) bt
#0  0x00007fad38e80912 in __libc_pause () at ../sysdeps/unix/sysv/linux/pause.c:30
#1  0x00007fa51c9eab55 in ucs_debug_freeze () at /home/souchakr/WORKSPACE/ucx/contrib/../src/ucs/debug/debug.c:820
#2  0x00007fa51c9edef8 in ucs_error_freeze (message=0x7fa51ca1420e "address not mapped to object") at /home/souchakr/WORKSPACE/ucx/contrib/../src/ucs/debug/debug.c:915
#3  ucs_handle_error (message=message@entry=0x7fa51ca1420e "address not mapped to object") at …
```
=> UCP/RNDV: Ensure rkey is updated for put pipeline

test/apps/iodemo/io_demo.cc
clean double "-q" command options for io_demo command
unify option declaration
=> test/io_demo: remove redundant cmd options declaration

src/uct/ib/mlx5/dv/ib_mlx5_ifc.h, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/rc/accel/rc_mlx5.inl
Use first fragment indication bit in CQE->byte_count, if available
Performance optimization for single fragment messages (i.e. small and latency-critical ones).
Can just check certain bit instead of hash lookup for distinguishing single fragment messages and fragments of big messages
Check 29-th bit in cqe->byte_count. No other check is required, because when first bit indication is not supported this bit is always zero (it is part of number of strides mask and we always have just 1 stride reported by cqe)
=> UCT/HWTM: First fragment bit support for MP XRQ

src/ucp/proto/proto_am.inl
set correct req->send.lane in stream/short progress
adding to pending should have valid value
ported from https://github.com/yosefe/ucx/pull/23
=> UCP/STREAM: set correct req->send.lane in stream/short progress

src/uct/sm/scopy/knem/knem_md.c
Updated knem rcache name.
To make it align with other rcache names which don't use spaces.
This changes also affects directory name in VFS.
Before:
After:
=> UCT/SM: Updated knem rcache name.

src/ucs/memory/rcache.c, src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h
Added directory to VFS tree representing UCS rcache object.
Added number of regions of UCS rcache to VFS structure.
The changes help to perform runtime analysis of UCX-based applications.
=> UCS/MEMORY: Added VFS nodes representing UCS rcache.

src/ucp/core/ucp_worker.c, src/ucp/wireup/wireup.c
complete AUX EP pending requests on err flow
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210419_211836_76084_7261_jazz05.swx.labs.mlnx/iodemo_logs/1618857746-437203640/iodemo_jazz07_client_06.log
```
[jazz07:151650:0:151650]      ucp_ep.c:869  Bug: pending request 0x3963238 (ucp_wireup_ep_progress_pending) on ep (nil) should have been flushed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210419_211836_76084_7261_jazz05.swx.labs.mlnx/installs/PJNZ/tests/io_demo/ucx.git/src/ucp/core/ucp_ep.c: [ ucp_destroyed_ep_pending_purge() ]
...
865 
866 void ucp_destroyed_ep_pending_purge(uct_pending_req_t *self, void *arg)
867 {
==>   868     ucs_bug("pending request %p (%s) on ep %p should have been flushed",
869             self, ucs_debug_get_symbol_name(self->func), arg); …
```
=> UCP/WIREUP/EP: complete AUX EP pending requests on err flow

src/uct/Makefile.am, src/uct/base/uct_iface.h, src/uct/base/uct_iface_vfs.c, src/uct/base/uct_md.c
Added iface capabilities to VFS structure.
Added iface limitations for put/get/am operations.
This is a part of instrumentation and monitoring feature. The feature allows to analyze UCX-based applications.
Please find a part of VFS structure on the attached screenshot. The part shows files with capabilities for a couple of UCT interfaces.
=> UCT/BASE: Added iface capabilities to VFS structure.

NEWS, contrib/test_jenkins.sh, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_md.c
Configurable loopback address support
To fix #6695 in 1.10 without porting #6704
=> UCT/TCP: add enable loopback flag. [v1.10]

src/ucs/Makefile.am, src/ucs/type/serialize.h, src/uct/ib/base/ib_iface.c, test/gtest/ucs/test_type.cc
Simplify the packing/unpacking process. To be used for packing/unpacking UCP remote keys.
=> Add common serialize macros and use them for IB address packing

src/ucs/type/float8.h
- Fix assertion _min / _max usage e.g `UCS_FP8_DECLARE_TYPE(RKEY_BANDWIDTH, 512 * UCS_MBYTE, 4 * UCS_TBYTE)`
- Remove whitespaces
=> UCS/FLOAT8: Add () around macro parameters

src/ucs/sys/topo.c, src/ucs/sys/topo.h, test/gtest/ucs/test_topo.cc
- Return total number of system devices, for allocating temporary distance arrays
- Convert distance to human string for debug purpose
- Common definition of "default" distance: zero latency, infinite bandwidth
=> UCS/TOPO: Add methods for number of devices and distance string

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, test/gtest/ucp/test_ucp_sockaddr.cc
Get rid of TMP EP.
We don't need a TMP EP on a client anymore. So, the CM WIREUP code could be simplified.
1. Remove all code related to TMP EP.
2. Store initial configuration in main UCP EPs.
=> UCP/CORE/WIREUP/GTEST: Get rid of TMP EP

buildlib/azure-pipelines-pr.yml
Avoid pipeline build for documentation files to speed up merge process
=> AZP/PR: Add exclude-build for non-doxygen documentation files

src/uct/api/v2/uct_v2.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/base/ud_iface.c, src/uct/ib/ud/base/ud_iface.h, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/rocm/copy/rocm_copy_iface.c, src/uct/rocm/gdr/rocm_gdr_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c, src/uct/sm/base/sm_iface.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/base/ugni_iface.c, test/gtest/uct/v2/test_uct_query.cc
Provide operation-specific bandwidth estimates when `uct_iface_estimate_perf` is called with CUDA or GDRCopy interface.
The bandwidth varies significantly according to the operation, therefore having a more precise estimate rather than a generic value is desirable.
Add `internal_ops` in `uct_base_iface_t`, which allows having a separate implementation of `iface_estimate_perf` for each interface type - and provides support for adding more such internal per-interface ops in the future.
=> UCT/IFACE: Improve performance query for CUDA / GDRCopy interfaces

src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/sm/base/sm_iface.c, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_sockcm_ep.c, test/gtest/ucs/test_sock.cc, test/gtest/uct/tcp/test_tcp.cc
Fix reachability of loopback ifaces in TCP transport, when those ifaces are running on different nodes.
Fixes #6695 
TCP ifaces on different nodes and using loopback interfaces (i.e. "127.0.0.1") shouldn't be reachable.
1. Introduce common local address structure and add `get` and `is_reachable` functions to fill address and check reachability (the implementation is copied from SM).
2. Add `ucs_sockaddr_is_inaddr_loopback()` function to check whether the address is loopback or not.
3. Use common local address functions and structures for SM device addresses.
4. Remove `in_port_t` which was used as a TCP fiace address, since it is not needed and it is already part of the device address (`struct sockaddr_in`).
5. Use common local address functions and structures for TCP iface and EP …
=> UCT/TCP/BASE/GTEST: Fix reachability of loopback ifaces

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucs/Makefile.am, src/ucs/type/param.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/ib/base/ib_iface.c, src/uct/ib/rc/accel/rc_mlx5_iface.c
Add a generic macro, which returns a param value from a params struct, after checking a corresponding condition flag in its `field_mask` - otherwise it returns a default value.
Avoid code repetition & duplication - have this logic in one single place instead.
=> UCS/TYPE: Add a generic UCS_PARAM_VALUE macro

NEWS, src/ucp/core/ucp_am.c
Maximal size for eager short with reply protocol should subtract `sizeof(ucs_ptr_map_key_t)`
Thes header of reply protocol  is `ucp_am_hdr_t` + `ucs_ptr_map_key_t`.
=> UCP/AM: Adjust max_short for UCP_AM_SEND_REPLY - v1.10.x

src/ucp/core/ucp_am.c, src/ucp/core/ucp_request.h, test/gtest/ucp/test_ucp_am.cc
Adds check when the user returns the wrong `UCS_OK` instead of `UCS_INPROGRESS` from AM callback and tries to obtain the data by `ucp_am_recv_data_nbx()`.
=> UCP/AM: added checking for ucp_am_recv_data_nbx() uses the correct data descriptor

test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Use `requests_wait()` where it is possible
To reduce code/functionality duplication
1. Reimplement `requests_wait()` to use `test_ucp_wireup::waitall()` implementation - it is simpler and retrieves elements from `std::vector`.
2. Use `requests_wait()` instead of `waitall`.
=> GTEST/UCP: Use requests_wait where it is possible

src/ucp/wireup/wireup.c, test/gtest/ucp/test_ucp_peer_failure.cc
- Test TCP error handling with smaller segment size and multi-frag protocol
- Fix remote-id resolve on a failed ep (should be skipped)
- Use smaller TCP segment size in test, to uncover issue with unexpected receive descriptors leak
- Use active message instead of tag in test, to fix the leak
- Fix active message sending on failed ep: do not try to resolve remote id on a failed ep
=> Fix active-message-with-reply on failed ep and test it

src/ucp/wireup/wireup.c
Fix leak of UCP request for sending WIREUP/REQ.
Fixes #6746
This PR fixes the leak of UCP request allocated from a heap directly. This UCP request was needed to send WIRUEP/REQ message to a peer, but it happens that a peer is already connected, i.e. REMOTE_CONNECTED flag is set on a EP.
Use `out_free_req` instead of `out` in order to free allocated request and buffer for sending WIREUP/REQ message.
=> UCP/WIREUP: Fix leak of UCP request for sending WIREUP/REQ

.github/ISSUE_TEMPLATE/bug_report.md
Adding information how to identify Bluefield DOCA setups
It is not obvious how to identify DOCA setup
It is based on info from DOCA devs
=> GITHUB: Updating issue template

src/ucp/api/ucp.h, src/ucp/core/ucp_ep.c, test/gtest/Makefile.am, test/gtest/ucp/test_ucp_ep.cc
Support querying performance of an endpoint, by message length and operation type.
At the first stage, a constant bandwidth is returned, regardless of the given params.
In the future, more precise bandwidth calculation will be implemented.
Allow users to retrieve bandwidth information per-endpoint.
=> UCP/API: Support endpoint performance evaluation

src/ucp/wireup/select.c, src/ucp/wireup/wireup_cm.c, src/uct/tcp/tcp_sockcm.c, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc
Retry getting CM initial config if it doesn't fit CM private data.
Fixes:
```
$ UCX_TLS=ud,rc,sm gdb --args ./src/tools/info/.libs/ucx_info -ep -u tme -n 128 -A 1.1.3.28
...
[1617052881.795899] [jazz28:155982:async]       wireup_cm.c:427  UCX  ERROR CM private data buffer is too small to pack UCP endpoint info, ep 0x7fffece17000/0x7fffece17078 service data 11, address length 64, cm 0xb955f0 max_conn_priv 54
[1617052881.795937] [jazz28:155982:async]      ucp_worker.c:560  UCX  ERROR ep 0x7fffece17000: error 'Provided buffer is too small' on CM lane will not be handled since no error callback is installed
<Failed to flush UCP endpoint>
```
i.e. address of a CM initial configuration doesn't fit CM private data.
If the initial config doesn't fit CM private data, retry getting CM initial …
=> UCP/WIREUP: Retry getting CM initial config if it doesn't fit CM private data

src/uct/base/uct_iface.h, src/uct/base/uct_iface_vfs.c, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/ud/accel/ud_mlx5.c, src/uct/ib/ud/verbs/ud_verbs.c, src/uct/sm/base/sm_iface.c, src/uct/sm/base/sm_iface.h, src/uct/sm/mm/base/mm_iface.c, src/uct/sm/scopy/base/scopy_iface.c, src/uct/sm/scopy/base/scopy_iface.h, src/uct/sm/scopy/cma/cma_iface.c, src/uct/sm/scopy/knem/knem_iface.c
- Allow transport interfaces to extend VFS-refresh function and add their own information
- scopy transports should also use internal ops to define "ep_tx" method
=> UCT/BASE/SM: Add iface internal operation to refresh VFS

src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h
remove EPs lock
UCP does not call `uct_ep_create` from async thread any more due to improvements in UCT CM API and related UCP wireup impl
=> UCT/RC/IFACE: remove EPs lock

src/ucp/core/ucp_am.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.inl, src/ucp/rma/amo_sw.c, src/ucp/rma/get_am.c, src/ucp/rma/rma_send.c, src/ucp/rma/rma_sw.c, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/tag_rndv.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_sockaddr.cc
Don't release ID for receive operations.
To fix the crash after "Retry count exceeded":
```
[1620863140.234291] [jazz05:77128:0]     ib_mlx5_log.c:147  UCX  DIAG  Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
[1620863140.234291] [jazz05:77128:0]     ib_mlx5_log.c:147  UCX  DIAG  RC QP 0x327a1 wqe[921]: SEND s-- [inl len 18] [va 0x7fb5feb1c564 len 8238 lkey 0x5fb7c9]
[jazz05:77128:0:77128] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210513_003809_71416_11691_jazz05.swx.labs.mlnx/installs/qPA2/tests/io_demo/ucx.git/src/ucp/core/ucp_request.inl: [ ucp_request_id_release() ]
...
883     ucp_ep_h ep = req->send.ep;
884     ucs_status_t UCS_V_UNUSED status;
885
==>   886 …
```
=> UCP/CORE: Don't release ID for receive operations

src/uct/tcp/tcp_sockcm_ep.c
add an assert that write event cannot be skipped on disconnecting state
https://github.com/openucx/ucx/pull/6668#discussion_r624697618
=> UCT/TCP/CM: add an assert

src/ucp/rndv/rndv.c
Remove fatal error in AM zcopy completion in case of error.
To fix:
```
[jazz14:75380:0:75380]        rndv.c:1608 Fatal: error handling is unsupported with rendezvous protocol
/labhome/dmitrygla/work_auto/ucx/src/ucp/rndv/rndv.c: [ ucp_rndv_am_zcopy_completion() ]
...
1605     if (sreq->send.state.dt.offset == sreq->send.length) {
1606         ucp_rndv_am_zcopy_send_req_complete(sreq, status);
1607     } else if (status != UCS_OK) {
==>  1608         ucs_fatal("error handling is unsupported with rendezvous protocol");
1609     }
1610 }
1611
==== backtrace (tid:  75380) ====
0 0x00000000000b7de9 ucp_rndv_am_zcopy_completion()  /labhome/dmitrygla/work_auto/ucx/src/ucp/rndv/rndv.c:1608
1 0x000000000003446f uct_invoke_completion()  /labhome/dmitrygla/work_auto/ucx/src/uct/base/uct_iface.h:791 …
```
=> UCP/RNDV: Remove fatal error in AM zcopy completion in case of error

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
Fix doing KA multiple times for the same EP in a single round.
before (difference 0.002-0.003 seconds between KA messages until KA message is not done for all 128 EPs):
```
[1620746626.363275] [jazz17:141234:0]          ucp_ep.c:2654 UCX  DIAG  ep 0x7f114bcdd0f0: sending KA: src-7 dst-139: 88
...
[1620746626.365858] [jazz17:141234:0]          ucp_ep.c:2654 UCX  DIAG  ep 0x7f114bcdd0f0: sending KA: src-7 dst-139: 88
...
```
after (every 60 seconds - as expected):
```
[1620844406.049948] [jazz03:161405:0]          ucp_ep.c:2654 UCX  DIAG  ep 0x7f65cac7e438: sending KA: src-21 dst-165: 88
...
[1620844466.052248] [jazz03:161405:0]          ucp_ep.c:2654 UCX  DIAG  ep 0x7f65cac7e438: sending KA: src-21 dst-165: 88
...
```
Save first EP iterator that was set when the round completed and use it …
=> UCP/CORE: Fix doing KA multiple times for the same EP in a single round

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h
Provide correct number of DC CQEs to CQ creation (and tx ops) routines, taking into account number of DCI pools.
Fixes #6579
=> UCT/DC: Fix number of CQEs for DCI pools

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.inl
Always set completion callback for correct send state ff.
Fixing:
```
[jazz14:24302:0:24302]  ucp_worker.c:2346 Assertion `req->send.discard_uct_ep.cb_id == UCS_CALLBACKQ_ID_NULL' failed
/labhome/dmitrygla/work_auto/ucx/src/ucp/core/ucp_worker.c: [ ucp_worker_discard_uct_ep_progress_register() ]
...
2343 {
2344     ucp_worker_h worker = req->send.ep->worker;
2345
==>  2346     ucs_assert_always(req->send.discard_uct_ep.cb_id == UCS_CALLBACKQ_ID_NULL);
2347     uct_worker_progress_register_safe(worker->uct, func, req,
2348                                       UCS_CALLBACKQ_FLAG_ONESHOT,
2349                                       &req->send.discard_uct_ep.cb_id);
==== backtrace (tid:  24302) ====
0 0x000000000005d3ee ucp_worker_discard_uct_ep_progress_register() …
```
=> UCP/CORE: Always set completion callback for correct send state ff

src/tools/perf/lib/libperf.c
The wrong field was used to initialize ucp_context.
Ensure multiple workers to share ucp_context safely.
=> UCP/PERFTEST: Fix wrong parameter

src/uct/base/uct_cm.h, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/ib/rdmacm/rdmacm_listener.c, src/uct/tcp/tcp_sockcm_ep.c, test/gtest/uct/ib/test_sockaddr.cc
improve server side error handling in case if client EP is destroyed before server does accept/reject 
cherry-picked form https://github.com/openucx/ucx/pull/6688 + rdmacm_cm fixes
=> UCT/TCP/RDMACM: early client closure

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c
Print UCP memory type EPs information when printing UCP worker information
The PR fixes 2nd item of https://github.com/openucx/ucx/pull/6271#issuecomment-773386235
```
$ ./install/bin/ucx_info -w -u t
#
#
#
#
#
#
#
#
#
#
#
#
#
#
```
1. Go through all memory types and use `ucp_ep_print_info()` function to print endpoint information.
2. Update `ucp_ep_print_info()` function to check whether some endpoint is "memtype" one or not:
if it is "memtype" endpoint, print memory type description and name and don't print peer name
=> UCP/CORE: Print memory type EPs info

test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Fix unknown conn_id happened when only one peer is fully connected.
It happens that peers are connected to do UCP TAG operations beetween each other, but only the client received a connection ID from a peer through UCP Stream. So the client started sending IO messages (11 reads and 5 writes), but the server isn't received a connection ID from a peer and isn't ready to receive the data - it just discards the 16 received messages.
client:
```
[1621265591.444772] [UCX-connection #4 0.0.0.0:0] created new connection 0x2081f10 total: 4
[1621265591.444781] [UCX-connection #4 2.1.3.20:20002] Connecting to 2.1.3.20:20002
[1621265591.444800] [UCX-connection #4 2.1.3.20:20002] created endpoint 0x7f7e48565168, connection id 4
...<after 5 minutes>...
[1621265896.249686] [DEMO] timeout waiting for 16 …
```
=> APPS/IODEMO: Fix unknown conn_id happened when only one peer is fully connected

src/uct/base/uct_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c
Fixed crash while refreshing UCT iface VFS sub-tree. 
The issue was detected on `ucp_hello_world` application. `iface_vfs_refresh` was not initialized for TCP  UCT iface. This caused a crash in `uct_iface_vfs_refresh` function
```C
ucs_debug("failed to query iface attributes");
}
iface->internal_ops->iface_vfs_refresh(&iface->super);
}
```
=> UCT/BASE: Fixed crash on UCT iface vfs refresh.

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h
Added name to UCP endpoint parameters to identify the endpoint.
Introduced new API query method to retrieve endpoint attributes.
Added name to UCP endpoint attributes to get the actual endpoint name.
The parameter is required for more convenient run time analysis of UCX-based application. E.g. ucx_vfs tool.
=> UCP/API: Added name to ep parameters.

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c
test all wireup lanes to define if the EP local connected in case of
presence CM lane
```
#0  0x00007eff9d429207 in raise () from /lib64/libc.so.6
#1  0x00007eff9d42a8f8 in abort () from /lib64/libc.so.6
#2  0x00007eff9f2b31d0 in ucs_fatal_error_message (file=0x7eff9f031186 "wireup/wireup_ep.c", line=610,
function=0x7eff9f031d10 <__FUNCTION__.15913> "ucp_wireup_ep_mark_ready",
message_buf=0x7ffe512a8460 "Assertion `wireup_ep->flags & UCP_WIREUP_EP_FLAG_LOCAL_CONNECTED' failed")
at debug/assert.c:38
#3  0x00007eff9f2b334b in ucs_fatal_error_format (file=0x7eff9f031186 "wireup/wireup_ep.c", line=610,
function=0x7eff9f031d10 <__FUNCTION__.15913> "ucp_wireup_ep_mark_ready",
format=0x7eff9f030e85 "Assertion `%s' failed") at debug/assert.c:53
#4  0x00007eff9efde108 in ucp_wireup_ep_mark_ready …
```
=> UCP/WORKER: fix error handling

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c
Block worker async before doing KA for EPs.
To prevent touching lanes which haven't initialized in `ucp_wireup_init_lanes()` yet.
- async thread
```
#0  ucp_wireup_init_lanes (ep=0x7fffe1f3a000, ep_init_flags=16, local_tl_bitmap=0x7ffff77f49b0 <ucp_tl_bitmap_max>, remote_address=0x7fffef19c520, addr_indices=0x7f
ffef19c420) at wireup/wireup.c:1352
#1  0x00007ffff77d2e37 in ucp_wireup_init_lanes_by_request (worker=0x6b7010, ep=0x7fffe1f3a000, ep_init_flags=16, remote_address=0x7fffef19c520, addr_indices=0x7fff
ef19c420) at wireup/wireup.c:434
#2  0x00007ffff77d356e in ucp_wireup_process_request (worker=0x6b7010, ep=0x7fffe1f3a000, msg=0x7fffeb659fb0, remote_address=0x7fffef19c520) at wireup/wireup.c:561
#3  0x00007ffff77d4456 in ucp_wireup_msg_handler (arg=0x6b7010, data=0x7fffeb659fb0, …
```
=> UCP/CORE: Block worker async before doing KA for EPs

src/ucp/api/ucp.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_worker.c, test/gtest/Makefile.am, test/gtest/ucp/test_ucp_request.cc
ucp_request_queryfunctionality. The ability to query request objects for components, like memory type, status, and debug information about protocols and transport was used to complete it.
Follow up based on community discussion of #6487
=> UCP/API: ucp_request_query functionality.

src/ucp/core/ucp_ep.c
Added name to VFS node representing UCP endpoint.
The name is available only if debug data is enabled.
=> UCP/CORE: UCP ep name to VFS node.

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
Fixed doing KA multiple times for the same EP.
To not do KA endlessly for the same EP due to unsigned integer overflow:
```
...
[1621367413.983911] [jazz01:180803:0]          wireup.c:777  UCX  DIAG  ep 0x7f358569c780: received KA: src-123 dst-35
[1621367413.984180] [jazz01:180803:0]          wireup.c:777  UCX  DIAG  ep 0x7f358569c780: received KA: src-123 dst-35
[1621367413.984448] [jazz01:180803:0]          wireup.c:777  UCX  DIAG  ep 0x7f358569c780: received KA: src-123 dst-35
[1621367413.984727] [jazz01:180803:0]          wireup.c:777  UCX  DIAG  ep 0x7f358569c780: received KA: src-123 dst-35
[1621367413.985005] [jazz01:180803:0]          wireup.c:777  UCX  DIAG  ep 0x7f358569c780: received KA: src-123 dst-35
[1621367413.985272] [jazz01:180803:0]          wireup.c:777  UCX  DIAG  ep …
```
=> UCP/CORE: Fixed doing KA multiple times for the same EP

src/ucp/api/ucp_def.h, src/ucs/sys/compiler_def.h
This part of documentation improvement efforts.
This references break clean doxygen generation.
Manual debug
=> UCP/UCS: Fixing broken doxygen references

src/uct/api/uct.h, src/uct/api/v2/uct_v2.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/cuda/cuda_copy/cuda_copy_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_md.c, src/uct/cuda/gdr_copy/gdr_copy_md.c, src/uct/ib/base/ib_md.c, src/uct/rocm/copy/rocm_copy_md.c, src/uct/rocm/gdr/rocm_gdr_md.c, src/uct/rocm/ipc/rocm_ipc_md.c, src/uct/sm/mm/xpmem/mm_xpmem.c, src/uct/sm/scopy/cma/cma_md.c, src/uct/sm/scopy/knem/knem_md.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_md.c, src/uct/ugni/base/ugni_md.c
- added experimental API uct_md_mem_dereg_flags function to support flags in
memory de-registration
Why:
- needed to fix issue in error handling when connect-to-iface transport is used
How:
- in case if error happened delay user request completion till memory region is unregistered to provide RDMA operation failure or data consistency
Details:
The goal of this PR is to solve data corruption issue with rendezvous protocol during error flow: one side unexpectedly closes the connection (for example because keepalive detects temporary network error), while the other side can still do RDMA_READ invalid data from it.
The method to solve the problem is to destroy the related registration cache region after all other users of it (maybe other connections) finished using it and its refcount reached …
=> API/EXPERIMENTAL/MD: added flags-based mem_dereg

src/ucp/core/ucp_listener.c
do not set UCT backlog in case of auto UCP value
to avoid bogus DIAG messages from UCT:
```
jazz01: [1621413220.814319] [jazz01:178433:0]          uct_cm.c:259  UCX  DIAG  configure value 2147483647 is greater than the max_value 1024. using max_value
jazz01: [1621413220.814373] [jazz01:178433:0]          uct_cm.c:259  UCX  DIAG  configure value 2147483647 is greater than the max_value 15000. using max_value
```
=> UCP/LISTENER: do not set UCT backlog in case of auto

src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, test/gtest/ucs/test_vfs.cc
Added return status to `ucs_vfs_obj_add_dir` and `ucs_vfs_obj_add_ro_file`.
The methods return:
- `UCS_ERR_ALREADY_EXISTS` if directory or file with specified name already exists.
- `UCS_ERR_INVALID_PARAM`  if node for parent object does not exist.
- `UCS_ERR_NO_MEMORY` if cannot create a new node.
- `UCS_OK` if everything is ok.
To be able to handle duplicate names while creating new directories or files. E.g.:
```C
while (ucs_vfs_obj_add_dir(NULL, rcache, "ucs/rcache/%s_%zu", rcache->name, i) ==
UCS_ERR_ALREADY_EXISTS) {
++i;
}
```
=> UCS/VFS: Added return status to add file/directory methods.

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/stream/stream_recv.c, src/uct/tcp/tcp_ep.c, test/gtest/ucp/test_ucp_sockaddr.cc
- add ERROR_HANDLER_DELAY configuration
- add test_ucp_sockaddr.close_ep_force_before_err_cb
- related fixes in UCP and UCT
- updated version of  of https://github.com/openucx/ucx/pull/5931
to handle a case then err handling callback is scheduled on slow path progress but EP was closed by ucp_ep_close_nbx(force) earlier
=> UCP/CONTEXT: add ERROR_HANDLER_DELAY configuration

src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/ib/base/ib_md.c, test/gtest/uct/test_md.cc, test/gtest/uct/test_md.h
- added uct_md_mem_dereg_v2 implementation
- added support of memory invalidation into IB memory
domain
- improved UCT_MD_MEM_DEREG_CHECK_PARAMS macro
- added gtest for new API
=> UCT/MD: added md_dereg_v2 implementation

src/ucs/debug/debug.c, src/ucs/profile/profile.c, src/ucs/profile/profile_defs.h, src/ucs/profile/profile_on.h, src/ucs/sys/init.c, test/gtest/ucs/test_profile.cc
Extend ucs profiler API in order to support profiling external code.
These changes are needed to reuse ucs profiler in ucc.
- Move ucs global opts out from profiler, pass them as profiler init arguments and store on context.
- Add global profiler context as a parameter to API functions so that ucx and ucc will have different contexts and can be profiled independently.
- API macros will be duplicated in ucc e.g. UCC_PROFILE_FUNC
=> UCS/PROFILE: add support for external profiler context

test/apps/iodemo/ucx_wrapper.cc
do not handle io-msg before connection is established
io-msg tag-recv request can be completed before id-exchange
connection establishment stream-recv callback is invoked
handle the io-msg on next progress round
=> IODEMO: do not handle io-msg before connection is established

src/uct/ib/dc/dc_mlx5.c
Remove extra lookup EP from DCI.
Lookup EP is already done in `src/uct/ib/dc/dc_mlx5.c:1136`.
Remove invoking `ep = uct_dc_mlx5_ep_from_dci(iface, dci_index);`
=> UCT/IB/DC: Remove extra lookup EP from DCI

test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc
add lock on async to prevent race of accessing user data
bugfix
lock async thread until user data is added to `m_ep_client_data`
=> GTEST: fix race condition on client user data in test_uct_sockaddr

docs/.readthedoc.requirements.txt
It appears that by default openucx.readthedocs.org cached some very old version
requirements for our project. Locking-in special version requirements to a
specific version that we know works well. This shell solve rendering issues on
our documentation website.
=> DOCS: Locking-in explicit version requirements

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.inl
Use TIME_UNITS for KA interval configuration.
To align with other parameters and set `inf` - if user want to disable doing KA.
And it aligns with `uct_iface_params_t`'s `keepalive_interval` parameter
1. Replace `UCS_CONFIG_TYPE_TIME` by `UCS_CONFIG_TYPE_TIME_UNITS`.
2. Change type of interval from `double` to `ucs_time_t`
3. When checking whether KA is enabled or not, compare interval value with `UCS_TIME_INFINITY`.
=> UCP/CORE: Use TIME_UNITS for KA interval configuration

src/ucs/config/global_opts.c, src/ucs/config/types.h, src/ucs/debug/log.c, test/gtest/ucs/test_log.cc
Allow filtering log messages by file name to get a more precise log output.
Reminder: the default log level for release build is now "debug".
- Add glob-syntax config for log filter
- Use hash table to cache result of glob pattern matching
@Sergei-Lebedev  @dmitrygx
=> UCS/LOG: Add log filter by source file name.

src/ucs/arch/bitops.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_net.c, test/gtest/Makefile.am, test/gtest/ucs/test_bitops.cc, test/gtest/ucs/test_math.cc, test/gtest/uct/ib/test_ib.cc
This patch adds another criteria to IP/GID selection in the IB transport: a subnet mask. Similarly to IP networks, the subnet mask can be used to determine reachability (and thus routing) to a remote destination. This allows the user to set a mask (in bits, e.g. 24 out of 32 for IPv4) to tell UCX which remote IPs are reachable from this RoCE device/port. Before this patch - any remote address (of the same address family) was assumed to be reachable.
This PR solves two RoCE-related problems: the primary is using the IP address to choose the device/port, and the secondary is that I didn't find a clear way to disable RoCEv2 in favor of RoCEv1. More specifically about the first problem: I want to configure 2 RoCE ports to sit on different subnets, let's say 1.2.3.X and 1.2.4.X. With this …
=> UCT: Determine RoCE IP reachability using a subnet mask

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, test/gtest/uct/ib/test_dc.cc
Resend FC_HARD_REQ when FC window is 0.
Timeout waiting for replies was reproduced in IO-demo application under high load and doing port up/down for some port.
Doing port up/down affects DC Flow Control (FC) EP which detects error on DCI which was assigned to send data to a peer on failed nodes and on normal ones. So, FC_PURE_GRANT could be missed during recovering from error. And sender's EP is waiting for FC_PURE_GRANT endlessly. 
The fix is to do resend of FC_HARD_REQ packet every `fc_hard_req_timeout` (default=5) seconds from sender's side when window reaches `0` to receive FC_PURE_GRANT and unblock TX.
=> UCT/IB/DC: Resend FC_HARD_REQ when FC window is 0

src/uct/ib/mlx5/dv/ib_mlx5_ifc.h, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/ib/rdmacm/rdmacm_cm_ep.h, src/uct/ib/rdmacm/rdmacm_component.c
UCT/IB/RDMACM: Use DevX to allocate uniq QPN for rdma_cm/DC
Avoid allocating UD QP per connection in RDMACM CM
The PRM object RESERVED_QPN allows software to reserve a QPN value out of the FW’s managed QP number namespace range. This lets multiple software processes hold a unique QPN value instead of ‘inventing’ one which might collide with FW defined values.
The Obj ID is the start QPN from the allocated range.
=> UCT/IB/RDMACM: Use DevX to allocate uniq QPN for rdma_cm/DC

src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/rc/accel/rc_mlx5_devx.c
DCSP parameter for CREATE_DCT command is not set correctly for RoCE port. Need to use traffic_class only for IB, and dscp field for RoCE v2.
Set parameter according to link layer type
--
NOTE: This fix is needed for UCX v1.11
=> UCT/DC: Fix setting DSCP value for RoCE DCT

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_rkey.h, src/ucp/dt/datatype_iter.h, src/ucp/dt/dt.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_select.c, src/ucp/proto/proto_select.inl, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/rndv.c, src/ucs/memory/memory_type.c, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, test/gtest/ucp/test_ucp_mem_type.cc, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/ucs/test_memtype_cache.cc
Use base address and alloc length to register to avoid repeated registration belonging to the same allocations.
=> UCS/MEMORY: register whole cuda allocations

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/base/rc_iface.h
Refactoring of FC send operations.
Fixes #6904
1. Fixes comments from #6850.
2. Get rid of calling DCI put operations in case of failure.
3. Remove `uct_dc_mlx5_ep_fc_ctrl()` function and do sending of `FC_HARD_REQ`/`FC_PURE_GRANT` directly.
1. Add comment in DCI put, re-organize code in `uct_dc_mlx5_ep_fc_hard_req_send()` to make it more readable.
2. Don't do DCI put in case of failure or not expired timeout - just delete added EP from hash in case of failure from sending FC_HARD_REQ (it is better, since it handles not only `UCS_ERR_NO_RESOURCE` failures).
3. Introduce `uct_dc_mlx5_ep_fc_pure_grant_send()`/`uct_dc_mlx5_ep_fc_hard_req_send()` functions and use them directly instead of `uct_dc_mlx5_ep_fc_ctrl()` which is passed to RC iface ops.
=> UCT/IB/DC: Refactoring of FC send operations

configure.ac, ucx.spec.in
The first commit after creating a new branch https://github.com/openucx/ucx/tree/v1.11.x should be version bump
=> CONFIG/SPEC: Bump version to 1.12.0

src/uct/rocm/copy/rocm_copy_md.c
Fix error in ROCm memory deregistration
GPU memory is not locked during registration and hence should not be unlocked during deregistration
Fix memory leak of mem_hndl
=> UCT/ROCM/COPY: Fix device memory deregistration

src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_common.h, src/uct/ib/rc/accel/rc_mlx5_devx.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c
Set `log_ack_req_freq` to a default of 8 (or overridden by configuration) when invoking RTR2RTS in DevX.
Current value of 0 means an ack for every packet, which is undesirable.
=> UCT/IB/RC: Use a configurable ack frequency for requests in DevX

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
Ensure that KA isn't done several times for the same EP during the round.
1. To not do KA for the same EP several times in a keepalive interval.
2. To simplify check for KA that verifies if we ensure doing KA for the same EP once per round.
1. Use global `iter_begin` to stop doing KA for EPs when either `iter` == `iter_begin` or EP count reaches `KEEAPLIVE_NUM_EPS` value.
2. Remove `ka_count` from EP and introduce `ucs_time_t ka_last_round` field and check and set it every time when KA done for a EP.
=> UCP/CORE: Ensure that KA isn't done several times for the same EP during the round

src/ucp/core/ucp_worker.c
Re-initialize KA begin iterator correctly.
To fix possible doing KA for the same EP twice.
Check if removed EP from KA is the same as EP set in `iter_begin`. If it is true, move `iter_begin` to the next one.
=> UCP/CORE: Re-initialize KA begin iterator correctly

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_iface.h
Resend `FC_PURE_GRANT` in case of CQE failure.
To re-send `FC_PURE_GRANT` packets which are failed to be sent due to error detected to another peer.
1. Add `FC_PURE_GRANT` operation to TX outstanding.
2. Resend `FC_PURE_GRANT` in case of CQE status is `FLUSH_ERR` - this is done when purging TX QP outstanding operations during error handling.
=> UCT/IB/DC: Resend FC_PURE_GRANT in case of CQE failure

src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/vfs/fuse/vfs_fuse.c
Introduced global option to control FUSE thread affinity.
The affinity is disabled by default.
To improve responsiveness of data retrieving from VFS.
=> UCS/VFS: Set affinity for FUSE thread via option.

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.h
Remove unused DCI flags field.
It is not used anymore in DC code.
1. Remove the `flags` field in `uct_dc_dci_t` structure.
2. Remove all usages/occurrences of `uct_dc_dci_t::flags` field.
=> UCT/IB/DC: Remove unused DCI flags field

src/ucs/async/pipe.c, src/ucs/async/pipe.h, src/ucs/memory/rcache.c, src/ucs/memory/rcache.h, src/ucs/memory/rcache_int.h, src/uct/base/uct_md.c, src/uct/base/uct_md.h
Keep track of the total size of memory in the invalidate queue and the GC list of each rcache. When it is beyond threshold, trigger a cleanup.
Avoid having too much memory pending cleanup, as it might lead to memory leaks in some scenarios,
=> UCS/MEMORY: Cleanup rcache when invalidate queue and GC list are large

src/tools/info/proto_info.c, src/tools/info/ucx_info.c, src/tools/info/ucx_info.h
Introduce process placement to control type of selected devices.
The PR fixes 1st item of #6271 (comment)
Remote peer placement could be controlled by setting `-P` parameter `{ self, intra, inter }` to emulate a specific transport selection for their communications.
1. Introduce `-P` parameter.
2. Select devices based on `-D` and `-P` parameters.
=> TOOLS/INFO: Introduce process placement to control type of selected devices

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/rndv/rndv.c, src/ucp/wireup/select.c, src/uct/api/v2/uct_v2.h, src/uct/base/uct_md.h, src/uct/ib/base/ib_md.c, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h, test/gtest/uct/test_md.cc, test/gtest/uct/test_md.h
Invalidate remote key of UCP rendezvous requests when force-closeing an endpoint, to prevent the remote peer from accessing the memory. 
- Start invalidation process during ep requests purge and complete when mem region is not used any more
- After this point the memory will not be accessed remotely so it's OK to release the region
- Enable only for RDNV RTS requests and for one-sided transports such as DC
=> API/UCP/ERR-HANDLING: added memory invalidation on error

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5.inl, src/uct/ib/rc/accel/rc_mlx5_iface.c, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/test_peer_failure.h
Set flag `FAILED` for DCI when error is detected and verify that send/rma/amo/ep_check are not done when `FAILED` flag set on a DCI.
No operations should be scheduled on a failed DCI, because the operations will be failed immediately.
1. Set `UCT_DC_MLX5_DCI_FLAG_FAILED` flag when failure is detected on some DCI.
2. Remove `UCT_DC_MLX5_DCI_FLAG_FAILED` flag in `uct_dc_mlx5_iface_reset_dci()`.
3. Check that `UCT_DC_MLX5_DCI_FLAG_FAILED` isn't set when doing am/rma/amo/ep_check operations.
4. Introduce `uct_dc_mlx5_iface_inline_post()` to minimize code duplication for inline operations.
=> UCT/IB/RC/DC: Set FAILED flag for TXWQ when error is detected

src/uct/ib/dc/dc_mlx5_ep.h
Fix a hang in the following test, which is caused by adding a pending request to DCI-wait arbiter while it's actually waiting for RDMA_READ credits and not for a DCI.
```
mpirun -np 8 -x UCX_TLS=dc_x,self,sm -x UCX_IB_NUM_PATHS=4 -x UCX_MAX_EAGER_LANES=4 -x UCX_MAX_RNDV_LANES=4 --map-by node -x UCX_RC_MAX_GET_ZCOPY=8192 -x UCX_RC_TX_NUM_GET_BYTES=128K osu_alltoall
...
1                       2.57
2                       2.50
4                       2.44
8                       2.45
16                      2.44
32                      2.55
64                      2.80
128                     3.14
256                     4.37
512                     4.86
1024                    6.19
2048                    8.19
4096                   14.49
8192                   28.20
16384 …
```
=> UCT/DC/MLX5: Fix deadlock between DCI resources and RDMA_READ credits

src/ucp/wireup/select.c
Fix comment in CUP/WIREUP selection code.
1. To not repeat `"in case"`.
2. To remove extra `"in"`.
1. Remove `"in case"` at the begging of the comment and start the comment from the capital letter,
2. Remove `"in"`
=> UCP/WIREUP: Fix comment

src/ucp/wireup/wireup.c, src/ucs/config/parser.c, src/ucs/memory/rcache.c, src/uct/ib/mlx5/ib_mlx5_log.c
- there is set of coverity false positives
- suppressed
back port from https://github.com/openucx/ucx/pull/6945
(cherry picked from commit a1f0aa9ec6902a5ce38d8f023a3e626d89b80aaa)
=> COVERITY: suppressed false positives - v1.10

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv.h, src/ucp/tag/offload.c
Complete super request and release ID if sending RTR fails.
To complete user's request and fix request ID leak,
1. Rename `ucp_rndv_rts_handle_status_from_pending()` to `ucp_rndv_send_handle_status_from_pending()`.
2. Update `ucp_rndv_send_handle_status_from_pending()` to handle RTR send request by releasing RTR request and super RECV request.
3. Use `ucp_rndv_send_handle_status_from_pending()` for handling status of sending RTS/RTR packets.
=> UCP/RNDV/CORE: Complete super request and release ID if sending RTR fails

src/ucp/core/ucp_am.c, src/ucp/core/ucp_am.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/rndv/rndv.h, src/ucp/tag/tag_rndv.c, src/ucp/tag/tag_rndv.h
Purge super request for send request during fast-forward.
When doing send state fast-forward for normal send request, this send request can be RTR send request which has super request (i.e. receive request - exposed to a user). So, the receive request should be completed as well if the derived request fails, otherwise - it will be a leak.
Fixes `"No traffic"` and `"timeout waiting for <number> replies"` and `"Have read min:0"`/`"write min:0"`.
1. Expose `ucp_ep_req_purge()` for using in `ucp_request_send_state_ff()`.
2. Use `ucp_ep_req_purge()` to complete super request when doing fast-forward for the send request and `super_req` is not `NULL`.
=> UCP/CORE: Purge super request for send request during fast-forward

src/uct/ib/rc/base/rc_iface.c
Skip invoking AM handler when getting PURE_GRANT message on an endpoint which is being removed or cancelled.
Invoking the AM handler results in reaching the stub AM handler (id = 0, length = 0).
=> UCT/IB/RC: Don't invoke AM handler for PURE_GRANT messages

src/uct/ib/base/ib_log.c, src/uct/ib/base/ib_log.h, src/uct/ib/base/ib_verbs.h, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/dv/ib_mlx5_ifc.h, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
Print remote QP info for RC QPs when TX op fails.
With RC, WQEs do not contain av info, but it would be useful to have it printed when TX operation fails 
Output examples:
```
[     INFO ] < Transport retry count exceeded on mlx5_1:1/IB (synd 0x15 vend 0x81 hw_synd 0/0) >
[     INFO ] < RC QP 0x938 wqe[1]: RDMA_WRITE --- [rva 0x0 rkey 0x0] [rqpn 0x937 rlid 2 dgid fe80::1c34:da03:5b:b25d] >
```
```
[     INFO ] < send completion with error: transport retry counter exceeded [qpn 0x92c wrid 0x2vendor_err 0x81] [rqpn 0x92b rlid 2 dgid fe80::1c34:da03:5b:b25d] >
```
```
[     INFO ] < Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0) >
[     INFO ] < RC QP 0xd1e wqe[1]: RDMA_WRITE --- [rva 0x0 rkey 0x0] [rqpn 0xd1d dgid ::ffff:2.1.3.16] >
```
fixes #6673
=> UCT/RC: Print remote QP info for tx error CQEs

src/ucp/core/ucp_ep.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup_cm.c, test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc
1. Fix not selecting RNDV/RMA/AMO lanes during CM init phase.
2. Add gtest to check RNDV lanes selection.
3. Add support for `UCT_MD_FLAG_INVALIDATE` flags in TCP.
1. To use RNDV GET/PUT Zcopy schemes for EP created when `UCX_CM_USE_ALL_DEVICES=n` is set.
2. To reproduce the problem.
3. To pass gtest for TCP.
1. Added support `UCP_EP_INIT_CREATE_AM_LANE_ONLY` EP init flags; use this flag when creating CM client initial config to fit CM data length limit.
2. If PUT/GET Zcopy capabilities are supported by EP, check that RNDV lanes are created.
3. To pass the new gtest for TCP.
=> UCP/WIRUEP/GTEST/UCT: Fix not selecting RNDV/RMA/AMO lanes during CM init phase

src/uct/ib/base/ib_log.c, src/uct/ib/base/ib_log.h, src/uct/ib/base/ib_verbs.h, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/dv/ib_mlx5_ifc.h, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
=> UCT/RC: Print remote QP info for tx error CQEs - v1.11x

src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, src/ucs/vfs/fuse/vfs_fuse.c, test/gtest/ucs/test_vfs.cc
Added method to add symbolic link to VFS tree.
Added method to get relative to the target of a symbolic link.
Implemented FUSE callback to read symbolic link.
Added gtest for the new method.
To support links between nodes in VFS. E.g. link between UCP lane and UCT ep.
=> UCS/VFS: Symbolic links support in VFS.

src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, test/gtest/ucp/test_ucp_sockaddr.cc
Handle WIRUEP_MSG sending failure.
Fixes:
```
[jazz11:58472:0:58472]   wireup_cm.c:1223 Assertion `status == UCS_OK' failed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210615_112011_166943_41021_jazz11.swx.labs.mlnx/installs/7RUC/tests/io_demo/ucx.git/src/ucp/wireup/wireup_cm.c: [ ucp_cm_server_conn_notify_progress() ]
...
1220         ucp_wireup_remote_connected(ucp_ep);
1221     } else {
1222         status = ucp_wireup_send_pre_request(ucp_ep);
==>  1223         ucs_assert_always(status == UCS_OK);
1224     }
1225     UCS_ASYNC_UNBLOCK(&ucp_ep->worker->async);
1226     return 1;
==== backtrace (tid:  58472) ====
0 0x000000000014f568 ucp_cm_server_conn_notify_progress()  /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210615_112011_166943_41021_jazz11.swx.labs.mlnx/installs/7RUC/tests/io_dem …
```
=> UCP/WIREUP/GTEST: Handle WIRUEP_MSG sending failure

src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/perftest.c
This PR generalizes the calculation and display of the median latency to support any user-defined percentile.
A `-R <rank>` option is added to `ucx_perftest` so that the user can provide a percentile rank (0% ~ 100%), and the corresponding percentile will be displayed in the output.
So the user can get different types of statistics: 0.01% = best latency, 50.0% = median latency, 99.9% = tail latency.
This PR also fixes an issue in median latency calculation: if the number of iterations is less than half of `TIMING_QUEUE_SIZE`, the `timing_queue` array will only be less than half full, so the median latency will always be zero.
Add a new `-R` option, adjust the quick select function, adjust the stats display code.
One question: is there any reason why the length of the `timing_queue` array, …
=> TOOLS/PERF: Generalize median calculation to support any percentile

contrib/buildrpm.sh
Fix issue that binary RPM created with rpmbuild.sh tool did not include VFS/Fuse support
=> BUILD/RPM: Fix with-fuse arg for rpm build

src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_request.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, test/gtest/ucp/test_ucp_sockaddr.cc
Don't ask INVALIDATE for p2p lanes. 
They don't need to support INVALIDATE capability on their MD.
This returns back usage RNDV for TCP with CM + Error-Handling.
1. Check p2p connection mode instead of just `CONNECT_TO_IFACE` (transport could support both `CONNECT_TO_EP` and `CONNECT_TO_IFACE`).
2. Don't request support of `INVALIDATE` flag during selection if p2p connection is going to be used.
3. Fix gtests to pass now.
=> UCP/CORE/WIREUP/GTEST: Don't ask INVALIDATE for p2p lanes

src/uct/ib/dc/dc_mlx5_ep.c
- in case if EP allocated DCI and no outgoing operarions are in progress,
then schedule EP to TX queue to eliminate
EP arb_group leak
=> DC/MLX5/ARB: force schedule EP to TX queue

src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_sockaddr.cc
Stop processing client/server's connect if endpoint disconnected.
Fixes #6966 
If users does `ucp_ep_close_nbx()` while UCP endpoint is still connecting (e.g. `ucp_cm_client_connect_progress()` was scheduled on the callbackq, but not completed yet), we should stop all CM-related callbacks to make sure they won't be called after CM was already discontented.
1. Check flag `LOCAL_CONNECTED` on `client_connect_progress`/`server_conn_notify_progress` as assertion.
2. Remove `client_connect_progress`/`server_conn_notify_progress` from callbackq if they are set.
3. Reproduce the problem in gtests by setting EP failed after cleint/server connect progress function added to callbackq.
4. In `ucp_ep_disconnected()`, if the EP is still locally conencted by CM, need to disconnect from a peer.
=> UCP/WIREUP/GTEST: Stop processing client/server's connect if endpoint disconnected

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
extend io_demo server statistics
```
[1620725353.456991] [DEMO] read:77376 ops, write:77402 ops, active connections:1, min:154777/604.598MB(2.1.3.26:60322), max:154777/604.598MB(2.1.3.26:60322), buffers:698
[1620725354.457181] [DEMO] read:77559 ops, write:77554 ops, active connections:1, min:155113/605.91MB(2.1.3.26:60322), max:155113/605.91MB(2.1.3.26:60322), buffers:698
[1620725355.457230] [DEMO] read:77272 ops, write:77265 ops, active connections:1, min:154537/603.66MB(2.1.3.26:60322), max:154537/603.66MB(2.1.3.26:60322), buffers:698
```
to analyze fairness
cherry-pick from https://github.com/yosefe/ucx/pull/140
=> IODEMO: extend server statistics

src/uct/rocm/copy/rocm_copy_iface.c, test/gtest/uct/test_p2p_rma.cc, test/gtest/uct/v2/test_uct_query.cc
Backport https://github.com/openucx/ucx/pull/6989 to 1.11.x branch
=> UCT/ROCM/COPY: Fix test_uct_query gtest

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c
Complete KA round if iter == iter_begin when removing EP from KAю
To fix the following assertion detected when running IO-demo:
```
[jazz15:169944:0:169944]      ucp_ep.c:2803 Assertion `(now - ucp_ep_ext_control(ep)->ka_last_round) >= worker->context->config.ext.keepalive_interval' failed: ep 0x7fb3009b16b0: now=<975076.878278 sec> ka_last_r
ound=<975076.268333 sec> (diff=<0.609944 sec>) ka_interval=<60.000000 sec>
```
Before the PR, we completed KA round when moved `iter` now points to `iter_begin`. This PR moves this to the common place, which handles not only moving of `iter`, but also moving of `iter_begin`.
=> UCP/CORE: Complete KA round if iter == iter_begin when removing EP from KA

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.inl, src/ucp/proto/proto_am.inl, src/ucp/rma/flush.c, src/ucp/rma/rma_basic.c, src/ucp/rma/rma_send.c, src/ucp/rndv/rndv.c
Handle in-place failure from AM/RMA operations.
To not complete the same operation twice - it leads to undefined behavior.
- Removed ucp_request_send_state_advance_comp() as no longer needed.
- Operations now responsible to correctly handle failure - i.e. to call ucp_request_send_state_ff() - this is mvoed to the operations level, because some operations need to advance send state, but other don't need to do it (e.g. RMA basic and SW).
- Added memory deregistration in ucp_request_send_state_ff() to be used for RMA operations as well - it is safe, since it is no-op if no registrations were done.
=> UCP/CORE/PROTO: Handle in-place failure from AM/RMA operations

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_sockaddr.cc
Set lanes failed when error is detected.
To fix doing AM/GET/PUT/AMO operations after the UCT EP failed.
```
[1623875636.709979] [UCX-connection #5 1.1.28.1:33236] completing request 0x137fc10 with status "Endpoint timeout" (-80) during disconnect
[1623875636.709985] [UCX-connection #5 1.1.28.1:33236] released
[swx-ucx03:52327:0:52327]   rc_mlx5.inl:456  Assertion `!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED)' failed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210616_214156_71374_41349_swx-ucx01.swx.labs.mlnx/installs/4qZZ/tests/io_demo/ucx.git/src/uct/ib/rc/accel/rc_mlx5.inl: [ uct_rc_mlx5_common_post_send() ]
...
453     if (opcode != MLX5_OPCODE_NOP) {
454         /* If FAILED, allow only NOP sends to be posted (used by endpoint
455          * flush operations) */
==>   456 …
```
=> UCP/CORE: Set lanes failed when error is detected

src/ucp/core/ucp_ep.c
Remove incorrect assertion for error handling mode.
Fixes #7001.
Remove incorrect assertion that checks error handling in `ucp_ep_discard_lanes()`.
=> UCP/CORE: Remove incorrect assertion for error handling mode

src/ucp/core/ucp_request.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
fix discarding from pending on failed lane
bugfix
- increase completion counter only when flush cancel operation has been posted
- purge pending for discarding lane since discard op can be on pending
=> UCP/EP: fix discarding from pending on failed lane

buildlib/tests.yml
Increase the timeout of test job in the pipeline to 6 hours.
Tests number is increasing and they take more time. We want to avoid the pipeline failing on timeout.
=> AZP/TEST: Increase test job timeout to 6 hours

ucx.spec.in
Remove execution of `ucx_info -fC` upon RPM installation. 
Transactions on several sub-packages can lead to an inconsistent state and invalid execution of `ucx_info`, with memory corruption. 
The default config can be manually generated later by the user.
=> RPM/SPEC: Do not generate ucx.conf default config after installation

ucx.spec.in
Remove execution of `ucx_info -fC` upon RPM installation. 
Transactions on several sub-packages can lead to an inconsistent state and invalid execution of `ucx_info`, with memory corruption. 
The default config can be manually generated later by the user.
=> RPM/SPEC: Do not generate ucx.conf default config after installation - v1.11.x

src/ucs/vfs/fuse/vfs_fuse.c
- there was uninitialized variable access in affinity set
=> VFS: fixed uninitialized variable access

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/vfs/fuse/vfs_fuse.c
Changed log level of inotify_init() failure from 'error' to 'diag'.
Added workaround to diagnostic message.
Use case.
User doesn't launch ucx_vfs daemon.
User runs several processes that use UCX library.
Each process initializes inotify to be ready to connect with daemon when it starts.
However, the number of inotify instances are limited by fs.inotify.max_user_instances.
Thus, only first fs.inotify.max_user_instance processes will be monitored by ucx_vfs, when user start the daemon.
=> UCS/VFS: Changed log level of inotify_init failure to diag.

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/rndv/rndv.c, test/gtest/ucp/test_ucp_am.cc
Fallback to PUT pipeline only if PUT protocol is supported. 
Fixes #6836.
When is going to fallback to PUT pipeline protocol, check PUT Zcopy support assuming symmetric configuration of sender and receiver, i.e. check that the length of the message is:
- greater than minimum PUT Zcopy
- maximum PUT Zcopy isn't `0`
=> UCP/RNDV: Fallback to PUT pipeline only if PUT protocol is supported

buildlib/azure-pipelines-pr.yml, src/tools/info/ucx_info.c, src/ucp/core/ucp_context.c, src/uct/ib/rdmacm/rdmacm_cm.c
- Don't fail to create UCP context if no CM components are present
- Add ucx_info-based tests to AZP
We may want to use UCX without client/server connection establishment, so no need to always require CM components.
For example, inside a docker, we don't always have TCP.
=> UCP/CONTEXT: Don't fail if no CM components are found

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucs/async/async.c, src/ucs/async/async.h, src/ucs/async/async_int.h, src/ucs/async/signal.c, src/ucs/async/thread.c, test/gtest/ucp/test_ucp_sockaddr.cc
Don't invoke set_ep_failed from async thread.
`ucp_worker_set_ep_failed()` mustn't be called from async thread to avoid undefined behavior. e.g.:
```
[1624837542.225089] [jazz29:91333:async]       wireup_cm.c:143  UCX  DIAG  client ep 0x7f39bccda000 failed to connect to 2.1.3.29:20000 using rdmacm,tcp cms
[jazz29:91333:0:91333] ucp_request.inl:947  Assertion `req->flags & UCP_REQUEST_FLAG_SUPER_VALID' failed: req=0x2469980 req->super_req=(nil)
[jazz29:91333:async:91397] ucp_request.inl:947  Assertion `req->flags & UCP_REQUEST_FLAG_SUPER_VALID' failed: req=0x2469980 req->super_req=(nil)
[1624837542.225940] [jazz29:91333:async]           debug.c:1377 UCX  WARN  ucs_debug_disable_signal: signal 8 was not set in ucs
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210628_015958_133135_44637_jazz28. …
```
=> UCP/CORE/UCS/GTEST: Don't invoke set_ep_failed from async thread

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc
Improve logging for connection-related actions.
To print connection info when disconnecting to improve debugging.
```
[1623350558.799549] [DEMO] timeout waiting for 45 replies on the following connections (0 connections to disconnect):
1. [0x246f640: [UCX-connection #13 2.1.3.23:20000]] has 14 uncompleted operations (read: 0/6; write: 2/10)
2. [0x25a9190: [UCX-connection #38 2.1.3.23:20008]] has 15 uncompleted operations (read: 1/11; write: 0/5)
3. [0x2570770: [UCX-connection #29 2.1.3.23:20007]] has 16 uncompleted operations (read: 0/7; write: 0/9)
```
```
[1623350274.213618] [DEMO] disconnecting [0x25815d0: [UCX-connection #31 2.1.3.23:20002]] connection with 0 uncompleted operations (read: 0/0; write: 0/0) due to "Operation timed out"
```
1. Get log prefix of the connection and its …
=> APPS/IO-DEMO: Improve logging for connection-related actions

docs/source/faq.md
Fix the docs (currently they are outdated).
`ucx.conf` is not created upon installation anymore: https://github.com/openucx/ucx/commit/1357977e64e97f9553290f8e39576aa03402e109.
=> DOCS/SOURCE: Fix configuration file documentation

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h
- there was issue in ep_flush resource check:
incorrect sequence of evaluation which caused
extra arbiter processing
- added progress pending into purge_pending routine
=> DC/MLX5: fix in flush resource check

src/ucp/api/ucp.h, src/ucp/core/ucp_am.c, src/ucp/core/ucp_am.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/proto/proto_am.inl, src/ucp/rndv/rndv.c, src/ucp/stream/stream_recv.c, src/ucp/stream/stream_send.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/eager_snd.c, src/ucp/tag/tag_rndv.c, src/uct/ib/base/ib_iface.c, src/uct/sm/mm/base/mm_iface.c, test/gtest/ucp/test_ucp_am.cc
Add UCP AM  alignment support on the receiver
It is required by several customers
Always send the same size AM header for eager messages. The rest of meta data is added to the end of message (footer) for those protocols which need bigger header.
=> UCP: AM alignment

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Currently, io_demo use polling method to deal with event. This PR makes io_demo could use epoll to monitor the event happened on ucp_worker.
Feature request
=> support io_demo to use "-e" option to enable epoll ucp_worker

src/ucp/core/ucp_context.c
Reduce KA interval to detect failures earlier.
To detect peer failures earlier and no impact on normal flow.
1. "60s" -> "20s".
2. Remove the comment.
=> UCP/CORE: Reduce KA interval to detect failures earlier

src/tools/perf/perftest.c
Improve ucx_perftest usability
- Print if transport or device are missing for UCT test
- Remove "iov" data layout from UCT tests help message
=> TOOLS/PERF: Improve help and error message

src/ucs/datastruct/mpool.c, src/ucs/datastruct/mpool.h, test/gtest/ucs/test_mpool.cc
Fix #7043 
- Make chunk-size vars and funcs use size_t instead of unsigned
- Add gtest
=> UCS/MPOOL/TEST: Fix integer overflow in mpool chunk allocation

test/apps/iodemo/io_demo.cc
Fix random shuffle of servers on Client.
1. To not do shuffle of servers prior setting `srand()`.
2. To do shuffle of servers in case of AM and (chunk_size < max_data_size).
1. Move setting `srand()` in `adjust_opts()`.
2. Remove return in case of AM and (chunk_size < max_data_size).
=> APPS/IO-DEMO: Fix random shuffle of servers on Client

src/ucs/datastruct/bitmap.h, src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h
- use ucs_bitmap to store set of dci's to release instead of check every DCI
=> DC/MLX5/OPTIMIZATION: use bitmap to release detached dci's

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c
fix pending discard lane on failure
bug fix
fast forward pending queue requests via temporary queue since uct_arbiter_t does not support recursive calls
=> UCP/WORKER: fix pending discard lane on failure

src/ucp/rndv/rndv.c
Don't send ATP on PUT Zcopy failure.
Fixes:
```
[jazz28:20338:0:20338]   rc_mlx5.inl:456  Assertion `!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED)' failed
/labhome/dmitrygla/work_auto/ucx/src/uct/ib/rc/accel/rc_mlx5.inl: [ uct_rc_mlx5_common_post_send() ]
...
453     if (opcode != MLX5_OPCODE_NOP) {
454         /* If FAILED, allow only NOP sends to be posted (used by endpoint
455          * flush operations) */
==>   456         ucs_assert(!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED));
457     }
458
459     ctrl = txwq->curr;
==== backtrace (tid:  20338) ====
0 0x00000000000e4521 uct_rc_mlx5_common_post_send()  /labhome/dmitrygla/work_auto/ucx/src/uct/ib/rc/accel/rc_mlx5.inl:456
1 0x00000000000e4521 uct_rc_mlx5_txqp_inline_post() …
```
=> UCP/RNDV: Don't send ATP on PUT failure

buildlib/az-distro-release.yml, buildlib/az-helpers.sh, buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.yml, buildlib/jucx/jucx-publish.yml
Fix condition checking for release pipeline
- Fix that artifacts are not uploaded for tag trigger
- Fix jucx publish
Build.Reason| Trigger reason | Build packages |  Upload release artifacts| JUcx mode
-- | -- | -- | -- | ---
PullRequest | PR with `"AZP/RELEASE"*` commit title | Yes | No | Build only
PullRequest | PR without `"AZP/RELEASE"*` commit title | No | No | Skip
ResourceTrigger | Merge to master/release branch | Yes | No | Snapshot
IndividualCI | New tag matching `v*` pattern | Yes | Yes | Release
- Move conditions to upper layer script (az-pipelines-release.yml)
- Use variables instead of parameters for jucx-publish.yml
- Change container path in jucx pipeline to workaround docker run error
=> AZP/RELEASE: Fix github release pipeline conditions

src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h
Move to the previous EP if removed EP points to the last EP.
To avoid doing keepalive twice for `iter_begin` element during the same round.
Before:
After:
1. Rename `iter_begin` to `iter_end`, because this name better reflects the purpose of the iterator.
2. When removing `iter` which points to `iter_end`, update `iter_end` to point to the predecessor of the `iter_end`. If `iter == iter_end`, KA round will be completed.
=> UCP/CORE: Move to the previous EP if removed EP points to the last EP

src/ucp/tag/offload.c
remove unneeded parameter in tag offload bcopy sending function
=> UCP/HWTM: bcopy protocol cleanup

src/ucp/api/ucp.h
=> UCP/API: Fix typo in post atomics description

src/ucp/rndv/rndv.c
Don't initialize variable by 0 if it is not read then.
To fix the following warning:
```
/__w/1/s/src/ucp/rndv/rndv.c:1349:5: warning: Value stored to 'is_get_zcopy_supported' is never read [deadcode.DeadStores] <--[clang]
is_get_zcopy_supported = 0;
^                        ~
1 warning generated.
```
The initial value stored in `is_get_zcopy_supported` is not used then, it is just overwritten.
Don't initialize `is_get_zcopy_supported` by `0`.
=> UCP/RNDV: Don't initialize variable by 0 if it is not read then

test/apps/iodemo/io_demo.cc
Add assertions for `num_send` and `num_completed` counters.
To debug the following assertion:
```
io_demo.cc:1548: static long int DemoClient::get_num_uncompleted(const DemoClient::server_info_t&): Assertion `num_uncompleted >= 0' failed
```
Use standard `assert()` to check:
- `server_info.num_completed[op] < server_info.num_sent[op]`.
- `_num_completed < _num_sent`.
=> APPS/IO-DEMO: Add assertions for num_send|completed counters

src/uct/ib/dc/dc_mlx5.h
Fix build with rdma-core 20 which does not have devx
Add full_handshake parameter to dummy function
=> UCT/DC: Fix compilation with rdma-core 20

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c
Don't send FC_PURE_GRANT if DCI hasn't been reset yet after failure.
To fix the following failure:
```
[jazz26:110223:0:110223]   rc_mlx5.inl:456  Assertion `!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED)' failed
/labhome/dmitrygla/work_auto/ucx/src/uct/ib/rc/accel/rc_mlx5.inl: [ uct_rc_mlx5_common_post_send() ]
...
453     if (opcode != MLX5_OPCODE_NOP) {
454         /* If FAILED, allow only NOP sends to be posted (used by endpoint
455          * flush operations) */
==>   456         ucs_assert(!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED));
457     }
458
459     ctrl = txwq->curr;
==== backtrace (tid: 110223) ====
0 0x00000000001265da uct_rc_mlx5_common_post_send()  /labhome/dmitrygla/work_auto/ucx/src/uct/ib/rc/accel/rc_mlx5.inl:456
1 0x00000000001265da uct_rc_mlx5_txqp_inline_post() …
```
=> UCT/IB/DC: Don't send FC_PURE_GRANT if DCI hasn't been reset yet after failure

contrib/valgrind.supp, test/gtest/common/test_perf.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucs/test_mpool.cc
- Reduce testing time with valgrind to prevent kill by timeout
- Add some suppressions to fix [valgrind failures](https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=20810&view=logs&jobId=df68dda4-06c2-536e-ce97-89c9eb16a9f6&j=df68dda4-06c2-536e-ce97-89c9eb16a9f6&t=8fc70d47-5a35-50c6-bed4-97d5d142cf9e)
=> TEST: Improvements for gtest with valgrind

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucs/datastruct/frag_list.c, src/ucs/debug/memtrack.c, src/ucs/memory/rcache.c, src/ucs/stats/libstats.h, src/ucs/stats/stats.c, src/ucs/stats/stats.h, src/uct/base/uct_iface.c, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_md.c, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/ud/base/ud_iface.c, test/gtest/ucs/test_stats.cc, test/gtest/ucs/test_stats_filter.cc
- The problems:
(1) The UDP server interface for counters collection is very
inefficient.
(2) The number of UCX counters grows significantly by the number of
MPI processes due to an increased number of endpoints.
This yields a challenge for trace counters collection tools such
as Score-P.
- The proposed solution:
(1) Use a per-process API rather than a gathering of all counters
in the root process by the UDP server.
(2) Use an aggregate-sum API of all counters of the same class
and type.
==> This mechanism yields a constant number of counters.
_It is optional but for complex PRs please provide information about the …
=> UCS: Add API for a per-process aggregate-sum statistics report

src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.h
Allow tuning of estimated Cuda copy bandwidth for tweaking protocol selection
=> UCT/CUDA_COPY: Option to set cuda_copy bandwidth

src/ucs/async/async.h, src/ucs/type/spinlock.c, src/ucs/type/spinlock.h, src/uct/ib/base/ib_device.c, src/uct/ib/base/ib_device.h, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5.h, src/uct/ib/mlx5/ib_mlx5.inl, src/uct/ib/mlx5/ib_mlx5_log.c, src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/ib/test_ib_event.cc
- Handle rc_mlx5 error CQEs which arrive after endpoint id destroyed
- Fix potential reorder in rc_verbs when releasing CQ resources without arbiter dispatch (during ep destroy)
- Refactor RC cleanup so it will always happen from the progress queue
- Release CQ resources from RC cleanup context and dispatch arbiter
- mlx5: keep one CQ credit for each posted WQE to be released when the CQE eventually arrives. This is needed to avoid CQ overrun if CQ credits are released too soon (for verbs, ibv_destroy_qp would remove CQE entries)
Since we count CQ credits by building blocks[1], if we have a completion without an associated endpoint, we cannot know how many CQ credits to return. On the other hand, can't release all credits during EP destroy since completions did not arrive and it may cause …
=> UCT/RC: Fix handling error CQE after rc_ep is destroyed 

src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, test/gtest/ucp/test_ucp_sockaddr.cc
Remove trying next CM callback upon destroying EP.
Trying next CM callback should be removed upon destroying EP to avoid calling it when UCP EP is already destroyed.
1. Added `UCP_EP_FLAG_TRY_NEXT_CM` flag to check whether trying next CM callback scheduled or not - needed for DEBUG-only purposes and for GTESTs.
2. Introduced two GTESTs which fail wireup procedure when client is scheduling trying next CM callback.
3. Introduced filter function to remove trying next CM callback from cbq.
4. Use the new filter to remove trying next CM callback from cbq upon destroying UCP EP.
5. Destroy next UCT EP by using discarding functionality to allow calling it from async functions, e.g. UCT CM callback (resolve_cb, connect_cb).
6. Move destroying next UCT EP of CM lane to the place where scheduling …
=> UCP/CORE/WIREUP/GTEST: Remove trying next CM callback upon destroying EP

buildlib/azure-pipelines-release.yml, buildlib/azure-pipelines.yml, buildlib/jucx/jucx-publish.yml
Reverts jucx changes on #7081 
https://search.maven.org/artifact/org.openucx/jucx - it publishes to maven central except of snapshot on master merge. 
Master merge triggers by `Individual CI`: 
Need to publish release only when tag is created, otherwise publish to snapshot.
Thanks, @abellina for mentioning it.
=> AZP: fix JUCX publish.

src/uct/tcp/tcp_sockcm.c
suppress EHOSTUNREACH error message
this error can be handled by user via return code
decrease log level
=> UCT/SOCKCM: suppress EHOSTUNREACH

src/uct/base/uct_iface.h
verbose AM CB return assert
to simplify debugging
cherry-picked from https://github.com/yosefe/ucx/pull/162
=> UCT/IFACE: verbose AM CB return assert

src/ucp/core/ucp_request.inl
Add assertion that request hasn't been completed yet.
To debug the possible issue when completing receive operations more than once.
Before setting `UCP_REQUEST_FLAG_COMPLETED` check that it is not set for the request.
=> UCP/CORE: Add assertion that request hasn't been completed yet

src/ucp/core/ucp_worker.c, src/ucp/wireup/wireup_cm.c
Destroy UCT EP before destroying UCP EP in discarding.
to fix the following data race:
```
Thread 2 (Thread 0x7fd346f1d780 (LWP 174140)):
#0  0x00007fd345b2b4b2 in pthread_spin_lock () from /lib64/libpthread.so.0
#1  0x00007fd3427ddf44 in ucs_spin_lock (lock=0x142d028)
at /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210711_081125_22405_47588_jazz11.swx.labs.mlnx/installs/TfJU/tests/io_demo/ucx.git/src/ucs/type/spinlock.h:83
#2  0x00007fd3427ddf91 in ucs_recursive_spin_lock (lock=0x142d028)
at /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210711_081125_22405_47588_jazz11.swx.labs.mlnx/installs/TfJU/tests/io_demo/ucx.git/src/ucs/type/spinlock.h:95
#3  0x00007fd3427e1b3e in uct_rdmacm_cm_ep_t_cleanup (self=0x15e3700) at rdmacm_cm_ep.c:704
#4  0x00007fd3467f5de0 in ucs_class_call_cleanup_chain …
```
=> UCP/CORE/WIREUP: Destroy UCT EP before destroying UCP EP in discarding

src/ucp/core/ucp_am.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/proto/proto_am.inl, src/ucp/proto/proto_common.inl, src/ucp/rma/amo_sw.c, src/ucp/rma/rma.inl, src/ucp/rma/rma_sw.c, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv_get.c, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/tag_send.c, src/ucp/wireup/wireup.c
Remove unused flags in pending_add wrapper/
All functions pass `0` as `pending_flags` argument to `ucp_request_pending_add()`.
1. Remove `pending_flags` argument for `ucp_request_pending_add()`, `ucp_request_send()`, `ucp_request_try_send()`.
2. Remove passing the second argument to these functions in all places where they are called.
=> UCP/CORE/PROTO: Remove unused flags in pending_add wrapper

src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Increase keepalive interval from 1 to 2 seconds and use system default for keepalive retries count.
Fixes #6705.
Fixes #6471.
When the large amount of connections are started simultaneously, it leads to network congestions and some TCP EPs are failed, because they don't receive ACK on previously sent KEEPALIVE packet. Increasing timeout helps to resolve the issue. `1s` timeout between retries is too small one.
1. Change value of `UCT_TCP_EP_DEFAULT_KEEPALIVE_INTVL` from `1` to `2`.
2. Update KEEPCNT configuration parameter to be ULUNITS and set `"auto"` as a default value. Handle it when setting socket options for KA.
=> UCT/TCP: Increase keepalive interval from 1 to 2 seconds and use system default for keepalive retries count

src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/base/vfs_obj.h, src/ucs/vfs/fuse/vfs_fuse.c, test/gtest/ucs/test_vfs.cc
Added method to add a read-write file to VFS.
Added method to write to the read-write file.
Implemented write fs operation.
Added gtests for the feature.
RW files in VFS allows to configure the library via VFS files, e.g. change log level.
=> UCS/VFS: RW files support in VFS. 

src/ucp/wireup/wireup.c
Expect that dst_ep_id is always sent in WIREUP_MSG in case of CM.
E.g. to make sure we don't create new UCP EP when handling WIREUP_MSG/REQ.
Check that we don't pass `UCS_PTR_MAP_KEY_INVALID` to `dst_ep_id` when preparing WIREU_MSG in case of CM.
=> UCP/WIREUP: Expect that dst_ep_id is always sent in WIREUP_MSG in case of CM

.gitignore, Makefile.am, buildlib/tools/builds.sh, cmake/Makefile.am, cmake/ucx-config-version.cmake.in, cmake/ucx-config.cmake.in, cmake/ucx-targets.cmake.in, configure.ac, examples/cmake/CMakeLists.txt, examples/cmake/test_ucp.c, examples/cmake/test_uct.c, ucx.spec.in
This PR makes the installation script writes cmake config files to ${prefix}/lib/cmake/ucx so that cmake projects can easily find UCX installed on the system. PyTorch uses cmake, so this will be helpful for PyTorch to integrate the ucx/ucc backend to upstream.
This PR is tested by: https://github.com/zasdfgbnm/cmake-ucx-ucc, please let me know if you want cmake testes to be included in this repository as well.
Related: https://github.com/openucx/ucc/pull/255
=> BUILD: Help cmake find UCX on system

NEWS, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c
Increase keepalive interval from 1 to 2 seconds and use system default for keepalive retries count.
Fixes #6705.
Fixes #6471.
Backporting #7093.
=> UCT/TCP: Increase keepalive interval from 1 to 2 seconds and use system default for keepalive retries count [v1.11.x]

src/ucs/memory/rcache.c
Add debug information for removing in-use region
=> UCS/RCACHE: Print region pointer when destroying in-use region

test/gtest/common/mem_buffer.cc, test/gtest/common/mem_buffer.h, test/gtest/ucm/rocm_hooks.cc
Fixes a gtest that tests hipMallocManaged
The unit test fails on machines on devices which are not capable of performing hipMallocManaged
Add a check to see if the current device can perform hipMallocManaged, and only perform the test if this is true.
=> GTEST/UCM/ROCM: Fix hipMallocManaged hook gtest

src/ucs/vfs/fuse/vfs_fuse.c
=> VFS/FUSE: Don't print a diagnostic message when fuse thread is stopped

test/gtest/ucp/test_ucp_perf.cc, test/gtest/ucs/arch/test_x86_64.cc
Fix recent test failures in test_arch.memcpy and test_ucp_wait_mem.envelope
=> TEST/PERF: Relax performance requirements

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.inl, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h
Potential fix for this error. The queued operation is `uct_dc_mlx5_iface_fc_grant` which returns UCS_ERR_NO_RESOURCES because its DCI has failed.
```
[1626626933.466407] [jazz20:154486:0]     ib_mlx5_log.c:170  UCX  DIAG  Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
[1626626933.466407] [jazz20:154486:0]     ib_mlx5_log.c:170  UCX  DIAG  DCI QP 0x1d11e wqe[0]: SEND s-e [rqpn 0x1f3ee rmac ec:0d:9a:c0:46:3d sgix 3 dgid ::ffff:2.1.3.21 tc 106] [inl len 11]
[jazz20:154486:0:154486]  dc_mlx5_ep.c:1297 Assertion `!uct_dc_mlx5_iface_dci_ep_can_send(ep)' failed: pending callback returned error, but send resources are available
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210717_111502_22719_49387_jazz03.swx.labs.mlnx/installs/2M7r/tests/io_demo/ucx.git/src/uct/ib …
```
=> UCT/DC: Don't schedule failed flow control ep

src/ucs/async/thread.c, src/ucs/debug/assert.c, src/ucs/stats/libstats.c, src/ucs/stats/stats.c, src/ucs/sys/string.c, src/ucs/sys/string.h, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/vfs/base/vfs_obj.c, src/ucs/vfs/fuse/vfs_fuse.c, test/gtest/common/test_perf.cc
To allow quick identification of the various service threads in gdb
=> UCS/SYS: Set names for threads

test/apps/iodemo/ucx_wrapper.cc
- there was memory leak in send_io_message routine
when connection is in "disconnecting" state
- added callback notification to allow release object
=> IO-DEMO: fixed memory leak

src/uct/api/v2/uct_v2.h, src/uct/base/uct_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c, test/gtest/uct/v2/test_uct_query.cc
- Rename UCT_OP_xx to UCT_EP_OP_xx because the enum is named `uct_ep_operation_t`
- Add informative names for UCT endpoint operations
- Add UCT_EP_OP_LAST to be the invalid operation ID
=> UCT/API/V2: Add names for UCT endpoint operations

test/apps/iodemo/io_demo.cc
Fix assertion failures in io_demo test
When invalidating the last entry, pointed by _num_active_servers_to_use, also need to rewind _next_active_index to 0.
Otherwise, _next_active_index can get out of bounds.
@dmitrygx
=> IODEMO: Fix active_servers_make_unused

src/uct/ib/dc/dc_mlx5_devx.c
Set traffic class for RoCE, because:
- it is used by v1
- some FW versions rely on it even for RoCE v2
=> UCT/DC: Set tclass for RoCE in dct

src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/proto/proto.h, src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_reconfig.c, src/ucp/rma/get_am.c, src/ucp/rma/get_offload.c, src/ucp/rma/put_am.c, src/ucp/rma/put_offload.c, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload/eager.c, src/ucp/tag/tag_rndv.c
- Optimize protocols progress function by using different function pointers instead of branches
- More structured definition of protocols with multiple stages. For example: rdnv-get has {get_zcopy, ats} and rndv-put would have {put_zcopy, flush/fence, atp}. Pipeline protocol will have an additional stage of rdnv fragment copy.
=> UCP/PROTO/RNDV: Add protocol stages

src/ucp/core/ucp_request.inl, src/ucs/sys/stubs.c, src/ucs/sys/stubs.h
- added fake callback into request_put routine to
handle incorrectly completed cases
=> UCP/REQUEST: added fake callback into request_put

src/uct/ib/rc/verbs/rc_verbs_iface.c, src/uct/ib/rc/verbs/rc_verbs_impl.h
Align WC error status with MLX5 error handling.
If this is some recoverable error (e.g. due to connection reset or remote access error in case of peer down), need to report error with DIAG log level instead of ERROR.
1. Mapping MLX5 CQE syndrome to WC status was taken from `mlx5_handle_error_cqe()` - https://github.com/gpudirect/libmlx5/blob/9d34626161340d3c922654ea2654a25c73766386/src/cq.c#L368
2. Make `uct_rc_verbs_wc_to_ucs_status()` static, since it is used only in a single place.
=> UCT/IB/RC/VERBS: Align WC error status with MLX5 error handling

test/gtest/common/test_helpers.cc
Ignore watchdog thread when debugging with gdb
=> TEST/GTEST: Set name for the watchdog thread

src/ucs/arch/aarch64/bitops.h, src/ucs/arch/ppc64/bitops.h, src/ucs/arch/x86_64/bitops.h, test/gtest/ucs/test_bitops.cc
rdnv/put/zcopy protocol would have to go over lane bitmaps which are small
=> UCS/ARCH/BITOPS: Add ucs_ffs32

src/ucp/core/ucp_request.c, src/ucp/proto/proto_common.inl
- Fix tracing req before req->send.proto_config is set
- When progress func returns INPROGRESS, req->send.lane may be uninitialized
=> UCP/REQUEST: Fix proto request tracing

src/ucp/core/ucp_worker.c
max_eager_short is being pointer to wrong structure
=> UCP/WORKER: Fix tag short threshold selection

configure.ac, src/ucs/Makefile.am, src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/debug/debug.c, src/ucs/debug/debug_int.h, src/ucs/profile/profile.c, src/ucs/sys/init.c, src/ucs/sys/lib.c, src/ucs/sys/lib.h, test/gtest/ucs/test_config.cc, test/gtest/ucs/ucx_test.conf
Search in several directories for the `ucx.conf`. Each file is parsed and its contents override the previous ones. Any file which is not found or cannot be parsed is silently ignored. The paths are scanned in the following order:
1. %sysconfdir/ucx.conf
2. <libucs.so>/../etc/ucx.conf
3. ~/.ucx.conf
4. $UCX_CONFIG_DIR
5. $PWD/ucx.conf
Provide more flexibility for the user, by combining system-wide, user personal and local project configuration.
=> UCS/CONFIG: Search for configuration in multiple paths

src/ucp/Makefile.am, src/ucp/dt/datatype_iter.c, src/ucp/dt/datatype_iter.h, src/ucp/dt/datatype_iter.inl, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_dt.cc, test/gtest/ucp/ucp_datatype.cc, test/gtest/ucp/ucp_datatype.h
In order to use datatype_iter to unpack RDNV_DATA, it should be able to handle any offset
- Add datatype seek
- Extend tests to test unpack with random segment size and order
=> UCP/DATATPE: Arbitrary offset for ucp_datatype_iter_unpack()

contrib/test_jenkins.sh
Call `get_active_ip_ifaces` instead of `get_active_ip_iface`.
Fix a typo - `get_active_ip_iface` does not exist.
=> CONTRIB: Fix typo in test_jenkins.sh

src/uct/ib/base/ib_verbs.h
This fixes the following error:
```
#39 81.07 In file included from base/ib_log.h:10:0,
#39 81.07                  from base/ib_log.c:11:
#39 81.07 base/ib_verbs.h: In function 'uct_ib_query_qp_peer_info':
#39 81.07 base/ib_verbs.h:346:5: error: implicit declaration of function 'memcpy' [-Werror=implicit-function-declaration]
#39 81.07      memcpy(ah_attr, &qp_attr.ah_attr, sizeof(*ah_attr));
#39 81.07      ^~~~~~
#39 81.07 base/ib_verbs.h:346:5: error: incompatible implicit declaration of built-in function 'memcpy' [-Werror]
#39 81.07 base/ib_verbs.h:346:5: note: include '<string.h>' or provide a declaration of 'memcpy'
#39 81.07 cc1: all warnings being treated as errors
#39 81.08 make[4]: *** [base/libuct_ib_la-ib_log.lo] Error 1
#39 81.08 make[4]: *** Waiting for unfinished jobs.... …
```
=> UCT: Include string.h because memcpy is used

test/gtest/ucp/test_ucp_perf.cc
Fix the following failures:
```
[2021-07-27T06:07:26.947Z] [ RUN      ] shm/test_ucp_wait_mem.envelope/33 <shm/am_mr>
[2021-07-27T06:07:27.203Z] [     INFO ]      put latency reference : 0.319 usec (performance not checked)
[2021-07-27T06:07:27.460Z] [     INFO ]      put latency reference : 0.319 usec (performance not checked)
[2021-07-27T06:07:27.717Z] [     INFO ]      put latency reference : 0.319 usec (performance not checked)
[2021-07-27T06:07:27.973Z] [     INFO ]      put latency reference : 0.319 usec (performance not checked)
[2021-07-27T06:07:28.230Z] [     INFO ]      put latency reference : 0.322 usec (performance not checked)
[2021-07-27T06:07:28.487Z] [     INFO ]      put latency reference : 0.319 usec (performance not checked)
[2021-07-27T06:07:28.743Z] [     INFO ] …
```
=> TEST/PERF: Increase thresholds for test_ucp_wait_mem

src/uct/api/v2/uct_v2.h, src/uct/base/uct_iface.c
Added API for `uct_iface_is_reachable_v2()`.
Provide upper layers with information on why some remote address is not reachable, for better error reporting.
Add uct_iface_is_reachable_v2() function to replace the existing uct_iface_is_rechable()
=> UCT/IFACE: introduces API for uct_iface_is_reachable_v2()

contrib/test_jenkins.sh, test/apps/test_init_mt.c
- there is at test on multithread init test
- in some cases when filesystem works slow test failed
due to timeout
- this fix excludes FS affect
=> TEST/INIT_MT: improved diagnostic

src/ucp/Makefile.am, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.inl, src/ucp/core/ucp_request.h, src/ucp/proto/proto_am.c, src/ucp/proto/proto_multi.h, src/ucp/proto/proto_multi.inl, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv.h, src/ucp/rndv/rndv_put.c, src/ucp/rndv/rndv_rtr.c, src/uct/base/uct_iface.h, test/gtest/ucp/test_ucp_tag_match.cc
- Allow put_zcopy mode with new protocols, useful for TCP transport for example
- Infrastructure for 3-staged pipeline which also uses put-based protocol
- Fixes vs. current put protocol: 
- better latency by sending ATP immediately after put
- fix correctness by using either fence or flush to ensure data is written remotely
put/zcopy protocol can work in 2 modes:
- fence: put_zcopy,fence(all lanes),atp(all lanes)
- flush: put_zcopy,flush(all lanes). on flush completion: atp(one lane)
The mode is selected according to transport capabilities (supports am_bcopy and put_zcopy on same lane) and according to configuration. "fence" mode is preferred because it has better latency.
=> UCP/PROTO/RNDV: Add new protocol for rndv over put_zcopy

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucs/async/async.c, src/ucs/async/async.h, src/ucs/async/async_int.h, src/ucs/async/signal.c, src/ucs/async/thread.c, test/gtest/ucp/test_ucp_sockaddr.cc
Set lanes failed when error is detected, Don't invoke set_ep_failed from async thread.
Backporting fixes from the master branch:
- #6974
- #7015
The PRs were ported manually, since the have merge conflicts which are quite hard to resolve.
=> UCP/CORE: Set lanes failed when error is detected, Don't invoke set_ep_failed from async thread - v1.11.x

src/tools/perf/lib/libperf.c
Signed-off-by: Vasily Philipov <vasilyf@nvidia.com>
Bug fix on error flow in ucp_perf_test_send_local_data func
=> LIBPERF: copy/paste bug fix on error flow

src/ucs/datastruct/ptr_array.c, src/ucs/datastruct/ptr_array.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/ud/base/ud_iface.c, test/gtest/ucs/test_datatype.cc
Signed-off-by: Alex Margolin <alex.margolin@huawei.com>
1. new API: allocating X ptr_array slots with a single call (much faster than X calls allocating single slots)
2. Avoid checking for leaks when this is not an issue for the user
3. Make macros slightly more readable
This is going to be used for the contiguous counters PR (#6783)
=> UCS: new ptr_array API for bulk allocation

src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.h, test/gtest/uct/ib/test_dc.cc
- allow missordered dci allocation in some tests
- some tests update resources manually to make some corner cases in UCX, due to this dci allocation ordering may be broken. suppress assertion in such cases
=> DC/DEBUG: added dci alloc assert, allow missorder

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h
- updated dci releasing progress data: dcis to
release are stored into same stack as allocated dcis
=> DC/MLX5: refactoring for dci release progress

src/ucp/api/ucp.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/api/uct_def.h, src/uct/api/v2/uct_v2.h, src/uct/base/uct_cm.c, src/uct/base/uct_cm.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/ib/rdmacm/rdmacm_cm_ep.h, src/uct/tcp/tcp_sockcm.c, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/uct/ib/test_sockaddr.cc
Add functions to query the ucp and uct endpoints
Sometimes users need API to get remote and local IP/port per endpoint
Get the remote and local IP/port through RDMA_CM
=> API/UCP/UCT/IODEMO: Add functions to query the ucp and uct endpoints

test/apps/iodemo/run_io_demo.sh
https://github.com/Mellanox/hpc-mtt-conf/issues/638
kill via -9
stop via SIGINT
=> IODEMO: Kill with -9, Stop via SIGINT

src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Implement flush of all outstanding operations.
To fix `uct_ep_flush()` which don't wait for all operations being completed. As a result if fixes the following case:
```
/* client */
for (i= 0; i < 1000; ++i) { 
req = ucp_ep_tag_send_nb(ep)
reqs.push_back(req);
}
wait_for_reqs(reqs);
req = ucp_ep_close_nb(ep, FLUSH);
wait_for_req(req);
exit(0);
```
```
/* server */
for (i = 0; i < 1000; ++i) {
req = ucp_worker_tag_recv_nb(worker);
reqs.push_back(req);
}
wait_for_reqs(reqs);
/* 998-999 completed successfully, but 1-2 completed with error  */
```
1. Do PUT operation if `last_acked_sn != tx.sn` in EP
2. Fix EP flush conditions when checking resources. Return `UCS_OK` if connection has already been closed.
3. Fix tests.
=> UCT/TCP: Implement flush of all outstanding operations

src/ucp/core/ucp_worker.c
Print xpmem lane when it is used
Better debugging experience:
Now it is shown (when selected ) with info log level
`[1628016549.696474] [swx-dgx03:75816:0]      ucp_worker.c:1810 UCX  INFO    ep_cfg[0]: tag(posix/memory xpmem/memory cma/memory);`
=> UCP/TAG/AM: Print xpmem lane when it is used

src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
backport of #7140 PR to v1.11.x branch to be included in 1.11.1 release version
Implement flush of all outstanding operations.
To fix `uct_ep_flush()` which don't wait for all operations being completed. As a result if fixes the following case:
```
/* client */
for (i= 0; i < 1000; ++i) { 
req = ucp_ep_tag_send_nb(ep)
reqs.push_back(req);
}
wait_for_reqs(reqs);
req = ucp_ep_close_nb(ep, FLUSH);
wait_for_req(req);
exit(0);
```
```
/* server */
for (i = 0; i < 1000; ++i) {
req = ucp_worker_tag_recv_nb(worker);
reqs.push_back(req);
}
wait_for_reqs(reqs);
/* 998-999 completed successfully, but 1-2 completed with error  */
```
1. Do PUT operation if `last_acked_sn != tx.sn` in EP
2. Fix EP flush conditions when checking resources. Return `UCS_OK` if connection has already been closed.
3. Fix …
=> UCT/TCP: Implement flush of all outstanding operations [v1.11.x]

src/uct/ib/dc/dc_mlx5_devx.c
backport of #7132 
Set traffic class for RoCE, because:
it is used by v1
some FW versions rely on it even for RoCE v2
=> UCT/DC: Set tclass for RoCE in dct - v1.11.x

src/ucs/sys/sock.c
Fix printing message about number of FDs limit exceeded.
UCS expected to print more information in case number of files limit exceeded, but it doing `ucs_error()` prior checking `errno == EMFILE` in `ucs_socket_print_error_info()`, doesn't work.
Now it prints:
```
[1628073207.539411] [swx-ucx03:51150:0]            sock.c:50   UCX  ERROR socket create failed: the maximal number of files that could be opened simultaneously was reached, try to increase the limit by setting the max open files limit (ulimit -n) to a greater value (current: 1024)
```
instead of:
```
[1628067927.627923] [swx-ucx03:41937:0]            sock.c:140  UCX  ERROR socket create failed: Too many open files
```
Print error message in `ucs_socket_print_error_info()` only for `ucs_socket_create()`/`ucs_socket_accept()`. So, …
=> UCS/SYS/SOCK: Fix printing number of FDs limit exceeded message

src/ucm/bistro/bistro_x86_64.c
Newer Cuda versions (11.3) add debug hooks prefix to driver API functions. This patch fixes installing bistro memory hooks on them.
=> UCM/BISTRO: Parse libcuda debug hooks

src/ucm/bistro/bistro_x86_64.c
=> UCM/BISTRO: Parse libcuda debug hooks - v1.11.x

src/ucp/api/ucp.h, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, test/gtest/ucp/test_ucp_worker.cc
Add query routine for ucp worker address. The only available parameter for now is worker unique ID   
The process may need to know the identificator of its peer. With this routine it is possible to get unique id of the remote process.
Can be useful for various profiling tools.
=> UCP/API: Add ucp_worker_address_query routine

contrib/test_jenkins.sh, src/ucm/api/ucm.h, src/ucm/bistro/bistro_x86_64.c, src/ucm/cuda/cudamem.c, src/ucm/util/sys.c, src/ucs/config/ucm_opts.c
Follow-up on #7195 , which added support for "cmpl $imm32,$disp32(%rip)" but copying this instruction as-is readers it unusable. It has to be translated to use the right address instead of rip-related offset.
=> UCM/BISTRO/TEST: Fix support for cuda memory hooks

contrib/test_jenkins.sh, src/ucm/api/ucm.h, src/ucm/bistro/bistro_x86_64.c, src/ucm/cuda/cudamem.c, src/ucm/util/sys.c, src/ucs/config/ucm_opts.c
Backporting #7204 as it fixes a critical issue with Cuda memory hooks with 11.3/4
Fixes #7210
=> UCM/BISTRO/TEST: Fix support for cuda memory hooks - v1.11.x

NEWS
Update NEWS file with bugfixes on v1.11.x branch
=> NEWS: Update v1.11 news

test/gtest/ucp/test_ucp_wireup.cc
The PR fixes setting EP params in UCP wireup keepalive test suite.
No need to overwrite EP params from base test suite.
1. Remove `memset(&params, 0, sizeof(params));` at the beginning of the function.
2. Assign `field_mask` field of `ucp_ep_params_t` by ORing values.
=> GTEST/UCP/WIREUP: Don't overwrite EP params from base test suite

contrib/check_qps.sh
Introduce QP check script which finds QPs that are stuck.
To find QPs which are stuck, i.e. `ci != pi` and `ci` wasn't increased from the first run.
e.g.:
```
$ PRINT_ALL_QPS=yes QP_CHECK_INTERVAL=1 ~/work_auto/ucx/contrib/check_qps.sh
...
qp=0xaae7: pi=65535 ci=65535 initial_ci=65535 - ok
qp=0x19527: pi=36687 ci=36677 initial_ci=48895 - ok
qp=0xaa48: pi=65535 ci=65535 initial_ci=65535 - ok
qp=0x1955b: pi=56554 ci=56522 initial_ci=56522 - stuck (path=/tmp/ucx/62136/uct/worker/0x766d40/iface/0x78af00/dci_pool/0/7)
qp=0x194ff: pi=62989 ci=62989 initial_ci=62959 - ok
qp=0x195c8: pi=23262 ci=23262 initial_ci=23262 - ok
...
```
1. Goes over `/tmp/ucx` VFS directory and trying to find TXWQ directory which contains `qp_num`, `hw_ci`, `prev_sw_pi` files (only DC is supported now, since RC/UD …
=> CONTRIB: Introduce QP check script

test/apps/iodemo/run_io_demo.sh
add tag all_clients / all_servers stop/start for run_io_demo.sh for start/stop
manually manage kill clients and servers
=> IODEMO: add tag all_clients / all_servers stop/start for run_io_demo.sh

buildlib/az-distro-release.yml, buildlib/azure-pipelines-release.yml, buildlib/dockers/centos-release.Dockerfile, buildlib/dockers/centos8-release.Dockerfile, buildlib/dockers/docker-compose.yml, buildlib/jucx/jucx-publish.yml
The UCX community releases:
We are dropping support for CUDA 10.x.
WRT to the OS’s, the released builds will remain as they are now (rpm/deps) – for example - https://github.com/openucx/ucx/releases
(other than dropping cuda10 support and the renaming in bullet #4)
The naming will change to reflect backwards compatibility for MLNX_OFED 5.x and CUDA 11.x.
For example - ucx-v1.11.0-ubuntu18.04-mofed5-cuda11.deb
=> AZP/RELEASE: Release matrix

src/ucs/debug/log.c
Don't call fsync for stdout/stderr.
To avoid errors shown from `strace`
```
$ strace ucx_info -eptw -u tra
...
rt_sigaction(SIGSEGV, {SIG_DFL, [], SA_RESTORER, 0x7fdc7fb315d0}, {0x7fdc804d492b, [], SA_RESTORER|SA_STACK|SA_SIGIN│  PID TTY          TIME CMD
FO, 0x7fdc7fb315d0}, 8) = 0                                                                                         │47146 pts/1    00:00:00 pdsh
rt_sigaction(SIGILL, {SIG_DFL, [], SA_RESTORER, 0x7fdc7fb315d0}, {0x7fdc804d492b, [], SA_RESTORER|SA_STACK|SA_SIGINF│  PID TTY          TIME CMD
O, 0x7fdc7fb315d0}, 8) = 0                                                                                          │47146 pts/1    00:00:00 pdsh
rt_sigaction(SIGBUS, {SIG_DFL, [], SA_RESTORER, 0x7fdc7fb315d0}, {0x7fdc804d492b, [], …
```
=> UCS/LOG: Don't call fsync for stdout/stderr

test/apps/iodemo/io_demo.cc
Add debug mode which allows debugging connections which are stuck.
To be able find QPs which are stuck or attach to a process when IO-demo application detects "timeout waiting for <N> replies"
1. Introduce new argument `-D`.
2. If "timeout waiting for <N> replies" is detected, and `-D` is set, don't destroy connections which are stuck (just call `progress()`)
=> APPS/IO-DEMO: Add debug mode which allows debugging connections which are stuck

src/uct/ib/rc/accel/rc_mlx5_iface.c
Fail to create interface if user specifies invalid IB segment.
Segment size is limited by 2 bytes in `rc_mlx5` and `dc` transports. 
To have a clear error message when user sets invalid value rather than segfault
=> UCT/RCX/DC: Do not allow to set invalid IB segment size

contrib/check_qps.sh
Update check_qps script to check RC QPs.
To find possible stuck RC QPs using VFS instrumentation.
Introduce new globbing path for RC EPs: `/tmp/ucx/*/uct/worker/*/iface/*/ep/*`
=> CONTRIB: Update check_qps script to check RC QPs

test/gtest/ucp/test_ucp_tag.cc
Remove extra initialization of param `user_data` fields
=> UCP/GTEST: Remove extra initialization of param fields

src/uct/ib/rc/accel/rc_mlx5.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs.h, src/uct/ib/rc/verbs/rc_verbs_ep.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
Print EP info using VFS instrumentation.
It is needed for better debugging and will be used by #7205.
e.g.:
```
tree /tmp/ucx/*/uct/worker/*/iface/*/ep/*/
...
/tmp/ucx/64267/uct/worker/0x109d7e0/iface/0x114e080/ep/0x11f8d20/
├── available
├── bb_max
├── hw_ci
├── prev_sw_pi
├── qend
├── qp_num
├── qstart
├── sig_pi
├── sw_pi
└── unsignaled
/tmp/ucx/64267/uct/worker/0x109d7e0/iface/0x114e080/ep/0x123a2d0/
├── available
├── bb_max
├── hw_ci
├── prev_sw_pi
├── qend
├── qp_num
├── qstart
├── sig_pi
├── sw_pi
└── unsignaled
...
```
Introduced `uct_rc_mlx5_iface_vfs_refresh()` and `uct_rc_verbs_iface_vfs_refresh()` to go over all EPs on a specific IFACE and print TXQP and TXWQ (mlx5) or QP number only (verbs) information.
=> UCT/IB/RC: Print EP info using VFS instrumentation

src/ucp/proto/proto.h, src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_reconfig.c, src/ucp/proto/proto_select.c, src/ucp/proto/proto_select.h, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/proto_rndv.h, src/ucp/rndv/rndv_get.c
Add performance calculation infra for rndv pipeline protocol. Each protocol should estimate its own "pipelined" performance, so we can estimate the overall performance of sending sub-protocols such as rndv-put-frag or rndv-get-frag in a pipelined fashion.
=> UCP/PROTO: Calculate protocol pipelined performance

src/ucp/core/ucp_context.c, src/ucs/sys/sock.c
- Print UCP version with log level info.
- Reduce log level for `failed to read ... assuming 802.3ad bonding is disabled` to avoid logs flooding.
Better debug experience
=> UCP/UCS: Print UCP version and reduce log level for bond init error

contrib/test_jenkins.sh, examples/hello_world_util.h, examples/ucp_hello_world.c, examples/uct_hello_world.c, src/ucp/core/ucp_ep.c, src/uct/tcp/tcp_ep.c
As a result of #7140, ucp_hello_world fails in docker when it uses TCP transport, like this:
```
2021-08-10T19:42:56.9329573Z + taskset -c 0 ./examples/ucp_hello_world -f -m host -p 16001
2021-08-10T19:42:56.9651931Z INFO: UCP_HELLO_WORLD mode = 2 server = (null) port = 16001, pid = 20460
2021-08-10T19:43:11.9295628Z + '[' 0 -eq 1 ']'
2021-08-10T19:43:11.9304753Z + client_pid=20476
2021-08-10T19:43:11.9305794Z + wait 20476
2021-08-10T19:43:11.9307301Z + taskset -c 1 ./examples/ucp_hello_world -f -m host -n 0231793f6e3f -p 16001
...
2021-08-10T19:43:12.0205215Z [0231793f6e3f:20476:0:20476]      ucp_ep.c:2822 Assertion `ucp_ep_config(ep)->key.err_mode != UCP_ERR_HANDLING_MODE_NONE' failed
2021-08-10T19:43:12.0206896Z ==== backtrace (tid:  20476) ====
2021-08-10T19:43:12.0208701Z  0 …
```
=> TCP/TEST: Fix simultaneous ep close with ucp_hello_world

src/ucm/cuda/cudamem.c, src/ucp/core/ucp_context.c, src/uct/cuda/base/cuda_iface.h, src/uct/cuda/base/cuda_md.c, src/uct/cuda/cuda_copy/cuda_copy_md.c, src/uct/cuda/cuda_copy/cuda_copy_md.h, test/gtest/ucm/cuda_hooks.cc, test/gtest/ucm/malloc_hook.cc, test/gtest/ucs/test_memtype_cache.cc
- T4 GPUs have smaller bar1 space so registering whole allocations increases changes of IB reg failures
- So we detect device name and disable whole registration
=> UCT/CUDA: Disable whole alloc reg if T4 GPUs detected

src/ucp/Makefile.am, src/ucp/dt/datatype_iter.inl, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.inl, src/ucp/proto/proto_single.inl, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_rcv.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/offload/eager.c, src/ucp/tag/proto_eager.inl, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_send.c, test/gtest/ucp/test_ucp_dt.cc, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_xfer.cc
- Enable rndv on non-contig data
- Enable more tests for new protocols and fix related issues
=> UCP/PROTO: Enable test_tag_xfer on new protocol and fix related issues

buildlib/az-helpers.sh
Detect missing GPU-direct driver
=> AZP: Fail if running on a GPU machine without GPU-direct driver

src/uct/base/uct_iface.c
1. Set dirty iface VFS object when creating EP.
2. Add cleanup of EP VFS object.
1. To update EPs when visiting of an IFACE directory was done even before creating EPs.
2. To remove EP directory for EP which isn't valid anymore.
1. Update `uct_ep_create()` function to call `ucs_vfs_obj_set_dirty()` for IFACE and set `uct_iface_vfs_refresh()` refresh function.
2. Update `uct_ep_destroy()` function to call `ucs_vfs_obj_remove()` for EP object.
=> UCT/BASE: Set dirty iface VFS object when creating EP and add cleanup of EP VFS object

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/core/ucp_worker.inl, src/ucs/Makefile.am, src/ucs/datastruct/ptr_map.c, src/ucs/datastruct/ptr_map.h, src/ucs/datastruct/ptr_map.inl, src/uct/tcp/tcp.h, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, test/gtest/ucs/test_datatype.cc
Converted ptr_map implementation to macros.
Implemented thread safe put operation. Other operations are not thread safe.
Added gtest.
The changes are required to fix retrieving endpoint from worker using endpoint's id.
=> UCS/DATASTRUCT: Thread safe put to ptr_map.

test/apps/iodemo/io_demo.cc
Check status when retrying listening.
To stop Server process when receiving SIGINT when retrying listening.
Check `_status == OK` in listening retry loop.
=> APPS/IO-DEMO: Check status when retrying listening

src/ucp/api/ucp.h, src/ucp/proto/proto_select.c, src/ucp/proto/proto_select.h, src/ucp/proto/proto_select.inl
- On API layer, add hints for protocol selection
- Internally, this flag will be used for RNDV pipeline protocols - to prefer staging protocols even though they have higher latency
=> UCP/API: Add request flag to influence latency vs. bandwidth protocol

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
1. Cancel connection establishment if disconnecting.
2. Destroy all connections in UCxContext dtor to remove them from lists.
1. To fix the following assertion:
```
[1628505026.738032] [DEMO] disconnecting [UCX-connection 0x254b1c0: #147 1.1.28.5:20011] read 0/0 write 0/0 due to "End of the Client run"
io_demo: ucx_wrapper.cc:784: void UcxConnection::disconnect(UcxCallback*): Assertion `_establish_cb == __null' failed.
```
2. To fix the following assertion:
```
[1628619045.774204] [UCX] removed [UCX-connection 0x20f7610: #208 1.1.28.3:20011] from connection map
io_demo: ucx_wrapper.cc:786: void UcxConnection::disconnect(UcxCallback*): Assertion `_disconnect_cb == __null' failed.
```
1. If connection isn't established yet, call `established(UCS_ERR_CANCLED)` to free memory stored in …
=> APPS/IO-DEMO: Cancel connection establishment if disconnecting

src/ucp/core/ucp_request.c, src/ucp/core/ucp_worker.c, src/ucs/datastruct/mpool.c, src/ucs/datastruct/mpool.h, src/ucs/datastruct/string_buffer.c, src/ucs/datastruct/string_buffer.h, src/ucs/memory/rcache.c, src/uct/base/uct_mem.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/ib/mlx5/dv/ib_mlx5dv_md.c, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/ib/rc/base/rc_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c, src/uct/sm/scopy/base/scopy_iface.c, src/uct/sm/self/self.c, src/uct/tcp/tcp_iface.c, src/uct/ugni/base/ugni_iface.c, src/uct/ugni/rdma/ugni_rdma_iface.c, src/uct/ugni/smsg/ugni_smsg_iface.c, src/uct/ugni/udt/ugni_udt_iface.c, test/gtest/ucs/test_mpool.cc, test/gtest/ucs/test_string.cc
When memory pool object leaks, it's useful to know more details to understand why the object wasn't released
=> UCP/MPOOL: Detailed mpool leak check

src/ucp/rma/amo_basic.c, src/ucp/rma/amo_sw.c, src/ucp/rma/rma_sw.c
The error code returned by `req->send.uct.func()` is not `UCS_OK`, `UCS_INPROGRESS` and `UCS_ERR_NO_RESOURCE`, that cause process aborts.
https://github.com/openucx/ucx/blob/797596d8582b85434129b5795405999983f5e5de/src/ucp/core/ucp_request.inl#L318
In my case, TCP Iface is used to simulate RMA, and it returns `UCS_ERR_CONNECTION_RESET`.
The following code assumes that only three error codes will be returned, and other error codes will cause fatal.
https://github.com/openucx/ucx/blob/797596d8582b85434129b5795405999983f5e5de/src/ucp/core/ucp_request.inl#L312-L331
`UCS_OK` should be returned when the request fails not because there are no resources.
=> UCP/RMA: Return UCS_OK when status != UCS_ERR_NO_RESOURCE

contrib/test_jenkins.sh, src/ucp/core/ucp_ep.c, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/ucs/time/time.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, test/gtest/uct/test_peer_failure.cc
Backport #7254 and #7271 to v1.11.x
Conflicts: 
- In uct_iface.c on v1.11.x, there is no uct_operation_names array after uct_base_ep_error_handle_info_t
- No additional merge conflicts
=> Port keepalive fixes to v1.11.x branch

examples/ucp_client_server.c, src/ucp/core/ucp_am.c
Set `user_hdr` to `NULL` if `user_hdr_size` is 0. Verify it in `ucp_client_server`.
Current behavior is a bug.
=> UCP/CORE: Do not fill user_hdr in AM handler when length is 0

ucx.spec.in
Fix UCX RPM install issue during kickstart if 'coreutils' not installed yet
Internal issue [link](https://redmine.mellanox.com/issues/2780194)
=> RPM/POST: Don't create $sysconfdir/ucx at post-install step

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc
Don't do IO operations on failed connection.
Doing IO operations on failed connections don't have any effect, it reports errors and can lead to "Have min:0 ..." since it is trying to send data on failed connection and don't reconnect on it and don't report performance.
1. Move removing from `active_servers` list to `disconnect_server()` function instead of `DisconnectCallback`.
2. Add assertions to check that no IO operations done on failed connections.
3. Add `progress()` to the `DemoClient::run()` loop in order to progress failed connections - it is needed to progress disconnection and make them connected then (no performance degradations seen, the following operations and message sizes are checked: 4k read/write, 32k read/write, 64k read/write).
=> APPS/IO-DEMO: Don't do IO operations on failed connection

src/ucp/core/ucp_ep.c, src/ucp/stream/stream.h, src/ucp/stream/stream_recv.c
So that stream receive callback will have the endpoint failure status
=> UCP/STREAM: Pass endpoint failure status to stream receive completion

src/ucp/rma/flush.c, src/ucp/wireup/wireup.c
When have retry exceeded when while sending EP_REMOVED, it's not on a particular connection, so it may be missed
=> UCP/WIREUP: Print diagnostic message when failed to send EP_REMOVED

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/ep_match.c, src/ucp/wireup/ep_match.h, src/ucp/wireup/wireup.c, src/ucs/datastruct/conn_match.c, src/ucs/datastruct/conn_match.h, src/uct/ib/ud/base/ud_iface.c, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_iface.c, test/gtest/ucs/test_conn_match.cc
Introduce maximum connection sequence number after which connection matching is disabled.
Some applications may want to support creating large number of connections even without connection matching, e.g. it makes sense, if they create more than 65534 connections to the same peer from one UCP context.
1. Introduce maximum connection sequence number after which connection matching is not done.
2. Provided supported maximum connection sequence number in UCP, TCP and UD.
3. If maximum connection sequence number is reached on UD or TCP - abort.
4. Handle connection matching in UCP according to updated connection API to support working without connection matching.
=> UCS/UCP/UCT: Introduce maximum conn_sn after which conn_match isn't done

src/ucs/debug/log_def.h
- there was undefined log level used in non-defined log level
=> LOGGING: fixed potential build issue

test/apps/iodemo/ucx_wrapper.cc
Track stream request for sending connection ID.
`UcxConnection` connections (and as a result UCP endpoints) could be closed without waiting `ucp_ep_stream_send_nb` request completion, which could lead to undefined behavior and warning about unreleased `ucp_request_t` object to mpool.
1. In `UcxConnection::connect_tag()` method: if `sreq` is a pointer, save it to connection's list of requests by calling `process_request()`.
2. In `UcxConnection::stream_send_callback` completion callback: complete and release the request.
=> APPS/IO-DEMO: Track stream request for sending connection ID

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Improve assertion of send/completed bytes in server_info.
To improve debugging of issues related to `bytes_sent`/`bytes_completed`.
1. Update `commit_operation()` to check that `bytes_completed < bytes_sent` if no zero-length operations are allowed and otherwise - `bytes_completed <= bytes_sent`.
2. Update `handle_operation_completion()` to check that `bytes_completed == bytes_sent` if no uncompleted operations and otherwise - if no zero-length operations are allowed, then `bytes_completed < bytes_sent`, else - `bytes_completed <= bytes_sent`.
=> APPS/IO-DEMO: Improve assertion of send/completed bytes in server_info

src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_rkey.h, src/ucp/rma/amo_send.c, src/ucp/rma/rma.h, src/ucp/rma/rma_send.c, src/ucs/sys/compiler_def.h, test/gtest/common/test_obj_size.cc, test/gtest/ucp/test_ucp_mmap.cc
Reduces `ucp_rkey_t` from 64 to 40 bytes.
Allows reducing mem consumption by approximately 30%.
- reordering of structure fields
- using protocols indexes instead of pointers {amo|rma}_proto
UPD: removed `max_put_short` that reduces rkey to 32 bytes.
=> UCP/RKEY: optimizes memory consumption of ucp_rkey_t

test/gtest/ucp/test_ucp_rma_mt.cc, test/gtest/ucp/test_ucp_tag_mt.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h, test/gtest/uct/test_peer_failure.cc
Fix failures in gtest when running on 28-core machine with 2 RDMA NICs:
<details>
<summary>
`make -C build-devel/test/gtest test GTEST_FILTER=rc_mlx5/test_uct_peer_failure_multiple.test*:shm_ib/test_ucp_rma_mt.put_get*:shm_ib/test_ucp_tag_mt.send_recv*`
</summary>
<p>
```
[     INFO ] ugni is not available
[     INFO ] ugni,cuda_copy,rocm_copy is not available
[     INFO ] Using random seed of 20954
Note: Google Test filter = rc_mlx5/test_uct_peer_failure_multiple.test*:shm_ib/test_ucp_rma_mt.put_get*:shm_ib/test_ucp_tag_mt.send_recv*
Note: Randomizing tests' orders with a seed of 95248 .
[==========] Running 10 tests from 3 test cases.
[----------] 4 tests from shm_ib/test_ucp_tag_mt
[ RUN      ] shm_ib/test_ucp_tag_mt.send_recv/0 …
```
=> TEST/GTEST: Don't open too many files

test/apps/iodemo/io_demo.cc
Use C-string constant instead of std::string.
To not pay for memory allocation/release on a heap, since `check_counters()` method is called on data path.
`std::string_view` couldn't be used, since C++17 is not used by UCX.
Replce `const std::string&` by `const char*`.
=> APPS/IO-DEMO: Use C-string constant instead of std::string

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c
Fix this:
```
Assertion `(now - ucp_ep_ext_control(ep)->ka_last_round) >= worker->context->config.ext.keepalive_interval'
```
As a result of https://github.com/openucx/ucx/pull/7301, we can restart an active keepalive round which leads to this assertion.
This PR will make sure that if we are during a keepalive round and iter reached end - the round will be finished, and we are not during a round - no action will be taken.
=> UCP/KEEPALIVE: Fix assertion that keepalive done too soon on same ep

src/ucp/core/ucp_ep.c
Allow calling user's error callback when error mode is NONE.
To not catch the following assertion:
```
[ddf9089ce11d:20961:0:20961]      ucp_ep.c:2833 Assertion `ucp_ep_config(ep)->key.err_mode != UCP_ERR_HANDLING_MODE_NONE' failed
==== backtrace (tid:  20961) ====
0  /__w/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_handle_error+0x13c) [0x7f8c7a4f4adc]
1  /__w/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_fatal_error_message+0x58) [0x7f8c7a4f1878]
2  /__w/1/s/build-test/src/ucs/.libs/libucs.so.0(ucs_fatal_error_format+0xd1) [0x7f8c7a4f1a01]
3  /__w/1/s/build-test/src/ucp/.libs/libucp.so.0(ucp_ep_invoke_err_cb+0x1cb) [0x7f8c7a1db6eb]
4  /__w/1/s/build-test/src/ucp/.libs/libucp.so.0(ucp_ep_set_failed+0x1f2) [0x7f8c7a1e05c2]
5  /__w/1/s/build-test/src/ucp/.libs/libucp.so.0(+0x4f3da) …
```
=> UCP/CORE: Allow calling user's error callback when error mode is NONE

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc
Don't validate msg if connection failed.
The message may be incomplete.
1. Move calling `validate()` method under `UcxConnection::ucx_status() == UCS_OK` check.
2. Replace checking `server_index < _server_info.size()` by assertion, where `server_index` is the result of `get_active_server_index(conn)`.
=> APPS/IO_DEMO: Don't validate msg if connection failed

test/gtest/ucs/test_async.cc, test/gtest/ucs/test_class.cc
Don't use "base" for type names.
Fixes #7329 
1. Rename "base" class to "base_async" in ucs/test_class.cc.
2. Remove "base"/"derived"/"derived2", since they can use only typedef version of it - "base_t"/"derived_t"/"dervied2_t"
=> GTEST/UCS: Don't use base type name

examples/ucp_client_server.c, src/ucp/api/ucp_def.h, src/ucp/core/ucp_am.c
Revert to filling `user_hdr`, even if the header length is 0.
Avoid extra branch.
=> UCP/API: Revert "UCP/CORE: Do not fill user_hdr in AM handler when length is 0"

src/ucp/core/ucp_worker.c
Increment completion count before calling `uct_ep_flush()`.
Fixes the following assertion in UD EP flush which expects that the completion counter > 0.
```
[swx-ucx02:54317:0:54317]       ud_ep.c:1001 Assertion `comp->count > 0' failed
[1630582789.248645] [swx-ucx02:54303:0]          ucp_ep.c:1107 UCX  ERROR ep 0x7fba25d451c8: error 'Destination is unreachable' on NULL lane will not be handled since no error callback is installed
[1630582789.248588] [swx-ucx02:54317:0]          ucp_ep.c:1107 UCX  ERROR ep 0x7ff6b2f2c098: error 'Destination is unreachable' on NULL lane will not be handled since no error callback is installed
/labhome/dmitrygla/work_auto/ucx/src/uct/ib/ud/base/ud_ep.c: [ uct_ud_ep_flush_nolock() ]
...
998      * released when the current sequence number is completed.
999 …
```
=> UCP/CORE: Increment completion count before calling uct_ep_flush

test/gtest/ucp/test_ucp_stream.cc
Use `std::string::size_type` instead of `size_t`.
To align with other places in our C++ code:
https://github.com/openucx/ucx/blob/3e4ed2735ef4b34b3e52fb51a09f9188bf5720ca/test/gtest/common/test.cc#L61
Also, it is useful if some `std::string` implementation uses other type than `size_t` for `std::string::npos` constant.
Replace size_t by `std::string::size_type`.
=> GTEST/UCP: Use std::string::size_type instead of size_t

src/uct/sm/mm/xpmem/mm_xpmem.c
Avoid excessive errors in case of abnormal termination
=> UCT/XPMEM: Reduce log level of leaked xpmem segments

src/uct/sm/scopy/base/scopy_iface.c, src/uct/sm/scopy/base/scopy_iface.h, src/uct/sm/scopy/cma/cma_iface.c, src/uct/sm/scopy/knem/knem_iface.c
Move overhead of iface_attr from CMA/KNEM to common code
To reduce code duplication, because overhead of CMA and KNEM are identical.
1. Remove setting of overhead attribute in CMA and KNEM iface_query implementation.
2. Add setting of overhead attribute in SCOPY iface_query implementation which is called from CMA and KNEM.
=> UCT/SCOPY: Move overhead of iface_attr from CMA/KNEM to common code

src/ucp/wireup/wireup.c
Replace returning "Unreachable" error by assert if lane exists during connect.
Catch sooner a problem with EP reconfiguration code.
It is rather bug when UCT EP is set to some lane, since this shouldn't happen:
- connect through CM: intersection logic should update lanes according to the old/new configuration.
- connect through Worker address: "reconfiguration" bug fatal error must be printed.
1. Replace check for `(ep->uct_eps[lane] != NULL) && !ucp_wireup_ep_test(ep->uct_eps[lane])` and returning `UCS_ERR_UNREACHABLE` by `ucs_assertv_always()`.
2. Remove `ucs_assert(cm_wireup_ep != NULL);` assertion since the function has the check above.
=> UCP/WIREUP: Replace returning Unreachable error by assert if lane exists during connect

src/ucp/wireup/address.h, src/ucp/wireup/select.c
Handle address count > 64.
To fix using UCX out of the box on large nodes, e.g NVIDIA DGX A100, where the number of resources is bigger than 64. And as result, the number of address entries is bigger than 64.
```
...
#
#
[1630939198.390763] [node01:683504:0]          wireup.c:1061 UCX  ERROR   old: am_lane 0 wireup_msg_lane 3 cm_lane <none> reachable_mds 0x1ffff ep_check_map 0x0
[1630939198.390802] [node01:683504:0]          wireup.c:1082 UCX  ERROR   old: lane[0]:  2:self/memory0.0 md[2]          -> md[2]/self/sysdev[255] am am_bw#0
[1630939198.390808] [node01:683504:0]          wireup.c:1082 UCX  ERROR   old: lane[1]:  0:posix/memory.0 md[0]          -> md[0]/posix/sysdev[255] rkey_ptr
[1630939198.390813] [node01:683504:0]          wireup.c:1082 UCX  ERROR   old: lane[2]: …
```
=> UCP/WIREUP: Handle address count > 64

src/uct/ib/ud/base/ud_def.h, src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_ep.h, src/uct/ib/ud/base/ud_log.c
Align negative-ack packet flag name with other flags.
It is easier to find code related to negative-ack and also it aligns with other flags (e.g. `UCT_UD_EP_FLAG_TX_NACKED`)
1. Replace `UCT_UD_PACKET_FLAG_NAK` by `UCT_UD_PACKET_FLAG_NACK`.
2. Fix all occurrences.
3. Fix comments where negative-ack is mentioned.
=> UCT/IB/UD/BASE: Align negative-ack packet flag name with other flags

src/ucs/time/timerq.c
- there was unpaired malloc/free on timerq buffer
- fixed
=> UCS/TIMERQ: fixed buffer release

src/uct/ib/base/ib_device.c
Handle SM_CHANGE/CLIENT_REREGISTER async events as diagnostics.
[1630842634.549719] [node01:33913:1]      ib_device.c:482  UCX  WARN  IB Async event on mlx5_0: client reregistration on port 1
[1630842635.421273] [node01:33913:1]      ib_device.c:482  UCX  WARN  IB Async event on mlx5_0: client reregistration on port 1
Move `IBV_EVENT_SM_CHANGE`/`IBV_EVENT_CLIENT_REREGISTER` to the case where we print diagnostic instead of warning.
=> UCT/IB/BASE: Handle SM_CHANGE/CLIENT_REREGISTER async events as diagnostics

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h
- added obj_str implementation for send-ops mpool to simplify
resource leaks investigation
=> IB/SEND-OPS/STR: added obj-str implementation

src/ucp/api/ucp_def.h
Remove "Can be NULL" from documentation of `header` in AM callback
See https://github.com/openucx/ucx/pull/7333#discussion_r702289041
=> UCP/API: Improve documentation

src/ucp/rndv/rndv.h
remove UCP_RNDV_RTS_TAG_CANCELED
cleanup not used code
=> UCP/TAG: remove UCP_RNDV_RTS_TAG_CANCELED

src/ucs/config/parser.c, src/ucs/stats/client_server.c, src/uct/rocm/ipc/rocm_ipc_cache.c, src/uct/sm/scopy/knem/knem_md.c, src/uct/ugni/base/ugni_md.c
- use UCS allocators for parser and client/server stats
- fixed potential ucs/malloc/free calls in error handlers
=> UCS/MALLOC/FREE: use UCS allocators

src/ucp/wireup/address.c
Do not fail if address version is not exactly the same
These version bits can be used for packing optional extensions
=> UCP: Remove UCP address version restriction

test/gtest/uct/test_md.cc, test/gtest/uct/test_tag.cc
1. Don't use `ucs::ptr_vector`'s methods for manipulating with `std::vector`.
2. Use ptr_vector where possible.
1. Using `ucs::ptr_vector`'s methods for `std::vector` is possible, but make code unclear.
2. Use `ucs::ptr_vector` instead of `std::vector` to not take care of objects allocated and added to the vector.
1. Replace `ucs::ptr_vector<void>::const_iterator` by `std::vector<void>::const_iterator`.
2. Remove `std::for_each` which calls `free()` for all objects, and use declare buffers as `ucs::ptr_vector` instead of `std::vector`.
=> GTEST/UCT: Don't use ptr_vector's method for std::vector, use ptr_vector where possible

src/ucs/arch/aarch64/cpu.h
Suppress the warning about set but never used variable
Fixes #7371
Use `UCS_V_UNUSED` attribute for `tmp` variable declaration in`ucs_arch_wait_mem()` function.
=> UCS/ARCH/AARCH64: Suppress warning about set but never used variable

src/ucp/core/ucp_ep.c, test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc
1. Add assertion for connection status.
2. Set `status` for `ucx_request` objects when handling UCP Stream receive operations.
1. 
2. Ensure that stream receive operation status reflects correct
before:
```
[1630617673.417183] [UCX-connection 0xdc1d90: #101 2.1.3.4:20009] completing conn_id receive request 0xfc64d8 with status "Success" (0) during disconnect
```
after:
```
[1631102046.926942] [UCX-connection 0x1fe2630: #163 2.1.3.11:20017] completing conn_id receive request 0x2407998 with status "Endpoint is not connected" (-24) during disconnect
```
1. Add assertions:
- `status` must be error in `ucp_ep_set_failed()`.
- `status` must be `UCS_OK` when handling receive operations.
2. Set `status` for `ucx_request` objects in `UcxConnection::stream_recv_callback()` callback.
=> APPS/IO-DEMO/UCP: Add assertion for connection status

test/gtest/ucs/test_rcache.cc
Reduce testing time by decreasing number of pages checked in rcache pfn test when running under valgrind.
To reduce testing time.
before:
```
[ RUN      ] test_rcache_pfn.enum_pfn <> <>
[    PAGES ] 1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536
[       OK ] test_rcache_pfn.enum_pfn (181494 ms)
[----------] 1 test from test_rcache_pfn (181508 ms total)
[==========] 1 test from 1 test case ran. (181625 ms total)
[  PASSED  ] 1 test.
```
after:
```
[ RUN      ] test_rcache_pfn.enum_pfn <> <>
[    PAGES ] 1 2 4 8 16
[       OK ] test_rcache_pfn.enum_pfn (107 ms)
[----------] 1 test from test_rcache_pfn (119 ms total)
[==========] 1 test from 1 test case ran. (224 ms total)
[ …
```
=> GTEST/UCS: Reduce rcache pfn test runtime under valgrind

src/tools/perf/perftest.c
Don't check the received message if receive failed during barrier.
Fixes the following assertion failed:
```
+--------------+--------------+------------------------------+---------------------+-----------------------+
|              |              |       overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+----------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | 50.0%ile | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+----------+---------+---------+----------+----------+-----------+-----------+
[1631303657.809706] [bf2-smc-02-01:10881:0]        perftest.c:129  UCX  ERROR recv() failed: Connection reset by peer …
```
=> TOOLS/PERF: Don't check the received message if recv failed

src/uct/base/uct_md.c, src/uct/base/uct_md.h, src/uct/ib/rc/accel/rc_mlx5_common.c, src/uct/sm/self/self.c
Remove component name from UCT rkey (which is present in debug mode only)
align with release version format and facilitate potential extensions
=> UCT: Remove component name from rkey

src/uct/ib/dc/dc_mlx5_ep.c
- fixed resource leak in error handling: object send_op was
leaked when fc grant operation was re-scheduled
=> DC/MLX5/FC: fixed resource leak

test/gtest/uct/test_tag.cc
Replace iterating over `std::vector` by `std::for_each`.
It looks simpler and less error-prone.
Remove `for(...)` and use `std::for_each()` instead.
=> GTEST/UCT: Replace iterating over std::vector by std::for_each

contrib/test_jenkins.sh, src/ucp/core/ucp_context.c, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/parser.c, src/ucs/config/parser.h, src/ucs/stats/stats.c, src/ucs/sys/module.c
Allow disabling some of the loadable modules by a configuration parameter, to prevent undesired initialzation.
For example, `UCX_MODULES=^cuda` would disable loading cuda modules.
=> UCS/CONFIG: Allow-list for loadable modules

src/ucp/core/ucp_mm.h, src/ucp/dt/datatype_iter.c, src/ucp/dt/datatype_iter.h, src/ucp/dt/datatype_iter.inl, src/ucp/rndv/proto_rndv.inl, test/gtest/ucp/test_ucp_proto.cc
With new protocols no need to check all the things we check in the rereg_mds() function. We can assume registration is needed and supported, and that no prior registration was done.
=> UCP/DATATYPE: Reduce memory reg/dereg overhead for new protocols

test/gtest/ucs/test_conn_match.cc
Reduce testing time of conn_match under valgrind.
Check only 5 connections and up to 5 addresses instead of 128 when the test running under valgrind.
It reduces testing time.
before:
```
[ RUN      ] tcp/test_ucp_stream.send_zero_ending_iov_recv_data/0 <tcp>
==168595== WARNING: valgrind ignores shmget(shmflg) SHM_HUGETLB
[       OK ] tcp/test_ucp_stream.send_zero_ending_iov_recv_data/0 (97415 ms)
[----------] 1 test from tcp/test_ucp_stream (97428 ms total)
```
after:
```
[ RUN      ] test_conn_match.random_insert_retrieve <> <>
[     INFO ] address length: 56
[     INFO ] address length: 23
[     INFO ] address length: 9
[     INFO ] address length: 93
[       OK ] test_conn_match.random_insert_retrieve (419 ms)
[----------] 1 test from test_conn_match (432 ms total)
```
The test is one …
=> GTEST/UCS: Reduce testing time of conn_match under valgrind

src/uct/ib/ud/base/ud_ep.c
Fix receiving duplicated CREQ packet or CREQ packet after CREP packet was already received.
Fixes the following assertion (`head_sn == 2`, `neth->psn == 1`):
```
[node1:17303:0:17303]       ud_ep.c:746  Assertion `ep->rx.ooo_pkts.head_sn == neth->psn' failed: iface=0x404c7090 ep=0x40559bc0 conn_sn=0 ep_id=0, dest_ep_id=0 rx_psn=2 neth_psn=1 ep_flags=0xd8 ctl
_ops=0x0 rx_creq_count=1
/hpc/mtr_scrap/users/dmitrygla_bf2/ucx/src/uct/ib/ud/base/ud_ep.c: [ uct_ud_ep_rx_creq() ]
...
738                        ep->dest_ep_id);
739
740     /* creq must always have same psn */
==>   741     ucs_assertv_always(ep->rx.ooo_pkts.head_sn == neth->psn,
742                        "iface=%p ep=%p conn_sn=%d ep_id=%d, dest_ep_id=%d rx_psn=%u "
743                        "neth_psn=%u ep_flags=0x%x …
```
=> UCT/IB/UD/BASE: Fix receiving duplicated CREQ or CREQ after CREP

src/ucp/core/ucp_worker.c
With new protocols, system topology is already taken into account
=> UCP/WORKER: Do not adjust bandwidth by system distance for new protocols

test/gtest/ucp/test_ucp_stream.cc
Reduce testing time by decreasing maximum test size and use step=111 instead of step=1 when running under valgrind.
To reduce testing time.
before:
```
[ RUN      ] tcp/test_ucp_stream.send_zero_ending_iov_recv_data/0 <tcp>
==168595== WARNING: valgrind ignores shmget(shmflg) SHM_HUGETLB
[       OK ] tcp/test_ucp_stream.send_zero_ending_iov_recv_data/0 (97415 ms)
[----------] 1 test from tcp/test_ucp_stream (97428 ms total)
[==========] 1 test from 1 test case ran. (97534 ms total)
[  PASSED  ] 1 test.
```
after:
```
[ RUN      ] tcp/test_ucp_stream.send_zero_ending_iov_recv_data/0 <tcp>
==172248== WARNING: valgrind ignores shmget(shmflg) SHM_HUGETLB
[       OK ] tcp/test_ucp_stream.send_zero_ending_iov_recv_data/0 (2515 ms)
[----------] 1 …
```
=> GTEST/UCP: Decrease maximum test size and use step=111 under valgrind

test/gtest/uct/test_p2p_am.cc, test/gtest/uct/test_pending.cc, test/gtest/uct/test_uct_perf.cc, test/gtest/uct/uct_test.h
Remove IB CM related stuff.
IB CM is deprecated.
1. Remove `has_transport("cm")` checks.
2. Remove "cm" from UCT transports enabled for testing.
=> GTEST/UCT: Remove IB CM related stuff

src/ucs/vfs/fuse/vfs_fuse.c
Reduced log level of inotify read in case of "Interrupted system call" error.
=> UCS/VFS: Reduced log level in case of intotify read failed.

test/apps/iodemo/io_demo.cc
Remove the checks for status=OK from Write/Read response callbacks.
Fixes:
```
Log: /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210912_081742_57991_66409_jazz23.swx.labs.mlnx/iodemo_logs/1631424149-447875792/iodemo_jazz23_server_12.log
Error iodemo analyzer: [1631424864.852342] [DEMO] Assertion "_conn->ucx_status() == UCS_OK" failed conn_status=-25
```
introduced by #7362.
Update `IoReadResponseCallback`/`IoWriteResponseCallback` to not have assertion for `conn.ucx_status() == UCS_OK`.
=> APPS/IO-DEMO: Remove the checks for status=OK from Write/Read response callbacks

buildlib/pr/distro.yml
Use random free port for wire compatibility tests.
To avoid port collisions during parallel tests
=> AZP: use random free port for wire compatibility tests.

test/gtest/ucp/test_ucp_stream.cc
Reduce buffer length and step multiplier when running under valgrind.
before:
```
[ RUN      ] udx/test_ucp_stream.send_recv_iov/0 <ud_x>
[       OK ] udx/test_ucp_stream.send_recv_iov/0 (13095 ms)
[----------] 1 test from udx/test_ucp_stream (13105 ms total)
```
after:
```
[ RUN      ] udx/test_ucp_stream.send_recv_iov/0 <ud_x>
[       OK ] udx/test_ucp_stream.send_recv_iov/0 (1592 ms)
[----------] 1 test from udx/test_ucp_stream (1603 ms total)
```
i.e. now the test takes 1.6s instead of 13.1s.
These are one of the longest tests under valgrind:
```
2021-09-12T21:37:45.4632585Z 12. shm_ib/test_ucp_stream.send_recv_iov/0                                                                                    - 15444 ms
2021-09-12T21:37:45.4641504Z 13. posix/test_uct_perf.envelope/0 …
```
=> GTEST/UCP: Reduce buffer length and step multiplier under valgrind

src/ucp/wireup/address.h, src/ucp/wireup/select.c
=> UCP/WIREUP: Handle address count > 64 - v1.11.x

src/ucp/tag/tag_match.inl
Remove extra `rdesc` word from traces
Avoiding
"matched unexp **rdesc rdesc** 0x7f2bf91fc108 te--f- len 24+4080 to probe tag 11/ffff"
=> UCP: Remove extra rdesc from traces

buildlib/pr/main.yml
Fix test failures when RoCE devices are visible inside the container, but cannot be used because no `--net=host`
=> AZP: remove --privileged for docker

buildlib/pr/distro.yml
AZP: use localhost for wire compat tests.
Fixes wen `hostname -I` has multiple values https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/25449/logs/212
=> AZP: use localhost for wire compat tests.

test/gtest/ucp/test_ucp_wireup.cc
Don't skip wireup test for TCP.
The issues was fixed by #7288 (TCP part).
Remove skip condition of `has_transport("tcp")` is `true`.
=> GTEST/UCP: Don't skip wireup test for TCP

contrib/test_jenkins.sh, src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/ucp_tests.cc, src/tools/perf/perftest.c, src/tools/perf/perftest.h, src/tools/perf/perftest_params.c, src/tools/perf/perftest_run.c, test/gtest/common/test_perf.cc, test/gtest/common/test_perf.h, test/gtest/ucp/test_ucp_perf.cc
Signed-off-by: Vasily Philipov <vasilyf@nvidia.com>
Add loopback transport support for UCP tests
=> LIBPERF: Add loopback transport support for UCP tests

src/ucp/rma/flush.c
Fix recent CI failures on "roce" machines: 
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=25646&view=logs&s=8bfbeaae-4c8e-5f12-f154-edd305817000&j=fe065d53-24bf-55d6-97e1-9993908ec8ed
```
[ RUN      ] all/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/2 <all/tag,not_all_devs>
[     INFO ] Testing 2.1.6.4:0
[     INFO ] server listening on 2.1.6.4:54226
[swx-rain04:87501:0:87501]       flush.c:68   Assertion `ep->flags & UCP_EP_FLAG_FAILED' failed
/scrap/azure/agent-10/AZP_WORKSPACE/1/s/contrib/../src/ucp/rma/flush.c: [ ucp_ep_flush_progress() ]
...
65              *   so remove destroyed/failed lanes from started_lanes and count
66              *   them completed.
67              */
==>    68             ucs_assert(ep->flags & UCP_EP_FLAG_FAILED);
69 …
```
=> UCP/FLUSH: Handle removed lanes during wireup process

src/ucp/rma/amo_offload.c, src/ucp/rma/amo_send.c, src/ucp/rma/amo_sw.c, test/gtest/common/mem_buffer.cc, test/gtest/common/mem_buffer.h, test/gtest/ucp/test_ucp_atomic.cc, test/gtest/ucp/test_ucp_mmap.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Add support for atomic arguments allocated in GPU memory.
Copy arguments to host memory using dt_pack API.
=> UCP/AMO: Mem type atomic arguments

src/ucp/proto/proto_am.inl, test/gtest/ucp/test_ucp_sockaddr.cc
Fixes segfault on emty memh when CM switches from rdmacm -> tcp (due to listener started on non RDMA NIC)
=> UCP: Reregister memh on CM switch.

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h
Using network buffer directly within am receive callback not only avoids extra buffer allocation but also improves throughput.
Using network buffer directly within am receive callback not only avoids extra buffer allocation but also improves throughput.
Added a new memory type support for class Buffer. That way keeps the logic clear and not impact current code structure much.
=> APPS/IO-DEMO: memcpy removal for AM eager data receiving

src/ucp/core/ucp_am.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_select.c, src/ucp/proto/proto_select.h, src/ucp/rndv/proto_rndv.c, src/ucp/tag/tag_recv.c
- Implement UCP request info string for new protocols
- Add profiling for potentially time-consuming steps during a request lifetime
=> UCP/PROTO: Add request debugging and profiling

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_worker.c
Fix an issue that transport error is not printed
=> UCP/EP: Fix error handler return status when user callback is not set

src/ucp/proto/proto_am.inl
Fix failure like [this (internal link)](http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/14255/pipeline/135) on r-vmb-ppc-jenkins (MellanoxLab test)
```
[2021-09-21T21:49:03.447Z] [ RUN      ] all/test_ucp_sockaddr_cm_switch.rereg_memory_on_cm_switch/0
[2021-09-21T21:49:03.703Z] [     INFO ] Testing 65.65.65.12:0
2021-09-21T21:49:03.703Z] [     INFO ] server listening on 65.65.65.12:33430
[2021-09-21T21:49:03.960Z] /scrap/jenkins/workspace/ucx-9/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:271: Failure
[2021-09-21T21:49:03.960Z] Error: Input/output error
[2021-09-21T21:49:03.960Z] [r-vmb-ppc-jenkins:14408:p-0:14408]  ucp_worker.c:2534 Assertion `worker->inprogress++ == 0' failed
[2021-09-21T21:49:05.327Z] 
[2021-09-21T21:49:05.327Z] …
```
=> UCP/AM: Fix request datatype state during CM switch

src/ucp/core/ucp_rkey.inl, src/ucp/rma/amo_offload.c, src/ucp/rma/get_offload.c, src/ucp/rma/put_offload.c, src/ucp/rma/rma.inl, src/ucp/rma/rma_send.c, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_put.c
Fix failures with new protocols when a transport does not require a remote key (NEED_RKEY for me is not set), so it's initialized with rkey_index==NULL_RESOURCE. When used without any checks, it generates memory access error (to invalid array index).
=> UCP/RMA/RNDV: Handle rkey_index==UCP_NULL_RESOURCE

src/ucp/proto/proto_am.inl
=> UCP/AM: Fix request datatype state during CM switch - v1.11.x

src/ucp/core/ucp_context.c
No need to print a ucs_diag() warning if `resource->sys_device` is `UCS_SYS_DEVICE_ID_UNKNOWN`
Before this PR, if `resource->sys_device` was `UCS_SYS_DEVICE_ID_UNKNOWN`, it triggered a ucs_diag() message, since `UCS_SYS_DEVICE_ID_UNKNOWN` >= ` UCP_MAX_SYS_DEVICES`, But it's not really a problem we should warn about.
=> UCP/CONTEXT: Remove wrong DIAG message during context create

buildlib/jucx/jucx-test.yml, buildlib/pr/go/go-test.yml
use -xeE for JUCX and Go tests.
As mentioned in comment in #7412
=> AZP: use -xeE for JUCX and Go tests.

src/ucp/wireup/address.c
So packet tracer will not fail on assert even if packet content is corrupted
=> UCP/ADDRESS: If got invalid bandwidth - return error instead of assert

test/gtest/common/test_perf.cc, test/gtest/common/test_perf.h
Potentially reduce testing time by not binding to a single core after loopback perftest
Do not call test_func in single-threaded/loopback mode since it sets CPU affinity; call ucx_perf_run() directly
=> TEST/PERF: Do not set CPU affinity for loopback tests

src/ucp/api/ucp.h, src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_worker.c, src/ucs/config/parser.h, src/uct/api/uct.h, test/gtest/ucp/ucp_test.cc
1. cache UCT configurations in ```ucp_config_modify``` API, apply UCT configurations when creating ```ucp_context``` and ```ucp_worker```
2. print UCT configurations in ```ucp_config_print``` API
3. print unused cached UCT configurations in ```ucp_warn_unused_uct_config``` API
Feture requirement
1. cache input key/value in the ```ucp_config``` object
2. copy the cached key/value into ```ucp_context```, apply them to UCT configurations when creating ```ucp_context```
3. apply the cached key/value into UCT configurations when creating ```ucp_worker```
=> Set UCT parameters from UCP API

src/tools/perf/perftest_run.c
Fix a bug where perftest prints "Final" when the output is set to CSV
The word "Final" should not be printed when printing in CSV mode.
=> TEST/PERF: Do not print 'Final' when output set to CSV

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/proto/proto_am.inl, src/ucp/proto/proto_select.inl, src/ucp/stream/stream_send.c, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/ucs/sys/init.c, src/uct/cuda/base/cuda_md.c, test/gtest/ucs/test_memtype_cache.cc
A single instance of memtype cache that can be accessed within UCP as well as UCTs. This allows UCTs themselves to avoid repeated lookups of memory attributes.
Review topic:
Disabling memtype cache in UCP land doesn't disable the same for UCTs with this PR -- i.e global instance continues to be used by UCTs. All intercepted regions in CUDA are marked unknown to begin with and they go through CUDA API to actually mark regions as CUDA or not. This means that entries in memtype cache are always valid (whether libcudart gets statically or dynamically linked). Are there issues in this logic? If not, should we change things in ucm/rocm as well?
cc @yosefe @bureddy
=> UCS/MEMTYPE_CACHE: add global memtype cache instance

test/gtest/common/googletest/Makefile.am
- there were missing header files listed in makefile.am which
were not packed into distro archive
=> GTEST: fixed make dist

buildlib/pr/static_checks.yml
remove ucx_docker_fast label because this label duplicate with ucx_docker 
remove ucx_docker_fast
=> AZP: remove unused label

src/ucp/tag/eager_rcv.c, src/ucp/tag/tag_recv.c
fix recv of single packet sent by multi protocol
after EP reconfiguration after wireup, max_bcopy might be increased, so the whole message will be sent as a first packet of multi packet protocol which was handled wrongly on receiver side
=> UCP/TAG: fix recv of single packet sent by multi protocol

test/gtest/common/mem_buffer.cc
Fixing a missing bracket in mem_buffer::memset for ROCM-enabled code path
Code won't compile properly without it
Added a single bracket
=> GTEST/COMMON: Fix missing bracket on ROCM memset

src/ucp/proto/proto_common.inl
NO_IMM_CPML flag was ignored with new protocols
Use same macro as in old protocols - ucp_request_imm_cmpl_param
=> UCP/PROTO: Fix handling of NO_IMM_CMPL flag

src/ucp/core/ucp_context.c, src/ucp/core/ucp_ep.c, src/ucp/proto/proto_select.c
Fast-path short protocol was not used because short threshold was not set correctly so performance is not as good
1. Fix signed/unsigned compare
2. Set the default of UCX_BCOPY_THRESH to "auto", to not force bcopy protocol from length 0
=> UCP/PROTO: Fix short not being enabled with new protoocols

src/uct/api/v2/uct_v2.h, src/uct/base/uct_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.h, src/uct/cuda/gdr_copy/gdr_copy_iface.c, src/uct/cuda/gdr_copy/gdr_copy_iface.h
Allow exposing different latency per specific UCT operation for a more accurate performance estimation with new protocols
=> UCT/API/V2: Add latency estimation to uct_iface_estimate_perf()

src/ucp/core/ucp_request.c
New protocols information is already printed before this code (in line 53)
=> UCP/REQUEST: Remove unused code of request info print

test/gtest/ucp/test_ucp_wireup.cc
Reduce testing time of multi_wireup test under valgrind.
e.g. the following testing results on jazz nodes:
before:
```
[ RUN      ] shm_ib/test_ucp_wireup_1sided.multi_wireup/3 <shm,ib/rma,unified,no_ep_match>
[       OK ] shm_ib/test_ucp_wireup_1sided.multi_wireup/3 (16521 ms)
```
after:
```
[ RUN      ] shm_ib/test_ucp_wireup_1sided.multi_wireup/3 <shm,ib/rma,unified,no_ep_match>
[       OK ] shm_ib/test_ucp_wireup_1sided.multi_wireup/3 (4180 ms)
```
Decrease the number of iterations from 10 to minimum value between `2` and `10 / ucs::test_time_multiplier()` when running under valgrind.
=> GTEST/UCP: Reduce testing time of multi_wireup test under valgrind

test/gtest/ucs/test_async.cc
Reduce testing time of `*/test_async.many_timers/0` async test under valgrind.
To reduce the whole testing time of CI.
e.g. the following testing results on jazz nodes:
before:
```
[ RUN      ] signal/test_async.many_timers/0 <signal>
[       OK ] signal/test_async.many_timers/0 (29043 ms)
```
after:
```
[ RUN      ] signal/test_async.many_timers/0 <signal>
[       OK ] signal/test_async.many_timers/0 (1253 ms)
```
1. Reserve memory for `timers` STL vector prior to adding/removing element to it.
2. Decrease number of timers used in iterations from `250` to `250 / ucs::test_time_multiplier`.
=> GTEST/UCS: Reduce testing time of some async test under valgrind

test/gtest/ucs/test_async.cc
Reduce the number of min threads count in async_event_mt test under valgrind.
It reduces CI testing time for `*/test_async_event_mt.multithread/0` test.
e.g. the following results could be obtained on jazz nodes:
before:
```
[ RUN      ] thread_spinlock/test_async_event_mt.multithread/0 <thread_spinlock>
[       OK ] thread_spinlock/test_async_event_mt.multithread/0 (28192 ms)
```
after:
```
[ RUN      ] thread_spinlock/test_async_event_mt.multithread/0 <thread_spinlock>
[       OK ] thread_spinlock/test_async_event_mt.multithread/0 (5194 ms)
```
Use `ucs_max(4, COUNT / ucs::test_time_multiplier())` instead of `COUNT` to reduce testing time.
=> GTEST/UCS: Reduce number of min threads count in async_event_mt test under valgrind

buildlib/pr/io_demo/az-stage-io-demo.yaml, buildlib/pr/io_demo/io-demo.yml
Due to issue https://redmine.mellanox.com/issues/2789448 the port is not restored after an interference cycle, which leads to "No traffic" failures
=> AZP: Run DC io_demo without port up/down

bindings/go/src/ucx/context_params.go, bindings/go/src/ucx/endpoint_params.go, bindings/go/src/ucx/listener_params.go, bindings/go/src/ucx/request.go, bindings/go/src/ucx/utils.go, bindings/go/src/ucx/worker_params.go, bindings/go/tests/context_test.go
Prevent memory leak in C allocated memory. Checks if the memory is set - free it, and sets finalizer for all C allocated objects
Tested by adding loggers to finalizers and if statements. 
Fixes #7422
=> BINDINGS/GO: Fix memory leak for C allocated mem.

src/ucs/debug/log.c, src/ucs/vfs/fuse/vfs_fuse.c
- Fix hang in gtest while trying to stop Fuse thread
- Fix wrong PID in ucs_log message after fork
- Reset Fuse thread context after fork
- Reset ucs_log_pid after fork
@avildema FYI it fixes hang at gtest exit
=> UCS/VFS/LOG: Fix fork() handling and hang at exit

test/gtest/ucp/test_ucp_stream.cc
Reduce testing time of some stream tests under valgrind.
e.g. it gives the following testing time improvement on jazz nodes:
before:
```
[ RUN      ] shm_ib/test_ucp_stream.send_exp_recv_32/0 <shm,ib>
==47910== Warning: noted but unhandled ioctl 0x7801 with no size/direction hints.
==47910==    This could cause spurious value errors to appear.
==47910==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
[       OK ] shm_ib/test_ucp_stream.send_exp_recv_32/0 (9570 ms)
```
after:
```
[ RUN      ] shm_ib/test_ucp_stream.send_exp_recv_32/0 <shm,ib>
==44644== Warning: noted but unhandled ioctl 0x7801 with no size/direction hints.
==44644==    This could cause spurious value errors to appear.
==44644==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing …
```
=> GTEST/UCP: Reduce testing time of some stream tests under valgrind

src/uct/tcp/tcp_iface.c
Don't allow connecting loopback with other devices.
1. If `ethtool` isn't configured on a system, TCP is unable to identify BW/latency characteristics. 
2. Let's assume both nodes has the following IP configuration:
```
lo: 127.0.0.1
eth0: 192.168.22.1
```
3. Firstly, TCP client tries to check `lo -> lo` connectivity, it fails reachability check since `boot_id` values are different (it is a part of additional NS information which is packed with `lo`).
4. Then, TCP client tries to check `lo -> eth0` connectivity, it succeeded reachability check since `eth0` address doesn't contain additional NS information.
5. Trying to establish `lo -> eth0` fails, since they are really unreachable.
Fixes #7599
1. Always pack NS information for loopback and ordinary addresses.
2. AIf at least one of the …
=> UCT/TCP: Don't allow connecting loopback with other devices

contrib/test_jenkins.sh, src/ucp/core/ucp_context.c, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/parser.c, test/apps/Makefile.am, test/apps/test_ucp_config.c, test/gtest/common/test.cc
Allow passing UCS variables through `ucp_config_modify()` API function.
Some application can use `ucp_config_modify()` to set UCS parameters, e.g. `UCX_MODULES=^cuda` to disabel CUDA modules.
1. Add `ucp_apply_ucs_config_list()` which goes over all variables and tries to set them through `ucs_global_opts_set_value()` function.
2. Update `ucx_info` utility to handle the`"-L"` parameter which could be used to specify glob patter as `UCX_MODULES` variable accepts.
3. Add test for filtering B transport by specifying "^ib,rdmacm" through `"-L"` parameter of `ucx_info` utility.
=> UCP/CORE/INFO: Allow passing UCS variables through ucp_config_modify()

config/m4/cuda.m4, src/uct/cuda/base/cuda_iface.h, src/uct/cuda/base/cuda_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
Limit cuda-ipc get zcopy to [0, 0] range on platforms where concurrent reads are slow compared to concurrent puts (observed through osu_alltoall and osu_bibw reports)
=> UCT/CUDA-IPC: disable get_zcopy on gpus with no active nvlinks

src/uct/cuda/cuda_ipc/cuda_ipc_md.c, test/gtest/uct/test_md.cc
Support MD_FLAG_INVALIDATE using rcache to track memory regions
=> UCT/CUDA_IPC: MD_FLAG_INVALIDATE stub implementation

src/ucs/configure.m4, src/ucs/debug/debug.c
configure option to disable overriding sigaction and signal glibc functions
For applications not related to UCX, the linker can resolve these symbols from libucs.so, which can cause unwanted behaviors.
=> UCS/DEBUG/CONFIG: Add config option to disable sigaction overriding

src/ucp/core/ucp_worker.c
1. refine the message to warn the unused cached confiurations
2. use "key=value" to show the unused cached configurations instead of "key"
=> refine msg format to warn the unused cached configurations.

examples/hello_world_util.h, examples/ucp_client_server.c, examples/ucp_hello_world.c, examples/uct_hello_world.c, src/tools/info/proto_info.c, src/tools/info/ucx_info.c, src/tools/info/ucx_info.h, src/tools/perf/perftest.c, src/tools/perf/perftest.h, src/tools/perf/perftest_params.c, src/ucs/sys/sock.c, src/ucs/sys/sock.h, src/uct/ib/base/ib_iface.c, src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, src/uct/tcp/tcp_iface.c, src/uct/tcp/tcp_md.c, test/gtest/common/test_obj_size.cc, test/gtest/ucs/test_sock.cc, test/gtest/uct/tcp/test_tcp.cc
Add IPv6 address support
-  Use generic IPv4/IPv6 portable data structures and socket APIs
-  Port TOOLS and EXAMPLES to support IPv6 addresses for data exchange
=> UCT/TCP: Add IPv6 address support

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpListener.java, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/main/native/listener.cc, bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java
Query for listener address.
Since ucp_listener supports bindings on port 0 (would find free port), we can't cache InterSocketAddress any more, but need to query listener for its sockaddr. Needed for SparkUCX protocol.
cc @abellina
=> JUCX: Always query for listener address.

test/apps/iodemo/Makefile.am
UCX compilation may fail if installation destination already has older 
revision of the library
Libtool by default inserts `-rpath <prefix>` to the linking command.
This also means that if `<prefix>` already has UCX libraries installed
from previous build it will use those for linking *instead* of ucx
libraries in the build tree. The problem arises when UCT introduces API
changes. In this case libtool/linker fails to resolve new symbols since
rpath overwrites search path and inserts old revision of the library.
Unfortunately there is no way to remove rpath from the libtool default
flags. Instead we can add path to libuct to make sure that the linker
picks up updated revision of the library from the build tree. Since the
io-demo is always linked to uct through ucp it actually a reasonable …
=> IODEMO: Fixing linking issue

test/apps/iodemo/io_demo.cc
use write syscall in signal handler instead to print log
LOG requires malloc to print log, if the signal was recevied when malloc/free was being performed, a deadlock would occur.
replace LOG of write syscall to print log
=> APPS/IODEMO: use write syscall in signal handler instead

contrib/configure-prof, src/ucs/Makefile.am, src/ucs/configure.m4, test/mpi/Makefile.am
Allow building UCX with a custom-installed binutils
=> UCS/BUILD: Support custom path for binutils dependency

config/m4/sysdep.m4, src/ucm/bistro/bistro_ppc64.c, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/ppc64/timebase.c
Fix compile errors for ppc64.
Fixes #7618.
1. Use `UCX_PTR_BYTE_OFFSET` macro for pointer arithmetic.
2. Check `__ppc_get_timebase()` function existence.
=> UCM/UCS/CONFIG: Fix compile errors for ppc64

src/ucp/core/ucp_ep.c, src/uct/ib/base/ib_md.c
- Avoid flooding of mem registration messages in the debug log (available in the release mode)
- Have more informative error message for some of the asserts
=> UCP/UCT: Improve debugging

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/stream/stream_recv.c, test/gtest/ucp/test_ucp_am.cc
Use set of memory pools with different sizes for UCT AM descriptors in UCP.
Currently, single memory pool is used for any inlined data coming from UCT. Even if 1 byte message arrives, it consumes ~8KB element, which leads to huge memory consumption (or even 64K with tcp).
Initializing several memory pools of different sizes will help to preserve reasonable memory consumption
fixes #7151
=> UCP: Use mpool set for UCT AM descriptors

src/tools/info/proto_info.c, src/tools/info/ucx_info.c
Use conn_req instead accept_cb and provide EP error cb.
To fix the following error seen when launching `ucx_info` utility with error handling support and CM connection establishment method:
```
[1636141932.187527] [ice01:38606:0]          ucp_ep.c:1224 UCX  ERROR ep 0x7fffe806f098: error 'Connection reset by remote peer' on CM lane will not be handle
d since no error callback is installed
```
1. Replace `accept_handler` by `conn_handler` to create UCP endpoint with our own EP parameters when accepting a connection from a peer.
2. Provide EP error callback along with "PEER" error mode when creating UCP EPs.
=> TOOLS/INFO: Use conn_req instead accept_cb and provide EP error cb

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_types.h, src/ucp/core/ucp_worker.c, src/ucp/wireup/address.c, src/ucp/wireup/address.h, src/ucp/wireup/select.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_cm.h, test/gtest/ucp/test_ucp_wireup.cc, test/gtest/ucs/test_type.cc
Define new version of UCP worker address format
- Make it shorter
- Make it more flexible (allowing bigger address lengths, md ids, etc)
- use `ucs_fp8` instead of `floats`
- use extensions for address length or md id if they are too big
=> UCP: Define new worker address format

src/ucp/core/ucp_request.inl, src/ucp/dt/datatype_iter.c, test/gtest/ucp/test_ucp_proto.cc
Fix a [segmentation fault](https://redmine.mellanox.com/issues/2845386) (internal link):
```
(gdb) bt
#0  0x00007ffff5740efd in pause () from /lib64/libpthread.so.0
...
#6  <signal handler called>
#7  0x0000000000000000 in ?? ()
#8  0x00007fffd272ac60 in ucp_invoke_uct_completion (status=UCS_OK, comp=0x11bd020)
at ucx/contrib/../src/ucp/core/ucp_request.inl:1028
#9  ucp_request_invoke_uct_completion_success (req=0x11bcf80)
at ucx/contrib/../src/ucp/core/ucp_request.inl:1035
#10 ucp_proto_single_status_handle (status=<optimized out>, lane=<optimized out>,
complete_func=<optimized out>, is_zcopy=1, req=0x11bcf80)
at ucx/contrib/../src/ucp/proto/proto_single.inl:65
#11 ucp_proto_zcopy_single_progress (uct_comp_cb=<optimized out>, complete_func=<optimized out>,
send_func=<optimized out>, …
```
=> UCP/DATATYPE: Fix length==0 initialization of dt_reg array

test/apps/iodemo/io_demo.cc
Fix performance printing if `wait_for_responses()` takes ~= `print_interval` seconds.
Fix inaccurate perf measurement including `wait_for_responces()` to the whole result:
Before:
```
[1636396139.269192] [DEMO] total min:90 max:90 total:90 | read 3203.26 MBs min:40(2.1.3.1:1337) max:40 total:40 | write 4004.07 MBs min:50(2.1.3.1:1337) max:50 total:50 | active:1/1 buffers:64
[1636396139.701740] [DEMO] total min:10 max:10 total:10 | read 158.012 MBs min:5(2.1.3.1:1337) max:5 total:5 | write 158.012 MBs min:5(2.1.3.1:1337) max:5 total:5 | active:1/1 buffers:64
[1636396143.053006] [DEMO] total min:80 max:80 total:80 | read 3237.73 MBs min:37(2.1.3.1:1337) max:37 total:37 | write 3762.77 MBs min:43(2.1.3.1:1337) max:43 total:43 | active:1/1 buffers:64
[1636396143.460260] [DEMO] total min:10 …
```
=> APPS/IO-DEMO: Fix performance printing if wait_for_responses takes ~= 'print_interval' seconds

src/uct/ib/rc/accel/rc_mlx5_common.c, test/gtest/ucp/test_ucp_tag_offload.cc
Disable MP XRQ by default
This in turn disables multi-eager tag offload protocols which currently have some issues
=> UCT/GTEST: Disable MP_SRQ by default

buildlib/pr/io_demo/az-stage-io-demo.yaml
Don't pass CI allow-list type to IO-demo analyzer.
IODEMO CI jobs are running as follows:
```
python /hpc/noarch/git_projects/hpc-mtt-conf/scripts/iodemo_analyzer.py --allow_list CI,master -d drop_29252/am_cx6_dc --duration 600 -t 3
```
So, "timeout waiting for replies" errors are allowed to be caught during CI testing, but they should be reported as error and fail jobs.
Remove passing "CI" from `--allow_list` argument.
=> AZP/IO-DEMO: Don't pass CI allow-list type to IO-demo analyzer

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.h
Deprecate `UCX_SOCKADDR_AUX_TLS` configuration parameter.
It is not used by the new client/server connection establishment flow.
1. Remove `sockaddr_aux_tls` field from `ucp_config_t`.
2. Use `UCS_CONFIG_DEPRECATED_FIELD_OFFSET` and `UCS_CONFIG_TYPE_DEPRECATED` to mark `UCX_SOCKADDR_AUX_TLS` as deprecated.
=> UCP/CORE: Deprecate UCX_SOCKADDR_AUX_TLS configuration parameter

src/ucp/core/ucp_ep.c
Fix UCP endpoint use after free.
UCP endpoint may be dereferenced after destroying.
Replace calling `ucp_ep_destroy_internal()` by `goto err_destroy_ep` which does the same and returns the functions.
=> UCP/CORE: Fix UCP endpoint use after free

src/ucp/core/ucp_request.c
Handle ACK wireup msg which passed to UCT directly.
Fixes #7648
Allow `WIREUP_MSG/ACK` to be purged from UCT transport directly.
=> UCP/WIREUP: Handle ACK wireup msg which passed to UCT directly

bindings/go/Makefile.am
Use abs_top_srcdir to fix OOS build.
Fixes #7647 when OOS is outside of ucx directory.
=> BINDINGS/GO: Use abs_top_srcdir to fix OOS build.

src/ucm/util/sys.c
- there was incorrect exit from initialization sequence which may
lead to hang
=> UTIL/SYS: fixed potential hang on failed init

src/ucs/arch/bitops.h, src/uct/ib/mlx5/ib_mlx5.inl
There's below error when compiling code on CentOS 6.3 & 6.10:
src/ucs/arch/bitops.h: In function 'ucs_bitwise_is_equal':
src/ucs/arch/bitops.h:179: error: declaration of 'remainder' shadows a global declaration
/usr/include/bits/mathcalls.h:289: error: shadowed declaration is here
cc1: warnings being treated as errors
In file included from src/ucs/sys/math.h:17,
from util/sys.c:21:
=> UCS: solve name shadow problem in CentOS6.x

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Ensure request purging is done after destroying of UCT EPs.
Fixes potential data reading (as a part of RNDV) from the send buffer which is tied with already completed UCP requests.
Let's imagine we have the following scenario:
1. Connection established between two peers (`A` and `B`).
2. `A` sends some large buffer that goes to RNDV protocol.
3. `B` starts `RDMA_READ` operation to read it to the local receive buffer. After sending RTS, UCP EP on `A` adds requests to hlist which tracks the requests until ATS is received.
4. User decides to kill `A` by sending `SIGINT`. Application's signal handler forcibly closes UCP EP and waits for completion of all requests (and fills send buffers by `ffff`).
5. UCP EP's force close starts discard operation for all UCT EPs (but they are not completed …
=> UCP/CORE: Ensure request purging is done after destroying of UCT EPs

src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, test/gtest/ucp/test_ucp_sockaddr.cc
Fix error handling of connecting p2p lanes during WIREUP phase.
`uct_ep_connect_to_ep()` could fail.
So, UCP/CM application hangs waiting for error/success, but it doesn't come, since UCP doesn't call error callback in case of `uct_ep_connect_to_ep()` fails during WIREUP phase.
1. Add UCP EP debug flag: `UCP_EP_FLAG_CONNECT_WAIT_PRE_REQ` to use it for testing purposes.
2. Remove `ucp_wireup_init_lanes_by_request()` wrapper and use directly `ucp_wireup_init_lanes()` with setting UCP EP failure manually.
3. Handle errors from `ucp_wireup_connect_local()` by calling `ucp_ep_set_failed_schedule()`.
4. Introduce the test which emulates the failure of WIREUP by changing `uct_ep_connect_to_ep` pointer.
5. Re-organize code in `test_ucp_sockaddr_wireup_fail` test suite to reduce code duplication …
=> UCP/CORE/WIREUP/GTEST: Fix error handling of connecting p2p lanes during WIREUP phase

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/wireup/ep_match.c, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c
Simplify resetting of UCP endpoint's flush state.
To reset UCP endpoint's flush state when:
- creating UCP EP
- retrieving from EP matching
- removing from EP matching
1. Remove all places where `ucp_ep_flush_state_reset()` is called - remain them only in places listed above.
2. Move `ucp_ep_flush_state_reset()`/`ucp_ep_flush_state_invalidate()` to the `ucp_ep.c`/`ucp_ep.h` instead of `ucp_ep.inl` where it was declared as `inline`ed
=> UCP/CORE/WIREUP: Simplify resetting of UCP endpoint's flush state

src/uct/base/uct_component.h
- fixed copy-paste issue in macro definition
=> UCT/COMPONENT: fixed typo

src/uct/ib/mlx5/ib_mlx5_log.c
Fix overriding CQE status in case of completion error.
Querying QP peer info return `ucs_status_t` and it is overriding `status` which was already set to some error taking into account CQE error value.
It fixes reporting an incorrect completion status for a particular operation.
1. Rename `status` to `ep_status` to use it for storing a CQE error value and return the function result.
2. Introduce new `status` to store the result of `uct_ib_mlx5_query_qp_peer_info()`.
=> UCT/IB/MLX5: Fix overriding CQE status in case of completion error

config/m4/cuda.m4
Configure step to show error if nvml isn't detected on the system.
=> CONFIG/CUDA: show error messages if nvml not detected - v1.12.x

bindings/go/Makefile.am
Fix `go: cannot find main module, but found .git/config in /tmp/ucx` when building goperftest before goucx
=> BINDINGS/GO: disable module for goperftest.

test/apps/iodemo/ucx_wrapper.cc
Fix progress loop in io_demo
Fixes a hang in io_demo test over shared memory transport
If `progress_worker_event()` returns `false`, we don't progress the io message. We have to progress io_msg and worker at least once to avoid the situation when io_msg is completed on previous iteration of worker progress.
The issue is stable reproducible with shared memory transport
=> IODEMO: fix progress loop

src/ucp/core/ucp_ep.c, test/gtest/ucp/test_ucp_sockaddr.cc
Fix possible purge of requests after discarding is in-progress after error handling.
It fixes a new type of "iov data corruption" issue found by MTT/IO-Demo testing:
- client and server exchange data
- some network issues happen on some links, but some other links are still health
- client detects an issue while some RNDV operations are in-progress and RTS for them was sent
- `ucp_ep_set_failed` discards all UCT lanes (they operations are in-progress)
- `ucp_ep_set_failed` invokes a user's error callback which closes the failed endpoint with mode=FORCE
- `ucp_ep_reqs_purge` is called from `ucp_ep_discard_lanes`, since no lanes to discard
- send operations are canceled and their invalidate data
- server doesn't detect an issue and continues reading data using health links, but the data is …
=> UCP/CORE/GTEST: Fix possible purge of requests after discarding is in-progress after error handling

src/ucp/core/ucp_ep.inl, src/ucp/wireup/address.c, src/ucp/wireup/address.h, test/gtest/ucp/test_ucp_wireup.cc
- Fixes for UCP address v2 packing/unpacking:
- Do not pack unused MD flags to md_index byte
- Fix packing of latency and overhead (need to pack nsecs) 
- Take into account remote segment size when checking `max_bcopy` and `max_zcopy` for  UCT AM sends in UCP protocols
=> UCP: Fix UCP address v2 packing/unpacking and usage of seg_size

test/apps/Makefile.am, test/apps/iodemo/ucx_wrapper.cc
if use gcc 4.4.7 on centos6.10, IODEMO would not be compiled
HAVE_GLIBCXX_NOTHROW non-declared
remove this dependency as iodemo does not depend on it anymore.
After removal, got below build errors when compiling ucx-1.11.2, hence changed lines to function call.
ucx_wrapper.cc: In static member function ‘static const std::string UcxContext::sockaddr_str(const sockaddr*, size_t)’:
ucx_wrapper.cc:298: error: dereferencing pointer ‘addr.108’ does break strict-aliasing rules
ucx_wrapper.cc:298: note: initialized from here
ucx_wrapper.cc:303: error: dereferencing pointer ‘addr.110’ does break strict-aliasing rules
ucx_wrapper.cc:303: note: initialized from here
test/apps/iodemo/ucx_wrapper.cc
298         port = ntohs(((struct sockaddr_in*)&addr)->sin_port);
=> TEST/IODEMO: remove build dependency on HAVE_GLIBCXX_NOTHROW

src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_multi.h, src/ucp/rma/get_offload.c, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv_get.c, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_mem_type.cc
Fix the failure https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/30370/logs/453
- Protocol specified whether it can handle non-0 min_frag value
- rndv/get/zcopy and get/offload/zcopy will check if they send a too small size, and extend the sent data forward or backward to compensate. It can cause fetching overlapping data, but correctness is still maintained. In the worst case, we may send an extra 64b per rendezvous fragment, which is not a significant performance impact.
=> UCP/PROTO/RNDV: Fix fragmentation to avoid a too small get_zcopy size

src/ucp/core/ucp_ep.inl, src/ucp/wireup/address.c, src/ucp/wireup/address.h, test/gtest/ucp/test_ucp_wireup.cc
- Fixes for UCP address v2 packing/unpacking:
- Do not pack unused MD flags to md_index byte
- Fix packing of latency and overhead (need to pack nsecs)
- Take into account remote segment size when checking max_bcopy and max_zcopy for UCT AM sends in UCP protocols
- Gtest
porting #7678 to v1.12
=> UCP: Fix UCP address v2 packing/unpacking and usage of seg_size - v1.12

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_ep.inl, src/ucp/wireup/ep_match.c, src/ucp/wireup/wireup_cm.c
Get rid of `UCP_EP_CLOSE_REQ_VALID` flag.
To have one more free bit to use for another flag when it is needed.
1. Remove `UCP_EP_CLOSE_REQ_VALID` flag and all places where it is used.
2. Remove `ucp_ep_close_proto_req_t` structure.
3. Initialize `close_req` to `NULL`.
4. Check `close_req != NULL` where `UCP_EP_CLOSE_REQ_VALID` flag was checked.
5. Don't check `close_req != NULL` fro flush_state and EP matching context, since they are not share the union anymore.
=> UCP/CORE: Get rid of CLOSE_REQ_VALID flag

src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_common.inl, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_multi.h, src/ucp/rma/get_offload.c, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv_get.c, test/gtest/ucp/test_ucp_tag_match.cc, test/gtest/ucp/test_ucp_tag_mem_type.cc
Porting #7630 bugfix to v1.12.x release branch
No merge conflicts.
=> UCP/PROTO/RNDV: Send overlapping data to satisfy min_frag constraint - v1.12.x

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_worker.c, src/ucp/rma/flush.c, test/gtest/ucp/test_ucp_sockaddr.cc
Don't destroy UCP EP which owns send request when invalidation is in-progress.
To fix touching UCP EP which could be already destroyed, but memory invalidation is still in-progress.
It fails when assertions from the PR are added with:
- the previous test case `test_ucp_sockaddr_protocols_err_sender::tag_rndv_killed_sender`:
```
[ RUN      ] dcudx/test_ucp_sockaddr_protocols_err_sender.tag_rndv_killed_sender/0 <dc_x,ud,cuda_copy,rocm_copy/mt>
[New Thread 0x7fffee581700 (LWP 102949)]
[     INFO ] server listening on 2.1.3.1:57341
[jazz01:102844:0:102844] ucp_request.inl:226  Assertion `(req->send.ep == ((void *)0)) || (req->send.ep->refcount > 0)' failed: ep 0x7fffd82c6000
/labhome/dmitrygla/work_auto/ucx/src/ucp/core/ucp_request.inl: [ ucp_request_complete_send() ]
...
222 static …
```
=> UCP/CORE/GTEST: Don't destroy UCP EP which owns send request when invalidation is in-progress

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_worker.c, src/ucp/wireup/select.c, src/ucp/wireup/wireup.h
Make sure optimal memory-type transports are selected for intra-node endpoints, and not just host/ipc transports
=> UCP/SELECT: Add mem access lanes for all supported memory types

src/ucp/wireup/address.c
Fix UCP worker address unpacking 
Older UCX version do not set UCP_ADDRESS_HEADER_FLAG_WORKER_UUID flag even if worker uuid IS packed. Thus, when UCX v1.12 receives an address packed by older UCX version it may not be correctly unpacked
- Always assume that address contains worker uuid if UCP_ADDRESS_PACK_FLAG_WORKER_UUID is passed in unpack_flags (irrespectively of addr_flags value)
=> UCP/WIREUP: Fix wire compatibility in address unpacking

src/ucp/wireup/address.c
Fix UCP worker address unpacking
Port of #7695 
Older UCX version do not set UCP_ADDRESS_HEADER_FLAG_WORKER_UUID flag even if worker uuid IS packed. Thus, when UCX v1.12 receives an address packed by older UCX version it may not be correctly unpacked
=> UCP/WIREUP: Fix wire compatibility in address unpacking - v1.12

src/uct/sm/scopy/knem/knem_md.c
Fix memory registration cost reported by knem md 
To correctly report mem registration cost by `uct_md_query` and by `ucx_info`
BEFORE:
```
$UCX_KNEM_RCACHE_OVERHEAD=16us ./src/tools/info/ucx_info -d | grep -A 3 "Memory domain: knem"
$UCX_KNEM_RCACHE=n ./src/tools/info/ucx_info -d | grep -A 3 "Memory domain: knem"
$./src/tools/info/ucx_info -d | grep -A 3 "Memory domain: knem"
```
AFTER:
```
$UCX_KNEM_RCACHE_OVERHEAD=16us ./src/tools/info/ucx_info -d | grep -A 3 "Memory domain: knem"
$UCX_KNEM_RCACHE=n ./src/tools/info/ucx_info -d | grep -A 3 "Memory domain: knem"
$./src/tools/info/ucx_info -d | grep -A 3 "Memory domain: knem"
```
=> UCT/MD/KNEM: Fix mem registration cost

src/tools/info/tl_info.c
Print memory invalidation cap in the output of ucx_info -d
```
$ucx_info -d | grep -A 5 "Memory domain: mlx5_0"
```
=> UCT/TOOLS: Print memory invalidate cap by ucx_info -d

bindings/go/Makefile.am
set GOCACHE to point to a local directory 
There are imported C APIs in bindings/go, if imported C APIs had change it would not be detected by GOCACHE and cause inconsistency and failure in CI.
From go help cache:
the build cache does not detect changes to C libraries imported with cgo. If you have made changes to the C libraries on your system, you will need to clean the cache explicitly or else use the -a build flag (see 'go help build') to force rebuilding of packages that depend on the updated C libraries.
set GOCACHE in CI to point to a local directory that is cleared for each job
=> BINDINGS/GO: set GOCACHE to point to a local directory

src/ucp/core/ucp_worker.c
Make sure not pending ops are scheduled if EP failed, but not under discarding.
To catch possible errors if we have some operations scheduled when UCP EP is marked as failed.
Invoke `uct_ep_pending_purge()` with purge callback which does `ucs_bug()`.
=> UCP/CORE: Make sure not pending ops are scheduled if EP failed, but not under discarding

buildlib/pr/go/go-test.yml
BINDINGS/GO: Increase port range + make it dependent from agent_id.
To fix failed pipelines like https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=31880&view=logs&j=3326af28-725b-5a76-d9b2-a6afcb2c442d&t=325b69bb-50d4-51fd-759e-eb1ff0fb9743&s=4d0c1fdc-6c5a-5c53-9fc6-e87124c468bb
=> BINDINGS/GO: Increase port range + make it dependent from agent_id.

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, test/gtest/ucp/test_ucp_sockaddr.cc
Fix EP refcount overflow.
Fixes:
```
[swx-ucx02:61382:0:61382] ucp_request.c:387  Assertion `(req->send.ep)->refcount < (255)' failed
/hpc/mtr_scrap/users/dmitrygla/ucx/src/ucp/core/ucp_request.c: [ ucp_request_dt_invalidate() ]
...
384
385     /* Do not allow destroying UCP endpoint, since the memeroy invalidation
386      * depends on it */
==>   387     ucp_ep_refcount_add(req->send.ep, invalidate);
388
389     req->send.state.uct_comp.count  = 1;
390     req->send.state.uct_comp.func   = ucp_request_mem_invalidate_completion;
==== backtrace (tid:  61382) ====
0 0x0000000000057b6c ucp_request_dt_invalidate()  /hpc/mtr_scrap/users/dmitrygla/ucx/src/ucp/core/ucp_request.c:387
1 0x000000000004b674 ucp_ep_req_purge_send()  /hpc/mtr_scrap/users/dmitrygla/ucx/src/ucp/core/ucp_ep.c:3145
2 …
```
=> UCP/CORE: Fix EP refcount overflow [v2]

src/uct/cuda/base/cuda_iface.h, src/uct/cuda/cuda_copy/cuda_copy_ep.c, src/uct/cuda/cuda_copy/cuda_copy_iface.c, src/uct/cuda/cuda_copy/cuda_copy_iface.h, src/uct/cuda/cuda_copy/cuda_copy_md.c, src/uct/cuda/cuda_ipc/cuda_ipc_cache.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/cuda/cuda_ipc/cuda_ipc_iface.h, test/gtest/common/mem_buffer.cc
- cache cuda context against which Stream/Event resources are created
- during cleanup, if calling thread has the ctx against which resources were allocated, then destroy Stream/Event resources
- Also, don't retain primary context even for cuMemAlloc. Assume higher layer sets the right context before making cuMemAlloc attempt
=> UCT/CUDA: cache cuda ctx and cleanup if correct ctx is set

test/gtest/ucp/test_ucp_sockaddr.cc
Add gtest cases to check UCX_IB_NUM_PATHS compatible.
UCX should work for the NICs with one or two interfaces. Add test cases into regular tests.
=> gtest to check UCX_IB_NUM_PATHS compatible

test/gtest/ucp/test_ucp_sockaddr.cc
Reduce testing time of invalidation test under Valgrind.
Fixes #7729 - It takes too much time for testing and the job was canceled.
Reduces testing time of some memory invalidation tests in `test_ucp_sockaddr_protocols_err_sender` test suite:
- before (376.7 seconds):
```
[ RUN      ] tcp/test_ucp_sockaddr_protocols_err_sender.tag_rndv_killed_sender_4_extra_senders_multiple_sends/0 <tcp,cuda_copy,rocm_copy/mt>
[     INFO ] server listening on 1.1.31.1:43814
[     INFO ] ignoring error Endpoint timeout on endpoint 0xc622000
[       OK ] tcp/test_ucp_sockaddr_protocols_err_sender.tag_rndv_killed_sender_4_extra_senders_multiple_sends/0 (376679 ms)
[----------] 1 test from tcp/test_ucp_sockaddr_protocols_err_sender (376699 ms total)
```
- after (3.1 seconds):
```
[ RUN      ] …
```
=> GTEST/UCP: Reduce testing time of invalidation test under Valgrind

src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5_log.c
Choose PKEY index 0 for RoCE devices.
RoCE devices have `0xffff` PKEY set for index `0`.
Other indices are invalid.
When initializing PKEY, check for RoCE and select PKEY index `0` and PKEY value `0xffff` if the device is RoCE.
=> UCT/IB: Choose PKEY index 0 for RoCE devices

src/uct/ib/base/ib_device.h, src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/mlx5/dv/ib_mlx5_dv.c, src/uct/ib/mlx5/ib_mlx5.c, src/uct/ib/mlx5/ib_mlx5_log.c
Porting #7724 to v1.12.x
Choose PKEY index 0 for RoCE devices.
RoCE devices have `0xffff` PKEY set for index `0`.
Other indices are invalid.
When initializing PKEY, check for RoCE and select PKEY index `0` and PKEY value `0xffff` if the device is RoCE.
=> UCT/IB: Choose PKEY index 0 for RoCE devices [v1.12]

src/uct/api/uct_def.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/base/rc_iface.h, src/uct/ib/rc/verbs/rc_verbs_iface.c, test/gtest/uct/test_peer_failure.cc, test/gtest/uct/test_peer_failure.h
Fix purging of pending requests after error handling in DC, RC MLX5/Verbs.
Fixes "timeout waiting for <N> replies" issues found by IO-demo testing. It happens that FLUSH_CANCEL couldn't be done and discarding of UCT EP was added to the pending queue. And discarding of this UCT EP is no longer completed.
The issue above happens because purging of requests scheduled on UCT EP doesn't work if UCT EP detects an error.
Descheduling of UCT EP arbiter group was added in https://github.com/openucx/ucx/pull/6549 PR to not invoke pending callback for a failed UCT EP, but https://github.com/openucx/ucx/pull/7080 PR removes dispatching arbiter when updating TX resources. So, it is no longer needed.
Also, UCP EP is able to handle purging of discarding operation when detecting error - it was …
=> UCT/IB: Fix purging of pending requests after error handling

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs_iface.c
Purge internal pending ops to avoid dispatching them when EP failed.
Fixes:
```
[swx-ucx08:862  :0:862]   rc_mlx5.inl:457  Assertion `!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED)' failed
/hpc/mtr_scrap/users/dmitrygla/ucx/src/uct/ib/rc/accel/rc_mlx5.inl: [ uct_rc_mlx5_common_post_send() ]
...
454     if (opcode != MLX5_OPCODE_NOP) {
455         /* If FAILED, allow only NOP sends to be posted (used by endpoint
456          * flush operations) */
==>   457         ucs_assert(!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED));
458     }
459
460     ctrl = txwq->curr;
==== backtrace (tid:    862) ====
0 0x0000000000089e48 uct_rc_mlx5_common_post_send()  /hpc/mtr_scrap/users/dmitrygla/ucx/src/uct/ib/rc/accel/rc_mlx5.inl:457
1 0x0000000000089e48 uct_rc_mlx5_txqp_inline_post() …
```
=> UCT/IB/DC/RC: Purge internal pending ops to avoid dispatching them when EP failed

config/m4/sysdep.m4, src/ucs/arch/ppc64/cpu.h, src/ucs/arch/ppc64/timebase.c
- removed double check for __ppc_get_timebase_freq function
=> PPC/UCS: removed extra check for __ppc_get_timebase_freq

src/tools/perf/cuda/cuda_alloc.c
Similar to https://github.com/openucx/ucx/pull/7679/files#diff-b1631cb616b57b17879df7eac53787b13fabb97c13f98e08f6ede217ad701371R124. Without this `ucx_perftest` with `-m cuda` were failing as perf allocator calls failed.
=> TOOLS/PERF: use cudaFree to set context and avoid cuda perftest failures

NEWS
- Port list of features and bugfixes introduced in 1.11.1 and 1.11.2 to master
- Remove obsolete info from the `current` section (already covered by 1.11 release listing)
=> NEWS: Porting news from 1.11.x to master

test/gtest/ucs/test_memtype_cache.cc
Fix memtype cache testing.
Fixes #7745.
Update `init()` function of `test_memtype_cache` test suite to allocate `mem_buffer` on HOST and call `test_lookup_notfound()` to allocate global memory cache for further successful adding elements.
=> GTEST/UCS: Fix memtype cache testing

src/ucp/core/ucp_context.h, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/uct/cuda/cuda_copy/cuda_copy_ep.c
Fix memory cache lookup return value handling.
The return value could be either `UCS_OK` or `UCS_ERR_NO_ELEM`.
1. Re-organize the code of branches.
2. Add useful assertions.
3. Remove incorrect assertion.
4. Remove extra brackets around a condition.
=> UCP/CORE: Fix memory cache lookup return value handling

src/ucp/api/ucp.h, test/gtest/ucp/test_ucp_am.cc, test/gtest/ucp/test_ucp_tag.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Optimization for zero-copy path, first stage of FR [internal link](https://redmine.mellanox.com/issues/2770592)
Allow passing pre-registered memory handle as a hint, to avoid memory cache lookup overhead.
This PR adds API and gtests veriants for active message and tag-match, the implementation will be in a follow-up PR.
Active message tests were changed so all tests will run with and without pre-registration. So the test variant indexes had to be changed (add 1) since variant 0 is for prereg flag.
Replaces #7345
=> UCP/TEST: API to pass pre-registered memory handle to UCP operations

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5_iface.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/base/rc_iface.c, src/uct/ib/rc/verbs/rc_verbs_iface.c
Restore FC window size in case of error was detected.
To allow rescheduling DCI allocation for failed EP to do some pending operations (e.g. UCT EP flush(CANCEL)).
1. Introduce `UCT_RC_RESTORE_FC_WND` to use it for restoring RC/DC FC window size.
2. Use `UCT_RC_RESTORE_FC_WND` to restore the window in case of error happened on DC.
3. Do `uct_dc_mlx5_iface_set_ep_failed` before `uct_dc_mlx5_iface_dci_put` to ensure restoring FC window.
=> UCT/IB/DC: Restore FC window size in case of error was detected

src/ucs/stats/stats.h, src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/dc/dc_mlx5_ep.h, src/uct/ib/rc/accel/rc_mlx5_ep.c, src/uct/ib/rc/base/rc_ep.c, src/uct/ib/rc/base/rc_ep.h, src/uct/ib/rc/verbs/rc_verbs_ep.c
Update FC to not allocate statistics if FC is disabled.
1. Don't allocate unnecessary memory for statistics.
2. Remove `if` from `UCT_RC_UPDATE_FC_WND` macro.
1. Introduce some helpful macro in `UCS_STATS_NODE_*` to use them for manipulation with FC statistic node.
2. Remove `iface` parameter from `UCT_RC_UPDATE_FC_WND` and `UCT_RC_UPDATE_FC` macros.
=> UCT/IB/RC/STATS: Update FC to not allocate statistics if FC is disabled

src/uct/ib/ud/base/ud_ep.c, src/uct/tcp/tcp_ep.c
1. Don't purge pending requests during `flush(CANCEL)` in TCP and UD transports.
2. Complete all outstanding operations in TCP transport.
1. Purging of pending requests mustn't be done since a user could potentially have some pending operations which are not TX.
2. Need to stop in-progress operations to not progress them anymore.
1. Remove calling `uct_ep_pending_purge()` from TCP's and UD's `uct_ep_flush(CANCEL)`.
2. Call `uct_tcp_ep_purge()` which stops TX operations and completes all outstanding Zcopy operations..
=> UCT/TCP/UD: Don't purge pending requests during flush(CANCEL)

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h, src/ucp/rndv/rndv.c
Option to avoid GPUDirectRDMA on large messages rndv
or mem type, Ignore mem type GDR lane while initializing the lanes for zcopy if the length of the zcopy is greater than the threshold,
=> UCP/RNDV: Option to limit GPUDirectRDMA size in rndv

src/ucm/malloc/malloc_hook.c, src/ucm/malloc/malloc_hook.h, src/ucm/util/log.c, src/ucm/util/log.h, src/ucm/util/reloc.c, src/ucm/util/sys.c, src/ucs/datastruct/khash.h, test/gtest/Makefile.am, test/gtest/ucs/test_khash.cc
- use single constructor entry to initialize UCM
- as part of activiti for UCX static build
- use direct calls of initialisation routines
=> UCM/INIT: use single constructor entry

src/ucp/core/ucp_request.c
Porting #7649 to v1.12.x.
Handle ACK wireup msg which passed to UCT directly.
Fixes #7648
Allow `WIREUP_MSG/ACK` to be purged from UCT transport directly.
=> UCP/WIREUP: Handle ACK wireup msg which passed to UCT directly [v1.12.x]

docs/CodeStyle.md
Add C++11 usage for google tests in the code style guide.
Improve the code by making use of advanced language features.
=> DOCS: Add C++11 usage for tests

src/uct/ib/rc/accel/rc_mlx5_ep.c
Always use `sig_pi` when flushing.
`sig_pi` after sending NO-OP has the same value as `sw_pi` before sending NO-OP.
So, use `sig_pi` in both cases (neither has signaled operations or doesn't have) for simplicity reason.
1. Remove declaration of `sn`.
2. Use directly `ep->tx.wq.sig_pi` when initializing flush completion.
=> UCT/UB/RC_MXL5: Always use sig_pi when flushing

src/uct/ib/dc/dc_mlx5_ep.c, src/uct/ib/rc/accel/rc_mlx5_ep.c
Don't check FC resources in case of `flush(CANCEL)`.
It aligns DC's `flush(CANCEL)` with RC's one.
If `flush(CANCEL)` was issued when no error detected by the transport, but FC window is exhausted, `flush(CANCEL)` may be completed with `UCS_ERR_NO_RESOURCE` forever, since peer doesn't update our resources.
1. Update `uct_dc_mlx5_iface_dci_ep_can_send` to accept `flush_cancel` boolean value.
2. Use `flush_cancel` boolean value to check whether we need to verify FC window or not.
=> UCT/IB/RC/DC: Don't check FC resources in case of flush(CANCEL)

NEWS
- News update for v.1.12.0 release
- Porting v.1.11.x news from v.1.11.x branch
Release preparation
Comparing v1.11.x and v1.12.x branches
=> NEWS: News update for v1.12.0 rc1

src/ucs/memory/rcache.c, src/ucs/memory/rcache_int.h
Removed field representing number of regions in list from ucs_rcache.lru structure.
Code cleanup. There is no need to have separate structure field to count items in list. It is used only in warning text message.
=> UCS/MEMORY: Removed redundant field from ucs_rcache structure.

src/uct/tcp/tcp_sockcm.c
Fixed TCP CM implementation of query attributes from UCT endpoint.
Query local/remote socket address only if appropriate flag is set.
=> UCT/TCP: Query local/remote saddr only if appropriate flag is set.

src/ucp/api/ucp.h, src/ucp/api/ucp_def.h, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, src/uct/api/uct.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c, src/uct/tcp/tcp_sockcm_ep.c, test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc, test/apps/iodemo/ucx_wrapper.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/uct/ib/test_sockaddr.cc, test/gtest/uct/uct_test.cc, test/gtest/uct/uct_test.h
What
support selecting local address for each connection
Why ?
if users have multiple HCAs on client side, they can select the NIC they want to use (round robin fashion for example)
How ?
specify local address in ucp_ep_params when call ucp_ep_create() for each connection
=> UCP/EP: support selecting local address for each connection

bindings/java/src/main/native/context.cc
Fix missed error  - if ucp_mem_query() fails, need to throw Java exception
ported from #7345
=> JAVA: Throw exception if ucp_mem_query failed

src/ucp/core/ucp_worker.c, test/gtest/common/test.h, test/gtest/ucp/test_ucp_am.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Fix #7782 
Do not call setenv() while UD progress thread may call getenv() through strerror()
If we can ignore non-existing variables, might as well use ucp_config_modify() that also sets uct/ucs params [and ignore its return value] rather than ucp_config_modify_internal()
=> TEST/UCP: Avoid setenv()/genenv() race

src/uct/ib/rdmacm/rdmacm_cm.c
The client error when no listener exists on server side should be CONNECTION_RESET and not UNREACHABLE
(Issue was found when testing ucx-py)
=> UCT/RDMACM: Fix error status in case of network reject

buildlib/azure-pipelines-release.yml, buildlib/dockers/docker-compose.yml, buildlib/dockers/ubuntu-release.Dockerfile
Fail release pipeline 
ubuntu want to check libnvidia-ml.so libs 
libnvidia-ml.so is kernel driver 
and need to create stub link
=> AZP/RELEASE: Add link to libnvidia-ml.so

buildlib/azure-pipelines-release.yml, buildlib/dockers/docker-compose.yml, buildlib/dockers/ubuntu-release.Dockerfile
Fail release pipeline 
ubuntu want to check libnvidia-ml.so libs 
libnvidia-ml.so is kernel driver 
and need to create stub link
=> AZP/RELEASE: Add link to libnvidia-ml.so - v1.12.x

src/uct/ib/mlx5/ib_mlx5_log.c
Log WQE details in responder error.
Sample output:
```
[jazz13:26543:0:26543] ib_mlx5_log.c:181  strides 1 next wqe 1 desc 0x7faabddfcb9e [seg 0 bytes 8256 lkey 0x12345678 addr 0x7faabddfcc00] on mlx5_0:1/IB (synd 0x4 vend 0x32 hw_synd 0/146)
```
Improve logs verbosity.
=> UCT/IB/MLX5: Improve responder errors logging

src/uct/ib/rc/accel/rc_mlx5_common.c, test/gtest/ucp/test_ucp_tag_offload.cc
- Enable tag offload for small (inlined) data
- Update some tests to use small value 
memcpy was removed from UCT, now it is handled correctly in UCP.
If data scattered to CQE, the CQE pointer will be provided to UCP and unpacked according to 
set min_recv capability of UCT iface to 0
(rollback #5188)
=> UCT/GTEST: Enable tag offload recv for inlined data

src/uct/ib/dc/dc_mlx5_ep.c
Remove extra removing of EP from FC hash.
This is not needed, since removing of EP from FC hash was done in `uct_dc_mlx5_ep_fc_cleanup` function.
Remove unneeded `kh_get` and `kh_del` in DC_MLX5 EP clenup function.
=> UCT/IB/DC: Remove extra removing of EP from FC hash

config/m4/compiler.m4, src/tools/perf/Makefile.am, src/tools/perf/lib/uct_tests.cc, test/gtest/Makefile.am, test/gtest/common/googletest/Makefile.am, test/gtest/common/test.h
allowing replace of clang's unsupported -dynamic-list-data flag and replacing it with supported -dynamic-list
allowing clean clang builds
=> replace -dynamic-list-data if unsupported

buildlib/pr/io_demo/az-stage-io-demo.yaml
Allow running CI manually, and not only as PR trigger
Don't try to use `$(System.PullRequest.TargetBranch)` if it's not defined
=> AZP/IODEMO: Don't pass allow-list if no target branch

test/gtest/ucp/test_ucp_sockaddr.cc
Fix sockaddr gtest usage of recv buffer.
1. Fixes possible receive to already released buffer.
2. Fixes passing `recv_buf.ptr()` instead of `recv_buf` as user_data for receive operation.
1. Introduce ptr_vector which holds all receive buffers, allocate `mem_buffer` for receive buffers on the heap.
2. Replace `recv_buf.ptr()` by `recv_buf` when calling `recv()`.
=> GTEST/UCP: Fix sockaddr gtest usage of recv buffer

src/uct/ib/rdmacm/rdmacm_cm.c, src/uct/ib/rdmacm/rdmacm_cm.h, src/uct/ib/rdmacm/rdmacm_cm_ep.c
Add warning if some dummy QPs weren't destroyed.
To investigate #7680 issue which fails on CI testing of the master branch from time to time.
1. Add `num_dummy_qps` field to RDMACM device context structure.
2. Every time when dummy QP is created, increment it.
3. Every time when dummy QP is destroyed, decrement it.
4. Check if `num_dummy_qps` is `0` when destroying RDMACM device context.
5. Simplification of the code by not calling `uct_rdamcm_cm_ep_destroy_qpn()` if QPN hasn't been set yet.
=> UCT/RDMACM: Add warning if some dummy QPs weren't destroyed

src/uct/ib/base/ib_iface.c, src/uct/ib/base/ib_iface.h, src/uct/ib/dc/dc_mlx5_devx.c, src/uct/ib/rc/accel/rc_mlx5_devx.c
Remove device parameter from `uct_ib_iface_is_roce_v2` function.
The parameter `dev` is not used.
1. Remove `dev` from `uct_ib_iface_is_roce_v2` function declaration.
2. Fix all occurencies of `uct_ib_iface_is_roce_v2` function where `dev` is passed.
=> UCT/IB: Remove device parameter from is_roce_v2 function

src/uct/rocm/ipc/rocm_ipc_cache.c
- there was incorrect calculation of page range to invalidate:
could be additional range invalidated
=> IPC/CACHE: fixed range for invalidate page lookup

test/apps/iodemo/io_demo.cc, test/apps/iodemo/ucx_wrapper.cc
Remove excessive is_rndv branches in AM.
No need to check `is_rndv` prior calling `recv_am_data` method, since it is called inside `recv_am_data` method.
Remove branch `!ucx_am_is_rndv(data_desc)` and its body.
=> APPS/IO-DEMO: Remove excessive is_rndv branches in AM

src/ucp/api/ucp_def.h
PR #7623 breaks UCX ABI because the new field local_sockaddr was added to the middle of ucp_ep_params_t struct. Need to move it to the end.
It will ABI-break any application that uses conn_request or name fields (so pretty much any client/server application)
Fixes #7822
move local_sockaddr to the end of ucp_ep_params_t.
=> UCP/EP: move local_sockaddr to end of ucp_ep_params_t to fix ABI break

src/uct/ib/base/ib_iface.c
=> UCT/IB: Detect NDR - v1.12.x

src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_ep.h, src/uct/sm/scopy/cma/cma_ep.c, src/uct/sm/scopy/cma/cma_ep.h, test/gtest/uct/test_peer_failure.cc
Implement intra-node keep-alive protocol based on _startime_ value from _/proc/pid/stat_
The current implementation relies on stat() info performed on /proc/pid dir. This is incorrect, because the files in /proc have no existence of their own, and the info returned by stat() is not persistent.
=> UCT/SM/CUDA: Fix common intra-node keepalive protocol

src/ucp/core/ucp_request.inl
Take alignment from the corresponding parameter in `ucp_recv_desc_init` (rather than from the worker directly) 
Fix typo, need to take alignment from argument (worker alignment is required for UCP AM only)
=> UCP/TAG/AM: Use alignment param for UCT AM rdesc init

src/ucp/core/ucp_am.c, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_request.c, src/ucp/core/ucp_request.h, src/ucp/core/ucp_request.inl, src/ucp/rndv/rndv.c, src/ucp/rndv/rndv.h, src/ucp/stream/stream_send.c, src/ucp/tag/eager_snd.c, src/ucp/tag/offload.c, src/ucp/tag/offload.h, src/ucp/tag/tag_recv.c, src/ucp/tag/tag_rndv.c, src/ucp/tag/tag_rndv.h, src/ucp/tag/tag_send.c
Implement the performance optimization of passing user pre-registered memory handle, and bypassing registration cache lookup.
- send: copy UCT handles from memo to dt_reg during send request initialization
- recv: cache memh in req->recv.user_memh, and copy it to dt_reg when we start a zero-copy rondo protocol and already know the relevant lanes and mds. it's done when starting ram_get and when sending RTR with keys to trigger ram_put (from sender).
Note: Need to retest after #7761 is merged
=> UCP: Implement passing user memh in proto_v1

src/ucp/tag/eager_rcv.c, src/ucp/tag/probe.c, src/ucp/tag/tag_match.inl, src/ucp/tag/tag_recv.c, test/gtest/ucp/test_ucp_tag_offload.cc
1. Roll-back changes fixing the probe for multi-eager offload flow
When the first eager offload fragment arrives it needs to be handled immediately, which means that expected queue must searched for a match, if no match - fragment needs to be added to the unexpected queue. Otherwise, HW vs SW conflict may be provoked, e.g. like described below:
1. First fragment arrives, there is not match in the expected queue and it is not added to the unexpected queue (waiting for the rest of fragments)
2. User invokes `ucp_tag_recv_nb` operation, which in turn invokes `uct_iface_tag_recv_zcopy` and this synchronize SW and HW unexpected counters. Now all incoming messages will be inspected for a match in the HW tag list
3. Another `ucp_tag_recv_nb` is posted by the user
4. Last fragment for the message …
=> UCP/TAG: Refactor multi offload flow (fix HW and SW counters conflict)

src/uct/tcp/tcp.h, src/uct/tcp/tcp_cm.c, src/uct/tcp/tcp_ep.c, test/gtest/ucp/test_ucp_wireup.cc
Fix having UCT EP pairs with only RX capability.
It might happen that UCT EP pairs with only RX capability remain functional, but they can do nothing since a user don't know about them.
The following situation leads to this:
- UCT_EP was created by a user on peer1
- UCT_EP was created by a user on peer2
- UCT_EP_1 and UCT_EP_2 are connected to each other
- `uct_ep_destroy()` was invoked for UCT_EP_1 - it wasn't destroyed, since it has RX capability
- `uct_ep_destroy()` was invoked for UCT_EP_2 - it wasn't destroyed, since it has RX capability
- UCT_EP_1 and UCT_EP_2 will live forever until either peer1 or peer2 will destroy UCT IFACE.
1. Introduce new connection event - `UCT_TCP_CM_CONN_FIN`.
2. Update `uct_tcp_cm_trace_conn_pkt()` function to support `UCT_TCP_CM_CONN_FIN` and simplify it …
=> UCT/TCP: Fix having UCT EP pairs with only RX capability

src/uct/ib/base/ib_iface.c
=> UCT/IB: Detect NDR - v1.11

src/ucp/am/eager.c, src/ucp/core/ucp_ep.c, src/ucp/proto/proto.h, src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_reconfig.c, src/ucp/rma/amo_sw.c, src/ucp/rma/get_am.c, src/ucp/rma/get_offload.c, src/ucp/rma/put_am.c, src/ucp/rma/put_offload.c, src/ucp/rndv/proto_rndv.inl, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_ppln.c, src/ucp/rndv/rndv_put.c, src/ucp/rndv/rndv_rkey_ptr.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload/eager.c, src/ucp/tag/tag_rndv.c
- infrastructure for error handling of new protocols
- ucp_rndv_get_zcopy_proto
- ucp_tag_rndv_proto
- ucp_eager_short_proto
- ucp_eager_bcopy_single_proto
- ucp_put_am_bcopy_proto
- ucp_put_offload_bcopy_proto
- ucp_put_offload_zcopy_proto
error handling support in new protocols
`ucp_proto_t::abort`
```
UCX_PROTO_ENABLE=y test/gtest/gtest --gtest_filter=*test_ucp_peer_failure*:-*kill_receiver/0:*kill_receiver/1:*force_close/0:*force_close/2:*zcopy/0:*zcopy/2 --gtest_break_on_failure --gtest_shuffle
```
passed on jazz, skipped tests are AM/RNDV which is not implemented
=> UCP/PROTO: error handling

NEWS, src/ucp/tag/tag_send.c
- added slow path where datatype is processed
back port from https://github.com/openucx/ucx/pull/7766
(cherry picked from commit fc4e270cbe355dd6c30c611d2247adab3ae2609f)
=> UCP/TAG/SEND: fixed datatype issue - v1.12

NEWS, src/ucs/sys/sys.c, src/ucs/sys/sys.h, src/uct/base/uct_iface.c, src/uct/base/uct_iface.h, src/uct/cuda/cuda_ipc/cuda_ipc_ep.c, src/uct/cuda/cuda_ipc/cuda_ipc_ep.h, src/uct/sm/mm/base/mm_ep.c, src/uct/sm/mm/base/mm_ep.h, src/uct/sm/scopy/cma/cma_ep.c, src/uct/sm/scopy/cma/cma_ep.h, test/gtest/uct/test_peer_failure.cc
backport of #7780 to v1.12.x branch
(Implement intra-node keep-alive protocol based on startime value from /proc/pid/stat)
=> UCT/SM/CUDA: Fix common intra-node keepalive protocol - v1.12.x

test/gtest/ucp/test_ucp_sockaddr.cc
Add gtests for testing AM RNDV in sockaddr.
To cover AM RNDV functionality.
Fixes #7825
1. Handle RNDV data in AM receive callback.
2. Add testing of the following scenarios in test_ucp_sockaddr_protocols:
- 1 KB
- 64 KB
- 2 MB
=> GTEST/UCP: Add AM RNDV gtest

configure.ac, src/tools/info/build_info.c, src/uct/api/version.h.in, ucx.pc.in
- Print branch information in ucx_info
- Allow embedding custom version string in the UCX version string
=> BUILD/TOOLS/INFO: Add extra version information

src/uct/ib/base/ib_iface.c
Fallback to default port speed (instead of failing) when encountering an unsupported port speed value.
This allows older versions of UCX to work on newer hardware, even if not perfectly.
=> UCT/IB: Fallback to SDR if port speed not detected

src/ucp/core/ucp_request.h, src/ucp/tag/eager_rcv.c, src/ucp/tag/probe.c, test/gtest/ucp/test_ucp_tag_offload.cc
Fix `ucp_tag_probe_nb()` for multi-fragment eager protocol with tag offload
With tag_offload and multi eager the total message length is not known until all fragments arrive, because there is no room for the `total_length` in tag offload headers. Thus, without this fix, probe returns incorrect length for any found/probed message which is not fully arrived yet.
1. Set `UCP_RECV_DESC_FLAG_RECV_STARTED` flag for the first eager fragment and clear it when the last fragment arrives.
2. When probe finds some message (note that only first fragments are added to the unexpected queue), this flag is checked. If it is present, the total_length is not known yet and probe returns `NULL`. Once it is cleared, it is safe to return the `rdesc`  from the probe
3. This should not introduce any ordering …
=> UCP/TAG: Fix probe for multi-fragment eager

docs/doxygen/header.tex.in
Workaround "Undefined control sequence" error in doxygen doc generation, ref: doxygen/doxygen#7609
=> DOCS/DOXYGEN: Fix PDF generation with doxygen 2019

src/uct/ib/rc/accel/rc_mlx5_common.c
Try using MP XRQ by default
Using MP XRQ improves tag offload performance and memory consumption.
It was disabled because of the bug fixed by #7849
=> UCT/TAG: Try using MP XRQ by default

src/ucp/api/ucp_def.h, src/ucp/core/ucp_am.c, test/apps/iodemo/ucx_wrapper.cc, test/gtest/ucp/test_ucp_am.cc
Replace using `UCP_AM_SEND_REPLY` by `UCP_AM_SEND_FLAG_REPLY`.
`UCP_AM_SEND_REPLY` is a part `ucp_send_am_flags_t` for backward compatibility.
Use `UCP_AM_SEND_FLAG_REPLY` instead of `UCP_AM_SEND_REPLY`.
=> UCP/CORE/TEST: Replace using UCP_AM_SEND_REPLY by UCP_AM_SEND_FLAG_REPLY

src/ucm/api/ucm.h, src/ucm/event/event.c, src/ucs/Makefile.am, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/parser.h, src/ucs/config/ucm_opts.c, src/ucs/config/ucm_opts.h, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/ucs/sys/init.c, src/ucs/vfs/fuse/vfs_fuse.c, test/mpi/test_memhooks.c
- use single constructor/destructor entry to initialize UCS
- as part of activiti for UCX static build
- use direct calls of initialisation routines
=> UCS/INIT: use single constructor entry

src/uct/ib/ud/base/ud_ep.c, src/uct/ib/ud/base/ud_iface.c
Fix leak warning about ep_removed flush request (added by `ucp_wireup_send_ep_removed`, when the worker is destroyed. 
Fix test [failures](https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=35167&view=logs&j=73bd2a9e-6688-5c22-d122-7b1a0b6cbb81&t=cd3d3953-51ff-5d5c-c5ca-2864f3c1d670&s=8bfbeaae-4c8e-5f12-f154-edd305817000) like:
```
2022-01-17T17:25:13.3034557Z [ RUN      ] udx/test_ucp_wireup_errh_peer.stress_connect_force_disconnect/2 <ud_x/rma,no_ep_match>
2022-01-17T17:25:13.8430781Z [1642440313.842728] [swx-rdmz-ucx-gpu-01:5074 :0]           mpool.c:54   UCX  WARN  object 0x5494b40 {flags:0x200002 <no debug info>} was not returned to mpool ucp_requests
2022-01-17T17:25:13.8687245Z /scrap/azure/agent-11/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:344: Failure …
```
=> UCT/UD: Fix completion callback not called for flush operation

buildlib/azure-pipelines-pr.yml, contrib/check_qps.sh
Fix name of VFS in QPs check script.
1. It should be "VFS" instead of "CFS".
2. Use default path "/tmp/ucx" from variable instead of duplication.
1. Replace "VFS" by "CFS".
2. Print `${VFS_UCX_PATH}` instead of `/tmp/ucx`.
3. Excluded `contrib/check_qps.sh` from AZP CI.
=> CONTRIB/SCRIPTS: Fix name of VFS in QPs check script

src/ucp/api/ucp.h, src/ucp/core/ucp_am.c, src/ucp/core/ucp_am.h, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.c, test/gtest/ucp/test_ucp_am.cc
Support aligning AM data by a custom user-provided offset.
Configuration flexibility: allow aligning the UCT memory pool element, instead of aligning the data.
=> UCP/CORE: Support AM align offset

src/ucm/bistro/bistro_x86_64.c, src/ucm/bistro/bistro_x86_64.h, src/ucm/util/log.c, test/apps/test_cuda_hook.c
Fix the issue described in https://github.com/openucx/ucx/pull/7791#issuecomment-1016719453
Bistro to handle functions that begin with a compare and short conditional jump, when need to jump more than 32-bit distance from the patched function to the hook code.
- Decrease patch size for long jump from 13 bytes to 12 bytes by using rax (caller-saved) register instead of r11
- Translate a short jump to a long 64-bit jump (from hook code back to the original function), and make sure we don't overwrite more than the jump target
=> UCM/BISTRO: Translate relative jumps

src/uct/ib/dc/dc_mlx5.c
Fix below RoCE LAG case when creating DCI under DEVX:
```
uct_dc_mlx5_iface_create_dci
|--> uct_ib_mlx5_devx_create_qp
|--> uct_dc_mlx5_iface_dci_connect
|--> uct_dc_mlx5_iface_devx_dci_connect
|--> uct_ib_mlx5_devx_set_qpc_port_affinity(dci->path_index)
|--> dci->path_index = path_index
```
Correct set dci port affinity
It should use right value to set dci port affinity
assign value to dci->path_index before using it.
=> UCT/DC: initialize dci->path_index before setting port affinity

src/uct/ib/mlx5/dv/ib_mlx5_dv.c
In uct_ib_mlx5_devx_query_qp, use uct_ib_mlx5_query_qp_out_bits to get syndrome instead of uct_ib_mlx5_modify_qp_out_bits
=> UCT/IB: correct data structure to get member value

src/ucp/core/ucp_mm.c, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/uct/cuda/base/cuda_md.c, test/gtest/ucs/test_memtype_cache.cc
Fix #7575 
The issue was that whole-alloc logic returned wrong region boundaries, so the registered memory did not contain the actual communication buffer.
- Track merged memtype cache region range by start/end only; drop base_addr/alloc_length
- Assert that "whole-alloc" really returns a region that contains the original one
- Add logging
Currently, the test case fails with ibv_reg_mr: Bad address, instead of Local protection error, but it could be a driver issue. Reproducer:
```
$ ssh swx-dgx01
$ conda activate ucx
$ env UCX_MEMTYPE_CACHE=y UCX_MAX_RNDV_RAILS=1 UCX_MEMTYPE_REG_WHOLE_ALLOC_TYPES=cuda \
python dask_cuda/benchmarks/local_cudf_merge.py -d 0,1,2,3,4,5,6,7 --runs 5 -c 100_000_000 -p ucx \
--interface ib0 --enable-nvlink --enable-infiniband --enable-rdmacm
```
=> UCP/UCS/UCT: Fix memtype_cache region info after merge

test/gtest/common/test_helpers.cc, test/gtest/common/test_helpers.h, test/gtest/ucp/test_ucp_sockaddr.cc, test/gtest/uct/test_md.cc, test/gtest/uct/uct_test.cc
Fix test failures when docker instances run on the same machine and create temporary bridge interfaces.
Prevent sockaddr gtests from running on bridge interfaces
=> TEST/GTEST: Don't run sockaddr tests on bridge interfaces

src/uct/api/uct.h
What
[PR #7623](https://github.com/openucx/ucx/pull/7623) breaks UCT ABI because the new field local_sockaddr was added to the middle of uct_ep_params_t struct. Need to move it to the end.
Why ?
Fix UCT ABI break
How ?
move local_sockaddr to the end of uct_ep_params_t.
=> UCT/EP: move local_sockaddr to end of uct_ep_params_t to fix ABI break

NEWS, src/ucm/bistro/bistro_x86_64.c, src/ucm/bistro/bistro_x86_64.h, src/ucm/util/log.c, test/apps/test_cuda_hook.c
=> UCM/BISTRO: Translate relative jumps - v1.12.x

src/ucs/config/parser.c
Closes https://github.com/openucx/ucx/issues/7874.
Fix a bug, lib file path was used instead of its dir.
=> UCS/CONFIG: Fix config file lookup

test/apps/iodemo/io_demo.cc
Print per-connection info in this format:
[1643264984.412080] [UCX-connection 0x675a60: #1 192.168.30.6:1337] read 744.076MBs iops: 190483 | write 744.057MBs iops: 190478 | total 1488.13MBs iops: 380962
[1643264984.412096] [UCX-connection 0x675f50: #2 192.168.30.6:1337] read 744.069MBs iops: 190481 | write 744.065MBs iops: 190480 | total 1488.13MBs iops: 380962
Sometimes we need analyse performance on per-connection basis.
=> APPS/IODEMO: print per-connection info

NEWS, src/ucp/core/ucp_mm.c, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/uct/cuda/base/cuda_md.c, test/gtest/ucs/test_memtype_cache.cc
Backport #7791
Fixes #7863 
No conflicts, added NEWS entry
=> UCP/UCS/UCT: Fix memtype_cache region info after merge - v1.12.x

src/uct/base/uct_component.h, src/uct/base/uct_iface.h, src/uct/sm/mm/base/mm_iface.h, src/uct/sm/mm/base/mm_md.h, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c, src/uct/sm/mm/xpmem/mm_xpmem.c, src/uct/sm/scopy/cma/cma_iface.c, src/uct/sm/scopy/cma/cma_md.c, src/uct/sm/scopy/knem/knem_iface.c, src/uct/sm/scopy/knem/knem_md.c
- implemented single constructor entries for
SM modules: posix, sysv, xpmem, cma, knem
=> UCT/SM: refactoring for SM modules initialization

src/ucp/core/ucp_worker.c, test/gtest/ucp/test_ucp_peer_failure.cc, test/gtest/ucp/ucp_test.cc, test/gtest/ucp/ucp_test.h
Drain keeplive `timerfd` to not trigger unnecessary events on user's fd.
Fixes #7864.
`timerfd`  should be drained by doing 64-bit `read()` to not re-trigger events.
1. Update keepalive gtest to reproduce the issue by draining wakeup FD after detecting error and closing fdailed EP.
2. Added `ucp_worker_fd_read()`, used it for `eventfd`.
3. Made keepalive `timerfd` non-blocking, to call `read()` in non-blocking manner inside `ucp_worker_do_keepalive_progress()`.
4. Used `ucp_worker_fd_read()` in a loop while `status == UCS_ERR_BUSY` to drain keepalive `timerfd`.
5. If wakeup feature is used, use `ucp_worker_do_keepalive_progress()` directly instead of `ucp_worker_keepalive_progress()` which skips some keepalive attempts.
=> UCP/CORE/GTEST: Drain keeplive timer fd to not trigger unnecessary events on user's fd

src/ucp/wireup/address.c
Fix parsing AM_ONLY flag from the header of a worker address.
`UCP_ADDRESS_HEADER_FLAG_AM_ONLY`  and other flags packed to the header in case of address_v1, but packed after header in case of address_v2.
1. Update `ucp_address_is_am_only` function to unpack header and get `addr_flags` and `addr_version` from it.
2. Check that `addr_flags` has `UCP_ADDRESS_HEADER_FLAG_AM_ONLY` bit set.
=> UCP/WIREUP: Fix parsing AM_ONLY flag from the header of a worker address

NEWS, src/ucp/core/ucp_worker.c
ported only UCP changes from #7868
=> UCP/CORE: Drain keeplive timer fd to not trigger unnecessary events on user's fd [v1.12.x]

src/ucp/core/ucp_worker.c
Revert change in function declaration of doing KA progress.
This unneeded change was introduced in #7868.
Replace by the previous declaration of `ucp_worker_do_keepalive_progress`.
=> UCP/CORE: Revert change in function declaration of doing KA progress

src/uct/tcp/tcp_cm.c
Fix error logging for sending CM packet.
Fixes #7890
If the error logging is requested and `(status != UCS_ERR_CANCELED)` it should print the trace using `UCS_LOG_LEVEL_ERROR`, otherwise - `UCS_LOG_LEVEL_DEBUG`.
=> UCT/TCP: Fix error logging for sending CM packet

src/ucp/Makefile.am, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_request.c, src/ucp/core/ucp_rkey.c, src/ucp/core/ucp_rkey.h, src/ucp/proto/proto_common.c, src/ucp/proto/proto_common.h, src/ucp/proto/proto_debug.c, src/ucp/proto/proto_debug.h, src/ucp/proto/proto_init.c, src/ucp/proto/proto_multi.c, src/ucp/proto/proto_select.c, src/ucp/proto/proto_select.h, src/ucp/proto/proto_select.inl, src/ucp/rndv/proto_rndv.c, src/ucp/rndv/rndv_ppln.c, test/gtest/ucp/test_ucp_proto.cc
- Preparation for extending the debug/info abilities
- Separate debug code from initialization/runtime logic
=> UCP/PROTO: Move protocol debugging code to new file: proto_debug.c

buildlib/pr/static_checks.yml
When clang static checker fails in CI, it's not easy to understand the underlying reason.
This PR uploads HTML files with more details about the failure.
- Add `-Xanalyzer:-analyzer-output=html` to cslng env var `CSCLNG_ADD_OPTS`
- Upload the resulting directory as AZP artifact
=> AZP/STATIC_CHECK: Upload HTML report as artifact

src/ucp/core/ucp_rkey.c, src/ucs/Makefile.am, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/memory/memtype_cache.h, src/ucs/sys/init.c, src/ucs/sys/topo/base/topo.c, src/ucs/sys/topo/base/topo.h, src/uct/api/uct.h, src/uct/api/v2/uct_v2.h, test/gtest/ucs/test_topo.cc, test/gtest/uct/v2/test_uct_query.cc
- based on yosefe/wip/backtrace
- allows for topo detection logic to use external modules like nvml, hwloc
=> UCS/TOPO: add topo module infrastructure

src/ucp/core/ucp_rkey.c, src/uct/sm/mm/posix/mm_posix.c, src/uct/sm/mm/sysv/mm_sysv.c
- Add profiling for rkey management routines in posix and sysv. They are quite intrusive and can be used on RMA or/and RNDV data-path
- remove profiling for `ucp_ep_rkey_unpack` because it is just a wrapper for `ucp_ep_rkey_unpack_internal` which is also profiled
better profiling experience
=> UCP/UCT: Add profiling for rkey management routines

src/ucs/datastruct/string_buffer.c, test/gtest/ucs/test_string.cc
Fix corner case in ucs_string_buffer_rtrim
=> UCS/STRING/TEST: Fix ucs_string_buffer_rtrim() for empty string

config/m4/ucm.m4, src/ucm/cuda/cudamem.c, src/ucm/mmap/install.c, src/ucm/mmap/mmap.h, src/ucm/util/reloc.c, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/ucm_opts.c, src/ucs/memory/memtype_cache.c, src/ucs/memory/rcache.c, test/gtest/ucs/test_memtype_cache.cc, test/gtest/uct/test_p2p_err.cc
Many Cuda applications use static link, so it's not safe to assume that relocation-based memory hooks on Cuda runtime API can be enough. To be on the safe safe, fail to create the registration cache and (by default) fallback to pointer-query based memory detection.
Note: As a side effect, this will also disable RDMA registration cache when could not install Cuda hooks, since not knowing about a Cuda memory release can lead to stale memory keys in the cache and a data corruption.
- Use Cuda Bistro hooks by default
- UCX_MEMTYPE_CACHE can by yes/no/try (default: try). If set to yes and it could not be created - print a warning.
- Memtype cache fails to create if could not set memtype hooks
The logic is:
* `UCX_MEM_CUDA_HOOK_MODE=bistro (default)`:
* If bistro hooks on driver API **fail** - …
=> UCM/UCS: Fail to create memtype cache if cannot patch Cuda driver API

test/gtest/ucp/test_ucp_wireup.cc
Fix the name of the transport printed which should be closed.
We have two transports `tl` and `better_tl`, `tl` should be closed.
So, this transport should be mentioned in the corresponding message.
Replace `better_tl` by `tl`.
=> GTEST/UCP: Fix the name of the transport printed which should be closed

src/ucp/wireup/wireup.c
Create EP which sends WIREUP_MSG/EP_REMOVED with AM lane only.
Sending WIREUP_MSG/EP_REMOVED requires only AM lane from the UCP EP.
Set the following EP init flags when created EP for sending WIREUP_MSG/EP_REMOVED:
- `UCP_EP_INIT_CREATE_AM_LANE`
- `UCP_EP_INIT_CREATE_AM_LANE_ONLY`
=> UCP/WIREUP: Create EP which send WIREUP_MSG/EP_REMOVED with AM lane only

src/ucp/wireup/select.c
Respect show_error flag if no lanes selected.
`show_error` flag is set to `0`, if selecting scalable transports. if they don't exist we shouldn't print any errors, because we should try selecting non-scalable transports.
Print `ucs_error` that no lanes were selected only if `num_lanes == 0` and `show_error` is true.
=> UCP/WIREUP: Respect show_error flag if no lanes selected

src/ucp/core/ucp_context.c, src/ucp/core/ucp_context.h
- Catch problems with memory type detection
- Slight optimization of branches - to check for fast path first (address not found - host, or address found as GPU)
=> UCP/CONTEXT: Add debug logging to memory type detection

NEWS, config/m4/ucm.m4, src/ucm/cuda/cudamem.c, src/ucm/mmap/install.c, src/ucm/mmap/mmap.h, src/ucm/util/reloc.c, src/ucp/core/ucp_context.h, src/ucs/config/global_opts.c, src/ucs/config/global_opts.h, src/ucs/config/ucm_opts.c, src/ucs/memory/memtype_cache.c, src/ucs/memory/memtype_cache.h, src/ucs/memory/rcache.c, src/uct/cuda/cuda_copy/cuda_copy_ep.c, test/gtest/ucs/test_memtype_cache.cc, test/gtest/uct/test_p2p_err.cc
Backport #7737  and  #7865 to v1.12.x
Conflicts: cudamem.c, memtype_cache.c
=> Memtype cache fixes - v1.12.x

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/core/ucp_proxy_ep.c, src/ucp/core/ucp_proxy_ep.h, src/ucp/core/ucp_request.h, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/wireup/wireup.c, src/ucp/wireup/wireup_cm.c, src/ucp/wireup/wireup_ep.c, src/ucp/wireup/wireup_ep.h, src/ucs/datastruct/callbackq.c, test/gtest/ucp/test_ucp_worker.cc
Deactivate UCT iface progress when there is no active ep for this iface.
Optimize case when TCP connection is created and then closed: currently, uct_tcp_iface_progress() continues to waste CPU cycles calling epoll_wait(). After this fix, TCP progress will not be called when no TCP endpoint is active.
Deactivate iface within ucp_ep_discard_lanes and ucp_ep_cleanup_lanes.
NOTE: This solves only client-server case.
=> UCP/CORE: deactivate iface when discard/cleanup lanes

buildlib/tools/builds.sh, src/ucp/core/ucp_ep.c, src/ucp/core/ucp_mm.c, src/ucp/core/ucp_request.inl, src/ucp/core/ucp_worker.inl, src/ucs/datastruct/ptr_map.inl, src/ucs/type/class.h, src/uct/ib/mlx5/ib_mlx5.h
Fix compiler warnings with `-Og` option
Fixes #7914
1. Set a pointer to pointer to `NULL` in places where it is required to suppress compiler warning.
2. Fix real issue in `ucp_ep_config_init` where `rsc_index` wasn't set to a proper value before calling `ucp_worker_iface_get_attr` for it.
3. Set all fields of `ucp_mem_map_params_t` to `0`, because the compiler thinks that `flags` filed could be used even if `field_mask == 0`.
4. Added compilation with `-Og` to our AZP CI's `builds.sh` script.
=> UCP/UCT/UCS: Fix compiler warnings with -Og option

src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, src/ucp/proto/proto_debug.c
Improve printing configuration:
Use UCS string buffer instead of `char*` and pointer arithmetic.
To simplify code and trim the trailing "; ".
Before:
```
[1644537002.052399] [swx-ucx01:42934:0]          parser.c:1918 UCX  INFO  UCX_* env variable: UCX_LOG_LEVEL=info
[1644537002.052738] [swx-ucx01:42934:0]      ucp_worker.c:1887 UCX  INFO    ep_cfg[0]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1); rma(rc_mlx5/mlx5_bond_0:1); amo(rc_mlx5/mlx5_bond_0:1);
```
After:
```
[1644536631.543315] [swx-ucx01:56970:0]          parser.c:1918 UCX  INFO  UCX_* env variable: UCX_LOG_LEVEL=info
[1644536631.543668] [swx-ucx01:56970:0]      ucp_worker.c:1877 UCX  INFO    ep_cfg[0]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1); rma(rc_mlx5/mlx5_bond_0:1); amo(rc_mlx5/mlx5_bond_0:1)
```
Use UCS string …
=> UCP/CORE: Improve printing configuration

src/ucp/rndv/rndv.c
Fix #7921
The test fails because rndv protocol receiver is responding with frag-RTR, while the sender cannot really use put-pipeline. As a result, the sender sends rndv_data packets as a response to that frag-RTR, but those cannot be processed for a fragment request (and fail on assert).
The fix is to prevent sending frag-RTR when the sender is host memory.
=> UCP/RNDV: Disable put-pipeline when sender side is host memory

src/uct/ib/rc/base/rc_iface.c
Don't do FC operations on failed RC EP to not post send WQEs on QPs which are in error state.
Fixes:
```
[swx-ucx04:12780:0:12780]   rc_mlx5.inl:457  Assertion `!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED)' failed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20220211_064053_52399_1008_swx-ucx02.swx.labs.mlnx/installs/QjC3/tests/io_demo/ucx.git/src/uct/ib/rc/accel/rc_mlx5.inl: [ uct_rc_mlx5_common_post_send() ]
...
454     if (opcode != MLX5_OPCODE_NOP) {
455         /* If FAILED, allow only NOP sends to be posted (used by endpoint
456          * flush operations) */
==>   457         ucs_assert(!(txwq->flags & UCT_IB_MLX5_TXWQ_FLAG_FAILED));
458     }
459 
460     ctrl = txwq->curr;
==== backtrace (tid:  12780) ====
0 0x000000000008e741 uct_rc_mlx5_common_post_send() …
```
=> UCT/IB/RC: Don't do FC on failed RC EP

NEWS, src/ucp/rndv/rndv.c
- Backport #7936 - no conflicts
- Add NEWS
=> UCP/RNDV: Disable put-pipeline when sender side is host memory - v1.12.x

src/uct/rocm/copy/rocm_copy_iface.c, src/uct/rocm/gdr/rocm_gdr_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c
Make the rocm components compile and run on master again
The rocm tls were not compiling currently on master
The reason I have the changes in two separate commits is because I *think* the second one might be required for the 12.x branch
=> UCT/ROCM: make rocm components compile again on master

src/uct/ib/base/ib_md.c
`reg_mem_types` is initialized by `md->reg_mem_types` below, no need to set it to `HOST` here
=> UCT/IB: Remove obsolete reg_mem_types initialization

src/tools/perf/api/libperf.h, src/tools/perf/lib/libperf.c, src/tools/perf/lib/libperf_int.h, src/tools/perf/lib/libperf_thread.c, src/tools/perf/perftest.c, test/gtest/common/test_perf.cc
When running ucx_perftest with a large buffer size, the default value of warmup iterations can be too high, so the test will not report results for a long time and appear "stuck". 
Perform several warmup rounds, each round increasing the number of iterations by 2x, until we reached the time limit.
=> TOOLS/PERF: Limit warm-up time

src/uct/ib/rc/base/rc_iface.c
Set the UCX_RC_MAX_RD_ATOMIC default value to 16.
The performance experiments show that this value is more reasonable than the previous one (4).
=> UCT/IB: Update the default MAX_RD_ATOMIC value

src/uct/ib/dc/dc_mlx5.c, src/uct/ib/dc/dc_mlx5.h
increase UCT_DC_MLX5_IFACE_MAX_USER_DCIS.
UCX_DC_MLX5_NUM_DCI needs a larger value to gain better throughput in a large scale scenario. from our experiments, w/ UCX_DC_MLX5_NUM_DCI=60, io_demo could reach to 10GBs each direction in a scale of 89 nodes, 17.6k connections per node. w/ UCX_DC_MLX5_NUM_DCI=120, io_demo could surpass 10GBs.
=> UCT/IB/DC: Increase max number of DCIs

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c
prefer boot id over mac address for cuda/rocm IPC reachability check
=> UCT/CUDA/ROCM: Prefer boot_id for IPC tls reachability check

.gitignore, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpRequestParams.java, bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java, bindings/java/src/main/native/endpoint.cc, bindings/java/src/main/native/jucx_common_def.cc, bindings/java/src/main/native/jucx_common_def.h, bindings/java/src/main/native/worker.cc, bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
Adding new class `UcpRequestParms` that contains additional request parameters (currently memory type and memory handle) 
and not breaking existing API.
TODO: next step would be to support external requests and move callback to request params.
To avoid memh detection from registration cache.
=> JUCX: Add request params class with memh hint.

src/uct/tcp/tcp_net.c
- fixed missing and incorrect include config.h
=> UCT/BUILD: fixed config.h include

src/ucp/am/eager.c, src/ucp/core/ucp_context.c, src/ucp/proto/proto.c, src/ucp/proto/proto.h, src/ucp/proto/proto_reconfig.c, src/ucp/proto/proto_select.c, src/ucp/rma/amo_offload.c, src/ucp/rma/amo_sw.c, src/ucp/rma/get_am.c, src/ucp/rma/get_offload.c, src/ucp/rma/put_am.c, src/ucp/rma/put_offload.c, src/ucp/rndv/rndv_am.c, src/ucp/rndv/rndv_get.c, src/ucp/rndv/rndv_ppln.c, src/ucp/rndv/rndv_put.c, src/ucp/rndv/rndv_rkey_ptr.c, src/ucp/rndv/rndv_rtr.c, src/ucp/tag/eager_multi.c, src/ucp/tag/eager_single.c, src/ucp/tag/offload/eager.c, src/ucp/tag/tag_rndv.c
- implemented proto registration without CTOR, using static
initialization
=> UCP/PROTO: proto registration without CTOR

src/ucs/datastruct/string_buffer.h
Fix macro definition - no need `\` in last line
=> UCS/STRING: Remove trailing slash

src/ucp/core/ucp_request.c, src/ucp/core/ucp_worker.c, src/ucp/core/ucp_worker.h, test/gtest/ucp/test_ucp_sockaddr.cc
Fix `ep_pending_add`/`ep_flush` which return busy/no_resource for discard only
Fixes running of multiple iterations of `test_ucp_sockaddr.force_close_during_rndv` and `test_ucp_sockaddr.fail_and_force_close_during_rndv` tests over UD transport.
To fix hang due to hanging in `ucp_request_send` which tries to send `WIREUP_MSG/EP_REMOVED`:
- `uct_ep_am_bcopy` returns `UCS_ERR_NO_RESOURCE`
- `uct_ep_pending_add` return `UCS_ERR_NO_BUSY`
- it hangs always doing `uct_ep_am_bcopy`-`uct_ep_pending_add`.
The example of the issue described above:
```
#0  0x00007ffff7331b44 in ucp_wireup_msg_progress (self=0x36e32f8) at wireup/wireup.c:179
#1  0x00007ffff7332624 in ucp_request_try_send (req=0x36e3210) at /auto/rdmzsysgwork/dmitrygla/ucx/src/ucp/core/ucp_request.inl:334
#2  ucp_request_send …
```
=> GTEST/UCP: Fix ep_pending_add/ep_flush which return busy/no_resource for discard only

src/ucp/am/eager.c
Fix assertion failure when trying to display active message protocol description
=> UCP/AM: Add am/eager/zcopy protocol description

test/apps/iodemo/ucx_wrapper.cc
Backport https://github.com/openucx/ucx/pull/7662
fix io_demo timeouts waiting for replies with tcp transport
=> APPS/IODEMO: fix progress loop - v1.12.x

src/ucm/mmap/install.c
- added static build mode support: in case if library is built statically
and symbol to patch could not be found then patch statically linked
function
=> UCM/BISTRO: added static build mode support

src/ucp/core/ucp_am.c
Fix not selecting AM short_iov protocol for UCP AM send.
AM short_iov should be selected if memtype is HOST and datatype is CONTIG.
Currently, AM short_iov is selected only if no `DATATYPE` and no `NO_IMM_CMPL` are set and only HOST memory type is supported. If at least one is true, it won't be selected.
Update `ucp_am_send_req` function as follows:
1. Remove check for `(count != 0) && (user_header_length != 0)` and `TODO` comment.
2. Always set `max_short` from `ucp_am_get_short_max(req, max_short)`.
=> UCP/CORE: Fix not selecting AM short_iov protocol for UCP AM send

src/ucm/rocm/rocmmem.c, src/uct/rocm/gdr/rocm_gdr_iface.c, src/uct/rocm/ipc/rocm_ipc_iface.c
Bring PR #7941 (commit 7afce316ea87782fdaf99ee28e39d5ea0ecbdb6f) and PR #7954 from master to the v1.12 branch
These PRs are necessary to make the rocm components work correctly on the v1.12. branch
=> ROCm fixes - v1.12.x

src/ucp/core/ucp_context.c, src/ucp/core/ucp_version.c.in
Improve UCX version print to include canonical version string and library path
* Correct version (+ `UCX_LOG_LEVEL=info`):
```
[1645974996.154356] [myhost:31897:0]     ucp_context.c:1799 UCX  INFO  UCP version is 1.13 (release 0)
```
* Mismatch version:
```
[1645975021.374097] [myhost:1397 :0]     ucp_context.c:1796 UCX  WARN  UCP version is incompatible, required: 1.13, actual: 1.12 (release 0)
```
* Correct version (+ `UCX_LOG_LEVEL=info`):
```
[1645974884.130258] [myhost:23614:0]     ucp_context.c:1810 UCX  INFO  Version 1.13.0 (loaded from /path/to/usr/lib64/libucp.so.0)
```
* Mismatch version:
```
[1645974950.527876] [myhost:27319:0]     ucp_context.c:1810 UCX  WARN  UCP API version is incompatible: required >= 1.13, actual 1.12.0 (loaded from /path/to/usr/lib64/libucp.so.0)
```
=> UCP/CONTEXT: Improve version print

src/ucp/core/ucp_ep.c, src/ucp/core/ucp_ep.h, src/ucp/wireup/wireup.c
Fix not allocating indirect remote ID for internal EP if connected EP supports `PEER_FAILURE`.
To allocate indirect remote ID, since internal UCP EP is created with `PEER_FAILRUE` capability.
Currently, direct ID is always allocated for internal EP.
1. Set ep_init_flags to `PEER_FAILURE` flag prior doing `ucp_worker_create_ep` where the type of remote ID is identified based on configuration and `PEER_FAILURE` flag.
2. Check that local and remote EPs don't have a mismatch in error mode.
=> UCP/WIREUP: Fix not allocating indirect remote ID for internal EP if connected EP supports PEER_FAILURE

src/ucs/configure.m4
Fix #7955 and this [internal issue](https://redmine.mellanox.com/issues/2993074)
When running configure-time test, force shared library build, to fail if binutils library is not relocatable.
=> UCS/BUILD: Make sure libibfd and libiberty can be used with dynamic link

src/uct/ib/base/ib_iface.c
No need to fail creating IB uct_iface (and UCP worker) since there is fallback to no subnet mask
=> UCT/IB: Don't fail if can't detect RoCE subnet mask
