openucx/ucx

src/tools/perf/perftest.c
src/ucs/sys/sys.c
src/ucs/sys/sys.h
src/ucs/vfs/fuse/vfs_fuse.c
src/uct/Makefile.am
src/uct/base/uct_component.c
src/uct/base/uct_component.h
src/uct/base/uct_iface_vfs.c
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/base/uct_md_vfs.c
src/uct/base/uct_vfs_attr.c
src/uct/base/uct_vfs_attr.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/ib/rdmacm/rdmacm_component.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/gdr/rocm_gdr_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/base/mm_md.h
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
src/uct/ugni/base/ugni_md.c
test/gtest/common/test_perf.cc

Added VFS node representing UCT component.
Added VFS nodes representing UCT memory domain and its features.
Added symbolic link from UCT iface to UCT memory domain.
Added symbolic link from UCT memory domain to UCS registration cache.

UCT/BASE: VFS nodes representing UCT components and memory domains.

---

test/gtest/ucs/test_vfs.cc

Fixed order of parameters in `EXPECT_EQ` macro.

GTEST/UCS: Fixed expected/actual parameters order.

---

src/ucs/debug/memtrack.c

- updated leaked memtrack message: added name of leaked allocation
- fixed hang on leak detection

UCS/MEMTRACK: updated leaked message

---

src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/configure.m4
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/ud/accel/ud_mlx5.c

Always enable CQ override check in HW if assert mode is enabled
Improve debugging experience

UCT/IB: Check CQ overrun in assert mode

---

src/ucp/Makefile.am
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_multi.h
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rtr.c

Estimate performance of rndv pipeline performance

UCP/PROTO: Add generic rendezvous pipelined protocol initialization

---

src/ucs/vfs/fuse/vfs_fuse.c

Changed log level of message to more suitable type.

UCS/VFS: Changed log level of debug message.

---

src/ucp/dt/datatype_iter.inl
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c

Implement pipelined protocol progress - create fragment requests and send them.

UCP/RNDV: Implement rendezvous pipeline progress

---

contrib/test_jenkins.sh
test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/uct/test_p2p_rma.cc
test/gtest/uct/uct_p2p_test.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Reduce the time it takes to complete a CI job, currently it's up to 5.5 hrs
- Remove some perftest permutations
- Optimize pattern_check

Reduce testing time on GPU machines

---

src/ucp/Makefile.am
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_types.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_mtype.inl
src/ucp/rndv/rndv_ppln.c

Implement 2-stage pipeline over get_zcopy with new protocols

UCP/RNDV: Add get-pipeline protocol

---

src/ucp/wireup/address.c

The intent of the PR is to restore compatibility with old UCX versions.
Since the old UCX versions pack "dedicated - shared" bandwidth value, they could send negative BW, which represents "shared" BW instead of "dedicated" BW which is a positive one.
Fixes the following assertion discovered by MTT:
```
[node01:43706:0:43706]      select.c:270  Assertion `(score >= 0.0) || (rsc_index == ((ucp_rsc_index_t)-1))' failed
/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210908_234502_165745_66027_jazz23.swx.labs.mlnx/installs/uMI4/tests/io_demo/ucx.git/src/ucp/wireup/select.c: [ ucp_wireup_init_select_info() ]
...
267 {
268     /* score == 0.0 could be specified only when initializing a selection info
269      * to add CM lane (rsc_index == UCP_NULL_RESOURCE in this case) */
==>   270 …
```

UCP/WIREUP: Restore compatibility with old UCX versions

---

src/uct/ib/ud/accel/ud_mlx5.c

Update doorbell by CQ CI even if destination GID is wrong.
The doorbell must be kept updated.
If GRH checking fails for some packet, go to the code which updates doorbell cq ci and then ends up handling.

UCT/IB/UD/MLX5: Update doorbell by CQ CI even if dgid is wrong

---

src/uct/ib/ud/base/ud_ep.c

UCT/IB/UD/BASE: Fix receiving duplicated CREQ or CREQ after CREP - v1.11.x

---

src/ucm/api/ucm.h
src/ucm/util/log.c
src/ucm/util/reloc.c
src/ucs/stats/libstats.h
src/ucs/time/timer_wheel.h

Fixed some typos and deleted some outdated comments.

Some cosmetic changes in comment

---

src/ucp/core/ucp_am.c

Remove duplicated update of `recv_flags`

UCP/AM: ucp_am_handler_common cleanup

---

test/gtest/ucp/test_ucp_tag_mem_type.cc

Decrease memtype length size when running under valgrind.
before:
```
[ RUN      ] udx/test_ucp_tag_mem_type.basic/0 <ud_x,cuda_copy,rocm_copy/host:host>
[       OK ] udx/test_ucp_tag_mem_type.basic/0 (6701 ms)
```
after:
```
[ RUN      ] udx/test_ucp_tag_mem_type.basic/0 <ud_x,cuda_copy,rocm_copy/host:host>
[       OK ] udx/test_ucp_tag_mem_type.basic/0 (1366 ms)
```
memtype tests are one of the longest tests:
```
2021-09-13T20:03:09.6520202Z TOP-20 longest tests:
...
2021-09-13T20:03:09.6707240Z 15. udx/test_ucp_tag_mem_type.basic/40                                                                                        - 15243 ms
2021-09-13T20:03:09.6716464Z 16. ud/test_ucp_tag_mem_type.basic/68                                                                                         - …
```

GTEST/UCP: Decrease memtype length size under valgrind

---

src/ucp/core/ucp_request.h

UCP: Remove extra line in ucp_recv_desc definition

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_request.inl
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/rma/rma.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rtr.c

Better RNDV performance with new protocols when GPU-direct is slow or does not exist

UCP/PROTO/RNDV: Add 3-stage pipeline put new protocol

---

test/apps/iodemo/io_demo.cc

Print connection info if validation fails.
To get more information about the connection and its status.
1. Add `UcxConnection` parameter to `validate()` functions.
2. Print `UcxConnection` log prefix and UCX status.

APPS/IO-DEMO: Print connection info if validate fails

---

src/ucp/proto/proto_am.inl
test/gtest/ucp/test_ucp_sockaddr.cc

Port #7403 to v1.11
cc @abellina

UCP: Reregister memh on CM switch (v1.11)

---

src/ucs/sys/string.c
src/ucs/sys/string.h
src/ucs/sys/topo.c
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/ucs/test_string.cc

Better estimation for system topology: the main factor for system distance, when traversing sysfs device tree, is who is the common ancestor - rather than the path distance to it.
When using this PR, this is the topology distance estimation:
Case 1: Supermicro X10DGQ, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
<details>
<summary>(Open details)</summary>
```
$ nvidia-smi topo -m
GPU0	GPU1	mlx5_0	mlx5_1	CPU Affinity	NUMA Affinity
GPU0	 X 	SYS	PHB	PHB	0-11	0
GPU1	SYS	 X 	SYS	SYS	12-23	1
mlx5_0	PHB	SYS	 X 	PIX		
mlx5_1	PHB	SYS	PIX	 X 		
$ ./build-devel/src/tools/info/ucx_info -T
#
#
#
```
</details>
Case 2: NVIDIA DGX-1 with V100-32, Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
<details>
<summary>(Open details)</summary>
```
$ nvidia-smi topo -m
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	mlx5_0 …
```

UCS/TOPO: More accurate topology distance estimation

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_worker.c

UCP/EP: Fix error handler return status when user callback is not set - v1.11.x

---

test/gtest/common/googletest/gtest.cc

More verbose test run mesage with new gtest version

TEST/GTEST: Print test parameters

---

buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/io_demo/io-demo.yml

AZP: Iodemo cx6

---

src/ucp/core/ucp_context.c

Remove extra newlines from env config descriptions

UCP: Remove extra newlines from config descs

---

NEWS

Update NEWS file with the bugfixes of v1.11.2 release

NEWS: Update v1.11.2-rc1 release

---

docs/source/running.md

Fixes a typo in the docs.
Same as above.
NA

DOCS: Fix typo

---

src/uct/base/uct_md.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
test/gtest/common/main.cc
test/gtest/uct/ib/test_dc.cc
test/gtest/uct/ib/test_rc.cc
test/gtest/uct/uct_p2p_test.cc

Reduce testing time with valgrind
Reduce the time to create a UCP worker - which is mostly spent on creating all UCT interfaces, and buffer pools memory allocation

UCT/TEST: Improve testing time on valgrind

---

bindings/go/Makefile.am
bindings/go/src/ucx/endpoint.go
bindings/go/src/ucx/request.go
bindings/go/src/ucx/ucs_constants.go
bindings/go/src/ucx/utils.go
bindings/go/src/ucx/worker.go
bindings/go/tests/endpoint_test.go
bindings/go/tests/listener_test.go
bindings/go/tests/memory_test.go
bindings/go/tests/utils.go

GPU tests. Set and get memory utilities to test endpoint operations on GPU memory
Prepare test infrastructure for further ucp ep operations (AM, RMA, etc.).

BINDINGS/GO: Endpoint GPU tests.

---

buildlib/pr/io_demo/io-demo.yml

enable iodemo testing on CX6/DC
test coverage

TEST/IODEMO: test CX6/DC/AM

---

src/ucs/config/global_opts.c

Remove extra lines from env var descriptions

UCS: Remove extra newlines from var descriptions

---

NEWS

Update news for v1.11.2 release

NEWS: Update for v1.11.2

---

buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/io_demo/io-demo.yml

enable iodemo testing on CX6/DC
test coverage

TEST/IODEMO: test CX6/DC/TAG

---

buildlib/pr/main.yml

Disable Cuda_compatible test
Now We don't have Nvidia GPU machine

AZP: Disable Cuda_compatible test

---

src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_inl.h
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/uct/ib/test_ud.cc

Fixed UD verbs implementation of AM short IOV method.
Added missed copy of IOV data to skb.

UCT/IB/UD: Fixed short iov in UD verbs.

---

buildlib/az-helpers.sh
buildlib/azure-pipelines-release.yml
buildlib/azure-pipelines.yml
buildlib/dockers/docker-compose.yml
buildlib/dockers/push-release-images.sh
buildlib/tools/common.sh
contrib/test_jenkins.sh

Update CUDA version to 11.4 in docker images

AZP/RELEASE: Update CUDA version to 11.4 for release pipeline

---

src/uct/tcp/tcp_sockcm_ep.c

add status to uct_cm_ep_resolve_args_t in TCP
TCP implementation of API added in https://github.com/openucx/ucx/pull/7516/commits/3acea1bab2a879eb3b3d88d64f4e55a8adc7a6e9

UCT/TCP/CM: add status to uct_cm_ep_resolve_args_t

---

src/ucp/core/ucp_ep.c

Align printing RMA config with other protocols.
To make printing config are identical and easier for understanding.
1. Introduce printing short, middle and last proto thresh functions.
2. Use them to print RMA and other EAGER/RNDV protocols.

UCP/CORE: Align printing RMA config with other protocols

---

test/apps/iodemo/io_demo.cc

Invalidate send IOV when the operation is completed.
To check if a peer reads (or local side writes) invalid data to a remote buffer which is verified then by a target side.
1. Invalidate memory allocated for `BufferIov` during `release()` if it was filled.
2. Some minor code improvements and cleanups.

APPS/IO-DEMO: Invalidate send IOV when operation completed

---

src/ucs/vfs/fuse/Makefile.am

UCS/FUSE: Remove cuda flags from build

---

test/apps/iodemo/io_demo.cc

Do Not Merge. Only for CICD test purpose
Do Not Merge. Only for CICD test purpose
Do Not Merge. Only for CICD test purpose

[DNM] Do Not Merge. Only for CICD test purpose

---

src/ucp/core/ucp_worker.c
test/gtest/ucp/test_ucp_worker.cc

Fix dereferencing invalid UCP EP during UCT EP which was under discarding.
Fixes potential use-after-free of UCP endpoint which was already destroyed from `ucp_worker_discard_uct_ep_complete()` when puring UCT EP requests. It may happen inside `uct_ep_close()` when UCT EP completes some in-flight UCP requests (e.g. RNDV GET Zcopy operation).
1. Update `ep_destroy_func()` which is set as `uct_ep_destroy()` in UCP discarding testing to check UCP EP refcount (it indeed reporuces issue with use-after-free of UCP EP).
2. Re-write `ucp_worker_discard_uct_ep_purge()` to not complete discard operations.
3. Discard operations will be completed after `uct_ep_destroy()` if discarding UCP request was scheduled on UCT EP pending queue.

UCP/CORE/GTEST: Fix dereferencing invalid UCP EP during UCT EP which was under discarding

---

src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/ud/accel/ud_mlx5.c

UCT/IB/MLX5: Fix TX WQ overflow check

---

configure.ac
ucx.spec.in

Bump version after creating v1.12.x branch

CONFIG/SPEC: Bump version to 1.13.0

---

buildlib/tools/builds.sh
contrib/buildrpm.sh
ucx.spec.in

BUILD/RPM: enable optional build rpm with debug function

---

test/gtest/ucp/test_ucp_rma.cc

UCP/GTEST: Fix typo

---

config/m4/gdrcopy.m4

Fix incorrect setting of gdrcopy lib dir during configuration.

CONFIG: Use correct gdrcopy lib dir

---

src/ucm/event/event.c

- fixed ordering-sensitive constructor's ordering hang:
in case of "incorrect" constructor call sequence ucm spin-lock
may be used prior to initialized

UCM/INIT: fixed potential hang

---

bindings/go/Makefile.am
bindings/go/src/examples/perftest/perftest.go
bindings/go/src/ucx/connection_request.go
bindings/go/src/ucx/context.go
bindings/go/src/ucx/listener.go
bindings/go/src/ucx/memory.go
bindings/go/src/ucx/request.go
bindings/go/src/ucx/ucs_constants.go
bindings/go/src/ucx/ucx_error.go
bindings/go/src/ucx/worker.go
buildlib/pr/go/go-test.yml

GO: Standalone performance benchmark.

BINDINGS/GO: Standalone performance benchmark.

---

buildlib/tools/builds.sh
buildlib/tools/common.sh
config/m4/fuse3.m4
src/tools/vfs/Makefile.am
src/ucs/vfs/fuse/Makefile.am

Supported static link of FUSE3 library.
Fixed configuration and building with FUSE3 in user defined location.

CONFIG/M4: Support static link of FUSE3 library.

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h

Added two files to UCP worker to display number of total and failed creations of UCP endpoint.

UCP/CORE: Added number of total/failed EP creations to VFS.

---

bindings/go/Makefile.am

BINDINGS/GO: port OOS fixes to 1.12

---

config/m4/cuda.m4

Configure step to show error if nvml isn't detected on the system.

CONFIG/CUDA: show error messages if nvml not detected

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_listener.c
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h

Added files with number of destroys of endpoints and with number of failed endpoints.
Increased number of created endpoints in case of using accept callback flow.

UCP/CORE: Added ep destroys and failed eps to VFS.

---

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpEndpoint.java
bindings/java/src/main/java/org/openucx/jucx/ucp/UcpMemory.java
bindings/java/src/main/native/jucx_common_def.cc
bindings/java/src/main/native/ucs_constants.cc
bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java
docs/LoggingStyle.md
docs/doxygen/design.md

BINDINGS/JAVA: Fix typo

---

test/apps/iodemo/io_demo.cc

Use different IOV buffer fillers for Client and Server.
It helps to understand whether an IOV buffer was taken from the next operation or not while it is in progress for some previous operation.
1. Add `_iov_buf_filler` constant for `P2pDemoCommon` base class.
2. Set `_iov_buf_filler` to 32-bit `0xeeeeeeee` for `DemoServer`.
3. Set `_iov_buf_filler` to 32-bit `0xddddddd` for `DemoClient`.
4. Use `_iov_buf_filler` for IOV buffer initialization instead of `0` passed for `sn` and `conn_id`.

APPS/IO-DEMO: Use different IOV buffer fillers for Client and Server

---

buildlib/pr/io_demo/io-demo.yml

AZP/IODEMO: Remove active messages on CX4 stage

---

test/gtest/ucp/test_ucp_sockaddr.cc

Add UCP AM support in `send_recv()`
Fixes https://dev.azure.com/ucfconsort/ucx_int4/_build/results?buildId=31767&view=logs&j=8cc70074-80e3-506d-e80d-a542b02430e7&t=da02301d-00be-54d1-aa97-9bf0b310a3f6
1. Add `send()` of AM.
2. Update `send_recv()` to use AM's `send()` and setting AM handler.
3. Set `rreq` to `NULL` to fix compiler warning.

GTEST/UCP: Add UCP AM send_recv

---

config/m4/go.m4

Check go compiler version.
Fixes  #7669

BINDINGS/GO: Check compiler minimum version.

---

src/uct/sm/scopy/cma/cma_md.c

Add en var for enabling "stub" memory invalidation on CMA
port #7701
For CMA to be selected for RNDV protocol when error handling is requested

UCT/CMA: Add stub cap for memory invalidation - v1.12

---

src/uct/sm/scopy/cma/cma_md.c

Add en var for enabling "stub" memory invalidation on CMA
For CMA to be selected for RNDV protocol when error handling is requested
before:
```
$UCX_TLS=cma,tcp  ./src/tools/info/ucx_info -e -ute
#
#
#
#
#
```
after:
```
$UCX_CMA_MEMORY_INVALIDATE=y UCX_TLS=cma,tcp ./src/tools/info/ucx_info -e -ute
#
#
#
#
#
```

UCT/CMA: Add stub cap for memory invalidation

---

bindings/go/src/examples/perftest/perftest.go

- Add warmup perftest parameter to have uniform results.
- Fix correct number of threads in workgroup on server (on server we have global worker progress thread + thread per connection).

BINDINGS/GO: Perftest warmup + fixes.

---

src/uct/ib/mlx5/dv/ib_mlx5_dv.c

UCT/MLX5: Set pkey_index - v1.12.x

---

test/gtest/uct/uct_test.cc

GTEST: A workaround for the GCC issue in FC35 - 1.12.x

---

test/gtest/uct/uct_test.cc

GTEST: A workaround for the GCC issue in FC35

---

src/ucp/Makefile.am
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_ep_vfs.c
src/ucp/core/ucp_ep_vfs.h
src/ucp/core/ucp_listener.c
src/ucp/core/ucp_vfs.c
src/ucp/core/ucp_vfs.h
src/ucp/core/ucp_worker.c

Added files to directory representing UCP endpoint in VFS. These files contain remote and local addresses including ip and port number.

UCP/CORE: Added ep remote address to VFS.

---

config/m4/fuse3.m4

- fixed potential issue on env var set/restore

FUSE/CONFIG: fixed env var manipulation issue

---

src/ucp/rma/flush.c

Fix error handling from UCT EP flush.
Fixes #7742
UCT/TCP endpoints could return an error code from `uct_ep_flush()` and it should decrease completion counter set in UCP flush request prior calling `ucp_ep_flush_progress()` and checking flush completion, otherwise - it may stuck.
1. Fix code style in `ucp_ep_flush_progress_pending()` function.
2. Move marking of a UCP flush request as failed where handling of `UCS_OK` to decrease completion counter in a UCP request prior checking completion.
3. Reorganize checking error code at the end of the function to simplify it.
4. Add logging of UCT EP pointer - it could be useful to find out the exact UCT EP which is completed with some status.

UCP/FLUSH: Fix error handling from UCT EP flush

---

bindings/go/tests/endpoint_test.go

Wait for progress thread to write all requests to the channel.
Fixes #7756

BINDINGS/GO: Wait for thread to write to the channel.

---

test/gtest/ucp/test_ucp_am.cc

Add UCP AM tests, which create peers with different supported segment sizes
To avoid changes which would break support for communication between peers with different segment sizes

GTEST/UCP/AM: Add tests when peers have different segment sizes

---

buildlib/azure-pipelines-pr.yml
contrib/pr_merge_check.py

Optimize review process to check pull request changes with force-push
Checkout pull request to a local repo and compare merge result before/after
Example:
```diff
(base) 17:50 [yosefe@hpchead ucx]$ ./contrib/pr_merge_check.py --pr 7760 -v
github head commit: 6505e1b
github approved commit: a51b518 (by 'yosefe')
initialized empty repo at /tmp/yosefe/pr_check
fetched upstream/master as 03b935e
comparing a51b518 and 6505e1b when merged to master
- merge of a51b518 to upstream/master is ea72ecc
- merge of 6505e1b to upstream/master is 667ada5
diff --git a/src/uct/ib/dc/dc_mlx5.h b/src/uct/ib/dc/dc_mlx5.h
index 04fb9af..4d703af 100644
--- a/src/uct/ib/dc/dc_mlx5.h
+++ b/src/uct/ib/dc/dc_mlx5.h
@@ -49,6 +49,7 @@ struct ibv_ravh {
#define UCT_DC_MLX5_IFACE_TXQP_DCI_GET(_iface, _dci, _txqp, …
```

CONTRIB: Script to check if a pull request was changed after approval

---

src/ucp/tag/tag_send.c

- added slow path where datatype is processed
fixes https://github.com/openucx/ucx/issues/7754

UCP/TAG/SEND: fixed datatype issue

---

src/ucp/core/ucp_request.c

Convert discard's flush from LOCAL to CANCEL during request fast-forward procedure.
If some discard operations with `flush(LOCAL)` were queued, but error detected on UCP EP (and fast-forward of request is done as a part of error handling), need to do `flush(CANCEL)` during discard operation to avoid flushing UCT EP with error.
1. Add assertion that `ucp_request_send_state_ff()` is called with error status passed to it.
2. When handling discard request, set `UCT_FLUSH_FLAG_CANCEL` to `req->send.discard_uct_ep.ep_flush_flags` and restart discard.

UCP/CORE: Convert discard's flush to CANCEL during fast-forward

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/rndv/rndv.c

UCP/RNDV: Option to limit GPUDirectRDMA size in rndv - 1.12.x

---

contrib/test_jenkins.sh
src/tools/perf/cuda/cuda_alloc.c
src/tools/perf/lib/libperf.c
src/tools/perf/lib/libperf_int.h
src/tools/perf/lib/libperf_memory.c
src/tools/perf/lib/libperf_thread.c
src/tools/perf/lib/ucp_tests.cc
src/tools/perf/lib/uct_tests.cc
test/gtest/common/test_perf.cc
test/gtest/common/test_perf.h
test/gtest/ucp/test_ucp_perf.cc
test/gtest/uct/test_uct_perf.cc
test/gtest/uct/uct_test.h

Signed-off-by: Vasily Philipov <vasilyf@nvidia.com>
Why ?
Add loopback transport support for UCT tests

LIBPERF: Add loopback transport support for UCT tests

---

src/ucs/debug/memtrack.c
test/gtest/ucs/test_memtrack.cc

Added `memtrack` directory to VFS. The directory contains a file with dump of memtrack feature.

UCS/DEBUG: Memtrack output to VFS.

---

config/module-pkg-config.am
src/ucs/vfs/fuse/Makefile.am
src/ucs/vfs/fuse/configure.m4
src/ucs/vfs/fuse/ucx-fuse.pc.in
src/uct/ib/Makefile.am
src/uct/ib/configure.m4
src/uct/ib/rdmacm/Makefile.am
src/uct/ib/rdmacm/configure.m4
src/uct/ib/rdmacm/ucx-rdmacm.pc.in
src/uct/ib/ucx-ib.pc.in
src/uct/sm/scopy/cma/Makefile.am
src/uct/sm/scopy/cma/configure.m4
src/uct/sm/scopy/cma/ucx-cma.pc.in
src/uct/sm/scopy/knem/Makefile.am
src/uct/sm/scopy/knem/configure.m4
src/uct/sm/scopy/knem/ucx-knem.pc.in
ucx.pc.in
ucx.spec.in

- added module-specific .pc files to build

UCT/MODULES: added .pc files

---

src/ucm/cuda/cudamem.c
src/ucm/util/reloc.c
src/ucp/core/ucp_listener.c
src/ucp/core/ucp_worker.c
src/ucs/sys/topo.c
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_md.c
src/uct/ib/rdmacm/rdmacm_listener.c

Improve debugability
- Adjust log levels based on frequency
- Add more information to log messages

Debug logging improvements

---

.gitignore

- added test applications
- added ucx-*.pc files

GIT: updated gitignore

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c

Fix a bug in the address range while invalidating the regions

UCT/CUDA_IPC: Fix a bug in invalidating address range

---

src/uct/cuda/Makefile.am
src/uct/cuda/configure.m4
src/uct/cuda/gdr_copy/Makefile.am
src/uct/cuda/gdr_copy/configure.m4
src/uct/cuda/gdr_copy/ucx-gdrcopy.pc.in
src/uct/cuda/ucx-cuda.pc.in
src/uct/rocm/Makefile.am
src/uct/rocm/configure.m4
src/uct/rocm/gdr/Makefile.am
src/uct/rocm/gdr/configure.m4
src/uct/rocm/gdr/ucx-rocm-gdr.pc.in
src/uct/rocm/ucx-rocm.pc.in
src/uct/sm/mm/xpmem/Makefile.am
src/uct/sm/mm/xpmem/configure.m4
src/uct/sm/mm/xpmem/ucx-xpmem.pc.in
src/uct/ugni/Makefile.am
src/uct/ugni/configure.m4
src/uct/ugni/ucx-ugni.pc.in

- added module-specific .pc files stubs

UCT/CONFIG: added generation of module .pc files

---

buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/io_demo/io-demo.yml

Fix pipeline failures when running io_demo stage as individual CI : `$(System.PullRequest.TargetBranch)` is undefined

AZP/IODEMO: Fix using undefined variable PullRequest.TargetBranch

---

test/apps/iodemo/ucx_wrapper.cc

Replace `completed` field by checking UCS status in UCP request.
Simplifies code and reduces the size of `ucx_request` structure.
1. Remove `completed` field.
2. Set `UCS_INPROGRESS` to `status` field as initial value.
3. Check `status != UCS_INPRORGESS` instead of `completed`.

APPS/IO-DEMO: Replace completed field by checking UCS status

---

contrib/pr_merge_check.py

Support checking already merged PRs by `contrib/pr_merge_check.py`
To allow checking a PR was not changed after approval after it was already merged
1. Remove safety checks
2. Take base sha1 from PR information, instead of pulling the target branch

CONTRIB/PR_CHECK: Support checking merged PRs

---

NEWS

Update news file for the upcoming v1.12.0 release

NEWS: Update news for v1.12.0 release

---

src/uct/api/v2/uct_v2.h
test/gtest/uct/v2/test_uct_query.cc

API/V2: minor typo

---

NEWS

Port UCX v1.12.0 news to the master  branch

NEWS: Backport v1.12.0 news to master

---

contrib/pr_merge_check.py

Fix few issues in pr_merge_check.py script , introduced in #7826

CONTRIB/PR_MERGE: Script fixes

---

buildlib/pr/io_demo/io-demo.yml
test/apps/iodemo/io_demo.cc

to fix:
1)AM/eager caused SIGSEGV.
2)enabling validation caused iodemo exited unexpectedly.
to fix:
1)AM/eager caused SIGSEGV.
2)enabling validation caused iodemo exited unexpectedly.

APPS/IODEMO: Fix dysfunctional AM

---

src/ucp/api/ucp.h
src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h
src/ucp/core/ucp_request.inl
src/ucp/core/ucp_worker.c
test/gtest/ucp/test_ucp_am.cc

This reverts commit a0543a691ca1f1ad4d9fb79e1865c769e2d4838f, reversing
changes made to ba6e81b9c03df749daaddc18f726ec571925bad6.
Revert merging made by mistake.

Revert "Merge pull request #7832 from gleon99/align-offset"

---

test/apps/iodemo/ucx_wrapper.cc
test/apps/iodemo/ucx_wrapper.h

Handle iomsg later if the connection isn't established.
To get rid of "head-of-line blocking" problem when some connection isn't established yet, i.e. ID wasn't received through Stream API, but some `iomsg`s was already received to handle IO operations.
1. If the message was received, but the connection wasn't established yet, save the `iomsg` to the vector of unhandled `iomsg`s.
2. When the connection was established, extract all `iomsg`s from the vector of unhandled `iomsg`s and dispatch the message.

APPS/IO-DEMO: Handle iomsg later if connection isn't established

---

src/uct/ib/ud/base/ud_ep.c

Check that acked_psn is always smaller than current_psn.
To catch problems with `tx.acked_psn` and `tx.psn` earlier. And this assertion is more informative than checking TX window queue emptiness.
1. Move checking `tx.window` queue emptiness to `uct_ud_ep_is_last_ack_received` to reduce code duplication.
2. Update `uct_ud_ep_process_ack` to detect case when `tx.acked_sn < tx.psn` which is not expected to be true.

UCT/IB/UD: Check that acked_psn is always smaller than current_psn

---

src/ucp/core/ucp_ep.inl

extend assertion print
for debugging purposes 
port of https://github.com/yosefe/ucx/pull/239

UCP/EP: extend assertion print

---

src/uct/base/uct_component.c
src/uct/base/uct_iface.h
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_iface.c
src/uct/tcp/tcp_md.c

- used single constructor entry for SELF and TCP transports

UCT/TCP/SELF: single constructor entry

---

NEWS
configure.ac
ucx.spec.in

Preparation for publishing v1.12.1-rc1
cc @shamisp @tonycurtis @brminich

NEWS/BUILD: Update for v1.12.1-rc1

---

test/apps/iodemo/io_demo.cc

Support set multiple client ip addresses.
Feature requirement

TEST/IODEMO: support set multiple client ip addresses

---

buildlib/pr/coverity.yml
buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/main.yml

AZP: Increase timeouts

---

configure.ac
src/ucs/sys/module.c
src/ucs/sys/sys.c
src/ucs/sys/sys.h

- added static/dynamic lib detection
- in static lib disabled module loading

UCS/SYS: added static/dynamic lib detection

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_proxy_ep.c
src/ucp/core/ucp_proxy_ep.h
src/ucp/core/ucp_request.h
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_ep.c
src/ucp/wireup/wireup_ep.h
src/ucs/datastruct/callbackq.c
test/gtest/ucp/test_ucp_worker.cc

Backport https://github.com/openucx/ucx/pull/7819 bugfix to v1.12.x branch

UCP/CORE: deactivate iface when discard/cleanup lanes - v1.12.x

---

src/ucs/Makefile.am
src/ucs/configure.m4
src/ucs/debug/debug.c
src/ucs/debug/debug_int.h
src/ucs/signal/Makefile.am
src/ucs/signal/signal.c
src/ucs/sys/sys.h

- added separate module to handle signal and sigaction calls

UCS/SIGNAL: signal and sigaction handlers were moved to separate module

---

docs/OptimizationStyle.md

Fix a potential typo in the optimizations style document
Training assignment - check I'm able to commit and create pull requests.

DOC: fix typo - patch should be path?

---

docs/source/faq.md
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_request.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/proto/proto.c
src/ucp/proto/proto.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_ppln.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucs/datastruct/string_buffer.c
src/ucs/datastruct/string_buffer.h
src/ucs/debug/log.c
src/ucs/debug/log_def.h
src/ucs/sys/string.h
test/gtest/ucp/test_ucp_proto.cc
test/gtest/ucs/test_string.cc

Improve visibility to UCX protocols selection and switch-over thresholds

UCP/PROTO: Print endpoint's protocols configuration as a table

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/io_demo/io-demo.yml

remove artifacts after success test
artifacts have a big size

AZP: remove artifacts after test

---

src/ucp/am/eager.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/rma/amo_sw.c
src/ucp/rma/rma_sw.c
src/ucp/rndv/rndv.c
src/ucp/stream/stream_recv.c
src/ucp/tag/eager_rcv.c
src/ucs/sys/init.c

- refactoring of AM handlers initialization to make it called from single
entry point

UCP/AM: handlers initialization static init

---

src/ucp/core/ucp_request.inl

UCP/REQUEST: Fix adding one lane to registration map with user memh

---

src/ucp/Makefile.am
src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/proto/proto.c
src/ucp/proto/proto_multi.inl
src/ucp/tag/eager_multi.c
test/gtest/ucp/test_ucp_am.cc

Added AM multi-fragment bcopy protocol for new infrastructure. 
The changes are part of UCP transition to new infrastructure.

UCP/AM: Added implementation of multi-fragment bcopy.

---

src/ucm/Makefile.am
src/ucm/configure.m4
src/ucm/ucx-ucm.pc.in
src/ucs/Makefile.am
src/ucs/configure.m4
src/ucs/ucx-ucs.pc.in
src/ucs/vfs/fuse/ucx-fuse.pc.in
src/uct/Makefile.am
src/uct/configure.m4
src/uct/cuda/gdr_copy/ucx-gdrcopy.pc.in
src/uct/cuda/ucx-cuda.pc.in
src/uct/ib/rdmacm/ucx-rdmacm.pc.in
src/uct/ib/ucx-ib.pc.in
src/uct/rocm/gdr/ucx-rocm-gdr.pc.in
src/uct/rocm/ucx-rocm.pc.in
src/uct/sm/mm/xpmem/ucx-xpmem.pc.in
src/uct/sm/scopy/cma/ucx-cma.pc.in
src/uct/sm/scopy/knem/ucx-knem.pc.in
src/uct/ucx-uct.pc.in
src/uct/ugni/ucx-ugni.pc.in

- added libraries and dependencies for basic PC files: cma/knem/fuse
- updated PC files to use new macro for version definition

BUILD/CONFIG: added content for basic pc files

---

buildlib/pr/io_demo/az-stage-io-demo.yaml
test/apps/iodemo/run_io_demo.sh

Allows running on an environment with multiple network interfaces in the
same subnet.
To run multi-interface tests in the same environment
cc @avildema

TEST/IODEMO: Bind to local IP address

---

NEWS

NEWS: Update for v1.12.1-rc3   (v1.12.x)

---

src/tools/perf/lib/libperf.c

Fix segfault in perftest when worker create failed and trying to destroy the workers as part of cleanup flow

TOOLS/PERF: Fix worker destroy in error flow

---

src/tools/perf/lib/uct_tests.cc

Fix #7977
- Avoid running receive-side logic in loopback case, so m_last_recvd_sn is not overridden with an invalid value, since it's actually the same variable instance for both sender and receiver
- Receiver side logic is not really needed for loopback case - added code comment to explain why
Before the fix - test failed at iteration 185
After the fix - passed 1000 iterations

TOOLS/PERF: Fix assertion in test_uct_loopback

---

src/uct/ib/base/ib_md.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_devx.c

Better debug information about DevX related checks

UCT/IB: Improve DevX debug prints

---

test/gtest/common/test_helpers.cc

Do not run sockaddr tests on devices without proper IPv4/IPv6 address

TEST/COMMON: Skip IPv6 link-local and loopback addresses

---

contrib/test_jenkins.sh

Optimize testing time. Needed mostly for embedded systems such as BlueField.

TEST/JENKINS: Unite devel and release tests, to reduce compilation time

---

.gitignore
buildlib/pr/main.yml
buildlib/tools/builds.sh
buildlib/tools/check_tls.sh
configure.ac
src/ucm/ucx-ucm.pc.in
src/ucs/ucx-ucs.pc.in
test/apps/uct_info/Makefile.in
test/apps/uct_info/configure.m4
test/apps/uct_info/uct_info.c

- added application to link with UCT statically
produces output like:
```
#
#
#
```

TEST/APP/UCT: added test app for static UCT build

---

src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/proto/proto.c
test/gtest/ucp/test_ucp_am.cc

Added AM multi-fragment zcopy protocol for new infrastructure.
The changes are part of UCP transition to new infrastructure.

UCP/AM: Added implementation of multi-fragment zcopy.

---

src/ucs/sys/preprocessor.h
src/uct/base/uct_component.c
src/uct/base/uct_component.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/configure.m4
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/exp/ib_exp_md.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/rdmacm/rdmacm_component.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c
src/uct/sm/mm/base/mm_iface.h
src/uct/sm/mm/base/mm_md.h
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_iface.c

- re-design of IB initialization: used single constructor entry to
initialize IB module

UCT/IB: used single constructor entry

---

src/uct/cuda/Makefile.am
src/uct/cuda/gdr_copy/Makefile.am
src/uct/rocm/Makefile.am
src/uct/rocm/gdr/Makefile.am
src/uct/ugni/Makefile.am

- disabled installation of unused .pc files

BUILD/CONFIG: disabled unused .pc files

---

src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c

Aligned function names with files hierarchy.
+ removed duplicate function filling zcopy footer.
Fixed https://github.com/openucx/ucx/pull/8019#discussion_r825461677

UCP/AM: Aligned function names with files hierarchy.

---

src/ucp/core/ucp_am.c
src/ucp/proto/proto_common.inl
src/ucp/rma/amo_send.c
src/ucp/rma/rma_send.c
src/ucp/tag/tag_send.c

Fixed active message protocol selection taken into account user header length.

UCP/PROTO: Proto selection take into account user header length.

---

ucx.spec.in

- added static libs to RPM build of devel package

BUILD/RPM: added static libs

---

src/ucp/am/eager_single.c
test/gtest/ucp/test_ucp_am.cc

Fixed single zcopy proto initialization.
Fixed proto v2 am tests.

UCP/AM: Fixed single zcopy proto initialization.

---

buildlib/dockers/centos7.Dockerfile
buildlib/pr/main.yml
buildlib/tools/builds.sh
buildlib/tools/check_tls.sh
src/ucs/ucx-ucs.pc.in
src/uct/ib/ucx-ib.pc.in

- added content of .pc file for IB module
- updated CI scripts to test IB components

BUILD/IB: added content of ucx-ib.pc module file

---

src/ucp/am/eager_single.c

Added missed flags to Active Message eager short protocols.

UCP/AM: Fixed missed proto flags.

---

contrib/test_jenkins.sh

Fix recent CI failures on BlueField and HWI-arm due to changes in hpcx-gcc module

CONTRIB/JENKINS: Fix module for MPI tests

---

buildlib/pr/main.yml
buildlib/tools/builds.sh
test/apps/uct_info/Makefile.in

- added ucp test for static build
- added CMA transport into static test
- updated docker config to enable CMA

UCP/STATIC: added ucp test

---

buildlib/pr/main.yml

Add RHEL9.0 to CI to build tests

AZP: Add RHEL9.0 to CI

---

buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/io_demo/io-demo.yml
test/apps/iodemo/run_io_demo.sh

Add new key to run_io_demo.sh
--env client UCX_IB_NUM_PATHS=1 \
--env server UCX_IB_NUM_PATHS=2 \
--env all UCX_RNDV_THRESH=4k \
allow set different envs for servers and client

TEST: Add env key to iodemo.sh

---

contrib/test_jenkins.sh

Fix recent CI failures on HWI machine, since armclang license expired
- Unload module if "armclang -v" fails and set the job status as "completed with issues"
- Remove "l" from the test_jenkins.sh shebang to use functions from az-helpers.sh script, which is sourced before running test_jenkins.sh

CONTRIB/JENKINS: Unload armclang module if it's unusable

---

src/uct/ib/base/ib_md.c

Now the RDMA transport is automatically disabled when the memlock limit is lower than some predefined value. This patch removes this logic.
It was decided that hard error during the further operation with IB transport is better customer experience than disabling of transport + warning. Plus we cannot define some common limit that will guarantee the proper RDMA transport work in all cases.

UCT/IB: Remove RDMA transport disabling logic in case of too low memlock limit value

---

buildlib/tools/check_tls.sh
src/ucs/config/ucm_opts.c
src/ucs/config/ucm_opts.h
src/ucs/sys/init.c
src/ucs/ucx-ucs.pc.in

- added missing copyrights in scripts
- minor sync with int3 branch

COMMENTS/COPYRIGHTS: added missing copyrights

---

buildlib/pr/main.yml
src/uct/ib/rdmacm/ucx-rdmacm.pc.in

- added content for .pc file for rdmacm component

RDMACM/BUILD: added content for .pc file

---

src/ucp/Makefile.am
src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/am/rndv.c
src/ucp/am/ucp_am.inl
src/ucp/core/ucp_am.c
src/ucp/proto/proto.c
src/ucp/proto/proto.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl
src/ucp/rma/amo_send.c
src/ucp/rma/rma_send.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv.h
src/ucp/rndv/rndv.inl
src/ucp/rndv/rndv_get.c
src/ucp/tag/tag_rndv.c
src/ucp/tag/tag_send.c
test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_proto.cc

Added AM rendez-vous protocol for new infrastructure.
The changes are part of UCP transition to new infrastructure.

UCP/AM: Added implementation of rendez-vous protocol.

---

src/uct/ib/base/ib_md.c

IB/MD: removed artefact

---

src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

DC code improvements.
To reduce code duplications and decrease amount of code.
1. Remove separate `if` block for randmo DCI policy to do arbiter group purge in `uct_dc_mlx5_ep_pending_purge`.
2. Remvoe branch `uct_dc_mlx5_iface_is_dci_rand` from `uct_dc_mlx5_iface_dci_detach`.

UCT/IB/DC: Code simplifications

---

docs/source/faq.md

- added instructions how to build UCX-based apps for dynamic and static modes

DOCS/FAQ: added build instructions

---

src/uct/ib/base/ib_md.c

More proper checks for ibv_get_device_list return values, and error message print.
If no devices are found, then num_devices is set to 0, and non-NULL is returned by ibv_get_device_list.
To avoid unnecessary 0-size allocations.

UCT/IB/BASE: Checked ibv_get_device_list return values.

---

src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/ud/accel/ud_mlx5.c

Backport https://github.com/Mellanox/ucx/pull/25
To prevent coredump in case of ifdown/ifup

UCT/IB: Backport device fatal handling

---

src/ucp/wireup/wireup_cm.c

Change CM wireup fallback log level.
To reduce amount of traces in case of `UCX_LOG_LEVEL=diag`
1. Change logging of fallback as follows:
- debug: has another variant of endpoint initialization flags
- diag: has another CM
- error: otherwise
2. Trace CM fallback as `DIAG`.

UCP/WIREUP: Change CM wireup fallback log level

---

src/ucp/rndv/rndv.c

- fix `ucp_rkey_pack_uct` wrong parameters ordering
- set `UCP_REQUEST_FLAG_RKEY_INUSE` in correct place
backport from https://github.com/openucx/ucx/pull/8137

UCP: ucp rkey pack v1.13.x

---

src/ucp/rndv/rndv.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
test/gtest/uct/test_md.cc

UCT/MD/IB: improve dereg param check
this part was missed https://github.com/openucx/ucx/pull/8072#discussion_r844943165

UCT/MD/IB: improve dereg param check

---

src/ucs/debug/memtrack.c
test/gtest/ucs/test_memtrack.cc
test/gtest/ucs/test_rcache.cc

Added logging of zero-size allocation.

UCS/DEBUG: Log zero-size allocation.

---

test/gtest/ucp/test_ucp_am.cc

Fixed reply configuration of test_ucp_am_nbx_seg_size.
Moved reply configuration to new parent class.

GTEST/UCP: Fixed UCP AM test configuration.

---

buildlib/tools/builds.sh
configure.ac
test/gtest/ucp/test_ucp_context.cc
ucx.spec.in

fix versioning infra
the bugs were discovered with bumping extra version

UCX: fix versioning infra

---

buildlib/tools/builds.sh
configure.ac
test/gtest/ucp/test_ucp_context.cc
ucx.spec.in

backport of https://github.com/openucx/ucx/pull/8163

UCX: fix versioning infra v1.13.x

---

src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_ep.c
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/base/ud_iface.h
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/uct/ib/test_ud.cc

Drop packets if EP is p2p and disconnected.
Backportinf of #8151.
See #8151's description.

UCT/IB/UD: Drop packets if EP is p2p and disconnected [v1.13.x]

---

test/gtest/ucm/malloc_hook.cc

GTEST: Silence use-after-free Fedora 36 GCC error

---

docs/source/faq.md

- re-worded some text in static build section

DOCS/FAQ: re-worded static build section

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_init.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_rtr.c
src/ucs/datastruct/linear_func.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/gdr/rocm_gdr_md.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
test/gtest/ucs/test_math.cc

Will be used in several places in protocol v2 performance calculations

UCP/UCT/UCS: Add define for zero linear function

---

contrib/pr_merge_check.py

Pushing (or force-pushing) commits would change the state of reviews from APPROVED to DISMISSED

CONTRIB/PR_MERGE: Support dismissed review

---

src/ucm/malloc/malloc_hook.c

Valgrind leak detection is partially broken (leaks not detected) because of UCM. This PR fixes it.

UCM/MALLOC: Fix memory leak detection with valgrind

---

test/apps/iodemo/io_demo.cc

Print per-connection info in this format:
```
[1652359269.408880] [UCX-connection 0x204a0e0: #1 1.1.1.3:1337] read 371.476MBs iops: 95097 max-lat: 26.9413us avg-lat: 4.94058us | write 371.476MBs iops: 95097 max-lat: 21.9345us avg-lat: 5.04014us | total 742.952MBs iops: 190195 max-lat: 26.9413us avg-lat: 4.99036us
```
Sometimes we need analyse latency on per-connection basis.

APPS/IODEMO: latency per connection

---

src/uct/rocm/ipc/rocm_ipc_ep.c

use the correct remote_agent handle if information is available. Using the local_agent for both src and destination is just the backup plan in case the remote_agent info is not available, e.g. in case the user limited the visibility of devices for a/some/all processes.
using the local_agent for both src and destination triggers a different code both in the runtime layer than using two different agents, limiting the availability of the CUs for compute operations.

UCT/ROCM/IPC: use remote_agent if available

---

src/ucp/core/ucp_worker.c

Same or better atomics capabilities are now a condition when choosing interfaces for a specific worker
For each worker we need the minimal set of interfaces to use, such that all capabilities are at least as good as all the rest.
(including atomics)

UCP/CORE: added atomic caps comparison to 'ucp_worker_iface_find_better'

---

buildlib/az-network-corrupter.sh
buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/io_demo/io-demo.yml
test/apps/iodemo/run_io_demo.sh

add test for multi HPCs test for iodemo

AZP: Add multi HCAs iodemo test

---

src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
test/gtest/ucp/test_ucp_am.cc

Fixed max payload calculation for AM in new infra to take into account AM user header size.

UCP/PROTO: Fixed max payload calculation for AM in new infra.

---

src/uct/ib/dc/dc_mlx5_ep.c

Fix managing `FC_HARD_REQ` resend time in DC transport.
`iface->tx.fc_hard_req_resend_time` is initialized only, but then never updated. So, it always leads to invoking of `uct_dc_mlx5_ep_fc_hard_req_progress`.
1. Add new function `uct_dc_mlx5_ep_fc_hard_req_set_resend` which sets the `iface->tx.fc_hard_req_resend_time` to the `now + iface->tx.fc_hard_req_timeout` value, i.e. the time when `uct_dc_mlx5_ep_fc_hard_req_progress` must be called again.
2. Invoke `uct_dc_mlx5_ep_fc_hard_req_set_resend` in `uct_dc_mlx5_ep_check_fc` if `kh_hash` of FC_HARD_REQs is empty.
3. Invoke `uct_dc_mlx5_ep_fc_hard_req_set_resend` in `uct_dc_mlx5_ep_fc_hard_req_progress` if `now >= iface->tx.fc_hard_req_resend_time`.

UCT/IB/DC: Fix managing FC_HARD_REQ resend time

---

src/ucp/core/ucp_ep.c
src/ucp/proto/proto_common.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.inl
src/ucp/tag/eager_single.c

- add ucp_eager_bcopy_single_proto.abort
- fix pending perge for rndv get with ats stage]
fixes io_demo with new protocols

UCP/PROTO: error flows

---

NEWS

update release date in NEWS file

NEWS: update release date - v1.13.x

---

buildlib/pr/io_demo/az-stage-io-demo.yaml
buildlib/pr/io_demo/io-demo.yml
src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/configure.m4
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h
test/gtest/uct/ib/test_rc.cc

Support ECE(enhanced connection establishment) in UCX.
ECE could be used to negotiate 1) packet loss 2) congestion control strategy etc. between source and target.
It's better to make use of this feature in UCX.
Issue: 2332889 & 2684830
Design document
Public: [UCX ECE Development](https://docs.google.com/document/d/1TEBDa83299gKvkhvOI4AMlFMazZQ3Zle-JfiAt1UwNE/edit?usp=sharing)

Add Enhanced Connection Establishment feature

---

src/tools/info/type_info.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_request.h
src/ucp/core/ucp_request.inl
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/rma/flush.c
src/ucp/stream/stream.h
src/ucp/stream/stream_recv.c
src/ucp/wireup/ep_match.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
test/gtest/common/test_obj_size.cc

Unite all EP extensions to a single struct
Preparation for supporting many lanes

UCP/CORE: Refactor endpoint extension

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_get.c
src/ucs/datastruct/string_buffer.c
src/ucs/datastruct/string_buffer.h
src/ucs/sys/sys.c
src/ucs/sys/sys.h
test/gtest/ucs/test_string.cc

Add the infrastructure to print protocol performance visualization as .dot file. The output is demonstrated in #8233

UCP/PROTO: Infra to print protocols performance

---

src/uct/ib/base/ib_md.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/test_md.cc

Backport of:
- https://github.com/openucx/ucx/pull/8218
- https://github.com/openucx/ucx/pull/8251

UCT/IB/GTEST: Backport KSM registration fixes [v.1.13.x]

---

test/gtest/ucp/test_ucp_tag_mem_type.cc

Reduce testing time.
Testing time on GPU nodes is reduced by ~1hr.

TEST/UCP/TAG: Remove or skip unnecessary mem type variants

---

src/ucs/vfs/base/vfs_cb.c
src/uct/ib/ud/base/ud_ep.c
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/base/ud_iface.c

Inspect UD endpoint TX/RX state

UCT/UD: Add UD endpoint information to VFS

---

src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Clone of https://github.com/openucx/ucx/pull/8293 for v1.13.x

UCT/CUDA: use right driver macro to log errors with drv fxns - v1.13.x

---

src/uct/rocm/copy/rocm_copy_iface.c

provide an implementation of estimate_performance for the internal ops.
Makes a test pass in the gtest suite.

UCT/ROCM/COPY: implement estimate_perf function

---

buildlib/pr/main.yml

AZP: remove HWI hosts from testing

AZP: remove HWI hosts from testing - v1.13.x

---

buildlib/pr/main.yml

AZP: remove HWI hosts from testing

AZP: remove HWI hosts from testing

---

test/gtest/common/mem_buffer.cc

fix issue in rocm gtest
execute gtests for hip unified memory only on relevant platforms
Added another check so that the ROCM managed memory tests will run on the machines where this is relevant

GTEST/ROCM_Managed_memory: more checks is_rocm_managed_supported

---

src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c

Following up on #8282 , adding performance estimation information to rendezvous protocols

UCP/PROTO/RNDV: Add performance data to rendezvous protocols

---

test/gtest/uct/ib/test_ib.cc

Get info about CQ events from the corresponding mlx5 related structure (`uct_ib_mlx5_cq_t`)  during the test if possible.
It's a part of bigger #8257 PR that adds ability to create CQ using DEVX. If CQ created using DEVX, there is no `ibv_cq` entity anymore, so any CQ information should be discovered via corresponding UCX cq structure if possible.

GTEST/IB: Get CQ events info from mlx5 structure if possible

---

buildlib/pr/io_demo/io-demo.yml
buildlib/pr/io_demo/jobs-io-demo.yaml
buildlib/pr/main.yml

AZP: improve CI

---

src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_wireup.cc

1) Added fp8 pack/unpack to local latency value when calculating transport score (address V2).
2) Added num_eps to latency calculation (address V1).
1) FP8 is a lossy compression method, so it can cause modification to remote latency values, when packing/unpacking remote address. 
As a result, score calculation is effected, and may cause asymmetric transports selection in a pair of connected endpoints.
The solution is adding pf8 pack/unpack to local address, which will make the calculation symmetric.
2) In address V1, remote address latency now contains num_eps. This was done to match the existing local address latency calculation.

UCP/WIREUP: Symmetric latency calculation in transport selection

---

test/gtest/ucp/test_ucp_am.cc

Replaced using of variants by iterating through datatypes inside a test in UCP AM gtests.
The objective of the changes is to reduce test execution time while keeping coverage at the same level.

GTEST/UCP: Replaced variants by iterating datatypes in AM tests.

---

src/uct/base/uct_iface.h
src/uct/ib/base/ib_md.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/base/rc_ep.c
src/uct/ib/rc/base/rc_ep.h
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h
test/gtest/uct/test_flush.cc

- added IB DEVX memory registration into MD
- updated DC iface address to include flush remote remote key
- updated RDMA atomic/put operation to store flush remote flag
- added smoke test for slush remote operation

UCT/DC: added flush remote operation

---

NEWS

Update NEWS file for 1.13.0 release
Merge rc1 and rc2 change lists

NEWS: 1.13.0 update

---

src/ucp/rndv/proto_rndv.c

Fix failure when gdrcopy was loaded on one machine and not the other one, since md_map was different on local and remote side could not select the right lane for data transfer.
Set remote key configuration according to remote MD map

UCP/PROTO/RNDV: Use remote md_map (instead of local) for rkey config

---

test/gtest/ucp/test_ucp_sockaddr.cc

minor code improvement using c++11
code cleanup

GTEST: minor code improvement in test_ucp_sockaddr using c++11

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.inl

add memh logging
for development and debug purposes

UCP/CORE: add memh logging

---

bindings/java/src/main/native/jucx_common_def.cc

If listener is bind to Ipv6 address, we don't copy its scope_id to java.
@hoopoepg  can you please check on your PR
Android java implementation has a handy method: [`private static InetAddress getByAddress(String hostName, byte[] ipAddress, int scopeId) `](https://android.googlesource.com/platform/libcore/+/9b510df35b57946d843ffc34cf23fdcfc84c5220/luni/src/main/java/java/net/InetAddress.java#858). Unfortunately, openjdk doesn't have this method - so in case of Ipv6 we need to construct an instance of java.net.Inet6Address with a scope id.

JUCX: Copy scope id to java inet address.

---

contrib/test_jenkins.sh

Fix CI failures where ucp_client_server test could not listen to port 20000, for example: 
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=47914&view=logs&j=74876da5-c0e8-5509-4929-d550f147815a&t=8a45b11e-6db7-52a5-8389-552756497e36
This port number is also used by io_demo test.

TEST/JENKINS: Fix TCP port ranges in CI

---

contrib/test_jenkins.sh

TEST/JENKINS: Fix TCP port ranges in CI - v1.13.x

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/accel/rc_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_ep.h
src/uct/ib/rc/verbs/rc_verbs.h
src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
test/gtest/common/test_obj_size.cc
test/gtest/uct/uct_test.cc

- added RC_V/RC_MLX5 implementation for flush_remote
- updated tests itialization to use iface address

UCT/IB/RC: flush remote

---

src/ucp/rndv/rndv.c
test/gtest/ucp/test_ucp_sockaddr.cc

Fix support of user's memh for RNDV AM and PUT Zcopy schemes.
User's memory handle isn't used by RNDV AM and PUT Zcopy schemes.
1. Update `ucp_rndv_reg_send_buffer` function to set a user's memory handle even if RNDV scheme isn't set to GET Zcopy.
2. Reproduce the issue for RNDV AM and PUT Zcopy schemes by updating `test_am_send_recv` to support a send memory handle.

UCP/RNDV/GTEST: Fix support of user's memh for RNDV PUT Zcopy scheme

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/ud/accel/ud_mlx5.c

- enabled HW DCS support
- added runtime configuration to limit DCI streams to use
- updated *post_op routines to set DCI stream channel ID
- added HCA capabilities read to get max DCI stream number

DC/HW-DCS: enabled HW DCS

---

src/ucp/api/ucp.h

- align description of ucp_worker_fence with shmem_fence

API/UCP: align ucp_worker_fence description with oshmem

---

src/ucp/wireup/select.c

UCP/WIREUP/SELECT: Update wireup lane bandwidth calculation - v1.13.x

---

src/uct/ib/base/ib_iface.c

Fixes BW reporting for RoCE LAGs
For UCT users to get correct BW characteristics for RoCE LAG tls

UCT/IB: Report correct BW for RoCE LAGs

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/rma/get_offload.c
src/ucp/rma/put_offload.c
src/uct/tcp/tcp_ep.c
test/gtest/ucp/test_ucp_rma.cc

- enabled multirail for RMA on new proto
- fixed issue in TCP wireup initialization

UCP/RMA: enabled RMA multirail

---

src/ucp/am/eager_single.c
test/gtest/ucp/test_ucp_am.cc

Fixed single vs multi protocol selection taking into account reply footer size.

UCP/AM: Fixed single vs multi selection adding reply footer size.

---

debian/rules.in

Build the debian package with `--enable-mt` 

BUILD: Build the debian package with multiple-thread support

---

src/ucp/wireup/address.c

Add error traces for UCP address pack/unpack failures

UCP: Add error traces for address pack/unpack errors

---

docs/source/faq.md

update RDMA requirements in FAQ
sync with https://github.com/openucx/ucx/pull/8403

DOC/FAQ: update RDMA requirements

---

src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_am.c

UCP/RNDV: Fix rDnv typo

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c

Always remove EPs from FC hash when restoring FC window.
1. If some endpoint was failed and its FC window was restored, it could still exist on FC hash to resend `FC_HARD_REQ`s, but it doesn't make sense anymore.
2. If some endpoint was `flush(CANCEL)`ed, it could still exist on FC hash to resend `FC_HARD_REQ`s with exhausted FC window (since we don't restore it), and consume new DCIs for trying to resend `FC_HARD_REQ` packet, but these attempts would fail in case of peer is unreachable. So, it could lead to "timeout waiting for replies" in IO-demo, since DCIs can't be reused by normal not failed endpoints to send their data.
1. Introduce `uct_dc_mlx5_fc_restore_wnd` function which gets an iterator from FC hash, removes an element from FC hash updates FC window, and progress pending if …

UCT/IB/DC: Always remove EPs from FC hash when restoring FC window

---

src/uct/api/v2/uct_v2.h

Fix comment for UCT tag matching rendezvous operation

UCT/DOC: Fix rndv operation comment

---

NEWS

NEWS: v1.13.1 release

---

src/ucp/wireup/select.c

Ignore path indexes when adding new lane and there is existing non-bw lane with the same tl resources
The problem shown on the picture below may appear on heterogeneous configurations, like:
- only one of nodes has bonding device/interface configured
- different number of paths used by devices on different peers
- etc

UCP: Ignore path idx for non-bw lanes

---

src/ucp/api/ucp.h

Introduce exported memory handle API.
External memory handle will be used to allow using UCP operation on a memory allocated by another process on same or another process, but registered on the same network device.
1. Introduce new value `UCP_EP_PARAMS_FLAGS_EXPORTED_MEMH` in `ucp_ep_params_flags_field` enumeration.
2. Introduce new value `UCP_MEM_MAP_PARAM_FIELD_EXPORTED_MEMH_BUFFER` in `ucp_mem_map_params_field` enumeration.
3. Introduce new value `UCP_MEM_MAP_EXPORTED` in enumeration which are used then as flags passed to `ucp_mem_map()`.
4. Introduce new field `exported_memh_buffer` in `ucp_mem_map_params_t` structure.
5. Move comments for each field before the value in `enum ucp_ep_params_flags_field`, `enum ucp_mem_map_params_field`, `ucp_mem_map()` flags enumerations to fit 80 …

UCP/API: Introduce exported memory handle

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/base/mm_md.c
src/uct/sm/mm/base/mm_md.h
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/cma/cma_md.h
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/scopy/knem/knem_md.h
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
src/uct/ugni/base/ugni_md.c

In preparation for https://github.com/openucx/ucx/pull/7847 being broken into separate PRs, introduce md_query_v2 in this PR.

UCT/API/V2: Introduce md_query_v2

---

buildlib/pr/main.yml
buildlib/pr/tests.yml
contrib/test_jenkins.sh

add to CI gtest with proto enable eq yes

AZP: add to CI gtest with proto enable

---

buildlib/pr/main.yml
buildlib/tools/build_static.sh
buildlib/tools/builds.sh

move build with static library to separate stage in CI

AZP: build static like a separate stage

---

src/ucp/core/ucp_request.c

- query mem type
- access to freed EP in case of request leak
`UCX_PROTO_ENABLE=y gtest --gtest_filter=*ucp*request*leak*:*ucp*request*query*`

UCP/PROTO: fix request query

---

test/gtest/ucp/test_ucp_fence.cc
test/gtest/ucp/test_ucp_wireup.cc

Fix blocking UCP cases
SW protocols and RNDV requires progress of both sides

GTEST: fix blocking UCP cases

---

src/ucp/rma/amo_offload.c
src/ucp/rma/amo_sw.c
src/ucp/rma/put_am.c
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_rtr.c

UCP: minor fixes in code style

---

src/ucp/proto/proto_common.inl
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/proto_eager.inl
src/ucp/tag/tag_rndv.c

UCP/PROTO: add statistic

---

buildlib/pr/main.yml
src/ucp/wireup/select.c

Add support Ubuntu 22.04 and 22.10

AZP: Add support ubuntu 22.xx

---

src/ucp/core/ucp_mm.c

Set parent memh field for memh created with `UCP_MEM_MAP_ALLOCATE` flag.
Fixes the following bug:
```
[ RUN      ] shm_ib_ipc/test_ucp_mmap.fixed/3 <shm,ib,cuda_ipc,rocm_ipc,cuda_copy,rocm_copy/no_rcache>
[New Thread 0x7ffff2540700 (LWP 192078)]
[jazz11:191967:0:191967]    ucp_mm.inl:89   Assertion `context->rcache != ((void *)0)' failed
/hpc/mtr_scrap/users/dmitrygla/ucx/src/ucp/core/ucp_mm.inl: [ ucp_memh_put() ]
...
86         return;
87     }
88
==>    89     ucs_assert(context->rcache != NULL);
90
91     UCP_THREAD_CS_ENTER(&context->mt_lock);
92     ucs_rcache_region_put_unsafe(context->rcache, &memh->super);
==== backtrace (tid: 191967) ====
0 0x000000000006debb ucp_memh_put()  /hpc/mtr_scrap/users/dmitrygla/ucx/src/ucp/core/ucp_mm.inl:89
1 0x000000000006debb ucp_mem_unmap() …
```

UCP/CORE: Set parent memh field for memh created with ALLOCATE flag

---

examples/ucp_hello_world.c

Switches deprecated API calls inside `ucp_hello_world` example to non-deprecated ones.

UCP/EXAMPLE: Get rid of deprecated API usage inside ucp_hello_world

---

buildlib/pr/main.yml

swx-infra was be deleted from rdmz side 
move all need images to ucx proj

AZP: change path to docker images

---

src/ucs/debug/log.c

Fix UCS logger wrongly handle fork() and prints wrong pid.
To reduce calls to getpid() process pid is cached on a static var. 
After calling to fork() process pid is changed and global vars are duplicated so the cached pid values of the child and parent are equal. 
UCS Logger handle that by attaching atfork handler to the child process. this handler change the log_pid var value to the child pid, 
but if the application attach more atfork handlers before UCS they will be called before UCS atfork handler and can cause the logger to run with the wrong pid...
From the Man:
"The handlers for each phase are called in a specified order: 
the prepare handlers are called in reverse order of registration; 
**the parent and child handlers are called in the order of registration**"
By creating "init …

UCS/VFS/LOG: Fix fork() child pid handling when assigning multiple atfork handlers

---

src/ucp/rndv/rndv.c

Do not check local MD caps using remode MD index in 2-stage pipeline protocol
Peers may be heterogeneous and MD indexes may not match on both sides 
Add one more byte with md index to the RTR packet (after rkey). Presence of this md index would mean that 2-stage pipeline is possible

UCP: Remove checking local md caps for remote MDs

---

src/ucp/rma/amo_sw.c

UCP/AMO/SW: fixed incorrect assert

---

contrib/pr_merge_check.py

Allow checking diff even if PR was not approved yet

CONTRIB/PR: Check diff after multiple force pushes

---

examples/ucp_hello_world.c

- there was incorrect connection sequence in UCP hello world which leads backward compatibility

UCP/HELLO-WORLD: fixed connection issue

---

src/tools/perf/perftest.c

Fix ucx_perftest hang in MPI mode. The hang may occur when peers are exchanging meta information using `MPI_Send` and rendezvous protocol is selected by the MPI. In this case `MPI_Send` will hang until matching `MPI_Recv` is posted (which is not assumed by the `ucx_perf_rte_t` interface). 
Fixes [bug](https://redmine.mellanox.com/issues/3208341) (internal Nvidia link)
Use `MPI_Bsend` (which is always a local operation) instead of `MPI_Send`

TOOLS: Fix MPI RTE send deadlock

---

test/gtest/ucp/test_ucp_am.cc

Fix issue reported in [bug](https://github.com/openucx/ucx/issues/8523)
Receiving messages out of order caused the unit test pattern check to fail.
All AM unit tests use the same class field ("m_rx_buf" of test_ucp_am_nbx ) to store the pointer to the buffer used when calling "ucp_am_recv_data_nbx".
Due to false progressing scheme in the test, message was received out of order and therefore the pattern check was called with the wrong buffer.
Example:
//Msg 1 AM CB
m_rx_buf = allocate new buffer
call ucp_am_recv_data_nbx with
//Before msg 1 finished - Msg 2 AM CB
m_rx_buf = allocate new buffer
call ucp_am_recv_data_nbx with m_rx_buf 
//msg 2 received 
pattern check called with m_rx_buf 
release m_rx_buf
//msg 1 received 
pattern check called with m_rx_buf 
error...
Fix the unit test …

GTEST: AM copy header - Enforce receiving all the messages in a test set before moving to the next set

---

src/ucp/am/rndv.c
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_common.inl
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/eager_multi.c
src/ucp/tag/offload/eager.c
src/ucp/tag/tag_rndv.c

add more `ucp_proto_t::reset`
- RNDV
- sync send

UCP/PROTO: add more ucp_proto_t::reset

---

src/ucp/rndv/proto_rndv.c

Taken into account send NBR threshold for calculation of rendezvouz protocols threshold in new infrastructure.
There are use cases with worse latency using new protocol infrastructure comparing to old infra. These cases are characterized by using of UCP_OP_ATTR_FLAG_FAST_CMPL operation flag.

UCP/RNDV: Use send NBR threshold as threshold for fast completion rendezvous.

---

test/gtest/ucp/test_ucp_wireup.cc

fix select_transport_rma_bw.select_rc test
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/52235/logs/628

GTEST: fix select_transport_rma_bw.select_rc

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_request.h
src/ucp/core/ucp_types.h
src/ucp/rma/flush.c
test/gtest/ucp/test_ucp_fence.cc

- added implementation of worker_fence via EPs flush_remote calls
- added test

UCP/WORKER_FENCE: added worker_fence over EPs

---

src/uct/ib/base/ib_md.c

fixes https://github.com/openucx/ucx/issues/8628

IB/MD: fixed build on SLES SP3

---

src/uct/ib/base/ib_md.c

Pack `component_name` to `global_id` in MD attributes.
To make sure that `global_id` is unique even for different components.
1. Save `md_attr->global_id` to a local variable.
2. Copy `md->component->name` to `md_attr->global_id`.
3. And copy a data from a local variable of `global_id` to `md_attr->global_id + strlen(md->component->name)`.

UCT/BASE/IB: Pack component_name to global_id in MD attributes

---

docs/source/faq.md
src/uct/cuda/base/cuda_iface.h

Report ptx error even if error is hidden and add FAQ

UCT/CUDA: address "provided PTX was compiled with an unsupported toolchain" error

---

buildlib/pr/distro.yml

AZP: add test for compatibility

---

src/uct/ib/configure.m4
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_iface.c

Fixing internal issue [3232874](https://redmine.mellanox.com/issues/3232874)

UCT/IB/DEVX: Fix HAVE_DEVX macro

---

test/gtest/ucp/test_ucp_tag_xfer.cc

Fix multi_rail_max test failure
Removed static var declaration from msg_size calculation, and re-enabled multi_rail_max test.

TEST/UCP: Removed static var declaration from msg_size calculation.

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Backport https://github.com/openucx/ucx/pull/8656

UCT/IB/DEVX: Check UAR support - v1.14.x

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fixing internal issue [3236372](https://redmine.mellanox.com/issues/3236372)

UCT/IB/DEVX: Check UAR support

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/am/rndv.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h
src/ucp/proto/proto_am.inl
src/ucp/rndv/proto_rndv.c
test/gtest/ucp/test_ucp_am.cc

fix proto/AM send status handler 
request can be completed and released

UCP/PROTO/AM: fix send status handler

---

src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rtr.c

RTR abort implementation
```
Fatal: abort request 0x55a552290840 proto rndv/rtr/mtype, not implemented
```

UCP/PROTO: RTR abort implementation

---

src/ucp/proto/proto_common.c

- Check rkey_ptr capability on the component if protocol sets `UCP_PROTO_COMMON_INIT_FLAG_RKEY_PTR` flag
- Allow to search any type of line (i.e. `UCP_LANE_TYPE_LAST`)
Will be used by 2-stage pipeline protocol to find any suitable lane with rkey_ptr property on its component
ref #8668

UCP/PROTOV2: Check rkey_ptr cap on component

---

contrib/test_jenkins.sh
test/mpi/Makefile.am
test/mpi/test_memhooks.c

TEST/JENKINS: Disable osc/ucx component when using mpirun - v1.14.x

---

contrib/test_jenkins.sh
examples/ucp_client_server.c

Defines AM receive callback on the client side. Additionally extends the CI to cover this case.
This callback is required in case of using RNDV proto to get FIN msg.

EXAMPLES: Add recv callback for receiving FIN message

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Use `uct_ib_mlx5_devx_general_cmd` instead of `mlx5dv_devx_general_cmd` to print a syndrome when devx command fails.
E.g:
before
```
ib_mlx5dv_md.c:1464 UCX  ERROR   md 0x435e140 (mlx5_bond_1): mlx5dv_devx_general_cmd() failed: Remote I/O error
```
after
```
ib_mlx5_dv.c:464  UCX  ERROR   mlx5dv_devx_general_cmd(ALLOW_OTHER_VHCA_ACCESS) failed on mlx5_bond_1, syndrome 0x88f347: Remote I/O error
```

UCT/DEVX: Use proper wrapper for devx_general_cmd

---

src/ucp/proto/proto.c
src/ucp/rndv/rndv_am.c
src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_am.cc

rndv/am/zcopy protocol implementation

UCP/RNDV: rndv/am/zcopy new proto implementation

---

src/ucp/core/ucp_mm.c

Print memory type names instead of bits and consolidate error message for protov1/protov2 flows
Example error message:
```
[1669631183.411894] [host:11111:0]          ucp_mm.c:61   UCX  ERROR failed to register address 0x7f1186000000 (host) length 1073741824 on md[6]=ibp3s0f0: Input/output error (md supports: host)
```

UCP/MM: Improve memory registration error message

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_request.h
src/ucp/proto/proto.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_mtype.inl
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c

Complete adding 2-stage ppln protocol for protocols v2 (#8526)

UCP/RNDV: Add 2-stage ppln protocol for protocols v2

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_worker.inl
src/ucp/proto/proto_multi.c
src/ucp/wireup/address.c
src/ucp/wireup/select.c
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/base/cuda_md.c
src/uct/ib/base/ib_device.c
src/uct/tcp/tcp_iface.c
test/gtest/ucs/test_topo.cc

Filter lanes according to distance from GPU
Improve performance for GPU machines where multi lane protocols are involved

UCP/PROTO: Filter lanes according to distance from GPU (proto v2)

---

src/ucp/core/ucp_request.c

UCP/REQUEST: Add request flag names to request debug info

---

test/gtest/uct/uct_test.h

Removed declarations of functions without definitions.

GTEST/UCT: Removed declarations wo definitions.

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h

Backport of https://github.com/openucx/ucx/pull/8757

UCT/IB: Make md_open() able to return UCS_OK in case of memlock limit - v1.14.x

---

contrib/test_jenkins.sh
test/apps/Makefile.am
test/apps/test_no_cuda_ctx.c

Added test to check that `upc_init` doesn't create CUDA context.

TEST/APPS: ucp_init doesn't create CUDA context.

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Port of https://github.com/openucx/ucx/pull/8798 to 1.14.x

UCT/CUDA: Detect Hopper Architecture - v1.14.x

---

NEWS

- Align news with the latest releases
- Add news for ucx v1.14
preparation for ucx v1.14 release

RELEASE: Updated news for v1.14.x

---

AUTHORS

Update `AUTHORS` file for v1.14 release

RELEASE: Update authors for v1.14 release

---

src/ucm/api/ucm.h
src/ucm/event/event.c
src/ucm/mmap/mmap.h
src/ucm/util/replace.c
src/ucm/util/sys.c
test/gtest/ucm/malloc_hook.cc

UCM/TEST: Fix mremap() override - pass new_address

---

Makefile.am
contrib/test_jenkins.sh
contrib/ucx_perftest_config/test_types_ucp_amo
src/ucp/core/ucp_request.h
src/ucp/core/ucp_request.inl
src/ucp/proto/proto.c
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl
src/ucp/rma/amo_offload.c
src/ucp/rma/amo_send.c
src/ucp/rma/amo_sw.c
src/ucp/rma/rma.inl
src/ucp/rma/rma_send.c
src/ucp/stream/stream_recv.c
src/ucp/stream/stream_send.c
src/ucp/tag/tag_recv.c
test/gtest/ucp/test_ucp_proto.cc

Support atomic reply_buffer on GPU memory
Detect memory type of reply buffer and save it in protocol selection parameters

UCP/AMO: Fix protov2 atomics for GPU memory

---

buildlib/az-distro-release.yml
buildlib/az-helpers.sh
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose.yml
buildlib/dockers/ubuntu-release.Dockerfile
buildlib/jucx/jucx-publish.yml

This PR incorporates https://github.com/openucx/ucx/pull/8823 & https://github.com/openucx/ucx/pull/8831.

AZP/RELEASE: Add Ubuntu 22.04 and fixes

---

NEWS

Set correct date for ucx v1.14-rc1 release

RELEASE: Update news with proper date

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Use peak pcie or nvlink bandwidth for cuda_ipc perf estimates to be used by protov2. 
With this implemenation, UCP needs to rely on rkey_unpack(IpcOpenMemhandle) failing to fallback to non-cuda-ipc path. In the future we could improve this implementation further to potentially allow protov2 to make the decision to not use cuda-ipc rma_bw lane if cuda_ipc_iface_estimate_perf could process rkey and return bandwidth 0 if remote GPU is not peer-reachable.

UCT/CUDA_IPC: add a simplistic impl of estimate_perf

---

NEWS

Updating NEWS to release ucx v1.14-rc2

RELEASE: Update NEWS file for v1.14-rc2

---

test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/uct/test_mem.cc

TEST: Replacing hardcoded mmap with dynamic

---

buildlib/az-distro-release.yml

Switch to in-tree Deb build.
https://github.com/openucx/ucx/issues/8854

AZP/RELEASE: Build in-tree -  v1.14.x

---

buildlib/az-distro-release.yml

Switch to in-tree Deb build.
https://github.com/openucx/ucx/issues/8854

AZP/RELEASE: Build in-tree, move back to the working directory

---

NEWS

preparation for UCX v1.14.0.rc-3 release

RELEASE: Updated NEWS file for rc3

---

src/uct/sm/mm/base/mm_md.h

Removed declaration of function w/o definition.

UCT/SM/MM: Removed declaration of function w/o definition.

---

NEWS

RELEASE: Updated NEWS file for rc4

---

src/uct/api/uct.h

Removes an empty line in a UCT header.
It did not match the expected code style.

UCT/API: Remove empty line

---

NEWS

preparation for UCX v1.14.0-rc5 release

RELEASE: Updated NEWS file for rc5

---

src/tools/perf/lib/libperf_memory.c
src/ucp/core/ucp_context.c
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_request.c
src/ucp/wireup/select.c
src/uct/api/uct.h
src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/base/uct_mem.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h
test/gtest/uct/uct_test.cc

separate testing of AMO and KSM caps
they are not always needed together

UCT/IB/MLX5DV: separate testing of AMO and KSM caps

---

NEWS

preparation for UCX v1.14.0 RC6 release

RELEASE: Updated NEWS file for rc6

---

src/ucs/arch/aarch64/memcpy_thunderx2.S

Fixes typos
Make license section easier to read.

Typo fixes in license

---

README.md

Update installation instructions in the README 
There is no autogen script, use autoconf -fi instead.
Update Readme

README: build from git or from tarball

---

src/ucp/rndv/rndv.c

Fixing internal issue [3283063](https://redmine.mellanox.com/issues/3283063)
Remove unnecessary async lock which otherwise would block UD progress.

UCP/RNDV: Remove async blocking

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/sm/scopy/cma/cma_md.c

fix missed invalidate flags
fixes https://github.com/openucx/ucx/issues/8916
@pentschev FYI

UCT/MD: fix missed invalidate flags

---

src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_rkey.inl
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/core/ucp_worker.inl
src/ucp/proto/proto_select.c
src/ucp/rndv/proto_rndv.c
test/gtest/ucp/test_ucp_proto.cc

Back port of https://github.com/openucx/ucx/pull/8866

UCP/WORKER: convert EP configs storage to dynamic array v1.14.x

---

test/apps/iodemo/io_demo.cc

use new server info format ```<server-ip>:<port>[:<count>]``` to support repeat connect with same server.
process argument number is limited, e.g. getconf ARG_MAX. The current io_demo process can't accept too long arguments.
support [server_ip:port:repeat_count] to specify the number for repeating connection with same server.

support enable specify repeat connection to same server

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5.inl
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

HW DCS policy added to config options.
Makes it easier to use HW DCS by automatically configure all needed parameters for HW DCS to work properly.

UCT/DC: HW DCS policy added to config options

---

src/uct/ib/rc/base/rc_iface.c

```uct_ib_iface_create_qp``` calls ```uct_ib_iface_fill_attr```

UCT/IB: fill ib iface attr in ib/base/iface

---

NEWS

keep NEWS file in master synced

RELEASE: Update news file

---

buildlib/az-distro-release.yml
debian/control.in
debian/rules.in
debian/ucx-xpmem.install

Add a separate xpmem deb subpackage, that is built if the build profile xpmem is used: dpkg-buildpackage -Pxpmem

BUILD/DEBIAN: A separate xpmem binary package

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml

Add CUDA-12 support to the PR pipeline.

AZP: Add CUDA-12 support to the PR pipeline

---

src/ucp/core/ucp_ep.c

Backport https://github.com/openucx/ucx/pull/8865, no conflicts

UCP/EP: Fix rendezvous threshold for multi-path - v1.14.x

---

src/uct/rocm/base/rocm_base.c

add sys_device information for AMD GPUs.

UCT/ROCM: add sys_device for AMD GPUs

---

buildlib/az-distro-release.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose-aarch64.yml
buildlib/dockers/docker-compose-x86_64.yml
buildlib/dockers/push-release-images.sh
buildlib/dockers/ubuntu-release.Dockerfile

Add CUDA-12 support to the release pipeline.
https://github.com/openucx/ucx/issues/8912

AZP/RELEASE: Add CUDA-12 release

---

src/ucp/core/ucp_rkey.c
src/ucp/proto/proto_common.inl

minor fixes in ucp 
better debugging experience

UCP: Minor fixes in proto v2

---

src/uct/ib/base/ib_device.c

UCT/IB: Add device specification for BlueField3 - v1.14.x

---

config/m4/rocm.m4
src/uct/rocm/base/rocm_base.c
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_md.c

add support for dmabuf for the rocm memory domain.

UCT/ROCM: introduce dmabuf support

---

buildlib/jucx/jucx-test.yml
buildlib/pr/go/go-test.yml
buildlib/pr/main.yml

Port tiny micro fixes from master.

AZP: Port fixes from master - v1.14.x

---

src/ucp/wireup/select.c
src/uct/base/uct_iface.c
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/ucp/test_ucp_wireup.cc

UCT/IB: Added IB iface is_reachable_v2
Improve IB iface locality test by only comparing specific address fields.

UCT/IB: Added IB iface is_reachable_v2

---

src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h

Add configuration to control usage of dmabuf feature for cuda memory transfers

UCT/CUDA: Add config for dmabuf support

---

bindings/java/pom.xml.in
bindings/java/src/main/java/org/openucx/jucx/NativeLibs.java
bindings/java/src/main/native/Makefile.am
buildlib/az-helpers.sh
buildlib/azure-pipelines-release.yml
buildlib/jucx/jucx-build.yml
buildlib/jucx/jucx-publish.yml
buildlib/jucx/jucx-test.yml

What
Build and release ARM-based artifacts.
Part 3: Build JUCX on ARM
Why ?
https://github.com/openucx/ucx/issues/8762

AZP/RELEASE: Add ARM release - Part #3

---

src/uct/tcp/tcp_iface.c

UCT/TCP: output tcp iface device name for debug purpose

---

NEWS

Preparations for v1.15.0 release

NEWS: Add section for 1.15.0-rc1

---

src/tools/profile/read_profile.c
src/ucm/event/event.c
src/ucp/tag/eager_rcv.c
src/ucp/tag/offload.h
src/ucp/tag/tag_match.c
src/ucs/config/parser.c
src/ucs/datastruct/string_set.c
src/ucs/debug/debug.c
src/ucs/debug/memtrack.c
src/ucs/stats/stats.c
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/ib/ud/base/ud_iface.c
src/uct/sm/mm/base/mm_ep.c
src/uct/sm/mm/xpmem/mm_xpmem.c

use enumerated ```ucs_kh_put_t``` value to check kh operation return value.

UCS/DATASTRUCT: check kh op value with defined enum

---

src/ucp/Makefile.am
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_request.h
src/ucp/proto/proto.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/eager.h
src/ucp/tag/eager_multi.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload.c
src/ucp/tag/offload/eager.c
src/ucp/tag/offload/rndv.c
src/ucp/tag/tag_rndv.c
src/ucp/tag/tag_rndv.h
src/uct/ib/rc/accel/rc_mlx5.inl
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag_offload.cc

Add tag offload rendezvous and offload via sw rndv protocols for protov2 infrastructure

UCP/PROTOv2: Add rndv offload protos

---

NEWS

NEWS: News update before RC3

---

src/uct/rocm/base/rocm_base.c

The kernel has to have certain options enabled in order for dmabuf support to be fully functional. This commit adds a check whether the kernel has the required options.

UCT/ROCM: check kernel config for dmabuf support

---

src/ucp/core/ucp_am.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_request.inl
src/ucp/dt/datatype_iter.inl
src/ucp/dt/dt_iov.c
src/ucp/dt/dt_iov.h
src/ucp/rma/rma_send.c
src/ucp/rndv/proto_rndv.c
src/ucp/stream/stream_recv.c
src/ucp/stream/stream_send.c
src/ucp/tag/tag_recv.c
src/ucp/tag/tag_send.c
test/gtest/ucp/test_ucp_am.cc

Fixes memory detection for ucp iov datatypes for proto v2
Fixes [bug](https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=4065349&cmtNo=) (Nvidia internal link)

UCP: Fix memory detection for iov dts

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

UCT/IB/MLX5: Improve ODP support output

---

src/ucs/async/async.c
src/ucs/async/thread.c

- Show unreleased resources with UCX_LOG_LEVEL=diag
- Fix function name

UCS/ASYNC: Improve debug log of unreleased resources

---

src/tools/profile/Makefile.am
src/tools/profile/read_profile.c
src/ucs/config/parser.c
src/ucs/config/parser.h
src/ucs/profile/profile.c
src/ucs/profile/profile_defs.h
test/gtest/ucs/test_profile.cc

In the profiling output file: printing the full command line and adding env variables
That way we can know exactly what was executed when analyzing the .prof file.

UCS/PROFILE: added ucx env to profiling output

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.inl

Catch error of trying to register an unsupported memory type

UCP/MM: Add mem type assertion and logging

---

test/gtest/ucp/test_ucp_mmap.cc
test/gtest/ucp/test_ucp_tag_mem_type.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

UCP/GTEST: Reduce gtest execution time

---

test/apps/iodemo/ucx_wrapper.cc
test/apps/iodemo/ucx_wrapper.h

Do not use deprecated APIs in io_demo.

TEST/IODEMO: do not use deprecated APIs

---

src/ucp/core/ucp_context.c

Fix RNDV scheme documentation.

UCP/CONFIG: Add missing RNDV schemes to listed options

---

buildlib/tools/zombie_killer.sh

Fix cmd to find the parent process ID (PPID) for zombie processes.
Also improved zombie search. 
Wrong PPID was the reason that the script couldn't kill some zombies.

INFRA: Fix PPID cmd

---

src/ucs/config/parser.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/ib/test_ib_xfer.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Backport #9143 
Fix minor conflict in ib_md.c

UCT/IB/MLX5: Fix invalid access error to strict-order key with offset - v1.15.x

---

buildlib/az-helpers.sh
buildlib/jucx/jucx-test.yml
buildlib/pr/cuda/cuda.yml
buildlib/pr/cuda/test_malloc_hook.sh
buildlib/pr/go/go-test.yml
buildlib/pr/tests.yml

Make sure the GPU is detected for all GPU-based tests.
Reduce troubleshooting efforts.

AZP: Check GPU presence for GPU tests

---

buildlib/pr/io_demo/az-stage-io-demo.yaml

Temporary disable job failures on io_demo counter.

AZP: Do not fail on io_demo counter

---

README.md

README: fix xpmem URL

---

src/ucs/debug/log.c

Make the global log filter key hash store allocated filenames.
At lookup time, comparing against a previously stored `__FILE__` leads to `SEGFAULT` if the corresponding library has already been `dlclose()`'d.
Use variable size chunk allocation.
Gtest are missing, if approach is ok, we can move this to `ucs/datastruct`, and add corresponding tests.
configure: `--enable-logging=trace_poll`
run: `mpirun -x UCX_LOG_LEVEL=trace -x UCX_PROTO_ENABLE=y -mca pml ucx -np 2 osu_bw -x 400 -m 4096:4096`
```
[jazz29:39743] *** Process received signal ***
[jazz29:39743] Signal: Segmentation fault (11)
[jazz29:39743] Signal code:  (-6)
[jazz29:39743] Failing at address: 0x182cd00009b3f
[jazz29:39743] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x7f13f847e5d0]
[jazz29:39743] [ 1] …
```

UCS/LOG: Store an allocated filename in log filter key hash

---

test/gtest/common/test_perf.cc

Make sure to yield the CPU when running on Valgrind.
Valgrind's memcheck's VM uses actual threads, but serializes them anyways with one global code lock. With the added yield, the producer gets the opportunity to run more often.
For instance the time to run `ud_verbs/test_uct_perf.envelope/2` is:
- without the fix: between 32 seconds and 55 sec
- with the fix, the runtime is a constant 18sec.
There are many tests using this generic infra.
Build with `--with-valgrind`, but also need to detect if actually running inside valgrind otherwise some tests might become too slow (`ud/test_ucp_perf.envelope/37`).
```
valgrind --tool=memcheck --leak-check=full --track-origins=yes \
--fair-sched=try --num-callers=25 --error-exitcode=1 --child-silent-after-fork=yes \
./test/gtest/gtest …
```

GTEST: Use RTE to yield CPU when configured with valgrind

---

src/ucs/configure.m4

Cherry-pick #9183 to enable UCX 1.15.x build with binutils 2.40.

UCS/BUILD: Add binutils 2.40 library dependency - v1.15.x

---

src/ucs/configure.m4

The binutils 2.40 newly depends on `libsframe`, adding corresponding m4 macros.
Tested `--with-bfd` 2.37, 2.40, and without bfd option.

UCS/BUILD: Add binutils 2.40 library dependency

---

src/tools/perf/api/libperf.h
src/tools/perf/lib/libperf_memory.c
src/tools/perf/perftest.c
src/tools/perf/perftest_params.c

```s/UCX_PERF_TEST_MAX_FC_WINDOW/UCT_PERF_TEST_MAX_FC_WINDOW```

TOOLS/PERF: perftest misc fix

---

src/ucp/wireup/select.c
src/ucp/wireup/wireup.c

UCP: Fix ep config locality assignment - v1.15

---

src/ucp/tag/eager_snd.c

UCP/EAGER: Remove redundant declaration

---

test/gtest/ucp/test_ucp_am.cc

Skipped `test_ucp_am_nbx_dts.zcopy_send` tests if AM zcopy is not supported. Otherwise, the test does the same as `test_ucp_am_nbx_dts, short_bcopy_send` does. Because AM bcopy is used in this case.

GTEST/UCP: Skipped AM datatype duplicate tests.

---

src/ucp/core/ucp_ep.c

Improve ep config info, so that every unique lane config field is printed (seg size is currently missing)
Better debugging experience when ep reconfig error happens

UCP: Improve ep config info

---

AUTHORS

AUTHORS: Updated the list of authors for 1.15.0-rc2.

---

NEWS

Copied 1.14.1 news from 1.14.x branch.

NEWS: Copied 1.14.1 news from 1.14.x branch.

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Get more detailed information about Cuda function calls and their timings
[[Nvidia internal tracker](https://redmine.mellanox.com/issues/3519158)]

UCT/CUDA: Add profiling to Cuda runtime API calls

---

src/uct/rocm/base/rocm_base.c

The kernel has to have certain options enabled in order for dmabuf support to be fully functional. This commit adds a check whether the kernel has the required options.
(cherry picked from commit a4080426a3397ab51f91fcc1c151bc8a3b12059b)

UCT/ROCM: check kernel config for dmabuf support-v1.15

---

buildlib/azure-pipelines-perf.yml

Resolve the error in perf pipeline:
"fatal: reference is not a tree"

AZP/PERF: Pass GitHub PR as param

---

src/ucp/core/ucp_context.c

Fix description of new proto infra config

UCP: Fix new proto config description

---

NEWS

NEWS: Added 1.15.0-rc4 section.

---

AUTHORS

Updated the list of authors.
Cherry-picked from v1.15.x branch.

AUTHORS: Updated the list of authors.

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
src/ucp/dt/datatype_iter.inl

- Log memory handle cleanup
- Add name to memory registration log messages

UCP/MM: More logging of memory registration flows

---

.readthedocs.yaml

Update Readthedocs config with an OS keyword.

AZP: Readthedocs - add OS

---

src/ucp/wireup/select.c

Restrict creation more BW lanes than during first lanes initialization.
To prevent endpoint reconfiguration error in case when some BW lanes were dropped due to low BW during first initialization, but there are available resources with higher BW that still can be chosen instead of dropped lanes during second initialization.
This is the short-term solution. The long-term solution is to support endpoint reconfiguration.

WIREUP: Restrict creation more BW lanes than previously

---

buildlib/pr/io_demo/az-stage-io-demo.yaml

This reverts commit 38fa027354e2baa4390d20714a8f884693e8f7be.

Revert "AZP: Fix io_demo var access - v1.15.x"

---

src/uct/base/uct_iface.h
src/uct/tcp/tcp.h
src/uct/tcp/tcp_ep.c
src/uct/tcp/tcp_iface.c

is_connected implementation for TCP

UCT/TCP: is_connected implementation for TCP

---

cmake/ucx-targets.cmake.in

Fix internal issue [587678](https://redmine.mellanox.com/issues/3587678)

CMAKE: Use relative path for prefix

---

NEWS

NEWS: Added 1.15.0-rc5 section.

---

src/ucp/core/ucp_mm.c

Fixes https://github.com/openucx/ucx/pull/9270

UCP/MM: Use rcache in mem type pack - rebase fix

---

NEWS

NEWS: Updated RC5 date.

---

src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
src/uct/cuda/gdr_copy/gdr_copy_iface.c

UCT/CUDA: is_connected implementation for CUDA

UCT/CUDA: is_connected implementation for CUDA

---

src/ucp/core/ucp_mm.c

Don't register memory when looking up host memory allocator as it can cause issues with cuda.
Caching the md index for host memory involves alloc/mem_reg/mem_dereg. This is performed at send time during proto v2 RTR mtype init. With cuda_copy `cudaHostUnregister()` is called for mem_dereg.
With nccl-test and UCX plugin seems we have deadlock situation:
- thread 1: pending for completion for cuda job: `testStreamSynchronize() { .. cudaStreamQuery(streams[i]); .. }`, not ready
- thread 2: the sender that progresses the test, but stuck on `cudaHostUnregister()`, as it seems synchronuous unregister cannot progress while cuda job is ongoing.
When forcing thread 1 to finish/timeout, the call to `cudaHostUnregister()` in thread 2 completes properly.
- thread 1 unblocks thread 2 when setting cuda …

UCP/MEMORY: Don't register when looking up RMA capable host memory allocator

---

src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/sm/scopy/cma/cma_md.c

Removed duplicate code related to dummy memory registration.

UCT/BASE: Removed code duplication related to dummy mem reg.

---

src/uct/base/uct_iface.h
src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
src/uct/ib/rc/accel/rc_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_ep.c
src/uct/ib/rc/base/rc_ep.h
src/uct/ib/rc/verbs/rc_verbs.h
src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_ep.c
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/verbs/ud_verbs.c
src/uct/ib/ud/verbs/ud_verbs.h
test/gtest/uct/ib/test_ud_ds.cc
test/gtest/uct/test_uct_ep.cc

UCT/IB: is_connected implementation for IB

UCT/IB: is_connected implementation for IB

---

src/ucs/Makefile.am
src/ucs/datastruct/lru.c
src/ucs/datastruct/lru.h
src/ucs/datastruct/usage_tracker.c
src/ucs/datastruct/usage_tracker.h
test/gtest/Makefile.am
test/gtest/ucs/test_lru.cc
test/gtest/ucs/test_usage_tracker.cc

Added Usage Tracker class
Support tracking most active EPs.

UCS/DATASTRUCT: Intoducing Usage Tracker

---

src/uct/rocm/copy/rocm_copy_md.c

with v2 protocols there seems to be a scenario where we try to register hipHostMalloc'd memory and fail.  This fix here ensure that we skip the hsa_amd_memory_lock() operation during memory registration for all memory types that return HSA_EXT_POINTER_TYPE_HSA (which includes device and hipHostMalloc'd memory).
With this fix we are down to one single test that does not pass with v2 protocols :-) (which passes with v1).

UCT/ROCM: don't try to lock hipHostMalloc'd memory

---

src/uct/rocm/copy/rocm_copy_iface.c
src/uct/sm/mm/base/mm_ep.c
src/uct/sm/mm/base/mm_ep.h
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/scopy/cma/cma_ep.c
src/uct/sm/scopy/cma/cma_ep.h
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c

UCT/SM: is_connected implementation for SM

UCT/SM: is_connected implementation for SM

---

NEWS

NEWS: Add 1.15.0-rc6

---

src/ucp/core/ucp_worker.c
src/ucs/datastruct/array.c
src/ucs/datastruct/array.h
src/ucs/datastruct/array.inl

Fixes a race for ep configs array.
Main thread may access some of ep configs, while async thread adding new element to ep config array. Since UCS array use realloc to extend the array, main thread may try to acces invalid memory. 
Use calloc + memcpy + free for extending array (and call free on the main thread for ep configs array)

UCP/UCS: Fix ep configs race

---

src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h

Reverted https://github.com/openucx/ucx/pull/9346
Please find reasons here https://github.com/openucx/ucx/pull/9346#issuecomment-1714347976

Reverted UCT/CUDA/CUDA_COPY: Set device context within mem alloc.

---

NEWS

Copied 1.15.0 section from 1.15.x branch.

NEWS: Copied 1.15.0 section from 1.15.x branch.

---

.gitignore

Fix build output files shown as untracked

GIT: Update .gitignore file

---

docs/.readthedoc.requirements.txt

Add missing requirement for readthedocs build.

READTHEDOCS: add recommonmark lib

---

buildlib/azure-pipelines-perf.yml
buildlib/tools/perf-common.yml
buildlib/tools/perf_results.py

Extend UCX perf pipeline to include also GPU, intra-node, and osu_mbw_mr tests.
[Successful test run](https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=70200&view=logs&j=94be751c-9e4c-5c28-d13e-4c720246b05d&t=91332361-356c-5009-c13f-158bec505cbf&l=70)

AZP: Extend perf testing

---

bindings/go/Makefile.am
bindings/go/src/cuda/cuda.go
bindings/go/src/cuda/nocuda.go
bindings/go/src/examples/perftest/perftest.go
bindings/go/tests/memory_test.go
bindings/go/tests/utils.go
buildlib/pr/go/go-test.yml

Set CUDA device before allocating CUDA memory using UCX.

BINDINGS/GO: Set CUDA device before allocating CUDA memory.

---

docs/.readthedoc.requirements.txt

Cherry-pick from https://github.com/openucx/ucx/pull/9403

READTHEDOCS: add recommonmark lib - v1.15.x

---

.gitignore

Add new entries to .gitignore to suppress the creation of the files which are automatically created during the UCX build:
Duplicate of #9444

GIT/GITIGNORE: Add .noinst directories and test_no_cuda_ctx

---

src/ucs/Makefile.am
src/ucs/memory/numa.c
src/ucs/memory/numa.h
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h

Fix issue [3656632](https://redmine.mellanox.com/issues/3656632) (internal link)

UCS/TOPO: Revert "Calculate distance for common NUMA node separately" - v1.16.x

---

buildlib/pr/main.yml
buildlib/pr/wire_compat.yml

Test wire compatibility with newly created 1.16.x branch

AZP: Add wire-compat tests with v1.16.x

---

bindings/java/pom.xml.in
bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java

Set CUDA device before allocating CUDA memory using UCX.

BINDINGS/JAVA: Set CUDA device before allocating CUDA memory.

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/proto/proto_common.inl
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_rtr.c
src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/ugni/base/ugni_md.c
test/gtest/ucp/test_ucp_mem_type.cc
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/uct/test_md.cc

UCT/CUDA-IPC: Handle memh with multiple registrations - v1.16.x

---

src/uct/cuda/base/cuda_iface.c

Added condition to call `cuCtxGetDevice` only if there is a CUDA context bound to the calling CPU thread. Otherwise, `cuDeviceGet(ordinal = 0)` is used in query method.
Previously `cuCtxGetDevice` could return `CUDA_ERROR_INVALID_CONTEXT` error. The error was not traced, but could be caught by `compute-sanitaizer`.

UCT/CUDA/BASE: Get device for current context only if context is active.

---

bindings/java/src/main/native/Makefile.am
buildlib/jucx/jucx-publish.yml

Cherry-pick from https://github.com/openucx/ucx/pull/9538

AZP: Fix JUCX with ARM build-v1.16.x

---

src/ucp/proto/proto_init.c

Backport of https://github.com/openucx/ucx/pull/9499

UCP/PROTO: Do not change multi-fragment perf for 1 fragment range - v1.16

---

src/ucs/datastruct/bitmap.h
src/ucs/datastruct/dynamic_bitmap.h
test/gtest/ucs/test_bitmap.cc

Implementation of a bitmap that can grow as needed

UCS/BITMAP/TEST: Implement dynamic bitmap data structure

---

src/uct/ib/ud/base/ud_ep.c

backport of https://github.com/openucx/ucx/pull/9602

UCT/IB/UD: Remove erroneous assertion - v1.16.x

---

.clang-format
src/ucs/Makefile.am
src/ucs/datastruct/bitmap.c
src/ucs/datastruct/bitmap.h
src/ucs/datastruct/dynamic_bitmap.h
test/gtest/ucs/test_bitmap.cc

Extend the implementation of dynamic bitmap to support bit iteration

UCS/BITMAP/TEST: Implement find-first, find-next and foreach

---

src/uct/rocm/base/rocm_base.c
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_iface.c

Backport of https://github.com/openucx/ucx/pull/9596

UCT/ROCM: set parameters dependent on GPU type - v1.16.x

---

src/ucs/Makefile.am
src/ucs/datastruct/linear_func.h
src/ucs/datastruct/piecewise_func.c
src/ucs/datastruct/piecewise_func.h
test/gtest/ucs/test_datatype.cc

Introduce new piecewise linear function data structure.
That structure should be useful for performance estimations.

UCS/DATASTRUCT: Add piecewise function data structure

---

buildlib/pr/main.yml

Enable Address Sanitizer testing on ucx-new partition

CI: Enable Address Sanitizer testing on ucx_new

---

test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/ucm/rocm_hooks.cc

Backport https://github.com/openucx/ucx/pull/9613

GTEST/COMMON: check support for hipMallocPitch - v1.16.x

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.inl
src/ucp/rma/amo_sw.c
src/ucp/rma/flush.c
src/ucp/wireup/address.c
src/ucp/wireup/address.h
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_ep.c
src/ucs/datastruct/bitmap.h
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/rdmacm/rdmacm_cm.h
test/gtest/ucp/test_ucp_wireup.cc
test/gtest/ucp/test_ucp_worker.cc

Switch from previous to new static bitmap implementation, to allow code cleanup

UCP/CUDA: Use static_bitmap structure

---

buildlib/azure-pipelines-perf.yml

Get PerfX codebase by tag instead of the latest master.
Improve stability by shielding possible breaking changes in PerfX.
Current change management procedure:
1.	UCX uses PerfX with a tag v1.0.0.
2.	A change is needed in PerfX.
3.	Someone creates a branch in PerfX and develops it, PR is created.
4.	UCX branch is created to use new Perf. If a change is complex, we verify it and cont. development of PerfX as needed.
5.	Merge PerfX and create a new tag v1.0.1.
6.	Update UCX branch to use v1.0.1.

AZP/PERF: Get PerfX codebase by tag

---

buildlib/az-helpers.sh
buildlib/jucx/jucx-test.yml
buildlib/pr/go/go-test.yml
buildlib/tools/common.sh
contrib/test_jenkins.sh
test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/ucp/test_ucp_mem_type.cc
test/gtest/uct/test_md.cc

Backport the following PRs:
#9565
#9640
#9609
#9658

Backport Cuda device not present test fixes - v1.16.x

---

src/ucp/core/ucp_context.c
src/uct/ib/base/ib_iface.c

UCP/UCT/IB: Don't allocate huge pages by default - v1.16.x

---

src/ucp/core/ucp_mm.c

add device name to trace on memh import attach
for debugging

UCP/MM: add device name to trace on memh import attach

---

AUTHORS

Update AUTHORS file.
Progress release.

RELEASE: Update AUTHORS file

---

src/uct/ib/Makefile.am
src/uct/ib/base/ib_md.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/gga_mlx5.c

initial commit for gga_mlx5 transport
new HW capabilities support

UCT/GGA: initial commit for gga_mlx5 transport

---

NEWS

NEWS: Added 1.16.0-rc3 section.

---

examples/ucp_client_server.c

Make sure `ucp_client_server` always completes with `-c am` option.
AM callback can be invoked multiple times inside a given iteration.
Related: #9694 
Use overall count tracking instead of edge tracking.
- rock, rndv thresh
- loopback
```
./examples/ucp_client_server -c am -i 10000 -s 10000
./examples/ucp_client_server -c am -i 10000 -s 10000 -a X.X.X.X
```

EXAMPLES: Fix ucp_client_server AM completion handling

---

NEWS

List latest backported bugfixes.
Depends on:
- v1.16.x #9702 
- v1.16x #9705

 NEWS: Add 1.16.0-rc4 Bugfixes section

---

src/ucp/rma/rma_send.c

Check datatype field independently from no immediate completion flag.
Reported by #9626.

UCP/PROTOV2: Don't depend on NO_IMM_CMPL for DATATYPE checks

---

buildlib/pr/main.yml
buildlib/pr/tests.yml
contrib/test_jenkins.sh
test/gtest/ucs/test_config.cc

Avoid test failures due to issue [3815783](https://redmine.mellanox.com/issues/3815783)

TEST/PR: Don't run tests on BlueField

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_rtr.c
src/ucp/stream/stream_multi.c
src/ucp/tag/eager_multi.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload/eager.c
src/ucp/tag/offload/rndv.c

Added UCX_PROTO_OVERHEAD configuration variable.

UCP/CORE: Added configuration variable to set protocol overheads.

---

buildlib/pr/main.yml

Enable ASAN testing for `ucx_roce` setup.

CI: Enable ASAN roce testing

---

src/ucp/wireup/select.c

Backport of https://github.com/openucx/ucx/pull/9424

UCP/WIREUP: Consider local distance during slow lanes dropping - v1.16.x

---

debian/rules.in

Disabled Go bindings in Debian package.

DEBIAN: Disabled Go bindings.

---

src/ucp/core/ucp_mm.c

Fixes internal issue [3849089](https://redmine.mellanox.com/issues/3849089), introduced by #9771
Fixes Java test failures

UCP/MM: Invalidate memh with mismatching uct_flags, instead of dereg

---

NEWS

RELEASE: Update NEWS RC5

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

In ksm registration: setting iova to `(uint64_t)memh->address` in case of memic.
In perftest: check allocators are not NULL before initializing them
MEMIC-relate bugfixes - 
1. Fix in ksm registration is necessary for rdma memory to work
2. Fix in perftest avoids a segfault when using multiple threads with RDMA memory

UCT/IB/MLX5/DV: fixed memic iova in ksm registration

---

buildlib/az-helpers.sh

Update the gdrcopy module version.
Make it consistent with the latest driver

AZP: Update the gdrcopy module version

---

Makefile.am
config/Makefile.am
config/ucx.conf
configure.ac
ucx.spec.in

Added configuration file with section for Grace Hopper, setting `REG_NONBLOCK_MEM_TYPES=host,cuda-managed`.

CONFIG: Added configuration file with section for Grace Hopper.

---

src/uct/ib/Makefile.am
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/gga_mlx5.c

MD API implementation of GGA transport
continue https://github.com/openucx/ucx/pull/9678

UCT/GGA: md api implementation

---

test/gtest/uct/test_mm.cc
test/gtest/uct/uct_test.h
test/gtest/uct/v2/test_uct_query.cc

Added tests for IB_SEND_OVERHEAD, MM_SEND|RECV_OVERHEAD.
To address https://github.com/openucx/ucx/pull/9707#discussion_r1530713733

GTEST/UCT: Added tests for IB_SEND_OVERHEAD, MM_SEND|RECV_OVERHEAD.

---

config/ucx.conf

Disabled creation objects by DEVX on Grace Hopper.

CONFIG: Disabled devx objects for GH.

---

src/ucp/wireup/select.c

Fix RMA lane score computation when an eligible AM lane was skipped.
The list of lanes must be ordered by score. Without the fix, when `mlx5_0:1` has a better score than `mlx5_2:1`, for put single proto, we erroneously select the later interface.
Broken:
```
lane[0]:  0:dc_mlx5/mlx5_0:1.0 md[0]      -> addr[0].md[0]/ib/sysdev[1] seg 4294967295 amo#0 am am_bw#0
lane[1]:  2:dc_mlx5/mlx5_2:1.0 md[1]      -> addr[2].md[1]/ib/sysdev[3] seg 4294967295 rma_bw#0
lane[2]:  0:dc_mlx5/mlx5_0:1.1 md[0]      -> addr[0].md[0]/ib/sysdev[1] seg 4294967295 rma_bw#1
lane[3]:  2:dc_mlx5/mlx5_2:1.1 md[1]      -> addr[2].md[1]/ib/sysdev[3] seg 4294967295 rma_bw#2
lane[4]:  0:dc_mlx5/mlx5_0:1.2 md[0]      -> addr[0].md[0]/ib/sysdev[1] seg 4294967295 rma_bw#3
```
After fix:
```
lane[0]:  0:dc_mlx5/mlx5_0:1.0 …
```

UCP/WIREUP: Remove skipped paths from RMA lane score

---

NEWS

Preparation for making 1.17.0 releases

NEWS: Add 1.16.0 and 1.17.0-rc1 sections - v1.17.x

---

configure.ac
ucx.spec.in

CONFIG/SPEC: Bump version to 1.18.0

---

configure.ac
src/ucp/api/ucp.h

- fixed few typos in comments
- more accurate wording

COMMENT: fixed typos

---

NEWS

Update News 1.16
Release process

RELEASE: Update News 1.16

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c

UCT/DC: Revert making peers with different max_rd_atomic unreachable - v1.17.x

---

src/ucs/sys/stubs.c
src/ucs/sys/stubs.h
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/gga_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c

init/cleanup stub GGA iface
continue https://github.com/openucx/ucx/pull/9703

UCT/GGA: init/cleanup stub iface

---

config/ucx.conf

Changed filter of Grace section from Product name to CPU model.
Cherry-picked https://github.com/openucx/ucx/pull/9844.

CONFIG: Grace section filtered by CPU model.

---

NEWS

Fixed date for 1.17 News
Release version

RELEASE: Fixed date for 1.17 News

---

AUTHORS

Updated AUTHORS list for v1.17
1.17 Release

RELEASE: Updated AUTHORS list for v1.17

---

buildlib/pr/main.yml
buildlib/pr/wire_compat.yml

Test wire-compatibility with 1.17 branch

AZP: Add wire-compat testing with v1.17.x

---

buildlib/pr/main.yml

Failures should be fixed after FW upgrade

AZP: Re-enable running tests on BlueField

---

NEWS

Updated NEWS file for 1.17
v1.17 Release

Updated NEWS file for 1.17

---

buildlib/tools/builds.sh
config/m4/compiler.m4
src/ucs/sys/sys.c
test/gtest/ucs/test_datatype.cc

Build UCX with Intel ICC/ICX compilers.
Basic Intel compiler support.
Relax needed options, for Intel compiler only.
Build tested only with `configure-devel` and `configure-release`.
```
icc -V
Intel(R) C Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.4.196 Build 20170411
icx -V
Intel(R) C Compiler for applications running on Intel(R) 64, Version 2021.1 NextGen Beta Build 20200304
```
```
./autogen.sh; CXX=icpc CC=icc ./contrib/configure-devel
./autogen.sh; CXX=icpx CC=icx ./contrib/configure-devel
```

BUILD/CONFIG: Build with Intel Compiler

---

src/ucm/util/sys.c

On some systems UCX can fail while parsing `/proc/self/maps` information, resulting in the crash with the following trace:
"sys.c:194  UCX  FATAL failed to allocate maps buffer(size=32768)"
Using mmap instead of remap resolves the issue.

UCM: Use mmap instead of mremap while parsing /proc/self/maps

---

buildlib/pr/main.yml
contrib/lsan.supp
contrib/test_jenkins.sh

Add CI jobs that executes tests on BlueField with enabled ASAN.

CI: Add BlueField ASAN check job

---

NEWS

Updated NEWS for RC2
Release V1.17

RELEASE: Updated NEWS RC2

---

src/ucp/core/ucp_worker.c
src/uct/ib/base/ib_iface.h
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
test/gtest/ucp/test_ucp_worker.cc

Fix JUCX test failures found in #9904

UCT/IB: Consider number of supported completion vectors

---

NEWS

Update NEWS 1.17 RC2
Release process.

RELEASE: Update NEWS 1.17 RC2

---

src/ucp/proto/proto_perf.c
src/ucp/proto/proto_perf.h
src/ucs/datastruct/list.h
test/gtest/ucp/test_ucp_proto.cc

Support combining multiple protocol parts

UCP/PROTO/PERF: Add function to aggregate multiple performances

---

NEWS

Updated NEWS 1.17 RC3
Release process

RELEASE: Updated NEWS 1.17 RC3

---

.gitignore

Ignore `ucp_hello_world_static` binary.

GIT/GITIGNORE: Add test/apps/uct_info/ucp_hello_world_static to ignore

---

src/ucp/rma/amo_sw.c

Cleanup code as per issue #9945.

UCP/AMO/SW: Remove unnecessary status check

---

AUTHORS

Updated AUTHORS list 1.17
Release process 1.17

RELEASE: Updated AUTHORS list 1.17

---

src/ucs/time/time.h

Backport #9968 to v1.17.x to address issue #9969.

UCS/TIME: Add math.h to provide INFINITY - v1.17.x

---

src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.h

Add gdr_copy singleton rcache for regions of 64k GPU page-aligned regions and remove alignment restriction from UCP rcache.
Fix [internal issue 3819771](https://redmine.mellanox.com/issues/3819771)

UCT/CUDA/GDR_COPY: Singleton MD instance

---

src/uct/ib/rc/accel/rc_mlx5_ep.c

fix zcopy_post flags in MLX5 TL

UCT/IB/MLX5: fix zcopy_post flags

---

buildlib/pr/main.yml
buildlib/pr/wire_compat.yml
buildlib/tools/check_tls_perf_caps.sh
buildlib/tools/test_wire_compat.sh

backport of #9962 and #10000
avoid failures on rain machine due to recent HW updates

AZP: Wire compat fixes -  v1.17.x

---

test/gtest/ucp/test_ucp_am.cc

- Increase test coverage
- Force rendezvous protocol by flag rather than by threshold, which is the preferred way

TEST/RNDV: Run memtype rndv tests on 1-byte message

---

src/ucp/core/ucp_request.h
src/ucp/dt/datatype_iter.inl
src/ucp/rndv/rndv_put.c

Fix internal issue [4003121](https://redmine.mellanox.com/issues/4003121) and [3998165](https://redmine.mellanox.com/issues/3998165)

UCP/RNDV: Fix sending too many ATPs for small messages

---

buildlib/tools/test_mad.sh

Select the first active InfiniBand interface for MAD tests; exit with error if none found.
We encountered a situation where an Ethernet interface was used with MAD tests, causing failures.

AZP/TEST: Select active IB HCA or else

---

test/gtest/ucp/test_ucp_worker.cc

GTEST: Fix tcp_device name detection in pci_bw test - v1.17.x

---

src/uct/cuda/gdr_copy/gdr_copy_md.c

Require rcache to be used by gdr copy md by default
Otherwise there maybe an issue where small memory region to be registered is aligned to 64K and IB registration fails with the following errors
```
ib_md.c:276  UCX  ERROR ibv_reg_dmabuf_mr(address=0x7f271a600000, length=65536, access=0xf) failed: Invalid argument
ucp_mm.c:70   UCX  ERROR failed to register address 0x7f271a600000 (cuda) length 65536 dmabuf_fd 98 on md[2]=mlx5_0: Input/output error (md supports: host|cuda)
```
Keep `UCX_GDR_COPY_RCACHE` env var, but make it bool instead of ternary. So it is always enabled by default, but there is still a possibility to debug/use gdrcopy transport without rcache

UCT/GDRCOPY: Require rcache by default

---

src/ucp/wireup/select.c

Replaces comma typo by semicolon

UCP/WIREUP: Replace comma typo by semicolon

---

test/gtest/Makefile.am
test/gtest/common/cuda_context.cc
test/gtest/common/cuda_context.h
test/gtest/ucm/cuda_hooks.cc
test/gtest/uct/cuda/test_cuda_ipc_md.cc

GTEST: Minor code refactoring related to CUDA context usage.

---

.codespellrc
bindings/go/src/ucx/worker.go
bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java
buildlib/pr/codestyle.yml
src/ucp/api/ucp.h
src/ucp/proto/proto_perf.h
src/ucp/wireup/wireup.c
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/ib/ud/base/ud_iface.h
src/uct/tcp/tcp_cm.c
src/uct/tcp/tcp_ep.c

Add spell check to CI
To reduce number of spelling issues.

CI: Add codespell check job

---

src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.h

Backport https://github.com/openucx/ucx/pull/9943, https://github.com/openucx/ucx/pull/10048, https://github.com/openucx/ucx/pull/10052

UCT/CUDA/GDR_COPY: Singleton MD instance - v1.17.x

---

buildlib/tools/check_tls_perf_caps.sh

Fix CI failures in wire compat jobs

TEST/COMPAT: Fix wire compat test failures

---

src/ucp/core/ucp_mm.c
test/gtest/uct/test_md.cc

Backport of https://github.com/openucx/ucx/pull/10119

Fix CI failures – v1.17.x

---

src/uct/ib/base/ib_md.c

Currently GPUdirect support detected by checking `/sys/kernel/mm/memory_peers/nv_mem/version`. This patch adds two new files that can be used to detect GPUdirect support: `/sys/module/nvidia_peermem/version` for driver version >= 470 and `/sys/module/nv_peer_mem/version` for driver version < 470.
The upstream linux kernel has dropped the `/sys/kernel/mm` paths since kernel 5.6. So we need to implement new ways to detect peermem support.

UCT/IB/MD: Add new ways to detect GPUdirect support

---

buildlib/pr/wire_compat.yml
buildlib/tools/test_wire_compat.sh

AZP: Use different ports in one wire-compat job - v1.17.x

---

test/gtest/common/test.h
test/gtest/configure.m4
test/gtest/ucp/ucp_test.h
test/gtest/ucs/test_callbackq.cc
test/gtest/uct/uct_test.h

Fix CI failures in test_callbackq
Backport #10024

TEST/CALLBACKQ: Fix test_callbackq.test_callbackq test failures - v1.17.x

---

docs/source/faq.md
src/uct/ib/mlx5/ib_mlx5.c

Document after merging #10013.

DOC/FAQ: Add section for adaptive routing on RoCE

---

src/ucs/debug/memtrack.c

fix allocation on memtrack dump
memtrack.c:139  Assertion `(sizeof(*all_entries) * ((&ucs_memtrack_context.entries)->size)) <= UCS_ALLOCA_MAX_SIZE' failed: alloca(1208)
use malloc/free instead of `ucs_alloca`

UCS/MEMTRACK: fix allocation on memtrack dump

---

bindings/go/src/ucx/endpoint.go
bindings/go/src/ucx/request.go
bindings/go/src/ucx/worker.go

Add common function to prepare `C.ucp_request_param_t`

BINDINGS/GO: Add multi-send flag and user memh support request params

---

src/uct/rocm/copy/rocm_copy_md.c

fix for the test_md_fork test of gtest.
backport of PR #9919

UCT/ROCM: fix test_md_fork - v1.17

---

src/uct/cuda/gdr_copy/gdr_copy_md.c

Ensure that the loaded `libgdrapi.so` is binary compatible with the version of UCX it was built against.
Issue: [4088373](https://redmine.mellanox.com/issues/4088373)
We see late error/crash, instead of gracefully disabling GDR transport:
```
symbol lookup error: /opt/nvidia/hpc_sdk/Linux_x86_64/24.9/comm_libs/12.6/hpcx/hpcx-
2.20/ucx/lib/ucx/libuct_cuda_gdrcopy.so.0: undefined symbol: gdr_get_info_v2
```
Detect version currently in use.

UCT/GDRCOPY: Detect runtime version match (API changed >=v2.4)

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Set `byte_count` field for KLM entries.
This fixes [RM4025026](https://redmine.mellanox.com/issues/4025026) issue which is caused by interoperability between ODP and KSM features.

UCT/IB/DEVX: Fix FETCH_ADD remote access error for ODP + KSM case

---

contrib/ucx_perftest_config/test_types_uct
src/tools/perf/perftest.c
test/gtest/uct/test_uct_perf.cc

increase window size for put_bw and get tests
to reach FWS with GGA transport (https://github.com/openucx/ucx/pull/9993)

PERF/UCT: increase window size for put_bw and get tests

---

src/ucp/wireup/address.c

Help user by being explicit with the configuration that might be needed.
Simple assert might not be descriptive enough.
Return unsupported error code and add descriptive log.

UCP/WIREUP: Explicitly prompt for address v2 configuration if needed

---

src/ucs/sys/sys.c
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_worker.cc

Don't create worker if we cannot open enough file descriptors.
Prevent test failure.
- Don't cache `RLIMIT_NOFILE` value so that we don't dump misleading error message on socket creation failure
- Function only used in testing
- Try to grow soft limit but don't touch max limit value
- Estimate number of file descriptors and limit the test accordingly

GTEST/UCP: Test workers on CPUs according to max open file count

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h

Backport https://github.com/openucx/ucx/pull/10233 into 1.18.x

UCP: Fixed stack overflow in exported rkey unpack - v1.18.x

---

test/apps/iodemo/README.md

Updates `run_io_demo.sh` `README.md` file.
Tried to run the commands as described in the `README.md`, and fixed what didn't work.
Checked `run_io_demo.sh` to see the current implementation.

TEST/IODEMO: update README.md

---

test/gtest/uct/test_sockaddr.cc

Fixed race condition when waiting for client disconnect event.
Prevent `concurrent_handle_conn_req_and_close_listener` test failure with the following error:
```
{{2024-09-25T05:13:37.8435372Z Value of: m_ep_client_data.empty()}}
{{2024-09-25T05:13:37.8436767Z   Actual: false}}
{{2024-09-25T05:13:37.8438018Z Expected: true}}
```

UCT/TEST: Fixed race condition in test_sockaddr

---

config/ucx.conf

Currently async memory is detected as cuda-managed and it does not seem support ODP

UCT/CUDA: Detect async mem as cuda

---

.github/PULL_REQUEST_TEMPLATE.md

This PR updates the `PULL_REQUEST_TEMPLATE.md` to improve clarity and readability. 
To make the template easier to follow and reduce ambiguity.
Minor grammar corrections have been made, and additional punctuation has been added to clarify instructions.

GITHUB: Update PULL_REQUEST_TEMPLATE.md

---

src/ucp/proto/proto_multi.c

While working on [RM#4134043](https://redmine.mellanox.com/issues/4134043), we discovered that lanes for multi-frag protocols are not sorted by bandwidth. It's desirable to sort them in order to use lanes with higher bandwidth first
As discussed with UCX team, in multi-frag protocols it's desirable to have lanes sorted by bandwidth in order to optimize sending. First we try to send message over lane with highest bandwidth, and therefore potentially avoid splitting a message into several parts.
Sort lanes by BW after picking them and detecting BW

UCP/PROTO/MULTI: Sort lanes by BW

---

src/ucs/arch/x86_64/cpu.c

It introduces a new function ucs_x86_nt_all_buffer_transfer() to handle the case when both source and destination are non-temporal
Other notable changes.
a) increase nt_dest_thresh
b) Smaller transfer sizes are improved for ucs_x86_nt_dst_buffer_transfer() & ucs_x86_nt_src_buffer_transfer()
It is an enhancement

ARCH/X86: make nt_all transfer a seperate function

---

src/ucs/arch/x86_64/cpu.c

It introduces a new function ucs_x86_nt_all_buffer_transfer() to handle the case when both source and destination are non-temporal
Other notable changes.
a) increase nt_dest_thresh
b) Smaller transfer sizes are improved for ucs_x86_nt_dst_buffer_transfer() & ucs_x86_nt_src_buffer_transfer()

ARCH/X86: make nt_all transfer a seperate function - v1.18.x

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h

Increase DCI index to 16 bits
Support large number of DCIs

UCT/DC: Increase DCI index to 16 bits

---

buildlib/tools/coverity.sh

Improves error reporting in buildlib/tools/coverity.sh to make Coverity errors more visible in the Azure DevOps CI pipeline.
Currently, identifying the specific Coverity errors causing CI failures is difficult because they are buried in the log output. This change helps to quickly see the errors without scrolling through the logs.
Modifies the script to capture Coverity errors and output them at the end, making the cause of the failure immediately clear in the CI logs.

CI: improve Coverity error reporting

---

AUTHORS

Update for commit range `upstream/v1.17.x..upstream/v1.18.x`.

AUTHORS: Update list of authors

---

src/ucp/wireup/wireup.c

UCP/WIREUP: Removed obsolete condition.

---

examples/hello_world_util.h
examples/ucp_client_server.c
examples/uct_hello_world.c

Fixed checking for memory type support.
Plus minor fixes.

EXAMPLES: Fixed checking for memory type support.

---

test/gtest/ucp/test_ucp_tag_offload.cc

GTEST: Fix tag offload multi rx test - v1.18.x

---

src/uct/ib/ud/base/ud_iface.c

UCT/UD: Minor variable definition fix

---

test/apps/test_ucx_tls.py

TEST/APPS: Fix test_ucx_tls.py failure - v1.18.x

---

AUTHORS
src/ucs/sys/compiler_def.h
src/uct/ib/base/ib_iface.h
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/rc/rc_mlx5_common.c
src/uct/ib/mlx5/rc/rc_mlx5_common.h
src/uct/ib/mlx5/rc/rc_mlx5_devx.c
src/uct/ib/mlx5/rc/rc_mlx5_iface.c
test/gtest/uct/ib/test_ib.cc

Add DDP support for RC and DC over DevX
Supporting OOO recv wqes out of the box.

UCT/IB/MLX5: Add devx DDP support

---

src/tools/perf/lib/ucp_tests.cc

[[RM#4173667](https://redmine.mellanox.com/issues/4173667)]
There is a discrepancy between client and server final perf result, which is especially visible with pipeline protocols, but it occurs also with many others. On the client side we measure time needed to send all the messages, and with pipeline protocol we essentially measure the time needed to send message to the remote bounce buffer. With default window size of 32 we see an initial performance spike on the client side, but with larger amount of iterations the client and server results are converging to the same value due to implicit synchronisation between send/recv.
Workaround: increase iteration count (-n 1000) or decrease window size (-O 1)
We need to provide reliable performance result on the sender side, that would be …

PERF: Fix final perf report discrepancy between client and server

---

src/ucp/proto/proto_select.c
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
test/gtest/Makefile.am
test/gtest/ucp/test_ucp_proto_mock.cc

Mock infrastructure and reference test for protocol selection
To enable writing tests for protocol selection, that are executed on different HW

GTEST: Mock protocol selection tests

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

UCT/CUDA-IPC: Always set cuda-ipc device as SHM - v1.18.x

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
src/ucp/dt/datatype_iter.inl
src/ucp/dt/dt.c

Optimize mem type registration to alleviate performance degradation introduced in https://github.com/openucx/ucx/pull/10053
Replace static user memh with lightweight pack context.

UCP/MM: Optimize mem type fast-path

---

src/ucp/rndv/rndv_put.c

Added check for fragment memory type to rndv/put/mtype protocol.
Cherry-picked https://github.com/openucx/ucx/pull/10371.
Fix for the following type of error:
```
ib_md.c:287  UCX  ERROR ibv_reg_mr(address=0x4002a0000000, length=536870912, access=0xf) failed: Bad address
ucp_mm.c:76   UCX  ERROR failed to register address 0x4002a0000000 (cuda-managed) length 536870912 on md[6]=mlx5_2: Input/output error (md supports: host|cuda-managed)
mpool.c:269  UCX  ERROR Failed to allocate memory pool (name=ucp_rndv_frags) chunk: Input/output error
```

UCP/RNDV: Added check for fragment type to rndv/put/mtype - v1.18.x

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Backport of https://github.com/openucx/ucx/pull/10258

UCT/CUDA_IPC: increase MAX_PEERS and MAX_STREAMS - v1.18.x

---

config/m4/cuda.m4
src/ucp/wireup/wireup.c
src/uct/api/uct.h
src/uct/api/v2/uct_v2.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h

Backport of Mikhail's PR https://github.com/openucx/ucx/pull/10198

UCT/CUDA_IPC: Use fabric info for cuda-ipc reachability check - v1.18.x

---

test/gtest/uct/cuda/test_cuda_ipc_md.cc

Upstream v1.18.x #10381 test in master, actual fix is already in master as #10281.

UCT/CUDA_IPC: Return rkey unreachable with missing device context

---

test/gtest/uct/test_sockaddr.cc

fixed race condition in uct_sock test
fix test

UCT/TEST: fixed race condition in uct_sock test - v1.18

---

src/tools/info/tl_info.c

Improve log message on failure, remotely related to #10372.

TOOLS/INFO: Improve log message on md open error

---

test/gtest/ucp/test_ucp_ep_reconfig.cc

Adding parallelism to the send-recv operation
In order to cover more usecases and test more complicated scenarios

UCP/TEST: Enhance EP reconfiguration tests

---

src/uct/ib/mlx5/gga/gga_mlx5.c

lock IB mem attach call
https://github.com/openucx/ucx/pull/10205#issuecomment-2574785282

UCT/GGA: lock IB mem attach call

---

src/uct/ib/mlx5/rc/rc_mlx5_iface.c

Skip cyclic_emulated when ddp is enabled
Cyclic emulated + DDP results in timeout / hangs in large scale

UCT/IB/MLX5/RC: skip cyclic_emulated when using ddp

---

src/uct/ib/mlx5/gga/gga_mlx5.c

return info string from iface_is_reachable_v2
https://github.com/openucx/ucx/pull/10403#discussion_r1905294105

UCT/GGA: return info string from iface_is_reachable_v2

---

config/m4/cuda.m4
src/uct/cuda/cuda_copy/cuda_copy_md.c

UCT/CUDA: Runtime CUDA >= 12.3 to enable VMM - v1.18.x

---

NEWS

Prepare NEWS file for v1.18.0.

NEWS: Update to 1.18.0 for release

---

buildlib/pr/main.yml
config/m4/cuda.m4
src/ucs/arch/bitops.h

Fix compilation with new gcc and enable CI testing

UCS/BITOPS/BUILD: Fix compilation on centos10 and fedora41

---

NEWS

Add NEWS file content from v1.18.0 for next release (#10428).

NEWS: Add v1.18.0 description to main branch

---

src/ucs/datastruct/dynamic_bitmap.h
test/gtest/ucp/test_ucp_perf.cc

Fix newly found spellchecks across various PRs.

CI: Fix newly found spellchecks

---

AUTHORS

Update AUTHORS file from v1.18.0.

AUTHORS: Update the list of authors from v1.18.0

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Detect BW and update iface bandwidth.

UCT/CUDA_IPC: Detect BW systems

---

test/gtest/ucp/test_ucp_proto_mock.cc

When the first MD does not have devices (for example port down) the mock would fail to open device

TEST/UCP/MOCK: Fix mock to handle memory domain without devices

---

src/tools/perf/cuda/cuda_alloc.c
src/tools/perf/lib/libperf.c

Better error message when Cuda memory cannot be allocated

TOOLS/PERF/CUDA: Improve error messages for Cuda use cases

---

src/uct/sm/mm/base/mm_ep.c

Fix for https://github.com/openucx/ucx/issues/10477

UCT/MM: Fix FIFO availability check

---

NEWS

Prepare NEWS file for v1.18.1-rc1

NEWS: Update to 1.18.1-rc1 release

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

UCT/IB/MLX5: Disable ODP when the device supports DDP

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h

UCT/CUDA_IPC: Use buffer_id to detect VA recycling - v1.18.x

---

NEWS
config/ucx.conf
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h

Backport #10155 cuda_copy bandwidth config keys from the master branch.

UCT/CUDA: Update cuda_copy perf estimates for Grace - v1.18.x

---

test/gtest/ucp/test_ucp_tag_xfer.cc

Fix the [failure](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/99245/logs/1427):
```
2025-03-22T13:08:03.5146610Z [ RUN      ] rc/multi_rail_max.max_lanes/5 <rc/rndv_am_zcopy>
2025-03-22T13:08:04.1500872Z /__w/1/s/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:1248: Failure
2025-03-22T13:08:04.1503043Z Expected equality of these values:
2025-03-22T13:08:04.1504114Z   num_lanes()
2025-03-22T13:08:04.1505016Z     Which is: 64
2025-03-22T13:08:04.1505803Z   ucp_ep_num_lanes(sender().ep())
2025-03-22T13:08:04.1507155Z     Which is: '?' (63, 0x3F)
2025-03-22T13:08:04.5474663Z [  FAILED  ] rc/multi_rail_max.max_lanes/5, where GetParam() = rc/rndv_am_zcopy (1033 ms)
```
With `UCX_PROTO_ENABLE=n` and running on first CPU socket on swx-rain03/04

TEST/TAG: Don't require exact number of lanes with protov1

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c
test/gtest/uct/cuda/test_cuda_ipc_md.cc

This is minimal version of #10569 (plus applying one comment about ctx push)

UCT/CUDA-IPC: Mkey pack with no ctx set

---

src/ucs/datastruct/frag_list.c
src/ucs/datastruct/frag_list.h
src/uct/ib/efa/Makefile.am
src/uct/ib/efa/srd/srd_ep.c
src/uct/ib/efa/srd/srd_ep.h
src/uct/ib/efa/srd/srd_iface.c
src/uct/ib/efa/srd/srd_iface.h
src/uct/ib/efa/srd/srd_log.c
src/uct/ib/efa/srd/srd_log.h
test/gtest/ucs/test_frag_list.cc
test/gtest/uct/ib/test_srd.cc

Add active message with defragmentation, with tests. This depends on #10525 which triggers reordering.

UCT/IB/EFA/SRD: Add reordering on receive path and AM handling

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_mtype.inl
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rtr.c

Allocate staging buffer on the same device where the send/receive buffer is located.

UCP/RNDV: Allocate staging buffer on the device of send/recv buffer.

---

src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
test/gtest/uct/cuda/test_switch_cuda_device.cc

Test scenario when cuda memory is allocated on a certain device, but cuda context from different device is used during the operation.

UCT/GTEST: Test multi_gpu send with cuda tls

---

src/uct/ib/base/ib_log.c
src/uct/ib/base/ib_log.h
src/uct/ib/efa/srd/srd_def.h
src/uct/ib/efa/srd/srd_ep.c
src/uct/ib/efa/srd/srd_ep.h
src/uct/ib/efa/srd/srd_iface.c
src/uct/ib/efa/srd/srd_iface.h
test/gtest/uct/ib/test_srd.cc

Add AM and RMA GET operations, missing PUT, which will be added afterwards.

UCT/EFA/SRD: Add AM and GET operations

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

UCT/CUDA/CUDA_COPY: Fix naming and comments for sync memops setting

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Address minor comments from #10537.

UCT/CUDA_COPY: enable rdma flag for fabric allocations - v1.18.x

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Upstreams #10595 in master from v1.18.x (replaces #10007).

UCT/CUDA_COPY: enable rdma flag for fabric allocations

---

src/ucm/bistro/bistro_x86_64.c

https://redmine.mellanox.com/issues/4370940
https://nvbugspro.nvidia.com/bug/5182364
UCX fails to install bistro hooks for cuda 12.9, which leads sometimes to UCC crash
The issue appears to be that CUDA 12.9 amd64 is using a different stack frame setup sequence that includes an 8-bit immediate SUB instruction which the current relocator doesn't handle.
```
push %rbp           # REX=0  OPCODE=55 
mov  %rsp, %rbp     # REX=48 OPCODE=89 
push %r12           # REX=41 OPCODE=54 
sub $imm8, %rsp     # REX=48 OPCODE=83 (stack alignment) - unknown instruction
```
Added this new instruction to the bistro x86_64 relocator
Tested with submitter image: docker://gitlab-master.nvidia.com/dl/dgx/pytorch:25859036-devel-amd64
Problem does not exist in cuda12.9 on arm64

UCM/CUDA: Fixed cuda12.9 amd64 bistro hook missing instruction

---

src/ucm/bistro/bistro_x86_64.c

Backport of https://github.com/openucx/ucx/pull/10624 to v1.18.x
https://redmine.mellanox.com/issues/4370940
https://nvbugspro.nvidia.com/bug/5182364
UCX fails to install bistro hooks for cuda 12.9, which leads sometimes to UCC crash
The issue appears to be that CUDA 12.9 amd64 is using a different stack frame setup sequence that includes an 8-bit immediate SUB instruction which the current relocator doesn't handle.
```
push %rbp           # REX=0  OPCODE=55 
mov  %rsp, %rbp     # REX=48 OPCODE=89 
push %r12           # REX=41 OPCODE=54 
sub $imm8, %rsp     # REX=48 OPCODE=83 (stack alignment) - unknown instruction
```
Added this new instruction to the bistro x86_64 relocator
Tested with submitter image: docker://gitlab-master.nvidia.com/dl/dgx/pytorch:25859036-devel-amd64
Problem does …

UCM/CUDA: Fixed cuda12.9 amd64 bistro hook missing instruction - v1.18.x

---

src/ucp/wireup/select.c

Fix mismatch in wireup (fails in `ucp_wireup_match_p2p_lanes()`) due to asymmetric sorting in all to all connections.
All to all connections selected different lanes on each side due to inconsistent sorting logic, causing broken lane matching.
Applied symmetric sorting in `ucp_wireup_add_fast_lanes_a2a()` to ensure local[i] matches remote[I].

UCP/WIREUP/SELECT: Fix a2a wireup lane matching

---

src/ucp/proto/proto_common.c
test/gtest/ucp/test_ucp_proto_mock.cc

There is a bug in protocol lane selection: when we select the first lane and it gets filtered out by min/max frag - then we skip the entire protocol without trying next lanes. In particular, I noticed that UCP skips get_zcopy sometimes when cuda_ipc without NVLink is present.
Even if there are multiple candidates for the first lane, we check just the first one.
This leads to undesired protocol selection skip sometimes.
Minimal fix for 1.19 release - just always request at least 4 lanes even if 1 is needed. Proper fix would be to pass filter callback to `ucp_proto_common_find_lanes`
Added unit test

UCP/PROTO: Don't skip protocol if first lane is filtered out by min/max frag

---

src/ucp/rndv/proto_rndv.c

RM: https://redmine.mellanox.com/issues/4403455
There is a big performance degradation caused by commit: https://github.com/openucx/ucx/pull/10603
The root cause is that during RNDV send response we try to detect the sys_dev for pipeline bound buffers. The problem happens when we can't allocate CUDA memory - in this case we repeat this attempt again and again, which provokes the degradation.
Avoid updating alloc_md cache from RNDV response, only query cache from this flow.
alloc_md cache is updated by protocol probe.
With this fix performance is on par with 1.18, and pipeline protocol with cuda staging buffers work (tested with rcx_gpu/test_ucp_proto_mock_gpu.cuda_managed_ppln_host_frag)

UCP/RNDV: Fix degradation by avoiding alloc_md cache update from RNDV send response

---

src/ucp/wireup/select.c

Add UCT_MD_FLAG_REG to rkey_ptr selection criteria
Restore xpmem selection as rkey_ptr lane
Fix internal issue https://redmine.mellanox.com/issues/4359775

UCP/WIREUP: Add UCT_MD_FLAG_REG to rkey_ptr selection criteria

---

test/gtest/uct/test_flush.cc

Fix IB flush remote support detection in flush related tests.

GTEST/UCT/FLUSH: Fix flush support detection

---

configure.ac
ucx.spec.in

Update main branch version to v1.20.0 after creating v1.19.x branch

CONFIG/SPEC: Bump version to 1.20.0

---

contrib/ibmock/efa.c
contrib/ibmock/verbs.c
contrib/ibmock/verbs.h
src/uct/ib/efa/base/ib_efa.h
src/uct/ib/efa/base/ib_efa_md.c
src/uct/ib/efa/configure.m4
src/uct/ib/efa/srd/srd_ep.c
src/uct/ib/efa/srd/srd_ep.h
src/uct/ib/efa/srd/srd_iface.c
src/uct/ib/efa/srd/srd_iface.h
test/gtest/uct/ib/test_ib_xfer.cc
test/gtest/uct/ib/test_srd.cc

Add RDMA_WRITE support for EFA SRD transport.

UCT/IB/EFA: Add RMA WRITE operations

---

docs/source/ucx_features.rst

Mention in the docs that UCX supports NVLink

DOC: Mention nvlink as supported tl

---

buildlib/pr/efa.yml
contrib/test_efa.sh
test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_atomic.cc
test/gtest/ucp/test_ucp_context.cc
test/gtest/ucp/test_ucp_perf.cc
test/gtest/ucp/test_ucp_request.cc
test/gtest/ucp/test_ucp_rma.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag_mem_type.cc
test/gtest/ucp/test_ucp_tag_xfer.cc
test/gtest/ucp/test_ucp_worker.cc
test/gtest/ucp/ucp_test.h

Enable UCP tests for EFA SRD, tested on actual setup.

GTEST/UCP: Enable EFA SRD support

---

src/ucm/util/replace.c
src/ucm/util/replace.h

Removed unused macro parameter.

UCM/UTIL: Removed unused macro parameter.

---

AUTHORS
src/tools/perf/api/libperf.h
src/tools/perf/lib/libperf_int.h
src/ucs/arch/aarch64/cpu.h
src/ucs/arch/ppc64/cpu.h
src/ucs/arch/rv64/cpu.h
src/ucs/arch/x86_64/cpu.c
src/ucs/sys/init.c

UCS: Fix for GCC 15 -Werror=enum-int-mismatch

---

test/apps/test_cuda_hook.c

Replaced `cuCtxCreate` by `cuDevicePrimaryCtxRetain`.
Recommended by the CUDA Driver API documentation.
Cherry-picked https://github.com/openucx/ucx/pull/10707

TEST/APPS: Removed cuCtxCreate from test_cuda_hook - v1.19.x

---

bindings/go/Makefile.am

Fixed https://github.com/openucx/ucx/issues/10567.

BINDINGS/GO: Fixed go bindings compilation with CUDA.

---

NEWS

Prepare NEWS file for 1.19.0-rc1

NEWS: Add v1.19.0-rc1 description

---

test/gtest/ucp/test_ucp_peer_failure.cc

Add gtest to make sure that all the lanes properly include/exclude transports with invalidate rma when rndv is active/inactive.

UCP/WIREUP: Don't request invalidate without RNDV

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/proto/proto_common.c
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/ib/Makefile.am
src/uct/ib/base/ib_log.inl
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/ucs/test_topo.cc

Direct NIC datapath support without flush support, relates to #10744.

Direct NIC Datapath

---

src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Addressed code review comments:
https://github.com/openucx/ucx/pull/10760#discussion_r2256446753
https://github.com/openucx/ucx/pull/10760#discussion_r2260398464

UCT/IB: Minor fixes related to Direct NIC.

---

AUTHORS

No longer at SBU
keep my name there

Use personal email address, to keep connected to project

---

src/ucp/api/device/ucp_device_impl.h
src/ucp/api/device/ucp_device_types.h
src/ucs/sys/compiler_def.h

Add cooperation level and flag definition.

UCP/DEVICE: Add cooperation level and flags

---

Makefile.am
buildlib/az-helpers.sh
buildlib/tools/common.sh
contrib/test_jenkins.sh
contrib/ucx_perftest_config/test_types_ucp_device_cuda
src/tools/perf/Makefile.am

CI jenkins job for UCP cuda device perftest

UCP/PERF: CI jenkins job for cuda device perftest

---

contrib/test_jenkins.sh
src/tools/perf/cuda/cuda_alloc.c
src/tools/perf/cuda/cuda_common.h
src/tools/perf/cuda/cuda_kernel.cuh
src/tools/perf/cuda/ucp_cuda_kernel.cu
src/tools/perf/lib/libperf.c

- FIxes for previous PR (https://github.com/openucx/ucx/pull/10850)
- UCP cuda device real tests

UCP/PERF: UCP cuda device real tests

---

AUTHORS
bindings/go/Makefile.am
buildlib/az-distro-release.yml
buildlib/az-helpers.sh
buildlib/azure-pipelines-release-drp.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose-aarch64.yml
buildlib/dockers/docker-compose-x86_64.yml
buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml
buildlib/tools/common.sh
buildlib/tools/perf-common.yml
test/gtest/uct/cuda/test_switch_cuda_device.cc

Ported from PR #10788
Depends on PR https://github.com/openucx/ucx/pull/10889

AZP/RELEASE: Add CUDA 13 support - v1.19.x

---

NEWS

Updated NEWS for release v1.19.1.

NEWS: Add v1.19.1-rc1 description

---

src/ucp/api/device/ucp_device_impl.h
src/ucp/core/ucp_device.c
src/ucs/sys/device_code.h
test/gtest/ucp/cuda/test_kernels.cu
test/gtest/ucp/cuda/test_kernels.h
test/gtest/ucp/test_ucp_device.cc

Add method to write to local counter.

UCP/DEVICE: add method to write to local counter.

---

src/uct/api/device/uct_device_impl.h
src/uct/cuda/cuda_ipc/cuda_ipc.cuh
src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
test/gtest/Makefile.am
test/gtest/ucp/test_ucp_device.cc
test/gtest/uct/cuda/test_cuda_ipc_device.cc
test/gtest/uct/cuda/test_kernels.cu
test/gtest/uct/cuda/test_kernels_uct.cu
test/gtest/uct/cuda/test_kernels_uct.h
test/gtest/uct/test_device.cc

Add cuda_ipc device api implementation for
* uct_device_ep_put_multi_partial
* uct_device_ep_put_multi
* uct_device_ep_atomic_add

UCT/CUDA_IPC: implement device put multi, put partial, atomic

---

buildlib/tools/test_ctags.sh
contrib/ctags_ucx.awk

Generate tags for profile macros with suffix `_ALWAYS`.

BUILD: Add tags for profile macros with _ALWAYS suffix

---

src/ucp/core/ucp_context.c

UCP: Simplify md map initialization

---

AUTHORS
src/uct/ze/copy/ze_copy_iface.c
src/uct/ze/copy/ze_copy_md.c

Fix ZE transport build failures

UCT/ZE: fix ze transport build failures
