openucx/ucx

test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_tag_match.cc
test/gtest/ucs/test_mpool.cc
test/gtest/uct/uct_p2p_test.cc

Allow running on system with smaller memory size, such as BlueField SoC

TEST/GTEST: Limit test buffer sizes according to memory size

---

test/gtest/ucp/test_ucp_am.cc

Generate REPLY_EP/non-REPLY_EP AM closed EP tests as variant.
To simplify code and not duplicate tests by having variants.
Use variants of `{ 0; REPLY_EP }` flag to test different cases. Pass AM operation `flags` to warmup iterations.

GTEST/UCP: Generate REPLY_EP/non-REPLY_EP AM closed EP tests as variants

---

src/ucp/core/ucp_am.c
src/ucp/core/ucp_ep.c
src/uct/api/uct.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/sm/mm/base/mm_ep.c
src/uct/sm/scopy/cma/cma_ep.c
test/gtest/ucp/test_ucp_am.cc
test/gtest/uct/test_peer_failure.cc

1. Resolve remote ID only when if the endpoint was created with `PEER_FAILURE` feature support.
2. Update `test_ucp_am_nbx_closed_ep` gtest to do `0`-length AM operation which only ensures that two peers are fully connected.
3. Introduce `UCT_SEND_FLAG_PEER_CHECK` AM Bcopy flag; use this flag when sending AM-base keepalive `EP_CHECK` message to a peer; handle the flag in UCT/MM to check remote peer existence.
1. To make sure that EP knows the correct ID of a remote peer prior to communicating with the peer.
2. To reproduce the issue when EP wasn't resolved during AM short and then `ucp_ep_close_nbx` is done for receiver's EP (other protocols resolve it - so they are not suitable).
3. `UCT_SEND_FLAG_PEER_CHECK` - forces checking connectivity to a peer during sending some data to it. All …

UCT/API/MM/UCP: Introduce PEER_CHECK AM Bcopy flag, resolve remote ID for UCP EP if PEER_FAILURE requested

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/wireup.c

Align `ucp_ep_create_base` with `ucp_ep_destroy_base`.
`ucp_ep_destroy_base` is not align with `ucp_ep_create_base` after merging https://github.com/openucx/ucx/pull/7919.
`ucp_ep_destroy_base` should be called after `ucp_ep_create_base` without any additional actions, i.e. they are mutually inverse.
1. Remove `ucp_worker_create_ep` function.
2. Align `ucp_ep_create_base` to make sure that `ucp_ep_destroy_base` is mutually inverse.
3. Add auxiliary functions: `ucp_ep_allocate`/`ucp_ep_deallocate`/`ucp_ep_shall_use_indirect_id` to simplify code and reduce duplications.

UCP/CORE: Make ucp_ep_create_base mutually inverse to ucp_ep_destroy_base

---

contrib/ucx_perftest_config/test_types_ucp_rma

Restore missing performance test file that is used in CI (but skipped since not found)

CONTRIB/PERFTEST: Add missing file

---

src/tools/perf/lib/libperf.c

Fix race condition of multiple threads trying to send over the same socket
issue introduced by #7948

TOOLS/PERF: Fix status exchange with multiple threads during warmup

---

test/gtest/ucp/test_ucp_am.cc

Fixed missing of test_ucp_am_nbx_align instantiation.

GTEST/UCP: Enabled UCP AM align tests.

---

config/m4/go.m4

Default ./configure command can fail if go compiler is too old

CONFIG/GO: Don't fail configure if can't find go compiler

---

contrib/test_jenkins.sh

Do not let io_demo test run infinitely

CONTRIB/JENKINS: Limit io_demo retries to avoid infinite run

---

contrib/test_jenkins.sh
test/gtest/uct/test_peer_failure.cc

Few small fixed, needed to make CI pass on BlueField SoC
* Restore LD_LIBRARY_PATH after MPI tests. On latest Linux distros, DT_RPATH is replaced by DT_RUNPATH that has lower priority than LD_LIBRARY_PATH. So keeping that env var set later on makes gtest load UCX libraries from install dir rather than from build dir, which fails test_module gtest (since the test module is not installed).
* When using armclang compiler, force using GCC toolchain from module instead of from the local OS. By default, clang tries to take the one which is newer in some (but not all) cases. Without this fix, there are link issues with basic_string default constructor.
* Reduce number of concurrent IB contexts, otherwise device fails to open.

Fixes for running CI on a BlueField device

---

src/uct/sm/mm/base/mm_iface.c

Disable PEER_FAILURE capability for XPMEM.
XPMEM doesn't support neither KA mechanisms nor PEER_FAILURE capability.
Remove `UCT_IFACE_FLAG_ERRHANDLE_PEER_FAILURE` flag from iface's capability flags.

UCT/MM: Disable PEER_FAILURE capability for XPMEM

---

src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_md.c

Some properties of subfunction device (such the one inside BlueField SoC) were not read correctly from sysfs: device bus id and PCIe speed. Since bus id was not ready correctly, some unit tests failed when sys_dev of IB devices was UNKNOWN.
Before this fix, only PCIe identifiers (vendor and device) were adjusted to support subfunction devices.
- Move PCIe code from ib_md.c to ib_device.c
- Read all device-related sysfs information in ib_device.c
- Discover sysfs path once (the correct directory should contain a file named "device") and use it throughout the initialization phase.

UCT/IB: Fix subfunction device query

---

buildlib/az-helpers.sh
contrib/test_jenkins.sh
test/apps/test_ucx_tls.py

Fix several CI tests on BlueField SoC, that were failing because tried to run traffic over representor devices.
Skip representor devices - they are detected by an empty GID table

AZP/CI: Skip representor devices

---

test/gtest/common/mem_buffer.cc

Add missing white spaces to error prints

GTEST/GPU: Add missing spaces to error prints

---

config/m4/go.m4

Fix Go compiler detection - backport #7688 and #8021

Backport GO bindings build fixes to v1.12.x

---

contrib/buildrpm.sh
ucx.spec.in

Disables go bindings in rpmbuild scripts
To fix #8027

BINDINGS/GO: Disable go bindings in rpmbuild.

---

README.md
src/uct/ib/rc/accel/rc_mlx5_common.c

Backport https://github.com/openucx/ucx/pull/7982 to v1.12.x

UCT/IB: Use DV QP create_flags only if needed - v1.12.x

---

src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h

Fix printing invalid configuration.
Now it is printed as follows:
```
[1647246206.076101] [swx-ucx07:40361:0]      ucp_worker.c:1899 UCX  INFO  ep_cfg[0]:
[1647246206.079982] [swx-ucx07:40361:0]      ucp_worker.c:1899 UCX  INFO  ep_cfg[1]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1) rma(rc_mlx5/mlx5_bond_0:1) amo(rc_mlx5/mlx5_bond_0:1)
[1647246206.086670] [swx-ucx07:40361:0]      ucp_worker.c:1899 UCX  INFO    ep_cfg[2]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1) rma(rc_mlx5/mlx5_bond_0:1) amo(rc_mlx5/mlx5_bond_0:1)
```
Fixes #8024
`print_cfg` parameter was removed from `ucp_worker_get_ep_config` function in 03e9f2b0052bf6e7e17c18c0c2d8cb6cf194acc0
1. In `ucp_worker_get_ep_config`, check and add to lanes bitmap only valid TL resources.
2. In `ucp_worker_get_ep_config`, add AM …

UCP/CORE: Fix printing invalid configuration

---

src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h

Get rid of `tx_ops_count` which has the same value as `tx_cq_len`
`tx_ops_count` duplicates `tx_cq_len`, we could leave one of them.
1. Move `tx_cq_len` away from `UCX_ENABLE_ASSERT` section.
2. Make `tx_cq_len` unsigned.
3. Remove `tx_ops_count` field and replace all its occurrences with `tx_cq_len`.

UCT/IB/RC: Get rid of tx_ops_count which has the same value as tx_cq_len

---

contrib/test_jenkins.sh
src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/base/ib_md.h

When running CI tests on machine with several interfaces without RoCEv2, and also on different subnets, need to prevent them from connecting to each other.

UCT/IB/TEST: Don't cross-connect RoCE devices in gtest

---

src/ucp/core/ucp_ep.h
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c

Allow selecting auxiliary transports when creating EP for sending `EP_REMOVED` packet.
If `ud` will be used as a keepalive lane for `UCX_TLS=rc` (where `ud` is defined as auxiliary transport), creating EP for sending `EP_REMOVED` will fail, because it couldn't select AM lane with `CONNECT_TO_IFACE` capability.
1. Add new EP initialization flag - `UCP_EP_INIT_ALLOW_AUX_TL_RSC`.
2. Pass `UCP_EP_INIT_ALLOW_AUX_TL_RSC` flag to create UCP EP.
3. Update `ucp_wireup_select_transport` to allow selecting auxiliary transport in case of `UCP_EP_INIT_ALLOW_AUX_TL_RSC` flag specified.

UCP/CORE/WIREUP: Allow selecting auxiliary transports when creating EP for sending EP_REMOVED

---

NEWS

NEWS: Update for v1.12.1-rc4

---

buildlib/pr/main.yml
contrib/test_jenkins.sh

Run UCX CI on BLueField2 SoC device

AZP: Add BF to CI

---

src/uct/ib/ud/base/ud_ep.c

Remove duplicated async dispatch.
`uct_ud_iface_dispatch_async_comps` is done in `uct_ud_ep_purge`, no need to do it twice.
Remove `uct_ud_iface_dispatch_async_comps` in `uct_ud_ep_flush(CANCEL)`.

UCT/IB/UD: Remove duplicated async dispatch

---

contrib/valgrind.supp

The existing suppression, added in #8046 did not work because missing "..." for additional stack frames, and also it would not cover a case of different libmlx5.so path.

CONTRIB/VALGRIND: Fix suppression for rdma-core uar leak

---

src/uct/api/uct.h

Introduce feature flags for describing UCT interface capabilities requested by UCP layer.
When calling `uct_iface_open`, UCP will specify to UCT which feature are needed - according to UCP context/worker initialization.
Then, each UCT interface will support only these capabilities which are requested by UCP, and needed by its internal type logic.
The initial motivation for this change is to allow using DC half-handshake if RDMA_WRITE is not needed. For the UCT layer (DC interface) to determine that, UCP worker need to pass that info ("PUT" not needed).
In the future this logic can be extended in order to save resources and avoid initializing "features" which were not requested.

UCT/API: Introduce interfaces features

---

src/ucm/util/reloc.c

Fixes a bug when getauxval is not available, in which case
HAVE_DECL_GETAUXVAL is defined to zero, so it needs to be checked with `if` and not `ifdef`.
See above.

UCM/UTIL: Fix HAVE_DECL_GETAUXVAL ifdefs

---

src/ucp/core/ucp_worker.c

This commit fixes an occasional crash observed in MPI_Finalize of Open MPI when using UCX with ROCm support.
The crash is triggered from ucp_worker_progress() - opal_common_ucx_mca_pmix_fence().
Root cause of the issue is that the rocm uct components do not set UCT_IFACE_FLAG_EVENT_RECV in the iface_query() functions.
##Why
Actual error message:
```
[ixt-sjc2-54:62513:0:62513]  ucp_worker.c:612  Assertion `wiface->attr.cap.event_flags & (1ul << (1))' failed
```
The line in question ucp_worker.c is :
``` 
ucs_assert(wiface->attr.cap.event_flags & UCT_IFACE_FLAG_EVENT_RECV);
```
Avoid calling ucp_worker_iface_check_events() if UCT_IFACE_FLAG_EVENT_RECV is not set.

UCP/CORE: fix occasional crash in finalize

---

src/ucs/datastruct/queue.h
src/uct/ib/ud/base/ud_ep.c
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/base/ud_iface.c

Fix `flush(CANCEL)` in UD transport.
`flush(CANCEL)` doesn't work correctly - it doesn't wait for all Zcopy TX operation completions.
1. Send control messages with `SIGNALED` flag if `FLUSH_CANCEL` flag set on endpoint.
2. Release completed operations in TX window even if `resent_skb` isn't set in `cdesc`.
3. Remove `UCT_UD_SEND_SKB_FLAG_ACK_REQ` flag from SKB and always send `UCT_UD_EP_OP_ACK_REQ` to make sure it is send with `SIGNALED` flag.

UCT/IB/UD: Fix flush(CANCEL)

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c

Fix CM wireup fallback.
To allow selecting multiple paths (if their are supported) in CM initial configuration. It was restricted by `AM_LANE_ONLY` flag 
during fallback, because `rc` and `dc` try to create CM configuration with auxiliary UD for keepalive.
1. Introduce `UCP_EP_INIT_DISALLOW_AUX_TL_RSC` EP init flag to disallow selection of AUX transports at all.
2. Change order in EP init flags to have `UCP_EP_INIT_DISALLOW_AUX_TL_RSC` before `UCP_EP_INIT_CREATE_AM_LANE_ONLY` -  it is needed to prefer `UCP_EP_INIT_DISALLOW_AUX_TL_RSC` over `UCP_EP_INIT_CREATE_AM_LANE_ONLY` in `ucs_for_each_submask`.
3. Update `ucp_cm_client_uct_connect_progress` to do the following retries of initializing of CM configuration:
- `ep_init_flags` = `0`
- `ep_init_flags` = `UCP_EP_INIT_DISALLOW_AUX_TL_RSC`
- …

UCP/WIREUP/CORE: Fix CM wireup fallback

---

src/ucp/wireup/select.c

Do not print error if UCP is not able to establish all rma/bw lanes. 
Currently UCX can create up to 6 lanes. When many rma|am bw lanes are requested they may not fit the requirement and UCX prints an error, like:
`ERROR   cannot add rma_bw lane - reached limit (6)`
But in this case it is not really an error, because ep is created with as many additional lanes as fit ucp ep limits

UCP: Do not report lane limit error for rma and bw lanes

---

src/ucs/datastruct/pgtable.c

Check that number of regions of page table is not 0 before starting to purge the table.
The issue was caught by memory checker tool ElectricFence.

UCS/DATASTRUCT: Check num regions before call to calloc.

---

src/tools/info/ucx_info.c
src/ucp/core/ucp_ep.c

1. Print stream API limits.
2. Handle stream feature in `ucx_info`.
To show stream API limits from `ucx_info` utility.
Before:
```
#
#
#
#
```
After:
```
#
#
#
#
```
1. Update `ucx_info` utility by setting `UCP_FEATURE_STREAM` to the bitmap of UCP features if `-u s` is specified.
2. Update `ucp_ep_config_print` function to print stream AP limits using AM message configuration limits (checked stream_send.c) and pass them to `ucp_ep_config_print_proto` function + disable RNDV by passing `SIZE_MAX`.

UCP/CORE/INFO: Print stream API limits and handle stream feature in ucx_info

---

src/ucp/core/ucp_worker.c

Print keepalive lane from the configuration.
To make sure that keepalive is done on a desired transport.
Before:
```
[1648584569.734329] [swx-ucx01:45206:0]      ucp_worker.c:1686 UCX  INFO  ep_cfg[1]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1) stream(rc_mlx5/mlx5_bond_0:1)
```
After:
```
[1648589358.246918] [swx-ucx01:62071:0]      ucp_worker.c:1690 UCX  INFO    ep_cfg[0]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1) rma(rc_mlx5/mlx5_bond_0:1) amo_am(rc_mlx5/mlx5_bond_0:1) keepalive(ud_mlx5/mlx5_bond_0:1)
```
Update `ucp_worker_print_used_tls` to print keepalive lane using `ucp_worker_add_feature_rsc` function.

UCP/CORE: Print keepalive lane from the configuration

---

src/uct/ib/ud/base/ud_iface.c

Remove `return` operator from CEP purge callback.
It is not needed since there is no return value in connection matching purge callback.
Remove `return`, just invoke `ep_free` by using `uct_iface_invoke_ops_func`.

UCT/IB/UD: Remove return operator from CEP purge callback

---

src/ucp/core/ucp_mm.c
src/ucp/rndv/rndv_ppln.c

Replaced space by underscore in rcache name because all other rcache names use underscore style, and in ucs_calloc because we mostly use underscore style in such cases.
Replaced expression by appropriate function call.
before:
after:
list of some objects created by ucs_calloc/ucs_malloc:

UCP/CORE: Minor code improvements.

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/core/ucp_rkey.inl
src/ucp/core/ucp_types.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv.h
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/ucp/test_ucp_tag_mem_type.cc

Implement 2-staged pipeline protocol with proto v1 version
Avoiding one memory copy gives noticeable performance gain for the intranode transfers
Based on the existing put-ppln scheme, but sender copies its data to the receiver staging buffer rather than its own

UCP/RNDV/GPU: Add 2-stage ppln rndv protocol

---

src/ucs/arch/cpu.h

Automatically enable relaxed order for AMD model
to maximize performance for AMD model

UCS/ARCH: auto enable relaxed order for AMD

---

src/uct/ib/ud/base/ud_ep.c

Add missing locks in deferred timeout handler.
Fixes potential data race of deferred timeout handler (which is called from application's thread) and UD async thread which polling TX/RX CQEs.
e.g.:
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f13f5013311 in ucs_arbiter_group_desched_nonempty (arbiter=0x279f648, group=0x47e7080) at datastruct/arbiter.c:231
231         ucs_arbiter_elem_t *head = group->tail->next;
(gdb) bt
#0  0x00007f13f5013311 in ucs_arbiter_group_desched_nonempty (arbiter=0x279f648, group=0x47e7080) at datastruct/arbiter.c:231
231         ucs_arbiter_elem_t *head = group->tail->next;
Missing separate debuginfos, use: debuginfo-install coreutils-8.22-23.el7.x86_64 fuse3-libs-3.6.1-2.el7.x86_64 glibc-2.17-260.el7.x86_64 libgcc-4.8.5-36.el7.x86_64 …
```

UCT/IB/UD: Add missing locks in deferred timeout handler

---

src/uct/ib/base/ib_md.c

Changes the message about "disabling IB transports due to memlock limit" to warning.
Now this message prints on diagnostic message. But some customers may consider the disabling of IB transports without may warning as a regression. So, this patch moves this message to the warning level.

UCT/IB: Change the IB transports memlock message to warning

---

src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h
src/uct/ib/rc/verbs/rc_verbs_iface.c

- Use maximal allowed `max_rd_atomic` value by default
- Print clear error when user requests `max_rd_atomic` value which is not supported
- Automatically pick-up maximal allowed by the HCA `max_rd_atomic` value for better performance
- Better user experience
Examples of error output if incorrect value is requested:
```
$UCX_TLS=dc UCX_RC_MAX_RD_ATOMIC=567 ./src/tools/info/ucx_info -e -ut
rc_iface.c:546  UCX  ERROR invalid max_rd_atomic value: 567, can be up to 16
<Failed to create UCP worker>
$UCX_TLS=dc UCX_RC_MAX_RD_ATOMIC=inf ./src/tools/info/ucx_info -e -ut
rc_iface.c:546  UCX  ERROR invalid max_rd_atomic value: inf, can be up to 16
<Failed to create UCP worker>
```

UCT/RC/DC: Set max allowed rd_atomic_value

---

src/tools/info/sys_info.c
src/ucs/arch/x86_64/cpu.c
src/ucs/arch/x86_64/cpu.h
src/ucs/time/time.c

Fix CPU frequency on AMD platforms.
before:
```
$ ucx_info -s
```
after:
```
$ ./src/tools/info/ucx_info -s
```
CPU info:
```
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
CPU MHz:                         3283.823
BogoMIPS:                        4491.52
```

UCS/ARCH/INFO: Measure x86 TSC value if can't read it from CPU model

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h

Fix double free of TX DCIs array.
Fixes:
```
[1649063561.762911] [swx-ucx02:25944:0]         dc_mlx5.c:473  UCX  ERROR ibv_modify_qp(DCI, RTS) failed : Invalid argument
*** Error in `/hpc/mtr_scrap/users/dmitrygla/ucx/./test/gtest/gtest': double free or corruption (!prev): 0x0000000002adc010 ***
```
It frees `iface->tx.dcis` array twice:
1. https://github.com/openucx/ucx/blob/55c3ae4f5d8cfe80fe5fcbc438c120f66d40aaf7/src/uct/ib/dc/dc_mlx5.c#L861
2. https://github.com/openucx/ucx/blob/55c3ae4f5d8cfe80fe5fcbc438c120f66d40aaf7/src/uct/ib/dc/dc_mlx5.c#L1464
1. Remove calling `ucs_free(iface->tx.dcis)` in `uct_dc_mlx5_iface_dcis_destroy`.
2. Add calling `ucs_free(iface->tx.dcis)` in DC's iface destructor after calling `uct_dc_mlx5_iface_dcis_destroy`.

UCT/IB/DC: Fix double free of TX DCIs array

---

src/ucp/core/ucp_worker.c
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h

Use DC half-handshake with adaptive routing, when RDMA_WRITE is not used (if RNDV is only RDMA_READ, and no GPU memory).
Following https://github.com/openucx/ucx/pull/7511, we want to improve the logic by allowing DC half-handshake even with AR, in case RDMA_WRITE is not needed.
Introduce "features" in UCT iface layer, which are filled by the UCP worker according to its features & config, before calling `uct_iface_open`.
Then, supported iface caps are limited according to the requested features. The UCP layer knows in advance, whether RDMA_WRITE will be needed, and is able to pass that information to the UCT layer.

UCT/IB: Use DC half-handshake with AR, when RDMA_WRITE is not used

---

src/ucp/rma/amo_sw.c
src/ucp/rma/rma_sw.c

Initialize request's send state in case of SW RMA/AMO.
Fixes the following issue:
```
/auto/rdmzsysgwork/dmitrygla/ucx/src/ucs/sys/stubs.c: [ ucs_empty_function_do_assert_void() ]
...
99
100 void ucs_empty_function_do_assert_void()
101 {
==>   102     ucs_assert_always(0);
103 }
==== backtrace (tid:   9039) ====
0 0x000000000008482b ucs_empty_function_do_assert_void()  /auto/rdmzsysgwork/dmitrygla/ucx/src/ucs/sys/stubs.c:102
1 0x000000000006cc2c ucp_send_request_invoke_uct_completion()  /auto/rdmzsysgwork/dmitrygla/ucx/src/ucp/core/ucp_request.inl:453
2 0x000000000006cc2c ucp_request_send_state_ff()  /auto/rdmzsysgwork/dmitrygla/ucx/src/ucp/core/ucp_request.c:710
3 0x00000000000531f1 ucp_ep_err_pending_purge()  /auto/rdmzsysgwork/dmitrygla/ucx/src/ucp/core/ucp_ep.c:1176
4 …
```

UCP/RMA: Initialize request send state in case of SW RMA/AMO

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h

1. Use address version flag.
2. Check whether HW reports better performance when no RDMA_WRITE
1. Currently device flag is used, which is a bug (incorrect value).
2. Only set `rdma_wr_disabled` bit when it has an impact.

UCT/IB: Improve DC full handshake logic

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fix max_rd_atomic_dc value for DV
Before
```
$UCX_IB_MLX5_DEVX=no UCX_TLS=dc UCX_DC_MLX5_MAX_RD_ATOMIC=16  ucx_info -e -ut
[1649332429.743654] [jazz07:34105:0]        rc_iface.c:549  UCX  ERROR invalid max_rd_atomic value: 16, can be up to 0
<Failed to create UCP worker>
```
After
```
$UCX_IB_MLX5_DEVX=no UCX_TLS=dc UCX_DC_MLX5_MAX_RD_ATOMIC=16  ucx_info -e -ut
#
#
#
#
#
```

UCT/DC: Fix max_rd_atomic_dc value for DV

---

src/ucp/core/ucp_context.c

Fix `ucx_info` formatting of some rndv vars
Before
```
$ ucx_info -f | grep -B 5 MULTI_LANE_MAX_RATIO
#
#
#
UCX_MULTI_LANE_MAX_RATIO=4.000
```
After
```
$ ./src/tools/info/ucx_info -f | grep -B 5 MULTI_LANE_MAX_RATIO
#
#
UCX_MULTI_LANE_MAX_RATIO=4.000
```

UCP: Fix ucx_info -c formatting for rndv vars

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/ugni/base/ugni_md.c

Introduce forward compatible `uct_md_mkey_pack_v2`
UCT/IB/DEVX: invalidate MR using indirect key #8061 requires extra argument `flags` for `uct_md_mkey_pack`

UCT/API: uct_md_mkey_pack_v2

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c

Add another fallback type by creating KA lane from already selected resources.
To not open additional resources in case of lack of space in CM private data to pack all addresses.
1. Add `tl_bitmap` to UCP wireup select context and update it by adding `rsc_index` which were selected.
2. Introduce new EP init flag - `UCP_EP_INIT_KA_FROM_EXIST_LANES` to select transport fo keepalive lane from already selected lanes.
3. Add `UCP_EP_INIT_KA_FROM_EXIST_LANES` flag to fallback priority list.

UCP/WIREUP: Try fallback creating KA lane from exisiting lanes

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/rndv/rndv.c
src/uct/base/uct_md.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/sm/scopy/knem/knem_md.c
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/test_md.cc

Invalidate MR using indirect key. Another approach of #8002
To minizimize rkey collisions.

UCT/IB/DEVX: invalidate MR using indirect key

---

src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/ib/base/ib_md.c
src/uct/sm/scopy/knem/knem_md.c

Add the option to disable rcache invalidation on fork.
rcache invalidation on fork can have performance overheads due to extra registration/deregistration. For IB in particular, and in presence of with ibv_fork_init, if the user knows that all buffers that are passed to UCX are page-aligned, there is no need to purge rcache on fork. This PR provides `UCX_IB_RCACHE_PURGE_ON_FORK` to disable IB rcache purge on fork.

Add the option to disable rcache invalidation on fork

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_worker.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_ep.c
src/ucp/wireup/wireup_ep.h

Fix keepalive selection logic.
UCP EP should select EP_CHECK only for lanes from `p2p_lanes` map, otherwise - use AM-based keepalive.
1. Update `ucp_ep_is_am_keepalive` and `ucp_ep_do_uct_ep_keepalive` to accept lane on which keepalive should be done.
2. Update `ucp_ep_is_am_keepalive` to check whether `lane` exists in `p2p_lanes` or not. If doesn't exist there, use AM-based keepalive.

UCP/CORE: Fix keepalive selection logic

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c

Fix resending `FC_PURE_GRANT` in case of failure of DCI.
Purging of pending queue of FC endpoints during error handling leads to removing `FC_PURE_GRANT` requests which were rescheduled to pending queue due to completing them with `WC_FLUSH_ERR` status.
Don't release FC requests to mpool, need to collect them in a queue of FC pure grants and resend them after recovering DCI .

UCT/IB/DC: Fix resending FC_PURE_GRANT in case of failure

---

src/uct/base/uct_mem.c

- in case if in uct_iface_mp_chunk_alloc function used non-MD method
without registration support it crashed
- fix:  force use MD allocation method in such cases

UCT/MEM: fixed potential crash on MD mem alloc

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/exp/ib_exp_md.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/ud/accel/ud_mlx5.c

- disabled DC on over pure verbs: added get_flags interface into IB ops
to allow get ops configuration

DC/MLX5: disabled DC on verbs

---

configure.ac
ucx.spec.in

Followup to branching v1.13.x. This PR must be merged before any other PR on master.

CONFIG/SPEC: Bump version to 1.14.0

---

src/ucp/core/ucp_context.c

Report an error if KA interval = 0.
Running `UCX_KEEPALIVE_INTERVAL=0 ./install/master/bin/ucx_info -eptw -u traew` fails with:
```
[swx-ucx01:8132 :0:8132]  ucp_worker.c:3110 Assertion `ka_interval > 0' failed
/hpc/mtr_scrap/users/dmitrygla/ucx/src/ucp/core/ucp_worker.c: [ ucp_worker_keepalive_timerfd_init() ]
...
3107         ucs_debug("worker %p: removed keepalive current ep %p, moving to next",
3108                   worker, ep);
3109         worker->keepalive.lane_map = 0;
==>  3110         ucp_worker_keepalive_next_ep(worker);
3111         ucs_assert(worker->keepalive.iter != &ucp_ep_ext_gen(ep)->ep_list);
3112
3113         if (worker->keepalive.iter == &worker->all_eps) {
==== backtrace (tid:   8132) ====
0 0x0000000000084a50 ucp_worker_keepalive_timerfd_init() …
```

UCP/CORE: Report an error if KA interval = 0

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/verbs/rc_verbs_impl.h

Remove assertion which expects that sending FC grant will be completed with either `UCS_ERR_NO_RESOURCE` or `UCS_OK`.
This assertion could fail in case of `ibv_create_ah` fails during discovering some errors.
1. Implement `uct_dc_mlx5_iface_fc_pure_grant_str` function to use for printing FC_PURE_GRANT request where it is needed.
2. Replace `ucs_assert_always` by `ucs_diag` for checking the result of `uct_dc_mlx5_iface_fc_grant`.

UCT/IB/DC: Remove assertion for sending FC grant

---

src/ucp/api/ucp.h
src/ucp/api/ucp_def.h

The purpose for this PR is to push the public API changes needed to implement an extension to the ucp_ep_query function so that the transport and device names associated with an endpoint can be queried.  
I am implementing a change to OpenMPI that will allow a user to query the UCX transport(s) and device name(s) used for OpenMPI to communicate between node pairs in the set of nodes used by the application.
The current version of these changes can be seen at https://github.com/drwootton/ompi/commit/2a01800e74004c0e07ae97e302e2b7bd37500928 where the changes that use the proposed ucp_ep_query change are contained in ompi/mca/pml/ucx/pml_ucx.c
My intent is to follow up with a second PR that implements the changes needed to actually query the endpoint information in src/ucp/core/ucp_ep.c. The …

UCP/EP API changes to support extending ucp_ep_query to query endpoint transport information

---

src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

Remove internal purge callback in DC.
Remove unneeded functions.
Remove `uct_dc_mlx5_ep_arbiter_purge_internal_cb` and integrate its code to `-uct_dc_mlx5_ep_arbiter_purge_cb`.

UCT/IB/DC: Remove internal purge callback

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_proxy_ep.c
src/ucp/core/ucp_proxy_ep.h
src/ucp/wireup/wireup.c

Remove dead proxy_ep-related code.
Removed some code which is not needed anymore, since signaled-proxy EP was removed.
Remove `ucp_proxy_ep_destroy`, `ucp_proxy_ep_replace_if_owned`, `ucp_proxy_ep_test`.

UCP/WIRUEP: Remove dead proxy_ep-related code

---

src/ucs/async/async.c
src/ucs/async/async.h
src/ucs/async/thread.c
src/ucs/config/global_opts.c
src/ucs/config/global_opts.h
src/ucs/datastruct/mpmc.c
src/ucs/datastruct/mpmc.h
test/gtest/ucs/test_async.cc
test/gtest/ucs/test_mpmc.cc

Remove async_max_events limit
To support unexpected high number of concurrent TCP connections for example
By using ucs_queue instead of array inside mpmc queue

UCS/ASYNC: Remove async_max_events limit

---

src/ucp/am/rndv.c
src/ucp/dt/datatype_iter.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_am.c
test/gtest/ucp/test_ucp_am.cc

Enabled non-contig datatypes in AM rendezvous.
The changes are part of UCP transition to new infrastructure.

UCP/RNDV: Enabled non-contig datatypes in AM rendezvous.

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
test/gtest/ucp/test_ucp_am.cc

Disable resolving remote EP ID when creating local EP by default.
To not create remote endpoints which were not closed after the local one is closed.
1. Add `UCX_RESOLVE_REMOTE_EP_ID = { on, off, y, n, auto }` configuration parameter in UCP.
2. When creating "connect_to_worker" EPs, check this parameter and decide whether we need to resolve remote ID or not.
3. Resolve remote ID during creating a local EP only if configuration parameter is set to "y"/"on" or "auto" and error-handlign and keepalive are enabled.

UCP/CORE/GTEST: Disable resolving remote EP ID when creating local EP by default

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
test/gtest/ucp/test_ucp_am.cc

Disable resolving remote EP ID when creating local EP by default.
Backport of #8142.
See #8142's description.

UCP/CORE/GTEST: Disable resolving remote EP ID when creating local EP by default [v1.13.x]

---

src/uct/ib/ud/base/ud_def.h

Remove unused constants in packet flags.
`UCT_UD_PACKET_PUT_SHIFT` and `UCT_UD_PACKET_AM_ID_MASK` are unused and could be removed.
Remove `UCT_UD_PACKET_PUT_SHIFT` and `UCT_UD_PACKET_AM_ID_MASK`.

UCT/IB/UD: Remove unused constants in packet flags

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_listener.c
src/ucp/core/ucp_listener.h
src/ucp/wireup/wireup_cm.c

count the pending connection requests in ucp_listener
audit the connection requests that are dealed by the user application i.e. "After parsing the connection request parameters, it doesn't establish connection or reject the connection request"
Add ucp_listener::conn_reqs member filed and audit the number.

UCP: count pending connection request

---

src/uct/ib/ud/base/ud_ep.c
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/base/ud_iface.c
src/uct/ib/ud/base/ud_iface.h

Remove unused EP cloning.
`uct_ud_ep_clone` and `uct_ud_iface_replace_ep` functions are unused.
Remove `uct_ud_ep_clone` and `uct_ud_iface_replace_ep` functions.

UCT/IB/UD: Remove unused EP cloning

---

src/ucp/core/ucp_ep.c

Updated UCP EP config key copy: changing destination config key only in error-free flow, checking number of reachable mds before copying data. 
To avoid unnecessary 0-size allocations and memory copies.

UCP/CORE: UCP EP config key copy improvement.

---

src/uct/ib/base/ib_md.c

Align with b6722f27:
UCT/IB: Disable mlx5 over exp verbs
var is not defined and there's no need to declare it.
exp verbs has been removed.

UCT/IB: remove unmeaningful var declaration

---

src/uct/rocm/base/rocm_base.c

Increase the max. number of hsa agents to 63 (from 16).  Furthermore, minor reorganization of the uct_rocm_base_agents structure to reduce the number of cache misses.
The max. number of hsa agents includes both CPUs + GPUs and was too low for today's systems.

UCT/ROCM: increase max. number of hsa agents

---

test/gtest/ucp/test_ucp_sockaddr.cc

Fix arguments passing to `client_ep_connect`.
`specify_src_addr` is passed instead of `ep_index`, which is a bug.

TEST/GTEST: Fix connect_and_send_recv in test_ucp_sockaddr

---

src/ucp/core/ucp_mm.c
src/ucp/dt/dt.c
src/ucp/dt/dt.h

- due to no error processing in mem_pack/mem_unpack functions
ucs_error macro is replaced by ucs_fatal

DT/MEMPACK: changed error flow

---

src/ucp/api/ucp_def.h

Minor comment wording change in ucp_def.h
This change was requested in #7990 which had already been merged and closed
Signed-off-by: David Wootton <dwootton@us.ibm.com>

UCP/ENDPOINT: Fix wording in comment in ucp_def.h

---

src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_ep.c
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/base/ud_iface.h
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/uct/ib/test_ud.cc

Drop packets if EP is p2p and disconnected.
Drop packets on EP which p2p and disconnected to not answer with ACK packets to a peer.
So, a peer will detect an error due to not receiving ACKs.
1. Add UD verbs/mlx5 `ep_create` operation to use it for creating EPs and pass initial `flags` for EP (e.g. CONNECT_TO_EP).
2. Updated `uct_ud_ep_process_rx` to drop packets if `UCT_UD_EP_FLAG_DISCONNECTED` and `UCT_UD_EP_FLAG_CONNECT_TO_EP` flags are set on EP.

UCT/IB/UD: Drop packets if EP is p2p and disconnected

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5.inl
src/uct/ib/dc/dc_mlx5_ep.c

Schedule EP for resending `FC_HARD_REQ`.
Backportinf of #8169.
See #8169's description.

UCT/IB/DC: Schedule EP for resending FC_HARD_REQ [v1.13.x]

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/ib/test_ib_md.cc

UCT/IB/MLX5: Fix 2G aligned MR registration - v1.13.x

---

test/apps/iodemo/Makefile.am

- fixed build io-demo on Ubuntu 20.04
- on some Ubuntu distro autotools don't follow libs dependency
fixes https://github.com/openucx/ucx/issues/8178

BUILD/UBUNTU: fixed io-demo build

---

test/apps/iodemo/Makefile.am

- fixed build io-demo on Ubuntu 20.04
- on some Ubuntu distro autotools don't follow libs dependency
back port from https://github.com/openucx/ucx/pull/8179
(cherry picked from commit b0190283e06cdcd8b269195beb5314faea9d0e79)

BUILD/UBUNTU: fixed io-demo build - v1.13

---

src/ucs/memory/rcache.c
src/ucs/profile/profile.c
src/ucs/profile/profile_defs.h
src/ucs/profile/profile_off.h
src/ucs/profile/profile_on.h
src/uct/base/uct_mem.c
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_md.c
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rdmacm/rdmacm_cm_ep.c
test/apps/profiling/ucx_profiling.c
test/gtest/ucs/test_profile.cc

- Enable profiling some slow-path functions, such as memory registration, also in release mode - so it could be used in the default binary distributions\
- Fix UCS_PROFILE_CODE macro to not require a nested scope
- Add UCS_PROFILE_xx_ALWAYS() macros
- Reduce location id size to reduce memory footprint
- Add "always" profiling to some functions in IB component
- Update profiling unit tests to run also in release mode

UCS/PROFILE: Add UCS_PROFILE_xx_ALWAYS macros, enabled in release mode

---

src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.h

Fix initialization of the `log_ack_req_freq` field in RC MLX5 ifaces.
There is a bug - the field appears in 2 config types and gets overridden with 0 from the second (unused) config.

UCT/IB: Fix log_ack_req_freq field initialization

---

src/uct/sm/self/self.c

Without this fix, the self transport uses "memory0" device name, but it should use "memory" to show that shared memory transports such as cma/knem/sysv/posix should not be instantiated alongside with it.

UCT/SELF: Don't add device index if have only one device

---

examples/ucp_hello_world.c
src/ucp/api/ucp.h
src/ucp/api/ucp_compat.h

- Cleanup ucp.h
- Discourage using "_nb/_nbi/_nbr" APIs when there is an "_nbx" alternative
- Move deprecated APIs to ucp_compat.h
- Add a deprecation note with the recommended replacement
The APIs and their documentation were copied as-is, except adding the `@deprecated` note.

UCP/API: Move deprecated functions to ucp_compat.h

---

src/ucp/core/ucp_am.c
src/ucp/core/ucp_request.h
src/ucp/rndv/proto_rndv.c
src/ucp/tag/tag_recv.c

Fix UCP_OP_ATTR_FLAG_MULTI_SEND flag was not passed to all RNDV protov2 initialization functions

UCP/PROTO: Add op_attr_mask to rendezvous protocol selection

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/ud/accel/ud_mlx5.c

Fix using thread domain object in accelerated verbs flow
Thread domain provides per-thread IB verbs resources isolation.
When thread domain not supported - falling back to isolation in UCT layer.

UCT/IB: Fix thread domain

---

src/ucp/core/ucp_request.c

Remove assertion for checking `WIREUP_MSG`s when purging.
Only `WIREUP_MSG`/`PRE-REQ` packet is allowed to be scheduled on normal UCT EP. But no need to check it.
Update `ucp_request_send_state_ff` to not check `WIREUP_MSG`s being scheduled on normal UCT EP.

UCP/CORE: Remove assertion for checking WIREUP_MSGs when purging

---

src/ucp/core/ucp_ep.c
test/gtest/ucp/test_ucp_ep.cc

Implement a change to the API for the ucp_ep_query function so the caller can query the transport/device name pairs associated with an active endpoint. This implements the API header changes in pull request #7990.
OpenMPI users have requested the ability to query the transport and device name pairs used by an MPI task when the transport used by OpenMPI is UCX. This information is useful to OpenMPI users so they can verify that application tasks are actually using the transports that the user requested. 
The ucp_ep_attr structure is modified by adding a new bitmask bit, UCP_EP_ATTR_FIELD_TRANSPORTS that the caller sets to request endpoint transport/device name pairs. The caller fills in the transports structure in ucp_ep_attrs to specify the attributes of the ucp_transport_entry_t array …

UCP/ENDPOINT: Implementation of API changes to query transport/endpoint pairs associated with an endpoint

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
test/gtest/uct/test_peer_failure.cc

Fix error handling for keepalive DCI if EP has another DCI.
If got failure on keepalive DCI, don't update TX resources of normal DCI of the EP, because CQE is not related to this DCI.
It fixes:
```
[jazz17:136720:0:136720]   dc_mlx5.inl:21   Assertion `uct_rc_txqp_available(txqp) <= txwq->bb_max' failed
/hpc/mtr_scrap/users/dmitrygla/ucx_int3/src/uct/ib/dc/dc_mlx5.inl: [ uct_dc_mlx5_update_tx_res() ]
...
18                           uct_rc_txqp_t *txqp, uint16_t hw_ci)
19 {
20     uct_rc_txqp_available_set(txqp, uct_ib_mlx5_txwq_update_bb(txwq, hw_ci));
==>    21     ucs_assert(uct_rc_txqp_available(txqp) <= txwq->bb_max);
22
23     uct_rc_iface_update_reads(&iface->super.super);
24 }
==== backtrace (tid: 136720) ====
0 0x00000000001341d2 uct_dc_mlx5_update_tx_res() …
```

UCT/IB/DC: Fix error handling for keepalive DCI if EP has another DCI

---

test/gtest/Makefile.am
test/gtest/uct/ib/test_cqe_zipping.cc
test/gtest/uct/ib/test_ib.h

Testing of the CQE zipping feature.
No we don't have a special test case that covers CQE zipping.
This test performs a lot of similar send operation using active messages UCT API (bcopy/zcopy) and then checks the CQE zipping counters after that.  If at least one CQE zipping event was noticed, the test was passed successfully.

UCT/IB/MLX5: CQE zipping feature testing

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_worker.c

While adding new string configuration to ucp_context_config_t (proto_info_dir), it turned out we need to strdup() it manually. But a better method is to use ucs_config_parser_clone_opts().

UCP/CONTEXT/CONFIG: Use ucs_config_parser_clone_opts for copying config

---

docs/source/faq.md

Fix static build section not rendered correctly in the read-the-docs site

DOC/FAQ: Use HTML markup for static build table

---

src/uct/ib/rc/base/rc_ep.c
src/uct/ib/rc/base/rc_iface.h

Fix always having STATUS flag in IFACE send ops.
Send ops which belong to IFACE must have only `UCT_RC_IFACE_SEND_OP_FLAG_IFACE` flag set when kept in the free list.
1. Move setting status and `UCT_RC_IFACE_SEND_OP_STATUS` flag to the place where we're calling `op`'s `handler` (only there the status could be read).
2. Add `assert`s to make sure only `UCT_RC_IFACE_SEND_OP_FLAG_IFACE` is set when doing put/get for IFACE send ops.

UCT/IB/RC: Fix always having STATUS flag in iface send op

---

src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_iface.c
src/uct/ib/ud/base/ud_iface.h
src/uct/ib/ud/verbs/ud_verbs.c

Two new files were added to UD interface vfs node ("tx/available credits" and "rx/available credits"), which mirrors the current value of 
`uct_ud_iface_t->tx.available` and `uct_ud_iface_t->rx.available`.
Better debugging issues related to UD transport.

UCT/IB/UD: Add "available credits" data to UD iface vfs node

---

src/uct/ib/base/ib_iface.h
test/gtest/uct/ib/test_cq_moderation.cc

remove exp verbs cq moderation configurations.
exp verbs has been removed in PR#8158.
Align with the changes in PR#8158.

remove exp verbs cq moderation configs

---

src/uct/ib/ud/base/ud_inl.h

Fix error detection if new operations are scheduled.
See #8219.
See #8219..

UCT/IB/UD/GTEST: Fix error detection if new operations are scheduled [v1.13.x]

---

src/uct/ib/base/ib_iface.c

Remove unneeded `return` statement.
We could simply remove unneeded code.
Remove check for `IBV_QPT_UD` qp type and `return` statement..

UCT/IB: Remove unneeded return statement

---

src/uct/rocm/base/rocm_base.c
src/uct/rocm/ipc/rocm_ipc_ep.c

This pr brings three fixes from the master repository over to the v1.13 branch.
The three Prs are:
UCT/ROCM: increase max. number of hsa agents
(cherry picked from commit https://github.com/openucx/ucx/commit/7baac93d8a046a3e305ebb1247bfa7849076eb39)
UCT/ROCM: fix memory type detection 
(cherry picked from commit https://github.com/openucx/ucx/commit/4a876b592bb0154b26562f84de6e1517c7341815)
UCT/ROCM/IPC: use remote_agent if available
(cherry picked from commit https://github.com/openucx/ucx/commit/79ea940bebe9308366dd467567f6867ccdcd16b7)
All three commits are required for correct execution of rocm/ucx jobs.

UCT/ROCM: bring ROCm fixes over to v1.13 branch

---

src/uct/tcp/tcp_listener.c

Fix possible destroying of server EP twice.
TCP_SOCKCM endpoint could be destroyed twice:
- in `uct_tcp_listener_conn_req_handler` after handling failure from `ucs_async_set_event_handler`.
- in TCP_SOCKCM component destroy when destroying all endpoints stored in `ep_list`.
Move adding endpoint to `ep_list` after calling `ucs_async_set_event_handler`.

UCT/TCP/SOCKCM: Fix possible destroying of server EP twice

---

test/gtest/common/test.cc
test/gtest/common/test.h
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h
test/gtest/ucs/test_rcache.cc
test/gtest/uct/ib/test_cqe_zipping.cc
test/gtest/uct/ib/test_rc.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

- Makes `stats_activate/restore` methods members of the `test_base` class
- Moves compile-time `ENABLE_STATS` macro checks inside `stats_activate/restore` methods
Now `uct_test` end `ucp_test` implementations fully duplicates the `stats_activate/restore` methods. This duplication is reduced by moving these methods to common base class.

UCT/GTEST: Get rid of stats (de)activation related methods duplication

---

test/gtest/uct/ib/test_ud.cc
test/gtest/uct/ib/ud_base.cc
test/gtest/uct/ib/ud_base.h

Reproduce issue with error detection if new operations are scheduled
The PR adds test for the issue fixed in #8219.
1. Introduce error handling in test_ud.cc if required.
2. Add the test which post EP_CHECK and AM operations when a receiver was killed.

GTEST/UCT/UD: Reproduce issue with error detection if new operations are scheduled

---

src/uct/ib/base/ib_md.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fix indirect key registration by using correct MR type.
We register KSM with `atomic` access flag set. So, if default MR has relaxed ordering, we should use special MR with strict ordering.
Fixes:
```
[ RUN      ] dc_ud/test_ucp_sockaddr.force_close_during_rndv/0 <dc_x,ud_v,ud_x,mm/tag>
[New Thread 0x7fffedd81700 (LWP 7649)]
[Thread 0x7fffedd81700 (LWP 7649) exited]
[New Thread 0x7fffedd81700 (LWP 7650)]
[Thread 0x7fffedd81700 (LWP 7650) exited]
[New Thread 0x7fffedd81700 (LWP 7655)]
[     INFO ] Testing 1.1.27.2:0
[     INFO ] server listening on 1.1.27.2:60349
[1651871131.827338] [swx-ucx02:9673 :0]    ib_mlx5dv_md.c:457  UCX  ERROR   mlx5_bond_0: LRU push returned Unsupported operation
[swx-ucx02:9673 :0:9673]        rndv.c:166  Fatal: failed to pack rendezvous remote key: Unsupported …
```

UCT/IB: Fix indirect key registration by using correct MR type

---

test/gtest/ucp/test_ucp_tag_xfer.cc
test/gtest/uct/test_uct_ep.cc

Remove skipping of tests on DC due to DCI stuck issue.
DCI stuck issues shouldn't appear anymore.
1. Remove skip condition in `test_ucp_tag_xfer.generic_err_unexp`.
2. Remove skip condition in `test_uct_ep.disconnect_after_send`.

GTEST: Remove skipping of tests on DC due to DCI stuck issue

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/ud/accel/ud_mlx5.c

In case of failing to create QP to avoid segment fault
check QP existence before destroying it.
It's possible that it failed to create QP and there's no need to destory the un-existed QP.
Verify whethe the QP is created or not before destroying it.

UCT/IB: correct reclaim resources at failure cases

---

src/ucp/api/ucp.h

This PR adds a new public API function to query attributes for a UCP datatype. Currently, the packed size is the only attribute that can be queried.
The size of a message or data transfer is a performance-relevant information. Performance tools should be able to query this information. MPI provides `MPI_Type_size` to query the size of any MPI datatype.
A follow-up PR will implement `ucp_dt_query` in `src/ucp/dt/dt.c`. Unfortunately, the size of a UCP generic datatype is not available before it has been used in a UCP communication operation without more significant API changes.

UCP: Add API to query datatype attributes

---

AUTHORS
NEWS

preparation for new release
according to https://github.com/openucx/ucx/wiki/Release-process
@shamisp @tonycurtis @yosefe @edgargabriel  @brminich @hoopoepg @Artemy-Mellanox @dmitrygx @Akshay-Venkatesh pls take a look

v1.13.0 update NEWS and AUTHORS

---

src/uct/sm/scopy/knem/knem_iface.c

- due to last investigations KNEM transport has good
multithreading support which provides good
performance on runs with high PPN
- mark KNEM BW as dedicated

UCT/SHM/KNEM: mark knem BW as dedicated

---

src/ucp/proto/proto.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
test/gtest/ucp/test_ucp_proto.cc

Start an infrastructure for debugging protocol selection. The below diagram will be produced (rendered with graphviz) and it shows the estimated performance of each protocol stage and how it's based on low-level UCT performance and system topology.
If a wrong protocol is selected, it means one (or more) of the performance estimation stages is wrong.
[source](https://gist.github.com/yosefe/4a73f973fab024f978b3aa59f878b558#file-proto_node_demo-dot)

UCP/PROTO: Add performance tree data structure

---

src/uct/ib/rdmacm/rdmacm_listener.c
src/uct/tcp/tcp_listener.c
test/gtest/Makefile.am
test/gtest/uct/test_sockaddr.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Fix case when destroying listener in parallel with conn_req_cb invocation.
Reproduces and fixes the case when UCT listener is destroyed in parallel with conn_req_cb invocation.
1. Add gtest which emulates destroying of UCT listener and conn_req_cb invocation in different threads simultaneously.
2. Add `UCS_ASYNC_BLOCK`/`UCS_ASYNC_UNBLOCK` in RDMACM's and TCP_SOCKM's listener destroy functions.

UCT/CM: Fix destroying listener in parallel with conn_req_cb

---

src/ucp/core/ucp_worker.c
src/ucp/rndv/rndv.c
src/ucs/datastruct/mpool.c
src/ucs/datastruct/mpool.h
src/ucs/datastruct/mpool_set.c
src/ucs/memory/rcache.c
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/base/uct_mem.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/ib/base/ib_iface.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/base/rc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/scopy/base/scopy_iface.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_iface.c
src/uct/ugni/base/ugni_iface.c
src/uct/ugni/rdma/ugni_rdma_iface.c
src/uct/ugni/smsg/ugni_smsg_iface.c
src/uct/ugni/udt/ugni_udt_iface.c
test/gtest/ucp/test_ucp_stream.cc
test/gtest/ucs/test_mpool.cc

The change is to optimize mpool usage i.e. enable growing chunks including:
1).add grow_factor and max_chunk_size in ucs_mpool_data
2).set grow_factor to 1.0, max_chunk_size to 128m in ucs_mpool_params_reset(), hence most mpool use the two values as default
3).add gtest to check elem number in chunks
Mpool uses fixed size chunks, if to allocate big memory, there may be many small chunks. For underlying alloc functions using shmget(), so many chunks may exceed the system limit i.e. /proc/sys/kernel/shmmni (default value is 4096 on linux) and cause failure.
This implementation would enlarge chunk size when grow mpool by grow_factor which is put in by users calling ucs_mpool_init(), this parameter can be one meaning using fixed chunk size.

UCS/MPOOL: optimize mpool usage

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_reconfig.c
src/ucp/rma/put_offload.c
src/ucp/rndv/rndv_get.c

add abort impl for zcopy and reconfig protocols
- missed  functionality
- bugfix

UCP/PROTO: add abort impl for zcopy and reconfig protocols

---

.clang-format
src/ucp/proto/proto.c
src/ucp/proto/proto.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_ppln.c
src/ucs/arch/bitops.h
src/ucs/datastruct/array.h
src/ucs/datastruct/string_buffer.c
src/ucs/stats/stats.c
src/ucs/sys/compiler_def.h
test/gtest/ucs/test_datatype.cc
test/gtest/ucs/test_math.cc
test/gtest/ucs/test_string.cc

Preparation for adding protocols performance debug info.
The main goal is to get rid of `ucp_proto_select_range_t` and unify the performance envelope / stages calculation functions.
Each performance range will (in next PR) contain a performance "tree node" so better remove this extra hierarchy.
- Flatten performance range heirarchy by moving cfg_thresh from `ucp_proto_select_range_t` to `ucp_proto_config_t`
- Remove perf_range name field; it will be replaced by a performance tree node with detailed information
- `ucp_proto_perf_envelope_make()` now just calculates the envelope of linear functions and is not aware of perf ranges (for better abstraction)
- `ucp_proto_init_parallel_stages()` combines the logic of `ucp_proto_perf_envelope_append()` and `ucp_proto_common_add_perf_ranges()`
- …

UCP/PROTO: Refactor protocol initialization ranges

---

src/ucp/am/eager_multi.c
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c

In some cases the initialization of `initial_reg_md_map` field was missed

UCP/PROTO: Fix missing initial_reg_md_map

---

src/ucs/datastruct/mpool.c
src/ucs/datastruct/mpool.h
src/ucs/memory/rcache.c

Fix a deadlock in rcache with `UCX_LOG_LEVEL=debug`, with the following call sequence (top to bottom):
- malloc() (holding heap lock)
- munmap() 
- rcache memory hook handler 
- allocate invalidation element from rcache->mp 
- ucs_mpool_get 
- ucs_mpool_grow 
- ucs_debug 
- allocate TLS element (needed for logging) 
- malloc() ---> deadlock since heap lock is held by the first malloc

UCP/RCACHE: Avoid printing debug messages from rcache mpool

---

contrib/test_jenkins.sh

For keeping track of machine state and SW versions when tests pass/fail

CONTRIB/JENKINS: Dump machine state to build log

---

src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rdmacm/rdmacm_cm.c

Adding of syndrome output on the DEVX calls failures (in the places when it was missed).
Some places of DEVX failures don't print the syndrome now.
- Tested manually

UCT/IB/DEVX: Print missed syndromes at DEVX calls failures

---

src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h

Set QP `ts_format` to default to inherit timestamp format from the system configuration.
Some HCAs supports only "free running" or only "real time" ts format, and if `ts_format` configured to the "free running" value (0), but system supports only "real time" mode, QP creation fails. To avoid it we should set QP `ts_format` to default mode.
- Tested manually on ConnectX-6 Dx

UCT/IB/DEVX: Set QP ts_format to default

---

src/tools/info/Makefile.am
src/tools/info/build_info.c
src/tools/info/version_info.c

Adding runtime linked libraries version to the `ucx_info -v` output.
Now `ucx_info -v` prints only version of the library headers that were used to compile this tool. But printing runtime libraries version may be useful too.
For example if customer has ucx shared objects but old `ucx_info` binary, then it still will report only the old version.

TOOLS/INFO: Add runtime library version to ucx_info -v output

---

src/ucp/am/ucp_am.inl
src/ucp/core/ucp_am.c
src/ucp/proto/proto_am.inl
src/ucp/tag/probe.c

- del copy-pasted `ucp_am_pack_user_header` and move one to common `.inl` file
- del unused variable

UCP: minor code cleanup

---

src/ucs/datastruct/mpool.c
test/gtest/ucs/test_mpool.cc

add max_chunk_size check in ucs_mpool_init()
mpool may allocate a chunk not enough for even one element and code may get segv at corner case such as element size is less than alignment.
Calculate min_chunk_size and compare to max_chunk_size in ucs_mpool_init(), return fail creating the memory pool for invalid input max_chunk_size .

UCS/MPOOL: add max_chunk_size check

---

src/ucp/tag/offload.c

Use correct `max_iov` limit for tag offload rendezvous

UCP/HWTM/RNDV: Use correct max_iov for tag offload rndv

---

src/ucp/api/ucp.h
src/ucp/core/ucp_context.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_worker.c
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_ep.h
src/ucs/datastruct/arbiter.h
src/uct/base/uct_cm.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_iface.c

- remove some unnecessary code and var attributions.
- fix some typos and refine comments
clean part of code to make it easy to be understood

remove unused code and fix comment typos

---

src/ucp/proto/proto_select.c

Fix tracing of  protocols with user specified threshold
Need to update `max_prio_proto_id` only if the current proto has higher prio than max proto. Otherwise this leads to incorrect print on line 159 below

UCP/PROTOV2: Fix trace of configured protos

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/put_am.c
src/ucp/rndv/rndv_am.c
src/ucp/tag/eager_multi.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload/eager.c
test/gtest/ucp/test_ucp_am.cc

Fixed max fragment size calculation taking into account segment size.
Enabled new protocols for the appropriate test.

UCP/PROTO: Fix max fragment size calculation.

---

config/m4/cuda.m4

If Cuda headers are not found, but nvml headers are, should not set cuda_happy=yes

CONFIG/CUDA: Fix NVML check

---

src/uct/ib/dc/dc_mlx5_ep.c

Fix managing `FC_HARD_REQ` resend time.
`iface->tx.fc_hard_req_resend_time` is initialized only, but then never updated. So, it always leads to invoking of `uct_dc_mlx5_ep_fc_hard_req_progress`.
Backport of https://github.com/openucx/ucx/pull/8253

UCT/IB/DC: Fix managing FC_HARD_REQ resend time [v1.13.x]

---

src/uct/ib/dc/dc_mlx5.inl
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

Backport of https://github.com/openucx/ucx/pull/8289 to v1.13.x release branch.

UCT/IB/DC: Always schedule DCI allocation during FC_HARD_REQ progress [v1.13.x]

---

src/uct/ib/dc/dc_mlx5.inl
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

Always schedule DCI allocation during FC_HARD_REQ progress.
To fix not sending `FC_HARD_REQ` in case of no DCI is allocated for EP.
1. Update `uct_dc_mlx5_ep_schedule` and `uct_dc_mlx5_iface_schedule_dci_alloc` to accept `force` parameter.
2. If `force` specified in `uct_dc_mlx5_iface_schedule_dci_alloc`, schedule EP on DCI wait queue.
3. Pass `force=1` to `uct_dc_mlx5_ep_schedule` in `uct_dc_mlx5_ep_fc_hard_req_progress`.

UCT/IB/DC: Always schedule DCI allocation during FC_HARD_REQ progress

---

src/ucp/tag/tag_rndv.c

Enable rendezvous protocol for `tag_send_sync` in proto v2
Rendezvous protocol can be used (and is more efficient for large messages) with tag sync API

UCP/RNDV/PROTOV2: Enable rndv for tag sync sends

---

src/uct/api/uct.h

Extend uct_ep_flush API to allow remote completion
For implementing multi-rail RMA fence functionality
- added flag UCT_FLUSH_FLAG_REMOTE to notify UCT to update
remote buffers

UCT/EP_FLUSH: added flag for remote complete

---

src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Fix issues reported by clang and cuda 11.7 reported here https://github.com/openucx/ucx/issues/8278

UCT/CUDA: use right driver macro to log errors with drv fxns

---

src/uct/api/uct.h

Fix `uct_md_mem_reg`'s address parameter type.
`address` is passed as `in` instead of `out` parameter to `uct_md_mem_reg`.
`out` -> `in`.

UCT/API: Fix uct_md_mem_reg's address parameter type

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_single.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_rtr.c

Follow up on https://github.com/openucx/ucx/pull/8233 and https://github.com/openucx/ucx/pull/8264, populate the performance information tree for non-rendezvous protocols (split to reduce the PR size).

UCP/PROTO: Add performance tree data to non-rndv protocols

---

src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_devx.c

It's a part of bigger https://github.com/openucx/ucx/pull/8257 PR that adds ability to create CQ using DEVX. This patch is too big to be merged in one PR so it's one of the parts.
Creation CQ via DEVX requires passing non zero access mode to buffer allocation. This patch prepares `uct_ib_mlx5_md_buf_alloc` interface for the further using in CQ DEVX creation.

UCT/IB/MLX5: Add access mode argument to md buf allocation

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c

Some time ago all DEVX create/destroy/modify/general_cmd calls were already wrapped. But two destroy calls were missed for some reason. This patch fixes that.
P.S. Also if someone adds more `devx_obj_destroy` calls then coverity start fails with message that in these places return code of `devx_obj_destroy` isn't checked.

UCT/IB/DEVX: Wrap missed DEVX obj destroy calls to UCX calls

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/gdr/rocm_gdr_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
src/uct/ugni/base/ugni_md.c
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h

Introduced a new APIv2 function - `uct_mem_reg_v2`.
The `uct_mem_reg_v2` will close demand on extending memory registration routines. And it will extend already existing `uct_mem_dereg_v2` API function.
1. Define `uct_md_mem_reg_field_mask_t` which could be extended in the future by new fields.
2. Define `uct_md_mem_reg_params_t` which could be extended in the future by new fields.
3. Update `uct_md_mem_dereg_v2` to mention `uct_md_mem_reg_v2` along with `uct_md_mem_reg` and describe return value for consistency.
4. Declare `uct_md_mem_reg_v2` and add its implementation.
5. Move implementation of `uct_md_mem_reg` to `uct_md_mem_reg_v2`. And implement `uct_md_mem_reg` on top of `uct_md_mem_reg_v2`.
6. Define `UCT_MD_MEM_REG_FIELD_VALUE` auxiliary macro for getting fields from registration …

UCT/API: Introduce uct_mem_reg_v2

---

src/ucp/api/ucp.h

Fix indentation of `ucp_mem_advise_params` structure
Fields are not aligned as it required.
Change indentation of all fields of `ucp_mem_advise_params` structure to be 4 whitespace from the beginning of the structure.

UCP/API: Fix indentation of ucp_mem_advise_params

---

src/uct/rocm/copy/rocm_copy_md.c

commit 604c3b05879576a936932dc31bfd696c9dbe148c (Introduce uct_mem_reg_v2) accidentally renamed a parameter in
uct_rocm_copy_mem_rcache_reg(), breaking the compilation of the rocm/copy component. This commit fixes it.

UCT/ROCM/COPY: fix compilation problem

---

src/ucm/rocm/rocmmem.c
test/gtest/ucm/rocm_hooks.cc

Delay the memtype detection to rocm md. Otherwise the code path for the detection of rocm memory between ucm/rocm and uct/rocm can easily diverge and lead to unintended consequences.
Also have to clean up a testcase in gtest/ucm/rocm_hooks that failed after the modification.
Fixes an issue observed with a testcase on rocm 5.1 with older linux kernels.

UCM/ROCM: delay memtype detection to md's

---

src/ucp/proto/proto_debug.c

Show select flags (in addition to op_attr_mask) in protocols information

UCP/PROTO: Show protocol selection flags as part of info

---

src/uct/ib/base/ib_md.c

Fix a typo
ibv_reg_ms should be ibv_reg_mr

UCT/IB: ibv_reg_ms should be ibv_reg_mr

---

test/gtest/ucp/test_ucp_am.cc

Added separate test checking UCP_AM_SEND_FLAG_EAGER to avoid multiple checks of the same functionality in different test class.
Removed overlapping tests from test_ucp_am_nbx_eager_data_release which were added to check the intermediate steps of enabling new protocol infrastructure for UCP AM.
The changes reduces the number of redundant tests and the testing time as well.

GTEST/UCP: Separate test for AM eager flag.

---

contrib/test_jenkins.sh

- Do not waste worker resource in case of fatal error
- Possible solution for 100% CPU usage of AzurePlugin

CONTRIB/JENKINS: Do not freeze in case of fatal error

---

src/ucm/rocm/rocmmem.c
src/uct/rocm/copy/rocm_copy_iface.c
test/gtest/common/mem_buffer.cc
test/gtest/ucm/rocm_hooks.cc

This pr brings a couple of fixes for the rocm components from master to the v1.13 branch
Specifically:
GTEST/UCM/ROCM: Fix is_rocm_managed_supported gtest  
(cherry picked from commit  https://github.com/openucx/ucx/commit/a049c271a7bb494cde5f38cf7f66725e1f13aae7)
UCT/ROCM/COPY: implement estimate_perf function 
(cherry picked form commit https://github.com/openucx/ucx/commit/21ca9045d2f1cc837c125170c1724804b583f8ab)
UCM/ROCM: delay memtype detection to md's 
(cherry picked from commit https://github.com/openucx/ucx/commit/ee3aee9cf4893360196a98162bb2cec699c4c8d7)
fixes existing issues and makes rocm gtests pass.

GTEST/ROCM and UCM/ROCM: fixes for the v1.13 release

---

src/uct/ib/base/ib_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_def.h
src/uct/ib/ud/base/ud_iface.c

Fix bug - Wrong size of UD post receive buffers.
Fix inconsistency - seg_size should define the size of post recv buffers according to the description
Fix initialization of RX mpool elements size - can lead to confusion/memory waste in some transports (RC/DC).
Posting buffers with wrong size can cause unexpected behavior, buffer overrun when message is too big instead of "Not enough space" error code from HW
Fix UD seg size - Not meets seg_size definition, this creates a inconsistency in the meaning of seg_size between different transports.
Fix initialization of RX mpool elements size - Wrong element size can lead to confusion and a waste of memory.
1. Make sure preparation of rx wqe's is done properly, with the right size.
2. Change UD seg_size to meet seg_size definition.
3. Change RX …

UCT/IFACE - Bug fix, Wrong setting of post recv desc size and UD seg_size

---

src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/ud/accel/ud_mlx5.c

Fix CQ length calculation in UD/DC.
CQ length could be less than:
- QP_length in UD
- num_dcis * QP_length in DC
1. Calculate `tx_wqe_ratio` in case of DV by creating fake QP (UD or DCI) and getting `wqe_cnt / qp_init_attr.cap.max_send_wr`.
2. Remove `wqe_size` calculation in case of DEVX; use `UCT_IB_MLX5_MAX_BB` value which is `4` to calculate QP length.

UCT/IB: Fix CQ length calculation in UD/DC

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/ud/accel/ud_mlx5.c

Getting all required CQ related information during DEVX calls from the UCX structure (instead of IBV strucuture).
It's a part of bigger https://github.com/openucx/ucx/pull/8257 PR that adds ability to create CQ using DEVX. This patch is too big to be merged in one PR so it's one of the parts.
If CQ created using DEVX then there is no IBV CQ at all, so all information about CQs should be discovered from the common `uct_ib_mlx5_cq_t` entity.
- Move `uct_ib_mlx5_get_cq` right after the CQ creation (inside `create_cq` function pointer) to make all CQ related info accessible earlier. It is required at least for XRQ creation via DEVX.
- Pass UCT CQ structures to all related APIs and get all required information from them.

UCT/IB/DEVX: Using UCX CQ structure during DEVX calls

---

contrib/test_jenkins.sh

```bash
2022-06-06T16:28:55.4988449Z + ../contrib/configure-devel --prefix=/__w/1/s/install --without-java--with-iodemo-cuda --enable-gtest
2022-06-06T16:28:55.6078392Z configure: WARNING: unrecognized options: --without-java--with-iodemo-cuda
```

TEST/JENKINS: fixes missed space in configure line

---

NEWS

Update NEWS file for RC2 
Full list of changes since RC1:
- ff64ffad7 AZP: remove HWI hosts from testing
- 7e2df9171 UCT/CUDA: use right driver macro to log errors with drv fxns
- 28b0f30b5 UCT/IB/DC: Always schedule DCI allocation during FC_HARD_REQ progress
- f92b1727c TEST/UCT: Remove atomic access from invalidate tests
- 5cec39013 UCT/IB: Fix indirect key registration by using correct MR type
- a6c5a472f UCT/IB/DC: Fix managing FC_HARD_REQ resend time

NEWS: 1.13.0 update for RC2

---

test/gtest/ucp/test_ucp_am.cc

Combined `test_ucp_am_nbx_dts` tests with overlapping functionality.
The changes reduces the number of redundant tests and the testing time as well.
Addressed https://github.com/openucx/ucx/pull/8323#discussion_r901125577 .

GTEST/UCP: Reduced number of tests in AM datatype test class.

---

contrib/test_jenkins.sh
src/ucs/Makefile.am
src/ucs/algorithm/string_distance.c
src/ucs/algorithm/string_distance.h
src/ucs/config/parser.c
test/apps/test_fuzzy_match.py
test/gtest/ucs/test_algorithm.cc
test/gtest/ucs/test_config.cc

Unrecognized user vars will be fuzzy matched to provide some alternatives
User may want to fix the mistyped env vars.
We calculate levenstein distance between a given user env var and all UCX configuration vars.
Strings that have a small enough distance will be added to the suggestions list.
Current distance threshold is 3.

UCS/CONFIG_PARSER: Unrecognized user vars will be fuzzy matched to provide some alternatives

---

test/apps/iodemo/run_io_demo.sh

run_io_demo.sh can kill iodemo process from other test
grep by IODEMO_ROLE (it's applicable only for process which launch via run_io_demo.sh

AZP: Kill own iodemo process in CI

---

src/tools/perf/lib/ucp_tests.cc

Simplify send command selection in PERF utility.
Remove overcomplicated double switch-case for selecting send command.
Merge two switch-cases for TAG, TAG_SYNC, STREAM and AM commands.

TOOLS/PERF: Simplify send command selection

---

src/ucs/sys/sock.h
src/uct/tcp/tcp_sockcm_ep.c

Fix printing peer address in TCP_SOCKCM.
Before:
```
[1656422715.765136] [ldev-doca-15-bf:744208:a]   tcp_sockcm_ep.c:648  UCX  DEBUG fd 27: remote_data: (field_mask=15) dev_addr: <invalid address family> (length=6), conn_priv_data_length=47
```
After:
```
[1656424136.071887] [ldev-doca-15-bf:751731:a]   tcp_sockcm_ep.c:648  UCX  DEBUG fd 27: remote_data: (field_mask=15) dev_addr: 192.168.101.3:38158 (length=6), conn_priv_data_length=47
```
Use `saddr` instead of `remote_data.dev_addr`, because `saddr` is `sockaddr`, but `remote_data.dev_addr` is `in_addr`/`in6_addr`.

UCT/TCP_SOCKCM: Fix printing peer address

---

src/ucp/rndv/proto_rndv.c

Fix protocol v2 performance issue where cuda_ipc is not selected because it's "remote system" distance is considered lower than it actually is
The issue is that the order in rpriv->sys_distance array is according to lanes order, but it should actually be according to the order of bits in sys_dev_map. This wrong order caused a mixup between the system distance of cuda_ipc and mlx5_0. This fix is to first generate the map, and then populate the distance array according to bits order.
cc @Akshay-Venkatesh 
Before:
After:

UCP/PROTO/RNDV: Fix order in sys_distance array

---

src/uct/ib/dc/dc_mlx5.inl
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

Fix "timeout waiting for replies" in IO-demo (30 iterations passed successfully with the fix).
Happened because all DCIs were acquired by endpoints for sending FC hard requests, but did not actually send them, because no UCT-API operations were done on these endpoints.
1. Partially revert changes from #8169 and #8289 PRs.
2. Invoked `uct_dc_mlx5_ep_check_fc` from `uct_dc_mlx5_ep_fc_hard_req_progress`'s loop over all EPs added to FC hash.
UCT user may not have pending operations scheduled, but FC_HARD_REQ could be posted and then resend.
If DC transport will acquire DCI, it couldn't be used at all if user doesn't post new operations and no pending operations scheduled.
The following scenario was observed:
`FC_HARD_LIMIT` was reached on DC endpoint and `FC_HARD_REQ` packet was sent. But it …

UCT/IB/DC: Resend FC_HARD_REQ instead of scheduling EP on waitq

---

src/uct/sm/mm/base/mm_iface.c

Updated default bandwidth value for memory mapper transports.
Adjusted default bandwidth to enhance protocol selection.
Before the changes get_zcopy over knem transport was selected instead of rkey_ptr over xpmem.

UCT/SM/MM: Updated default bandwidth value for mm transports.

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_rtr.c

As preparation for extending these functions, since they are used for protocol initialization flow
- Rename the functions
- Move without code changes to proto_init.c

UCP/PROTO: Move memreg_time and buffer_copy_time to proto_init.c

---

src/ucp/rndv/rndv.c

Fix copying user's memory handle on a receiver.
User's memory handle isn't used for a receive operation and new memh is registered, since `md_map` of user's memh doesn't correlate with MD indices of RNDV lanes.
Apply `UCS_BIT` to `ucp_ep_md_index(ep, lane)` value.

UCP/RNDV: Fix copying user's memory handle on a receiver

---

src/tools/perf/lib/uct_tests.cc

Allow testing cuda_copy get_short performance (with loopback mode)

TOOLS/PERF: Add test case for uct_ep_get_short()

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup.h
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_cm.h
src/ucp/wireup/wireup_ep.c
src/ucp/wireup/wireup_ep.h
test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_worker.cc

Always pack TL resource indices into CM private data.
TL resources must be packed into CM private data to make sure that `ucp_wireup_init_lanes()` uses correct destination resource indices to check config intersections.
1. `dst_rsc_indices` stored in CM wireup endpoint are by `UCP_NULL_RESOURCE`s when client's EP was created.
2. `dst_rsc_indices` are set to the proper values on a client after receiving CM private data from a server.
3. `dst_rsc_indices` will be used to check config intersections during WIREUP_MSG phase, if `UCX_CM_USE_ALL_DEVICES=y`
1. Update `ucp_ep_create_server_accept()` to use `ucp_cm_address_pack_flags()` for unpacking remote worker address to make sure the same flags are used for packing/unpacking CM private data.
2. Update `UCP_ADDRESS_PACK_FLAGS_CM_DEFAULT` to …

UCP/WIREUP: Always pack TL resource indices into CM private data

---

src/uct/ib/dc/dc_mlx5_ep.c
test/gtest/uct/ib/test_dc.cc
test/gtest/uct/ib/test_rc.cc
test/gtest/uct/ib/test_rc.h

Fix handling of return value of checking FC.
The if condition should be reverted.
Replace `((status == UCS_OK) || (status == UCS_ERR_NO_RESOURCE))` by `((status != UCS_OK) && (status != UCS_ERR_NO_RESOURCE))`.

UCT/IB/DC: Fix handling of return value of checking FC

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_worker.c
src/ucp/rndv/rndv.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.h
src/ucs/config/parser.c
src/ucs/config/parser.h
src/uct/ib/base/ib_md.c
test/gtest/ucs/test_config.cc

Define minimal size of fragment when splitting message over multiple lanes
To not split the message into small chunks (which degrades performance)

UCP/RNDV: Define min chunk size for multi-rail

---

src/ucs/datastruct/array.h
test/gtest/ucs/test_datatype.cc

For error flow of adding performance stage to an array: if something failed after adding the array element, this method allows to remove it

UCS/ARRAY: Add method to remove last array element

---

src/ucp/proto/proto_debug.c

Display correctly performance estimations of < 1MBps (could happen with very small fragments such as atomic operations)

UCP/PROTO/DEBUG: Support kB/s bandwidth in performance tree node

---

src/ucp/am/eager_single.c
src/ucp/rma/put_offload.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload/eager.c
src/uct/base/uct_iface.h
src/uct/ib/base/ib_iface.c

- Short protocol having lower latency should be implemented as UCT performance estimation and not assumptions on UCP layer
- Current IB latency estimation is actually the minimal value, so need to increase the cost of bcopy/zcopy rather than adding negative latency to short.

UCP/PROTO/IB: Improve performance estimations for short/bcopy/zcopy

---

src/ucs/sys/compiler_def.h
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c

- Remove the assumption that cuda_copy source is HOST and destination is DEVICE
- Set right CPU overhead/latency for sync/async operations

UCT/CUDA: Improve performance estimation

---

src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

Dispatch pending ops to fix DCI reordering.
Fixes #8381.
DCI/TX arbiters should be dispatched when resources become available.
1. Update `test_dc_flow::enable_entity` to progress pending operations when DCIs become available.
2. Remove `UCT_DC_MLX5_IFACE_IGNORE_DCI_WAITQ_REORDER` flag and code places which set/check it, because it's no longer needed.

GTEST/UCT/DC: Dispatch pending ops to fix DCI reordering

---

src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5.inl
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc
test/gtest/uct/ib/test_rc.cc
test/gtest/uct/ib/test_rc.h

Resend FC_HARD_REQ instead of scheduling EP on waitq.
To fix "timeout waiting for replies" errors seen on DC when running io-demo on large scale.
Include commits from https://github.com/openucx/ucx/pull/8348 and https://github.com/openucx/ucx/pull/8351.
No merge conflicts.

UCT/IB/DC: Resend FC_HARD_REQ instead of scheduling EP on waitq [v1.13.x]

---

src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/am/rndv.c
src/ucp/am/ucp_am.inl
src/ucp/core/ucp_am.c
src/ucp/core/ucp_request.h
src/ucp/proto/proto_am.inl

refactor ucp_request_t::send::msg_proto::am
this is a preparation to re-initialization of protocol related part of request
from pending queue in case when ep is reconfigured during wireup.
replace union of user header and reg_desc with structure

UCP/AM: refactor ucp_request_t::send::msg_proto::am

---

src/tools/perf/perftest.c

Fix the name of `setup_sock_rte_loobkack` function.
It should be `loopback` instead of `loobkack`.
Replace `setup_sock_rte_loobkack` by `setup_sock_rte_loopback`.

TOOLS/PERF: Fix function name

---

src/ucp/wireup/select.c

Update lane bandwidth calculation in wireup.
Currently, we use the minimum of local and remote iface bandwidths to calculate lane scores. 
This can result in the same score for all lanes if the local (remote) ifaces have a lower bandwidth
than all remote (local) ifaces. This can lead to undesirable lane selections because the NIC-device
affinity on the remote (local) side is ignored.
Add weighted sum of the local and remote iface bandwidths when calculating lane bandwidth for lane scores.

UCP/WIREUP/SELECT: Update wireup lane bandwidth calculation

---

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/rma/rma_send.c
src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_atomic.cc
test/gtest/ucp/test_ucp_memheap.cc
test/gtest/ucp/test_ucp_memheap.h
test/gtest/ucp/test_ucp_rma.cc

Add support of user's memh for RMA operations.
Passing a pre-allocated memory handle could be used by some users to not rely on RCACHE or for XGVMI implementation in the future which always requires passing a memory handle to operations.
1. Use `ucp_send_request_set_user_memh()` in `ucp_rma_request_init()` to set user's memory handle.
2. Introduce new variant in RMA gtests and update do_put/do_get send functions to accept `memh` to test passing user' memory handle.

UCP/RMA/GTEST: Add support of user's memh for RMA operations

---

src/ucp/core/ucp_am.c
test/gtest/ucp/test_ucp_am.cc

Add missing release of RNDV receive descriptor for AM receive operation.
Fixes receive descriptor leak of AM RNDV operation for 0-lengh message.
```
[1657279884.508973] [swx-ucx01:45001:0]           mpool.c:55   UCX  WARN  object 0x8ebd40 {flags:0xc0 length:50 payload_offset:0 release_offset:0 name:am_rndv_process_rts} was not returned to mpool ucp_am_bufs
```
Invoke `ucp_recv_desc_release` for 0-length RNDV descriptors from `ucp_am_recv_data_nbx` if the operation isn't issued from AM callback context.

UCP/CORE: Add missing release of RNDV receive descriptor

---

src/ucs/sys/sock.c

Allow using IPv6 loopback address for TCP transport.
Loopback with IPv6 wasn't available in the list of supported resources returned from TCP.
Update `ucs_netif_get_addr` by removing `IN6_IS_ADDR_LOOPBACK(&saddr6->sin6_addr)` check.

UCS/SYS: Allow using IPv6 loopback address

---

src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
test/gtest/ucp/test_ucp_proto.cc

Support replacing node's children - will be used by rendezvous protocol to represent the remote system performance estimation

UCP/PROTO/DEBUG: Extend performance tree infra

---

src/ucp/am/eager_multi.c
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto_common.h
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_multi.h
src/ucp/proto/proto_multi.inl
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_put.c
src/ucp/tag/eager_multi.c
test/gtest/ucp/test_ucp_tag_match.cc

Fixes Proto v2 perf degradation for large message sizes in comparison with the old protocol.
Calculating such size for the first fragment to ensure proper alignment for the following fragments.

UCP/PROTO/RNDV: added alignemt for get zcopy

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/rndv/rndv_mtype.inl
src/ucp/wireup/select.c
src/uct/sm/scopy/knem/knem_md.c

Fixed memory handle registration.
`UCT_MD_MEM_FLAG_HIDE_ERRORS` flag should prevent from failing memory handler registration process in case of memory registration fail on a memory domain.
`ucp_memh_get_slow` should perform memory handler registration process with `UCT_MD_MEM_FLAG_HIDE_ERRORS` flag.

UCP/CORE: Fixed memory handle registration.

---

src/uct/ib/base/ib_md.c

- sync build configuration and IB ops references
fixes https://github.com/openucx/ucx/issues/8412

UCT/IB/BUILD: sync build and references - v1.13

---

src/ucs/sys/sock.c
test/gtest/ucs/test_sock.cc

- print scope_id value for IPv6 address
- useful for loopback addresses

SOCK/DEBUG: print scope_id for IPv6 address

---

src/ucm/util/sys.c

Potential fix for https://github.com/openucx/ucx/issues/8415
cc @omor1

UCM/SYS: Don't use inline assembly for brk syscall

---

config/m4/sysdep.m4

When LTO is enabled, malloc hook test can fail because ptr is unused and eliminated.
Per https://github.com/openucx/ucx/pull/8417#issuecomment-1202151666
@cc omor1

CONFIG/BUILD: Fix malloc hook detection with LTO

---

bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java

Disable link local listener bindings.
Fails on TCP CM on link-local addresses
@hoopoepg please check on your PR

JUCX: disable link local listener bindings.

---

contrib/test_jenkins.sh
src/uct/tcp/tcp_iface.c

When using ports from range 33000..60000, it can collide with TCP local (client) port numbers used by various processes on the system, for example NFS client. This can cause random CI failures.

CONTRIB/JENKINS: Move TCP port range to not collide with ip_local_port_range

---

src/ucp/rndv/rndv.c
test/gtest/ucp/test_ucp_sockaddr.cc

Fix RNDV GET_Zcopy initialization of user's memh.
`req->send.rndv.lanes_map_all` contains indices of array RNDV GET Zcopy lanes.
Go through `rndv_req->send.rndv.lanes_map_all` and lookup lane from `ucp_ep_config(ep)->rndv.get_zcopy.lanes` array.

UCP/RNDV/GTEST: Fix RNDV GET_Zcopy initialization of user's memh

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
src/ucp/dt/datatype_iter.inl
src/ucs/memory/rcache.inl
test/gtest/ucp/test_ucp_mmap.cc

This way ucp_mem_unmap will match corresponding ucp_mem_map and will be able to unroll operations that should be unrolled (i.e. allocations, registrations of MDs which shouldn't be cached)
ucp_mem_map() won't return memh from rcache but will wrap it in unique temporary memh.

UCP/MM: Make ucp_mem_map return unique memh

---

src/uct/ib/mlx5/ib_mlx5.h

- fixed macro arg names to fit code guidelines (to eliminate
variables shadowing)

IB/MLX5: fixed macro arg

---

test/gtest/uct/test_sockaddr.cc

- in case if rdmacm failed to resolve peer for some reason
it could crash which prevents continue testing
- added error handler to report issue without test abort

GTEST/RDMACM: fixed potential crash

---

contrib/test_jenkins.sh

Fix CI recent failures of failing to start listener
Separate port range for TCP iface and server listener.
The following job failure (with debug prints) shows it's the issue:
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=48484&view=logs&j=087a5e36-b289-5cda-d2a1-de6f38127104
```
+ taskset -c 0 ./examples/ucp_hello_world -m host -p 11513
(Not all processes could be identified, non-owned process info
will not be shown, you would have to be root to see it all.)
INFO: UCP_HELLO_WORLD mode = 0 server = (null) port = 11513, pid = 417
Failed to open server socket
Failed to server_connect
+ sleep 15
[1659904161.218133] [swx-rdmz-ucx-althca:417  :0]     ucp_context.c:1890 UCX  INFO  Version 1.14.0 (loaded from /scrap/azure/agent-01/AZP_WORKSPACE/2/s/build-test/src/ucp/.libs/libucp.so. …
```

TEST/JENKINS: Set different port ranges for listener and TCP iface

---

src/uct/ib/ud/base/ud_ep.c
test/gtest/uct/ib/test_ud_ds.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Fix assertion for path_index to allow cross-path connections.
Fixes assertion on a system where a IB device has the number of LID path bits = 1, i.e. `lmc == 0`:
```
ud_ep.c:840  Assertion `ctl->conn_req.path_index == ep->path_index' failed: creq->path_index=1 ep->path_index=0
```
1. Add gtest to reproduce the issue.
2. In case of RoCE - check path_index only if `iface->super.config.roce_path_factor > 0`.
3. In case of IB - do `path_index % path_bits_count` before checking them.

UCT/IB/UD: Fix assertion for path_index to allow cross-path connections

---

src/ucp/wireup/select.c
src/ucp/wireup/wireup.h
test/gtest/ucp/test_ucp_wireup.cc

Support optional flags for select criteria
Rndv will select DC even if only one capability of (put/get) is supported.

UCP/WIREUP: Support optional flags for select criteria

---

src/ucp/core/ucp_worker.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/base/rc_ep.h
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h
src/uct/ib/rc/verbs/rc_verbs_ep.c

- enabled UCT_IFACE_FEATURE_FLUSH_REMOTE feature: iface will
produce flush(remote) op only if feature was created with
correcponding flag
- added FLUSH_REMOTE feature for iface_open when RMA
functionality is requested

UCT/FLUSH: enabled FLUSH_REMOTE feature

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/accel/ud_mlx5_common.h

- updated ctrl segment fill by AV data: now it is filled in DC scope
(not in common scope as previous)
- allows to reduce RP DC structure size

DC/AV: refactoring for ctrl seg fill

---

src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/am/rndv.c
src/ucp/am/ucp_am.inl
src/ucp/dt/datatype_iter.inl
src/ucp/proto/proto.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_reconfig.c
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/eager_multi.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload/eager.c
src/ucp/tag/tag_rndv.c
src/ucp/wireup/wireup.c
src/ucs/sys/stubs.c
src/ucs/sys/stubs.h

Add UCP request clean and reinit after wireup:
infrastructure and basic protocols
EP might be reconfigured during wireup, then initially selected protocols are not applicable for pending requests and should be re-selected, so the requests also should be re-inisialized.
- add `ucp_proto_t::clean`
- restart requests from pending replay:
- clean
- init
- send
- support AM user header release. description can be found [here](https://github.com/openucx/ucx/pull/8173#discussion_r928840502)

UCP/PROTO/AM: ucp_proto_t::reset for eager protocols and support new user header release API

---

src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/configure.m4
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_iface.c
src/uct/ib/ud/base/ud_iface.h
src/uct/ib/ud/base/ud_inl.h
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_wireup.cc

CQ creation via DEVX API + using DEVX event channel for handling completion events.
This way of creation CQ allows to support more FW features (e.g. enhanced CQE zipping)
Before moving this PR out of draft state, several "preparation" requests were merged:
- #8297
- #8299
- #8300
- #8302
At this moment union with both verbs and DEVX cq representation was created inside `uct_ib_mlx5_cq_t`. There is no any practical sense of keeping verbs part there at this moment but it's there to save the consistency of storing corresponding objects on the same abstraction level. The question of removing verbs representation from that union can be discussed separately.

UCT/IB/DEVX: Create CQ using DEVX

---

src/ucp/wireup/select.c

For score calculation, take avg of latencies(local/remote) instead of max.
When 2 or more ifaces get the same score on both sides, then selection will depend on the order.
This will cause endpoint reconfig issue.
Using avg instead of max, will result in different scores, which will make the highest score to be selected.

UCP/WIREUP: For score calculation, take avg of latencies(local/remote) instead of max.

---

contrib/test_jenkins.sh
src/uct/tcp/tcp_iface.c

Port CI fixes of failing to start TCP listener because the port is in use from master branch
- Port #8423 
- Port #8436
- Fixed one merge conflict in test_jenkins.sh

Port CI port range fixes to v1.13.x

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h

Introduce `uct_md_mem_attach` UCT API function.
The function will be used to bind remote memory handle with local memory handle using `shared_mkey_buffer`.
Introduce `uct_md_mem_attach` in UCTv2.

UCT/API: Introduce uct_md_mem_attach

---

src/ucs/arch/aarch64/cpu.h

This patch aligns UCX with kernel subsystem:
https://patchwork.kernel.org/project/linux-rdma/patch/0-v1-c5dade92f363+11-mlx5_io_stop_wc_jgg@nvidia.com/
The patch streamlines the code quite a bit. Since DGH is a hint
instruction, on platforms that do not support the DGH extension the hint gets
translated to no-op.
It is safe to remove TX2 branch since anyways it is translated to  no-op.
It is also safe to remove DMB barrier because on older implementations the
buffer gets retired before 64B write is completed. Alternatively, it can
be retired on timeout and on most platforms it will be faster than DMB.

ARCH: Adding support for Data Gathering Hint

---

src/ucs/debug/debug.c

The PTR macro is missing on the latest Arch linux.
Replace the cast `(PTR)` with `(void *)` in `debug.c`.
The `PTR` macro is not defined in the latest Arch Linux bfd headers.
See reported error in the comment in https://aur.archlinux.org/packages/openucx
`PTR` is probably a pointer to a specific type. Since we are casting here, casting to `void *` should work.

UCS/DEBUG: replace PTR with void *

---

src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/base/ud_def.h
src/uct/ib/ud/base/ud_ep.h
src/uct/ib/ud/base/ud_inl.h
src/uct/ib/ud/verbs/ud_verbs.c

Cleanup setting of packet_type.
To make reuse common code and remove unneeded functions.
1. Remove `uct_ud_neth_set_am_id` as it is unused.
2. Remove `uct_ud_neth_set_type_put` as it is used only once in UD/verbs code and could be replaced.
3. Introduce `uct_ud_neth_set_packet_type` and use it instead of `uct_ud_neth_set_type_am` and `uct_ud_neth_set_type_put`.

UCT/IB/UD: Cleanup setting of packet_type

---

test/gtest/uct/test_tag.cc

- there is build issue when gtest is built with -O1 optimization
flag:
make[3]: Entering directory `/auto/mtrswgwork/sergeyo/vs-projects/ucx/test/gtest'
CXX      uct/gtest-test_tag.o
In file included from uct/test_tag.cc:8:0:
/labhome/sergeyo/ucx/src/uct/api/uct.h: In member function ‘virtual void test_tag_tag_hold_uct_desc_Test::test_body()’:
/labhome/sergeyo/ucx/src/uct/api/uct.h:2725:21: error: inlining failed in call to always_inline ‘void uct_iface_release_desc(void*)’: indirect function call with a yet undetermined callee
UCT_INLINE_API void uct_iface_release_desc(void *desc)
^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
from ./common/googletest/internal/gtest-port.h:264,
from ./common/googletest/internal/gtest-internal.h:40,
from ./common/googletest/gtest.h:62, …

GTEST: fixed build with -O1 optimization

---

src/ucp/wireup/wireup.c

Print EP configuration index which is used by EP.
Printing EP configuration index is useful to investigate which configuration is used by EP as a final one. Currently, it isn't possible to understand.
Update trace in `ucp_wireup_remote_connected` to print `ep->cfg_index`.

UCP/WIREUP: Print EP configuration index which is used by EP

---

src/ucp/wireup/select.c

Fix printing missing capabilities during transport selection.
Before:
```
[1660634021.508599] [swx-dgx02:12994:0]          select.c:451  UCX  TRACE   addr[0] tcp: no get
[1660634021.508601] [swx-dgx02:12994:0]          select.c:451  UCX  TRACE   addr[1] tcp: no getno get
[1660634021.508602] [swx-dgx02:12994:0]          select.c:451  UCX  TRACE   addr[2] tcp: no getno getno get
[1660634021.508603] [swx-dgx02:12994:0]          select.c:451  UCX  TRACE   addr[3] tcp: no getno getno getno get
[1660634021.508605] [swx-dgx02:12994:0]          select.c:451  UCX  TRACE   addr[4] tcp: no getno getno getno getno get
[1660634021.508606] [swx-dgx02:12994:0]          select.c:451  UCX  TRACE   addr[5] tcp: no getno getno getno getno getno get
```
After:
```
[1660635804.675492] [swx-dgx02:20696:0] …
```

UCP/WIRUEP: Fix printing missing capabilities during transport selection

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h

Implementation of `ucp_proto_t::reset` for eager protocols
Depends on https://github.com/openucx/ucx/pull/8386
The method was intoduced in https://github.com/openucx/ucx/pull/8386 and should be implemented for all protocols

UCP/PROTO/AM: impl ucp_proto_t::reset for eager protocols

---

NEWS
configure.ac
ucx.spec.in

update NEW for UCX v1.13.1 release

NEWS: 1.13.1 update

---

src/ucp/wireup/select.c

Fixes AM BW lane score calculation
To avoid error like:
```
[ RUN      ] rcx/test_ucp_am_nbx_seg_size.single/7 <rc_x/prereg/proto/reply>
[     INFO ] seg size 1024 data size 512
[1661087849.623034] [swx-rain04:148009:0]          wireup.c:404  UCX  ERROR   ep 0x7f9aa897f000: no remote ep address for lane[2]->remote_lane[2]
[1661087859.654742] [swx-rain04:148009:0]       ucp_test.cc:301  UCX  ERROR request 0x4746750 completed with error Destination is unreachable
```
which happens because of asymmetrical lanes selection by peers
Take into account remote segment size, which can be smaller than the local value.
note: different segment sizes are only supported with UCP worker address v2.

UCP: Fix AM BW lane score calculation

---

src/uct/ib/dc/dc_mlx5.c

Fix handling of `AUTO` value for `FC_HARD_REQ_TIMEOUT`.
If `UCX_DC_MLX5_FC_HARD_REQ_TIMEOUT=auto` is set, then fc_hard_req_timeout will be not a `5s` as expected to be, it will be the value of `UCS_ULUNITS_AUTO` which is `(unsigned long)-2`.
1. Define `UCT_DC_MLX5_FC_HARD_REQ_TIMEOUT` macro and set value to `5s`.
2. Set ``UCT_DC_MLX5_FC_HARD_REQ_TIMEOUT`` as a default value for `FC_HARD_REQ_TIMEOUT` configuration parameter.
3. Update DC's `uct_iface_open()` to handle the case if config's fc_hard_req_timeout is `UCS_ULUNITS_AUTO` and set the `fc_hard_req_timeout` to `ucs_str_to_memunits(UCT_DC_MLX5_FC_HARD_REQ_TIMEOUT)`.

UCT/IB/DC: Fix handling of AUTO value for FC_HARD_REQ_TIMEOUT

---

src/ucp/am/eager_single.c
src/ucp/am/rndv.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_types.h
src/ucp/proto/proto_am.c
src/ucp/proto/proto_am.inl
src/ucp/proto/proto_single.inl
src/ucp/rma/amo_basic.c
src/ucp/rma/amo_offload.c
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/put_offload.c
src/ucp/rma/rma.inl
src/ucp/rma/rma_basic.c
src/ucp/rma/rma_send.c
src/ucp/rma/rma_sw.c
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/eager_single.c
src/ucp/tag/eager_snd.c
src/ucp/tag/offload.c
src/ucp/tag/offload/eager.c
src/ucp/tag/tag_rndv.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup.h
test/gtest/common/test_obj_size.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Max number of lanes for EP is now increased from 5 to 8.
Increase limit of EP lanes.
In order to maintain fast path performance, we add the new 3 lanes in ep_extension struct.
The new lanes will be considered slow path, and will be used only for slow path protocols.

UCP/CORE: Support up to eight EP lanes

---

src/ucp/api/ucp.h
src/ucp/api/ucp_compat.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_rkey.c

Introduce `ucp_memh_pack` API function
`ucp_memh_pack` API function was introduced to replace already existing `ucp_rkey_pack` to make it extendable and support packing SHARED memory key in the future.
1. Introduce `ucp_memh_pack` and `ucp_memh_buffer_release`.
2. Implement `ucp_rkey_pack` and `ucp_rkey_buffer_release` through `ucp_memh_pack` and `ucp_memh_buffer_release`.
3. Deprecate `ucp_rkey_pack` and `ucp_rkey_buffer_release`.
4. Use `ucp_memh_pack` and `ucp_memh_buffer_release` instead of `ucp_rkey_pack` and `ucp_rkey_buffer_release` in perftest/gtest/UCP code.

UCP/API: Introduce ucp_memh_pack API function

---

bindings/java/src/main/java/org/openucx/jucx/ucp/UcpWorker.java
bindings/java/src/main/native/worker.cc
bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java

Implement the methods `UcpWorker.arm()` and `UcpWorker.getEventFD()` in JUCX, which call the native methods `ucp_worker_arm()` and `ucp_worker_get_efd()`.
Currently, polling a worker with JUCX using the wakeup mechanism is only possible by first calling `UcpWorker.waitForEvents()`, which blocks until the next event on that worker occurs, and then calling `UcpWorker.progress()`. However, this does not work well for programs, which use multiple workers, since it is not possible to call `UcpWorker.waitForEvents()` on multiple workers at the same time. A solution for this problem is to use an epoll file descriptor (e.g. with the help of [this](https://github.com/helins/linux-epoll.java) library), but for doing so, it is necessary to get each worker's event file descriptor and re-arm each …

JUCX: Implement arm() and getEventFD() in UcpWorker

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h

Added uct_ep_connect_to_ep_v2 method and corresponding data type
Allow implementation of extended connect_to_ep
Added extendable data set to pass into connect_to_ep routine

UCT/API: added uct_ep_connect_to_ep_v2 method

---

src/ucp/am/eager_single.c
test/gtest/ucp/test_ucp_am.cc

- Fix a bug in proto V2 "short" send function that can cause segmentation fault 
- Check why gtest missed it and make sure it won't happen again
- In "ucp_am_eager_short_proto_progress_common" iov array is initialized with size 3, but when sending AM
with user header and reply EP iov list contains 4 elements.
- @rakhmets found that gtest missed it because of the order we are running the tests. The test first sends message without header, and the message with the header is sent after, when wireup is completed, therefore the message with the header is sent using old proto, ucp_am_send_short, and there the iov list length is correct. 
- Fix the iov length to be 4 instead of 3.
- Decide how to change the tests so we will not have another miss.

UCP/PROTOV2/EAGER/SHORT: Bug fix - iov array is initialized with a wrong length

---

src/tools/profile/read_profile.c
src/ucm/util/reloc.c
src/ucs/sys/sys.h
test/apps/sockaddr/sa_tcp.cc
test/gtest/ucs/test_vfs.cc

Fix deprecation warnings like:
```
In file included from /var/tmp/portage/sys-cluster/ucx-1.10.0_rc5/work/ucx-1.10.0-rc5/src/ucs/sys/sys.h:29,
from mmap/install.c:21:
/usr/include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp]]
1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
|  ^~~~~~~
```
Bug: https://bugs.gentoo.org/832966
Signed-off-by: Sam James <sam@gentoo.org>## What
architecture, approach, …

UCM: Fix deprecated <sys/fcntl.h> includes

---

config/m4/go.m4
configure.ac

configure scripts need to be runnable with a POSIX-compliant /bin/sh.
On many (but not all!) systems, /bin/sh is provided by Bash, so errors
like this aren't spotted. Notably Debian defaults to /bin/sh provided
by dash which doesn't tolerate such bashisms as '=='.
This retains compatibility with bash.
Fixes configure warnings/errors like:
```
checking for go... yes
./configure: 26781: test: xyes: unexpected operator
```
Signed-off-by: Sam James <sam@gentoo.org>
Remove Bashisms from the build system which cause issues
when `/bin/sh` is not Bash, but is a POSIX-compliant shell.
The build may be misconfigured or fail with a POSIX-compliant-but-not-Bash
/bin/sh.

CONFIG: Fix bashisms in configure.ac, config/m4/go.m4

---

test/apps/sockaddr/sa_util.h

Closes: https://github.com/openucx/ucx/issues/8347
Signed-off-by: Sam James <sam@gentoo.org>
Add a missing include for `uint32_t`.
Fixes a build failure with GCC 13, as transient internal includes were changed in the compiler.

TEST/SOCKADDR: Add missing <cstdint> include for GCC 13

---

test/gtest/ucp/test_ucp_tag_xfer.cc

Fix generic_dt start/finish counters check
Restart send request might call extra start/finish callbacks

GTEST: fix generic_dt start/finish counters check

---

src/ucp/core/ucp_ep.c
src/uct/tcp/tcp.h
src/uct/tcp/tcp_cm.c
src/uct/tcp/tcp_ep.c

Add failed EP status tracking.
Fix status returned when TCP disconnected.
For consistency.
To make value returned via UCP EP error callback and values returned from following operations be the same.
To make value returned to client when server closed be same with RDMA and TCP protocols.

UCT/TCP: Fix status returned when disconnected

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/wireup/select.c

Fix rma_bw lanes selection for different memory types. 
No need to search rma_bw lanes for different memory types on the same memory domains to avoid asymmetrical lanes selection  (e.g. when one node has nv_pee_mem loaded, while the other does not) 
Partially revert #7683

UCP: Fix rndv lanes selections for memtypes

---

test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/ucp_test.h

Moved memory preregistration variant of test from base class to inherited classes.
To get rid of redundant test variants.

GTEST/UCP: Moved prereg variant to inherited classes.

---

test/gtest/common/test_perf.h
test/gtest/ucp/test_ucp_perf.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag_offload.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

skip not implemented UCP/proto_v2 functionality
missed functionality found by `UCX_PROTO_ENABLE=y`, regular testing will be covered by https://github.com/openucx/ucx/pull/8509

GTEST: skip not implemented UCP/proto_v2

---

src/ucp/api/ucp.h
src/ucp/core/ucp_rkey.c

Make `ucp_memh_pack()`'s/`ucp_memh_buffer_release()`'s `params` as `const`
To align with other API functions which accept `params` as `const`, e.g. `ucp_mem_map()`
Add `const` qualifier to `params` for `ucp_memh_pack()`, `ucp_memh_pack_internal()`, `ucp_memh_buffer_release()`.

UCP/API: Make memh_pack/memh_buffer_release params const

---

src/uct/rocm/Makefile.am
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_cache.c
src/uct/rocm/copy/rocm_copy_cache.h
src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/copy/rocm_copy_ep.h
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.h

introduce the ability to use hsa_amd_memory_async_copy() for short operations of the rocm/copy uct component
locking the local host memory and using hsa_amd_memory_async_copy() can improve the performance of short operations. This requires a local cache to avoid constantly locking/unlocking host memory.
Note: this is currently more relevant for the device-to-host direction.

UCT/ROCM use hsa async_copy for short operations

---

src/uct/ib/dc/dc_mlx5_ep.c
test/gtest/uct/ib/test_dc.cc
test/gtest/uct/ib/test_rc.cc
test/gtest/uct/ib/test_rc.h
test/gtest/uct/ib/ud_base.cc
test/gtest/uct/ib/ud_base.h
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Don't allocate a new sequence number for resending an existing `FC_HARD_REQ` packet.
Not reusing a sequence number which was allocated for FC entry existed in FC hash could lead to always dropping `FC_PURE_GRANT` packets with "old" sequence numbers if a peer is not fast enough to send `FC_PURE_GRANT` back.
This PR fixes IO-demo's "timeout waiting for replies", because server can't send replies, since FC window is exhausted and not renewed by receiving `FC_PURE_GRANT` with an expected sequence number.
1. If `kh_put` completed with `UCS_KH_PUT_KEY_PRESENT`, don't assign new FC sequence number. just reuse the existing one from a FC entry returned from `kh_put`.
2. Add useful assertions to make sure FC hash is used correctly, i.e. a FC entry should exist in FC hash only if endpoint's `fc_wnd` …

UCT/IB/DC: Don't allocate new sequence number for resending existing FC_HARD_REQ

---

src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c

the md_attr_v2 commit broke the rocm compilation. This commit fixes the compilation part.
Note: gtest generates even with this fix a segfault in rocm_copy/test_p2p_rma_madvise, I will investigate that later this week.

UCT/ROCM: make rocm components compile again

---

src/uct/api/uct.h
src/uct/api/uct_def.h
src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/ugni/base/ugni_md.c

Introduce shared mkey buffer in UCT.
Shared mkey buffer will be packed by `uct_md_mkey_pack_v2`.
1. Introduce `UCT_MD_FLAG_SHARED_MKEY` MD capability flag.
2. Update `uct_md_mkey_pack_v2` to support packing shared mkey.
3. Introduce `shared_mkey_packed_size` and `global_id` MD attributes.
4. Update all transports to set `shared_mkey_packed_size` and `global_id`.

UCT/API: Introduce exported mkey buffer

---

src/ucp/wireup/select.c

- enabled RMA BW lane selection in case if context was created with UCP_FEATURE_RMA enabled

UCT/WIREUP: enable RMA BW lanes on RMA_FEATURE

---

test/gtest/ucp/test_ucp_mmap.cc

Set `RCACHE_ENABLE` parameter prior creating entities.
It should be done prior creating ucp_context to apply changes.
Move `modify_config("RCACHE_ENABLE", "n")` to be set prior calling `ucp_test::init()`.

GTEST/UCP: Set RCACHE_ENABLE parameter prior creating entities

---

src/uct/api/uct.h
src/uct/api/v2/uct_v2.h

This PR changes exported MKEY UCT API.
#8422 API changes have been merged, but some issues were found.
We need to declare that a local memory key is "exportable" when it's created. Doing it when it's packed is already too late.
1. `UCT_MD_MEM_FLAG_EXPORT` registration flag wasn't added.
2. `UCT_MD_MKEY_PACK_FLAG_EXPORT` can be removed, because `UCT_MD_MEM_FLAG_EXPORT` flag can be saved during memory key registration and used when packing memory key.
3. Description of `uct_md_mkey_pack_v2`'s `mkey_buffer` is not correct.
1. Fix comment formatting in `enum uct_md_mem_flags`, add `UCT_MD_MEM_FLAG_EXPORT` flag.
2. Remove `CT_MD_MKEY_PACK_FLAG_EXPORT` from `uct_md_mkey_pack_flags_t` enumeration.
3. `remote` -> `memory`.

UCT/API: Get rid of EXPORTED MKEY pack flag and add EXPORT mkey registration flag

---

src/uct/base/uct_md.c

Handle `exported_mkey_packed_size` and `global_id` fields in `uct_md_attr_v2_copy`.
They should be handle to make sure copying of MD attributes from temporary attributes to user's ones work correctly in `uct_md_attr_v2`.
Invoke `UCT_MD_ATTR_V2_FIELD_COPY` for `exported_mkey_packed_size` and `global_id` field in `uct_md_attr_v2_copy` auxiliary function.

UCT/BASE: Handle exported_mkey_packed_size and global_id field in uct_md_attr_v2_copy

---

test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h
test/gtest/uct/test_mm.cc
test/gtest/uct/test_p2p_mix.cc
test/gtest/uct/test_stats.cc
test/gtest/uct/test_zcopy_comp.cc
test/gtest/uct/uct_p2p_test.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Use uct_md_query_v2() instead of uct_md_query().
To make sure that tests have an access to new fields introduced in `uct_md_query_v2`'s attributes.
Find `uct_md_attr_t` and replace by `uct_md_attr_v2_t` and adopt its usage.

GTEST/UCT: Use uct_md_query_v2() instead of uct_md_query()

---

src/ucp/api/ucp.h
src/ucp/dt/dt.c
test/gtest/ucp/test_ucp_dt.cc

Implementation of the the routine `ucp_dt_query` according to PR #8120. Currently, the only datatype attribute to query is the packed size.
The size of a message or data transfer is a performance-relevant information. Performance tools should be able to query this information similar to `MPI_Type_size` to query the size of any MPI datatype
For _contig_ data types, the return value of `ucp_contig_dt_elem_size()` provides the element size.
For generic data types, a field `packed_size` has been added to `ucp_dt_generic_t`, which is set with the user-defined pack routine. When the size of the generic data type is queried, the value of this field is used. All other data types are not supported and `UCS_ERR_INVALID_PARAM` is returned as `ucs_status_t`.
A unit tests verifies the expected …

UCP: Implementation of routine to query datatype attributes

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h

Fixed backward compatibility issue
- due to compatibility issue updated uct_ep_connect_to_ep_v2 routine parameters
- added uct_ep_connect_to_ep_param_field_t enum to add ep_address length
- iface address will not be used in ep_connect_to_ep routine

UCT/API: fixup for uct_ep_connect_to_ep_v2

---

src/uct/ib/rc/accel/rc_mlx5_iface.c

Check the value of `UCX_RC_MLX5_TM_SEG_SIZE` during RC/DC iface creation.
In rcx and dc transport segments are limited by `UCT_IB_MLX5_MP_RQ_BYTE_CNT_MASK` value (in `uct_rc_mlx5_iface_common_poll_rx`). If the segment is bigger the behavior is undefined, because wrong length is reported to UCP when tag message arrives. Need to fail iface creation if the segment is bigger than allowed value

UCT/RC/DC: Check tag seg size during iface creation

---

src/ucs/arch/cpu.c

CPU bandwidth for ZHAOXIN is missing
The function ucs_cpu_get_memcpy_bw can be out of array range.
```
double ucs_cpu_get_memcpy_bw()                                                  
{                                                                               
return ucs_cpu_est_bcopy_bw[ucs_arch_get_cpu_vendor()];                     
}  
```
Add bandwidth for it.

UCS: Add missing ZHAOXIN cpu bandwith

---

buildlib/pr/main.yml

removed swx-infra on docker hub, move to ucx proj

AZP: change path to docker images - v1.13.x

---

examples/ucp_client_server.c

fix ucp_client_server finalization:
- close EP in flush mode on client side
- acknowledge delivery from server side
local send operation completion does not guarantee delivery as well as local flush
@ivankochin

EXAMPLES: fix ucp_client_server finalization

---

src/tools/info/tl_info.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.h
src/uct/api/uct.h
src/uct/sm/mm/base/mm_md.h

Introduce `UCT_COMPONENT_FLAG_RKEY_PTR` and use it instead of `UCT_MD_FLAG_RKEY_PTR`
`uct_rkey_ptr()` function is invoked for component (not memory domain),  so the flag indicating support for this API needs to be checked/present on component rather than md

UCT/UCP/API: Add RKEY_PTR flag on component

---

src/uct/rocm/base/rocm_base.c
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/ipc/rocm_ipc_ep.c
src/uct/rocm/ipc/rocm_ipc_md.c

1. Cleanup handling of remote_addr vs. iov->buffer in rocm_copy_ep_zcopy.
For put operations, src has to be iov->buffer and dst has to be remote_addr, for get operations exactly the other way around.
2. the rkey does not necessarily contain the registration information of the host buffer, it might be the rkey of the device buffer. Hence, we need to check for that and locally 'lock' the host buffer using hsa_amd_memory_lock() if the provided rkey belongs to a device buffer.
3. Introduce the ability to perform host-to-host memcpy in the component, since the rocm/copy component seems to be selected for host-to-host operations in send-to-self scenario as well.
Fixes issues observed in send-to-self scenarios with Open MPI + UCX + rocm memory

UCT/ROCM: send-to-self fixes

---

src/ucp/api/ucp.h

Replace `UCP_MEM_MAP_EXPORT` by `UCP_MEMH_PACK_FLAG_EXPORT`.
This change makes possible packing the same memory handle as RKEY or EXPORTED memory handle.
1. Remove `UCP_MEM_MAP_EXPORT` from `ucp_mem_map()`'s flags.
2. Add `UCP_MEMH_PACK_FLAG_EXPORT` to `ucp_memh_pack()`'s flags.

UCP/API: Replace UCP_MEM_MAP_EXPORT by UCP_MEMH_PACK_FLAG_EXPORT

---

src/uct/api/uct.h
src/uct/api/v2/uct_v2.h

Replace `UCT_MD_MEM_FLAG_EXPORT` by `UCT_MD_MKEY_PACK_FLAG_EXPORT`.
This change makes possible packing the same memory handle as RKEY or EXPORTED memory handle.
1. Remove `UCT_MD_MEM_FLAG_EXPORT` from `uct_md_mem_reg()`'s flags.
2. Add `UCT_MD_MKEY_PACK_FLAG_EXPORT` to `uct_md_mem_pack_v2()`'s flags.

UCT/API: Replace UCT_MD_MEM_FLAG_EXPORT by UCT_MD_MKEY_PACK_FLAG_EXPORT

---

debian/copyright

See format definition in the URL in the first line of this file.
The file has generally a format similar to debian/control (inspired by mail headers).
No functional change. Fixes formatting for whatever tools that may attempt to figure out the licensing data automatically from this file.

BUILD/DEBIAN: Fix format of debian/copyright

---

src/uct/sm/mm/base/mm_iface.c
src/uct/sm/mm/base/mm_iface.h
src/uct/sm/mm/posix/mm_posix.c

Check that the size of /dev/shm is not "too small" according to UCX perspective and disqualify its md to prevent the TL from opening.
Machine running UCX can limit the size of /dev/shm. This can result in insufficient memory for the TL resources, for example receive buffers pool. 
In uct_posix_md_query check that the size of /dev/shm is bigger than the min value expected by UCX.
A configurable parameter (UCX_POSIX_SHM_MIN_SIZE) was added to the UCX configuration. it's enforce shm minimum size. Default value is set to 16MB.

UCT/MD/QUERY: Check that the size of dev/shm is not too small

---

debian/control.in
debian/ucx-cuda.install
debian/ucx-gdrcopy.install

Move gdrcopy-dependent modules independent of the CUDA ones: it is  possible to have just CUDA without gdrcopy.
First commit slightly edits the descriptions of the other two binary deb packages. The second commit adds the new binary deb package ucx-gdrcopy and moves files to it from the original ucx-cuda package.

A separate gdrcopy binary Deb package

---

src/tools/info/proto_info.c
src/tools/info/ucx_info.c
src/tools/info/ucx_info.h
src/ucp/api/ucp.h
src/ucp/core/ucp_mm.c

- Basic test for dmabuf support: `ucx_info -m 1m,cuda` is expected to show that memory is registered with IB devices
- Extend ucp_mem_print_info() function to accept memory type in addition to size. Since it's passed as a string, this change is backward compatible.
- Update ucx_info tool with correct help message and change variable names

UCP/API/TOOLS: Specify memory type when allocating with ucx_info tool

---

src/tools/perf/perftest.c

Remove incorrect rte context initialization (added by mistake in #5013)

TOOLS: Fix perftest init for external RTE

---

contrib/test_jenkins.sh
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/rma/flush.c
src/ucp/wireup/wireup.c

add testing variable to force restart after wireup
test coverage

UCP/PROTO: add testing variable to force restart after wireup

---

src/uct/rocm/base/rocm_base.c
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_md.c

this pr is adding the `uct_rocm_copy_mem_alloc` and `uct_rocm_copy_mem_free` functions for use but the ucx_perftest.
Users who are running ucx_perftest on 1 node, will need to set ROCR_VISIBLE_DEVICES to different devices to ensure that the devices used are different per process
ucx_perftest has not been working with the ROCM components

UCT/ROCM: added memory allocation functions

---

src/ucp/rndv/proto_rndv.c

fix RNDV/ATS completion
finish callback was not invoked for generic DT

UCP/PROTO: fix RNDV/ATS completion

---

src/ucs/sys/sys.c
src/ucs/sys/sys.h
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/ib/base/ib_device.c
src/uct/tcp/tcp_iface.c
test/gtest/ucp/test_ucp_wireup.cc

Consider PCIe BW for TCP iface BW calculation.
OFED query does not consider PCIe BW value, so we add it to get the full BW calculation for TCP iface.

UCT/TCP: Consider PCIe BW for TCP iface BW calculation

---

src/uct/sm/mm/base/mm_iface.c

Bug caused by #8508 disqualified xpmem
fixes [#8597](https://github.com/openucx/ucx/issues/8597)
Disqualification of MD was based only on mem allocation capabilities and not take into account mem registration capabilities.
That cause xpmem to be disqualified.
Check for mem registration capabilities. Only devices without mem registration capabilities nor mem allocation capabilities will be disqualified.
*This test is relevant only for POSIX/XPMEM/SYSV

UCT/MD/QUERY: Bug Fix - Accidentally disqualified xpmem

---

src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_devx.c

Fix NVIDIA internal issue [3139906](https://redmine.mellanox.com/issues/3139906)
When creating a DevX QP, attach it to the default port counters, so QP events would be reflected through sysfs.
Create a dummy QP, modify it to INIT, and query its counter_set_id. Cache the counter_set_id per port.

UCT/IB/DEVX: Set counter_set_id for DevX QP and DCT

---

src/ucp/dt/datatype_iter.inl
src/ucp/proto/proto_common.c

do not reinitialize datatype iterator on request restart 
there were design decision do not cleanup iterator on request reset

UCP/PROTO: do not reinit iterator on restart request

---

src/tools/info/tl_info.c
src/uct/api/uct.h
src/uct/api/uct_def.h
src/uct/api/v2/uct_v2.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

As part of dmabuf support, add dambuf registration (import) support to UCT API and implement it for IB transport
- API: Add `UCT_MD_FLAG_REG_DMABUF` md capability and `dmabuf_fd`,`dmabuf_offset` params to memory registration.
- IB: Check dmabuf support on startup, and pass dmabuf fd and offset to internal registration functions
This PR complements #8581 
cc @Akshay-Venkatesh

UCT/API/IB: Add support for dmabuf registration

---

src/ucp/tag/eager_single.c

fix eager_zcopy_single seg size
failure in test_ucp_address_v2.diff_seg_sizes with `UCX_PROTO_ENABLE=y`

UCP/PROTO: fix eager_zcopy_single seg size

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_request.h
src/ucp/core/ucp_types.h
src/ucp/rndv/rndv.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/uct/ib/dc/dc_mlx5.h
test/gtest/common/test_obj_size.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Add support for a max of 16 lanes per ucp_ep. 
Allow more lanes to be selected, and thus better performance and utilization of resources.
In order to preserve small EP memory signature, we dynamically allocate uct_eps array in ep extension.

UCP/CORE: 16 lanes support

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

While looking at debug log in #8604, turned out the message `UCX  DEBUG mlx5dv_open_device(mlx5_2) failed: Protocol not supported` is printed incorrectly.

UCT/IB/MLX5: Fix error message

---

docs/source/faq.md
src/tools/info/tl_info.c
src/uct/api/uct.h
src/uct/api/uct_def.h
src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/rocm/base/rocm_base.c

- Support dmabuf export - querying dmabuf_fd and dmabuf_offset
- Extend uct_mem_query() API
- Implemend dmabuf query for cuda_copy transport
- Add dmabuf capabilities print to ucx_info
Replaces #7847

UCT/API/CUDA/INFO: Implement dmabuf export

---

src/ucp/rma/amo_send.c

fix access to freed request
```
[ RUN      ] shm_ib/test_ucp_atomic32.post/4 <shm,ib,cuda_copy,rocm_copy/device/proto>
==31280== Invalid read of size 4
==31280==    at 0x58C73C8: ucs_mpool_put_inline (mpool.inl:82)
==31280==    by 0x58C73C8: ucp_request_put (ucp_request.inl:219)
==31280==    by 0x58C73C8: ucp_proto_request_send_op (proto_common.inl:261)
==31280==    by 0x58C73C8: ucp_atomic_op_nbx_inner (amo_send.c:218)
==31280==    by 0x58C73C8: ucp_atomic_op_nbx (amo_send.c:159)
==31280==    by 0x866C1C: test_ucp_atomic<unsigned int>::do_atomic(ucp_atomic_op_t, unsigned long, void*, ucp_rkey*, void*, ucp_request_param_t&) (test_ucp_atomic.cc:202)
==31280==    by 0x866E03: test_ucp_atomic<unsigned int>::post(unsigned long, void*, ucp_mem*, void*, ucp_rkey*, void*) (test_ucp_atomic.cc:63) …
```

UCP/PROTO: fix valgrind issues

---

src/uct/ib/rc/accel/rc_mlx5_iface.c

Fix initialization of DC iface with HWTM but without MPXRQ  
To avoid errors, like
```
rc_mlx5_common.c:863  Assertion `iface->tm.mp.num_strides == 1' failed
==== backtrace (tid:   5649) ====
0 0x000000000005f382 uct_rc_mlx5_init_rx_tm()  /labhome/mikhailb/wgit/ucx-tmp/src/uct/ib/rc/accel/rc_mlx5_common.c:863
1 0x000000000008083d uct_dc_mlx5_init_rx()  /labhome/mikhailb/wgit/ucx-tmp/src/uct/ib/dc/dc_mlx5.c:665
2 0x0000000000036d81 uct_rc_iface_t_init()  /labhome/mikhailb/wgit/ucx-tmp/src/uct/ib/rc/base/rc_iface.c:701
3 0x0000000000055865 uct_rc_mlx5_iface_common_t_init()  /labhome/mikhailb/wgit/ucx-tmp/src/uct/ib/rc/accel/rc_mlx5_iface.c:783
4 0x000000000008a996 uct_dc_mlx5_iface_t_init()  /labhome/mikhailb/wgit/ucx-tmp/src/uct/ib/dc/dc_mlx5.c:1402
5 0x000000000008a996 …
```

UCT/DC: Fix HWTM initialization without MPXRQ

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_rkey.c
src/ucp/proto/proto_common.c
src/ucp/rndv/proto_rndv.c

Support dmabuf in UCP by querying dmabuf fd and providing it to memory registration function

UCP/MM/PROTO: Register memory using dmabuf with protov2

---

test/gtest/uct/test_md.cc

fix memory leak in test_md.exported_mkey

GTEST: fix memory leak in test_md.exported_mkey

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

- fixed crash on configuration where MLX5 MD with KSM is not initialized

MD/MLX5: fixed crash on flush remote cleanup

---

src/ucp/rndv/proto_rndv.c

fix remote MD map in RNDV protocols
CM lane does not have dedicated resource (`UCP_NULL_RESOURCE`)

UCP/PROTO: fix remote MD map in RNDV protocols

---

src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rc/accel/rc_mlx5_ep.c

Do not take `max_rd_atomic` value from the `iface->config` when connecting RC QP. Always take `max_rd_atomic` from device attributes instead. 
When dc interface creates command QP for tag offload it creates it as RC, but its config contains `max_rd_atomic` value relevant for DC. And this value can be different for RC and DC.
Fixes the following issue when running UCX with tag offload enabled:
`ib_mlx5_dv.c:416  UCX  ERROR MBR mlx5dv_devx_obj_modify(opcode=0x503) failed, syndrome 0x6da61b: Remote I/O error`

UCT/DC: Fix max_rd_atom for cmd_qp connect

---

src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/ib/rdmacm/rdmacm_cm.h

Fix leak if some operations failed after `uct_ib_md_open_common()`.
If some operations failed after `uct_ib_md_open_common()`, then we don't roll back changes done by `uct_ib_md_open_common()`.
1. Introduce `uct_ib_md_close_common()` which performance reverse actions which could be done by `uct_ib_md_open_common()`.
2. Update `uct_ib_mlx5_devx_md_open()` and `uct_ib_mlx5dv_md_open()` to invoke `uct_ib_md_close_common()` if some operations failed after `uct_ib_md_open_common()` was invoked.

UCT/IB: Fix leak if some operations failed after uct_ib_md_open_common()

---

src/ucm/cuda/cudamem.c
src/ucm/cuda/cudamem.h
src/uct/cuda/base/cuda_md.c
test/gtest/ucm/cuda_hooks.cc

Adding support for CUDA virtual/stream-ordered memory with `cudaMallocAsync`.
For proper CUDA virtual memory identification, add required hooking for `cudaMallocAsync`. Although this is currently adding support for `cudaMallocAsync`/`cudaMallocAsyncFromPool`, the stream-ordered memory allocator is part of the [Virtual Memory Management in CUDA](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html), which is why its special case was named `UCS_MEMORY_TYPE_CUDA_VIRTUAL` for the time being.
This change was successfully tested with Dask+UCX-Py using bounce buffers setting `UCX_RNDV_FRAG_MEM_TYPE=cuda` and demonstrates to behave correctly so far, also providing similar performance to CUDA managed memory under the same conditions.

UCM/CUDA: Add support for CUDA virtual memory with `cudaMallocAsync`

---

buildlib/pr/distro.yml

Fix [test failures](https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=52689&view=logs&j=bbc87450-d2e1-51f2-95ed-08aac0f92777&t=d334a637-21ef-514c-a2c1-f970364dfd02) on swx-rain machines after merging https://github.com/openucx/ucx/pull/8527

TEST/COMPAT: Set UCX_IB_ROCE_LOCAL_SUBNET=y to fix connectivity

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fixes #8637 because leak of flush_mr
`UCT_IB_MLX5_MD_FLAG_KSM` might be reset if atomic mr is not supported

UCT/IB/MLX5: fix leak of flush mr

---

src/ucp/api/ucp.h

fixed typo in tag_recv_nbx description

UCP/API: fixed typo in tag_recv_nbx

---

src/ucp/proto/proto_select.c

Changed top node name in proto selection tree.
Using of `frag` is confusing because `fragment` is already used in protocol terminology. E.g. single/multiple fragment bcopy/zcopy protocols.

UCP/PROTO: Changed top node name in proto selection tree.

---

test/gtest/ucp/test_ucp_mmap.cc

handle proto_enable configuration if it's set externally

GTEST/UCP: handle proto_enable if it's set externally

---

debian/rules.in

The names of packages provided by NVidia in CUDA don't seem to follow the standard required by Debian (package per library), and therefore shlibdep creates dependencies that are too strict: on libnvidia-compute-515 instead of the actual name of the library.
So this commit fixes the generated dependency.
It seems that the name of the library, provided by all relevant packages, is "libnvidia-ml1". Use the standard dependency name of <specific> | <provides>.

BUILD/DEBIAN: Use dep libnvidia-ml1 for ucx-cuda

---

config/m4/mpi.m4
configure.ac
test/mpi/Makefile.am

Test that shmemcc is present as the part of MPI install.
Fixing #8593 
The makefile should not assume that every MPI install comes with SHMEM.
Check that shmemcc is part of MPI install, if not disable the build.

TEST/CONFIG: Fixes #8593

---

buildlib/pr/distro.yml
buildlib/pr/tests.yml
examples/ucp_client_server.c
examples/ucp_util.h
test/gtest/ucp/test_ucp_tag_xfer.cc

Fix some recent CI issues
- Fix return code check: tests could fail but CI still passed
- Fix ucp_client_server error on Bluefield
- Fix ucp_hello_world compat failure on swx-rain machines
- Temporarily disable a failing test with valgrind

AZP: fix return code

---

src/ucp/wireup/wireup_cm.c

Wrong multiple indirection of uct_pending_purge_callback_t argument
Will cause segmentation fault if ucp_request_purge_enqueue_cb is called with non empty pending queue.
Remove wrong indirection.

UCP/WIREUP_CM/BUG: Bug Fix - Wrong multiple indirection in ep cleanup

---

src/uct/cuda/gdr_copy/gdr_copy_iface.c

Prefer zero-copy over gdrcopy for sender side with protov2

UCT/GDRCOPY: Use worst-case latency and bandwidth estimation

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/rma/amo_offload.c
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/get_offload.c
src/ucp/rma/put_offload.c
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/eager_multi.c
src/ucp/tag/offload/eager.c
src/ucs/sys/stubs.c
src/ucs/sys/stubs.h

improve not implemented reset/abort stubs in UCP protov2
for better logging in case of failure

UCP/PROTO: improve not implemented reset/abort stubs

---

config/m4/compiler.m4

Extend the warnings that will be shown as errors during compilation using icc.
Intel compiler reports unknown/unsupported compilation flags as warnings and therefore compilation still ends successfully. This logic prevents autoconf `AC_LINK_IFELSE` function from detection such compilation flags. The warning №10006 is already turned to workaround this issue. But there are different compiler options related warnings that can be reported by ICC and absence of support such options still cannot be detected by autoconf.
For example:
```
icc: command line warning #10148: option '-Wno-unused-label' not supported
```
Turn all warnings to errors.

BUILD/FLAGS: Turn 'unsupported option' ICC command line warning to error

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c

remove already included files to reduce preprocess time.

UCT/IB: reduce preprocess time without reading included files

---

test/gtest/ucp/test_ucp_wireup.cc

Temporary disable select_transport_rma_bw test.
Prevent occasional failure on CI.

TEST/UCP: Temporary disable select_transport_rma_bw test

---

src/ucp/rndv/rndv.c

fix a corner case for calculating the rkey_index in case the md_index is not part of the md_map.
Fixes issue https://github.com/openucx/ucx/issues/8627

UCP/CORE: fix corner case for rkey_index

---

buildlib/az-helpers.sh
buildlib/pr/go/go-test.yml

Signed-off-by: artemry-nv <artemry@nvidia.com>
Fix for instabilities in env module loading (more likely caused by unstable autofs).
Regular UCX CI failures.
Added missing env module init step. Added redundant env module files reading just to force autofs update corresponding file structures.

AZP: fixed env module issue (W/A for unstable rdmz network/autofs)

---

src/ucp/dt/datatype_iter.inl

Fix assertion formatting
Before
`datatype_iter.inl:527 ...:  iterator mem_type=host cache_md_map=0x1cmd_map=0x19`
After
`datatype_iter.inl:527 ...: iterator mem_type=host cache_md_map=0x1c md_map=0x19`

UCP: Fix assertion formatting

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_worker.c
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_select.c
src/ucp/wireup/select.c
src/uct/base/uct_iface.c
src/uct/tcp/tcp_iface.c

Improve protocol information output by printing endpoint locality information
Replaces #7902 
Example output:
```
+----------------+--------------------------------------------------------------------------------------------+
| mpi self cfg#0 | tagged message by ucp_tag_send*() from host memory                                         |
+----------------+-------------------------------------------+------------------------------------------------+
|        0..8184 | eager short                               | self/memory                                    |
|    8185..37142 | eager copy-in copy-out                    | self/memory                                    |
|     37143..inf | (?) rendezvous zero-copy read from remote | 68% on knem/memory and 32% on rc_mlx5/mlx5_0:1 | …
```

UCP/EP/PROTO: Print endpoint locality with protov2 select info

---

src/ucp/core/ucp_context.c
src/ucs/config/global_opts.c
src/ucs/config/parser.c
src/ucs/config/parser.h
src/ucs/config/ucm_opts.c
src/uct/base/uct_cm.c
src/uct/base/uct_component.c
src/uct/base/uct_component.h
src/uct/base/uct_md.c
test/apps/test_fuzzy_match.py
test/gtest/ucs/test_config.cc

Filter out not loaded config tables for unused vars message
Avoid displaying wrong env var suggestions

UCS/CONFIG: Filter out not loaded config tables for unused vars message

---

src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c

Fixing #8601 - counter_set_id field was set in a wrong place for RC / DCI QP
Fix NVIDIA internal issue [3139906](https://redmine.mellanox.com/issues/3139906)

UCT/IB/MLX5: Set counter_set_id during modify 2INIT instead of create

---

src/ucp/core/ucp_mm.c

UCP: Fix rcache dump function

---

src/ucp/core/ucp_rkey.c
src/ucs/debug/log_def.h

Reduce SW overhead for rkey unpack

UCP/RKEY: Avoid TLS log indent access in release mode

---

src/ucp/rndv/rndv_rkey_ptr.c

Now `dt_cleanup` can be called twice during `rndv/rkey` proto execution. This patch removes the redundant `dt_cleanup` call from `ucp_proto_rndv_progress_rkey_ptr` while other one from `ucp_proto_rndv_ats_progress` is still on the place.
Tested with xpmem manually.

UCP/RKEY: Remove double dt cleanup from rndv rkey proto

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c

Cache host memory alloc md index during context creation
will be checked by 2-stage pipeline protocol to decide what MD keys need to be packed to RTR rkey
ref #8668

UCP: Cache alloc md idx on context

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/core/ucp_rkey.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv.c

Add skip MD map to UCP rkey unpack routine
Preparation for 2-stage pipeline protocol with proto v2. With this protocol RTR packs shm or posix rkey, so that the sender can attach remote fragment memory and copy directly to it. Also this protocol caches unpacked key to avoid expensive memory attach for every operation. Thus, we do not need to unpack such keys in the common code rndv code - the corresponding protocol will take care of that.
ref #8668

UCP: Add skip_md_map to UCP rkey_unpack

---

src/ucp/am/eager_multi.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_debug.c
src/ucp/tag/eager_multi.c

Removed extra parenthesis.
Added prefix to distinguish multi- and single-fragment protocols.

UCP/PROTO: Fixed proto info output.

---

contrib/test_jenkins.sh
test/mpi/Makefile.am
test/mpi/test_memhooks.c

Fix recent test failures like this:
```
+ mpirun --bind-to none -x UCX_ERROR_SIGNALS -x UCX_HANDLE_ERRORS -mca pml ob1 -mca btl tcp,self -mca btl_tcp_if_include lo -mca orte_allowed_exit_without_sync 1 -mca coll '^hcoll,ml' -np 1 ./test/mpi/test_memhooks -t flag_no_install -m reloc
==== Running memory hook (flag_no_install mode reloc) on MPI ====
flag_no_install: initialized
total_mapped=1048576
test_memhooks.c:432: Callback for mmap invoked, while hooks were not set
flag_no_install: FAIL
```
It happens because osc/ucx now calls ucp_init() during component_init, which triggers memory hooks install.

TEST/JENKINS: Disable osc/ucx component when using mpirun

---

src/uct/ib/configure.m4

Remove the configure of "ibv_cmd_modify_qp", because it's not used anymore.

BUILD/CONFIG: Remove no use build configure.

---

src/ucp/core/ucp_ep.c

Fix  ucp ep config INFO trace
before
```
ucp_worker.c:1784 UCX  INFO    0x2d96740 self cfg#1tag(sysv/memory cma/memory cuda_copy/cuda) rma(sysv/memory)
ucp_worker.c:1784 UCX  INFO    0x2d96740 intra-node cfg#2tag(sysv/memory cma/memory) rma(sysv/memory)
ucp_worker.c:1784 UCX  INFO    0x2a719d0 self cfg#1tag(sysv/memory cma/memory cuda_copy/cuda) rma(sysv/memory)
ucp_worker.c:1784 UCX  INFO    0x2a719d0 intra-node cfg#2tag(sysv/memory cma/memory) rma(sysv/memory)
```
after
```
ucp_worker.c:1784 UCX  INFO    0x252d990 self cfg#1 tag(sysv/memory cma/memory cuda_copy/cuda) rma(sysv/memory)
ucp_worker.c:1784 UCX  INFO    0x252d990 intra-node cfg#2 tag(sysv/memory cma/memory) rma(sysv/memory)
ucp_worker.c:1784 UCX  INFO    0x1018750 self cfg#1 tag(sysv/memory cma/memory cuda_copy/cuda) …
```

UCP: Fix ep config info trace

---

src/ucp/core/ucp_mm.inl

Just a minor refactoring to get rid of redundant `goto`.

UCP: Minor ucp_memh_get refactoring

---

src/tools/perf/lib/libperf_int.h

Bump the buffer size for receiving ucp_address_t data in the perf library.
Came across a system that makes 3KB ucp_address_t structs. It has 18 ROCe ports. So it blows up the perf assert(). Fixable by passing params like UCX_UNIFIED_MODE, but blowing up with the default env is not good.
Bump the address size macro.

TOOLS\PERF: Bump address size

---

src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/test_md.cc

Create umem with default page size only
A temporary fix for packing exported mkeys. Fixes the following problem:
```
mlx5dv_devx_obj_create(MKEY) failed on mlx5_bond_1, syndrome 0x317175: Remote I/O error
```
where 0x317175 is _page offset of the starting point in the umem must match the page offset indicated by the mkey.start_address_
Also driver bug is created - [Nvidia internal link](https://redmine.mellanox.com/issues/3260653)

UCT/IB: Fix exported memh packing

---

src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c

Backport #8677 to v1.14.x
Clean cherry-pick.

UCT/IB/MLX5: Set counter_set_id during modify 2INIT instead of create - v1.14.x

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_request.h
src/ucp/rndv/rndv.c

fix rtr/ppl error flow
- `UCP_REQUEST_FLAG_RNDV_FRAG` is a recv request, so we can not access send part of it
- leaked `req->send.rndv.mdesc` from rtr request

UCP/RNDV: fix rtr/ppl error flow

---

src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_rtr.c

Pack rkey to RTR/RTS if CMA transport is present
Enable CMA for rendezvous transports when it is the only RMA capable transport on the system.
This way rndv pipeline protocol based on CMA can be selected when transferring data from device to host.
Gives ~10x speedup with `osu_bw -d cuda D H` and UCX_TLS=`sysv,cma,cuda_copy`
OR about 15% speedup with host memory

UCP/PROTOV2: Pack rkey in rts/rtr when CMA is present

---

buildlib/pr/tests.yml

report `roce_proto_enable` failures as errors
to highlight regressions

AZP: report roce_proto_enable failures as errors

---

src/ucp/rndv/rndv.c

fix a corner case for calculating the rkey_index in case the md_index is not part of the md_map.
Fixes issue https://github.com/openucx/ucx/issues/8627
(cherry picked from commit 2034fbc0b911f7ccb3601312f090d28e11f30c6a)

UCP/CORE: fix corner case for rkey_index - v.14.x

---

test/gtest/ucp/test_ucp_wireup.cc

fix test_ucp_wireup_2sided.multi_ep_2sided
fixes https://github.com/openucx/ucx/issues/8719
- add fence + control put
- fix collision between `send_data` and cleared receive buffer

GTEST: fix test_ucp_wireup_2sided.multi_ep_2sided

---

src/ucp/rndv/rndv_get.c

fixes occasional failures of `dc_ud/test_ucp_sockaddr.force_close_during_rndv/*`
DC transport has missed memory invalidation on peer failure, so fail recv request on RTS failure even if get op was completed successfully.
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/54652/logs/661
```
022-11-25T08:41:49.3071833Z [ RUN      ] dc_ud/test_ucp_sockaddr.force_close_during_rndv/2 <dc_x,ud_v,ud_x,mm/tag,sa_data_v2>
2022-11-25T08:41:49.6986992Z [     INFO ] Testing 2.1.5.4:0
2022-11-25T08:41:49.6990398Z [     INFO ] server listening on 2.1.5.4:47232
2022-11-25T08:41:50.2242459Z [     INFO ] ignoring error Connection reset by remote peer on endpoint 0x7f7b0676c000
2022-11-25T08:41:50.2249023Z /scrap/azure/agent-08/AZP_WORKSPACE/2/s/contrib/../test/gtest/co …
```

UCP/PROTO: workaround in error handling of rndv/get/zcopy

---

src/uct/ib/base/ib_iface.h
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/accel/ud_mlx5.h
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/uct/ib/test_cqe_zipping.cc

Allows controlling CQE zipping per CQ RX/TX direction.
This option would help to control the UCX configuration more accurately.

UCT/MLX5: CQE zipping user control per CQ direction

---

src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.h
src/uct/rocm/copy/rocm_copy_md.c

1. add parameters to allow control over the rcache used by the rocm_copy component.
2. Remove the short d2h and h2d parameters, there is no need for separate threshold parameters for short vs. zcopy functions.
Improve control of rcache options and simplify threshold parameter handling
CC @akolliasAMD

ROCM/COPY: add rcache parameters

---

src/uct/ib/mlx5/dv/ib_mlx5_dv.h
src/uct/ib/rc/accel/rc_mlx5_common.c

exp verbs were removed, remove this piece of unused code.
remove exp verbs related code
exp verbs were removed at https://github.com/openucx/ucx/pull/8102 & https://github.com/openucx/ucx/pull/8158 & https://github.com/openucx/ucx/pull/8231

UCT/IB: remove unused code used to support exp verbs

---

src/ucm/util/sys.c

Do not read unnecessary header file
Decrease  preprocess time without reading unnecessary file

UCM: avoid reading unnecessary header file

---

src/ucm/util/reloc.h
src/ucs/datastruct/ptr_array.c
src/ucs/sys/compiler_def.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_common.c

"__attribute__((used))" prevents the compiler from generating warnings if the function is not referenced and avoids being removed by linker.
"__attribute__((unsed))" does not change the behavior of the unused function removal process .i.e. linker could remove the unused function.
remove unused functions from the generated executable file.

UCS: enable remove unused function by linker

---

src/ucp/core/ucp_mm.c

UCT flags parameter was not passed down to UCT memory registration.
For example, UCT_MD_MEM_FLAG_HIDE_ERRORS was not passed from ucp_mem_reg_md_map_update, leading to excessive error messages.

UCP/MM: Fix passing uct_flags parameter in ucp_memh_alloc

---

src/ucp/core/ucp_context.c

Updated the logic of processing the allow/deny list of transports.
Fixed disabling the transport used in the alias as an auxiliary transport.
E.g. `ud_mlx5` transport was disabled, if a user uses `UCX_TLS=^dc`.
Before:
After:

UCP/CORE: Don't disable tl if it used as aux tl in alias.

---

src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_ep.c
src/ucp/wireup/wireup_ep.h

Replay pending requests of wireup EP CM during connection establishment.
To prevent potential ordering issues and wrong configuration.
During connection establishment phases replay all pending requests including Wireup EP CM.

UCP/EP/WIREUP: Replay pending requests of wireup EP CM during connection establishment

---

src/ucp/core/ucp_am.c
src/ucp/proto/proto_am.inl
src/ucp/tag/tag_send.c

Pass user-provided memory type to the function that checks whether the buffer can be sent inline or not.
Inline send can be done for host memory only and we don't detect memory type in inline send path due to overheads. Therefore, on a GPU system, inline send is never used even for host memory buffers. However, if the memory type is already provided by the user and it is host memory, we can try inline send without any extra overhead.
Pass the user-provided memory type to the function that checks whether the buffer can be sent inline or not.
Pass UCS_MEMORY_TYPE_UNKNOWN if user has not provided memory type.

Pass user-provided memory type to inline send check

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_devx.c
src/uct/ib/rc/accel/rc_mlx5_iface.c

Check lag mode info to decide set lag_tx_port_affinity or not.
Add configuration to ```force set```/```force not set```/```auto detect decision``` to configure DCI lag_tx_port_affinity.
In hash mode under non-switchdev, it's better to not set lag_tx_port_affinity to decrease explicit port flow table overhead.
Define new IFC bits ```uct_ib_mlx5_lag_context_bits::port_select_mode``` to get lag mode info.
For lag device,
1. When ```UCX_DC_MLX5_LAG_PORT_SELECT=auto```(default)
In **hash mode** under non-switchdev, this PR does not set DCI lag_tx_port_affinity.
```if lag device supports bypass port select flow table```, it's better to not set lag_tx_port_affinity to decrease explicit port flow table overhead.
```if lag device does not support …
```

add DC config to set lag_tx_port_affinity according to lag mode info

---

src/uct/ib/rc/base/rc_iface.c

Do not show available CQ resources for DC transport in VFS
It is misleading value, because DC creates CQ of sufficient length and does not do CQ resources moderation

UCT/DC: Do not show cq_available in VFS

---

src/ucp/core/ucp_context.c
src/ucs/arch/cpu.c
src/ucs/arch/cpu.h

Increased BCOPY BW in new protocol infrastructure.
Increasing BCOPY BW helps to get better bandwidth values on several message sizes (e.g. 2k-4k), avoiding using of rendezvous protocol on the message sizes instead of bcopy.

UCP/CORE: Increased BCOPY BW in new protocols infrastructure.

---

src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h
src/ucp/proto/proto.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_reconfig.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c
test/gtest/ucp/test_ucp_tag_mem_type.cc

reset implementation for rndv/recv/ppln and rndv/get/mtype protocols
missed functionality in protov2

UCP/PROTO: reset rndv/recv/ppln and rndv/get/mtype

---

test/gtest/common/test_helpers.cc
test/gtest/ucp/test_ucp_sockaddr.cc

On VPN virtual NICs the value is NULL and it causes segfault in gtest
Signed-off-by: Pasha (Pavel) Shamis <pshamis@nvidia.com>

GTEST: Skip transports with sockaddr NULL

---

src/ucs/debug/debug.c

This will avoid to crash during signal-handling/stack-unwinding upon ENOMEM/failed memory alloc situation.
Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>
Add error handling in order to avoid crashes. 
For UCX Issue #8716 .

UCS/DEBUG: handle error return from ucs_debug_backtrace_create()

---

test/gtest/ucp/test_ucp_wireup.cc

fix test_ucp_wireup_2sided.multi_ep_2sided/rma
```
[  FAILED  ] dcx/test_ucp_wireup_2sided.multi_ep_2sided/2, where GetParam() = dc_x/rma,no_ep_match
```
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=55233&view=logs&j=de7f2b91-0060-5c03-79ec-8e744740a59d&t=b4a9095b-911f-5006-fff5-4df2a89d16a4&s=8bfbeaae-4c8e-5f12-f154-edd305817000

GTEST: fix test_ucp_wireup_2sided.multi_ep_2sided/rma

---

configure.ac
contrib/configure-devel
ucx.spec.in

The option has never been implemented. There is no reason to have it in configure. This can also mislead developers.

CONFIG: Removing failt-injector option

---

test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/uct/uct_p2p_test.cc

Current max message size does not take in consideration the limitations of BAR1 size. For ML GPUs the BAR1 is very large and it has never been a limitation. For consumer class of GPUs the BAR1 size can be in a range of ~ megabytes. As a result, gtest can fail. 
This patch adds query for the BAR1 size and limits the max message size.
NVML has an API to query Bar1 size

GTEST: Limit max gtest message size to BAR1 size

---

src/uct/ib/base/ib_md.c

Fix an error in checking return status of multi-threaded mem reg function

UCT/IB: Fix error checking for multi registration

---

src/uct/cuda/base/cuda_md.c

CUDA: Adding support for CUDA-12

CUDA: make cuGetProcAddress to work with cuda 12

---

test/gtest/common/test_helpers.cc

Don't run gtest on wireless interfaces
Makes it difficult to develop on desktops and workstations.

GTEST: Don't run gtest on wireless interfaces

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Make gdrcopy path preferred over rndv/get/zcopy with cuda_ipc for intra-node small messages when using protocols v2
Increase estimated overhead of cuda_ipc transfer - make it closer to actual performance.

UCT/CUDA_IPC: Improve overhead estimation

---

buildlib/pr/main.yml
buildlib/tools/builds.sh

add a rocm docker container for testing. Build only at the moment.
simplify code development and maintenance for rocm devices

AZP: Add ubuntu20 container w/ rocm software stack

---

test/gtest/ucp/test_ucp_tag_match.cc

skip test_ucp_tag_match under valgrind in case of forced UCX_PROTO_ENABLE and HWTM variants
workaround for  https://github.com/openucx/ucx/pull/8731, minimal reproducer is implemented in https://github.com/openucx/ucx/pull/8769

GTEST: skip test_ucp_tag_match under valgrind

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto_debug.c

Improve debug experience - print protocols information about specific operations and not all of them.

UCP/PROTO/DEBUG: Support glob pattern with UCX_PROTO_INFO

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_worker.c
test/gtest/ucp/test_ucp_wireup.cc

Removed unused code related to old `sockaddr` flow.
The code became unused after removing the single place where `UCP_TL_RSC_FLAG_SOCKADDR` is set. It was in `ucp_add_tl_resources` before, and removed by https://github.com/openucx/ucx/pull/6268

UCP/CORE: Removed unused sockaddr code.

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/rndv/rndv_rtr.c
src/ucp/wireup/select.c
src/uct/sm/scopy/knem/knem_md.c

Removed test memory registration during UCP context initialization.
Added test memory registration to KNEM memory domain query method.
Partially reverted https://github.com/openucx/ucx/pull/8392 (which was the original fix for KNEM memory registration issue).
Having test memory registration during UCP context initialization caused CUDA API calls. Which caused the creation of extra CUDA contexts.

UCP/CORE: Removed test memory registration during UCP context initialization.

---

src/uct/ib/base/ib_device.c

Make rc_x transport work on BlueField3
cc @Sergei-Lebedev

UCT/IB: Add device specification for BlueField3

---

src/ucp/api/ucp.h

Add comments to UCP_OP_ATTR_FLAG_NO_IMM_CMPL to make the doc clearer.
Users are confused that CB are called when UCP_OP_ATTR_FLAG_NO_IMM_CMPL is set.
They thought that UCP_OP_ATTR_FLAG_NO_IMM_CMPL means not call completion callback.
Add some comments.

UCP/DOC: add comments to UCP_OP_ATTR_FLAG_NO_IMM_CMPL

---

src/ucp/am/eager.inl
src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h
src/ucp/core/ucp_request.h
src/ucp/proto/proto_am.c
src/ucp/proto/proto_am.inl
test/gtest/ucp/test_ucp_sockaddr.cc

Support re-initialization of protocols with non persistent user header
#8386 
Zcopy clean function need to handle the case when user header is not persistent and need to be copied.
[Description can be found here](https://github.com/openucx/ucx/pull/8173#discussion_r928840502)

Am user header release/support protov2 reset

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h

Removes hard errors in case of too strict memlock limit during md_open
Now if system has too strict memlock limit the md_open() will fail and error messages would be printed. That can confuse customers if they don't plan to use IB transport at all.
Should solve https://github.com/openucx/ucx/issues/8746

UCT/IB: Make memlock limit settings non-fatal for md_open

---

bindings/java/src/test/java/org/openucx/jucx/UcpListenerTest.java

Fix occasional failures in Java test on GPU test node

JAVA/TEST: Don't run tests on docker interfaces

---

src/ucs/datastruct/string_buffer.c
src/ucs/datastruct/string_buffer.h
test/gtest/ucs/test_string.cc

Will be used for atomics protocols v2 query description

UCS/STRING/TEST: Add ucs_string_buffer_rbrk() to split right token

---

test/gtest/uct/test_uct_perf.cc

Concurrent execution of cuda_copy/test_uct_loopback_cuda on the same machine leads to significantly lower performance which causes the test to time out

TEST/UCT: Don't check cuda_copy performance in test_uct_loopback

---

bindings/java/src/main/native/context.cc
examples/ucp_client_server.c
examples/ucp_hello_world.c
src/tools/info/proto_info.c
src/tools/perf/lib/libperf.c
test/apps/iodemo/io_demo.cc
test/apps/iodemo/ucx_wrapper.cc
test/apps/iodemo/ucx_wrapper.h

Improve protocols information output when using perftest, ucx_info, and jucx

TOOLS/PERF/INFO: Pass context name parameter to ucp_init()

---

src/ucp/core/ucp_context.c

Returned back dash in context printed info to address the issue https://github.com/openucx/ucx/issues/8780.

UCP/CORE: Returned back dash in context printed info.

---

src/ucp/am/eager_multi.c
src/ucp/am/rndv.c
src/ucp/am/ucp_am.inl
src/ucp/proto/proto.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl
src/ucp/rma/amo_offload.c
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c
src/ucp/rma/rma.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_mtype.inl
src/ucp/rndv/rndv_ppln.c
src/ucp/tag/eager.h
src/ucp/tag/eager_multi.c
src/ucp/tag/tag_rndv.c
test/gtest/ucp/test_ucp_proto.cc

Free up more space in `ucp_proto_select_param_t` structure, so we could add reply_buffer.{mem_type, sys_dev} fields to it.
- We need to add reply_buffer mem info to fix atomic operations on GPU buffers, to take into account reply buffer memory type and not just send buffer memory type. UCP API supports any combination of memory types for send buffer and reply_buffer.
- Fix for atomic protocols v2 will be in next PR
- Remove INTERNAL flag from select params - it could be a parameter for the protocol select functions, since it only affects debug tracing.
- The flags for different operations could overlap, so 4 upper bits in op_id field should suffice.
- Add helper functions to access flags and op_id
- Increase the reserved space (padding) to 2 bytes

UCP/PROTO: Unite select_param->op_flags and select_param->op_id

---

src/ucp/api/ucp.h

Replaced deprecated `ucp_worker_get_address` by `ucp_worker_query` in the description of `ucp_worker_release_address`.
https://github.com/openucx/ucx/pull/3076
https://github.com/openucx/ucx/pull/8194

UCP/API: Updated ucp_worker_release_address description.

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
src/ucp/core/ucp_request.inl
src/ucp/dt/datatype_iter.c
src/ucp/dt/datatype_iter.h
src/ucp/dt/datatype_iter.inl
src/ucp/proto/proto_common.inl
test/gtest/ucp/test_ucp_dt.cc
test/gtest/ucp/test_ucp_proto.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/ucp_datatype.h

User memh proto v2 support.
Allow memory handle to be supplied from user in order to prevent multiple registration and improve performance.

UCP/CORE: User memh proto v2

---

src/ucp/rma/amo_sw.c

Fix `Unsupported: got software atomic request while device atomics are selected on worker nnn` error with protov2 atomics.
Disable SW atomics if target worker uses device atomics

UCP/AMO/SW: Fix CPU/device atomics selection with protov2

---

test/gtest/ucp/test_ucp_tag_mem_type.cc

skip HWTM with memtype protov2
similar to https://github.com/openucx/ucx/pull/8770

GTEST/UCP: skip HWTM with memtype protov2

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Without this detection, `ib` gen5 is preferred over `cuda_ipc` which leads to lower bandwidth between p2p accessible Hopper GPUs. 
- Detect Hopper architecture and provide a more accurate cuda_ipc bandwidth estimation
- Add env var to allow user to explicitly set cuda_ipc bandwidth

UCT/CUDA: Detect hopper architecture

---

src/uct/base/uct_md.c

Signed-off-by: Howard Pritchard <howardp@lanl.gov>
fix so UCX can build with non-old GCC variants
Its nice if UCX can build with newer GCC variants
this patch fixes this build issue

UCT/BASE: Fix conflicting types for 'uct_md_mem_advise'.

---

Makefile.am
src/tools/perf/lib/libperf.c

After adding a missing perftest file `test_types_ucp_rma`, CI found a hang/deadlock in libperf - the workers of multiple threads have to be flushed in parallel. The hang happened with `UCX_TLS=tcp`.
Both processes hang in:
```
#0  0x00007f79fe379483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f79ffb4bb23 in ucs_event_set_wait (event_set=0xe4f3d0, 
num_events=num_events@entry=0x7fff7db4e9f0, timeout_ms=timeout_ms@entry=0, 
event_set_handler=event_set_handler@entry=0x7f79ffea4dc0 <uct_tcp_iface_handle_events>, 
arg=arg@entry=0x7fff7db4e9e0) at <ucxdir>/src/ucs/sys/event_set.c:198
#2  0x00007f79ffea4d44 in uct_tcp_iface_progress (tl_iface=0xed40d0) at <ucxdir>/src/uct/tcp/tcp_iface.c:334
#3  0x00007f7a0012ef22 in ucs_callbackq_dispatch (cbq=<optimized out>) at …
```

TOOLS/PERF: Fix worker flush deadlock when using multiple workers

---

test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag.h
test/gtest/ucp/test_ucp_tag_match.cc
test/gtest/ucp/test_ucp_tag_mem_type.cc
test/gtest/ucp/test_ucp_tag_offload.cc

+ skip `test_ucp_tag_offload_multi` with proto_v2
+ del code duplication
similar to https://github.com/openucx/ucx/pull/8770

GTEST/UCP: disable HWTM protov2

---

src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_log.c
src/uct/ib/base/ib_log.h
src/uct/ib/base/ib_md.c
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/ib/ud/accel/ud_mlx5.c

Adds the additional logging to the places that can be affected by setting the locked memory limit.
Now we already have messages about too strict locked memory limit, but not all places were covered.

UCT/IB: Improve memlock limit logging

---

buildlib/az-helpers.sh
buildlib/pr/io_demo/az-stage-io-demo.yaml

Azure CI - Add a check for the out-of-sequence counter when testing iodemo with interferences.
Check that it's increased when interference is on.
Verify https://redmine.mellanox.com/issues/3139906 - Nvidia internal issue.

buildlib/pr/io_demo: Add a check for the out-of-sequence counter.

---

src/uct/rocm/Makefile.am
src/uct/rocm/base/rocm_signal.c
src/uct/rocm/base/rocm_signal.h
src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.h
src/uct/rocm/ipc/rocm_ipc_ep.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.h

This commit introduces the ability to use asynchronous progress for the zcopy operations in the rocm/copy tl. 
Performance improvements.
Move some common code from the rocm/ipc directory to rocm/base to minimize code duplication.

ROCM/COPY: allow async progress for zcopy operations

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Fix dmabuf not being used when the buffer is not page-aligned (its size or address)
cc @Akshay-Venkatesh

UCT/CUDA: Pass page-aligned address and length to dmabuf query

---

docs/source/faq.md
src/ucp/core/ucp_context.c

Updated logic to handle allow/deny list of transports.
Previously, transport was completely disabled if it was mentioned in deny list. However, some transport may be used as an auxiliary transport, and disabling them in this way may implicitly break using of another transport.
E.g, transport `tl_name_1` can be used only with `tl_name_2` as an auxiliary transport. `UCX_TLS=^tl_name_2` implicitly break usage of  `tl_name_1`.
After these changes, such transports can be disabled only explicitly: `UCX_TLS=^tl_name_2,tl_name_2:aux`.
Note, that to completely disable other transports it is enough to mention them without 'aux' suffix.

UCP/CORE: Fixed processing of allow/deny list of transports.

---

src/tools/perf/api/libperf.h
src/tools/perf/lib/ucp_tests.cc
src/tools/perf/perftest.h
src/tools/perf/perftest_params.c
test/gtest/ucp/test_ucp_perf.cc

Add option to perform additional user-side memcpy for AM benchmarks.

TOOLS/PERF: Add user-side memcpy option for AM benchmarks

---

AUTHORS

porting #8821 to keep the list of contributors up to date

RELEASE: Update authors list

---

bindings/java/src/main/native/endpoint.cc
bindings/java/src/main/native/jucx_common_def.cc
bindings/java/src/main/native/jucx_common_def.h
bindings/java/src/main/native/worker.cc

JUCX allocates a global reference to each request, which is used as `user_data` for the request parameters. These global references are deleted inside the native callback. However, when requests are finished directly, the references are not deleted, causing a memory leak. This PR fixes the leakage of global references.
I ran a test application, which sends/receives small tagged messages in a ping-pong pattern using 12 connections (1 thread per connection) and monitored the allocated memory and GC activity:
After 1:25 minutes, the JVM heap is around 10 GB large and grows further, while the GC activity spikes well over 30%, negatively impacting performance.
With the fix applied, the heap size is stable at around 2 GB and the GC activity stays under 1%:
By deleting the global reference, when …

JUCX: Fix leakage of jucx_request global references

---

buildlib/az-distro-release.yml
buildlib/az-helpers.sh
buildlib/azure-pipelines-release.yml
buildlib/jucx/jucx-publish.yml

Manually cherry-pick fixes to resolve various CI failures.

AZP/RELEASE: Fixes for v1.14 release

---

buildlib/az-distro-release.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose.yml
buildlib/dockers/ubuntu-release.Dockerfile

What
Add ubuntu 22.04 to the release pipeline.
How ?
The new Ubuntu image was built with Dockerfile & docker-compose below.

AZP/RELEASE: Add Ubuntu 22.04 - v1.14.x

---

buildlib/pr/distro.yml

change label ucx_docker to swx-rain03
failing builds [https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=52808&view=logs&j=5afb4f82-935f-5137-d62f-bc721755fb44&t=880ff2b6-670e-58f5-7dea-5da90e095d00&s=092fc06a-bf28-53e8-3671-20e6cafa6bc9](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fucfconsort%2Fucx%2F_build%2Fresults%3FbuildId%3D52808%26view%3Dlogs%26j%3D5afb4f82-935f-5137-d62f-bc721755fb44%26t%3D880ff2b6-670e-58f5-7dea-5da90e095d00%26s%3D092fc06a-bf28-53e8-3671-20e6cafa6bc9&data=05%7C01%7Cekaidrikov%40nvidia.com%7C8064fe04fd8248dacd8a08daf8717424%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638095463404430960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5oDW5xYjJcMJfyQHl8k%2B …

change label to ucx_iodemo_without_interference

---

test/gtest/common/mem_buffer.cc
test/gtest/uct/uct_p2p_test.cc

There are gtest flows that do not call CUDA TL. As a result the nvml library does not get initialized. The side effect of this is that the trim function always returns the MAX size_t value.

GTEST: Adding explicit call to nvml init

---

src/ucp/wireup/wireup_cm.c

use the default enumerated value as argument instead of using int value directly.
improve readability.
broken by https://github.com/openucx/ucx/pull/8144

UCP/EP/WIREUP: use enumerated log level value as argument

---

src/uct/Makefile.am
src/uct/sm/base/sm_md.c
src/uct/sm/base/sm_md.h
src/uct/sm/mm/base/mm_md.c
src/uct/sm/mm/base/mm_md.h
src/uct/sm/self/self.c

Adding support for put_zcopy and get_zcopy on self transport (uct)
To avoid fallbacks to other transports when possible (proto v2).
Implemented the API interface functions for put_zcopy and get_zcopy using memcpy, treating remote address as a local pointer

Add rkey_ptr to self transport, tag matching performance improvement

---

src/ucs/Makefile.am
src/ucs/async/eventfd.c
src/ucs/async/eventfd.h
src/uct/cuda/base/cuda_iface.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Use event_fd notification to support arm/wakeup feature and avoid async_cb in cuda_copy to avoid potentially having to contend with UCP worker async lock.
- haven't really considered multi-threaded safety but ucx_perftest with `-T 4 -E sleep` options seems to be working

UCT/CUDA_COPY: use EVENT_FD instead of EVENT_ASYNC_CB

---

src/ucs/Makefile.am
src/ucs/async/eventfd.c
src/ucs/async/eventfd.h
src/uct/cuda/base/cuda_iface.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Port https://github.com/openucx/ucx/pull/8754 to 1.14.x

UCT/CUDA_COPY: use EVENT_FD instead of EVENT_ASYNC_CB  - v1.14.x

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_worker.c

Fixed filename generated when using `UCX_PROTO_INFO_DIR`.
Changes from https://github.com/openucx/ucx/pull/8699 added an extra underscore to filenames generated using `UCX_PROTO_INFO_DIR`. E.g. `0x807be0_self_cfg_0__tag_send_from_host_memory_0_0.dot`.

UCP/CORE: Fixed proto info filename.

---

src/ucp/am/ucp_am.inl
src/ucp/core/ucp_am.c
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_init.c
src/ucp/proto/proto_select.inl
src/ucp/rndv/proto_rndv.inl

Fixed printing operation flags when using UCX_PROTO_INFO.
Before:
After:

UCP/PROTO: Fixed operation flags in proto v2 info.

---

test/apps/iodemo/io_demo.cc

While establishing many connections, ports may be used out with using same src ip when selecting the src ip randomly. Update to use round-robin method to select the src ip.
Use round-robin method to select the src ip.
ports may be used out with using same src ip when selecting the src ip randomly. 
Use server index as input parameter to select the src ip.

TEST/IODEMO: round-robin balance among different src ip dev

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.h

Add checks/assertions for DCI_NUM.
Currently UCX uses int8_t/uint8_t to store DCI index/num, not support >127 DCIs.
But it gives no error message if DCI_NUM is > 127.
Add parameter checks and assertions.

UCT/IB/DC: add DCI_NUM checks

---

ucx.spec.in

Fix UCX RPM build on machines that have libxpmem-devel rpm from MLNX_OFED installation

RPM/SPEC: Use pkgconfig for xpmem BuildRequires

---

ucx.spec.in

Fix https://bugzilla.redhat.com/show_bug.cgi?id=2159661
Before this PR:
```
$ rpm -qRp <path>/ucx/build-devel/rpm-dist/x86_64/ucx-rdmacm-1.15.0-1.el7.x86_64.rpm | grep ucx
ucx(x86-64) = 1.15.0-1.el7
```
After:
```
$ rpm -qRp <path>/ucx/build-devel/rpm-dist/x86_64/ucx-rdmacm-1.15.0-1.el7.x86_64.rpm | grep ucx
ucx-ib(x86-64) = 1.15.0-1.el7
```

RPM/SPEC: ucx-rdmacm to require ucx-ib subpackage

---

buildlib/az-distro-release.yml

Move back to the working directory before creating an artifact.
Artifacts should be present in the working directory in order to get uploaded.

AZP/RELEASE: Move back to the working directory

---

buildlib/az-distro-release.yml

Statically add cuda var to dpkg-buildpackage command, so cuda will be added to DEB_BUILD_PROFILES env var.
(Porting https://github.com/openucx/ucx/pull/8862 into master.)
CUDA support should always be added to the release package.

AZP/RELEASE: Add CUDA support to Deb packages

---

src/ucp/core/ucp_ep.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_cm.h

ucp_cm_ep_init_flags is called in ucp_ep_init_flags.

UCP/CORE: refine get ep_init_flags

---

src/ucp/core/ucp_ep.c

Fix performance degradation due to using 2 paths on NDR400 by default
Divide the estimated bandwidth of each lane by the number of paths on the resource.
This fix would be ported to v1.14.x branch.

UCP/EP: Fix rendezvous threshold for multi-path

---

test/gtest/ucp/test_ucp_worker.cc

Fixes `test_ucp_worker_thread_mode` test when built without `--enable-mt` configuration.
Test fails when built without thread support.
Skip MT variant when built without thread support.

TEST/UCP: Expect single thread without MT support build

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_rkey.inl
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/core/ucp_worker.inl
src/ucp/proto/proto_select.c
src/ucp/rndv/proto_rndv.c
test/gtest/ucp/test_ucp_proto.cc

convert EP configurations storage to dynamic array
in some cases 64 EPs are not enough
convert storage from static to dynamic array

UCP/WORKER: convert EP configs storage to dynamic array

---

buildlib/az-distro-release.yml

What
Porting https://github.com/openucx/ucx/pull/8875 to master.
Publish CUDA DEB files along with UCX DEB upon release.
Why ?
Since v1.14.0, the cuda packages will be a separate DEB file.

AZP/RELEASE: Rename and publish all DEBs

---

buildlib/az-distro-release.yml

Publish CUDA DEB files along with UCX DEB upon release. 
Since v1.14.0, the cuda packages will be a separate DEB file.

AZP/RELEASE: Publish CUDA DEBs - v1.14.x

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

print log_max_qp when opening device successfully.
debug purpose

UCT/IB: show log_max_qp info in debug log

---

src/uct/sm/self/self.c
test/gtest/ucp/test_ucp_tag_xfer.cc
test/gtest/ucp/test_ucp_wireup.cc

rkey_ptr was implemented in self but not being selected in proto v2

UCT/SM/SELF: Choosing self rndv/rkey_ptr for big messages in same-process communications

---

src/uct/ib/rdmacm/rdmacm_cm.c

print log_max_num_reserved_qpn if it can use reserved qpn in rdmacm
debug purpose

UCT/RDMACM: show log_max_num_reserved_qpn info in debug log

---

src/uct/tcp/tcp.h
src/uct/tcp/tcp_iface.c

Added upper bound to TCP BW calculation
Try to simulate better TCP BW by adding TCP stack computation time limit.
The purpose is to prevent scenarios where TCP BW is higher than IB BW.

UCT/TCP: Added upper bound to TCP BW calculation

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

fix below error when DEVX is not support in build environment
```
error: ‘uct_ib_mkey_token’ defined but not used [-Werror=unused-const-variable=]
static const char uct_ib_mkey_token[] = "uct_ib_mkey_token";
^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

UCT/IB/MLX5DV: fix not use defined var error under no DEVX

---

buildlib/az-distro-release.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose.yml
buildlib/dockers/push-release-images.sh
buildlib/dockers/ubuntu-release.Dockerfile
debian/control.in

1. Remove 'cuda-compat' from nvidia/cuda images.
2. Install 'libnvidia-compute' with driver version matching the CUDA runtime version [(e.g. driver ver 515 for CUDA 11.7)](https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local).
3. Drop libnvidia-ml.so linking hack, as it is provided by 'libnvidia-compute'.
4. Uncouple the gdrcopy build profile from cuda profile.
5. Push images script: exclude commented-out images.
6. Drop the unsupported Ubuntu16 release.
7. Drop superfluous dependencies from ucx-cuda DEB, as those are satisfied by default CUDA installation.
Fix dependencies for CUDA build.
Improve the image-building process.
##
Note: this solution replaces …

AZP/RELEASE: rm cuda-compat & separate gdrcopy"

---

test/gtest/ucp/test_ucp_fence.cc
test/gtest/ucp/test_ucp_rma_mt.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h

Fix assert failure below, on tests like `test_ucp_fence*`, when built without `--enable-mt`:
```
==>  2807     ucs_assert(worker->inprogress++ == 0);
```
The sender thread calls `request_wait()` or `flush_worker()` that eventually calls `check_events()`. That later one progresses all entities, so including the sender and the receiver workers. This is an issue because the main thread is already progressing the receiver worker.
To fix, we make sure that the sender thread does not progress the receiver worker by adding one new parameter to restrict processing to a subset of the list of entities. In case of `self`, only the sender needs to progress.

TEST/UCP: Separate progress to avoid concurrent ucp_worker_progress

---

src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_wireup.cc

Set EP locality based on selected lanes.
Prevent wrong EP locality as a result of internal TCP NICs (as observed in BlueField machines).
The issue was found during the following bug investigation:
https://redmine.mellanox.com/issues/3340697#change-25091571

UCP/WIREUP: Set EP locality based on selected lanes

---

contrib/wireshark/ucx_le64.lua

Add some UCX protocols for 64-bit little-endian platforms.
It's easier to understand captured payloads with dissections.
Add Wireshark LUA dissectors, to be copied in its personal plugin folder.
Capture:
```
$ # Generate traffic with example ucp_client_server on TL tcp/ib
```
Works on Wireshark (tested on Windows and Linux):
```
$ wireshark -Xlua_script:ucx_le64.lua <pcap_file>
```
or copy the LUA file in the Wireshark plugins directory:
- `Help` -> `About Wireshark` -> `Folders` -> `Personal Lua plugins`

CONTRIB/WIRESHARK: Add UCX LUA dissectors for 64-bit little-endian

---

src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/base/ib_verbs.h
src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/uct/ib/test_ib_xfer.cc

Remove implicit ODP support. Explicit ODP is still on the place since it would be used for future ODPv2 support feature.
Implicit ODP support probably will have different API in the future.

UCT/IB: Remove implicit on-demand paging

---

test/gtest/common/test_helpers.cc

Reduce test timeout used when polling/waiting for flag
When running with Valgrind test deadline is multiplied by 20 and exceeds watchdog timeout. This can lead to a wrong report if the test fails, watchdog timeout instead of test timeout.
Set upper limit to test deadline based on watchdog timeout.

GTEST: Reduce test deadline

---

examples/uct_hello_world.c

It's better to output normal info to stdout instead of stderr.

EXAMPLES/UCT: output normal info to stdout instead of stderr

---

test/apps/iodemo/io_demo.cc
test/apps/iodemo/ucx_wrapper.cc
test/apps/iodemo/ucx_wrapper.h

Test connection establishment with client_id sending. It increases the connection meta-data size and exercises additional code flows such as wireup_cm fallback.

TEST/IODEMO: Add option to send client id

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
src/uct/ugni/base/ugni_md.c

Add `uct_md_attr_v2_t::odp_reg_mem_types` to fill the ODPable transports for each MD.
ODPv2 support. We are planning to introduce UCP interface that forces ODP memory registration for certain MDs and therefore we want to check availability of ODP registration.

UCT/IB: Introduce MD capability for non-blocking registration memory types

---

buildlib/az-distro-release.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose.yml
buildlib/dockers/push-release-images.sh
buildlib/dockers/ubuntu-release.Dockerfile
debian/control.in

1. Remove 'cuda-compat' from nvidia/cuda images.
2. Install 'libnvidia-compute' with driver version matching the CUDA runtime version [(e.g. driver ver 515 for CUDA 11.7)](https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local).
3. Drop libnvidia-ml.so linking hack, as it is provided by 'libnvidia-compute'.
4. Uncouple the gdrcopy build profile from cuda profile.
5. Push images script: exclude commented-out images.
6. Drop the unsupported Ubuntu16 release.
7. Drop superfluous dependencies from ucx-cuda DEB, as those are satisfied by default CUDA installation.
Fix dependencies for CUDA build.
Improve the image-building process.

AZP/RELEASE: Cherry-pick release proccess changes from v1.14.x 

---

src/uct/rocm/base/rocm_base.c

no need to call the hsa functionality to determine device type if we know that we are dealing with a host pointer.
fixes an issue observed with  a rocm version and the corresponding hsa functionality. But makes also logically sense and saves a function call into the hsa stack.

UCT/ROCM: fix device detection for host address

---

NEWS

Preparation for ucx v1.14.0 release

RELEASE: NEWS update for v1.14.0 release

---

src/uct/ib/base/ib_iface.h

UCT/IB/BASE: Removed unused typedefs.

---

src/uct/rocm/base/rocm_base.c

no need to call the hsa functionality to determine device type if we know that we are dealing with a host pointer.
fixes an issue observed with a rocm version and the corresponding hsa functionality. But makes also logically sense and saves a function call into the hsa stack.
(cherry picked from commit d25a3eee8cee5703711d1093c544f491fa8db1fa)

UCT/ROCM: fix device detection for host address - v1.14.x

---

src/uct/tcp/tcp.h
src/uct/tcp/tcp_iface.c

Added upper bound to TCP BW calculation
Try to simulate better TCP BW by adding TCP stack computation time limit.
The purpose is to prevent scenarios where TCP BW is higher than IB BW.

UCT/TCP: Added upper bound to TCP BW calculation - v1.14.x

---

src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_worker.cc

Filter slow lanes in selection process.
Avoid selecting TCP lanes if we have IB lanes.
The filtering is done by removing lanes with a large enough progress overhead compared to the best lane.
By default, each lane with more than 0.25 of the minimum overhead is filtered out.
Backport of https://github.com/openucx/ucx/pull/8777

UCP/WIREUP: Filter slow lanes in selection process - v1.14.x

---

src/uct/cuda/base/cuda_md.c

cherry-picked f572bb7e328a91fc2187ca86b8f09f67cb38ce9a

CUDA: make cuGetProcAddress to work with cuda 12 - v1.14.x

---

src/ucp/proto/proto_am.inl
test/gtest/ucp/ucp_test.cc

use API to get ep lane rsc_index
better encapsulation
use ```ucp_ep_get_rsc_index```

UCP: use ucp_ep_get_rsc_index to get ep lane rsc_index

---

src/uct/base/uct_iface.h

implement ```UCT_TL_DEFINE``` with ```UCT_TL_DEFINE_ENTRY```
```UCT_TL_DEFINE_ENTRY``` define the object. ```UCT_TL_DEFINE``` needs to define the **exactly same** object, then register the object into resource.

UCT/BASE: implement UCT_TL_DEFINE with UCT_TL_DEFINE_ENTRY

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/sm/scopy/knem/knem_md.c
test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h

Fix the bug that causes absence of ODP registration even if `UCT_MD_MEM_FLAG_NONBLOCK` was passed to `uct_md_mem_reg`
The current `uct_ib_mlx5_devx_md_open` flow that causes the issue:
1. `uct_ib_mlx5_devx_check_odp()` set `md->super.config.odp.max_size` to the certain value (see [here](https://github.com/openucx/ucx/compare/master...ivankochin:ucx:topic/uct/fix-explicit-odp-initialization?expand=1#diff-716148bcb0d4d7e0ef6be8f54003f7cc322baaca473baf9a442182c42830b7f8L768))
2. `uct_ib_md_open_common()` overwrites `md->super.config` by `md_config->ext` that contain the actual config values and therefore always set `md->config.odp.max_size` to 0. (see [here](https://github.com/openucx/ucx/compare/master...ivankochin:ucx:topic/uct/fix-explicit-odp-initialization?expand=1#diff-975534026ea952036 …

UCT/IB: Fix explicit ODP initialization

---

src/ucp/proto/proto_debug.c
src/ucp/proto/proto_select.inl

Fixed operation attributes packing to select parameters.
Only flags in `UCP_PROTO_SELECT_OP_ATTR_MASK` should affect protocol selection.
Otherwise, we may have a cache miss, and print duplicating protocol information.

UCP/PROTO: Fixed operation attributes packing to select params.

---

examples/ucp_client_server.c

Fix #8944
Fixed flags passing to ucp_ep_close_nbx via ep_close in ucp_client_server example.

EXAMPLES: Fixed flags passing to ep_close in ucp_client_server.

---

src/ucs/datastruct/mpool.c
src/ucs/datastruct/mpool.inl
test/gtest/ucs/test_mpool.cc

Fixes memory corruption as below, when using `UCX_MPOOL_FIFO=y`:
```
#7  0x00007fda667b9e66 in ucs_error_signal_handler (signo=11, info=<optimized out>, context=<optimized out>) at /labhome/tvegas/share/srcs/ucx/contrib/../src/ucs/debug/debug.c:1075
#8  <signal handler called>
#9  0x00007fda67b27e53 in ucp_rndv_am_zcopy_send_req_complete (req=0x7ffd41c46e30, status=-128) at /labhome/tvegas/share/srcs/ucx/contrib/../src/ucp/rndv/rndv.c:1895
#10 0x00007fda67acbdc4 in ucp_proto_perf_envelope_make (perf_list=<optimized out>, range_start=<optimized out>, range_end=0, convex=<optimized out>, envelope_list=0x4d430000)
at /labhome/tvegas/share/srcs/ucx/contrib/../src/ucp/proto/proto_init.c:171
#11 0x00007fda67b32ad8 in ucp_request_complete_am_recv (status=UCS_OK, req=0x7ffd41c47500) at …
```

UCS/MPOOL: Fix memory corruption when using UCX_MPOOL_FIFO=y

---

src/tools/info/tl_info.c
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c

Add the user control that allow to force ODP registration for certain memory types.
At this moment it seems reasonable to force memory registration through ODP for certain memory types on some systems.

UCP: ODPv2 control configuration

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_verbs.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

1. simplify ```IBV_HAVE_ATOMIC_HCA``` macro definition and rename it to be ```IBV_DEVICE_ATOMIC_HCA```
2. remove other macro definition for exp verbs

UCT/IB: simplify macro to check device atomic capability

---

src/ucp/api/ucp.h
src/ucp/api/ucp_compat.h

Moved deprecated ucp_ep_close_mode to ucp_compat.h.
Because ucp_ep_close_nb was deprecated.
The description was copied as-is, except the deprecated note.

UCP/API: Moved deprecated ucp_ep_close_mode to ucp_compat.h

---

src/ucp/core/ucp_worker.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.h

Added send completion event to list of events on which the UCT interface should wake up.
The example of the possible issue is in RC wire up procedure. RC uses UD to establish connection. However, the last message in wire up messaging is acknowledge reply, which is sent using RC. If RC interface's progress isn't enabled, and events are being checked, the RC interface can wake up only on send completion event.

UCP/CORE: Wake up UCT iface on send completion event.

---

src/uct/ib/rc/base/rc_iface.c
src/uct/ib/rc/base/rc_iface.h

```ooo_rw``` is used for exp verbs. exp verbs has been removed.

UCT/IB: remove unused exp verbs configuration

---

src/ucs/config/parser.c
src/ucs/config/parser.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

add configuration to set RoCE lag dct port for response under queue affinity mode
On the device that has no hash lag function, for RDMA read operation, the target side return data traffic from the dct affiliated port to the initiator side. Without this option, the dct affiliated port is always the logic port number.
Add ```UCX_DC_MLX5_DCT_PORT_AFFINITY``` to config the RoCE lag dct port affinity.
1) ```default```, use the default logic port number. This is default behavior.
2) ```random```, use ```random``` function to select the affinity.
3) ```other value```, use ```configured value``` to set the affinity.

UCT/IB/DC: default/random/explicit set RoCE lag DCT port affinity

---

src/uct/rocm/ipc/rocm_ipc_iface.c

the current implementation of uct_rocm_ipc_iface_get_bw() in rocm_ipc uses a single value for the bw depending on the connection type. There is no point in repeating the same sequence of functions calls over and over again, the result will always be the same. 
Use a static variable to cache the value after it has been determined once.

UCT/ROCM: avoid repetitive calls to rocm_base_get_link_type

---

src/uct/ib/base/ib_device.c

UCT/IB: use cached device name in log

---

src/ucp/core/ucp_am.c
src/ucp/rma/amo_sw.c
src/ucp/rma/rma_sw.c

Replaced `UCP_DEFINE_AM` by `UCP_DEFINE_AM_WITH_PROXY`.
Use UCP Active Message (AM) handler with proxy handler for all AM, except connection establishment (`UCP_AM_ID_WIREUP`).
To be able to activate UCP worker interface on any AM.

UCP/CORE: Expanded usage of AM handler with proxy.

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/address.c
src/ucp/wireup/address.h
src/ucp/wireup/wireup_cm.c

1. optimize using [ep_init_flags_prio](https://github.com/openucx/ucx/blob/v1.14.0-rc1/src/ucp/wireup/wireup_cm.c#L432) array member to get ep config before creating uct_eps.
2. Do not create uct_ep before fallback to use other CM
Different ep_init_flags_prio results in creating different uct_eps, after packing the ucp_ep address, the address length maybe out of connection channel data space. Then, the pre-created uct_ep needs to be discarded/destroyed. This is a resource & time consuming process. It needs to optimize the process of selecting ```ep_init_flags_prio``` array member to get the ep config and evaluate the ucp address length before creating the uct_ep.
1. check whether the cm private data space is enough for ucp ep address …

UCP/EP/WIREUP: avoid create extra uct_ep needed to be discarded

---

src/uct/ib/rdmacm/rdmacm_cm_ep.c

```rdam``` should be ```rdma```

UCT/RDMACM: fix "rdam" typo to be "rdma"

---

src/ucp/api/ucp.h
src/ucp/core/ucp_request.inl
src/ucp/core/ucp_worker.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/rma/amo_send.c
src/ucp/rma/rma_send.c

Fix short threshold calculation.
Short init threshold function didn't consider opt flags when calculating the short threshold, that cause send operation to enter short fast path, when the optimized protocol was different than short.
Pass `UCP_OP_ATTR_FLAG_MULTI_SEND` optimization flag so the selection of the threshold will also consider short threshold of multi operation.

UCP/PROTO: Fix short threshold calculation

---

buildlib/jucx/jucx-test.yml
buildlib/pr/go/go-test.yml

Clean up the workspace before running tests.
CI hosts suffer from repeated disk space exhaustion due to gtest files piling up.

AZP: Add workspace cleanup for gtest and jucx tests

---

buildlib/pr/main.yml

Container `centos7_cuda11` was defined twice.
The one removed was never actually used.
Clean up to prevent future confusion.

AZP: Remove duplicate resource definition

---

buildlib/pr/main.yml

Move a container image to the private registry.
Pulling from DockerHub by automation is highly discouraged.
We have hit the limit and have been blocked before.

AZP: Pull images from private registry

---

buildlib/pr/io_demo/jobs-io-demo.yaml

correct ```test_intefrafe``` to be ```test_interface```

CI: correct interface name typo

---

buildlib/az-helpers.sh

Workaround for automount availability issues while loading modules.
Multiple job failures due to the on and off availability of automount shares.
Attempt to remount by accessing the NFS.

AZP: retry module load when automount fails

---

src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.h
src/uct/rocm/ipc/rocm_ipc_ep.c
src/uct/rocm/ipc/rocm_ipc_ep.h
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.h

move the memhandle caches from the endpoint to the iface structures. 
Improves scalability and reduces memory footprint

UCT/ROCM: move memh caches to iface

---

buildlib/pr/io_demo/io-demo.yml

Do not build unrelated modules that are not needed to do io_demo test cases.
CI test cases are time consuming process. 
1. For the gtest TCs & examples TCs & java bind TCs & go bind TCs, they've already covered by other test cases.
2. io_demo TCs do not depend on these modules at all.

CI/AZP: do not build unrelated module in io_demo test cases

---

src/ucm/util/sys.c

This failure is usually not causing any errors. It can happen if the application is linked statically.

UCM/SYS: Convert self-load failure message from warning to diag

---

src/ucp/core/ucp_ep.c

When a test is failing, a crash is observed in the teardown path of some tests.
Found internally: [bug](https://redmine.mellanox.com/issues/3411534)
Reason for the test failing to be investigated separately.
A sanity check on the teardown path is dereferencing a null pointer.
Skip null uct_ep while checking sanity on the failure path. After fix proper test failure is seen.
Make sure tcp iface connect() fails. Stack trace is misleading as file line numbers are off.
```
GTEST_SHARD_INDEX=0 GTEST_TOTAL_SHARDS=2 UCX_HANDLE_ERRORS=bt gdb --args ./test/gtest/gtest --gtest_filter="tcp/test_ucp_sockaddr.listen/1"
```
```
[ RUN      ] tcp/test_ucp_sockaddr.listen/1 <tcp/tag,mt>
[     INFO ] Testing 10.210.0.169:0
[     INFO ] server listening on 10.210.0.169:51466
[1680279564.140259] …
```

UCP/CORE: Ignore null uct_ep at sanity check while setting failed lanes

---

src/ucs/arch/cpu.c
src/ucs/config/global_opts.c
src/ucs/memory/numa.c
src/ucs/memory/numa.h
src/ucs/sys/init.c
src/ucs/sys/sys.c
src/ucs/sys/sys.h
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/ucs/ucx-ucs.pc.in
src/uct/ib/base/ib_md.c
test/gtest/ucs/test_topo.cc

Implement `numa_distance` function to calculate the distance between IB devices and CPU's NUMA node.
- Remove UCX `libnuma` dependency
- Extend Topo providers API to include method for calculating NUMA distance between IB devices and CPU's NUMA node.
- Remove/Replace `libnuma` dependent code.
- Remove `libnuma` from UCX

UCS/TOPO: Replace numa_distance with sysfs based implementation

---

test/gtest/ucp/test_ucp_am.cc

Skip AM header copy test.
AM header copy test is causing CI to hang from time to time, need to find the root cause and solve it. 
We will skip the test until we release a fix for the problem.
Add skip with reason to the test.

GTEST: Skip test while debugging CI Hang bug

---

src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
test/gtest/uct/ib/test_rc.cc

Do not add the `flush_rkey` to the packed address when RMA and AMO32/64 are not there.
The flush rkey is making address too big for `rdmacm`.
Use the existing flush remote flag to disable remote flush at interface instantiation. Handle it at `rc_mlx5` interface level as other transports are using the same memory domain.
perftest `ucp_get` still contains the `flush_rkey`, io_demo skips it:
```
UCX_SOCKADDR_TLS_PRIORITY=rdmacm ./test/apps/iodemo/io_demo -C 12 -P 1000000 &
UCX_SOCKADDR_TLS_PRIORITY=rdmacm libtool --mode=execute  ./test/apps/iodemo/io_demo -C 12 -P 1000000 <ip address>
```

UCT/MLX5: Only pack flush rkey when flush remote is enabled

---

src/ucp/wireup/select.c
src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c
src/uct/tcp/tcp_iface.c
src/uct/tcp/tcp_sockcm.c
src/uct/ugni/smsg/ugni_smsg_iface.c
test/gtest/ucp/test_ucp_sockaddr.cc

Added base implementation to is_reachable_v2 API using intra/inter flag.
Support identifying intra/inter node communications.

UCT/BASE: Added base implementation to is_reachable_v2 API using intra/inter flag

---

src/ucm/util/sys.c

Cherry-pick #8991 to v1.14.x, no conflicts

UCM/SYS: Convert self-load failure message from warning to diag - v1.14.x

---

src/ucp/proto/proto_init.c

Now protov2 performance calculation for choosing the protocols use only memory registration cost estimation, while UCP use rcache lookup by default now. In approximate case it can be defined that lookup is successful, so the lookup cost should be taken into account instead of memory registration.

UCP/PROTOV2: Add rcache lookup perf estimation

---

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java

Potential fix for CI failures like this:
```
2023-04-08T19:19:55.6068083Z + make -C bindings/java/src/main/native test
...
2023-04-08T19:20:14.5005790Z Running org.openucx.jucx.UcpEndpointTest
2023-04-08T19:20:35.6360937Z Running testGetNB with memType: 0
2023-04-08T19:20:36.1680271Z Running testGetNB with memType: 1
2023-04-08T19:20:36.7147595Z Running testGetNB with memType: 2
2023-04-08T19:20:37.2901614Z Running testActiveMessages with memType: 0
2023-04-08T19:20:38.2809052Z Running testSendRecv with memType: 0
2023-04-08T19:20:38.2810158Z Running testSendRecv with memType: 1
2023-04-08T19:20:38.5802474Z Running testSendRecv with memType: 2
2023-04-08T19:20:39.0931438Z Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.591 sec <<< FAILURE!
2023-04-08T19:20:39.0932814Z …
```

JAVA/TEST: Wait for active message to arrive before checking data

---

src/uct/rocm/ipc/rocm_ipc_ep.c
src/uct/rocm/ipc/rocm_ipc_ep.h
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.h

Commit a5246b8 moved the memhandle cache for rocm_copy and rocm_ipc from the endpoint datastructure to the iface data structure. While this is correct and beneficial for rocm_copy, it is actually detrimental for rocm_ipc.
The reason is that the memhandle cache is using virtual addresses for finding and identifying a registered memory region and ipc key. Multiple processes can use however the same virtual address, in which case the memhandle cache will find an entry, but will fail in the comparison of the ipc keys stored. Consequently, the operation will unmap the previous key, and map/open the current ipc key. Compared to the previous solution this can lead to thrashing of ipc registrations in case the same virtual address is used by multiple processes.
This commit therefore reverts …

UCT/ROCM: revert a5246b8 for rocm_ipc

---

contrib/test_jenkins.sh

Fix CI failures when workers run as root user

TEST/JENKINS: Run mpi with --allow-run-as-root

---

src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/wireup/address.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup.h

This PR adds support for using GPU-NIC distance information when calculating lane scores even if the new protocols are enabled.
During lane creation, GPU-NIC distance information and its impact on latency/bandwidth was used only if new protocols were NOT enabled. Otherwise, we could end up selecting sub-optimal NICs for GPU buffers.
1. Add distance information to worker iface so we can use it for local iface.
2. Use distance-updated latency/bandwidth for remote iface attributes during address pack.

UCP/WIREUP: Use distance info in lane score calculation with new protocols

---

src/ucp/wireup/ep_match.c
src/uct/ib/base/ib_verbs.h
src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fix compilation errors with armclang-22.1

UCT/UCP: Fix compilation errors with armcc-22.1

---

src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/ib/base/ib_device.c
src/uct/tcp/tcp_iface.c
test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_wireup.cc
test/gtest/ucp/test_ucp_worker.cc

Fixed sysfs_path expansion for TCP iface.
In order to find sysfs path for a device, there are few stages:
1) Getting the unresolved path from sys/class. (for example: `/sys/class/net/enp3s0f0s0`).
2) Removing all symbolic links. for example:
`/sys/devices/pci0000:00/0000:00:00.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/mlx5_core.sf.2/net/enp3s0f0s0`
3) Find the sysfs root for the device:
`/sys/devices/pci0000:00/0000:00:00.0/0000:01:00.0/0000:02:00.0/0000:03:00.0`
For TCP iface, we didn't used this process, which caused some architectures to fail (ARM Blufield in this case).
This PR fixes this issue.

UCT/TCP: Fixed sysfs_path expansion for TCP iface

---

buildlib/pr/go/go-test.yml

Run modules init prior to module loading attempts.
'displayname' is a cosmetic change for better readable logs.
Failure to load modules otherwise.

AZP: init modules before loading

---

test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_peer_failure.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_wireup.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h

Replaced deprecated ucp_ep_close_nb in gtest.

GTEST/UCP: Removed deprecated ucp_ep_close_nb.

---

buildlib/pr/go/go-test.yml

Fix failures in go test
The [default port number](https://github.com/openucx/ucx/blob/master/bindings/go/src/examples/perftest/perftest.go#L340) of goperftest is used by Azure agent:
```
[root@swx-rdmz-ucx-gpu-02 ~]# netstat  -t -p|grep 36458
tcp6       0      0 swx-rdmz-ucx-gpu-:36458 13.107.42.20:https      ESTABLISHED 9587/Agent.Listener 
```

TEST/GO: Fix passing port number to goperftest

---

buildlib/pr/go/go-test.yml

TEST/GO: Fix passing port number to goperftest - v1.14.x

---

buildlib/az-distro-release.yml
buildlib/az-github-draft.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose-aarch64.yml
buildlib/tools/common.sh

What
Build and release ARM-based artifacts.
Part 2: Build DEB/RPM artifacts on ARM.
Why ?
https://github.com/openucx/ucx/issues/8762

AZP/RELEASE: Add ARM release - Part #2

---

src/ucp/core/ucp_context.h

Increase epsilon for the lanes calculation function for 10 times.
Epsilon value is supposed to detect the cases when floating point math operations shows different numbers for lanes with the same performance. I increased it since I detected that current value is not enough in some cases.
For example [this bug](https://redmine.mellanox.com/issues/3421919) caused by capping TCP lanes by configuration-defined threshold #8878 and after that lanes selection logic can select different lanes that have the same performance because error of calculation is little-bit overcome the epsilon.

UCP/PROTO: Increase epsilon for lanes score comparison

---

buildlib/az-helpers.sh

What
Workaround for automount availability issues while loading modules.
Why ?
Multiple job failures due to the on and off availability of automount shares.
How ?
Attempt to remount by accessing the NFS.

AZP: retry modules load when automount fails - v1.14.x

---

src/ucp/rndv/rndv.c
test/gtest/ucp/test_ucp_am.cc

Fix mem types recognition for UCP AM rndv gtests. Currently all the tests are using host memory (even if cuda requested)

UCP/GTEST: Fix AM rndv memtypes

---

src/ucs/profile/profile_defs.h

ucs_profile_record prototype is below:
void ucs_profile_record(parameter0, parameter1, parameter2,
uint32_t param32, uint64_t param64, ...);
1) the 4th parameter's type is uint32_t
2) the 5th parameter's type is uint64_t
Marco parameter name should be aligned with ucs_profile_record parameters
```
ucs_profile_record prototype is below:
void ucs_profile_record(parameter0, parameter1, parameter2,
uint32_t param32, uint64_t param64, ...);
1) the 4th parameter's type is uint32_t
2) the 5th parameter's type is uint64_t
```

UCS/PROFILE: align macro parameter name to the semantic

---

bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java

Backport #9002 to fix CI failures

JAVA/TEST: Wait for active message to arrive before checking data - v1.14.x

---

src/ucp/rndv/proto_rndv.c

Increase the actual values for RTS and ACK software overheads.
The new values are based on the profiling data on the DGX cluster. The new values are supposed to improve protocol selection logic for D2D case.

UCP/PROTO: Adjust RTS and ACK software overheads

---

contrib/wireshark/rmpp.lua

Add RMPP dissector and register it to trigger on vendor specific payloads.
It useful to be able to decode perftest management datagram traffic.
Tested on Wireshark, Windows. Run:
```
ibdump -o /tmp/a.pcap
wireshark -Xlua_script:rmpp.lua /tmp/a.pcap
```
or copy the LUA file in the Wireshark plugins directory:
- `Help` -> `About Wireshark` -> `Folders` -> `Personal Lua plugins`

CONTRIB/WIRESHARK: Add IB Management Datagram RMPP LUA dissectors

---

src/ucp/tag/tag_recv.c

If rdesc is NULL(not found in unexpected list), it means that it's not found at all.

UCP/TAG: align comment with expected tag recv implementation

---

test/gtest/common/main.cc

Removed configuration of obsolete environment variable when running on valgrind.
The configuration field was removed by https://github.com/openucx/ucx/pull/6712.

GTEST/COMMON: Removed obsolete config from valgrind run.

---

src/ucp/tag/offload.c

No need to write code like below.
```C
if (worker->tm.offload.iface == NULL) {
ucs_assert(worker->tm.offload.iface        == NULL);
```

UCP/TAG: no need to assert after obvious check

---

src/ucs/sys/sys.c

From `man 3 sysconf`: "To distinguish an indeterminate limit from an error, set errno to zero before the call, and then check whether errno is nonzero when -1 is returned."
Fixes #9021

UCS/SYS: do not check errno if sysconf(3) was successful

---

src/ucp/wireup/wireup.c

Improve assertion failure message to:
```wireup.c:345  Assertion `0&&ep_addr_index < address->num_ep_addrs' failed: lane=1/3 tl_name_csum=0xd47a address_index=1 ep_addr_index=0 num_ep_addrs=1```
It had been observed that there can be addresses containing zero uct ep (`num_ep_addrs == 0`).
Try to dump as much details as possible when failure occurs.

UCP/WIREUP: Improve assert failure message when matching p2p lanes

---

test/gtest/ucp/test_ucp_sockaddr.cc

Make sure that `test_ucp_sockaddr` only ever use the first network interface address for `sockcm` connection.
Follow-up for issue [3411534](https://redmine.mellanox.com/issues/3411534)
TCP UCT interfaces only listen on the first IP address of a given network interface. When the interface has multiple IP addresses, the test can end up using the second address for `sockcm` and also for the subsequent TCP UCT interface connection which then fails.
Only add one address for a given address family / network interface.
Interface has two addresses:
```
inet 1.1.10.2/24 scope global ib0
valid_lft forever preferred_lft forever
inet 65.65.65.0/24 brd 65.65.65.255 scope global ib0
valid_lft forever preferred_lft forever
```
UCT TCP interface is listening on first address:
```
tcp        0      0 …
```

GTEST/UCP: Only use the first address of a given network interface

---

src/uct/ib/mlx5/dv/ib_mlx5_ifc.h

Cosmetic fix of header declaration.
The structures are listing bytes but are actually used as bits. It can get confusing if the declared hexadecimal bit position for reserved areas is not accurate.
List mismatched values:
`pahole --hex mlx5/dv/.libs/libuct_ib_la-ib_mlx5*o | grep reserved_at | grep -v "reserved_at_\([^\s\[]\+\).*\/\*\s\+0x\1\>`
```
uint8_t                    reserved_at_0[48];    /*     0  0x30 */
uint8_t                    reserved_at_0[64];    /*     0  0x40 */
uint8_t                    reserved_at_0[128];   /*     0  0x80 */
uint8_t                    reserved_at_122[1];   /*  0xc2   0x1 */
uint8_t                    reserved_at_128[3];   /*  0xc8   0x3 */
uint8_t                    reserved_at_130[3];   /*  0xd0   0x3 */
uint8_t                    reserved_at_138[3]; …
```

UCT/IB: Fix 'reserved_at_' displayed offsets

---

src/ucp/core/ucp_context.c

1. ucp_tl_md_t parameter isn't used at all.
2. ucp_tl_md_t object could be got from below type object: ucp_context_h & ucp_md_index_t

UCP: remove unnecessary ucp_tl_md_t paramter

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c

replay pending AM short request after EP reconfiguration
TCP has too large max_short value which is not supported by IB transport

UCP/WIREUP: replay pending AM short request after EP reconf

---

src/ucp/core/ucp_context.c

Merge below same code
```
out_free_resources:
uct_release_tl_resource_list(tl_resources);
err_free_resources:
uct_release_tl_resource_list(tl_resources);
```
```status``` should be UCS_OK if it passes through ```out_free_resources``` label.

UCP: refine release resource in ucp_add_tl_resources

---

src/ucp/core/ucp_context.c

It only checks users configurations simply here. It can't assert that there're existed resources.
Remove comment since the log explains very well.

UCP: update comment before detecting resources

---

.gitignore
Makefile.am
config/m4/compiler.m4
config/m4/lcov.m4
configure.ac

Adds LCOV-based html coverage report generation.
Helpful to confirm what code paths are run, or what could be missing from testing.
Use GCOV flags and LCOV.
Tested:
- tested without enabling: coverage disabled
- tested enabling without lcov/genhtml installed: failure
- tested `make distclean`: lcov files also removed
- tested `make lcov-clean`: generated files removed
Build like:
```
yum install lcov
mkdir build && cd build
../contrib/configure-devel --enable-gcov --enable-lcov
```
Run:
```
./test/gtest/gtest --gtest_filter=*test_ucp_sockaddr*
make lcov
<browser: file://<path>/ucx/build/lcov_data/index.html>
make lcov-clean
```

BUILD/FLAGS: Add LCOV report generation target

---

src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/copy/rocm_copy_md.h

add a parameter that allows to control whether to use dmabuf in rocm_copy md. The parameter is currently set by default to 'off', i.e. dmabuf will not be used. The plan is to turn it on by default starting from 1.16 release series.

UCT/ROCM: add parameter to control dmabuf usage

---

src/ucp/core/ucp_worker.c
src/ucp/proto/proto.c
src/ucp/proto/proto.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_single.c
src/ucp/rma/amo_offload.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c
src/ucp/wireup/wireup.c
test/gtest/common/main.cc

Activate UCP worker interface only for selected lanes.
Activating UCP worker interface only for selected lanes prevents of enabling of unnecessary UCT interfaces.
Which [enabling of unnecessary UCT interfaces] may have a negative impact on performance.

UCP/PROTO: Activate wiface only for selected lanes.

---

src/ucp/core/ucp_context.c

The current code outputs nothing for the unsupported memory type if there's no MD supports it.

UCP: update memory registration type info by MD

---

src/ucm/bistro/bistro_aarch64.c

Removed an extra summand from the size passed to the method allocating the code.
The maximum required code size is `max_code_len` (used by `ucm_bistro_relocate_code`) plus `sizeof(ucm_bistro_jmp_indirect_t)` (used by `ucm_bistro_init_jmp_indirect`).

UCM/BISTRO: Removed an extra summand from the allocated code size.

---

bindings/java/pom.xml.in
bindings/java/src/main/java/org/openucx/jucx/NativeLibs.java
bindings/java/src/main/native/Makefile.am
buildlib/az-helpers.sh
buildlib/azure-pipelines-release.yml
buildlib/jucx/jucx-build.yml
buildlib/jucx/jucx-publish.yml
buildlib/jucx/jucx-test.yml

Build and release ARM-based artifacts.
Part 3: Build JUCX on ARM
https://github.com/openucx/ucx/issues/8762
Cherry-pick the commit from https://github.com/openucx/ucx/pull/8896
(226fc81d9a7d255b1d5a2ef17a85c99a788b8a5a)

AZP/RELEASE: Add ARM release - part3 for v1.15.x

---

src/tools/perf/perftest_run.c

Changed fetch & add, swap and cswap window size to 32
When running `ucx_perftest` without setting -O, fetch & add, swap and cswap tests are currently waiting for a response after each send, affecting performance heavily compared to the `ib_atomic_bw` benchmark.

TOOLS/PERF/PERFTEST: Added a print for window size

---

.readthedocs.yaml
docs/.readthedoc.requirements.txt

Bump up the Python version used to build docs and limit the urllib3 ver.
Failure due to package version mismatch.

DOCS: bump up the Python ver for docs build

---

.readthedocs.yaml
docs/.readthedoc.requirements.txt

Bump up the Python version used to build docs and limit the urllib3 ver.
Failure due to package version mismatch.

DOCS: bump up the Python ver - v1.15.x

---

src/uct/rocm/copy/rocm_copy_ep.c

newer ROCm releases don't like locking host pinned memory (e.g. hipHostMalloc). 
If the pointer type is HSA_EXT_POINTER_TYPE_HSA, one can use the address directly, independent of whether the owner is CPU or GPU. This avoids the lock operation.
This fix will have to be ported to v1.15.x and v1.14.x as well.

UCT/ROCM: don't try to lock host pinned memory

---

buildlib/tools/zombie_killer.sh

Clean up leftover zombie processes.
The script runs hourly on all CI hosts, scheduled via crontab.
The PR serves exclusively for visibility and documentation reasons.

AZP: Kill zombie processes

---

src/uct/rocm/copy/rocm_copy_ep.c

newer ROCm releases don't like locking host pinned memory (e.g. hipHostMalloc). avoid the lock operation in the rocm_copy path.
(cherry picked from commit 745df301bb3420fa236f9291a56d224e60f412c7)

UCT/ROCM: don't try to lock host pinned memory -v1.15

---

src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h

[UCP/CORE: Removed unused sockaddr code](https://github.com/openucx/ucx/pull/8752) removed the sockaddr open iface mode, then it only support ```UCT_IFACE_OPEN_MODE_DEVICE``` open iface mode. This PR wrapper the iface open parameters into ```ucp_worker_iface_open```.

UCP: wrap function to open interface on specific device

---

src/ucp/core/ucp_worker.c
src/ucs/sys/topo/base/topo.c

fixes https://github.com/openucx/ucx/issues/9072
Bug
Fix perf estimation, Add NUMA latency only when it's relevant.
Results after applying the fix on Peter's setup:
**Old Proto**
<details>
```
+--------------+--------------+------------------------------+---------------------+-----------------------+
| API:          protocol layer                                                                             |
|              |              |       overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
| Test:         tag match bandwidth                                                                        |
+--------------+--------------+----------+---------+---------+----------+----------+-----------+-----------+
| Data layout:  (automatic) …
```

UCP/TOPO/BUG: Add memory distance only for relevant devices

---

src/ucp/core/ucp_worker.c
src/ucs/sys/topo/base/topo.c

Backport #9083 to 1.15.x branch

UCP/TOPO/BUG: Add memory distance only for relevant devices - v1.15.x

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h
test/gtest/uct/test_md.cc

If user sets preferred location of a range of managed memory allocation, then set sys_device attribute for that range to the preferred location. This allows protocols to make a better decision about where to stage managed memory by examining the sys_device associated with the range. The two cases to consider are:
1. memory = managed && preferred location = CPU, then use CPU staging buffers because managed memory buffers have backing pages that likely reside on the CPU. This decision helps avoid pcie traffic if staging buffer location was statically set to GPU. 
2. memory = managed && preferred location = GPUx, then use staging buffers on GPUx because managed memory buffers have backing pages that likely reside on that GPUx. This can reduce pcie traffic (if staging buffer location was …

UCT/CUDA: Set sys_dev to preferred location for managed mem

---

src/ucp/core/ucp_mm.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Backport #9077 to v1.15.x
No merge conflicts

UCT/IB/MLX5: Don't create KSM with atomic access unless needed - v1.15.x

---

src/ucs/datastruct/callbackq.c
src/ucs/datastruct/callbackq.h
test/gtest/ucs/test_callbackq.cc

Connection establishment and error handling progress callbacks (in UCT and UCS) add a callback per endpoint. 
In the existing implementation, remove_if function goes over the entire callbacks array, which can result in O(n^2) complexity during connect/disconnect/error handling flows.
This PR adds support for adding/removing callbacks by key, and next PRs will convert UCP/UCT to use this new API.
Keep oneshot callbacks in a hash table instead of an array.

UCS/CALLBACKQ/TEST: Add scalable oneshot callbacks

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_listener.c
src/ucp/core/ucp_listener.h
src/ucp/core/ucp_request.c
src/ucp/core/ucp_request.h
src/ucp/core/ucp_worker.c
src/ucp/rma/flush.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/uct/base/uct_iface.c
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
src/uct/ib/ud/base/ud_ep.c
src/uct/tcp/tcp_ep.c
test/gtest/ucp/test_ucp_sockaddr.cc

Improve scalability of connection establishment and error handling
Use the new callbackq oneshot API, to remove callbacks by key instead of going over the whole callbacks list.
Replaces #8812

UCP/UCT: Use the new callbackq oneshot API

---

src/ucp/proto/proto_am.inl
test/gtest/ucp/test_ucp_am.cc

Fix assert abort in `ucp_do_am_zcopy_multi`.
To avoid stack overflow ucs_alloca only permits 1200 bytes for echo memory allocating request.
But in `ucp_do_am_zcopy_multi`, the request memory size is greater than 1200 bytes in some case (tcp in AM sending with 64k data size).
Limit the maximum iov account based on UCS_ALLOCA_MAX_SIZE.

UCP: Limit the maximum iov account based on UCS_ALLOCA_MAX_SIZE

---

src/ucp/wireup/select.c
src/ucp/wireup/wireup.c

Fix ep reconfiguration error, which happens because of wrong ep config locality assignment
```
[ RUN      ] dcx/test_ucp_perf.envelope/25 <dc_x/amo_swap/cpu>
[1684918078.644718] [jazz02:71503:p-0]          wireup.c:1237 UCX  ERROR   old: am_lane 0 wireup_msg_lane <none> cm_lane <none> keepalive_lane <none> reachable_mds 0xf
[1684918078.644741] [jazz02:71503:p-0]          wireup.c:1247 UCX  ERROR   old: lane[0]:  0:dc_mlx5/mlx5_0:1.0 md[0]      -> md[3]/ib/sysdev[255] am am_bw#0
[1684918078.644748] [jazz02:71503:p-0]          wireup.c:1251 UCX  ERROR   old: err mode 0 flags 0x2
[1684918078.644753] [jazz02:71503:p-0]          wireup.c:1237 UCX  ERROR   new: am_lane 0 wireup_msg_lane <none> cm_lane <none> keepalive_lane <none> reachable_mds 0xf
[jazz02:71503:p-0:71611]      wireup.c:1589 …
```

UCP: Fix ep config locality assignment

---

src/ucp/proto/proto.c
src/ucp/proto/proto_multi.inl
src/ucp/rndv/rndv_am.c
src/ucp/stream/stream_multi.c
src/ucp/tag/eager_multi.c

Enable zero-copy for stream API protov2
- Added stream/multi/zcopy protocol definitions
- Added `ucp_proto_eager_zcopy_multi_common_send_func()`, reuse it in stream, tag/eager, and rndv/data protocols

UCP/PROTO/STREAM: Add stream/zcopy/multi protocol

---

src/ucm/util/log.c

- fixed potential overrun on log message gen
- there was potential issue on generation of long log message: due to incorrect strncat limit memory after buffer may be overwritten, issue could lead incorrect memory access
- changed strncat string limit

UCM/LOG: fixed potential overrun on log message gen

---

src/ucp/core/ucp_worker.h
src/ucp/proto/proto_select.c
src/ucp/wireup/wireup.c

This patch fixes the following problem:
1. ep is created using some ep config
2. Some protocols are selected for some operations and this enables progress for the affected lanes
3. ep is destroyed and progress is disabled for all corresponding ifaces
4. New ep is created with the same ep config used during step n1
5. Progress is not enabled, because protocols selection for these parameters (and ep config) was already done on step n2 (and corresponding protos are already hashed).

UCP/PROTOV2: Fix progress enabling for selected lanes

---

src/tools/info/type_info.c

Show sizes of different parts of ucp_request , to see what could be optimized

TOOLS/INFO: Print sizes of ucp_request_t fields

---

src/ucp/proto/proto_debug.c
src/ucp/proto/proto_select.c

- Go thru all ranges when obtain lane map for progress activation
- print atomic protocols info (need to also consider all existing ranges)
For atomic protocols Stub (invalid) protocol  can be chosen not only for the last range, so need to process other ranges as well.
Otherwise progress will not be enabled for the amo lanes and amo operations will take lots of time. Also atomic proto info output was not correct. After the fix it is like below:
```
[ RUN      ] dcx/test_ucp_perf.envelope/26 <dc_x/amo_swap/device>
[1684941213.249486] [jazz02:22262:p-1]   +---------------------------+--------------------------------------------------------------------------------------------+
[1684941213.249501] [jazz02:22262:p-1]   | perftest intra-node cfg#0 | fetching atomic by ucp_atomic_op*(multi) into …
```

UCP/PROTOV2: Activate progress for amo proto lanes

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h

Use indirect MR for cross-gvmi mkey instead of direct MR with DEVX UMEM.
Creating DEVX UMEM for large MR takes a lot of time.

UCT/DEVX: Indirect cross-gvmi mkey

---

buildlib/pr/main.yml
buildlib/pr/tests.yml
contrib/test_jenkins.sh
src/ucp/core/ucp_context.c
test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_atomic.cc
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/ucp/test_ucp_perf.cc
test/gtest/ucp/test_ucp_rma.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag.h
test/gtest/ucp/test_ucp_tag_match.cc
test/gtest/ucp/test_ucp_tag_mem_type.cc
test/gtest/ucp/test_ucp_tag_offload.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Enable protov2 by default
Just enable proto v2 by default and update corresponding test.
All wire-compat issues will be updated in other PRs

UCP/GTEST: Enable protov2 by default (wire-compat is not addressed)

---

src/tools/perf/perftest_run.c

Fix med output lines when running ucx_perftest with multiple threads
Build the output line in a string buffer and then print it at once

TOOLS/PERF: Enhance multi-thread test output

---

src/ucs/debug/debug.c

Fix failure to attach gdb-valgrind when multiple processes are running on the machine
Pass pid to gdb command

UCS/DEBUG: Specify pid when attaching valgrind debugger

---

README.md

Fix rdma-core note so it would not look like it's under "TCP" transport
Before:
After:

README: Fix rdma-core note placement

---

src/ucp/core/ucp_mm.inl
src/ucp/core/ucp_request.c
src/ucp/core/ucp_request.h
src/ucp/core/ucp_request.inl
src/ucp/dt/datatype_iter.c
src/ucp/dt/datatype_iter.h
src/ucp/dt/datatype_iter.inl
src/ucp/proto/proto_common.inl
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/offload.c
test/gtest/ucp/test_ucp_proto.cc

Optimization - no need to pass context parameter to ucp_memh_put() since it's already a field in memh

UCP/MM: Remove context param from ucp_memh_put()

---

buildlib/pr/main.yml
buildlib/tools/builds.sh

1. Add volume mapping for ROCM container.
2. Skip building CUDA with ROCM.
Failure to load env modules served as a canary, unearthing a bigger problem of dysfunctional ROCM job.

AZP: Fix ROCM building and testing

---

test/gtest/ucp/test_ucp_wireup.cc

Remove unused function argument

UCP/GTEST: Minor fix in wireup test

---

test/gtest/common/main.cc

Show logs only during test run and not during initialization

TEST/COMMON: Add env var to set log level just before test run

---

src/ucs/debug/debug.c
src/ucs/memory/rcache.c
src/ucs/memory/rcache_int.h

Fix deadlock when forked debugger is attached during an error in rcache operation

UCS/RCACHE: Disable atfork hooks before forking and attaching a debugger

---

test/gtest/uct/ib/test_ib_md.cc

exp verbs & ```MAX_INLINE_KLM_LIST``` have been removed at commit b6722f27

GTEST: remove exp verbs functionality

---

src/ucs/memory/memtype_cache.c
src/ucs/memory/memtype_cache.h

Change `ptrhead_lock` to spinlock for all operations related to memtype cache.
This change improves performance for protov2 logic.

UCP/UCS/UCT: Use spinlock for memtype cache

---

src/uct/cuda/gdr_copy/gdr_copy_iface.c

Changed the performance estimation of gdr_copy UCT interface, switching the bandwidth of get operation from shared to dedicated.
Experiments showed that the bandwidth of gdr_copy get operation remained maximum when simultaneously running the number of processes equal to the number of GPUs on the node.
The change of the performance estimation of gdr_copy UCT interface enhanced the protocol selection logic, preventing switching from Eager to Rendezvous protocol too early.

UCT/CUDA/GDR_COPY: Estimated BW of get operation is dedicated.

---

docs/doxygen/ucxdox
src/ucp/core/ucp_worker.c
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucs/Makefile.am
src/ucs/datastruct/callbackq.c
src/ucs/datastruct/callbackq.h
src/ucs/datastruct/callbackq_compat.h
src/uct/api/uct.h
src/uct/base/uct_iface.c
src/uct/base/uct_worker.c
src/uct/ib/base/ib_device.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/sm/scopy/base/scopy_ep.c
test/gtest/common/test.cc
test/gtest/ucs/test_callbackq.cc
test/gtest/uct/test_progress.cc

UCS/CALLBACKQ/TEST: Remove previous implementation of slowpath/oneshot

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Preparation for MD ops refactoring
ODP prefetch is not mlx5-specific. We can move it to the common code and remote the prefetch callback.

UCT/IB: Remove mem_prefetch operation

---

src/ucp/core/ucp_context.h
src/ucp/wireup/wireup.c
src/ucs/debug/assert.h

Allows to choose the lanes during the second initialization basing only on lanes that were already chosen when there is no CM.
Reverts recent change of epsilon for lanes selection.
To prevent reconfiguration issue in case of absence of CM.
See these bugs:
- https://redmine.mellanox.com/issues/3421919
- https://redmine.mellanox.com/issues/3451404
Recent epsilon change broke the wire compatibility, so it should be reverted.

UCP/WIREUP: Restrict using lanes that were not chosen previously

---

src/ucs/config/parser.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/ib/test_ib_xfer.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Fix remote access error when running ucx_perftest on ConnectX-5 like so:
`UCX_RNDV_THRESH=3074 UCX_IB_PCI_RELAXED_ORDERING=on UCX_NET_DEVICES=mlx5_0:1 UCX_RNDV_SCHEME=put_zcopy ./build-devel/src/tools/perf/ucx_perftest cascade1  -t ucp_am_bw  -s 4096 -w 0 -n 1 -O 1`
Avoid creating a relaxed-order key on DevX MD if KSM/atomic is not supported.
Currently, if KSM/atomic is not supported, we are sending the direct key, and the requestor will try to access it with atomic offset resulting in out-of-bounds access.
On the other hand, if strict ordering is enabled, the default key does not guarantee order.
Edit: Tested that the performance degradation fixed by #9077 is not happening again with this PR
cc @jithinjosepkl

UCT/IB/MLX5: Fix invalid access error to strict-order key with offset

---

src/ucp/dt/datatype_iter.c
src/ucp/rndv/rndv_am.c
test/gtest/ucp/test_ucp_tag_xfer.cc

Allows to define RNDV/AM scheme via RNDV_SCHEME control and applies this new option to protocols. 
Now RNDV/AM protos can be chosen even if RNDV_SCHEME is defined to different value.

UCP/RNDV: Fix "rndv through am" thresholds definition

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_worker.c
src/ucp/proto/proto_common.c
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h

Adjust information printing after enabling protov2 by default
- Print lanes configuration with UCX_LOG_LEVEL=info
- Don't print protov1 thresholds
- Print protov2 info by `ucx_info -u t -e` command

UCP/LOG: Fix printing protov2 lanes information

---

src/ucp/core/ucp_context.h
src/ucp/wireup/wireup.c
src/ucs/debug/assert.h

UCP: Restrict unselected lanes during second initialization - v1.15.x

---

src/uct/cuda/base/cuda_iface.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.c

Make sure that the error string is always non-null.
Crash report #9099.
Wrap the call and use similar default string in driver API as done in applicative API.

UCT/CUDA: Don't pass null pointer to logging function

---

src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.h

adjust the rocm_copy latency parameter and the d2h_thresh to lead to similar performance with v2 protocols as previously.

UCT/ROCM: adjust rocm_copy params

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml

Cherry-pick from https://github.com/openucx/ucx/pull/9176/
Update tags for cuda11 images, as older versions were removed from Dockerhub.
Also replaced non-existing Centos8 images with UBI8 alternative.

AZP: Update tags for cuda11 images - v1.15.x

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml

Update tags for cuda11 images, as older versions were removed from Dockerhub.
Also replaced non-existing Centos8 images with UBI8 alternative.

AZP: Update tags for cuda11 images

---

test/gtest/uct/test_sockaddr.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

In the UCT sockaddr code, make sure to yield the CPU when running on valgrind.
Valgrind serializes the OS threads anyways so we need to manually yield them to help in client/server senario involving multiple threads.
On the test subset evaluated, the duration is:
- 69 sec without fix
- 17 sec with the fix
Make small independent PRs and run/test them individually through CI as they could cause other issues.
Parameters: `jazz, SHARD=1/4, --gtest_filter=*tcp/test_uct_sockaddr*`
Without fix:
```
[2023-06-29 15:07:45] [==========] 95 tests from 5 test suites ran. (69270 ms total)
[2023-06-29 15:07:45] [  PASSED  ] 95 tests.
```
With fix:
```
[2023-06-29 15:57:34] [==========] 95 tests from 5 test suites ran. (17316 ms total)
[2023-06-29 15:57:34] [  PASSED  ] 95 tests.
```

GTEST: Yield CPU during UCT sockaddr tests

---

test/gtest/uct/ib/test_ib_md.cc

Reduced size of buffer registered on memory domain when running on Valgrind. 
The test is in the list of the most time consuming test.

GTEST/UCT/IB: Reduced size of buffer in test_ib_md.aligned

---

src/ucp/wireup/select.c
src/uct/base/uct_iface.c
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/ucp/test_ucp_wireup.cc

Backport of #9032 
To fix valgrind errors in #9179
Moving `uct_iface_is_reachable` check inside `uct_base_iface_is_reachable_v2` earlier makes valgrind happy.

UCT/IB: Added IB iface is_reachable_v2 - v1.15

---

debian/control.in

Add Replaces and Conflicts to mark that the main ucx package has the same role as the inbox package libucx0, libucx-dev and ucx-utils.
A versioned dependency in case we'll want to switch to packages with same names as the current inbox ones.

BUILD/DEBIAN: Remove inbox packages on install

---

src/uct/ib/mlx5/ib_mlx5_log.c

Before:
```
[r-hpc39:4177761:0:4177761] ib_mlx5_log.c:177  strides 1 next wqe 257 desc 0x7fd3edff0b9e [seg 0 bytes 8256 lkey 0x1621df addr 0x7fd3edff0c00] on mlx5_0:1/IB (synd 0x4 vend 0x32 hw_synd 0/146)
[r-hpc39:4177761:0:4177761] ib_mlx5_log.c:177  RC QP 0x12567 wqe[1]:
```
- Error type is missing
- Wrong WQE index is printed
- WQE details should be printed in the 2nd line
- Print "SRQ" instead of "RC"
After:
```
[r-hpc39:4184378:0:4184378] ib_mlx5_log.c:184  Local protection error on mlx5_0:1/IB (synd 0x4 vend 0x32 hw_synd 0/146)
[r-hpc39:4184378:0:4184378] ib_mlx5_log.c:184  SRQ QP 0x12639 wqe[1]: next_wqe 2 desc 0x7f1b495faade - [byte_count 8256 lkey 0x179d5d addr 0x7f1b495fab40] 
```

UCT/IB/MLX5: Fix error logging of responder error

---

src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/knem/knem_md.c
test/gtest/uct/ib/test_ib.cc

- Preparation for removing most of ib_md operations
- Remove unused is_sockaddr_accessible
- Make uct_md_ops_t  the super of uct_ib_md_ops_t, so uct_md_ops_t could be defined for verbs/dv/devx md implementations
- Move gross-gvmi import to devx
- Move cleanup operation to specific md

UCT/IB: Unify md operation and partial cleanup

---

src/tools/perf/lib/libperf_memory.c

Without this fix, KSM-atomic can be created without atomic access enabled. 
As a result, `rc_mlx5/test_uct_loopback.envelope/0` fails on rock cluster when running atomic tests.

TOOLS/PERF: Fix perftest memory access flags

---

contrib/test_jenkins.sh
src/ucm/bistro/bistro.c
src/ucm/bistro/bistro_aarch64.c
src/ucm/bistro/bistro_aarch64.h
src/ucm/bistro/bistro_int.h
src/ucm/bistro/bistro_x86_64.c
src/ucm/bistro/bistro_x86_64.h
src/ucm/util/sys.h
src/ucs/time/time.h
test/apps/Makefile.am
test/apps/test_hooks.c

Adds a locking step and grace period while patching the hooked functions to narrow existing race condition.
Race conditions could be seen when ucm bistro code is being invoked through a `dlopen()` call.
After inserting a lock, we wait for existing parallel code flows to complete. The lock itself is eventually removed so that we don't grow the patch size. For instance, including the first instruction after the syscall instruction under the patched area could lead to corruption, as a system call could take longer to complete than the grace period.
Added a test program to exercise the busy loop locking/unlocking sequence.
Built in release and tested:
- `while :; do ./test/apps/test_hooks || break; done`
- test on x86_64 (short and long patch) and aarch64
- repro with and without fix on …

UCM/BISTRO: Add locking step while hooking library functions

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fix memory corruption for relaxed memory order mode of the memory domain.
bug
Fix memh size calculation if relaxed order is enabled
The issue was observed on AMD EPYC 73F3 16-Core Processor CPU
where the `ucs_cpu_prefer_relaxed_order()` returns true.
The issue is that memory order is being calculated after the
memh size is determined. This causes memory corruption
via buffer overflow.
In relaxed order case memh must have two elements in mrs field
and because of the issue above only one was allocated.
The problem was detected and debugged using Address Sanitizer.

Fix memory corruption for relaxed memory order mode of the memory domain.

---

src/ucp/am/eager_multi.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h

unify palace to define same macro with same meaning

UCP/CORE: align macro for am frag first and mid meta len

---

src/ucp/core/ucp_mm.c
src/uct/base/uct_mem.c

1. use stack variable on hot function instead of allocating dynamically.
2. explicitly show the ```reg_md_map``` output is in hex format
3. remove unneeded blank line
4. output status with ```ucs_status_string(status)```

UCP/CORE: use stack varible on hot function ucp_mem_alloc

---

src/tools/perf/perftest_run.c

use same column width for the header output.

TOOLS/PERF: align AM Header size info width with other output

---

src/uct/ib/base/ib_md.c

Fix gtest failure:
```
[ RUN      ] ib/test_md.exported_mkey/0 <mlx5_0>
[     INFO ] allocated 0x7f44c92bf000 of size 192512
[rock21:15720:0:15720]       ib_md.c:908  Assertion `!(memh->flags & UCT_IB_MEM_FLAG_RELAXED_ORDERING)' failed
[rock21:15720:0:15720] Process frozen, press Enter to attach a debugger...
```

UCT/IB: Fix RELAXED_ORDERING assertion - v1.15.x

---

debian/control.in

Add Replaces and Conflicts to mark that the main ucx package has the same role as the inbox package libucx0, libucx-dev and ucx-utils.
A versioned dependency in case we'll want to switch to packages with same names as the current inbox ones.

BUILD/DEBIAN: Remove inbox packages on install - v1.15.x

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_common.h
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.h
src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
test/gtest/uct/ib/test_rc.cc

Unify function to check iface flush rkey.
make verbs & dv & devx to use one function to check iface flush rkey and related function.

UCT/IB: unify function to check flush rkey

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Removed redundant code from uct_cuda_ipc_md_open.
Fixed return values in uct_cuda_ipc_get_remote_cache and uct_cuda_ipc_is_peer_accessible.

UCT/CUDA/CUDA_IPC: Minor code improvements.

---

src/ucp/core/ucp_types.h
src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_proto.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Fix test failures:
```
[==========] Running 1 test from 1 test suite.
[----------] 1 test from ib/test_max_lanes
[ RUN      ] ib/test_max_lanes.16_lanes_reconf/3 <ib/tag,sa_data_v2,mt>
[     INFO ] Testing 2.1.5.4:0
[     INFO ] server listening on 2.1.5.4:40636
/labhome/yosefe/work/ucx/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1451: Failure
Expected equality of these values:
16
(int)ucp_ep_num_lanes(sender().ep())
Which is: 10
[     INFO ] ignoring error Connection reset by remote peer on endpoint 0x7f9bc0024000
[  FAILED  ] ib/test_max_lanes.16_lanes_reconf/3, where GetParam() = ib/tag,sa_data_v2,mt (2312 ms)
[----------] 1 test from ib/test_max_lanes (2312 ms total)
[==========] 1 test from …
```

UCP/WIREUP/TEST: Remove UCP_MAX_OP_MDS limit

---

src/ucp/proto/proto_multi.inl

Added assert catching invalid size of AM user header.

UCP/PROTO: Assert in case of invalid user header size.

---

configure.ac
contrib/ucx.in

Proposal to have a development based UCX modulefile.
Could not find an equivalent functionality, so when testing I need to make symlinks `ucx/lib -> my_ucx/rfs/lib`, and/or use environment variables (PATH, LD_PRELOAD, LIBRARY_PATH...) which is not handy.
Use a parametrized modulefile on some random non-dev machine like below.
```
./configure --prefix=`pwd`/rfs && make && make install
module load ./contrib/ucx-dev
module unload ucx-dev
```

CONTRIB/MODULEFILE: Provide development modulefile

---

test/gtest/ucp/test_ucp_am.cc

Skip `test_ucp_am_nbx_dts.short_bcopy_send` and `test_ucp_am_nbx_dts.zcopy_send` for UD transports in new proto infrastructure.
There are unstable reproducible failures during `roce on worker` jobs. The failures look like:
```
[ RUN      ] ud/test_ucp_am_nbx_dts.short_bcopy_send/0 <ud_v>
[1689063810.082094] [swx-rain04:448254:0]        ud_verbs.c:255  UCX  ERROR Invalid am_bcopy length: 5944 (expected: <= 4096)
[1689063820.115899] [swx-rain04:448254:0]       ucp_test.cc:280  UCX  ERROR operation returned error: Invalid parameter
```
```
[ RUN      ] udx/test_ucp_am_nbx_dts.zcopy_send/0 <ud_x>
[1689075622.531834] [swx-rain04:334703:0]         ud_mlx5.c:269  UCX  ERROR Invalid am_zcopy payload length: 5944 (expected: <= 4096)
[1689075632.566755] [swx-rain04:334703:0]       ucp_test.cc:280 …
```

GTEST/UCP: Skipped AM datatype test for ud_v and ud_x.

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/rc/verbs/rc_verbs_impl.h
test/gtest/uct/ib/test_rc.cc

Fix an issue [1] introduced by #9147
rc_verbs transport did not pass mr_id value in its address, so the initiator assumed mr_id==0, and did not apply an offset when issuing RDMA_WRITE operation to a KSM indirect key (with strict ordering)
[1]
On a machine with relaxed ordering enabled by default (AMD Milan):
```
[==========] Running 1 test from 1 test suite.
[----------] 1 test from rc/test_ucp_tag_match_rndv
[ RUN      ] rc/test_ucp_tag_match_rndv.bidir_multi_exp_post/0 <rc_v/rndv_auto>
[rock01:33412:0:33412] rc_verbs_iface.c:123  send completion with error: Work Request Flushed Error [qpn 0x1a5ef wrid 0x110 vendor_err 0xf4]
[rock01:33412:0:33412] rc_verbs_iface.c:123  [rqpn 0x1a5f1 dlid=20 sl=0 port=1 src_path_bits=0]
[rock01:33412:0:33412] …
```

UCT/IB: Fix remote access error with rc_verbs transport

---

test/gtest/ucp/test_ucp_tag_xfer.cc

Fix test failures that look like [1]
The issue happens when running with protov1 (test is skipped on protov2) and on swx-rain[03-04] machines on NUMA1.
In this case, am_lane is selected as mlx5_bond_0 and is not used as rma_bw lane, so it does not send the data.
[1]
```
[ RUN      ] ib/multi_rail_max.max_lanes/7 <ib/proto_v1>
[     INFO ] sender lane[0] : 68 bytes
[     INFO ] receiver lane[0] : 65 bytes
/labhome/yosefe/work/ucx/contrib/../test/gtest/ucp/test_ucp_tag_xfer.cc:1252: Failure
Expected: (bytes_sent) >= (50000 / ucs::test_time_multiplier()), actual: 133 vs 50000
[     INFO ] sender lane[1] : 0 bytes
[     INFO ] receiver lane[1] : 77312 bytes
...
[     INFO ] sender lane[15] : 0 bytes
[     INFO ] receiver lane[15] : 72704 bytes
[  FAILED  ] ib/multi_rail_max.max_lanes/7, where …
```

TEST/TAG: Fix multi_rail_max.max_lanes test

---

contrib/test_jenkins.sh

Removed extra arguments from gtest running on Valgrind.
The arguments are only required for performance check.

CONTRIB: Removed extra arguments from running gtest on valgrind.

---

src/ucp/core/ucp_am.c
src/ucp/core/ucp_am.h
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/proto/proto_multi.inl
test/gtest/ucp/test_ucp_am.cc

Added check for the length of user defined Active Message header.
`ucp_am_send_nbx` returns error if the length of the user header is greater than the length the maximum allowed header size, which is available via `ucp_worker_query`.
Added gtest.
Removed printing the return value of `ucp_am_max_header_size` in assert in method `ucp_proto_multi_max_payload`. Because the value is a feature of Active Message, but the method is not.
Follow up on https://github.com/openucx/ucx/pull/9211

UCP/CORE: Check length of user header in ucp_am_send_nbx.

---

src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c

Fix regression introduced by #9209 
Low byte of flush mkey (aka atomic mr_id) can be 0. When unified mode is used, UCP uses local iface query to know the length of ep address. If one of the peers atomic mr_id is 0 while another is not, UCP uses wrong ep address length and incorrectly unpacks UCP address.
Do not rely on the fact that low byte of flush mkey can't be zero

UCT/RC/VERBS: Fix ep address management

---

src/ucp/tag/probe.c

Reduce log level of probe call to avoid logs flooding 
Many applications use probe function in a polling mode waiting for some message to arrive. In this case the log is flooded by the following traces:
`probe_nb tag 0/0 remove=1`
So, it's better to print this trace with a poll log level and have requst level print only for success matching case. The print will be like:
`probe_nb tag 0/0 sender tag 0 length 4096 desc removed`

UCP/TAG: Reduce trace level of tag_probe

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/rc/verbs/rc_verbs_impl.h

First part of removing uct_ib_md operations such as reg_key, reg_atomic_key, etc.
Verbs/mlx5dv do not need special handling since they don't support indirect/atomic/exported keys.

UCT/IB/MLX5: Refactor verbs and mlx5dv memory domains operations

---

src/uct/ib/base/ib_device.c

None-zero flow_label value is used to affect the source udp port for none rc devx qp transport.
output flow_label value for debug purpose.

UCT/IB: add flow_label info in ah_attr output string

---

config/m4/gdrcopy.m4
src/uct/cuda/gdr_copy/Makefile.am

Removed CUDA flags and libs from GDR_COPY Makefile.
Added GDR_COPY_LIBS to distinguish LD_FLAGS and LIBADD.

UCT/CUDA/GDR_COPY: Cleaned up configure and makefile.

---

src/ucs/sys/sock.c
src/ucs/sys/sock.h
src/uct/tcp/tcp_iface.c

Support acquiring bond ad port number via bond subinterface.
When UCX works on VLAN subinterfce, the bond ad port number should be acquired from the lower bond interface,
such as `/sys/class/net/bond0.192/lower_bond0/bonding/ad_num_ports` rather than `/sys/class/net/bond0.192/bonding/ad_num_ports`. It's because the latter doesn't exist.
In the PR code, if `bonding/ad_num_ports` doesn't exist, re-try to access `lower_*/bonding/ad_num_ports`. If neither is found, then return 1.

UCS/SYS: support acquiring bond ad port number via bond subinterface

---

contrib/test_jenkins.sh
src/ucm/api/ucm.h
src/ucm/bistro/bistro_x86_64.c
src/ucm/util/sys.c
src/ucs/config/ucm_opts.c
test/gtest/ucm/cuda_hooks.cc

Fix conditional jump patching: push instruction sign-extends the 32-bit operand to 64-bit, so "push, push, ret" does not really jump to the destination address. Replace by indirect absolute jump "jmp *(%rip), .long addr"
To be backported for v1.15.x

UCM/BISTRO: Fix conditional jump translation

---

src/tools/info/tl_info.c
src/tools/perf/lib/libperf.c
src/uct/ib/base/ib_iface.c
test/gtest/uct/uct_test.cc

There's no need to specify CPU mask if using the default cpu mask.

UCT: no need to specify default CPU mask field without mask CPU

---

NEWS

Updated `NEWS` file filling 1.15.0-rc1 and 1.15.0-rc2. sections.
Added 1.14.1 section.

NEWS: Updated NEWS for 1.15.0-rc1 and 1.15.0-rc2.

---

test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_atomic.cc
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/ucp/test_ucp_rma.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag_match.cc
test/gtest/ucp/test_ucp_tag_offload.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Disables testing protov1 with valgrind.
To reduce CI valgrind time.

TEST: Disable protov1 testing with valgrind

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Next part of ib_md refactoring:
1. Don't use ops->reg_key for devx memory registration: Pass API registration params struct in multi-threaded registration flow
Full series in https://github.com/yosefe/ucx/tree/topic/refactor-ib-md

UCT/IB/MLX5: Partial refactoring in memory registration flow

---

src/ucs/type/float8.h
test/gtest/ucs/test_type.cc

Fix fp8 packing function
Values with exponent equal to `min_exp - 1` are packed (and therefore unpacked) with 0 exponent, while they need to be rounded up to `min_exp` value
E.g.:
UCP packs BW as `UCS_FP8_DECLARE_TYPE(BANDWIDTH, 512 * UCS_MBYTE, 4 * UCS_TBYTE)`
So, without this fix, values from  `[256 * UCS_MBYTE, 512 * UCS_MBYTE)` range are packed as zeroes.

UCP: Fix fp8 packing

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Show diagnostic message when `nvmlInit_v2` returns error.
This is a workaround when user runs application using UCX on an environment where libnvidia-ml.so is only available via stubs.
Please expand the Details section to find the difference in the behavior before and after the changes: 
<details>
Before:
```
$ LD_PRELOAD=<path_to_cuda>/lib64/stubs/libnvidia-ml.so ucx_info -d -t cuda_ipc
...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:
You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display …
```

UCT/CUDA/CUDA_IPC: Show diag message when nvmlInit fails.

---

test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Fix CI failures
There is a max md limitation for RMA BW lanes in protov1. Thus, it may not be possible to create 16 lanes with proto v1 if the node has many different transports/HCAs/NICs.
Also porting some other test fixes from master

GTEST/UCP: Fix CI failures - v1.15.x

---

test/gtest/ucp/test_ucp_tag_xfer.cc

Fix test output
This test failed in CI a couple of times (e.g. [here](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/66549/logs/852)). 
The correct info can give some hint (the issue is not reproduced manually)

GTEST/UCP: Fix msg info in mrail test

---

src/ucp/wireup/select.c

Fix one issue from #9248, introduced by #9210
cc @tonycurtis

UCP/WIREUP: Remove unused md_map variable to fix compilation

---

src/ucm/bistro/bistro_x86_64.c

Backport #9228 (without the test)
No merge conflicts

UCM/BISTRO: Fix conditional jump translation - v1.15.x

---

test/gtest/ucp/ucp_test.cc

Disable UD verbs UCP testing with valgrind.
To reduce valgrind CI time.

UCP/TEST: Disable UD verbs UCP testing with valgrind

---

src/uct/ib/base/ib_md.h
src/uct/ib/base/ib_verbs.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

```vhca_id``` is 16 bits. Update it.

UCT/IB: fix vhca_id length to be 16bits

---

src/tools/perf/lib/libperf_memory.c

Backport #9187 to v1.15.x to fix gtest/perf failure, no conflicts

TOOLS/PERF: Fix perftest memory access flags - v1.15.x

---

src/ucm/bistro/bistro.c

On RISC-V for an atomic update the destination must be naturally aligned with the size of the type. Since the destinations in this case are addresses of library functions to patch we cannot control the addresses. Fortunately the instructions must be aligned to a 16-bit alignment which also matches the potential size of the patch on RISC-V (compressed J instruction.)
For other architectures the size of patch is either 4 bytes (aarch64) or 2 bytes (x86-64) which are both handled by this patch.
Use atomic updates that match size of data to be updated
For RISC-V (and potentially for other architectures) the target address for atomic instructions should be naturally aligned with the size of the value.
Check the size of the value and use the atomic update function that matches the size.

UCM/BISTRO: Use appropriate atomic swap for size of update

---

src/ucp/wireup/select.c

-  Device num_paths coefficient should be applied after  fp8 pack/unpack. Otherwise the ratio effect maybe just hidden by fp8 inaccuracy
-  When deciding what rma bw lanes to drop, local bw value needs to be packed/unpacked in fp8 format to make sure both sides make the same decision
To avoid ep reconfiguration issues, because of assymetrical selection

UCP/ADDRV2: BW lanes selection fixes - v1.15.x

---

src/ucm/bistro/bistro.c

By using the static constant value we can be sure that the compiler will not generate an out of bounds error even for code that is unreachable.
e.g If sizeof(ucm_bistro_lock_t) == 4 the compiler generates an out of bounds error for the copy of bytes into the uint16_t (as 4 > 2) even though that code is unreachable.
Fixes: #9269
Using constant values for memcpy to avoid compiler error for unreachable code.
Fix for #9269
Using a constant value will prevent the out-of-bounds since the number of bytes is the same as the size of the type.

UCM/BISTRO: Use constant size in memcpy for ucm_bistro_modify_code

---

src/ucp/rma/flush.c

Fix test failure:
```
[ RUN      ] dcx/test_ucp_rma.get_nonblocking/3 <dc_x,cuda_copy,rocm_copy/user_memh>
[swx-rain04:256279:0:256279]       flush.c:232  Assertion `!req->send.flush.started_lanes' failed: req=0x5511540 flush started_lanes=0x1
```
Align the flush assertion check with:
https://github.com/openucx/ucx/blob/5221a5c2cf4265b6a83da3cd540f5d4898fa6f70/src/ucp/wireup/wireup.c#L1075-L1076

UCP/FLUSH: Align assertion check with connect_lane_to_iface logic

---

src/ucp/core/ucp_worker.c

Call `ucp_worker_mem_type_eps_destroy` instead of `ucp_worker_mem_type_eps_create` during `ucp_worker_cleanup` cleanup.

UCP/WORKER: Destroy mem_type EPs in case of worker creation error

---

NEWS

Updated NEWS file filling 1.15.0-rc3 sections.

NEWS: Updated NEWS for 1.15.0-rc3.

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h

Next step of ib md refactoring: 
- Rename mlx5 structs to mlx5_devx - since they are used only by devx and contain devx objects
- Pass memh struct size to ibv_reg_mr instead of keeping in on the md

UCT/IB/MLX5: Rename devx memh structs and pass size during allocation

---

buildlib/tools/builds.sh
src/tools/perf/lib/libperf.c
src/uct/cuda/base/cuda_iface.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/base/cuda_md.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/cuda/gdr_copy/gdr_copy_md.c

Created cuda_base.h to include the file in gdr_copy subcomponent to get rid of including of CUDA Runtime header.
Moved uct_cuda_base_query_devices to cuda_base.h.
Added uct_cuda_base_check_device_name to cuda_base.h, and moved macro UCT_CUDA_DEV_NAME from cuda_iface.h to cuda_iface.c to incapsulate the usage of the string constant.
Replaced `CUdeviceptr` by `unsigned long` to pass the type used by gdr copy API.
Replaced cuda_iface.h by cuda_md.h in gdr_copy_md.c because only a method from cuda_md.h is used.
The PR fixes build issues https://github.com/openucx/ucx/issues/9260 introduced by https://github.com/openucx/ucx/pull/9233, completing removing dependency on CUDA headers and libraries from gdr_copy subcomponent .

UCT/CUDA: Moved declaration of commonly used methods to the separate header file.

---

buildlib/azure-pipelines-perf.yml
buildlib/tools/perf_results.py

A pipeline for performance testing.
The pipeline should be started manually by adding the comment below under selected PRs:
`/azp run perf`
The test will fail if degradation of >5% will be detected (set by the `threshold` var).
A shared FS is used as a working directory, to prevent compiling on each node.
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=66519

AZP: Performance testing

---

src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_put.c
test/gtest/ucp/test_ucp_peer_failure.cc
test/gtest/ucp/test_ucp_sockaddr.cc

Define `abort()` functionality for `rndv/put_zcopy` protocol.
To fix that problem: [RM 3500817](https://redmine.mellanox.com/issues/3500817)

UCP/PROTO: Enable error handling for rndv/put_zcopy protocol

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h

Stores memory region address explicitly and separately of `ibv_mr` to avoid using `ibv_mr::addr` field.
For some reason `ibv_reg_dmabuf_mr` stores offset instead of address to the output structure (https://github.com/linux-rdma/rdma-core/blob/master/libibverbs/verbs.c#L411). So we need to avoid using it, since it leads to incorrect KSM creation.

UCT/IB: Avoid using ibv_mr::addr field

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucs/memory/rcache.c
src/ucs/memory/rcache.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.h
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/copy/rocm_copy_md.h

UCP rcache does not allow setting limits on max_size, max_regions, etc. As IB registrations may need to be limited for specific platforms (for example where amount memory that can be pinned is not unlimited), having user set limits on IB through UCP rcache is useful. The PR moves rcache params initialization logic to UCS and uses it in UCP rcache initialization.

UCP/RCACHE: Move rcache config to ucs and use for ucp_rcache

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Backport of #9282. To make this PR work the #9200 was also backported as part of this PR.
The `uct_ib_md_parse_reg_methods` was manually moved later because of deoendency on `memh_struct_size` which definition was moved in another place in #9200.

UCT/IB: avoid using ibv mr addr and fix relaxed order memh size - v1.15

---

src/ucs/datastruct/array.h

Include ucs_status in array.inl
Array class uses ucs_status_t

UCS/DATASTRUCT: Include ucs_status in array.inl

---

src/ucs/memory/memory_type.c
src/ucs/memory/memory_type.h

New memory allocation flags in UCT API, to enable device memory support.
Those flags will indicate the memory type and capabilities required by the memic feature.

UCT/API: Device memory allocation flags

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_worker.c
src/ucp/wireup/address.c
src/ucp/wireup/address.h
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_wireup.cc

If server device supports larger num_paths value than the client does, address packing may fail on the sever because of insufficient space (values larger than 1 require extra byte in the address). Need to check client's value in the unpacked address and make sure that server is also using the same value.

UCP/CM: Fix address packing on a server side

---

src/ucp/core/ucp_context.c
test/gtest/ucp/test_ucp_sockaddr.cc

Use sa data v2 format by default, because it is supported since UCX v1.12.0 and therefore should be compatible with UCX v1.[12-15]

UCP: Enable v2 sa data format

---

src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_wireup.cc

1. prefer selecting AUX transport with async active message callback
2. add gtest case to check select TCP as AUX transport.
The current criteria requires the tl has UCT_IFACE_FLAG_CB_ASYNC capability(UCP_ADDR_IFACE_FLAG_CB_ASYNC), it results that TCP can't be selected as AUX transport and rc_verbs can't exchange qp info when it's limited to use TCP and rc_verbs transport in connect-to-worker model.
This PR enables selecting the tls to be used as AUX transport if there's no tls has UCT_IFACE_FLAG_CB_ASYNC capability.

UCP/WIREUP: prefer AUX transport with async active message callback

---

src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/sm/base/sm_iface.c
src/uct/sm/base/sm_iface.h
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_iface.c
src/uct/tcp/tcp_sockcm.c
src/uct/ugni/base/ugni_iface.c
src/uct/ugni/base/ugni_iface.h
src/uct/ugni/smsg/ugni_smsg_iface.c

Convert all users of `uct_base_iface_is_reachable_v2()` to users of `uct_base_iface_is_reachable()` instead. This means that corresponding transports will now forward v1 is reachable calls to v2 is reachable actual implementations.
This is a step towards removing the v1 is reachable structure member.
Combine the scope and param validity checks in a common UCT base function, that transports can use to reduce duplication.
Build:
```
./contrib/configure-devel --prefix=$(pwd)/rfs \
--with-ugni=yes --with-verbs=yes --with-knem=yes \
--with-gdrcopy=yes --with-cuda=yes --with-rocm=yes --with-xpmem=yes
```

UCT/BASE: Remove base is reachable v2 forwarding function

---

src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/core/ucp_rkey.inl
src/ucp/rndv/proto_rndv.c
test/gtest/ucp/test_ucp_proto.cc

Enhanced remote protocol selection during rendezvous initialization, taking into account reachability of memory domains.
The reachability is checking during remote key unpacking.
Ignoring this information can lead to performance issues. E.g. RTR protocol can be mistakenly selected as a remote protocol, even if there is no valid MD for the protocol. Which leads to fallback to rndv/am protocol.

UCP/RNDV: Use only reachable MDs for protocol selection.

---

.clang-format
src/ucs/Makefile.am
src/ucs/datastruct/lru.c
src/ucs/datastruct/lru.h
test/gtest/Makefile.am
test/gtest/ucs/test_lru.cc

Added LRU cache infrastructure.
Satisfy various LRU needs in the system (for example, will be used for RCDC selection).

UCS/DATASTURCT: LRU cache

---

src/ucs/sys/topo/base/topo.c

This reverts commit f33c9aa514891a38a8d416960e6b2809a3bd7100.
This commit was merged by mistake. See [comment](https://github.com/openucx/ucx/pull/9307#issuecomment-1691472650).

Revert "UCS/DISTANCE: Update Intel Ice Lake sys root bandwidth"

---

src/uct/ugni/rdma/ugni_rdma_ep.c
src/uct/ugni/rdma/ugni_rdma_iface.c
src/uct/ugni/smsg/ugni_smsg_iface.c
src/uct/ugni/udt/ugni_udt_iface.h

Fix ugni build.
Seems ugni build just started failing even when using much older commits (tooling/env?).
Add needed include as close as possible to the error.
Failure seen on old 472553769d1cb6ba358d5bd4465cdadba63e4960 configured with `./contrib/configure-release --with-ugni=yes`
Failure (gcc 4.8.5):
```
CC       rdma/libuct_ugni_la-ugni_rdma_iface.lo
rdma/ugni_rdma_iface.c: In function ‘uct_ugni_rdma_iface_query’:
rdma/ugni_rdma_iface.c:98:48: error: ‘UCS_MBYTE’ undeclared (first use in this function)
iface_attr->bandwidth.dedicated = 6911.0 * UCS_MBYTE; /* bytes */
^
rdma/ugni_rdma_iface.c:98:48: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [rdma/libuct_ugni_la-ugni_rdma_iface.lo] Error 1
CC …
```

UCT/UGNI: Fix UGNI build

---

buildlib/tools/common.sh
contrib/test_jenkins.sh
contrib/test_namespace.sh

Move functions to common library.
Script clean up.
Use copy/paste first approach for that move.
Note: test_jenkins.sh now uses V=1 on make argument.

TEST/JENKINS: Move functions to buildlib/tools/common.sh

---

buildlib/azure-pipelines-perf.yml

Switch to an OAuth-based service connector instead of a personal token-based one.

AZP: OAuth-based service connector

---

NEWS

NEWS: Updated 1.15.0-rc4 section - v1.15.x

---

src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/rdmacm/rdmacm_cm.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c
src/uct/tcp/tcp_iface.c
src/uct/tcp/tcp_sockcm.c
src/uct/ugni/smsg/ugni_smsg_iface.c

Introducing uct_ep_is_connected API
In order to use it in later EP reconfiguration intersection (replace dst_rsc_index).

UCT/API: Introducing uct_ep_is_connected API

---

src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_wireup.cc

1. When deciding what rma bw lanes to drop, local bw value needs to be packed/unpacked in fp8 format to make sure both sides make the same decision
2. Device num_paths coefficient should be applied after fp8 pack/unpack. Otherwise the ratio effect maybe just hidden by fp8 inaccuracy

UCP: Fix ep reconfig because of fp8 inaccuracy

---

src/ucp/core/ucp_worker.c

Added logging of the distance calculation between device corresponding to UCP worker interface and device of the memory domain configured using SELECT_DISTANCE_MD.
The additional trace enhanced the existing debug output. E.g.:
```
ucp_worker.c:1234 UCX  TRACE distance between rc_mlx5/mlx5_0 and cuda_copy/GPU0 is 500ns 5100.00MB/s
```

UCP/CORE: Trace device distance calculation.

---

src/ucp/api/ucp.h
src/ucp/core/ucp_rkey.c

Add new API for remote key comparisons, proto v2 support only.
Add flag to request ucp_mem_map() to perform memory registration on specific range.
We need to compare remote keys to deduplicate received remote keys, > 0, = 0 or < 0
Usage:
```
ucp_rkey_compare_params_t params = {};
status = ucp_rkey_compare(context, rkey1, rkey2, &params, &result);
```

UCP/API: Add ucp_rkey_compare() API

---

src/uct/api/uct.h
src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c

Add `uct_rkey_compare()` API, relates to #9289.
We need to compare remote keys to deduplicate received remote keys, > 0, = 0 or < 0.
Usage:
```
uct_rkey_compare_params_t params = {};
status = uct_rkey_compare(context, rkey1, rkey2, &params, &result);
```

UCT/API: Add uct_rkey_compare() function

---

src/tools/info/sys_info.c
src/ucs/arch/x86_64/cpu.c

Define ucx_info name for Icelake CPUs.

TOOLS/INFO: Add Icelake CPU model name

---

src/ucp/proto/proto_init.c

Adds information about non-zero bias to the performance tree. e.g.
To make performance calculation process more clear.

UCP/PROTO: Add bias information to performance tree

---

src/tools/info/type_info.c
src/ucp/core/ucp_am.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_request.c
src/ucp/core/ucp_request.h
src/ucp/core/ucp_request.inl
src/ucp/dt/datatype_iter.inl
src/ucp/dt/dt_iov.c
src/ucp/dt/dt_iov.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.inl
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/stream/stream_recv.c
src/ucp/tag/eager_rcv.c
src/ucp/tag/offload.c
src/ucp/tag/offload.h
src/ucp/tag/tag_match.inl
src/ucp/tag/tag_recv.c
test/gtest/ucp/test_ucp_tag_match.cc

- Part of moving to protocols v2 - unify datatype processing code to use datatype_iter infra
- Simplify user memory handle support
- When protov1 is removed, more datatype handling code can be removed
- Replace recv.dt by recv.dt_iter
- Adjust protocols accordingly

UCP/DT/TEST: Use datatype_iter for receive requests

---

src/ucs/sys/topo/base/topo.c

`ucs_topo_get_distance_sysfs` returns default distance if sysfs path provider fails.
Plus tracing different code paths of `ucs_topo_get_distance_sysfs`.
The changes are needed to properly handle UCX usage on integrated GPUs.
Assert is triggered without these changes.

UCS/SYS/TOPO: Use default distance if sysfs path fails.

---

src/ucs/memory/numa.c
src/ucs/sys/sys.c

Make fail of numa node file opening silent.
There is no need to print error message here, because the case is handled on the next lines by returning `UCS_NUMA_NODE_DEFAULT`.

UCS/MEMORY: Make fail of numa node file opening silent.

---

src/ucp/core/ucp_worker.c

Reserve space for ep configurations. Otherwise there may be a race when main thread accesing ep config while UD async thread is extending it (by means of realloc)

UCP: Fix ep config race v1.15.x

---

src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h

Set primary device context as current context for the calling thread, if there is no active context during memory allocation.

UCT/CUDA/CUDA_COPY: Set device context within mem alloc.

---

src/uct/rocm/copy/rocm_copy_md.c

include sys/arch/cpu.h in rocm_copy_md.c 
A recent change in ucx left UCS_SYS_CACHE_LINE_SIZE not being set correctly in rocm_copy_md.c, which leads to an error at runtime (not at compile time). Including this header fixes the issue.

UCT/ROCM: include sys/arch/cpu.h

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/dt/dt.c

This approach caches memory registration for memory needing special treatment like CUDA. It also facilitates the removal of gdrcopy rcache, replacing it with UCP rcache.

UCP/MM: Use rcache in mem type pack

---

buildlib/az-helpers.sh

Cherry-picked from https://github.com/openucx/ucx/pull/9327.

AZP/RELEASE: Fix launch condition-v1.15.x
