src/uct/ib/base/ib_verbs.h
src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fix CI failures on BlueField nodes with new MLNX_OFED
```
2023-09-12T05:05:00.5641027Z [----------] 2 tests from ib/test_md_non_blocking
2023-09-12T05:05:00.5643035Z [ RUN      ] ib/test_md_non_blocking.reg_advise/0 <mlx5_0>
2023-09-12T05:05:00.5700802Z [1694495100.569296] [swx-rain04-bf1:3038825:4]           ib_md.c:292  UCX  ERROR ibv_reg_mr(address=0xaaaaf4b06390, length=1024, access=0x4f) failed: Operation not supported
2023-09-12T05:05:00.5704854Z /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/uct/test_md.cc:648: Failure
2023-09-12T05:05:00.5706559Z Error: Input/output error
2023-09-12T05:05:00.5720382Z /scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:366: Failure
2023-09-12T05:05:00.5723714Z Failed
2023-09-12T05:05:00.5725726Z Got 1 errors …
```

UCT/IB: Check dev_attr.odp_caps for ODP support

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Changed uct_ib_mlx5_devx_reg_ksm_data_contig signature to receive iova separately
Added iova parameter to `uct_ib_mlx5_devx_reg_ksm_data_contig`
So we can pass an `iova` which is different from `address` (which we would want to pass as 0 for zero-based mrs),
mapping 0 to some virtual address as needed by #9308

UCT/IB/MLX5/DV: Change uct_ib_mlx5_devx_reg_ksm_data_contig to accept address and iova

---

src/uct/cuda/base/cuda_iface.h

Removed extra parentheses.
Before:
```
cuda_copy_md.c:265  UCX  ERROR   cuMemAlloc_v2((CUdeviceptr*)address_p, *length_p)() failed: invalid device context
```
After:
```
cuda_copy_md.c:265  UCX  ERROR   cuMemAlloc_v2((CUdeviceptr*)address_p, *length_p) failed: invalid device context
```

UCT/CUDA/BASE: Removed extra parentheses.

---

buildlib/pr/go/go-test.yml
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_request.c
src/ucp/core/ucp_request.h
src/ucp/proto/proto_common.inl
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_rtr.c
test/gtest/ucp/test_ucp_peer_failure.cc

Enabling of RNDV through DC memory invalidation logic for protov2.
If DC transport is in use, without this logic receiver can still make RMA ops on the remote address even if sender ep is closed for some reason and memory is deregistered.
Pass corresponding memory invalidation flags during rkey packing and memory deregistration operations for RTS and RTR protocols.
The side effect of that change is simplification of the `abort()` logic for `rndv/get/zcopy` proto.
Replace the protocols `progress()` functions with wrapper that closes the sender EP that causes memory invalidation right before the first call of `rndv/get/zcopy` progress function. After that expect that receive operation will end with error before the second stage of the `rndv/get/zcopy` proto.

UCP/PROTOV2: Support memory invalidation for RNDV protocols through DC transport

---

src/ucp/rndv/rndv.c

Do not use recv ppln protocols if send user buffer is non-contig
fixes #9373

UCP/RNDV: Do not use recv ppln with generic send buf - v1.15.x

---

src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.h

Adds parameter (UCX_ROCM_COPY_SIGPOOL_MAX_ELEMS) to control the maximum number of elements in hsa signal pool (ucs_mpool_params). Changes from 1024 (default) to parameter.
Running the osu_bw benchmark beyond the standard 4MB message length for D-H communication leads to an error due to the uct/rocm_copy component running out of pre-allocated hsa-signals. Increasing the number of pre-allocated signals fixes the problem. This PR introduces a parameter for controlling the number of elements in the signal pool.
@edgargabriel

UCT/ROCM: Add parameter to control max elements in sigpool

---

src/ucp/api/ucp.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_rkey.c
test/gtest/ucp/test_ucp_mmap.cc

Add `ucp_rkey_compare()` implementation.
This is needed as part of symmetric remote key implementation.
Add forwarding of symmetric key registration flag, add the UCP comparison function and corresponding tests.
(will need #9349 to be merged for all tests to pass)

UCP/RKEY: Add ucp_rkey_compare() implementation and tests

---

bindings/go/src/examples/perftest/perftest.go

Add panic failures in case of errors.
Currently, Golang perftest client can end successfully even if endpoint error happened and all the requests returns error status.

BINDINGS/GO: Improve perftest error detection

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_verbs.h

To add check for ATOMIC_GLOB device attribute 
Devices with GLOB atomic support can make use of UCX framework

UCT/IB: Add check for ATOMIC_GLOB device attribute

---

src/uct/rocm/ipc/rocm_ipc_md.c

The ROCr runtime returns  in the hsa ptr_info function as the buffer size the exact length that was allocated. The length provided as an input to the rocm_ipc_pack_key routine might however have been adjusted by up to 64 bytes (if my math is correct) when using the rcache. So comparing the input buffer lengths vs. the size returned by the hsa_ptr_info function can be inaccurate. In addition, I do not see what the comparison of the 'expected' size vs. 'real' size gives us from the functionality perspective in this routine.
The issue was exposed while running the UCC testsuite with UCX master (with v2 protocols).  Not entirely sure why it was not a problem with previous ucx releases.

UCT/ROCM: don't check buffer size during key-packing

---

bindings/go/src/ucx/request.go

Set error status for non-pointer failed requests 
Currently we return `error` but don't update the status field inside returned request.

BINDINGS/GO: Set error status for failed requests

---

bindings/go/src/examples/perftest/perftest.go

Changes the counting of completed requests inside the go perftest logic to avoid hanging on the server side.
`progressWorker` call the `ucp_worker_progress` until it returns `0`. So during one `progressWorker` call we can increase `perfTest.numCompletedRequests` several times, but after end of the `WaitGroup.Wait()` we increase `i` only by `1`. So we can miss some completed requests if they were handled during one `progressWorker` call.
Also, the server side didn't take warmup iterations into attention.
Increase `i` by number of completed requests

BINDINGS/GO: Change perftest server completions counting logic

---

NEWS

NEWS: Added 1.15.0 section.

---

src/tools/info/tl_info.c
src/uct/api/v2/uct_v2.h
src/uct/base/uct_md.c

In order to remove the registration cache from gdrcopy transport, need UCP (rcache) to respect its memory registration alignment requirements.

UCT/API: Add reg_alignment

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/test_amo_add_xor.cc

Add symmetric key creation option for IB devx.
Needed to generate keys that are likely to compare as equal.
Use KSM key creation with offsetted atomic key creation.

UCT/IB: Add symmetric key creation

---

src/ucp/core/ucp_context.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/base/ib_verbs.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h
test/gtest/uct/test_mem.cc

Porting changes from https://github.com/openucx/ucx/pull/3559 with updated mlx5 / verbs API
To support the usage of MEMIC, enhancing atomic operations performance.
Using verbs mlx5 and devx libs

UCT/IB: Added support for device memory allocation (memic/rdma)

---

src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/tag_recv.c
src/ucp/tag/tag_rndv.c
test/gtest/ucp/test_ucp_tag_xfer.cc

Fix test failures like:
```
[ RUN      ] shm_ib/test_ucp_tag_stats.rndv_expected/0 <shm,ib>
[     INFO ] get_zcopy: 0 send_rtr: 1 rkey_ptr: 0
ucp/test_ucp_tag_xfer.cc:1110: Failure
Expected equality of these values:
1u
Which is: 1
rkey_ptr
Which is: 0
[  FAILED  ] shm_ib/test_ucp_tag_stats.rndv_expected/0, where GetParam() = shm,ib (270 ms)
```
The test failed because with protov2, when NIC bandwidth is high, xpmem is not selected for rendezvous.
Fixes internal issue [3581178](https://redmine.mellanox.com/issues/3581178)
* Add put_zcopy rndv statistics counter
* With protov2, expect either put_zcopy/get_zcopy/rkey_ptr to be selected when have xpmem or zcopy support.

UCP/RNDV/TEST: Fix rndv counters expectation for protov2

---

test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h

Skip 2 tests (`rocm_ipc/test_md.invalidate` and `rocm_ipc/test_md.rkey_compare`) in gtest for rocm_ipc as rocm_ipc only works with device memory. These tests pass with rocm_cpy.
@edgargabriel

GTEST/UCT: Skip invalidate and rkey_compare tests for rocm_ipc

---

src/uct/ib/base/ib_md.c

uct_ib_md_open_common() shouldn't overwrite md_attr flags.
We set some md_attr flags  before calling uct_ib_md_open_common() during querying device.

UCT/IB/MLX5/DV: fix md_attr flags

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml

The image `nvidia/cuda:11.4.3-devel-centos` is no longer available at DockerHub.

AZP: rm non-existing img reference

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml

CentOS 8 cuda images were removed from DockerHub.

AZP: rm Centos8 refs to DockerHub

---

src/uct/sm/scopy/base/scopy_iface.c

Adjusting the latency overhead for `knem` and `cma`.
To bring the performance estimation model closer to the real picture.
After the measurements on different platforms it was turned out that the real latency overhead for knem and cma transports are 0.5 usec. Method of measurements:
```
ucx_perftest localhost -t get -d memory -x knem -D zcopy -s 1
```

UCT/SCOPY: Adjust latency overhead

---

test/gtest/common/mem_buffer.cc

Adds condition based on HIP_VERSION for using `type` instead of `memoryType` in `hipPointerAttribute_t`.
From ROCm 5.5 onwards, `memoryType` is deprecated and `type` is used instead in `hipPointerAttribute_t`.

GTEST/COMMON: Add HIP_VERSION condition for ROCm compatibility

---

buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml

Porting https://github.com/openucx/ucx/pull/9422 to v1.15.x
CentOS 8 cuda images were removed from DockerHub.

AZP: rm Centos8 refs to DockerHub - v1.15.x

---

src/ucp/wireup/select.c
src/uct/sm/scopy/base/scopy_iface.c
src/uct/sm/scopy/base/scopy_iface.h
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c

Fix #9413 
Avoid adding extra lanes for accessing RDMA memory type

UCP/WIREUP: Don't select allocated memory access lanes for non-host

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/put_am.c
src/ucp/rma/rma.inl

Prefer native RMA and AMO protocols over emulations to avoid selections like below:
```
7543 [1696516991.258413] [jazz20:103988:0]   +----------------------------+-------------------------------------------------------------+
7544 [1696516991.258425] [jazz20:103988:0]   | 0x2d0aca0 intra-node cfg#2 | remote memory write by ucp_put* from host memory to host    |
7545 [1696516991.258428] [jazz20:103988:0]   +----------------------------+------------------------------------------+------------------+
7546 [1696516991.258430] [jazz20:103988:0]   |                     0..220 | short                                    | rc_mlx5/mlx5_0:1 |
7547 [1696516991.258433] [jazz20:103988:0]   |                   221..349 | software emulation                       | rc_mlx5/mlx5_0:1 |
7548 …
```

UCP/PROTOV2: Prefer native proto implementation

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/ib/test_ib_md.cc

Skip multi-threaded memory registration when symmetric key is requested and FW supports it.
Simplest approach, could later be improved to generate KSM(MT) with specific mkey_index using KSM wrapper introduced by related #9424.
Add corresponding tests and assertion.

UCT/IB: Skip multi-thread memory registration for symmetric key

---

src/ucp/dt/datatype_iter.inl
src/ucp/tag/offload.c

When tag offlowd SW rndv request complets in HW, UCP takes RVH from user buffer and handles it in SW. SW protocol copies memh from recv req (in `ucp_proto_rndv_receive_start`/`ucp_datatype_iter_move`), but this memh is later released in `ucp_tag_offload_rndv_cb`. Thus, need to deregister recv req memh in `ucp_tag_offload_rndv_cb` before handling this req in SW (`ucp_tag_rndv_matched`).
Fixes [RM3602178](https://redmine.mellanox.com/issues/3602178) ( (internal link))

UCP/HWTM: Fix memory corruption by proper memh handling in rndv cb

---

src/ucp/core/ucp_request.inl
src/ucp/tag/tag_recv.c
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag.h
test/gtest/ucp/test_ucp_tag_match.cc

Return `tag_info` data on immediate completion when requested.
Fixes #9425 
Match existing documentation:
`NULL - The receive operation was completed immediately. In this case, if param->recv_info.tag_info is specified in the param, the value to which it points is updated with the information about the received message.`
Populate field on immediate completion when receive info is passed and immediate completion is not prevented.

UCP/TAG: Populate tag_info on immediate completion

---

src/uct/sm/mm/base/mm_iface.c

I found that osu_gatherv sometimes hangs when using UCX_TLS=sm in a single aarch64 node (Kunpeng 920). 
Command is below:
`mpirun -np 128 -x UCX_TLS=sm osu_gatherv -m 65536:65535`
When I reduced the fifo size, the probability increased.
`mpirun -np 128 -x UCX_TLS=sm -x UCX_MM_FIFO_SIZE=2 osu_gatherv -m 65536:65535`
When receiver invoked am callback return not OK in function `uct_mm_iface_process_recv`, here ucx will assign a new receive descriptor to FIFO element and update fifo tail. In aarch64 machine, the sender may get the new tail while pack data to a old FIFO element.
memory fence should be added before tail update.

UCT/MM: fix possible sending in out-of-order.

---

test/gtest/common/mem_buffer.cc

Adds condition based on HIP_VERSION for using `type` instead of `memoryType` in `hipPointerAttribute_t`.
From ROCm 5.5 onwards, `memoryType` is deprecated and `type` is used instead in `hipPointerAttribute_t`.

(v1.15.x) GTEST/COMMON: Add HIP_VERSION condition for ROCm compatibility

---

buildlib/azure-pipelines-perf.yml
buildlib/azure-pipelines-pr.yml
buildlib/tools/perf-common.yml

Save PerfX log file per job. 
Preserve as artifacts and show in the build log.
perfx.log got overwritten, so only the last one was handled.

AZP: Handle multiple log files

---

src/ucp/core/ucp_worker.c
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl

When the ucp_ep_config array is extended by the async thread, the main thread may modify ep_config->proto_select.hash by adding new protocol selections. These newly added elements will not be reflected in the new ep_config_array and will be released together with the old ep_config array. Using a pointer to the hash in proto_select fixes this issue because the hash will persist in memory regardless of ep_config array reallocations.
Fixes [RM3633376](https://redmine.mellanox.com/issues/3633376) (internal link)

UCP: Fix proto select hash race

---

src/ucp/wireup/select.c

Minor fix in RMA selection code (affects exported memh feature only)
found by code-review

UCP: Fix RMA lanes selection for exported memh

---

src/ucs/config/parser.c
src/ucs/config/parser.h
src/ucs/sys/init.c

UCS/CONFIG: Cleanup the configuration parser after profiler cleanup

---

src/ucs/Makefile.am
src/ucs/memory/numa.c
src/ucs/memory/numa.h
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h

Detect the case when two devices have no common PCI root but belong to one NUMA.
BW in cross-NUMA and intra-NUMA cases differs significantly.
Check `numa_node` file content inside PCI device path.

UCS/TOPO: Calculate distance for common NUMA node separately

---

src/ucp/core/ucp_context.c
test/gtest/ucp/test_ucp_rma.cc
test/gtest/ucp/test_ucp_wireup.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h

Use strong fence with proto V2
With proto v2 UCP can use different RMA lanes for different sizes, thus fence can't be a no-op

UCP/GTEST: Use strong fence with protov2

---

configure.ac
ucx.spec.in

Bump version to 1.17.0 after creating v1.16.x branch

CONFIG/SPEC: Bump version to 1.17.0

---

config/m4/rocm.m4

Add `-D__HIP_PLATFORM_AMD__` to HIP_CPPFLAGS as `-D__HIP_PLATFORM_HCC__` is removed in ROCm 6.0, which affects configure checks for hip_runtime and breaks UCX gtest for ROCm.
We keep `-D__HIP_PLATFORM_HCC__` for compatibility with older ROCm versions.

(v1.15.x) CONFIGURE/ROCM: modify HIP_CPPFLAGS for ROCm 6.0

---

config/m4/rocm.m4

Add `-D__HIP_PLATFORM_AMD__` to HIP_CPPFLAGS as `-D__HIP_PLATFORM_HCC__` is removed in ROCm 6.0, which affects configure checks for hip_runtime and breaks UCX gtest for ROCm.
We keep `-D__HIP_PLATFORM_HCC__` for compatibility with older ROCm versions.

(v1.16.x) CONFIGURE/ROCM: modify HIP_CPPFLAGS for ROCm 6.0

---

buildlib/az-helpers.sh

Ensure that 'nv_peer_mem' kernel module is loaded before running GPU tests.
1. Check if the module is loaded.
2. Exit if not, print debug info.
3. Skip the check when running from Docker.

AZP: Ensure nv_peer_mem loaded on GPU

---

src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rkey_ptr.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c

Changes the way how do we calculate ACK performance for multi protocols. Previously we simply added the ack perf to the perf of the proto, but the calculating it as the parallel stages (choosing the slowest stage in case of multi perf type) seems the correct way to do that.
To improve perf estimations for RNDV protos. Without this patch multi benchmarks with many PPN prefer RNDV through AM instead of pure RNDV.
| Before| After|
|--------|--------|
| ![image](https://github.com/openucx/ucx/assets/22097249/c1ec1df2-0b83-47e7-90a1-38f5686a21b4) | ![image](https://github.com/openucx/ucx/assets/22097249/382b986f-c507-41d9-bc14-4686c547e34a)|

UCP/PROTO: Calculate perf for ack messages as parallel stages

---

config/m4/rocm.m4

Add `-D__HIP_PLATFORM_AMD__` to HIP_CPPFLAGS as `-D__HIP_PLATFORM_HCC__` is removed in ROCm 6.0, which affects configure checks for hip_runtime and breaks UCX gtest for ROCm.
We keep `-D__HIP_PLATFORM_HCC__` for compatibility with older ROCm versions.

CONFIGURE/ROCM: modify HIP_CPPFLAGS for ROCm 6.0

---

src/ucp/proto/proto_reconfig.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/test_md.cc

UCT/IB/MLX5/DV: disable device memory if atomics are not available
UCP/PROTO: changed proto_reconfig assert to ucs_error
Disabled device memory if atomics are not available and replaced proto_reconfig assert to `ucs_error` informative log so `UCX` won't crash if some of the protocols are missing.
Fixing the following bug:
when memic is available and atomics are not supported by FW, proto tries to create atomic `rkey` and fails

UCT/IB/MLX5/DV: disable device memory if atomics are not available

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.inl
src/ucs/memory/rcache.c
src/ucs/memory/rcache.h
src/ucs/memory/rcache.inl
src/ucs/memory/rcache_int.h
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/sm/mm/xpmem/mm_xpmem.c
test/gtest/common/test_obj_size.cc
test/gtest/ucs/test_rcache.cc

Some transports (e.g. gdrcopy) require special alignment. 
Regions in the UCP rcache will select the maximum alignment from the MD registrations they comprise. When merging regions, the rcache will also choose the maximum alignment.

UCS/RCACHE: Add support for dynamic region alignment

---

src/ucp/proto/proto_reconfig.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/test_md.cc

Backport https://github.com/openucx/ucx/pull/9459
UCP/PROTO: changed proto_reconfig assert to ucs_error
UCT/IB/MLX5/DV: added uct_ib_devx_get_atomic_mr_type which set to default for dm
(cherry picked from commit 0e9d05283920881e9e3b03bebe5eab718bd179ff)

UCT/IB/MLX5/DV: disable device memory if atomics are not available - v1.16.x

---

buildlib/azure-pipelines-perf.yml

Reduce user interference with perf testing CI .
1. Warn active users.
2. DIsconect SSH sessions.
3. Reminder once a minute till CI testing stops.
Also added a warning MOTD.

AZP: Reduce user interference with perf testing CI

---

buildlib/azure-pipelines-perf.yml

Retain working dirs for the three most recent builds for manual repro attempts.
Depends on https://github.com/openucx/ucx/pull/9431

AZP: Retain env for manual repro

---

src/ucp/am/eager_multi.c
src/ucp/stream/stream_multi.c

UCP/EAGER/STREAM: Fix missing proto initializations

---

src/ucp/wireup/select.c

Select RMA lanes with regard to local device distance BW.
Fix issue [3656632](https://redmine.mellanox.com/issues/3656632) (internal link) on master branch.

UCP/WIREUP: Calculate RMA score with regard to local distance BW

---

src/ucs/sys/topo/base/topo.c

Detect same NUMA distance when devices has common sys root part only.
When devices have distance distance closer then sys_root and pci (e.g. PXB), NUMA distance is reported, when the right thing is to report default distance.

UCS/TOPO: Report NUMA node distance for sys root only

---

src/ucp/wireup/wireup.c

Wireup ack can only be sent with wireup lane If AM lane is not requested
Fixes [3655964](https://redmine.mellanox.com/issues/3655964) (internal link)
Problem popped up after #9445, because with that fix AM is not always selected (if not requested)

UCP: Fix lane selection for wireup ack message

---

src/uct/ib/mlx5/ib_mlx5.inl

using `vst4q_u64` vector copy (SIMD) for arm neon instead of `int16x8_t` word copy in `bf_copy_bb`
Matching [rdma-core ](https://github.com/linux-rdma/rdma-core/blob/f16330dc0e079a6670a31fa54e89abb52994fd9d/util/mmio.h#L215) blueflame copy

UCT/IB/MLX5: using vst4q_u64 vector copy (SIMD) for arm neon

---

src/uct/tcp/tcp.h
src/uct/tcp/tcp_iface.c
src/uct/tcp/tcp_md.c

Filtered out bridge devices.
Added control `UCX_TCP_BRIDGE_DEVICES`. The default value is set to `no`. It means that the function querying the list of available TCP devices doesn't include bridge devices to the list.
The lane associated with the bridge device may be selected for transferring data. However, the lane is unreachable.

UCT/TCP: Filtered out bridge devices.

---

src/uct/tcp/tcp.h
src/uct/tcp/tcp_iface.c
src/uct/tcp/tcp_md.c

Filtered out bridge devices.
Added control UCX_TCP_BRIDGE_DEVICES. The default value is set to no. It means that the function querying the list of available TCP devices doesn't include bridge devices to the list.
The lane associated with the bridge device may be selected for transferring data. However, the lane is unreachable.
Cherry-picked #9475

UCT/TCP: Filtered out bridge devices - v1.16.x

---

src/tools/perf/lib/libperf.c
src/tools/perf/lib/libperf_int.h
src/tools/perf/lib/libperf_thread.c
src/tools/perf/lib/ucp_tests.cc
src/tools/perf/perftest_params.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Removing usage of allocators in ucp perftest.
So adding new memory types will be easier as memory handling will be managed only through UCP / UCT api's
perftest object will have a pointer to `memcpy` function, anything else related to allocators will be used only in UCT perftest.

TOOLS/PERF: make ucp perftest independent from allocators

---

src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c

Set reverse_sl to the same value of sl (service level) configured by `UCX_IB_SL` env.
Currently on certain device configurations reverse_sl is 0 if not set.

UCT/IB/DC: add env for reverse_sl (default: same value of sl)

---

src/ucp/rndv/proto_rndv.c

Fixed rendezvous protocol query.
Fixed proto info output.
Before:
```
+---------------------------+--------------------------------------------------------------+
| perftest intra-node cfg#2 | active message by ucp_am_send* from host memory              |
+---------------------------+-----------------------------------------------+--------------+
|                     0..92 | short                                         | sysv/memory  |
|                  93..2824 | copy-in                                       | sysv/memory  |
|                 2825..inf | (?) rendezvous copy from mapped remote memory | xpmem/memory |
+---------------------------+-----------------------------------------------+--------------+
+---------------------------+-------------------------------------------------- …
```

UCP/RNDV: Fixed rendezvous protocol query.

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_init.c

- Remove overheads that are applicable only for non-empty messages for 0 size estimations.
- Enable short protocol for non-host memory types on empty messages
To improve performance prediction model.

UCP/PROTO: Eliminate copy and bandwidth overheads for empty messages

---

contrib/squash_commit.sh

Add a script to use for squashing branches after PR approval.
There can be one or more commits interleaved with zero or more merges. It's easier to use a script to do squashing.
Auto-detect most recent base point. The commit message can later be amended. Usage:
```
./contrib/squash_commit.sh -h
usage: ./ucx_commit/contrib/squash_commit.sh -m <commit_message> [-r <remote_branch>] [-p <new_parent>]
Arguments
-m <commit_message>     commit message to use
-r <remote_branch>      upstream master branch to merge into
-p <new_parent>         new base to use for squashed commit
Sample
./ucx_commit/contrib/squash_commit.sh -m "Commit message" -r upstream/master
./ucx_commit/contrib/squash_commit.sh -m "Commit message" -p adef30
```

CONTRIB: Add squash script to use after PR approval

---

src/ucp/rma/flush.c

With PCI relaxed order flush with remote does not always guarantee correct ordering (i.e. seems previous write is not completed after the flush). To be reconsidered and fixed in UCT
Fixes [3674158](https://redmine.mellanox.com/issues/3674158) (internal link)

UCP: Fix strong fence to always ensure ordering - 1.16.x

---

src/uct/cuda/Makefile.am
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Replace remaining references to CUDA runtime API to reduce dependencies.

UCT/CUDA: move rt api -> drv api

---

src/uct/rocm/copy/rocm_copy_md.c

remove the rcache_addr_align parameter from rocm/copy md, since the parameter doesn't exist anymore.

UCT/ROCM: remove rcache_addr_align parameter

---

bindings/go/tests/endpoint_test.go

UCX may choose a protocol which uses cuda_copy transport during receiving message. Set CUDA context in AM receive handler to fix inactive CUDA context issue.

BINDINGS/GO/TESTS: Fixed inactive CUDA context failure.

---

src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/rndv/proto_rndv.c

Move additional multi-fragment overheads to multi-fragment ranges.
Currently multi-fragmented protocols changes perf by applying the fragment size to the performance function linear factor even for 1 fragment range which is wrong. We should calculate one-fragment perf using the provided untouched data for all the protocols and apply the additional PPLN overheads on multi-frag ranges.

UCP/PROTO: Do not change multi-fragment perf for 1 fragment range

---

bindings/go/Makefile.am

Fixed `make install` command failure with enabled GO UCX bindings.
```
/usr/bin/install: cannot stat '/root/ucx/build/bindings/go/.libs/tmp/goperftest': No such file or directory
```

BINDINGS/GO: Fixed make install.

---

src/ucp/core/ucp_types.h
test/gtest/ucp/test_ucp_mmap.cc

Check rkey and topo distance difference doesn't cross `UCS_FP8_PRECISION` ratio.
Now test uses hardcoded values, but with big BW difference can be more then 600 MB/s
Can be tested on rock partition by the following command: `GTEST_FILTER=*rc/test_ucp_mmap.reg_mem_type/0* ./test/gtest/gtest`

TEST/RKEY: Check rkey distance with accordance to fp8 precision

---

src/ucp/core/ucp_mm.c
src/ucs/sys/math.h
test/gtest/ucp/test_ucp_rma.cc

With the addition of the dynamic alignment feature, MDs now specify alignment requirements and expect the registering region to align accordingly. By default, UCP relies on rcache to align the region. However, in cases where rcache is disabled, UCP should manage alignment on its own.

UCP/MM: Fix alignment when rcache disabled

---

src/ucp/core/ucp_am.c
test/gtest/ucp/test_ucp_am.cc

Fix the issue introduced recently in https://github.com/openucx/ucx/pull/9415 
The issue happens when registering AM handlers out of message ID order. For example, when client registers AM handlers in the order IDs [3, 4, 1], then only the last ID remains in the AM handlers array. Handlers [3, 4] are sliced away, which is manifested as
```
ucp_am.c:234  UCX  WARN  UCP Active Message was received with id : 3, but there is no registered callback for that id
ucp_am.c:234  UCX  WARN  UCP Active Message was received with id : 4, but there is no registered callback for that id
```
This happens because in current logic we unconditionally resize an array of AM handlers when adding new element to it. This works in most of the cases, when we register handlers ordered by message ID. However, if we …

UCP/AM: Allow AM handlers registration in any order

---

src/uct/cuda/base/cuda_iface.c

Avoid using locality information of cuda device 0 if no active context detected.
Usage of 0 device breaks the wire compatibility because master now detect the distance to the CUDA device even if there is no active context. But older version cannot detect such distance and set it to default now which causes incompatibility.
Fixes the following issue (reproduces only on swx-rdmz-ucx-gpu-01): https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=72705&view=logs&j=fd287c5c-dcf2-52b8-cd0f-25b007d2717e&t=64aaf147-dfa5-5aa9-0220-0479128fc8a3

UCT/CUDA/BASE: Do not use cuda device 0 if no context is active

---

src/ucp/wireup/select.c

Add `ucp_wireup_md_flags` entry for `UCT_MD_FLAG_INVALIDATE_RMA`
`ucp_wireup_add_rma_bw_lanes` can set `UCT_MD_FLAG_INVALIDATE_RMA` in `criteria.local_md_flags` and if there is no such flag for some MD, the `ucp_wireup_get_missing_flag_desc` would try to access it's definition through index in `ucp_wireup_md_flags`.
Found by ASAN.

UCP/WIREUP: Define UCT_MD_FLAG_INVALIDATE_RMA description

---

config/m4/compiler.m4

Introduces `--enable-asan` option which checks the Address Sanitizer availability and passes corresponding flags during compilation and linkage.
Address Sanitizer is significantly faster then Valgrind and can detect more types of memory errors. For details go to the link: https://github.com/google/sanitizers/wiki/AddressSanitizerComparisonOfMemoryTools
Testing with GCC-7.2.0 on RHEL 7.6 detected false-positive buffer underflow errors during `ucs_container_of` call.
Testing with GCC-11 on Ubuntu-22.04 detected the following issues:
- https://github.com/openucx/ucx/pull/9518
- https://github.com/openucx/ucx/pull/9527
- https://github.com/openucx/ucx/pull/9534
So it is important to test with fresh OS/compiler.

BUILD/CONFIG: Introduce Address Sanitizer flag option

---

test/gtest/ucm/cuda_hooks.cc

TEST/UCM/CUDA: Include assert header

---

src/ucp/core/ucp_mm.c
src/ucs/memory/rcache.c
src/ucs/memory/rcache.h
test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/uct/test_mem.cc

The UCP rcache currently depends on UCP synchronization, making the pgt_lock unreliable for memory event handling.
Always queue event's inv_q to handle it by upcoming region creation process.

UCS/RCACHE: Synchronize events

---

test/gtest/uct/test_md.cc

Allocate `rkey_packed_size` rkey.
To prevent buffer overflow during `uct_md_mkey_pack_v2` reported by ASAN check.

TEST/UCT/MD: Prevent rkey buffer overflow

---

bindings/java/src/main/native/Makefile.am
buildlib/jucx/jucx-publish.yml

Fix JUCX package publishing, so it will include support for ARM.
1. Copy both libraries into the resources folder to match the resources section in pom.xml.
2. Copy specific files, not a wildcard, so `make `will fail if one of them is missing.
3. Added a validation target to check the final Jar before publishing.

AZP/RELEASE: Fix JUCX with ARM build

---

src/ucp/core/ucp_mm.c

Imported rcache caching memory registrations of foreign host, it shouldn't be invalidated basing on memory events happening in local host.

UCP/MM: Disable memory events for imported rcache

---

test/gtest/ucp/test_ucp_tag_xfer.cc

Make message size divisible to page size.
`aligned_alloc` requires that allocated size should be divisible to alignment
[cppreference](https://en.cppreference.com/w/c/memory/aligned_alloc):
> Allocate size bytes of uninitialized storage whose alignment is specified by alignment. The size parameter must be an integral multiple of alignment.
Found by ASAN.

TEST/UCP: Meet aligned_alloc requirements for requested size

---

src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
src/uct/ib/ud/accel/ud_mlx5.c
src/uct/ib/ud/verbs/ud_verbs.c

Fixing code duplication when setting reverse_sl in different ib transports.
PR https://github.com/openucx/ucx/pull/9489 was already merged

UCT/IB: fixed reverse_sl feature - removed code-dup and parentheses

---

src/ucs/sys/sys.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c

Error handling is not always needed by the UCT user (e.g. MPI apps). Ignore ka initialization failure, which enables cuda-ipc multinode for MPI flows.

UCT/CUDA-IPC: Ignore ka failure during ep creation

---

contrib/test_jenkins.sh
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_devx.c

Support FLID-based IB router
* Change reachability logic to consider FLID
* When creating address vector or sending DC grant, use FLID instead of direct LID, if applicable
[Design doc (internal link)](https://confluence.nvidia.com/pages/viewpage.action?pageId=2423189486)
Replaces #9548

UCT/IB: Add FLID based routing support

---

buildlib/pr/main.yml

Add a compilation step for ROCm 6.0 on a ubuntu 22.04 docker image
test compilation of ROCm 6.0 in UCX CI

AZP: add ubuntu 22.04 container w/ rocm6.0 stack

---

buildlib/pr/wire_compat.yml
buildlib/tools/check_tls_perf_caps.sh

Add comparision of transport performance charasteristics reported by `ucx_info -d`
Wire-compatibility check. Diffferent values of the same perf capability between different UCX versions may result in ep reconfiguration error

AZP: Add wire-compat check for perf caps

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto_common.c

Max seg size can be configured by user for RMA/ZCOPY
Better control seg size and enable simulate complex multi fragment scenarios.

UCP/PROTO: Max seg size can be configured by user for RMA/ZCOPY

---

src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/rc/accel/rc_mlx5_devx.c

Backport #9551
Don't port test_jenkins.sh change, and one minor conflict in ib_iface.h

UCT/IB: Add FLID based routing support - v1.16.x

---

src/uct/ib/base/ib_md.c

Fix the logging of multithreading registration.
Now the operation (reg or dereg) defines basing on the `ctx->reg` value which is never set. 
In the base MT registration function we define reg/dereg based on passed `params` value. This patch applies this logic to the thread function too.

UCT/IB/MD: Fix MT (de)registration logging

---

src/ucp/rndv/proto_rndv.c
test/gtest/common/test_helpers.cc
test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_atomic.cc
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/ucp/test_ucp_peer_failure.cc
test/gtest/ucp/test_ucp_rma.cc
test/gtest/ucp/test_ucp_tag.cc
test/gtest/ucp/test_ucp_tag_xfer.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h

Backport #9545 to v1.16.x branch

CI fixes - v1.16.x

---

bindings/java/src/main/native/Makefile.am

Specify the file to publish to skip rebuilding the jar file.
Maven publish target rebuilds the jar, effectively overriding any attempts to include ARM support.

AZP/RELEASE: MVN publish wo rebulding jar

---

src/tools/perf/lib/ucp_tests.cc
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h

In ucp perftests - called `ucp_ep_flush` of self_ep after writing/reading sn to/from memory type buffer. 
We need to guarantee sn was updated before the next read of the buffer, flush will guarantee any RMA/AMO operation.

TOOLS/PERF/LIB: ep_flush after write_sn / read_sn when using memory types

---

.clang-format
src/ucs/Makefile.am
src/ucs/datastruct/bitmap.h
src/ucs/datastruct/dynamic_bitmap.h
src/ucs/datastruct/static_bitmap.h
test/gtest/ucs/test_bitmap.cc

Initial implementation of dynamic bitmap based on ucs_array and sharing common code with static bitmap.
Dynamic bitmap is needed for adding protocol variants (since total number of instantiated protocol variants is not known in advance)

UCS/BITMAP/TEST: Initial implementation of dynamic bitmap structure

---

src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c

set the UCP_REQUEST_FLAG_PROTO_INITIALIZE flag in `ucp_proto_rndv_put_mtype_copy_progress()` before calling `ucp_proto_rndv_mtype_copy()`. In case the mytpe_pack/copy operation reports immediate completion, the progress function invoked later might fail because the UCP_REQUEST_FLAG_PROTO_INITIALIZED flag has not yet been set on the request otherwise
Fixes issue #9570

UCP: set FLAG_PROTO_INITIALIZED before mtype_copy

---

src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c

fix a call-path in ucp_proto_rndv_mtype_copy if the mytpe_copy reports immediate completion. In that case the progress function invoked later might fail because the UCP_REQUEST_FLAG_PROTO_INITIALIZED flag has not yet been set on the request.
Apply the same change to ucp_proto_rndv_rkey_ptr_mtype_copy_progress as well.
Backport #9571 to v1.16.x
Fixes issue #9570

UCP: set FLAG_PROTO_INITIALIZED before mtype_copy - v1.16.x

---

src/ucp/core/ucp_context.c
src/ucs/config/global_opts.c
src/ucs/config/parser.c
src/ucs/config/parser.h
src/uct/base/uct_md.c
test/gtest/ucp/test_ucp_request.cc
test/gtest/ucp/test_ucp_wireup.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h
test/gtest/ucs/test_config.cc
test/gtest/uct/ib/test_ib.cc
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/ib/test_ib_xfer.cc
test/gtest/uct/ib/test_rc.cc
test/gtest/uct/tcp/test_tcp.cc
test/gtest/uct/test_many2one_am.cc
test/gtest/uct/test_md.cc
test/gtest/uct/test_mm.cc
test/gtest/uct/test_tag.cc
test/gtest/uct/uct_test.cc

Reset request tests for offset = 0
First phase for reset in the middle PR.

TEST/PROTO: Reset request tests for offset = 0

---

bindings/go/src/examples/perftest/perftest.go

Locked OS thread before setting CUDA device.
This is an attempt to fix the following failure:
```
/scrap/azure/agent-08/AZP_WORKSPACE/_temp/ucx-73847/bin/goperftest -p=30800 -m=cuda
...
/scrap/azure/agent-08/AZP_WORKSPACE/_temp/ucx-73847/bin/goperftest -p=30800 -m=cuda -i=localhost
...
cuda_ipc_md.c:212  UCX  ERROR   cuCtxGetDevice(&this_device) failed: invalid device context
ucp_rkey.c:902  UCX  ERROR   failed to unpack remote key from remote md[5]: Input/output error
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x38)
```
Goroutine is an abstraction which allows to develop multi-threaded applications. There is no guarantee that goroutine will be executed on the same CPU thread for the entire time. What can result an issue, because CUDA device (aka …

BINDINGS/GO: Locked OS thread before setting CUDA device.

---

src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.h

introduce two new parameters for rocm/ipc that allow to fine tune the protocol selection. 
They help to resolve the issue seen with v2 protocols for short message intra-node collective operations.
Backport #9568

UCT/ROCM: adjust rocm/ipc performance parameters - v1.16.x

---

buildlib/jucx/jucx-build.yml

Add missing params to Java build.
Failure to publish Java build.
[Failure log
](https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=74066&view=logs&j=2e2740d9-d4aa-5179-08dd-ad68a55c4bdb&t=d0bcc340-d162-529a-87d7-53d53d7ac2c5&l=20)

AZP/RELEASE: Fix dual release - v1.16.x

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/ib/test_ib_xfer.cc
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h
test/gtest/uct/test_p2p_mix.cc
test/gtest/uct/test_p2p_mix.h
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Support indirect keys creation for memory regions that were created by multiple treads.
MT memory registration can happen (or not) implicitly for large buffers, but the current code doesn't support indirect keys creation for such registration (it always assumes that MR was registered as contig buffer by one thread)
Create `uct_ib_mlx5_devx_reg_ksm_data` wrapper that separates KSM creation method by MR flags.

UCT/MD/IB: Fix indirect key creation for MT registered memory

---

bindings/java/src/main/native/Makefile.am
buildlib/azure-pipelines-release.yml
buildlib/dockers/centos-release.Dockerfile
buildlib/jucx/jucx-build.yml

Refactoring the process for releasing Jar files to enable build, sign, and publishing per platform.
Failures in Maven publish otherwise.
1. Move forward from CentOS-7 to CentOS-8 due to the outdated GPG agent.
2. Add the 'pinentry' package in Docker.
3. Configure the GPG agent to use pinentry.
4. Add filename suffix for non-x86 platforms.

AZP/RELEASE: Refactor GPG sign and publish of Jar files - 1.16.x

---

src/tools/perf/Makefile.am
src/tools/perf/api/libperf.h
src/tools/perf/perftest.c
src/tools/perf/perftest.h
src/tools/perf/perftest_daemon.c
src/tools/perf/perftest_params.c
src/tools/perf/perftest_run.c
src/ucs/sys/sock.c
src/ucs/sys/sock.h
test/gtest/common/test_perf.cc
test/gtest/ucs/test_sock.cc
ucx.spec.in

This is the first part of the "Support XGVMI in ucx perftest" story (original PR: https://github.com/openucx/ucx/pull/8767). 
The scope of this change-set is:
- daemon skeleton implementation
- appropriate config options for perftest
- address existing comments from the original PR
The overall goal is to provide initial support for offloading communication to DPU using exported memh feature. We split the original change-set into several parts not exceeding 500 LOC limit, so that it's easier to review.

TOOLS/PERF: Skeleton for DPU daemon

---

buildlib/pr/main.yml
buildlib/pr/tests.yml
config/m4/compiler.m4
contrib/lsan.supp
contrib/test_jenkins.sh
src/ucm/util/sys.h
test/gtest/Makefile.am
test/gtest/common/test_helpers.cc
test/gtest/uct/ib/test_cqe_zipping.cc
test/gtest/uct/test_md.cc

Add Address Sanitizer check job to CI

CI: Enable ASAN testing

---

src/ucp/core/ucp_mm.c

Fix sporadic ibv_reg_mr() failure with "Cannot allocate memory" or "Bad address"
[Internal issue](https://redmine.mellanox.com/issues/3605689)
The rcache memory registration callback is expected to fail if the memory region contains invalid addresses. In this case, rcache will revert a merge operation and register only the minimal requested region. Currently UCP rcache memory registration callback does not do that, so rcache may merge with invalid memory area, leading to a registration error later on.

UCP/RCACHE: Fix ibv_reg_mr error by registering memory in rcache callback

---

buildlib/pr/main.yml

Remove duplicate testing on "new" machines.
Requested to remove "new" machines.

AZP: Remove "new" from testing - v1.16.x

---

src/ucp/core/ucp_mm.c

UCP/RCACHE: Fix ibv_reg_mr error by registering memory in rcache callback - v1.16.x

---

src/ucs/config/parser.c
src/ucs/config/parser.h
test/gtest/ucs/test_config.cc
test/gtest/ucs/ucx_test.conf

Advanced key-value parser for UCX config.
Usage example:
```
{"TEMP", "20", "Temperature", 0,
UCS_CONFIG_TYPE_KEY_VALUE(UCS_CONFIG_TYPE_UINT,
{"front", "front temperature", ucs_offsetof(car_opts_t, temp_front)},
{"rear",  "rear temperature",  ucs_offsetof(car_opts_t, temp_rear)},
{NULL}
)},
```
There are several use cases when config environment variables may contain multiple values (e.g. `RNDV_FRAG_ALLOC_COUNT= host:128,cuda:128`). However there are several drawbacks with current implementation: storing intermediate strings, 2-phase processing, syntax is not enforced.
Advanced key-value config parser aims to solve these issues.
[Design considerations document](https://nvidia.sharepoint.com/:p:/r/sites/NBU-UCX/_layouts/15/Doc.aspx?sourcedoc=%7B232d86f5-c9e1-4a3c-8e40-7b6a6f3cf161%7D&action …

UCS/CONFIG: Key-value config parser

---

src/ucs/datastruct/array.c
src/ucs/datastruct/array.h
src/ucs/datastruct/callbackq.c
src/ucs/debug/assert.h
src/ucs/sys/compiler_def.h
test/gtest/ucs/test_datatype.cc
test/gtest/ucs/test_string.cc

2 improvements in this PR:
- Use bit field in ucs_array for storing `is_fixed` flag
- Allow to create array of dynamic (not just compile-time constant) size on stack 
Before this change we used lower bit of ucs_array `capacity` field to store the "fixed" flag.
There are 2 issues with this design choice:
- debugability: while you see certain value in the debugger for array capacity (e.g. say 3), this might not be the REAL capacity of an array, because LSB is simply disregarded when checking capacity. This is ambiguous and error-prone
- can't use full capacity of fixed array in some cases.
The problem here is that despite the REAL capacity is 3, ucs_array_capacity returns 2, because it discards the LSB. For dynamic arrays this is not an issue - it will just grow a bit in advance (still not …

UCS/ARRAY: Use bit field for array is_fixed flag

---

src/uct/ib/ud/base/ud_ep.c

Unacknowledged messages may be sent before CREP.
Fix internal issue [3476311](https://redmine.mellanox.com/issues/3476311)
```
[jazz15:129603:0:129603]       ud_ep.c:1271 Assertion `!uct_ud_ep_ctl_op_check(ep, UCT_UD_EP_OP_CREQ) && uct_ud_ep_is_last_ack_received(ep)' failed: iface=0xa264a0 ep=0xd16da0 conn_sn=1 ep_id=277, dest_ep_id=329 rx_psn=2 ep_flags=0x1d8 ctl_ops=0x8 rx_creq_count=1
==== backtrace (tid: 129603) ====
0 0x0000000000060d93 uct_ud_ep_prepare_crep()  /build-result/src/hpcx-gcc-redhat7/ucx-master/src/uct/ib/ud/base/ud_ep.c:1265
1 0x0000000000060d93 uct_ud_ep_do_pending_ctl()  /build-result/src/hpcx-gcc-redhat7/ucx-master/src/uct/ib/ud/base/ud_ep.c:1520
2 0x0000000000062447 uct_ud_ep_do_pending()  /build-result/src/hpcx-gcc-redhat7/ucx-master/src/uct/ib/ud/base/ud_ep.c:1609 …
```

UCT/IB/UD: Remove erroneous assertion

---

bindings/go/src/examples/perftest/perftest.go

Locked OS thread before setting CUDA device.
This is an attempt to fix the following failure:
```
/scrap/azure/agent-08/AZP_WORKSPACE/_temp/ucx-73847/bin/goperftest -p=30800 -m=cuda
...
/scrap/azure/agent-08/AZP_WORKSPACE/_temp/ucx-73847/bin/goperftest -p=30800 -m=cuda -i=localhost
...
cuda_ipc_md.c:212  UCX  ERROR   cuCtxGetDevice(&this_device) failed: invalid device context
ucp_rkey.c:902  UCX  ERROR   failed to unpack remote key from remote md[5]: Input/output error
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x38)
```
Goroutine is an abstraction which allows to develop multi-threaded applications. There is no guarantee that goroutine will be executed on the same CPU thread for the entire time. What can result an issue, because CUDA device (aka …

BINDINGS/GO: Locked OS thread before setting CUDA device - v1.16.x 

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

UCT/IB/MLX5: Refactor KSM functions and extend logging

---

src/uct/rocm/base/rocm_base.c
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_iface.c

set the bandwidth values in the rocm/copy performance estimate functions based on the GPU type that we found. We use the same parameters for MI300A and MI300X at the moment, but the infrastructure is in place in case we need to distinguish between them at a later point.
Performance fixes with ucx 1.16 for non MI200 GPUs

UCT/ROCM: set parameters dependent on GPU type

---

src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_md.h
src/uct/ib/rdmacm/rdmacm_cm.c

Use routable gid when FLID routing is configured and enabled
better use experience, no need to set GID manually for FLID based routing to work properly

UCT/IB: Auto-detect GID idx with FLID routing

---

buildlib/az-distro-release.yml
debian/rules.in

Fix upgrading ucx-cuda package, internal issue [3749336](https://redmine.mellanox.com/issues/3749336)

BUILD/DEBIAN: Remove libnvidia-compute version dependency

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_worker.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/tag/offload/rndv.c
test/gtest/ucp/test_ucp_tag.cc

Introduced intra/inter-node fine-grained configuration for rendezvous switching.
This change is **only supported by proto v2**. For proto v1 only coarse grained config is supported (e.g. `UCX_RNDV_THRESH=1000`)
Current implementation provides coarse-grained config (`UCX_RNDV_THRESH`) to set rendezvous switching threshold. There is a demand from some clients to introduce fine-grained config allowing to set this threshold separately for intra-node and inter-node communication.
We use newly developed key-value parser in the config, that is used to configure fine-grained thresholds for intra and inter communication. Coarse-grained config (value for all) is still acceptable. Fine-grained config has precedence over coarse-grained one
```
UCX_RNDV_THRESH=1000  // 1000 is the limit for intra and …
```

UCP: Fine-grained intra/inter config for rendezvous

---

.clang-format
src/ucs/datastruct/bitmap.h
src/ucs/datastruct/static_bitmap.h
test/gtest/ucs/test_bitmap.cc

Implement a static bitmap on top of common bitmap functions. The macros can detect the bitmap size according to its type.

UCS/BITMAP/TEST: Implement static bitmap

---

buildlib/az-distro-release.yml
debian/rules.in

Backport #9617 to v1.16.x branch
cc @tzafrir-mellanox

BUILD/DEBIAN: Remove libnvidia-compute version dependency - v1.16.x

---

test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/ucm/rocm_hooks.cc

gfx94* architectures do not support hipMallocPitch, so disable them in gtest. Add a check for image support on the GPU, which is  required for hipMallocPitch.

GTEST/COMMON: check support for hipMallocPitch

---

buildlib/pr/main.yml
buildlib/pr/tests.yml
contrib/test_jenkins.sh

Moves tests execution with enabled Valgrind to the separate stage of CI.
In that scheme, if valgrind fails but tests without valgrind passed, there is no need to rerun the tests without valgrind.

CI: Move Valgrind check to a separate stage

---

config/m4/mad.m4

Fix dependency leak from rpm build machine, when `libibmad-devel` and `libumad-devel` are installed.
RPM users might not have those libs installed. Valid also for non-rpm package builders.
Force disable in v1.16, later can be default guess (or rather yes for more predictability), then `dlopen()` at runtime.

CONFIG/M4: Disable MAD support to prevent libibmad/libumad dependency leak

---

config/m4/mad.m4

CONFIG/M4: Disable MAD support to prevent libibmad/libumad dependency leak - v1.16.x

---

.gitignore

Cleanup MPI binaries, seen when building with `--with-mpi=yes`.

GIT/GITIGNORE: Add MPI related binaries

---

test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/ucm/rocm_hooks.cc

Backport https://github.com/openucx/ucx/pull/9613
I understand that there might not be another ucx 1.15 release, but having this fix in the 1.15 branch might still be userful for our internal QA process.

GTEST/COMMON: check support for hipMallocPitch - v1.15.x

---

src/ucp/proto/proto_debug.h
src/ucp/proto/proto_reconfig.c
src/ucs/datastruct/linear_func.h

Added checks to avoid division by zero.
To fix https://github.com/openucx/ucx/issues/9631

UCS/DATASTRUCT: Fixed FP division by zero.

---

buildlib/tools/perf-common.yml

Change the path to PerfX config file to reflect the recent files structure reorg in PerfX.
UCX Perf pipeline fails.

AZP/PERF: Change config files path

---

bindings/java/pom.xml.in
bindings/java/src/test/java/org/openucx/jucx/UcpEndpointTest.java
src/uct/cuda/cuda_copy/cuda_copy_md.c

Fix Cuda host memory registration error (from ucp_mem_map) when there is no active context.
For example, ails with shmem applications, like so:
```
[r-hpc-gpu08:62403:0]    cuda_copy_md.c:173  UCX  ERROR cudaHostRegister() failed: invalid argument
[r-hpc-gpu08:62403:0]          ucp_mm.c:70   UCX  ERROR failed to register address 0xff000000 (host) length 11202985984 on md[3]=cuda_cpy: Input/output error (md supports: host|cuda|cuda-managed)
```
Fixes internal issue [3748762](https://redmine.mellanox.com/issues/3748762)
The fix is needed only on v1.16.x branch, since on master branch it was already fixed by #8590

UCT/CUDA: Don't register memory without active context - v1.16.x

---

buildlib/az-helpers.sh
buildlib/jucx/jucx-test.yml
buildlib/pr/go/go-test.yml
buildlib/pr/main.yml
buildlib/tools/common.sh
contrib/test_jenkins.sh

* try_load_cuda_env was defined twice, remove the duplication
* valgrind tests do not run on althca or bf machines, so remove the stage

CI: Remove empty valgrind tests and duplicate function

---

src/ucp/proto/proto_debug.h
src/ucp/proto/proto_reconfig.c
src/ucs/datastruct/linear_func.h

Added checks to avoid division by zero.
To fix https://github.com/openucx/ucx/issues/9631
Cherry-picked https://github.com/openucx/ucx/pull/9636

UCS/DATASTRUCT: Fixed FP division by zero - v1.16.x

---

test/apps/test_fuzzy_match.py
test/apps/test_ucx_tls.py

Fixed test_fuzzy_match.py and test_ucx_tls.py python version reference.
Default python for RHEL8 is python3.

TEST/APPS: Modify test_fuzzy_match.py and test_ucx_tls.py to use default python version

---

src/ucp/proto/proto.h
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucs/datastruct/bitmap.h
src/ucs/datastruct/dynamic_bitmap.h
test/gtest/ucs/test_bitmap.cc

Allow creating multiple instances of the same protocol with different configuration traits (as stored in protocol priv) and let the common protocol selection logic pick best configuration per message size.
For example, it will allow device memory pipeline and auto-tuning of number of lanes used by a multi protocol.

UCP/PROTO: Support protocol variants

---

buildlib/pr/main.yml

Add docker args for IB testing for Ubuntu 22.04 image initialization
This image is used for ASAN testing, without these options IB isn't tested.

CI: Add IB options for Ubuntu 22.04 image

---

src/ucp/core/ucp_context.c
src/uct/ib/base/ib_iface.c

Workaround test failures on `swx-rain02-bf1` with `Ubuntu 22.04.3 LTS`
`MLNX_OFED_LINUX-23.10-0.5.5.0`
Huge pages are reserved by default:
```
$ cat /proc/meminfo |grep -i hugepage
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
FileHugePages:         0 kB
HugePages_Total:    1024
HugePages_Free:      980
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```
Test failure is:
```
$ iter env RDMAV_HUGEPAGES_SAFE=1 UCX_LOG_LEVEL_TRIGGER=error ./test/gtest/gtest --gtest_filter=rcx/test_ucp_mmap.alloc_rereg*
...
=========================================
Iteration 10 started at Sun Feb 4 16:00:25 IST 2024
=========================================
env RDMAV_HUGEPAGES_SAFE=1 UCX_LOG_LEVEL_TRIGGER=error ./test/gtest/gtest …
```

UCP/UCT/IB: Don't allocate huge pages by default

---

src/ucm/ptmalloc286/malloc.c

Bugfix for #8898 - added UCS_V_UNUSED attribute to nfences
In non-debug compilation `assert` have empty definition making nfences an unused variable which fails compilation.

UCM/PTMALLOC286: added UCS_V_UNUSED attribute to nfences

---

src/uct/rocm/base/rocm_base.c

we need to increase the max. no. of HSA agents to accommodate some of the potential system configurations.

UCT/ROCM: increase max. no. of agents

---

.gitignore
src/tools/perf/api/libperf.h
src/tools/perf/lib/libperf_int.h
src/tools/perf/lib/ucp_tests.cc
src/tools/perf/perftest.c
src/tools/perf/perftest_daemon.c
src/tools/perf/perftest_params.c
test/gtest/common/test_perf.cc

Second batch commit for DPU xgvmi daemon
It contains handlers for host-to-peer and peer-to-peer messages no the daemon side.
For reference:
The first batch commit https://github.com/openucx/ucx/pull/9536 is merged.
The original changes: https://github.com/openucx/ucx/pull/8767
The overall goal is to provide initial support for offloading communication to DPU using exported memh feature. We split the original change-set into several parts not exceeding 500 LOC limit, so that it's easier to review.

TOOLS/PERF: Second batch commit for DPU xgvmi daemon

---

src/ucp/proto/proto_select.c

Fixinig initialization
Looks like when using '-02' optimization is different from '-03' from perspective of memory initialization
Explicitly initialize the data

UCP/PROTO: Fix unitialized struct

---

NEWS

Update NEWS 1.16 RC5
To progress release process

RELEASE: Update NEWS 1.16 RC5

---

src/uct/ib/base/ib_iface.c

This PR fixes minor issue for printed error trace when `ibv_create_qp()` function failed
in UCT/IB base code.
When debugging some issue noticed that string representation of `errno` is printed twice:
```
[1707374670.430287] [***:1409 :0]        ib_iface.c:1031 UCX  ERROR   iface=0x55555564cfa0: failed to create RC QP TX wr:256 sge:5 inl:64 resp:64 RX wr:0 sge:1 resp:64: File exists failed: File exists
```
Remove extra `%m` passed to `uct_ib_check_memlock_limit_msg()` macro, because it prints an error string taken as `%s` from `strerror()`.

UCT/IB/BASE: Fix error message for QP create

---

buildlib/pr/static_checks.yml
buildlib/tools/static_checks.sh

Move bash part of yaml file in its own shell script.
Easier to run on local machine to repro various failures.
Add new shell script. Use with or without same docker image.
```
docker run -it --rm -v $(pwd):/mnt rdmz-harbor.rdmz.labs.mlnx/ucx/fedora33:1 /bin/bash
WORKDIR=$(pwd) EXECUTOR_NUMBER=0 BUILD_ID=0 ./buildlib/tools/static_checks.sh
```

AZP/STATIC_CHECKS: Separate shell part of yaml file

---

src/ucp/api/ucp.h

Clarify some of the aspects of `ucp_put_nbx` and `ucp_get_nbx`.
Guarantees are currently not well-documented.

DOCS: Clarify `ucp_put_nbx` and `ucp_get_nbx`

---

src/ucp/proto/proto_common.inl
src/ucp/rndv/rndv_rtr.c

Excluded memory domains from the list where memory registration failed.
Scenario:
```C
ucp_tag_rndv_rts_progress
ucp_proto_rndv_rts_request_init
ucp_datatype_iter_mem_reg(rpriv->md_map)
ucp_datatype_iter_mem_reg_single
ucp_memh_register
ucp_memh_register_internal
/* uct_md_mem_reg_v2 fails for md_x */
ucp_proto_am_bcopy_single_progress
ucp_proto_am_bcopy_single_send
ucp_tag_rndv_proto_rts_pack
ucp_proto_rndv_rts_pack
ucp_proto_request_pack_rkey(rpriv->md_map)
ucp_rkey_pack_memh
/* uct_md_mkey_pack_v2 crashes for md_x */
```

UCP/RNDV: Fixed rkey pack crash when mem reg failed.

---

src/uct/sm/mm/posix/mm_posix.c

Display log message instead of returning an error when failing on `uct_posix_unlink` in `uct_posix_mem_alloc`
Prevent UCX init from failing over sporadic "No Such file or directory" error when trying to delete a SHM file.
This PR fix this issue:
https://redmine.mellanox.com/issues/3602767
Also the same error was seen in:
https://redmine.mellanox.com/issues/3730544

UCT/MM: Replaced error value with debug log message for shm_unlink

---

cmake/ucx-targets.cmake.in

Check target existence before adding them.
Triggers error when `find_package()` is invoked multiple times.
Derived from #9622, but since we don't generate the ucx cmake target file, take simpler approach.

CMAKE: Add targets once in case of multiple find_package()

---

src/ucp/proto/proto_common.inl
src/ucp/rndv/rndv_rtr.c

Excluded memory domains from the list where memory registration failed.
Scenario:
```C
ucp_tag_rndv_rts_progress
ucp_proto_rndv_rts_request_init
ucp_datatype_iter_mem_reg(rpriv->md_map)
ucp_datatype_iter_mem_reg_single
ucp_memh_register
ucp_memh_register_internal
/* uct_md_mem_reg_v2 fails for md_x */
ucp_proto_am_bcopy_single_progress
ucp_proto_am_bcopy_single_send
ucp_tag_rndv_proto_rts_pack
ucp_proto_rndv_rts_pack
ucp_proto_request_pack_rkey(rpriv->md_map)
ucp_rkey_pack_memh
/* uct_md_mkey_pack_v2 crashes for md_x */
```
Cherry-picked https://github.com/openucx/ucx/pull/9676

UCP/RNDV: Fixed rkey pack crash when mem reg failed - v1.16.x 

---

src/uct/ib/mlx5/ib_mlx5.inl

Help compiler to optimize without introducting any function call, using instead `movl`, `movq` or `xmm` registers, depending on the optimization level selected.
With `-O2` only, the compiler replaces `UCS_WORD_COPY(uint64_t, dst, uint64_t, src, MLX5_SEND_WQE_BB);` by `memmove()`. This is causing crash below:
```
ib_mlx5_log.c:179  Local length error on mlx5_0:1/IB (synd 0x1 vend 0x68 hw_synd 0/141)
ib_mlx5_log.c:179  UD QP 0x15a6 wqe[18856]: SEND --- [rqpn 0x15a7 rlid 5] [inl len 24] [va 0x7f2e11f79fe0 len 4072 lkey 0x203400]
```
It is not entirely clear why, but this could be related to introduced out-of-order/block copy, added prefetch intel instruction...
Internal: [3774158](https://redmine.mellanox.com/issues/3774158)
Adding compiler fence inside `UCS_WORD_COPY()` disables usage of …

UCT/IB/MLX5: Prevent compiler to use memmove

---

src/ucp/rma/rma_send.c

Return no resource if we risk not being able to complete put immediately.
Reported as #9691.

UCP/PROTOV2: Return error with immediate completion when put short fails

---

src/uct/ib/rc/accel/rc_mlx5.h
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
test/gtest/uct/ib/test_ib_event.cc

Introduce `uct_rc_mlx5_ep_base_t` to separate HWTM structures
To avoid overhead in RC based endpoint which may do not have HW capabilities
Add another level of inheritance: `uct_rc_mlx5_ep_t : uct_rc_mlx5_ep_base_t`

UCT/RC/MLX5: refactor uct_rc_mlx5_ep_t

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Adding dci_pool_index attribute to `uct_dc_mlx5_ep_t` instead of using the first 3 bits of `ep->flags`.
`UCT_DC_MLX5_IFACE_MAX_DCI_POOLS` is defined to be 16, meaning 3 bits aren't enough, this patch fixes the issue by adding a separate field for dci_pool_index.

UCT/IB/DC: bugfix - dci_pool_index have only 3 bits in ep->flags (it's max value is 15)

---

src/uct/ib/mlx5/ib_mlx5.inl

UCT/IB/MLX5: Prevent compiler to use memmove - v1.16.x

---

cmake/ucx-targets.cmake.in

Backport #9696 to support multiple cmake `find_package()` invocations.

CMAKE: Add targets once in case of multiple find_package() - v1.16.x

---

src/uct/ib/Makefile.am
src/uct/ib/base/ib_md.c

fix compilation without devx
gga_mlx5.c file was wrongly added under `HAVE_MLX5_DV` condition instead of `HAVE_DEVX`

UCT/IB/GGA: fix compilation

---

src/tools/perf/lib/libperf.c
src/tools/perf/lib/libperf_int.h
src/tools/perf/lib/libperf_memory.c

Third batch commit for DPU xgvmi daemon
For reference:
First batch commit https://github.com/openucx/ucx/pull/9536 is merged.
Second batch commit https://github.com/openucx/ucx/pull/9624 is merged.
Original changes: https://github.com/openucx/ucx/pull/8767
The overall goal is to provide initial support for offloading communication to DPU using exported memh feature. We split the original change-set into several parts not exceeding 500 LOC limit, so that it's easier to review.

TOOLS/PERF: Third batch commit for DPU xgvmi daemon

---

test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_mmap.cc

Fix potential double `munmap()` causing unrelated memory to disappear altogether.
Triggered with #9668 at commit 9e98b04 with `UCX_LOG_LEVEL=debug.. >/dev/null` to help repro:
```
[ RUN      ] tcp/test_ucp_mmap.fixed/0 <tcp,cuda_copy,rocm_copy>
[swx-rdmz-ucx-new-02:29082:0:29082] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7f8142912ec0)
/scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test_helpers.cc:55: Failure
Failed
```
Instantiating `ucs::mmap_fixed_address` creates a new mapping in an available range. `ucp_mem_map(ALLOCATE|FIXED)` is then invoked and eventually `mmap(FIXED)` replaces that already owned mapping. In the test, `ucp_mem_unmap()` releases it, but `ucs::~mmap_fixed_address` is also calling `munmap()`. Issue arise when …

TEST/UCP: Fix double munmap in ucp mmap tests

---

src/ucp/rndv/rndv_ppln.c

Do not select pipeline rndv protocols when sender buffer is not contig (in this case address is zero in RTS header)

UCP: Fix rndv ppln protocols selection - v1.16.x

---

src/ucm/bistro/bistro.c
src/ucm/bistro/bistro_ppc64.h

UCM/BISTRO: Add empty locking step while patching on PPC64 - v1.16.x

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Always return unreachable from `uct_cuda_ipc_rkey_unpack` to ignore cuda IPC key when it can't be used (e.g. cuda device is not set for this process)

UCT/CUDA: Return unreachable from rkey unpack in case of error - v1.16.x

---

src/uct/ib/mlx5/ib_mlx5.inl

UCT/IB/MLX5: Prevent compiler to replace SSE instructions by memmove() - v1.16.x

---

contrib/test_jenkins.sh
src/ucs/sys/topo/base/topo.c
src/uct/ib/rc/accel/gga_mlx5.c

Fix the following failures on BF3 machines:
1.
```
[ RUN      ] all/test_pci_bw.get_pci_bw/0 <all/tag>
/.autodirect/rdmzsysgwork/yosefe/ucx/contrib/../test/gtest/ucp/test_ucp_worker.cc:923: Failure
Expected: (pci_bw) < (std::numeric_limits<double>::max()), actual: 1.79769e+308 vs 1.79769e+308
[  FAILED  ] all/test_pci_bw.get_pci_bw/0, where GetParam() = all/tag (348 ms)
[----------] 1 test from all/test_pci_bw (348 ms total)
[==========] 1 test from 1 test suite ran. (349 ms total)
[  PASSED  ] 0 tests.
```
2. (Valgrind) memory leak in GGA transport

Fixes for CI failures on BF3 test nodes

---

NEWS

Update NEWS 1.16 RC4
Prepare v.16 RC4

RELEASE: Update NEWS 1.16 RC4

---

src/ucm/bistro/bistro.c
src/ucm/bistro/bistro_ppc64.h

Fix build on PPC64.
Reported by #9725.
Take simplest functional approach in absence of testing.

UCM/BISTRO: Add empty locking step while patching on PPC64

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c

RDMA_READ or/and atomic operations may fail if peers are using dcis configured with different values of max_rd_atomic. Since certain FW in CX-7 this value was increased from 16 up to 64. This PR checks whether just one of the peers is using old value (16) of max_rd_atomics and prints an error if it is different from the local value.
Later, when dynamic dci allocation is introduced, ep will create a new dci pool matching peers config rather than just printing an error.

UCT/DC: Print error when max_rd_atomic is different on peers

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_multi.h
src/ucp/proto/proto_select.c
src/ucp/proto/proto_single.c
src/ucp/proto/proto_single.h
src/ucp/rma/amo_offload.c
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/stream/stream_multi.c
src/ucp/tag/eager_multi.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload/eager.c
src/ucp/tag/offload/rndv.c

Next phase of adding protocol variants, moving from init() to probe()

UCP/PROTO: Move non-rndv protocols to use probe() instead of init()

---

src/ucp/proto/proto_select.c

Fixes the bug of select node connection to children introduced by https://github.com/openucx/ucx/pull/9615
In the current master select node always has link only to selected protocol so the other protocols info is missing.

UCP/PROTO: Fix selection perf-node children connection

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/ib/test_ib_md.cc

Now we do multithreading registration without alignment of the memory region which can cause errors during KSM creation. This patch would register chunk with regard to the alignement.
Current state:
After the patch:
1. Register first direct MR up to `md->config.mt_reg_chunk` alignment to meet this alignment for all further MRs.
2. Register N bytes before first direct MR to meet `md->dev.atomic_align` alignement.

UCT/MD/IB: Support MT KSM registration for unaligned buffers

---

src/uct/ib/mlx5/ib_mlx5.inl

Prevent compiler to replace SSE instructions with `memmove()`. This is continuation of #9692.
With `-O2` compiler can replace code by `memmove()`, even when SSE types are used.
Use structure assignment like the non-SSE case to avoid `memmove()` optimization.
Patch below also works, but we want to avoid to selectively and globally disable optimizations:
```diff
diff --git a/src/uct/ib/Makefile.am b/src/uct/ib/Makefile.am
index 3974e3784..cad31a1bc 100644
--- a/src/uct/ib/Makefile.am
+++ b/src/uct/ib/Makefile.am
@@ -9,7 +9,7 @@ SUBDIRS = . rdmacm
module_LTLIBRARIES    = libuct_ib.la
libuct_ib_la_CPPFLAGS = $(BASE_CPPFLAGS) $(IBVERBS_CPPFLAGS)
-libuct_ib_la_CFLAGS   = $(BASE_CFLAGS)
+libuct_ib_la_CFLAGS   = $(BASE_CFLAGS) -fno-tree-loop-distribute-patterns
libuct_ib_la_LIBADD   = …
```

UCT/IB/MLX5: Prevent compiler to replace SSE instructions by memmove()

---

src/ucp/rndv/rndv_put.c

set the UCP_PROTO_COMMON_INIT_FLAG_MIN_FRAG when initialing put_zcopy protocol. Without it, the rocm/ipc transport is not selected for D2D transfer when using RNDV_SCHEME put_zcopy, since rocm/ipc sets a non-zero min_zcopy value.
Note, that this flag is being set in the corresponding get_zcopy routine

UCP/PROTO: add MIN_FRAG flag for put_zcopy proto

---

src/ucp/am/eager_multi.c
src/ucp/core/ucp_request.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.h
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_put.c
src/ucp/stream/stream_multi.c
src/ucp/tag/eager_multi.c
src/ucp/tag/tag_recv.c
test/gtest/ucp/test_ucp_request.cc

Support replacing ucp protocol in the middle of send operation (offset > 0).
Needed for several features: RC/DC, memic, EP reconfig.

UCP/PROTO: Replace ucp protocol in the middle of send operation (offset > 0)

---

src/uct/ib/base/ib_iface.c
src/uct/ib/ud/accel/ud_mlx5.c

UCT/IB: Print device name when failed to create a QP

---

src/ucs/sys/topo/base/topo.c

Fix CI failures on v1.16.x branch
Cherry-picked from 943c64fb71

UCS/TOPO: Add support for PCIe gen5 bandwidth detection - v1.16.x

---

src/ucp/rndv/proto_rndv.c

Make RTR unpack time node visible on the perf graph.
Now mtype RTR contain BW but the only child node is rcache lookup.
| Before| After|
|--------|--------|
| ![image](https://github.com/openucx/ucx/assets/22097249/4a50874a-bfd6-4c93-a9e6-5fafb47e757e) | ![image](https://github.com/openucx/ucx/assets/22097249/18b9009f-4dbc-4ab5-80d3-2adc72ffbad6) |

UCP/PROTO: Attach unpack time perf node for mtype RTR

---

src/ucp/rndv/rndv_put.c

Backport PR #https://github.com/openucx/ucx/pull/9730
set the UCP_PROTO_COMMON_INIT_FLAG_MIN_FRAG when initialing put_zcopy protocol. Without it, the rocm/ipc transport is not selected for D2D transfer when using RNDV_SCHEME put_zcopy, since rocm/ipc sets a non-zero min_zcopy.
Note, that this flag is also set in the corresponding get_zcopy routine

UCP/PROTO: add MIN_FRAG flag for put_zcopy proto - v1.16.x

---

src/ucp/wireup/select.c
src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/ib/base/ib_iface.c
src/uct/ib/dc/dc_mlx5.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/sm/mm/base/mm_iface.c

Add UCT flag when TX (like AM) depends on RX (like RDMA_READ). Implement AM lane isolation wrt to RMA lane.
To avoid RX throughput dependency that limits overall TX throughput.
- Add a TX/RX dependency flag
- Allow skipping AM lane when creating RMA lanes
- To maintain overall number of lanes, allow overriding dev_num_paths, when a AM lane has been skipped for that reason
- Old and new version: each side performs according to its code version
- CX7 sees 1 AM + 2 RMA lanes, CX6 sees 1 lanes AM/RMA
```
ep 0x7f4224a4b000: am_lane 0 wireup_msg_lane <none> cm_lane <none> keepalive_lane <none> reachable_mds 0x7
ep 0x7f4224a4b000: lane[0]:  0:dc_mlx5/mlx5_0:1.0 md[0]      -> addr[0].md[0]/ib/sysdev[1] seg 4294967295 am am_bw#0
ep 0x7f4224a4b000: lane[1]:  4:dc_mlx5/mlx5_2:1.0 md[2]      -> …
```

UCP/WIREUP: Add capability to separate RMA and AM lanes

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Always return unreachable from uct_cuda_ipc_rkey_unpack to ignore cuda IPC key when it can't be used (e.g. cuda device is not set for this process)
cherry-picked from #9717

UCT/CUDA: Return unreachable from rkey unpack in case of error

---

src/tools/info/sys_info.c
src/ucs/arch/cpu.c
src/ucs/arch/cpu.h
src/ucs/config/parser.c
src/ucs/sys/string.h
src/ucs/sys/sys.c
src/ucs/sys/sys.h
test/gtest/ucs/ucx_test.conf

Added "Product name" to the output of `ucx_info -s`.
Added ability to skip sections of config file, if it is filtered out by "CPU vendor", "CPU model", or "Product name".

UCS/CONFIG: Filtered out sections from config by platform info.

---

src/ucs/time/time.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/mm/base/mm_iface.h

Added IB_SEND_OVERHEAD configuration variables.
Added MM_[SEND|RECV]_OVERHEAD configuration variables.
Added helper method to time units, including special values, to seconds.

UCT: Added configuration variables to set overheads for IB and MM interfaces.

---

src/ucp/proto/proto_common.c
src/ucp/wireup/select.c
src/ucs/type/float8.h
test/gtest/ucs/test_type.cc

Do FP8 pack/unpack operations for local lane distance
To remove inconsistency with remote distance which always came to comparison after packing/unpacking.

UCP/PROTO: Local lanes distance FP8 pack/unpack

---

src/ucp/proto/proto_common.c

Change error message from
` Fatal: abort request 0x123456 proto rndv/rts, not implemented`
to
`Fatal: 'abort' is not implemented for protocol rndv/rts (req: 0x123456)`

UCP/PROTO: Improve logging of unimplemented abort/reset

---

test/gtest/uct/ib/test_ib_xfer.cc

Removes skip test condition due to unaligned buffer. 
After this https://github.com/openucx/ucx/pull/9449 unaligned buffers MT registration should work

UCT/DEVX/MD: MT mix1000 test - remove alignment check

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/rndv/rndv_mtype.inl
src/ucp/rndv/rndv_rtr.c

Allocate staging buffers for ppln protocols according to UCX_RNDV_FRAG_MEM_TYPE. (currently it is parsed by v1 protos only)

UCP/PROTOV2: Enable using device staging buffers for ppln protos

---

src/ucp/proto/proto_common.c

Add conversion of latency to nanoseconds to make FP8 pack/unpack correctly
Latency FP8 pack/unpack supports value represented in nanoseconds
Latency value without this patch after FP8 pack 😄 :

UCP/PROTO: Add latency conversion to nsec before FP8 pack/unpack

---

src/ucp/rndv/rndv_rtr.c

Do not select pipeline rndv protocols when sender buffer is not contig (in this case address is zero and there is no rkey in RTS header)
cheryy-picked from #9720 + added gtest

UCP: Fix rndv ppln protocols selection

---

src/uct/ib/base/ib_md.c

Disabling MR MT registration.
The implementation of multithreading MR registration contains many errors that are already fixed in master.

UCT/IB/MD: Disable MR multithreading registration - м1.16.x

---

src/ucp/wireup/select.c

Reverting the backport of https://github.com/openucx/ucx/pull/9512 since it breaks wire compatibility.

UCP/WIREUP: Consider local distance during slow lanes dropping - v1.16.x - revert

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
test/gtest/ucp/test_ucp_mmap.cc

Fix a remote access error when a memory region obtained from rcache is not registered with atomic access as needed
Fixes internal issue [3784182](https://redmine.mellanox.com/issues/3784182)

UCP/MM: Check registration flags after taking memh from rcache

---

src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
test/gtest/common/test_obj_size.cc
test/gtest/uct/test_peer_failure.cc

uct_ep_check implementations were removed from CUDA_IPC.
uct_ep_check API is used for error handling mechanism.
As part of the lane selection process, we select a single keepalive lane, which is used to check remote EP connection status.
Only transports with one of the following caps can be used as keepalive lane:
1) CONNECT_TO_EP + EP_CHECK flag.
2) CONNECT_TO_IFACE + AM_BCOPY flags.
3)  CONNECT_TO_EP + EP_KEEPALIVE flags.
CUDA_IPC doesn't fulfill those conditions, so cannot be used as keepalive lane.

UCT/CUDA: Removed uct_ep_check support from CUDA_IPC

---

src/ucp/proto/proto_common.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.h

Add latency conversion to nanoseconds before FP8 pack/unpack
https://github.com/openucx/ucx/pull/9738 misses conversion to nanoseconds during the wirep ([link to line](https://github.com/openucx/ucx/pull/9738/files#diff-ff110fb0f2e163038a3eb15545d3b81d9d32c121b79e7a764b72fbb1fa643470L654))

UCP/WIREUP: Add missed conversion to nanoseconds before FP8 pack/unpack

---

contrib/ucx_perftest_config/test_types_ucp
src/tools/perf/lib/libperf.c
src/tools/perf/lib/libperf_int.h
src/tools/perf/lib/libperf_memory.c
src/tools/perf/lib/libperf_thread.c

1. Fixes for bugs in UCP perftests when combining usage of memory types and multithreading, segfault in allocators initialization and using the wrong worker / worker addresses for the self_eps.
2. Adding multithreading perftests to CI
Those bugs were not discovered until now because the CI did not contain any perftest with multithreading tests.

TOOLS/PERF/LIB: bugfixes for multithreading in UCP perftest

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

init atomic_rkey on mem_attach
zcopy using imported memh can wrongly resolve rkey

UCT/IB/DEVX/MD: init atomic_rkey on mem_attach

---

src/ucp/rndv/proto_rndv.c

Report protocol name to the perf tree instead of ACK name.
| Before| After|
|--------|--------|
| ![image](https://github.com/ivankochin/ucx/assets/22097249/81ab87d0-6e1c-4bc5-bf1e-d824459e22a5) | ![image](https://github.com/ivankochin/ucx/assets/22097249/02a086c2-a41b-4079-9df7-ef2ea5dca3ec)|

UCP/PROTO: Report right proto name during ACK perf adding

---

src/ucp/core/ucp_worker.c
src/ucp/wireup/address.c

Fix gtest failure on rock cluster:
```
[ RUN      ] dcx/test_ucp_mmap_atomic.reuse_buffer/0 <dc_x,cuda_copy,rocm_copy>
[1711951084.768635] [rock12:15343:0]          wireup.c:1239 UCX  ERROR   old: am_lane 0 wireup_msg_lane <none> cm_lane <none> keepalive_lane <none> reachable_mds 0xe
[1711951084.768666] [rock12:15343:0]          wireup.c:1249 UCX  ERROR   old: lane[0]:  5:dc_mlx5/mlx5_2:1.0 md[3]      -> md[3]/ib/sysdev[4] seg 4294967295 am am_bw#0
[1711951084.768674] [rock12:15343:0]          wireup.c:1249 UCX  ERROR   old: lane[1]:  5:dc_mlx5/mlx5_2:1.0 md[3]      -> md[2]/ib/sysdev[2] seg 4294967295 amo#0
[1711951084.768679] [rock12:15343:0]          wireup.c:1249 UCX  ERROR   old: lane[2]:  1:dc_mlx5/mlx5_1:1.0 md[1]      -> md[1]/ib/sysdev[3] seg 4294967295 rma_bw#0 …
```

UCP/WORKER: Fix atomic device selection

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/core/ucp_worker.inl
src/ucp/proto/proto_select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucp/wireup/wireup_ep.c

Added usage counter to ep configuration structure to track the number of endpoints using the configuration.
Reverted https://github.com/openucx/ucx/pull/9104.
Activated UCP worker interfaces when setting endpoint configuration to an endpoint.
The changes are required to properly deactivate worker interface when it is unused.
Currently we may deactivate worker interface even if there are still active endpoints.

UCP/CORE: Fixed wiface activation counter.

---

src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/rndv/proto_rndv.c

Remove `frag_size` argument from `ucp_proto_init_parallel_stages` API.
Since this argument participates only in logs and perf tree information. Can be removed since `ucp_proto_common_add_ppln_range` already prints info about fragment size.

UCP/PROTO: Remove redundant frag_size argument from parallel_stages()

---

src/ucp/core/ucp_request.inl
src/ucp/tag/tag_recv.c

Fix JVM segfault in Java CI tests when gdrcopy driver is not loaded
ucp_tag_recv_nbx() can call the user callback when the request is completed immediately (with self transport), even though Jucx does not pass NO_IMM_CMPL flag in request params. This leads to calling set_native_id method on a released object.
The segfault looks like this:
```
Stack: [0x00007ffa692de000,0x00007ffa693de000],  sp=0x00007ffa693da420,  free space=1009k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x6d2a6f]  jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x1af
V  [libjvm.so+0x6d709f]  jni_CallVoidMethodV+0x10f
C  [libjucx_amd64.so+0x61b1]  JNIEnv_::CallVoidMethod(_jobject*, _jmethodID*, ...)+0x81
C …
```

UCP/TAG: Call user callback from tag_recv only if NO_IMM_CMPL is passed

---

src/uct/ib/dc/dc_mlx5_ep.c

Report max_rd_atomic inconsistency as a diag rather than error message

UCT/DC: Report max_rd_atomic issue as diag instead of error

---

buildlib/pr/mad_tests.yml
buildlib/pr/main.yml
buildlib/tools/test_mad.sh

Add ucx_perftest between two nodes with MAD mode.
[HPCINFRA-1704](https://jirasw.nvidia.com/browse/HPCINFRA-1704) (Internal link).
High-level sequence of operations:
2. Build UCX with MAD on both nodes.
3. Run the server side in Docker.
4. Extract server-side target values for LID, GUID and pass them as vars to the client-side tasks.
5. Run a client-side test using LID.
6. Restart the server-side.
7. Run a client-side test using GUID.
8. Stop the server-side.
Note the stage locking, to prevent parallel test execution.

AZP/TEST: Add MAD tests

---

NEWS

Update NEWS for 1.16 GA version
Progress release.

RELEASE: Update NEWS for 1.16 GA version

---

bindings/go/src/ucx/endpoint.go
bindings/go/src/ucx/request.go
bindings/go/src/ucx/worker.go

Fixed failure:
```
request.go:32:10: cannot define new methods on non-local type *C.ucp_request_param_t
```
Checked with go1.22.2.
https://github.com/openucx/ucx/issues/9482

BINDINGS/GO: Fixed go build failure.

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c

Register rndv staging buffers on all MDs supporting registration (even if non-blocking registration is requested for the given memory type, but MD does not support it)
Fixes [RM3861726](https://redmine.mellanox.com/issues/3861726) (internal link)

UCP: Register staging buffers on all MDs supporting registration

---

src/ucp/core/ucp_context.c

Fixed the description of `UCX_REG_NONBLOCK_MEM_TYPES` configuration variable.
```
$ ucx_info -cf | grep -B 7 UCX_REG_NONBLOCK_MEM_TYPES 
#
#
UCX_REG_NONBLOCK_MEM_TYPES=
```

UCP/CORE: Fixed REG_NONBLOCK_MEM_TYPES description.

---

buildlib/pr/main.yml

Remove Valgrind testing on RoCE
It's already covered by ASAN and fails due to timeout sometimes.

CI: Remove RoCE Valgrind testing

---

src/ucs/config/parser.c

Fixed the relative path to load the configuration file.
`./configure --prefix=<install_path> && make install` installs `ucx.conf` configuration file to `<install_path>/etc/ucx`.

UCS/CONFIG: Fixed relative path to load the configuration file.

---

config/ucx.conf

Fixed [Grave Hopper].UCX_IB_MLX5_DEVX_OBJECTS value.
```
$ ucx_info -c | grep -A 1 MLX5_DEVX_OBJECTS
[1713436665.803947] [sj-cg4-01:1413613:0]          parser.c:1339 UCX  ERROR Invalid value for MLX5_DEVX_OBJECTS: '""'. Expected: comma-separated list of: [rcqp|rcsrq|dct|dcsrq|dci|cq]
[1713436665.803963] [sj-cg4-01:1413613:0]          uct_md.c:271  UCX  ERROR Failed to read MD config
[1713436665.803969] [sj-cg4-01:1413613:0]          parser.c:1339 UCX  ERROR Invalid value for MLX5_DEVX_OBJECTS: '""'. Expected: comma-separated list of: [rcqp|rcsrq|dct|dcsrq|dci|cq]
[1713436665.803973] [sj-cg4-01:1413613:0]          uct_md.c:271  UCX  ERROR Failed to read MD config
[1713436665.803978] [sj-cg4-01:1413613:0]          parser.c:1339 UCX  ERROR Invalid value for MLX5_DEVX_OBJECTS: '""'. Expected: …
```

CONFIG: Fixed UCX_IB_MLX5_DEVX_OBJECTS value.

---

src/ucp/am/rndv.c
src/ucp/proto/proto.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
src/ucp/proto/proto_init.c
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_single.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_ats.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c
src/ucp/tag/offload/rndv.c
src/ucp/tag/tag_rndv.c

- Support adding protocol variants to rendezvous protocols
- Cleanup protocols initialization code needed for to init() callback, after all protocols are switched to probe()

UCP/PROTO: Implement protocol probe for rendezvous, to support variants

---

src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h

UMR approach for XGVMI.
This part contains all the core components of the UMR approach:
- UMR primitives: CQ, QP, init, destroy
- UMR mkey pool for the exporter part
- UMR hash map for the importer side
This changeset triggers UMR workflow:
In the exporter (host process), in `uct_ib_mlx5_devx_reg_exported_key`:
- Find existing UMR mkey in the pool, or create a new one
- Bind passed UMR with given MR (if MR length is below 2GB and not MT)
- Otherwise (large or MT MR) fallback to KSM registration
- Mark UMR mkey tag (8 LBS) so that we distinguish it on the importer side
On the importer side (DPU process), when receiving new rkey (`uct_ib_mlx5_devx_mem_attach`):
- If passed mkey is UMR key, then lookup alias in the UMR hash map
- If alias is found, just use it and don't create a new one
- …

UCT/UCP: UMR approach for XGVMI

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h

Removing keepalive feature from DC transport
It's unused / not needed anymore.

UCT/IB/DC: removed dc keepalive

---

src/tools/info/tl_info.c
src/tools/perf/cuda/cuda_alloc.c
src/ucp/core/ucp_mm.c
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/base/mm_md.c
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
src/uct/ugni/base/ugni_md.c
src/uct/ze/copy/ze_copy_md.c
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h
test/gtest/uct/uct_test.cc

This is the fix for [RM#3873368](https://redmine.mellanox.com/issues/3873368).
The issue is always reproducible on rock, when building and running UCX with the following modules:
```
module load hpcx-env
module load hpcx-env/cuda
module load hpcx-env/gdrcopy
```
With `gdr_copy` MD configured, memory registration fails in several test suites:
- 3 tests in test_md
- 2 tests in uct_test
- test_uct_loopback_cuda
The root cause was always the same: CUDA memory of arbitrary size was allocated, and then this memory is registered with `uct_md_mem_reg` without any alignment. However this does not work for gdr_copy transport, because it's required to register memory aligned by GPU_PAGE_SIZE (64k in this case).
I fixed the memory registration in all those places the same way it's done in ucp_mm …

UCT/GTEST: Fixed multiple tests for gdr_copy transport

---

buildlib/pr/mad_tests.yml
buildlib/tools/test_mad.sh

Get server logs from ephemeral Docker containers.
Currently, there is no way to see stdout+stderr of the server container.
Redirect server output to a file on the workspace volume.

AZP/TEST: Add server-side log prints

---

src/tools/info/tl_info.c
src/tools/perf/cuda/cuda_alloc.c
src/ucp/core/ucp_mm.c
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/base/mm_md.c
src/uct/sm/scopy/cma/cma_md.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_md.c
src/uct/ugni/base/ugni_md.c
src/uct/ze/copy/ze_copy_md.c
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h
test/gtest/uct/uct_test.cc

This is a double commit of https://github.com/openucx/ucx/pull/9840
This is the fix for [RM#3873368](https://redmine.mellanox.com/issues/3873368).
The issue is always reproducible on rock, when building and running UCX with the following modules:
```
module load hpcx-env
module load hpcx-env/cuda
module load hpcx-env/gdrcopy
```
With `gdr_copy` MD configured, memory registration fails in several test suites:
- 3 tests in test_md
- 2 tests in uct_test
- test_uct_loopback_cuda
The root cause was always the same: CUDA memory of arbitrary size was allocated, and then this memory is registered with `uct_md_mem_reg` without any alignment. However this does not work for gdr_copy transport, because it's required to register memory aligned by GPU_PAGE_SIZE (64k in this case).
I fixed the memory …

UCT/GTEST: Fixed multiple tests for gdr_copy transport - v1.17.x

---

config/m4/mad.m4

Enable perftest MAD by default.
Runtime dependency is properly handled by dlopen() (#9637 )

CONFIG: Guess perftest MAD support by default

---

buildlib/tools/builds.sh
src/tools/perf/lib/libperf.c
src/tools/perf/mad/perftest_mad.c
src/tools/perf/perftest.c
test/apps/test_init_mt.c

TOOLS/PERF/TEST: Fix build without openmp

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5_ep.c

This reverts commit dfdaa58a96fff32563889c2c10b49852a99ab04a.
Should be fixed by allocating proper DCI with matching max_rd_atomic value

UCT/DC: Revert making peers with different max_rd_atomic unreachable

---

src/ucp/core/ucp_mm.c
src/ucs/memory/rcache.c
src/ucs/memory/rcache.h
src/uct/rocm/copy/rocm_copy_md.c
src/uct/sm/mm/xpmem/mm_xpmem.c
test/gtest/ucs/test_rcache.cc

Fix a performance degradation with #9794 due to not excessive memory re-registration when merging rcache regions
cc @Sergei-Lebedev 
Internal issue [3884209](https://redmine.mellanox.com/issues/3884209)

UCP/RCACHE: Preserve uct_flags from memory regions we merge with

---

src/uct/tcp/tcp.h
src/uct/tcp/tcp_cm.c
src/uct/tcp/tcp_ep.c
src/uct/tcp/tcp_iface.c

bind internal fd of TCP/EP to iface address
fixes https://github.com/openucx/ucx/issues/9763 miltirail case with multiple network interfaces ~~in the same subnet~~.
update: @huzhijiang [mentioned ](https://github.com/openucx/ucx/pull/9839#discussion_r1576554596) that the issue can be reproduced in different subnets too.
Add a configurable parameter `UCX_TCP_EP_BIND_SRC_ADDR=y`

UCT/TCP: bind EP fd to iface

---

src/ucm/cuda/cudamem.c
src/ucm/cuda/cudamem.h
test/gtest/ucm/cuda_hooks.cc

Add memory hooks for VMM allocations
Potential fix for internal issue [4598755 ](https://nvbugspro.nvidia.com/bug/4598755)

UCM/CUDA/TEST: Add memory hooks for cuMemMap/Unmap

---

src/ucp/core/ucp_request.h
src/ucp/proto/proto_multi.inl
src/ucp/rndv/rndv_put.c

Allow keeping same request size if increasing max lanes

UCP/RNDV/PUT: Replace request ATP/flush lane map with lane indexes

---

buildlib/pr/main.yml

Allow access to /dev/gdrdrv inode for GPU-enabled Docker containers.
[HPCINFRA-2031](https://jirasw.nvidia.com/browse/HPCINFRA-2031) (Internal link).

CI: Fix gdrcopy check by allowing the dev access from Docker

---

src/ucp/core/ucp_request.h
src/ucp/rndv/rndv.c

Removes redundant fields from request structure.
To avoid increasing `ucp_request` structure size after merging https://github.com/openucx/ucx/pull/9814
Performance was tested on osu_latency, osu_bw and osu_mbw_mr benchmarks

UCP/PROTOV1: Remove redundant fieds from request structure

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_worker.c
src/ucp/core/ucp_worker.h
src/ucp/wireup/wireup_ep.c
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h

There is a bug introduced in recent commit https://github.com/openucx/ucx/pull/9650, which is exposed in 2 ways:
- assertion failure in debug build in function `ucp_worker_iface_deactivate : wiface->activate_count > 0`
- in release mode process hangs
Revert of that commit solves the connectivity issue both for daemon CI use case and RFI.
The issue happens on the receiver side, only when there are multiple connections from the same sender. In this case there are multiple wireup_eps created and they reuse the same ep_config. However, increments and decrements of interface reference counter are not consistent:
```
First sender connect:
ucp_worker_get_ep_config -> Load new config
ucp_worker_ep_config_short_init -> Select protocols
ucp_wiface_process_for_each_lane -> activate_count ++ …
```

UCP/CORE: Fix for activate count

---

test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc

Fix heap-buffer overflow in test code.
Reported by ASAN in CI on many PRs.
```
==25238==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200009d3b8 at pc 0x55d822608015 bp 0x7ffe8ac96730 sp 0x7ffe8ac96720
READ of size 8 at 0x60200009d3b8 thread T0
#0 0x55d822608014 in uct_amo_test::run_workers(ucs_status_t (uct_amo_test::*)(uct_ep*, uct_amo_test::worker&, uct_test::mapped_buffer const&, unsigned long*, uct_amo_test::completion*), uct_test::mapped_buffer const&, std::vector<unsigned long, std::allocator<unsigned long> >, bool) /__w/6/s/contrib/../test/gtest/uct/test_amo.cc:130
#1 0x55d82261404a in uct_atomic_key_reg_rdma_mem_type_fadd64_Test::test_body() /__w/6/s/contrib/../test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc:31
```

TEST/GTEST/UCT: Fix heap-buffer overflow in AMO test

---

contrib/lsan.supp
test/gtest/common/main.cc
test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h

Backport #9877.
Branch v1.17.x also needs to build and test cleanly.

GTEST/COMMON: Cache CUDA device BAR1 available size - v1.17.x

---

buildlib/tools/test_mad.sh

Regain ownership of files in the working directory after running custom "docker run" commands.
CI fails, as it's unable to clean up root files left on hosts by the Docker container.
Findings:
```
[swx-azure-svc@vulcan03 11:00:53 azure]$ find . -user root
./agent-02/AZP_WORKSPACE/3/s/ucx_perf_srv_LID_80635.log
./agent-02/AZP_WORKSPACE/3/s/ucx_perf_srv_GUID_80635.log
```

CI/MAD: Run Docker as a user to avoid creating files as root 

---

contrib/lsan.supp
test/gtest/common/main.cc
test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h

Cache the obtained BAR1 available size.
The `nvmlInit_v2()` seems to `fork()/wait()` which is causing issues when running under valgrind.
Internal link: [3886807](https://redmine.mellanox.com/issues/3886807)
Only request available size once on a given run.

GTEST/COMMON: Cache CUDA device BAR1 available size

---

test/gtest/common/main.cc

Fix for [RM#3886801](https://redmine.mellanox.com/issues/3886801)
I managed to reproduce this issue on rock machines in 100% of the cases, but only when running this test under high CPU load. This CPU load I generate using dummy 64 processes (yes > /dev/null).
I checked ud_ep timeout logic, and it seems to work correctly. So the reasonable fix would be to increase UCX_UD_TIMEOUT (from 30s to 300s) when running under valgrind. With increased timeout the issue is not reproducible anymore, even with artificial CPU load

GTEST/UD: Increase UD EP timeout when running under valgrind

---

src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_devx.c

Set atomic_mode during DEVX device creation basing on the device capabilities.
Currently atomic_mode always set to one hardcoded value, but if extended atomics are not supported or disabled by PCI it should be set to another one.
Tested manually with PCI_ATOMICS_ENABLED_EXT_ATOMICS_DISABLED setting.

UCT/IB/DEVX: Set atomic_mode basing on device capabilities

---

test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc
test/gtest/uct/test_md.cc

Cap MEMIC allocations, to reduce out-of-memory failures
Memory is very limited, and some might already be allocated.

GTEST/UCT: Limit MEMIC allocation to prevent out-of-memory test failures

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/uct/ib/test_devx.cc

Few unit tests for XGVMI UMR approach to check that:
- Lazy initialization works as expected
- All UMR invariants are respected
- UMR mkey pool is properly used on exporter when XGVMI is supported and when it's not
- UMR mkey hash map is properly used on importer side with and without XGVMI support
- All allocated objects are freed
We introduce new config option UCX_XGVMI_UMR_ENABLE option as a part of this commit, which enables XGVMI UMR workflow.

GTEST/UCT: Unit tests for UMR XGVMI

---

src/ucp/core/ucp_mm.c
test/gtest/ucp/test_ucp_mmap.cc

`UCP_MEMH_FLAG_IMPORTED` was added in https://github.com/openucx/ucx/pull/8584, as the only memory handle flag. But this flag is only set in the memh parent, and never propagated to user memh. Despite that, flag is used on user memh:
```
ucp_am_params_check_memh(const ucp_request_param_t *param, uint32_t *flags_p)
{
...
if (ucs_unlikely(param->memh->flags & UCP_MEMH_FLAG_IMPORTED)) {
if (ENABLE_PARAMS_CHECK &&
ucs_unlikely(*flags_p & UCP_AM_SEND_FLAG_EAGER)) {
return UCS_ERR_INVALID_PARAM;
}
*flags_p |= UCP_AM_SEND_FLAG_RNDV;
}
```
I think this flag must copied from parent to child in `ucp_memh_init_from_parent`, so that we can distinguish whether user memh is attached to imported memory or not

UCP: Copy memh flags from parent to child

---

src/ucp/core/ucp_ep.inl
src/ucp/core/ucp_types.h
src/ucp/core/ucp_worker.c
src/ucp/proto/proto_init.c
src/ucp/proto/proto_multi.inl
src/ucp/rma/flush.c
src/ucp/rndv/rndv.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_cm.c
src/ucs/arch/bitops.h
src/ucs/datastruct/array.h
src/ucs/datastruct/pgtable.c
src/ucs/sys/compiler_def.h
src/ucs/sys/math.h
test/gtest/common/mem_buffer.h
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/test_ucp_tag_xfer.cc
test/gtest/ucs/test_bitops.cc

Increase number of maximal lanes per EP to 64.
To allow collecting information about all lanes on systems with many transports/devices.

UCP/WIREUP: Increase UCP_MAX_LANES to 64

---

src/ucp/api/ucp.h
src/ucp/core/ucp_mm.c

Add UCP_MEM_MAP_BLOCK so the user can enforce blocking memory mapping (e.g., non-ODP registration).
On GH systems, UCX will automatically enable nonblocking mapping (ODP) for all system-allocated memory. In certain cases, however, the user may want to explicitly disable ODP for particular ucp_mem_map calls. This flags allows the user to achieve that.

Add UCP_MEM_MAP_BLOCK flag

---

test/gtest/common/main.cc

This is double commit of https://github.com/openucx/ucx/pull/9880, into v1.17.x branch
Fix for [RM#3918537](https://redmine.mellanox.com/issues/3918537)
I managed to reproduce this issue on rock machines in 100% of the cases, but only when running this test under high CPU load. This CPU load I generate using dummy 64 processes (yes > /dev/null).
I checked ud_ep timeout logic, and it seems to work correctly. So the reasonable fix would be to increase UCX_UD_TIMEOUT (from 30s to 300s) when running under valgrind. With increased timeout the issue is not reproducible anymore, even with artificial CPU load

GTEST/UD: Increase UD EP timeout when running under valgrind - v1.17.x

---

src/ucp/proto/proto_multi.c

Calculate `perf::max_frag` as a sum across all the chosen lanes instead of choosing minimal `max_frag`.
Fix errors like [that one](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/81603/logs/449):
```
2024-05-30T17:31:50.2347606Z [ RUN      ] rcx/test_proto_reset.put_offload_zcopy/0 <rc_x>
2024-05-30T17:31:50.5009110Z [swx-rain01-bf1:712800:4:712800]  proto_init.c:730  Assertion `range_end >= caps->min_length' failed: range_end=256 caps->min_length=324
2024-05-30T17:31:50.5033953Z ==== backtrace (tid: 712800) ====
2024-05-30T17:31:50.5035454Z  0  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/build-test/src/ucs/.libs/libucs.so.0(ucs_debug_print_backtrace+0x9c) [0xffffb89a6020]
2024-05-30T17:31:50.5036470Z  1 …
```

UCP/PROTO: Accumulate max frag across all lanes

---

buildlib/pr/main.yml

Add JUCX tests on ARM
Following https://github.com/openucx/ucx/pull/9593, some of the newly added tests on ARM failed.
This PR is to troubleshoot failures and complete the ARM-based testing cycle.

AZP/SNAPSHOT: Add JUCX tests on ARM

---

src/ucs/memory/rcache.c

This is fix for [RM#3919044](https://redmine.mellanox.com/issues/3919044)
There are multiple test failures reported as:
```
==54391== Conditional jump or move depends on uninitialised value(s)
==54391==    at 0x50AE1A2: ucs_rcache_check_overlap (rcache.c:860)
==54391==    by 0x50AE1A2: ucs_rcache_create_region (rcache.c:952)
==54391==    by 0x50AE9AB: ucs_rcache_get (rcache.c:1108)
==54391==    by 0xBE26F4: test_rcache::get(void*, unsigned long, int, unsigned long) (test_rcache.cc:109)
==54391==    by 0xBD33E1: test_rcache_basic_Test::test_body() (test_rcache.cc:276)
==54391==    by 0x637499: ucs::test_base::thread_func(void*) (test.cc:397)
==54391==    by 0x995ADD4: start_thread (in /usr/lib64/libpthread-2.17.so)
==54391==  Uninitialised value was created by a stack allocation
``` …

UCS/GTEST: fixed uninitialized value access

---

src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_rtr.c
test/gtest/ucp/test_ucp_am.cc

This test provokes a data validation failure in CI
To be extended with the fix for that failure

GTEST: Use more than 1 fragment in rndv ppln test

---

test/gtest/uct/test_uct_perf.cc

Do not check gdr_copy performance in test_uct_loopback
To avoid CI failures like:
```
2024-06-03T14:20:53.8553317Z [ RUN      ] gdr_copy/test_uct_loopback_cuda.envelope/0 <gdr_copy/cuda>
2024-06-03T14:20:53.8575555Z [     INFO ] send mem type: host / recv mem type: cuda
2024-06-03T14:20:55.8972802Z [     INFO ] cuda               put latency : 8.168 usec
2024-06-03T14:20:59.5822542Z [     INFO ] cuda               put latency : 8.150 usec (attempt 1)
2024-06-03T14:21:03.2452147Z [     INFO ] cuda               put latency : 8.042 usec (attempt 2)
2024-06-03T14:21:07.0235042Z [     INFO ] cuda               put latency : 8.586 usec (attempt 3)
2024-06-03T14:21:10.7139065Z [     INFO ] cuda               put latency : 8.124 usec (attempt 4)
2024-06-03T14:21:14.4211134Z [     INFO ] cuda …
```

GTEST/UCT: Do not check gdr_copy perf in test_uct_loopback

---

src/ucp/wireup/select.c

backport #9915
Only skip AM lanes with appropriate with peers >= v1.17.

UCP/WIREUP: Only skip AM lanes for RMA with supported remote addresses - v1.17.x

---

bindings/go/Makefile.am

Fixed `make distcheck` command when go bindings are enabled.
An example of the error in the output of the command:
```
make[3]: Entering directory `/ucx/build/ucx-1.18.0/_build/sub/bindings/go'
go env -w GO111MODULE=off ; \
cd /ucx/build/ucx-1.18.0/_build/sub/../../bindings/go/src/examples/perftest ;\
go build --tags= -o /ucx/build/ucx-1.18.0/_build/sub/bindings/go/.libs/tmp/goperftest
/bin/sh: line 1: cd: /ucx/build/ucx-1.18.0/_build/sub/../../bindings/go/src/examples/perftest: No such file or directory
package .: no Go files in /ucx/build/ucx-1.18.0/_build/sub/bindings/go
```
The error was mentioned https://github.com/openucx/ucx/issues/9798.
Fixed uninstalling of the go performance benchmark. The binary should be manually removed since it is installed using install-exec-hook.

BINDINGS/GO: Fixed make distcheck.

---

config/ucx.conf
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/proto/proto_init.c
src/ucp/wireup/select.c
src/uct/base/uct_md.c
src/uct/base/uct_md.h

Removed `uct_md_rcache_overhead`. The method became unused after merging https://github.com/openucx/ucx/pull/8225.
Added logic to use previously unused `UCX_RCACHE_OVERHEAD` environment variable. The variable can be used to configure the `rcache lookup` node (applied suggestion https://github.com/openucx/ucx/pull/8995#discussion_r1160421878).
Added `UCX_RCACHE_OVERHEAD` to `[Fujitsu ARM]` section to restore adjustments made by https://github.com/openucx/ucx/pull/7583.

UCP/CORE: Use rcache overhead env for protocol perf estimation.

---

src/tools/perf/perftest_params.c

Add explanation for the "-b" flag of `ucx_perftest` help message.
Following https://github.com/openucx/ucx/discussions/9868:
The current help message of  "-b" flag of `ucx_perftest` doesn't specify that the first element of each line is supposed to be a user defined test name.
before:
after:

TOOLS/PERF: fix batch documentation

---

test/gtest/Makefile.am

Only use a single ASAN version with LD_PRELOAD.
Some machines had both libasan6 and libasan8 installed, so LD_PRELOAD tried to load them both:
`env LD_PRELOAD=/lib/aarch64-linux-gnu/libasan.so.8 /lib/aarch64-linux-gnu/libasan.so.6:  ...`
Even though libasan.so.6 was present, the linker stopped after finding libasan.so.8 and never reached the path to libasan.so.6. This resulted in error:
`env: ‘/lib/aarch64-linux-gnu/libasan.so.6:’ No such file or directory`

BUILD/ASAN: Preload a single ASAN version

---

src/ucp/wireup/select.c

Only skip AM lanes with appropriate with peers >= v1.17.
Maintain wire compatibility.
Check unpacked remote address version.
- same version, am lanes skipped
- older version, am lanes not skipped

UCP/WIREUP: Only skip AM lanes for RMA with supported remote addresses

---

.clang-format
src/ucp/tag/eager_rcv.c

Removed duplicated field from `.clang-format` file.
Used local variable assigned to the value of the structure's filed.

CLANG-FORMAT:UCP/TAG: Minor fixes.

---

test/gtest/Makefile.am

Choose ASAN version that was used during linkage for `LD_PRELOAD` setting.
To use only compatible version of ASAN during the test.

BUILD/ASAN: Choose right ASAN version for LD_PRELOAD

---

test/gtest/ucp/test_ucp_tag_match.cc

Improve asserts and remove 2.5GB transfer from test, which is causing issue on BF likely with many tests in parallel.
Expectation failure is actually due to a transport retry count failure. Also with the provided `param->recv.cb`, `req->info` content is only valid when `status == UCS_OK`.
```
[ RUN      ] dcx/test_ucp_tag_match_rndv.exp_huge_mix/0 <dc_x/rndv_auto>
...
Expected equality of these values:
sendbuf.size()
Which is: 2064117248
my_recv_req->info.length
Which is: 8000
...
Expected equality of these values:
sendbuf
Which is: { 'B' (66, 0x42), 'k' (107, 0x6B), '\x12' (18), '\x6' (6), '\0', '\0', '\0', '\0', '\xA5' (165), '0' (48, 0x30), '\xB8' (184), '<' (60, 0x3C), '\0', '\0', '\0', '\0', '\x83' (131), '\xE6' (230), '1' (49, 0x31), '_' (95, 0x5F), '\x2' (2), '\0', '\0', '\0', '/' …
```

GTEST/UCP/TAG: Avoid transfer timeouts on CI for BF

---

buildlib/jucx/jucx-build.yml
buildlib/jucx/jucx-test.yml

Remove git unshallow.
No longer needed and causes failure sometimes.

AZP: Remove git unshallow - v1.17.x

---

NEWS

Updated NEWS for 1.17
Release 1.17

RELEASE: Updated NEWS for 1.17

---

buildlib/pr/main.yml

Temporarily disable wirecompatibility tests on rain machines. The test fails due to long standing issue when RMA BW lanes performance is estimated differently in selection score function and during lanes creation in `ucp_wireup_add_rma_bw_lanes`.
To unblock CI

AZP: Disable wire-compat tests on rain machines

---

buildlib/jucx/jucx-build.yml
buildlib/jucx/jucx-test.yml

Remove git unshallow.
No longer needed and causes failure sometimes.

AZP: Remove git unshallow - master

---

buildlib/pr/io_demo/io-demo.yml

Remove io_demo tests for CX4.
CX-4 EOL.

AZP: Remove io_demo tests for CX-4

---

src/ucs/time/time.h

Included <math.h> in ucs_time_units_to_sec() to resolve compilation errors due to missing INFINITY constant.
Fixes the following build issue:
```
/ompi-mtt/ucx/src/ucs/time/time.h: In function ‘ucs_time_units_to_sec’:
/ompi-mtt/ucx/src/ucs/time/time.h:165:16: error: ‘INFINITY’ undeclared (first use in this function); did you mean ‘NFDBITS’?
return INFINITY;
^~~~~~~~
NFDBITS
/ompi-mtt/ucx/src/ucs/time/time.h:165:16: note: each undeclared identifier is reported only once for each function it appears in
In file included from  /ompi-mtt/ucx/src/ucm/util/sys.h:13,
from  /ompi-mtt/ucx/src/ucm/bistro/bistro_int.h:16,
from bistro/bistro.c:18:
/ompi-mtt/ucx/src/ucs/time/time.h: In function ‘ucs_time_units_to_sec’:
/ompi-mtt/ucx/src/ucs/time/time.h:165:16: error: ‘INFINITY’ undeclared (first use in …
```

UCS/TIME: Fix undeclared INFINITY error in ucs_time_units_to_sec()

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
src/ucp/rndv/proto_rndv.c

Place full protocol chain to the perf nodes' names.
Makes protocol graph debugging more convenient.
| Before| After|
|--------|--------|
| ![image](https://github.com/openucx/ucx/assets/22097249/f52ea648-1caf-4561-8f2c-91a38e0e8ec2)| ![image](https://github.com/openucx/ucx/assets/22097249/0d5cd410-4f7f-4f82-aff2-4be127925bc1)|

UCP/PROTO: Make perf nodes names more informative

---

buildlib/pr/io_demo/io-demo.yml

Remove io_demo tests for CX4.
(Porting https://github.com/openucx/ucx/pull/9935 by cherry-pick)
CX-4 EOL.

AZP: Remove io_demo tests for CX4 - v1.17.x

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h

Keep trying to register memory. If it return EAGAIN it means following registration should succeed.

UCT/IB: Retry ODP registration unlimitedly

---

config/m4/cuda.m4
src/ucm/cuda/cudamem.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h
test/gtest/ucm/cuda_hooks.cc

Breaking https://github.com/openucx/ucx/pull/9787 into parts. This part isolates:
1. Fabric memory detection in cuda_copy transport
2. Change UCM cuda hooks to treat mallocasync memory as CUDA memory and not CUDA managed memory.
3. Add ability to allocate fabric pinned memory for rendezvous fragments
1. This will break existing mallocasync support which applies managed memory pipeline protocols
2. Currently EGM fabric VMM allocations are treated as device memory for subsequent PRs to leverage NVLINKs for EGM transfers. In a subsequent PR, this change will be reverted once it is confirmed that cuda_ipc supporting host memory doesn't break UCP protocolsV2.

UCT/CUDA: Detect fabric vmm memory

---

test/gtest/ucp/test_ucp_wireup.cc

Fix ordering issue in the test. Need to wait for flush to complete before issuing the second put.
Fixes internal issue [RM3916800](https://redmine.mellanox.com/issues/3916800)

GTEST: Wait for flush to complete between 2 puts

---

src/ucp/api/ucp.h
src/ucp/core/ucp_am.c
test/gtest/ucp/test_ucp_am.cc

When registering an AM handler, ensure the id fits within the `uint16_t` range.
The AM API accepts the AM handler id as an `unsigned int`, but internally the id is constrained to `uint16_t`. This difference can cause multiple ids (up to 2^16) to map to the same internal id, ultimately referring to the same AM handler (the last one registered).
When registering AM handler, ensure `param->id`'s 16 msb are not set. If any of them are non-zero, the function returns an error.

UCP/AM: Limit active message id to uint16_t

---

buildlib/az-github-draft.yml

Include RC version in the UCX source tarball name.
Unify naming convention.

AZP/RELEASE: Include revision in tarball filenames

---

test/gtest/Makefile.am

disable-new-dtags to use RPATH instead of RUN_PATH to avoid loading of wrong libucp.so if it's accessible by LD_LIBRARY_PATH
fixes https://github.com/openucx/ucx/issues/9890
add the parameter to the linker command

GTEST: disable-new-dtags

---

src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h
test/gtest/Makefile.am
test/gtest/uct/cuda/test_cuda_ipc_md.cc

Redesigned peer accessible cache in uct_cuda_ipc component.
There were several design flaws in existing implementation:
- uct_cuda_ipc_component stores a reference to the last created MD. However if last MD is closed this leads to the dangling pointer (root cause of VASP application segfault)
- peer accessible cache is not thread safe, fails in case of multiple contexts
- cache is stored per each cuda_ipc MD, but in fact only the last created MD is used for caching
- minor: improved lookup to use hash map instead of an array based search
Consideration: locking
- global cache, single lock (current impl)
- cache in TLS
- cache per UCT worker
UPD:
I tested lock overhead with ucx_perftest on 4-16 threads with different message sizes (64-4096).
There is **no visible performance drop** when …

UCT/CUDA_IPC: Redesign peer accessible cache

---

src/ucs/arch/x86_64/cpu.c
test/gtest/ucs/arch/test_x86_64.cc

It fine-tunes the nt-buffer-transfer copy functions
It is an enhancement.
a) add prefetch_tail to mark cache lines with NTA precisely
b) align the writes to handle unaligned transfers more efficiently
c) reduce the gtest time

ARCH/X86: fine tune nt-buffer-transfer functions

---

src/uct/ib/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/rc/accel/gga_mlx5.c
src/uct/ib/rc/accel/rc_mlx5.h
src/uct/ib/rc/accel/rc_mlx5.inl
src/uct/ib/rc/accel/rc_mlx5_common.c
src/uct/ib/rc/accel/rc_mlx5_ep.c
src/uct/ib/rc/accel/rc_mlx5_iface.c
src/uct/ib/rc/base/rc_iface.c
test/gtest/common/test_helpers.cc
test/gtest/common/test_helpers.h
test/gtest/uct/ib/test_ib_pkey.cc
test/gtest/uct/test_p2p_am.cc
test/gtest/uct/uct_test.h

Implement and test basic GGA iface and ep infrastructure
Continue https://github.com/openucx/ucx/pull/9811

UCT/GGA: basic iface and ep infrastructure

---

src/ucs/async/async.c
src/ucs/datastruct/mpmc.c
src/ucs/datastruct/mpmc.h
test/gtest/ucs/test_async.cc

Skip events in poll missed process if its handler has already been removed.
Async handler might be removed while events missed.
When the handler be called in poll missed process and same memory is reused by the other worker, the handler will try to access wrong resources.
Set MPMC queue element's value to -1 if handler removed, then skip the events in poll missed process.

UCS/ASYNC: Skip released handler in poll missed process

---

src/ucs/sys/topo/base/topo.c

Bandwidth on different NUMA nodes is almost identical to the ones on same NUMA nodes on Grace.
Issue: [3972096](https://redmine.mellanox.com/issues/3972096)
With GPU0 on NUMA 0, mlx5_0/mlx5_3/mlx5_7/mlx5_9 on NUMA 0/1/2/3. Without that patch, mlx5_0 is seen so fast that other interfaces are not used for D2H transfers (RNDV get), and bandwidth is capped at <50GBs (400Gbps CX7).
Adding huge `UCX_MULTI_LANE_MAX_RATIO` leads to using many interfaces but with traffic still going through mlx5_0:1 for >90% of it.

UCS/TOPO: Set higher bandwidth for different NUMA nodes on Grace

---

contrib/test_jenkins.sh

Fix test failures such as "Kill xxxxx : no such process"

TEST/JENKINS: Ignore failure to kill the server in client/server test

---

src/tools/info/type_info.c
src/uct/ib/base/ib_device.h
src/uct/ib/dc/dc_mlx5.c
src/uct/ib/dc/dc_mlx5.h
src/uct/ib/dc/dc_mlx5_devx.c
src/uct/ib/dc/dc_mlx5_ep.c
src/uct/ib/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

Instead of creating all dci pools (and dcis) on iface init, dci pools will be created dynamically on demand by configuration
As part of the active messages priority feature - creating different pools with different SLs is required, enabling dedicated dci pools for different lanes with different priorities, as we can't change SL of a dci (qp) after creation / connection.
For each new dc ep created - a matching dci pool will be created unless a dci pool with the same exact configuration already exists in the hash table, in which the configuration is the key and the value is pool_index, so eps which share configuration will also share a dci pool.

UCT/IB/DC: dynamic allocation of dci pools by configuration

---

src/ucp/core/ucp_worker.c
src/ucs/datastruct/array.c
src/ucs/datastruct/array.h
test/gtest/ucs/test_datatype.cc

Skip calling `memcpy` when passing `_old_buffer_p` to `ucs_array_append_safe` / `ucs_array_reserve_safe`, making it callers responsibility copying the data to the new allocated buffer.
Some arrays may contain pointers or pointer-based data structures (e.g. linked lists), for which a`memcpy` won't do, and the inner data structures would break.

UCS/DATASTRUCT: disable memcopy when passing _old_buffer_p to array_grow

---

buildlib/azure-pipelines-release-drp.yml

Create a parallel pipeline for UCX release from DRP.
Redundancy in case of issues with the main site.

AZP/RELEASE: Create a DRP release pipeline

---

src/uct/api/v2/uct_v2.h

Fix doc (flag `UCT_MD_MKEY_PACK_FLAG_INVALIDATE` does not exist)

UCT: Fix descriprion of uct_md_flags_v2_t

---

src/tools/perf/lib/uct_tests.cc

add fence to UCT/STREAM_UNI test before sentinel ack
if TL does not guarantee put-after-put ordering then test may hang due to wrong value in recv buffer

PERF: add fence to UCT/STREAM_UNI test before sentinel ack

---

src/uct/rocm/copy/rocm_copy_md.c

fix for the test_md_fork test of gtest for ROCm devices and memory domains.

UCT/ROCM: fix test_md_fork

---

buildlib/pr/wire_compat.yml
buildlib/tools/check_tls_perf_caps.sh
buildlib/tools/test_wire_compat.sh

Some fixes in wire-compat testing:
- Use tag API in client-server example to make sure that RMA BW lanes are established
- Use `UCX_TCP_BRIDGE_ENABLE=y` to not fail `check_tls_perf_caps.sh`, because bridge devices are not shown in `ucx_info -d` since #9487
- Do not try to connect to different subnet addresses with RoCE

AZP: Multiple wire-compat test fixes

---

src/ucm/util/sys.c

Backport the related #9901 and #9876 to keep the code in sync with master.

UCM: Use mmap instead of mremap while parsing /proc/self/maps - v1.17.x

---

src/ucm/cuda/cudamem.c
src/ucm/util/log.h
src/ucm/util/replace.h
src/ucs/debug/assert.h
src/ucs/debug/log_def.h
src/ucs/memory/rcache_int.h
src/ucs/profile/profile_defs.h
src/uct/ib/base/ib_log.h
src/uct/ib/mlx5/ib_mlx5_log.h

Use `__func__` instead of `__FUNCTION__` on supported C versions
To meet [C standard](https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html)

UCS/SYS/COMPILER_DEF: use __func__ instead of __FUNCTION__ to meet standard

---

src/ucp/api/ucp.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h

This addition to the endpoint query API adds a new field_mask value that
will instruct ucp_ep_query to return the endpoint's user_data pointer.
The UCP API allows the user to register a user_data pointer inside of an
endpoint. Currently this pointer is only exposed back to the user in
the error callback and via ucp_stream_worker_poll.
When working in a code base that has many endpoints associated with a
single worker, the application needs to create a mapping data structure
between endpoints and user data that it accesses in the AM callback.
This is an extra overhead that can be avoided by simply adding a way
to extract the user_data pointer out of the endpoint.

UCP: Add user_data to ucp_ep_query

---

test/gtest/ucp/test_ucp_sockaddr.cc

Remove CM_USE_ALL_DEVICES=n modifier for `test_ucp_sockaddr_protocols_err_sender` test
Before that patch `CM_USE_ALL_DEVICES` always was set to 0 for this test since this test doesn't have variant for different CM options. I believe that was done by mistake and it is better to run test like this on default configuration (CM_USE_ALL_DEVICES=y).

UCP/PROTO/TEST: Remove CM_USE_ALL_DEVICES=n modifier from RNDV err sender test

---

contrib/lsan.supp
contrib/valgrind.supp

When binutils-dev package is installed on CI machines, it triggers ASAN/valgrind errors:
```
#0 0xffff8d49a2f4 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
#1 0xffff8cb9c3f8  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xac3f8)
#2 0xffff8cb9e0f0  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xae0f0)
#3 0xffff8cb9f94c  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xaf94c)
#4 0xffff8cba3928  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xb3928)
#5 0xffff8cb73294 in _bfd_elf_find_nearest_line (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0x83294)
#6 0xffff8d306cfc in find_address_in_section /scrap/azure/agent-02/AZP_WORKSPACE/3/s/contrib/../src/ucs/debug/debug.c:335
#7 0xffff8cb3f99c in bfd_map_over_sections …
```

GTEST: ASAN suppression for memory leak in binutils/bfd

---

src/uct/cuda/cuda_copy/cuda_copy_md.c
test/gtest/ucp/test_ucp_am.cc

- Do not log errors reproted by cuda fabric allocations if FABRIC_ENABLE config is not set to yes
- Add a test checking that sending cuda memory thru cuda staging buffers is possible
Fixes the following errors:
```
[ RUN      ] rc/test_ucp_am_nbx_rndv_ppln.cuda_buff_cuda_frag/0 <rc_v,cuda_copy,rocm_copy>
[1720611489.711215] [rock06:27460:0]    cuda_copy_md.c:241  UCX  ERROR   cuMemCreate(&alloc_handle->generic_handle, alloc_handle->length, &prop, 0) failed: operation not permitted
[1720611489.726205] [rock06:27460:0]    cuda_copy_md.c:241  UCX  ERROR   cuMemCreate(&alloc_handle->generic_handle, alloc_handle->length, &prop, 0) failed: operation not permitted
```

UCT/GTEST: Fix cuda_copy md allocations

---

src/ucs/datastruct/array.h
src/ucs/datastruct/list.h
src/ucs/datastruct/queue.h
src/ucs/debug/debug.h
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

Used `ucs_array_append_safe` when adding a new DCI, and `ucs_array_resize_safe` in random policy
Applying changes from #9930 to `dcis` array and avoiding the reservation of the entire array (a fix that was used as a workaround to `ucs_array_t` copy issue)

UCT/IB/DC: apply append_safe mechanism to dcis array, added ucs_array_resize_safe for similar reasons

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

HW_DCS policy assumes a dci was already created, leading to infinite polling if not creating it in ep_basic_init
* Added a few simple hw_dcs tests as that policy is not tested in CI at all.
This is a bug that started in one of the recent features: dynamic creation of dcis (#9665)

UCT/IB/DC: minor fix - hw_dcs assumes 1 dci was created

---

src/ucs/datastruct/string_buffer.c
src/ucs/datastruct/string_buffer.h
src/ucs/sys/sock.c
src/ucs/sys/sock.h
src/uct/ib/base/ib_iface.c
test/gtest/ucs/test_sock.cc

Added new API for subnet match support.
To allow subnet matching from all parts of code.
Before this PR, subnet matching was done only in ib_iface_roce_is_reachable, but there is a demand to support it also for
matching with user configured subnets (ie. for GID selection).
This is the first PR of the GID subnet filter feature.

UCS/SOCK: Added subnet match support

---

contrib/lsan.supp
contrib/valgrind.supp

Double commit of https://github.com/openucx/ucx/pull/10023 into v1.17.x branch
When binutils-dev package is installed on CI machines, it triggers ASAN/valgrind errors:
```
#0 0xffff8d49a2f4 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
#1 0xffff8cb9c3f8  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xac3f8)
#2 0xffff8cb9e0f0  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xae0f0)
#3 0xffff8cb9f94c  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xaf94c)
#4 0xffff8cba3928  (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0xb3928)
#5 0xffff8cb73294 in _bfd_elf_find_nearest_line (/lib/aarch64-linux-gnu/libbfd-2.38-system.so+0x83294)
#6 0xffff8d306cfc in find_address_in_section /scrap/azure/agent-02/AZP_WORKSPACE/3/s/contrib/../src/ucs/debug/debug.c:335
#7 …
```

GTEST: ASAN suppression for memory leak in binutils/bfd - v1.17.x

---

src/uct/base/uct_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/self/self.c
test/gtest/uct/test_uct_ep.cc
test/gtest/uct/uct_test.h

Fixed uct_ep_is_connected API for 3 transports: knem, self, cuda_ipc.
These transports should support is_connected API in order for EP reconfiguration to work properly.
1) The macro `UCT_EP_IS_CONNECTED_CHECK_DEV_IFACE_ADDRS` is removed from `uct_base_ep_is_connected`, in order to allow transports without dev_addr to use it (eg. knem).
2) In cuda_ipc/self -> updated `ep_is_connected` callback.

UCT/KNEM/CUDA_IPC/SELF: Fixed uct_ep_is_connected

---

src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/ib/base/ib_iface.c
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/rc/rc_mlx5_iface.c

During the wireup process, provide a reason when a resource's lane is unreachable.
Users need more information about why a device is not reachable after an unsuccessful connection establishment. This information should be passed from UCT to UCP. 
Pass a string to select/search_lane functions so in case the wireup process fails, the reason will be printed out in an upper layer.

UCP/WIREUP/IB: provide a reason when a resource's lane is unreachable

---

src/ucs/config/parser.c
src/ucs/config/parser.h
src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
test/gtest/uct/ib/test_ib.cc

Allow to specify a list of allowed/restricted subnets, of which a GID would be selected from.
To support setups with asymmetric GID table configuration.
Request came from following ticket:
https://nvbugspro.nvidia.com/bug/4214093
1) Add a new config var: UCX_ROCE_SUBNET_FILTER_LIST, which will be of the following pattern: 
1.1.1.1/24,2.2.2.2/16,3.3.3.3/8
2) Move `uct_ib_iface_roce_to_sockaddr` from `ib_iface.c` to `ib_device.c`, and rename it to `uct_ib_device_roce_gid_to_sockaddr`.
3) In RoCE GID initialization:
- Parse the given subnets and report any issues.
- Iterate through all gid entries and check if match to any subnet.
For now, checked manually.
When CI setup is ready, will add gtests as well.
ticket for CI setup:
https://jirasw.nvidia.com/browse/HPCINFRA-2389

UCT/IB: Support subnet filter list for RoCE GID

---

src/ucp/core/ucp_request.h
src/ucp/rndv/rndv_put.c

Minimal backport of #10029 for v1.17.x branch.
The rndv/put code has changed between master and v1.17.x branch, so this backport does not include the refactoring.

UCP/RNDV: Fix sending too many ATPs for small messages - v1.17.x

---

src/uct/cuda/gdr_copy/gdr_copy_md.c

Fix crash in `uct_gdr_copy_md_close` when GDR_COPY rcache is disabled
```
0x00007f3ef989542f in __GI___wait4 (pid=pid@entry=3071342, stat_loc=stat_loc@entry=0x7f3efac6ceac, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x00007f3ef989542f in __GI___wait4 (pid=pid@entry=3071342, stat_loc=stat_loc@entry=0x7f3efac6ceac, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00007f3ef98953ab in __GI___waitpid (pid=pid@entry=3071342, stat_loc=stat_loc@entry=0x7f3efac6ceac, options=options@entry=0) at ./posix/waitpid.c:38
#2  0x00007f3efd01bbbf in ucs_debugger_attach () at debug/debug.c:819
#3  0x00007f3efd01eef9 in ucs_error_freeze …
```

UCT/GDR: Fix md_close when no rcache

---

src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_perf.c
src/ucp/proto/proto_perf.h
src/ucp/proto/proto_reconfig.c
src/ucp/proto/proto_select.c
src/ucs/datastruct/array.h
src/ucs/datastruct/string_buffer.c
test/gtest/ucp/test_ucp_proto.cc

The first part of #9954 which includes changes related to `ucp_proto_perf_t`  structure. The main changes is introduction of 
`ucp_proto_flat_perf_t` structure which stores result of sum or envelope across all the factors for all ranges. It required to calculate final performance estimation for SINGLE or MULTI mode.
Origin PR is too big to merge it without separation.

UCP/PROTO: Extend ucp_proto_perf structure interfaces

---

config/m4/mad.m4

Make m4 shell test POSIX bourne compliant as per report in #10041.
Configuration step always fails on some distributions.

CONFIG/M4: Use POSIX bourne syntax to check equality

---

src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
test/gtest/uct/ib/test_ib.cc

Modified the function `uct_ib_device_is_gid_raw_empty` to check if the lower 64 bits of the GID are all zeros, indicating an invalid GID, and renamed it to `uct_ib_device_is_invalid_gid`.
The previous implementation checked all 128 bits of the GID to determine if it was invalid. As a result, GIDs like "fe80:0000:0000:0000:0000:0000:0000:0000" weren't filtered out, even though they are considered invalid. The new implementation aligns with the filter used in `ibv_devinfo`: https://github.com/linux-rdma/rdma-core/blob/a7528e06cf108954ea1fddb96d4aab240ae6c5a0/libibverbs/examples/devinfo.c#L225, ensuring consistency and accuracy in identifying invalid GIDs.
Renamed and modified the function to check the lower 64 bits.

UCT/IB: fix invalid GIDs filter

---

src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h

Improve error logging for UAR allocation failure in `uct_ib_mlx5_devx_alloc_uar`.
To inform users to increase `PF_LOG_BAR_SIZE` and reboot when UAR allocation fails due to insufficient memory.
see also: https://github.com/open-mpi/ompi/issues/6854
Update the error message in `uct_ib_mlx5_devx_alloc_uar` to suggest increasing `PF_LOG_BAR_SIZE` and mention the reboot requirement.

UCT/IB/MLX5: suggest user to increase PF_LOG_BAR_SIZE when UAR allocation fails

---

test/gtest/ucp/test_ucp_worker.cc

Fix tcp device name detection in pci bw test
```
2024-08-14T21:20:05.1331101Z [----------] 1 test from all/test_pci_bw
2024-08-14T21:20:05.1332298Z [ RUN      ] all/test_pci_bw.get_pci_bw/0 <all/tag>
2024-08-14T21:20:05.5218597Z /scrap/azure/agent-08/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_worker.cc:923: Failure
2024-08-14T21:20:05.5220864Z Expected: (pci_bw) < (std::numeric_limits<double>::max()), actual: 1.79769e+308 vs 1.79769e+308
2024-08-14T21:20:05.6323040Z [  FAILED  ] all/test_pci_bw.get_pci_bw/0, where GetParam() = all/tag (499 ms)
2024-08-14T21:20:05.6325843Z [----------] 1 test from all/test_pci_bw (499 ms total)
```
```
mikhailb@swx-rain03:~/work/ucx$ ls /sys/class/net/bond0/slave_*
ls: cannot access '/sys/class/net/bond0/slave_*': No such file or directory …
```

GTEST: Fix tcp_device name detection in pci_bw test

---

src/tools/vfs/Makefile.am
src/tools/vfs/vfs_daemon.h
src/tools/vfs/vfs_main.c
src/tools/vfs/vfs_server.c
src/ucs/config/global_opts.c
src/ucs/config/global_opts.h
src/ucs/sys/string.c
src/ucs/sys/string.h
src/ucs/vfs/fuse/vfs_fuse.c
src/ucs/vfs/sock/vfs_sock.c
src/ucs/vfs/sock/vfs_sock.h

Make VFS unix socket path configurable with UCX_VFS_SOCK_PATH option
By default put listening socket in dedicated folder: `/run/user/<user_id>/ucx/vfs.sock`
We use inotify watch from the client side to detect VFS server presence. When we run inotify watch in a public folder (/tmp) with many files, then we experience the following issues:
- inotify_add_watch can take more than a second to start (in NVHPC cluster), and the main thread is delayed
- we wake VFS fuse thread on all the file create events, even unrelated to us
Added option UCX_VFS_SOCK_PATH to configure socket path on the client side. Before it was only configurable on VFS daemon side with -l option.
Use %i wildcard that represents user_id. Ideally we should use `ucs_fill_filename_template` here, but ucs library is not linked by …

UCS/VFS: inotify watch from private user folder

---

src/ucs/debug/log.c

Add log level check to `ucs_log_print_backtrace`
Currently `ucs_log_print_backtrace` doesn't check if the given log level is enabled in UCX
Used `ucs_log_is_enabled` to check the given log level

UCS/LOG: add log level check to UCS backtrace log

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h

Second part of https://github.com/openucx/ucx/pull/9787 and follow up to https://github.com/openucx/ucx/pull/9867. This implements IPC-support for fabric handle associated memory using the newer import/export API and caches import operations similar to legacy IPC handles.
Note: need to solve https://redmine.mellanox.com/issues/4005305 before merging

UCT/CUDA_IPC: Fabric memory support

---

buildlib/pr/coverity.yml
buildlib/tools/common.sh
buildlib/tools/coverity.sh

Allow iterative runs for coverity script.
A full run takes more than 30 minutes. Using the added `INCREMENTAL=yes` allows rebuild with html generation within 6 minutes.
Split configure and cleanup part.
```
$ parallel_jobs=32 ENABLE_JAVA=no BUILD_ID=scrap/build ./buildlib/tools/coverity.sh devel
$ INCREMENTAL=yes parallel_jobs=32 ENABLE_JAVA=no BUILD_ID=scrap/build ./buildlib/tools/coverity.sh devel
```

COVERITY: Allow iterative runs for faster turnaround time

---

src/ucp/core/ucp_ep.c

Use proper flags for checking bcopy capability before sending keepalives.
Was previously ending-up using `UCP_WORKER_IFACE_FLAG_ON_ARM_LIST` potentially causing transcient errors.
Exercise code path with `./test/gtest/gtest --gtest_filter=ud/test_ucp_peer_failure_keepalive.kill_receiver/0` where we should see wireup check AM being sent instead of zero size PUT.

UCP/CORE: Fix wrong flag being used for checking BCOPY capability

---

src/ucp/core/ucp_context.c

Limit the transport availability check to configuration lists set to ALLOW mode only.
Currently ucp_context checks the availability of a user configured transport even when the configuration list is set to NEGATE (i.e. all the transports in this list must NOT be used). This creates a problem when the user excludes an already unavailable transport, for instance `UCX_TLS=^gdr_copy`.

UCP/CONFIG: limit transport availability check to ALLOW mode configuration lists only

---

buildlib/tools/builds.sh

Added logic to `builds.sh` to print the test name if a test fails.
To quickly identify which test failed, improving debugging efficiency.
Inserted a conditional check after each test in builds.sh to print the test name and exit on failure.

BUILD: print test name on failure in builds.sh

---

src/ucm/cuda/cudamem.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h

Detect async memory allocations as cuda-managed memory to avoid cuda-ipc transport being selected.
Fixes a regression from #9867 
```
Allocate async cuda memory
Allocate async cuda memory
cuda_ipc_md.c:112  UCX  ERROR cuIpcGetMemHandle(&key->ph, (CUdeviceptr)addr) failed: invalid argument
proto_common.inl:373  UCX  ERROR failed to pack remote key: Input/output error
cuda_ipc_md.c:112  UCX  ERROR cuIpcGetMemHandle(&key->ph, (CUdeviceptr)addr) failed: invalid argument
proto_common.inl:373  UCX  ERROR failed to pack remote key: Input/output error
proto_rndv.c:850  Assertion `(address != 0) == (rkey_length > 0)' failed: rts rts->address=0x320000000 rkey_length=0
```

UCT/CUDA: Detect async allocations as managed (plus env var)

---

src/uct/ib/base/ib_md.c

UCT/IB: Fix MD allocation naming typo

---

src/ucs/arch/x86_64/cpu.c

The MI300A has 24 Zen4 cores, which are architecturally (mostly) identical to the Genoa processors. They have however a different CPU id. Add the CPU ID to recognize CPU on this architecture.

ARCH/X86: Add CPU Model for MI300A

---

buildlib/pr/main.yml

Add '--ipc=host' docker option for GPU nodes.
Fix CUDA segfaults during tests.
https://github.com/NVIDIA/nvidia-docker/issues/1396

GPU/DOCKER: Add --ipc=host docker option for GPU

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl

Fix performance gap when requesting registered memory with alternating access flags.
Internal issue: [4007343](https://redmine.mellanox.com/issues/4007343)
It is possible to observe 10x performance reduction depending on the use-case due to this invalidation bouncing, between:
- `UCT_MD_MEM_ACCESS_LOCAL_WRITE` / `UCT_MD_MEM_ACCESS_REMOTE_PUT`
Augment registration flags.

UCP/MM: Augment registered access flags to avoid repeated invalidations

---

buildlib/pr/wire_compat.yml
buildlib/tools/test_wire_compat.sh

Use different ports in one wire-compat job to avoid CI failures like
```
[1724129739.884304] [swx-rdmz-ucx-new-02:17268:0]          parser.c:2307 UCX  WARN  (set UCX_WARN_UNUSED_ENV_VARS=n to suppress this warning)
[1724129739.884905] [swx-rdmz-ucx-new-02:17268:0]          parser.c:2314 UCX  INFO  UCX_* env variables: UCX_WARN_UNUSED_ENV_VARS=n UCX_TLS=^sm UCX_CM_REUSEADDR=y UCX_IB_ROCE_LOCAL_SUBNET=y UCX_LOG_LEVEL=info
[1724129740.029045] [swx-rdmz-ucx-new-02:17268:0] rdmacm_listener.c:83   UCX  DIAG  rdma_bind_addr(addr=0.0.0.0:22000) failed: Cannot assign requested address
[1724129740.029084] [swx-rdmz-ucx-new-02:17268:0]    ucp_listener.c:242  UCX  DIAG  failed to create UCT listener on CM 0x10e1830 (component rdmacm) with address 0.0.0.0:22000 status Device is busy
failed to listen …
```

AZP: Use different ports in one wire-compat job

---

src/uct/ib/base/ib_device.c

Adding ConnectX-8 device spec
So UCX will be able to identify ConnectX-8 devices and use them

UCT/IB/BASE: added ConnectX-8 to uct_ib_builtin_device_specs[]

---

config/ucx.conf
src/ucs/config/global_opts.c
src/ucs/config/global_opts.h
src/ucs/memory/numa.h
src/ucs/sys/topo/base/topo.c

Added options to set estimated latency and bandwidth values according to the distance within the sysfs device tree.
Moved platform specific values to `ucx.conf` file.

UCS/SYS/TOPO: Added options to set distance between devices.

---

src/uct/ib/mlx5/dc/dc_mlx5_ep.h

Removed limitation of `dci_channel_index` by `num_dci_channels`
Improvement in performance, utilization of all 256 DCI channels

UCT/IB/MLX5/DC: dci_channel_index is not limited by num_dci_channels

---

src/uct/ib/mlx5/dc/dc_mlx5.c

Increase default numbers of dcis in each pool to 32
Performance optimization

UCT/IB/MLX5/DC: increase default NUM_DCIS to 32

---

src/ucs/vfs/fuse/vfs_fuse.c

Fix for https://redmine.mellanox.com/issues/4044773
We see that fuse thread is not interrupted from the main thread dtor, and remains waiting for data in the read:
```
Thread 2 (Thread 0x7fb4cffff700 (LWP 420349)):
#0  0x00007fb4de0abaa4 in read () from /lib64/libpthread.so.0
#1  0x00007fb4de6448f6 in ucs_vfs_fuse_wait_for_path (path=path@entry=0x7fb4cfffecd2 "/run/user/90540/ucx/vfs.sock") at vfs_fuse.c:311
#2  0x00007fb4de644c2d in ucs_vfs_fuse_thread_func (arg=<optimized out>) at vfs_fuse.c:418
Thread 1 (Thread 0x7fb4de7fb8c0 (LWP 420284)):
#0  0x00007fb4de0a36bd in __pthread_timedjoin_ex () from /lib64/libpthread.so.0
#1  0x00007fb4de6443d5 in ucs_fuse_thread_stop () at vfs_fuse.c:510
```
The only reason it can happen is that folder that we monitor (`/run/user/<user_id>/ucx`) gets …

UCS/VFS: Detect deletion of the monitored folder

---

test/gtest/common/test.h
test/gtest/configure.m4
test/gtest/ucp/ucp_test.h
test/gtest/ucs/test_callbackq.cc
test/gtest/uct/uct_test.h

Fix test failures like:
```
2024-07-10T10:31:07.4474989Z [ RUN      ] test_callbackq.oneshot_mt/mt_10 <> <>
2024-07-10T10:31:07.4478332Z /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucs/test_callbackq.cc:360: Failure
2024-07-10T10:31:07.4478820Z Expected equality of these values:
2024-07-10T10:31:07.4479038Z   1u
2024-07-10T10:31:07.4479254Z     Which is: 1
2024-07-10T10:31:07.4479513Z   ctx.count
2024-07-10T10:31:07.4479810Z     Which is: 1
2024-07-10T10:31:07.4481242Z [  FAILED  ] test_callbackq.oneshot_mt/mt_10, where TypeParam =  and GetParam() =  (1 ms)
2024-07-10T10:31:07.4481612Z [ RUN      ] test_callbackq.remove_self_safe <> <>
```

TEST/CALLBACKQ: Fix test_callbackq.test_callbackq test failures

---

src/ucp/core/ucp_mm.c

Set memh reg_id when memh is created.
Currently reg_id is reset every ucp_memh_get_slow() call e.g. when there is a pending memory event.

UCP/MM: Set reg_id when memh created

---

buildlib/tools/check_tls_perf_caps.sh

Fix wire compat CI failures on v1.17.x branch
Backport #10113 to v1.17.x + minor whitespace fix

TEST/COMPAT: Fix wire compat test failures - v1.17.x

---

debian/ucx.install

Also package UCT mlx5 library for Debian.
Internal issue: [4054962](https://redmine.mellanox.com/issues/4054962)
Tested:
```
dpkg-buildpackage -us -uc
dpkg --contents ucx_1.18.1f91c55_amd64.deb | grep uct_mlx5
```

DEBIAN: Add libuct_ib_mlx5.so to package

---

buildlib/tools/builds.sh

Updated ucx/buildlib/tools/builds.sh to allow running a specific test by passing its name as an argument.
To make debugging more efficient by allowing developers to run only the necessary test.
Added logic to check for a test name argument and run only that test if provided, with error handling for invalid names.

BUILD: enable single test run in builds.sh

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h

define `ucp_ep_init_create_wireup` as static
code cleanup, I noticed that `ucp_ep_init_create_wireup ` function is used only once

UCP/EP/WIREUP: minor code cleanup

---

src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/sm/base/sm_iface.c
src/uct/sm/base/sm_iface.h
src/uct/sm/mm/base/mm_iface.c
src/uct/sm/scopy/cma/cma_iface.c
src/uct/sm/scopy/knem/knem_iface.c
src/uct/sm/self/self.c
src/uct/tcp/tcp_iface.c
src/uct/ze/copy/ze_copy_iface.c

During the wireup process, provide a reason when a resource's lane is unreachable (second part after https://github.com/openucx/ucx/pull/9995. Includes all the transports other than IB).
Users need more information about why a device is not reachable after an unsuccessful connection establishment. This information should be passed from UCT to UCP.
Pass a string to select/search_lane functions so in case the wireup process fails, the reason will be printed out in an upper layer.

UCP/WIREUP: specify a reason for wireup failure - part 2

---

src/ucs/arch/x86_64/cpu.c

The MI300A has 24 Zen4 cores, which are architecturally (mostly) identical to the Genoa processors. They have however a different CPU id. Add the CPU ID to recognize CPU on this architecture.
(cherry picked from commit 8b2113067bc5d158561c9564282d52c5e79d3bfe)

ARCH/X86: Add CPU Model for MI300A - v1.17.x

---

src/ucm/api/ucm.h
src/ucp/core/ucp_context.h
src/ucs/config/global_opts.h
src/ucs/config/parser.c
src/uct/ib/base/ib_md.h

Align all users to `uint64_t` and validate bit ranges.
We were previously using `uint64_t` for one configuration instead of the then expected `unsigned`.

UCS/CONFIG: Use uint64_t to parse configuration bitmaps

---

src/ucs/sys/string.c
src/ucs/sys/string.h
src/ucs/sys/topo/base/topo.c

This PR changes all stack allocations of char arrays sized `PATH_MAX` to heap allocations in `topo.c`.
Customers with limited stack sizes have recently experienced stack overflow issues when running UCX, where functions like `ucs_topo_get_distance_sysfs()` were using more than 12kB of stack space due to multiple PATH_MAX-sized stack allocations. 
They have temporarily increased their stack size to mitigate this, but a code change in UCX is needed to reduce stack space usage and avoid such workarounds.
Changed PATH_MAX-sized buffers in `topo.c` use heap allocation, reducing stack usage.

UCS/TOPO: change topo.c stack allocation to heap

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Added missing compilation checks for `HAVE_IBV_DM` reported by #10129
To avoid compilation issues when dm is not supported / ucx is configured with `--without-dm` flag

UCT/IB/MLX5/DV: added missing conditional compilation checks for dm

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h

Check whether implicit ODP with PCI relaxed order flag is supported by driver
Internal issue [4042329](https://redmine.mellanox.com/issues/4042329)

UCT/IB: Check implicit ODP with relaxed ordering

---

config/ucx.conf
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/ucp/test_ucp_mmap.cc

Allow memory registration for cuda-managed memory when ODP is enabled on machines with coherent memory.
Needed to enable rdma, avoiding long-term page pinning.
Advertise support, and make sure non-blocking registration is always requested for cuda-managed, since it currently fails otherwise.
```
mpirun -mca coll ^hcoll -mca pml ucx -np 2 osu_bw -d managed MD MD
./bin/ucx_perftest -m cuda-managed -t <tag_bw|ucp_put_bw|ucp_get>
```
- Confirmed actual RDMA operation against cuda-managed memory with ODPv1
- enable rdma assertion on gtest
- tested on GH200 / A100 without coherent.
- tested with `UCX_IB_ODP_PREFETCH=y`

UCT/IB: Support cuda-managed memory when ODP is available

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
src/ucs/memory/rcache.c
src/ucs/memory/rcache.h
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/sm/mm/xpmem/mm_xpmem.c
test/gtest/ucs/test_rcache.cc

backport #9859, cherry-picked, minor function prototype conflict

UCP/RCACHE: Preserve uct_flags from memory regions we merge with - v1.17.x

---

src/ucs/config/types.h
src/uct/ib/base/ib_iface.h
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/rc/rc_mlx5_common.c
src/uct/ib/mlx5/rc/rc_mlx5_common.h
src/uct/ib/mlx5/rc/rc_mlx5_devx.c
src/uct/ib/mlx5/rc/rc_mlx5_iface.c

Add adaptive routing support for `rc_x` and `dc` transports on RoCE by the use of `multi_path` and `multi_path_force` parameters.
Need to implement `UCX_IB_AR_ENABLE=auto/no/yes` for RoCE.
Use PRM to add:
- HCA Cap/Cap2 multi_path force/rc/rcx/dc handling
- force option allows overriding nvconfig/sm..
- skip setting multipath parameters upon QP creation
- on RoCE: dc: set both for DCT context and DC QP INIT2RTR transition as specified in PRM
- on RoCE: rc_x: set multipath parameters on QP INIT2RTR transition as specified in PRM
On RoCE cluster tested UCX_IB_AR_ENABLE=auto/no/yes for rc_x and dc. Could not confirm actual throughput improvement.

UCT/IB/MLX5: Add multi_path config to enable Adaptive Routing

---

src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_ep.c
src/ucp/wireup/wireup_ep.h
test/gtest/Makefile.am
test/gtest/ucp/test_ucp_ep_reconfig.cc
test/gtest/ucp/ucp_test.h

Support partial EP reconfiguration: only non-reused, fully wired-up scenarios. (Lanes must not be reused and must all be p2p).
PR 2 for EP reconfiguration.
Add a new function for replacing wireup lane by moving internal AUX EP to the new lane.
The following steps are performed:
1) Set uct_ep to be used for new lane:
a) for CM flow -> use CM EP.
b) otherwise -> create a new wireup_ep.
2) Move aux ep from old config to new wireup lane.
3) Delete old wireup lane.
4) Select lane to be used as new wireup lane:
a) for CM flow -> use CM lane.
b) otherwise -> select a random lane. (Will be modified in next PRs to look for a non-reused lane).

UCP/WIREUP: Support EP reconfiguration for non-reused p2p scenarios

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_mm.inl
src/ucp/dt/dt.c
src/uct/cuda/gdr_copy/gdr_copy_md.c

Bypass UCP rcache when using gdr_copy for mem_type operations.
gdr_copy has its own rcache and double rcache restores internal issue [3606732](https://redmine.mellanox.com/issues/3606732). The root cause of this issue is the insufficient support for overlapping regions in the gdr_copy driver. With single caching, the memory handle's reference count tracks the number of in-flight operations, ensuring no overlapping memory regions for mem_type operations. However, with double caching, the reference count in the secondary cache corresponds to the number of primary memory regions, which does not provide the same guarantee.
Introduce a static user memh flow for mem_type operations and mark gdr_copy as non-cacheable of UCP.

UCP/MM: Selectively exclude mem type MDs from rcache

---

src/uct/base/uct_component.c
src/uct/ib/base/ib_md.c

fix GGA component loading
too late GGA component registration (found with `ucx_perftest`)
move IB load from query_md_resources to `so` ctor

UCT/GGA: fix component loading

---

test/gtest/uct/test_md.cc

Fix occasional failures in test_md.alloc
```
2024-09-17T05:24:31.6460426Z [ RUN      ] ib/test_md.alloc/1 <mlx5_1>
2024-09-17T05:24:32.2106135Z /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/uct/test_md.cc:460: Failure
2024-09-17T05:24:32.2108474Z Expected: ((double)num_alloc_failures / iterations) < (0.3), actual: 0.35 vs 0.3
2024-09-17T05:24:32.2110905Z Too many OUT_OF_RESOURCE failures
2024-09-17T05:24:32.2146490Z [  FAILED  ] ib/test_md.alloc/1, where GetParam() = mlx5_1 (570 ms)
```

TEST/MD: Add short sleep before retrying memory allocation

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/rc/rc_mlx5_common.c
src/uct/ib/mlx5/rc/rc_mlx5_iface.c

Initialize adaptive routing configuration when creating GGA interface. Relates to #10013.
Avoid random QP modify failures on CI.

UCT/GGA: Initialize RoCE multipath configuration when creating interface

---

config/ucx.conf
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.h

Add option to set gdrcopy BW and LAT and set them to platform specific value on GH systems.
To optimize performance estimations on different platforms

UCT/GDRCOPY: Extend ENV variables interface to set platform specific perf estimations

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h

Sets dcis array initial capacity to max by default
Currently there are some use-after-free issues when the array resize occurs, as some functions are holding a pointer to a dcis before and after the reallocation of the array.

UCT/IB/MLX5/DC: New env for dcis array initial capacity (defaults to max)

---

src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/rc/rc_mlx5_common.c

Enable ddp support for mlx5dv flow, in order to use it need to disable devx: `UCX_IB_MLX5_DEVX=no`
DDP is a new feature in CX8

UCT/IB/MLX5: enable ddp support when available

---

test/gtest/Makefile.am

Removed extra whitespace.
Fixed `test/gtest/Makefile.am:154: warning: whitespace following trailing backslash`.

TEST/GTEST: Removed extra whitespace.

---

src/ucp/rndv/rndv_am.c

Removed bcopy/zcopy configuration values from consideration when calculating the threshold of rndv/am/bcopy and rndv/am/zcopy protocols.
Considering bcopy/zcopy configuration values can lead to confusing behavior. E.g. setting the limits can force the use of rndv/am/bcopy and rndv/am/zcopy protocols over other protocols. This also doesn't work properly when a user sets rndv_scheme to am.

UCP/RDNV: Fixed rndv/am protocols threshold calculation.

---

test/apps/test_fuzzy_match.py

- Print output of `ucx_info` when /test_fuzzy_match.py fails
- remove trailing spaces
**Before**
```
+ ../test/apps/test_fuzzy_match.py --ucx_info ./src/tools/info/ucx_info
ERROR:root:"unused vars" message was not found
```
**After**
```
./test/apps/test_fuzzy_match.py --ucx_info ./src/tools/info/ucx_info
First 5 lines of output:
[1726845961.155049] [swx-rdmz-ucx-gpu-01:2444236:0]    cuda_copy_md.c:314  UCX  ERROR               attempt to allocate cuda memory without active context
[1726845961.155076] [swx-rdmz-ucx-gpu-01:2444236:0]         uct_mem.c:155  UCX  ERROR               failed to allocate 1 bytes using md cuda_cpy for get_alloc_md_id: No such device
[1726845961.155885] [swx-rdmz-ucx-gpu-01:2444236:0]          parser.c:2306 UCX  WARN  unused …
```

AZP: Fix test_fuzzy reporting

---

contrib/test_jenkins.sh

Added a check to ensure AddressSanitizer is loaded before running tests in `run_asan_check()` in `test_jenkins.sh`. 
To prevent tests from running without AddressSanitizer enabled in `run_asan_check()`, ensuring memory issues are caught during CI.
Added a check for `libasan.so` in the `run_asan_check()` function. If AddressSanitizer is not loaded, the script logs an error and exits.

CI: add AddressSanitizer load check in test_jenkins

---

src/tools/info/proto_info.c

Fix memory leak in print_ucp_ep_info()
Backtrace:
Error executing /__w/1/s/install/bin/ucx_info -u a r t s -e:
=================================================================
==45079==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 600 byte(s) in 1 object(s) allocated from:
#0 0x7f408f721ba8 in __interceptor_malloc (/usr/lib64/libasan.so.5+0xefba8)
#1 0x7f408e6e52a7 in ucs_malloc /__w/1/s/contrib/../src/ucs/debug/memtrack.c:320
#2 0x7f408f053e70 in ucp_address_pack /__w/1/s/contrib/../src/ucp/wireup/address.c:1562
#3 0x7f408ee35e8a in ucp_worker_address_pack /__w/1/s/contrib/../src/ucp/core/ucp_worker.c:2972
#4 0x7f408ee360ef in ucp_worker_query /__w/1/s/contrib/../src/ucp/core/ucp_worker.c:2990
#5 0x405988 in print_ucp_ep_info …

TOOLS/INFO: fix memory leak in print_ucp_ep_info()

---

src/ucp/core/ucp_ep.c

Reverted short protocol disable with log level trace
Prevent perf degradation

UCP/PROTO: Reverted short protocol disable with log level trace

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/uct/ib/test_ib_md.cc
test/gtest/uct/test_md.cc
test/gtest/uct/test_md.h

Support ODPv1 for verbs and mlx5dv MDs.
To provide workaround in case of issues with DEVX ODP support.

UCT/MD/IB: Add ODP support for verbs and mlx5dv

---

src/ucp/core/ucp_rkey.c

Use `assertv` in `ucp_rkey_packed_size`

UCP: Use assertv in rkey size calc

---

test/gtest/Makefile.am

Remove `./autogen.sh` warning.
```
$ ./autogen.sh
...
test/gtest/Makefile.am:154: warning: whitespace following trailing backslash
...
```

GTEST: Remove warning during ./autogen.sh

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_ppln.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rtr.c
test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_peer_failure.cc

Using UCX in this combination: 1.18+proto_v2+CUDA async+error handling, causes memory transfer via host instead of bounce buffers, making transfers prohibitively slow. Unlike with proto_v1, pipeline protocol (rndv_ppln over rnvd_(put/rtr)_mtype) is not being selected, because it doesn't support error handling.
As a result, memory copy is done through host staging buffers which drastically affect performance. The proper solution would be to enable error handling for aforementioned protocols with rkey invalidation.
This PR is the first step towards the real solution: here we just advertise support for error handling without providing invalidation flow. Subsequent PR will provide the invalidation functionality.
Related PRs: https://github.com/openucx/ucx/pull/8666, …

UCP/RNDV/PPLN: Advertise error handling capability for put_mtype/ppln protocols

---

buildlib/tools/builds.sh

Reverts https://github.com/openucx/ucx/pull/10096
The build fails but it does not cause the test to exit

BUILD: Revert "BUILD: enable single test run in builds.sh"

---

src/uct/rocm/ipc/rocm_ipc_iface.c

Fixed  logic consistent in `uct_rocm_ipc_iface_is_reachable_v2`
Fixes bug in https://github.com/openucx/ucx/issues/10181

UCT/ROCM: fixed uct_rocm_ipc_iface_is_reachable_v2 bug

---

src/uct/ib/mlx5/ib_mlx5.c

Reduce log level of both `WC` and `NC_DEDICATED` unsupported in `uct_ib_mlx5_devx_check_uar()`.
Following https://github.com/openucx/ucx/issues/10180.
Reduce the log level of "both WC and NC_DEDICATED UAR allocation types are not supported" from ERROR to DIAG, and let UCX disable DevX automatically in this case.

UCT/IB/MLX5: reduce log level of both WC and NC unsupported

---

src/tools/perf/lib/libperf.c

Use `mkey_pack_v2` in `ucx_perftest`
Some transports (e.g. `cuda_ipc`) require passing address to `mkey_pack`. Fixes bug that fails these transports mkey packaging.

TOOLS/PERF: Use mkey_pack_v2

---

src/uct/ib/mlx5/rc/rc_mlx5_devx.c

1. There's no need to get one dim array address as array member start address.
2. unify rmac & rgid start address with the access method in function uct_ib_mlx5_set_dgram_seg_grh
```correct one dim array address grammar semantic usage```.
There's no function error in the original code implementation.
```align the rmac & rgid start address with the access method in``` [uct_ib_mlx5_set_dgram_seg_grh](https://github.com/openucx/ucx/blob/v1.17.0/src/uct/ib/mlx5/ib_mlx5.inl#L340)

UCT/IB/MLX5: correct array address grammar semantic

---

src/uct/api/uct.h

Update description of `UCT_MD_MEM_FLAG_HIDE_ERRORS`
- Statemenet about merged memory regions is no longer valid
- Allow users using this flag for allocations

UCT/API: Change HIDE_ERRORS flag description

---

src/tools/perf/lib/ucp_tests.cc

Make receive operations with `UCP_OP_ATTR_FLAG_MULTI_SEND` flag for BW benchmarks.
Without this flag UCX traits receive operations as blocking which is not right for BW benchmarks and therefore can select suboptimal protocol.

TOOLS/PERF: Set MULTI flag for recv operations in BW benchmarks

---

buildlib/az-helpers.sh
buildlib/pr/wire_compat.yml

Retry 'git clone' command in case of a failure.
Sometimes we get a git clone error:
```
git clone --depth 1 -b v1.16.x https://github.com/openucx/ucx.git /__w/2/s/ucx_v1.16.x_88170_gpu
Cloning into '/__w/2/s/ucx_v1.16.x_88170_gpu'...
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly 
```
Switching to the built-in Azure function will prevent such failures using the retry logic.

AZP: Retry git clone

---

buildlib/az-helpers.sh
buildlib/azure-pipelines-release-drp.yml

Add scheduled testing for the DRP release environment.
https://jirasw.nvidia.com/browse/HPCINFRA-2291 (internal link)
Scheduled builds to create artifacts but not publish them.
Emergency release procedure:
1. Disable the main release pipeline.
2. Proceed as usual.
The DRP release pipeline will check the status of the main release pipeline.
Only if main is disabled will it run the full release cycle including the artifact's publishing.

AZP/RELEASE: Scheduled DRP testing

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

This PR reduces stack memory usage in `uct_ib_mlx5_devx_md_open()`.
Customers with limited stack sizes have recently experienced stack overflow issues when running UCX. Moving these allocations to the heap prevents such overflows.
`uct_ib_mlx5_devx_md_open()` exceeds the threshold.
It converts stack allocation at `uct_ib_mlx5_devx_md_open()` to heap.

UCT/IB/MLX5/DV: convert stack allocation at uct_ib_mlx5_devx_md_open() to heap

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5.inl
src/uct/ib/mlx5/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

Introducing a new dci allocation policy - dcs_hybrid which will behave the same as dcs_quota except using a dedicated HW dci when available instead of waiting for a dci from the pool to be available
Utilizing hw resources instead of waiting for another dci, improves latency for certain message sizes
In case `dci_alloc_or_create` returned 0 - use the dedicated HW dci with a new dci channel.

UCT/IB/MLX5/DC: introducing dcs_hybrid policy

---

test/gtest/common/googletest/gtest-param-test.h
test/gtest/common/test.h

This PR refactors test suite registration macros to reduce stack frame size and defer complex initialization logic.
Customers with limited stack sizes have recently experienced stack overflow issues when running UCX. 
The goal is to ensure that the entire UCX runs within a defined stack size threshold. By reducing the stack frame size in test macros, this change helps in testing the runtime stack usage, ensuring that it starts within the threshold.
The registration logic has been moved to separate functions and marked as noinline, deferring execution and reducing the complexity of static initialization.

GTEST: reduce stack frame size in gtest macros

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Fix reachability check for cuda-ipc (bug introduced with mnnvl support)
Running some banchmark on two CG1 nodes reports UCP configs as `intra-node`
**Before:**
```
[1727532130.625696] [lego-cg1-qs-139:2450144:0]   +--------------------------------+-------------------------------------------------------------------------------------------------------+
[1727532130.625700] [lego-cg1-qs-139:2450144:0]   | ucp_context_0 intra-node cfg#3 | tagged message by ucp_tag_send*(multi) from host memory                                               |
[1727532130.625701] [lego-cg1-qs-139:2450144:0]   +--------------------------------+-------------------------------------------+-----------------------------------------------------------+
[1727532130.625703] [lego-cg1-qs-139:2450144:0]   | …
```

UCT/CUDA-IPC: Fix reachability check

---

src/ucp/rndv/rndv_put.c

Fixes the following bug in CI
```
[ RUN      ] dcx/test_ucp_am_nbx_rndv_memtype.rndv/32 <dc_x,cuda_copy,rocm_copy/cuda-managed/cuda-managed>
common/mem_buffer.cc:321: Failure
Pattern check failed at 0x7fab92100200 offset 524288 (length 1 mask: 0xff): Expected: 0xb4 Actual: 0x0
Trace/breakpoint trap (core dumped)
```
The issue occurs when using the rndv put pipeline protocol, and data is split into two fragments: the first being 512KB and the second only 1 byte. For the second fragment, UCP sends the 1 byte starting from lane 1, transmitting all of it on that lane. However, ATP is sent starting from lane 0. Each ATP, except the last one, confirms just 1 byte to prevent premature receive completion on the peer side.
The problem arises because the data size is only 1 byte. The first ATP (on …

UCP: Send ATP on a correct lane to fix CI failures

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
test/gtest/uct/cuda/test_cuda_ipc_md.cc

Follow up to https://github.com/openucx/ucx/pull/9982. This PR caches the operation that imports remotely exported handle for a custom CUDA memory pool as the mapping operation via `cuMemPoolImportFromShareableHandle` is expensive.

UCT/CUDA_IPC: Cache for mempool import operation

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Enabling MNNVL by default causes pipeline protocols to be used for inter-node transfers on systems without MNNVL capabilities. This PR disables MNNVL capability by default and users are expected to manually enable using `UCX_CUDA_IPC_ENABLE_MNNVL=try` or `UCX_CUDA_IPC_ENABLE_MNNVL=yes` on MNNVL systems

UCT/CUDA_IPC: disable mnnvl by default

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_rkey.h
src/ucp/dt/dt.c
src/ucp/dt/dt.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_init.c
src/ucp/rma/amo_offload.c
src/ucp/rma/amo_sw.c
src/ucp/rma/get_am.c
src/ucp/rma/get_offload.c
src/ucp/rma/put_am.c
src/ucp/rma/put_offload.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.h
src/ucp/rndv/rndv_am.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_put.c
src/ucp/rndv/rndv_rkey_ptr.c
src/ucp/rndv/rndv_rtr.c
src/ucp/stream/stream_multi.c
src/ucp/tag/eager_multi.c
src/ucp/tag/eager_single.c
src/ucp/tag/offload/eager.c
src/ucp/tag/offload/rndv.c

Need to take into account device distances for rndv ppln protocols (taking mtype and sys_dev for the corresponding fragment type)
PPLN protocols should not be selected over get/put based when GPU direct RDMA is enabled
**Before**
```
[1727631616.028245] [rock24:3137233:0]   +--------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
[1727631616.028250] [rock24:3137233:0]   | ucp_context_0 inter-node cfg#3 | rendezvous data fetch(multi) into cuda/GPU0 from cuda/dev[0]                                                                      |
[1727631616.028253] [rock24:3137233:0]   +--------------------------------+-----------------------------------------------------------------+--------- …
```

UCP: Fix perf estimation for rndv ppln protos

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c

[VMM ](https://developer.nvidia.com/blog/introducing-low-level-gpu-virtual-memory-management/) and [stream-ordered allocations](https://developer.nvidia.com/blog/using-cuda-stream-ordered-memory-allocator-part-2/) allocations can opt for fabric handle generation for IPC capabilities. Currently, UCX supports only allocations with fabric handles associated with it and fails in `uct_md_mem_reg` if allocations lack fabric handles. But with https://github.com/openucx/ucx/pull/10104 merged, UCX can pipeline VMM and stream-ordered allocations using staged pipelines that use library internal fabric pinned device memory buffers. This PR introduces a new key type (NON_IPC) that allows `uct_md_mem_reg` to pass when non-fabric user buffers are passed to it and forces cuda_ipc transport to fail during …

UCT/CUDA_IPC: Handle lack of IPC capability in unpack

---

.codespellrc

Don't write to inapropriate files when running `codespell --write-changes`.

CI: Fix spellcheck on generated files

---

src/ucs/async/async.c
src/ucs/sys/compiler.h

Use heap-based instead of stack-based allocation, while avoiding crashes.
The `ucs_alloca()` asserts for allocations above 1kB and we generally want to avoid using heap for such allocations anyways.
Use `malloc()` with bigger max size.

UCS/ASYNC: Use heap to process expired timers in batch

---

src/ucp/proto/proto_init.c
src/ucp/rndv/rndv_am.c

Add ACK overhead for ZCOPY protocols not only if FAST_CMPL flag is set.
Now this PR also includes fix for `rndv/am/bcopy` abortion since original change revealed this bug inside `tcp/test_ucp_sockaddr.force_close_during_rndv/0` test since `rndv/am/bcopy` started to be chosen instead of `rndv/am/zcopy`.
This overhead exists even if FAST_CMPL flag is not set
*Still need to test perf*

UCP/PROTO: Add ACK ovh without fast completion flag for zcopy

---

src/ucs/config/parser.c
test/gtest/ucs/test_config.cc

add pattern match to ucs_config
https://github.com/openucx/ucx/pull/9993#discussion_r1697056724

UCS/CONFIG: mask variables ignoring table prefix on set value

---

src/uct/cuda/gdr_copy/gdr_copy_iface.c

Report GDR copy BW and LAT for `iface_query` as mean between GET and PUT operations.
That PR is a fix for performance regression on rock setup that was introduced here https://github.com/openucx/ucx/pull/10112
Before introducing env variables for setting GDR copy perf `iface_query` reported put BW but get LAT (since get LAT is the worse case). After  https://github.com/openucx/ucx/pull/10112 it started to report get BW and LAT (because get BW is worst case too), but that lead to significant performance degradation on rock because cuda_copy started to be chosen as memcopy EP instead of gdr_copy.
Since reporting GET LAT and PUT BW for `iface_query` seems weird FMPOV I decided that solution may be reporting mean of GET and PUT operations performance  for `iface_query`. Initial experiment …

UCT/GDRCOPY: Set LAT/BW for iface_query as best between put and get operations

---

config/ucx.conf

Increase gdrcopy cpu overhead to 200ns on GH. Additional 170ns is rcache lookup.
Current estimation doesn't include rcache lookup for gdrcopy which leads to performance degradations.
To fix degradations, #10216 and #10213 are also required

UCT/GDRCOPY: Add rcache overhead for GH systems

---

test/gtest/common/main.cc

Fixes the issue where gtest fails to catch exceptions during test initialization, which causes a core dump.
When an exception is thrown during the test creation phase, gtest does not handle it properly, resulting in a crash. This change ensures exceptions are caught, preventing the core dump.
Added try-catch blocks around gtest initialization to catch and handle exceptions, logging the errors without crashing the application.
```
#0  0x00007ffff5105a4f in raise () from /lib64/libc.so.6
#1  0x00007ffff50d8db5 in abort () from /lib64/libc.so.6
#2  0x00007ffff5cde09b in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] () from /lib64/libstdc++.so.6
#3  0x00007ffff5ce453c in __cxxabiv1::__terminate(void (*)()) () from /lib64/libstdc++.so.6
#4  0x00007ffff5ce4597 in std::terminate() () …
```

GTEST/COMMON/MAIN: fix core dump issue on exception in gtest initialization

---

src/ucp/proto/proto_init.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_get.c
src/ucp/rndv/rndv_rtr.c

Remove extra-cpu overhead for zcopy operations
In terms of current performance estimation logic zcopy and bcopy are same operations in terms of transport that just performed on differrent buffers, so there shouldn't be difference at least for async (multi) case.
To fix degradations, https://github.com/openucx/ucx/pull/10217 and https://github.com/openucx/ucx/pull/10213 are also required

UCP/PROTO: Remove extra remote-cpu overhead for zcopy

---

config/ucx.conf

Add rcache lookup overhead to gdrcopy perf estimation. Now it is just part of CPU overhead, but later should be moved to separate perf node.
To fix broad degradation for osu_latency inter-node d2d d2h on rock cluster.

UCT/GDRCOPY: Add rcache overhead for AMD Milan systems

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto_select.c
src/ucp/proto/proto_select.h
src/ucp/proto/proto_select.inl
src/ucp/rndv/rndv_ppln.c

Added environment variables (`UCX_FORCE_FAST_CMPL` and `UCX_FORCE_MULTI_SEND`) to enforce the `UCP_OP_ATTR_FLAG_FAST_CMPL` and `UCP_OP_ATTR_FLAG_MULTI_SEND` flags globally for all UCX operations.
To simplify configuration and improve performance by enabling these optimizations globally without needing to modify each operation individually.
Added `FORCE_FAST_CMPL` and `FORCE_MULTI_SEND` to `ucp_context_config_t` and updated the environment parsing logic to apply these flags automatically during protocol initialization.

UCP/CONTEXT/CONFIG: create env vars to force MULTI_SEND and FAST_CMPL

---

configure.ac
ucx.spec.in

Bump version to 1.19.0 after branching v1.18.x

CONFIG/SPEC: Bump version to 1.19.0

---

src/ucp/core/ucp_rkey.c

When running ucp_perftest_daemon with ASAN and trace logs, 2 buffer overflows are detected, both related to HEX dump of mkey/rkey. The regression was introduced in PR: https://github.com/openucx/ucx/pull/6745
The original hex dump was correct: https://github.com/openucx/ucx/pull/4153/files#diff-81ab501a3a76470dfbfe72e890118aa3083efe0434532272d12f2d5614047ec7R92
Then the impl was refactored to use common serialization API. And the issue is that `ucs_serialize_next_raw` already advances the pointer, so we dump the garbage value behind the key bytes

UCP/ASAN: Fixed ASAN detected buffer overflow

---

test/gtest/ucp/test_ucp_perf.cc

Disabled performance checking for UD transports in `test_ucp_perf.envelope`.
To avoid such failures:
```
[ RUN      ] udx/test_ucp_perf.envelope/37 <ud_x/am_bw_b>
[     INFO ]                    am_bw_b : 1.025 MB/sec
[     INFO ]                    am_bw_b : 2.523 MB/sec (attempt 1)
[     INFO ]                    am_bw_b : 2.535 MB/sec (attempt 2)
[     INFO ]                    am_bw_b : 1.774 MB/sec (attempt 3)
[     INFO ]                    am_bw_b : 1.777 MB/sec (attempt 4)
[     INFO ]                    am_bw_b : 1.573 MB/sec (attempt 5)
[     INFO ]                    am_bw_b : 1.409 MB/sec (attempt 6)
/__w/1/s/contrib/../test/gtest/common/test_helpers.cc:55: Failure
Failed
Connection timed out - abort testing
```
, or
```
[ RUN      ] ud/test_ucp_perf.envelope/37 <ud_v/am_bw_b> …
```

GTEST/UCP: Disabled performance checking for UD transports.

---

src/uct/base/uct_mem.c

Detail logging.
`uct_mem.c:298  UCX  DEBUG   could not allocate user memory: host memory length=4096 flags=0x0 num_methods=1`

UCT/MEM: Improve logs on allocation failure

---

src/uct/ib/mlx5/gga/gga_mlx5.c

When packing mkey GGA always sets `UCT_MD_MKEY_PACK_FLAG_EXPORT` which forces to create a mkey for export of size `exported_mkey_packed_size` (even if not explicitly requested by caller). This is unexpected by the caller, who allocates an array of `rkey_packed_size` to handle the rkey.
Currently it works by chance, because `rkey_packed_size > exported_mkey_packed_size`.
But it becomes an issue when we increase the `uct_ib_md_packed_mkey_t` (like we do for XGVMI purposes).
The fix is to set `rkey_packed_size = exported_mkey_packed_size` for GGA transport to match the pack behavior

GGA: Always use exported_mkey_packed_size for mkey pack

---

src/ucp/rndv/proto_rndv.inl

Many unit tests in `force_close_during_rndv` in master are failing with assertion:
```
[ RUN      ] dc_no_ud_ud_x/test_ucp_sockaddr.force_close_during_rndv/1 <dc_mlx5,mm/tag,mt>
369 ucp_proto_rndv_recv_complete_status(ucp_request_t *req, ucs_status_t status)
370 {
371     /* Remote key should already be released */
==>   372     ucs_assert(req->send.rndv.rkey == NULL);
```
The bug was introduced in https://github.com/openucx/ucx/pull/10038

UCP: Fix for assertion on rkey destroy

---

config/m4/compiler.m4

Fix PGI compiler errors found during `build_pgi` step like:
```
2024-10-10T08:54:25.0639396Z "/__w/1/s/contrib/../test/gtest/ucs/test_algorithm.cc", line 51: error #1626: routine is both "inline" and "noinline"
2024-10-10T08:54:25.0640811Z   UCS_TEST_F(test_algorithm, crc16) {
```

BUILD/CONFIG: Fix PGI compiler error: routine both inline and noinline

---

src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/ib_mlx5.inl
src/uct/ib/mlx5/ud/ud_mlx5.c
src/uct/ib/ud/base/ud_iface.h
src/uct/ib/ud/verbs/ud_verbs.c

Some RoCE device drivers fail to set the service level in the work completion for UD completions. This leads to silently dropping all (or almost all) UD packets on these networks. This commit updates the GRH check logic to use the GRH to detect IPv4  vs IPv6.
Update the GID length calculation to use the GRH instead of the service level in the work completion.
We have a system using Intel iRDMA which is not setting the service level for any UD work completion. This makes UCT silently drop all UD packets. This PR changes the code for non-mlx hardware to detect the address family (IPv4 vs IPv6) based on the data in the GRH. For IPv6 the first byte will contain 0x6X where X is any value whereas this byte will be untouched in IPv4. To ensure that a mix of IPv6 and IPv4 packets does not confuse …

 UCT/IB/UD: Use interface address family when checking RoCE GRH

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h

Fix for the segfault described in [RM#4105410](https://redmine.mellanox.com/issues/4105410)
The root cause is that export unpack logic stores all **combinations** of remote_md-local_md in 
`tl_mkeys[UCP_MAX_MDS]` array, which is not sufficient to store all of them. WIth large number of IB devices (like on nemo01) this overrides memory on stack and leads to stack corruption, therefore we don't see the backtrace.
This is initial behaviour introduced in https://github.com/openucx/ucx/pull/8584
- Changed `ucp_unpacked_exported_tl_mkey_t` structure to store MD map instead of an individual index, to avoid storing combinations.
- Changed impl of key export to deal with `local_md_map`
- Added assertion to avoid stack overflow in the future

UCP: Fixed stack overflow in exported rkey unpack

---

src/ucs/datastruct/mpmc.c
src/ucs/datastruct/mpmc.h
src/ucs/datastruct/queue.h
src/ucs/debug/debug.c

Don't check for pointer validity when accessing without lock.
We cannot assume stable memory content outside of lock.
Add and use specific function for unlocked accesses as it's racing with either free or alloc path.
```
[ RUN      ] test_mpmc.multi_threaded <> <>
[swx-rdmz-ucx-gpu-01:31308:4:35972]       debug.c:1339 Fatal: (queue)->ptail at: 0x6020002503b0 is poisoned
```
```
queue.h:73   Assertion `!__asan_region_is_poisoned((void*)((queue)->ptail), sizeof(*(queue)->ptail))' failed: (queue)->ptail: address=0x602000055ed0 size=8
```

UCS/MPMC: Don't assume pointer validity without lock

---

buildlib/tools/builds.sh
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/ib_mlx5_log.c

fix build `--with-mlx5-dv=no --with-devx=no`
to fix non-default build configuration

UCT/GGA: fix compilation --with-mlx5-dv=no --with-devx=no

---

contrib/test_jenkins.sh

Fixed typo in env var for cuda_hooks gtest.

CONTRIB: Fixed typo in env var for cuda_hooks gtest.

---

src/ucm/cuda/cudamem.c
src/ucm/rocm/rocmmem.c
src/ucm/util/sys.c
src/ucm/ze/zemem.c
src/ucs/memory/memtype_cache.c
test/gtest/ucs/test_memtype_cache.cc

Segfault in MT applications using CUDA memory allocated before UCX is initialised.
Segfault happens because UCX treats passed memory buffer as HOST memory instead of CUDA
Because `memtype_cache` does not contain all maps allocated before UCX init
Because `ucs_memtype_cache_get_global` creates multiple instances of `memtype_cache`, but concurrent init is buggy
```
ucp_datatype_iter_detect_mem_info
ucp_memory_detect
ucp_memory_detect_internal
ucs_memtype_cache_lookup
ucs_memtype_cache_get_global
**create ucs_memtype_cache_t per each concurrent thread**
ucm_set_event_handler
get_existing_alloc
ucm_cudamem_get_existing_alloc
ucm_parse_proc_self_maps  << parallel reads, but read is **destructive**
```
- Fixed destructive read in ucm_parse_proc_self_maps
- Added unit test that reproduces the …

UCM: Fixed race condition in parsing proc maps

---

src/tools/perf/lib/ucp_tests.cc
test/gtest/common/googletest/gtest.h
test/gtest/ucs/test_bitops.cc
test/gtest/uct/ib/test_ud.cc

This PR reduces stack memory usage by converting stack allocations to heap in various UCX tests.
Customers with limited stack sizes have recently experienced stack overflow issues when running UCX.
The goal is to ensure that the entire UCX runs within a defined stack size threshold. By reducing the stack frame size in tests, this change helps in testing the runtime stack usage, ensuring that it starts within the threshold.
This PR reduces stack usage by creating separate helper functions for excessive inline functions calls.

STACK: reduce stack usage in tests

---

src/ucm/cuda/cudamem.c
src/ucm/rocm/rocmmem.c
src/ucm/util/sys.c
src/ucm/ze/zemem.c
src/ucs/memory/memtype_cache.c
test/gtest/ucs/test_memtype_cache.cc

Segfault in MT applications using CUDA memory allocated before UCX is initialised.
Segfault happens because UCX treats passed memory buffer as HOST memory instead of CUDA
Because `memtype_cache` does not contain all maps allocated before UCX init
Because `ucs_memtype_cache_get_global` creates multiple instances of `memtype_cache`, but concurrent init is buggy
```
ucp_datatype_iter_detect_mem_info
ucp_memory_detect
ucp_memory_detect_internal
ucs_memtype_cache_lookup
ucs_memtype_cache_get_global
**create ucs_memtype_cache_t per each concurrent thread**
ucm_set_event_handler
get_existing_alloc
ucm_cudamem_get_existing_alloc
ucm_parse_proc_self_maps  << parallel reads, but read is **destructive**
```
- Fixed destructive read in ucm_parse_proc_self_maps
- Added unit test that reproduces the …

UCM: Fixed race condition in parsing proc maps - 1.18

---

config/ucx.conf

Detect  async allocated memory as cuda on Grace platform
Fixes internal issue [RM4125745](https://redmine.mellanox.com/issues/4125745)
(fixed in v1.18.x by #10254)

UCT/CUDA: Detect async mem as cuda on Grace

---

src/uct/ib/base/ib_md.c
test/gtest/uct/ib/test_ib_md.cc

Fix error handling path on multi-threaded registration.
Currently we see segfault in the thread because we try to teardown the first failing registration.
More generally, a thread can fail to start or fail to properly register all its tasked `mrs`.
- Make sure we cannot dereg twice.
- Make sure we only teardown `mrs` entries corresponding to started threads.
- Make sure started threads return with their `mrs` all initialized.

UCT/IB: Fix teardown path on memory handler callback

---

src/tools/perf/perftest_daemon.c
test/gtest/ucp/test_ucp_sockaddr.cc

handle error status in send/recv callbacks of ucx_perftest_daemon
to avoid segfault on cleanup

PERF: handle error status in send/recv callbacks

---

src/ucm/util/replace.h
src/ucs/config/ucm_opts.c

- Minor fixes in hooks env var descriptions
- Removing unsed UCM_OVERRIDE_FUNC
**Before**
```
[mikhailb@rock06 ucx-tmp]$ ucx_info -f | grep -B 12 UCX_MEM_CUDA_HOOK_MODE
#
#
#
UCX_MEM_CUDA_HOOK_MODE=bistro
```
**After**
```
[mikhailb@rock06 ucx-tmp]$ ./src/tools/info/ucx_info -f | grep -B 12 UCX_MEM_CUDA_HOOK_MODE
#
#
```

UCM: Minor mem hooks fixes

---

buildlib/pr/cuda/test_malloc_hook.sh
test/apps/test_cuda_hook.c

Testing of CUDA memory hooks with and without forcing of far jumps in binary instrumentation mode.
`test_cuda_hook` is executed with and without forcing far jump when applying bistro patches. Thus, the allocation of a large VA space segment was removed from the test code.
(+ replaced deprecated `cuCtxDetach` by `cuCtxDestroy`)

BUILDLIB/PR/CUDA: Test memory hooks w/o forcing far jump in bistro mode.

---

src/uct/ib/mlx5/dc/dc_mlx5.c

Added a docstring to dcs_hybrid policy
`ucx_info -cf` should present all available dc policies with short explanations on the difference between them,
dcs_hybrid was added recently but the documentation for `ucx_info` is missing.

UCT/IB/MLX5/DC: add a docstring to dcs_hybrid policy (for ucx_info -cf)

---

src/tools/perf/lib/libperf.c
src/ucs/datastruct/string_set.h

List available devices / transports when UCT perftest cannot find the one required by the user
User experience and ease of use of UCT perftests.

TOOLS/PERF/LIB: add hints for devices and transports in UCT perftests

---

Makefile.am
buildlib/tools/common.sh
contrib/test_jenkins.sh
contrib/ucx_perftest_config/test_types_ucp_daemon
src/tools/perf/Makefile.am
src/tools/perf/api/libperf.h
src/tools/perf/lib/libperf.c
src/tools/perf/lib/ucp_tests.cc
src/tools/perf/perftest.h
src/tools/perf/perftest_daemon.c
src/tools/perf/perftest_params.c
src/ucp/core/ucp_mm.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/uct/api/v2/uct_v2.h
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/uct/ib/test_devx.cc

First CI test for perftest_daemon.
XGVMI functionality must be covered by CI tests to prevent regressions.
Some refactoring was needed to allow daemon to support perftest batch mode:
- Moved command line arguments from `TEST_PARAMS_ARGS` (i.e. per-test options) to global options. Reason: these daemon offloading options are immutable during the process lifetime, and should not be changed on per-test basis. It's pretty much like existing options for receiver IP and port.
- Moved daemon-related config params into a separate struct
- Added `daemon-keep-alive` option, to keep daemon alive across multiple test runs
- Support "reconnection" for daemon clients. That means that TCP connection between host and daemon is not reestablished, but it's possible to reconnect to daemon from another EP …

TOOLS/PERF: CI test for perftest daemon

---

ucx.spec.in

backport #10268, re-tested on v1.18.x.

CONFIG/SPEC: Enable IB mlx5 build by default - v1.18.x

---

ucx.spec.in

Enable ib mlx5 UCX submodule by default. When using `rpmbuild.sh`, issue is not visible as it explicitly passes the `--with-mlx5`.
With script below, uct mlx5 rpm is not built, with patch mlx5 is built:
```
sed -i '/with.*mlx5/d' contrib/buildrpm.sh
./autogen.sh
./configure
./contrib/buildrpm.sh -t
./contrib/buildrpm.sh --binrpm
```

CONFIG/SPEC: Enable IB mlx5 build by default

---

src/tools/vfs/vfs_main.c
src/ucp/proto/proto_debug.c
src/ucs/config/parser.c
src/ucs/debug/log.c
src/ucs/debug/memtrack.c
src/ucs/memory/numa.c
src/ucs/sys/module.c
src/ucs/sys/sock.c
src/ucs/sys/string.c
src/ucs/sys/string.h
src/ucs/sys/topo/base/topo.c
src/ucs/vfs/base/vfs_obj.c
src/ucs/vfs/fuse/vfs_fuse.c
src/ucs/vfs/sock/vfs_sock.c
src/uct/ib/base/ib_device.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/tcp/tcp_iface.c
test/gtest/common/test_helpers.cc
test/gtest/ucp/test_ucp_worker.cc
test/gtest/ucs/test_string.cc

This PR changes all stack allocations of char arrays sized `PATH_MAX` to heap allocations.
Customers with limited stack sizes have recently experienced stack overflow issues when running UCX. Moving these allocations to the heap prevents such overflows.
Heap allocations replace stack allocations for char arrays of size `PATH_MAX`.

STACK: Change PATH_MAX stack allocation to heap

---

buildlib/dockers/fedora.Dockerfile
buildlib/pr/codestyle.yml
buildlib/pr/main.yml
buildlib/tools/test_ctags.sh
contrib/ctags.sh
contrib/ctags_ucx.awk

Generate tag including profiled functions.
Need to be able to follow those functions.
```shell
$ ./contrib/ctags.sh
$ grep 'cuda_ocpy_ep_get.*PROFILE_FUNC' tags
uct_cuda_copy_ep_get_short      ./src/uct/cuda/cuda_copy/cuda_copy_ep.c /^UCS_PROFILE_FUNC(ucs_status_t, uct_cuda_copy_ep_get_short,$/;"        f       typeref:typename:ucs_status_t   file:
uct_gdr_copy_ep_get_short       ./src/uct/cuda/gdr_copy/gdr_copy_ep.c   /^UCS_PROFILE_FUNC(ucs_status_t, uct_gdr_copy_ep_get_short,$/;" f       typeref:typename:ucs_status_t   file:
```

CONTRIB/CTAGS: Add ctags script trying to also generate profile functions

---

buildlib/az-helpers.sh

Trigger warning if CUDA device is unavailable on non-GPU nodes.
Trigger error if CUDA device is unavailable on GPU nodes.
If CUDA device was not found, UCX is configured with no CUDA:
https://github.com/openucx/ucx/blob/master/buildlib/jucx/jucx-test.yml#L39
It's expected in some cases, as we currently do not have ARM machines with GPU.

AZP: Improve reporting of CUDA device status during tests

---

src/uct/ib/rc/verbs/rc_verbs_impl.h

Fix the macro that is supposed fill desc withing uct rc.
This change fixes a typo in the implementation of `UCT_RC_VERBS_FILL_DESC_WR`.
The assignment to `sge->addr` incorrectly uses `desc` instead of `_desc`. While this won't cause a compilation error if the actual variable passed to the macro is named `desc`, the macro should consistently use `_desc` throughout its implementation.
Since this is just a typo, the only change required was adding an underscore (`_`)!

UCT/VERBS/RC: Fix the macro that is supposed fill desc within uct rc.

---

test/gtest/uct/ib/test_ib.cc

Configure available SLs in gtest.
Right now, the `test_uct_ib_sl` case in gtest assumes that all SLs map to a valid, available VL, but that’s not always the case. Some systems don’t support all VLs. This change lets us set which SLs are available, so gtest can check only the relevant ones.
Introduce an environment variable as a bitmask to specify the SLs to be checked.

UCT/IB/TEST: Configure available SLs in gtest

---

src/ucs/sys/sys.c

Fix what seems to be false positive.
```
sys/sys.c: In function 'ucs_sys_max_open_files':
sys/sys.c:341:12: error: 'value' may be used uninitialized in this function [-Werror=maybe-uninitialized]
341 |     return (int)value;
|            ^~~~~~~~~~
sys/sys.c: In function 'ucs_sys_get_effective_memlock_rlimit':
sys/sys.c:1611:19: error: 'value' may be used uninitialized in this function [-Werror=maybe-uninitialized]
1611 |     *rlimit_value = (value == RLIM_INFINITY) ? SIZE_MAX : value;
|     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

UCS/SYS: Workaround uninitialized value for rlimit

---

src/uct/ib/mlx5/rc/rc_mlx5_common.c

UCT/IB/MLX5: Cleanup QP modify flag

---

test/gtest/uct/test_sockaddr.cc

Fixed race condition in uct_sock test
Fix the following error:
```
2024-11-05T12:40:53.0873763Z Value of: m_ep_client_data.empty()
2024-11-05T12:40:53.0875383Z   Actual: false
2024-11-05T12:40:53.0876712Z Expected: true
```

UCT/TEST: Fixed race condition in uct_sock test

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Fixed return value of `uct_cuda_ipc_is_peer_accessible`.
Restored old behavior, which was changed by https://github.com/openucx/ucx/pull/9978.
Returning value other than `UCS_ERR_UNREACHABLE` causes an issue during unpacking remote key.
The issue can be reproduced by `iodemo` example application.
Client side:
```
ucp_mm.c:369  UCX  WARN  failed to dereg from md[4]=cuda_ipc: Unsupported operation
```
Server side:
```
ucp_rkey.c:899  UCX  ERROR   failed to unpack remote key from remote md[4]: Input/output error
```

UCT/CUDA/CUDA_IPC: Fix return value of is_peer_accessible.

---

src/uct/ib/mlx5/dc/dc_mlx5.h

Convert dcis array to use new index typedef
Follow code convension

UCT/DC: Convert dcis array to use new index typedef

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h

Increase DCI index to 16 bits -> backported from master
Support large number of DCIs

UCT/DC: Increase DCI index to 16 bits - v1.18

---

buildlib/pr/cuda/test_malloc_hook.sh
config/m4/cuda.m4
configure.ac
src/ucm/cuda/cudamem.c
src/ucm/cuda/cudamem.h
test/apps/Makefile.am
test/apps/test_cuda_get_symbol_address.cu

Added hook for `cudaGetSymbolSize` to support device-side variables.

UCM/CUDA: Added support for device-side variables.

---

src/ucm/cuda/cudamem.c
src/ucm/cuda/cudamem.h
test/gtest/ucm/cuda_hooks.cc

Replaced `CUDA_VERSION` by `CUDART_VERSION` in case of using CUDA Runtime API.

UCM/CUDA: Use CUDART_VERSION macro for CUDA Runtime API.

---

src/tools/perf/lib/ucp_tests.cc
src/tools/perf/lib/uct_tests.cc

In perftest there were several places where `unsigned` 32b is used to represent buffer size, which is of type `size_t` in the rest of the code
Integer overflow occurs on large message sizes > 4GB, and as a consequence perftest produces completely random results
Use `size_t` instead of `unsigned` for buffer size

PERF: Fix integer overflow: use size_t instead of unsigned for buffer size

---

buildlib/pr/codestyle.yml
buildlib/tools/codestyle.sh
buildlib/tools/git_ready.sh

Shell script to perform simple preliminary checks before pushing.
Avoid spending CI cycles with repeated pushing.
Implement commit title, code format and spell checks locally. Ran `shellcheck` on it.
```
$ ./contrib/gitready.sh
$ ./contrib/gitready.sh --push origin/my_branch
```

CONTRIB: Add checking script before push

---

src/tools/perf/lib/ucp_tests.cc
src/tools/perf/lib/uct_tests.cc

This is a double commit of https://github.com/openucx/ucx/pull/10295 into v1.18.x branch
In perftest there were several places where `unsigned` 32b is used to represent buffer size, which is of type `size_t` in the rest of the code
Integer overflow occurs on large message sizes > 4GB, and as a consequence perftest produces completely random results
Use `size_t` instead of `unsigned` for buffer size

PERF: Fix integer overflow: use size_t instead of unsigned for buffer size v1.18.x

---

test/gtest/common/mem_buffer.cc
test/gtest/common/mem_buffer.h
test/gtest/ucp/test_ucp_am.cc

Extended UCP AM RNDV tests by adding buffers allocated by `cudaMallocAsync`.

GTEST/COMMON: Added test for cuda async allocated buffers.

---

bindings/go/src/examples/perftest/perftest.go

Implement a cumulative statistics printout that reports performance metrics every second using a single EP for communication.
Align performance measurement and reporting style with `ucx_perftest`, which provides similar cumulative, per-second statistics.

BINDINGS/GO/PERF: Periodic statistics

---

config/m4/compiler.m4

Improves stack memory usage by introducing an 8KB threshold for stack frames using the GCC flag `-Wframe-larger-than=8192`. The fixes for functions that exceed this limit were merged:
Customers with limited stack sizes have recently experienced stack overflow issues when running UCX.
The goal is to ensure that the entire UCX runs within a defined stack size threshold.
Mitigates the risk of stack overflow, particularly in environments with limited stack sizes.

BUILD/CONFIGURE: enforce 8KB stack threshold on compilation

---

config/ucx.conf
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Add ability to set platform specific cuda_ipc latency and overhead
To improve protocols performance prediction accuracy

UCT/CUDA_IPC: Patch latency and overhead

---

NEWS

Add empty v1.18.0.rc1 section for now.

RELEASE: Mark NEWS for 1.18.0-rc1 as TBD for now

---

bindings/go/src/examples/perftest/perftest.go
bindings/go/src/ucx/ucs_constants.c
bindings/go/src/ucx/ucs_constants.go
bindings/go/src/ucx/ucs_constants.h

Implement `flag.Value` interface for `ucx.UcsMemoryType` and use `flag.Var` function to set `-m` argument.
For enums, `flag.Value`/`flag.Var` is the better choice because it promotes good software design principles like type safety, reusability, and clean separation of concerns.

BINDINGS/GO/PERF: Implement flag.Value for UcsMemoryType

---

src/uct/sm/self/self.c

Don't check for device flag + don't call `uct_iface_scope_is_reachable`
Device address is not relevant for `self` transport.

UCT/SELF: Remove device address from is_reachable

---

test/gtest/ucp/test_ucp_atomic.cc

Change for the UCP atomic tests allows to simply reproduce issue of interoperability of ODPv1, KSM and atomic operations.
Originally this issue was reported on GG systems ([RM4025026](https://redmine.mellanox.com/issues/4025026)) but I was able to reproduce it on x64 CPU with IB device. 
To extend test coverage.

UCP/ATOMIC: Test ODP/KSM interoperability

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
test/gtest/ucp/test_ucp_mmap.cc

This is an auxiliary PR to introduce new invalidation design in UCX. The aim is to avoid using rcache for RNDV fragment memory pool
RNDV fragment memory pool is created on demand and remains allocated during the application lifetime. Rcache is desirable for this use case, because:
1) does not bring any benefits
2) can be harmful in case of merging with other parent regions
3) redundant memory usage for parent memh
Introduce new UCP memh flag NO_RCACHE

UCP/RNDV/RCACHE: Don't use rcache for RNDV frag mpool

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.inl
src/uct/ib/mlx5/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

This PR fixes tx / ep scheduling for DC dcs_hybrid policy, rescheduling when the hw dci is being used by the ep.
Recently added `dcs_hybrid` policy failed during pending queue test in gtest.

UCT/IB/MLX5/DC: hybrid dcs fixes - pending queue

---

src/ucp/proto/proto.c

Added name and description for stream operation.
Before
```
+--------------------------------+-------------------------------------------------+
| client_server intra-node cfg#3 | (null) from host memory                         |
+--------------------------------+--------------------------------------+----------+
|                        0..8184 | multi-frag stream copy-in copy-out   | tcp/eth0 |
|                      8185..inf | multi-frag stream zero-copy copy-out | tcp/eth0 |
+--------------------------------+--------------------------------------+----------+
$ ls proto_info_dir/
client_server_intra_node_cfg_1__null_from_host_memory_0_0.dot     client_server_intra_node_cfg_1__null_from_host_memory_65529_inf.dot
client_server_intra_node_cfg_1__null_from_host_memory_1_8184.dot …
```

UCP/PROTO: Added name and description for stream operation.

---

config/ucx.conf
src/ucs/arch/cpu.c
src/ucs/arch/cpu.h
src/ucs/arch/x86_64/cpu.c

Acked-by: Edgar Gabriel <edgar.gabriel@amd.com>
Adding support for AMD's Turin processors.
Ref: https://www.amd.com/en/products/processors/server/epyc/9005-series.html

ARCH/X86: Add Turin support

---

AUTHORS
buildlib/pr/codestyle.yml
contrib/authors_update.sh

Automate AUTHORS updates according to documentation.
Seems better to try to have common approach.
```shell
$ ./contrib/authors_update.sh upstream/v1.17.x..upstream/v1.18.x
..
Artemy Kovalyov <artemyko@nvidia.com>
++ Arun Chandran <Arun.Chandran@amd.com>
Edgar Gabriel <Edgar.Gabriel@amd.com>
Evgeny Leksikov <evgenylek@mellanox.com>
..
```

CONTRIB: Automate AUTHORS file update

---

src/ucp/rndv/proto_rndv.c
src/ucp/rndv/proto_rndv.inl
test/gtest/ucp/test_ucp_am.cc
test/gtest/ucp/test_ucp_sockaddr.cc
test/gtest/ucp/ucp_test.cc
test/gtest/ucp/ucp_test.h

Change `RNDV_SCHEME` and `RNDV_THRESH` logic to work properly.
Currently if user set certain `RNDV_SCHEME` without setting `RNDV_THRESH` this scheme would be forced on all sizes since `cfg_thresh` for this protocol would be `0`. This change fixes that.
With this change remote variant can report only 2 values as `cfg_thresh`: `AUTO` and `INF`. `AUTO` reported for:
- all protocols if `RNDV_SCHEME=auto`
- protocol that is set in `RNDV_SCHEME`
`INF` is reported for all protocols that are not set in `RNDV_SCHEME` if `RNDV_SCHEME` is set to some certain protocol.
| RNDV_THRESH| RNDV_SCHEME| RESULT|
|--------|--------|--------|
| AUTO| AUTO| All protocols are selected basing on perf comparison|
| AUTO| GET_ZCOPY| No hard thresh, but only GET_ZCOPY protocol participates in proto selection |
| …

UCP/PROTO: Fix RNDV_SCHEME logic

---

test/gtest/ucp/test_ucp_perf.cc

Disabled checking the values in test_ucp_perf.envelope. It doesn't make much sense to check the performance during the CI. Since multiple instances may run on the same host, and there may be slowdowns.
Reverted https://github.com/openucx/ucx/commit/4ec14557474d025e80fd7c9979ba5ae4b191b11a.

GTEST/UCP: Disabled checking the values in test_ucp_perf.envelope.

---

test/apps/test_fuzzy_match.py
test/apps/test_ucx_tls.py

Convert Python2 testing scripts to Python3.
We missed the Python2 EOL date a bit (Jan 1, 2020).

CI: Convert Python2 testing scripts to Python3

---

config/ucx.conf
src/ucs/arch/cpu.c
src/ucs/arch/cpu.h
src/ucs/arch/x86_64/cpu.c

Acked-by: Edgar Gabriel <edgar.gabriel@amd.com>
Adding support for AMD's Turin processors.
Ref: https://www.amd.com/en/products/processors/server/epyc/9005-series.html

ARCH/X86: Add Turin support - v1.18.x

---

examples/hello_world_util.h
examples/ucp_client_server.c
examples/ucp_hello_world.c
examples/uct_hello_world.c

Fixed `ucp_hello_world -h` output removing `Failed to parse_cmd` line in the end of it.

EXAMPLES: Fixed ucp_hello_world help output.

---

contrib/lsan.supp
src/ucp/core/ucp_context.c
src/ucp/rndv/rndv.c
src/uct/ib/mlx5/gga/gga_mlx5.c
test/gtest/ucp/test_ucp_request.cc
test/gtest/ucp/ucp_test.h

1. add `gga_mlx5` to `ib` transport alias
2. add `gga` alias for `gga_mlx5`
3. add testing of `shm,gga`
4. fix align_mtu in `gga_mlx5` transport
5. fix test_proto_reset  test for `shm,gga` case
start point is `UCX_TLS=^ib` use case
~~in dependency from https://github.com/openucx/ucx/pull/10236, early merging may cause failures of MT tests~~

UCP: add gga_mlx5 to UCP transport aliases

---

test/apps/test_fuzzy_match.py
test/apps/test_ucx_tls.py

Convert Python2 testing scripts to Python3.
(Porting https://github.com/openucx/ucx/pull/10290 to v1.18.x)

CI: Convert Python2 testing scripts to Python3 (v1.18.x)

---

AUTHORS
src/tools/vfs/vfs_main.c
src/ucs/vfs/sock/vfs_sock.c

Ignore EEXIST errno in `vfs_mount()` and `ucs_vfs_sock_mkdir()`.
Bug introduced in https://github.com/openucx/ucx/pull/10127 where instead of ignoring the EEXIST that returns from mkdir, `vfs_mount()` and `ucs_vfs_sock_mkdir()` return an error in case the directory already exists, which should be ignored.

VFS: Ignore EEXIST errno

---

buildlib/jucx/jucx-build.yml

Porting https://github.com/openucx/ucx/pull/10343 to the release branch.

AZP/RELEASE: Fix variable substitution syntax for JUCX publishing (v1.18.x)

---

test/apps/test_ucx_tls.py

Fix failures like:
```
...
Using UCX_TLS=tcp, found TL: self
Using UCX_TLS=posix, found TL: posix
Using UCX_TLS=posix, found TL: self
Using UCX_TLS=ib, found TL: rc_mlx5
Using UCX_TLS=ib, found TL: self
Using UCX_TLS=\rc_mlx5, found TL: None
```
Python3 changed the order in available_tls list, exposing an issue that RC transport could be instantiated without UD for wireup.

TEST/APPS: Fix test_ucx_tls.py failure

---

src/uct/rocm/copy/rocm_copy_ep.c

recognize UCT_INVALID_RKEY in rocm/copy TL and perform the local host memory locking on the fly instead of relying on the rkey information. 
Fix an issue was discovered testing of UCX 1.18.0RC1. and will have to be backported to the v1.18.x branch as well.

UCT/ROCM: recognize invalid uct rkeys

---

src/uct/rocm/copy/rocm_copy_ep.c

recognize UCT_INVALID_RKEY and perform the local host memory locking on the fly instead of relying on the rkey information. 
This issue was discovered testing of UCX 1.18.0RC1, and will have to be backported to the v1.18.x branch as well.
cherry picked from commit 59ad2e544ea852c7ba2c97e7625ae06cdd591208

UCT/ROCM: recognize invalid uct rkeys - v1.18.x

---

src/ucs/sys/compiler_def.h
src/uct/ib/base/ib_iface.h
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5_devx.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/dv/ib_mlx5_ifc.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/ib/mlx5/rc/rc_mlx5_common.c
src/uct/ib/mlx5/rc/rc_mlx5_common.h
src/uct/ib/mlx5/rc/rc_mlx5_devx.c
src/uct/ib/mlx5/rc/rc_mlx5_iface.c
test/gtest/uct/ib/test_ib.cc

Signed-off-by: Roie Danino <rdanino@nvidia.com>
(cherry picked from commit 90cea8c023669104f7e81ace7a2e6f576f0a58b8)
Backport #10167
Porting Devx DDP Support to v1.18.x
Performance optimization for Connect-X8 devices which enables full wirespeed.

v1.18.x - UCT/IB/MLX5: Add DDP support for DevX

---

config/m4/cuda.m4
src/ucp/wireup/wireup.c
src/uct/api/uct.h
src/uct/api/v2/uct_v2.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h

UCT/CUDA-IPC: Fix MNNVL reachability check

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Need this ensure greater concurrency for a larger count of peers reachable by cuda_ipc.

UCT/CUDA_IPC: Increase MAX_PEERS and MAX_STREAMS

---

src/ucp/wireup/wireup.c
test/gtest/ucp/test_ucp_ep_reconfig.cc

Support reused lanes for EP reconfiguration.
Reused lanes means lanes we don't have to reconnect, but just use them as they are.
This usecase requires special handling in the code in order to allow reconfiguration of such scenarios.
Part of EP reconfiguration feature.

UCP/WIREUP: Support reused lanes for EP reconfiguration

---

src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Always sets cuda-ipc device as SHM (even if MNNVL is supported), otherwise it is disabled when someone specified UCX_NET_DEVICES and does not mention cuda there.

UCT/CUDA-IPC: Always set cuda-ipc device as SHM

---

src/uct/cuda/cuda_ipc/cuda_ipc_md.c
test/gtest/uct/cuda/test_cuda_ipc_md.cc

Return unreachable if the CUDA device context is not already set.
Restores behavior of #9747 after #9978.

UCT/CUDA_IPC: Return rkey unreachable with missing device context - v1.18.x

---

config/m4/cuda.m4
src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Switched from `nvmlDeviceGetGpuFabricInfoV` to `nvmlDeviceGetGpuFabricInfo` to be able to be compiled and run with any minor version of CUDA 12.
`nvmlDeviceGetGpuFabricInfoV` was introduced in CUDA 12.4. It means that UCX built with CUDA 12.4 will fail during symbol lookup, if CUDA 12.3 is installed on the system.
Also removed `fabric_info.cliqueId` from debug output to avoid adding extra compile time macros. Because the name of the field was changed in 12.3 version.

UCT/CUDA/CUDA_IPC: Switched to nvmlGpuFabricInfo v1 - v1.18.x

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_multi.c
src/ucp/rndv/proto_rndv.c

This is fix for [RM#4177809](https://redmine.mellanox.com/issues/4177809).
The root cause of the issue is sorting lanes by BW introduced in https://github.com/openucx/ucx/pull/10264
That PR solves one issue, but introduces another one
- It solves issue when we always choose first AM lane for RNDV, even if it's slower
- It introduces the issue that we may choose several paths of the same device, even though it's not optimal (must prefer another device instead)
This is a quick fix, the ideal solution would be to do lane sorting in proto_multi after performance calculation, taking into account multiple paths and performance boost of extra paths
- Revert lane sorting by BW (https://github.com/openucx/ucx/pull/10264)
- Rely on rma_bw_lanes array for finding RMA_BW lanes for RNDV
- Tested with …

UCP/PROTO/RNDV: Use rma_bw_lanes for lanes sorting

---

src/ucp/rndv/rndv_put.c
test/gtest/ucp/test_ucp_am.cc

Added check for fragment memory type to rndv/put/mtype protocol.
Fix for the following type of error:
```
ib_md.c:287  UCX  ERROR ibv_reg_mr(address=0x4002a0000000, length=536870912, access=0xf) failed: Bad address
ucp_mm.c:76   UCX  ERROR failed to register address 0x4002a0000000 (cuda-managed) length 536870912 on md[6]=mlx5_2: Input/output error (md supports: host|cuda-managed)
mpool.c:269  UCX  ERROR Failed to allocate memory pool (name=ucp_rndv_frags) chunk: Input/output error
```

UCP/RNDV: Added check for fragment type to rndv/put/mtype.

---

test/gtest/uct/ib/test_ib_md.cc

Fix reverted `has_ksm()` usage, actually working because it is used before `m_mlx5_flags` is initialized.

GTEST/UCT/IB: Fix skip condition for multi-thread memory registration

---

config/m4/cuda.m4
src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Switched from `nvmlDeviceGetGpuFabricInfoV` to `nvmlDeviceGetGpuFabricInfo` to be able to be compiled and run with any minor version of CUDA 12.
`nvmlDeviceGetGpuFabricInfoV` was introduced in CUDA 12.4. It means that UCX built with CUDA 12.4 will fail during symbol lookup, if CUDA 12.3 is installed on the system.
Also removed `fabric_info.cliqueId` from debug output to avoid adding extra compile time macros. Because the name of the field was changed in 12.3 version.

UCT/CUDA/CUDA_IPC: Switched to nvmlGpuFabricInfo v1.

---

NEWS

Update news file to prepare v1.18.0-rc1 release.
Used small helper scripts to classify:
- https://gist.github.com/tvegas1/8ea2da41b5a8fd49f266583f6535d194

RELEASE: Updated NEWS for v1.18.0-rc1

---

src/ucp/core/ucp_rkey.c

When unpacking and building `ucp_rkey_h`, ensure the `md_map` field reflects the state of `tl_rkey` array.
This ensures that `ucp_rkey_destroy` can consistently clean up a `ucp_rkey_h` object, even if its creation was interrupted by an `uct_rkey_unpack` failure.

UCP/RKEY: Keep md_map consistent with tl_rkey

---

test/gtest/uct/uct_test.cc

Add ability to limit gtest runs by MD and RSC name.
Shorten test time on systems with 30+ interfaces.
Do it from gtest test instantiation, as `UCX_NET_DEVICES` is inoperent.
```
GTEST_UCT_MD_NAME=mlx5_0 GTEST_UCT_RSC_NAME=mlx5_0:1  ./test/gtest/gtest --gtest_filter=ib/test_md.reg*
```

GTEST/UCT: Add ability to filter by resource or md name

---

src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h

Filter out unsupported resources from GGA component
```
```
full log: https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/92757/logs/1012
check capabilities

UCT/GGA: filter out unsupported resources from component list

---

test/gtest/uct/test_sockaddr.cc

Fixed race in sockaddr
CI somtime fails on assert because of this race

UCT/TEST: Fixed race in sockaddr

---

test/gtest/uct/uct_test.cc

Following https://github.com/openucx/ucx/pull/10393, this PR fixes the retry mechanism in `uct_test::entity::mem_alloc` to ensure that errors during memory allocation retries are handled locally and do not propagate to the global error state.
The retry mechanism allowed tests to handle temporary allocation failures but lacked a scoped_log_handler. This caused intermediate errors during retries to be logged as global errors, leading to test failures. This PR resolves that issue.
Added `scoped_log_handler slh(wrap_errors_logger);` inside the retry loop to prevent intermediate allocation failures from being logged as global errors, ensuring tests with successful retries pass.

TEST/GTEST/UCT: Fix retry when it cannot allocate MEMIC memory - add scoped_log_handler

---

NEWS
src/uct/ib/mlx5/rc/rc_mlx5_iface.c

(cherry picked from commit eaa47eb31c50c2bded93cdb51a42cb7db4ab63dd)
Porting https://github.com/openucx/ucx/pull/10410 to 1.18.x

UCT/IB/MLX5/RC: skip cyclic_emulated when using ddp - v1.18.x

---

test/apps/Makefile.am

Fixed the following scenario:
```
$ ./autogen.sh
$ ./contrib/configure-release --with-java=no
$ ./contrib/buildrpm.sh -s -t -b
...
nvcc fatal   : Could not open output file .deps/test_cuda_get_symbol_address.Tpo
```

TEST/APPS: Fixed building rpm.

---

buildlib/jucx/jucx-build.yml

Fix variable substitution syntax according to the documentation:
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?WT.mc_id=devops-9483-zdeptawa&view=azure-devops&tabs=yaml%2Cbatch#reference-secret-variables-in-variable-groups
JUCX publishing failed otherwise.

AZP/RELEASE: Fix variable substitution syntax for JUCX publishing

---

test/gtest/uct/test_sockaddr.cc

Fixed race in test_sockaddr
Backport https://github.com/openucx/ucx/pull/10409

UCT/TEST: Fixed race in test_sockaddr - v1.18

---

test/gtest/common/test_helpers.h
test/gtest/ucp/test_ucp_proto_mock.cc

This PR contains enhancements of the original protocol selection mock (https://github.com/openucx/ucx/pull/9989):
- Ability to mock any number of devices with different capabilities
- Match the exact config of protocol selection (e.g. `rc_mlx5/mock_0:1 50% on path0 and 50% on path1`)
- Small improvements
Finally all those changes are needed to reproduce real protocol selection issues (like https://redmine.mellanox.com/issues/4177809, https://redmine.mellanox.com/issues/4134043)

GTEST: Refactored protocol selection mock

---

buildlib/pr/main.yml

Align and expand the OS support matrix in CI builds to match supported Doca-ofed OSes (V2.9.0).
RHEL7.2
RHEL7.4
RHEL7.6 (keep RHEL7.6_mofed)
Fedora34
sles15sp2
sles15sp5
debian12.5
euleros2.0sp12
kylin10sp3
sles15sp6

AZP: Align build OS list with the support matrix

---

config/m4/cuda.m4
src/uct/cuda/cuda_copy/cuda_copy_md.c

Do not use `cuCtxSetFlags()` if CUDA driver does not support it.
Unresolved symbol for `cuCtxSetFlags` on CUDA driver < 12.1 causes crash.
Assumptions:
- `cuCtxSetFlags` is only needed for VMM, which has UCX support starting from CUDA driver >= 12.3
- `cuCtxSetFlags` is not strictly needed for malloc async
Locally tested, needs final testing on platform with actual older drivers.
```
UCX_IB_GPU_DIRECT_RDMA=no ./rfs/bin/ucx_perftest -t tag_bw -m cuda 
```

UCT/CUDA: Runtime CUDA >= 12.3 to enable VMM

---

src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/rc/rc_mlx5.h
src/uct/ib/mlx5/rc/rc_mlx5_ep.c
test/gtest/uct/test_uct_ep.cc

Allow GGA to work properly during EP reconfiguration

UCT/GGA: Support is_connected API

---

src/ucs/memory/rcache.h

Removed unused field from structure `ucs_rcache_config`.
The usage of the field removed by this pull request: https://github.com/openucx/ucx/pull/9441.

UCS/MEMORY: Removed unused field from ucs_rcache_config.

---

src/ucs/datastruct/array.h
src/uct/ib/base/ib_device.h
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5.inl
src/uct/ib/mlx5/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

- Access DCIs by index instead of by pointer
- in poll_tx: relocate dcis array so asan would catch if memory violation is done
- Set default dcis array capacity to 1.
Suggesting a future proof fix for the issues caused by dynamic resizing of dcis array (use after free caused by using an old pointer after resize).

UCT/IB/MLX5/DC: Change DCIs array to pointers - dynamic array grow

---

config/m4/cuda.m4

Fix error from configure:
```
...
checking for cuMemRetainAllocationHandle in -lcuda... yes
/ucx/contrib/../configure: line 26521: ,: command not found
checking whether CU_MEM_LOCATION_TYPE_HOST is declared... yes
```

BUILD/CUDA: Remove extra comma from autoconf script

---

config/m4/cuda.m4

BUILD/CUDA: Remove extra comma from autoconf script - v1.18.x

---

src/uct/ib/base/ib_iface.c

Fix printing of UD CREQ/CREP in the log

UCT/IB: Fix uct_ib_address_str(), used for UD CREQ/CREP log.

---

src/ucp/proto/proto_perf.c
src/ucp/proto/proto_perf.h
src/ucp/rndv/proto_rndv.c
test/gtest/ucp/test_ucp_proto_mock.cc

Applies `UCX_RNDV_PERF_DIFF` setting effect for protov2. 
Cherry-picked from https://github.com/openucx/ucx/pull/10292.
This control effect was removed during introducing perf-factors logic. This PR brings it back.
That how it looks like with that patch:

UCP/PROTO: Consider RNDV_PERF_DIFF

---

buildlib/tools/builds.sh
src/ucs/stats/serialization.c

Mark variable as unused to prevent build failure.
Use ucs_assert MACRO instead of assert.
When building UCX with `DNDEBUG` flag assert macro is evaluated to `((void)0)` and it cause compilation to fail due to `unused variable` exception.

UCS/STATS: Mark variable as unused to prevent build failure

---

AUTHORS
buildlib/tools/build_static.sh
buildlib/tools/test_wire_compat.sh
contrib/test_jenkins.sh
src/ucs/Makefile.am
src/ucs/sys/netlink.c
src/ucs/sys/netlink.h
src/ucs/sys/sock.c
src/ucs/sys/sock.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/tcp/tcp_ep.c
src/uct/tcp/tcp_sockcm_ep.c
test/gtest/common/test_helpers.cc
test/gtest/ucs/test_sock.cc
test/gtest/uct/ib/test_ib.cc
test/gtest/uct/tcp/test_tcp.cc

Add a new reachability check mode for IP-based lanes.
Currently, the reachability of IP-based lanes is only verified by checking if the local and remote addresses share the same subnet. If they do, the remote address is considered reachable.
However, we want to introduce an additional reachability check (and mode) that considers non-local addresses. This will allow us to determine if the remote address is reachable based on routing information, not just subnet matching.
When the reachability mode is set to "route," the routing table will be consulted to verify reachability based on the specified interface and destination address.

UCT: check reachability using the routing table

---

test/gtest/ucs/arch/test_x86_64.cc

Fix for https://github.com/openucx/ucx/issues/10449

ARCH/X86: check the return value of posix_memalign()

---

src/ucp/proto/proto_perf.c

Fix memory corruption, as we cannot pass `va_list` to function with variable number of arguments.
Triggered by #10401 from inside:
```
if (fabs(params->perf_bias) > UCP_PROTO_PERF_EPSILON) {
```
```
==255151== Use of uninitialised value of size 8
==255151==    at 0x72D71E7: __printf_fp_l (in /usr/lib64/libc-2.28.so)
==255151==    by 0x72D367E: vfprintf (in /usr/lib64/libc-2.28.so)
==255151==    by 0x72FC2F3: vsnprintf (in /usr/lib64/libc-2.28.so)
==255151==    by 0x4EC9DB1: ucs_vsnprintf_safe (string.c:222)
==255151==    by 0x4EC9DB1: ucs_vsnprintf_safe (string.c:216)
==255151==    by 0x570B155: ucp_proto_perf_node_new (proto_debug.c:489)
==255151==    by 0x570B34D: ucp_proto_perf_node_new_data (proto_debug.c:537)
==255151==    by 0x570ED15: ucp_proto_perf_apply_func (proto_perf.c:468) …
```

UCP/PROTO: Do not pass va_list to variable parameters function

---

configure.ac
src/ucs/datastruct/dynamic_bitmap.h
test/gtest/ucp/test_ucp_perf.cc
ucx.spec.in

- Bump version since v1.18.0 was released
- Fix spell checks to make CI pass

Fix spellcheck and bump version to v1.18.1 - v1.18.x

---

src/ucp/proto/proto_debug.c
src/ucp/proto/proto_debug.h
test/gtest/ucp/test_ucp_proto_mock.cc

- Provide better info message when protocol selection is not as expected
- Extend testing to cma, self, tcp transports
A failure looks like this:
```
[ RUN      ] tcp/test_ucp_proto_mock_tcp.am_send_1_lane/0 <tcp>
/hpc/newhome/yosefe/workspace/hpc/ucx/contrib/../test/gtest/ucp/test_ucp_proto_mock.cc:357: Failure
Expected equality of these values:
expected_data
Which is: 65529..366864 desc: multi-frag zero-copy, config: tcp/mock
actual_data
Which is: 65529..366985 desc: multi-frag zero-copy, config: tcp/mock
unexpected difference at range[2]
/hpc/newhome/yosefe/workspace/hpc/ucx/contrib/../test/gtest/ucp/test_ucp_proto_mock.cc:357: Failure
Expected equality of these values:
expected_data
Which is: 366865..inf desc: rendezvous zero-copy fenced write to remote, config: tcp/mock
actual_data …
```

TEST/UCP/MOCK: Improve error message and test tcp, cma, self

---

test/gtest/ucs/arch/test_x86_64.cc

Fixing https://github.com/openucx/ucx/issues/10449 in v1.18.x

ARCH/X86: check the return value of posix_memalign() - v1.18.x

---

src/tools/perf/lib/ucp_tests.cc

Users complain on too optimistic performance reports provided by some ucx_perftest tests (e.g. ucp_put_bw), especially visible on huge messages and low iteration count. The root cause is the absence of synchronisation between client and server at the end of the test execution. This synchronisation was added (https://github.com/openucx/ucx/pull/10310) only for some tests: (UCX_PERF_CMD_TAG, UCX_PERF_CMD_TAG_SYNC, UCX_PERF_CMD_AM). It should be extended to others
There is a discrepancy between client and server final perf result, which is especially visible with pipeline protocols, but it occurs also with many others. On the client side we measure time needed to send all the messages, and with pipeline protocol we essentially measure the time needed to send message to the remote bounce …

UCP/PERF: Use final sync up for all UCP ucx_perftest tests

---

contrib/test_jenkins.sh
src/uct/ib/rdmacm/configure.m4

Do not advertize `rdmacm` in the build_module list when `--without-verbs` is specified.
gtest crashes because `enum_md_resources()` calls `dlopen(rdmacm)` which ends-up loading the unrelated system-wide library, which in turn loads the system-wide uct ib.
```
==== backtrace (tid:1050034) ====
0 0x0000000000012ce0 __funlockfile()  :0
1 0x000000000005b319 ucs_config_parser_parse_field()  src/ucs/config/parser.c:1333
2 0x000000000005b537 ucs_config_parser_set_default_values()  src/ucs/config/parser.c:1384
3 0x000000000005b50d ucs_config_parser_set_default_values()  src/ucs/config/parser.c:1378
4 0x000000000005c560 ucs_config_parser_fill_opts()  src/ucs/config/parser.c:1831
5 0x0000000000017c43 uct_config_read()  src/uct/base/uct_component.c:151
6 0x0000000000014559 uct_md_config_read() …
```

UCT/IB/RDMACM: Disable rdmacm support when verbs is disabled

---

buildlib/azure-pipelines-perf.yml

Add auto-cleanup of working directories for the UCX performance tests pipeline.
Large log files collected under the working directory have been found to contribute to disk space exhaustion.

AZP: Cleanup workspace for perf tests

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_worker.c
src/ucp/wireup/address.c
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup.h

Consider EP priority in iface score calculation.
Prioritize RC over DC for promoted EPs in selection process.
1) Add is_prioritized flag to score funcion callback.
2) Set est_num_eps to small number if EP is prioritized (in order to get better latency and thus select this EP).

UCP/WIREUP: Consider EP priority in iface score calculation

---

src/ucp/proto/proto_reconfig.c
test/gtest/ucp/test_ucp_sockaddr.cc

Handle copy of AM user header in `ucp_proto_reconfig_progress`.
When using sockaddr to establish connection requests go into pending queue but user header is not being copy even if `UCP_AM_SEND_FLAG_COPY_HEADER` is enabled. It breaks API and can cause data corruption.
fix #10424 
Copy user header to internal UCX buffer if needed like done for other protocols.

UCP/PROTO/RECONFIG: Fix copy header handling in reconfig.

---

config/ucx.conf
src/ucp/proto/proto_init.c
src/ucp/proto/proto_perf.c
src/ucp/proto/proto_perf.h
src/ucp/proto/proto_reconfig.c
src/ucp/rndv/proto_rndv.c
src/ucp/rndv/rndv_ppln.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.h
test/gtest/ucp/test_ucp_proto.cc

Added configuration variable to set gdr_copy registration cache lookup overhead.
Original pull request: https://github.com/openucx/ucx/pull/10311.

UCT/CUDA/GDR_COPY: rcache lookup overhead config variable.

---

buildlib/azure-pipelines-perf.yml

Update the PerfX code used by the perf pipeline.
The new PerfX release should print the full stderr to logs.

AZP/Perf: Update the PerfX code used by the perf pipeline

---

test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc
test/gtest/uct/uct_test.cc

Following https://github.com/openucx/ucx/pull/10393, add another fix to the sporadic failure of `uct_atomic_key_reg_rdma_mem_type` test.
It still fails once in a while:
Increase the number of retries from 5 to 10 and make add random sleep between retries.

TEST/GTEST/UCT: Increase retries and add random sleep when MEMIC allocation fails

---

buildlib/pr/efa.yml
buildlib/pr/main.yml
contrib/ibmock/Makefile
contrib/ibmock/README.md
contrib/ibmock/config.c
contrib/ibmock/config.h
contrib/ibmock/efa.c
contrib/ibmock/fake.h
contrib/ibmock/lib.h
contrib/ibmock/stubs.c
contrib/ibmock/verbs.c
contrib/ibmock/verbs.h
contrib/test_efa.sh
src/uct/ib/efa/srd/srd_iface.c
test/gtest/common/test_helpers.cc
test/gtest/ucp/test_ucp_perf.cc

Add IB mocking (EFA support) capability.
Need to run gtest without the need for EFA interface.
Implement loopback libibverbs/libefa. Keep build/code independent from UCX libraries.
```
vdi$ export LD_LIBRARY_PATH=$(pwd)/../efa_mock/build:$LD_LIBRARY_PATH
vdi$ UCX_TLS=srd ucx_perftest -t tag_bw -l
vdi$ UCX_TLS=ud ucx_perftest -t tag_bw -l
vdi$ ucx_info -d
```
```
vdi$ export LD_LIBRARY_PATH=$(pwd)/../hpc-poc/ibmock/build
vdi$  ./test/gtest/gtest --gtest_filter=*ud*
...
[==========] 2300 tests from 119 test suites ran. (642250 ms total)
[  PASSED  ] 2300 tests.
vdi$ valgrind --leak-check=full  ./test/gtest/gtest --gtest_filter=\
*ud*-*perf.enveloppe*
```

CONTRIB/IBMOCK: Inital add with EFA support

---

contrib/api_update.sh

Move steps from wiki to script to help avoid/fix mistakes. Wiki will need to be updated.
```shell
./contrib/api_update.sh upstream/v1.18.x
git show
git push upstream HEAD:gh-pages
```

CONTRIB: Automate update of API documentation

---

src/ucp/wireup/address.c
src/ucp/wireup/address.h
test/gtest/ucp/test_ucp_worker.cc

cleanup deprecated flags in UCP address
to inclrease number of supported MDs

UCP/ADDRESS: cleanup deprecated flags

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/rc/rc_mlx5_common.c
src/uct/ib/mlx5/rc/rc_mlx5_common.h
src/uct/ib/mlx5/rc/rc_mlx5_iface.c

Fix https://redmine.mellanox.com/issues/4246892
```
[ RUN      ] rcx/test_ucp_tag_match.send2_nb_recv_medium_wildcard/1 <rc_x/req_ext>
[1736352962.257227] [nemo03:678154:0]      ib_mlx5_dv.c:407  UCX  ERROR mlx5dv_devx_obj_modify(opcode=0x503) failed, syndrome 0x823f8d: Remote I/O error
```

UCT/MLX5: Initialize DP fields before creating command QP

---

buildlib/az-distro-release.yml
buildlib/azure-pipelines-release-drp.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose-aarch64.yml
buildlib/dockers/docker-compose-x86_64.yml
buildlib/dockers/ubuntu-release.Dockerfile
buildlib/pr/main.yml

Cherry-pick from https://github.com/openucx/ucx/pull/10480/.

AZP/RELEASE: Add Ubuntu 24.04 to UCX build and release pipelines - v1.18

---

test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc
test/gtest/uct/uct_test.cc
test/gtest/uct/uct_test.h

Backport #10393, #10413 and #10475 to v1.18.x

TEST/GTEST/UCT: Retry when MEMIC allocation fails - v1.18.x

---

src/tools/perf/perftest_run.c
src/ucs/datastruct/string_buffer.h
src/uct/ib/mlx5/rc/rc_mlx5_iface.c
test/gtest/ucs/test_string.cc

Without this fix, if the none of the SRQ topologies provided in the configuration is supported, there is a failure to create the uct_iface without an indicative error message.

UCT/MLX5/UCS: Print error message if SRQ topology is invalid

---

src/ucp/wireup/select.c

Remove unused `ucp_wireup_select_bw_info_t::md_map`
Code clean up

UCP/WIREUP: Remove unused ucp_wireup_select_bw_info_t::md_map

---

src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c

Added logging for `cuInit`.
Removed duplicate logging for `cuDeviceGetCount` in `uct_cuda_ipc_create_dev_cache`.

UCT/CUDA/BASE: Print error if cuInit fails.

---

src/uct/ib/mlx5/rc/rc_mlx5_common.c

Fix a failure to initialize RC/DC iface with DDP_ENABLE=n, when the NIC does not support OOO/AR.
Happens because of an issue in the current logic: DDP_ENABLE=n implies we want MD to support UCT_IB_MLX5_MD_FLAG_DP_ORDERING_FORCE (presumable to force-disable), while in fact it is not needed.
Examine DDP and AR configurations independently; fail if they conflict; pick the maxinal level that is both supported and needed.
Failure example:
```
$ UCX_RC_MLX5_DDP_ENABLE=n UCX_DC_MLX5_DDP_ENABLE=n <path>/gtest --gtest_filter='*reorder_cyclic*' 
[ RUN      ] dc_mlx5/test_rc_srq.reorder_cyclic/0 <dc_mlx5/mlx5_0:1>
[     INFO ] < mlx5_0: cannot set ar_enable=3, ddp_enable=0, capability=0 on dc >
/labhome/yosefe/work/ucx/contrib/../test/gtest/uct/uct_test.cc:862: Failure
Error: Invalid parameter
[ …
```

UCT/MLX5: Fix dp_ordering logic - needed to disable DDP when no AR

---

test/gtest/uct/ib/test_rc.cc

Make CI pass with ConnectX-8 NIC that supports DDP, but DDP cannot be used in combination with cyclic SRQ.

TEST/RC: Disable DDP when forcing cyclic SRQ

---

test/gtest/uct/test_p2p_am.cc

A very short SRQ can cause RNR hang when DDP is used, due to deadlock with too low number of receive buffers.

TEST/UCT/P2P: Increase minimal RX queue length from 64 to 128

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
test/gtest/uct/test_md.cc

Fix [RM](https://redmine.mellanox.com/issues/4314268)

UCT/IB: Fix use of strict order as auxilary rkey

---

docs/source/running.md

DOC/RTD: Fix OpenMPI clone command to include submodules

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5_ep.h

1. Passing pool_index param into dci_create() -> dci_connect() so dci would use the correct configuration by using the correct pool index
2. in find_dci: check that dci is not null before accessing dci->txwq
1. Currently `dci->pool_index` is initialized after dci_connect which relies on its value for determining DCI configuration (such as path_index)
2. in `uct_dc_mlx5_iface_dci_find` when UIDX is not set, `uct_dc_mlx5_iface_dci(iface, dci_index)->txwq.super.qp_num` is being accessed without checking whether DCI is valid (not null)

UCT/IB/MLX5/DC: pass pool_index to dci_create, dci_find: check dci is valid

---

src/ucp/am/eager_multi.c
src/ucp/am/eager_single.c
src/ucp/am/rndv.c
src/ucp/core/ucp_am.c
src/ucp/proto/proto_am.c
src/ucp/proto/proto_am.h
src/ucp/proto/proto_am.inl
src/ucp/proto/proto_reconfig.c

- Handle request progress status properly. 
- Refactor Code.
In some flows of send operations we can reach `ucs_fatal` because status is not handled properly. 
Instead of returning unexpected status code we should abort operation and return `UCS_OK`

UCP/PROTO: Handle request status correctly and refactor

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c

Backport #10436 with cherry-pick of the two commits merged.

UCT/CUDA_IPC: Detect BW systems - v1.18.x

---

src/uct/ib/configure.m4
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/uct/ib/test_devx.cc

This PR discontinues XGVMI support on BF2 devices, by removing umem fallback XGVMI registration
However the tricky part here is that FW capability does not allow to detect whether indirect XGVMI mkeys are actually supported. So we do this check by trying to allow XGVMI access on flush_rkey during MD open.
This has consequences for GGA as well: see the changes

UCT: Removed XGVMI BF2 support (umem)

---

src/ucs/vfs/fuse/vfs_fuse.c

UCS/VFS: Remove unused label

---

buildlib/az-helpers.sh
src/uct/cuda/cuda_copy/cuda_copy_md.c
test/gtest/Makefile.am
test/gtest/uct/cuda/test_switch_cuda_device.cc

Enabled memory attributes query by `cuda_cpy` memory domain after switching CUDA GPU.
Added test.
Without the changes in `cuda_cpy` memory domain the test fails with the following error:
```
cuda_copy_md.c:649  UCX  ERROR cuMemGetAddressRange(0x7f8cd9e00000) error: named symbol not found
```

UCT/CUDA/CUDA_COPY: Enabled memory attributes query after switching CUDA GPU.

---

src/uct/ib/mlx5/dv/ib_mlx5dv_md.c

Fix DEVX ODP check so it will use ODP V1 only if DEVX objects are not created.
ODP V1 can't work with DEVX objects but we only check that RCQP is not created.
Check that we don't use DEVX object on any type.

UCT/IB/DEVX: Fix check ODP.

---

src/uct/cuda/base/cuda_md.c

Changed log level of `cuInit` errors.
Error level is too high for this logging. This code can be called on a system with no CUDA-capable device. Debug message is enough in this case.
Fixes internal issue [4338480](https://redmine.mellanox.com/issues/4338480)

UCT/CUDA/BASE: Changed log level of cuInit errors.

---

AUTHORS
src/ucp/core/ucp_mm.c
test/gtest/ucs/test_string.cc

Fix input validation for -m flag in ucx_info, to allow only positive memory size values
```
ucx_info -u a -m -1,host
[1740736432.183591] [rock16:2056552:0]             sys.c:924  UCX  ERROR   shmget(size=0 flags=0xfb0) for user memory failed: Invalid argument, please check shared memory limits by 'ipcs -l'
[1740736432.183613] [rock16:2056552:0]             sys.c:924  UCX  ERROR   shmget(size=0 flags=0x7b0) for user memory failed: Invalid argument, please check shared memory limits by 'ipcs -l'
[1740736432.183621] [rock16:2056552:0]         mm_sysv.c:114  UCX  ERROR   failed to allocate 18446744073709551615 bytes with mm for user memory
[1740736432.183628] [rock16:2056552:0]         uct_mem.c:161  UCX  ERROR   failed to allocate 18446744073709551615 bytes using md sysv for user memory: Out …
```

TOOLS/INFO: Validate -m flag

---

src/ucp/wireup/select.c

reuse ucp_score_cmp
stable lanes sorting and code unification

UCP/WIREUP: reuse ucp_score_cmp

---

.clang-format
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/base/uct_iface_vfs.c
src/uct/base/uct_md.c
src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
test/gtest/uct/ib/test_dc.cc

- Fix a segfault when trying to show non-existing DCIs in VFS
- Add more details about DCIs and pools to VFS

UCT/DC: Fix VFS objects for DCIs and pools

---

buildlib/tools/check_tls_perf_caps.sh
buildlib/tools/common.sh
src/ucs/sys/netlink.c
src/ucs/sys/netlink.h
src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_verbs.h
src/uct/ib/configure.m4
test/apps/test_ucx_tls.py
test/gtest/common/test_helpers.cc

Multi-plane ConnectX-8 device can have  SMI sub-devices, which we don't want to use for communication.
See more info: https://lore.kernel.org/lkml/171983740416.330197.16009173038296516665.b4-ty@nvidia.com/T/

UCT/IB: Skip SMI devices using netlink query

---

src/tools/perf/lib/ucp_tests.cc

When `ucx_perftest -t ucp_am_bw` is executed in debug mode, then we hit an assertion that verifies the received RNDV message length = configured message size. 
This check fails on final sync message of size 1
Adjust assertion depending on the role: receiver asserts on the payload size, sender may receive only 1 byte final ack

PERF: Assertion on final ack message with RNDV

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h

1. Export handles are used for VA recycling check today but this is not guaranteed to be unique for newer memory allocators like VMM, and CUDA memory pools. We need to switch to using buffer_id attribute to perform this check.
2. We call MempoolDestroy when invalidating import entries which can hurt performance for mempool caching logic as we would be forced to reimport mempools again. This PR frees the suballocation instead of freeing the imported mempool altogether.

UCT/CUDA_IPC: Use buffer id to detect VA recylcing

---

src/uct/rocm/base/rocm_signal.c
src/uct/rocm/copy/rocm_copy_ep.c
src/uct/rocm/ipc/rocm_ipc_ep.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.h

add a UCX parameter that allows to control whether we want to use the rocm_ipc handle cache.
There are some situation where caching the IPC handles/registrations is detrimental for a multitude of reasons.

UCT/ROCM: add control of ipc cache usage

---

config/m4/rocm.m4

cleanup of the rocm configure script, removing outdated directories, macro definitions, and libraries that are not required.
Fixes https://github.com/openucx/ucx/issues/10542

CONFIG/M4: cleanup rocm configure script

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/core/ucp_ep.c
src/ucp/core/ucp_ep.h
src/ucp/wireup/select.c
src/ucp/wireup/wireup.c
src/ucp/wireup/wireup.h
src/ucp/wireup/wireup_cm.c
test/gtest/ucp/test_ucp_ep_reconfig.cc

UCP/WIREUP: Support EP reconfiguration for non wired-up scenarios
This PR introduces 2 additional usecases supported:
1) Reconfiguration during send/recv phase (after wireup completion).
2) Reconfiguration during wireup phase for non p2p transports, given that one of the following conditions takes place:
- wireup lane and AM lane are equal.
- AM lane is reused.
- AM transport is p2p.

UCP/WIREUP: Support EP reconfiguration for non wired-up scenarios

---

buildlib/az-helpers.sh
buildlib/tools/common.sh
buildlib/tools/perf-common.yml

Update CUDA and gdrcopy modules used in CI to version 12.8.
[HPCINFRA-3113](https://jirasw.nvidia.com/browse/HPCINFRA-3113) (Internal link).

AZP: Update CUDA and gdrcopy versions

---

src/ucs/sys/netlink.c
src/ucs/sys/netlink.h
src/uct/ib/base/ib_device.c
src/uct/ib/base/ib_device.h
src/uct/ib/base/ib_iface.c

Add a routing table cache.
Instead of sending a Netlink request to retrieve the routing table for each reachability check, reuse the same local routing table data structure and free it after the wire-up process completes.

Add a routing table cache to the reachability check

---

src/ucp/rndv/proto_rndv.inl
test/gtest/ucp/test_ucp_proto_mock.cc

The max_frag assertion that was fixed with https://github.com/openucx/ucx/pull/10407 is still possible to happen with slightly different combination:
when ucp_proto_multi_scaled_length > lpriv->min_end_offset = max_frag
The root cause of this issue is weight calculation.
We calculate weights according to the lane BW/total BW. And we expect that max_frag ratio is the same, but it's not always the case. For example, there is a corner case when `max_frag` of the maximal BW lane is smaller than `max_frag` of the slow lane.
In theory we should calculate lane weight according to lane max_frag/total max_frag, but this requires quite some changes in proto_multi and might be risky (tried that).

UCP/RNDV: Fixed assertion when scaled end offset > max_frag

---

contrib/test_efa.sh
src/uct/ib/efa/Makefile.am
src/uct/ib/efa/srd/srd_def.h
src/uct/ib/efa/srd/srd_ep.c
src/uct/ib/efa/srd/srd_ep.h
src/uct/ib/efa/srd/srd_iface.c
src/uct/ib/efa/srd/srd_iface.h
test/gtest/Makefile.am
test/gtest/uct/ib/test_srd.cc
test/gtest/uct/uct_test.h

Add initial SRD endpoint creation.

UCT/IB/EFA/SRD: Initial add of endpoint

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto_init.c
src/ucp/proto/proto_init.h
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_single.c
src/ucp/rndv/rndv_mtype.inl
src/ucp/rndv/rndv_ppln.c
src/ucp/wireup/select.c
src/uct/api/v2/uct_v2.h
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
test/gtest/ucp/test_ucp_proto_mock.cc

Make sure to disable any protocol using locally or remotely, a memory type based copy.
Need to avoid all cuda calls from under `ucp_worker_progress()`. Cuda memory queries are fine since they are performed under send/recv operations. `cuda_ipc` transport can be disabled altogether, and `gdr_copy` is anyways not of interest when specifying `UCX_MEMTYPE_AVOID_COPY=y`.
Disable applicable protocols altogether, for any memory type (cuda/host..).
Might need to make inline sizes to 0, see below otherwise.
```
UCX_IB_TX_INLINE_RESP=0 UCX_MEMTYPE_AVOID_COPY=y ucx_perftest
UCX_IB_TX_INLINE_RESP=0 UCX_MEMTYPE_AVOID_COPY=y ucx_perftest -t ucp_put_bw -m cuda,cuda rock
```
Used by perftest to exchange `psn_t sn`:
```
| perftest self cfg#2 | remote memory read by ucp_get* into host memory from cuda    | …
```

UCP/PROTO: Disable protocols that need memory type copy

---

src/ucp/core/ucp_worker.c

Dump rkey config hashtable keys when full. This is to help understand why the situation occurs.
Before this patch, the only error seen in the log is:
```
ucp_worker.c:2155 UCX  ERROR             too many rkey configurations: 128 (max: 128)
```
which is not sufficient to understand why there are so many keys in this setup.

UCP/CORE: Dump rkey configs when limit is reached

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h
test/gtest/uct/cuda/test_switch_cuda_device.cc

Allow a single UCP context to handle multiple CUDA devices for cuda_copy transport. This enables use cases under Legion/Realm, OpenACC, and MPI workloads that prefer 1:N process-to-GPU mapping than the default current 1:1 mapping.
CUDA stream and event resources which were previously tied to iface now are tied to each newly detected cuda device context. When resources are needed, context ID is looked up using a hashtable and appropriate resources are picked.
1. ~~Need a way to detect if cuda context is destroyed before destroying stream/event resources associated with that context~~ (not going to cleanup resources and leave it to the OS to handle it)
2. ~~Need to check if stream bitmap is needed for flush operations and flush each individually using streamsync~~ (removed)

UCT/CUDA_COPY: add multi-device support in cuda_copy

---

src/ucp/core/ucp_context.h

fix ucp_tl_resource_desc_t::dev_index documentation
to clarify real behavior

UCP/CORE: fix ucp_tl_resource_desc_t::dev_index documentation

---

test/gtest/uct/test_p2p_am.cc

Fix test failures on ConnectX-8 with DDP enabled

TEST/UCT: Increase RX queue length of no-buffers test to 256

---

src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/api/uct.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/base/uct_mem.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/base/cuda_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.c
src/uct/cuda/cuda_copy/cuda_copy_md.h
src/uct/ib/mlx5/dv/ib_mlx5dv_md.c
src/uct/ib/mlx5/ib_mlx5.h
src/uct/rocm/copy/rocm_copy_md.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/ze/copy/ze_copy_md.c
test/gtest/ucs/test_topo.cc
test/gtest/uct/cuda/test_switch_cuda_device.cc
test/gtest/uct/uct_test.cc

Re-adds existing API PR #10448 with latest comments addressed, and UCT implementation.
Fragments used for pipeline need to use the same GPU as the user GPU.
Set context if needed, if not available find first usable primary context. If explicit context was requested and not found, return an error.

UCT/CUDA: Use sys_dev to allocate CUDA memory

---

contrib/test_jenkins.sh
src/ucs/arch/bitops.h
src/ucs/arch/x86_64/cpu.c
test/gtest/ucs/arch/test_x86_64.cc
test/gtest/ucs/test_bitops.cc

Use common UCS count leading zeros function (implemented with `__builtin_clz()`) to address #10509.
nvc 24.9 seems to have issue with `_lzcnt_u32()`. It defines it as `__builtin_ia32_lzcnt_u32()` but fails to find it at link time. But the `_lzcnt_u32()` function seems to be likely defined as `__builtin_clz()` in gcc, and is also properly linked by nvc.

ARCH/X86: Use UCS function to count leading zeros

---

test/gtest/ucp/test_ucp_ep_reconfig.cc

Skip reconfig test temporarily 
Ensure CX8 tests pass successfully

UCP/TEST: Skip reconfig test temporarily

---

src/uct/cuda/base/cuda_iface.c
src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_copy/cuda_copy_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h

Original PR: https://github.com/openucx/ucx/pull/9654
Currently CUDA_IPC transport uses integer stream_count to track outstanding work but in preparation for multi-device support, this PR moves to active_queue usage similar to cuda_copy transport. This will eventually also help unify more common code shared between cuda_ipc and cuda_copy when it comes to stream/event usage. This PR also removes max peer limitations.

UCT/CUDA_IPC: Context switching aware resource management

---

src/ucp/core/ucp_ep.c
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/core/ucp_rkey.inl
src/ucp/rndv/proto_rndv.c
src/uct/api/v2/uct_v2.h
src/uct/base/uct_component.h
src/uct/base/uct_md.c
src/uct/base/uct_md.h
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/gdr_copy/gdr_copy_md.c
src/uct/ib/base/ib_md.c
src/uct/ib/base/ib_md.h
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/rocm/copy/rocm_copy_md.c
src/uct/rocm/ipc/rocm_ipc_md.c
src/uct/sm/mm/posix/mm_posix.c
src/uct/sm/mm/sysv/mm_sysv.c
src/uct/sm/mm/xpmem/mm_xpmem.c
src/uct/sm/scopy/knem/knem_md.c
src/uct/sm/self/self.c
src/uct/ugni/base/ugni_md.c
src/uct/ze/copy/ze_copy_md.c
test/gtest/ucp/test_ucp_mmap.cc
test/gtest/uct/cuda/test_cuda_ipc_md.cc

Define uct_rkey_unpack_v2 to be able to pass sys_device to rkey unpack. It may be needed for some transports (e.g. cuda_ipc) to properly unpack the rkey. For cuda_ipc handle should be imported on the context corresponding to the device where the user buffer was allocated.

UCT/API: Define rkey_unpack v2

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_multi.c
src/uct/api/v2/uct_v2.h
src/uct/base/uct_iface.c
src/uct/base/uct_iface.h
src/uct/cuda/cuda_copy/cuda_copy_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/gdr_copy/gdr_copy_iface.c
src/uct/ib/base/ib_iface.c
src/uct/rocm/copy/rocm_copy_iface.c
src/uct/sm/mm/base/mm_iface.c
src/uct/ze/copy/ze_copy_iface.c
test/gtest/ucp/test_ucp_proto_mock.cc

This is the minimal version of https://github.com/openucx/ucx/pull/10508
Formerly known as "lane sorting" task.
When CUDA context is set, then rma_bw_lanes array is adjusted with GPU distance.
When CUDA context is not set in the caller thread, then UCX protocol does not always choose fastest lanes for GPU memory.
The idea is to select lanes at the protocol selection stage after performance estimation.
We need to find the best combination of lanes for a given operation.
https://confluence.nvidia.com/display/NSWX/Protocol+lane+selection+testing
Mock tests PR: https://github.com/openucx/ucx/pull/10547

UCP/PROTO: Minimal version of protocol lane selection

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dc/dc_mlx5.h
src/uct/ib/mlx5/dc/dc_mlx5_ep.c
src/uct/ib/mlx5/dc/dc_mlx5_ep.h
src/uct/ib/mlx5/rc/rc_mlx5_ep.c
src/uct/ib/rc/base/rc_ep.h
src/uct/ib/rc/verbs/rc_verbs_ep.c
test/gtest/uct/ib/test_dc.cc

Fix invalid access to dci at index NO_DCI during fence
- Check ep->dci!= NO_DCI before accessing the array
- Add assertion that we don't access DCI at invalid index
- Small changes in DCI create flow to not fail on the new assertion

UCT/DC: Fix segfault in uct_dc_mlx5_ep_fence

---

src/uct/cuda/base/cuda_iface.h
src/uct/cuda/cuda_copy/cuda_copy_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
test/gtest/uct/cuda/test_switch_cuda_device.cc
test/gtest/uct/test_p2p_rma.cc
test/gtest/uct/test_p2p_rma.h

Relaxed CUDA context dependency in cuda_copy transport.

UCT/CUDA/CUDA_COPY: Relaxed CUDA context dependency in cuda_copy transport.

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h
test/gtest/uct/cuda/test_cuda_ipc_md.cc

After #10405, existing error becomes visible when unpacking rkey. Memory was allocated with `cuMemAlloc()` as fabric-related allocations fail (rock, perftest -m cuda,cuda, recv_memh/send_memh), then in `cuda_ipc` mpack, we erroneously see legacy attribute being false.
The `allowed_handle_types` should apparently be 8 bytes, not 4 bytes and it seems to be corrupting the legacy variable.
Added fix and corresponding test.
```
#0  uct_cuda_ipc_open_memhandle (key=0x2470343, mapped_addr=0x7fffffffb468) at cuda_ipc/cuda_ipc_cache.c:339
#1  0x00007fffec29fbac in uct_cuda_ipc_map_memhandle_inner (mapped_addr=0x7fffffffb468, key=0x2470343) at cuda_ipc/cuda_ipc_cache.c:528
#2  uct_cuda_ipc_map_memhandle (key=0x2470343, mapped_addr=0x7fffffffb468) at cuda_ipc/cuda_ipc_cache.c:478
#3 …
```

UCT/CUDA_IPC: Fix missing legacy type detection during mpack

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.c
src/uct/cuda/cuda_ipc/cuda_ipc_iface.h
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h
test/gtest/uct/cuda/test_cuda_ipc_md.cc
test/gtest/uct/test_md.cc

Pass sys device to the rkey_unpack function, assuming it is safe to always retain primary context of that device. If sys device is not passed to the rkey_unpack function, we either use the current context or fail. It would be incorrect to use any active primary context at this stage because we don’t yet know where the target memory will reside.

UCT/CUDA-IPC: Support multi context for rkey unpack

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/wireup/select.c
test/gtest/ucp/test_ucp_perf.cc
test/gtest/ucp/test_ucp_tag_mem_type.cc
test/gtest/ucp/test_ucp_tag_xfer.cc

Fixes on top of https://github.com/openucx/ucx/pull/10503 to finalize the All2All Wireup on Multi NIC-GPU feature.
Performance optimization for multiple NICs/GPUs systems.
Renamed the env var to `UCX_CONNECT_ALL_TO_ALL`, added a restriction to allow only one path for this feature, fixed lane creation ordering to avoid `ucp_wireup_match_p2p_lanes()` failure, and applied additional review comments.

UCP/WIREUP: Fix All2All Wireup on Multi NIC-GPU

---

src/ucp/wireup/select.c

Fix `ucp_wireup_add_bw_lanes_a2a()` to continue evaluating all device pairs when selecting bandwidth lanes.
Previously, when `ucp_wireup_select_transport()` returned `UCS_ERR_UNREACHABLE` for a given (local_dev, remote_dev) pair, the loop exited early due to a break statement.
This caused some lanes to be skipped, resulting incorrect All2All lane selection.
Replaced break with continue to ensure the function evaluates all valid (local_dev, remote_dev) combinations, even if some of them are unreachable.

UCP/WIREUP: Fix a2a lane creation

---

src/uct/rocm/ipc/rocm_ipc_ep.c
src/uct/rocm/ipc/rocm_ipc_iface.c
src/uct/rocm/ipc/rocm_ipc_iface.h

_Describe what this PR is doing._
Adds parameter (UCX_ROCM_IPC_SIGPOOL_MAX_ELEMS) to control the maximum number of elements in hsa signal pool (ucs_mpool_params). Changes from 1024 (default) to parameter.
Same as #9366 but for ROCM_IPC
_Justification for the PR. If there is an existing issue/bug, please reference it. For
bug fixes, the 'Why?' and 'What?' can be merged into a single item._
We may want to increase the number of signals for certain applications
_It is optional, but for complex PRs, please provide information about the design,

UCT/ROCM: Add parameter to control max elements in IPC sigpool

---

src/ucp/rma/flush.c
src/ucp/rma/rma.inl

Fix assertion failure in `ucp_ep_fence_weak()` when `unflushed_lanes` is 0.
The function `ucp_ep_fence_weak()` was being called when there were no `unflushed_lanes` to fence, causing an assertion failure.
Skip fence operation in `ucp_ep_rma_handle_fence()` when unflushed_lanes is 0.

UCP/RMA/FLUSH: Fix failure in ucp_ep_fence_weak when unflushed_lanes is 0

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Set CUDA SYNC_MEMOPS flags during init phase as it is causing deadlock with other CUDA operations that might be running in parallel.
It is currently assumed that setting again the SYNC_MEMOPS flag on a CUDA context that already has it, does not cause deadlock.

UCT/CUDA/CUDA_COPY: Set sync memops flag early to avoid deadlocks

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Currently, asynchronous memory can be detected as CUDA-managed, with its sys_dev set to unknown. However, for async VMM memory, knowing the sys_dev is crucial to identify the correct CUDA context for executing cuMemcpyAsync.
Test from #10601 fails when sending an eager message from legacy pinned  memory to asynchronous VMM memory (on isr1). On the receiver side, the destination buffer is detected as CUDA-managed with an unknown sys_device, preventing the cuda_copy transport from selecting the correct context for the VMM allocation.

UCT/CUDA: Detect sys_dev for async allocations

---

src/ucp/rndv/proto_rndv.c

When rndv pipeline is used for CUDA-managed memory, rkey received in RTS or RTR must be unpacked with a default sys_dev instead of UNKNOWN_ID. This ensures that CUDA IPC can correctly map/import the handle from the rkey on the appropriate device, matching device where staging buffer was allocated.
Will be tested by #10601

UCP: Use correct device for cuda-managed memory ppln

---

src/ucp/wireup/wireup.c
src/ucp/wireup/wireup_ep.c
src/ucp/wireup/wireup_ep.h

wireup uses UD uct_ep_am_bcopy to send wireup message to the peer, and that message size depends on amount of used devices. It is also limited by MTU/max_bcopy size.
With large number of devices (>15) and small MTU/max_bcopy size (1024) it leads to a memory corruption/hang in release mode, or assertion in debug.
Current solution is to detect this limit in wireup before sending a message, and report an error

UCP/WIREUP: Fix memory corruption when MTU/max_bcopy is small

---

test/gtest/ucp/test_ucp_perf.cc

Disabled checking the values in test_ucp_perf.envelope. It doesn't make much sense to check the performance during the CI. Since multiple instances may run on the same host, and there may be slowdowns.
Cherry-picked https://github.com/openucx/ucx/pull/10336

GTEST/UCP: Disabled checking the values in test_ucp_perf.envelope - v1.18.x

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Changed log level used in `uct_cuda_copy_mem_free`. `DIAG` log level is enough for the purpose of the function.
The memory can be implicitly destroyed using CUDA Driver/Runtime API: e.g. `cuDevicePrimaryCtxRelease`, `cuDevicePrimaryCtxReset`, `cudaDeviceReset`. The following error may be observed during the resources clean up:
```
cuda_copy_md.c:610  UCX  ERROR cuMemFree_v2(alloc_handle->ptr) failed: invalid argument
ucp_mm.c:460  UCX  WARN  failed to free: Input/output error
```

UCT/CUDA/CUDA_COPY: Changed log level in mem_free.

---

src/uct/cuda/cuda_ipc/cuda_ipc_cache.c

Push the primary device context before calling `cuIpcCloseMemHandle`.
There is a warning if there is no CUDA context bound to the current CPU thread while closing memory handle.
```
cuda_ipc_cache.c:132  UCX  WARN  cuIpcCloseMemHandle( (CUdeviceptr)region->mapped_addr) failed: invalid device context
```

UCT/CUDA/CUDA_IPC: cuCtxPushCurrent before cuIpcCloseMemHandle.

---

src/uct/ib/base/ib_iface.h

Cleanup index usage in IB macros.

UCT/IB: Use parameter index in RXWQE and completion error macros

---

test/gtest/uct/test_stats.cc

Fix always skipped pending add statistics tests.
```
[ RUN      ] rc_mlx5/test_uct_stats.pending_add/0 <rc_mlx5/mlx5_0:1>
[     SKIP ] (Can't add to pending)
[       OK ] rc_mlx5/test_uct_stats.pending_add/0 (42 ms)
```
```
[ RUN      ] rc_mlx5/test_uct_stats.pending_add/0 <rc_mlx5/mlx5_0:1>
[       OK ] rc_mlx5/test_uct_stats.pending_add/0 (42 ms)
```

GTEST/UCT: Fix pending_add test

---

src/ucp/rma/flush.c
src/ucp/rma/rma.inl
test/gtest/ucp/test_ucp_rma.cc

Following https://github.com/openucx/ucx/pull/10602#discussion_r2028268723
Reduce branching in `ucp_ep_rma_handle_fence()`, by using `ucs_is_pow2_or_zero()` instead of `ucs_is_pow2()`, which is less branches, and because unflushed lanes isn't 0, this swap is valid.
The test case reproduces a case where unflushed lanes is 0 for both weak and strong fences.

UCP/RMA/FLUSH: Reduce branches in EP based fence

---

src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
test/apps/test_ucx_tls.py

Setting `UCX_TLS=^ib` now disables all ib transports, including auxiliary ones.
For other aliases, auxiliary disabling must be explicitly specified. 
Based on https://github.com/openucx/ucx/pull/8778, when disabling ud based transports, they should still be available as auxiliary. Thus, `UCX_TLS=^ud` does not disable their auxiliary usage.
However, we still want `UCX_TLS=^ib` to be treated as a global exclusion of all ib transports, including auxiliary ones.
To support this, a new distinction now differentiates global aliases (e.g. ib) from specific aliases (e.g. ud, rc, etc.).

UCP/CORE: disable everything (aux as well) when ^ib is configured

---

src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
test/gtest/uct/ib/test_rc.cc

When md does not support flush_rkey, rc verbs already returns reduced size. This PR generalizes that behavior by checking iface remote flush support, which matches what is done for rc_x and dc transports.
When unpacking address, the flag `UCT_RC_VERBS_ADDR_HAS_ATOMIC_MR` is gating the access to the extra 3 bytes, so this should not impact wire compatibility. Also it is assumed symmetric iface FLUSH_REMOTE configuration.

UCT/IB/RC: Adapt EP address size without flush_rkey

---

src/uct/ib/base/ib_log.c
src/uct/ib/base/ib_log.h
src/uct/ib/efa/srd/srd_def.h
src/uct/ib/efa/srd/srd_ep.c
src/uct/ib/efa/srd/srd_ep.h
src/uct/ib/efa/srd/srd_iface.c
src/uct/ib/efa/srd/srd_iface.h
src/uct/ib/efa/srd/srd_log.c
src/uct/ib/efa/srd/srd_log.h
test/gtest/uct/ib/test_srd.cc

Add pending management and control message exchange to remotely add AH, before posting RMA operations.
Tracking remote AH state on iface or MD could cause issues as there could be multiple MD (protection domain) opened on the same remote HCA, and while locally iface or MD could remain, the remote entities could have been released and reopened with same QP id, making it difficult to identify if sending another control request is needed.
All posts are anyways heavily reordered so:
1. Only one pending queue for an endpoint
2. We put RMA on pending if confirmation has not been received, as they cannot be posted
3. We put AM on pending if our pending is not empty (we could probably simply post but this could cause prio issues wrt RMA)
4. We allow the sending of AM if pending is empty, even …

UCT/EFA/SRD: Add pending and control request and response

---

test/gtest/common/mem_buffer.cc
test/gtest/ucp/test_ucp_proto_mock.cc
test/gtest/uct/cuda/test_cuda_ipc_md.cc

RM: https://redmine.mellanox.com/issues/4403835
Fix for failing tests executed under valgrind

GTEST: Fixed valgrind tests

---

test/gtest/ucp/test_ucp_mmap.cc

On protov1, `ucp_rma_basic_proto` can only be selected when both PUT and GET operations are available.

UCP/GTEST: Do not assert when checking proto v1 rma protocol

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Calling cuMemHostUnregister does not produce an error when invoked from a different context than the one it was originally registered in (or even without an active context). However, it will fail if the context in which the memory was allocated has been destroyed.
fixes [RM4410114](https://redmine.mellanox.com/issues/4410114)  (internal link)
same way as #10606

UCT/CUDA: Do not print host unregister error (use diag)

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Calling cuMemHostUnregister does not produce an error when invoked from a different context than the one it was originally registered in (or even without an active context). However, it will fail if the context in which the memory was allocated has been destroyed.
porting #10643

UCT/CUDA: Do not print host unregister error (use diag) - v1.19.x

---

src/ucp/wireup/wireup.c

Moved gather_pending_requests to be executed only when reconfig occurs
Prevent pending requests replay when not needed
Solves issue: https://redmine.mellanox.com/issues/4411471

UCP/WIREUP: Moved gather_pending_requests to be executed only when reconfig occurs

---

src/ucp/wireup/wireup.c

Backport https://github.com/openucx/ucx/pull/10656
Prevent pending requests replay when not needed
Solves issue: https://redmine.mellanox.com/issues/4411471

UCP/WIREUP: Moved gather_pending_requests to be executed only when reconfig occurs - v1.19

---

src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
test/gtest/uct/ib/test_rc.cc

Revert #10633 
Backport https://github.com/openucx/ucx/pull/10661

UCT/IB/RC: Revert adapt EP address size without flush_rkey - v1.19.x

---

src/tools/perf/lib/libperf_int.h

Fix build failure reported in #10663. libgomp (gcc) and libomp (llvm) both already protect their declarations with `extern C` when applicable.

TOOLS/PERF: Include omp.h outside of extern C declarations

---

src/ucp/wireup/select.c
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/efa/srd/srd_ep.c
src/uct/ib/efa/srd/srd_iface.c
src/uct/ib/mlx5/gga/gga_mlx5.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/rc/rc_mlx5_ep.c
src/uct/ib/mlx5/rc/rc_mlx5_iface.c
src/uct/ib/mlx5/ud/ud_mlx5_common.c
src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/ud/verbs/ud_verbs.c
test/gtest/Makefile.am
test/gtest/uct/ib/test_ib.cc
test/gtest/uct/ib/test_ib_pkey.cc
test/gtest/uct/ib/test_ud_ds.cc
test/gtest/uct/test_uct_iface.cc

Before:
`[1740477778.122527] [swx-ucx-ibr-03:1950035:0]          select.c:641  UCX  ERROR   no active messages transport to <no debug data>: self/memory - Destination is unreachable, rc_verbs/mlx5_0:1 - Destination is unreachable`
After:
`[1740487396.304113] [swx-ucx-ibr-03:1951997:0]          select.c:642  UCX  ERROR   no active messages transport to swx-ucx-ibr-01:3618365: self/memory - unreachable, rc_verbs/mlx5_0:1 - different subnet prefix 0xfec0000000000002/0xfec0000000000001 and FLID is not available`

UCP/WIREUP/IB: Fix error message when FLID is not available

---

src/uct/ib/rc/verbs/rc_verbs_ep.c
src/uct/ib/rc/verbs/rc_verbs_iface.c
test/gtest/uct/ib/test_rc.cc

Revert #10633, as when MD has a valid flush_rkey (devx MD), the atomic mr offset is still needed for rc verb ep fence put, as for RTR there is a valid atomic rkey, regardless of flush_remote configuration.
repro: `./test/gtest/gtest --gtest_filter=rc/test_ucp_tag_match_rndv.post_larger_recv/2`

UCT/IB/RC: Revert adapt EP address size without flush_rkey

---

contrib/test_jenkins.sh
test/mpi/Makefile.am
test/mpi/test_mpi_cuda.c

TEST/MPI: Added MPI+CUDA example.

---

bindings/go/src/ucx/am_data.go
bindings/go/src/ucx/callbacks.go
bindings/go/src/ucx/context.go
bindings/go/src/ucx/endpoint.go
bindings/go/src/ucx/listener.go
bindings/go/src/ucx/listener_params.go
bindings/go/src/ucx/request.go
bindings/go/src/ucx/ucp_contsants.go
bindings/go/src/ucx/worker.go

Fix gobindings bugs.
- cbId -> worker map, `idToWorker`, is not thread safe.
- UCX's mem hooks not working properly with Go.
- Remove `idToWorker` map and pass tuple.
- Use golang convention for passing obj to native, [Handles](https://pkg.go.dev/runtime/cgo#Handle), instead of direct use of hashmap.
- Set `GVA_ENABLE` to auto by default on ctx creation.

BINDINGS/GO: Bug fix - make gobindings thread safe.

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Removed redundant debug log message from the method that checks that memory is allocated using VMM API.

UCT/CUDA/CUDA_COPY: Removed redundant log message from memory query.

---

src/ucp/proto/proto_common.c

On rock and other devices cuda_copy transport is not selected for loopback d2d tests.
This happens because cuda_copy BW is `10000MBs,h2d:8300MBs,d2h:11660MBs,d2d:320GBs`, but protocol selection does not specify the src/dst memory types when performing an evaluation.
Use existing API to pass specific information about src/dst memory to cuda_copy so that it can use appropriate BW from the config above.
Tested manually with ucx_perftest, gtest does not work with cuda out of the box

UCP/PROTO/CUDA: Detect src/dst memtype when estimating lane perf

---

src/uct/cuda/Makefile.am
src/uct/cuda/cuda_ipc/cuda_ipc.inl
src/uct/cuda/cuda_ipc/cuda_ipc_cache.c
src/uct/cuda/cuda_ipc/cuda_ipc_cache.h
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.c
src/uct/cuda/cuda_ipc/cuda_ipc_md.h
test/gtest/uct/cuda/test_cuda_ipc_md.cc

Set context associated with local buffer before performing RMA operation in cuda_ipc transport.
Fix the following scenario:
1. Allocate data using CUDA VMM API, setting access to CUDA device X.
2. Set CUDA device Y.
3. Unpack remote key.
4. Perform UCP RMA operation.
5. `cuda_ipc::[get|put]_zcopy` fails to perform `cuMemcpyDtoDAsync`.
The issue was found using https://github.com/openucx/ucx/pull/10670.

UCT/CUDA/CUDA_IPC: Set context associated with local buffer.

---

src/ucp/proto/proto_init.c
test/gtest/ucp/test_ucp_proto_mock.cc

Increase the latency factor of send-zcopy protocols in cases of fast completion only.
To fix the performance issue revealed in https://redmine.mellanox.com/issues/4119625, this PR limits the increment of the latency factor in send-zcopy to cases of fast-completion only, as done until this PR https://github.com/openucx/ucx/pull/10213 (remote cpu overhead is still incremented for all cases that wait for a response).

UCP/PROTO: Increase latency factor in send-zcopy protocols only for fast completions

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Removed non-versioned typedef.

UCT/CUDA/CUDA_COPY: Removed non-versioned typedef.

---

AUTHORS
src/ucs/sys/sys.c

Delete redundant code in "ucs_read_file_vararg" function.
There is no point to check if "read_bytes" is less than "max" because we are calling "read" with buffer size "max - 1".
Thereforce we can delete redundant check and always terminate the buffer (string) in "read_bytes" position.

UCS/SYS: Delete redundant code in ucs_read_file_vararg

---

src/tools/perf/perftest_params.c

Fix wakeup feature request during context creation, which already uses `-I` option.

TOOL/PERFTEST: Differentiate wakeup feature and extra info options

---

src/ucp/core/ucp_context.h
src/ucp/core/ucp_worker.c
src/ucp/wireup/select.c

Do not request for memory invalidation if RDNV, intra or inter, cannot be used.
```
UCX_PROTO_INFO=y ucx_perftest -l -t ucp_get -e
<invalidate requested, sw emulation if no support>
UCX_PROTO_INFO=y UCX_RNDV_THRESH=intra:auto,inter:inf ucx_perftest -l -t ucp_get -e
<invalidate requested, sw emulation if no support>
UCX_PROTO_INFO=y UCX_RNDV_THRESH=inf ucx_perftest -l -t ucp_get -e
<invalidate not requested, zcopy>
```

UCP/WIREUP: Don't request invalidate without RNDV

---

src/uct/rocm/base/rocm_base.c
src/uct/rocm/base/rocm_base.h
src/uct/rocm/copy/rocm_copy_iface.c

- use the gfx arch name as the main mechanism to detect GPU type.
- Remove the distinction between MI300A and MI300X, we are not distinguishing between the two later stages anyway.
- detect gfx950 for MI350/355 GPUs (tuning for these GPUs might come in a later commit).

UCT/ROCM: cleanup GPU detection code

---

debian/control.in
debian/rules.in

Moved `ucx-cuda` package dependency on `libnvidia-compute | libnvidia-ml1` from `Depends` to `Recommends`.
The default behavior of `apt-install` remains unchanged. And  `--no-install-recommends` can be used to avoid installing driver level packages in a container.

DEBIAN: Moved driver level dependencies under Recommends section.

---

src/uct/cuda/base/cuda_iface.h

Removed extra branch from `UCT_CUDADRV_FUNC` macro.
Very few CUDA Driver API calls can return `CUDA_ERROR_NOT_READY`: `cuEventQuery`, `cuStreamQuery`, `cuEventElapsedTime`. And `cuEventQuery` is handled without the macro.
Added `ucs_likely` since the macro is used in fast path.

UCT/CUDA: CUDA call logging enhancment.

---

src/ucp/core/ucp_mm.h

Remove unused function which cannot be used with `ucp_memh->uct` as first parameter because it is a sparse array.

UCP/MM: Remove deprecated function

---

test/gtest/uct/cuda/test_switch_cuda_device.cc
test/mpi/test_mpi_cuda.c

Builds failed with newer versions. This PR addresses new use in preparation for upcoming release.

TEST: use cuCtxCreate_v4 by default for newer CUDA versions

---

src/uct/cuda/cuda_copy/cuda_copy_md.c

Fix stack overflow bug when calling cuPointerGetAttribute
Fix crash caused by override of log_level value to fatal.

UCT/CUDA_COPY: Fix stack overflow bug when calling cuPointerGetAttribute

---

debian/control.in

Allow any library that depends on the upstream Ubuntu packaging (libucx0, libucx-dev, ucx-utils) to work with the internal UCX packaging, that is distributed in DOCA/MLNX_OFED.
[Internal issue](https://redmine.mellanox.com/issues/4512374)

DEBIAN: Add Provides field for upstream packages

---

debian/control.in

DEBIAN: Add Provides field for upstream packages - v1.19.x

---

bindings/java/pom.xml.in
buildlib/jucx/jucx-build.yml

Migrate JUCX publishing from OSSRH to Central Portal to fix Maven deployment failures.
OSSRH reached End-of-Life on June 30, 2025: https://central.sonatype.org/pages/ossrh-eol/
All namespaces were migrated to Central Portal, requiring updated build configuration to use the new publishing system.
- Use `nexus-staging-maven-plugin` with Central Portal compatibility endpoints
- Update distribution management URLs to `ossrh-staging-api.central.sonatype.com`
- Configure pipeline to use `central` server ID in settings.xml

CI: Migrate JUCX publish from OSSRH to Central Portal

---

bindings/java/pom.xml.in
buildlib/jucx/jucx-build.yml

Migrate JUCX publishing from OSSRH to Central Portal to fix Maven deployment failures.
OSSRH reached End-of-Life on June 30, 2025: https://central.sonatype.org/pages/ossrh-eol/
All namespaces were migrated to Central Portal, requiring updated build configuration to use the new publishing system.
- Use `nexus-staging-maven-plugin` with Central Portal compatibility endpoints
- Update distribution management URLs to `ossrh-staging-api.central.sonatype.com`
- Configure pipeline to use `central` server ID in settings.xml

CI: Migrate JUCX publish from OSSRH to Central Portal - v1.19.x

---

src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/cuda/cuda_copy/cuda_copy_md.c

Map DMA_BUF handle via PCIe only if GPU has a sibling Direct NIC device.
Reverted fix for https://github.com/openucx/ucx/pull/10760#discussion_r2226303345.

UCT/CUDA/CUDA_COPY: Fixed mapping of DMA_BUF handle.

---

test/gtest/uct/cuda/test_cuda_ipc_md.cc

Skip test_cuda_ipc_md.mkey_pack_mempool when running with CUDA Driver 13.

GTEST/UCT/CUDA: Skip test_cuda_ipc_md.mkey_pack_mempool.

---

config/cuda.am
config/m4/compiler.m4
config/m4/cuda.m4
configure.ac
contrib/ctags.sh
test/apps/Makefile.am

Add CUDA files build support.
Need to add .cu/.cuh files in the build system.
- Separate rules in CUDA-specific Makefile with general flags
- Detect and load files dependency implicitly
- Add gencode configure option (not all CUDA libraries support all arch, and there might be later version)

BUILD: Add ability to build CUDA code

---

src/ucp/rndv/proto_rndv.c

When calculating rkey size for rndv protocols need to check whether each lane can reach memory sys_dev (which may not be the case for direct NIC)
To fix this assert  (happens on the system with direct NIC)
```
rndv_rtr.c:121  Assertion `rkey_size == rpriv->super.packed_rkey_size' failed: rkey_size=31 exp=58
```

UCP/RNDV: Fix rkey size estimation

---

test/gtest/uct/cuda/test_cuda_nvml.cc

Relaxed test_cuda_nvml.device_get_fabric_info condition.
`nvmlDeviceGetGpuFabricInfoV` may return an error. This is not critical.
We handle this behavior in the UCT code.

GTEST/UCT: Relaxed test_cuda_nvml.device_get_fabric_info condition.

---

src/ucs/sys/topo/base/topo.c

Added error codes to `ucs_topo_find_device_by_bus_id`.
It always returns `UCS_OK`.

UCS/SYS/TOPO: Added error codes to ucs_topo_find_device_by_bus_id.

---

src/uct/ib/mlx5/dc/dc_mlx5.c
src/uct/ib/mlx5/dv/ib_mlx5_dv.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h

To create QP/CQ with work buffer and doorbell record in non-regular memory like VRAM.
Decouple memory allocation from object creation code.

UCT/MLX5: Add DEVX QP/CQ on foreign memory support

---

src/tools/perf/api/libperf.h
src/tools/perf/cuda/cuda_alloc.c
src/tools/perf/perftest.c
src/tools/perf/perftest.h
src/tools/perf/perftest_params.c
src/tools/perf/perftest_run.c
test/gtest/common/test_perf.cc
test/gtest/ucp/cuda/test_kernels.cu

Added GDAKI kernel option to ucx_perftest, so that we can run GDAKI tests with arbitrary GPU devices:
`ucx_perftest -a cuda:3,cuda:2`
Easy of testing
Currently inproc multi-GPU is not supported: for that we need to change cuda_alloc similar to: https://github.com/openucx/ucx/pull/10810
Tested on Pre Tyche:
```
UCX_PROTO_INFO=y ucx_perftest -c 0 &
UCX_PROTO_INFO=y ucx_perftest localhost -c 1 -t ucp_put_bw -n 1000 -s 1024 -m cuda -a cuda:3,cuda:2
+----------------------------------------------------------------------------------------------------------+                                                                                                                                                                                                                                         
| API: …
```

PERF: Perftest GDAKI kernel option

---

README.md

Suggest setting `UCX_IB_ROCE_REACHABILITY_MODE=all` when having reachability issues.
Known issues

README: add note about reachability check mode

---

buildlib/pr/main.yml

Run GPU tests using the new RHEL9 image with DOCA3.1.
Test DOCA3.1 on GPU nodes.

AZP: Test DOCA3.1 on GPU

---

test/gtest/uct/cuda/test_cuda_ipc_md.cc

Relaxed uct_rkey_unpack_v2 return status requirement, adding `UCS_ERR_UNREACHABLE`.
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=107222&view=logs&j=da813497-1cca-54a8-f0a9-cb3fd519bc00&t=1f53f049-9d56-5ab2-8515-95f5f52811a1&l=38974

GTEST/UCT/CUDA: Relaxed uct_rkey_unpack_v2 return status check.

---

src/ucm/cuda/cudamem.c
src/ucm/cuda/cudamem.h

Added hook for `cuLibraryGetGlobal`.
`cudaGetSymbolAddress` leads to `cuLibraryGetGlobal` in CUDA RT 13. It was `cuModuleGetGlobal` before.
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=107122&view=logs&j=6f19b6b7-d713-51f9-34ca-64a8f00f7407&t=6d7bb64e-bfad-52af-9e32-fec3c0a4ba72&l=1669

UCM/CUDA: Added hook for cuLibraryGetGlobal.

---

src/uct/cuda/gdaki/gdaki.cuh

uct_gdaki_wqe_prepare_put_or_atomic assumes
wqe_idx is at most UINT16_T_MAX but atomic & single
APIs passed sq_rsvd_index, an ever-incrementing
uint64_t counter.
Other submit APIs avoid this issue by using inc_mask() per lane,
which properly masks the WQE index down to uint16_t.

UCT/GDAKI: Fix wqe_idx overflow

---

buildlib/az-helpers.sh
buildlib/pr/main.yml
buildlib/tools/common.sh
config/m4/cuda.m4
contrib/test_jenkins.sh
src/tools/perf/cuda/cuda_kernel.cuh
src/tools/perf/cuda/ucp_cuda_kernel.cu
src/tools/perf/lib/libperf_int.h
src/tools/perf/perftest_params.c
src/ucp/wireup/select.c
src/ucs/sys/topo/base/topo.c
src/ucs/sys/topo/base/topo.h
src/uct/ib/mlx5/gdaki/configure.m4
src/uct/ib/mlx5/gdaki/gdaki.c
src/uct/ib/mlx5/ib_mlx5.c
src/uct/ib/mlx5/ib_mlx5.h
test/gtest/ucp/test_ucp_device.cc
test/gtest/ucs/test_topo.cc
test/gtest/uct/cuda/test_switch_cuda_device.cc
test/gtest/uct/test_device.cc

CI:
- Cherry picked changes from #10861 / #10865
- Build UCX with local cuda in CI and fix NVCC search
- Detect nvidia_peermem module for GPU-direct - since it's needed for new drivers
Build:
- Fail if building with gpunetio but it cannot be found
- Add rpath-link of cuda compat libs to GPUNETIO_LDFLAGS
- Fix NVCC search path when using local cuda installation
Code/test:
- Don't print DOCA version since it messes up some test scripts that expect specific output
- Check if UAR is supported for better handing of systems without peer mapping override configuration
- Fix hang in cuda kernel perftest - related to results reporting mechanism. PSN copy logic is not needed for Cuda kernel tests since the kernel can read GPU memory directly, and no need to read PSN on the host side.
- Fix topo …

Run GDA in CI

---

src/uct/ib/mlx5/gdaki/gdaki.c

Add peer failure error handling cap to gdaki.

UCT/GDAKI: Add peer failure error handling cap.

---

src/uct/ib/mlx5/gdaki/gdaki.c

Reduce DOCA log level from WARNING to ERROR in GDAKI transport to prevent log spam.
DOCA warnings were excessively spamming logs in NIXL, making it difficult to read the output.
Changed `doca_log_level_set_global_sdk_limit()` parameter from `DOCA_LOG_LEVEL_WARNING` to `DOCA_LOG_LEVEL_ERROR` in the DOCA initialization function.

UCT/GDA/MLX5: Reduce DOCA log spam by setting ERROR level

---

AUTHORS
buildlib/az-distro-release.yml
buildlib/az-helpers.sh
buildlib/azure-pipelines-release-drp.yml
buildlib/azure-pipelines-release.yml
buildlib/dockers/docker-compose-aarch64.yml
buildlib/dockers/docker-compose-x86_64.yml
buildlib/pr/cuda/cuda.yml
buildlib/pr/main.yml
buildlib/tools/common.sh
buildlib/tools/perf-common.yml
test/gtest/uct/cuda/test_switch_cuda_device.cc

Add CUDA 13 support across build/CI/tests.
Skip CUDA gtests when CUDA memory type is unsupported (patch by @iyastreb).
Issue https://github.com/openucx/ucx/issues/10787
- Bump to CUDA 13 in CI configs. 
- Build new release images.
- Verified in PR, Performance, and Release pipelines (no actual release pushed).

AZP/RELEASE: Add CUDA 13 support

---

src/ucp/api/ucp.h
src/ucp/core/ucp_context.c
src/ucp/core/ucp_context.h
src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.h
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_multi.c
src/ucp/proto/proto_single.c
test/gtest/ucp/test_ucp_proto_mock.cc

Added option to use single network device for all protocols.
Added option to pass unique id to the context.
The combination of these two options allows to balance the traffic going from a single node with several network devices with the same estimated bandwidth.

UCP/PROTO: Added option to use single network device.

---

src/ucp/api/device/ucp_host.h

Add local and remote address fields (`l_addr`, `r_addr`) to `ucp_device_mem_list_elem_t` structure with corresponding field mask flags.
Provide the interface definition needed for NIXL development. This establishes the API contract without implementation, allowing NIXL to progress while UCX implementation can be added separately.
Extended the memory list element structure with two new optional fields controlled by field mask flags (`UCP_DEVICE_MEM_LIST_ELEM_FIELD_L_ADDR`, `UCP_DEVICE_MEM_LIST_ELEM_FIELD_R_ADDR`) to maintain backward compatibility. No functional implementation included - this is interface-only.

UCP/DEVICE: Add local and remote address fields to memory list element

---

src/ucp/proto/proto.c
src/uct/base/uct_iface.h
src/uct/ib/base/ib_iface.c
src/uct/ib/base/ib_iface.h
src/uct/ib/configure.m4
src/uct/ib/mlx5/dc/dc_mlx5.c

- Add recognition of XDR speed
- Initialize put_zcopy protocol before send_ppln/put_mtype, so that put_zcopy would be selected if they both have the same bandwidth

UCT: Add XDR perf recognition

---

src/uct/cuda/cuda_ipc/cuda_ipc.cuh
src/uct/cuda/cuda_ipc/cuda_ipc_ep.c
test/gtest/uct/cuda/test_cuda_ipc_device.cc

Change cuda_ipc put_partial implementation:
* counter_index is a direct index in mem_list
* mem_list_count is exact number of puts (atomic is not included)

UCT/CUDA_IPC/TEST: change indices handling in put partial

---

src/ucp/rma/flush.c

When checking for Direct NIC flush, only use `flush_state` when valid.

UCP/FLUSH: Check flush_state validity before using it

---

src/ucp/core/ucp_mm.c
src/ucp/core/ucp_mm.h
src/ucp/core/ucp_rkey.c
src/ucp/core/ucp_rkey.h
src/ucp/core/ucp_rkey.inl
src/ucp/proto/proto_multi.c
src/ucp/rma/flush.c
src/ucp/rndv/proto_rndv.c
test/gtest/ucp/test_ucp_proto.cc

Re-use #10804 to:
- Make sure to set sys_dev's flush-needed bit when packing rkey.
- Make sure to only send-flush when sys_dev needs it and the transport uses a network device (avoids cuda_ipc/cuda_copy).
With `ucx_perftest` and `nixlbench`, confirmed pattern.

UCP/RKEY: Pack sender flush flag where applicable.

---

src/ucp/proto/proto_common.c
src/ucp/proto/proto_common.inl
src/ucp/proto/proto_init.c
src/uct/ib/base/ib_iface.c

Fix performance estimation for many ppns. 
[RM4655218 (internal link)](https://redmine.mellanox.com/issues/4655218)

UCP: Fix multi ppn perf estimation
